redpanda-data/redpanda

tests/rptest/clients/kubectl.py, tests/rptest/scale_tests/cloud_storage_compaction_test.py, tests/rptest/services/redpanda.py, tests/rptest/tests/availability_test.py, tests/rptest/tests/cluster_view_test.py, tests/rptest/tests/controller_upgrade_test.py, tests/rptest/tests/e2e_shadow_indexing_test.py, tests/rptest/tests/end_to_end.py, tests/rptest/tests/mirror_maker_test.py, tests/rptest/tests/nodes_decommissioning_test.py, tests/rptest/tests/partition_balancer_test.py, tests/rptest/tests/read_replica_e2e_test.py, tests/rptest/tests/redpanda_binary_test.py, tests/rptest/tests/redpanda_test.py, tests/rptest/tests/scaling_up_test.py, tests/rptest/tests/services_self_test.py, tests/rptest/tests/shadow_indexing_compacted_topic_test.py, tests/rptest/tests/timely_shutdown_test.py, tests/rptest/tests/timequery_test.py, tests/rptest/tests/transactions_test.py
Fixes https://github.com/redpanda-data/cloudv2/issues/5893, Fixes #10346, Fixes https://github.com/redpanda-data/devprod/issues/670
This PR adds a new `ducktape` class `RedpandaServiceCloud` which enables tests to run against redpanda cloud. The new class uses inner class `RedpandaServiceCloud.CloudCluster` to connect with the redpanda cloud swagger API to provision and delete clusters. There are some hard-coded values passed to the swagger API that will need to be cleaned up in a future PR because the swagger API is v0.1.0.
Client ID and secrets from redpanda cloud UI are needed to connect to the api. Set these settings in `ducktape --globals` for the new classes to work:
```json
{
"cloud_oauth_url": "https://auth.example.com/oauth/token",
"cloud_oauth_client_id": "your-client-id", …
```
=> tests: ducktape redpanda service for cloud

tests/rptest/scale_tests/many_partitions_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11022
Fixes https://github.com/redpanda-data/redpanda/issues/11068,
=> [v23.1.x] Treat RpkException as retryable in `_node_leadership_evacuated`

tests/rptest/scale_tests/many_partitions_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11022
Fixes https://github.com/redpanda-data/redpanda/issues/11067,
=> [v22.3.x] Treat RpkException as retryable in `_node_leadership_evacuated`

src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment.h, src/v/utils/stream_utils.h, src/v/utils/tests/input_stream_fanout_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/10828 and https://github.com/redpanda-data/redpanda/pull/9786.
The fix in https://github.com/redpanda-data/redpanda/pull/10828 unveiled a deadlock in input_fanout_stream which was fixed in https://github.com/redpanda-data/redpanda/pull/9786.
=> [v22.2.x] cloud_storage: tolerate exceptions in the hydration loop

src/v/raft/service.h
Using `seastar::chunked_fifo` to group shard heartbeats to avoid large memory
allocations.
Fixes: #10747
- none
=> Use `chunked_fifo` to group shard heartbeats

src/v/archival/scrubber.cc, src/v/cluster/topic_table.cc, src/v/cluster/topics_frontend.cc
It's not entirely clear what's causing duplicate purge messages for a lifecycle marker in https://github.com/redpanda-data/redpanda/issues/11090 because it's a run without debug logs, but there are some changes we can make defensively:
- If topics_frontend sees a redundant purge RPC, ignore it
- Clearer INFO-level logging around topic deletion and lifecycle marker purge
* none
=> cluster: harden lifecycle marker purge path

src/go/rpk/pkg/cli/debug/bundle/bundle_k8s_linux.go
Since redpanda uses the same SASL information
stored in the rpk's kafka API knob, we need to
pass through this info to the client generated
to gather the admin API information.
* rpk debug bundle now can be used in clusters with SASL enabled to gather Admin API information.
=> rpk debug bundle: pass SASL info to admin client

src/v/cluster/config_manager.cc, src/v/cluster/config_manager.h, src/v/cluster/controller.cc, src/v/cluster/members_table.cc, src/v/cluster/members_table.h, src/v/cluster/node_status_backend.cc, src/v/cluster/node_status_backend.h, src/v/cluster/partition_balancer_backend.cc, src/v/cluster/partition_balancer_backend.h, src/v/cluster/partition_balancer_state.h, src/v/cluster/topic_table.cc, src/v/cluster/topic_table.h, src/v/config/configuration.cc, src/v/config/configuration.h, tests/rptest/services/redpanda.py, tests/rptest/tests/nodes_decommissioning_test.py, tests/rptest/tests/partition_balancer_test.py
This patch triggers the balancer when nodes are added/decommissioned (member table updates) or absed on a drop in # of in progress updates (topic table updates). This makes it event driven instead of a pure timer based trigger.
* none
=> partition_balancer: event driven partition balancer runs

tests/rptest/scale_tests/many_partitions_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11022
Fixes https://github.com/redpanda-data/redpanda/issues/11069,
=> [v22.2.x] Treat RpkException as retryable in `_node_leadership_evacuated`

tests/rptest/tests/controller_log_limiting_test.py
Skipping test that requires allocating 10 nodes not to run in debug mode.
- none
=> Skip controller log limiting mm2 test in debug mode

tests/rptest/services/redpanda.py
Previously we would only flag these in _passing_ tests, where the general log error search tripped on them.  If a test failed (e.g. with a timeout due to a crashed node being inaccessible), then we would report the failure as a timeout rather than a NodeCrash
* none
=> tests: flag AddressSanitizer crashes as NodeCrash

src/v/cluster/controller.cc, src/v/cluster/partition_balancer_backend.cc, src/v/cluster/partition_balancer_backend.h, src/v/cluster/partition_balancer_planner.cc, src/v/cluster/partition_balancer_planner.h, src/v/config/configuration.cc, src/v/config/configuration.h
Internal topics should only be moved if there are no other topics to be
moved. Using a minimum priority + 1 for all internal Redpanda topics
makes sure that those topics will be moved as a last one before the one
that falls below the threshold.
* none
=> Handling internal topics in partition balancer planner

tests/rptest/services/redpanda.py
I noticed the controller log check complain in my local test runs. Turns out there's a typo.
```
redpanda - validate_controller_log - lineno:3693]: Failed to read controller status from docker-rp-3: 'int' object is not subscriptable
redpanda - validate_controller_log - lineno:3693]: Failed to read controller status from docker-rp-4: 'int' object is not subscriptable
redpanda - validate_controller_log - lineno:3693]: Failed to read controller status from docker-rp-5: 'int' object is not subscriptable
redpanda - validate_controller_log - lineno:3700]: Failed to read controller status from any node, cannot validate record count
```
* none
=> tests: fix typo in oversized controller log check

src/v/cluster/partition.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/10856
=> [v22.3.x] cluster: include ntp in timequery logs

tests/rptest/tests/retention_policy_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/10718
Fixes https://github.com/redpanda-data/redpanda/issues/10769,
=> [v22.3.x] tests: fix timeout in test_cloud_size_based_retention

tests/rptest/services/kcat_consumer.py, tests/rptest/tests/throughput_limits_snc_test.py
This is a follow-up to #10285. A kcat based standalone consumer is introduced, and it is used to verify a case where there a throttled rdkafka consumer in the cluster reading from all brokers, and still other consumers are able to connect and join a consumer group.
A standalone kcat consumer allows to run consumers in dedicated nodes, which is a desired layout for the tests that involve high thoughput cases. It is easier to manage that to spawn an instance of ducktape in a separate node and still communitcate to it via ssh.
Re #10141
* none
=> DT for limiting the kafka API api_keys scope

tests/rptest/tests/scaling_up_test.py
In the criteria to determine that the partitions are now balanced, check whether max(replicas per node) is greater than min(replicas per node) by no more than 1, in this case the partitions are considered balanced without checking the 20% tolerance range.
This enables distributions like [1,1,2] to be always successful regardless of the tolerance range.
Fixes #11042.
* none
=> Check for perfect replicas distribution in `ScalingUpTest.test_adding_nodes_to_cluster`

src/go/rpk/pkg/cli/cmd/debug/bundle/bundle_k8s_linux.go
(Manual cherry-pick of 11a8290f812dcfa508b556e8a748cecc80dd26ad)
Since redpanda uses the same SASL information
stored in the kafka API knob, we need to
pass through this info to the client generated
to gather the admin API information.
Fixes #11111
* rpk debug bundle now can be used in clusters with SASL enabled to gather Admin API information.
=> [v23.1.x] rpk debug bundle: pass SASL info to admin client

src/v/cloud_storage/remote_segment.cc, src/v/cluster/tests/serialization_rt_test.cc, src/v/compat/model_compat.h, src/v/compat/model_generator.h, src/v/compat/raft_compat.h, src/v/compat/raft_generator.h, src/v/compat/raft_json.h, src/v/compat/run.cc, src/v/features/feature_table.cc, src/v/features/feature_table.h, src/v/model/record.h, src/v/raft/append_entries_buffer.cc, src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/consensus_client_protocol.h, src/v/raft/raftgen.json, src/v/raft/recovery_stm.cc, src/v/raft/recovery_stm.h, src/v/raft/replicate_batcher.cc, src/v/raft/replicate_entries_stm.cc, src/v/raft/replicate_entries_stm.h, src/v/raft/rpc_client_protocol.cc, src/v/raft/rpc_client_protocol.h, src/v/raft/service.h, src/v/raft/tests/type_serialization_tests.cc, src/v/raft/types.cc, src/v/raft/types.h, src/v/storage/tests/compaction_index_format_tests.cc, src/v/test_utils/randoms.h
Introduced new append entries request type and endpoint. The new type
leverages `serde` based serialization of `model::record_batch` in
request `record_batch_reader`. The new serialization does not
materialize batch records but uses an opaque `iobuf` to serialize batch
payload.
Fixes: #10743
-  fixed large allocations when replicating batches with large number of records
=> Use opaque records in Raft append entries message

.github/workflows/buildkite-slash-commands.yml, .github/workflows/slash-commands.yml
Triggering nightly releases from PRs through slash command.
https://github.com/redpanda-data/vtools/pull/1760
redpanda-data/vtools#1753
* none
=> add slash command for triggering release+publish workflow

src/v/pandaproxy/schema_registry/avro.cc, src/v/pandaproxy/schema_registry/seq_writer.cc, src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h, src/v/pandaproxy/schema_registry/storage.h, src/v/pandaproxy/schema_registry/test/consume_to_store.cc, src/v/pandaproxy/schema_registry/test/sanitize_avro.cc, src/v/pandaproxy/schema_registry/test/sharded_store.cc, src/v/pandaproxy/schema_registry/test/storage.cc, src/v/pandaproxy/schema_registry/types.h, tests/rptest/remote_scripts/schema_registry_test_helper.py, tests/rptest/tests/schema_registry_test.py
Additional sanitization:
* Sort members of all complex types
* Sort members of record fields
Fix #7609
NOTE: This is not [Parsing Canonical Form](https://avro.apache.org/docs/1.11.1/specification/#parsing-canonical-form-for-schemas), but it is equivalent.
* Schema Registry: Canonicalize AVRO schema so that syntactic differences don't fail lookups by schema contents.
=> schema_registry/avro: Canonicalize AVRO schema

src/v/pandaproxy/schema_registry/avro.cc, src/v/pandaproxy/schema_registry/seq_writer.cc, src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h, src/v/pandaproxy/schema_registry/storage.h, src/v/pandaproxy/schema_registry/test/consume_to_store.cc, src/v/pandaproxy/schema_registry/test/sanitize_avro.cc, src/v/pandaproxy/schema_registry/test/sharded_store.cc, src/v/pandaproxy/schema_registry/test/storage.cc, src/v/pandaproxy/schema_registry/types.h, tests/rptest/remote_scripts/schema_registry_test_helper.py, tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/10786
Fixes https://github.com/redpanda-data/redpanda/issues/11142,
=> [v23.1.x] schema_registry/avro: Canonicalize AVRO schema

src/go/rpk/pkg/cli/debug/bundle/bundle_linux.go, src/go/rpk/pkg/config/config.go, src/go/rpk/pkg/config/params.go, src/go/rpk/pkg/config/params_test.go, src/go/rpk/pkg/config/redpanda_yaml.go, src/go/rpk/pkg/config/weak.go, src/go/rpk/pkg/config/weak_test.go
The old deprecated TLS / SASL sections were only decoded in params.Load; moving this into the weak.go UnmarshalYAML allows this same backcompat fix to work in --from-simple.
* none
=> rpk: fix `profile create --from-simple`

tests/rptest/tests/cluster_config_test.py
The test is checking config status, but it is not waiting for the status object to have content for all the expected nodes.
Fixes #10977
Not seen on v23.1.x in the last 14d / 55 runs.
* none
=> ducktape/test_simple_live_change: wait for all nodes

src/v/cloud_storage_clients/tests/CMakeLists.txt, src/v/cloud_storage_clients/tests/exception_test.cc, src/v/cloud_storage_clients/util.cc, src/v/cloud_storage_clients/util.h
If a nested exception is seen during an HTTP call where either the inner or outer exception is abort or gate closed, then the exception is logged on debug level, to be consistent with how these exception types (abort/gate closed) are handled in isolation.
If both the components of the nested exception are of any other kind, an error is logged.
Fixes https://github.com/redpanda-data/redpanda/issues/10706
* none
=> cloud_storage: Handle nested benign exception

src/v/storage/compacted_index_chunk_reader.cc
Adjust the memory calculation based on the memory usage,
which is the in-memory size of a `compaction::entry`, currently
56 bytes. Do not exceed the max_chunk_memory by calculating how
big the container will be on the next insert.
Fixes https://github.com/redpanda-data/redpanda/issues/10311
* none
=> storage/compacted_index_chunk_reader: fix memory calculation

tests/rptest/remote_scripts/compute_storage.py, tests/rptest/services/redpanda.py, tests/rptest/tests/e2e_topic_recovery_test.py, tests/rptest/util.py
From my investigation it seems like the tests in `test_restore_with_aborted_tx` fail because of a race with truncation. The truncation check is slow enough that we only ever issue a single check in `wait_for_local_storage_truncate` so if that ever doesn't pass the first time, then we will fail the test. Rewriting all the back and forth calls of redpanda.storage() to a single remote python script that reports the data as json makes the runtime of that function go from 45seconds -> ~0.1seconds this allows the checks to execute multiple times in the `wait_for_local_storage_truncate`.
Fixes: #10928 
* none
=> Ducktape: compute ClusterStorage faster

src/v/bytes/oncore.cc, src/v/bytes/oncore.h, src/v/net/conn_quota.cc, src/v/net/conn_quota.h, src/v/utils/source_location.h, src/v/vlog.h
This makes the API contract more explicit since we now require the
connection quota units doesn't change shards.
Related: #10544
* none
=> Require conn_quota::units stay on a single shard

src/v/cluster/members_backend.cc, src/v/cluster/scheduling/allocation_node.cc, src/v/cluster/scheduling/allocation_node.h, src/v/cluster/scheduling/allocation_state.cc, src/v/cluster/scheduling/allocation_state.h, src/v/cluster/scheduling/constraints.cc, src/v/cluster/scheduling/constraints.h, src/v/cluster/scheduling/partition_allocator.cc, src/v/cluster/scheduling/partition_allocator.h, src/v/cluster/scheduling/types.cc, src/v/cluster/tests/backend_reallocation_strategy_test.cc, src/v/cluster/tests/partition_allocator_tests.cc, src/v/cluster/tests/topic_updates_dispatcher_test.cc, src/v/cluster/topic_updates_dispatcher.cc, src/v/cluster/topic_updates_dispatcher.h
When moving partitions, partition allocations on old nodes are not removed until the move is finished. This makes sense because partitions remain physically present on old nodes until the very end. But we also use these allocation counts for count-based rebalancing. This is incorrect because after all moves are finished, the distribution won't necessary be uniform.
To fix this, introduce "final counts" - the number of partitions on a node after all currently in-progress moves are finished, maintain it when (re)allocating partitions and in `topic_updates_dispatcher` and use it in placement constraints and partition counts rebalancing in `members_backend`.
* none
=> c/partition_allocator: maintain and use final partition counts

src/v/cloud_storage/remote.cc, src/v/cloud_storage/segment_chunk_data_source.cc, src/v/cloud_storage/segment_chunk_data_source.h
When chunk hydration fails due to abort request, this change makes sure that exception handling paths are mutually exclusive. There was a bug in the previous code where the abort requested error was handled and then control was handed off to the generic exception handler, resulting in an unexpected error message.
Fixes: https://github.com/redpanda-data/redpanda/issues/10868
Fixes: https://github.com/redpanda-data/redpanda/issues/11088
* none
=> cloud_storage: Handle expected hydrate errors

src/v/storage/compacted_index_chunk_reader.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11138
Fixes https://github.com/redpanda-data/redpanda/issues/11162,
=> [v23.1.x] storage/compacted_index_chunk_reader: fix memory calculation

src/v/cloud_storage/tests/CMakeLists.txt, src/v/cloud_storage/tests/remote_test.cc, src/v/cloud_storage/tests/s3_imposter.cc
A couple things I found while writing tests for cluster metadata uploads:
- it's useful to have s3_imposter outside of the cloud_storage library
- it shouldn't return contents when a delimiter is passed
* none
=> miscellaneous improvements to s3_imposter

tests/rptest/tests/cloud_storage_chunk_read_path_test.py
The test changed in commit asserts that the read path works when the segment size is smaller than chunk size. The expectations in test are often unmet on debug build in CI, we expect to be able to read 2500 messages total but the test falls marginally short. Since this test is not a load test but simply a check that read path works in this corner case, this change lowers the message count for the test to pass.
Fixes: https://github.com/redpanda-data/redpanda/issues/11151
* none
=> ducktape: Reduce parallel reads in test

src/v/cloud_storage/tests/util.h
Enable chunked storage by using latest sname format when making segments in remote partition tests.
* none
=> cloud_storage: Use chunked storage in tests

tests/docker/Dockerfile, tests/docker/ducktape-deps/teleport
part of fix for https://github.com/redpanda-data/vtools/issues/1748
* none
=> ducktape: add teleport as test dependency

src/v/rpc/transport.cc, src/v/rpc/transport.h
Currently the way the code is structured can result in temporary
dispatch stalls timing out a bunch of requests.
Consider a request queue of sequence numbers [5, 6, 7, 8]
Lets assume seq=6 dispatch got delayed. This can happen if timeout is
low or there is an unknown delay by the scheduler (eg: debug builds).
_last_seq=4, queue = [5, 7, 8] - 5 is dispatched right away
_last_seq=5, queue = [7,8] -- out of order.
Dispatch of 7, 8 doesn't happen right away due to out of order sequence
and we never do a dispatch with seq=6 because we detect it already
timed out.
Now it takes a new RPC request to clear the stalled queue but
that may not happen for a while  (eg: until the queued RPCs are timed out) and
meanwhile seq=7/8 timeout for no fault of theirs.
This patch does two main things.
* …
=> rpc/transport: fix temporary dispatch loop stalls

src/v/cloud_storage/remote.cc, src/v/cloud_storage_clients/configuration.h, src/v/config/CMakeLists.txt, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/config/tests/CMakeLists.txt, src/v/config/tests/throughput_control_group_test.cc, src/v/config/throughput_control_group.cc, src/v/config/throughput_control_group.h, src/v/kafka/server/connection_context.cc, src/v/kafka/server/connection_context.h, src/v/kafka/server/fwd.h, src/v/kafka/server/snc_quota_manager.cc, src/v/kafka/server/snc_quota_manager.h, src/v/utils/functional.h, tests/rptest/tests/cluster_config_test.py, tests/rptest/tests/throughput_limits_snc_test.py
This PR introduces a feature to make client_ids specified by a value, regex, or by a special selector for missing client_ids exempt from throughput control. Connections presenting a matching client_id value will not have the size of their requests accounted for throughput control, not they will be throttled.
The new configuration is forward looking to support the fully functional throughput control groups, this is why it may look too bulky for this specific PR.
Fixes #10575
* A client_id, or a group of client_ids specified with a regex, can now be excluded from node wide throughput control. The new cluster property `kafka_throughput_control` can be used to define throughput control groups for which Kafka traffic will not be limited by the values specified by …
=> Node-wide throughput exemptions for clients

src/v/bytes/iobuf.h
=> [nit] Fix a comment spelling typo.

src/v/cluster/self_test/diskcheck.cc
`diskcheck_opts::request_size` is provided by the user.
To avoid very large allocations, split the request size into at most 128KiB chunks, and read/write them via an iovec.
Local testing with a single core:
```
Prior to the change                           With the change
NAME        512KB sequential r/w throughput disk test     512KB sequential r/w throughput disk test
INFO        write run                                     write run
TYPE        disk                                          disk
TEST ID     ff291688-11f8-4d94-a5bc-62329c105f55          90b89748-f61e-4ab9-bd3b-425ad7672e42
TIMEOUTS    0                                             0
DURATION    30006ms                                       30004ms
IOPS        386 req/sec                                   382 req/sec …
```
=> c/self-test/diskcheck: Avoid large allocations

src/v/cloud_storage/segment_meta_cstore.cc
`it` should point to the first hint that needs to be removed. Previously it was computed with upper_bound, but this means that it will never point to a value that's equal to frame_max_offset, meaning that that hint value could be left behind, pointing incorrectly at an offset that's no longer valid.
to find the issue, this test was extracted from cloud_storage_basic_rptest suite
https://github.com/andijcr/redpanda/blob/issue/10602/exceptional_future_ignored/src/v/cloud_storage/tests/partition_manifest_outofrange.cc
function ```test_partition_manifest``` repeatedly exercises partition_manifest::truncate, and the high randomized repetition count ensures that the exception is triggered. 
this assertion https://github.com/andijcr/redpanda/blob/issue/10602/exceptional_future_ignored/src/v/cloud …
=> [cloud_storage] segment_meta_cstore::prefix_truncate fix range of _hints to remove

src/v/cluster/controller.cc, src/v/cluster/controller.h, src/v/cluster/partition_balancer_backend.cc, src/v/cluster/partition_balancer_backend.h, src/v/cluster/partition_balancer_planner.cc, src/v/cluster/partition_balancer_planner.h, src/v/cluster/partition_balancer_state.cc, src/v/cluster/partition_balancer_state.h, src/v/cluster/tests/partition_balancer_bench.cc, src/v/cluster/tests/partition_balancer_planner_fixture.h, src/v/cluster/tests/partition_balancer_planner_test.cc, src/v/cluster/tests/topic_table_fixture.h, src/v/redpanda/application.cc
Using `node_status_table` last heartbeat timestamps to determine if a
node is unavailable. Previously `partition_balancer_planner` was using
follower state coming from the controller raft group.
Fixes: #7218 
- none
=> Using `node_status_table` to determine node unavailability in partition balancer

src/v/cluster/node_status_backend.cc, src/v/cluster/node_status_backend.h, src/v/cluster/node_status_table.h
Partition balancer is going to relay on the `node_status_table` when deciding which cluster members are unresponsive. Previously a `node_status_table` were not updated until the first status response was received from newly joined node, this made it impossible to recognize a failure of a newly joined node. Additionally removed members were never removed from the status table.
- none
=> Improved handling of notification in `cluster::node_status_backend` 

src/v/features/feature_table.h
Ideally a perfect hashing scheme with constexpr support would be used to use minimum memory with guaranteed O(1) lookups, but std::unordered_set is still [better](https://quick-bench.com/q/yo8MP1nByPrdHkPnPekK3tAe2iM) than std::set.
* none
* The check for unsupported features now has amortized `O(1)` complexity vs previous `O(log(N))`.
=> [feature_table] Replace set with unordered_set.

src/v/config/tls_config.h
Makes `tls_config::get_credentials_builder` set gnutls priority strings to chose CPU friendlier ciphers which should help with TLS performance. We were already doing this for the cloud clients (see `build_tls_credentials` in `configuration.cc`) but not in `tls_config::get_credentials_builder` which is used for all API TLS endpoints.
This results in chosen ciphers as follows:
Before:
```
stephan@rp:~$ nmap -Pn --script ssl-enum-ciphers -p 9092 35.86.175.191
Starting Nmap 7.93 ( https://nmap.org ) at 2023-06-02 16:39 BST
Nmap scan report for ec2-35-86-175-191.us-west-2.compute.amazonaws.com
(35.86.175.191)
Host is up (0.13s latency).
PORT     STATE SERVICE
9092/tcp open  XmlIpcRegSvc
| ssl-enum-ciphers:
|   TLSv1.0:
|     ciphers:
|       TLS_DHE_RSA_WITH_AES_128_CBC_SHA (dh 2048) - A
| …
```
=> tls: Prefer faster ciphers and use server preference

src/v/archival/scrubber.cc, src/v/archival/scrubber.h, src/v/cloud_storage/lifecycle_marker.h, src/v/cloud_storage/remote.cc, src/v/cloud_storage/remote.h, src/v/redpanda/admin/api-doc/shadow_indexing.json, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h, tests/docker/ducktape-deps/client-swarm, tests/rptest/archival/abs_client.py, tests/rptest/clients/rp_storage_tool.py, tests/rptest/services/admin.py, tests/rptest/services/redpanda.py, tests/rptest/tests/topic_delete_test.py, tests/rptest/utils/si_utils.py
This is worth landing in 23.2 ahead of more general scrubbing functionality, because it disambiguates situations where we see partial content for a topic, and can't tell if the system is damaged, or if it just did an incomplete deletion.
* none
=> cloud_storage: write remote lifecycle markers after purge

src/v/config/tls_config.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/11167
=> [v23.1.x] tls: Prefer faster ciphers and use server preference

tests/rptest/tests/cloud_retention_test.py
Backport of PR #10797
Fixes https://github.com/redpanda-data/redpanda/issues/10804
* none
=> [v23.1.x] Backport 10797 v23.1.x

tests/rptest/tests/retention_policy_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/10718
Fixes https://github.com/redpanda-data/redpanda/issues/10767,
=> [v23.1.x] tests: fix timeout in test_cloud_size_based_retention

src/v/cloud_storage_clients/abs_client.cc
Fix argument count for logging of unexpected errors by abs client.
* none
=> cloud_storage_clients/abs: fix arg count for log

src/v/pandaproxy/schema_registry/avro.cc, src/v/pandaproxy/schema_registry/protobuf.cc, src/v/pandaproxy/schema_registry/requests/get_schemas_ids_id.h, src/v/pandaproxy/schema_registry/requests/get_subject_versions_version.h, src/v/pandaproxy/schema_registry/requests/post_subject_versions.h, src/v/pandaproxy/schema_registry/requests/test/get_subject_versions_version.cc, src/v/pandaproxy/schema_registry/requests/test/post_subject_versions.cc, src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h, src/v/pandaproxy/schema_registry/storage.h, src/v/pandaproxy/schema_registry/store.h, src/v/pandaproxy/schema_registry/test/compatibility_protobuf.cc, src/v/pandaproxy/schema_registry/test/compatibility_protobuf.h, src/v/pandaproxy/schema_registry/test/consume_to_store.cc, src/v/pandaproxy/schema_registry/test/delete_subject_endpoints.cc, src/v/pandaproxy/schema_registry/test/post_subjects_subject_version.cc, src/v/pandaproxy/schema_registry/test/sharded_store.cc, src/v/pandaproxy/schema_registry/test/storage.cc, src/v/pandaproxy/schema_registry/test/store.cc, src/v/pandaproxy/schema_registry/types.cc, src/v/pandaproxy/schema_registry/types.h
Return `references` for `GET /schemas/ids/<id>`.
Fixes #11194 
The `store` has two mappings:
1) `schema_map`: Schema ID to Schema
2) `subject_map`: Subject-Versions to Schema ID
Each of these mappings are then balanced across shards, coordinated by `sharded_store`.
Prior to this change, `references` were attached to the Subject-Versions.
This is an incorrect modelling; Schema should own the references to other schema. This commit does that refactoring by moving references from `typed_schema` to `typed_schema_definition`.
This allows returning the references when querying a schema by ID.
Additionally there is a fix to ignore references when a subject-version has been soft-deleted.
* Schema Registry: Return `references` for `GET /schemas/ids/<id>`.
=> Schema Registry: `GET /schemas/ids/<id>` should return references

src/go/rpk/pkg/cli/cloud/auth/list.go, src/go/rpk/pkg/cli/profile/list.go, tests/rptest/clients/rpk.py, tests/rptest/clients/rpk_remote.py, tests/rptest/services/redpanda.py, tests/rptest/tests/rpk_cloud_test.py, tests/rptest/tests/rpk_config_test.py, tests/rptest/tests/rpk_profile_test.py, tests/rptest/utils/rpk_config.py
This PR introduces:
- Ducktape tests for `rpk profile`.
- Ducktape tests for `rpk cloud login` using client credentials.
- Small refactor of rpk config ducktape test.
* none
=> tests: ducktape test of rpk -X and rpk profile

src/go/k8s/Dockerfile
This reverts commit 06e14eee004be7d9b4f3ce764cafc21d1f2bdd07.
Removing the platform flag is causing builds to time out. This reverts that while we investigate further.
* none
=> k8s: revert remove --platform flag from operator images' dockerfile

tests/rptest/scale_tests/partition_balancer_scale_test.py
Fixed setup of `PartitionBalancerScaleTest::test_partition_balancer_with_many_partitions`. Previously the number of created partitions did not taken into account the node which is stopped during the test. 
Fixes: #9337
- none
=> Fixed `test_partition_balancer_with_many_partitions` setup

.gitignore
After https://github.com/redpanda-data/vtools/pull/1855 we support custom tasks, we need to gitignore that file too.
* none
=> gitignore usertasks.yml

src/v/CMakeLists.txt, src/v/cloud_storage_clients/client_probe.cc, src/v/cluster/node_status_table.h, src/v/config/property.h, src/v/kafka/client/test/consumer_group.cc, src/v/kafka/client/test/fetch.cc, src/v/kafka/client/test/produce.cc, src/v/kafka/client/test/retry.cc, src/v/kafka/server/tests/produce_consume_utils.h, src/v/model/adl_serde.cc, src/v/model/tests/model_serialization_test.cc, src/v/net/connection.cc, src/v/pandaproxy/rest/test/consumer_group.cc, src/v/pandaproxy/rest/test/list_topics.cc, src/v/pandaproxy/schema_registry/store.h, src/v/raft/tests/raft_group_fixture.h, src/v/raft/vote_stm.h, src/v/rpc/netbuf.cc, src/v/rpc/test/serialization_test.cc, src/v/rpc/transport.cc, src/v/rpc/transport.h, src/v/security/acl.h, src/v/storage/file_sanitizer.h, src/v/storage/fs_utils.h, src/v/storage/spill_key_index.cc, src/v/storage/tests/storage_test_fixture.h
The idea here is to (1) replace the separate part of the pipeline that handles this in CI and (2)  provide a simple way for devs to invoke and modify this.
The tree is currently clang-tidy clean w.r.t. to the checks added in this PR.
* none
=> build: add an option to run clang-tidy along side compilation

.github/workflows/rp-storage-tool-checks.yml
Followup to https://github.com/redpanda-data/redpanda/pull/11223
* none
=> tools: add a github action for rp-storage-tool tests

tests/rptest/tests/e2e_shadow_indexing_test.py
The E2E test for SI checks that indices are uploaded during a normal write operation. 
This change uses `wait_until` with a timeout for the assertion that indices are uploaded, replacing a single check used earlier.
Fixes: https://github.com/redpanda-data/redpanda/issues/11166
* none
=> ducktape: Wait for the metric tracking index uploads to update

tests/rptest/services/verifiable_consumer.py, tests/rptest/tests/end_to_end.py, tests/rptest/tests/simple_e2e_test.py
Improved error handling when `VerifiableConsumer` is stopped because of a violation. The change in this PR skips waiting for all the messages to be consumed and exit early if consumer was already stopped. 
- none
=> Improve verifiable consumer error

src/v/pandaproxy/schema_registry/avro.cc, src/v/pandaproxy/schema_registry/protobuf.cc, src/v/pandaproxy/schema_registry/requests/get_schemas_ids_id.h, src/v/pandaproxy/schema_registry/requests/get_subject_versions_version.h, src/v/pandaproxy/schema_registry/requests/post_subject_versions.h, src/v/pandaproxy/schema_registry/requests/test/get_subject_versions_version.cc, src/v/pandaproxy/schema_registry/requests/test/post_subject_versions.cc, src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h, src/v/pandaproxy/schema_registry/storage.h, src/v/pandaproxy/schema_registry/store.h, src/v/pandaproxy/schema_registry/test/compatibility_protobuf.cc, src/v/pandaproxy/schema_registry/test/compatibility_protobuf.h, src/v/pandaproxy/schema_registry/test/consume_to_store.cc, src/v/pandaproxy/schema_registry/test/delete_subject_endpoints.cc, src/v/pandaproxy/schema_registry/test/post_subjects_subject_version.cc, src/v/pandaproxy/schema_registry/test/sharded_store.cc, src/v/pandaproxy/schema_registry/test/storage.cc, src/v/pandaproxy/schema_registry/test/store.cc, src/v/pandaproxy/schema_registry/types.cc, src/v/pandaproxy/schema_registry/types.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/11216
Fixes https://github.com/redpanda-data/redpanda/issues/11237,
=> [v23.1.x] Schema Registry: GET /schemas/ids/<id> should return references

src/v/pandaproxy/schema_registry/avro.cc, src/v/pandaproxy/schema_registry/protobuf.cc, src/v/pandaproxy/schema_registry/requests/get_schemas_ids_id.h, src/v/pandaproxy/schema_registry/requests/get_subject_versions_version.h, src/v/pandaproxy/schema_registry/requests/post_subject_versions.h, src/v/pandaproxy/schema_registry/requests/test/get_subject_versions_version.cc, src/v/pandaproxy/schema_registry/requests/test/post_subject_versions.cc, src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h, src/v/pandaproxy/schema_registry/storage.h, src/v/pandaproxy/schema_registry/store.h, src/v/pandaproxy/schema_registry/test/compatibility_protobuf.cc, src/v/pandaproxy/schema_registry/test/compatibility_protobuf.h, src/v/pandaproxy/schema_registry/test/consume_to_store.cc, src/v/pandaproxy/schema_registry/test/delete_subject_endpoints.cc, src/v/pandaproxy/schema_registry/test/post_subjects_subject_version.cc, src/v/pandaproxy/schema_registry/test/sharded_store.cc, src/v/pandaproxy/schema_registry/test/storage.cc, src/v/pandaproxy/schema_registry/test/store.cc, src/v/pandaproxy/schema_registry/types.cc, src/v/pandaproxy/schema_registry/types.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/11216
Fixes https://github.com/redpanda-data/redpanda/issues/11238,
=> [v22.3.x] Schema Registry: GET /schemas/ids/<id> should return references

tests/docker/Dockerfile
On arm64 machines, there are no python wheels for confluent-kafka. When attempting to install them with the previous Dockerfile, the librdkafka source was not available. This commit uses the librdkafka intermediate image as the base of the final stage of the ducktape test node image
fixes https://github.com/redpanda-data/vtools/issues/1859
* none
=> ducktape-deps: fix installing confluent-kafka on arm64

src/v/archival/tests/archival_metadata_stm_test.cc, src/v/cluster/archival_metadata_stm.cc, src/v/cluster/archival_metadata_stm.h, src/v/cluster/cluster_utils.cc, src/v/cluster/cluster_utils.h, src/v/cluster/controller_backend.cc, src/v/cluster/id_allocator_stm.cc, src/v/cluster/id_allocator_stm.h, src/v/cluster/persisted_stm.cc, src/v/cluster/persisted_stm.h, src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h, src/v/cluster/tests/cluster_utils_tests.cc, src/v/cluster/tm_stm.cc, src/v/cluster/tm_stm.h, src/v/cluster/types.h, src/v/storage/kvstore.h, src/v/storage/tests/kvstore_fixture.h, src/v/storage/tests/kvstore_test.cc
This change adds the ability to the persisted_stm to write its snapshots to the kvstore instead of using the snapshot_manager. This change is necessitated as the new log_eviction_stm (see https://github.com/redpanda-data/redpanda/pull/10061) will be adding yet another checkpoint file that will be periodically written to. With many partitions there are concerns with performance and stability, moving the backing store of the persisted_stm to the kvstore solves this.
Note this not modify existing behavior of the kvstore. These changes make it so that users will opt-in or out of this behavior. The default is to work as it always did, using the snapshot manager as its backing store.
* Introduces the ability to use kvstore for snapshots for the persisted_stm tool
=> cluster: Allow persisted_stm to use the kvstore for snapshots if selected 

tests/rptest/services/redpanda.py
If redpanda crashes very early on then it gets reported as a generic thing like "failed to start within 30 seconds". When this happens, let's look to see if a crash happened and report that. Otherwise, we'll just continue to raise the generic error.
* none
=> test: check for early aborts on start-up failure

src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/recovery_stm.cc
In cases where one follower falls far behind(like when a node goes down) it is often the case that we are reading large amounts of old batches only once. If these reads are placed in the batch cache then newer, more likely to be consumed, batches will be evicted. This can cause a noticeable increase in batch cache misses during recovery.
This PR avoids this problem by not adding read batches to the cache in cases where only one follower is recovering. In the cases where more than one follower is recovering its no longer a read-once workload and it may be optimal to put read batches in the cache.
* none
=> Avoid caching batches when only one node is recovering

src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_partition.h, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment.h, src/v/cloud_storage/tests/remote_partition_test.cc, src/v/cloud_storage/tests/remote_segment_test.cc, src/v/cloud_storage/tests/util.h, src/v/cloud_storage/types.h, src/v/cluster/partition_manager.cc, src/v/cluster/partition_manager.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/CMakeLists.txt, src/v/redpanda/application.cc, src/v/redpanda/application.h, src/v/resource_mgmt/CMakeLists.txt, src/v/resource_mgmt/storage.cc, src/v/resource_mgmt/storage.h
Adds a cloud cache interface for estimating the target minimum for storage size, as well as a control loop skeleton which will be used to manage disk space to be added in subsequent PR.
* none
=> storage: add cache target estimates and space management control loop skeleton

src/v/cloud_storage/cache_service.h, src/v/cloud_storage/remote_segment.cc
We currently ignore cache status and always read from cloud storage with chunked reads. This fixes that and noops the chunked read in this case as the read from cache will succeed during materialization.
Fixes: https://github.com/redpanda-data/redpanda/issues/10938
* none
=> cloud storage: Check cache status before hydrating remote segments

src/v/archival/tests/archival_metadata_stm_test.cc, src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/partition_manifest.h, src/v/cloud_storage/tests/partition_manifest_test.cc, src/v/cluster/archival_metadata_stm.cc, src/v/cluster/archival_metadata_stm.h, src/v/cluster/partition.cc, src/v/cluster/partition.h, src/v/redpanda/admin/api-doc/debug.json, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h, tests/rptest/services/admin.py, tests/rptest/tests/e2e_shadow_indexing_test.py
Backport of https://github.com/redpanda-data/redpanda/pull/10806
Also brings in [3d08cc3](https://github.com/redpanda-data/redpanda/commit/3d08cc3544d03ee224528cce9840762b0e6e1173)
Fixes https://github.com/redpanda-data/redpanda/issues/10813
Conflicts:
* Pulled in a partial backport of a commit for utility methods
* Upload policy seems like it's different in this version than dev, so updated the test to sleep instead of wait for uploads to complete
Based on https://github.com/redpanda-data/redpanda/pull/10787
The goal of this PR is to add an escape hatch that can reset the in-memory contents of the archival manifest across all replicas, given an input JSON. When manifests are incorrect (e.g. from older buggy versions), we need a way to reset in-memory state without bringing down all …
=> [v23.1.x] cloud_storage: escape hatch to reset metadata partition manifest

src/v/cloud_storage_clients/client_pool.cc
Fixes https://github.com/redpanda-data/redpanda/issues/11285
* none
=> cloud_storage: Destroy client_pool probe in stop()

src/v/cloud_storage/partition_manifest.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/10833
=> [v22.3.x] cloud_storage: improved debug on partition manifest parse error

src/go/k8s/controllers/redpanda/cluster_controller_configuration_test.go, src/go/k8s/pkg/resources/configuration/patch.go, src/go/k8s/tests/e2e/additional-configuration/04-update-version_and_config.yaml
Reverts redpanda-data/redpanda#11013
* none
=> Revert "[v22.3.x] k8s: parse configuration arrays correctly"

src/go/rpk/pkg/cli/acl/acl.go, src/go/rpk/pkg/cli/acl/user.go, src/go/rpk/pkg/cli/acl/user/create.go, src/go/rpk/pkg/cli/acl/user/delete.go, src/go/rpk/pkg/cli/acl/user/list.go, src/go/rpk/pkg/cli/acl/user/update.go, src/go/rpk/pkg/cli/acl/user/user.go, tests/rptest/clients/rpk.py, tests/rptest/tests/rpk_acl_test.py
This PR adds: 
- a new command that allows the user to update the user's credentials:
```
$ rpk acl user update test-update --new-password test 
Updated user "test-update" successfully.
```
- a ducktape test that creates a user, adds ACL, changes the password, and checks that it was correctly updated.
- split `acl user` codebase into its own directory to keep consistency with the rest of the codebase
Fixes #8252
* rpk: now you can update user credentials with `rpk acl user update`.
=> rpk: add `rpk acl user update` and tests

src/v/cluster/tests/topic_table_test.cc, src/v/kafka/server/tests/CMakeLists.txt, src/v/kafka/server/tests/config_utils_test.cc
Add some tests as an exposition of setting and removing schema id validation properties.
Fixes https://github.com/redpanda-data/redpanda/issues/11115
* none
=> schema_registry: Schema ID Validation low-level tests

tests/rptest/test_suite_quick.yml
Not needed for every single PR, plus, we can save some logins by avoiding running this test every PR.
* none
=> tests: only run rpk_cloud_test in CDT

src/go/rpk/pkg/cli/cluster/logdirs.go, src/go/rpk/pkg/cli/profile/clear.go, src/go/rpk/pkg/cli/profile/create.go, src/go/rpk/pkg/cli/profile/current.go, src/go/rpk/pkg/cli/profile/delete.go, src/go/rpk/pkg/cli/profile/edit.go, src/go/rpk/pkg/cli/profile/edit_defaults.go, src/go/rpk/pkg/cli/profile/print.go, src/go/rpk/pkg/cli/profile/print_defaults.go, src/go/rpk/pkg/cli/profile/profile.go, src/go/rpk/pkg/cli/profile/prompt.go, src/go/rpk/pkg/cli/profile/prompt_test.go, src/go/rpk/pkg/cli/profile/set_defaults.go, src/go/rpk/pkg/cli/profile/use.go, src/go/rpk/pkg/cli/root.go, src/go/rpk/pkg/cli/topic/describe.go, src/go/rpk/pkg/config/params.go, src/go/rpk/pkg/config/params_test.go, src/go/rpk/pkg/config/rpk_yaml.go, src/go/rpk/pkg/config/rpk_yaml_test.go, src/go/rpk/pkg/kafka/client_franz.go, src/go/rpk/pkg/os/file.go, src/go/rpk/pkg/out/color.go, src/go/rpk/pkg/out/out.go, tests/rptest/clients/rpk_remote.py, tests/rptest/tests/rpk_profile_test.py
This PRs adds some missing features of rpk profile:
- Adds rpk profile clear: let the user clear the current profile. (Useful to under prod cluster profiles)
- Enable creating a profile from another file that contains a profile (rpk profile create --from-profile)
- Adds rpk profile prompt command: It let's user configure a custom bash prompt via rpk for a specific profile.
- Adds a new flag `--stable` to `rpk topic describe` to only print the `stable` column if the flag is used.
- Fix: allow rpk to be used without setting $HOME
- Revert the `-v` change to default to DEBUG level instead of INFO.
- Hide non -X flags by default.
- This means users won't see the help text for any of the non -X flags (`brokers`, `api-urls`, `admin-api-tls`, etc...)
- Adds Defaults to rpk.yaml: Global …
=> rpk profile: more

tests/rptest/tests/cloud_storage_timing_stress_test.py, tests/rptest/tests/e2e_shadow_indexing_test.py
This PR adjusts tests to make sure chunk read paths are covered in existing tests. Setting a chunk size smaller than the segment size in existing tests ensures that the read path uses chunks to download segments.
* none
=> ducktape: testing for chunk read path

tests/rptest/tests/scram_test.py
Logic error where an 'if' should have been a 'while'
Fixes: #10330
* None
=> dt/scram: Ensure control characters are present

src/v/kafka/protocol/kafka_batch_adapter.cc, tests/rptest/scale_tests/cloud_storage_compaction_test.py
Backport https://github.com/redpanda-data/redpanda/pull/11324 into v23.1.x
Fixes: https://github.com/redpanda-data/redpanda/issues/11331
* none
=> [v23.1.x] k/proto: use log-level warn for missmatch crc

src/v/kafka/protocol/kafka_batch_adapter.cc
Backport https://github.com/redpanda-data/redpanda/pull/11324 into v22.2.x
Fixes: https://github.com/redpanda-data/redpanda/issues/11332
* none
=> [v22.2.x] k/proto: use log-level warn for missmatch crc

src/v/kafka/protocol/kafka_batch_adapter.cc
Backport https://github.com/redpanda-data/redpanda/pull/11324 into v22.3.x
Fixes: https://github.com/redpanda-data/redpanda/issues/11330
* none
=> [v22.3.x] k/proto: use log-level warn for missmatch crc

src/v/cluster/rm_stm.cc, tests/rptest/tests/tx_admin_api_test.py
The test expires the same tx on multiple partitions. The expiration is a background process so the cancellation of the same tx using 2nd partition may collide with the background part of the first request.
Adding retries to solve the problem.
Fixes #10168
* none
=> ducky: retry mark_transaction_expired request

tools/rp_storage_tool/src/bucket_reader.rs, tools/rp_storage_tool/src/remote_types.rs
This PR teaches rp-storage-tool to validate the existence of segments mentioned
by archive manifests (same as it does for segments mentioned by the STM manifest).
I've also included some basic parsing and reporting of the lifecycle markers which are
uploaded as part of scrubbing.
* none
=> tools/rp-storage-tool: validate segments in the archive

tests/rptest/k8s_tests/simple_k8s_test.py, tests/rptest/services/cluster.py, tests/rptest/services/redpanda.py, tests/rptest/tests/availability_test.py, tests/rptest/tests/cluster_config_test.py, tests/rptest/tests/cluster_metrics_test.py, tests/rptest/tests/partition_balancer_test.py, tests/rptest/tests/redpanda_binary_test.py, tests/rptest/tests/redpanda_kerberos_test.py, tests/rptest/tests/services_self_test.py, tests/rptest/tests/transactions_test.py
Assert that nodes have <50% CPU usage before teardown
In ducktape during test teardown, poll metrics to assert that we don't have a bunch of work that isn't being cleaned up properly.
We poll over a 1 second interval, then fallback to a 5 second interval in the case of compaction happening in the background.
These checks are disabled for now on a few tests that do not shutdown cleanly nodes, as the metrics requests fail. There should be followup work to enable the checks on those tests.
Fixes: #10837
* none
=> Assert CPU <50% at the end of ducktape tests

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/config/convert.h, src/v/config/property.h, src/v/config/rjson_serialization.cc, src/v/config/rjson_serialization.h, src/v/features/feature_table.cc, src/v/features/feature_table.h, src/v/kafka/server/handlers/alter_configs.cc, src/v/kafka/server/handlers/configs/config_utils.h, src/v/kafka/server/handlers/describe_configs.cc, src/v/kafka/server/handlers/incremental_alter_configs.cc, src/v/kafka/server/tests/alter_config_test.cc, src/v/pandaproxy/schema_registry/schema_id_validation.h, src/v/pandaproxy/schema_registry/validation.cc, src/v/pandaproxy/schema_registry/validation.h, tests/rptest/tests/cluster_config_test.py, tests/rptest/tests/schema_registry_test.py, tests/rptest/tests/topic_creation_test.py
#10650 introduced schema ID validation gated behind a feature that was enabled by default.
Instead, gate it on cluster configuration, that is disabled by default. E.g.:
```
rpk cluster config set enable_schema_id_validation redpanda --api-urls=localhost:19644
```
There are three possible configuration options:
* `none`: feature is disabled, checking will not occur, associated topic properties cannot be modified
* `redpanda`: Feature is enabled, redpanda topic properties are accepted
* `compat`: Feature is enabled, redpanda and compatible topic properties are accepted
Closes #11113 
* none
=> schema_registry: Switch Schema ID Validation enablement to cluster config

src/v/cluster/partition_balancer_backend.cc, src/v/cluster/partition_balancer_backend.h, src/v/cluster/partition_balancer_planner.cc, src/v/cluster/partition_balancer_planner.h, src/v/cluster/partition_balancer_state.cc, src/v/cluster/partition_balancer_state.h, src/v/cluster/tests/partition_balancer_bench.cc, src/v/cluster/tests/partition_balancer_planner_fixture.h, src/v/cluster/tests/partition_balancer_planner_test.cc, src/v/cluster/tests/topic_table_fixture.h, src/v/cluster/tests/topic_table_test.cc, src/v/cluster/topic_table.cc, src/v/cluster/topic_table.h, src/v/utils/stable_iterator_adaptor.h, src/v/utils/tests/CMakeLists.txt, src/v/utils/tests/stable_iterator_test.cc
Fixes https://github.com/redpanda-data/core-internal/issues/550
* none
=> partition_balancer: futurize ticks to avoid reactor stalls with large number of topics

src/v/cloud_storage/segment_chunk_data_source.cc
When chunk hydration fails, copy the exception pointer instead of using reference to it, so that there are no lifetime issues when rethrowing the exception after cleanup.
Spin off from #11292, which failed the static analysis.
Fixes: https://github.com/redpanda-data/redpanda/issues/11285
* none
=> cloud_storage: adjust chunk hydration error handling

tests/rptest/tests/throughput_limits_snc_test.py
The test could create two kafka_throughput_control groups with empty names, or other identical names. Group names are required to be unique when present. This change guarantees unique group names provided by the test.
Fixes #11338
* none
=> Avoid duplicate group names in the test in snc trhoughput config test

src/v/kafka/protocol/kafka_batch_adapter.cc
Recently, #11324 changed the log-level from error to warn for a CRC missmatch. However, on the same event, RP will also log "batch has invalid CRC" at the error level.
This PR therefore changes the log for "batch has invalid CRC" to warn level.
Fixes #11361
* none
=> k/proto: use log-level warn for invalid crc

src/v/archival/probe.h, src/v/cloud_roles/probe.h, src/v/cloud_roles/refresh_credentials.cc, src/v/cloud_roles/refresh_credentials.h, src/v/cloud_storage/probe.h, src/v/kafka/group_probe.h, src/v/kafka/latency_probe.h, src/v/kafka/server/handlers/handler_probe.h, src/v/kafka/server/server.cc, src/v/kafka/server/server.h, src/v/net/client_probe.h, src/v/net/server.cc, src/v/net/server.h, src/v/net/server_probe.h, src/v/net/transport.cc, src/v/net/transport.h, src/v/pandaproxy/probe.h, src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/probe.h, src/v/raft/recovery_stm.cc, src/v/raft/replicate_batcher.cc, src/v/raft/vote_stm.cc, src/v/rpc/transport.cc, src/v/rpc/transport.h, src/v/storage/disk_log_impl.cc, src/v/storage/disk_log_impl.h, src/v/storage/probe.h
Probes register metrics by capturing `this`, and it's not save to move
them after that. In a lot of places this is safe because their lifetime
is directly tied to a service which lives the whole program's lifetime,
but any small move of that object even during initialization can break
things (see #11155, #11095, #11107).
This takes a big hammer approach to removing this foot gun by making all
probes immovable and wrapping them in `std::unique_ptr`.
* none
=> treewide: Mark all probes as immovable

src/v/cluster/controller.h, src/v/redpanda/admin/api-doc/debug.json, src/v/redpanda/admin_server.cc, tests/rptest/tests/controller_erase_test.py
Controller erasure test is supposed to validate if there is a mismatch
between the last appended entry in `kvstore` and controller max offset. In
order for the test to work correctly we must wait for all the messages
to be committed as we only delete the last segment that contains a
single message (new replicated configuration). In order to make the test
reliable change the condition to wait for the applied offset on the node
where controller log is going to be removed to be equal to the leader
dirty offset.
Fixes: #8217
- none
=> Wait for the victim node to apply the dirty offset

tests/rptest/services/redpanda.py
Without this the allow list of logs will build up as a process runs.
* none
=> ducktape: Copy allowed log lines before modifying them

tests/rptest/tests/throughput_limits_snc_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11339
Fixes https://github.com/redpanda-data/redpanda/issues/11392,
=> [v23.1.x] Avoid duplicate group names in the test in snc trhoughput config test

src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h
Backport of PR #10671
Fixes #10819
* none
=> [v23.1.x] Fix aborted txs being visible

tests/rptest/services/kcat_consumer.py, tests/rptest/tests/throughput_limits_snc_test.py
In `ThroughputLimitsSnc.test_consumers`, by the time the 1st consumer joins the cgroup, the 0th consumer has not fetched any messages from partition 1 yet, and there is no offset stored for that partition. Consumer 1, who was supposed to read from the stored offset, then defaults to reading from the end, and since the producer is already done by that time, does not fetch a single message, thus failing to verify the assertion.
This PR makes the 1st consumer to default to reading from the beginning of partition.
The issue was introduced in #10785
Fixes #11157
* none
=> Default to reading from the beginning of partition in `ThroughputLimitsSnc.test_consumers`

tests/rptest/clients/rpk.py
In tests that enable SASL auth, it is possible for RPK to issue a CreateTopics requests before the user has replicated across the cluster. The solution is to retry the request.
Fixes #11203
* none
=> tests/rpk: auto-retry on SASL auth fail

tests/rptest/tests/partition_move_interruption_test.py
Recent changes in Redpanda debug builds caused it to be even slower than before. Limited the amount of data produced during the test for debug builds to make the test less flaky and not report false positives.
Fixes: #10497 
- none
=> Limited throughput for debug builds in `partition_move_interruption` test

tests/rptest/services/redpanda.py
When debugging #11275, it seems like there is an `apport` process who's
pid is being picked up. Here's a process dump that includes the line.
There are no running redpanda processes, but checking for redpanda
processes times out, leading me to believe that this process is being
picked up.
In that case `stop_node` can fail if the node is already failed in CDT,
as this `apport` process is picked up.
[DEBUG - 2023-06-12 02:54:07,216 - redpanda - _log_node_process_state - lineno:2215]: root      136962 99.6  6.0 1587948 1452804 ?     R    02:53   0:49 /usr/bin/python3 /usr/shar
e/apport/apport -p136954 -s5 -c18446744073709551615 -d1 -P136954 -u0 -g0 -- !opt!redpanda_installs!head!libexec!redpanda
Fixes: #11275
* none
=> ducktape: use pgrep to find the redpanda process

tests/rptest/k8s_tests/simple_k8s_test.py, tests/rptest/services/cluster.py, tests/rptest/services/redpanda.py, tests/rptest/tests/availability_test.py, tests/rptest/tests/cluster_config_test.py, tests/rptest/tests/cluster_metrics_test.py, tests/rptest/tests/partition_balancer_test.py, tests/rptest/tests/redpanda_binary_test.py, tests/rptest/tests/redpanda_kerberos_test.py, tests/rptest/tests/services_self_test.py, tests/rptest/tests/transactions_test.py
Reverts redpanda-data/redpanda#10939
Fixes https://github.com/redpanda-data/redpanda/issues/11424
* none
=> Revert "Assert CPU <50% at the end of ducktape tests"

src/v/kafka/protocol/kafka_batch_adapter.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11384
Fixes https://github.com/redpanda-data/redpanda/issues/11395,
=> [v22.2.x] k/proto: use log-level warn for invalid crc

src/v/kafka/protocol/kafka_batch_adapter.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11384
Fixes https://github.com/redpanda-data/redpanda/issues/11399
=> [v23.1.x] k/proto: use log-level warn for invalid crc

src/v/cluster/tests/local_monitor_test.cc, src/v/redpanda/admin/api-doc/debug.json, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h, src/v/redpanda/application.cc, src/v/storage/node.cc, src/v/storage/node.h, tests/rptest/services/admin.py, tests/rptest/tests/full_disk_test.py
Lie about disk space stats so that we can do things like avoid having to fill up a disk to simulate low-disk space. This is possible today with an environment variable, but we'd like more control.
* none
=> [storage]: add interface for lying about disk space stats

tests/rptest/tests/compacted_verifier_test.py
Debug builds are slower than release and sometimes they time out. Fixing the flakiness by increasing the progress timeout for the debug builds only.
Fixes #11065
* none
=> ducky: increase test_tx timeout for debug builds

src/v/pandaproxy/auth_utils.h, src/v/pandaproxy/kafka_client_cache.cc, src/v/pandaproxy/server.h, src/v/pandaproxy/test/kafka_client_cache.cc, src/v/pandaproxy/types.h, src/v/redpanda/request_auth.cc, src/v/redpanda/request_auth.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/11425
=> [v22.3.x] pandaproxy: Support SCRAM-SHA-512 for basic_auth

src/v/bytes/details/io_fragment.h, src/v/bytes/iobuf.cc, src/v/bytes/iobuf.h, src/v/http/tests/framing_test.cc, src/v/storage/batch_cache.cc
* Mostly interface cleanup (rename, remove dead code, simplify constructors)
* none
=> A few v::bytes clean-ups

tests/rptest/services/cluster.py, tests/rptest/services/redpanda.py
In #11275 we get a false positive detecting a crash because of an
expected log line. Let's ignore those when looking for crashes.
Note the test is still failing, but due to a different reason than what
this function is calling.
* none
=> ducktape: support skipping log lines for `raise_on_crash`

src/go/rpk/pkg/cli/acl/user/create.go, src/go/rpk/pkg/cli/acl/user/update.go, src/go/rpk/pkg/cli/container/start.go, src/go/rpk/pkg/config/params.go
=> rpk: avoid mentioning old flags in help text, fix -X defaults.no_default_cluster

src/v/cluster/cluster_utils.cc, src/v/cluster/cluster_utils.h, src/v/cluster/node_status_backend.cc, src/v/cluster/node_status_backend.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/application.cc, src/v/rpc/connection_cache.cc, src/v/rpc/connection_cache.h, tests/rptest/tests/node_status_test.py
When a peer restarts and a backoff is applied locally, it needs to be
reset once the peer is available again. Otherwise the transport does not
reconnect until the entire backoff elapses thus marking it unavailable
for downstream consumers like partition balancer.
Fixes https://github.com/redpanda-data/redpanda/issues/5795
Fixes #11307
Fixes https://github.com/redpanda-data/redpanda/issues/11276
* none
=> node_status_backend: reset backoff on peer checkin

src/v/pandaproxy/schema_registry/validation.cc, src/v/redpanda/admin_server.cc, tests/rptest/tests/schema_registry_test.py
* Prevent enabling schema ID validation checks if schema registry is disabled
* If schema registry becomes disabled, reject records and log an error
The documentation may need improving to make it clear that server-side-schema-validation requires the `schema_registry` to be enabled in `redpanda.yaml`.
Fixes #11116
* none
=> schema_registry: Schema id validation - config checking

tests/rptest/tests/retention_policy_test.py
The condition for the test checks if the number of segments uploaded is exactly equal to one minus the local segment count. 
Since the max upload interval is set we can end up uploading all segments to the cloud including the open segment(as seen in CI failures). This change adjusts the success condition to include the case where all segments are uploaded.
Fixes https://github.com/redpanda-data/redpanda/issues/9587
* none
=> ducktape: Change condition for upload check to pass when all segments are uploaded

src/go/rpk/pkg/api/admin/api_user.go, src/go/rpk/pkg/cli/cloud/login.go, src/go/rpk/pkg/cli/profile/create.go, src/go/rpk/pkg/cloudapi/api_virtual_cluster.go, src/go/rpk/pkg/cloudapi/cloudapi.go, src/go/rpk/pkg/config/rpk_yaml.go, src/go/rpk/pkg/kafka/client_franz.go
This PR has one extra commit on #11394, which was approved otherwise.
Now rpk cloud login will display a list of
virtual clusters and clusters when you succesfully logged in. Then you can pick one of them and rpk
will create a profile with the selection.
If there is just one cluster, it will select that
cluster by default and create a profile.
* none
=> rpk: list virtual cluster on cloud login

src/v/config/throughput_control_group.cc
=> throughput control groups: fixed zero byte dumped to the log by noname group

src/v/storage/log_manager.cc
This function can race with segment::close before being able to call orphan_filter. This commit lowers the log level similar to how it is done in segment::close
Fixes #10366 
* none
=> [storage] log_manager::remove_orphan_files: error -> trace for ENOENT

src/v/config/throughput_control_group.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11340
=> [v23.1.x] throughput control groups: fixed zero byte dumped to the log by noname group

tests/rptest/tests/leadership_transfer_test.py
This PR updates the node start timeout of this test to 60 seconds for debug builds. The need for this change comes from the 500+ partitions this test creates which leads to the node starting up 6 times slower compared to an empty node when on a debug build. This change wasn't needed originally, however, with the update to clang-16 there seems to be a slight performance regression in our debug builds causing the node start time to be right around 20s.
Fixes #11044 
* none
=> Update start timeout for `leadership_transfer_test` on debug builds

src/v/kafka/server/group.cc, src/v/kafka/server/group.h, src/v/kafka/server/group_manager.cc, src/v/kafka/server/group_manager.h
The commit is correlated with the new ci-failures. Rolling it back. It's ok to rollback only a single commit from the [PR](https://github.com/redpanda-data/redpanda/pull/11110) because its other commits don't depend on it.
Fixes:
- https://github.com/redpanda-data/redpanda/issues/11372
- https://github.com/redpanda-data/redpanda/issues/11452
- https://github.com/redpanda-data/redpanda/issues/11344
This reverts commit f7fc026f3203da167acc0e4c95b86f2e7e082dec.
* none
=> Revert "txn: update abort_old_txes to use locks"

tests/rptest/tests/retention_policy_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11433
Fixes https://github.com/redpanda-data/redpanda/issues/11445,
=> [v23.1.x] ducktape: Change condition for upload check to pass when all segments are uploaded

tests/rptest/tests/controller_erase_test.py
`RedpandaService::controller` may sometimes return `None` causing the test to fail. Fixed this issue with waiting for the controller to be reported.
Fixes: #11456
- none
=> tests: wait for controller to be elected when deciding which node to use

tests/rptest/tests/nodes_decommissioning_test.py
If we throttle after we issue the decom command, decom can finish before the throttling will take effect. The correct order (if we want the partition movements to get stuck) is throttle-then-decom.
Fixes https://github.com/redpanda-data/redpanda/issues/11365
* none
=> node_decommissioning_test: fix order of throttle and decommission

tests/rptest/scale_tests/partition_balancer_scale_test.py
After we enabled trace logs in CDT, size of redpanda logs for this test started to exceed 20GB which is unwieldy and sometimes even leads to test failures (bad log lines scans timing out).
* none
=> c/partition_balancer: reduce log level in scale tests

tests/rptest/tests/nodes_decommissioning_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11471
Fixes https://github.com/redpanda-data/redpanda/issues/11487,
=> [v22.3.x] node_decommissioning_test: fix order of throttle and decommission

tests/rptest/tests/nodes_decommissioning_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11471
Fixes https://github.com/redpanda-data/redpanda/issues/11486,
=> [v23.1.x] node_decommissioning_test: fix order of throttle and decommission

tests/rptest/tests/random_node_operations_test.py
Previously a length for tests not using controller snapshots which was set to `None` was overridden in `_setup_test_scale` method
Fixes: #11179
- none
=> Fixed setting max controller log length

tests/rptest/tests/simple_e2e_test.py
Previously the producer used high throughput which may lead to the situation in which consumer continued without a gap in the offset space even after the topic was deleted.
The producer might have already produced enough records to fill the gap and allow consumer to continue where it left of.
Using lower producer throughput and waiting for large number of records to be consumed before deleting topic will prevent this situation from happening.
Fixes: #11459
- none
=> Fixed setting up consumer for interruption test

src/v/cluster/members_table.cc, src/v/cluster/members_table.h, src/v/cluster/node_status_backend.cc
If the members table update is coming from a controller snapshot, and the node is already being decommissioned, there won't be a notification with status "added", only with status "draining". Node discovery code should handle this case as well.
(partially) fixes https://github.com/redpanda-data/redpanda/issues/9052
* none
=> c/node_status_backend: fix handling members notification

tests/rptest/services/admin_ops_fuzzer.py
When answering the admin API requests a node should be a cluster member,
otherwise it may returned stalled data which will never converge to the
expected state. 
Made admin operations fuzzer aware of decommissioned node to prevent querying stale state.
Fixes: #11158 
Fixes: #9293
- none
=> Do not query decommissioned nodes

tests/rptest/clients/everything-allowed-exec-pod.yml, tests/rptest/clients/kubectl.py, tests/rptest/services/action_injector.py, tests/rptest/services/failure_injector.py, tests/rptest/services/redpanda.py, tests/rptest/tests/e2e_finjector.py, tests/rptest/tests/partition_balancer_test.py, tests/rptest/tests/services_self_test.py
Fixes https://github.com/redpanda-data/devprod/issues/680
No changes to existing test behaviour that does not use redpanda cloud.
This PR adds a factory method `make_failure_injector()` to instantiate object from either the existing behaviour `FailureInjector` class or the newly-added class `FailureInjectorCloud` based on config settings in `ducktape_globals.json` (similar to factory pattern in PR #10521)
A simple test class `FailureInjectorSelfTest` is created in `tests/rptest/tests/services_self_test.py` to test the `_isolate()` method on cloud if cloud is enabled in the globals config file. I verified test passes with a cluster that was created before ducktape was run:
```console
ducktape \
--debug \
--globals=/path/to/ducktape_globals.json \
--cluster=ducktape.cluster.json.JsonCluster …
```
=> tests: cloud failure injector

tests/rptest/tests/partition_move_interruption_test.py
Disabled `test_cancellations_interrupted_with_restarts` test running in
debug mode.
Fixes: #10497
- none
=> Disable `test_cancellations_interrupted_with_restarts` in debug 

tests/rptest/tests/cloud_storage_chunk_read_path_test.py
Previously, test_read_when_segment_size_smaller_than_chunk_size would not use the correct segment size when waiting for truncation. _produce_baseline used self.log_segment_size, but the test only updated the topic config. The result was that the test could fail due to no chunk reads being performed.
Fixes #11507
* none
=> rptest: fix wait for trunction in chunk read test

tests/rptest/tests/cloud_storage_usage_test.py, tests/rptest/utils/si_utils.py
When comparing the on disk size of an NTP with the cloud manifest size, we now skip the data which is below manifest start offset to prevent mismatches due to a pending prefix truncation.
Fixes https://github.com/redpanda-data/redpanda/issues/11066
* none
=> ducktape: Fix ntp cloud size estimate

src/v/storage/segment.cc, src/v/storage/segment.h, src/v/storage/segment_reader.cc, src/v/storage/segment_reader.h, src/v/storage/segment_utils.cc, src/v/storage/tests/log_replayer_test.cc
This patch wraps all segment_reader usages into a unique_ptr. Move
semantics for segment_reader are tricky to get right. One of the ways
this could go wrong previously is moving a segment_reader with
outstanding gated operations. Since gate guards hold a pointer to the
underlying gate, a move would create dangling pointers.
A similar strategy is also used for the segment_appender.
Fixes https://github.com/redpanda-data/redpanda/issues/11408
* Fix a possible dangling pointer issue in the storage layer
=> storage: wrap segment_reader in a unique_ptr

src/v/resource_mgmt/tests/CMakeLists.txt, src/v/resource_mgmt/tests/memory_sampling_reclaimer_test.cc, src/v/resource_mgmt/tests/memory_sampling_tests.cc
In those tests we set a `std::stringstream` for the seastar logger so that
we can actually test what is being logged.
However, in contrast to `std::cerr` `std::stringstream` is of course not
threadsafe so if multiple reactors try to log at the same time things go
wrong.
Ideally we could just use `<syncstream>` but libc++ doesn't support that
yet. Hence, just run the tests with only a single reactor thread.
Additionally properly stop the services.
Issue https://github.com/redpanda-data/redpanda/issues/11513
* none
=> memory-sampling: Reduce reactor count for mem sampling tests

tests/rptest/tests/memory_sampling_test.py
The admin_api memory sampling test was bound to fail as it assumed a
fixed shard count but that obviously depends on the infra and fails on
CDT.
Make the test use the actual shard count to confirm we get results for
all shards.
Fixes https://github.com/redpanda-data/redpanda/issues/11509
* none
=> memory-sampling: Make admin api test work on CDT

src/v/storage/segment.cc, src/v/storage/segment.h, src/v/storage/tests/storage_e2e_test.cc, tests/rptest/tests/log_segment_ms_test.py
When a segment is rolled due to the `segment.ms` property its base offset is set to the committed offset of last segment plus one. In a segment constructor all segment offset tracker offsets were set to the base offset passed as the constructor argument. This way an empty segment had exactly the same set of offsets as the segment containing single batch containing one record and base offset equal to the segment base offset.
Incorrect offset accounting in empty segments lead to the situation in which eviction driven `log::truncate_prefix` was called with an incorrect offset, leading to the situation in which a log wasn't truncated at the segment boundary. This in the end resulted in the disconnection between the offset translator truncation point and first log segment start offset.
For …
=> s/segment: fixed tracking offsets of empty segments

src/v/resource_mgmt/tests/CMakeLists.txt, src/v/storage/batch_cache.cc
We added a condition variable which would notify from the batch cache
whenever a reclaim happened.
This is bad because the signal in the condition variable can potentially
allocate which can lead to recursive reclaim calls.
Disable the notification (and as a consequence the logging when reaching
a lower watermark threshold) until we have a proper fix. We will either
need to use another notification mechanism or notify from the background
reclaimer.
Keeping all the other code in place as we will want to reuse it.
* none
=> memory-sampling: Disable top-n alloc sites logging on low memory

src/v/raft/consensus.cc, src/v/raft/prevote_stm.cc, src/v/raft/vote_stm.cc, tests/rptest/tests/cluster_features_test.py, tests/rptest/tests/maintenance_test.py
Redpanda Raft implementation exposes an API allowing to override a voter
priority. This is used by the drain manager when a node is in
maintenance mode. In current implementation when the only voter is in
maintenance mode the Raft group is not able to elect a leader as the
reported priority it to low (the priority override in maintenance is set to 0).
Fixed Raft implementation to make sure that it prioritize an
availability over the user priority preference. If a node is the only
voter the priority override is ignored.
* Fixed not being able to elect a leader in situation when only voter is in maintenance mode
=> Fixed Raft voter priority override with single replica topics

src/v/archival/adjacent_segment_merger.cc, src/v/archival/adjacent_segment_merger.h, src/v/archival/ntp_archiver_service.cc, src/v/archival/scrubber.cc, src/v/archival/scrubber.h, src/v/archival/tests/upload_housekeeping_service_test.cc, src/v/archival/types.h, src/v/archival/upload_housekeeping_service.cc, src/v/archival/upload_housekeeping_service.h, src/v/cloud_storage/remote.cc, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_partition.h, src/v/cluster/partition.cc, src/v/cluster/partition.h, src/v/cluster/partition_manager.cc, src/v/cluster/topic_table.cc, src/v/cluster/types.cc, src/v/cluster/types.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/utils/retry_chain_node.cc, src/v/utils/retry_chain_node.h, src/v/utils/tests/retry_chain_node_test.cc, tests/rptest/archival/abs_client.py, tests/rptest/archival/s3_client.py, tests/rptest/services/redpanda.py, tests/rptest/tests/topic_delete_test.py, tests/rptest/utils/si_utils.py
This PR updates the topic deletion logic to make it aware of spillover manifests.
Deletion of spillover manifests and their segments is done as part of the scrub,
which means it can be retried as many times as required.
The general approach is to:
1. Issue ListObjects request to find all manifests
2. Starting with the current manifests, iterate over all manifests found
in the bucket and delete all their associated segments and, finally,
the manifest itself.
* none
=> archival: handle deletion of topics with spilled over manifests

.github/workflows/old-backports
Initial commit. May need to explicitly include gh token. Directing this to my personal channel, so that others do not get spammed. Once everything is ironed out, frequency will be set to once per week.
* none
=> Send out a list of backports that are older than 15 days [skip-ci]

src/v/resource_mgmt/memory_sampling.cc, src/v/resource_mgmt/tests/memory_sampling_tests.cc
Probably got lost in the various revisions.
Add it back and make sure the test catches it.
* none
=> memory-sampling: Fix missing newline between stacks in OOM output

src/go/rpk/pkg/cli/generate/prometheus.go, src/go/rpk/pkg/cli/generate/prometheus_test.go
This PR introduces a new flag '--labels' which
lets the user add a common label for the targets
in the rpk-generated scrape-config.
Fixes #5548
Common tag
```yaml
$ rpk generate prometheus-config --job-name redpanda-metrics-test --node-addrs 'localhost:9644,localhost:9645' --internal-metrics --labels "hello=world" 
- job_name: redpanda-metrics-test
static_configs:
- targets:
- localhost:9644
- localhost:9645
labels:
hello: world
metrics_path: /public_metrics
- job_name: redpanda-metrics-test
static_configs:
- targets:
- localhost:9644
- localhost:9645
labels:
hello: world
metrics_path: /metrics
```
Different tags per job
```yaml
$ rpk generate prometheus-config --job-name redpanda-metrics-test --node-addrs 'localhost:9644,localhost:9645' --internal-metrics --labels …
```
=> rpk: add labels to rpk generate prometheus-config

.github/workflows/old-backports.yml
Name the action file properly, and use the latest actions' version.
* none
=> Name the action file properly [skip-ci]

.github/workflows/old-backports.yml
=> Run  the old-backports command every day (not just thursday) while we are testing things out. [skip-ci]

.github/workflows/old-backports.yml
=> Point the old-backports action to a public channel. [skip-ci]

.github/workflows/old-backports.yml
=> old-backports action: use the correct variable name. [skip-ci]

src/v/cluster/cluster_utils.cc, src/v/redpanda/admin_server.cc, src/v/rpc/connection_cache.cc, src/v/rpc/connection_cache.h, src/v/rpc/errc.h
The first step in the shutdown sequence is to empty the local cache. Previously, attempts to get a connection after that returned with errc::missing_node_rpc_client, which is potentially indicative of a bug. Return a more benign error code instead.
Fixes https://github.com/redpanda-data/redpanda/issues/10112
* none
=> rpc/conn_cache: return errc::shutting_down after shutdown

tests/rptest/tests/memory_stress_test.py
The failing case is OOM when memory reserved for fetch is 80% of kafka memory, but apparently some knobs in memory control do not reflect what is going on with allocations indeed. For this specific test, the setting should go down gradually until this crash is gone, and that should become the highest recommended setting for now.
Getting it down to 0.7.
Fixes #11458
* none
=> Adjust maximum value for `memory_share_for_fetch` in `MemoryStressTest.test_fetch_with_many_partitions`

tests/rptest/tests/rack_aware_replica_placement_test.py
...in debug mode. Runs are failing with timeout in topic creation.
Creation doesn't return control until all partitions are assigned leaders. Raft groups are created but the RPCs to other nodes are repeatedly timing out resulting in leaderlessness. Disabling the test until we get to the bottom of it.
* none
=> ducktape: disable test_replica_placement.num_partitions=400

tests/rptest/tests/topic_creation_test.py
Test test being updated does not wait for the ntp manifsets to be uploaded since that's not its aim. Its therefore fine for the ntp manifest to be missing at the end.
Fixes #10605
* none
=> rptest: allow missing ntp manifest in upgrade test

src/v/net/batched_output_stream.cc
`close()` must always be called; move it to a finally block.
Prevent `Assertion !_in_batch && "Was this stream properly closed?"` in `seastar::output_stream<char>::~output_stream()`
Fix #11564
Fix #10218 
* net: Fix a rare crash during shutdown of a failed connection with outstanding requests
=> net/batched_output_stream: call `close()` in a finally block

src/v/raft/consensus.cc, src/v/raft/prevote_stm.cc, src/v/raft/vote_stm.cc, tests/rptest/tests/cluster_features_test.py, tests/rptest/tests/maintenance_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/10800
=> [v23.1.x] Fixed Raft voter priority override with single replica topics

src/v/archival/ntp_archiver_service.cc, src/v/archival/tests/ntp_archiver_test.cc, src/v/cloud_storage/async_manifest_view.cc, src/v/cloud_storage/tests/async_manifest_view_test.cc, src/v/http/tests/http_imposter.cc
This PR fixes a bunch of issues with the archive retention mechanisms. These surfaced
while I was working on including spillover in the timing stress tests.
**Infinite loop**
In order to queue segments up for deletion we iterate over the spillover
manifests and pick the ones below the archive start offset. This
procedure could result in an infinite loop if the archive start offset
equals the start offset of the STM region. Checking if the cursor has
reached the end solves the issue.
**Time based retention in the archive**
1. Timestamp search of spilled manifests is inclusive, so if, for
example, we have a spillover manifest where all segments are 10
minutes old and retention limit of 5 minutes, we'd not apply any
retention since the spillover manifest could not be found. This is
fixed by …
=> cloud_storage: archival retention and garbage collection fixes

src/v/cloud_storage/recovery_request.cc, src/v/cloud_storage/recovery_request.h, src/v/cloud_storage/tests/recovery_request_test.cc, src/v/cloud_storage/tests/topic_recovery_service_test.cc, src/v/cluster/topic_recovery_service.cc, src/v/cluster/topic_recovery_service.h, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h
Currently the seastar framework reads the full request body in for us on
every request: https://github.com/redpanda-data/seastar/blob/245e0ccfa6d58d7e0dca2b4034ce1bc43e39bdc5/src/http/httpd.cc#L202-L210
In our efforts to reduce large contiguous allocations, we probably
shouldn't always do this. Also, in the future there maybe large payloads
we accept (i.e. WASM file uploads) that we certainly don't want to fully
read into memory contiguously. So this gives each caller the ability to determine if
it's safe to read the full stream into contiguous memory.
I don't know if there are any admin server payloads that could
potentially read in large request bodies today, but I essentially inlined
all the places where we read in `req->content` to instead read the full
input stream.
* none
=> admin: Stream request bodies

tests/rptest/services/admin_ops_fuzzer.py, tests/rptest/tests/admin_operations_test.py
The Admin operation fuzzer creates and deletes some topics, to make the
test more complete added an operation that will produce some messages to
topics created by admin ops fuzzer.
- none
=> Added produce to topic operation to ops fuzzer

src/v/archival/tests/ntp_archiver_test.cc
Previously, the archive gc future was backgrounded, but that may race with the stopping of the async_manifest_view.
Fixes https://github.com/redpanda-data/redpanda/issues/11626
* none
=> archival: wait for gc future completion in unit test

src/v/cluster/tests/partition_balancer_simulator_test.cc
* Fix even topic partition distribution check - expect variance to be proportional to sqrt(expected)
* Fix node disk sizes (prevent disk overflow on target nodes)
Fixes https://github.com/redpanda-data/redpanda/issues/11538
* none
=> Fix counts rebalancing simulation test problems

tests/rptest/archival/s3_client.py, tests/rptest/services/redpanda.py
A previous refactor of the code around emptying the bucket and deletion was buggy. This resulted in tests not cleaning up their buckets properly. This patch fixes the issue and adds an appropriately scary error log.
* none
=> rptest: fix S3 bucket deletion

src/v/cluster/tests/serialization_rt_test.cc, src/v/cluster/tests/topic_configuration_compat_test.cc, src/v/cluster/types.cc, src/v/model/tests/randoms.h
* Add `adl` tests for `incremental_property_update`
* Remove `adl` serailization for `topic_properties`
* Add serde tests for `topic_properties` and `incremental_topic_updates`
Fixes #11112
* none
=> c/types: Add tests for Schema ID Validation properties

src/v/cluster/partition_probe.cc, src/v/cluster/partition_probe.h, src/v/kafka/server/handlers/produce.cc, src/v/pandaproxy/schema_registry/validation.cc, src/v/pandaproxy/schema_registry/validation.h
* Add a metric for schema id validation failure - Fixes #11501
* Convert exceptions into failed result - Fixes #11526
* Add the metrics also to the public endpoint.
* Reconfigure when enable_schema_id_validation is toggled, so that a restart isn't required to view the metrics.
* I put these in the same PR since I found the latter whilst fixing the former, and they'd just collide anyway.
New topic-level metrics on `/metrics`:
```
```
New topic-level  metrics on `/public_metrics`
```
```
* none
=> Server side schema id validation metrics v2

src/v/net/connection.cc, src/v/net/tests/CMakeLists.txt, src/v/net/tests/connection.cc
Look through an `ss::nested_exception` to see if it's a `disconnect_exception`.
Fixes #11617 by changing the log level from `error` to `info`.
* none
=> net: `ss::nested_exception` might be a `disconnect_exception`

src/v/kafka/protocol/errors.cc, src/v/kafka/protocol/schemata/generator.py, src/v/kafka/protocol/tests/protocol_test.cc
Tag fields that are primitives, and don't have assigned default values, should not be encoded if their value is equal to 0.
Fixes: #11358
* Improved efficiency in encoding tag values in kafka wire protocol
=> k/protocol: Checking for tag value to be 0

tests/rptest/test_suite_cloud.yml
initial test suite for use by cdt to test on redpanda cloud
this pr is needed for issue https://github.com/redpanda-data/cloudv2/issues/6662
* none
=> rptest: add test_suite_cloud.yml [skip-ci]

src/v/kafka/server/replicated_partition.cc
An upstream Kafka validates if fetch offset is between start offset and log end offset. Fixed validation in Redpanda as we were validating the end of range with high watermark.
Signed-off-by: Michal Maslanka <michal@redpanda.com>
(cherry picked from commit bd73f10597aacf6b237834b5bfabd248e6b78864)
* none
=> [v23.1.x] Backport of bd73f10597aacf6b237834b5bfabd248e6b78864

src/v/net/connection.cc, src/v/net/tests/CMakeLists.txt, src/v/net/tests/connection.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11619
Fixes https://github.com/redpanda-data/redpanda/issues/11640,
=> [v23.1.x] net: `ss::nested_exception` might be a `disconnect_exception`

src/v/net/batched_output_stream.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11586
Fixes https://github.com/redpanda-data/redpanda/issues/11604,
=> [v23.1.x] net/batched_output_stream: call `close()` in a finally block

tests/rptest/clients/rpk.py, tests/rptest/tests/topic_delete_test.py, tests/rptest/utils/si_utils.py
This was a case of passing `topic_name` instead of `[topic_name]`, python helpfully accepting a string as something to iterate over, rpk topic describe not throwing an error on a missing topic, and `quiesce_uploads` not throwing an error of rpk gives it zero partition descriptions.
Fixes https://github.com/redpanda-data/redpanda/issues/8496
Fixes https://github.com/redpanda-data/redpanda/issues/10655
Fixes https://github.com/redpanda-data/redpanda/issues/9629
* none
=> tests: fix call to quiesce_uploads in topic deletion test

src/go/rpk/pkg/cli/cluster/logdirs.go
This PR adds autocompletion for `--agregate-into` flag of `rpk cluster logdirs describe` and it introduces the `--human-readable / -H` flag that prints the size of the log dirs in an human-readable format
```
$ rpk cluster logdirs describe -H
BROKER  DIR                     TOPIC               PARTITION  SIZE     ERROR
1       /var/lib/redpanda/data  __consumer_offsets  0          68.58kB  
1       /var/lib/redpanda/data  asdf                0          2.132kB  
1       /var/lib/redpanda/data  asdf                1          2.132kB  
```
```
$ rpk cluster logdirs describe --aggregate-into broker -H
BROKER  SIZE     ERROR
1       203.9kB
```
Fixes #10536
* rpk: now you can print logdirs in a human-readable format with the `--human-readable` flag in `rpk cluster logdirs describe`
=> rpk: human-readable size in `rpk cluster logdirs describe`

src/go/rpk/pkg/cli/cmd/common/common.go, src/go/rpk/pkg/cli/cmd/redpanda/admin/admin.go
These were missing and are needed for admin API
auth.
This is a manual "backport" of https://github.com/redpanda-data/redpanda/pull/11648
* rpk: support SASL flags in `rpk redpanda admin` commands.
=> [v23.1.x] rpk: add sasl flags to rpk redpanda admin commands

src/go/rpk/pkg/cli/cluster/config/config.go, src/go/rpk/pkg/cli/cluster/health.go, src/go/rpk/pkg/cli/cluster/license/license.go, src/go/rpk/pkg/cli/cluster/maintenance/maintenance.go, src/go/rpk/pkg/cli/cluster/partitions/partitions.go, src/go/rpk/pkg/cli/cluster/selftest/selftest.go, src/go/rpk/pkg/cli/cluster/storage/recovery/recovery.go, src/go/rpk/pkg/cli/redpanda/admin/admin.go, src/go/rpk/pkg/config/params.go
In the refactoring of the new params, we separated the commands that needed admin-api flags and the
commands that needed kafka-api flags. However, the kafka-api flags contains the SASL user, password,
and mechanism which is used by the Admin API for
authentication.
We will only need to backport the `rpk redpanda admin` flags, in <23.1 all the commands installed the kafka flags as well as the admin API flags.
No release notes for this fix, since it's something that is not in prod yet.
* none
=> rpk: add missing SASL flags for admin api auth.

src/v/cluster/log_eviction_stm.cc, src/v/storage/disk_log_impl.cc
Recent CI failures have triggered an ERROR during shutdown due to an exception handler catching a gate closed exception and logging at the error level. Fix is to catch these exceptions and not log error.
Fixes #11628
Fixes https://github.com/redpanda-data/redpanda/issues/11662
* none
=> Cluster: Eviction stm catch gate_closed on shutdown

src/go/rpk/pkg/cli/acl/user/create.go, tests/rptest/clients/rpk.py, tests/rptest/tests/rpk_acl_test.py
This PR adds the ability to auto-generate a secure random password when you create an user without providing the password:
```
$ rpk acl user create foo           
Created user "foo".
Automatically generated password:
klyTO)sF80JnkAxaARG+6DN6ro,9XX
```
This behavior matches how it's done in Redpanda Console.
The generated password gets printed to stdout in the last line in case you automate the process you can pipe it to `tail -1`.
You can still select your password using `-p / --new-password` flag.
Fixes #11235 
The first commit also fixes a minor bug when using --password along with --new-password.
* rpk now generate a password automatically when running `rpk acl user create` with no password
=> rpk: generate password automatically in `rpk acl user create`

src/v/cluster/node/local_monitor.cc, src/v/cluster/node/local_monitor.h, src/v/redpanda/application.cc, src/v/resource_mgmt/CMakeLists.txt, src/v/resource_mgmt/storage.cc, src/v/resource_mgmt/storage.h, src/v/storage/node.cc, src/v/storage/node.h, src/v/storage/types.h
Two changes
1. Largely a refactor/clean-up. Adds a struct to hold extra information like computed thresholds for low-space/degraded states to disk space notification handlers.
2. Wires up the space management control loop to receive disk space notifications.
* none
=> Wire-up and enhance disk space notifications that are delivered to space management control loop

src/v/net/batched_output_stream.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11586
Fixes https://github.com/redpanda-data/redpanda/issues/11600,
=> [v22.3.x] net/batched_output_stream: call `close()` in a finally block

src/v/net/connection.cc, src/v/net/tests/CMakeLists.txt, src/v/net/tests/connection.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11619
Fixes https://github.com/redpanda-data/redpanda/issues/11639,
Small conflict in `CMakeLists.txt` due to #6560 not backported
=> [v22.3.x] net: `ss::nested_exception` might be a `disconnect_exception`

src/v/net/batched_output_stream.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11586
Fixes https://github.com/redpanda-data/redpanda/issues/11602,
=> [v22.2.x] net/batched_output_stream: call `close()` in a finally block

tests/docker/docker-compose.yml
The console port is high numbered and has been seen to occasionally collide with some other program in the CI environment.  We do not use the console anything, so simply switch it off.
* none
=> tests: disable minio console

src/v/storage/disk_log_impl.cc
We have seen a bad_alloc in `compaction_backlog` at least once in the field.  This function was using a gratuitous amount of memory while building a list of all segments divided up by term.
While looking at this code, I also noticed that we would have a O(N^2) runtime in cases where a large number of segments existed in the same term: this is not a typical situation but there are realistic scenarios where it could happen.  Rather than revising the algorithm, I've simply added a clamp on the inner loop so that if a term has a large number of segments we will only consider the first N while calculating compaction backlog.
Fixes https://github.com/redpanda-data/redpanda/issues/11682
* Memory consumption for housekeeping on compacted topics is reduced
=> storage: make `compaction_backlog` more efficient for large segment counts

src/v/cloud_storage/segment_meta_cstore.cc, src/v/cloud_storage/segment_meta_cstore.h, src/v/cloud_storage/tests/CMakeLists.txt, src/v/cloud_storage/tests/segment_meta_cstore_fuzz.cc, src/v/utils/delta_for.h
previously to_iobuf was achieved by constructing a temporary cstore,
appending all the segments and serializing it. this is done so that
to_iobuf can be const, in turn to be able to use it in
base_manifest::serialize.
To minimize operations and memory, this commits adds the ability to
create a column_store that shares all the iobuf with the *this object,
and then serialize it.
sharing is done by constructing on top of deltafor_encoder::share()
const a series of unsafe_alias() const methods, responsible to construct
the subobjects.
this new schema saves time by not re-encoding the segment_meta, and
saves memory by sharing the underlying iobuf objects, to write them
directly in the final serde iobuf
* none
=> cloud_storage: segment_meta_cstore serde optimizations

tests/rptest/services/kgo_verifier_services.py, tests/rptest/tests/topic_delete_test.py, tests/rptest/util.py
Make this test better behaved and remove ok_to_fail
Also opportunistically make some other improvements to the deletion test class, including removing use of the KafkaCliTools.produce helper, which can hide issues (https://github.com/redpanda-data/redpanda/issues/11689)
Fixes https://github.com/redpanda-data/redpanda/issues/11232
* none
=> tests: reinstate drop_lifecycle_marker_test

src/v/kafka/protocol/errors.cc, src/v/kafka/protocol/schemata/generator.py, src/v/kafka/protocol/tests/protocol_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11443
Fixes https://github.com/redpanda-data/redpanda/issues/11642,
=> [v22.2.x] k/protocol: Checking for tag value to be 0

src/v/kafka/protocol/errors.cc, src/v/kafka/protocol/schemata/generator.py, src/v/kafka/protocol/tests/protocol_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11443
Fixes https://github.com/redpanda-data/redpanda/issues/11646,
=> [v22.3.x] k/protocol: Checking for tag value to be 0

src/v/net/tests/connection.cc
This prevents:
```
Test setup error: std::runtime_error: No tests registered
```
The error was introduced in https://github.com/redpanda-data/redpanda/pull/11641 which I accidentally merged.
* none
=> net/tests: Register a BOOST_TEST_MODULE

src/v/archival/scrubber.cc, src/v/archival/upload_housekeeping_service.cc, src/v/cloud_storage/remote.cc, src/v/cloud_storage/tests/remote_test.cc, src/v/cloud_storage/tests/s3_imposter.cc, tests/rptest/services/kgo_verifier_services.py, tests/rptest/tests/topic_delete_test.py, tests/rptest/util.py
The main goal of this PR is to fix an issue with topic deletion that surfaced in
CDT testing. Previously, the scrubber did not re-send retryable requests. The
intention here was to drop out  if the cloud storage provider is applying
throttling as it is unlikely that much progress would be made.
However, the connection is killed after specific request sequences
(posibly due to htpp client bug). Not retrying means that the scrubber
does not make progress. This patch changes the retry strategy used for
purging partitions to exponential backoff in order to work around the
issue.
Related #11710
* none
=> cloud_storage: topic deletion follow up

tests/rptest/tests/upgrade_test.py
For local truncation to happen, we need all the nodes to come up, and object store uploads to finish, and a manifest to upload, and storage-gc interval to tick around.  30 seconds wasn't always enough.
We could just reduce some intervals in the redpanda config, but these tests are intrinsically somewhat time consuming so let's prioritize keeping them
authentic.
Fixes https://github.com/redpanda-data/redpanda/issues/9756
* none
=> tests: bump local truncation timeout in upgrade tests

src/v/cloud_storage/remote_segment_index.cc, src/v/cloud_storage/remote_segment_index.h, src/v/cloud_storage/tests/remote_segment_index_test.cc
When creating coarse index, in addition to reading the index fields, we also read the offset fields. This ensures that in cases where the index is very small and all the data is contained in the offset fields, a mini index can still be generated.
Additionally the calculation of offsets to add in the index is changed so that we do not end up skipping offsets when the mod of current offset is unchanged, which is a bug that the previous iteration of the code was susceptible to.
Fixes https://github.com/redpanda-data/redpanda/issues/11703
* none
=> cloud_storage: Read offset arrays when creating coarse index

src/v/archival/ntp_archiver_service.cc, src/v/archival/tests/archival_metadata_stm_test.cc, src/v/cloud_storage/CMakeLists.txt, src/v/cloud_storage/async_manifest_view.cc, src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/partition_manifest.h, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/segment_meta_cstore.cc, src/v/cloud_storage/segment_meta_cstore.h, src/v/cloud_storage/tests/async_manifest_view_test.cc, src/v/cloud_storage/tests/common_def.h, src/v/cloud_storage/tests/remote_partition_test.cc, src/v/cluster/archival_metadata_stm.cc, src/v/cluster/archival_metadata_stm.h, src/v/raft/consensus.cc, src/v/raft/consensus.h, tests/rptest/tests/archive_retention_test.py, tests/rptest/tests/offset_for_leader_epoch_archival_test.py, tests/rptest/utils/si_utils.py, tools/rp_storage_tool/deltafor/src/lib.rs, tools/rp_storage_tool/src/batch_reader.rs, tools/rp_storage_tool/src/bucket_reader.rs, tools/rp_storage_tool/src/error.rs, tools/rp_storage_tool/src/main.rs, tools/rp_storage_tool/src/main_unstable.rs, tools/rp_storage_tool/src/remote_types.rs, tools/rp_storage_tool/src/util.rs
- Add new duck tape test that checks offset for leader epoch request on `archive` part of the log
- Add spillover manifest metadata to the `spillover_cmd` to improve reliability (the command can be validated by the STM)
* none
=> cloud_storage: Improve manifest spillover robustness

src/v/kafka/protocol/errors.cc, src/v/kafka/protocol/schemata/generator.py, src/v/kafka/protocol/tests/protocol_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11443
Fixes https://github.com/redpanda-data/redpanda/issues/11643,
=> [v23.1.x] k/protocol: Checking for tag value to be 0

src/v/raft/coordinated_recovery_throttle.cc, src/v/raft/tests/coordinated_recovery_throttle_test.cc, tests/rptest/util.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11625
Fixes https://github.com/redpanda-data/redpanda/issues/11727,
=> [v23.1.x] raft/recovery_throttle: use total available capacity

tests/rptest/tests/nodes_decommissioning_test.py, tests/rptest/util.py
Replaced verifiable consumer/producer pair with more robust kgoverifier. 
Fixes: #11061
Fixes: #9837
Fixes: #9290
Fixes: #8980
- none
=> Using kgo-verifier in nodes decommissioning test

src/v/bytes/iobuf.h
Have prepend_take_ownership mirror the append variant.
* none
=> iobuf: use unique_ptr<fragment> instead of new-allocation

tests/rptest/util.py
This replaces the previous non-fixing fix in a4d9e4fcdc7a22d193c818cc071df7f18f50b01e
* none
=> test: fix zero segments handling in wait_for_local_storage_truncate

src/v/archival/ntp_archiver_service.cc, src/v/cloud_storage/async_manifest_view.cc, src/v/cloud_storage/cache_probe.cc, src/v/cloud_storage/cache_probe.h, src/v/cloud_storage/cache_service.cc, src/v/cloud_storage/cache_service.h, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment.h, src/v/cloud_storage/tests/async_manifest_view_test.cc, src/v/cloud_storage/tests/cache_test.cc, src/v/cloud_storage/tests/cache_test_fixture.h, src/v/cloud_storage/tests/cloud_storage_fixture.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/admin/api-doc/debug.json, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h, src/v/redpanda/application.cc, tests/rptest/scale_tests/many_partitions_test.py, tests/rptest/scale_tests/tiered_storage_cache_stress_test.py, tests/rptest/scale_tests/tiered_storage_single_partition_test.py, tests/rptest/services/kgo_verifier_services.py, tests/rptest/services/redpanda.py, tests/rptest/services/storage.py, tests/rptest/tests/cloud_storage_chunk_read_path_test.py, tests/rptest/tests/node_id_assignment_test.py, tests/rptest/tests/rpk_start_test.py, tests/rptest/tests/services_self_test.py
- Cache size is now limited by object count, as well as byte count, to avoid issues where many small objects stress the metadata/trimming code
- A new test validates that a read workload reading data much beyond the cache size proceeds with good performance as long as the cache is large enough that trimming 20% every 5 seconds enables the reader to proceed.  This will cache any "stutters" in the cache management, or issues with prompt trimming.
- ENOSPC errors in cache ::put are handled explicitly by blocking writes and immediately trimming.
- The reservation mechanism is revised to require all put() calls to provide a reservation, and to release reserved capacity atomically at the same time as the actual used capacity is updated at the end of a put.
- When a cache trim has failed to free …
=> cloud_storage: further cache improvements

src/v/archival/ntp_archiver_service.cc, src/v/archival/retention_calculator.cc, src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/partition_manifest.h, src/v/cluster/archival_metadata_stm.cc, src/v/cluster/partition.cc, src/v/cluster/types.h, src/v/redpanda/admin/api-doc/shadow_indexing.json, src/v/redpanda/admin_server.cc, tests/rptest/services/redpanda.py, tests/rptest/tests/cloud_retention_test.py, tests/rptest/tests/cloud_storage_timing_stress_test.py, tests/rptest/tests/cloud_storage_usage_test.py, tests/rptest/tests/cluster_config_test.py, tests/rptest/tests/e2e_shadow_indexing_test.py, tests/rptest/tests/retention_policy_test.py, tests/rptest/tests/topic_delete_test.py, tests/rptest/tests/usage_test.py, tests/rptest/utils/si_utils.py
The main goal of this PR is to add spillover operations to CloudStorageTimingStressTest.
A couple other things had to be changed:
* cloud storage status endpoint became spillover aware
* cloud log size utilities became spillover aware  
Also picked up a little fix to the snapshot logic (archive size was not included).
Maybe these tests should perform a read from snapshot somehow.
* none
=> cloud_storage: perform spillovers in cloud timing stress tests

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/application.cc, src/v/resource_mgmt/storage.cc, src/v/resource_mgmt/storage.h, src/v/storage/api.cc, src/v/storage/api.h, src/v/storage/disk_log_impl.cc, src/v/storage/disk_log_impl.h, src/v/storage/log_manager.cc, src/v/storage/log_manager.h, tests/rptest/tests/full_disk_test.py
Adds a log storage monitor / control loop whose goal is to enforce the target usage size of log storage.
This PR adds a greedy approach to reclaiming cloud-uploaded data by violating local retention policies in an effort to meet the target storage limit.
* none
=> storage: add greedy log storage target size control loop monitor

tests/rptest/scale_tests/high_throughput_test.py, tests/rptest/services/redpanda.py
Tier name is supplied via `cloud_tier` ducktape global. It is also possible to define more tier configurations in addition to the cloud ones. One such noncloud tier is defined here as a `docker-local`. More tiers can be defined for e.g. CDT.
Re #9491
* none
=> A simple throughput test that uses cloud tier configurations

src/v/cluster/partition_balancer_planner.cc
This particular map can get large-ish with lots of partitions. Switch to btree_map as this is not a hot-path.
Fixes #11677
* none
=> pb/planner: switch _ntp2size to absl::btree_map

src/v/cluster/persisted_stm.cc, src/v/storage/disk_log_impl.cc, src/v/storage/disk_log_impl.h, src/v/storage/log.h, src/v/storage/tests/storage_e2e_test.cc, src/v/storage/types.cc, src/v/storage/types.h
This PR removes the calculation of `last_term_start_offset` from  `storage::log::offsets()` and adds a separate function to calculate it. 
This value is only ever used in `persisted_stm` on term changes. And the `storage::log::offsets` function that calculates it often shows up on `perf top` and is on the produce path. This PR reduces the time complexity of the function from being linear to the number of segments since term start to being constant in most cases.
Additionally this PR is the first of likely a few to reduce reactor utilization when partitions have many segments. I.e,
Reactor utilization vs number of 128MiB segments on a 500MB/s produce/consume OMB test;
Reactor utilization vs number of 3GiB segments on the same OMB test;
* none
=> Remove `last_term_start_offset` from `storage::offset_stats`

.github/workflows/scripts/backport-command/create_pr.sh
Previously `Fixes` section was missing a colon, without it the issue isn't automatically closed by github when PR is merged.
- none
=> github/backport: fixed backport pr and issue link

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/net/server.cc, src/v/net/server.h, src/v/redpanda/application.cc, tests/rptest/tests/tcp_keepalive_test.py
We have seen RP "leak" client connections in different scenarios ([1] [2]).
One of those cases is when running in cloudv2 on AWS. The inuse AWS
load balancer which distributes bootstrap server connections to all
brokers "drops" connections after 350s. This means that when the
client eventually disconnects the LB doesn't forward the RST/FIN to the
RP brokers anymore. As a result RP thinks those connections are still
going. Scenarios where nodes/VMs just crash result in similar scenarios.
Redpanda right now doesn't have something like an application level
"connection reaper" that closes inactive connections.
However, the issue above eventually gets resolved by TCP keepalive. We
do already enable TCP keepalive but don't specify any of the parameters
explicitly which means we use the linux …
=> net: Explicitly set and reduce TCP keepalive on the kafka API

src/v/kafka/server/fetch_session.h, src/v/kafka/server/handlers/fetch.cc, tests/rptest/services/kafka_cli_consumer.py, tests/rptest/tests/consumer_group_balancing_test.py, tests/rptest/tests/consumer_group_test.py, tests/rptest/tests/follower_fetching_test.py
If partition contain information about preferred replica it MUST be
included in incremental fetch response. Otherwise a client would
indefinitely retry asking leader about preferred replica and
stop making progress.
Fixes: #11767 
- fixed not being able to clear consumer backlog when using incremental fetch requests and follower fetching
- fixed returning read replica that may be unavailable from replica selector
=> Fixed inter-operation between follower fetching and incremental fetch requests

cmake/oss.cmake.in, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/admin/api-doc/debug.json, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h, src/v/redpanda/application.cc, src/v/redpanda/application.h, src/v/resource_mgmt/CMakeLists.txt, src/v/resource_mgmt/cpu_profiler.cc, src/v/resource_mgmt/cpu_profiler.h, src/v/resource_mgmt/logger.cc, src/v/resource_mgmt/logger.h, src/v/resource_mgmt/tests/CMakeLists.txt, src/v/resource_mgmt/tests/cpu_profiler_test.cc, tests/rptest/services/admin.py, tests/rptest/tests/cpu_profiler_admin_api_test.py
An integration of the seastar CPU profiler PR [here](https://github.com/redpanda-data/seastar/pull/48) into Redpanda. This PR provides a service that controls and polls samples from the seastar CPU profilers. It also provides an admin api endpoint the returns samples in the following json format;
```json
[
{
"shard_id": 0, 
"user_backtrace": "0x687335a 0x65d4cf5 /lib64/libc.so.6+0x3cb1f /home/brandonallard/data/projects/redpanda-3/vbuild/release/clang/rp_deps_install/lib/libc++.so.1+0x51764 0  x65f9da0 0x65f6d49 0x6507d61 0x6505e7f 0x2099d2e 0x6929979 /lib64/libc.so.6+0x2750f /lib64/libc.so.6+0x275c8 0x2094124",
"occurrences": 1
},
...
]                                                 
```
The build will fail until the seastar PR is merged and vtools is updated.
* Adds a built-in CPU …
=> Integrate a CPU profiler into RP

src/v/resource_mgmt/storage.cc, src/v/storage/disk_log_impl.cc, tests/rptest/tests/full_disk_test.py
* Improves logging
* Fixed a bug causing reclaim to run slower than expected
* Decreased control loop frequency which was low because of said bug
* Tighten up the test timeout which was also high because of the bug
* none
=> [storage] space management bug fixes and logging improvements

src/v/archival/ntp_archiver_service.cc, src/v/archival/tests/service_fixture.cc, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment_index.cc, src/v/cloud_storage/remote_segment_index.h, src/v/cloud_storage/tests/remote_segment_index_test.cc, src/v/cloud_storage/tests/remote_segment_test.cc
Previoiusly, the set of batch types for offset translation was hardcoded in the index builder code. This commit fixes this by using function that returns list of record batch types that participate in offset translation.
* none
=> cloud_storage: Fix remote segment index generation

src/v/archival/ntp_archiver_service.cc, src/v/cluster/archival_metadata_stm.cc, src/v/cluster/archival_metadata_stm.h, src/v/storage/disk_log_impl.cc, src/v/storage/ntp_config.h, tests/rptest/tests/read_replica_e2e_test.py
Rather than add more complexity to try and synchronize the manifest incrementally, just change how it works to do a total replacement of the manifest each time we download it.  Now that manifests are in an efficient binary encoding, the size of the resulting raft writes are bounded (or they will be, once spilling is on by default).
~TODO:~
* none
=> cloud_storage: revise read replica sync to work with spilled metadata

src/v/model/async_adl_serde.cc, src/v/model/async_adl_serde.h, src/v/model/record.h, src/v/reflection/async_adl.h, src/v/storage/kvstore.cc, src/v/storage/kvstore.h
Backports:
* #5129
* #10953
* Reduced latency impact from storing metadata in certain scenarios where the number of partitions per shard is high
=> [v23.1.x] storage: use async serialization for large kvstore snapshot batches

tests/rptest/clients/rpk.py, tests/rptest/services/redpanda.py, tests/rptest/services/redpanda_installer.py, tests/rptest/services/workload_protocol.py, tests/rptest/tests/redpanda_test.py, tests/rptest/tests/workload_dummy.py, tests/rptest/tests/workload_license.py, tests/rptest/tests/workload_producer_consumer.py, tests/rptest/tests/workload_upgrade_runner_test.py
A framework to execute tests on a sequence of redpanda versions, composed of 2 components:
- PWorkload, an interface to implement
- RedpandaUpgradeTest, a test that runs a collection of PWorkloads through a cluster while upgrading it
A Workload can implement PWorkload, spin up an external producer/consumer, and check progress on the external service in a stable and upgrading cluster.
Workloads run in parallel, so care should be taken not to disrupt other workloads, like changing cluster properties or removing nodes. 
Various tests implementing a upgrading+testing pattern can be moved to this test to reduce the number of tests and total ci execution time while doing a more rigorous test.
Fixes https://github.com/redpanda-data/redpanda/issues/7310
* none
=> Ducktape test to execute workloads through multi-release upgrades

src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment.h, src/v/cloud_storage/segment_chunk_api.cc, src/v/cloud_storage/segment_chunk_api.h, src/v/cloud_storage/segment_chunk_data_source.cc, src/v/cloud_storage/segment_chunk_data_source.h, src/v/cloud_storage/tests/remote_segment_test.cc, src/v/cloud_storage/tests/segment_chunk_test.cc, src/v/config/configuration.cc, src/v/config/configuration.h, tests/rptest/tests/cloud_storage_chunk_read_path_test.py
Chunk prefetching allows fetching more than one segment chunks at once for performance improvement. The http call to fetch data includes a single byte range covering the original chunk plus the prefetch, and the response is written to disk as individual chunk files. 
**Note on potential inefficiency/wasted effort:** With these changes, consider a set of contiguous chunks A,B,C,D,E,F. With a prefetch of 4, when A is downloaded, B,C,D,E are also downloaded. These are not however hydrated or materialized. The chunk files are kept on disk. When/if a request for hydrating B is issued, if it is still on disk, it is directly materialized. If not, it is re-downloaded and then materialized. In the event that B is deleted for some reason (cache eviction) and C,D,E are still on disk, when B is …
=> cloud_storage: enable prefetching chunks

src/v/cluster/topics_frontend.cc, tests/rptest/tests/read_replica_e2e_test.py
We would previously crash by referencing _cloud_storage_api.local() without checking that it was initialized.
* Avoids a crash when attempting to create a read replica topic while cloud storage is not configured.
=> cluster: reject read replica creation when no cloud

tests/rptest/tests/full_disk_test.py
Faster, better, stronger with kgo producer service. In reality, there are some known issues with the kafka cli producer and it's better to gather around a good tool for this type of test requirement.
This commit also parameterizes the test for more flexible configuration but otherwise keeps the same test goal / structure.
* none
=> test: improve and generalize the log storage target size test

tests/docker/cdt_ducktape_deps.sh
install-deps is currently part of the vtools repo [ref](https://github.com/redpanda-data/vtools/blob/1242110a01b367707e2a92b516bab83bf09db501/qa/image/packer/install-deps.sh). CDT is designed to always run tip of vtools dev.
This causes issues when for example a dt dependency exists in redpanda `dev` branch, and not in `v22.3.x` branch. Once we teach install-deps of vtools/dev
to install a ducktape dependency, then it'll expect the same dependency file in all cdt runs, including older branches.
To avoid that, the install-deps should follow the redpanda ducktape dependencies per branch. Additionally, developers could modify/add a ducktape dependency and update cdt at once
ref #redpanda-data/devprod#741
Another PR on vtools will be introduced
* none
=> add cdt script to install dt deps on cdt infra

tests/rptest/services/cluster.py, tests/rptest/tests/delete_records_test.py
After some investigation it was observed that this test was failing because it had generated a situation in which orphaned segments could occur, and the logic to determine PASS/FAIL determined on counting the number of observed segments and comparing to an expected value.
Segment(s) were being orphaned because this test injects a failure right around the time of log truncation. Redpanda does handle orphaned segments, but only invokes this recovery when replaying cluster deletion events, whereas the log truncation in this case arose from retention logic.
The fix includes a change to turn off the check for storage usage inconsistent es (conditionally for this test alone) for now and avoid comparing results of the node that has been killed to an expected value. Once a solution for orphaned …
=> Fix for `DeleteRecordsTest.test_delete_records_segment_deletion` failures

src/v/archival/ntp_archiver_service.cc, src/v/archival/tests/archival_metadata_stm_test.cc, src/v/archival/tests/ntp_archiver_test.cc, src/v/cloud_storage/async_manifest_view.cc, src/v/cloud_storage/async_manifest_view.h, src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/tests/async_manifest_view_test.cc, src/v/cloud_storage/tests/remote_partition_fuzz_test.cc, src/v/random/generators.h, tests/rptest/utils/si_utils.py
This PR fixes a number of issues with retention within the archive.
I've tested this with a custom version of CloudArchiveRetentionTest which asserts that
the precise number of segments was deleted. That requires a kgo-verfier patch and some
further fixes, so it'll come as a separate PR.
Firstly, the archive start and clean offsets are reset when retention has removed the entire archive.
This allows the retention in the STM region to proceed. The list of spillover manifests is also truncated
when the clean offset is advanced.
Secondly, fixes are included for the truncation point search for retention within the archive:
Incorrect truncation point search for size based retention. Cosider the example below:
```
A      B C      D E      F G      H
[------] [------] [------] [------] ....
10B …
```
=> cloud_storage: allow STM retention to proceed and more archive retention fixes

src/v/cluster/topics_frontend.cc, tests/rptest/tests/read_replica_e2e_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11792
=> [v23.1.x] cluster: reject read replica creation when no cloud

src/v/cluster/topics_frontend.cc, tests/rptest/tests/read_replica_e2e_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11792
=> [v22.3.x] cluster: reject read replica creation when no cloud

src/v/cluster/controller.cc, src/v/cluster/health_manager.cc, src/v/cluster/members_backend.cc, src/v/cluster/partition_balancer_planner.cc, src/v/cluster/scheduling/allocation_node.cc, src/v/cluster/scheduling/allocation_node.h, src/v/cluster/scheduling/allocation_state.cc, src/v/cluster/scheduling/allocation_state.h, src/v/cluster/scheduling/allocation_strategy.cc, src/v/cluster/scheduling/allocation_strategy.h, src/v/cluster/scheduling/constraints.cc, src/v/cluster/scheduling/constraints.h, src/v/cluster/scheduling/partition_allocator.cc, src/v/cluster/scheduling/partition_allocator.h, src/v/cluster/scheduling/types.cc, src/v/cluster/scheduling/types.h, src/v/cluster/tests/partition_allocator_fixture.h, src/v/cluster/tests/partition_allocator_tests.cc, src/v/cluster/tests/partition_balancer_planner_fixture.h, src/v/cluster/tests/partition_balancer_simulator_test.cc, src/v/cluster/tests/topic_table_fixture.h, src/v/cluster/topics_frontend.cc
Internal topics are now excluded from partition allocator limit checks. This means that a given allocation node can host any number of such internal topic partitions. A topic is considered internal in the following cases:
- It belongs to `redpanda` or `kafka_internal` namespaces or
- It belongs to `kafka` namespace but included in `kafka_nodelete_topics`
The rationale for do so is that these topics can potentially be created lazily, for example transactions related topics are created when a user uses transactions for the first time. This could be problematic if the user has already exhausted `topic_partitions_per_shard` limits and the creation of these internal topics just hangs. To avoid such scenarios we exclude these internal topics from limit checks. This should not be problematic in …
=> partition_allocator: exclude internal topics from per node partition limit checks

src/v/archival/ntp_archiver_service.cc, tests/rptest/scale_tests/tiered_storage_cache_stress_test.py, tests/rptest/scale_tests/tiered_storage_single_partition_test.py, tests/rptest/services/redpanda.py
This shook out a small change to the archiver to avoid doing unnecessary manifest uploads when applying archive GC.
It also includes a change to configure the tiered storage cache large enough for the end-of-test consume to proceed promptly when running on a workstation.
* none
=> tests: use spillover in `TieredStorageSinglePartitionTest`

tests/rptest/services/redpanda.py, tests/rptest/util.py
For unknown reasons, `du` is failing sometimes when run concurrently with tiered storage reads.
In the contexts where it is used mid-test, we generally do not care about cache sizes, so just avoid doing the check.
Also fix these remote command executions to separate stderr from stdout, so that if they do fail we get a more descriptive error.  Issue https://github.com/redpanda-data/redpanda/issues/11665 also had one of these enigmatic remote command failures where we can't see stderr.
Fixes: https://github.com/redpanda-data/redpanda/issues/11815
* none
=> tests: avoid unnecessary `du` calls on cache dir

src/v/cloud_storage/cache_service.cc
Where reserved is same order of magnitude as
total cache size, we must include it in our
pre-check for whether to trim at all.
This the same issue that
9f05d78eccec0689565d511cfd6f91d5d5c706db
was addressing: it should have been changed
in that commit.
Fixes https://github.com/redpanda-data/redpanda/issues/11819
* none
=> cloud_storage: fix a trim bug on small caches

src/v/storage/record_batch_builder.cc, src/v/storage/record_batch_builder.h
Some uses of `record_batch_builder` build very large batches, resulting in oversize allocations in `std::vector _records`.
Remove the `std::vector` by serializing into an `iobuf` at the point of `add_raw_kv`. This requires storing an `int32_t` for the record count.
Fixes https://github.com/redpanda-data/redpanda/issues/10749
Related to #11809 
* Avoid large allocation when storing metadata in certain scenarios where the number of partitions per shard is high
=> storage/record_batch_builder: Avoid intermediate `std::vector`

src/v/storage/record_batch_builder.cc, src/v/storage/record_batch_builder.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/11837
Fixes: https://github.com/redpanda-data/redpanda/issues/11853,
=> [v23.1.x] storage/record_batch_builder: Avoid intermediate `std::vector`

tests/rptest/tests/delete_records_test.py
This test did not account for the case where a storage segment object has no data_file.
Example failure: https://buildkite.com/redpanda/redpanda/builds/32439#01891df7-b751-49dc-afa0-d0c07cf7a46e
* none
=> tests: fix AttributeError in delete_records_test

tests/rptest/tests/cpu_profiler_admin_api_test.py
Fixes https://github.com/redpanda-data/redpanda/issues/11790
* none
=> tests: skip debug mode on test_get_cpu_profile

src/v/cluster/rm_stm.cc, src/v/raft/state_machine.cc, src/v/raft/state_machine.h
- This change reverts a previous attempt to fix rm_stm reporting invalid_lso (in change 20285dff0f35f07c9b30dbcb5a79907e9696f714), which sets `booststrap_committed_offset` in apply_snapshot() to fix the case where invalid_lso is indefinitely returned on a node that had just restarted, applied a snapshot, but no data was produced onto it.
- The change was however incorrect, as the bootstrap committed offset is expected to be the value of a complete read of the log, and the value of the offset in the rm_stm snapshot at the time of reading it at startup, does not necessarily reflect this.
- The solution is to at startup wait until the consensus later has modified the committed offset.
* none
=> cluster: Fix for incorrect end_offset reported

src/v/cloud_storage/async_manifest_view.cc, src/v/cloud_storage/async_manifest_view.h, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/tests/async_manifest_view_test.cc, src/v/kafka/server/replicated_partition.cc
This PR fixes a few issues with the handling of OffsetForLeaderEpoch in the cloud log.
The issues manifested in https://github.com/redpanda-data/redpanda/pull/11759 as a stuck consumer.
The following issue is fixed and unit tests are introduced for it:
```
Consider the example below:
[--------]  [--------]
^           ^    ^
Term:   T1          T1   T2
Offset: A           B  X C
^
|________ _archive_start_offset
Previously, when looking for the last offset in T1, we'd correctly pick
the second spillover manifest in the diagram and we would attempt to
create a cursor starting at B (i.e. the start of the selected spill
manifest). This request is not fulfilled as the cursor refuses to answer
queries below the archive start offset. The fix here, is to init the
cursor with the start offset of …
```
=> cloud_storage: fix OffsetForLeaderEpoch when it lands in the cloud log

tests/rptest/tests/delete_records_test.py
This was broken in 0570d19d6225ea59e79e197dca2d96ed72f3aa9c
Fixes https://github.com/redpanda-data/redpanda/issues/11871
* none
=> tests: fix test_delete_records_segment_deletion

tests/docker/ducktape-deps/kaf
This avoid a build error with the latest version
Commit https://github.com/redpanda-data/redpanda/commit/e9315cecd927204000b879951cfe22461ce6f670 changed this to not have a specific version.
Fixes #11882
* none
=> v22.2.x: Downgrade kaf to v0.2.3

src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/model/record.h, tests/rptest/tests/transactions_test.py
Changed the way how expired producer ids are cleaned up in `rm_stm`. Previously an `rm_stm` was incorrectly using the `transactional.ix.expiration.ms` to expire producer ids. Changed the producer id expiration timeout to be separate property and aligned it with Kafka behavior. 
Fixes: https://github.com/redpanda-data/core-internal/issues/640
- fixed `rm_stm` resource leak
=> Improved `rm_stm` resource management.

src/v/net/server.cc
net::server objects are at the core of the wire layer for Redpanda, so let's log key information about server objects when they are created.
This also fills out operator<< for the server configuration object to include most fields as it was pretty threadbare before.
Issue redpanda-data/core-internal#472.
* none
=> Logging at server creation

tools/offline_log_viewer/controller.py, tools/offline_log_viewer/viewer.py
Using python generator to decode controller log prevents reading the whole log to memory, this way it is possible to process very large controller logs with offline metadata viewer tool.
- none
=> Use python generator to read controller log

tests/rptest/services/redpanda.py
The previous 160MB/s default was only enough for
about 6MB/s of streaming throughput: this made some tests run more slowly than they should.
It also made many tests act as unrealistic torture tests for the cache, which is a distraction from
their actual purpose.
The coverage for teeny tiny caches will be re-added in https://github.com/redpanda-data/redpanda/issues/11835
* none
=> tests: revise default cache size for testing

tests/rptest/tests/nodes_decommissioning_test.py
In current redpanda version node ids are dynamically assigned we can not use a node id as an index in the `RedpandaService` nodes list as it may result in incorrect results. In this particular example a node that was stopped was not the one that was decommissioned, leading to some of the rf=1 partitions being not available which prevented test from finishing.
Fixes: #11751
- none
=> Fixed querying for the node in decommission test

tests/docker/ducktape-deps/kgo-verifier, tests/rptest/services/kgo_verifier_services.py, tests/rptest/services/redpanda.py, tests/rptest/tests/cloud_storage_timing_stress_test.py
Based on https://github.com/redpanda-data/redpanda/pull/11846 
Previously, whenever a KgoVerifierSequentialConsumer and a
KgoVerifierProducer ran in parallel (which a number of tests do), there
was no guarantee that the consumer would read all partitions entirely.
Whenever `wait` is called on the consumer, the `last_pass` command is
triggered without taking into account if the producer has completed.
This is problematic because it can hide stuck consumer issues. This
patch makes use of the enhanced kgo-verifier status which now contains
the high watermark for each partition. When creating a sequential
consumer, a reference to the producer can be provided. If that was the
case, when `wait` is called on the consumer we will wait until the
producer has finished and the high watermarks match. …
=> rptest: perform full log reads with KgoVerifierSeqConsumer

src/v/redpanda/admin_server.cc
Avoid oversized allocation by:
* Collecting summaries into a `fragmented_vector`
* Streaming the vector to an `ss::output_stream`
The overload of `ss::json::json_return_type` that provides an `ss::output_stream` requires a `std::function`, which is required to be copyable, so wrap the `fragmented_vector` in a simple container wrapper that holds the container by `ss::lw_shared_ptr`.
Another optimisation is moving rather than copying during accumulation.
Fixes #11674
* admin_server/get_partition: Avoid oversized allocation
=> admin_server/get_partition: Avoid oversized allocation

src/go/rpk/pkg/cli/cluster/logdirs.go, src/go/rpk/pkg/cli/group/offset_delete.go, src/go/rpk/pkg/cli/topic/consume.go
Fixes a few bugs noticed while working on other things (so, not user reported). The offset-delete bugs are more important and exist in 23.1, so this should be backported. The logdirs panic is hard to hit (only encountered if the RP request fails) but is also worth backporting. The consume bug is just a display printing bug (errors are collapsed into one line).
* `rpk group offset-delete` no longer tries to delete offsets for all topics if no empty topics are specified
* `rpk group offset-delete` no longer tries to delete offsets for empty-name topics
* `rpk cluster logdirs` no longer panics if there is an error getting a response from Redpanda
=> rpk: fix a few minor bugs

src/v/archival/tests/ntp_archiver_test.cc, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment_index.cc, src/v/cloud_storage/remote_segment_index.h, src/v/cloud_storage/tests/common_def.h, src/v/model/record.h, src/v/storage/kvstore.cc, src/v/storage/kvstore.h, src/v/storage/log_reader.cc, src/v/storage/log_reader.h, src/v/storage/log_replayer.cc, src/v/storage/parser.cc, src/v/storage/parser.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/11809
=> [v23.1.x] storage: `maybe_yield` when building a batch in `kvstore::save_snapshot`

src/v/cluster/log_eviction_stm.cc, tests/rptest/clients/kcl.py, tests/rptest/services/admin_ops_fuzzer.py, tests/rptest/tests/delete_records_test.py
This PR will add delete-records to the set of supported admin ops commands that will be used in tests that invoke the admin ops fuzzer.
* none
=> Add support for delete-records to the admin ops fuzzer

src/v/redpanda/admin_server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11824
Fixes #11924 
Conflicts:
src/v/redpanda/admin_server.cc
Due to 2cc38ee1a68282dd7a0966961ad64a3bc229963c
I took the opportunity to extract `reduce` and reuse it.
* admin_server/get_partition: Avoid oversized allocation
=> [v23.1.x] admin_server/get_partition: Avoid oversized allocation

src/go/rpk/pkg/cli/cmd/cluster/logdirs.go, src/go/rpk/pkg/cli/cmd/group/offset_delete.go, src/go/rpk/pkg/cli/cmd/topic/consume.go
This is a manual backport of #11900
Fixes a few bugs noticed while working on other things (so, not user reported). The offset-delete bugs are more important and exist in 23.1, so this should be backported. The logdirs panic is hard to hit (only encountered if the RP request fails) but is also worth backporting. The consume bug is just a display printing bug (errors are collapsed into one line).
* `rpk group offset-delete` no longer tries to delete offsets for all topics if no empty topics are specified
* `rpk group offset-delete` no longer tries to delete offsets for empty-name topics
* `rpk cluster logdirs` no longer panics if there is an error getting a response from Redpanda
=> v23.1.x: rpk minor bugs

src/v/cloud_storage/cache_service.cc, src/v/cloud_storage/cache_service.h, src/v/cloud_storage_clients/util.cc, tests/docker/docker-compose.yml, tests/rptest/scale_tests/tiered_storage_cache_stress_test.py, tests/rptest/services/redpanda.py
This fixes cases where the primary trim doesn't clear up .tx and .index files, when there is no chunk/segment file for the segment.
Rather than make the existing trim slower by having it consider all files individually, the existing trim behavior is retained in `trim_fast()`, and a `trim_exhaustive()` function is introduced to do a more expensive "inspect every file" trim.  This can clean up:
- .tx and .index files where there is no corresponding data file
- Abandoned .part files (which shouldn't exist, but could if there is a bug in the download path)
- Any other files in the cache directory, e.g. if a user mistakenly put some files in here, or if there were files from an old Redpanda version that we no longer use/need.
Note that the trim still only happens when it is necessary to enable …
=> cloud_storage: more exhaustive cache trim when fast trim doesn't free enough space

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/net/server.cc, src/v/net/server.h, src/v/redpanda/application.cc, tests/rptest/tests/tcp_keepalive_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11496
=> [v23.1.x] net: Explicitly set and reduce TCP keepalive on the kafka API

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/net/server.cc, src/v/net/server.h, src/v/redpanda/application.cc, tests/rptest/tests/tcp_keepalive_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11496
=> [v22.3.x] net: Explicitly set and reduce TCP keepalive on the kafka API

src/v/cloud_storage/remote.h, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_partition.h, src/v/cluster/partition.cc
Previously, any blocking of the remote storage requests involved in doing the final upload of metadata would result in stalling the controller's backend loop, stopping unrelated actions such as topic creations from proceeding.
While issues with timeouts on remote requests should also be resolved, we can change the structure of this to avoid the risk of any remote storage issues causing controller-wide stalls, by bundling up the state required for finalize, and copying it into a background fiber so that teardown of remote_partition can proceed unimpeded.
Fixes https://github.com/redpanda-data/redpanda/issues/11863
* none
=> cloud_storage: run partition finalize in background

src/v/cloud_storage/cache_service.cc, src/v/cloud_storage_clients/s3_client.cc
This is a response to issues seen in manual testing:
-  S3 client warnings don't say the response code or the request type
- Cache "failed to trim" lines don't mention object counts
* none
=> cloud_storage: logging improvements

src/v/storage/disk_log_impl.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11681
Fixes https://github.com/redpanda-data/redpanda/issues/11717,
=> [v23.1.x] storage: make `compaction_backlog` more efficient for large segment counts

src/go/rpk/pkg/cli/topic/consume.go, src/go/rpk/pkg/cli/topic/consume_test.go, src/go/rpk/pkg/cli/topic/topic.go, src/go/rpk/pkg/cli/topic/trim.go, src/go/rpk/pkg/cli/topic/trim_test.go, tests/rptest/clients/rpk.py, tests/rptest/tests/delete_records_test.py
This PR introduces the new command `rpk topic trim-prefix` that supports the DeleteRecords admin request
Fixes #11781
**Full Help Text**
```
$ rpk topic trim-prefix --help
Trim records from topics
This command allows you to trim records from topics, to trim the topics Redpanda
sets the LogStartOffset for partitions to the requested offset. All segments 
whose max partition is before the requested offset are deleted, and any records 
within the segment before the requested offset can no longer be read.
The --offset/-o flag allows you to indicate which index you want to set the 
partition's low watermark (start offset) to. It can be a single integer value 
denoting the offset or a timestamp if you prefix the offset with an '@'. You may
select which partition you want to trim the offset from …
```
=> rpk: add `rpk topic trim-prefix` (support for DeleteRecords)

src/v/cluster/security_manager.cc, src/v/pandaproxy/schema_registry/service.cc, src/v/pandaproxy/schema_registry/service.h, tests/rptest/tests/schema_registry_test.py
Previously, two things were occurring in Redpanda:
1. The call to create ACLs in schema registry startup could fail
2. The `security_manager` was storing ephemeral credentials in controller snapshots
Point (1) is a problem because the ephemeral principal needs all permissions on the `_schemas` topic. The solution is to automatically retry the create ACLs request until success with a small backoff. Point (2) is a problem because, upon controller log replay, RP would re-populate the credential store with a credential that has the ephemeral username (a random string) but no principal. This would lead to authorization failures because [this line](https://github.com/redpanda-data/redpanda/blob/b9fbd636a5699175ec7169107ca42aa05c9a02b7/src/v/security/scram_authenticator.cc#L34-L35) in …
=> sr: retry create ACLs for the ephemeral principal

src/v/cluster/health_monitor_backend.cc
It is convenient if the node IDs are sorted in the node health report.
This change sorts the "all nodes" and "nodes down" lists.
* none
=> Sort nodes in health report

src/v/archival/upload_housekeeping_service.cc
When idle timeout changes, the timer may already be armed. rearm it instead of arming it to avoid an assertion.
Fixes #11938
* none
=> archival/idle_timer: avoid arming an armed timer

src/go/rpk/pkg/cli/redpanda/admin/brokers/decommission.go, src/go/rpk/pkg/cli/topic/trim.go
This PR:
- Adds a new line in an rpk decommission command.
- Improve error handling for non-existent topics.
- Exit 1 if there was at least an error in the topics that you tried to trim.
* none
=> rpk: small improvements for rpk-trim

tests/rptest/clients/kcl.py, tests/rptest/services/admin_ops_fuzzer.py, tests/rptest/tests/controller_upgrade_test.py
The major change is to move to Rpk::delete_records() as this throws on any command errors which triggers retry logic in the main admin ops fuzzer harness.
* none
=> Fixes for AdminOpsFuzzer failures related to delete-records

tests/rptest/tests/delete_records_test.py, tests/rptest/tests/e2e_shadow_indexing_test.py, tests/rptest/tests/read_replica_e2e_test.py
PR https://github.com/redpanda-data/redpanda/pull/11957 introduced a behavior change in how rpk topic trim handles on observed errors. It now returns a processes exit code of 1 if there is any failure detected. This change is making the ducktape Rpk client throw on errors which is making some tests that expect failures actually fail.
This PR also includes a fix for another error which was making the read replica delete records test fail. That test invoked KCL::DeleteRecords which was deprecated without updating that test to use the Rpk tools version of the same command. 
* none
=> Fix for delete-records tests that don't handle RpkExceptions 

src/v/cloud_storage/async_manifest_view.cc
.. and log with lower severity. Log suggest it happened during ntp shutdown.
Fixes: #11782
* none
=> archival: handle gate closed exception

src/v/kafka/server/replicated_partition.cc, src/v/kafka/server/replicated_partition.h, tests/rptest/tests/log_segment_ms_test.py
In Kafka the semantics of `log_end_offset` is defined as a next offset assigned to a record produced to a given partition.
When local log is empty its `dirty_offset` is equal to `start_offset - 1`. In this case a `log_end_offset` should return Kafka offset corresponding to the `start_offset` as this is the next offset assigned to a record produced to given topic partition.
Fixes: #11403 
- gracefully handles listing offsets and fetching from a completely empty log
=> Fixed returning `log_end_offset` for empty local logs

src/v/cloud_storage/materialized_resources.cc, src/v/cloud_storage/materialized_resources.h, src/v/cloud_storage/probe.cc, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_partition.h, src/v/cloud_storage/segment_state.cc, src/v/utils/adjustable_semaphore.h, tests/rptest/scale_tests/many_partitions_test.py, tests/rptest/scale_tests/tiered_storage_reader_stress_test.py, tests/rptest/services/kgo_verifier_services.py
Previously, our reader concurrency limit applied to segment readers rather than partition readers, and it was a soft limit: it governed trimming behavior, but trimming could only happen if the segment readers weren't actively in use.  Therefore if clients deluged a server with tiered storage read requests (which can be done quite cheaply with time queries), they could create very large numbers of concurrent segment readers.
This is bad because we can OOM (and the new test does indeed OOM without the new limiting in this PR), but also because it leads to splitting available disk bandwidth very widely between all those readers, meaning that each one might well be too slow to complete quickly enough for a client's timeout.
That bad situation is compounded by lack of cancellation of requests …
=> cloud_storage: add TieredStorageReaderStressTest & strictly limit reader concurrency

src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/partition_manifest.h
`kafka::replicated_partition::start_offset` is called often on the fetch path. And when cloud storage is enabled for a partition this leads to a find operation on `segment_meta_cstore` for every call.
The result of this find doesn't change unless `_start_offset` in `cloud_storage::partition_manifest` has changed. So this commit caches the result of the find and updates it whenever `_start_offset` changes.
Partially fixes #11952 
* none
=> Cache values computed in `partition_manifest::full_log_start_kafka_offset`

src/v/cluster/archival_metadata_stm.cc, src/v/cluster/archival_metadata_stm.h, src/v/cluster/id_allocator_stm.cc, src/v/cluster/id_allocator_stm.h, src/v/cluster/log_eviction_stm.cc, src/v/cluster/log_eviction_stm.h, src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h, src/v/cluster/tm_stm.cc, src/v/cluster/tm_stm.h, src/v/raft/consensus.cc, src/v/raft/mux_state_machine.h, src/v/raft/state_machine.cc, src/v/raft/state_machine.h
Since Redpanda stms are using the Raft protocol semantics we must adhere to the same semantics even when using `acks=1` or `acks=0`. This PR protects the STM from reading beyond the `raft::committed_offset()`. Previously it was possible for the STM to read up to visible index. 
- fixed stms interoperation with relaxed consistency semantics
=> Fixed applying messages to stm when using `acks=0` or `acks=1`

tests/rptest/tests/controller_erase_test.py
Wait for all victim node records to be applied. If a victim node contains some of the records that were not applied or about to be truncated the test should wait before selecting segments to trim as in the case if segment contains only dirty records removing it will not cause inconsistency.
Fixes: #8217
- none
=> More strict `last_applied_offset` check

src/v/kafka/server/replicated_partition.h
Some of the error codes are not supported in certain type of Kafka responses. One of such situations is returning a timeout error in Fetch response. This cause client to throw `IvalidStateException` and stop consuming.
Fixes: #8688
- none
=> Do not return timeout error in fetch response

src/v/archival/ntp_archiver_service.cc, tests/rptest/services/kgo_verifier_services.py, tests/rptest/tests/archive_retention_test.py
The goal of this PR is to tighten up the archive retention tests in `CloudArchiveRetentionTest`.
Previously, the tests did not perform exact checks for the number of
segments deleted by retention. A number of test issues bubbled up when
I did this, but the most significant was that the time based test wasn't
working.
This was due to the fact that segment timestamps were too bunched up and
the precise check couldn't work. To fix that, custom timestamps with a
2 minute delta between records are used. I also had to fix the metric tracking
the number of deleted segments by the archive GC. Previously it treated indices
and tx manifests as segments.
Note that the bugs surfaced by this improved test were fixed in https://github.com/redpanda-data/redpanda/pull/11795.
* none
=> cloud_storage: check exact segment counts in `CloudArchiveRetentionTest`

src/v/cluster/partition_balancer_planner.cc, src/v/utils/stable_iterator_adaptor.h
Gets rid of the comma operator in the loop that is expected to throw
when the iterator is invalidated. Instead adds an explicit check that
does the same.
ASAN traces in https://github.com/redpanda-data/redpanda/issues/11664 are ideally not possible because the
freeing stack clearly bumps the topic map revision right after erase
that deallocates the memory, so any subsequent operation on the iterator
should throw right away.
The code is unnecessarily complex with the comma operator, so getting
rid of it in the hopes that there is some sort of miscompilation. If the
issue still reproduces after the patch we can at least eliminate this possibility.
Tests: repeat runs are unable to reproduce the UAF in 600 runs while without the
patch the issue reproduced once in 400 runs. 
* none
=> pb_planner: simplify iterator check

src/v/cluster/rm_stm.cc
The commit adds idempotency_num_pids_known metric to monitor when idempotency hits the limit of max pids in seq table.
Fixes #11886
* none
=> Add metric to monitor seq table size

src/v/kafka/server/group.cc, src/v/kafka/server/group.h, src/v/kafka/server/group_manager.cc, src/v/kafka/server/group_manager.h, src/v/kafka/server/tests/group_test.cc, src/v/utils/rwlock.h, src/v/utils/tests/CMakeLists.txt, src/v/utils/tests/rwlock_test.cc
An execution of abort_old_txes could span multiple terms so the so the method could modify new state assuming it's the old state resulting in undefined behavior.
This commit is the rewrite of the reverted [f7fc026f](https://github.com/redpanda-data/redpanda/commit/f7fc026f3203da167acc0e4c95b86f2e7e082dec) in [11474](https://github.com/redpanda-data/redpanda/pull/11474). The problem was caused by:
- do_detach_partition got blocked
- RP ignored blocked do_detach_partition and attempted next op leading double registration of the consumer groups ntp
The op was blocked by a deadlock:
- do_abort_old_txes was waiting for read lock while holding _gate
- do_detach_partition was holding write lock while waiting to the gate to be closed
This version doesn't wait for the read lock to become available …
=> Update `abort_old_txes` of the consumer group to use locks

tests/rptest/services/redpanda.py, tests/rptest/tests/e2e_shadow_indexing_test.py, tests/rptest/tests/node_id_assignment_test.py
When the only founding member of the cluster is restarted with a wiped
off disk, it can create its own cluster with a new cluster ID. This
patch avoids this by using multiple seed servers and auto node id assignment to
force the wiped off node to join the existing cluster instance.
Fixes #11109
* none
=> ducktape/si tests: use auto node_id assignment & multiple seed servers

src/v/archival/ntp_archiver_service.cc, src/v/archival/ntp_archiver_service.h, src/v/archival/tests/archival_metadata_stm_test.cc, src/v/archival/tests/ntp_archiver_test.cc, src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/partition_manifest.h, src/v/cloud_storage/remote_segment_index.cc, src/v/cloud_storage/remote_segment_index.h, src/v/cloud_storage/tests/remote_segment_index_test.cc, src/v/cluster/archival_metadata_stm.cc, src/v/config/configuration.cc, src/v/config/configuration.h
Previously we saw several cases in which:
- metadata didn't match the actual uploaded segment;
- metadata was inconsistent next segment didn't connect with the previous one;
This PR solves this by introducing the validation mechanism to the ntp_archiver and archival_metadata_stm.
During the segment upload ntp_archiver calculates the segment stats (base offset, last offset, size, offset translation parameters). This information is considered a 'ground truth' about the upload. It gets propagated up the call chain until the `ntp_archiver` finished uploading the data and produced the `segment_meta` instance that should be added to the STM. The 'segment_meta' is validated against the previous log and the 'ground truth' that we obtained by analyzing the segment.
The `archival_metadata_stm` also …
=> archival: Validate archival_metadata_stm updates

.gitignore
dev-cluster.py will by default create a data directory in the tools/data directory, which will fill with files that show in git unless we ignore them. So do that.
* none
=> Update .gitignore for dev-cluster data dir

src/v/kafka/server/handlers/fetch.cc
While changing the way we calculate fetch latency, I reversed the order of "now" and "start time" in the latency calculation, resulting in negative values for this duration. This interacted with the way histograms work in Prometheus to produce large (invalid) latency readings.
This change existed only in 23.2 and not in prior versions so no release note nor backports are required.
* none
=> Fix fetch latency calculation

src/v/kafka/server/handlers/metadata.cc
Add max_frag_bytes to the metadata memory estimate to account for the worse-cast overshoot during vector re-allocation.
Issue #5563.
* none
Makes the estimate of the memory used by a metadata request more conservative by including the extra allocated but unused space at the end of a fragmented vector.
=> Adjust metadata memory estimate for allocation

src/v/redpanda/application.cc
A small quality of life change: I keep my redpanda.yaml in a seperate
directory that is tuned to my system, so it's useful to just
pass ~/conf/redpanda.yaml instead of remembering to do
$HOME/conf/redpanda.yaml
* none
=> Expand '~' in --redpanda-cfg

src/v/cluster/archival_metadata_stm.cc
Throw exception if the replicated STM command is unknown. Currently, the STM silently drop the command on the floor. This may cause replicas to diverge during the rolling upgrade.
This may cause our upgrade tests to fail if we're not handling rolling upgrades correctly in tiered-storage.
* Make tiered-storage metadata handling more strict during rolling upgrades
=> cloud_storage: Unknown STM command handling

src/v/cloud_storage/tests/remote_partition_fuzz_test.cc
FIXES: https://github.com/redpanda-data/redpanda/issues/11880
Ignores timeout when connecting to S3 impostor, which can be caused due to the impostor not responding to rpc connection requests. 
The downside is that the test is erroneously reported as successful, with only a warning log message indicating that it did not complete its assertions.
This change should be rolled back once the problem with the impostor is investigated and fixed.
* none
=> cloud_storage/tests: Ignore impostor timeout in tests

src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/partition_manifest.h, src/v/cloud_storage/tests/partition_manifest_test.cc, src/v/cluster/partition.cc, tests/rptest/tests/e2e_shadow_indexing_test.py
Previously a `reset_metadata` command was followed up with the commands
setting up the `archival_metadata_stm` state (i.e. partition_manifest).
Since now the manifest is binary serialized and kept small in size it is
possible to serialize it as a part of reset command. This way a reset
command changes the manifest content in `archival_metadata_stm`
simplifying the whole reset operation.
Previously JSON deserializer didn't support the spillover manifests.
Added deserialization support in `partition_manifest_handler`. JSON
deserializtion is used in REST admin API to forcibly reset partition
with handcrafted manifest json.
Force push: 
- using `replace_manifest` command to reset the state
- serialize spillover manifests in an array as segment path is not required
- support for spillover …
=> Support for spillover manifests in `/v1/debug/unsafe_reset_metadata`

src/v/cloud_storage/materialized_resources.cc, src/v/cloud_storage/materialized_resources.h, src/v/cloud_storage/tests/remote_partition_fuzz_test.cc, src/v/cloud_storage/tests/util.cc, src/v/config/configuration.cc, src/v/config/configuration.h, tests/rptest/scale_tests/tiered_storage_io_stress_test.py, tests/rptest/scale_tests/tiered_storage_reader_stress_test.py, tests/rptest/tests/cloud_storage_chunk_read_path_test.py, tests/rptest/tests/e2e_shadow_indexing_test.py
In https://github.com/redpanda-data/redpanda/pull/11914, strict enforcement of partition reader concurrency was added, but the limit was driven by the existing segment reader config.
A separate property enables configuring the limit on partition readers
independently of the limit on segment readers.  Controlling
partition readers enables limiting tiered storage
read concurrency (e.g. because a drive is bottlenecked) without
limiting the number of segment readers we can cache (the limit
on segment readers is driven by memory)
* none
=> cloud_storage: add `cloud_storage_max_partition_readers_per_shard`

tests/rptest/tests/cloud_storage_timing_stress_test.py
In stress test when asserting that some number of compacted segments have been uploaded, this change sets a fixed cardinality for keys so that the segments are always compactible.
This is necessary because during compacted segment reupload we do not reupload unless the segment size has decreased.
This check can end up in preventing upload of compacted segments to the cloud, until all uploaded compacted segments fall off the end of the manifest and we are left with no compacted segments in the manifest, failing the test assertions.
FIXES #10836 
* none
=> cloud_storage/ducktape: Ensure segments are compactible

tests/rptest/clients/kubectl.py, tests/rptest/services/redpanda.py
Fixes https://github.com/redpanda-data/cloudv2/issues/7088
This PR changes the `KubectlTool` class to use `tbot` to get temp creds for `tsh` to connect to the agent node of a redpanda cloud cluster. This is needed for headless ducktape test execution and only works on EC2 machines that have a tbot IAM role assumed for redpanda testing.
To get the temp creds, `tbot` needs the auth server and bot token set in the duckatpe globals config file, e.g.:
```json
"cloud_teleport_auth_server": "auth.example.com:443",
"cloud_teleport_bot_token": "the-token",
```
if the `cloud_teleport_auth_server` is set but `cloud_teleport_bot_token` is unset, `tbot` will be skipped and teleport's default auth via github sso will be used (helpful for local dev env that do not have the tbot IAM role assumed).
No …
=> tests: setup tbot for tsh

src/v/archival/ntp_archiver_service.cc, src/v/archival/ntp_archiver_service.h, src/v/archival/tests/service_fixture.cc, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment.h, src/v/cloud_storage/remote_segment_index.cc, src/v/cloud_storage/remote_segment_index.h, src/v/cloud_storage/tests/remote_segment_index_test.cc, src/v/cloud_storage/tests/remote_segment_test.cc
This is a prerequisite to make timequeries seek
to the proper chunk, instead of reading from the
start of segments.
The timestamp we care about is the batch max timestamp, because timequeries will want to find a batch that is definitely before the target timestamp, to start their scan from there.
Related: https://github.com/redpanda-data/redpanda/issues/11801
* none
=> cloud_storage: add timestamps to remote segment index

src/v/cluster/persisted_stm.cc, src/v/cluster/rm_stm.cc
Added more detailed logging of snapshot operations in `rm_stm`
- none
=> More detailed logging around snapshot operations

src/v/config/bounded_property.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/config/tests/bounded_property_test.cc, src/v/kafka/server/connection_context.h, src/v/kafka/server/handlers/fetch.cc, src/v/kafka/server/handlers/fetch.h, src/v/kafka/server/request_context.h, src/v/kafka/server/server.cc, src/v/kafka/server/server.h, src/v/kafka/server/tests/CMakeLists.txt, src/v/kafka/server/tests/fetch_test.cc, src/v/kafka/server/tests/fetch_unit_test.cc, src/v/net/server.h, src/v/redpanda/tests/fixture.h, tests/rptest/tests/memory_stress_test.py
Backport of PR #10905 
Fixes #11262
Closes #11302
=> [v23.1.x] Limit memory used while fetching many partitions

src/v/cluster/members_backend.cc
Additional logging on members reconciliation path
This path involves a lot of logic and we've seen in the past cases
where reconciliation is either not succeeding or not apparently
making forward process. This change adds trace-level logging to the
cluster log to help diagnose these cases.
We also add an assert before referencing a vector front().
Issue redpanda-data/core-internal#472.
* none
=> Enhance trace logging in members reconciliation path

src/v/config/configuration.cc
This partially reverts https://github.com/redpanda-data/redpanda/commit/9a93a9c22238e145dfa9d7fe297eb494d7c5f0bf
While the original motiviation isn't invalidated we have now found a
counter example where the extra fetch groups makes things worse overall.
`ManyPartitionTest` fails on ARM with the extra group but passes
without. With the group in use CPU util hits 100% and grinds everything
to halt.
Fetch seems to be a lot slower on ARM. Hence, with the guaranteed share
of the extra group the whole system gets affected and hits CPU limits.
Because this is incredibly hard to reason about and it wasn't the core
fetch optimization we decided to revert back to keeping it disabled by
default.
We still keep the option around as it might be useful potentially in
corner cases.
Fixes …
=> kafka: Disable use of separate fetch scheduling group

src/v/model/model.cc
Made printing `topic_namespace` and `topic_partition` consistent with string representation of `ntp` which is printed as `namespace/topic/partition_id`.
- easier to read log entries
=> Made printing topic partitions and namespaces consistent

src/v/config/configuration.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11919
Fixes: https://github.com/redpanda-data/redpanda/issues/12034,
=> [v23.1.x] kafka: Disable use of separate fetch scheduling group

tests/rptest/tests/nodes_decommissioning_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11903
Fixes: https://github.com/redpanda-data/redpanda/issues/11906,
=> [v23.1.x] Fixed querying for the node in decommission test

src/v/cluster/archival_metadata_stm.cc
Throw exception if the replicated STM command is unknown. Currently, the STM silently drop the command on the floor. This may cause replicas to diverge during the rolling upgrade.
This may cause our upgrade tests to fail if we're not handling rolling upgrades correctly in tiered-storage.
Fixes https://github.com/redpanda-data/redpanda/issues/12014
* Make tiered-storage metadata handling more strict during rolling upgrades
=> [v23.1.x] cloud_storage: Unknown STM command handling

src/v/cloud_storage/segment_meta_cstore.cc, src/v/cloud_storage/segment_meta_cstore.h
short circuit segment_meta_cstore.empty() check
* none
=> cloud_storage/segment_meta_cstore: empty() shortcircuit

tests/rptest/tests/cluster_bootstrap_test.py
The test validating misconfigured cluster behavior is based on assumption that the nodes other than node[0] will not be able to exchange information with each other. Setting `seed_servers_explicitly` makes the previous semantics of a test.
Fixes: #12026
- none
=> Explicitly set seed_servers property in misconfigured bootstrap test

src/v/cluster/log_eviction_stm.cc, src/v/redpanda/admin/api-doc/debug.json, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h, tests/rptest/services/admin.py, tests/rptest/tests/delete_records_test.py
This change parameterizes the existing delete records tests in `tests/rptest/tests/delete_records_test.py` to work on local topics and topics enabled for cloud storage. When the cloud storage parameter is enabled, redpanda cfg options are configured so that local retention is aggressive enough to make all tests work with data that is not available locally but is available in tiered storage.
This change also includes another fix to the `at_segment_boundary` option in the `test_delete_records_segment_deletion` test. Previously this test compared the kafka low watermark against on disk segments base offsets to assert that data was actually deleted. This is incorrect because the low watermark is a kafka offset and the segment base offsets observed are redpanda offsets, one cannot make the …
=> Test existing DeleteRecords ducktape tests against topics with cloud storage enabled

src/v/raft/consensus.cc, src/v/raft/state_machine.cc, src/v/raft/state_machine.h
Improved the way how linearizable barrier is handled
Fixes: #11062
- Made linearizable barrier semantics more strict.
=> Linearizable barrier improvements

tests/rptest/tests/controller_upgrade_test.py
Skipping controller upgrade test in debug mode as it may write a lot of data during
Fixes: #10721 
- none
=> tests: skip controller upgrade test in debug mode

src/v/cluster/scheduling/leader_balancer_types.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/11706
Fixes https://github.com/redpanda-data/redpanda/issues/11730,
=> [v23.1.x] c/leader_balancer: use btree_map as a group to revision index

src/v/cloud_storage/async_manifest_view.cc, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/tests/cloud_storage_e2e_test.cc, src/v/cloud_storage/tests/delete_records_e2e_test.cc
There is a general problem with APIs that read from tiered storage, that they typically don't account for when spillover happens during the call. This PR addresses this by installing a check for when spillover happens, and retrying lookups or returning early to clients if it is detected.
I'm not in love with the approach, as it's very bolted on, but it's nice in that it doesn't incur an additional roundtrip to the client in most cases. Other approaches I considered:
- Put the detection closer to the Kafka layer, and return an error code to clients to retry (probably some timeout error; given these are rare, it's acceptable)
- Add a lock to the manifest on the read path that prevents spillover during iteration.
- Harden cursor iteration and usage of segment_containing() to be able to …
=> cloud_storage: handle cases where reads race with spillover

src/v/raft/append_entries_buffer.cc, src/v/raft/append_entries_buffer.h
Append entries buffer is used to coalesce multiple append entry requests into single batch and reduce number of flushes. Usually the size of the batch is small. In some case when it grows larger it may end up in causing large contiguous allocation.
Replaced vector used to buffer pending requests with a `chunked_fifo`. The chunk size was set to 32 as usually the size of the queue is small.
Fixes: #12072
- none
=> r/append_entries_buffer: use chunked fifo to store requests

src/v/kafka/server/handlers/offset_for_leader_epoch.cc, src/v/kafka/server/replicated_partition.cc, tests/rptest/tests/offset_for_leader_epoch_test.py
Correctly reported by @VladLazar and nicely explained in issue #11864 , the current issues with OffsetForLeaderEpochRequest handling are:
1. Requested epoch is in the future (i.e. larger than the current term). We should return `leader_epoch=-1 end_offset=-1`. Currently we return `leader_epoch=current_term end_offset=log_start_offset`.
2. Requested epoch is in the past, but still present in the log. We should return `leader_epoch=requested_epoch end_offset=last_offset of requested_epoch + 1` and we currently return `leader_epoch=current_term end_offset=last_offset of requested_epoch + 1`
This PR fixes both of these issues and modifies the ducktape tests to assert this new behavior holds true.
* Fix for OffsetForLeaderEpoch returning a value for when the requestedEpoch is larger then the …
=> Fix for incorrect handling of OffsetForLeaderEpoch request

src/v/raft/append_entries_buffer.cc, src/v/raft/append_entries_buffer.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/12074
Fixes: https://github.com/redpanda-data/redpanda/issues/12077,
=> [v23.1.x] r/append_entries_buffer: use chunked fifo to store requests

tests/rptest/services/redpanda.py
Less hardcoding of values passed into cloud api when creating a redpanda cloud cluster. More web service calls to get the latest values for:
* `regionId`
* `installPackVersion`
* `productId`
Also allows ducktape to create clusters by config profile name instead of product id.
This PR supersedes PR #12048
This PR is needed for https://github.com/redpanda-data/cloudv2/issues/6662
Tested with this command using configuration against `preprod`:
```console
ducktape \
--globals=/home/a/tmp/ducktape_globals.json \
--cluster=ducktape.cluster.json.JsonCluster  \
--cluster-file=/home/a/tmp/ducktape_cluster.json \
tests/rptest/tests/services_self_test.py::SimpleSelfTest
```
And the subsequent payload body generated with latest values:
```json
{
"cluster": {
"name": …
```
=> tests: query cloud api for region id, install pack ver, and product id

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/application.cc, src/v/resource_mgmt/CMakeLists.txt, src/v/resource_mgmt/storage.cc, src/v/resource_mgmt/storage.h, src/v/resource_mgmt/tests/CMakeLists.txt, src/v/resource_mgmt/tests/storage_test.cc, src/v/storage/disk_log_impl.cc, src/v/storage/disk_log_impl.h, src/v/storage/types.h, tests/rptest/scale_tests/log_storage_target_size_test.py, tests/rptest/tests/full_disk_test.py
This PR introduces two important changes:
1. A configuration option that makes local retention advisory. When enabled, storage is allowed to grow beyond the effective local retention. Normal GC will collect based on the consumable retention configuration (aka cloud retention aka max retention), and relies on space management to select data for removal when log data usage is over the target size.
2. Replaces the greedy selection approach--which culled data down to the max collectible offset--with a balanced (round robin removal of segments) and phased/leveled approach which prioritizes classes of data over others, such as removing data first which has expanded beyond the local retention policy when config from (1) is enabled.
Incoming 💾 🚒. 
* none
=> storage: balanced eviction and advisory policy

src/v/security/acl.cc, src/v/security/acl.h, src/v/security/authorizer.h
`acl_implied_ops` was quite visible (~3%) in the callchains leading to `operator new()` in the LRC profile.
It's called for every partition so this is not entirely surprising when using larger partition counts.
Avoid the allocations by "inlining" the check into the function so that no vector has to be allocated.
* none
=> acl: Avoid allocations when checking implied ops

tools/rp_storage_tool/src/bucket_reader.rs
When scanning a bucket using rp-storage-tool, both the json and binary manifests may be present. In this case, avoid overwriting the binary manifest if it has already been ingested.
Fixes: #12093 
* none
=> tools/rp-storage-tool: Avoid overwriting manifest

src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_types.h, src/v/redpanda/admin/api-doc/cluster.json, src/v/redpanda/admin_server.cc, tests/rptest/tests/cluster_health_overview_test.py
This series adds an "unhealthy reasons" field to the cluster health
admin endpoint.
Currently, the health monitor returns a boolean indicating if the
cluster is healthy, and some additional information about nodes which
are down and leaderless partitions.
However, it is possible for the "healthy" boolean to be false while
the remainder of the information does not indicate any problem,
leaving users of rpk cluster health with little to go on: "The cluster
is unhealthy, but you don't get to know why".
One way (only way?) this can happen is when the cluster health
report acquisition process fails.
This change adds an unhealthy reasons vector, which is set to non-empty
only if the cluster is unhealthy, and which contains one string for
each reason the cluster is unhealthy.
In another change …
=> Add "unhealthy reasons" to cluster_health_overview endpoint

src/go/rpk/pkg/cli/topic/add_partitions.go
This PR makes the `num` flag required in `rpk topic add-partitions`. 
Fixes https://github.com/redpanda-data/redpanda/issues/12004
* rpk: make num flag required in add-partitions
=> rpk: make num flag required in add-partitions

tests/rptest/scale_tests/large_controller_snapshot_test.py
Recent change in the default setting of seed servers in ducktape tests made this test to fail as the nodes were trying to connect to the seed node which was down. Fixed the issue by explicitly setting the see server nodes.
- none
=> tests: set the seed server list explicitly in controller snapshot test

src/v/cloud_storage/partition_probe.cc, src/v/cloud_storage/partition_probe.h, src/v/cloud_storage/probe.cc, src/v/cloud_storage/probe.h, src/v/cloud_storage/remote.cc, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment.h, src/v/cloud_storage/segment_state.cc, src/v/cloud_storage/tests/remote_segment_test.cc, tests/rptest/tests/cloud_storage_chunk_read_path_test.py, tests/rptest/util.py
Metrics are introduced to measure chunk hydration with this change. 
1. Histogram for chunk hydration latency
2. Histogram for client acquisition during segment download
3. Histogram for segment download
4. Gauge for chunk size (labelled by ntp)
The first measurement is roughly the sum of the second and third measurements, so may be redundant.
A couple of tests are changed to use the chunk size metric in their assertions.
* none
=> cloud_storage: Add metrics for chunk hydration

src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/segment_meta_cstore.cc, src/v/cloud_storage/segment_meta_cstore.h
Make `size_bytes` column available directly and use it to compute the size of the log instead of materialising every `segment_meta` struct.
* none
=> cloud_storage: Partition manifest fixes

tests/rptest/services/redpanda.py, tests/rptest/util.py
followup on #12017 
util.py::ssh_output_stderr works like ducktape ssh_output, but returns byte strings for stdout and for stderr
* none
=> move RedpandaService::_ssh_output_stderr to standalone function in util.py

src/go/rpk/pkg/cli/group/offset_delete.go, tests/rptest/clients/rpk.py, tests/rptest/tests/offset_retention_test.py
We want to always have all rpk commands logged at the verbose level so its easier to debug future problems. This specifically will be useful in tracking down the root cause of issue https://github.com/redpanda-data/redpanda/issues/11829
* none
=> rptest: Unconditionally enable verbose logging for all rpk commands in ducktape

src/go/rpk/pkg/cli/profile/edit_gobals.go, src/go/rpk/pkg/cli/profile/print_globals.go, src/go/rpk/pkg/cli/profile/profile.go, src/go/rpk/pkg/cli/profile/prompt.go, src/go/rpk/pkg/cli/profile/prompt_test.go, src/go/rpk/pkg/cli/profile/set.go, src/go/rpk/pkg/cli/profile/set_globals.go, src/go/rpk/pkg/cli/topic/trim.go, src/go/rpk/pkg/config/params.go, src/go/rpk/pkg/config/params_test.go, src/go/rpk/pkg/config/rpk_yaml.go, src/go/rpk/pkg/config/rpk_yaml_test.go, src/go/rpk/pkg/kafka/client_franz.go
Addressing a few feedbacks:
- Renaming profile defaults -> globals.
- Defaulting to printing the name of the profile in `rpk profile prompt` if the prompt string is not empty.
- Renaming `redpanda_client_id` to `kafka_protocol_request_client_id`
- Reword of confirmation prompt text in `rpk topic trim`
These features have not been released yet:
* none
=> rpk: profile globals rename

src/v/kafka/server/handlers/fetch.cc, src/v/kafka/server/handlers/fetch.h
By aggregating memory_units_t from the same shard together we reduce cross shard function calls from linear to the number of fetched partitions to 1.
* none
=> Aggregate `memory_units_t` in `fetch` to reduce cross-shard calls

src/go/rpk/pkg/adminapi/api_cluster.go, src/go/rpk/pkg/cli/cluster/health.go
See PR https://github.com/redpanda-data/redpanda/pull/12039 for more context.
This is that change + the RPK side changes to expose this value in `rpk cluster health`, so for the purposes of this review look only at the last commit (split the reviews since the audience is different and we want the redpanda side change even if RPK doens't expose it).
This basically adds one more line called `Unhealthy reasons:` to the `cluster health` output like so:
```
CLUSTER HEALTH OVERVIEW
=======================
Healthy:                     false
Unhealthy reasons:           [nodes_down under_replicated_partitions]
Controller ID:               0
All nodes:                   [0 1 2]
Nodes down:                  [1]
Leaderless partitions:       []
Under-replicated partitions: [redpanda/controller/0]
``` …
=> Add unhealthy reasons to RPK

tests/rptest/tests/delete_records_test.py
- In situations where orphaned segments lead to test timeout the exception handler in the delete_records_test_segment_deletion test will ensure that other nodes that were not triggered by a crash still have all required segments to have been truncated.
- The test was however incorrectly comparing an array of segments to a node object, allows the assertion check to occur on the downed node which is expected to have orphaned segments. This incorrectly triggers a test failure.
- The fix is to correctly compare the node names when iterating through the storage snapshot.
- Fixes: #11932
* none
=> Fix incorrect node name comparison in `DeleteRecordsTest.test_delete_records_segment_deletion`

src/v/cluster/partition_balancer_backend.cc, src/v/cluster/partition_balancer_backend.h, src/v/cluster/partition_balancer_planner.cc, src/v/cluster/partition_balancer_planner.h
In the case when partition is created right before the node is being
decommissioned it may be the case that its size is not present in the
health report. In this case a balancer would have to wait for at most
two metadata refresh periods to get the partition size information.
During that period the balancer backend may enter stalled mode.
Added a mechanism allowing partition balancer backend to detect
situation in which partition size is missing and force refresh the
health report. In this case a balancer tick is scheduled immediately.
Fixes: #11999
- none
=> Force refresh health report if partition size is missing 

src/v/security/acl.cc, src/v/security/acl.h, src/v/security/authorizer.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/12079
=> [v23.1.x] acl: Avoid allocations when checking implied ops

src/v/compression/compression.cc, src/v/compression/compression.h, src/v/storage/parser_utils.cc, src/v/storage/parser_utils.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/12071
Fixes: https://github.com/redpanda-data/redpanda/issues/12106,
=> [v23.1.x] storage/parse_utils: Use async_stream_zstd compression

src/v/config/property.h, tests/rptest/tests/cluster_config_test.py
Fix the legacy_default feature. First two commits fix what appear to be bugs in the feature, and the last commit introduces a test that exercises the functionality.
* none
=> config: fix legacy_default feature and add tests

src/v/kafka/server/handlers/offset_for_leader_epoch.cc, src/v/kafka/server/replicated_partition.cc, tests/rptest/tests/offset_for_leader_epoch_test.py
=> Backport of #12063 v23.1.x

.github/pull_request_template.md
=> .github: add 23.2.x and remove 22.2.x to PR template

tests/rptest/tests/retention_policy_test.py
The test previously waited to upload some amount of data, but didn't enable partial segment uploads. As such, sometimes we wouldn't upload everything in the span of the test.
This patch sets a low upload interval to ensure segments get uploaded in a timely manner.
Fixes #11204
* none
=> ducktape: set small upload interval in retention_policy_test

src/v/kafka/server/handlers/offset_for_leader_epoch.cc, src/v/kafka/server/replicated_partition.cc, tests/rptest/tests/offset_for_leader_epoch_test.py
Backporting #12063 to v22.3.x
* Fix for OffsetForLeaderEpoch returning a value for when the requestedEpoch is larger then the highest known.
* Fix for OffsetForLeaderEpoch returning the current leaders epoch (term) instead of the requested.
=> Backport of pr 12063 to v22.3.x

tests/rptest/clients/rpk.py
When an Rpk command times out in ducktape no output is printed except for a vague exception messaging stating that the command has timed out.  This change grabs the output from the process, prints it and forwards it to the RpkException constructor before throwing so the reason for the timeout can be more easy to debug.
* none
=> Print output from Rpk commands that timeout in ducktape

src/v/raft/state_machine.cc, src/v/raft/state_machine.h
7cb919c0dda574ddab1595bd5b5423fcb2c65283 introduced an optimisation which
uses `shared_future` for concurrent calls to trigger a linearisable barrier. Looks like
the related code caused an asan violation in https://github.com/redpanda-data/redpanda/issues/12143.
The code in the reverted commit looks fine, but I have some doubts about the `shared_future`
implementation. Note there should be no semantic change here as 7cb919c0dda574ddab1595bd5b5423fcb2c65283
is just an optimisation.
Fixes https://github.com/redpanda-data/redpanda/issues/12143 
* none
=> Revert "r/state_machine: share linearizable barrier result"

src/go/rpk/pkg/cli/redpanda/start.go, src/go/rpk/pkg/cli/redpanda/start_test.go
These are meant to be passed to the shell as we were typing them into the terminal. Normally, shells strip quotes from the string.
See https://github.com/redpanda-data/redpanda/issues/7878#issuecomment-1638524400 for extra logs on why stripping the quotes.
Fixes #7878
* rpk: fixes a bug where using quotes in flags values inside redpanda.yaml's `rpk.additional_start_flags` would make redpanda to fail on start.
=> rpk: strip quotes from additional start args

src/go/rpk/go.mod, src/go/rpk/go.sum
Fixes a logic race in franz-go
* none
=> rpk: bump franz-go to v1.14.2 to fix consumer logic race

src/v/cluster/rm_stm.h
An off by one error in `rm_stm::max_collectible_offset` may lead to situation in which an stm couldn't continue. If `max_collectible_offset` returned last offset in the segment it may lead to the situation in which the whole segment was evicted before its last entry was applied. As the `max_collectible_offset` was returning `last_stable_offset` which indicates the offset for which all _previous_ offsets are decided (has no pending transactions and have been committed). In rare cases it may lead to situation where a segment ending at offset `n` was removed even though only `n - 1` was decided.
- fixes log segments being evicted too early
=> c/rm_stm: fixed returning incorrect `max_collectible_offset`

src/v/cluster/rm_stm.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/12176
=> [v23.2.x] c/rm_stm: fixed returning incorrect `max_collectible_offset`

src/v/cluster/partition_probe.cc, tests/rptest/tests/cluster_metrics_test.py
The recommended way to calculate consumer lag with prometheus is
```
max by(redpanda_namespace, redpanda_topic,
redpanda_partition)(redpanda_kafka_max_offset{redpanda_namespace="kafka"}) - on(redpanda_topic, redpanda_partition) group_right max by(redpanda_group, redpanda_topic,
redpanda_partition)(redpanda_kafka_consumer_group_committed_offset)
```
which uses `max_offset` which in turn maps to the kafka translated offset of the last raft committed offset. however, kafka clients that read offset X commit offset X+1 (sort of like they commit the next thing that should be read).
So when computing the lag it will look like the consumer is always at least one offset away from the end despite having read naything.
HWM contains that +1 factor. This is also what seems to be done in franz-go and …
=> kafka: expose hwm for max offset in public metrics

src/v/cloud_storage/cache_service.cc, src/v/cloud_storage/cache_service.h, src/v/cloud_storage/tests/cache_test_fixture.h, src/v/cloud_storage/tests/cloud_storage_e2e_test.cc, src/v/cloud_storage/tests/cloud_storage_fixture.h, src/v/cloud_storage/tests/delete_records_e2e_test.cc, src/v/cluster/node/local_monitor.cc, src/v/cluster/node/local_monitor.h, src/v/cluster/node/types.cc, src/v/cluster/node/types.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/config/property.h, src/v/redpanda/application.cc, src/v/resource_mgmt/storage.cc, src/v/resource_mgmt/storage.h, src/v/storage/disk_log_impl.cc, src/v/storage/tests/log_retention_tests.cc, src/v/storage/types.h, tests/rptest/scale_tests/log_storage_target_size_test.py, tests/rptest/services/redpanda.py, tests/rptest/tests/cluster_config_test.py, tests/rptest/tests/full_disk_test.py
* First three commits are from PR https://github.com/redpanda-data/redpanda/pull/12132 under separate review which fix legacy_default config issue, but which this PR depends on.
* Then next four commits address integration with partition balancer by publishing size information into the cluster health report which the balancer will pick up. Used by @bharathv in separate PR.
* Final set of commits add / tweak configuration options to support (1) desired policies in upgrade scenarios and (2) percentage based expression of cache and log data disk size reservations.
Upgraded clusters
* The effect should be that new space management is not active
* In ordre to enable, turn the feature on and configure nonstrict-mode/disk sizes.
New clusters
* New space management is on by default.
Config option …
=> storage: space management config and health integration

src/go/rpk/.goreleaser.yaml
Now that branch 23.2.x has been cut, there will be no need to push homebrew updates from 23.1.x branch. This is a workaround and a proper filtering of releases should be done at the github actions level.
* none
=> rpk: disable uploads to homebrew repo from 23.1.x branch

src/v/cluster/rm_stm.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/12176
=> [v23.1.x] c/rm_stm: fixed returning incorrect `max_collectible_offset`

src/v/cloud_storage/cache_service.cc, src/v/cloud_storage/cache_service.h, src/v/cloud_storage/tests/cache_test_fixture.h, src/v/cloud_storage/tests/cloud_storage_e2e_test.cc, src/v/cloud_storage/tests/cloud_storage_fixture.h, src/v/cloud_storage/tests/delete_records_e2e_test.cc, src/v/cluster/node/local_monitor.cc, src/v/cluster/node/local_monitor.h, src/v/cluster/node/types.cc, src/v/cluster/node/types.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/application.cc, src/v/resource_mgmt/storage.cc, src/v/resource_mgmt/storage.h, src/v/storage/disk_log_impl.cc, src/v/storage/tests/log_retention_tests.cc, src/v/storage/types.h, tests/rptest/scale_tests/log_storage_target_size_test.py, tests/rptest/services/redpanda.py, tests/rptest/tests/full_disk_test.py
Backport https://github.com/redpanda-data/redpanda/pull/12091
Fixes https://github.com/redpanda-data/redpanda/issues/12284
Manually backported to drop legacy default config commits that were duplicated in dev and backport cherrypick didn't recognize as dupes.
* none
=> [v23.2.x] backport https://github.com/redpanda-data/redpanda/pull/12091 

tests/rptest/tests/leadership_transfer_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11472
Fixes https://github.com/redpanda-data/redpanda/issues/11478,
=> [v23.1.x] Update start timeout for `leadership_transfer_test` on debug builds

src/v/storage/disk_log_impl.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11956
=> [v23.1.x] storage: fix coroutine iteration over _segs

src/v/archival/ntp_archiver_service.cc, src/v/cloud_storage/async_manifest_view.cc, src/v/cloud_storage/tests/async_manifest_view_test.cc
The main change in this PR is to teach size based retention in the archive
to start from the clean offset. Previously, size based retention in the archive
would always start collecting from the first segment in the same spillover
manifest as the archive start offset. Since spillover manifests are not reuploaded,
said segment could have been below the archive clean offset. In this case,
retention wouldn't collect enough data to correctly satisfy the
retention policy as it's selecting the same segments as in previous
iterations.
This patch updates size based retention to skip segments below the clean
offsets when looking for the truncation point. It might look strange
that we're using the clean offset here. Intuitively, retention should
operate from the archive start offset. The intuition …
=> cloud_storage: skip below clean offset in archive sized retention and other fixes

tests/rptest/services/admin_ops_fuzzer.py
If `choice` function returns `None` then we should not try to query for topic description as this lead to assertion being triggered in test.
Fixes: #12137
- none
=> tests: do not issue describe command for empty topic object

src/v/storage/file_sanitizer_types.cc, tests/rptest/services/admin.py, tests/rptest/services/redpanda.py, tests/rptest/services/redpanda_monitor.py, tests/rptest/services/storage_failure_injection.py, tests/rptest/tests/storage_failure_injection_test.py, tools/offline_log_viewer/storage.py
This PR introduces the ducktape infra required to run tests with failure injection
enabled. A ducktape test that exercises the failure injection facilities is also added.
It can be used as a template for more complex failure injection tests.
* none
=> rptest: ducktape failure injection infra

src/v/cluster/partition_manager.cc, src/v/cluster/partition_manager.h, src/v/kafka/server/group_manager.cc
Within WASM transforms we're going to need the ability to intersect all of the topic partitions within a node/shard with the transforms that exist. This patch adds the appropriate callbacks to partition manager to support this.
* none
=> Support watching all topics within partition manager

src/v/cluster/health_monitor_backend.cc
Made marking node as alive independent from log level.
- none
=> Fixed marking node as alive in health monitor backend

src/v/cluster/health_monitor_backend.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12313
=> [v23.2.x] Fixed marking node as alive in health monitor backend

tests/rptest/tests/controller_availability_test.py
Added sorting the nodes by id before selecting the ones to stop in `controller_availability_test` this way the test is deterministic as it always stop the two nodes with smallest ids. This way the test stops the current controller and at the same time guarantees that the next candidate is the one with the highest priority from the nodes that were left running.
Fixes: #12275
- none
=> Sort nodes before stopping them in `ControllerAvailabilityTest`

src/v/cluster/persisted_stm.cc, src/v/cluster/rm_stm.cc
This change fixes an issue where a snapshot might
have been created with offset lower from the offset of a snapshot that
was already applied.
Fixes: #11659
- reduces amount of data read while bootstrapping `rm_stm`
=> Fixed taking snapshot in `rm_stm`

src/v/kafka/server/connection_context.cc, src/v/kafka/server/connection_context.h, src/v/ssx/future-util.h
Turns the long and hideous dispatch_method_once function into a coroutine in an on-going effort to clean-up and simplify the Kafka server.
* none
=> kafka: turn connection_context::dispatch_method_once into coroutine

src/v/archival/ntp_archiver_service.cc, src/v/archival/segment_reupload.cc, src/v/storage/offset_to_filepos.cc, src/v/storage/offset_to_filepos.h
When an upload candidate is created with the start or end offsets (which are read from the manifest) and also inside the batch boundaries of local disk segment, this change rejects the upload and skips ahead of the upload candidate.
FIXES: https://github.com/redpanda-data/redpanda/issues/12232
* none
=> archival: Reject segment reupload if candidate lies inside compacted batch

tests/rptest/clients/rpk.py, tests/rptest/services/redpanda.py, tests/rptest/tests/services_self_test.py
Creates a redpanda cloud user, grants acls, and exposes broker url so tests can use tools like `RpkTool` to send requests to the kafka api.
This PR is needed for https://github.com/redpanda-data/cloudv2/issues/6683
Updated `test_cloud` to use `rpk` with `tls_enabled` to verify user and acls work. Output of run against redpanda cloud:
```console
bash$ ducktape --globals=/home/a/tmp/ducktape_globals.json --cluster=ducktape.cluster.json.JsonCluster --cluster-file=/home/a/tmp/ducktape_cluster.json --test-runner-timeout=3600000 tests/rptest/tests/services_self_test.py::SimpleSelfTest
[INFO:2023-07-20 11:45:33,634]: starting test run with session id 2023-07-20--007...
[INFO:2023-07-20 11:45:33,634]: running 1 tests...
[INFO:2023-07-20 11:45:33,634]: Triggering test 1 of 1...
[INFO:2023-07-20 …
```
=> rptest: setup access to kafka api for redpanda cloud 

src/v/cluster/log_eviction_stm.cc, src/v/kafka/server/replicated_partition.cc, tests/rptest/tests/delete_records_test.py
Calls to delete-records were not returning the correct kafka error codes in the case leadership was lost. It was observed most error codes were plainly mapped to generic `unknown_server_error` codes, this is bad in the case the error was a retryable one.
This patch maps all cluster error codes to proper kafka ones for the `replicated_partition::prefix_truncate` call. Also a test was added that randomly invokes some partition moves while concurrently issuing delete-records. 
* Fixes a bug where unknown_server_error is incorrectly returned as an error code in situations where it shouldn't on call to delete-records
=> Map cluster error codes to correct kafka ones on call to prefix_truncate

src/v/cloud_storage/offset_translation_layer.cc, src/v/model/record_batch_types.h, src/v/raft/consensus.cc, src/v/storage/segment_utils.h
Currently, Raft and Tiered-storage are using the same set of batch types for offset translation. It's encoded in the
raft::offset_translator_batch_types function. But the comapction uses its own function called 'is_compactible' which uses hardcoded set of types. This commit fixes this by using the same set of types everywhere.
* none
=> storage: Do not hardcode set of batch types in storage

cmake/v_library.cmake
For compatibility reasons, we use `list(REMOVE_ITEM ...)` with cmake version 3.5.   
But now we require cmake minimum version 3.12 in root [CMakeLists.txt](https://github.com/redpanda-data/redpanda/blob/dev/CMakeLists.txt), it's time to turn to list(FILTER ...).
* none
=> cmake: use list FILTER since cmake version greater than 3.5 now

src/v/cloud_storage_clients/client_probe.cc
This metric was added in v23.2.1, very unlikely anyone is already using it, so let's quickly fix this before it becomes a backward compat issue.
* none
=> cloud_storage: fix a typo in a metric name

src/go/rpk/build.sh, src/go/rpk/pkg/adminapi/admin.go, src/go/rpk/pkg/cli/root.go, src/go/rpk/pkg/cli/version/version.go
This PR introduces an enhanced version command for rpk that prints more useful information about the build of rpk and, if possible, prints the Redpanda version running in each node in your cluster.
```
$ rpk version
Version:     v23.1.1
Git ref:     135af8f57
Build date:  2023-07-21T07:54:18-05:00
OS/Arch:     linux/amd64
Go version:  go1.20.4
Redpanda Cluster
node-0  v23.1.13 - 6b1c6f55d2a46871fafc7d003383b59215f12351
node-1  v23.1.13 - 6b1c6f55d2a46871fafc7d003383b59215f12351
node-2  v23.1.13 - 6b1c6f55d2a46871fafc7d003383b59215f12351
```
**Error handling:**
```
$ rpk version 
Version:     v23.1.1
Git ref:     e8c0ac04e
Build date:  2023-07-19T16:14:12-05:00
OS/Arch:     linux/amd64
Go version:  go1.20.4
Redpanda Cluster
Unreachable, to debug, use the '-v' flag. To get the broker …
```
=> rpk: enhanced version command

tests/rptest/infinite_retention/checks.py, tests/rptest/infinite_retention/helpers.py, tests/rptest/infinite_retention/infinite_retention_test.py
In order to utilize special procedure to check infinite retention it is needed to create a series of tests that focus on configuring cluster in a way that simulates different client use cases of prolonged use of redpanda without deleting anything from the storage.
fixes https://github.com/redpanda-data/devprod/issues/739
fixes https://github.com/redpanda-data/devprod/issues/744
First version of the pipeline will run healthy path of infinite retention without rolling restarts and failure injection
=> test: Create test suite to test infinite retention

tests/rptest/scale_tests/tiered_storage_reader_stress_test.py
This test used synthetic historic timestamps.  It usually ran fast enough for housekeeping not to happen, but sometimes not.
We never want anything reaped in this test, so just set retention.ms to -1.
Fixes https://github.com/redpanda-data/redpanda/issues/12319
* none
=> tests: disable retention.ms in reader stress test

tests/rptest/remote_scripts/compute_storage.py
In
https://buildkite.com/redpanda/redpanda/builds/33545#01896f0b-4206-4688-b578-4321e0069ea1
there was a failure due to a directory being deleted so the `listdir`
method threw. This fixes that by returning an empty list for those
case where the directory has been deleted by the time we got to listing
it.
* none
=> Make compute_storage.py robust to directories being deleted

src/go/rpk/pkg/cli/cloud/byoc/byoc.go
This previously was implicitly always passed because rpk did not strip rpk specific flags.
A PR in April changed the behavior to strip all rpk specific flags -- this was done for safety so that people could pass -X, -v, etc. to rpk while also execing the plugin, and rpk would strip all rpk flags and only give the plugin the plugin specific flags.
Since --redpanda-id was a defined rpk flag, it wasn't obvious that this flag was a part of the contract handoff to byoc, and we did not include it in the PR.
As it turns out, the flag is required.
* `rpk cloud byoc` now properly adds the `--redpanda-id` flag when handing off to the cloud plugin.
=> rpk cloud byoc: pass --redpanda-id to the plugin

src/go/rpk/.goreleaser.yaml
Fixes https://github.com/redpanda-data/devprod/issues/791
Following on from changes in PR #9981 that removed `github.com/redpanda-data/redpanda/src/go/rpk/pkg/cli/cmd`.
* none
=> rpk: fix ldflags for version in goreleaser

.github/workflows/lint.yml, .github/workflows/rpk-build.yml, src/go/rpk/.golangci.yml
For gofumpt in golangci, the lang version can just be major releases -- this is for formatting changes, which only happens in major releases
* none
=> rpk, github: use latest stable golang

src/go/rpk/.goreleaser.yaml
Backport of PR https://github.com/redpanda-data/redpanda/pull/12386
=> [v23.2.x] rpk: fix ldflags for version in goreleaser

src/v/raft/consensus.cc, src/v/raft/prevote_stm.cc, src/v/raft/vote_stm.cc, tests/rptest/tests/cluster_features_test.py, tests/rptest/tests/maintenance_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/10800 
Fixes: #11546
=> [v22.3.x] Fixed Raft voter priority override with single replica topics

tests/rptest/tests/partition_move_interruption_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11519
Fixes https://github.com/redpanda-data/redpanda/issues/11520,
=> [v23.1.x] Disable `test_cancellations_interrupted_with_restarts` in debug 

src/v/pandaproxy/schema_registry/protobuf.cc, src/v/pandaproxy/schema_registry/test/compatibility_protobuf.cc
`FileDescriptorProto::DebugString` puts import lines before the package line, swap them to adhere to https://protobuf.dev/programming-guides/style/#file-structure
Fixes #12335
* schema_registry: Improve the ordering of protobuf files
=> schema_registry: Improve the ordering of protobuf files

src/v/pandaproxy/schema_registry/avro.cc, src/v/pandaproxy/schema_registry/test/sanitize_avro.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12334
Fixes: https://github.com/redpanda-data/redpanda/issues/12416,
=> [v23.2.x] schema_registry: Improve sanitization of Avro namespaces

tests/rptest/tests/memory_stress_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11533 
Fixes: #11594 
Force pushed `9d4bff8` to re-trigger CI - no changes
=> [v23.1.x] Adjust maximum value for  in 

src/v/pandaproxy/schema_registry/avro.cc, src/v/pandaproxy/schema_registry/test/sanitize_avro.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12334
Fixes: https://github.com/redpanda-data/redpanda/issues/12412,
Manual backport as `<stack>` was not included - Closes #12414
=> [v22.3.x] schema_registry: Improve sanitization of Avro namespaces

src/v/pandaproxy/schema_registry/avro.cc, src/v/pandaproxy/schema_registry/test/sanitize_avro.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12334
Fixes: https://github.com/redpanda-data/redpanda/issues/12415,
Manual backport because `<stack>` wasn't included
Closes #12417
=> [v23.1.x] schema_registry: Improve sanitization of Avro namespaces

tests/rptest/scale_tests/many_partitions_test.py, tests/rptest/test_many_partitions.yml, tests/rptest/test_suite_ec2.yml
- Uncommented test_many_partitions_tiered_storage so it can be run
- Added separate suite to run tests
- Excluded tiered test from main ec2 run
* none
=> tests: add separate test suite to run partition tests

tests/rptest/test_suite_infinite_retention.yml
=> test/ci: add test suite for infinite retention

tests/rptest/clients/kafka_cli_tools.py, tests/rptest/scale_tests/high_throughput_test.py, tests/rptest/services/kgo_verifier_services.py, tests/rptest/services/redpanda.py, tests/rptest/test_suite_cloud.yml, tests/rptest/tests/redpanda_test.py
Updates to the ducktape tests so `KgoVerifierProducer` can work with redpanda cloud. Since redpanda cloud has TLS and SASL enabled by default, needed to configure the kgo-verifier and kafka cli tools to use these settings. The `HighThroughputTest2.test_throughput_simple` test was updated to use the redpanda cloud settings if they are detected and the test was added to the `test_suite_cloud.yml` so it can run on the scheduled buildkite job.
Fixes https://github.com/redpanda-data/cloudv2/issues/6663
Fixes https://github.com/redpanda-data/cloudv2/issues/6683
Output of run against redpanda cloud using an existing cluster in `preprod`:
```console
bash$ ducktape --globals=/home/ubuntu/redpanda/tests/globals.json --cluster=ducktape.cluster.json.JsonCluster …
```
=> rptest: enable `KgoVerifierProducer` to run against redpanda cloud

src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment.h, src/v/cloud_storage/tests/common_def.h, src/v/cloud_storage/tests/remote_partition_test.cc, src/v/cloud_storage/tests/remote_segment_index_test.cc, src/v/cloud_storage/tests/util.cc
Add two unit-tests. First one checks situation when the compacted segment has a hole in the middle of the segment. The second one has the hole at the end.
* none
=> cloud_storage: Add compacted segment read-path tests

src/v/cluster/tx_gateway_frontend.cc, tests/rptest/tests/transaction_kafka_api_test.py
Clients use scatter gather approach and asks all brokers to list transactions. A broker is expected to check hosted txn coordinators only if the broker is the current leader of the coordinators and let a client to merge the results. Fixing list transactions handler to ignore not leader errors.
Fixes https://github.com/redpanda-data/redpanda/issues/11948
* none
=> transactions: fix ListTransactions to return open transactions

tests/rptest/services/redpanda.py, tests/rptest/tests/adjacent_segment_merging_test.py
This PR includes a fix for the default cloud storage cache size used in duck-tape tests
and also tweaks the adjacent segment merging test to use a smaller segment size.
* none
=> retest: fix default cloud storage cache size test

src/v/storage/log_manager.cc, src/v/storage/log_manager.h
Normal housekeeping flow runs everything in a try/catch block so that exceptions don't cause the housekeeping loop to terminate. However, special handling for low-disk scenarios did not guard against exceptions which would have terminated housekeeping preventing retention and compaction from working properly on the affected core.
fixes: #12457
* none
=> storage: fix housekeeping shutdown on uncaught exception

tests/rptest/services/redpanda.py, tests/rptest/tests/adjacent_segment_merging_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12445
=> [v23.2.x] retest: fix default cloud storage cache size test

src/v/cluster/persisted_stm.cc, src/v/storage/disk_log_impl.cc, src/v/storage/disk_log_impl.h, src/v/storage/log.h, src/v/storage/mem_log_impl.cc, src/v/storage/tests/storage_e2e_test.cc, src/v/storage/types.cc, src/v/storage/types.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/11193
=> [v23.1.x] Remove `last_term_start_offset` from `storage::offset_stats`

src/v/archival/ntp_archiver_service.cc, src/v/cloud_storage/async_manifest_view.cc, src/v/cloud_storage/async_manifest_view.h, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/tests/async_manifest_view_test.cc, src/v/ssx/task_local_ptr.h, src/v/ssx/tests/CMakeLists.txt, src/v/ssx/tests/task_local_ptr_test.cc
The `async_manifest_view_cursor` is unsafe by default. When the code uses the cursor to iterate through all segments it is possible to hit a race condition. When the cursor selects STM manifest and then spillover happens the code will skip some segments.
This PR fixes these issues.
* The `task_local_ptr` smart pointer is used to return an object that should only be used in the same time-slice. It gets invalidated after the first scheduling point eliminating potential undefined behaviour when the object might be invalidated or not.
* The `task_local_ptr` is used to return a reference to the current manifest. The caller is supposed to use it in the same time slice (the code was already using it this way but it wasn't enforced).
* When the `async_manifest_view_cursor` is pointed to the STM …
=> cloud_storage: Spillover race prevention

src/go/k8s/tests/e2e/update/02-assert.yaml, src/go/k8s/tests/e2e/update/02-update-resources.yaml
The following CI runs failed due to :
* https://buildkite.com/redpanda/redpanda/builds/33919
* https://buildkite.com/redpanda/redpanda/builds/33913
* https://buildkite.com/redpanda/redpanda/builds/33916
* https://buildkite.com/redpanda/redpanda/builds/33899
Example
```
DEBUG 2023-07-25 01:10:44,080 [shard 0] seastar_memory - Failed to allocate 64 bytes at 0x6fcb423 0x6c4cb30 0x6c56fd9 0x6c9f6ac 0x6c92022 0x6c8e424 0x6cbf1c7 0x6cbd636 0x6cbcab4 0x6e842b4 0x6e368f0 0x6e44d27 0x6e4584c 0x6d1227f 0x6d15921 0x6d12ae6 0x6c175b0 0x6c159a8 0x213c945 0x700c27b /opt/redpanda/lib/libc.so.6+0x2d58f /opt/redpanda/lib/libc.so.6+0x2d648 0x21366a4
--------
seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::httpd::connection::do_response_loop()::$_0, seastar::future<void> …
```
=> k8s: Increase memory instead of decrease in e2e update test

src/go/k8s/tests/e2e/update/02-assert.yaml, src/go/k8s/tests/e2e/update/02-update-resources.yaml
Backport of PR https://github.com/redpanda-data/redpanda/pull/12458
=> [v23.2.x] k8s: Increase memory instead of decrease in e2e update test

src/v/cluster/log_eviction_stm.cc, src/v/cluster/log_eviction_stm.h, src/v/raft/consensus.h
Backport of https://github.com/redpanda-data/redpanda/pull/12470
* none
=> [v23.2.x] backport of https://github.com/redpanda-data/redpanda/pull/12470

src/go/rpk/pkg/cli/cloud/byoc/install.go, src/go/rpk/pkg/config/config.go, tests/docker/Dockerfile, tests/docker/ducktape-deps/byoc-mock, tests/go/byoc-mock/go.mod, tests/go/byoc-mock/go.sum, tests/go/byoc-mock/main.go, tests/rptest/clients/rpk.py, tests/rptest/tests/rpk_plugin_test.py
This PR Introduces:
* A new go binary into the ducktape docker image. This binary it's a mocked plugin which outputs the passed args.
* A test that uses this binary to assert that rpk is passing the required flags to the managed plugin (byoc). This is to test https://github.com/redpanda-data/redpanda/pull/12379
* A new dev override `RPK_CLOUD_TOKEN` that let the user bypass the login process and make rpk use the passed token.
* none
=> rpk: Test `rpk plugin` and managed plugin flag handling.

tests/rptest/services/redpanda.py, tests/rptest/services/redpanda_monitor.py, tests/rptest/tests/storage_failure_injection_test.py
`StorageFailureInjectionTest.test_storage_failure_injection` failed reliably on CDT nodes while waiting for the node to be restarted after a storage failure injection event. Upon further investigation it turned out that a large amount of time could be spent in the kernel in order to clean up resources associate with the Redpanda process. During this time, the process would be in the "uninterruptible sleep" state.
This patch makes the timeout more generous.
Fixes #12396
* none
=> rptest: increase failure injection test timeout

src/go/rpk/go.mod, src/go/rpk/go.sum
Backport of PR https://github.com/redpanda-data/redpanda/pull/12153
=> [v23.2.x] rpk: bump franz-go to v1.14.2 to fix consumer logic race

src/v/cluster/health_monitor_backend.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12313
=> [v23.1.x] Fixed marking node as alive in health monitor backend

src/v/cloud_storage/remote_segment.cc, src/v/storage/parser.h, src/v/storage/parser_errc.h
When the remote segment batch reader gets into a state where no more bytes are consumed, one reason could be because the underlying continuous batch parser has hit end of stream. To help debug this the state of the parser is logged in the error message.
<!--
If the changes in this PR do not need to be mentioned in the release
notes, then don't add a sub-section and simply list `none`, e.g.
* none
=> cloud_storage: log parser error info in read path

tests/rptest/tests/cloud_storage_chunk_read_path_test.py
In certain tests when the cache size is very small and trimming is done with a lot of downloads in progress, it is possible that cache trimming will not be able to free up enough space. This is usually a problem for systems with a well configured cache, but for tests with a small cache these errors should be ignored.
FIXES #12234 
* none
=> ducktape/cloud_storage: Ignore trim failure in test with small cache

.github/workflows/lint.yml
fixes redpanda-data/devprod#800
* none
=> dockerize lint clang-format

src/go/k8s/controllers/redpanda/cluster_controller.go, src/go/k8s/tests/e2e/lost-redpanda-decommission/00-assert.yaml, src/go/k8s/tests/e2e/lost-redpanda-decommission/00-cluster.yaml, src/go/k8s/tests/e2e/lost-redpanda-decommission/01-assert.yaml, src/go/k8s/tests/e2e/lost-redpanda-decommission/01-decommission-and-remove-rp.yaml
Starting from v23.2.x Redpanda Admin API is returning 404 http code when user request to decommission not existent Node ID.
Test fakes a scenario where in GCP VM is replaced with new local disks where PODs are not deleted, but rather they are re-scheduled on to the machine that has the same name, but Redpanda will generate new Redpanda Node ID. In kind environmnent it is hard to simulate local disk replacement without pod getting recreated, those faking none existent annotation overwrite using kubectl.
* Handle in Operator none existent Redpanda Node ID in Pod annotation
Fixes https://github.com/redpanda-data/redpanda/issues/12510
REF
https://github.com/redpanda-data/redpanda/pull/7572
=> k8s: Fix decommission logic when annotation is set

tests/rptest/services/redpanda.py
This was seen in a couple of tests and gives some insight into why the
command fails
* none
=> [ducktape] Add debug message when failing to decode partition manifests

src/v/kafka/server/replicated_partition.cc
Fixes: #12521
* Handle raft shutdown errors for delete record requests
=> delete records: handle raft shutting down errors

src/v/kafka/server/replicated_partition.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12522
Fixes: https://github.com/redpanda-data/redpanda/issues/12525,
=> [v23.2.x] delete records: handle raft shutting down errors

src/go/rpk/pkg/adminapi/admin.go, src/go/rpk/pkg/adminapi/api_config.go, src/go/rpk/pkg/cli/generate/app.go, src/go/rpk/pkg/cli/group/offset_delete.go, src/go/rpk/pkg/cloudapi/api_installpack.go, src/go/rpk/pkg/httpapi/httpapi.go, src/go/rpk/pkg/net/hostport.go, src/go/rpk/pkg/system/grub_test.go, src/go/rpk/pkg/tuners/aggregated_tunable_test.go, src/go/rpk/pkg/tuners/disk_tuner.go, src/go/rpk/pkg/tuners/executors/commands/write_sized_file.go, src/go/rpk/pkg/tuners/float_checker_test.go, src/go/rpk/pkg/tuners/network/nic_test.go
I went ahead and fixed a couple of typos apart from the help text.
* none
=> rpk: fix flag name in help text of `rpk generate app`

src/go/rpk/.goreleaser.yaml, src/go/rpk/pkg/cli/version/version.go
PR #12321 introduced an enhanced `rpk version` command that will use some values injected at build time.
Tested in Linux:
```
$ goreleaser release --snapshot --clean
• starting release...
• loading config file                              file=.goreleaser.yaml
...
• building binaries
• building                                       binary=dist/windows-and-linux_linux_arm64/rpk
• building                                       binary=dist/windows-and-linux_windows_amd64_v1/rpk.exe
• building                                       binary=dist/windows-and-linux_windows_arm64/rpk.exe
• building                                       binary=dist/windows-and-linux_linux_amd64_v1/rpk
...
$ ./dist/windows-and-linux_linux_amd64_v1/rpk version
Version:     v23.2.1-rc7
Git ref:     114da28be
Build …
```
=> rpk: add new linker flags for the enhanced rpk version

src/v/cluster/cluster_utils.cc, src/v/cluster/cluster_utils.h, src/v/cluster/persisted_stm.h, src/v/cluster/types.h, src/v/redpanda/admin/api-doc/debug.json, src/v/redpanda/admin_server.cc, src/v/storage/types.h, tests/rptest/tests/partition_state_api_test.py
Most times we want to be able to answer the following questions about stms when debugging
* what is the last applied for the stm - to see if a specific stm is lagging
* what is the max_collectible_offset for an stm - to check if a partition stm is holding up house keeping
This PR adds this metadata to the partition state debug end point. For each replica of the partition something like following is included in the debug end point for that partition.
```
"stms": [
{
"name": "log_eviction_stm.snapshot",
"last_applied_offset": 6,
"max_collectible_offset": 6
},
{
"name": "tx.snapshot",
"last_applied_offset": 6,
"max_collectible_offset": 6
}
]
```
* none
=> admin/observability/debugging: add stm information to partition debug endpoint

src/go/k8s/controllers/redpanda/cluster_controller.go
Using PodMonitor or ServiceMonitor from Prometheus Operator does not allow attach annotation as metric label. By reporting the same information as label Prometheus/Grafana alerts could give more precise information.
* Report Redpanda Node ID will be reported as label and annotation in Pod metadata
=> Report Redpanda Node ID as label

src/v/storage/segment_set.cc
When we log a disk_log_impl, it logs every segment. This can be stressful for logs that have thousands of local segments, since each segment may stream several hundreds of bytes of text[1], and in some cases cause Redpanda to OOM while logging[2].
This commit mitigates this by reducing the number of segments logged when logging a segment_set.
[1]
```
{offset_tracker:{term:20, base_offset:96, committed_offset:104, dirty_offset:104}, compacted_segment=0, finished_self_compaction=0, generation={18}, reader={/var/lib/redpanda/data/kafka/events/22_378813/96-20-v1.log, (8349 bytes)}, writer={no_of_chunks:64, closed:0, fallocation_offset:33554432, committed_offset:8349, bytes_flush_pending:0}, cache={cache_size=5}, compaction_index:nullopt, closed=0, tombstone=0, …
```
=> storage: don't ostream all segments

tests/rptest/tests/controller_availability_test.py
Added sorting the nodes by id before selecting the ones to stop in `controller_availability_test` this way the test is deterministic as it always stop the two nodes with smallest ids. This way the test stops the current controller and at the same time guarantees that the next candidate is the one with the highest priority from the nodes that were left running.
Fixes: #12275
- none
=> tests: sort nodes before stopping them

src/go/rpk/pkg/cli/group/describe.go, tests/rptest/clients/rpk.py
This PR adds a `TOTAL-LAG` field in the summary of `rpk group describe` and a new flag `--print-lag-per-topic` to print the total lag per topic:
```
$ rpk group describe g1 --print-lag-per-topic 
GROUP        g1
COORDINATOR  1
STATE        Empty
BALANCER     
MEMBERS      0
TOTAL-LAG    11
TOPIC      LAG
oct-10     2
test-seek  9
```
**Before and After:**
Fixes #5214
* rpk now prints the total lag of a group in `rpk group describe` and a new `--print-lag-per-topic` to aggregate the lag per topic.
=> rpk group: total describe lag

tests/rptest/tests/node_pool_migration_test.py
In node pool migration test all the nodes are decommissioned in the same time. In the case of slow debug build it may take longer before decommissioning will progress for an individual node. Made timeout longer to prevent test from being flaky with debug builds.
- none
=> tests: extend progress timeout in node pool migration test

tests/rptest/clients/rpk.py
Changes to rpk caused the COORDINATOR_NOT_AVAILABLE messages to be printed to stderr (makes sense) instead of stdout. Updated to check for this condition in stderr.
Fixes: #12291
* none
=> test: check stderr for coordinator error messages

src/v/cluster/tx_registry_frontend.cc, src/v/cluster/tx_registry_frontend.h, src/v/kafka/server/server.cc, tests/rptest/tests/transaction_kafka_api_test.py
`find_coordinator` creates txn coordinator's topic when it's used for the first time. `list_transactions` api expects the topic to be already created so it used to fail when the api was invoked before `find_coordinator`. Fixed the problem by creating the topic on the first list txns call too.
Fixes https://github.com/redpanda-data/redpanda/issues/11947
* none
=> txns: fix list txns failure when it's used before find_coordinator

src/v/finjector/CMakeLists.txt, src/v/finjector/stress_fiber.cc, src/v/finjector/stress_fiber.h, src/v/redpanda/CMakeLists.txt, src/v/redpanda/admin/api-doc/debug.json, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h, src/v/redpanda/application.cc, src/v/redpanda/application.h, tests/rptest/services/admin.py, tests/rptest/tests/cpu_stress_injection_test.py
This adds a mechanism for adding artificial stress to Redpanda. A
stress_payload is defined as one or multiple fibers that run in the
background, repeatedly counting up to some bounded random values/delays,
until stopped. This will be exposed via admin endpoint in a subsequent
patch.
It's expected that only one stress payload run at a time. The
public interface (stress_fiber_manager) reflects that.
The public interface exposes configuration by delay or by count. In
practice, I found the former helpful in reliably injecting reactor
stalls, and the latter helpful in having finer grained control over how
many cycles are "wasted".
This PR also plugs into ducktape via the admin endpoint, and adds a ducktape test to cover basic functionality. It is left as future work to plug this into the …
=> test utilities for artificially injecting CPU stress

src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_backend.h, src/v/cluster/health_monitor_frontend.cc, src/v/cluster/health_monitor_frontend.h, src/v/kafka/CMakeLists.txt, src/v/kafka/server/tests/CMakeLists.txt, src/v/kafka/server/tests/usage_manager_test.cc, src/v/kafka/server/usage_aggregator.cc, src/v/kafka/server/usage_aggregator.h, src/v/kafka/server/usage_manager.cc, src/v/kafka/server/usage_manager.h, src/v/redpanda/application.cc, tests/rptest/tests/usage_test.py
This change modifies how all nodes aggregate their usage metrics. Usage metrics are currently a feature needed to implement cloud billing. Previously all nodes independently opened their initial bucket on startup. This means that there would be a cluster-wide skew on the open/close interval of all aggregated usage data.
To prevent this skew this PR modifies the behavior to roll back the open time of the first usage bucket to the nearest hour. That way all nodes will have their buckets aligned to an hour and consumers of this data can properly aggregate it by time.
Fixes:  #11451
* Modifies usage metrics to be aligned by the configured interval
=> Align usage metrics to the configured interval

src/v/config/configuration.cc
This reverts commit https://github.com/redpanda-data/redpanda/commit/6d1223d4e4b0489c0fade40a727b9633d506398a.
While the reasoning in above commit for reverting isn't wrong (hard to
reason about and counter cases do exist) from rolling the change
out to cloudv2 it seems the majority of workloads do benefit from having
fetch in a separate scheduling group.
Hence, enable it again by default.
* Re-enable separate fetch scheduling group by default. In the majority of cases as seen in cloudv2 it seems to be beneficial.
=> kafka: Revert "kafka: Disable use of separate fetch scheduling group"

src/v/config/configuration.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12559
=> [v23.1.x] kafka: Revert "kafka: Disable use of separate fetch scheduling group"

src/v/config/configuration.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12559
=> [v23.2.x] kafka: Revert "kafka: Disable use of separate fetch scheduling group"

src/v/cloud_storage/tests/cloud_storage_e2e_test.cc, src/v/cloud_storage/tests/delete_records_e2e_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12495
Fixes: https://github.com/redpanda-data/redpanda/issues/12581,
=> [v23.2.x] tests: bump timeout for waiting on truncation

src/v/storage/segment_set.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12519
=> [v22.3.x] storage: don't ostream all segments

src/v/storage/segment_set.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12519
=> [v23.1.x] storage: don't ostream all segments

src/v/cloud_storage/tests/delete_records_e2e_test.cc, src/v/redpanda/tests/fixture.h, src/v/test_utils/async.h
Currently we have cooperative_spin_wait_with_timeout that throws if a condition
isn't met after a given timeout. The way this typically shows up in tests is
the exception is caught by the test fiber, the test's destructor is called, and
the generic timeout exception is logged after everything is cleaned up. This
makes it difficult to track down issues because it's rarely clear what timed
out.
This patch adds a new boost_require_eventually macro to BOOST_FAIL on timeout,
indicating the log line that failed.
Tests that use this will timeout like:
```
INFO  2023-08-03 12:53:16,023 [shard 0] cluster - members_manager.cc:373 - applying finish_reallocations_cmd, offset: 10, node id: 1
/home/awong/Repos/redpanda/src/v/cloud_storage/tests/delete_records_e2e_test.cc(272): fatal error: in …
```
=> test_utils: macro for waiting on condition

src/v/cluster/topics_frontend.cc, src/v/kafka/server/tests/fetch_test.cc, src/v/kafka/server/tests/list_offsets_test.cc, src/v/redpanda/tests/fixture.h, tests/rptest/tests/topic_creation_test.py
Changes the following
* Replaces empty checkpoint batch with linearizable barrier. Latter works without appending any batches to the log
* When recreating an existing topic, checks the topic table cache first before replicating to the log
Both these problems were contributing to log bloat, especially when a client tries to recreate existing topics.
Fixes https://github.com/redpanda-data/redpanda/issues/12530
* none
=> [backport] [v23.1.x] c/create_topics: improvements to create_topic workflow #12506

tests/rptest/tests/node_pool_migration_test.py, tests/rptest/utils/node_operations.py
When decommissioning many nodes at the same time a test code should not query any of the decommissioned nodes about the status at they may contain metadata which are not updated. When node is decommissioned and removed from the cluster it stops receiving metadata updates so its view of the cluster state is stale.
- none
=> Do not query decommissioned nodes about status

src/go/k8s/tests/e2e/decommission/07-clean.yaml, src/go/k8s/tests/e2e/managed-decommission/02-assert.yaml, src/go/k8s/tests/e2e/managed-decommission/02-probe.yaml, src/go/k8s/tests/e2e/managed-decommission/03-clean.yaml
Inside the decommission E2E test there is almost identical test Kubernetes Job.
As the whole kuttle test suite is running inside redpanda-system namespace
there are events when both Kubernetes Jobs runs at the same time.
It ends in the following error in kuttle output.
```
Job.batch "get-broker-count" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"controller-uid":"468f1776-e429-4e29-8954-1c811a709cf8", "job-name":"get-broker-count"}, Annotations:map[string]string(nil), …
```
=> K8S: Fix decommission E2E tests

tests/rptest/tests/full_disk_test.py
The collection of metrics needed by this test takes more time in debug mode. this pr increases the timeout accordingly
one issue with debug_mode is the increase in latency in acquiring the metrics.
for example:
this is a failure with a debug build.
The test could only do one loop over the metrics and it exhausted the timeout.
```
➜ rg expect_rate vbuild/ducktape/results/2023-07-11--001/FullDiskTest/test_full_disk_no_produce/1/test_log.debug 
486:[DEBUG - 2023-07-11 13:34:57,026 - expect_rate - expect_rate - lineno:104]: (waiting, 0.0/5 sec) bytes: 181813.0
488:[INFO  - 2023-07-11 13:35:21,601 - expect_rate - expect_rate - lineno:96]: Rate target met: 16630.3 bytes/sec over the last 24.575 sec.
502:[DEBUG - 2023-07-11 13:35:27,834 - expect_rate - expect_rate - lineno:104]: (waiting, 0.0/5 …
```
=> t/full_disk_test: longer timeout in debug_mode

src/v/cloud_storage/remote_partition.cc
Though we were previously syncing the manifest before proceeding to read, there is room for a spillover to happen after syncing before returning to the fetch fiber.
* Fixes a race between remote storage spillover that could result in fewer Kafka records being returned to consumers.
=> cloud_storage: retry cursor sync when racing with spillover

src/v/archival/ntp_archiver_service.cc, src/v/archival/ntp_archiver_service.h, src/v/archival/scrubber.cc, src/v/cloud_roles/signature.h, src/v/cloud_roles/tests/signature_test.cc, src/v/cloud_storage/recovery_utils.cc, src/v/cloud_storage/remote.cc, src/v/cloud_storage/remote.h, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/tests/remote_segment_test.cc, src/v/cloud_storage/tests/remote_test.cc, src/v/cloud_storage_clients/abs_client.cc, src/v/cloud_storage_clients/abs_client.h, src/v/cloud_storage_clients/client.h, src/v/cloud_storage_clients/s3_client.cc, src/v/cloud_storage_clients/s3_client.h, src/v/cloud_storage_clients/test_client/abs_test_client_main.cc, src/v/cloud_storage_clients/test_client/s3_test_client_main.cc, src/v/cloud_storage_clients/tests/s3_client_test.cc, tests/docker/docker-compose.yml
Previously, Redpanda would apply tags to objects uploaded to S3 and ABS. These tags were not used anywhere and caused compatibility issues when Redpanda was used with a storage account where "Hierachical Namespaces" were enabled.
This commit removes the tagging.
Related #11578
* Remove unused object tagging within cloud storage
=> cloud_storage: remove remote object tagging

.github/labeler.yml
The js directory has been deleted, and in #12322 we're introducing the
SDK for golang Wasm data transforms. More build/CI changes will come in
later PRs.
* none
=> Add area/wasm label to transform SDK

src/v/cluster/tx_gateway_frontend.cc, src/v/cluster/tx_gateway_frontend.h
`ntp_meta->get_assignments()` returns a reference to a collection and `expire_old_txs` iterates it asynchronously so there is a chance of the collection being modified out of `expire_old_txs` leading to the iterator invalidation and the crash. Fixing the problem by making a copy before iterating.
Fixes #12503
* none
=> Fix segmentation fault in `tx_gateway_frontend::expire_old_txs`

src/v/cluster/tx_registry_frontend.cc, src/v/cluster/tx_registry_frontend.h, src/v/kafka/server/server.cc, tests/rptest/tests/transaction_kafka_api_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12116
Fixes #12583
=> [v23.2.x] txns: fix list txns failure when it's used before find_coordinator

src/v/storage/disk_log_appender.cc, src/v/storage/disk_log_appender.h, src/v/storage/disk_log_impl.cc, src/v/storage/disk_log_impl.h, src/v/storage/tests/CMakeLists.txt, src/v/storage/tests/storage_e2e_fixture_test.cc
Based on https://github.com/redpanda-data/redpanda/pull/12546 to repro a crash in a test.
H/T to VladLazar for a similar change that inspired this one:
https://github.com/VladLazar/redpanda/commit/682aea582044225132987d23ef80406198526db4
https://github.com/redpanda-data/redpanda/pull/12516
The problem statement:
```
We have seen a couple of races between the application of `segment.ms`
and the normal append path. They had the following pattern in common:
1. application of `segment.ms` begins
2. a call to `segment::append` is interleaved
3. the append finishes first and and advances the dirty offsets, which
the rolling logic in `segment.ms` does not expect
-- or --
4. `segment.ms` releases the current appender while the append is
ongoing, which the append logic does not expect
```
The …
=> storage: fix race between segment.ms and appends

src/v/archival/archival_policy.cc, src/v/archival/ntp_archiver_service.cc, src/v/archival/segment_reupload.cc, src/v/archival/segment_reupload.h, src/v/archival/tests/ntp_archiver_reupload_test.cc, src/v/archival/tests/ntp_archiver_test.cc, src/v/archival/tests/service_fixture.cc, src/v/cloud_storage/tests/cloud_storage_e2e_test.cc, src/v/cloud_storage/tests/delete_records_e2e_test.cc, src/v/cloud_storage/tests/produce_utils.h, src/v/cluster/tests/eviction_stm_test.cc, src/v/cluster/tests/rm_stm_tests.cc, src/v/cluster/tests/tx_compaction_tests.cc, src/v/cluster/tests/tx_compaction_utils.h, src/v/kafka/server/tests/produce_consume_test.cc, src/v/resource_mgmt/storage.cc, src/v/storage/disk_log_impl.h, src/v/storage/log.h, src/v/storage/log_manager.cc, src/v/storage/tests/log_truncate_test.cc, src/v/storage/tests/storage_e2e_test.cc
We've been hiding behind `dynamic_cast` instead of being honest with ourselves about the unpleasant parts of the log interface. This PR changes that by surfacing the external interfaces to storage::log (it's really not so bad). In any case, the disk_log_builder is now the only remaining user of `dynamic_cast<disk_log_impl>` as it uses a bunch of low-level interfaces.
This change is important as we look towards evolving the local log implementation--we need to be able to clearly see the interface we are trying to support.
* none
=> [storage]: storage::log interface self-honesty

tests/rptest/clients/rpk.py, tests/rptest/services/redpanda.py, tests/rptest/services/rpk_consumer.py, tests/rptest/test_suite_cloud.yml, tests/rptest/tests/rpk_topic_test.py, tests/rptest/tests/services_self_test.py
Updates to the redpanda ducktape test helpers `RpkTool` and `RpkConsumer` so they can connect to redpanda cloud. This enables `RpkToolTest`, which does various topic operations, to be able to test redpanda cloud.
Fixes https://github.com/redpanda-data/cloudv2/issues/7909
Output of manual test run against redpanda cloud:
```console
bash$ ducktape --debug --globals=/home/ubuntu/redpanda/tests/globals.json --cluster=ducktape.cluster.json.JsonCluster --cluster-file=/home/ubuntu/redpanda/tests/cluster.json --test-runner-timeout=3600000 tests/rptest/tests/rpk_topic_test.py::RpkToolTest
...
test_id:    rptest.tests.rpk_topic_test.RpkToolTest.test_consume_as_group
run time:   25.118 seconds
------------------------------------------------------------------------------------------- …
```
=> rptest: run `rpk` tests against redpanda cloud

src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_segment.cc, src/v/kafka/server/connection_context.cc, src/v/kafka/server/connection_context.h, src/v/kafka/server/handlers/fetch.cc, src/v/kafka/server/handlers/fetch.h, src/v/kafka/server/handlers/list_offsets.cc, src/v/kafka/server/request_context.h, src/v/kafka/server/server.cc, src/v/net/connection.h, src/v/ssx/abort_source.h, src/v/ssx/tests/CMakeLists.txt, src/v/ssx/tests/abort_source_test.cc, src/v/storage/types.cc
kafka: Abort fetch and list_offsets (timequery) when the client disconnects for timely resource cleanup.
* Add an `abort_source` to `connection_context`
* This needs to be sharded as some requests span arbitrary shards
* Abort the `abort_source` when the socket is disconnected
* Wire up the `abort_source` to the `request_context` and into:
* `fetch` 
* `list_offsets` (timequery)
The primary goal is to improve the situation for https://github.com/redpanda-data/redpanda/issues/11799
Testing can be done with something like:
```
kcat -G foo -X fetch.wait.max.ms=60000
```
And the kill the client either gracefully or will `kill -9`.
* kafka: Abort `fetch` and `list_offsets` (timequery) when the client disconnects for timely resource cleanup.
=> kafka: Abort fetch and list_offsets when client disconnects

src/v/cluster/tests/health_monitor_test.cc, src/v/storage/types.cc
Since `storage::disk::fsid` is not serialized we can not assert that its
value is equal when a data structure is sent over the RPC transport.
Fixes: #12636
- none
=> Do not compare fsid when checking if reports are equal

src/v/cluster/controller_api.cc, src/v/cluster/scheduling/leader_balancer.cc, src/v/cluster/shard_table.h, src/v/raft/service.h, src/v/raft/tests/raft_group_fixture.h, src/v/redpanda/admin_server.cc
Previously when querying for `shard_id` of a Raft group, caller was forced to use `contains` and `shard_for` methods instead of simply calling shard for. This patch makes the interface more convenient.
- none
=> Changed api of `shard_table` not to be forced to do two lookups

src/v/raft/consensus.cc
Redpanda raft protocol implementation keeps track of the latest flushed offset. It does not require access `log::committed_offset`.
- none
=> Use `_flushed_offset` instead of `log::committed_offset`

src/v/cluster/tests/health_monitor_test.cc, src/v/storage/types.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12630
Fixes: https://github.com/redpanda-data/redpanda/issues/12651,
=> [v23.2.x] Do not compare fsid when checking if reports are equal

cmake/oss.cmake.in, cmake/testing.cmake, src/v/test_utils/CMakeLists.txt, src/v/test_utils/gtest_main.cc, src/v/test_utils/test.h, src/v/test_utils/tests/CMakeLists.txt, src/v/test_utils/tests/gtest_test.cc, tools/cmake_test.py
Adds Google Test and experimental support for Seastar-enabled testing with the framework so that we can take advantage of gtest's nice support for building test fixtures and value parameterized tests.
* none
=> [test]: add support for google test framework

tests/rptest/tests/consumer_group_recovery_tool_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12317
Fixes: https://github.com/redpanda-data/redpanda/issues/12640,
Changes from force-push `1ab1b2a`:
- Fix linter problems
=> [v22.3.x] tests/cg-recovery: retry list groups

tests/docker/ducktape-deps/kgo-verifier
Franz-go within kgo-verifier needs updating. This PR updates the SHA. For context, see https://redpandadata.slack.com/archives/C044RD18NMV/p1691076044618439?thread_ts=1691071206.358289&cid=C044RD18NMV
Merge https://github.com/redpanda-data/kgo-verifier/pull/39 first, then this PR.
Fixes: https://github.com/redpanda-data/redpanda/issues/12571
* none
=> tests/kgo-verifier: update to latest SHA

src/v/cluster/tx_gateway_frontend.cc, tests/rptest/tests/transaction_kafka_api_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12116
Fixes #12576
=> [v23.1.x] txns: fix list txns failure when it's used before find_coordinator

src/v/cluster/metrics_reporter.cc, src/v/cluster/metrics_reporter.h, tests/rptest/tests/metrics_reporter_test.py
Add an identifiable string to the report: `id_hash`
Changes from force-push `44ee865`:
- Use hashlib to check the returned value from Redpanda
* none
=> cluster: include a hash in the metrics reporter

src/v/pandaproxy/error.cc, src/v/pandaproxy/error.h, src/v/pandaproxy/schema_registry/error.cc, src/v/pandaproxy/schema_registry/error.h, src/v/pandaproxy/schema_registry/errors.h, src/v/pandaproxy/schema_registry/store.h, src/v/pandaproxy/schema_registry/test/store.cc, tests/rptest/tests/schema_registry_test.py
If a request for config fails, the error 40408 should be returned regardless of whether the subject exists.
Fixes #12654
* Schema Registry: Report 40408 if a subject config request fails
=> schema_registry: Add error compatibility_not_found

src/v/cloud_storage/async_manifest_view.cc, tests/rptest/tests/adjacent_segment_merging_test.py
The code in the seek method calls async method
'get_materialized_manifest' to get the manifest based on query (offset). Then, after a scheduling point it caches the start offset by querying the STM manifest.
The following sequence of events is possible:
- Initially, there are no spillover manifests;
- 'seek' is calling 'get_materialized_manifest(0)';
- 'get_materialized_manifest' finds STM manifest which at this point starts with offset 0 and returns it.
- Concurrently, spillover happens and the STM manifest gets truncated. The segment with offset 0 gets moved to the spillover manifest.
- The 'seek' method wakes up and caches the start offset of the manifest which is not 0 at this point.
- The client sees the partition that starts from unexpected offset.
This PR fixes this by caching the …
=> cloud_storage: Fix race in async_manifest_view_cursor

src/go/transform-sdk/LICENSE, src/go/transform-sdk/abi.go, src/go/transform-sdk/doc.go, src/go/transform-sdk/example_mirror_test.go, src/go/transform-sdk/example_regexp_filter_test.go, src/go/transform-sdk/example_transcoding_test.go, src/go/transform-sdk/go.mod, src/go/transform-sdk/guest_callbacks.go, src/go/transform-sdk/internal/rwbuf/rwbuf.go, src/go/transform-sdk/internal/rwbuf/rwbuf_test.go, src/go/transform-sdk/internal/rwbuf/unsafe.go, src/go/transform-sdk/sdk.go, src/go/transform-sdk/serialize.go, src/go/transform-sdk/serialize_test.go, src/go/transform-sdk/stub_abi.go
This patch set implements the initial ABI + SDK for Redpanda's data transforms.
There are 3 major pieces to Wasm Data Transforms:
- rpk: the `rpk transform` commands that allow you to write, manage and deploy transforms
- sdk: this golang module, which is the set of helper libraries to give users a idiomatic and user friendly interface to write these transforms and adhere to the ABI contract that the broker expects.
- core: there will be two new subsystems, transform and wasm. The wasm subsystem will abstract the actual wasm engine and contain the actual ABI contract that the SDK will provide. The second subsystem transform, will be manage the lifecycle of a transform and leverage the engine exposed in the wasm subsystem to actually perform the transforms.
See the individual commits for …
=> Initial Wasm Golang Transform SDK

src/v/cluster/topics_frontend.cc, src/v/kafka/server/tests/fetch_test.cc, src/v/kafka/server/tests/list_offsets_test.cc, src/v/redpanda/tests/fixture.h, tests/rptest/tests/topic_creation_test.py
Changes the following
* Replaces empty checkpoint batch with linearizable barrier. Latter works without appending any batches to the log
* When recreating an existing topic, checks the topic table cache first before replicating to the log
Both these problems were contributing to log bloat, especially when a client tries to recreate existing topics.
* none
=> [v22.3.x] c/create_topics: improvements to create_topic workflow #12531

src/v/archival/ntp_archiver_service.cc, src/v/archival/ntp_archiver_service.h, src/v/cluster/archival_metadata_stm.cc, src/v/cluster/archival_metadata_stm.h, src/v/cluster/id_allocator_stm.cc, src/v/cluster/persisted_stm.cc, src/v/cluster/persisted_stm.h, src/v/cluster/rm_stm.cc, src/v/cluster/tests/rm_stm_tests.cc, src/v/cluster/tm_stm.cc
Backport of https://github.com/redpanda-data/redpanda/pull/9633
Partial backport of https://github.com/redpanda-data/redpanda/pull/9237
Fixes https://github.com/redpanda-data/redpanda/issues/10775
CONFLICTS:
- cloud stress test doesn't exist in this branch
At a high level, the archival loop is implemented with the following steps:
```
while not aborted:
wait until node is leader
sync that offsets from previous terms are applied
while node is leader:
upload segments based on what is in the manifest
replicate changes to manifest via archival stm
wait for archival stm update to be applied (updates manifest)
```
The archival loop currently expects that updates to the manifest are either driven by it (or the housekeeping service, though ignoring this for the sake of example). One case where …
=> [v23.1.x] archival: remove timeouts from archival_metadata_stm

src/v/archival/ntp_archiver_service.cc, src/v/cluster/archival_metadata_stm.cc, src/v/cluster/archival_metadata_stm.h, src/v/cluster/id_allocator_stm.cc, src/v/cluster/persisted_stm.cc, src/v/cluster/persisted_stm.h, src/v/cluster/rm_stm.cc, src/v/cluster/tests/rm_stm_tests.cc, src/v/cluster/tm_stm.cc, src/v/raft/state_machine.cc, src/v/raft/state_machine.h
Backport of https://github.com/redpanda-data/redpanda/pull/9633
Fixes https://github.com/redpanda-data/redpanda/issues/10777
CONFLICTS:
- cloud stress test doesn't exist in this branch
- reimplemented the broken semaphore fix, git wasn't able to apply cleanly
At a high level, the archival loop is implemented with the following steps:
```
while not aborted:
wait until node is leader
sync that offsets from previous terms are applied
while node is leader:
upload segments based on what is in the manifest
replicate changes to manifest via archival stm
wait for archival stm update to be applied (updates manifest)
```
The archival loop currently expects that updates to the manifest are either driven by it (or the housekeeping service, though ignoring this for the sake of example). One case where …
=> [v22.3.x] archival: remove timeouts from archival_metadata_stm

src/v/test_utils/gtest_main.cc, src/v/test_utils/test.h, src/v/test_utils/tests/gtest_test.cc
This means that if you have class members that connect to seastar
primatives (like ss::lw_shared_ptr) then everything needs to be
constructed on the same seastar thread otherwise assertions get
triggered.
* none
=> Run all of gtest within a seastar context

src/v/cluster/archival_metadata_stm.cc
They're scary when they happen because they indicate a bug in our logic. Let's promote to error to make sure we see them when they happen.
* none
=> archival: promote some guardrail warnings to error

src/v/cloud_storage/async_manifest_view.cc, tests/rptest/tests/adjacent_segment_merging_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12665
Fixes: https://github.com/redpanda-data/redpanda/issues/12702,
=> [v23.2.x] cloud_storage: Fix race in async_manifest_view_cursor

.github/workflows/transform-sdk-build.yml
Can be merged after #12322 is merged.
* none
=> Add a github workflow to test the golang transform SDK

src/go/rpk/pkg/cli/acl/user/create.go, src/go/rpk/pkg/cli/acl/user/delete.go, src/go/rpk/pkg/cli/acl/user/list.go, src/go/rpk/pkg/config/format.go, src/go/rpk/pkg/config/redpanda_yaml.go, src/go/rpk/pkg/config/rpk_yaml.go, src/go/rpk/pkg/config/rpk_yaml_test.go
Potential future improvements could include documentation on the
shape(ish) output, but simply knowing the shape can be quite beneficial.
We also will error hard (panic) if our own code uses different types for
`--format help` vs. `--format json/yaml`
Also adds support for `--format help` to the acl user commands that currently support `--format`.
* none
=> rpk: support `--format help` to print the shape(ish) of json/yaml output

src/v/cloud_storage/tests/manual_fixture.h, src/v/cloud_storage/tests/read_replica_test.cc, src/v/cluster/archival_metadata_stm.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/kafka/server/tests/produce_consume_utils.cc, src/v/redpanda/tests/fixture.h, src/v/storage/log_manager.cc
I intend on writing more tests that use C++ fixtures, and it generally is helpful to have a few things on hand. This PR introduces a few QOL improvements:
- makes archival metadata stm's max collectible offset public
- adds a config to disable the local storage housekeeping loop, for use in tests
- makes the test kafka_produce_transport use acks=-1
- adds the ability to tweak replication factor when adding a topic to a redpanda_thread_fixture
- adds a fixture that spins up two Redpanda applications with tiered storage
These are pulled out of a separate PR https://github.com/redpanda-data/redpanda/pull/12643 that uses these to test tiered storage with mismatched on-disk segment layouts between replicas.
* none
=> tests: miscellaneous improvements for tiered storage C++ tests

tests/rptest/clients/rpk.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12121
=> [v23.2.x] Print output from Rpk commands that timeout in ducktape

src/v/cloud_storage/remote_partition.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12621
=> [v23.2.x] cloud_storage: retry cursor sync when racing with spillover

tests/rptest/scale_tests/tiered_storage_reader_stress_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12374
Fixes: https://github.com/redpanda-data/redpanda/issues/12387,
=> [v23.2.x] tests: disable retention.ms in reader stress test

src/v/redpanda/admin_server.cc, tests/rptest/tests/metrics_reporter_test.py
We should account for carriage return in the license and the metrics reporter test should skip if the license env var is unset.
Fixes: https://github.com/redpanda-data/redpanda/issues/12719
Fixes: https://github.com/redpanda-data/redpanda/issues/12718
* none
=> Skip metrics test on no license

tests/rptest/services/openmessaging_benchmark.py, tests/rptest/services/redpanda.py, tests/rptest/services/redpanda_cloud.py, tests/rptest/services/templates/omb_driver.yaml, tests/rptest/test_suite_cloud.yml
Updates to the ducktape class `OpenMessagingBenchmark` to enable it to run against redpanda cloud by adding SASL and TLS to the driver configuration as well as other small changes. This PR does not change the functionality or expected outcome of existing ducktape tests that use omb.
Also updated `test_suite_cloud.yml` so it runs a test using `OpenMessagingBenchmark`.
This PR also needs PR #12725 to be merged as well.
Example run with redpanda cloud configured in `globals.json`:
```console
bash$ ducktape --debug --globals=/home/ubuntu/redpanda/tests/globals.json --cluster=ducktape.cluster.json.JsonCluster --cluster-file=/home/ubuntu/redpanda/tests/cluster.json --test-runner-timeout=3600000 tests/rptest/tests/services_self_test.py::OpenBenchmarkSelfTest
test_id: …
```
=> rptest: enable OpenMessagingBenchmark to run against redpanda cloud

tests/docker/ducktape-deps/omb
To bring in changes that work with redpanda cloud. Specifically, need changes from https://github.com/redpanda-data/openmessaging-benchmark/pull/58 so when omb is benchmarking redpanda cloud, it doesn't try to delete the `_schema` topic.
Cannot bump to the [tip of main](https://github.com/redpanda-data/openmessaging-benchmark/tree/7d0251277a3582ffabcffc6c5a44b3af1b7df275) because it would bring in other changes that need adjustment to how omb is deployed. This bump is the simplest, for now. This PR does not change the functionality or expected outcome of existing ducktape tests that use omb.
Comparison of changes this bump brings in: https://github.com/redpanda-data/openmessaging-benchmark/compare/2674d6...8411e4a
* none
=> dt/docker: bump redpanda-data/openmessaging-benchmark to 8411e4a

src/v/kafka/server/usage_aggregator.cc
This bug was first observed as a CI issue reporting an unhandled exceptional future. This seemed strange as there are exception handlers surrounding the few call sites where a mutex is used within UBB, and they contain a catch clause for std exception.
The cause of a bug is a call to `mutex.get_units()` without a preceeding `co_await` in the context of a coroutine. This means the mutex is not being used properly and in the event it contains an exception it will not be caught by the handler because the value returned by `get_units()` is a future not the unwrapped value.
Fixes: #12733
* Fixes a bug in usage framework that where unhandled exceptions may be observed
=> Fix misappropriate use of mutex::get_units in usage based billing

src/v/net/conn_quota.cc
We need to await acquiring this lock. Found via grep after #12755
* none
=> co_await mutex hold in conn_quota

tests/rptest/services/redpanda.py, tests/rptest/tests/e2e_shadow_indexing_test.py
Empirically, segments may be uploaded ~1/partition/sec, particularly on dockeriszed environments. Thus, the current timeout for the number of segments we want to generate is flaky.
Fixes #11268
Also fixes slow scrubbing, from when there are too many segments to analyze in 30s.
Fixes #11698
Remaining flakiness appears to be fixed by https://github.com/redpanda-data/redpanda/pull/12756
* none
=> e2e_shadow_indexing_test: bump timeout for workload

src/v/cluster/partition.cc
This was found via grep after #12755
* none
=> Await acquiring the manifest lock

src/go/k8s/controllers/redpanda/cluster_controller.go, src/go/k8s/controllers/redpanda/cluster_controller_configuration_drift.go, src/go/k8s/controllers/redpanda/console_controller.go, src/go/k8s/controllers/redpanda/metric_controller.go, src/go/k8s/controllers/redpanda/redpanda_controller.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/12760
=> [v23.2.x] Context per reconciler

src/v/archival/ntp_archiver_service.cc, src/v/cloud_roles/signature.cc, src/v/cloud_storage_clients/abs_client.cc, src/v/cloud_storage_clients/abs_client.h, src/v/cloud_storage_clients/abs_error.cc, src/v/cloud_storage_clients/abs_error.h, src/v/cloud_storage_clients/client.h, src/v/cloud_storage_clients/client_pool.cc, src/v/cloud_storage_clients/client_pool.h, src/v/cloud_storage_clients/configuration.cc, src/v/cloud_storage_clients/configuration.h, src/v/cloud_storage_clients/s3_client.cc, src/v/cloud_storage_clients/s3_client.h, src/v/cloud_storage_clients/test_client/abs_test_client_main.cc, src/v/cloud_storage_clients/tests/CMakeLists.txt, src/v/cloud_storage_clients/tests/s3_client_test.cc, src/v/cloud_storage_clients/tests/util_test.cc, src/v/cloud_storage_clients/util.cc, src/v/cloud_storage_clients/util.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/application.cc, src/v/redpanda/application.h, src/v/utils/stop_signal.h
This PR aims to make Redpanda compatible with Azure storage accounts that have [HNS](https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-namespace) enabled.
In brief, when HNS is enabled, each container in the account will mimic file system like semantics.
This changes semantics for deletions and listing of objects:
1. Deleting a file does not delete the directories. For instance, deleting `a/log.txt` leaves behind the `a` blob.
2. Directories cannot be deleted via the [Blob Service REST API](https://learn.microsoft.com/en-us/rest/api/storageservices/blob-service-rest-api).
3. Listings include directory blobs by default.
(1) and (2) are solved by using the [Data Lake Storage Gen2 REST API](https://learn.microsoft.com/en-us/rest/api/storageservices/data-lake-storage-gen2 …
=> cloud_storage: become compatible with storage account where Hierarchical Namespaces are enabled

src/v/storage/segment_set.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12519
=> [v23.2.x] storage: don't ostream all segments

src/v/cloud_storage/tests/cloud_storage_e2e_test.cc, src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_types.cc, src/v/cluster/health_monitor_types.h, src/v/cluster/partition.h, src/v/storage/disk_log_impl.cc, src/v/storage/disk_log_impl.h, src/v/storage/log.h, src/v/storage/log_manager.cc, src/v/storage/log_manager.h
The partition balancer needs to know how much of a partition's size is easily reclaimable. That is, the amount of data that has grown best-effort above local retention threshold. This will be used to adjust the balancer's view of how much free space is available on a node.
Note: this is needs to be backported, but we should wait until we've accumulated changes and tests related to updates of the partition balancer as well. These are being track in https://github.com/redpanda-data/core-internal/issues/719
Fixes: https://github.com/redpanda-data/core-internal/issues/725
* none
=> [storage]: add local retention reclaimable to partition health report

tests/rptest/services/redpanda_cloud.py
=> rptest: Fixes Cloud Cluster tests error for vpc-id and owner-id

cmake/testing.cmake, src/go/kreq-gen/CMakeLists.txt, src/v/kafka/protocol/tests/CMakeLists.txt
avoid rebuilding kreq-generator when the tree is clean.
* none
=> Avoid kreq gen build all

tests/docker/cdt_ducktape_deps.sh
byoc-mock was introduced in #12456 to ducktape
tests. This commit adds the dependency to CDT.
This PR and vtools/2021 Fixes #12508 
* none
=> test-infra: add byoc-mock to cdt dependencies.

src/v/rpc/transport.cc, src/v/ssx/future-util.h
Travis mentioned in slack that `ssx::handle_shutdown_errors` was showing up in profiles.
This attempts to address that problem by creating less continuations when dispatching sends in the rpc transport layer. Additionally, switch `ssx::handle_shutdown_errors` to be a corountine.
* none
=> Optimize send path error handling

src/v/cloud_storage/async_manifest_view.h, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment.h, tests/rptest/tests/shadow_indexing_tx_test.py
cloud_storage: avoid writing empty tx ranges to cache
Previously the check for metadata_size_hint==0 was
initializing `_tx_range`, but that didn't stop `do_hydrate_txrange`
from running, attempting to download the transaction manifest,
and usually generating a 404 response and putting an empty
manifest into the cache.
After this change, segments with no tx manifest entries simply
issue no request for the tx manifest, and write nothing to
the cache for tx manifest.
Plus a test for this, and a couple of cleanup commits -- noticed this stuff while updating internals docs.
While this isn't strictly a functional bug fix, it is worth backporting because:
- with this change, SREs can start monitoring for 404s without having to deal with a load of false positives from `.tx` GETs.
- it is a …
=> cloud_storage: avoid attempting to GET and cache empty transaction manifests

src/v/archival/ntp_archiver_service.cc, src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/partition_manifest.h, src/v/cloud_storage/remote_partition.cc, src/v/cluster/archival_metadata_stm.cc, src/v/cluster/archival_metadata_stm.h, src/v/cluster/partition.cc
The manifest lock was needed because JSON serialization took long. The manifest might have changed during the process and the result would be invalid. Since we moved to binary format we no longer need to use this lock. The only place where we're using this lock is admin API (the endpoint returns JSON object). To avoid data races there this commit copies the entire manifest before serializing it to JSON. It also removes the lock.
* none
=> cloud_storage: Remove manifest lock

tests/rptest/services/redpanda.py
Removing unused import that was slipped through when backporting #12750
* none
=> [v23.2.x] Hotfix after backport of 12750

src/v/kafka/server/usage_aggregator.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12755
Fixes: https://github.com/redpanda-data/redpanda/issues/12764,
=> [v23.2.x] Fix misappropriate use of mutex::get_units in usage based billing

src/v/kafka/server/usage_aggregator.cc, src/v/kafka/server/usage_aggregator.h, tests/rptest/tests/usage_test.py, tests/rptest/utils/functional.py
This patch fixes two bugs observed with usage based billing:
1. The timer would sometimes appear to not fire on the configured interval
2. The correctly detected erraneous windows were not tossed aside from the result set
The root cause of the issues was a method called `rearm_window_timer`, it was erraneously querying `ss::lowres_clock` for wall clock timestamps to use in calculations to determine when to arm the timer so that it will close at exactly the next interval
* Fixes a bug in usage based billing where timer doesn't fire at configured interval.
* Fixes a bug in usage based billing where windows with inconstant begin/end timestamps are not tossed from the result set.
=> Fix observed window drift in usage based billing

src/v/kafka/server/usage_aggregator.cc, src/v/kafka/server/usage_aggregator.h, tests/rptest/tests/usage_test.py, tests/rptest/utils/functional.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12780
=> [v23.2.x] Fix observed window drift in usage based billing

src/v/rpc/transport.cc, src/v/ssx/future-util.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/12472
=> [v23.2.x] Optimize send path error handling

src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/api/api-doc/schema_registry_header.json, src/v/pandaproxy/schema_registry/service.cc, tests/rptest/tests/schema_registry_test.py
`referencedBy` is a typo, but has been around a long time, so replace it with `referencedby`, but keep it as an alias.
Fixes #12729
Closes #12745
The reference will need updating
https://docs.redpanda.com/docs/api/pandaproxy-schema-registry/
1. Version has been bumped from `1.0.1` to `1.0.2`.
2. Introduce `GET subjects/{subject}/versions/{version}/referencedby`
3. Deprecate `GET subjects/{subject}/versions/{version}/referencedBy`
* Schema Registry: Introduce `GET subjects/{subject}/versions/{version}/referencedby`
=> schema_registry: Alias referencedby by referencedBy 

tests/docker/Dockerfile, tests/docker/ducktape-deps/byoc-mock
This path mismatch triggers an error in cdt, first this commits deals with that and another PR will
add this dependency to vtools.
* none
=> tests: fix path for rpk byoc-mock

src/v/cloud_storage/tests/produce_utils.h, src/v/finjector/CMakeLists.txt, src/v/finjector/stress_fiber.cc, src/v/finjector/stress_fiber.h, src/v/kafka/server/tests/CMakeLists.txt, src/v/kafka/server/tests/produce_consume_utils.cc, src/v/kafka/server/tests/produce_consume_utils.h, src/v/redpanda/CMakeLists.txt, src/v/redpanda/admin/api-doc/debug.json, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h, src/v/redpanda/application.cc, src/v/redpanda/application.h, src/v/redpanda/tests/fixture.h, src/v/storage/disk_log_appender.cc, src/v/storage/disk_log_appender.h, src/v/storage/disk_log_impl.cc, src/v/storage/disk_log_impl.h, src/v/storage/log.h, src/v/storage/log_manager.cc, src/v/storage/mem_log_impl.cc, src/v/storage/tests/CMakeLists.txt, src/v/storage/tests/storage_e2e_fixture_test.cc
Backport of https://github.com/redpanda-data/redpanda/pull/12565
Pulls in:
- a commit to rename do_housekeeping -> apply_segment_ms
- produce_consume_utils to test
- stress fibers to test
* Avoids a race between appends and application of segment.ms that could result in a crash.
=> [v23.1.x] storage: fix race between segment.ms and appends

tests/docker/cdt_ducktape_deps.sh
Backport of PR https://github.com/redpanda-data/redpanda/pull/12775
Fixes: https://github.com/redpanda-data/redpanda/issues/12785,
=> [v23.2.x] test-infra: add byoc-mock to cdt dependencies.

tests/rptest/tests/node_pool_migration_test.py, tests/rptest/tests/nodes_decommissioning_test.py, tests/rptest/tests/scaling_up_test.py
Scaling up tests were previously using `VerifiableConsumer/Producer` services to generate the traffic. Those services relay on ducktape engine to analyze standard output and parse events. This is ineffective and as a result python wrapper for verifiable service may lag behind what was actually consumed/produced. To address this issue changed `ScalingUpTest` to use `kgo-verifier`
Fixes: #12826
Fixes: #12813
- none
=> Migrated scaling up tests to kgo services

src/v/cluster/metrics_reporter.cc, src/v/cluster/metrics_reporter.h, src/v/redpanda/admin_server.cc, tests/rptest/tests/metrics_reporter_test.py
Backport two PRs
1. https://github.com/redpanda-data/redpanda/pull/12671
2. https://github.com/redpanda-data/redpanda/pull/12727
Fixes https://github.com/redpanda-data/redpanda/issues/12799
Fixes https://github.com/redpanda-data/redpanda/issues/12803
* none
=> [v23.2.x] cluster: include a hash in the metrics reporter

src/v/ssx/future-util.h, src/v/storage/log_manager.cc, src/v/storage/log_manager.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/12459
Fixes: https://github.com/redpanda-data/redpanda/issues/12461,
=> [v23.2.x] storage: fix housekeeping shutdown on uncaught exception

src/go/rpk/pkg/adminapi/api_broker.go, src/go/rpk/pkg/cli/redpanda/admin/brokers/decommission-status.go
This PR adds a new section in the output of the decommission-status command per the change in https://github.com/redpanda-data/redpanda/pull/11899. If some partitions hit allocation failures during decommission, the output looks like this. Otherwise, the ALLOCATION FAILURES section doesn't appear.
```
$ rpk redpanda admin brokers decommission-status 3
ALLOCATION FAILURES
===================
[kafka/test/0 kafka_internal/id_allocator/0]
DECOMMISSION PROGRESS
=====================
NAMESPACE-TOPIC  PARTITION  MOVING-TO  COMPLETION-%  PARTITION-SIZE
<snip>
```
Fixes https://github.com/redpanda-data/redpanda/issues/12030
* rpk: show allocation failures in decommission-status
=> rpk: show allocation failures in decommission-status

tests/rptest/services/redpanda_cloud.py
New optional arg `cluster_config.install_pack_ver` for `globals.config`.
Before this PR, only the latest install pack was used for tests. This PR leaves the default as `latest` but allows configuration to a specific version when creating redpanda cloud clusters for ducktape tests.
Related issue https://github.com/redpanda-data/cloudv2/issues/7902
* none
=> rptest: add install_pack_ver optional arg to CloudClusterConfig

tests/docker/ducktape-deps/librdkafka
building the arm64 AMI image (for cdt) fails because the librdkafka version is too old to build confluent-kafka. from the err log:
```
==> redpanda-testing.amazon-ebs.ubuntu:       /tmp/pip-install-pzvhcqco/confluent-
kafka_5e848025e3cf41d8aca322a8e1526b79/src/confluent_kafka/src/confluent_kafka.h:66:2: error:
#error "confluent-kafka-python requires librdkafka v2.0.2 or later.
Install the latest version of librdkafka from the Confluent repositories,
see http://docs.confluent.io/current/installation.html"
```
fixes redpanda-data/devprod#819
* none
=> ducktape-deps: bump librdkafka version to v2.0.2

tests/rptest/services/redpanda_cloud.py
Fix access to `CloudClusterConfig.id` and set default values of config settings.
* none
=> rptest: fix `CloudClusterConfig`

src/v/storage/segment_appender.cc, src/v/storage/segment_appender.h, src/v/utils/fragmented_vector.h, src/v/utils/tests/fragmented_vector_test.cc
We are seeing an OOM case where we are trying to allocate 5MB in
`segment_appender::_flush_ops`.
Convert it to a `fragmented_vector` with lower block size. There is one
`segment_appender` per partition replica so we don't want to be too
wasteful.
This required adding a few methods to the `fragmented_vector` to replace `erase` and the iterator constructor.
Not sure I am 100% happy with this:
- Chunk size is picked a bit out of thin air to keep mem usage low
- The whole erase + create new vector dance isn't great I guess. Could optimize for the good case where the whole vector is being switched out.
Discarded options are:
- `ss::chunked_fifo`: Doesn't have `erase`
- `std::deque`: Has 4k blocks by default on libc++
Fixes https://github.com/redpanda-data/redpanda/issues/12547
* none
=> storage: Make segment_appender::_flush_ops a fragmented_vector 

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/kafka/server/handlers/produce.cc, src/v/kafka/server/request_context.h, src/v/kafka/server/tests/produce_consume_test.cc, src/v/net/probes.cc, src/v/net/server_probe.h, src/v/redpanda/application.h
Topics with timestamp.type=CreateTime delegates the producer to set the timestamp for each message.
a timestamp too far into the future is likely a sign of a client bug, while a timestamp into the past can be appropriate for some applications.
This pr introduced two tunable configurations, `log_message_timestamp_alert_before_ms` and `log_message_timestamp_alert_after_ms`, that define the max allowed skew before/after broker_time.
Outside these bounds, a warning is logged, and the metric `vectorized_kafka_rpc_produces_with_timestamps_out_of_bounds` is incremented to alert an observer that some producer is likely buggy.
log_message_timestamp_alert_after_ms defaults to 1 hour into the future
log_message_timestamp_alert_before_ms defaults to millis::max(), to effectively disable this check. …
=> Alert for messages with timestamp too far from broker time

src/v/cloud_storage/async_manifest_view.cc, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/tests/async_manifest_view_test.cc
If the timequery is used the async_manifest_view can chose the spillover manifest or STM manifest incorrectly. If the timestamp is inside the gap between the segments the async_manifest_view is not able to chose STM manifest.
This commit fixes this by changing the timequery logic inside the async_manifest_view. The 'in_stm' function for timequeries are simplified and no longer needs to call partition_manifest.timequery.
* Fix time query behaviour in situation when the timestamp doesn't match any segment
=> cloud_storage: Fix timequery

src/v/cloud_storage/materialized_resources.cc, src/v/cloud_storage/materialized_resources.h, src/v/cloud_storage/probe.cc, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_partition.h, src/v/cloud_storage/segment_state.cc, src/v/cloud_storage/segment_state.h, src/v/cloud_storage/tests/cloud_storage_fixture.h, src/v/cloud_storage/types.h, tests/rptest/scale_tests/tiered_storage_reader_stress_test.py
```
There's a number of cluster configs that impose limits on the cloud
storage read path:
* cloud_storage_max_segment_readers
* cloud_storage_max_partition_readers
* cloud_storage_max_materialized_segments_per_shard
Previously, only the partition reader limit was strictly respected.
The number of materialized segments and segment readers was allowed to
overshoot. This is detrimental in the event of a storm of cloud storage
requests since we can't trim fast enough and end up with a significant
amount of memory used by the cloud storage subsystem.
Enforcing these limits, also acts as a rudimentary multi-level
backpressure mechanism for cloud storage reads.
Implementation wise, the gist of this commit is that we separate finding
the metadata for the segment which should service the read, …
```
=> cloud_storage: enforce cloud read path limits strictly

src/v/storage/segment_appender.cc, src/v/storage/segment_appender.h, src/v/utils/fragmented_vector.h, src/v/utils/tests/fragmented_vector_test.cc
Backports https://github.com/redpanda-data/redpanda/pull/12580
* none
=> [v23.2.x] storage: Make segment_appender::_flush_ops a fragmented_vector

src/v/storage/segment_appender.cc, src/v/storage/segment_appender.h, src/v/utils/fragmented_vector.h, src/v/utils/tests/fragmented_vector_test.cc
Backports https://github.com/redpanda-data/redpanda/pull/12580
* none
=> [v23.1.x] storage: Make segment_appender::_flush_ops a fragmented_vector

src/v/bytes/details/io_iterator_consumer.h, src/v/bytes/tests/iobuf_tests.cc
It does so by using the return value of std::copy_n to update the out iterator.
* none
=> bytes/io_iterator_consumer: consume_to fix for std::backinserter

src/v/kafka/server/usage_aggregator.h
There have been some reports of failures in a usage test that is due to a timer being fired a second later then normal. Given some possible discrepancy with rounding and that the error has only been observed in cases where the observed timestamp is 1s over the expected, this patch raises the error threshold for the timer to two seconds. 
Fixes: #12678 
* none
=> tests: Raise the rounding timestamp error threshold for testing

tests/rptest/services/provider_clients/__init__.py, tests/rptest/services/provider_clients/ec2_client.py, tests/rptest/services/provider_clients/gcp_client.py, tests/rptest/services/redpanda.py, tests/rptest/services/redpanda_cloud.py
Create VPC peering for deployed cloud with private network
Steps:
1. Get VPC of the ducktape client instance
2. Detect cloud type and run corresponding workflow: FMC/BYOC
BYOC VPC Peering.
1. Prepare VPC info using boto3/vpc
2. Create peering in AWS or reuse existing one
3. Wait for pending acceptance using AWS if created
4. Accept it if created
5. Create routes
6. Ensure Active on AWS if created
FMC VPC Peering
1. Prepare vpc info using CloudV2
2. Create peering in CloudV2
3. Wait for Pending Acceptance usign CloudV2
4. Accept it
5. Create routes
6. Ensure Ready/Active state on both sides
Prior to implementing, in order not to have long list of arguments in each internal functions, use self.current as a data store. Each of the _*_payload functions and _get_* will use it as a source of …
=> retest: Implement VPC peering for Cloud Cluster with private network

src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/server.cc, tests/rptest/tests/schema_registry_test.py
If a subject already has a version of the schema, don't perform compatibility checks
* Schema Registry: Check compatibility iff the schema is a new version for the subject
=> schema_registry: Check compatibility iff the schema is a new version

src/v/cluster/partition_balancer_backend.cc, src/v/cluster/topic_table.cc, src/v/cluster/topic_table.h
When iterating over topic table in asynchronous loop it may be modified
by another fiber while loop yields in scheduling point. In this case
backend should retry immediately to make progress without delay of
waiting for next tick.
- faster convergence of partition balancer in face of topic operations
=> Retry balancer tick when topic_table was modified while iterating

tests/rptest/services/redpanda_cloud.py
When CloudV2 returns error, save it in addition to logging to be able to re-throw them later
ref: https://github.com/redpanda-data/cloudv2/issues/7904
* none
=> rptest: handle errors from cloudv2 and rethrow proper error messages

src/go/rpk/go.mod, src/go/rpk/go.sum, src/go/rpk/pkg/cli/container/common/client.go, src/go/rpk/pkg/cli/container/common/context.go, src/go/rpk/pkg/cli/generate/app.go
This is a workaround to new docker setups (e.g
docker desktop in Macs) which don't setup the
DOCKER_HOST env variable and does not have the
docker socket in the default location.
The alternative here is to manually parse the
docker endpoint out of the config file and the
docker context. Our current moby client does not
support contexts since this is a concept that is
only used by the CLI and the Desktop apps.
Fixes #12686 
* rpk container improvements: rpk now will search for your docker context if no `DOCKER_HOST` is set when running `rpk container` commands
=> rpk: load docker host from context in rpk container

tests/rptest/tests/scaling_up_test.py
Previously the test `test_adding_node_with_unavailable_node` was started
with partition balancer off. This was changed recently.
Fixes: #12813
Fixes: #12898
- none
=> tests/scaling_up_test: fixed initial conditions for unavailable nodes test

tests/rptest/services/redpanda_cloud.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12915
=> [v23.2.x] rptest: handle errors from cloudv2 and rethrow proper error messages

src/v/cluster/scheduling/leader_balancer_random.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/12905
=> [v23.1.x] c/leader_balancer: use node_hash_map to store leader information

src/v/cluster/scheduling/leader_balancer_random.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/12905
=> [v23.2.x] c/leader_balancer: use node_hash_map to store leader information

src/v/pandaproxy/schema_registry/sharded_store.cc, tests/rptest/tests/schema_registry_test.py
If the subject doesn't exist, the `error_code` should be `40401`
If the version doesn't exist, the `error_code` should be `40402`
Fixes https://github.com/redpanda-data/redpanda/issues/12892
* Schema Registry: `GET /subjects/{subject}/versions/{version}/referencedby` now returns a 404 if the subject or version doesn't exist
=> schema_registry: /referencedby should emit 404 if sub-ver doesn't exist

src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_segment.cc, src/v/kafka/server/connection_context.cc, src/v/kafka/server/connection_context.h, src/v/kafka/server/handlers/fetch.cc, src/v/kafka/server/handlers/fetch.h, src/v/kafka/server/handlers/list_offsets.cc, src/v/kafka/server/request_context.h, src/v/kafka/server/server.cc, src/v/net/connection.cc, src/v/net/connection.h, src/v/net/server.cc, src/v/redpanda/application.cc, src/v/ssx/abort_source.h, src/v/ssx/tests/CMakeLists.txt, src/v/ssx/tests/abort_source_test.cc, src/v/storage/types.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12021
Backport of PR https://github.com/redpanda-data/redpanda/pull/12955
Fixes: https://github.com/redpanda-data/redpanda/issues/12649
=> [v23.2.x]] kafka: Abort fetch and list_offsets when client disconnects

src/v/pandaproxy/schema_registry/sharded_store.cc, tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12956
Fixes: https://github.com/redpanda-data/redpanda/issues/12985,
=> [v23.1.x] schema_registry: /referencedby should emit 404 if sub-ver doesn't exist

src/v/pandaproxy/schema_registry/sharded_store.cc, tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12956
Fixes: https://github.com/redpanda-data/redpanda/issues/12987,
=> [v22.3.x] schema_registry: /referencedby should emit 404 if sub-ver doesn't exist

src/v/pandaproxy/schema_registry/sharded_store.cc, tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12956
Fixes: https://github.com/redpanda-data/redpanda/issues/12983,
=> [v23.2.x] schema_registry: /referencedby should emit 404 if sub-ver doesn't exist

src/go/rpk/pkg/cli/cloud/byoc/install.go, src/go/rpk/pkg/config/params.go
This includes 2 minor fixes:
[rpk: search for byoc plugins in PATH](https://github.com/redpanda-data/redpanda/commit/624f3de14e8721f3581bb80d41cb952a5fc5fbb3) 
Previously we only searched for the byoc plugin
in the default bin path (~/.local/bin) but a user
can have the plugin installed anywhere in PATH.
[rpk: use current default timeout in -X help text](https://github.com/redpanda-data/redpanda/commit/5113b96c47517c6bed16a18f95badc5ab12d1cc5) 
The old text might confuse someone reading our
docs, rpk timeouts are:
- Dial: 3s
- Overhead: 5s
- Retry: 11s
- Fetch: 5s
* rpk will now search for a byoc plugin installed in the user's $PATH.
=> rpk: minor fixes, -X help text and byoc binary lookup path

src/go/transform-sdk/internal/testdata/CMakeLists.txt, src/go/transform-sdk/internal/testdata/retry.py
We see tinygo segfaults and in an effort to reduce noise in CI, we
can just retry the build up to 3 times if it fails.
Upstream issue: https://github.com/tinygo-org/tinygo/issues/3874
* none
=> Add a retry wrapper to the tinygo command

.github/labeler.yml
Use labeler to set the `k8s/tests` label for operator PRs
* none
=> set k8s/tests label automatically

tests/rptest/services/provider_clients/gcp_client.py
=> rptest: Add proper zone mock to GCP client

tests/rptest/remote_scripts/compute_storage.py
Listing the segments lazily means that our try..catch wrapper does
nothing.
Fixes errors like seen here: https://ci-artifacts.dev.vectorized.cloud/redpanda/35662/018a299c-8e38-43c8-b545-edb4c4375eb6/vbuild/ducktape/results/2023-08-24--001/TopicDeleteStressTest/stress_test/193/report.txt
Stack trace below:
```
ducktape.cluster.remoteaccount.RemoteCommandError: root@docker-rp-14: Command 'python3 /tmp/compute_storage.py --data-dir=/var/lib/redpanda/data' returned non-zero exit status 1. Remote error message: b'Traceback (most recent call last):\n  File "/tmp/compute_storage.py", line 78, in <module>\n    output = compute_size(data_dir, args.sizes)\n  File "/tmp/compute_storage.py", line 49, in compute_size\n    for segment in safe_listdir(partition):\n  File …
```
=> Eagerly list all files in compute_storage.py

tests/rptest/tests/timequery_test.py
Extend timequery test to check cloud-storage with and without spillover enabled. Validate that the segments are actuallys spilled by checking the manifest.
* none
=> rptest: Test spillover and timequeries

src/v/raft/consensus.cc
When leader is not present request full heartbeat as the lightweight heartbeat doesn't contain leader information and can not update follower state.
Fixes: #12062
- none
=> r/consensus: request full heartbeat when leader is not present

.github/workflows/rpk-build.yml
bump quill from [v0.2.0](https://github.com/anchore/quill/releases/tag/v0.2.0) to [v0.4.1](https://github.com/anchore/quill/releases/tag/v0.4.1)
comparison of changes: https://github.com/anchore/quill/compare/v0.2.0...v0.4.1
* none
=> gha: bump quill to 0.4.1

tests/rptest/tests/node_pool_migration_test.py
We should use consistent policy on node assignment as it may lead to situation in which configured node_id doesn't match the assigned one.
Fixes: #12605
- none
=> tests: use auto assigned node_ids on newly added nodes

src/v/cluster/partition.cc, src/v/cluster/partition_probe.cc, src/v/cluster/partition_probe.h, src/v/raft/consensus.cc, src/v/raft/probe.h
By default `ss::metircs_group` uses RAII to unregister metrics. In case of the
consensus object the metrics should be cleared right after the instance
is stopped. The lifecycle of an object may be prolongated in Kafka
protocol handlers. By clearing metrics we prevent old stopped but still
present object from interfering with the newly created one.
Fixes: #11344 
Fixes: #12699 
- fixed rare but possible deadlock that might lead to Redpanda crash when moving partitions back and forth between nodes.
=> Clear Raft & Partition metrics after they are stopped

.github/workflows/rpk-build.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/13002
=> [v23.2.x] gha: bump quill to 0.4.1

.github/workflows/rpk-build.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/13002
=> [v22.3.x] gha: bump quill to 0.4.1

src/v/cloud_storage/cache_service.cc, src/v/cloud_storage/tests/cache_test.cc, src/v/cloud_storage/tests/cache_test_fixture.h, tests/rptest/scale_tests/tiered_storage_cache_stress_test.py
In the case where the cache dir consists solely of index+tx files, the current code path in fast trim does not remove anything. This should be followed up by an exhaustive trim to free up slots in cache, but due to an adjustment of the objects to delete counter, this ends up not happening.
The change here makes sure that if we have a certain count of objects to delete, and we were not able to delete the count, and there is a set of filtered out files, we proceed to do an exhaustive trim.
FIXES #12980 
* none
=> cloud_storage: Force exhaustive trim when fast trim fails

src/v/cloud_storage/read_path_probes.cc, src/v/cloud_storage/read_path_probes.h, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment.h, src/v/cloud_storage/remote_segment_index.cc, src/v/cloud_storage/remote_segment_index.h, src/v/cloud_storage/segment_chunk_api.cc, src/v/cloud_storage/segment_chunk_api.h, tests/rptest/tests/timequery_test.py
This PR updates the timequery read path to skip up to the first
index entry with a timestamp smaller than the searched one. The result
is that timequeries will hydrate/materialize a maximum of two chunks
(two because the chunk boundaries don't always line up with the entries
in the index).
If the index is not present, or was originally created in v1, the search
starts from the first chunk as it did previously.
Fixes #11801
* Timequeries (i.e ListOffsets requests) that land in the cloud log now use an index to speed up the search
and reduce the number of hydrated bytes required to serve the query. On average, a time query will have to download 4 times less data (if using the default segment and chunk size)
=> cloud_storage: use  remote index in cloud timequery

.github/dependabot.yml
Enable dependabot PRs for the `src/go/k8s` tree
* none
=> operator: add dependabot only for /src/go/k8s

src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/api/api-doc/schema_registry_header.json, src/v/pandaproxy/schema_registry/handlers.cc, src/v/pandaproxy/schema_registry/handlers.h, src/v/pandaproxy/schema_registry/service.cc, src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h, src/v/pandaproxy/schema_registry/store.h, src/v/pandaproxy/schema_registry/test/store.cc, tests/rptest/tests/schema_registry_test.py
Closes #12989
Without this endpoint, developers must fetch all schemas to figure out which subject(s) a certain schema ID belongs to. So this change adds an endpoint to fetch all subjects associated with a schema ID.
* Schema Registry: Support `GET /schemas/ids/{id}/subjects`
=> schema_registry: Support GET /schemas/ids/{id}/subjects

src/v/cloud_storage/cache_service.cc, src/v/cloud_storage/tests/cache_test.cc, src/v/cloud_storage/tests/cache_test_fixture.h, tests/rptest/scale_tests/tiered_storage_cache_stress_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13013
Fixes: https://github.com/redpanda-data/redpanda/issues/13062,
=> [v23.2.x] cloud_storage: Force exhaustive trim when fast trim fails

src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/api/api-doc/schema_registry_header.json, src/v/pandaproxy/schema_registry/handlers.cc, src/v/pandaproxy/schema_registry/handlers.h, src/v/pandaproxy/schema_registry/service.cc, src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h, src/v/pandaproxy/schema_registry/store.h, src/v/pandaproxy/schema_registry/test/store.cc, tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13020
Fixes: https://github.com/redpanda-data/redpanda/issues/13081,
=> [v23.2.x] schema_registry: Support GET /schemas/ids/{id}/subjects

src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/api/api-doc/schema_registry_header.json, src/v/pandaproxy/schema_registry/handlers.cc, src/v/pandaproxy/schema_registry/handlers.h, src/v/pandaproxy/schema_registry/service.cc, src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h, src/v/pandaproxy/schema_registry/store.h, src/v/pandaproxy/schema_registry/test/store.cc, tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13020
Fixes: https://github.com/redpanda-data/redpanda/issues/13083,
=> [v23.1.x] schema_registry: Support GET /schemas/ids/{id}/subjects

src/v/resource_mgmt/storage.cc, src/v/storage/disk_log_impl.cc, src/v/storage/log_manager.cc, src/v/storage/log_manager.h
Unbounded creation of num_partition * num_segment futures combined with default (1000) share scheduling group meant that a system with a large number of partitions/segments could really drown out other work.
Reduces concurrency and CPU shares to address concern.
* none
=> [storage]: make space management chill out

src/v/cloud_storage/recursive_directory_walker.cc, src/v/cloud_storage/recursive_directory_walker.h
It's typically unexpected for this container to grow large, but we've seen it before during manual intervention on a node: when trying to quickly clear out recent data from a cache directory.
* Redpanda will now allocate less contiguous memory when scanning a tiered storage cache directory that contains many empty directories.
=> cloud_storage: replace empty dir type with fragmented vector

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/storage/disk_log_impl.cc, src/v/storage/log_manager.cc
=> storage: add configuration to control space management concurrency

src/v/cloud_storage_clients/client_pool.cc, src/v/cloud_storage_clients/configuration.cc, src/v/net/transport.cc, src/v/net/transport.h, tests/rptest/archival/abs_client.py, tests/rptest/services/redpanda.py, tests/rptest/tests/adjacent_segment_merging_test.py, tests/rptest/tests/archival_test.py, tests/rptest/tests/cloud_storage_chunk_read_path_test.py, tests/rptest/tests/e2e_shadow_indexing_test.py, tests/rptest/tests/follower_fetching_test.py, tests/rptest/tests/license_upgrade_test.py, tests/rptest/tests/read_replica_e2e_test.py, tests/rptest/tests/services_self_test.py, tests/rptest/tests/shadow_indexing_admin_api_test.py, tests/rptest/tests/topic_creation_test.py, tests/rptest/tests/upgrade_test.py, tests/rptest/tests/workload_upgrade_runner_test.py, tests/rptest/utils/mode_checks.py
This PR includes some follow-ups for Azure HNS work:
* Skip EOF wait on TLS connection termination since the ABS TLS server does not comply to the spec
in this regard. Needs https://github.com/redpanda-data/seastar/pull/63 to be merged first.
* Various test fixes for Azure HNS
* none
=> cloud_storage: follow-ups and test fixes for Azure HNS

src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/api/api-doc/schema_registry_header.json, src/v/pandaproxy/schema_registry/handlers.cc, src/v/pandaproxy/schema_registry/handlers.h, src/v/pandaproxy/schema_registry/service.cc, src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h, src/v/pandaproxy/schema_registry/store.h, src/v/pandaproxy/schema_registry/test/store.cc, tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13020
Fixes: https://github.com/redpanda-data/redpanda/issues/13080,
=> [v22.3.x] schema_registry: Support GET /schemas/ids/{id}/subjects

src/v/cloud_storage/recursive_directory_walker.cc, src/v/cloud_storage/recursive_directory_walker.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/13079
=> [v23.2.x] cloud_storage: replace empty dir type with fragmented vector

src/v/cluster/config_manager.cc, tests/rptest/services/redpanda.py, tests/rptest/services/rolling_restarter.py, tests/rptest/tests/nodes_decommissioning_test.py, tests/rptest/tests/redpanda_test.py
There is a dependency between the `cluster::config_manager` and members
table. Cluster configuration status updates are not explicitly removed
from status but but `config_manager` rely on notifications from members
table. The relationship is correct since all the controller log commands
are applied in order i.e. if member was deleted after its configuration
status was updated the notification is guaranteed to be generated after
the status update hence `config_manager` can use notification to cleanup
not longer relevant statuses.
Issue leading to discrepancy between members table content and
`config_manager` status map was caused by the fact that manage
notification was register after the update was generated.
Moved the notification subscription earlier (to the constructor of …
=> Fixed configuration status and brokers list discrepancy 

src/go/k8s/go.mod, src/go/k8s/go.sum
Backport of PR https://github.com/redpanda-data/redpanda/pull/13076
=> [v23.2.x] build(deps): bump github.com/docker/distribution from 2.8.1+incompatible to 2.8.2+incompatible in /src/go/k8s

tests/rptest/tests/consumer_offsets_consistency_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12996
Fixes: https://github.com/redpanda-data/redpanda/issues/13040,
=> [v23.2.x] Retry listing groups in test flipping consumer offsets topic leadership 

tests/rptest/tests/consumer_offsets_consistency_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12996
Fixes: https://github.com/redpanda-data/redpanda/issues/13038,
=> [v23.1.x] Retry listing groups in test flipping consumer offsets topic leadership 

src/v/kafka/client/client.cc, src/v/pandaproxy/schema_registry/service.cc, src/v/pandaproxy/schema_registry/service.h, tests/rptest/tests/pandaproxy_test.py, tests/rptest/tests/schema_registry_test.py
#11563 revealed that SR startup could use some changes. This PR removes the background task that sets authz in a loop. Instead, the SR will set authz during error handling.
This patch also extends SR and PP tests to move the controller leader around startup.
Fixes: https://github.com/redpanda-data/redpanda/issues/13043
Changes from force-push `36f6f6a`:
- Capture the return from `security_frontend::create_acls` in-line
- Loop through the return from `security_frontend::create_acls`
* none
=> sr: improve startup

src/v/archival/upload_housekeeping_service.cc, src/v/cloud_storage/CMakeLists.txt, src/v/cloud_storage/cache_service.h, src/v/cloud_storage/download_exception.cc, src/v/cloud_storage/download_exception.h, src/v/cloud_storage/remote.cc, src/v/cloud_storage/remote.h, src/v/cloud_storage/remote_file.cc, src/v/cloud_storage/remote_file.h, src/v/cloud_storage/remote_probe.cc, src/v/cloud_storage/remote_probe.h, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment.h, src/v/cloud_storage/tests/CMakeLists.txt, src/v/cloud_storage/tests/remote_file_test.cc, src/v/cloud_storage/tests/remote_partition_fuzz_test.cc, src/v/cloud_storage/tests/remote_segment_test.cc, src/v/cluster/cloud_metadata/key_utils.cc, src/v/cluster/cloud_metadata/key_utils.h, src/v/cluster/cloud_metadata/manifest_downloads.cc, src/v/cluster/cloud_metadata/manifest_downloads.h, src/v/cluster/cloud_metadata/tests/uploader_test.cc, src/v/cluster/cloud_metadata/uploader.cc, src/v/cluster/cloud_metadata/uploader.h, src/v/cluster/controller.h, src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/storage/snapshot.cc, src/v/storage/snapshot.h
This PR improves the metadata upload loop in a couple ways:
* We now upload the latest controller snapshot as a part of the loop. Some utilities are added to capture the the ss::file of the underlying snapshot, and upload ss::files to remote storage rather than going through segment or manifest APIs.
* We now clean up objects that are not referenced by the manifest. This allows us to ensure that over time, we don't accumulate a large number of snapshot files. As this is a destructive operation, this is gated by a linearizable barrier.
Along the way, this PR includes some ancillary changes:
- adds a couple APIs for interacting with the controller snapshot file
- templatizes the upload/download_segment methods to be reusable for non-segments
- adds a wrapper around a remote cacheable file, …
=> cloud_metadata: flesh out uploader implementation for controller snapshots

src/go/rpk/pkg/adminapi/api_broker.go, src/go/rpk/pkg/cli/redpanda/admin/brokers/decommission-status.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/12089
Fixes: https://github.com/redpanda-data/redpanda/issues/12884,
=> [v23.2.x] rpk: show allocation failures in decommission-status

src/go/k8s/go.mod, src/go/k8s/go.sum
Backport of PR https://github.com/redpanda-data/redpanda/pull/13093
=> [v23.2.x] build(deps): bump github.com/moby/moby from 20.10.23+incompatible to 24.0.5+incompatible in /src/go/k8s

src/v/cluster/tm_stm.cc, src/v/cluster/tm_stm.h, src/v/cluster/tm_stm_cache.cc, src/v/cluster/tm_stm_cache.h, src/v/cluster/tx_gateway_frontend.cc, src/v/cluster/tx_gateway_frontend.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/application.cc, src/v/utils/rwlock.h, src/v/utils/tests/rwlock_test.cc, tests/rptest/tests/tx_overflow_test.py
PR adds tx thrashing to abort & evict old txn sessions once the number of known txn session passes a threshold (new `max_transactions_per_coordinator` property).
Fixes #12424
* none
=> Add thrashing of old txn sessions to prevent OOM

src/v/storage/segment_appender.cc, src/v/storage/segment_appender.h, src/v/storage/segment_appender_chunk.h, src/v/storage/tests/log_segment_appender_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12473
Note the original PR was merged without doing a rebase first, for simplicity of backporting and keeping the commits as similar to the original ones I kept all the commits as is.
Fixes https://github.com/redpanda-data/redpanda/issues/13112
=> [v23.2.x] Improved segment appender write merging

src/v/kafka/server/handlers/describe_producers.cc, tests/rptest/tests/transaction_kafka_api_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12285
Fixes: https://github.com/redpanda-data/redpanda/issues/12435,
=> [v23.1.x] txns: fix describe producers api to return correct last timestamp

cmake/oss.cmake.in
Updates the git SHA for seastar to include fixes to the CPU profiler.
* none
=> Update seastar git SHA

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/resource_mgmt/storage.cc, src/v/storage/disk_log_impl.cc, src/v/storage/log_manager.cc, src/v/storage/log_manager.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/13072
I also added this one: https://github.com/redpanda-data/redpanda/pull/13094 which would have needed backporting too, and depends on 13072.
* none
=> [v23.2.x] [storage]: make space management chill out

tests/rptest/tests/full_disk_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12023
Fixes: https://github.com/redpanda-data/redpanda/issues/13150,
=> [v23.2.x] t/full_disk_test: longer timeout in debug_mode

tests/rptest/tests/timequery_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13034
=> [v23.2.x] rptest: Test spillover and timequeries

src/v/cloud_storage/read_path_probes.cc, src/v/cloud_storage/read_path_probes.h, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment.h, src/v/cloud_storage/remote_segment_index.cc, src/v/cloud_storage/remote_segment_index.h, src/v/cloud_storage/segment_chunk_api.cc, src/v/cloud_storage/segment_chunk_api.h, tests/rptest/tests/timequery_test.py
Backport of https://github.com/redpanda-data/redpanda/pull/13011
* Timequeries (i.e ListOffsets requests) that land in the cloud log now use an index to speed up the search
and reduce the number of hydrated bytes required to serve the query. On average, a time query will have to download 4 times less data (if using the default segment and chunk size)
=> [v23.2.x] cloud_storage: use remote index in cloud timequery

src/v/storage/compaction_reducers.cc, src/v/storage/compaction_reducers.h, src/v/storage/tests/CMakeLists.txt, src/v/storage/tests/compaction_reducer_test.cc
Swap out the node hash map for a B-Tree. The issue with the node hash map is it's growth pattern. It doubles in size whenver it nears its capacity, which results in large allocations. The B-Tree is a lot more well behaved in this regard.
Note how the key into the B-Tree is the hash of the key. This avoids a lot of expensive string compares and maintains the randomness for when we evict from the index. Since there can be collisions, I've used the multimap variant of the tree.
I did some performance testing with the reducer bench in `compaction_idx_bench.cc` and the results are interesting. This branch performs about 10x better in terms of runtime compared to `dev` in the benchmark.
Each key of a segment needs to go through this reduced for compacted topics, so this could be a nice …
=> storage: use B-Tree for compaction reducer

src/v/cloud_storage/cache_service.cc, src/v/cloud_storage/tests/cache_test.cc
When a log segment is removed in fast trim, the associated index and tx files are also removed. This commit extends this feature to new log segment name formats, which may contain a term after the name.
* none
=> cloud_storage: Extend fast trim cleanup to new segment name

tests/docker/ducktape-deps/client-swarm
bump to latest version to bring in SASL SSL support from https://github.com/redpanda-data/client-swarm/pull/12. comparison of diff: https://github.com/redpanda-data/client-swarm/compare/5610f614545ee34f593e1279b30ee9986959d9b0...d20bbf6aa9451fd1d725146c05799b675ab20084
related issue https://github.com/redpanda-data/cloudv2/issues/8190
* none
=> tests/docker: bump client-swarm

src/v/CMakeLists.txt, src/v/transform/CMakeLists.txt, src/v/transform/fwd.h, src/v/transform/io.h, src/v/transform/logger.cc, src/v/transform/logger.h, src/v/transform/probe.cc, src/v/transform/probe.h, src/v/transform/tests/CMakeLists.txt, src/v/transform/tests/test_fixture.cc, src/v/transform/tests/test_fixture.h, src/v/transform/tests/transform_processor_test.cc, src/v/transform/transform_processor.cc, src/v/transform/transform_processor.h
This processor is the driver for a single instance of a wasm runtime.
Essentially at it's core the processor is a fiber that
read->transform->writes a partition.
There are optimizations to do to improve pipelining of the processor,
but I figured it would be better to start with the simplest thing
possible and have future changes for the optimizations.
* none
=> Introduce transform::processor

tests/rptest/scale_tests/high_throughput_test.py, tests/rptest/services/kgo_verifier_services.py, tests/rptest/services/redpanda.py
various fixes in `KgoVerifierService` and `RedpandaServiceCloud` for getting tests to run on redpanda cloud.
related issue: https://github.com/redpanda-data/cloudv2/issues/8189
* none
=> rptest: fixes to enable tests on redpanda cloud

src/v/kafka/server/server.cc, src/v/kafka/server/server.h, src/v/redpanda/application.cc, src/v/redpanda/application.h, src/v/security/gssapi_authenticator.cc, src/v/security/gssapi_authenticator.h, src/v/ssx/fwd.h, src/v/ssx/tests/thread_worker.cc, src/v/ssx/tests/thread_worker_bench.cc, src/v/ssx/thread_worker.h
Use a ring buffer to bulk pass tasks around, and also support creating a
twin worker thread for every reactor thread.
This amortizes the cost of running a task on an alien thread, this came about because we're going to be switching transforms over to Wasmtime running on an alien thread.
Before:
```
test                                      iterations      median         mad         min         max      allocs       tasks        inst
thread_worker_test.1                            3354   216.749us    47.062ns   216.590us   216.951us       5.000       4.000   1610844.2
thread_worker_test.10                            460     2.088ms   870.335ns     2.087ms     2.089ms      70.000      58.000  25391981.4
thread_worker_test.100                            61    16.465ms     1.733us    16.461ms …
```
=> Optimize thread_worker

tests/rptest/tests/tx_admin_api_test.py
`mark_transaction_expired` is an idempotent operation and is retried on any error; timeout is one of the possible transient errors; adding it to the allow list to prevent false positive test failure
Fixes #12806
* none
=> ducky: add timeout to mark_transaction_expired's allow list

src/v/storage/compaction_reducers.cc, src/v/storage/compaction_reducers.h, src/v/storage/tests/CMakeLists.txt, src/v/storage/tests/compaction_reducer_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13067
Fixes: https://github.com/redpanda-data/redpanda/issues/13162,
=> [v23.2.x] storage: use B-Tree for compaction reducer

src/v/storage/compaction_reducers.cc, src/v/storage/compaction_reducers.h, src/v/storage/tests/CMakeLists.txt, src/v/storage/tests/compaction_reducer_test.cc
Backport of https://github.com/redpanda-data/redpanda/pull/13067
* Fix OOM crashes for compacted topics and speed up filtering of compaction keys by up to 10x
=> [v23.1.x] storage: use B-Tree for compaction reducer

tests/rptest/services/producer_swarm.py
WIP
Related issue: https://github.com/redpanda-data/cloudv2/issues/8190
* none
=> rptest: test max connections to redpanda cloud

src/v/storage/segment_set.cc, tests/rptest/tests/index_recovery_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/10119
Fixes https://github.com/redpanda-data/redpanda/issues/12065
=> [v22.3.x] s/segment_set: recover base_index of last_clean_segment

tests/rptest/tests/consumer_offsets_consistency_test.py
Added retries to offset listing logic and reduced new members join timeout to make the test stable.
Fixes: #13061 
Fixes: #13159 
- none
=> Made `consumer_offsets_consistency_test.py` more robust

src/v/cluster/cluster_utils.cc
Previously `members_manager::handle_configuration_update_request` method did not validate if a node exists in the cluster. This lead to assertion being triggered when resulting cluster configuration was checked. Added validation of node existence in the `members_table`.
Fixes: #13108
- none
=> c/members_manager: validate if node exists in the cluster before update

tests/rptest/tests/retention_policy_test.py, tests/rptest/tests/timequery_test.py
Partial backport of https://github.com/redpanda-data/redpanda/pull/8955
CONFLICT:
- This patch was already mostly merged as a part of c41022f, but missed out on this bit to update segment size for non-cloud-storage clusters, and a removal of a test. This meant the log would not roll a segment, and therefore never have anything viable for GC, hence the failure to advance the start offset.
Previously, `test_timequery_after_segments_eviction` expected that timequeries for offsets within a segment would be serviced up until the segment was removed from disk. This assumption is not correct, as we should not serve timequeries that fall below the start offset of the local log (unless cloud storage is enabled and the offset is in the cloud log).
This commit removes the mentioned test, and adds a …
=> [v22.3.x] rptest: improve timequery below start offset test

tests/rptest/tests/timequery_test.py
The test sometimes fails to wait for retention to kick in within 1 minute in Kafka. Note that no Redpanda is involved, so this commit just bumps the timeout.
Fixes #10140
* none
=> ducktape: extend timeout in timequery_test

src/v/cloud_storage/tests/cloud_storage_e2e_test.cc, src/v/cloud_storage/tests/delete_records_e2e_test.cc, src/v/cloud_storage/tests/manual_fixture.h, src/v/cloud_storage/tests/read_replica_test.cc, src/v/config/tests/CMakeLists.txt, src/v/config/tests/scoped_config_test.cc, src/v/storage/tests/storage_e2e_fixture_test.cc, src/v/test_utils/scoped_config.h
Several tests set configs directly with config::shard_local_config
without cleaning them up after. This means that the next test that gets
run in the same process may be affected by whatever a previous test had
set.
This introduces a new scoped wrapper around config::shard_local_config
to track what properties may have been updated, so it may reset them
upon call to destructor.
Fixes https://github.com/redpanda-data/redpanda/issues/12839
* none
=> test_utils: add scoped config resetter

tests/rptest/tests/read_replica_e2e_test.py
We recently bumped the git tag so we're now upgrading from v23.2, which needs the "fast uploads" cluster configs to upload manifests quickly.
Fixes #13182
* none
=> rptest: use fast uploads in read replica upgrade test

tests/rptest/services/redpanda_cloud.py
This is `rptest` side of the freshly merged https://github.com/redpanda-data/vtools/pull/2058
* none
=> rptest: Support gcpkeyfile parameter on rptest for GCP Nightly

tests/rptest/tests/e2e_shadow_indexing_test.py
When a manifest spillover happens it is uploaded to the cloud storage. The original manifest, now truncated, is uploaded after a short period. This means that there is a window during which the spilled over manifest has been uploaded and the changed root manifest is not uploaded, and the same offset range could be present in both the root and spillover in cloud storage.
The test here constructs a reset manifest by analyzing the spillover and root manifests. If it happens to collect these during such a window, it ends up creating a reset manifest which is invalid, containing the same offset range in both the segment set and the spillover set. From this point onwards, no spillover command can succeed, because it always fails at the overlapping range.
The change here waits for a set of …
=> ducktape: Wait for spillover to stabilize before collection

src/v/cluster/cluster_utils.cc, src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/heartbeat_manager.cc, src/v/raft/heartbeat_manager.h, src/v/raft/recovery_stm.cc, src/v/raft/replicate_entries_stm.cc, src/v/raft/replicate_entries_stm.h, src/v/raft/types.cc, src/v/raft/types.h
Previously, concurrency in heartbeat suppression requests was managed by checking the sequence number of the request on the unsuppress call. This protected against the following:
* suppress(seq=1)
* suppress(seq=2)
* unsuppress(seq=1)
* unsuppress(seq=2)
But didn't protect against
* suppress(seq=1)
* suppress(seq=2)
* unsuppress(seq=2) (should still be suppressed here)
* unsuppress(seq=1)
The latter scenario is possible when we skip the recovering follower in replicate_entries_stm. Fix this by introducing a RAII guard that takes care of updating the in-flight requests count.
* none
=> raft: suppress heartbeats with a guard

tests/rptest/services/redpanda_cloud.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13059
=> [v23.2.x] rptest: Support gcpkeyfile parameter on rptest for GCP Nightly

tests/rptest/scale_tests/high_throughput_test.py, tests/rptest/services/redpanda.py, tests/rptest/services/redpanda_cloud.py, tests/rptest/test_suite_cloud.yml, tests/rptest/test_suite_ec2.yml
Check and implement functions that needed to run ProducerSwarm class
with RedpandaServiceCloud.
After that, create main test that will ramp-up connection load node-by-node
* none
=> rptest: create max connections test using ProducerSwarm

src/v/archival/tests/ntp_archiver_test.cc, src/v/cloud_roles/tests/fetch_credentials_tests.cc, src/v/cloud_storage/tests/async_manifest_view_test.cc, src/v/cloud_storage/tests/remote_segment_test.cc, src/v/cluster/tests/manual_log_deletion_test.cc, src/v/storage/tests/log_retention_tests.cc, src/v/storage/tests/storage_e2e_test.cc, src/v/storage/tests/storage_test_fixture.h
In some tests we never reset configs which are essentially global variables. This PR fixes some of the instances of this using `ss::defer`.
* none
=> treewide: Reset configs in tests

src/v/raft/consensus.cc, src/v/raft/heartbeat_manager.cc, src/v/raft/tests/append_entries_test.cc
All the places where follower sequence id is updated use post incrementation. Using pre incrementation operator in heartbeat manager lead to a situation in which two requests were assigned the same `sequence_id`.
- none
=> r/consensus: fixed reusing follower sequence id

src/v/model/record.h, src/v/raft/types.cc, src/v/raft/types.h, src/v/serde/serde.h, src/v/serde/test/serde_test.cc
Make it consistent with ordinary serde_[async]_read methods. This way user-defined direct read routines will have access to version information.
* none
=> serde: pass full header to serde_[async]_direct_read

src/v/cloud_storage/remote_partition.cc
Previously, when the start offset of the log advanced while processsing a fetch resulting in the fetch to land below the start of the log, we would log at ERROR level. However, this situation is normal when the consumer is fetching close to the boundary from which retention is operating.
This patch detects such situations and downgrades the log to the DEBUG level.
Fixes #12105
* none
=> cloud_storage: debug log on query below log start

src/v/model/record.h, src/v/raft/types.cc, src/v/raft/types.h, src/v/serde/serde.h, src/v/serde/test/serde_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13134
=> [v23.2.x] serde: pass full header to serde_[async]_direct_read

src/v/cloud_storage/remote_partition.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13211
Fixes: https://github.com/redpanda-data/redpanda/issues/13247,
=> [v23.2.x] cloud_storage: debug log on query below log start

tests/rptest/tests/shadow_indexing_admin_api_test.py
The test disables cloud storage at runtime. This may happen before the topic manifest upload goes through, so it's reasonable to allow the anomaly.
Fixes #10932
Based on @andrwng 's https://github.com/redpanda-data/redpanda/pull/12131
* none
=> rptest: allow ntr_no_topic_manifest in test_manifest_dump

tests/rptest/tests/shadow_indexing_admin_api_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13249
Fixes: https://github.com/redpanda-data/redpanda/issues/13255,
=> [v23.2.x] rptest: allow ntr_no_topic_manifest in test_manifest_dump

src/v/raft/tests/append_entries_test.cc
Previously the linearizable barrier test might use out of date leader offsets to assert if the barrier was executed correctly. This made the test flaky especially for slow debug builds where leadership can change throughout the test.
- none
=> r/tests: always use current leader offsets in linearizable barrier test

tests/rptest/scale_tests/cloud_storage_compaction_test.py
A new metric that matches the pattern has been introduced: `vectorized_cloud_storage_controller_snapshot_successful_uploads`. This breaks the metric collection in
`CloudStorageCompactionTest.test_read_from_replica`.
This commit fixes the issues by being more explicit with the metric's name.
Fixes #13181
* none
=> rptest: use explicit cloud storage metric name

.github/workflows/redpanda-migration-build.yml, .github/workflows/rpk-build.yml, .github/workflows/transform-sdk-build.yml, src/go/cluster-to-redpanda-migration/go.mod, src/go/cluster-to-redpanda-migration/go.sum
The golang github actions were only run on PRs to `dev` branch and git tag events. This PR updates gha to run them on PRs to release branches as well.
This will help catch issues in PRs like https://github.com/redpanda-data/redpanda/pull/13129 before tagging for release.
* none
=> gha: run go test on PRs to release branches

tests/rptest/scale_tests/many_partitions_test.py
So far we had not been giving a target bandwidth to the background
kgo-repeater traffic.
As a result the clients would just spam as fast as possible and make the
test flaky and unreliable as this might overload RP.
Especially on Arm this causes leadership to not stabilize.
Note we also change the final soak phase to run for two minutes instead
of a number of bytes and calculate this based on the expected bandwidth.
This again makes the test more predictable independent of where it's
running.
* none
=> ducktape: ManyPartitionTest - Explicitly set background traffic bandwidth

src/v/archival/tests/ntp_archiver_test.cc, src/v/cloud_roles/tests/fetch_credentials_tests.cc, src/v/cloud_storage/tests/async_manifest_view_test.cc, src/v/cloud_storage/tests/remote_segment_test.cc, src/v/cluster/tests/manual_log_deletion_test.cc, src/v/storage/tests/log_retention_tests.cc, src/v/storage/tests/storage_e2e_test.cc, src/v/storage/tests/storage_test_fixture.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/13168
=> [v23.2.x] treewide: Reset configs in tests

tests/rptest/scale_tests/tiered_storage_reader_stress_test.py, tests/rptest/services/redpanda.py
Previously, the assertions used to check for saturation with tiered
storage reads were too strong. Since the various limits on the read path
are now strongly enforced, the read path may become stalled at different
points.
Additionally, the test was very lax with the amount of time needed to
close all outstanding Kafka connections. Since we have a mechanism to
close Kafka connections on client abort, this limit is now set to the
default timequery timeout (5 seconds).
Fixes #12135 
* none
=> rptest: tweak cloud storage reader stress test 

tests/rptest/tests/transactions_test.py
Topic creation may be acked before it's created on all replicas but the test was expecting to find topic on all replicas immediately after the request is acked. Replacing an assert with wait_until to give RP time to propagate the change.
Fixes #11737
* none
=> ducky: relax assert in transactions_test

src/v/cluster/persisted_stm.h
I was reading the source and had to go lookup in the cover letters of
the PR that introduced the kvstore snapshots to understand when I should
use files over kvstore snapshots. This might help future readers of the
code.
* none
=> Add comments about which stm_snapshot backend to use

src/go/rpk/pkg/cli/root.go, src/go/rpk/pkg/cli/transform/transform.go
Just add the subcommand and alias `wasm` for this command (less to
type). I also regularly misspell `transform` as `transfrom` so I added an alias for that common typo.
* none
=> Add initial boilerplate for `rpk transform`

src/v/cluster/tests/serialization_rt_test.cc, src/v/compat/raft_compat.h, src/v/compat/raft_generator.h, src/v/compat/raft_json.h, src/v/raft/consensus.cc, src/v/raft/heartbeat_manager.cc, src/v/raft/heartbeats.h, src/v/raft/recovery_stm.cc, src/v/raft/service.h, src/v/raft/tests/heartbeat_bench.cc, src/v/raft/tests/heartbeats_test.cc, src/v/raft/tests/type_serialization_tests.cc, src/v/raft/types.cc, src/v/raft/types.h, tests/rptest/services/redpanda.py, tests/rptest/tests/raft_recovery_test.py
Add message fields that will be used for coordinating recovery:
* `append_entries_reply::may_recover` - This flag will be used by followers limit concurrency of in-progress recovery streams - the follower responding with may_recover=false is an advice to the leader that it is better to delay recovery for now.
* `protocol_metadata::dirty_offset` - Leader dirty_offset will be used by followers to distinguish between ordinary and recovery append_entries and also to get a sense of how many offsets are left to recover. For coordinated recovery, receiving an append_entries request with prev_log_index == dirty_offset will signal to the follower that recovery is over and another raft group can be allowed to start recovery.
* `install_snapshot_request::dirty_offset` - similar to the previous one …
=> Coordinated recovery: add message fields

src/v/raft/replicate_entries_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13300
Fixes: https://github.com/redpanda-data/redpanda/issues/13314,
=> [v22.3.x] Handle gate closing exceptions in replicate_entries_stm

src/v/raft/replicate_entries_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13300
Fixes: https://github.com/redpanda-data/redpanda/issues/13312,
=> [v23.2.x] Handle gate closing exceptions in replicate_entries_stm

tests/rptest/services/redpanda.py
Previously, we triggered test failure in case if redpanda crashed due to assertion, segfault, ignored exceptional future or undefined behaviour sanitizer failure. Crashes caused by uncaught exceptions were unnoticed. If redpanda terminated due to exception the test would be marked green. This commit fixes this by adding regexes that shold catch this.
* none
=> rptest: Trigger test failiure on uncaught exception

src/v/config/configuration.cc
Now that the archival metadata in-memory format has a smaller footprint and we have spillover, it's much safer to always upload. This sets the default value for the upload interval to 1hr, matching Redpanda's cloud offering.
Fixes #7652
* Tiered-storage partitions will now upload at least once an hour. See the `cloud_storage_segment_max_upload_interval_sec` cluster configuration for more details.
=> cloud_storage: set default upload interval

tests/rptest/infinite_retention/infinite_retention_test.py
The test fails after a scrub takes 10 minutes since we're using target_runtime (300 * 2). This bumps the timeout to 1800, as is used elsewhere in this test.
* none
=> infinite_retention_test: bump scrub timeout

src/go/k8s/.golangci.yml, src/go/k8s/Dockerfile
Backport of PR https://github.com/redpanda-data/redpanda/pull/13283
=> [v23.2.x] k8s: Bump Go version to v1.21.0

src/go/k8s/go.mod, src/go/k8s/go.sum
Backport of PR https://github.com/redpanda-data/redpanda/pull/13281
=> [v23.2.x] build(deps): bump github.com/stretchr/testify from 1.8.2 to 1.8.4 in /src/go/k8s

src/v/storage/segment_appender.cc, src/v/storage/segment_appender.h
When provided with a sufficiently large chunk of memory, `segment_appender::do_append` may produce deep enough recursion to cause a stack overflow. Fix by switching to a looping construct.
Fixes: https://github.com/redpanda-data/core-internal/issues/749
* none
=> [storage]: remove recursion from segment_appender::do_append

tests/rptest/services/redpanda.py
Previously, we triggered test failure in case if redpanda crashed due to assertion, segfault, ignored exceptional future or undefined behaviour sanitizer failure. Crashes caused by uncaught exceptions were unnoticed. If redpanda terminated due to exception the test would be marked green. This commit fixes this by adding regexes that shold catch this.
Backport of #13307 
Fixes #13322 
* none
=> [v23.2.x] rptest: Trigger test failiure on uncaught exception

src/v/wasm/tests/wasi_test.cc
Fixes #13348
We upgraded the golang version in our CI and that changes the way the initial seed for random numbers is generated, which broke this test. We should not let the test be dependent on the go version, so just disable that assertion.
* none
=> wasm: prevent goversion from changing tests

src/go/k8s/apis/vectorized/v1alpha1/console_types.go, src/go/k8s/pkg/console/deployment.go, src/go/k8s/pkg/console/deployment_internal_test.go
Fixes [#12864 ](https://github.com/redpanda-data/cloudv2/issues/7740)
* add support to the Console API (deprecated) for a user-specified ServiceAccount
=> allow user-specified ServiceAccount name for Console deployment

src/go/k8s/apis/vectorized/v1alpha1/console_types.go, src/go/k8s/pkg/console/deployment.go, src/go/k8s/pkg/console/deployment_internal_test.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/13120
=> [v23.2.x] allow user-specified ServiceAccount name for Console deployment

tests/rptest/tests/consumer_offsets_consistency_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13160
Fixes: https://github.com/redpanda-data/redpanda/issues/13196,
=> [v23.2.x] Made `consumer_offsets_consistency_test.py` more robust

src/v/cluster/cluster_utils.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13109
Fixes: https://github.com/redpanda-data/redpanda/issues/13200,
=> [v23.2.x] c/members_manager: validate if node exists in the cluster before update

tests/rptest/tests/timequery_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12127
Fixes: https://github.com/redpanda-data/redpanda/issues/13212,
=> [v23.2.x] ducktape: extend timeout in timequery_test

src/v/config/configuration.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13292
Fixes: https://github.com/redpanda-data/redpanda/issues/13326,
=> [v23.2.x] cloud_storage: set default upload interval

src/go/rpk/pkg/cli/cluster/config/set.go, src/go/rpk/pkg/cli/redpanda/config.go, src/go/rpk/pkg/cli/redpanda/config_test.go
This PR adds support for using `<key>=<value>` notation when using set commands, specifically this adds support for:
- `rpk redpanda config set`
- `rpk cluster config set`
This is particularly useful when setting negative values.
Fixes #12862
* `rpk cluster config set` and `rpk redpanda config set` now support setting values using the format `<key>=<value>`
=> rpk: Enable key=value notation for every `set` command

src/go/rpk/pkg/cli/topic/consume.go
Before, if you tried to consume from a topic that doesn't exist, rpk was blocked until the topic was created. 
That was confusing so we are failing now in those cases.
Fixes #11136
* rpk: Now rpk will fail if you try to consume from a non-existent topic in `rpk topic consume` instead of blocking the flow.
=> rpk: fail when an unknown topic is passed in consume

src/v/cluster/controller.cc, src/v/cluster/controller.h, src/v/cluster/controller.json, src/v/cluster/security_frontend.cc, src/v/cluster/security_frontend.h, src/v/cluster/service.cc, src/v/cluster/service.h, src/v/cluster/types.h, src/v/kafka/server/handlers/describe_acls.cc, src/v/redpanda/application.cc, tests/rptest/clients/rpk.py, tests/rptest/tests/rpk_acl_test.py
This PR attempts to solve the issue of stale describeACLs responses returned when a preceding modification of an ACL was issued shortly before.
This situation currently occurs because all requests that wish to edit ACL state get proxied to the controller, while all requests to query this state may be handled by a follower. Followers will only have the most up to date copy of the current state when their respective controller_stm's catchup with the leaders. Since the system is eventually consistent w.r.t. replicating the controller commands to followers there is no guarantee for a follower to return the freshest result set.
The proposed fix in this PR is to create a new endpoint to allow a follower to query the last applied offset of the controller log from the leader node. Once obtained, …
=> Allow followers to catchup with leader to return freshest describeACL responses

tests/rptest/services/redpanda_installer.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13019
=> [v23.1.x] ducktape: avoid writing empty release cache file

src/v/cluster/cluster_utils.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13109
Fixes: https://github.com/redpanda-data/redpanda/issues/13199,
=> [v23.1.x] c/members_manager: validate if node exists in the cluster before update

tests/rptest/tests/timequery_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12127
Fixes: https://github.com/redpanda-data/redpanda/issues/13215,
=> [v23.1.x] ducktape: extend timeout in timequery_test

src/go/rpk/pkg/cli/profile/create.go
StringSlice splits all inputs at comma, meaning config.Set cannot work. Currently, people can only input one key=value. If people use a second value (key=value1,value2), the input is split at comma and then config.Set runs against value2 alone (no key) and fails.
For #12802.
* `rpk profile set` now supports multiple comma separate values per key (`key=value1,value2`)
=> rpk profile create: use StringArray rather than StringSlice

src/go/rpk/pkg/cli/redpanda/config.go, src/go/rpk/pkg/config/config_test.go, src/go/rpk/pkg/config/params.go
There was a bug introduced in 23.2 that made setting a TLS struct value impossible via set commands (rpk profile set, rpk redpanda config set). We were just checking for the empty/boolean case.
* rpk/bugfix: enable back setting TLS struct values in set commands
=> rpk/bugfix: enable back setting TLS struct values in set commands

src/go/rpk/pkg/adminapi/api_partition.go, src/go/rpk/pkg/cli/cluster/partitions/cancel.go, src/go/rpk/pkg/cli/cluster/partitions/cancel_hidden.go, src/go/rpk/pkg/cli/cluster/partitions/list.go, src/go/rpk/pkg/cli/cluster/partitions/partitions.go, src/go/rpk/pkg/cli/topic/describe.go, src/go/rpk/pkg/cli/topic/describe_storage.go, src/go/rpk/pkg/out/out.go
In this PR, we add `rpk cluster partitions move-status` that shows ongoing partition movements in the cluster. The command wraps the `/v1/partitions/reconfigurations` endpoint. Example outputs below.
```
$ rpk cluster partitions move-status
ONGOING PARTITION MOVEMENTS
===========================
NAMESPACE-TOPIC  PARTITION  MOVING-FROM  MOVING-TO  COMPLETION-%  PARTITION-SIZE  BYTES-MOVED  BYTES-REMAINING
kafka/foo        0          [1 2 4]      [1 2 3]    5             894159279       50426326     843732953
kafka/foo        4          [1 2 4]      [1 2 3]    4             901834070       43817575     858016495
kafka/foo        7          [1 2 4]      [1 2 3]    8             983639717       81764714     901875003
kafka/foo        8          [1 2 4]      [1 2 3]    9             938510361 …
```
=> rpk: add move-status to show ongoing partition movements

tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/scale_tests/high_throughput_test.py, tests/rptest/services/redpanda.py, tests/rptest/services/redpanda_cloud.py, tests/rptest/test_suite_cloud.yml, tests/rptest/test_suite_ec2.yml
This PR introduces a number of changes to the high throughput tier suite. Most notably:
1. An actual traffic generator that allows all of the tests in the suite to operate under the advertised conditions, throwing if the throughput dips below the advertised
2. Refactor of the suite, unified the `HighThroughputTests` with the `HighThroughput2Tests` class
3. Removed the locally defined tier configurations in place of using the ones defined in `redpanda_cloud.py`
4. Other miscellaneous fixes and cleanup work
* none
=> Add advertised traffic generator for the high throughput tiers test suite

src/v/cloud_storage/partition_probe.h, src/v/cloud_storage/probe.h, src/v/cloud_storage_clients/client_pool.h, src/v/cloud_storage_clients/client_probe.h, src/v/cloud_storage_clients/test_client/abs_test_client_main.cc, src/v/cloud_storage_clients/test_client/s3_test_client_main.cc, src/v/http/demo/client.cc, src/v/kafka/CMakeLists.txt, src/v/kafka/latency_probe.h, src/v/kafka/server/connection_context.cc, src/v/kafka/server/connection_context.h, src/v/kafka/server/handlers/fetch.cc, src/v/kafka/server/handlers/fetch.h, src/v/kafka/server/handlers/handler_probe.cc, src/v/kafka/server/handlers/handler_probe.h, src/v/kafka/server/handlers/produce.cc, src/v/kafka/server/server.h, src/v/net/server.cc, src/v/net/server.h, src/v/pandaproxy/probe.cc, src/v/pandaproxy/probe.h, src/v/rpc/rpc_compiler.py, src/v/rpc/rpc_server.cc, src/v/rpc/rpc_server.h, src/v/rpc/types.h, src/v/utils/CMakeLists.txt, src/v/utils/log_hist.cc, src/v/utils/log_hist.h, src/v/utils/tests/seastar_histogram_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/10623
Backport of PR https://github.com/redpanda-data/redpanda/pull/12036
Backport of PR https://github.com/redpanda-data/redpanda/pull/12295
Backport of PR https://github.com/redpanda-data/redpanda/pull/12460
Backports all PRs/commits related to per handler metrics.
=> Backport per-handler metrics to v23.1

tests/docker/Dockerfile
kinetic reached eol ref https://wiki.ubuntu.com/Releases
from https://gallery.ecr.aws/docker/library/ubuntu
ref redpanda-data/devprod#843
* none
=> tests/docker: Change base image base to jammy
