- src/v/raft/heartbeat_manager.cc
- src/v/raft/heartbeat_manager.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/10915
Fixes https://github.com/redpanda-data/redpanda/issues/11024,
> [v23.1.x] Using `chunked_fifo` in `heartbeat_manager`

- src/v/cloud_storage/remote.cc
- src/v/cloud_storage_clients/configuration.h
- src/v/config/CMakeLists.txt
- src/v/config/configuration.cc
- src/v/config/configuration.h
- src/v/config/tests/CMakeLists.txt
- src/v/config/tests/throughput_control_group_test.cc
- src/v/config/throughput_control_group.cc
- src/v/config/throughput_control_group.h
- src/v/kafka/server/connection_context.cc
- src/v/kafka/server/connection_context.h
- src/v/kafka/server/fwd.h
- src/v/kafka/server/snc_quota_manager.cc
- src/v/kafka/server/snc_quota_manager.h
- src/v/utils/functional.h
- tests/rptest/tests/cluster_config_test.py
- tests/rptest/tests/throughput_limits_snc_test.py
Backport of PR #10755
Fixes #11188
> [v23.1.x] Node-wide throughput exemptions for clients

- src/go/k8s/tests/e2e/resources-cluster/01-make-production.yaml
- src/go/k8s/tests/e2e/resources-cluster/04-clean-cluster.yaml
- src/go/k8s/tests/e2e/resources-cluster/05-assert.yaml
- src/go/k8s/tests/e2e/resources-cluster/05-clean-persistent-volume.yaml
The following CI runs failed:
* https://buildkite.com/redpanda/redpanda/builds/30776#018894ee-07f7-4e2a-8a55-362d5e5365e3/2259-2859
* https://buildkite.com/redpanda/redpanda/builds/30770#0188948f-d179-4c98-a260-45a434e2c77b/2268-2969
* https://buildkite.com/redpanda/redpanda/builds/30757#01889400-b5c1-4f1c-9eb8-776feaf3601a/2263-2870
To identify which deletion is failing this PR split both resources
* none
> k8s: Split cleanup steps to identify which is timing out

- src/go/k8s/cmd/configurator/main.go
- src/go/k8s/go.mod
> replace hashicorp multierr with standard library

- src/go/k8s/Dockerfile
> [v23.1.x] k8s: revert remove --platform flag from operator images' dockerfile

- src/go/k8s/config/manager/manager.yaml
Adding timeout to stop restarts from livenessprobe failures.
* none
> k8s: add a timeout to prevent restarts due to liveness probe issues

- src/go/k8s/config/rbac/bases/operator/role.yaml
- src/go/k8s/controllers/redpanda/redpanda_controller.go
Should allow deletion of helmreleases objects to occur
* none
> k8s: update roles so delete of helmrelease can occur

- tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11387
Fixes https://github.com/redpanda-data/redpanda/issues/11414,
> [v22.2.x] ducktape: use pgrep to find the redpanda process

- tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11387
Fixes https://github.com/redpanda-data/redpanda/issues/11418,
> [v22.3.x] ducktape: use pgrep to find the redpanda process

- tests/rptest/scale_tests/many_clients_test.py
Marked `test_many_clients_pathological_compaction` as `ok_to_fail`
Fixes: #10936 
* None
> dt/many_clients: Split out test_many_clients

- src/v/pandaproxy/auth_utils.h
- src/v/pandaproxy/kafka_client_cache.cc
- src/v/pandaproxy/server.h
- src/v/pandaproxy/test/kafka_client_cache.cc
- src/v/pandaproxy/types.h
- src/v/utils/request_auth.cc
- src/v/utils/request_auth.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/11425
> [v23.1.x] pandaproxy: Support SCRAM-SHA-512 for basic_auth

- tests/rptest/tests/simple_e2e_test.py
Verifiable consumer may fail with two different messages when consuming while the topic is being deleted. Accounting for all the messages in the assertion checking error reporting.
Fixes: #11306
- none
> tests: fixed assertion checking error content

- tests/rptest/scale_tests/partition_balancer_scale_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11470
> [v22.2.x] c/partition_balancer: reduce log level in scale tests

- tests/rptest/scale_tests/partition_balancer_scale_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11470
> [v23.1.x] c/partition_balancer: reduce log level in scale tests

- tests/rptest/scale_tests/partition_balancer_scale_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11470
> [v22.3.x] c/partition_balancer: reduce log level in scale tests

- tests/rptest/services/redpanda.py
Exclude commands that run `redpanda --version` from pgrep
Related: #9052
* none
> ducktape: improve pid dectection v2

- src/v/raft/configuration_manager.cc
Fixed printing content of configuration manager not to include new line after each configuration entry.
Fixes: #11246 
- none
> Fixed printing configuration manager

- tests/rptest/tests/e2e_shadow_indexing_test.py
The test could sometimes fail to upload a sufficient number of segments (e.g. 17k instead of ~25k). It seems to be caused by the fact that segment rolling will not always keep up with the produce rate, resulting in fewer, larger segments than would be calculated by the data and segment size.
This commit bumps the total data size written by an order of magnitude -- the workload won't finish given the test stops the worklaod once a sufficient number of segments is reached.
Fixes https://github.com/redpanda-data/redpanda/issues/11268
* none
> e2e_shadow_indexing_test: bump workload

- tests/rptest/scale_tests/ht_partition_movement_test.py
- tests/rptest/scale_tests/node_operations_fuzzy_test.py
- tests/rptest/scale_tests/partition_balancer_scale_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/8040
Fixes https://github.com/redpanda-data/redpanda/issues/11539,
> [v22.3.x] tests: fixed incorrectly used ^ operator in scale tests

- .github/workflows/old-backports.yml
> old-backport action: change where the command is run [skip-ci]

- tests/rptest/tests/leadership_transfer_test.py
Using progress tracking and unbounded timeout to track topic aware rebalancing. Instead of using a particular timeout value we verify if topic aware rebalancing is making progress. If so we give the test a time to pass.
Fixes: #11454
- none
> Track progress of topic aware rebalancing

- tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11495 
Fixes: #11505
> [v22.2.x] ducktape: improve pid dectection v2

- src/v/rpc/reconnect_transport.cc
> rpc/transport: fix logging

- src/v/archival/ntp_archiver_service.cc
- src/v/cluster/cluster_utils.cc
- src/v/cluster/partition.h
- src/v/cluster/partition_probe.cc
- src/v/kafka/client/transport.h
- src/v/kafka/server/group_manager.cc
- src/v/kafka/server/replicated_partition.cc
- src/v/kafka/server/replicated_partition.h
- src/v/kafka/server/tests/CMakeLists.txt
- src/v/kafka/server/tests/delete_records_utils.cc
- src/v/kafka/server/tests/delete_records_utils.h
- src/v/kafka/server/tests/produce_consume_test.cc
- src/v/kafka/server/tests/produce_consume_utils.cc
This commit pulls out some precursory bits from https://github.com/redpanda-data/redpanda/pull/11579 that aren't directly related to the cloud storage. There are no functional changes in this PR. It includes:
- a rename of `start_offset()` to `raft_start_offset()` for clarity
- test utility changes
- a local-storage-only delete-records fixture test
* none
> miscellaneous non-functional changes for delete records

- tests/rptest/tests/topic_delete_test.py
As soon as a topic is deleted, raft is shut down.  This prevents ntp_archiver from updating archival_metadata_stm after uploading a segment, resulting in an orphan segment after deletion.
Fixes https://github.com/redpanda-data/redpanda/issues/8496
Fixes https://github.com/redpanda-data/redpanda/issues/10655
* none
> tests/topic_delete_test: wait for all uploads before deleting topics

- src/go/k8s/helm-chart/charts/redpanda-operator/Chart.yaml
- src/go/k8s/helm-chart/charts/redpanda-operator/templates/clusterrole.yaml
- src/go/k8s/helm-chart/charts/redpanda-operator/templates/clusterrole_binding.yaml
- src/go/k8s/helm-chart/charts/redpanda-operator/templates/crds/cluster.redpanda.com_redpandas.yaml
- src/go/k8s/helm-chart/charts/redpanda-operator/templates/crds/fluxcd.resources.yaml
- src/go/k8s/helm-chart/charts/redpanda-operator/templates/crds/redpanda.vectorized.io_clusters.yaml
- src/go/k8s/helm-chart/charts/redpanda-operator/templates/crds/redpanda.vectorized.io_consoles.yaml
- src/go/k8s/helm-chart/charts/redpanda-operator/templates/deployment.yaml
- src/go/k8s/helm-chart/charts/redpanda-operator/templates/role.yaml
- src/go/k8s/helm-chart/charts/redpanda-operator/templates/role_binding.yaml
- src/go/k8s/helm-chart/charts/redpanda-operator/values.yaml
Changes to enable deployment of new operator, not by default. 
* Changes to enable deployment of new operator, not by default.
> Redpanda-Operator: chart changes to support new operator

- README.md
add new line for formatting consistency
* none
> README: add newline

- src/v/cloud_storage/tests/async_manifest_view_test.cc
Update retention unit-test to fix it on CI.
* none
> cloud_storage: Fix retention unit-test

- src/v/kafka/server/replicated_partition.cc
Reverts redpanda-data/redpanda#10802
Release notes:
- none
> Revert "[v23.1.x] Backport of bd73f10597aacf6b237834b5bfabd248e6b78864"

- src/v/kafka/server/tests/produce_consume_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11432
Fixes https://github.com/redpanda-data/redpanda/issues/11552,
> [v23.1.x] Add retries to a timing sensitive unit test

- CONTRIBUTING.md
Blocked on PR https://github.com/redpanda-data/vtools/pull/1884
* none
> doc: update CONTRIBUTING.md with details of creating a PR with multiple backports

- src/go/rpk/pkg/cli/topic/config.go
Redpanda does not handle setting both properties
at the same time (see #4499) so as a temporary
workaround we error here.
Fixes #9191
* none
> rpk: work around setting remote.read|write

- src/v/storage/segment.cc
- src/v/storage/segment.h
- src/v/storage/tests/storage_e2e_test.cc
- tests/rptest/tests/log_segment_ms_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11450
Fixes: https://github.com/redpanda-data/redpanda/issues/11542,
> [v23.1.x] s/segment: fixed tracking offsets of empty segments

- src/v/cluster/metadata_dissemination_service.h
> c/metadata_dissemination: switch request queue to chunked_fifo

- src/v/cluster/node/local_monitor.cc
- src/v/resource_mgmt/storage.cc
- src/v/resource_mgmt/storage.h
- src/v/storage/node.h
- src/v/storage/types.h
Some misc changes I'm plucking off a larger PR.
* none
> Misc space management changes

- src/v/cluster/metadata_dissemination_service.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/11696
Fixes https://github.com/redpanda-data/redpanda/issues/11714,
> [v23.1.x] c/metadata_dissemination: switch request queue to chunked_fifo

- src/v/redpanda/admin_server.h
Cache management PR raced with node storage PR, both edited includes.
* none
> admin: fix cloud storage #include

- tests/rptest/tests/topic_creation_test.py
> topic_creation_test: set a lower bound of 4 message to produce

- tests/rptest/util.py
further work on top of https://github.com/redpanda-data/redpanda/pull/11733
Fixes #11182 
Fixes #11765
* none
> rptest/util: wait_for_local_storage_truncate robust on empty partitions

- src/v/archival/ntp_archiver_service.cc
- src/v/archival/ntp_archiver_service.h
- src/v/archival/probe.cc
- src/v/cloud_storage/tests/CMakeLists.txt
- src/v/cloud_storage/tests/cloud_storage_e2e_test.cc
- src/v/cloud_storage/tests/produce_utils.h
- src/v/cloud_storage/tests/read_replica_test.cc
- src/v/config/configuration.cc
- src/v/config/configuration.h
- src/v/kafka/server/tests/produce_consume_test.cc
- src/v/kafka/server/tests/produce_consume_utils.h
- src/v/redpanda/tests/fixture.h
This PR adds a few improvements to test fixture infra that I intend on using for testing delete-records (and beyond):
- Adds a config to be used in test to omit the upload/RRR loop
- Adds a test method to the archiver to sync, to be used in test bodies rather than in background loops
- Wraps producer test code with segment-generating abstraction
- Replaces `kv_t` underlying type with a struct
- Disables archiver probes when metrics are disabled (avoids a double registration in the new read replica fixture test)
- Adds a small fixture test for read replicas
* none
> cloud_storage: test fixture improvements

- tests/rptest/tests/timequery_test.py
Fixes #11746 
Adds test coverage for chunk read path when timequeries are issued. 
The version before this PR relied on each time query downloading a single segment. The change here asserts that the bytes downloaded for each time query are less than segment size. 
The new assertion is weaker and less precise, but it is necessary when using chunked reads, as during a time query all of the chunks in a segment need to be downloaded (until the queried element is found). 
Since each chunk download is registered in metrics as a segment download, the increase in segment downloads now may be larger than one. We cannot calculate the exact number of chunks in a segment during the test, but adding up the bytes downloaded and asserting that we are downloading less than one segment size is a close …
> ducktape: Add chunk read to timequery tests

- src/v/rpc/transport.cc
- src/v/rpc/transport.h
- src/v/ssx/future-util.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/11729 Closes #11754
> [v23.1.x] rpc: Handle errors while holding a gate

- src/v/rpc/transport.cc
- src/v/rpc/transport.h
- src/v/ssx/future-util.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/11729
closes #11755
> [v22.3.x] rpc: Handle errors while holding a gate

- src/v/cluster/partition_balancer_planner.cc
- tests/rptest/tests/scaling_up_test.py
Don't mark counts rebalancing as finished if there are unavailable or otherwise unhealthy nodes - if they become healthy later, the partition distribution won't be optimal.
Fixes https://github.com/redpanda-data/redpanda/issues/10185#issuecomment-1613464499
* none
> Fix rebalance in presence of unavailable nodes

- tests/docker/cdt_ducktape_deps.sh
> [v23.1.x] add cdt script to install dt deps on cdt infra

- tests/docker/cdt_ducktape_deps.sh
> [v22.2.x] add cdt script to install dt deps on cdt infra

- src/v/config/configuration.cc
- src/v/config/configuration.h
- src/v/resource_mgmt/storage.cc
- src/v/storage/disk_log_impl.cc
- tests/rptest/remote_scripts/disk_usage.py
- tests/rptest/scale_tests/log_storage_target_size_test.py
- tests/rptest/services/redpanda.py
Add scale test for log storage target size
* none
> Add scale test for log storage target size

- src/v/cloud_storage/partition_manifest.cc
- src/v/cloud_storage/partition_manifest.h
- src/v/cluster/log_eviction_stm.cc
- src/v/cluster/log_eviction_stm.h
- src/v/cluster/partition.cc
This PR includes some small changes to delete-records, mostly flagged in review:
- Plumbed the replication offset from log_eviction_stm so it can be waited for by archival_metadata_stm, instead of blindly using the Raft committed offset
- In cloud, renamed _start_kafka_offset to _start_kafka_offset_override, as is referenced in the Kafka layer
- Improve logging
- Use `likely`
* none
> cloud_storage: follow-up changes for delete records

- src/go/k8s/kuttl-test.yaml
- src/go/k8s/tests/e2e/update-image-and-node-port/02-assert.yaml
- src/go/k8s/tests/e2e/update-image-and-node-port/02-v22-2-13-with-si-pv-addition.yaml
- src/go/k8s/tests/e2e/update-image-and-node-port/03-assert.yaml
- src/go/k8s/tests/e2e/update-image-and-node-port/03-v22-3-22.yaml
- src/go/k8s/tests/e2e/update-image-and-node-port/04-assert.yaml
- src/go/k8s/tests/e2e/update-image-and-node-port/04-v23-1-13.yaml
- src/go/k8s/tests/e2e/update-image-tls-client-auth-external-ca/01-assert.yaml
- src/go/k8s/tests/e2e/update-image-tls-client-auth-external-ca/01-v23-1-13.yaml
- src/go/k8s/tests/e2e/update-image-tls-client-auth-no-external-ca/02-assert.yaml
- src/go/k8s/tests/e2e/update-image-tls-client-auth-no-external-ca/02-v22-2-13-with-si-pv-addition.yaml
- src/go/k8s/tests/e2e/update-image-tls-client-auth-no-external-ca/03-assert.yaml
- src/go/k8s/tests/e2e/update-image-tls-client-auth-no-external-ca/03-v22-3-22.yaml
- src/go/k8s/tests/e2e/update-image-tls-client-auth-no-external-ca/04-assert.yaml
- src/go/k8s/tests/e2e/update-image-tls-client-auth-no-external-ca/04-v23-1-13.yaml
- src/go/k8s/tests/e2e/update-image-tls-no-client-auth/02-assert.yaml
- src/go/k8s/tests/e2e/update-image-tls-no-client-auth/02-v22-2-13-with-si-pv-addition.yaml
- src/go/k8s/tests/e2e/update-image-tls-no-client-auth/03-assert.yaml
- src/go/k8s/tests/e2e/update-image-tls-no-client-auth/03-v22-3-22.yaml
- src/go/k8s/tests/e2e/update-image-tls-no-client-auth/04-assert.yaml
- src/go/k8s/tests/e2e/update-image-tls-no-client-auth/04-v23-1-13.yaml
The https://github.com/redpanda-data/redpanda/pull/11544 change should solve E2E tests failure when
upgrade test is stuck between v23.1.X and tip of the dev version.
https://github.com/redpanda-data/redpanda/releases/tag/v23.1.13 https://github.com/redpanda-data/redpanda/releases/tag/v22.3.22 https://github.com/redpanda-data/redpanda/releases/tag/v22.2.13
* none
> k8s: Bump Redpanda versions

- src/v/cluster/controller_api.cc
- src/v/cluster/controller_api.h
- src/v/kafka/server/handlers/topics/topic_utils.cc
> c/topics: reduce task parallelism when creating topics with lots of partitions

- src/go/k8s/controllers/redpanda/cluster_migration_controller.go
Every time reconciliation is called the start and end log line doesn't mean anything at the info level. The same instrumentation can be done using metrics.
* none
> Change log level in normal reconciliation

- src/go/k8s/Makefile
- src/go/k8s/config/rbac/bases/operator/role.yaml
- src/go/k8s/controllers/redpanda/redpanda_controller.go
- src/go/k8s/hack/get-redpanda-info.sh
- src/go/k8s/helm-chart/charts/redpanda-operator/templates/deployment.yaml
- src/go/k8s/helm-chart/charts/redpanda-operator/templates/role.yaml
- src/go/k8s/kuttl-v2-test.yaml
- src/go/k8s/tests/e2e-v2/resource-redpanda-crud/00-assert-create-redpanda.yaml
- src/go/k8s/tests/e2e-v2/resource-redpanda-crud/00-create-redpanda.yaml
- src/go/k8s/tests/e2e-v2/resource-redpanda-crud/01-assert-update-chart-version.yaml
- src/go/k8s/tests/e2e-v2/resource-redpanda-crud/01-update-chart-version.yaml
- src/go/k8s/tests/e2e-v2/resource-redpanda-crud/02-assert-update-clusterspec.yaml
- src/go/k8s/tests/e2e-v2/resource-redpanda-crud/02-update-clusterspec.yaml
- src/go/k8s/tests/e2e-v2/resource-redpanda-crud/03-assert.yaml
- src/go/k8s/tests/e2e-v2/resource-redpanda-crud/03-delete-redpandas.yaml
Fix operator helm chart deployment where permissions where not correctly set up.
The K8S Role are now in sync between kustomize and helm chart. They are generated
via `make manifests` (`controller-gen` behind the scenes)
Change log level setting for operator helm chart.
* none
> Create test pipeline for operator V2

- src/v/archival/upload_housekeeping_service.cc
Partial backport of https://github.com/redpanda-data/redpanda/pull/10831
* Redpanda will now report upload housekeping metrics.
> archival: wire probe into housekeeping service

- src/v/cluster/controller_api.cc
- src/v/cluster/controller_api.h
- src/v/kafka/server/handlers/topics/topic_utils.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11738
Fixes: https://github.com/redpanda-data/redpanda/issues/11893,
> [v23.1.x] c/topics: reduce task parallelism when creating topics with lots of partitions

- src/go/k8s/pkg/resources/statefulset_update.go
- src/go/k8s/pkg/resources/statefulset_update_test.go
pods are sorted alphabetically resulting in rolling restarts operating on:
> Pod 0 - Pod 1 - Pod 10 - Pod 11 - Pod 2 ....
This orders the podlist by ordinal
* none
> operator: sort pods by ordinal

- src/v/storage/disk_log_impl.cc
Noah noted that the current iteration is unsafe because nothing ensures that _segs iterators remain stable across the scheduling points.
This patch fixes this by collecting all-bogus segments and tweaking them at the end of the method, where we can guarantee that the container doesn't change.
* Fixed a potential invalid memory access when iterating through segments with timestamps in the future.
> storage: fix coroutine iteration over _segs

- src/v/cloud_storage/segment_meta_cstore.cc
Stop using transactional version of the 'append' method due to its overhead. Make sure that the column_store can't be left in the inconsistent state by terminating redpanda in case of exception.
Fixes #11952
* none
> cloud_storage: Append data to the column_store without transactions

- tests/rptest/tests/cluster_bootstrap_test.py
Dropped the test validating upgrade from v22.2.x version which didn't set the cluster UUID.
Fixes: #10362
- none
> tests: dropped upgrading from v22.2 version

- src/v/cloud_storage/tests/delete_records_e2e_test.cc
- src/v/kafka/server/tests/produce_consume_utils.h
This adds tests for truncating in cloud after receiving delete-records request.
* none
> tests: fixture test for offset-based retention

- src/v/cluster/rm_stm.cc
- src/v/cluster/rm_stm.h
Backport of PR #10671
Fixes #10821
* none
> [v22.3.x] Fix aborted txs being visible

- src/go/k8s/controllers/redpanda/cluster_controller.go
- src/go/k8s/pkg/resources/certmanager/ca_certificate_bundle.go
- src/go/k8s/pkg/resources/certmanager/pki.go
- src/go/k8s/pkg/resources/cluster_role_binding.go
- src/go/k8s/pkg/resources/configmap.go
- src/go/k8s/pkg/resources/secret.go
- src/go/k8s/pkg/resources/statefulset.go
- src/go/k8s/pkg/resources/superusers.go
* removes the finalizer if annotations mark the Cluster as not being managed
> improve Cluster reconciler readability

- src/v/cluster/rm_stm.cc
- src/v/cluster/rm_stm.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/11887
> [v22.3.x] Add metric to monitor seq table size

- src/v/cloud_storage/remote_partition.cc
`remote_partition::is_data_available` is on the hot path of fetch requests and is called for all of them. Previously, it called in to `segment_meta_cstore::{size,find}`. Both are rather expensive operations. The query can be answered without touching the cstore by using these two observations:
1. If the start offset for the STM region is not set, the the cloud is empty. This is the case if no segments were uploaded yet, or if all segments were truncated by retention.
2. If the start offset is set to a value greater than the end of the cloud log, then the cloud log is emtpy. This is the case if cloud retention advances the start offset to truncate all segments, but GC and the subsequent truncation did not run yet.
* none
> cloud_storage: optimise data availability check

- tools/redpanda-gdb.py
> Updated redpanda gdb

- tests/rptest/tests/follower_fetching_test.py
In the follower fetching tests we check if all fetch requests are handled by the replica in the same rack as the consumer. When leadership changes it may happen that the follower will have to contact the leader and refresh its metadata. In this case the test would fail as there would be some bytes sent to the follower from the node other than the closest replica. To prevent this from happening and make the test stable disabled the leader balancer to prevent leadership from being transferred.
Fixes: #11134
Fixes: #11992
- none
> Disable leader balancer in follower fetching test

- tests/rptest/services/redpanda.py
raise_on_cloud_storage_inconsistencies is similar to stop_and_scrub_cloud_storage, it uses
rp-storage-tool to check uploaded data. the main difference is that is
does not stop the cluster, and needs a list of anomalies to raise for.
It's meant to be used while a cluster is running, when the tool might
see some temporary inconsistencies
the second commit increases log level to warn for rp-storage-tool. this output is useful to understand the anomalies reported by the tool
* none
> tests/rp-storage-tool raise_on_cloud_storage_inconsistencies and log warn output

- src/v/cloud_storage/tests/segment_meta_cstore_test.cc
test_cstore_prefix_truncate randomly tries to dereference an end iterator of a vector generated for the test. 
the fix is to cap the range of the index
Fixes #11884 
* none
> t/segment_meta_cstore_test: fix oob access in test vector

- src/v/kafka/server/server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12042
Fixes: https://github.com/redpanda-data/redpanda/issues/12051,
> [v23.1.x] k/server: Better handling of SCRAM parsing errors

- src/v/kafka/server/handlers/sasl_authenticate.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12042 
Fixes #12050
> [v22.3.x] k/server: Better handling of SCRAM parsing errors

- src/v/archival/ntp_archiver_service.cc
- tests/rptest/tests/upgrade_test.py
We disable the upload loop while in a mixed version state. If we have to
rollback, we can end up with a system where the archival stm is stuck on
all nodes (the only way to get unstuck would be to finish the upgrade).
The system would look fine: can produce and consume, but uploads
wouldn't proceed and it leaves us vulnerable to disks filling up.
* none
> archival: block upload loop mid-upgrade

- src/v/kafka/server/handlers/sasl_authenticate.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12042
> [v22.2.x] k/server: Better handling of SCRAM parsing errors

- src/go/k8s/Makefile
- src/go/k8s/apis/redpanda/v1alpha1/redpanda_clusterspec_types.go
- src/go/k8s/apis/redpanda/v1alpha1/zz_generated.deepcopy.go
- src/go/k8s/config/crd/bases/cluster.redpanda.com_redpandas.yaml
- src/go/k8s/config/rbac/bases/operator/role.yaml
- src/go/k8s/controllers/redpanda/redpanda_controller.go
- src/go/migration-cli/tests/simple_cluster_test.go
This PR is a WIP to address various api changes/issues with new operator
Fixes #12049
* none
> Redpanda-Operator: api changes/fixes

- tests/docker/Dockerfile
- tests/docker/Dockerfile.dockerignore
- tests/rptest/services/redpanda.py
> docker: Added lsan_suppressions.txt file to docker

- src/v/cluster/rm_stm.cc
Using batch timestamps for pid expiration may result in unexpected
behavior when the batches are marked with past/future timestamps.
This patch switches to using broker's system clock for the same.
Clock drift among brokers is particularly not a concern in this code
path because the default expiration timeout is 7d.
* none
> rm_stm: use system time for producer expiration tracking

- src/v/raft/consensus.cc
- src/v/raft/consensus.h
- src/v/raft/heartbeat_manager.cc
- src/v/raft/heartbeat_manager.h
- src/v/raft/service.h
Improved performance of handling Raft heartbeats. Previously heartbeats were using a simple and naive approach of dispatch logic. Improved the logic by reducing number of allocations and lookups. 
Optimized the way how heartbeat requests are created. By minimizing the
number of lookups in the follower state map and not querying
configuration of a raft group at all.
Previously the heartbeat dispatch used foreign pointers and eager
conversion to `append_entries_request`. Replaced dispatching logic to
defer creation of `append_entries_request` to the point where it is
required. This way we are able to skip the foreign pointer wrapper.
- reduced complexity of sending hearbeats
> Improved heartbeats handling 

- src/v/kafka/server/connection_context.cc
- src/v/kafka/server/connection_context.h
- src/v/kafka/server/handlers/handler_probe.cc
- src/v/kafka/server/handlers/handler_probe.h
- src/v/utils/log_hist.h
- src/v/utils/tests/seastar_histogram_test.cc
Having per-handler latency histograms allows us to quick divide the search space for performance issues into smaller per-handler code paths. This allow us quicker insight into where high reactor utilization or end-to-end latency could be originating from.  
* adds a `kafka_handler_latency_seconds` metric to the internal metrics endpoint that provides per-method-type latency histograms
> Add per kafka handler histograms to metrics

- tests/rptest/tests/archive_retention_test.py
Previously, `CloudArchiveRetentionTest.test_delete` did not wait for all uploads to complete before picking the truncation point and setting the retention accordingly. This was problematic because more segments were deleted than the incorrect expectation.
Also fix the `wait_until` error message which was displaying the initial count of deleted segments (usually 0).
Fixes https://github.com/redpanda-data/redpanda/issues/12104
* none
> rptest: quiesce uploads before picking retention

- tests/rptest/tests/partition_force_reconfiguration_test.py
It appears that the __consumer_offsets topic is taking a bit of time to stabilize it's leadership in debug builds with all the chaos (16 partitions, 7 replicas, 3/7 nodes dead). This patch waits for stable leadership of consumer offsets before proceeding with validation.
Fixes #12000
* none
> ducktape: wait for consumer_offsets parititions to stabilize

- src/go/k8s/helm-chart/charts/redpanda-operator/templates/deployment.yaml
> Fix indentation issue for redpanda-operator helm chart

- src/go/k8s/helm-chart/charts/redpanda-operator/templates/deployment.yaml
Backport of PR https://github.com/redpanda-data/redpanda/pull/12008
Fixes: https://github.com/redpanda-data/redpanda/issues/12170,
> [v23.2.x] Fix indentation issue for redpanda-operator helm chart

- tests/docker/Dockerfile
- tests/docker/Dockerfile.dockerignore
- tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12029
Fixes: https://github.com/redpanda-data/redpanda/issues/12099,
> [v23.1.x] docker: Added lsan_suppressions.txt file to docker

- tests/docker/Dockerfile
Backport of PR https://github.com/redpanda-data/redpanda/pull/11220
> [v23.1.x] ducktape-deps: fix installing confluent-kafka on arm64

- src/v/cluster/rm_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11887
Fixes: https://github.com/redpanda-data/redpanda/issues/11986,
> [v23.1.x] Add metric to monitor seq table size

- src/v/cluster/partition_probe.cc
- tests/rptest/tests/cluster_metrics_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/9334
> [v23.2.x] kafka: expose hwm for max offset in public metrics

- src/go/k8s/apis/redpanda/v1alpha1/redpanda_clusterspec_types.go
- src/go/k8s/apis/redpanda/v1alpha1/zz_generated.deepcopy.go
Removing the use of unstructured type as this caused issues with the controller.
* none
> Redpanda-Operator: API removing unstructured for configs of console

- src/v/kafka/server/handlers/handler_probe.cc
- src/v/kafka/server/handlers/handler_probe.h
- src/v/utils/log_hist.h
Changes the `log_hist` to have deleted move and copy constructors. And reduces the number of in-progress requests for a handler when an error occurs.
* none
> Various fixes for per handler metrics

- tools/dev_cluster.py
Add schema registry and pandaproxy to dev_cluster.py
* none
> Add schema registry and pandaproxy to dev_cluster.py

- src/v/kafka/server/handlers/handler_probe.cc
- src/v/kafka/server/handlers/handler_probe.h
- src/v/utils/log_hist.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/12295
> [v23.2.x] Various fixes for per handler metrics

- src/v/cluster/health_monitor_types.cc
- src/v/cluster/partition_balancer_planner.cc
- src/v/cluster/partition_balancer_planner.h
- src/v/cluster/tests/partition_balancer_planner_fixture.h
- src/v/cluster/tests/partition_balancer_planner_test.cc
- src/v/cluster/tests/partition_balancer_simulator_test.cc
- tests/rptest/tests/custom_topic_assignment_test.py
- tests/rptest/tests/isolated_decommissioned_node_test.py
- tests/rptest/tests/partition_balancer_test.py
- tests/rptest/tests/partition_force_reconfiguration_test.py
- tests/rptest/tests/partition_move_interruption_test.py
- tests/rptest/tests/partition_movement_test.py
- tests/rptest/tests/self_test_test.py
- tests/rptest/tests/topic_delete_test.py
This PR integrates partition balancer with new space management policies introduced in https://github.com/redpanda-data/redpanda/pull/12091
High level changes are as follows.
* #12091 exposes new disk usage reporting via health monitor API
* partition balancer switches to using the new API instead of disk based usage statistics
* some additional test stabilization fixes, some of them found in repeat runs and not related to the PR itself.
* none
> partition_balancer with new space management

- src/v/cluster/health_monitor_types.cc
- src/v/cluster/partition_balancer_planner.cc
- src/v/cluster/partition_balancer_planner.h
- src/v/cluster/tests/partition_balancer_planner_fixture.h
- src/v/cluster/tests/partition_balancer_planner_test.cc
- src/v/cluster/tests/partition_balancer_simulator_test.cc
- tests/rptest/tests/custom_topic_assignment_test.py
- tests/rptest/tests/isolated_decommissioned_node_test.py
- tests/rptest/tests/partition_balancer_test.py
- tests/rptest/tests/partition_force_reconfiguration_test.py
- tests/rptest/tests/partition_move_interruption_test.py
- tests/rptest/tests/partition_movement_test.py
- tests/rptest/tests/self_test_test.py
- tests/rptest/tests/topic_delete_test.py
This PR integrates partition balancer with new space management policies introduced in https://github.com/redpanda-data/redpanda/pull/12091
High level changes are as follows.
https://github.com/redpanda-data/redpanda/pull/12091 exposes new disk usage reporting via health monitor API
partition balancer switches to using the new API instead of disk based usage statistics
some additional test stabilization fixes, some of them found in repeat runs and not related to the PR itself.
* none
> [backport] [v23.2.x] partition_balancer with new space management #12112

- tests/rptest/tests/services_self_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11092
Fixes: https://github.com/redpanda-data/redpanda/issues/11098
> [v23.1.x] tests: skip service self-tests in debug mode

- tests/rptest/utils/node_operations.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/9198
Fixes: https://github.com/redpanda-data/redpanda/issues/12149,
> [v23.1.x] tests/node_ops: ignore errors from fault injected nodes

- src/v/archival/ntp_archiver_service.cc
- src/v/cloud_storage/async_manifest_view.cc
- src/v/cloud_storage/tests/async_manifest_view_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12177
> [v23.2.x] cloud_storage: skip below clean offset in archive sized retention and other fixes

- src/go/k8s/apis/redpanda/v1alpha1/redpanda_clusterspec_types.go
- src/go/k8s/apis/redpanda/v1alpha1/zz_generated.deepcopy.go
Removing the use of unstructured type as this caused issues with the controller.
Backport of PR https://github.com/redpanda-data/redpanda/pull/12297 
Fixes #12301
- [] v23.2.x
* none
> [v23.2.x] Redpanda-Operator: API removing unstructured for configs of console

- src/v/cluster/persisted_stm.cc
- src/v/cluster/rm_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12155
Fixes: https://github.com/redpanda-data/redpanda/issues/12337,
> [v23.2.x] Fixed taking snapshot in `rm_stm`

- tests/rptest/tests/controller_availability_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12305
Fixes: https://github.com/redpanda-data/redpanda/issues/12332,
> [v23.2.x] Sort nodes before stopping them in `ControllerAvailabilityTest`

- tests/docker/cdt_ducktape_deps.sh
> [v22.3.x] add cdt script to install dt deps on cdt infra

- src/go/rpk/pkg/cli/cloud/login.go
- src/go/rpk/pkg/cli/profile/create.go
Adds messaging about cluster details when a user logs into the cloud. No release notes since this is a part of newly released features that have previously been noted.
* none
> rpk: add messaging when a user logs into the cloud

- src/v/archival/ntp_archiver_service.cc
- src/v/archival/segment_reupload.cc
- src/v/storage/offset_to_filepos.cc
- src/v/storage/offset_to_filepos.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/12345
Fixes: https://github.com/redpanda-data/redpanda/issues/12352,
> [v23.2.x] archival: Reject segment reupload if candidate lies inside compacted batch

- src/go/rpk/pkg/cli/cloud/login.go
- src/go/rpk/pkg/cli/profile/create.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/12351
> [v23.2.x] rpk: add messaging when a user logs into the cloud

- src/v/cluster/log_eviction_stm.cc
- src/v/kafka/server/replicated_partition.cc
- tests/rptest/tests/delete_records_test.py
Backporting #12883 to v23.2.x
* Fixes a bug where unknown_server_error is incorrectly returned as an error code in situations where it shouldn't on call to delete-records
> Backport of PR #12883 to v23.2.x

- src/v/cloud_storage/offset_translation_layer.cc
- src/v/model/record_batch_types.h
- src/v/raft/consensus.cc
- src/v/storage/segment_utils.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/12349
> [v23.2.x] storage: Do not hardcode set of batch types in storage

- tests/rptest/scale_tests/log_storage_target_size_test.py
Fix test
Fixes https://github.com/redpanda-data/redpanda/issues/12281
* none
> Fix space mgmt scale test

- src/go/rpk/pkg/cli/cloud/byoc/byoc.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/12379
> [v23.2.x] rpk cloud byoc: pass --redpanda-id to the plugin

- tests/rptest/remote_scripts/compute_storage.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12346
> [v23.2.x] Make compute_storage.py robust to directories being deleted

- src/v/pandaproxy/schema_registry/protobuf.cc
- src/v/pandaproxy/schema_registry/test/compatibility_protobuf.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12373
Fixes: https://github.com/redpanda-data/redpanda/issues/12405,
> [v23.2.x] schema_registry: Improve the ordering of protobuf files

- src/v/archival/ntp_archiver_service.cc
- src/v/archival/segment_reupload.cc
- src/v/archival/tests/segment_reupload_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11367
Fixes https://github.com/redpanda-data/redpanda/issues/11426,
> [v23.1.x] archival: fix collection for adjacent reupload

- src/v/pandaproxy/schema_registry/protobuf.cc
- src/v/pandaproxy/schema_registry/test/compatibility_protobuf.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12373
Fixes: https://github.com/redpanda-data/redpanda/issues/12408,
> [v22.3.x] schema_registry: Improve the ordering of protobuf files

- src/v/cluster/persisted_stm.cc
- src/v/cluster/rm_stm.cc
- tests/rptest/services/admin_ops_fuzzer.py
- tests/rptest/services/verifiable_consumer.py
- tests/rptest/tests/controller_erase_test.py
- tests/rptest/tests/end_to_end.py
- tests/rptest/tests/simple_e2e_test.py
Bacporting: 
- https://github.com/redpanda-data/redpanda/pull/11970
- https://github.com/redpanda-data/redpanda/pull/12155
- https://github.com/redpanda-data/redpanda/pull/11457
- https://github.com/redpanda-data/redpanda/pull/11448
- https://github.com/redpanda-data/redpanda/pull/10801
- https://github.com/redpanda-data/redpanda/pull/11484
Fixes: #11981, #12338 
- none
> [v23.1.x] Backport of #11970 #12155 #11457 #11484 #10801 #11448

- src/v/kafka/server/handlers/describe_producers.cc
- tests/rptest/tests/transaction_kafka_api_test.py
PR fixes describe producers api to return correct last timestamp
Fixes https://github.com/redpanda-data/redpanda/issues/11949
* none
> txns: fix describe producers api to return correct last timestamp

- tests/rptest/tests/nodes_decommissioning_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/9783
Fixes: https://github.com/redpanda-data/redpanda/issues/12420,
> [v23.1.x] tests: made decommissioning operation more reliable

- src/go/k8s/pkg/resources/secret.go
- src/go/k8s/tests/e2e/update/02-assert.yaml
- src/go/k8s/tests/e2e/update/02-update-resources.yaml
> operator: timeout cannot run functions

- src/go/k8s/apis/redpanda/v1alpha1/redpanda_clusterspec_types.go
- src/go/k8s/apis/redpanda/v1alpha1/zz_generated.deepcopy.go
- src/go/k8s/config/crd/bases/cluster.redpanda.com_redpandas.yaml
Further testing on migration, found a few api changes that made more sense and fixed issues with allowing migrations to happen wht making changes to the clusterSpec.config field. 
* none
> k8s: update and fix migration by updating crds

- src/v/cloud_storage/remote_segment.cc
- src/v/cloud_storage/remote_segment.h
- src/v/cloud_storage/tests/common_def.h
- src/v/cloud_storage/tests/remote_partition_test.cc
- src/v/cloud_storage/tests/remote_segment_index_test.cc
- src/v/cloud_storage/tests/util.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12383
> [v23.2.x] cloud_storage: Add compacted segment read-path tests

- tests/rptest/scale_tests/log_storage_target_size_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12367
Fixes: https://github.com/redpanda-data/redpanda/issues/12384,
> [v23.2.x] Fix space mgmt scale test

- src/v/cluster/log_eviction_stm.cc
- src/v/cluster/log_eviction_stm.h
- src/v/raft/consensus.h
Log eviction STM previously was using a condition variable and raft
offset monitor to synchronize processing of two different eviction
events types i.e. storage driven eviction and delete record related
eviction. The coordination between the fiber executing eviction and the
the one requesting it was complicated. Changed the coordination logic to
use a queue where all the eviction requests are enqueued and the fibre
simply executes them in sequence.
- fixes rare issue that may lead to a situation in which retention will stuck
> Changed implementation of log eviction stm to use queue

- tests/rptest/tests/cloud_storage_chunk_read_path_test.py
When asserting at the end of a test that the cache has been trimmed, instead of making a one-shot request, we retry for a while so that any lingering fetch requests are served before the cache is trimmed.
FIXES: #12441 
* none
> cloud_storage/ducktape: Wait for cache to be trimmed

- src/v/archival/ntp_archiver_service.cc
- src/v/cloud_storage/async_manifest_view.cc
- src/v/cloud_storage/async_manifest_view.h
- src/v/cloud_storage/remote_partition.cc
- src/v/cloud_storage/tests/async_manifest_view_test.cc
- src/v/ssx/task_local_ptr.h
- src/v/ssx/tests/CMakeLists.txt
- src/v/ssx/tests/task_local_ptr_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12316
> [v23.2.x] cloud_storage: Spillover race prevention

- src/v/cluster/partition_balancer_backend.cc
If partition sizes are missing, we force-refresh the health monitor. The problem is that this doesn't guarantee that they will appear (e.g. if all partition replicas are on dead nodes, they won't). In this case the balancer will try to plan in a busy-loop. To fix this, do force-refresh only once and if it doesn't help, revert to sleeping before the next tick.
Fixes https://github.com/redpanda-data/redpanda/issues/12307
* none
> c/partition_balancer: force-refresh health monitor only once

- src/v/cluster/log_eviction_stm.cc
- src/v/cluster/log_eviction_stm.h
- src/v/cluster/tests/CMakeLists.txt
- src/v/cluster/tests/eviction_stm_test.cc
Backport of https://github.com/redpanda-data/redpanda/pull/12476
Removes the queue-based signaling in log_eviction_stm, which proved to
be a bit error prone.
Instead, this reverts to the old implementation using a
condition_variable, but leaves out the offset monitor, which doesn't
seem needed.
Now, either storage or delete-records will bump their respective
offsets, and the event-processing loop will take the higher and truncate
to it. If this isn't finished, the process is repeated after some
timeout.
* none
> log_eviction_stm: further cleanup

- src/v/cluster/log_eviction_stm.cc
- src/v/cluster/log_eviction_stm.h
- src/v/cluster/tests/CMakeLists.txt
- src/v/cluster/tests/eviction_stm_test.cc
Backport of https://github.com/redpanda-data/redpanda/pull/12476
Removes the queue-based signaling in log_eviction_stm, which proved to
be a bit error prone.
Instead, this reverts to the old implementation using a
condition_variable, but leaves out the offset monitor, which doesn't
seem needed.
Now, either storage or delete-records will bump their respective
offsets, and the event-processing loop will take the higher and truncate
to it. If this isn't finished, the process is repeated after some
timeout.
* none
> [v23.2.x] log_eviction_stm: further cleanup

- src/go/rpk/pkg/cli/redpanda/start.go
- src/go/rpk/pkg/cli/redpanda/start_test.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/12161
Fixes: https://github.com/redpanda-data/redpanda/issues/12183,
> [v23.2.x] rpk: strip quotes from additional start args

- .github/workflows/lint.yml
- .github/workflows/rpk-build.yml
- src/go/rpk/.golangci.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/12378
> [v23.2.x] rpk, github: use latest stable golang

- src/go/rpk/pkg/cli/cloud/byoc/install.go
- src/go/rpk/pkg/config/config.go
- tests/docker/Dockerfile
- tests/docker/ducktape-deps/byoc-mock
- tests/go/byoc-mock/go.mod
- tests/go/byoc-mock/go.sum
- tests/go/byoc-mock/main.go
- tests/rptest/clients/rpk.py
- tests/rptest/tests/rpk_plugin_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12456
> [v23.2.x] rpk: Test `rpk plugin` and managed plugin flag handling.

- src/v/cluster/tx_gateway_frontend.cc
- tests/rptest/tests/transaction_kafka_api_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12130
Fixes: https://github.com/redpanda-data/redpanda/issues/12452,
> [v23.2.x] transactions: fix ListTransactions to return open transactions

- src/v/cluster/partition_balancer_backend.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12446
Fixes: https://github.com/redpanda-data/redpanda/issues/12481,
> [v23.2.x] c/partition_balancer: force-refresh health monitor only once

- tests/rptest/tests/nodes_decommissioning_test.py
> tests: add decom+space management test

- src/go/k8s/controllers/redpanda/cluster_controller.go
- src/go/k8s/tests/e2e/lost-redpanda-decommission/00-assert.yaml
- src/go/k8s/tests/e2e/lost-redpanda-decommission/00-cluster.yaml
- src/go/k8s/tests/e2e/lost-redpanda-decommission/01-assert.yaml
- src/go/k8s/tests/e2e/lost-redpanda-decommission/01-decommission-and-remove-rp.yaml
Backport of PR https://github.com/redpanda-data/redpanda/pull/12514
Fixes: https://github.com/redpanda-data/redpanda/issues/12517,
> [v23.2.x] k8s: Fix decommission logic when annotation is set

- src/v/kafka/server/handlers/describe_producers.cc
- tests/rptest/tests/transaction_kafka_api_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12285
Fixes: https://github.com/redpanda-data/redpanda/issues/12432,
> [v23.2.x] txns: fix describe producers api to return correct last timestamp

- src/go/k8s/controllers/redpanda/cluster_controller.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/12524
> [v23.2.x] Report Redpanda Node ID as label

- src/v/cluster/controller_stm.cc
- src/v/cluster/topics_frontend.cc
- src/v/kafka/server/tests/fetch_test.cc
- src/v/kafka/server/tests/list_offsets_test.cc
- src/v/redpanda/tests/fixture.h
- tests/rptest/tests/topic_creation_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12506
> [v23.2.x] c/create_topics: improvements to create_topic workflow

- .github/workflows/redpanda-migration-build.yml
- src/go/cluster-to-redpanda-migration/.goreleaser.yaml
Added:
- goreleaser file
- github workflow for migration-cli 
* none
> Redpanda-Operator: migration-cli goreleaser and workflow

- src/go/cluster-to-redpanda-migration/pkg/migration/configurations.go
Fixes #12535 back-port failure
* none
> Vbotbuildovich/backport 12465 v23.2.x 892

- src/v/cluster/security_manager.cc
- src/v/redpanda/admin_server.cc
- src/v/security/credential_store.h
Currently all users of the store may want to filter out principals that are of type ephemeral_user.
In order to prevent bugs such as serializing ephemeral users to disk, require a predicate when iterating the store.
Fixes #11786 
The backports aren't required as this is not a bug fix, but will make future refactoring easier.
* none
> security/credential_store: Make iteration more explicit

- tests/rptest/tests/node_pool_migration_test.py
Added simple test validating if after replacing all the nodes in the cluster partitions are evenly balanced. 
- none
> tests: added test validating replacement of all nodes in the cluster

- src/v/cluster/tx_gateway_frontend.cc
- tests/rptest/tests/transaction_kafka_api_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12130
Fixes #12448
> [v23.1.x] transactions: fix ListTransactions to return open transactions

- src/go/rpk/pkg/cli/group/describe.go
- tests/rptest/clients/rpk.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12499
Fixes: https://github.com/redpanda-data/redpanda/issues/12561,
> [v23.2.x] rpk group: total describe lag

- tests/rptest/services/redpanda.py
Cloud clouster deployment supports cloud types (fmc, byoc) and
also there is region and provider passed as well. Keys from
globals.json are: 'cloud_cluster_region', 'cloud_provider'
and 'cloud_cluster_type'
* none
> test/service: Support params for cloud cluster in RedpanadaCloud

- src/v/cloud_storage/tests/cloud_storage_e2e_test.cc
- src/v/cloud_storage/tests/delete_records_e2e_test.cc
If the eviction truncation loop truncates up to the max collectible offset but knows it has more to truncate, it will wait for 5s. Some tests wait for 3s and expect to be truncated down to one segment. This patch bumps these timeouts.
Alternatively, we could reduce the sleep with the expectation that max collectible offset will progress quickly. This isn't always the case (e.g. slow uploads, open transactions, etc).
Fixes https://github.com/redpanda-data/redpanda/issues/12509
* none
> tests: bump timeout for waiting on truncation

- src/v/storage/segment_set.cc
- tests/rptest/tests/index_recovery_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/10119
Fixes https://github.com/redpanda-data/redpanda/issues/12064
> [v23.1.x] s/segment_set: recover base_index of last_clean_segment

- src/v/cluster/health_monitor_backend.cc
- src/v/cluster/health_monitor_backend.h
- src/v/cluster/health_monitor_frontend.cc
- src/v/cluster/health_monitor_frontend.h
- src/v/kafka/CMakeLists.txt
- src/v/kafka/server/tests/CMakeLists.txt
- src/v/kafka/server/tests/usage_manager_test.cc
- src/v/kafka/server/usage_aggregator.cc
- src/v/kafka/server/usage_aggregator.h
- src/v/kafka/server/usage_manager.cc
- src/v/kafka/server/usage_manager.h
- src/v/redpanda/application.cc
- tests/rptest/tests/usage_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12067
Fixes: https://github.com/redpanda-data/redpanda/issues/12588,
> [v23.2.x] Align usage metrics to the configured interval

- src/v/cluster/health_monitor_backend.cc
- src/v/cluster/health_monitor_backend.h
- src/v/cluster/health_monitor_frontend.cc
- src/v/cluster/health_monitor_frontend.h
- src/v/kafka/CMakeLists.txt
- src/v/kafka/server/tests/CMakeLists.txt
- src/v/kafka/server/tests/usage_manager_test.cc
- src/v/kafka/server/usage_aggregator.cc
- src/v/kafka/server/usage_aggregator.h
- src/v/kafka/server/usage_manager.cc
- src/v/kafka/server/usage_manager.h
- src/v/redpanda/application.cc
- src/v/storage/tests/kvstore_fixture.h
- src/v/storage/tests/kvstore_test.cc
- tests/rptest/tests/usage_test.py
> [v23.1.x] Align usage metrics to the configured interval

- .github/workflows/redpanda-migration-build.yml
- src/go/cluster-to-redpanda-migration/.goreleaser.yaml
Backport of PR https://github.com/redpanda-data/redpanda/pull/12532
> [v23.2.x] Redpanda-Operator: migration-cli goreleaser and workflow

- src/go/k8s/apis/redpanda/v1alpha1/redpanda_types.go
- src/go/k8s/config/crd/bases/cluster.redpanda.com_redpandas.yaml
- src/go/k8s/controllers/redpanda/redpanda_controller_test.go
Official unreleased RedpandaSpec custom resource had redundant HelmRepositoryName property.
* none
> k8s: Remove duplicated property HelmRepositoryName

- src/go/k8s/tests/e2e/decommission/07-clean.yaml
- src/go/k8s/tests/e2e/managed-decommission/02-assert.yaml
- src/go/k8s/tests/e2e/managed-decommission/02-probe.yaml
- src/go/k8s/tests/e2e/managed-decommission/03-clean.yaml
Backport of PR https://github.com/redpanda-data/redpanda/pull/12601
> [v23.2.x] K8S: Fix decommission E2E tests

- src/go/k8s/pkg/resources/statefulset_scale.go
> k8s: Remove redundant check

- src/v/cloud_storage/partition_probe.cc
To enable the usage of internal metrics on clusters with large partition counts(100k+) a few new aggregations need to be introduced. This should hopefully allow us to reduce the number metrics by enough to allow for reasonable scraping intervals.
This PR adds aggregation to the top two contributors for the number of metrics. Reducing the number of metrics each generate from 19,019 to 1,107.
Partially fixes: #12563 
* Aggregate cloud_storage histograms by partition when the `aggregate_metrics cluster` property is set to true.
> Aggregate cloud_storage histograms by partition

- src/v/cloud_storage/remote_partition.cc
Preemptive backport of https://github.com/redpanda-data/redpanda/pull/12621
Though we were previously syncing the manifest before proceeding to read, there is room for a spillover to happen after syncing before returning to the fetch fiber.
(cherry picked from commit 2591e58e1ea6452c5f916ec397c86959e8946088)
* Fixes a race between remote storage spillover that could result in fewer Kafka records being returned to consumers.
> [v23.2.x] cloud_storage: retry cursor sync when racing with spillover

- src/v/cloud_storage/partition_probe.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12613
Fixes: https://github.com/redpanda-data/redpanda/issues/12618,
> [v23.2.x] Aggregate cloud_storage histograms by partition

- src/v/cluster/security_manager.cc
- src/v/redpanda/admin_server.cc
- src/v/security/credential_store.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/12502
Fixes: https://github.com/redpanda-data/redpanda/issues/12542,
> [v23.2.x] security/credential_store: Make iteration more explicit

- tests/rptest/tests/e2e_shadow_indexing_test.py
This test was only wiping one node and then running recovery. The original intent was to wipe all nodes.
* none
> ducktape: wipe all nodes in recovery tests

- tests/rptest/tests/consumer_group_recovery_tool_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12317
Fixes: https://github.com/redpanda-data/redpanda/issues/12639,
> [v23.1.x] tests/cg-recovery: retry list groups

- src/v/cluster/tx_gateway_frontend.cc
- src/v/cluster/tx_gateway_frontend.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/12551
Fixes: https://github.com/redpanda-data/redpanda/issues/12634,
> [v23.2.x] Fix segmentation fault in `tx_gateway_frontend::expire_old_txs`

- src/v/redpanda/admin_server.cc
- tests/rptest/clients/rpk.py
- tests/rptest/tests/maintenance_test.py
Previously when node health report was not available its maintenance
information wasn't set at all. This way a node wasn't reported as
draining when it was unavailable. Fixed this by always relaying on the
information available in `cluster::members_table` instead of waiting for
health report. The members table is a source of truth about the
nodes maintenance mode.
Fixes: #12548 
- fixes reporting maintenance mode status for nodes which are offline
> Fixed incorrectly reported maintenance mode status

- src/v/cloud_storage/cache_service.cc
Adds error logging when saving tracker state. An ignored exception here results in a seastar warning.
FIXES https://github.com/redpanda-data/redpanda/issues/9746
* none
> cloud_storage: Log exception when saving tracker

- src/v/cluster/archival_metadata_stm.cc
- src/v/cluster/archival_metadata_stm.h
- src/v/cluster/cluster_utils.cc
- src/v/cluster/cluster_utils.h
- src/v/cluster/config_manager.cc
- src/v/cluster/controller_backend.cc
- src/v/cluster/controller_backend.h
- src/v/cluster/id_allocator_stm.cc
- src/v/cluster/id_allocator_stm.h
- src/v/cluster/members_manager.cc
- src/v/cluster/members_table.h
- src/v/cluster/partition_balancer_state.cc
- src/v/cluster/rm_stm.cc
- src/v/cluster/rm_stm.h
- src/v/cluster/tests/cluster_utils_tests.cc
- src/v/cluster/tm_stm.cc
- src/v/cluster/tm_stm.h
- src/v/raft/consensus.cc
- src/v/raft/consensus.h
- src/v/raft/state_machine.cc
- src/v/raft/state_machine.h
- src/v/random/CMakeLists.txt
- src/v/redpanda/admin/api-doc/partition.json
- src/v/redpanda/admin_server.cc
- src/v/redpanda/admin_server.h
- tests/rptest/services/admin.py
- tests/rptest/services/admin_ops_fuzzer.py
- tests/rptest/tests/controller_availability_test.py
- tests/rptest/tests/nodes_decommissioning_test.py
- tests/rptest/utils/node_operations.py
Backport of PR: 
- https://github.com/redpanda-data/redpanda/pull/10325
- https://github.com/redpanda-data/redpanda/pull/9414
- https://github.com/redpanda-data/redpanda/pull/9380
- https://github.com/redpanda-data/redpanda/pull/8705
- https://github.com/redpanda-data/redpanda/pull/7201
- https://github.com/redpanda-data/redpanda/pull/11905
- https://github.com/redpanda-data/redpanda/pull/11840
- https://github.com/redpanda-data/redpanda/pull/11970
Fixes: #10470
Fixes: #10722
Fixes: #10723
Fixes: #11973
Fixes: #11978
Fixes: #11982
- none
> [v22.3.x] Backports

- src/v/pandaproxy/error.cc
- src/v/pandaproxy/error.h
- src/v/pandaproxy/schema_registry/error.cc
- src/v/pandaproxy/schema_registry/error.h
- src/v/pandaproxy/schema_registry/errors.h
- src/v/pandaproxy/schema_registry/store.h
- src/v/pandaproxy/schema_registry/test/store.cc
- tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12656
Fixes: https://github.com/redpanda-data/redpanda/issues/12693,
> [v23.1.x] schema_registry: Add error compatibility_not_found

- src/v/pandaproxy/error.cc
- src/v/pandaproxy/error.h
- src/v/pandaproxy/schema_registry/error.cc
- src/v/pandaproxy/schema_registry/error.h
- src/v/pandaproxy/schema_registry/errors.h
- src/v/pandaproxy/schema_registry/store.h
- src/v/pandaproxy/schema_registry/test/store.cc
- tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12656
Fixes: https://github.com/redpanda-data/redpanda/issues/12695,
> [v23.2.x] schema_registry: Add error compatibility_not_found

- src/v/pandaproxy/error.cc
- src/v/pandaproxy/error.h
- src/v/pandaproxy/schema_registry/error.cc
- src/v/pandaproxy/schema_registry/error.h
- src/v/pandaproxy/schema_registry/errors.h
- src/v/pandaproxy/schema_registry/store.h
- src/v/pandaproxy/schema_registry/test/store.cc
- tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12656
Fixes: https://github.com/redpanda-data/redpanda/issues/12696,
> [v22.3.x] schema_registry: Add error compatibility_not_found

- src/v/finjector/CMakeLists.txt
- src/v/finjector/stress_fiber.cc
- src/v/finjector/stress_fiber.h
- src/v/redpanda/CMakeLists.txt
- src/v/redpanda/admin/api-doc/debug.json
- src/v/redpanda/admin_server.cc
- src/v/redpanda/admin_server.h
- src/v/redpanda/application.cc
- src/v/redpanda/application.h
- src/v/storage/disk_log_appender.cc
- src/v/storage/disk_log_appender.h
- src/v/storage/disk_log_impl.cc
- src/v/storage/disk_log_impl.h
- src/v/storage/tests/CMakeLists.txt
- src/v/storage/tests/storage_e2e_fixture_test.cc
Backport of https://github.com/redpanda-data/redpanda/pull/12565 and pulls in stress fibers to test.
* Avoids a race between appends and application of segment.ms that could result in a crash.
> [v23.2.x] storage: fix race between segment.ms and appends

- src/go/k8s/kuttl-v2-test.yaml
V2 operator needed crds, we were using operator helm chart to install but these quickly are out of date.  Here we use local version to run tests. 
* none
> Redpanda-Operator: use local crds when testing

- src/go/k8s/controllers/redpanda/cluster_controller.go
Move pod labeling out setPodNodeIDAnnotation and into its own function. This fixes a bug where if the pod annotation was set but the label wasn't, the check to see that we didn't need to do any changes would be false, allowing the next step to assume that the broker id in the annotation was no longer valid, triggering a decommission.
By breaking this up into discreet functions, we can assure that the annotation and label are each set correctly according to their own logic.
fixes #12734
* split pod annotation and label functions to prevent unexpected decommissioning of brokers
> fix pod label causing decommission

- src/go/k8s/kuttl-v2-test.yaml
> k8s: use local crds when testing

- src/go/k8s/controllers/redpanda/cluster_controller.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/12735
Fixes: https://github.com/redpanda-data/redpanda/issues/12738,
> [v23.2.x] fix pod label causing decommission

- src/v/cloud_storage/CMakeLists.txt
- src/v/cloud_storage/segment_meta_cstore.cc
- src/v/config/configuration.cc
- src/v/config/configuration.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/12709
> [v23.2.x] Hotfix/cstore escape hatch

- tests/rptest/tests/controller_availability_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12343
Fixes: https://github.com/redpanda-data/redpanda/issues/12555,
> [v23.2.x] tests: sort nodes before stopping them

- .github/workflows/lint.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/12485
> [v23.2.x] dockerize lint clang-format

- tests/rptest/clients/rpk.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12564
Fixes: https://github.com/redpanda-data/redpanda/issues/12741,
> [v23.2.x] test: check stderr for coordinator error messages

- src/v/cluster/cluster_utils.cc
- src/v/cluster/cluster_utils.h
- src/v/cluster/persisted_stm.h
- src/v/cluster/types.h
- src/v/redpanda/admin/api-doc/debug.json
- src/v/redpanda/admin_server.cc
- src/v/storage/types.h
- tests/rptest/tests/partition_state_api_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12454
> [v23.2.x] admin/observability/debugging: add stm information to partition debug endpoint

- src/go/rpk/pkg/adminapi/admin.go
- src/go/rpk/pkg/adminapi/api_config.go
- src/go/rpk/pkg/cli/generate/app.go
- src/go/rpk/pkg/cli/group/offset_delete.go
- src/go/rpk/pkg/cloudapi/api_installpack.go
- src/go/rpk/pkg/httpapi/httpapi.go
- src/go/rpk/pkg/net/hostport.go
- src/go/rpk/pkg/system/grub_test.go
- src/go/rpk/pkg/tuners/aggregated_tunable_test.go
- src/go/rpk/pkg/tuners/disk_tuner.go
- src/go/rpk/pkg/tuners/executors/commands/write_sized_file.go
- src/go/rpk/pkg/tuners/float_checker_test.go
- src/go/rpk/pkg/tuners/network/nic_test.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/12487
> [v23.2.x] rpk: fix flag name in help text of `rpk generate app`

- src/go/k8s/controllers/redpanda/cluster_controller.go
- src/go/k8s/controllers/redpanda/cluster_controller_configuration_drift.go
- src/go/k8s/controllers/redpanda/console_controller.go
- src/go/k8s/controllers/redpanda/metric_controller.go
- src/go/k8s/controllers/redpanda/redpanda_controller.go
> Context per reconciler

- tests/rptest/tests/controller_availability_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12343
Fixes: https://github.com/redpanda-data/redpanda/issues/12553,
> [v23.1.x] tests: sort nodes before stopping them

- src/v/net/conn_quota.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12756
> [v23.1.x] co_await mutex hold in conn_quota

- tests/rptest/services/admin_ops_fuzzer.py
- tests/rptest/services/redpanda.py
- tests/rptest/tests/controller_availability_test.py
Fixed incorrect import in controller availability test
- none
> [v22.3.x] fixed incorrectly backported `controller_availability_test`

- src/v/kafka/server/usage_aggregator.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12755
Fixes: https://github.com/redpanda-data/redpanda/issues/12765,
> [v23.1.x] Fix misappropriate use of mutex::get_units in usage based billing

- src/v/cluster/rm_stm.cc
When a request hits a former leader which still thinks it's the leader there is a change that a valid request results in OOOSN since the broker validates new request against the stale data. Fixing the problem by double checking that a node is indeed the leader.
The perf impact of `linearizable_barrier` doesn't matter because OOOSN is already an exceptional situation leading to the session termination.
Fixes https://github.com/redpanda-data/redpanda/issues/12712
* none
> rm_stm: return sequence_out_of_order only when a client misbehaves

- cmake/main.cmake
- src/CMakeLists.txt
- src/v/hashing/CMakeLists.txt
- src/v/json/CMakeLists.txt
- src/v/reflection/test/CMakeLists.txt
Minor build system updates in preparation of open-source build revamp.
* none
> [build]: open-source build dependency updates

- src/v/net/conn_quota.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12756
> [v23.2.x] co_await mutex hold in conn_quota

- src/v/kafka/server/usage_aggregator.cc
- src/v/kafka/server/usage_aggregator.h
- tests/rptest/tests/usage_test.py
- tests/rptest/utils/functional.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12780
> [v23.1.x] Fix observed window drift in usage based billing

- src/v/cluster/partition.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12757
> [v23.2.x] Await acquiring the manifest lock

- tests/rptest/tests/node_pool_migration_test.py
During node pool migration test multiple nodes are decommissioned simultaneously. This lead to the situation in which some of those decommissioned and already removed nodes may no longer receive metadata updates. This caused the test to fail as it was querying those nodes for decommission status. Fixed the problem by not querying decommissioned node for decommission status to prevent querying stale cluster metadata.
Fixes: #12827
- none
> Do not query decommissioned node about draining status in `NodePoolMigrationTest`

- cmake/oss.cmake.in
- src/v/cluster/rm_stm.cc
- src/v/cluster/self_test/diskcheck.cc
- src/v/net/connection.cc
- src/v/pandaproxy/schema_registry/avro.cc
- src/v/redpanda/admin_server.cc
- src/v/resource_mgmt/io_priority.h
- src/v/storage/segment_appender.cc
- src/v/storage/tests/backlog_controller_test.cc
Related PRs:
* https://github.com/redpanda-data/seastar/pull/57
* https://github.com/redpanda-data/vtools/pull/2003
* none
> Upgrade seastar v23.3.x

- src/v/pandaproxy/api/api-doc/schema_registry.json
- src/v/pandaproxy/api/api-doc/schema_registry_header.json
- src/v/pandaproxy/schema_registry/service.cc
- tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12844
Fixes: https://github.com/redpanda-data/redpanda/issues/12855,
> [v22.3.x] schema_registry: Alias referencedby by referencedBy 

- src/v/pandaproxy/api/api-doc/schema_registry.json
- src/v/pandaproxy/api/api-doc/schema_registry_header.json
- src/v/pandaproxy/schema_registry/service.cc
- tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12844
Fixes: https://github.com/redpanda-data/redpanda/issues/12851,
> [v23.1.x] schema_registry: Alias referencedby by referencedBy 

- src/v/pandaproxy/api/api-doc/schema_registry.json
- src/v/pandaproxy/api/api-doc/schema_registry_header.json
- src/v/pandaproxy/schema_registry/service.cc
- tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12844
Fixes: https://github.com/redpanda-data/redpanda/issues/12853,
> [v23.2.x] schema_registry: Alias referencedby by referencedBy 

- src/go/rpk/pkg/api/admin/api_cloud_storage.go
- src/go/rpk/pkg/cli/cmd/cluster/storage/recovery/start.go
- src/go/rpk/pkg/cli/cmd/cluster/storage/storage.go
- src/v/cloud_storage/recovery_request.cc
- src/v/cloud_storage/tests/remote_test.cc
- src/v/cloud_storage/tests/s3_imposter.cc
- src/v/cloud_storage/tests/s3_imposter.h
- src/v/cloud_storage/tests/topic_recovery_service_test.cc
- src/v/cloud_storage/topic_recovery_service.cc
- tests/rptest/clients/rpk.py
- tests/rptest/tests/e2e_shadow_indexing_test.py
- tests/rptest/tests/shadow_indexing_admin_api_test.py
Backport of https://github.com/redpanda-data/redpanda/pull/10539
Pulls in https://github.com/redpanda-data/redpanda/pull/10223
Fixes https://github.com/redpanda-data/redpanda/issues/10635
* Automated topic recovery will be faster when operating on buckets with a large number of objects.
> [v23.1.x] topic_recovery: avoid listing with no prefix

- src/go/rpk/pkg/cli/redpanda/admin/brokers/decommission-status.go
`rpk redpanda admin brokers decommission-status <id>` now supports the -H option that prints partition size in a human-readable format. Example output below.
```
DECOMMISSION PROGRESS
=====================
NAMESPACE-TOPIC  PARTITION  MOVING-TO  COMPLETION-%  PARTITION-SIZE
kafka/test       0          2          66            964.4MB
kafka/test       1          2          72            598.6MB
```
Fixes https://github.com/redpanda-data/redpanda/issues/12881
* rpk: decommission-status supports -H option to show partition size in a human-readable format
> rpk: decommission-status supports human-friendly outputs

- src/v/kafka/client/fetch_session.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12923
Fixes: https://github.com/redpanda-data/redpanda/issues/12926,
> [v23.1.x] client/fetch_session: fix formatting string

- cmake/oss.cmake.in
> [v23.2.x] 3rdparty: Update seastar for semaphore_units fix

- cmake/oss.cmake.in
> [v23.1.x] 3rdparty: Update seastar for semaphore_units fix

- cmake/oss.cmake.in
> [v22.3.x] 3rdparty: Update seastar for semaphore_units fix

- src/v/cloud_storage/async_manifest_view.cc
- src/v/cloud_storage/remote_partition.cc
- src/v/cloud_storage/tests/async_manifest_view_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12902
> [v23.2.x] cloud_storage: Fix timequery

- tests/rptest/clients/kubectl.py
- tests/rptest/services/redpanda.py
> rptest: Update Kubectl client to support GCP

- src/v/pandaproxy/schema_registry/sharded_store.cc
- src/v/pandaproxy/server.cc
- tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12871
> [v22.3.x] schema_registry: Check compatibility iff the schema is a new version

- src/v/pandaproxy/schema_registry/sharded_store.cc
- src/v/pandaproxy/server.cc
- tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12871
> [v23.1.x] schema_registry: Check compatibility iff the schema is a new version

- tests/rptest/services/provider_clients/__init__.py
- tests/rptest/services/provider_clients/ec2_client.py
- tests/rptest/services/provider_clients/gcp_client.py
- tests/rptest/services/redpanda.py
- tests/rptest/services/redpanda_cloud.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12918 
Fixes #12958
> [v23.2.x] retest: Implement VPC peering for Cloud Cluster with private network

- src/go/rpk/go.mod
- src/go/rpk/pkg/cli/container/common/client.go
- src/go/rpk/pkg/cli/container/common/context.go
- src/go/rpk/pkg/cli/generate/app.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/12863
Fixes: https://github.com/redpanda-data/redpanda/issues/12968,
> [v23.2.x] rpk: load docker host from context in rpk container

- tests/rptest/services/redpanda_cloud.py
> rptest: Cloud tiers handling according to provider

- src/v/kafka/server/group_manager.cc
- src/v/kafka/server/group_manager.h
- tests/rptest/clients/rpk.py
- tests/rptest/tests/consumer_offsets_consistency_test.py
Previously when linearizable barrier returned an error it might lead to
situation in which a barrier was simply skipped. This in the end might
lead to a situation in which recovered consumer group state was
incomplete.
- fixed very rare error when consumer group recovery was incomplete
> Fixed handling errors when injecting barrier during consumer groups recovery

- tests/rptest/services/admin_ops_fuzzer.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12146
Fixes: https://github.com/redpanda-data/redpanda/issues/12886,
> [v23.2.x] tests: do not issue describe command for empty topic object

- src/v/cluster/partition_balancer_backend.cc
- src/v/cluster/topic_table.cc
- src/v/cluster/topic_table.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/12910
> [v23.2.x] Retry balancer tick when topic_table was modified while iterating

- src/v/kafka/client/fetch_session.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12923
Fixes: https://github.com/redpanda-data/redpanda/issues/12924,
> [v23.2.x] client/fetch_session: fix formatting string

- src/v/kafka/client/fetch_session.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12923
Fixes: https://github.com/redpanda-data/redpanda/issues/12925,
> [v22.3.x] client/fetch_session: fix formatting string

- src/v/storage/segment_appender.cc
- src/v/storage/segment_appender.h
- src/v/storage/segment_appender_chunk.h
- src/v/storage/tests/log_segment_appender_test.cc
- tests/rptest/tests/scaling_up_test.py
> Improved segment appender write merging

- src/v/cloud_storage/materialized_resources.cc
- src/v/cloud_storage/materialized_resources.h
- src/v/cloud_storage/probe.cc
- src/v/cloud_storage/remote_partition.cc
- src/v/cloud_storage/remote_partition.h
- src/v/cloud_storage/segment_state.cc
- src/v/cloud_storage/segment_state.h
- src/v/cloud_storage/tests/cloud_storage_fixture.h
- src/v/cloud_storage/types.h
- tests/rptest/scale_tests/tiered_storage_reader_stress_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12777
Fixes: https://github.com/redpanda-data/redpanda/issues/12932,
> [v23.2.x] cloud_storage: enforce cloud read path limits strictly

- src/v/kafka/server/group_manager.cc
- src/v/kafka/server/group_manager.h
- tests/rptest/clients/rpk.py
- tests/rptest/tests/consumer_offsets_consistency_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12931
> [v23.2.x] Fixed handling errors when injecting barrier during consumer groups recovery

- src/v/kafka/server/group_manager.cc
- src/v/kafka/server/group_manager.h
- tests/rptest/clients/rpk.py
- tests/rptest/tests/consumer_offsets_consistency_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12931
> [v23.1.x] Fixed handling errors when injecting barrier during consumer groups recovery

- src/v/cloud_storage/segment_meta_cstore.cc
- src/v/cloud_storage/segment_meta_cstore.h
- src/v/cloud_storage/tests/segment_meta_cstore_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12842
Fixes: https://github.com/redpanda-data/redpanda/issues/12942,
> [v23.2.x] Fix/cstore hints handling

- cmake/dependencies.cmake
Do not use commit revisions in OSS build dependency specification
- none
> cmake: updated seastar version for oss build

- tests/rptest/services/redpanda_installer.py
We noticed one of the CI runs fetched 0 releases and wrote an empty cache file. We suspect this was because of a transient github issue. Subsequent upgrade tests failed because they are not able to find desired previous release in cache.
Rather than waiting for next round of tests to fail, this commit adds a simple check that avoids writing an empty file essentially failing fast. Next test should repopulate the file again by fetching the release metadata from github.
* none
> ducktape: avoid writing empty release cache file

- tests/rptest/remote_scripts/compute_storage.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13015
> [v23.2.x] Eagerly list all files in compute_storage.py

- tests/rptest/scale_tests/high_throughput_test.py
Rebase of https://github.com/redpanda-data/redpanda/pull/9535 against dev
* none
> Move over in-progress work for high throughput cloud tiers

- cmake/dependencies.cmake
in debug mode seastar uses -Werror and this makes the build fail for reasons external to redpanda
this pr set -Wno-error to disable -Werror inside seastar
* none
> cmake/dependencies: Seastar_CXX_FLAGS -Wno-error

- README.md
References: https://redpandadata.slack.com/archives/C02LZGSS66M/p1693238424654829
> Update README.md to add GA tracking pixel

- tests/rptest/clients/kubectl.py
- tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12944
> [v23.2.x] rptest: Update Kubectl client to support GCP

- tests/rptest/services/redpanda_cloud.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12939
> [v23.2.x] rptest: Cloud tiers handling according to provider

- src/go/k8s/config/rbac/bases/operator/role.yaml
- src/go/k8s/controllers/redpanda/redpanda_controller.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/13069
> [v23.2.x] k8s: allow operator to create servicemonitors

- src/go/k8s/pkg/resources/statefulset_update.go
* fix a bug in the operator's Cluster controller where scaling a cluster would cause the pods to be rolled
> operator: fix bug that rolls pods that have no changes

- tests/rptest/tests/timequery_test.py
Fix racecondition in the timequery_test.py. The PR fixes the problem in the test code, not in Redpanda.
* none
> rptest: Fix timequery CI failure

- src/go/k8s/apis/redpanda/v1alpha1/redpanda_clusterspec_types.go
- src/go/k8s/config/crd/bases/cluster.redpanda.com_redpandas.yaml
Updating CRDs based on changes made recently to helm chart.
* none
> k8s: update api with latest changes in helm chart

- src/v/cluster/config_manager.cc
- tests/rptest/services/redpanda.py
- tests/rptest/services/rolling_restarter.py
- tests/rptest/tests/nodes_decommissioning_test.py
- tests/rptest/tests/redpanda_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13048
> [v23.2.x] Fixed configuration status and brokers list discrepancy 

- src/go/rpk/pkg/cli/cloud/byoc/install.go
- src/go/rpk/pkg/config/params.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/12999
> [v23.2.x] rpk: minor fixes, -X help text and byoc binary lookup path

- src/go/k8s/apis/redpanda/v1alpha1/redpanda_clusterspec_types.go
- src/go/k8s/config/crd/bases/cluster.redpanda.com_redpandas.yaml
Backport of PR https://github.com/redpanda-data/redpanda/pull/13071
> [v23.2.x] k8s: update api with latest changes in helm chart

- src/go/k8s/pkg/resources/statefulset_update.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/13086
> [v23.2.x] operator: fix bug that rolls pods that have no changes

- tests/docker/Dockerfile
- tests/docker/ducktape-deps/byoc-mock
Backport of PR https://github.com/redpanda-data/redpanda/pull/12808
> [v23.2.x] tests: fix path for rpk byoc-mock

- tools/rp_storage_tool/resources/test/cluster_manifest.json
- tools/rp_storage_tool/src/bucket_reader.rs
- tools/rp_storage_tool/src/remote_types.rs
Rebases https://github.com/jcsp/segment_toy/pull/6 in this repo, addressing comments from John.
This adds a couple tricks to the bucket scan around cluster metadata, to be used to begin validating the behavior of metadata uploads:
adds handling for controller snapshots and cluster metadata manifests
checks that the highest-IDed manifest points at a controller snapshot that exists (if any)
* none
> rp_storage_tool: update bucket scan to handle cluster metadata

- src/go/k8s/Dockerfile
- src/go/k8s/Makefile
Improve build-time for osx machines and testing. This should not affect our build process. 
* none
> k8s: makefile change to make building on osx faster

- src/v/cluster/tm_stm.cc
- src/v/cluster/tm_stm.h
- src/v/cluster/tm_stm_cache.cc
- src/v/cluster/tm_stm_cache.h
- src/v/cluster/tx_gateway_frontend.cc
- src/v/cluster/tx_gateway_frontend.h
- src/v/config/configuration.cc
- src/v/config/configuration.h
- src/v/redpanda/application.cc
- src/v/utils/rwlock.h
- src/v/utils/tests/rwlock_test.cc
- tests/rptest/tests/tx_overflow_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12477
Fixes: https://github.com/redpanda-data/redpanda/issues/13122,
> [v23.2.x] Add thrashing of old txn sessions to prevent OOM

- src/go/k8s/Dockerfile
- src/go/k8s/Makefile
Backport of PR https://github.com/redpanda-data/redpanda/pull/13166
> [v23.2.x] k8s: makefile change to make building on osx faster

- src/v/cloud_storage/remote_partition.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13126
> [v23.2.x] cloud_storage: Let partition reader work across manifest boundaries

- .github/workflows/cloud-installpack-bk-trigger.yml
This PR adds a workflow to trigger some automated jobs for cloud when new releases are published.
* none
> Workflow to trigger cloud CI on releases

- src/go/rpk/pkg/cli/redpanda/admin/brokers/decommission-status.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/12882
Fixes: https://github.com/redpanda-data/redpanda/issues/13147,
> [v23.2.x] rpk: decommission-status supports human-friendly outputs

- src/v/cloud_storage/cache_service.cc
- src/v/cloud_storage/tests/cache_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13158
> [v23.2.x] cloud_storage: Extend fast trim cleanup to new segment name

- tests/rptest/tests/workload_upgrade_runner_test.py
disable the test to not stall ci, while working on the fix.
Related to #13180 
* none
> tests/workload_license: ok_to_fail

- tests/rptest/tests/e2e_shadow_indexing_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12935
Fixes: https://github.com/redpanda-data/redpanda/issues/13243,
> [v23.2.x] ducktape: Wait for spillover to stabilize before collection

- tests/rptest/scale_tests/many_partitions_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13206
> [v23.2.x] ducktape: ManyPartitionTest - Explicitly set background traffic bandwidth

- tests/rptest/scale_tests/many_partitions_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13206
> [v23.1.x] ducktape: ManyPartitionTest - Explicitly set background traffic bandwidth

- src/v/raft/consensus.cc
- src/v/raft/heartbeat_manager.cc
- src/v/raft/types.h
- tests/rptest/tests/lw_heartbeats_test.py
Previously the `last_sent_seq` was post incremented which made it a next
sequence to be sent. Change the incrementation logic to make it actually
last sent follower request sequence.
- none
> Fixed incrementing `last_sent_follower_seq`

- src/v/cloud_storage/segment_chunk_api.cc
When a file close operation fails, make sure that the exception is moved out of the future so that we do not get ignored exception warnings.
Additionally use the right API to make sure that gate closed exceptions during chunk file trimming are ignored.
* none
> cloud_storage: Handle exceptions during chunk trim

- src/v/cloud_storage/segment_chunk_api.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13203
> [v23.2.x] cloud_storage: Handle exceptions during chunk trim

- src/v/cluster/tm_stm.cc
- src/v/cluster/tm_stm.h
- src/v/cluster/tm_stm_cache.cc
- src/v/cluster/tm_stm_cache.h
- src/v/cluster/tx_gateway_frontend.cc
- src/v/cluster/tx_gateway_frontend.h
- src/v/config/configuration.cc
- src/v/config/configuration.h
- src/v/redpanda/application.cc
- src/v/utils/rwlock.h
- src/v/utils/tests/rwlock_test.cc
- tests/rptest/tests/tx_overflow_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12477
Fixes https://github.com/redpanda-data/redpanda/issues/13121
> [v23.1.x] Add thrashing of old txn sessions to prevent OOM

- src/v/net/conn_quota.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12756
> [v22.3.x] co_await mutex hold in conn_quota

- src/v/raft/replicate_entries_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13300
Fixes: https://github.com/redpanda-data/redpanda/issues/13310,
> [v23.1.x] Handle gate closing exceptions in replicate_entries_stm

- .github/workflows/lint.yml
- tests/rptest/scale_tests/cloud_storage_compaction_test.py
- tests/rptest/services/kaf_consumer.py
- tests/rptest/services/kcat_consumer.py
- tests/rptest/services/redpanda.py
- tests/rptest/services/redpanda_installer.py
- tests/rptest/tests/cluster_features_test.py
related to https://github.com/redpanda-data/vtools/pull/1954
* none
> tests/py: apply format with yapf 0.40.1

- src/go/cluster-to-redpanda-migration/go.mod
- src/go/cluster-to-redpanda-migration/go.sum
- src/go/k8s/.golangci.yml
- src/go/k8s/apis/vectorized/v1alpha1/cluster_webhook.go
- src/go/k8s/go.mod
- src/go/k8s/go.sum
- src/go/k8s/pkg/resources/certmanager/pki_test.go
- src/go/k8s/pkg/resources/configmap_test.go
- src/go/k8s/pkg/resources/statefulset_test.go
- src/go/k8s/webhooks/redpanda/validate_enterprise_test.go
https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMCYPHARFILEPATHSECUREJOIN-5889602
based on the PRs and issues related to this report, it isn't relevant for how we're using fluxcd. No release notes or advisories are needed.
* none
> address snyk finding

- src/go/cluster-to-redpanda-migration/go.mod
- src/go/cluster-to-redpanda-migration/go.sum
- src/go/k8s/.golangci.yml
- src/go/k8s/apis/vectorized/v1alpha1/cluster_webhook.go
- src/go/k8s/go.mod
- src/go/k8s/go.sum
- src/go/k8s/pkg/resources/certmanager/pki_test.go
- src/go/k8s/pkg/resources/configmap_test.go
- src/go/k8s/pkg/resources/statefulset_test.go
- src/go/k8s/webhooks/redpanda/validate_enterprise_test.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/13354
> [v23.2.x] address snyk finding

- src/v/cluster/partition_balancer_backend.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13161
Fixes: https://github.com/redpanda-data/redpanda/issues/13172,
> [v23.2.x] Reshedule tick immediately when topic table was modified

- tests/docker/Dockerfile
Backport of PR https://github.com/redpanda-data/redpanda/pull/13383
> [v23.1.x] tests/docker: Change base image base to jammy

- src/go/k8s/Makefile
> k8s: Bump golangci-lint version

- src/v/cloud_storage/async_manifest_view.cc
Handle gate_closed_exception and other similar errors in the async_manifest_view.
Fixes #12819
* none
> cloud_storage: Fix exception handling in async_manifest_view

- .github/workflows/rpk-build.yml
manual backport of PR https://github.com/redpanda-data/redpanda/pull/13210
* none
> [v22.3.x] gha: run go test on PRs to release branches

- src/v/cloud_storage/async_manifest_view.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13384
Fixes: https://github.com/redpanda-data/redpanda/issues/13417,
> [v23.2.x] cloud_storage: Fix exception handling in async_manifest_view

- tests/rptest/tests/upgrade_test.py
disabling test_rollling_upgrade while we work on it
Releated to #13181 
* none
> tests/upgrade_test: test_rolling_upgrade ok_to_fail issue/13181

- tests/rptest/tests/topic_delete_test.py
`remote_partition::finlalize` may do a final manifest upload if the uploaded manifest is not at the latest insync offset. This may race with the removal of that manifest by the purger. Note that this can only happen if the grace timeout is set super low (this test had it at 5ms). Not an issue in the field, but let's bump the grace period to avoid races in the test.
Fixes #13235 
* none
> rptest: increase purge grace period in racy test

- tests/rptest/services/provider_clients/ec2_client.py
- tests/rptest/services/redpanda_cloud.py
> rptest: Fix route creation for private networks

- tests/rptest/redpanda_cloud_tests/high_throughput_test.py
> rptest: Update max connections test to support higher tiers

- tests/rptest/redpanda_cloud_tests/high_throughput_test.py
> rptest: Support configured tier in HTT tests

- tests/rptest/tests/topic_delete_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13470
Fixes: https://github.com/redpanda-data/redpanda/issues/13471,
> [v23.2.x] rptest: increase purge grace period in racy test

- src/v/config/configuration.cc
Related to https://github.com/redpanda-data/redpanda/issues/13447 and temporarily solves the segfault that is occurring in CI while we continue to investigate the underlying cause.
* none
> Change default value for `rpc_client_connections_per_peer`

- .github/workflows/rpk-build.yml
manual backport of PR https://github.com/redpanda-data/redpanda/pull/13210
* none
> [v23.1.x] gha: run go test on PRs to release branches

- src/go/k8s/tests/e2e/create-topic-given-issuer-with-client-auth/00-assert.yaml
- src/go/k8s/tests/e2e/create-topic-given-issuer-with-client-auth/00-create-cluster-issuer.yaml
- src/go/k8s/tests/e2e/create-topic-given-issuer-with-client-auth/01-assert.yaml
- src/go/k8s/tests/e2e/create-topic-given-issuer-with-client-auth/01-redpanda-cluster.yaml
- src/go/k8s/tests/e2e/create-topic-given-issuer-with-client-auth/05-clean.yaml
- src/go/k8s/tests/e2e/create-topic-given-issuer/05-clean.yaml
The ClusterIssuer and Issuer names where colliding with
`create-topic-given-issuer` test case. This commit changes only names.
In the logs for the operator we could see the following error
```
"error":"creating pki: kafka api certificates selfsigned check ClusterIssuer.cert-manager.io \"cluster-tls-root-issuer\" not found"
```
It was just unfortunate chain of events where `create-topic-given-issuer` was executed at the same time as `create-topic-given-issuer-with-client-auth` test case.
REF
https://buildkite.com/redpanda/redpanda/builds/37112
https://buildkite.com/redpanda/redpanda/builds/37133
* none
> Fix operator e2e flaky test

- src/go/k8s/tests/e2e/create-topic-given-issuer-with-client-auth/00-assert.yaml
- src/go/k8s/tests/e2e/create-topic-given-issuer-with-client-auth/00-create-cluster-issuer.yaml
- src/go/k8s/tests/e2e/create-topic-given-issuer-with-client-auth/01-assert.yaml
- src/go/k8s/tests/e2e/create-topic-given-issuer-with-client-auth/01-redpanda-cluster.yaml
- src/go/k8s/tests/e2e/create-topic-given-issuer-with-client-auth/05-clean.yaml
- src/go/k8s/tests/e2e/create-topic-given-issuer/05-clean.yaml
Backport of PR https://github.com/redpanda-data/redpanda/pull/13486
> [v23.2.x] Fix operator e2e flaky test

- .github/workflows/cloud-installpack-bk-trigger.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/13027
> [v23.2.x] Workflow to trigger cloud CI on releases

- src/v/cluster/id_allocator.cc
- src/v/cluster/id_allocator_frontend.cc
- src/v/cluster/id_allocator_frontend.h
- src/v/cluster/id_allocator_stm.h
- src/v/cluster/leader_router.h
- src/v/redpanda/application.cc
This will be useful for an upcoming change I have to target leaders of the offsets topic.
* none
> cluster: pull out to-ntp-leader dispatch from id_allocator_frontend

- src/v/cluster/cluster_utils.cc
- src/v/cluster/types.h
- src/v/raft/consensus.cc
- src/v/raft/recovery_stm.cc
- src/v/raft/recovery_stm.h
- src/v/raft/replicate_entries_stm.cc
- src/v/raft/types.cc
- src/v/raft/types.h
- src/v/redpanda/admin/api-doc/debug.json
- src/v/redpanda/admin_server.cc
Backporting: 
- https://github.com/redpanda-data/redpanda/pull/13495
Fixes: #13559
- none
> [v23.2.x] Backport of #13495

- src/go/cluster-to-redpanda-migration/go.mod
- src/go/cluster-to-redpanda-migration/go.sum
Backport of PR https://github.com/redpanda-data/redpanda/pull/13575
> [v23.2.x] cluster-to-redpanda-migration: decouple from operator

- src/v/cluster/partition.cc
removed repeated if block from partition.cc
* none
> cluster/partition: removed duplicated block

- src/go/rpk/pkg/cli/cluster/config/set.go
- src/v/storage/log_manager.cc
s/delete_retention_ms/log_retention_ms/g in a formatted output string
* none
> storage/log_manager: cleanup "delete_retention_ms"->"log_retention_ms"

- src/v/cluster/partition.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13568
> [v23.2.x] cluster/partition: removed duplicated block

- src/v/cloud_storage_clients/s3_client.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13585
> [v23.2.x] cloud_storage_clients/s3: handle HEAD slow downs

- tests/rptest/clients/rpk.py
- tests/rptest/tests/partition_balancer_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13587
> [v23.1.x] tests: increase rpk timeout in partition balancer maintenance test

- src/v/cluster/topics_frontend.cc
- src/v/cluster/topics_frontend.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/13645
Fixes: https://github.com/redpanda-data/redpanda/issues/13665,
> [v23.2.x] c/topics_frontend: create partition constraints on allocator shard

- src/v/kafka/server/handlers/fetch.cc
- tests/rptest/tests/follower_fetching_test.py
If a replica is in maintenance mode it should not be selected as a
candidate for the follower to fetch from.
Fixes: https://github.com/redpanda-data/core-internal/issues/753
- if a node is in maintenance mode it will not be used to serve fetch requests when follower fetching is enabled.
> Do not select replica in maintenance mode in replica selector

- src/go/rpk/pkg/api/admin/admin.go
> rpk: fix lint issue in v22.3.x

- src/v/cluster/partition.cc
- src/v/cluster/partition_probe.cc
- src/v/cluster/partition_probe.h
- src/v/cluster/topics_frontend.cc
- src/v/cluster/topics_frontend.h
- src/v/raft/consensus.cc
- src/v/raft/probe.h
- src/v/redpanda/admin_server.cc
- tests/rptest/clients/rpk.py
- tests/rptest/tests/maintenance_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12552
Backport of PR https://github.com/redpanda-data/redpanda/pull/13645
Backport of PR https://github.com/redpanda-data/redpanda/pull/13009
Fixes: https://github.com/redpanda-data/redpanda/issues/13667
Fixes: https://github.com/redpanda-data/redpanda/issues/12677
Fixes: https://github.com/redpanda-data/redpanda/issues/13054
> [v23.1.x] Backport of #12552 #13645 #13009

- src/v/kafka/server/group_manager.cc
- src/v/kafka/server/group_manager.h
- tests/rptest/clients/rpk.py
- tests/rptest/tests/consumer_offsets_consistency_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12931
> [v22.3.x] Backport of: #12931

- tests/rptest/tests/upgrade_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13538
> [v23.2.x] tests/upgrade_test: test_rolling_upgrade race fix

- src/v/kafka/server/handlers/fetch.cc
- tests/rptest/tests/follower_fetching_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13562
> [v23.2.x] Do not select replica in maintenance mode in replica selector

- src/go/k8s/controllers/redpanda/redpanda_controller.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/13681
> [v23.2.x] k8s: Redpanda-Operator - fix managed annotation response

- tests/rptest/redpanda_cloud_tests/high_throughput_test.py
> rptest: Support tiers 3-4 on max connections test

- tests/rptest/tests/partition_balancer_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13749
Fixes: https://github.com/redpanda-data/redpanda/issues/13765,
> [v23.1.x] ducky/partition_balancer_test: fix full_node_test

- tests/rptest/tests/partition_balancer_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13749
Fixes: https://github.com/redpanda-data/redpanda/issues/13763,
> [v22.3.x] ducky/partition_balancer_test: fix full_node_test

- tests/rptest/tests/partition_balancer_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13749
Fixes: https://github.com/redpanda-data/redpanda/issues/13766,
> [v23.2.x] ducky/partition_balancer_test: fix full_node_test

- src/v/cluster/tx_gateway_frontend.cc
I'm assuming we shouldn't be dropping this gate on the ground
immediately
* none
> cluster/tx: Fix missing gate hold

- src/go/rpk/pkg/cli/redpanda/admin/brokers/decommission-status.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/13704
> [v23.2.x] rpk: fix typo in decommission-status

- src/go/.goreleaser.yaml
> [v23.1.x] Consolidate goreleaser config and GHA workflows

- .github/workflows/rpk-build.yml
ref https://github.com/redpanda-data/devprod/issues/858
* none
> rpk: run go tests in gh actions

- tests/rptest/tests/cloud_storage_usage_test.py
some context around the failure 
Related to #13514 
* none
> tests/cloud_storage_usage_test: CloudStorageUsagetest add assert message

- tests/rptest/scale_tests/tiered_storage_cache_stress_test.py
"Internal Server Error" is a transient S3 error that can prevent the CDT stress test from passing even if the actual test worked correctly. This PR adds this error to allowed list.
Fixes https://github.com/redpanda-data/redpanda/issues/13696
* none
> rptest: Add transient S3 error to log allow list

- src/go/k8s/kind.yaml
- src/go/k8s/kuttl-v2-test.yaml
- src/go/k8s/tests/e2e-v2/decommission/03-delete-redpandas.yaml
- src/go/k8s/tests/e2e-v2/node-deleted/00-assert-create-redpanda.yaml
- src/go/k8s/tests/e2e-v2/node-deleted/00-create-redpanda.yaml
- src/go/k8s/tests/e2e-v2/node-deleted/01-assert-delete-node.yaml
- src/go/k8s/tests/e2e-v2/node-deleted/02-assert-delete-node-again.yaml
- src/go/k8s/tests/e2e-v2/node-deleted/03-delete-redpandas.yaml
- src/go/k8s/tests/e2e-v2/resource-redpanda-crud/00-assert-create-redpanda.yaml
- src/go/k8s/tests/e2e-v2/resource-redpanda-crud/00-create-redpanda.yaml
- src/go/k8s/tests/e2e-v2/resource-redpanda-crud/01-assert-update-chart-version.yaml
- src/go/k8s/tests/e2e-v2/resource-redpanda-crud/01-update-chart-version.yaml
- src/go/k8s/tests/e2e-v2/resource-redpanda-crud/02-assert-update-clusterspec.yaml
- src/go/k8s/tests/e2e-v2/resource-redpanda-crud/02-update-clusterspec.yaml
- src/go/k8s/tests/e2e-v2/resource-redpanda-crud/03-delete-redpandas.yaml
- src/go/k8s/tests/e2e-v2/resource-topic-crud/05-delete-redpandas.yaml
- src/go/k8s/tests/e2e-v2/upgrade-rollback/01-assert-upgrade-bad-redpanda.yaml
- src/go/k8s/tests/e2e-v2/upgrade-rollback/02-assert-upgrade-good-redpanda.yaml
- src/go/k8s/tests/e2e-v2/upgrade-rollback/03-delete-redpandas.yaml
- src/go/k8s/tests/e2e-v2/upgrade-values-check/02-delete-redpandas.yaml
Partially addresses: https://github.com/redpanda-data/redpanda/issues/13669
Attempt to reduce test complexity and increase reliability. 
* none
> k8s: improve testing reliability and fix broken tests

- src/v/json/json.h
- src/v/pandaproxy/json/rjson_util.h
- src/v/pandaproxy/schema_registry/requests/test/get_subject_versions_version.cc
- src/v/pandaproxy/schema_registry/requests/test/post_subject_versions.cc
- src/v/pandaproxy/schema_registry/test/sanitize_avro.cc
- src/v/pandaproxy/schema_registry/test/storage.cc
- src/v/security/CMakeLists.txt
- src/v/security/audit/CMakeLists.txt
- src/v/security/audit/schemas/CMakeLists.txt
- src/v/security/audit/schemas/application_activity.h
- src/v/security/audit/schemas/iam.h
- src/v/security/audit/schemas/schemas.h
- src/v/security/audit/schemas/tests/CMakeLists.txt
- src/v/security/audit/schemas/tests/ocsf_schemas_test.cc
- src/v/security/audit/schemas/types.h
Adds support for generating OCSF schema compliant JSON messages.
- [Authentication](https://schema.ocsf.io/1.0.0/classes/authentication?extensions=)
- [Application Lifecycle](https://schema.ocsf.io/1.0.0/classes/application_lifecycle?extensions=)
- [API Activity](https://schema.ocsf.io/1.0.0/classes/api_activity?extensions=)
Fixes: #13596 
Force push `7d791a7`:
- Multiple updates to address PR comments
Force push `1613b11:
- Updates for PR comments
- Moved `minify` to json utils
Force push `53238d9`:
- Updated tests to use BOOST_AUTO rather than seastar
- Improved coverage to 100%
- Random fixes for comments
Force push `d8cad70`:
- FIxed unused namespace error
Note to reviewers: I'm _not_ resolving the comments to allow you the ability to ensure I addressed your comments.
* none
> OCSF Schemas

- src/v/cloud_storage/tests/topic_recovery_service_test.cc
- src/v/cluster/controller.cc
- src/v/cluster/controller.h
- src/v/cluster/topics_frontend.cc
- src/v/cluster/topics_frontend.h
- src/v/kafka/server/handlers/create_topics.cc
- src/v/redpanda/application.cc
- tests/rptest/tests/topic_creation_test.py
The `create_topics` handler does a bit of preprocessing to incoming topic configs. This includes applying client-provided topic properties, some of which will fall back to cluster default configs. That fallback logic didn't appear on the autocreate_topics path, so I've moved some of it into `create_topics` itself. 
This PR also plumbs the `metadata_cache` down into `topics_frontend` to provide somewhat abstracted access to cluster-level defaults. 
Fixes #13492
* Fixes an issue where autocreated topics would not reflect cluster-level cloud storage config
> cluster/topics_frontend: Move some topic preprocessing into create_topics

- tests/rptest/services/admin_ops_fuzzer.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13758
Fixes: https://github.com/redpanda-data/redpanda/issues/13804,
> [v23.2.x] tests/admin_ops: check if topic is not listed when removed

- src/v/config/configuration.cc
These are customer facing and make the product look unprofessional.
* none
> chore: fix config description typos

- .github/pull_request_template.md
> .github: fix the "Pull request body" link in the PR template

- src/go/k8s/kind.yaml
- src/go/k8s/kuttl-v2-test.yaml
- src/go/k8s/tests/e2e-v2/decommission/03-delete-redpandas.yaml
- src/go/k8s/tests/e2e-v2/node-deleted/00-assert-create-redpanda.yaml
- src/go/k8s/tests/e2e-v2/node-deleted/00-create-redpanda.yaml
- src/go/k8s/tests/e2e-v2/node-deleted/01-assert-delete-node.yaml
- src/go/k8s/tests/e2e-v2/node-deleted/02-assert-delete-node-again.yaml
- src/go/k8s/tests/e2e-v2/node-deleted/03-delete-redpandas.yaml
- src/go/k8s/tests/e2e-v2/resource-redpanda-crud/00-assert-create-redpanda.yaml
- src/go/k8s/tests/e2e-v2/resource-redpanda-crud/00-create-redpanda.yaml
- src/go/k8s/tests/e2e-v2/resource-redpanda-crud/01-assert-update-chart-version.yaml
- src/go/k8s/tests/e2e-v2/resource-redpanda-crud/01-update-chart-version.yaml
- src/go/k8s/tests/e2e-v2/resource-redpanda-crud/02-assert-update-clusterspec.yaml
- src/go/k8s/tests/e2e-v2/resource-redpanda-crud/02-update-clusterspec.yaml
- src/go/k8s/tests/e2e-v2/resource-redpanda-crud/03-delete-redpandas.yaml
- src/go/k8s/tests/e2e-v2/resource-topic-crud/05-delete-redpandas.yaml
- src/go/k8s/tests/e2e-v2/upgrade-rollback/01-assert-upgrade-bad-redpanda.yaml
- src/go/k8s/tests/e2e-v2/upgrade-rollback/02-assert-upgrade-good-redpanda.yaml
- src/go/k8s/tests/e2e-v2/upgrade-rollback/03-delete-redpandas.yaml
- src/go/k8s/tests/e2e-v2/upgrade-values-check/02-delete-redpandas.yaml
Backport of PR https://github.com/redpanda-data/redpanda/pull/13812
> [v23.2.x] k8s: improve testing reliability and fix broken tests

- src/v/cloud_storage/tests/topic_manifest_test.cc
- src/v/cloud_storage/topic_manifest.cc
These values are all size_t under the hood and are deserialized as unsigned. In the event a value is accidentally underflowed, the serialization to a negative value means subsequent deserialization will fail.
This commit updates the serializtion to use uints.
Related https://github.com/redpanda-data/redpanda/issues/13727
* Topic manifests now serialize size values as unsigned instead of signed. Previously negative values could result in the failure to recreate the topic as a recovery topic.
> cloud_storage: serialize uint64 to topic manifest

- src/go/k8s/tests/e2e-v2/upgrade-rollback/00-create-redpanda.yaml
- src/go/k8s/tests/e2e-v2/upgrade-rollback/02-upgrade-good-redpanda.yaml
Fixes: https://github.com/redpanda-data/redpanda/issues/13669
Attempt to manage upgrades properly here and ensure we upgrade image not downgrade. 
* none
> k8s: make proper v2 tests for roll-back upgrade

- tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13725
Fixes: https://github.com/redpanda-data/redpanda/issues/13871,
> [v23.2.x] services/redpanda.py: make _get_object_storage_report dynamic

- src/v/archival/ntp_archiver_service.cc
- src/v/archival/tests/ntp_archiver_test.cc
- src/v/archival/tests/service_fixture.cc
- src/v/archival/types.cc
- src/v/archival/types.h
- src/v/cloud_storage/remote.cc
- src/v/cloud_storage/remote.h
- src/v/cloud_storage/tests/remote_test.cc
- src/v/cloud_storage/tests/s3_imposter.cc
- src/v/cloud_storage/tests/s3_imposter.h
- src/v/config/configuration.cc
- src/v/config/configuration.h
- src/v/redpanda/tests/fixture.h
- tests/rptest/tests/tiered_storage_model.py
Garbage collection of segments from the STM region was done one file at a time. This is not ideal as it blocks other maintenance work done by the archival service. This PR improves that by adding generic batching support in `remote`.
and using it.
Part of #12706
* none
> archival: batch delete segments during gc in stm region

- src/go/rpk/pkg/cli/transform/delete.go
Similar to acl delete we also support a --no-confirm flag
* none
> rpk/transform/delete: confirm deletion

- src/v/cluster/metadata_dissemination_service.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13899
Fixes: https://github.com/redpanda-data/redpanda/issues/13909,
> [v23.2.x] c/md_dissemination: fixed retrying leadership dissemination

- src/v/kafka/server/connection_context.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/13659
Fixes: https://github.com/redpanda-data/redpanda/issues/13670,
> [v23.2.x] Change rpk disconnect message from INFO to DEBUG

- src/v/raft/types.cc
The namespace was ambiguous:
/home/andrew/Repos/redpanda/src/v/raft/types.cc:290:5: error: reference to 'internal' is ambiguous
internal::hbeat_soa encodee(request.heartbeats.size());
^
Given the internal namespace is already in an anonymous namespace and can't be used outside the file, this just removes the namespace outright.
* none
> raft: remove internal namespace from types.cc

- .github/workflows/rpk-build.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/13799
> [v23.1.x] rpk: run go tests in gh actions

- .github/workflows/rpk-build.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/13799
> [v23.2.x] rpk: run go tests in gh actions

- .github/workflows/rpk-build.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/13799
> [v22.3.x] rpk: run go tests in gh actions

- src/v/cluster/tx_gateway_frontend.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13545
Fixes: #13782
> [v23.2.x] cluster/tx: Fix missing gate hold

- src/v/cloud_storage/tests/topic_manifest_test.cc
- src/v/cloud_storage/topic_manifest.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13740
> [v23.2.x] cloud_storage: serialize uint64 to topic manifest

- src/v/cloud_storage/tests/topic_manifest_test.cc
- src/v/cloud_storage/topic_manifest.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13740
> [v23.1.x] cloud_storage: serialize uint64 to topic manifest

- src/v/cloud_storage/remote_partition.cc
Since https://github.com/redpanda-data/redpanda/pull/13720, remote::delete_objects can handle inputs of any size and will split them in batches of the appropriate size for each backend.
Simplify the code by removing the unnecessary duplication of the batching logic.
* none
> cloud_storage/remote_partition: remove redundant batch chunking

- src/v/config/configuration.cc
- src/v/config/configuration.h
- src/v/raft/append_entries_buffer.cc
- src/v/raft/consensus.cc
- src/v/raft/consensus.h
- src/v/raft/group_manager.cc
- src/v/raft/group_manager.h
- src/v/raft/replicate_entries_stm.cc
- src/v/raft/tests/jitter_tests.cc
- src/v/raft/tests/mux_state_machine_fixture.h
- src/v/raft/tests/raft_group_fixture.h
- src/v/raft/timeout_jitter.h
- src/v/redpanda/application.cc
- tests/rptest/tests/raft_periodic_flush_test.py
- tests/rptest/tests/storage_resources_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13586
Backport of PR https://github.com/redpanda-data/redpanda/pull/13544
Fixes: #13926
> [v23.2.x] Added size bytes background flush to Raft

- src/v/pandaproxy/schema_registry/seq_writer.cc
- src/v/pandaproxy/schema_registry/seq_writer.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/13951
> [v23.2.x] schema_registry: Improve logging

- src/v/pandaproxy/schema_registry/error.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13917
Fixes: https://github.com/redpanda-data/redpanda/issues/13960,
> [v23.2.x] schema_registry: Fix error message for compatibility

- src/v/kafka/client/broker.cc
- src/v/kafka/client/broker.h
- src/v/kafka/client/client.cc
- src/v/kafka/client/client.h
- src/v/kafka/client/client_fetch_batch_reader.cc
- src/v/kafka/client/sasl_client.cc
- src/v/kafka/client/transport.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/13949
> [v23.2.x] kafka/client: Log client identifier

- src/v/cloud_storage/cache_service.cc
See issue/11270. an uncaught exception "filesystem error: rename failed" is failing test_scan_while_shutting_down, but there is no apparent intentional deletion of accesstime.tmp.
This commit handles the exception as error log, to catch it in ducktape if it happens during normal operations to further investigate it
Fixes #11270 
* none
> cloud_storage/cache_service: handle exception in cache::stop

- src/v/pandaproxy/schema_registry/seq_writer.cc
- src/v/pandaproxy/schema_registry/seq_writer.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/13951
> [v23.1.x] schema_registry: Improve logging

- src/v/redpanda/tests/fixture.h
Made waiting for controller quiescent state more robust. Now the test will wait for at least 2 seconds of quiescent controller state before proceeding to get the next revision.
Fixes: #13989
- none
> tests/fixture: wait for controller quiescent state

- src/v/cluster/CMakeLists.txt
- src/v/cluster/cloud_metadata/cluster_manifest.h
- src/v/cluster/cloud_metadata/tests/CMakeLists.txt
- src/v/cluster/cloud_metadata/tests/cluster_metadata_utils.h
- src/v/cluster/cloud_metadata/tests/controller_snapshot_reconciliation_test.cc
- src/v/cluster/cluster_recovery_reconciler.cc
- src/v/cluster/cluster_recovery_reconciler.h
- src/v/cluster/cluster_recovery_state.h
- src/v/cluster/cluster_recovery_table.cc
- src/v/cluster/cluster_recovery_table.h
- src/v/cluster/commands.h
- src/v/cluster/controller.cc
- src/v/cluster/controller.h
- src/v/cluster/fwd.h
- src/v/cluster/tests/CMakeLists.txt
- src/v/cluster/tests/cluster_recovery_table_test.cc
- src/v/cluster/tests/serialization_rt_test.cc
- src/v/cluster/tests/topic_properties_generator.h
- src/v/cluster/types.cc
- src/v/cluster/types.h
- src/v/model/model.cc
- src/v/model/record_batch_types.h
- src/v/redpanda/tests/fixture.h
- src/v/security/authorizer.h
This adds a new table that will be used to back a new controller stm for cluster recovery. Its interface is a simple list of attempted/in-progress recoveries, each representing the full attempt at recovery. This encodes the valid state changes for recoveries, broadly, only one active recovery may be present at a time, and once in a terminal state the recovery can't be changed.
A later PR will add plug this into the controller.
Related https://github.com/redpanda-data/redpanda/issues/9560
RFC: https://docs.google.com/document/d/1Db0y6nQX4zBkC1WyMKvoylTWdeaMia6xjWUQyC2qCoQ/edit?usp=sharing
* none
> cluster: add deterministic state for cluster recovery

- tests/rptest/tests/tiered_storage_model.py
- tests/rptest/tests/tiered_storage_model_test.py
Make few improvements to the model based tiered-storage test. Assert during consume phase without waiting for the test to complete. Tweak few parameters that caused problems. Clean the cache directory or transfer leadership during the consumption retries to force segment downloads.
Fixes #13745
* none
> rptest: Fix tiered_storage_test.py

- src/v/storage/log_housekeeping_meta.h
- src/v/storage/log_manager.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13615
Fixes #13831
> [v23.1.x] log_manager::housekeeping_scan iteration with suspension point fix

- .github/workflows/promote.yml
> add github workflow for triggering promotion steps in bk

- .github/workflows/promote.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/13930
> [v23.2.x] add github workflow for triggering promotion steps in bk

- .github/workflows/promote.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/13930
> [v23.1.x] add github workflow for triggering promotion steps in bk

- src/v/cluster/archival_metadata_stm.cc
The insync offset wasn't updated on every apply. Instead, it was only updated after archival configuration batches. Most notably, it wasnt updated after prefix_truncate batches. This PR fixes the problem.
Fixes #14017 
* none
> cluster: Fix archival stm insync offset update

- src/v/redpanda/tests/fixture.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/13991
Fixes: https://github.com/redpanda-data/redpanda/issues/14000,
> [v23.2.x] tests/fixture: wait for controller quiescent state

- tests/rptest/services/admin_ops_fuzzer.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13758
Fixes: https://github.com/redpanda-data/redpanda/issues/13801,
> [v23.1.x] tests/admin_ops: check if topic is not listed when removed

- src/v/cluster/tx_gateway_frontend.cc
- src/v/cluster/tx_gateway_frontend.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/13658
> [v23.1.x] Txn sessions thrashing: expire all old txs instead of one at a time

- src/v/cluster/drain_manager.cc
- src/v/cluster/drain_manager.h
- src/v/cluster/members_manager.cc
- src/v/cluster/partition_balancer_backend.cc
- src/v/cluster/partition_balancer_planner.cc
- src/v/cluster/partition_balancer_planner.h
- src/v/cluster/tests/partition_balancer_planner_test.cc
- src/v/redpanda/admin_server.cc
- tests/rptest/tests/partition_balancer_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13737
Fixes: https://github.com/redpanda-data/redpanda/issues/13977,
> [v23.2.x] Make maintenance mode opaque to the partition balancer

- src/v/cloud_storage/recovery_utils.cc
Since https://github.com/redpanda-data/redpanda/pull/13720, remote::delete_objects can handle inputs of any size and will split them in batches of the appropriate size for each backend.
Simplify the code by removing the unnecessary duplication of the batching logic.
* none
> cloud_storage/recover_utils: remove redundant batch chunking

- tests/rptest/services/cloud_cluster_utils.py
- tests/rptest/services/redpanda.py
- tests/rptest/services/redpanda_cloud.py
> rptest: Implement byoc cluster creation

- src/v/archival/ntp_archiver_service.cc
- src/v/cloud_storage/async_manifest_view.cc
- src/v/cloud_storage/remote_partition.cc
- src/v/cloud_storage/remote_segment.cc
- src/v/cloud_storage/types.h
Backport of #13806
Fixes #13973
* Stop logging errors on shutdown of the tiered storage subsystem
> [v23.2.x] cloud_storage: fix error logging on shutdown

- src/v/cluster/node/types.h
- src/v/cluster/tests/serialization_rt_test.cc
- src/v/cluster/types.h
- src/v/compat/check.h
- src/v/features/feature_table_snapshot.h
- src/v/kafka/server/tests/usage_manager_test.cc
- src/v/kafka/server/usage_aggregator.h
- src/v/net/unresolved_address.h
- src/v/serde/envelope.h
- src/v/utils/delta_for.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/13895
Fixes: https://github.com/redpanda-data/redpanda/issues/14028,
> [v23.2.x] serde: fix serde default comparison operator foot gun

- tests/rptest/redpanda_cloud_tests/high_throughput_test.py
> rptest: Fix topic creation and update some ignored tests

- src/go/k8s/apis/redpanda/v1alpha1/redpanda_clusterspec_types.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/13990
> [v23.2.x] Use Helm default for persistentVolume.enabled

- tests/rptest/tests/topic_recovery_test.py
When computing the cloud uploaded size during a test, the replaced segments should be skipped so we do not end up adding the sizes twice and throw off the comparison with on-disk sizes.
FIXES #13843 
* none
> ducktape: Exclude replaced segments when checking size

- src/v/pandaproxy/schema_registry/error.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13917
Fixes https://github.com/redpanda-data/redpanda/issues/13958
> [v23.1.x] schema_registry: Fix error message for compatibility

- src/v/storage/disk_log_impl.cc
- tests/rptest/tests/full_disk_test.py
While working on https://github.com/redpanda-data/redpanda/issues/13588 it was discovered that topics with `cleanup.policy=compact` and SI/TS enabled never delete local segments. Not even under disk pressure.
This commit asserts the existing behavior. Change in behavior will be discussed in a follow up pull request. Possibly in 
--
Open to suggestions how to improve the behavior assertion without waiting 2 minutes.
* none
> rptest: test compactible topics behavior under disk pressure

- tests/rptest/tests/topic_recovery_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14026
Fixes: https://github.com/redpanda-data/redpanda/issues/14044,
> [v23.2.x] ducktape: Exclude replaced segments when checking size

- tests/rptest/services/redpanda_installer.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13962
Fixes: https://github.com/redpanda-data/redpanda/issues/14080,
> [v23.2.x] Issue/13861/reduce api.github.com calls to fetch releases

- src/v/kafka/client/broker.cc
- src/v/kafka/client/broker.h
- src/v/kafka/client/client.cc
- src/v/kafka/client/client.h
- src/v/kafka/client/client_fetch_batch_reader.cc
- src/v/kafka/client/sasl_client.cc
- src/v/kafka/client/transport.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/13949
Fixes #13968 
Also steal a commit from https://github.com/redpanda-data/redpanda/pull/9830 to prevent conflict.
> [v23.1.x] kafka/client: Log client identifier

- src/v/archival/ntp_archiver_service.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13835
Fixes: https://github.com/redpanda-data/redpanda/issues/14036,
> [v23.2.x] archival: Audit meta in adjacent merger uploads

- src/v/redpanda/admin/api-doc/shadow_indexing.json
- src/v/redpanda/admin_server.cc
The metric is reported to RPK and used in `rpk topic describe-storage`. While it's not totally accurate, on account of missing out on spillover segments, we should still expose it.
I considered changing the field in RPK but this seems like the long-term field we want, and we should just eventually improve its correctness in Redpanda.
Fixes #14101
* `rpk topic describe-storage` will now report the number of segments in the STM region of the cloud log, rather than 0.
> admin: report cloud_log_segment_count

- tests/docker/ducktape-deps/kgo-verifier
- tests/rptest/services/kgo_verifier_services.py
- tests/rptest/tests/idempotency_stress_test.py
Added tests with a log of short lived producers that generate unique producer ids. 
- none
> Added tests stress testing producer id cache

- src/v/redpanda/admin/api-doc/shadow_indexing.json
- src/v/redpanda/admin_server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14102
Fixes: https://github.com/redpanda-data/redpanda/issues/14123,
> [v23.2.x] admin: report cloud_log_segment_count

- src/v/cloud_storage/tests/tx_range_manifest_test.cc
- src/v/kafka/protocol/request_reader.h
- src/v/kafka/protocol/schemata/generator.py
- src/v/utils/fragmented_vector.h
- src/v/utils/tests/fragmented_vector_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13854
Fixes #13882 
See commit messages for conflicts due to #9907
> [v23.1.x] k/protocol && utils/fragmented_vector improvements

- src/go/k8s/pkg/admin/mock_admin.go
> operator: fix race condition in test

- src/go/k8s/pkg/admin/mock_admin.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/14167
> [v23.2.x] operator: fix race condition in test

- src/v/cloud_storage_clients/s3_client.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14180
Fixes: https://github.com/redpanda-data/redpanda/issues/14186,
> [v23.1.x] s3_client: Check if response contains error

- tests/rptest/redpanda_cloud_tests/cloudv2_object_store_blocked.py
> rptest: Fix cloud provider type case

- src/go/k8s/apis/redpanda/v1alpha1/redpanda_clusterspec_types.go
(cherry picked from commit 6410e6f245c8e40e92b3e0474ae79385928c0792)
* none
> [v23.2.x] Operator-Redpanda: remove omitempty from users list for sasl

- src/go/rpk/pkg/adminapi/api_transform.go
- src/go/rpk/pkg/cli/transform/deploy.go
- src/v/redpanda/admin_server.cc
A few small fixes I found while testing deploys of wasm with rpk end to end.
* none
> transform: various fixes

- tests/rptest/tests/e2e_shadow_indexing_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14188
Fixes: https://github.com/redpanda-data/redpanda/issues/14189,
> [v23.2.x] ducktape/cloud_storage: Wait for topic info

- src/v/cloud_storage_clients/s3_client.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14180
Fixes: https://github.com/redpanda-data/redpanda/issues/14184,
> [v23.2.x] s3_client: Check if response contains error

- tests/rptest/scale_tests/high_throughput_test.py
ref #14208
fixes https://github.com/redpanda-data/devprod/issues/849
redpanda-data/devprod#878
* none
> [v23.2.x] scale tests: fix sizing variable name

- tests/rptest/services/cloud_cluster_utils.py
- tests/rptest/services/redpanda_cloud.py
> rptest: Update BYOC cluster creation for gcp

- tests/rptest/tests/idempotency_stress_test.py
Fixes: https://github.com/redpanda-data/redpanda/issues/14178
* none
> fix idempotency stress test

- src/v/redpanda/admin_server.cc
> redpanda/admin_server: set failure injection config on all shards

- src/v/archival/ntp_archiver_service.cc
Previously, we'd bail out of the upload loop if the initial sync call failed. The upload loop wouldn't restart until forced by re-setting the remote write topic config or restarting the node or changing leadership. This leads to the disk filling up since the collectable offset isn't advancing due to the lack of uploads.
The fix is to swap the `co_return` with `continue` to allow for retries. I've also added some error logging for when the loops quit unexpectedly.
* Fix a bug due to which the upload loop would terminate early if it failed to become in sync with the log
at start-up.
> archival: don't stop the upload loop on sync fails

- src/v/cloud_storage_clients/s3_client.cc
- src/v/cloud_storage_clients/tests/s3_client_test.cc
- src/v/hashing/secure.h
> hashing: add md5 specialization

- src/v/archival/ntp_archiver_service.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14214
> [v23.2.x] archival: don't stop the upload loop on sync fails

- src/v/archival/ntp_archiver_service.cc
- src/v/archival/segment_reupload.cc
- src/v/archival/tests/segment_reupload_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14152
> [v23.2.x] archival: skip reuploads of identical size

- src/go/k8s/config/crd/kustomization.yaml
- src/go/k8s/config/crd/patches/re-add-checksum-field_in_gitrepositories.source.toolkit.fluxcd.io.yaml
- src/go/k8s/config/crd/patches/re-add-checksum-field_in_ocirepositories.source.toolkit.fluxcd.io.yaml
- src/go/k8s/config/crd/patches/re-add-checksum-field_in_source.toolkit.fluxcd.io.yaml
Backport of PR https://github.com/redpanda-data/redpanda/pull/14265
> [v23.2.x] operator: patch back in the checksum field into the flux crds

- src/go/k8s/config/crd/kustomization.yaml
Backport of PR https://github.com/redpanda-data/redpanda/pull/14277
> [v23.2.x] operator: move kubebuilder comments back

- tests/rptest/perf/ts_read_openmessaging_test.py
- tests/rptest/perf/ts_write_openmessaging_test.py
- tests/rptest/services/openmessaging_benchmark_configs.py
- tests/rptest/services/redpanda.py
This PR introduces new nightly perf regression tests to test various cloud storage read/write paths.
`ts_write_openmessaging_test.py` has the following cloud storage metrics;
`ts_read_openmessaging_test.py` has the following cloud storage metrics;
* none
> Test cloud storage in nightly perf regression tests.

- src/go/k8s/pkg/resources/certmanager/type_helpers.go
- src/go/k8s/pkg/resources/statefulset.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/14239
> [v23.2.x] operator: add readiness check to Cluster statefulset

- src/v/cluster/members_manager.cc
- src/v/cluster/persisted_stm.cc
- src/v/features/feature_table.cc
- src/v/features/feature_table.h
- src/v/raft/configuration_manager.cc
- src/v/raft/consensus.cc
- src/v/raft/consensus.h
- src/v/raft/consensus_utils.cc
- src/v/raft/consensus_utils.h
- src/v/raft/group_configuration.cc
- src/v/raft/group_configuration.h
- src/v/raft/recovery_stm.cc
- src/v/raft/recovery_stm.h
- src/v/raft/tests/CMakeLists.txt
- src/v/raft/tests/configuration_manager_test.cc
- src/v/raft/tests/configuration_serialization_test.cc
- src/v/raft/tests/raft_fixture.cc
- src/v/raft/tests/raft_fixture.h
- src/v/raft/tests/raft_reconfiguration_test.cc
- src/v/raft/types.cc
- src/v/storage/snapshot.cc
- src/v/storage/snapshot.h
- tools/offline_log_viewer/model.py
If learner start offset is set in Raft configuration. Recovery STM is
going to request an on demand snapshot from stm manager (or an empty
snapshot if stm manager is not set) and deliver it to the follower as a
log starting point.
Fixes: https://github.com/redpanda-data/redpanda/issues/13709
- Added Raft ability to start learner recovery from arbitrary point in log.
> Raft learner initial offset

- src/v/cluster/members_backend.cc
- src/v/cluster/members_backend.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/13988
Fixes: https://github.com/redpanda-data/redpanda/issues/14060,
> [v23.2.x] c/members_backend: prioritize removing nodes when decomm isfinished

- src/go/k8s/api/redpanda/v1alpha1/redpanda_clusterspec_types.go
- src/go/k8s/api/redpanda/v1alpha1/zz_generated.deepcopy.go
- src/go/k8s/go.sum
Add secretRef which is available in Redpanda helm values and schema.
* none
> k8s: Add secretRef to listener TLS definition

- src/go/k8s/go.sum
Run go mod tidy on k8s source.
* none
> k8s: Fix go mod sum

- src/go/k8s/api/redpanda/v1alpha1/redpanda_clusterspec_types.go
- src/go/k8s/api/redpanda/v1alpha1/zz_generated.deepcopy.go
- src/go/k8s/go.sum
Backport of PR https://github.com/redpanda-data/redpanda/pull/14303
> [v23.2.x] k8s: Add secretRef to listener TLS definition

- src/v/storage/key_offset_map.cc
Updates the behavior of the key_offset_map to allow entries to be put even if it's already full, provided it doesn't require adding new keys.
This makes certain aspects of testing easier (e.g. we can say that a map with a limit of 10 keys will index all segments with a key space containing 10 keys, instead of stopping immediately after we see the 10th key).
* none
> storage: allow put on key collision even if map full

- src/v/cluster/log_eviction_stm.cc
- src/v/storage/disk_log_impl.cc
- tests/rptest/tests/full_disk_test.py
Reverts redpanda-data/redpanda#14212
Some topics (consumer offsets) need special consideration.
* none
> Revert "storage: evict data from compactible topics under disk pressure"

- src/v/kafka/server/tests/produce_consume_utils.h
- src/v/storage/probe.h
- src/v/test_utils/test.h
- src/v/test_utils/test_macros.h
While working on some upcoming compaction tests, I found the following set of changes helpful:
- specifying value part of `kv_t` for producer utils
- an equality operator for `kv_t`
- more ASSERT_*_CORO methods
- add a missing include for gtests
- exposed a storage metric via `probe`
This change contains no functional changes to production code.
* none
> miscellaneous utilities and test improvements for compaction

- src/go/k8s/config/crd/bases/cluster.redpanda.com_redpandas.yaml
From last 2 PRs the Redpnada CRD was not regenerated.
Ref
https://github.com/redpanda-data/redpanda/pull/14303
https://github.com/redpanda-data/redpanda/pull/14195
* none
> k8s: Regenerate Redpanda custom resource definition

- src/go/k8s/config/crd/bases/cluster.redpanda.com_redpandas.yaml
Backport of PR https://github.com/redpanda-data/redpanda/pull/14341
> [v23.2.x] k8s: Regenerate Redpanda custom resource definition

- src/v/cloud_roles/signature.cc
- src/v/cloud_roles/signature.h
- src/v/cloud_roles/tests/signature_test.cc
- src/v/http/client.cc
- src/v/http/client.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/14271
> [v23.2.x] cloud_roles: redact fields from request string representation

- src/go/k8s/go.mod
- src/go/k8s/go.sum
REF:
https://nvd.nist.gov/vuln/detail/CVE-2023-44487
Bump grpc dependnecy to latest v1.57.1.
* none
> k8s: Bump grpc dependnecy

- src/go/k8s/go.mod
- src/go/k8s/go.sum
Backport of PR https://github.com/redpanda-data/redpanda/pull/14354
> [v23.2.x] k8s: Bump grpc dependnecy

- src/go/rpk/pkg/cli/cluster/partitions/list.go
- src/go/rpk/pkg/cli/group/describe.go
- src/go/rpk/pkg/cli/topic/describe.go
- src/go/rpk/pkg/cli/topic/describe_storage.go
- src/go/rpk/pkg/out/out.go
Sections _always_ added a newline at the end of them. Some commands _also_ added a newline at the end inside a section.
This removes out.Header in favor of out.Sections, which is hopefully a bit more foolproof to use so we do not mistakenly add newlines in the wrong place. out.Sections only print newlines between sections. If we try to add a section that was not registered, nothing happens -- this allows the "conditional add" that we currently use in some areas. Although this is a liiitttllee bit uglier, it is hopefully a bit more understandable to use and more foolproof, rather than counting sections ahead of time and having two or three booleans dictating who knows what at the callsite.
The group describe code has been cleaned up such that each chunk that prints text is only responsible …
> rpk: always use one newline in section commands

- src/go/k8s/config/crd/bases/cluster.redpanda.com_redpandas.yaml
- src/go/k8s/kuttl-v2-helm-test.yaml
Manifests udpated with recent changes, and fixed testing artifacts directory. 
* none
> k8s: helm-v2 test fixed, and description for redpanda clusterspec updated

- src/v/cluster/types.cc
- src/v/kafka/server/handlers/alter_configs.cc
- src/v/kafka/server/handlers/configs/config_utils.h
- src/v/kafka/server/handlers/incremental_alter_configs.cc
- tests/rptest/tests/replication_factor_change_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14020
> [v23.1.x] Introduce validation for replication factor config

- src/v/cluster/types.cc
- src/v/kafka/server/handlers/alter_configs.cc
- src/v/kafka/server/handlers/configs/config_utils.h
- src/v/kafka/server/handlers/incremental_alter_configs.cc
- src/v/kafka/server/tests/config_utils_test.cc
- tests/rptest/tests/replication_factor_change_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14020
Fixes: https://github.com/redpanda-data/redpanda/issues/14332,
> [v23.2.x] Introduce validation for replication factor config

- src/go/rpk/pkg/cli/cloud/byoc/byoc.go
- src/go/rpk/pkg/cli/cloud/byoc/install.go
- src/go/rpk/pkg/cloudapi/api_installpack.go
This will let us bypass the redpanda ID
requirement for the byoc plugin in order to have
a new command: validate.
validate will always download the latest plugin
and run the command. For the rest of the commands, redpanda ID is needed.
* none
> rpk: make --redpanda-id optional in rpk cloud byoc

- src/v/config/node_config.cc
- src/v/model/metadata.h
- src/v/pandaproxy/rest/configuration.cc
- src/v/pandaproxy/rest/configuration.h
- src/v/redpanda/application.cc
- tests/rptest/services/redpanda.py
- tests/rptest/services/templates/redpanda.yaml
- tests/rptest/tests/configuration_update_test.py
- tests/rptest/tests/rpk_start_test.py
This PR adds validation for configs specifying advertised addresses for various APIs:
- `advertised_kafka_api`
- `advertised_rpc_api`
- `advertised_pandaproxy_api`
Specifically, halt broker startup if any of the above specify "0.0.0.0" as the host. If `advertised_{kafka,rpc}_api` are unset each fall back to the corresponding listener config. Validation takes this into account. e.g. validation fails if `advertised_kafka_api` is unset and `kafka_api` includes a listener with a "0.0.0.0" host.
Fixes #12395 
* Advertised addresses must be set to a valid ip address or hostname for that node.
> Enforce valid advertised addrs

- .github/workflows/promote.yml
> Use the official buildkite plugin to trigger the promotion

- src/v/pandaproxy/api/api-doc/schema_registry.json
- src/v/pandaproxy/schema_registry/handlers.cc
- src/v/pandaproxy/schema_registry/handlers.h
- src/v/pandaproxy/schema_registry/seq_writer.cc
- src/v/pandaproxy/schema_registry/seq_writer.h
- src/v/pandaproxy/schema_registry/service.cc
- src/v/pandaproxy/schema_registry/sharded_store.cc
- src/v/pandaproxy/schema_registry/sharded_store.h
- src/v/pandaproxy/schema_registry/storage.h
- src/v/pandaproxy/schema_registry/store.h
- src/v/pandaproxy/schema_registry/test/store.cc
- src/v/pandaproxy/schema_registry/types.h
- tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13557
Fixes: https://github.com/redpanda-data/redpanda/issues/14380,
> [v23.2.x] schema_registry: Add support for `DELETE /config/{subject}`

- src/v/raft/recovery_scheduler.cc
The recovery scheduler metrics were applying the `aggregate_metrics`
logic to both internal and public metrics.
This is not how we handle public metrics generally. We always aggregate
the shard label on public metrics and `aggregate_metrics` only applies
to internal metrics.
* none
> recovery_scheduler: Always aggregate shard label on public_metrics

- src/v/transform/transform_manager.cc
Fixes a use after move. The destructor could have moved the probe, and
left it `nullptr`, this was handled for with `state` being marked
`std::optional` but the probe was not accounted for.
* none
> transform/manager: fix use after move

- src/v/kafka/server/replicated_partition.cc
- tests/rptest/tests/offset_for_leader_epoch_read_replica_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14403
Fixes: https://github.com/redpanda-data/redpanda/issues/14417,
> [v23.2.x] cloud_storage: Fix offset for leader epoch request for read-replica

- .github/workflows/promote.yml
> Use trunk for promote job

- src/v/cluster/tm_stm.cc
- src/v/cluster/tm_stm.h
- src/v/cluster/tx_gateway_frontend.cc
- src/v/cluster/tx_hash_ranges.h
> tx: add more trace logging in init_producer_id code path

- src/v/kafka/server/replicated_partition.cc
- tests/rptest/tests/offset_for_leader_epoch_read_replica_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14403
Fixes: https://github.com/redpanda-data/redpanda/issues/14418,
> [v23.1.x] cloud_storage: Fix offset for leader epoch request for read-replica

- src/v/cluster/partition_balancer_planner.cc
- tests/rptest/tests/partition_balancer_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14145
> [v23.2.x] tests: added test validating if balancer can cooperate with space mgmnt

- src/v/raft/tests/raft_fixture.cc
- src/v/raft/tests/raft_fixture.h
- src/v/raft/tests/raft_reconfiguration_test.cc
The `reconfiguration` test might failed when executed with leader acks.
In slow debug build modes and with tight intervals it might happend that
the leader stepped down after returning from replicate but before
actually replicating batches to the followers. If new leader is elected
in this case the log may be truncated and there may be no batches in the
log, making the test to fail.
Fixes: #14425
- none
> Fixed Raft reconfiguration unit test

- .github/workflows/promote.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/14395
> [v23.1.x] Use the official buildkite plugin to trigger the promotion

- tests/rptest/tests/delete_records_test.py
- PR #14434 was merged too early before edits were made, this change represents the intended edits that were not force-pushed before merge.
* none
> rptest: Patch incomplete fix for delete-recrds test

- .github/workflows/promote.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/14395
> [v23.2.x] Use the official buildkite plugin to trigger the promotion

- .github/workflows/promote.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/14424
> [v23.1.x] Use trunk for promote job

- src/v/bytes/iobuf.cc
- src/v/bytes/tests/iobuf_tests.cc
Before:
```
00000000 | 41 65 6e 65 61 6e 20 73  65 64 20 6c 65 6f 20 70  | Aenean sed leo p
00000010 | 6f 72 74 74 69 74 6f 72  2e  | orttitor.
```
After:
```
00000000 | 41 65 6e 65 61 6e 20 73  65 64 20 6c 65 6f 20 70  | Aenean sed leo p
00000010 | 6f 72 74 74 69 74 6f 72  2e                       | orttitor.
```
* none
> bytes/iobuf: pad the hexdump ascii column

- .github/workflows/promote.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/14424
> [v23.2.x] Use trunk for promote job

- tests/rptest/redpanda_cloud_tests/high_throughput_test.py
> rptest: Bump generic timeouts

- src/go/rpk/pkg/adminapi/api_broker.go
- src/go/rpk/pkg/cli/cluster/maintenance/enable.go
- src/go/rpk/pkg/cli/cluster/maintenance/status.go
- src/v/redpanda/admin/api-doc/broker.json
- src/v/redpanda/admin_server.cc
- tests/rptest/clients/rpk.py
- tests/rptest/tests/maintenance_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13260
Fixes: https://github.com/redpanda-data/redpanda/issues/14210,
> [v23.2.x] Do not always report all fields in maintenance status

- tests/rptest/tests/audit_log_test.py
mitigates: https://github.com/redpanda-data/redpanda/issues/14565
Tests in this file use the existence of the audit topic as a proxy for full initialization of the audit manager. This is fine for the general case (interacting with the audit log), but the client probe is created after the topic, so we have a race in the test.
The fix will be straightforward, but I have a couple of questions for Rob. Marking this ok_to_fail to avoid a bunch of noise on various builds.
* none
> audit_log_test: Mark test_audit_log_metrics ok_to_fail

- tests/rptest/tests/usage_test.py
The usage_test was incorrectly asserting on a comparison of the values of the bytes_in_cloud_storage field.
Observed failures of this test saw the failure occur when comparing an open window to a closed window. In this case the test will use le other then eq to compare the fields, however this field is particularly special as it is supposed to be set to -1 if the queried broker is not the contoller leader. This test triggers a restart so it is common that this value may change.
The fix is to only compare these fields if the windows are closed, that way the value is fixed in time across restarts.
Fixes: #13448
* none
> Fix for CI failure (failure to assert_usage_consistency) in UsageTest.test_usage_collection_restart

- tests/rp_cloud_cleanup.py
- tests/rptest/services/cloud_cluster_utils.py
> Check provider when deleting BYOC cluster

- tools/dev_cluster.py
dev_cluster: fix advertised apis
* none
> dev_cluster: fix advertised apis

- src/go/k8s/pkg/resources/ingress.go
* fix nil pointer in Console controller when updating annotations
> operator(console): initialize null map before adding entries

- tests/rptest/tests/topic_recovery_test.py
Cloud storage segments encode the archiver term in the object key. This change is not reflected in the json translation of the binary partition manifest, which generates keys without an archiver term.
this means that we can have these segments in s3,
1. 9452-10253-881631-1-v1.log.1
2. 9452-10255-881909-1-v1.log.2
Have 1 listed in the replaced section of the binary partition manifest, but the json version will list it as 9452-1-v1.log. This confuses the TopicRecoveryTest.test_time_based_retention, which will consider both as replaced and not count them up.
This PR fixes the test by mangling the archiver_term in the segment key
Fixes #13547 
* none
> tests/topic_recovery_tests: archiver_term added to replaced segment key

- tests/rptest/tests/topic_recovery_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14573
Fixes: https://github.com/redpanda-data/redpanda/issues/14649,
> [v23.2.x] tests/topic_recovery_tests: archiver_term added to replaced segment key

- tests/rptest/tests/usage_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14584
Fixes: https://github.com/redpanda-data/redpanda/issues/14616,
> [v23.2.x] Fix for CI failure (failure to assert_usage_consistency) in UsageTest.test_usage_collection_restart

- tests/rptest/tests/memory_stress_test.py
Fixes: #12245
Created issue #12496 to address this test.
Force push `d1ee2ee`:
* Rebase off of dev (no changes)
* None
> dt/memory_stress_test: Mark `test_fetch_with_many_partitions` `@ok_to_fail`

- cmake/testing.cmake
Not having warnings makes it more likely to have buggy tests. A test asserting a behavior incorrectly is no different from the behavior being wrong in the first place.
...
The actual motivation is that I spent an evening debugging a "broken promise" exception because of the missing `return` statement in one of the branches, which the compiler didn't catch. I don't want that to happen again.
Some checks are explicitly disabled for now to avoid having to refactor too much code in one go. After the current change is merged we can work on improving the code gradually.
* none
> cmake: enable warnings for testing code

- tests/rptest/redpanda_cloud_tests/high_throughput_test.py
> Improved logging and timeouts calculations for instances with lower throughputs

- tests/rptest/tests/e2e_shadow_indexing_test.py
- tools/rp_storage_tool/src/remote_types.rs
Previously, rp_storage_tool did not decode the list of spillover manifests encoded as a column store in
`partition_manifest::_spillover_manifests`. This was problematic for a few reasons:
1. no way of inspecting the list of spillover manifests given a binary encoded partition manifest
2. tests that download the manifest, change it, and then perform a reset would lose the list of spillover manifests after the reset
This patch brings the rp_storage_tool capabilities largely in line with the tip of Redpanda dev. The `metadata_size_hint` is ignored from the segment metas, but that's likely fine for now. If we ever have
to do a manual reset of the partition manifest, we will not have to manually add the list of spillovers to
the decoded output.
This change is required for …
> rp_storage_tool: decode spillover manifest entries

- tests/rptest/tests/audit_log_test.py
The test harness uses the presence of the audit topic as a proxy for audit log initialization. The audit client probe, however, is constructed _after_ topic creation. For this test, we can just wait for each node to export the client probe metric on the internal endpoint before fetching and asserting on all expected metrics. It's unlikely that we'll ever timeout here unless something else is broken or changed.
Fixes #14565 
* none
> ducktape/audit_log_test: Fix racy metrics test

- tests/rptest/tests/cloud_storage_scrubber_test.py
If the partition moves while the request is being processed, a 404 response will be returned. The test should retry this in order to be more stable.
* none
> rptest: retry anomaly fetches on 404 responses

- tools/format-py
- tools/offline_log_viewer/kafka.py
- tools/offline_log_viewer/viewer.py
Archival metadata stm command viewer updates  🚁 
* none
> Archival metadata stm command viewer updates

- cmake/dependencies.cmake
- install-dependencies.sh
- src/v/bytes/CMakeLists.txt
- src/v/hashing/CMakeLists.txt
- src/v/pandaproxy/parsing/CMakeLists.txt
- src/v/reflection/CMakeLists.txt
Renamed `abseil` to `absl` as this is the name that is being used by other dependencies to query for `abseil` libraries.
- none
> Renamed abseil to absl

- src/v/archival/upload_housekeeping_service.cc
log error for unknown exception, this should make them visible in the log and ducktape
* none
> archival/upload_housekeeping_service: log error for unknown exception

- src/v/kafka/server/handlers/alter_partition_reassignments.cc
- src/v/kafka/server/handlers/create_topics.cc
- src/v/kafka/server/handlers/delete_acls.cc
- src/v/kafka/server/request_context.h
- src/v/kafka/server/server.cc
- src/v/redpanda/tests/fixture.h
Instead of holding onto authz results, instead immediately attempt to enqueue the results into the audit log.  If any failure is encountered, set a flag.  Once the call to `audit()` is made, the flag is checked and then handled appropriately.
Fixes: #14769
Force push `da4743c`:
* Made `do_authorized` private
Force push `79d353c`:
* Provide `api_key` in request header for fixture test
* Handle situation where API key does not find a handler
* Situation should only be encountered in tests
Force push `a5121f0`:
* Reverted change for handling situations where api key does not return a handler
* Situation should only occur in tests
* Would alert to issues with test
* none
> kafka: Remove container holding authz results

- src/v/pandaproxy/schema_registry/storage.h
- src/v/pandaproxy/schema_registry/test/storage.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14866
> [v22.3.x] schema_registry: Support the compatible format for CONFIG value

- src/v/io/interval_map.h
- src/v/io/tests/CMakeLists.txt
- src/v/io/tests/interval_map_test.cc
The interval map is the underlying container used to implement the page set index for the unified io proof-of-concept.
Coverage report 🧨 
```
[nwatkins@fedora coverage]$ src/v/io/tests/io_rpunit
[nwatkins@fedora coverage]$ ../../tools/gcovr src/v/io
------------------------------------------------------------------------------
GCC Code Coverage Report
Directory: ../..
------------------------------------------------------------------------------
File                                       Lines    Exec  Cover   Missing
------------------------------------------------------------------------------
src/v/io/cache.h                             109     109   100%
src/v/io/interval_map.h                       45      45   100%
src/v/io/tests/cache_test.cc                 491     491   100% …
```
> io: add interval map container

- tests/docker/docker-compose.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/11708
> [v23.1.x] tests: disable minio console

- src/v/security/CMakeLists.txt
- src/v/security/audit/CMakeLists.txt
> security: Moved utils.cc to correct library

- src/v/archival/ntp_archiver_service.cc
- src/v/cloud_roles/request_response_helpers.cc
- src/v/cluster/log_eviction_stm.cc
- src/v/cluster/metrics_reporter.cc
- src/v/http/demo/client.cc
- src/v/http/tests/http_client_test.cc
- src/v/pandaproxy/test/utils.h
- src/v/ssx/future-util.h
Fixed building Redpanda with `clang` version 17
The two changes were required to build Redpanda with clang-17.
1. Do not catch `ss::sleep_aborted_exception` when `ss::abort_requested`
is already captured. As `ss::sleep_aborted_exception` inherits from
more general `ss::abort_requested_exception` it is already handled
2. Boost `boost::basic_static_string` is not longer implicitly
convertible to `std::string_view`
Signed-off-by: Michal Maslanka <michal@redpadna.com>
- none
> chore: fixed building with clang-17

- src/v/kafka/server/handlers/produce.cc
- src/v/kafka/server/request_context.h
- tests/rptest/tests/audit_log_test.py
- tests/rptest/tests/cluster_config_test.py
Don't audit the auditing user's authz checks to prevent possible infinite loop of audit event generation.
Fixes: https://github.com/redpanda-data/core-internal/issues/893
Force push `8ed1af3`:
* Relaxed non-audit rule to only restrict auditing on the audit user on produce calls
Force push `ebbfd6a`:
* Rebased off dev to address merge conflicts
Force push `a24fc7f`:
* Fixed dead code
* none
> Don't audit audit user authz checks

- tests/rptest/redpanda_cloud_tests/high_throughput_test.py
- tests/rptest/tests/rpk_topic_test.py
> Updates on test timeouts and flow when throughput is low

- src/v/redpanda/admin_server.cc
This is in preparation for splitting the admin server into multiple files which will require having a less generic name for the logger. Thing takes over a minute to compile :(
* none
> redpanda: rename admin server logger

- src/v/archival/upload_housekeeping_service.cc
Quells bad log line errors like:
```
ERROR 2023-11-11 04:13:25,955 [shard 0:au  ] archival - upload_housekeeping_service.cc:411 - upload housekeeping job scrubber error: seastar::broken_named_semaphore (Semaphore broken: self_config_barrier)
```
Fixes https://github.com/redpanda-data/redpanda/issues/14807
Fixes https://github.com/redpanda-data/redpanda/issues/14915
* none
> archival: handle shutdown in housekeeping more gracefully

- src/v/cloud_storage/tests/s3_imposter.cc
- src/v/cluster/CMakeLists.txt
- src/v/cluster/cloud_metadata/cluster_recovery_backend.cc
- src/v/cluster/cloud_metadata/cluster_recovery_backend.h
- src/v/cluster/cloud_metadata/manifest_downloads.cc
- src/v/cluster/cloud_metadata/manifest_downloads.h
- src/v/cluster/cloud_metadata/tests/CMakeLists.txt
- src/v/cluster/cloud_metadata/tests/cluster_recovery_backend_test.cc
- src/v/cluster/cluster_recovery_manager.cc
- src/v/cluster/cluster_recovery_manager.h
- src/v/cluster/cluster_recovery_table.h
- src/v/cluster/controller.cc
- src/v/cluster/controller.h
- src/v/cluster/controller_snapshot.cc
- src/v/cluster/controller_snapshot.h
- src/v/cluster/controller_stm.cc
- src/v/cluster/controller_stm.h
- src/v/cluster/fwd.h
- src/v/config/configuration.cc
- src/v/config/configuration.h
- src/v/features/feature_table.cc
- src/v/features/feature_table.h
- src/v/redpanda/admin/api-doc/shadow_indexing.json
- src/v/redpanda/admin_server.cc
- src/v/redpanda/admin_server.h
- src/v/redpanda/application.cc
- src/v/test_utils/test_macros.h
- tests/rptest/services/admin.py
- tests/rptest/tests/cluster_recovery_test.py
This adds a new cluster recovery state machine to the controller. This will serve to accept recovery requests, and drive through the steps of recovery with a backend. It is the spiritual successor to `topic_recovery_service`, but is expected to be persisted and robust to restarts. This commit introduces the following pieces to manage this:
- `cluster_recovery_manager`: part of the controller stm that drives changes to the `cluster_recovery_table`
- `cluster_recovery_backend`: listens for active recoveries to show up in the `cluster_recovery_table` and performs actions from the `controller_snapshot_reconciler` to walk through stages of recovery.
RFC: https://docs.google.com/document/d/1Db0y6nQX4zBkC1WyMKvoylTWdeaMia6xjWUQyC2qCoQ/edit?usp=sharing
* none
> cluster: add cluster recovery controller stm management

- src/v/raft/consensus.cc
- tests/rptest/tests/simple_e2e_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14794
> [v23.2.x] Fix for `leader_ack` consistency level (do not advance last visible offset beyond majority replicated)

- src/v/kafka/server/server.cc
- tests/rptest/tests/transaction_kafka_api_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14822
> [v23.2.x] fixed rendering transaction status

- src/v/cluster/log_eviction_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/12959
Fixes: https://github.com/redpanda-data/redpanda/issues/14880,
> [v23.2.x] Add proper exception handler to around eviction_stm's call to replicate

- src/v/cluster/service.cc
Previously even if result returned from `raft::linerizable_barrier` in `cluster::service::get_controller_committed_offset` contained an error the code was accessing it causing an exception to be thrown. An exception wasn't handled leading to error log entry at the rpc service handler level.
- none
> c/service: fixed accessing result when it contains an error

- tests/rp_cloud_cleanup.py
- tests/rptest/services/provider_clients/ec2_client.py
- tests/rptest/services/provider_clients/rpcloud_client.py
> ci: make cleanup prefix agnostic

- src/v/archival/upload_housekeeping_service.cc
- src/v/kafka/server/connection_context.cc
- src/v/storage/log_manager.cc
These can be useful clues in debugging -- rather than silently ignoring/returning, logs a debug message.
This PR adds a few in various places that were previously either continuing or returning early.
* none
> treewide: log debug messages on shutdown error

- .github/workflows/build-redpanda.yml
This will have the affect of providing fresh ccache contexts from upstream/dev to each pull request.
* none
> build: improve ccache by updating the cache

- tests/rptest/tests/full_disk_test.py
Added data verification in full_disk_test.py to ensure successful cloud upload before local eviction.
Cherry-picked from #14484
* none
> t/full_disk_test: read the data after eviction

- src/v/raft/recovery_stm.cc
- src/v/raft/tests/raft_fixture.cc
- src/v/raft/tests/raft_fixture.h
- src/v/raft/tests/raft_reconfiguration_test.cc
Fixed incorrectly set on demand snapshot `offset_translator` state.
- none
> r/recovery_stm: fixed offset translator state in on demand snapshot

- src/v/cluster/scheduling/partition_allocator.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13397
> [v23.2.x] Better error message when topic creation fails

- tests/rptest/services/redpanda_cloud.py
> ci: remove byoc plugin install

- tests/rptest/redpanda_cloud_tests/high_throughput_test.py
- tests/rptest/redpanda_cloud_tests/omb_validation_test.py
- tests/rptest/services/machinetype.py
- tests/rptest/services/openmessaging_benchmark.py
- tests/rptest/services/openmessaging_benchmark_configs.py
- tests/rptest/services/redpanda.py
- tests/rptest/services/redpanda_cloud.py
- tests/rptest/services/templates/omb_driver.yaml
- tests/rptest/test_suite_cloud.yml
Adds OMB performance validation tests for cloud tiers.
* none
> Performance validation tests for cloud

- tests/rptest/redpanda_cloud_tests/high_throughput_test.py
> rptest: fix time tracking and checks in several tests

- tests/rptest/services/redpanda_cloud.py
> rptest: Check cluster health before the testrun

- src/v/raft/consensus.cc
- src/v/raft/state_machine.cc
- src/v/raft/state_machine.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/14929
Fixes: https://github.com/redpanda-data/redpanda/issues/14980,
> [v23.2.x] Fixed handling Raft snapshot

- tests/rptest/tests/cloud_storage_scrubber_test.py
Ordering of reported anomalies is not guaranteed. Previously, the test compared the contents of lists which resulted in failures when anomalies were out of order. This commit fixes the issue by replacing the lists with sets.
Fixes #14796
* none
> rptest: fix anomalies comparison

- src/v/cluster/CMakeLists.txt
- src/v/cluster/cloud_metadata/error_outcome.h
- src/v/cluster/cloud_metadata/key_utils.cc
- src/v/cluster/cloud_metadata/key_utils.h
- src/v/cluster/cloud_metadata/offsets_recovery_service.h
- src/v/cluster/cloud_metadata/offsets_snapshot.h
- src/v/cluster/cloud_metadata/offsets_upload_router.h
- src/v/cluster/cloud_metadata/offsets_upload_rpc_types.h
- src/v/cluster/cloud_metadata/offsets_uploader.cc
- src/v/cluster/cloud_metadata/offsets_uploader.h
- src/v/cluster/cloud_metadata/tests/CMakeLists.txt
- src/v/cluster/cloud_metadata/tests/offsets_recovery_test.cc
- src/v/cluster/offsets_recovery_rpc.json
- src/v/config/configuration.cc
- src/v/config/configuration.h
- src/v/kafka/server/group.h
- src/v/kafka/server/group_manager.cc
- src/v/kafka/server/group_manager.h
- src/v/redpanda/CMakeLists.txt
- src/v/redpanda/application.cc
- src/v/redpanda/application.h
This PR adds some utilities for serializing and uploading consumer offsets from the leaders managed by `kafka::group_manager`. At a high level there are two pieces introduced:
- an offsets snapshotting interface added to `kafka::group_manager`, that collects the NTP-to-offsets mapping of each group
- an uploader that wraps the `kafka::group_manager` and is exposed via internal RPC endpoint
To keep reviews more focused, this PR only introduces the high level abstractions and functionality, without plugging them into the broader cluster metadata uploader infra (that will come in a later PR).
Fixes https://github.com/redpanda-data/redpanda/issues/9553
RFC: https://docs.google.com/document/d/1Db0y6nQX4zBkC1WyMKvoylTWdeaMia6xjWUQyC2qCoQ/edit?usp=sharing
* none
> cloud_metadata: utilities for uploading consumer offsets

- src/v/config/configuration.cc
- src/v/config/configuration.h
- src/v/config/validators.cc
- src/v/config/validators.h
- src/v/kafka/server/request_context.h
- src/v/kafka/server/server.cc
- src/v/redpanda/admin/server.cc
- src/v/redpanda/admin/server.h
- src/v/security/audit/audit_log_manager.cc
- src/v/security/audit/audit_log_manager.h
- src/v/security/audit/schemas/tests/ocsf_schemas_test.cc
- src/v/security/audit/schemas/utils.cc
- src/v/security/audit/schemas/utils.h
- tests/rptest/tests/audit_log_test.py
Add two new cluster config options:
* `audit_exclude_topics`
* `audit_exclude_principals`
This will exclude those topics and principals from being audited. The exception would be, irt exclude_topics, that admin api endpoints that are touching topics would still report in the audit log in management events.
Fixes: #15029 
* none
> Add support for excluding topics and principals in auditing

- src/v/archival/ntp_archiver_service.cc
- src/v/archival/tests/archival_metadata_stm_gtest.cc
- src/v/archival/tests/archival_metadata_stm_test.cc
- src/v/archival/tests/ntp_archiver_test.cc
- src/v/cloud_storage/partition_manifest.cc
- src/v/cloud_storage/partition_manifest.h
- src/v/cluster/archival_metadata_stm.cc
- src/v/cluster/archival_metadata_stm.h
- src/v/cluster/partition.h
- src/v/cluster/rm_stm.h
The highest producer ID seen at the time of uploading a segment is now
included as a part of the partition manifest. This will be used during recovery to
determine the previous highest used producer ID across all uploaded data
Related https://github.com/redpanda-data/redpanda/pull/15054
Fixes https://github.com/redpanda-data/redpanda/issues/9554
* none
> archival: add highest_producer_id to manifest

- src/v/kafka/protocol/add_offsets_to_txn.h
- src/v/kafka/protocol/end_txn.h
- src/v/kafka/server/handlers/txn_offset_commit.cc
- src/v/kafka/server/server.cc
This PR adds audit logging and associated checks to the transactions API. Follows #14969 
Fixes #15051 
* none
> Audit logging for transaction API 

- src/v/compression/internal/lz4_frame_compressor.cc
Our lz4 frame compressor needs to take a lot of care to avoid monolithic allocations which aren't friendly to seastar memory allocator. To facilitate this the lz4 library provides a helpful method to compute the worst case compressed output size for a given input size, `LZ4F_compressBound`.
Before this change, in a very rare scenario, our code throws the following exception: `lz4f_compressupdate
error:ERROR_dstMaxSize_tooSmall`.
In hindsight, the bug is obvious if you look at the follow code excerpt:
```cpp
// Compress an input chunk and advance cursor.
...
// Compute the worst case compressed output size for the next chunk.
input_chunk_size = std::min(input_sz - input_cursor, max_input_chunk_size);
size_t next_output_size = LZ4F_compressBound(input_chunk_size, &prefs);
// Allocate new …
```
> compression: correctly compute the output buffer size for lz4

- src/v/kafka/protocol/add_partitions_to_txn.h
- src/v/kafka/server/handlers/txn_offset_commit.cc
- src/v/kafka/server/server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14969 
Closes https://github.com/redpanda-data/redpanda/issues/15048
> [v23.1.x] Transactions API Authorization

- src/v/kafka/sasl_probe.h
Use the new aggregate_metrics interface to support changing
aggregate_metrics at runtime.
* none
> sasl: Make metrics respect aggregate_metrics.needs_restart=no

- src/v/cluster/cloud_metadata/cluster_manifest.cc
- src/v/cluster/cloud_metadata/cluster_manifest.h
- src/v/cluster/cloud_metadata/manifest_downloads.cc
- src/v/cluster/cloud_metadata/offsets_upload_router.h
- src/v/cluster/cloud_metadata/offsets_upload_rpc_types.h
- src/v/cluster/cloud_metadata/offsets_uploader.cc
- src/v/cluster/cloud_metadata/tests/cluster_manifest_test.cc
- src/v/cluster/cloud_metadata/tests/offsets_recovery_test.cc
- src/v/cluster/cloud_metadata/uploader.cc
- src/v/cluster/cloud_metadata/uploader.h
- src/v/cluster/controller.cc
- src/v/cluster/controller.h
- src/v/redpanda/application.cc
Plugs the cluster offsets uploader into the metadata uploader that lives alongside the controller leader. The resulting uploaded paths are added to the manifest. As with other metadata, stale (not referenced by the current manifest) offset snapshot files are cleaned up.
* none
> Plug cluster offsets snapshot uploader into metadata uploader

- tests/rptest/tests/random_node_operations_test.py
Added a topic with fast partition movements enabled to `RandomNodeOperationsTest`
- none
> Added fast partition movements to random node operations test

- src/v/kafka/protocol/add_partitions_to_txn.h
- src/v/kafka/server/handlers/txn_offset_commit.cc
- src/v/kafka/server/server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14969 
Closes https://github.com/redpanda-data/redpanda/issues/15047
> [v23.2.x] Transactions API Authorization

- tests/rptest/services/kafka_cli_consumer.py
Added logging of raw cli consumer output as it may be very helpful to debug test issues.
- none
> tests: log output of cli consumer

- tests/rptest/tests/cluster_config_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14581
Fixes #14999
> [v23.2.x] tests/cluster_config_test: _check_value_everywhere retry and better error message

- .github/workflows/build-redpanda.yml
> build: trigger github action build on "ready for review"

- src/v/cluster/health_manager.cc
- src/v/config/configuration.cc
- src/v/config/configuration.h
- src/v/config/validators.cc
- src/v/kafka/server/handlers/produce.cc
- src/v/model/namespace.h
- src/v/pandaproxy/schema_registry/CMakeLists.txt
- src/v/pandaproxy/schema_registry/api.cc
- src/v/pandaproxy/schema_registry/api.h
- src/v/pandaproxy/schema_registry/service.cc
- src/v/pandaproxy/schema_registry/service.h
- src/v/redpanda/admin/server.cc
- src/v/redpanda/application.cc
- src/v/security/audit/audit_log_manager.cc
- src/v/security/audit/audit_log_manager.h
- src/v/security/audit/schemas/tests/ocsf_schemas_test.cc
- src/v/security/audit/schemas/utils.cc
- src/v/security/audit/schemas/utils.h
- src/v/security/audit/tests/audit_log_test.cc
- src/v/security/audit/types.h
- tests/rptest/services/redpanda.py
- tests/rptest/tests/audit_log_test.py
Also fixes bug with excluded ACLs in admin API
Fixes: #15079 
Fixes: #15085
* none
> Add auditing support in schema registry

- src/v/cluster/cloud_metadata/offsets_upload_router.h
- src/v/cluster/cloud_metadata/offsets_uploader.h
- src/v/cluster/cloud_metadata/uploader.cc
- src/v/cluster/cloud_metadata/uploader.h
- src/v/cluster/controller.cc
- src/v/cluster/leader_router.h
- src/v/redpanda/admin/api-doc/shadow_indexing.json
- src/v/redpanda/admin/server.cc
- src/v/redpanda/application.cc
- tests/rptest/services/admin.py
- tests/rptest/tests/cluster_recovery_test.py
- tests/rptest/tests/e2e_shadow_indexing_test.py
Swaps in cluster recovery to the admin endpoints for the `rpk cluster storage recovery` commands instead of topic recovery. Topic recovery is still accessible via a separate endpoint.
It's noteworthy that cluster recovery doesn't support the same arguments advertised by topic recovery. Subsequent work will clean up `rpk`.
Uncovered in CI, this PR also makes shutdown a bit faster when uploading metadata. Previously, ducktape tests would complain about shutdown taking too long when configured to do frequent cluster metadata uploads.
* none
> admin: allow cluster recovery to be used by recovery endpoints

- .github/workflows/build-redpanda.yml
The github build action uses ccache to speed up builds. Before a run a previous snapshot of the cache is restored, and after the run a new replacement snapshot is taken.
This works great, but has the side effect that the cache grows, each time accumulating new bits along side old bits. A fresh build for example might be around 190M of cache use, but I see that we are now saving cache snapshots >1G.
So instead we'll trim down before taking the snapshot. Generally we may want to periodically check-in and see if the cache size limit is large enough for a fresh build.
* none
> build: trim cache to avoid accumulation

- tests/docker/ducktape-deps/kgo-verifier
kgo-verifier diff: https://github.com/redpanda-data/kgo-verifier/compare/8ea3942c5bfb66f83009858010bb9ddad11dd409...0ce461399d3336cc825ff28a780582bab7bdefe4
* none
> tests: upgrade kgo with assert for kafka offset monotonicity

- src/v/cluster/cloud_metadata/offsets_recovery_manager.h
- src/v/cluster/cloud_metadata/offsets_recovery_rpc_types.h
Follow-up on a review comment.
* none
> cloud_metadata: add virtual destructor to offsets_recovery_manager

- src/v/security/audit/schemas/schemas.h
- src/v/security/audit/schemas/tests/ocsf_schemas_test.cc
- src/v/security/audit/schemas/types.h
- src/v/security/audit/schemas/utils.cc
Added node id from node config to OCSF messages in the product field.
Fixes: #15229
* none
> audit: Add node id to messages

- src/v/cloud_storage_clients/s3_client.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15220
Fixes: https://github.com/redpanda-data/redpanda/issues/15238,
> [v23.2.x] cloud_storage_clients: handle both gcp and s3 request ids

- src/v/kafka/server/handlers/create_partitions.cc
- tests/rptest/tests/partition_reassignments_test.py
CreatePartitionsAPI responds with REASSIGNMENT_IN_PROGRESS when servicing a request during an active partition reassignment.
Fixes: https://github.com/redpanda-data/redpanda/issues/8880
* CreatePartitionsAPI responds with REASSIGNMENT_IN_PROGRESS when servicing a request for a topic that also has an active partition reassignment.
> Check inprogress reasignments create partitions api

- src/v/kafka/server/handlers/create_partitions.cc
- tests/rptest/tests/partition_reassignments_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14270
Fixes: https://github.com/redpanda-data/redpanda/issues/15275,
> [v23.1.x] Check inprogress reasignments create partitions api

- src/go/rpk/pkg/adminapi/api_partition.go
- src/go/rpk/pkg/cli/cluster/partitions/move.go
- src/go/rpk/pkg/cli/cluster/partitions/move_test.go
- src/go/rpk/pkg/cli/cluster/partitions/partitions.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/13684
Fixes: https://github.com/redpanda-data/redpanda/issues/15235,
> [v23.2.x] rpk: add 'partitions move' command

- src/v/kafka/server/handlers/create_partitions.cc
- tests/rptest/tests/partition_reassignments_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14270
Fixes: https://github.com/redpanda-data/redpanda/issues/15272,
> [v23.2.x] Check inprogress reasignments create partitions api

- tests/rptest/clients/python_librdkafka.py
- tests/rptest/clients/rpk.py
- tests/rptest/services/keycloak.py
- tests/rptest/services/redpanda.py
- tests/rptest/tests/redpanda_oauth_test.py
This commit enables support for HTTPS in keycloak dev mode.
Fixes #15020 
TODO:
- ~~As written, anyway. Keycloak likes port 8443 for HTTPS traffic.~~
- Not really, as it turns out.
* none
> Turn on TLS in Keycloak

- tests/rptest/scale_tests/tiered_storage_single_partition_test.py
The delta expected by the changed test is incremented by ~1 per upload round to accommodate for the new command added per upload round to update the highest producer ID.
The assert on delta is now done with respect to both min and max values.
FIXES #15109 
* none
> ducktape/cloud_storage: Adjust delta expectation

- src/v/redpanda/admin_server.cc
- src/v/security/scram_algorithm.cc
- src/v/security/scram_algorithm.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15253 
Fixes #15280
> [v23.1.x] Validation and url_decode for SCRAM usernames

- src/v/pandaproxy/util.h
We want to return the consumed unit after we successfully
acquire the units.
* none
> pp/oneshot: release consumed value

- src/v/cluster/cloud_metadata/cluster_recovery_backend.cc
- src/v/cluster/cloud_metadata/tests/cluster_metadata_utils.h
- src/v/cluster/cloud_metadata/tests/cluster_recovery_backend_test.cc
- src/v/cluster/cluster_recovery_reconciler.cc
- src/v/cluster/topics_frontend.cc
We previously relied on downloading the topic manifest to be able to restore a topic. This meant that for cluster recovery, there would be a window between uploading the controller snapshot and uploading the first topic manifest where a topic would cause cluster recovery to fail.
This commit remediates this by building the remote_topic_properties with content from the restored constroller snapshot. A corresponding change is made to the topics_frontend such that when remote_topic_properties is provided, we skip the step to attempt downloading the topic_manifest, instead passing through the provided remote_topic_properties.
* none
> cloud_metadata: recover remote topic properties from controller snapshot

- src/v/cluster/migrations/tx_manager_migrator.cc
- src/v/cluster/migrations/tx_manager_migrator.h
- src/v/redpanda/admin/api-doc/recovery.json
- src/v/redpanda/admin/recovery.cc
- src/v/redpanda/application.cc
- tests/rptest/services/admin.py
- tests/rptest/tests/tx_coordinator_migration_test.py
Fixed stop condition in `cluster::tx_manager_migrator`. Previously a migration was finished before deleting a temporary tx manager topic. Additionally implemented a migration status API returning information if a migration is required. The status API validates if a migration is required or if previous migration failed in the middle.
Fixes: #15301 
- none
> Fixes and improvements in `tx_manager_migrator`

- src/v/raft/consensus.cc
- src/v/ssx/future-util.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/14794
> [v23.1.x] Fix for `leader_ack` consistency level (do not advance last visible offset beyond majority replicated)

- src/v/cluster/cloud_metadata/cluster_recovery_backend.cc
- src/v/cluster/cloud_metadata/cluster_recovery_backend.h
- src/v/cluster/cloud_metadata/tests/cluster_metadata_utils.h
- src/v/cluster/cloud_metadata/tests/cluster_recovery_backend_test.cc
- src/v/cluster/cloud_metadata/tests/offsets_recovery_test.cc
- src/v/cluster/cluster_recovery_manager.cc
- src/v/cluster/cluster_recovery_reconciler.cc
This includes some miscellaneous, mostly minor improvements to cluster recovery:
- Added some debug logging to the `cluster_recovery_manager`
- Catch `abort_requested_exception` from abort source to signal the end of a term
- Use the per-term abort source throughout the recovery backend
- Added missing state change after recovering the consumer offsets topic
- Made ordering of the recovery stages a bit stricter across leadership changes
* none
> Miscellaneous improvements to cluster recovery

- tests/rptest/scale_tests/many_partitions_test.py
> many_partitions_test: Fix a few typos in comments

- tests/rptest/scale_tests/cloud_storage_compaction_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14031
Fixes: https://github.com/redpanda-data/redpanda/issues/15388,
> [v23.2.x] rptest: Ignore transient log error message

- src/v/redpanda/admin/transform.cc
Fixes an RPK command hint in the error message (missing an `set` verb).
* none
> admin/transform: fix rpk command hint

- src/v/kafka/client/broker.cc
If an exception is thrown from `do_authenticate`, then stop the broker before it goes out of scope so that resources such as the connection can be cleaned up.
Here's an example of a failure in debug mode:
```
/include/seastar/core/iostream.hh:405: seastar::output_stream<char>::~output_stream() [CharType = char]: Assertion `!_in_batch && "Was this stream properly closed?"' failed.
```
Fixes #15118
* kafka/client: More robust error handling during initial connection
> kafka/client: Stop the broker if `do_authenticate` failed

- tests/rptest/scale_tests/many_partitions_test.py
We have an advertised "hard" partition limit of 50k.
That shouldn't stop us from testing with more than that though. Remove
this limitation in the many partitions test.
- none
> tests: Remove hard partition limit in the MPT

- src/v/redpanda/admin/server.cc
Only had escape hatch for audit authz.  Made a common function and added to audit auth.
* none
> audit: Add escape hatch for audit authn

- src/v/cluster/partition_balancer_backend.cc
- src/v/cluster/partition_balancer_planner.cc
- src/v/cluster/partition_balancer_types.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15413
Fixes: https://github.com/redpanda-data/redpanda/issues/15418,
> [v23.2.x] c/partition_balancer: handle members_table update during planning

- src/v/resource_mgmt/storage.cc
- src/v/resource_mgmt/storage.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15026
Fixes: https://github.com/redpanda-data/redpanda/issues/15358,
> [v23.2.x] storage: sort reclaimable partitions by size

- src/v/kafka/client/client.cc
- src/v/kafka/client/client_fetch_batch_reader.cc
- src/v/kafka/client/configuration.cc
- src/v/kafka/client/configuration.h
- src/v/kafka/client/consumer.cc
- src/v/kafka/client/fetcher.cc
- src/v/kafka/client/fetcher.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15438 
Closes #15588
> [v23.1.x] kafka/client: Configuration for consume min and max bytes

- src/v/kafka/client/client.cc
- src/v/kafka/client/client_fetch_batch_reader.cc
- src/v/kafka/client/configuration.cc
- src/v/kafka/client/configuration.h
- src/v/kafka/client/consumer.cc
- src/v/kafka/client/fetcher.cc
- src/v/kafka/client/fetcher.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15438 
Closes #15587
> [v23.2.x] kafka/client: Configuration for consume min and max bytes

- tests/docker/Dockerfile
- tests/docker/ducktape-deps/librdkafka
- tests/setup.py
Reimplementation of https://github.com/redpanda-data/redpanda/pull/14790
For SASL reauth support
The prebuilt confluent-kafka wheels do not include GSSAPI support, so confluent-kafka is now built from source explicitly when the ducktape container is built.
Signed-off-by: Oren Leiman <oren.leiman@redpanda.com>
(cherry picked from commit e09c68ad40a23a9f15178615cbd053a2cde288d4)
There were conflicts in the `tests/setup.py`
* none
> [v23.1.x] ducktape: Update librdkafka and confluent-kafka to v2.2.0

- src/v/raft/persisted_stm.cc
This is particularly relevant for kvstore-backed stms. They use ntp without revision as the kvstore key, therefore if there is leftover state from the previous partition instance (e.g. topic was re-created, and we relied on orphan log dir deletion to remove the previous instance), it could erroneously get used for the new partition instance. Delete it before the first start.
* none
> r/persisted_stm: remove persistent state from previous incarnations

- src/v/cluster/producer_state.cc
- src/v/cluster/rm_stm.cc
- src/v/model/record.cc
- src/v/model/record.h
- src/v/storage/compaction_reducers.cc
To debug compaction related issues.
* none
> compaction: miscellaneous logging improvements

- src/v/cluster/cloud_metadata/tests/offsets_recovery_test.cc
- src/v/kafka/server/group_manager.cc
This updates the behavior of consumer offsets recovery to skip over restoring groups: when the group already exists: this is meant to act as a safeguard in case applications have already started up again and begun consuming -- in that case, we should avoid overwriting offsets
* none
> cluster_recovery: tweaks consumer offsets recovery to ignore groups

- tests/rptest/tests/consumer_group_recovery_test.py
A workload is run after recovery to assert that consumers joining the same group which consumed from the topic pre-restore will read from the correct last committed offset per partition, as a result of __consumer_offsets restore.
* none
> Add workload after consumer offsets restore

- src/v/cluster/partition.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15680
Fixes: https://github.com/redpanda-data/redpanda/issues/15685,
> [v23.2.x] c/partition: fix acquiring _archiver_reset_mutex

- .github/CODEOWNERS
> codeowners: update consistency tests codeowner

- .github/CODEOWNERS
Backport of PR https://github.com/redpanda-data/redpanda/pull/15698
> [v23.1.x] codeowners: update consistency tests codeowner

- .github/CODEOWNERS
Backport of PR https://github.com/redpanda-data/redpanda/pull/15698
> [v23.2.x] codeowners: update consistency tests codeowner

- src/v/kafka/server/group_manager.cc
We previously accessed the iterator, when we really should be using the pointer to the partition.
* none
> kafka: fix holding of attached_partition

- src/v/cloud_storage/remote_segment.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15697
Fixes: https://github.com/redpanda-data/redpanda/issues/15709,
> [v23.3.x] cloud_storage: hold gate in hydration

- src/v/raft/consensus.cc
- src/v/storage/offset_translator_state.cc
- src/v/storage/segment_appender.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15193
> [v23.1.x] format exception fixes

- src/v/cluster/persisted_stm.cc
- src/v/cluster/persisted_stm.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15441
Backport of PR https://github.com/redpanda-data/redpanda/pull/15668 
Fixes https://github.com/redpanda-data/redpanda/issues/15671
> [v23.2.x] r/persisted_stm: remove persistent state from previous incarnations

- src/v/cluster/cloud_metadata/key_utils.cc
- src/v/cluster/cloud_metadata/key_utils.h
- src/v/cluster/cloud_metadata/offsets_snapshot.h
- src/v/cluster/cloud_metadata/offsets_uploader.cc
- src/v/cluster/cloud_metadata/tests/offsets_recovery_test.cc
- src/v/config/configuration.cc
- src/v/config/configuration.h
- src/v/kafka/server/group_manager.cc
- src/v/kafka/server/group_manager.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15748
Fixes: https://github.com/redpanda-data/redpanda/issues/15762,
> [v23.3.x] cloud_metadata: upload consumer groups in batches

- tests/rp_cloud_cleanup.py
- tests/rptest/services/provider_clients/ec2_client.py
- tests/rptest/services/provider_clients/gcp_client.py
- tests/rptest/services/provider_clients/rpcloud_client.py
Manual bucket cleaning
Fixes: https://github.com/redpanda-data/devprod/issues/966
* none
> ci: Add bucket cleanup scripts

- src/v/kafka/client/topic_cache.cc
- src/v/kafka/client/topic_cache.h
- src/v/kafka/protocol/schemata/generator.py
- src/v/kafka/server/handlers/metadata.cc
- src/v/kafka/server/tests/delete_topics_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15751
> [v23.3.x] k/h/metadata: use fragmented vec for topic metadata

- src/v/cluster/controller_backend.cc
- src/v/cluster/members_manager.cc
- src/v/raft/consensus.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15738
> [v23.3.x] c/members_member: don't ignore update_broker_client future

- tests/rptest/archival/s3_client.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15754
> [v23.3.x] rptest: clean up cluster metadata in CDT

- src/v/bytes/iobuf.h
- src/v/bytes/tests/iobuf_tests.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15778
> [v23.2.x] Fix 128K iobuf zero-copy

- src/v/cloud_storage_clients/client_pool.cc
- src/v/cloud_storage_clients/client_pool.h
- src/v/cloud_storage_clients/tests/CMakeLists.txt
- src/v/cloud_storage_clients/tests/client_pool_mt_test.cc
- src/v/cloud_storage_clients/tests/client_pool_test.cc
- src/v/cloud_storage_clients/tests/s3_client_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15681
> [v23.3.x] cloud_storage_clients: stricter but simpler invariants for the pool

- src/v/config/configuration.cc
- src/v/config/configuration.h
- src/v/redpanda/application.cc
- src/v/resource_mgmt/storage.cc
- src/v/resource_mgmt/storage.h
- src/v/storage/disk_log_impl.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15761
Fixes: https://github.com/redpanda-data/redpanda/issues/15788,
> [v23.3.x] Overrides for space_management_enable and retention_local_strict

- src/v/bytes/iobuf.h
- src/v/bytes/tests/iobuf_tests.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15778
> [v23.3.x] Fix 128K iobuf zero-copy

- src/v/config/configuration.cc
- src/v/config/configuration.h
- src/v/redpanda/application.cc
- src/v/resource_mgmt/storage.cc
- src/v/resource_mgmt/storage.h
- src/v/storage/disk_log_impl.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15761
Fixes: https://github.com/redpanda-data/redpanda/issues/15786,
> [v23.2.x] Overrides for space_management_enable and retention_local_strict

- src/v/archival/tests/archival_metadata_stm_gtest.cc
- src/v/cluster/archival_metadata_stm.cc
- src/v/cluster/archival_metadata_stm.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15677
> [v23.3.x] c/archival_stm: do not reset _last_replicate on timeout

- src/go/rpk/pkg/cli/debug/bundle/bundle_k8s_linux.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/15412
> [v23.2.x] rpk: gather k8s bundle logs of redpanda container

- src/v/archival/adjacent_segment_merger.cc
- src/v/archival/tests/segment_reupload_test.cc
- src/v/archival/types.cc
- src/v/archival/types.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15442
> [v23.2.x] archival: Disable cross term merging of adjacent segments

- src/v/cloud_storage/tests/topic_manifest_test.cc
- src/v/cloud_storage/topic_manifest.cc
- src/v/cluster/types.h
- src/v/tristate.h
- tests/rptest/tests/retention_policy_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14355
Fixes: https://github.com/redpanda-data/redpanda/issues/15688,
> [v23.2.x] fix topic_manifest.json deserialization for disabled tristate 

- tests/rptest/tests/controller_availability_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15730
> [v23.3.x] rptest: fix an always true assertion

- src/v/cluster/tests/partition_balancer_planner_fixture.h
- src/v/config/configuration.cc
- src/v/model/namespace.h
- tests/rptest/tests/audit_log_test.py
Renamed audit log topic from `__audit_log` to `_redpanda.audit_log`
* none
> audit: Renamed audit log topic

- src/v/cluster/controller.cc
- src/v/cluster/topics_frontend.cc
- src/v/cluster/topics_frontend.h
- src/v/config/configuration.cc
- src/v/config/configuration.h
- src/v/kafka/server/handlers/alter_configs.cc
- src/v/kafka/server/handlers/configs/config_utils.h
- src/v/kafka/server/handlers/create_topics.cc
- src/v/kafka/server/handlers/incremental_alter_configs.cc
- src/v/kafka/server/handlers/topics/validators.h
- src/v/kafka/server/tests/config_utils_test.cc
- tests/rptest/tests/audit_log_test.py
- tests/rptest/tests/cluster_config_test.py
- tests/rptest/tests/internal_topic_protection_test.py
- tests/rptest/tests/replication_factor_change_test.py
- tests/rptest/tests/topic_creation_test.py
- tests/rptest/utils/schema_registry_utils.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15777
> [v23.3.x] Support for clamping replication factor

- src/v/cluster/tests/partition_balancer_planner_fixture.h
- src/v/config/configuration.cc
- src/v/model/namespace.h
- tests/rptest/tests/audit_log_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15817
> [v23.3.x] audit: Renamed audit log topic

- src/v/archival/upload_housekeeping_service.h
> archival: remove outdated codedoc

- src/v/cluster/archival_metadata_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15804
> [v23.3.x] c/archival_stm: downgrade timeout log to warn

- .github/workflows/transform-sdk-release.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/15836
> [v23.3.x] gha: remove invalid permission

- src/v/cluster/partition_probe.cc
- src/v/cluster/partition_probe.h
- src/v/kafka/server/handlers/fetch.cc
- tests/rptest/services/redpanda.py
- tests/rptest/tests/follower_fetching_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15799
Fixes: https://github.com/redpanda-data/redpanda/issues/15828,
> [v23.3.x] Added metric representing bytes read from follower

- tests/rptest/e2e_tests/workloads/flink_table_transactions_basic.py
Basic workloads and test that can be used in parallel to simulate data transformations using Flink APIs
* none
> e2e: Basic producer and consumer using Table API

- src/v/config/configuration.cc
- tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15813
> [v23.3.x] archival: disable scrubber by default

- src/v/config/node_config.cc
- src/v/config/node_config.h
- src/v/redpanda/admin/api-doc/config.def.json
- src/v/redpanda/admin/api-doc/config.json
- src/v/redpanda/admin/server.cc
- src/v/redpanda/admin/server.h
- tests/rptest/services/admin.py
- tests/rptest/tests/log_level_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15798 
Fixes #15856
> [v23.3.x] verbose_logging_timeout_max

- src/v/cluster/cloud_metadata/cluster_recovery_backend.cc
- src/v/cluster/cloud_metadata/uploader.cc
- src/v/cluster/cluster_recovery_manager.cc
- src/v/cluster/controller.cc
- src/v/cluster/controller.h
- src/v/redpanda/admin/server.cc
- tests/rptest/tests/recovery_mode_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15844
> [v23.3.x] Disable cloud metadata upload and cluster restore in recovery mode

- src/go/rpk/pkg/cli/topic/create.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/15837
> [v23.3.x] rpk: Print create topics error message if available

- src/v/redpanda/application.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15835
> [v23.3.x] node_config: Disallow empty rack

- tests/rptest/services/redpanda.py
Changed in https://github.com/redpanda-data/redpanda/pull/13496
* none
> rptest: allow the new version of xfs/ext4 fs error msg

- tests/docker/ducktape-deps/kgo-verifier
> t/kgo: upgrade kgo to do a full run after /last_pass

- src/v/cluster/scheduling/leader_balancer_constraints.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15862
> [v23.1.x] c/s/leader_balancer: prevent oversized alloc

- src/v/cluster/scheduling/leader_balancer_constraints.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15862
> [v23.2.x] c/s/leader_balancer: prevent oversized alloc

- .github/workflows/promote.yml
ref redpanda-data/devprod#973
* none
> gh/workflow: add build message in promote trigger

- src/v/cluster/scheduling/leader_balancer_constraints.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15862
> [v23.3.x] c/s/leader_balancer: prevent oversized alloc

- .github/workflows/promote.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/15870
> [v23.1.x] gh/workflow: add build message in promote trigger

- .github/workflows/promote.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/15870
> [v23.3.x] gh/workflow: add build message in promote trigger

- .github/workflows/transform-sdk-release.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/15882
> [v23.3.x] gha: s/git.ref_name/github.ref_name

- README.md
Maybe this was already reported by someone else, just caught my eye when I was reading about this project.
* none
> fix grammar in README

- src/v/redpanda/application.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15835
> [v23.1.x] node_config: Disallow empty rack

- src/v/kafka/server/handlers/fetch.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15883
> [v23.2.x] kafka: Disable FF if rack awareness is disabled

- src/v/kafka/server/handlers/fetch.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15883
> [v23.3.x] kafka: Disable FF if rack awareness is disabled

- tests/rptest/scale_tests/audit_log_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15739
> [v23.3.x] Increase audit buffer sizes for audit scale test

- src/v/kafka/protocol/offset_fetch.h
- src/v/kafka/protocol/schemata/generator.py
- src/v/kafka/server/group.cc
- src/v/kafka/server/server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15918
Fixes: https://github.com/redpanda-data/redpanda/issues/15928,
> [v23.3.x] kafka/protocol: use frag vec for offset fetch

- src/v/kafka/protocol/offset_fetch.h
- src/v/kafka/protocol/schemata/generator.py
- src/v/kafka/server/group.cc
- src/v/kafka/server/server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15918
Fixes: https://github.com/redpanda-data/redpanda/issues/15925,
> [v23.2.x] kafka/protocol: use frag vec for offset fetch

- src/go/rpk/pkg/cli/transform/template/rust/main.rustsrc
- src/transform-sdk/rust/core-sys/src/lib.rs
- src/transform-sdk/rust/core-types/src/lib.rs
- src/transform-sdk/rust/examples/identity.rs
- src/transform-sdk/rust/examples/jaq/src/main.rs
- src/transform-sdk/rust/examples/json2avro/src/main.rs
- src/transform-sdk/rust/src/lib.rs
Backport of PR https://github.com/redpanda-data/redpanda/pull/15923
> [v23.3.x] transform-sdk/rust: introduce RecordWriter

- src/go/rpk/pkg/cli/transform/template/rust_template.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/15934
> [v23.3.x] rpk/transform/init: fix cargo.toml template

- tests/rptest/scale_tests/audit_log_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15820
> [v23.3.x] Skip assertion in audit log tests if results beat the baseline

- src/go/rpk/pkg/cli/transform/deploy.go
- tests/rptest/clients/rpk.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15932
> [v23.3.x] rpk/transform/deploy: introduce --file flag

- tests/rptest/archival/s3_client.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15755
> [v23.3.x] rptest: log error on failure to delete bucket

- src/v/net/connection.cc
- src/v/net/connection.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15931
> [v23.3.x] net: Cache value of local address

- tests/rptest/tests/internal_topic_protection_test.py
Added logic to wait for _schemas topic to become
ready before checking replications.
Fixes: #15944
* none
> dt: Fixed flaky schemas test

- tests/docker/ducktape-deps/java-dev-tools
- tests/docker/ducktape-deps/keycloak
openjdk: 11 -> 17
keycloak: 21 -> 23
(Maybe) Fixes #15304 on the basis that we were using an older keycloak version with a deprecated (from keycloak's standpoint) java version. By upgrading Keycloak to latest greatest and bumping openjdk to the most recent LTS version offered on Ubuntu 22.0.4, we may avoid these obscure Java errors altogether.
* none
> dt-deps: Bump openjdk and Keycloak

- tests/rptest/tests/internal_topic_protection_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15962
Fixes: https://github.com/redpanda-data/redpanda/issues/15969,
> [v23.3.x] dt: Fixed flaky schemas test

- src/v/config/configuration.cc
- src/v/config/configuration.h
- src/v/redpanda/application.cc
- src/v/transform/rpc/client.cc
- src/v/transform/rpc/client.h
- src/v/transform/rpc/deps.cc
- src/v/transform/rpc/deps.h
- src/v/transform/rpc/tests/transform_rpc_test.cc
- src/v/wasm/api.h
- src/v/wasm/tests/wasm_fixture.cc
- src/v/wasm/tests/wasm_transform_bench.cc
- src/v/wasm/wasmtime.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15967
> [v23.3.x] wasm: add runtime and max binary configs

- src/v/archival/tests/ntp_archiver_test.cc
- src/v/raft/consensus.cc
- src/v/raft/offset_translator.cc
- src/v/raft/offset_translator.h
- src/v/raft/tests/offset_translator_tests.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15919
> [v23.1.x] r/offset_translator: remove unsafe bootstrap code

- src/v/archival/tests/ntp_archiver_test.cc
- src/v/raft/consensus.cc
- src/v/raft/offset_translator.cc
- src/v/raft/offset_translator.h
- src/v/raft/tests/offset_translator_tests.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15919
> [v23.2.x] r/offset_translator: remove unsafe bootstrap code

- tests/rptest/utils/si_utils.py
include a message in the assertion
Related to https://github.com/redpanda-data/redpanda/issues/15793
* none
> tests/si_utils: assert message for verify_file_layout()

- tests/rptest/tests/topic_recovery_test.py
Today the test waits for {the delta between cloud and local storage to be steady for some time and under some size}, to denote quiesced state.
This meant that that even if we were no longer uploading to cloud, if local storage were to be truncated continually, the test would not consider the state quiesced, and then fail.
Instead it now waits for {the size in cloud to be steady for some time and the delta between cloud and local storage to be under some size}.
Fixes #13406
* none
> topic_recovery_test: adjust wait condition for finished uploads

- src/v/cluster/partition_balancer_planner.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15982
> [v23.3.x] c/partition_balancer: use full partition move when disk is full

- src/v/cluster/feature_manager.cc
- src/v/cluster/metrics_reporter.cc
- src/v/cluster/metrics_reporter.h
- src/v/config/validators.cc
- src/v/config/validators.h
- tests/rptest/tests/metrics_reporter_test.py
- tests/rptest/tests/redpanda_oauth_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15986
Fixes: https://github.com/redpanda-data/core-internal/issues/845
> [v23.3.x] securit/:OIDC: Enable licence check and telemetry

- src/go/rpk/pkg/cli/transform/deploy.go
Support deploying from HTTP source.
* `rpk transform deploy --file` now supports `https://` URLs
> rpk/transform/deploy: support http deploys

- tools/cmake_test.py
This is the first step in recording microbenchmark results from CI runs. Save results in vbuild/microbench/bench.json.
* Record result of running microbenchmarks in a file using JSON format
> test: Save microbenchmark results in JSON format

- src/v/archival/upload_housekeeping_service.cc
This leads to `-nan` being reported to seastar metrics engine and prometheus. However, prometheus text metric collector bails out leading to missing metrics.
Fixes #16054
* none
> archival: avoid division by 0 when computing slow down rate

- src/v/archival/upload_housekeeping_service.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16071
Fixes: https://github.com/redpanda-data/redpanda/issues/16072,
> [v23.3.x] archival: avoid division by 0 when computing slow down rate

- src/v/cloud_storage/remote_probe.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16070
> [v23.3.x] metrics: fix controller snapshot upload metrics

- src/v/raft/group_manager.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16068
> [v23.2.x] r/group_manager: protect against race with set_ready()

- src/go/rpk/pkg/cli/transform/deploy.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/16050
> [v23.3.x] rpk/transform/deploy: support http deploys

- tests/rptest/tests/audit_log_test.py
- So it can be easily observed how many records matching a predicate were observed on the audit log in the case the test fails
Linking to issue: https://github.com/redpanda-data/redpanda/issues/14942
* none
> rptest: Additional logging audit_log_test infra

- tests/rptest/tests/delete_records_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16078
> [v23.2.x] Fix for CI Failure (Failed to make list_offsets request, unknown broker) in DeleteRecordsTest.test_delete_records_segment_deletion

- src/v/archival/ntp_archiver_service.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14599
Fixes: https://github.com/redpanda-data/redpanda/issues/16110,
> [v23.3.x] archival: Start housekeeping jobs after STM sync

- tests/rptest/tests/audit_log_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16097
> [v23.3.x] rptest: Additional logging audit_log_test infra

- tests/docker/ducktape-deps/flink
Backport of PR https://github.com/redpanda-data/redpanda/pull/16135 
Fixes: #16150
> [v23.3.x] ci: Fix flink install on ARM64

- src/v/archival/ntp_archiver_service.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16163
> [v23.3.x] archival: Delete replaced segments during spillover GC

- src/v/syschecks/syschecks.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13496
> [v23.2.x] Ext4 detection

- src/v/rpc/netbuf.cc
- src/v/rpc/transport.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16156
> [v23.2.x] rpc: fix correlation_id overflow

- src/v/rpc/netbuf.cc
- src/v/rpc/transport.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16156
> [v23.3.x] rpc: fix correlation_id overflow

- src/v/cloud_storage/partition_manifest.cc
- src/v/cloud_storage/partition_manifest.h
- src/v/cluster/archival_metadata_stm.cc
- src/v/cluster/archival_metadata_stm.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16160
> [v23.3.x] cloud_storage: use fragvec to hold replaced segments

- src/v/resource_mgmt/memory_sampling.cc
- src/v/resource_mgmt/memory_sampling.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15616
Fixes: https://github.com/redpanda-data/redpanda/issues/16101,
> [v23.3.x] Add at: in Top-N alloc site output

- src/v/kafka/server/replicated_partition.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16146
> [v23.2.x] k/replicated_partition: fixed fetch offset validation for follower fetching

- src/v/redpanda/application.cc
- src/v/redpanda/application.h
- src/v/resource_mgmt/scheduling_groups_probe.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16154
> [v23.3.x] scheduling_groups: report cpu usage for all cores

- src/go/rpk/pkg/cli/transform/template/rust/main.rustsrc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16180
> [v23.3.x] rpk/transform/init: fix rust template

- tests/rptest/redpanda_cloud_tests/high_throughput_test.py
- tests/rptest/redpanda_cloud_tests/omb_validation_test.py
- tests/rptest/services/redpanda_cloud.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16108
> [v23.3.x] Rename max_client_count to max_connection_count

- .github/workflows/promote.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/15870
> [v23.2.x] gh/workflow: add build message in promote trigger

- tests/rptest/tests/tiered_storage_model_test.py
see https://github.com/redpanda-data/redpanda/issues/16208
* none
> tests/tiered_storage_model_test: temp ok_to_fail

- tests/rptest/tests/tiered_storage_model_test.py
> tests/rptest/tests/tiered_storage_model_test: ignore

- src/v/raft/consensus.cc
- src/v/raft/state_machine.cc
- src/v/raft/state_machine.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/14929
Fixes: https://github.com/redpanda-data/redpanda/issues/14982,
> [v23.1.x] Fixed handling Raft snapshot

- tests/docker/ducktape-deps/flink
> lint: fix linter error

- src/v/redpanda/admin_server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16233
> [v23.2.x] admin api: skip partition info in /brokers end point

- src/v/redpanda/admin/server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16233
> [v23.3.x] admin api: skip partition info in /brokers end point

- src/v/cluster/health_monitor_backend.cc
- src/v/cluster/health_monitor_types.cc
- src/v/cluster/health_monitor_types.h
- src/v/cluster/tests/health_monitor_test.cc
- src/v/cluster/tests/partition_balancer_simulator_test.cc
- src/v/cluster/tests/randoms.h
- src/v/cluster/tests/serialization_rt_test.cc
- src/v/compat/cluster_json.h
- src/v/compat/json.h
- src/v/json/json.h
- src/v/utils/to_string.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16247
> [v23.3.x] Changed the `partition_status` `chunked_fifo` chunk size to `8`

- tests/docker/ducktape-deps/flink
Backport of PR https://github.com/redpanda-data/redpanda/pull/16234
> [v23.3.x] ducktape: fix flink URL 404

- src/go/rpk/pkg/config/params.go
- tests/rptest/clients/rpk.py
- tests/rptest/tests/rpk_acl_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16278
Fixes: https://github.com/redpanda-data/redpanda/issues/16348,
> [v23.2.x] rpk: fix mixed use of backcompat flags with -X

- src/v/archival/probe.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16336
> [v23.3.x] Aggregate partition label in `ntp_level_probe`

- src/v/cluster/partition_manager.cc
- src/v/rpc/rpc_server.cc
- src/v/rpc/transport.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16304
> [v23.3.x] Wrapped logging with `vlog` macro in places that missed it

- tests/rptest/tests/cloud_retention_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16361
Fixes: https://github.com/redpanda-data/redpanda/issues/16373,
> [v23.3.x] rptest: Fix race condition in CloudRetentionTest

- src/v/rpc/netbuf.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16156
> [v23.1.x] rpc: fix correlation_id overflow

- src/v/cluster/rm_stm.cc
- src/v/cluster/rm_stm.h
preparing/prepared was a phase pre-GA transactions ( ~ 1.5y ago). It is extremely unlikely that a transaction was stuck in prepared for this long. It is extremely unlikely that the batches exist in the log for this long. With these assumptions, cleaning up the related code.
logs a warning for debugging if the state machine encounters such a batch.
* none
> rm_stm: remove log_state::prepared

- src/v/kafka/client/produce_partition.h
- src/v/kafka/client/producer.cc
- During one of the audit log tests it was observed that the broker did not shutdown.
- The logs demonstrated that `producer::stop()` had run to completion but `audit_log_manager::audit_client::shutdown()` had not. The only explanation would be the _gate within the `audit_client` holding up shutdown, and that gate is only used on invoke to `client::produce()`. This means data is left in the buffer and `producer::send()` was never called, which resolves outstanding promises.
- The kafka client waits to drain all data before shutdown, it does this by calling `produce_partition::stop()` however this contains a conditional that actually does nothing in the case _in_flight is true. This member variable ensures only one call to `send()` can occur at a time. If `stop()` does not drain the buffer …
> kafka/client: Fix for stall during client shutdown

- src/v/archival/ntp_archiver_service.cc
Avoid throwing and logging on error log level in case if retention fails due to shutdown.
Fixes #16322
* Fix graceful shutdown of the TS archive area retention procedure.
> archival: Graceful shutdown in the spillover retention

- tests/rptest/tests/rpk_tuner_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16353
Fixes: https://github.com/redpanda-data/redpanda/issues/16364,
> [v23.1.x] CDT: fix `rpk tune list` test in GCP.

- tests/rptest/tests/rpk_tuner_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16353
Fixes: https://github.com/redpanda-data/redpanda/issues/16368,
> [v23.2.x] CDT: fix `rpk tune list` test in GCP.

- tests/rptest/tests/e2e_shadow_indexing_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16383
Fixes: https://github.com/redpanda-data/redpanda/issues/16395,
> [v23.3.x] rptest: Add error message to log allow list

- tests/rptest/tests/e2e_shadow_indexing_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16384
Fixes: https://github.com/redpanda-data/redpanda/issues/16397,
> [v23.3.x] rptest: Fix throttling e2e test

- src/go/rpk/pkg/cli/cluster/health.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/16106
Fixes: https://github.com/redpanda-data/redpanda/issues/16362,
> [v23.3.x] rpk: improve --exit-when-healthy in cluster health

- src/go/rpk/pkg/cli/registry/schema/get.go
Adds a flag to print the schema (either AVRO or Protobuf) to the `rpk registry schema get` command.
**AVRO**
```
$ rpk registry schema get --id 3 --print-schema
{
"type": "record",
"name": "sensor_sample",
"fields": [
{
"name": "timestamp",
"type": "long",
"logicalType": "timestamp-millis"
},
{
"name": "value",
"type": "long"
}
]
}
```
**Protobuf**
```
$ rpk registry schema get --id 10 --print-schema 
syntax = "proto3";
package foo.bar;
message Person {
message PhoneNumber {
string number = 1;
.foo.bar.Person.PhoneType type = 2;
}
enum PhoneType {
PHONE_TYPE_UNSPECIFIED = 0;
PHONE_TYPE_MOBILE = 1;
PHONE_TYPE_HOME = 2;
PHONE_TYPE_WORK = 3;
}
string name = 1;
int32 id = 2;
string email = 3;
repeated .foo.bar.Person.PhoneNumber phones = 4;
}
message AddressBook {
repeated .foo.bar.Person …
```
> rpk registry schema get: add flag to print schemas

- src/go/rpk/pkg/cli/transform/build.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/16296
> [v23.3.x] rpk/transform/build: enable SIMD

- src/go/rpk/pkg/cli/registry/schema/get.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/16109
Fixes: https://github.com/redpanda-data/redpanda/issues/16411,
> [v23.3.x] rpk registry schema get: add flag to print schemas

- src/v/io/CMakeLists.txt
- src/v/io/logger.cc
- src/v/io/logger.h
- src/v/io/page.cc
- src/v/io/page.h
- src/v/io/tests/CMakeLists.txt
- src/v/io/tests/common.cc
- src/v/io/tests/common.h
- src/v/io/tests/common_test.cc
- src/v/io/tests/page_test.cc
Some miscellaneous updates and test helpers.
* none
> io: misc updates and test helpers

- src/v/kafka/server/handlers/configs/config_utils.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16399
Fixes: https://github.com/redpanda-data/redpanda/issues/16404,
> [v23.3.x] kafka: Wrap call to lexical_cast in try block

- src/v/kafka/server/handlers/create_topics.cc
- src/v/kafka/server/handlers/topics/types.cc
- tests/rptest/clients/kcl.py
- tests/rptest/tests/topic_creation_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16410
Fixes: https://github.com/redpanda-data/redpanda/issues/16447, Fixes: https://github.com/redpanda-data/redpanda/issues/16448,
> [v23.2.x] Return accurate partition count and replication factor in CreateTopics response

- tests/rptest/archival/s3_client.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16428
Fixes: https://github.com/redpanda-data/redpanda/issues/16438,
> [v23.3.x] rptest: Fix s3.copy_object when running on GCP

- src/v/cluster/health_monitor_backend.cc
- src/v/cluster/health_monitor_types.h
- src/v/cluster/partition.h
- src/v/resource_mgmt/storage.cc
- src/v/storage/disk_log_impl.cc
- src/v/storage/disk_log_impl.h
- src/v/storage/log.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16354
> [v23.3.x] cluster: publish total available reclaim size to balancer

- src/v/archival/ntp_archiver_service.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16382
Fixes: https://github.com/redpanda-data/redpanda/issues/16393,
> [v23.3.x] archival: Graceful shutdown in the spillover retention

- src/v/cloud_storage/remote_partition.cc
- src/v/cloud_storage/remote_partition.h
- src/v/cloud_storage/remote_segment.cc
- src/v/ssx/tests/CMakeLists.txt
- src/v/ssx/tests/watchdog_test.cc
- src/v/ssx/watchdog.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16466
> [v23.2.x] cloud_storage: Add watchdog utility and use it to detect stuck eviction loop

- src/v/config/configuration.cc
- src/v/config/configuration.h
- src/v/config/convert.h
- src/v/config/property.h
- src/v/config/rjson_serialization.cc
- src/v/config/rjson_serialization.h
- src/v/kafka/server/handlers/fetch.cc
- src/v/kafka/server/handlers/fetch.h
- src/v/kafka/server/tests/fetch_test.cc
- src/v/model/metadata.h
- src/v/model/model.cc
- src/v/raft/tests/basic_raft_fixture_test.cc
- src/v/ssx/abort_source.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15328
> [v23.3.x] Non-polling fetch implementation

- src/v/raft/consensus.cc
- src/v/raft/tests/basic_raft_fixture_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16475
> [v23.3.x] Improved handling of truncation with ACKS=1

- src/v/config/configuration.cc
- src/v/config/configuration.h
- src/v/rpc/rpc_server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16525
> [v23.3.x] rpc: Add config flag to enable/disable compression for replies

- tests/rptest/tests/prefix_truncate_recovery_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16472
Fixes: https://github.com/redpanda-data/redpanda/issues/16514,
> [v23.3.x] rptest: tolerate missing topic metrics after start

- src/go/rpk/.golangci.yml
- src/go/rpk/pkg/cli/redpanda/tune/tune.go
- src/go/rpk/pkg/tuners/executors/commands/write_sized_file.go
- src/go/rpk/pkg/tuners/executors/commands/write_sized_file_test.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/16576
Fixes: https://github.com/redpanda-data/redpanda/issues/16624, Fixes: https://github.com/redpanda-data/redpanda/issues/16625,
> [v23.2.x] rpk: Improve tuner output script
