redpanda-data/redpanda

src/v/cluster/cluster_utils.cc, src/v/cluster/cluster_utils.h, src/v/cluster/node_status_backend.cc, src/v/cluster/node_status_backend.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/kafka/client/broker.cc, src/v/pandaproxy/server.cc, src/v/raft/tests/raft_group_fixture.h, src/v/redpanda/admin_server.cc, src/v/redpanda/application.cc, src/v/rpc/CMakeLists.txt, src/v/rpc/backoff_policy.h, src/v/rpc/connection_cache.cc, src/v/rpc/connection_cache.h, src/v/rpc/connection_set.cc, src/v/rpc/connection_set.h, src/v/rpc/rpc_utils.cc, src/v/rpc/rpc_utils.h, src/v/rpc/test/CMakeLists.txt, src/v/rpc/test/connection_cache_test.cc, src/v/rpc/test/rpc_gen_cycling_test.cc
The first change this PR makes is to allow for the number of client connections to each of the brokers user configurable.
The second change this PR makes is to use a stateful connection allocation method that ensures the following;
- Each shard should have an equal number of client connections
- Each client connection should have an equal number of shards using it.
- On each node there should be max_connections to every other node in the cluster.
- If a shard wants a connection for a (node, shard) and the current shard has a connection for that (node, shard) it is selected. (from @travisdowns)
- For any broker A. Connections to broker A when aggregated by shard ID across every broker in the cluster should have an equal count per shard ID. (from …
=> Make max client connections configurable and refactor `rpc::connection_cache`

.github/workflows/backport-command.yml, .github/workflows/scripts/backport-command/create_milestone.sh, .github/workflows/scripts/backport-command/get_backport_type.sh, .github/workflows/scripts/backport-command/pr_details.sh
addressing comment https://github.com/redpanda-data/vtools/pull/2049#pullrequestreview-1611520364
related issue https://github.com/redpanda-data/vtools/issues/1717
this PR outputs a better backport error message
also, replaced github action `set-output` with env file (see [blog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/))
* none
=> slash backport command: better error message on failure to backport

cmake/dependencies.cmake, install-dependencies.sh, licenses/third_party.md, src/v/utils/log_hist.h, src/v/wasm/CMakeLists.txt, src/v/wasm/api.cc, src/v/wasm/api.h, src/v/wasm/probe.h, src/v/wasm/tests/wasm_fixture.cc, src/v/wasm/wasmedge.cc, src/v/wasm/wasmtime.cc, src/v/wasm/wasmtime.h
This patchset introduces wasmtime as a wasm::runtime in Redpanda and switches our usages over to it.
Currently WasmEdge AOT doesn't work in Redpanda, and the interpreter mode doesn't give us acceptable performance.
Instead we JIT compile WebAssembly at runtime for better performance. We must run compilation of WebAssembly on an
alien thread, Rust + cranelift (Wasmtime's JIT compiler) puts too much data on the stack, so at least in tests when 
we're running on a ss::thread with 128KiB of stack, we get stack overflow assertions in ASAN. Also compilation is 
synchronous and can be quite slow with large modules, so that will always need to run on an alien thread.
This PR also runs Wasmtime's VM itself on an alien thread - as there is some signals that the VM relies on to operate, 
which seem …
=> Introduce wasmtime as a wasm::runtime

src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_backend.h, src/v/cluster/health_monitor_types.h, src/v/cluster/tests/CMakeLists.txt, src/v/cluster/tests/health_bench.cc, src/v/cluster/tests/health_monitor_test.cc, src/v/cluster/tests/health_monitor_test_utils.h, src/v/redpanda/admin/api-doc/cluster.json, src/v/redpanda/admin_server.cc, tests/rptest/tests/cluster_health_overview_test.py
This series adds the count of leaderless and under-replicated
partitions to the cluster_health_overview API. This API already
contained an explicit list of such partitions, so what help is the
count? Well both lists are truncated at 128 entries, but the count
reports the true value.
This can be shown in the rpk health command so that progress can be
monitored even when the lists are beyond the truncation limit.
* Show the true count of leaderless and under-replicated partitions in the admin API.
=> Show true partition count in cluster health API

src/go/rpk/pkg/cli/profile/create.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/13361
=> [v23.2.x] rpk profile create: use StringArray rather than StringSlice

src/go/rpk/pkg/adminapi/api_transform.go, src/go/rpk/pkg/cli/transform/delete.go, src/go/rpk/pkg/cli/transform/transform.go
Add the ability to delete transforms.
See the corresponding RFCs for rpk and the admin API for context.
* none
=> Add rpk transform delete command

src/go/rpk/pkg/adminapi/api_partition.go, src/go/rpk/pkg/cli/cluster/partitions/cancel.go, src/go/rpk/pkg/cli/cluster/partitions/cancel_hidden.go, src/go/rpk/pkg/cli/cluster/partitions/list.go, src/go/rpk/pkg/cli/cluster/partitions/partitions.go, src/go/rpk/pkg/cli/topic/describe.go, src/go/rpk/pkg/cli/topic/describe_storage.go, src/go/rpk/pkg/out/out.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/13258
Fixes: https://github.com/redpanda-data/redpanda/issues/13380,
=> [v23.2.x] rpk: add move-status to show ongoing partition movements

src/go/rpk/pkg/config/config_test.go, src/go/rpk/pkg/config/params.go
*Manual Backport of https://github.com/redpanda-data/redpanda/pull/13343*
There was a bug introduced in 23.2 that made
setting a TLS struct value impossible via set
commands (rpk profile set, rpk redpanda config set). We were just checking for the empty/boolean case.
(cherry picked from commit f8d04d55b482d10bb94bf88a289b7ec639405481)
Fixes #13378 
* rpk/bugfix: enable back setting TLS struct values in set commands
=> [v23.2.x] rpk/bugfix: enable back setting tls struct values in set commands

tests/setup.py
Our fork of ducktape was rebased on top of 0.8.x. This PR updates the ducktape version.
It also updates the kafkatest version, since the older version of kafkatest, depends on
ducktape 0.8.8. the new one depends on
ducktape >0.8
ref https://github.com/redpanda-data/devprod/issues/332
* none
=> update ducktape version

tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/services/redpanda.py, tests/rptest/services/redpanda_cloud.py
Enable redpanda cloud metrics summary so redpanda cloud tests `test_disrupt_cloud_storage` and `test_cloud_cache_thrash` can run.
Fixes https://github.com/redpanda-data/cloudv2/issues/8845
I verified with:
```console
ducktape \
--debug \
tests/rptest/redpanda_cloud_tests/high_throughput_test.py::HighThroughputTest.test_disrupt_cloud_storage
```
Where output had line showing `metric_sum()` retrieving value `287`:
```
[INFO  - 2023-09-13 15:30:41,092 - si_utils - nodes_report_cloud_segments - lineno:483]: Cluster metrics report 287 / 1000 cloud segments
```
* none
=> rptest: add ability to retrieve public metrics from redpanda cloud

cmake/dependencies.cmake
Also remove the default features, we don't use anyof them
* none
=> cmake/oss: upgrade wasmtime

src/v/ssx/CMakeLists.txt, src/v/ssx/tests/CMakeLists.txt, src/v/ssx/tests/work_queue_test.cc, src/v/ssx/work_queue.cc, src/v/ssx/work_queue.h, src/v/transform/CMakeLists.txt, src/v/transform/tests/CMakeLists.txt, src/v/transform/tests/transform_manager_test.cc, src/v/transform/transform_manager.cc, src/v/transform/transform_manager.h, src/v/transform/transform_processor.cc, src/v/transform/transform_processor.h, src/v/utils/human.cc, src/v/utils/human.h
Transform manager is the component for ensuring that the correct `transform::processor` is running for a given core.
It is a component that recieves notifications from the rest of the system and processes those notifications on a single fiber queue.
The queue makes handling shutdown a little simpler, as we can remove most of the logic for handling shutdown correctly into another class,
additionally using a single fiber means we don't need to worry about concurrent modifications of data structures or duplicate notifications
being scheduled.
We also template the manager based on the clock type. This is a similar pattern used in other places that allows us to use the seastar manual 
clock for fully deterministic testing, but use the lowres clock for production usage.
* none
=> Introduce transform::manager

src/v/cluster/scheduling/partition_allocator.cc
Include also the predicted number of partitions in the error message since that's key information about the failure. Previously we only included the number of new partitions, leaving to weird messages like "creating 100 partitoins failed, limit is 1000", when the full truth is that there were 950 partitoins already so 950 + 100 > 1000.
* none
=> Better error message when topic creation fails

src/v/kafka/protocol/schemata/generator.py, src/v/kafka/server/request_context.h
From slack messages https://redpandadata.slack.com/archives/C04JM4NSZ1S/p1673495659635979?thread_ts=1673489527.731349&cid=C04JM4NSZ1S and https://redpandadata.slack.com/archives/C04JM4NSZ1S/p1673496016609889?thread_ts=1673489527.731349&cid=C04JM4NSZ1S
It looks like debugging would have been quicker if support found `NOT_COORDINATOR` response in the logs earlier.
The ask is to log errored Kafka responses in a way that make it easier to identify them in the logs so the debugging process is easier. Changing the log-level for errored responses is OK but that could also lead to large log volume.
Therefore, this PR adds a method to all Kafka responses that check for an error and it logs errored responses at a limit so they do not flood logging systems.
Fixes #12858
Changes from force-push …
=> kafka: log errored responses at DEBUG instead of TRACE

tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/services/redpanda_cloud.py
- These tests are hitting internal quota limits and create_topics requests are failing
- The solution is to not create a topic with the maximum number of partitions on test initializtion but rather a number that is slightly less then the max.
* none
=> Lower number of partitions created in high throughput tests

src/v/transform/transform_processor.cc
Using the moved string results in the empty string being added to the
logger
* none
=> transform/processor: fix use-after-move

src/v/kafka/protocol/schemata/generator.py, src/v/kafka/server/request_context.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/12860
Fixes: https://github.com/redpanda-data/redpanda/issues/13433,
=> [v23.2.x] kafka: log errored responses at DEBUG instead of TRACE

src/v/kafka/protocol/schemata/generator.py, src/v/kafka/server/request_context.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/12860
Fixes: https://github.com/redpanda-data/redpanda/issues/13435,
=> [v23.1.x] kafka: log errored responses at DEBUG instead of TRACE

src/go/rpk/pkg/adminapi/api_transform.go
The API slightly changed for deleting transforms and now it's more of a
proper REST endpoint.
* none
=> rpk/transform: Fix delete endpoint

src/v/redpanda/CMakeLists.txt, src/v/redpanda/admin/api-doc/transform.json, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h
Stub out the initial Admin HTTP endpoints for Data Transforms.
* none
=> Data Transform Admin APIs

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/features/feature_table.cc, src/v/features/feature_table.h, src/v/raft/CMakeLists.txt, src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/group_manager.cc, src/v/raft/group_manager.h, src/v/raft/recovery_scheduler.cc, src/v/raft/recovery_scheduler.h, src/v/raft/replicate_entries_stm.cc, src/v/raft/tests/raft_fixture.cc, src/v/raft/tests/raft_fixture.h, src/v/raft/tests/raft_group_fixture.h, src/v/raft/tests/simple_raft_fixture.h, src/v/raft/tests/state_removal_test.cc, src/v/raft/types.h, src/v/raft/vote_stm.cc, src/v/redpanda/admin/api-doc/raft.json, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h, src/v/redpanda/application.cc, tests/rptest/services/admin.py, tests/rptest/tests/raft_recovery_test.py
Although each raft group's recovery can proceed independently, it is not desirable to run all of them in parallel, because it leads to an excess of concurrent I/Os to a node coming back online after an outage. Introduce `recovery_scheduler` - the class responsible for limiting the number of recoveries done to a single node at once, and for prioritizing them to recover important metadata before bulk data.
* Introduce *coordinated recovery* - avoid overwhelming a starting node that has been offline for a long time with Raft recovery traffic by limiting concurrency and prioritizing the order of partition recovery. This is enabled by default, to configure the per-shard concurrency limit, change the `raft_recovery_concurrency_per_shard` cluster config property.
=> Coordinated recovery: scheduler

src/v/archival/tests/ntp_archiver_test.cc, src/v/cluster/metadata_cache.cc, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/kafka/server/handlers/describe_configs.cc, src/v/kafka/server/tests/alter_config_test.cc, src/v/redpanda/application.cc, src/v/resource_mgmt/storage.cc, src/v/storage/log_manager.cc, src/v/storage/log_manager.h, src/v/storage/ntp_config.h, tests/rptest/clients/rpk.py, tests/rptest/tests/cluster_config_test.py, tests/rptest/tests/tx_abort_index_test.py
Clean up the property name `delete_retention_ms` and rename it to `log_retention_ms`. The use of this property was already closer to the semantics of Kafka's `log.retention.ms`, so this is primarily a rename.
This is done in a backward-compatible way by renaming the property and adding an alias to `delete_retention_ms`.
Users are expected to use `log_retention_ms`, but the old name is still accepted. But when editing the configuration, `log_retention_ms` will be used, so this is a breaking change.
To allow the use of aliases in redpanda.yml, the new method `config_store::property_aliases` returns them and they get used by `node_config::load` to skip them. 
Fixes https://github.com/redpanda-data/redpanda/issues/4041
This pr surfaced these issue: …
=> rename delete_retention_ms -> log_retention_ms

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
Recently this test was unignored but now it is failing in the nightly cloud tests. This patch fixes the issue where the test was timing out before the total number of expected segments was uploaded.
https://github.com/redpanda-data/cloudv2/issues/8193
* none
=> Modify tiered storage upload parameters in high throughput test

src/go/cluster-to-redpanda-migration/go.sum
Ran `go mod tidy` against the cluster migration tool golang codebase to fix GHA workflow failures
* none
=> go: update `go.sum` to match source code

src/go/rpk/pkg/adminapi/api_transform.go, src/go/rpk/pkg/cli/transform/list.go, src/go/rpk/pkg/cli/transform/list_test.go, src/go/rpk/pkg/cli/transform/transform.go
Support listing the metadata from the broker Admin API endpoint
Supports text, json & yaml output formats
* none
=> rpk/transform: introduce list command

src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_backend.h, src/v/cluster/health_monitor_types.h, src/v/cluster/tests/CMakeLists.txt, src/v/cluster/tests/health_bench.cc, src/v/cluster/tests/health_monitor_test.cc, src/v/cluster/tests/health_monitor_test_utils.h, src/v/redpanda/admin/api-doc/cluster.json, src/v/redpanda/admin_server.cc, tests/rptest/tests/cluster_health_overview_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13296
=> [v23.2.x] Show true partition count in cluster health API

src/v/config/configuration.cc, src/v/kafka/server/tests/CMakeLists.txt
Increase this value from 1 to 4 MiB based on the observation that 1 MiB is not enough to prevent OOMs on some high-load + high-partition workloads.
Fixes #13460.
* The default value for topic_memory_per_partition is increased to 4 MiB. This means that Redpanda must be allocated at least 4 MiB of memory for every partition replica (partition count * replication factor). If this limit is not met, new partitions cannot be created.
=> Increase topic_memory_per_partition to 4 MiB

src/v/config/node_config.cc, src/v/redpanda/application.cc, tests/rptest/tests/crash_loop_checks_test.py
Defaults to 5. If a broker shuts down uncleanly 5 times back to back, it is considered to be in a crash loop.
Crash loop limit enforcement is disabled in `developer` mode which is also set by rpk's `dev-container` mode.
The idea is that crash_loop_limit tracking has value only when running at scale and disabling it prevents inadverdent lockups (and hence better UX) when running in container mode / CI etc.
* crash_loop_limit now defaults to 5. If a broker uncleanly shutdowns for 5 times back to back, it is considered to be in a crash loop mode and Redpanda refuses to start up and may need a manual intervention. This enforcement is disabled in `developer` mode and rpk's `dev-container` mode.
=> config: enable crash_loop_limit by default

src/go/rpk/pkg/cli/redpanda/tune/tune.go
If the user used a directory it would fail and panic without giving any meaningful error.
* rpk: prevent panic when using a directory instead of a filename in `rpk redpanda tune --output-script`
=> rpk: improved err msg in rpk tune --output-script

src/v/config/node_config.cc, src/v/redpanda/application.cc, tests/rptest/tests/crash_loop_checks_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13431
=> [v23.2.x] config: enable crash_loop_limit by default

src/go/rpk/pkg/cli/redpanda/tune/tune.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/13473
=> [v23.2.x] rpk: improved err msg in rpk tune --output-script

src/v/cluster/cloud_metadata/manifest_downloads.cc, src/v/cluster/cloud_metadata/manifest_downloads.h, src/v/cluster/cloud_metadata/tests/manifest_downloads_test.cc, src/v/cluster/cloud_metadata/tests/uploader_test.cc, src/v/cluster/cloud_metadata/uploader.cc, src/v/cluster/cloud_metadata/uploader.h, src/v/cluster/controller.cc, src/v/cluster/controller.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/application.cc, src/v/storage/api.h, tests/rptest/services/redpanda.py, tests/rptest/tests/cluster_metadata_upload_test.py, tests/rptest/utils/si_utils.py, tools/rp_storage_tool/src/bucket_reader.rs
This PR adds the controller uploader into the application:
- Plumbs the uploader into the controller, optionally avoiding the start() call for easier testing and backportability
- Register appropriate callbacks to allow the controller to listen to leadership changes
- Allows the uploader to wait for the cluster UUID to be set in the storage layer
Along the way, in testing, I found that subsequent usage of the same bucket previously resulted in multiple clusters contending with each others metadata IDs. This PR also tweaks the uploader to start its count from a metadata ID that is higher than the highest in the bucket, ensuring a single bucket can be used across multiple recoveries.
Fixes https://github.com/redpanda-data/redpanda/issues/9552
* none
=> cloud_metadata: plug upload loop into application

src/go/rpk/pkg/cli/cmd/redpanda/tune/tune.go
Manual Backport of https://github.com/redpanda-data/redpanda/pull/13473
Fixes #13541
* rpk: prevent panic when using a directory instead of a filename in `rpk redpanda tune --output-script`
=> [v23.1.x] rpk: improved err msg in rpk tune --output-script

src/go/rpk/pkg/cli/cmd/redpanda/tune/tune.go
If the user used a directory it would fail without giving any meaningful error.
Manual Backport of PR #13473
Fixes #13540
* rpk: prevent panic when using a directory instead of a filename in rpk redpanda tune --output-script
=> [v22.3.x] rpk: improved err msg in rpk tune --output-script

src/v/cluster/cluster_utils.cc, src/v/cluster/types.h, src/v/raft/consensus.cc, src/v/raft/recovery_stm.cc, src/v/raft/recovery_stm.h, src/v/raft/replicate_entries_stm.cc, src/v/raft/types.cc, src/v/raft/types.h, src/v/redpanda/admin/api-doc/debug.json, src/v/redpanda/admin_server.cc
In Redpanda Raft implementation there may more than one
`append_entries_request` dispatched to the follower at the same time.
Leader tracks follower expected end offset to coordinate `recovery_stm`
and `append_entries_stm` and prevent delivering the same batches twice.
In classic raft implementation there is always only one append entries
request pending to the follower hence it is enough to update follower
state when processing append entries reply. We must track the expected
follower end before receiving response as the requests may already be in
flight.
Fixes: https://github.com/redpanda-data/core-internal/issues/752
- none
=> fixed tracking expected last offset of a follower

src/v/cluster/tests/id_allocator_stm_test.cc, src/v/config/configuration.cc, src/v/raft/group_manager.cc, src/v/raft/group_manager.h, src/v/raft/tests/jitter_tests.cc, src/v/raft/tests/raft_fixture.cc, src/v/raft/tests/raft_fixture.h, src/v/raft/tests/raft_group_fixture.h, src/v/raft/tests/simple_raft_fixture.h, src/v/raft/timeout_jitter.h, src/v/redpanda/application.cc
All other Raft timeouts are configurable in runtime. Made election timeout runtime configurable as well.
Fixes: #13491
- `raft_election_timout_ms` change does not require restart now
=> r/consensus: made raft election timeout runtime configurable

tests/rptest/tests/upgrade_test.py
a race between test and redpanda to read/modify insync_offset on a manifest.
the fix is to read the cloud storage manifest before producing to the partition
Fixes #13181
* none
=> tests/upgrade_test: test_rolling_upgrade race fix

src/v/config/bounded_property.h, src/v/config/property.h, src/v/config/tests/bounded_property_test.cc
Small template helper `property<T>::set_value` to allow passing a value convertible to the property type T. This is primarily useful in unit tests, where otherwise one would be obliged to call set_value with the exact T type or face a runtime exception.
some examples are optional<chrono::milliseconds> property, where it was not possible to write set_value(1h).
* none
=> unit tests: make property::set_value accept values convertible to the property T 

src/v/cluster/controller.cc, src/v/cluster/controller.h, src/v/redpanda/admin_server.cc, tests/rptest/tests/partition_state_api_test.py
Added handling for returning `redpanda/controller/0` partition status from `/v1/debug/partition/{namespace}/{topic}/{partition}`
Fixes: https://github.com/redpanda-data/core-internal/issues/733
- none
=> Support returning controller partition status

.github/workflows/redpanda-migration-build.yml, src/go/cluster-to-redpanda-migration/go.mod, src/go/cluster-to-redpanda-migration/go.sum
Adds `go/src/k8s` to the list of paths that, when changed, trigger an execution of the `cluster-to-redpanda-migration-tool` workflow. Since the migration tool references code in the k8s operator codebase, this causes issues.
fixes https://github.com/redpanda-data/devprod/issues/847
* none
=> Trigger the `cluster-to-redpanda-migration-tool` workflow when `go/src/k8s/` is changed

tests/rptest/clients/rpk.py, tests/rptest/tests/partition_balancer_test.py
Rpk will make 3 admin requests with 10 second timeout, so with 1 problematic node, worst case it will hang for 30 seconds, which also happens to be the default RpkTool timeout. Therefore we need a larger timeout than that.
Fixes https://github.com/redpanda-data/redpanda/issues/10848
* none
=> tests: increase rpk timeout in partition balancer maintenance test

src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/recovery_stm.cc, src/v/raft/types.cc
If we lose leadership while heartbeats are suppressed, `follower_index_metadata` for a follower can get recreated, leading to suppress/unsuppress mismatch. Skip unsuppressing if we have lost leadership.
Fixes https://github.com/redpanda-data/redpanda/issues/13305
* none
=> raft: skip unsuppressing heartbeats if we lose leadership

src/v/cloud_storage/materialized_resources.cc, src/v/cloud_storage/materialized_resources.h, src/v/cloud_storage/remote.cc, src/v/cloud_storage/remote.h, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_partition.h, src/v/cloud_storage/remote_probe.cc, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment.h, src/v/cloud_storage/remote_segment_index.cc, src/v/cloud_storage/remote_segment_index.h, src/v/cloud_storage/segment_state.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/resource_mgmt/memory_groups.h
Count memory resources explicitly, instead of counting objects. Fixes https://github.com/redpanda-data/redpanda/issues/13419
Previously the read path of the tiered-storage had separate limits on:
- number of segment readers (which are used to read data from cached files, property name: `cloud_storage_max_segment_readers_per_shard`)
- number of materialized segments (objects that represent cloud storage segment in Redpanda, property name: `cloud_storage_max_materialized_segments_per_shard`)
- number of partition readers (property name: `cloud_storage_max_partition_readers_per_shard`)
The last parameter was actually used to limit number of parallel fetch requests handled by the tiered-storage per shard. Partition readers are transient objects which are created per fetch request. Because of …
=> TS Read Guardrails: Constrain tiered-storage resource consumption with memory limits

src/v/cluster/cluster_utils.cc, src/v/cluster/types.h, src/v/raft/consensus.h, src/v/redpanda/admin/api-doc/debug.json, src/v/redpanda/admin_server.cc
=> admin: add raft follower_recovery_state to debug partition json

tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/services/redpanda_cloud.py
=> rptest: Handle tier name before cluster creation

src/v/cloud_storage_clients/s3_client.cc
S3 may return a 503 Service Unavailable response to HeadObject requests in order to signal the client to back off. Previously, this wasn't handled and resulted to an error log being printed each time such a response was received for a HeadObject request.
* Fix handling of slow down responses for HeadObject requests
=> cloud_storage_clients/s3: handle HEAD slow downs

src/go/rpk/pkg/adminapi/api_cluster.go, src/go/rpk/pkg/cli/cluster/health.go, src/go/rpk/pkg/out/out.go
Introduced in https://github.com/redpanda-data/redpanda/pull/13296
Fixes https://github.com/redpanda-data/redpanda/issues/13399
**Example:**
```
CLUSTER HEALTH OVERVIEW
=======================
Healthy:                          true
Unhealthy reasons:                []
Controller ID:                    1
All nodes:                        [1 2 3]
Nodes down:                       []
Leaderless partitions (0):        []
Under-replicated partitions (0):  []
```
```
CLUSTER HEALTH OVERVIEW
=======================
Healthy:                          false
Unhealthy reasons:                [leaderless_partitions under_replicated_partitions]
Controller ID:                    1
All nodes:                        [1 2 3]
Nodes down:                       []
Leaderless partitions (2):        [foobar/0, …
```
=> rpk: Add URP and leaderless counts to `rpk cluster health`

.github/workflows/redpanda-migration-build.yml, src/go/cluster-to-redpanda-migration/go.mod, src/go/cluster-to-redpanda-migration/go.sum
Backport of PR https://github.com/redpanda-data/redpanda/pull/13570
=> [v23.2.x] Trigger the `cluster-to-redpanda-migration-tool` workflow when `go/src/k8s/` is changed

tests/rptest/clients/rpk.py, tests/rptest/tests/partition_balancer_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13587
Fixes: https://github.com/redpanda-data/redpanda/issues/13600,
=> [v23.2.x] tests: increase rpk timeout in partition balancer maintenance test

tests/docker/Dockerfile, tests/docker/ducktape-deps/keycloak, tests/rptest/clients/python_librdkafka.py, tests/rptest/services/keycloak.py, tests/rptest/tests/redpanda_oauth_test.py, tests/setup.py
As work adding OIDC authentication to Redpanda gets underway, we would like to have
access to a locally installable/configurable identity provider service for the purposes of
experimentation and integration testing. This PR introduces a new ducktape service
(`KeycloakService`) to this end, built around the open source [Keycloak](https://keycloak.org)
IAM  application.
Additionally, this PR integrates OAuth/OIDC support into the existing `PythonLibrdkafka`
ducktape client and adds a `redpanda_oauth_test.py`. The latter contains a simple test
to spin up a keycloak service and demonstrate that it is alive and servicing requests.
Fixes: https://github.com/redpanda-data/core-internal/issues/748 https://github.com/redpanda-data/core-internal/issues/755
=> KeycloakService and friends

src/v/storage/compacted_index.h, src/v/storage/compacted_index_writer.h, src/v/storage/compaction_reducers.cc, src/v/storage/compaction_reducers.h, src/v/storage/segment.cc, src/v/storage/spill_key_index.cc, src/v/storage/spill_key_index.h, src/v/storage/tests/compaction_index_format_tests.cc, src/v/storage/tests/storage_e2e_test.cc, tests/java/verifiers/src/main/java/io/vectorized/compaction/idempotency/IdempotentWorkload.java, tests/java/verifiers/src/main/java/io/vectorized/compaction/tx/TxUniqueKeysWorkload.java, tests/java/verifiers/src/main/java/io/vectorized/compaction/tx/TxWorkload.java, tests/rptest/tests/compaction_e2e_test.py
With this PR, control batches are not discarded but are compacted in the same manner as other data batches. This approach prevents the  elimination of the last batch within a segment when it happens to be a control batch. If the final batch in a segment is discarded, and there are no subsequent data batches, it could lead to clients being unable to advance their consumed offset until the LSO, creating the perception of a stuck consumer unable to make progress.
However, this situation is not problematic when the last batch is an aborted data batch. This is because we can guarantee the presence of user consumable batches following it (in the next segment), specifically the abort control batch (or maybe other interleaved committed batches), ensuring continuous consumer progress.
Fixes …
=> tx/compaction: ensure last batch in a segment is not compacted way.

tests/rptest/tests/node_pool_migration_test.py
Fixed validation of total broker count in node pool migration test.
- none
=> tests: fixed node pool migration test broker count check.

src/v/archival/ntp_archiver_service.cc
Follow up from https://github.com/redpanda-data/redpanda/pull/12177#discussion_r1267999549
* none
=> archival: promote log for noop GC to error

src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_backend.h, src/v/cluster/partition_balancer_backend.cc
It may happen that the health report notification for a given node is processed before the notification about the node addition. In this case `partition_balancer_backend` would wait for another tick to trigger rebalancing. Added immediate tick trigger when node add notification is processed and health report for a node is already present.
Fixes: #12220
- none
=> c/pb_backend: schedule tick immediately if health report is available

tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/services/redpanda_cloud.py, tests/rptest/services/templates/omb_workload.yaml
Test uses OMB and broker-based numbers of producers/consumers to test latency with min/max number of partitions
* none
=> Create test using OMB and variable number of partitions

src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_backend.h, src/v/cluster/partition_balancer_backend.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13616
Fixes: https://github.com/redpanda-data/redpanda/issues/13642,
=> [v23.2.x] c/pb_backend: schedule tick immediately if health report is available

src/v/cluster/topics_frontend.cc, src/v/cluster/topics_frontend.h
Changed `topics_fronted::change_replication_factor` code to create partition allocation constraints directly on the partition allocator shard. Constraints holds seastar shared pointers and they can not be referenced cross shards like it was previously.
Fixes: #13395
* none
=> c/topics_frontend: create partition constraints on allocator shard

src/v/kafka/server/connection_context.h
Fixes #13390
This message appears in the log very frequently depending on the number of rpk clients. In a default deployment of 3 brokers with 1 external rpk instance, this message appears ~75/min. This PR changes this message to DEBUG.
* Changes the log level for when rpk clients disconnect from the cluster to debug
=> Change rpk disconnect message from INFO to DEBUG

src/v/storage/disk_log_impl.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11681
Fixes https://github.com/redpanda-data/redpanda/issues/11721,
=> [v22.3.x] storage: make `compaction_backlog` more efficient for large segment counts

tests/rptest/tests/nodes_decommissioning_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11903
Fixes: https://github.com/redpanda-data/redpanda/issues/11910,
=> [v22.3.x] Fixed querying for the node in decommission test

src/v/archival/adjacent_segment_merger.cc, src/v/archival/ntp_archiver_service.cc, src/v/storage/disk_log_impl.cc, tests/rptest/tests/tiered_storage_model.py, tests/rptest/tests/tiered_storage_model_test.py, tests/setup.py
This PR adds new test that can be parametrised using solutions of the boolean model that represents dependencies between different actions that can be performed by tiered-storage.
The model captures dependencies like dependency between segment upload, download, segment rolling and produce.
The model is then solved to find what inputs are needed to see certain effect (e.g. segment download or segment deletion). The result contains not only inputs but all intermediate actions. The test runner uses set of validators to check if all these actions are actually performed so we could be certain that the actual test run matches with the model.
Currently, the model is solved only for few test cases (for instance, time query and spillover) to fill some gaps we have in our ducktape test suite. It …
=> rptest: Add model based test based on Z3

src/v/archival/scrubber.cc, src/v/cloud_storage/anomalies_detector.cc, src/v/cloud_storage/anomalies_detector.h, src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/partition_manifest.h, src/v/cloud_storage/tests/anomalies_detector_test.cc, src/v/cloud_storage/types.cc, src/v/cloud_storage/types.h, src/v/redpanda/admin/api-doc/shadow_indexing.json, src/v/redpanda/admin_server.cc, tests/rptest/tests/cloud_storage_scrubber_test.py
This PR introduces scrubbing of segment metadata.
In addition to missing segments and spills we can now detect:
* bad or missing deltas
* incorrect offsets within a segment
* offset gaps and overlaps
* none
=> cloud_storage: scrub segment metadata

src/v/kafka/server/handlers/handler_probe.cc, src/v/kafka/server/handlers/handler_probe.h
Exposes the produce and fetch per handler metrics on the public_metrics endpoint.
These will eventually replace the existing produce and fetch latency metrics on the public endpoint (as those measure non-meaningful latency intervals).
Ref https://github.com/redpanda-data/redpanda/issues/13363
* Export per handler produce/fetch metrics on the public_metrics endpoint
=> kafka: Expose per handler produce/fetch metrics on public_metrics

src/go/rpk/pkg/cli/redpanda/admin/brokers/decommission-status.go
```
Note %d is decommissioned successfully
```
to
```
Node %d is decommissioned successfully
```
* None
=> rpk: fix typo in decommission-status

src/v/cluster/rm_stm.cc
This is for debugging situations in which incorrect aborted transactions are populated in fetch response.
* none
=> rm_stm: trace logging for aborted transactions call

src/v/config/node_config.cc, src/v/redpanda/application.cc, tests/rptest/tests/crash_loop_checks_test.py
Defaults to 5. If a broker shuts down uncleanly 5 times back to back, it is considered to be in a crash loop.
Crash loop limit enforcement is disabled in developer mode which is also set by rpk's dev-container mode.
The idea is that crash_loop_limit tracking has value only when running at scale and disabling it prevents inadverdent lockups (and hence better UX) when running in container mode / CI etc.
Fixes https://github.com/redpanda-data/redpanda/issues/13534
* crash_loop_limit now defaults to 5. If a broker uncleanly shutdowns for 5 times back to back, it is considered to be in a crash loop mode and Redpanda refuses to start up and may need a manual intervention. This enforcement is disabled in developer mode and rpk's dev-container mode.
=> [backport] [v23.1.x] config: enable crash_loop_limit by default

src/v/storage/compacted_index.h, src/v/storage/compacted_index_writer.h, src/v/storage/compaction_reducers.cc, src/v/storage/compaction_reducers.h, src/v/storage/segment.cc, src/v/storage/spill_key_index.cc, src/v/storage/spill_key_index.h, src/v/storage/tests/compaction_index_format_tests.cc, src/v/storage/tests/storage_e2e_test.cc, tests/java/verifiers/src/main/java/io/vectorized/compaction/idempotency/IdempotentWorkload.java, tests/java/verifiers/src/main/java/io/vectorized/compaction/tx/TxUniqueKeysWorkload.java, tests/java/verifiers/src/main/java/io/vectorized/compaction/tx/TxWorkload.java, tests/rptest/tests/compaction_e2e_test.py
Backport of https://github.com/redpanda-data/redpanda/pull/13609
With this PR, control batches are not discarded but are compacted in the same manner as other data batches. This approach prevents the elimination of the last batch within a segment when it happens to be a control batch. If the final batch in a segment is discarded, and there are no subsequent data batches, it could lead to clients being unable to advance their consumed offset until the LSO, creating the perception of a stuck consumer unable to make progress.
However, this situation is not problematic when the last batch is an aborted data batch. This is because we can guarantee the presence of user consumable batches following it (in the next segment), specifically the abort control batch (or maybe other interleaved …
=> [backport] [v23.2.x] tx/compaction: ensure last batch in a segment is not compacted way

src/v/cluster/tx_gateway_frontend.cc, src/v/cluster/tx_gateway_frontend.h
This is a follow up to https://github.com/redpanda-data/redpanda/pull/12477
Previously we expired one old txn session per new tx. It helped to maintain the txn sessions cache size at the capacity but it couldn't bring the cache size down if it was already beyond `max_transactions_per_coordinator` (it may happen when a user sets `max_transactions_per_coordinator` for the first time).
Fixing it by bulk expiring.
* none
=> Txn sessions thrashing: expire all old txs instead of one at a time

src/v/storage/compacted_index.h, src/v/storage/compacted_index_writer.h, src/v/storage/compaction_reducers.cc, src/v/storage/compaction_reducers.h, src/v/storage/segment.cc, src/v/storage/spill_key_index.cc, src/v/storage/spill_key_index.h, src/v/storage/tests/compaction_index_format_tests.cc, src/v/storage/tests/storage_e2e_test.cc, tests/java/verifiers/src/main/java/io/vectorized/compaction/idempotency/IdempotentWorkload.java, tests/java/verifiers/src/main/java/io/vectorized/compaction/tx/TxUniqueKeysWorkload.java, tests/java/verifiers/src/main/java/io/vectorized/compaction/tx/TxWorkload.java, tests/rptest/tests/compaction_e2e_test.py
Backport of #13609
With this PR, control batches are not discarded but are compacted in the same manner as other data batches. This approach prevents the elimination of the last batch within a segment when it happens to be a control batch. If the final batch in a segment is discarded, and there are no subsequent data batches, it could lead to clients being unable to advance their consumed offset until the LSO, creating the perception of a stuck consumer unable to make progress.
However, this situation is not problematic when the last batch is an aborted data batch. This is because we can guarantee the presence of user consumable batches following it (in the next segment), specifically the abort control batch (or maybe other interleaved committed batches), ensuring continuous consumer …
=> [backport] [v23.1.x] tx/compaction: ensure last batch in a segment is not compacted way

src/v/cluster/controller_backend.cc, src/v/features/feature_table.cc, src/v/features/feature_table.h, src/v/redpanda/admin_server.cc, tests/rptest/tests/partition_force_reconfiguration_test.py
With these changes, controller now supports recovering from an all replicas lost scenario using force reconfiguration. A typical example is a broker hosting rf=1 partition is dead and cannot be recovered. 
Without this support, an operator has to delete the entire topic (hence all partitions) to recover the topic controller state and fix the replica assignment.
Example invocation for reconfiguring partition `foo/0` with only replica on node_id=1
```
curl -X POST http://localhost:9644/v1/debug/partitions/kafka/foo/0/force_replicas -H 'Content-Type: application/json' --data '[{"node_id": 0, "core": 0},{"node_id": 2, "core": 0}]'
```
After force reconfiguration, the partition is now reset to rf=2 on brokers (0, 2).
* Force reconfiguration now supports recovering from all replicas lost …
=> controller: force reconfiguration from all replicas gone scenario

src/v/cluster/tx_gateway_frontend.cc, src/v/cluster/tx_gateway_frontend.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/13658
=> [v23.2.x] Txn sessions thrashing: expire all old txs instead of one at a time

src/v/raft/state_machine.cc, src/v/raft/state_machine.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/12931
Fixes: #13393
=> [v23.1.x] Backport of #12157

src/v/cluster/partition.cc, src/v/cluster/partition_probe.cc, src/v/cluster/partition_probe.h, src/v/raft/consensus.cc, src/v/raft/probe.h
Backporting: 
- https://github.com/redpanda-data/redpanda/pull/13009
Fixes: #13053
- fixed rare but possible deadlock that might lead to Redpanda crash when moving partitions back and forth between nodes.
=> [v23.2.x] Backport of: #13009

src/v/cloud_storage/remote_segment.cc, src/v/storage/parser.h, src/v/storage/parser_errc.h, tests/rptest/tests/e2e_shadow_indexing_test.py
Backport two PRs to 23.2.x to enable parser error state to be printed in logs. The two PRs are closely related, one prints the parser state and the other changes the log level.
Fixes #13754
* none
=> Backport PRs 12888 and 12479

tests/rptest/tests/partition_balancer_test.py
Disable leader balancer after partition balancer has finished its work, because leadership transfers will create new segments that can cause disk usage to go over limit again even after we've verified that everything is stable.
Fixes https://github.com/redpanda-data/redpanda/issues/9788
* none
=> ducky/partition_balancer_test: fix full_node_test

tests/rptest/services/redpanda.py
The test can choose to initialize the cluster with a smaller node subset and start other nodes later with redpanda.start_node() (which doesn't invoke clean_node)
Fixes https://github.com/redpanda-data/redpanda/issues/13372
* none
=> tests: clean all nodes on first start in Redpanda service

src/go/rpk/pkg/cli/cmd/redpanda/tune/tune.go
slack ref: https://redpandadata.slack.com/archives/C029XT7FLQ2/p1695874197509739?thread_ts=1695829970.948859&cid=C029XT7FLQ2
Ref
* fix of #13548
* re-backport of #13473
fixes redpadnda-data/devprod#856
* none
=> [v22.3.x] rpk tune fix checking for tune script file

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
=> rptest: Fix topic creation on throughput test start

src/v/kafka/protocol/errors.cc, src/v/kafka/protocol/errors.h, src/v/kafka/server/handlers/produce.cc, src/v/kafka/server/partition_proxy.cc, src/v/kafka/server/partition_proxy.h, src/v/kafka/server/replicated_partition.cc, src/v/kafka/server/replicated_partition.h, src/v/model/record_batch_reader.cc, src/v/model/record_batch_reader.h, src/v/rpc/connection_cache.cc, src/v/rpc/connection_cache.h, src/v/rpc/rpc_compiler.py, src/v/transform/CMakeLists.txt, src/v/transform/rpc/CMakeLists.txt, src/v/transform/rpc/client.cc, src/v/transform/rpc/client.h, src/v/transform/rpc/deps.cc, src/v/transform/rpc/deps.h, src/v/transform/rpc/logger.cc, src/v/transform/rpc/logger.h, src/v/transform/rpc/rpc.json, src/v/transform/rpc/serde.cc, src/v/transform/rpc/serde.h, src/v/transform/rpc/service.cc, src/v/transform/rpc/service.h, src/v/transform/rpc/tests/CMakeLists.txt, src/v/transform/rpc/tests/transform_rpc_test.cc
This introduces the internal RPCs needed for producing the output of Wasm powered data transforms.
The justifications for using internal RPCs instead of the Kafka API:
- Our internal RPC client is not designed to be low latency or high throughput
- Using internal RPCs allows us to use a seperate set of accounting, limits, quotas and metrics specific to transforms
- Internal RPCs allows us to re-use internal authentication mechanism (mTLS, etc) instead of needing to mess with ephemeral credentials
* none
=> Introduce Internal Data Transform RPCs

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13748
Fixes: https://github.com/redpanda-data/redpanda/issues/13769,
=> [v23.2.x] tests: clean all nodes on first start in Redpanda service

src/go/rpk/pkg/adminapi/api_broker.go, src/go/rpk/pkg/cli/cluster/maintenance/enable.go, src/go/rpk/pkg/cli/cluster/maintenance/status.go, src/v/redpanda/admin/api-doc/broker.json, src/v/redpanda/admin_server.cc, tests/rptest/clients/rpk.py, tests/rptest/tests/maintenance_test.py
Some of the fields in broker maintenance status are reported based on the node health report. If a node is unavailable then its health is not reported. This PR changes the output of `/v1/brokers` & `/v1/maintenance_status`  admin apis to account for not present health report. Now if values based on maintenance report are unavailable they are simply not included into `maintenance_staus` JSON reply. 
Fixes: #13239 
- fixes incorrect reporting of maintenance statues if a node is stopped
=> Do not always report all fields in maintenance status

src/v/storage/tests/log_segment_appender_test.cc
adds some test context in case of failure of the test `test_concurrent_append_flush`
The core issue is that the appender inflights list is expected to be empty at that point in the test.
Related to #13035 
* none
=> storage/log_segment_appender_test: add test context for run_concurret_append_flush

tests/rptest/services/admin_ops_fuzzer.py
When topic is removed it must not be present in Kafka metadata. Added validation of Kafka metadata output before proceeding to validation of admin API output.
Fixes: #13638
- none
=> tests/admin_ops: check if topic is not listed when removed

tests/rptest/tests/consumer_offsets_consistency_test.py
Made timeouts a bit longer for release builds and much longer for slow debug builds.
Fixes: #13401
- none
=> tests: adjusted timeouts in test_flipping_leadership test

tests/rptest/tests/topic_creation_test.py
Nothing in this test guarantees that the partition manifest will be uploaded before its end, so it's appropriate to just ignore the anomaly.
Fixes #13646
* none
=> rptest: ignore missing ntp manifest in v22 upgrade test

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13748
=> [v23.1.x] tests: clean all nodes on first start in Redpanda service

src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_partition.h
In order to create a new materialised segment, one needs to grab units
from `materialized_resources` first. This is an async operation. By the
time units are acquired, said segment might have already been via a
different code path, resulting in the assertion in
`remote_partition::materialize_segment` triggering.
`remote_partition::aborted_transactions` was particularly susceptible to
this.
This patch fixes the issue by checking for the existence of the segment
and creating a segment (if needed) in the same scheduling task.
Functionally, for the read path, nothing should change.
* Fix race leading to assertion on materialisation of cloud storage segments
=> cloud_storage: fix segment materialisation race

src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_partition.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/13796
=> [v23.2.x] cloud_storage: fix segment materialisation race

tests/rptest/redpanda_cloud_tests/cloudv2_object_store_blocked.py, tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/services/provider_clients/ec2_client.py
Add ability to block write access to tiered storage s3 bucket. This is required for high throughputs phase 2 testing
- none
=> ht-phase-2: Block s3 TS bucket using a bucket policy

src/v/storage/log_housekeeping_meta.h, src/v/storage/log_manager.cc
Fixes iteration over a suspension point for apply_segment_ms() by introducing a new flag, bflags::lifetime_checked, and marking log handles as it rotates _logs_list.
Fixes #13589 
* fixes a use_after_free due to interaction with iterators and suspension points.
=> log_manager::housekeeping_scan iteration with suspension point fix

src/v/net/server.cc, src/v/net/server.h
server is shutdown in 2 phases. A synchronous call to `shutdown_input` where the listening sockets are closed followed a call to `wait_for_shutdown` and waiting on the return future. This leaves an opportunity for a race condition to occur.
Specifically, when the following sequence of events is observed:
1. `server::accept_finish` coroutine is called and suspended just before a new connection is added to the `server::_connections` list.
2. `server::shutdown_input` is called, connections from `server::_connections` are closed. Note that the incoming connection caused by the event above isn't yet added to that list.
3. `server::accept_finish` coroutine is resumed, the `server::_conn_gate` is open and the connection is serviced as usual.
4. `server::wait_for_shutdown` is called, and is …
=> net: fix shutdown and accept connection race

tests/rptest/tests/random_node_operations_test.py
to debug a panic crash in KgoVerifierConsumerGroupConsumer
* none
=> ducktape/node_operations: enable debug logging for kgo consumer

src/v/model/CMakeLists.txt, src/v/model/record.cc, src/v/model/record.h, src/v/model/tests/record_batch_test.cc
Introduce a simple iterator over a batch instead of using the `for_each` callbacks.
The `for_each` callbacks aren't coroutine friendly and this utility will simplify a bunch of 
callsites that mix coroutines and callbacks because of the `for_each_record` style of iteration.
* none
=> Introduce model::batch_record_iterator

tests/rptest/tests/consumer_offsets_consistency_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13756
Fixes: https://github.com/redpanda-data/redpanda/issues/13800,
=> [v23.2.x] tests: adjusted timeouts in test_flipping_leadership test

src/v/cloud_storage/types.cc, src/v/cloud_storage/types.h
When a type inherits from `serde::envelope` and doesn't define it's own comparison operator, `serde::envelope::operator==` ends up being used. Weirdness ensues after that.
Fixes #13760
* none
=> cloud_storage: add default eq operator for cloud serde types

src/go/k8s/config/rbac/bases/operator/role.yaml, src/go/k8s/controllers/redpanda/redpanda_controller.go
Configuring ingress in console subchart from Redpanda helm chart needs RBAC rules, so that flux controller can read, update and delete.
* Allow console ingress reconciliation using Redpanda custom resource
=> k8s: Allow ingress resource reconciliation in Redpanda controller

src/v/cloud_storage/tests/topic_recovery_service_test.cc, src/v/cluster/controller.cc, src/v/cluster/controller.h, src/v/cluster/topics_frontend.cc, src/v/cluster/topics_frontend.h, src/v/kafka/server/handlers/create_topics.cc, src/v/redpanda/application.cc, tests/rptest/tests/topic_creation_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13657
=> [v23.2.x] cluster/topics_frontend: Move some topic preprocessing into create_topics

tests/rptest/services/redpanda.py
Use the number of objects to apply a timeout, raise the default timeout to 5 minutes
It uses the number of objects, but a better metric would be to the aggregate size of objects
Fixes #13236 #12320
* none
=> services/redpanda.py: make _get_object_storage_report dynamic

src/v/cloud_storage/tests/tx_range_manifest_test.cc, src/v/kafka/protocol/schemata/generator.py, src/v/kafka/protocol/wire.h, src/v/utils/fragmented_vector.h, src/v/utils/tests/fragmented_vector_test.cc
`k/protocol/wire/read_array` now supports a template parameter for return type instead of `std::vector`.
* Requires `push_backable`
* Conditionally reserves space where `container::reserve` is supported
Rebase #11181
* Drop the last commit since which container to use is contentious
* Don't add `fragmented_vector::operator->` since it was added in #11691
* Improve `make_fragmented_vector` in `tx_range_manifest_test.cc`
* none
=> k/protocol && utils/fragmented_vector improvements

src/v/cloud_storage/tests/s3_imposter.cc, src/v/cloud_storage/tests/s3_imposter.h, src/v/cloud_storage/tests/topic_recovery_service_test.cc
FIXES https://github.com/redpanda-data/redpanda/issues/13794
In topic recovery tests some assertions simply wait for a count of requests made to S3 imposter. This may cause tests to fail when requests not related to the test are observed by the imposter, throwing off the expected count.
This change adds an optional predicate to the assertion so that the request count can be matched after filtering for specific requests by URL, method etc.
* none
=> cloud_storage: Match requests using URL during topic recovery tests

tests/rptest/tests/partition_force_reconfiguration_test.py
Post restart, the test was failing to achieve stable leadership because of low timeout. Restarted nodes are not seeing fresh health reports with updated leadership information. Since health reports are refreshed every 10s, we need to bump the wait timeout to factor in multiple health reports incase the first one is stale.
Fixes: https://github.com/redpanda-data/redpanda/issues/13051
* none
=> ducktape: bump timeout in force_reconfiguration test

src/v/cluster/health_manager.cc, src/v/model/ktp.h, src/v/model/namespace.h, src/v/transform/rpc/client.cc, src/v/transform/rpc/client.h, src/v/transform/rpc/deps.cc, src/v/transform/rpc/deps.h, src/v/transform/rpc/rpc.json, src/v/transform/rpc/serde.h, src/v/transform/rpc/service.cc, src/v/transform/rpc/service.h, src/v/transform/rpc/tests/transform_rpc_test.cc
This patch set supports storing Wasm binaries in an internal topic.
This topic is not user facing (it's in the Redpanda namespace) and uses internal RPCs for reading/writing.
The topic is compacted and we support deleting binaries by tombstoning.
* none
=> transform: Support wasm binary CRUD

src/v/cloud_storage/cache_service.cc, src/v/cloud_storage/cache_service.h
When an exhaustive trim fails, a common reason for this is .part files which were identified to be deleted but during the trim they were renamed to chunk/segment files.
This change adds a flag to the trim result, if the trim fails to free enough space and a tmp file was missed during the trim, the log is downgraded to INFO.
Additionally we catch filesystem error separately and if the error caught during a trim is not an FS error, it is logged as an error.
An FS error not related to a temp file is also logged as an error.
FIXES https://github.com/redpanda-data/redpanda/issues/13304
* none
=> cloud_storage: Log trim failure based on file type

src/v/cluster/metadata_dissemination_service.cc
After change from `std::vector` to `ss::chunked_fifo` to keep the updates in metadata dissemination service `update_metadata` we lost ability to retry metadata dissemination requests as pending updates were moved to lambda capture list. This way the next retry did not have any updates to deliver.
Fixes: #13051
- none
=> c/md_dissemination: fixed retrying leadership dissemination

src/v/redpanda/admin_server.cc
It may sometimes happen that the admin API request will be processed while Redpanda is shutting down or it is in the middle of reconfiguration with stale metadata. In this case an RPC client to currently reported leader may no longer be available. In this case we should request client to retry.
Fixes: #13855
- none
=> admin_server: map `missing_node_rpc_client` to service unavailable

src/v/cloud_storage/read_path_probes.cc
If the 'aggregate_metrics' configuration option is set aggregate metrics by id.
* none
=> cloud_storage: Aggregate read path metrics by partition

src/v/cluster/CMakeLists.txt, src/v/config/CMakeLists.txt, src/v/kafka/client/CMakeLists.txt, src/v/security/CMakeLists.txt, src/v/security/config_bsl.cc, src/v/security/config_rcl.cc, src/v/security/gssapi_principal_mapper.cc, src/v/security/gssapi_principal_mapper.h, src/v/security/mtls.cc, src/v/security/tests/CMakeLists.txt
Split `v::security_config` out from `v::security`.
`v::config` depends on `v::security_config` instead of `v::security`.
This will allow `v::security` to depend on `v::http`
* none
=> security: Break dependency from `v::config` to `v::security`

src/v/cloud_storage/tests/tx_range_manifest_test.cc, src/v/kafka/protocol/schemata/generator.py, src/v/kafka/protocol/wire.h, src/v/utils/fragmented_vector.h, src/v/utils/tests/fragmented_vector_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13854
=> [v23.2.x] k/protocol && utils/fragmented_vector improvements

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/raft/append_entries_buffer.cc, src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/group_manager.cc, src/v/raft/group_manager.h, src/v/raft/replicate_entries_stm.cc, src/v/raft/tests/basic_raft_fixture_test.cc, src/v/raft/tests/raft_fixture.h, src/v/raft/tests/simple_raft_fixture.h, src/v/redpanda/application.cc, tests/rptest/tests/raft_periodic_flush_test.py, tests/rptest/tests/storage_resources_test.py
Added a timer which flush Raft underlying log if not flushed bytes exceeds the configured threshold. 
- Flushing Raft underlying logs will allow stms to create snapshots and minimize amount of data read during redpanda startup
=> Added size bytes background flush to Raft

cmake/dependencies.cmake
Pulls in some fixes and a few c-api features we're going to need in
other PRs
* none
=> cmake: Upgrade wasmtime

src/go/rpk/pkg/cli/transform/buildpack/buildpack.go, src/go/rpk/pkg/cli/transform/init.go, src/go/rpk/pkg/cli/transform/project/project.go, src/go/rpk/pkg/cli/transform/template/golang/README.md, src/go/rpk/pkg/cli/transform/template/golang/transform.gosrc, src/go/rpk/pkg/cli/transform/template/golang_template.go, src/go/rpk/pkg/cli/transform/transform.go, src/go/rpk/pkg/out/out.go
Introduce the init command for data transformed
This will initialize a go project. 
More information is available in the [RFC](https://docs.google.com/document/d/1l9wuOmR_iQoDS-02FUQhOJ6mzV02H26Xmd5bAd8QB6Q/edit#heading=h.erwed2nknsfv)
* none
=> rpk/transform: introduce init command

src/v/storage/log_housekeeping_meta.h, src/v/storage/log_manager.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13615
Fixes #13830
=> [v23.2.x] log_manager::housekeeping_scan iteration with suspension point fix

src/v/kafka/server/handlers/handler_probe.cc, src/v/kafka/server/handlers/handler_probe.h
Backport of PR: https://github.com/redpanda-data/redpanda/pull/13549
Fixes: https://github.com/redpanda-data/redpanda/issues/13721
=> [v23.2.x] kafka: Expose per handler produce/fetch metrics on public_metrics

src/v/config/property.h, src/v/kafka/server/handlers/describe_configs.cc, src/v/redpanda/admin_server.h, src/v/security/acl.h, src/v/serde/rw/chrono.h, src/v/transform/tests/transform_manager_test.cc, src/v/utils/type_traits.h, src/v/wasm/ffi.h, src/v/wasm/wasmtime.cc
=> treewide: unify dependent_false implementations

src/v/rpc/transport.cc, src/v/rpc/transport.h
`ss::scattered_message` is already a pimpl class so there is no need for the extra indirection to make moves quicker. All it adds is additional allocations and fragmentation.
* none
=> Remove unneeded unique_ptr from transport::entry

tests/rptest/scale_tests/tiered_storage_reader_stress_test.py, tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13246
Fixes: https://github.com/redpanda-data/redpanda/issues/13287,
=> [v23.2.x] rptest: tweak cloud storage reader stress test 

tests/rptest/tests/topic_creation_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13752
Fixes: https://github.com/redpanda-data/redpanda/issues/13808,
=> [v23.2.x] rptest: ignore missing ntp manifest in v22 upgrade test

tests/rptest/services/redpanda.py
Setting `allow_fail` flag in ducktape `RemoteAccount::ssh_capture` makes the function to ignore an error. This prevented the `try except` block from intercepting an error and returning `None`.
By not allowing command to fail we make the error handling correct.
Fixes: #8362
- none
=> tests/redpanda: do not allow getting redpanda pid cmd to fail

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13920
Fixes: https://github.com/redpanda-data/redpanda/issues/13944,
=> [v23.2.x] tests/redpanda: do not allow getting redpanda pid cmd to fail

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13920
Fixes: https://github.com/redpanda-data/redpanda/issues/13946,
=> [v23.1.x] tests/redpanda: do not allow getting redpanda pid cmd to fail

src/v/kafka/server/handlers/handler_probe.cc, src/v/kafka/server/handlers/handler_probe.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/13549 
Fixes https://github.com/redpanda-data/redpanda/issues/13721
=> [v23.1.x] kafka: Expose per handler produce/fetch metrics on public_metrics

tests/rptest/tests/workload_license.py, tests/rptest/tests/workload_upgrade_runner_test.py
Only LicenceWorkload is failing in the set of workloads.
Since the framework is useful to catch inconsistencies during an upgrade, this pr temporarily disables LicenceWorkload to re-enable the rest of the test
Related to #13180 
* none
=> tests/workload_upgrade_runner_test: re-enabled test

src/v/pandaproxy/schema_registry/store.h, src/v/pandaproxy/schema_registry/test/store.cc
A subject may exist internally due to compatibility config or soft-deleted versions, but should not always be returned in the list of subjects.
This may fix #13376
* Schema Registry: `GET /subjects` no longer returns a subject that has no versions or only deleted versions (unless `?deleted=true`)
=> schema_registry/store: Don't return a subject with no versions

src/v/pandaproxy/schema_registry/error.cc
The compatibility levels must be specified in uppercase; improve the error message by uppercasing the levels.
Fixes #13873
* Schema Registry: Improve error message for invalid compatibility level
=> schema_registry: Fix error message for compatibility

src/v/cloud_storage/cache_service.cc, src/v/cloud_storage/cache_service.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/13892
Fixes: https://github.com/redpanda-data/redpanda/issues/13906,
=> [v23.2.x] cloud_storage: Log trim failure based on file type

src/v/pandaproxy/schema_registry/seq_writer.cc, src/v/pandaproxy/schema_registry/seq_writer.h
* Log if acquiring a semaphore will block
* Log if `project_ids` fails
* none
=> schema_registry: Improve logging

src/v/kafka/client/broker.cc, src/v/kafka/client/broker.h, src/v/kafka/client/client.cc, src/v/kafka/client/client.h, src/v/kafka/client/client_fetch_batch_reader.cc, src/v/kafka/client/sasl_client.cc, src/v/kafka/client/transport.h
Add the client identifier to logs, if it was provided.
* kafka/client logs now include the client identifier (e.g., `schema_registry_client`, `pandaproxy_client`)
=> kafka/client: Log client identifier

src/go/rpk/pkg/cli/container/common/client.go, src/go/rpk/pkg/cli/container/common/common.go, src/go/rpk/pkg/cli/container/container.go, src/go/rpk/pkg/cli/container/purge.go, src/go/rpk/pkg/cli/container/start.go, src/go/rpk/pkg/cli/container/status.go, src/go/rpk/pkg/cli/container/stop.go, src/go/rpk/pkg/cli/profile/create.go, src/go/rpk/pkg/cli/profile/delete.go, src/go/rpk/pkg/cli/root.go
This PR introduces a new behaviour to `rpk container`:
Now, when the user creates a container using `rpk container start`, rpk will create and use a profile with the kafka broker and admin API and schema registry addresses so the user can start using rpk seamlessly without having to worry about the flags nor the environment variables
```
$ rpk container start -n 3
Checking for a local image...
Creating network redpanda
Starting cluster...
Waiting for the cluster to be ready...
Cluster started!
NODE-ID  STATUS   KAFKA-ADDRESS    ADMIN-ADDRESS    PROXY-ADDRESS
0        running  127.0.0.1:36131  127.0.0.1:46387  127.0.0.1:44137
1        running  127.0.0.1:38361  127.0.0.1:44093  127.0.0.1:42481
2        running  127.0.0.1:40911  127.0.0.1:37757  127.0.0.1:36899
Created "rpk-container" …
```
=> rpk: integrate profiles with `rpk container`

.github/CODEOWNERS
Most of the changes going to this folder are relevant to core's team and not to devprod. Instead of assigning reviewers from devprod, we'll wait for devprod folks to be manually assigned on an as-needed basis
* none
=> codeowners: remove devprod for /tools folder

src/v/archival/ntp_archiver_service.cc, src/v/cloud_storage/async_manifest_view.cc, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/types.h
Previously, `async_manifest_view` would print lots of error logs on
shutdown. This is because we first shut-down the client pool and then
stop the async manifest view. The result is that calls into remote throw
`ss::broken_semaphore`, then `async_manifest_view` would flatten that to
`error_outcome::failure` and error log it in various places.
This patch adds a new error outcome: `shutting_down` and teaches the
`async_manifest_view` how to handle it without error logging. We map the
shut down exceptions to this new error code in
`async_manifest_view::hydrate_manifest`. From there, upstream call sites
have been updated. The next patch will teach external users of
`async_manifest_view` to handle the new error code.
This fixes all instances of bad error logs coming from the …
=> cloud_storage: fix error logging on shutdown

src/v/cluster/drain_manager.cc, src/v/cluster/drain_manager.h, src/v/cluster/members_manager.cc, src/v/cluster/partition_balancer_backend.cc, src/v/cluster/partition_balancer_planner.cc, src/v/cluster/partition_balancer_planner.h, src/v/cluster/tests/partition_balancer_planner_test.cc, src/v/redpanda/admin_server.cc, tests/rptest/tests/partition_balancer_test.py
Maintenance mode (triggers re-election to move leadership from the partitions hosted on the node in maintenance mode) doesn't do anything which couldn't happen naturally in the cluster when the mode is off.
So the balancer can't be affected if it ignores the mode.
Fixes #12069
* none
=> Make maintenance mode opaque to the partition balancer

src/go/rpk/pkg/cli/transform/init.go
This is the more common behavior in RPK, and we want to align this
command with that.
* none
=> rpk/transform/init: bail on empty name input

src/v/transform/tests/test_fixture.cc, src/v/transform/tests/test_fixture.h, src/v/transform/transform_processor.cc, src/v/utils/mutex.h, src/v/wasm/CMakeLists.txt, src/v/wasm/api.h, src/v/wasm/cache.cc, src/v/wasm/cache.h, src/v/wasm/tests/CMakeLists.txt, src/v/wasm/tests/wasm_cache_test.cc, src/v/wasm/tests/wasm_fixture.cc, src/v/wasm/tests/wasm_fixture.h, src/v/wasm/tests/wasm_transform_test.cc, src/v/wasm/wasmtime.cc
This patch set introduces a mechanism for caching factories (executable memory) and engines (linear vm memory).
We do this by wrapping a whole runtime and providing all the caching logic transparently.
Engines are able to be multiplexed on the same core as to reuse the memory resources.
Caching works via weak and shared pointers, otherwise the bookkeeping will be forced upon all callers.
When a weak pointer expires, we still have map entries holding the weak pointers, so there is a GC 
process to cleanup these entries that runs at a very low interval.
There are also a couple of PRs to cleanup mutex and remove some vestigal methods from the wasm engine API.
* none
=> wasm: Introduce Factory + Engine Caching

tests/rptest/services/redpanda.py
Previously an assertion message was accessing field `name` which doesn't exists.
- none
=> tests/redpanda: fixed assertion message accessing not existing field

src/v/cloud_storage/tests/topic_recovery_service_test.cc, src/v/cluster/controller.cc, src/v/cluster/controller.h, src/v/cluster/topics_frontend.cc, src/v/cluster/topics_frontend.h, src/v/kafka/server/handlers/create_topics.cc, src/v/redpanda/application.cc, tests/rptest/tests/topic_creation_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13657 
Fixes #13846
=> [v23.1.x] cluster/topics_frontend: Move some topic preprocessing into create_topics

src/v/archival/ntp_archiver_service.cc, src/v/cloud_storage/types.h
Force callers to handle failures or to be explicit about why failures aren't important.
* none
=> cloud_storage: add nodiscard to download and upload result

src/go/rpk/pkg/adminapi/api_transform.go, src/go/rpk/pkg/cli/transform/deploy.go, src/go/rpk/pkg/cli/transform/transform.go
Support deploying a transform to the cluster.
For users following the well trodden path of `rpk transform init`, `rpk transform build`, `rpk transform deploy`,
They don't have to specify any command line args if the `transform.yaml` file is filled out.
Additionally we support no configuration file deployments for users not using `rpk` to build their code (i.e. using
an existing toolchain directly). This is possible by passing all configuration files as command line args.
If both a `transform.yaml` file and command line args are specified we use the file as the base configuration
and the flags override values.
* none
=> rpk/transform: introduce deploy command

src/v/pandaproxy/schema_registry/store.h, src/v/pandaproxy/schema_registry/test/store.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13911
Fixes: https://github.com/redpanda-data/redpanda/issues/13956,
=> [v23.1.x] schema_registry/store: Don't return a subject with no versions

src/v/cluster/node/types.h, src/v/cluster/tests/serialization_rt_test.cc, src/v/cluster/types.h, src/v/compat/check.h, src/v/features/feature_table_snapshot.h, src/v/kafka/server/tests/usage_manager_test.cc, src/v/kafka/server/usage_aggregator.h, src/v/net/unresolved_address.h, src/v/serde/envelope.h, src/v/utils/delta_for.h
Previously, if a sub-class of envelope did not define its own equality
operator, the comparison would ignore all state from the derived class
and use the defaulted comparison operator of `serde::envelope`. This
caused comparison to behave in unexpected ways.
```
struct foo : serde::envelope<foo, ...> {
int x;
};
void compare() {
return foo{.x = 1} == foo{.x = 2}; // oops - uses serde::envelope::operator== and ingnores foo::x
}
```
The goal of this patch is to force serde types to overload their
comparison operators iff they wish to be comparable. To this end, the
implementation of said operators in `serde::envelope` is templated in
order to distinguish implict calls when the operator is generated for
the base class and accidental calls from sub classes that didn't
implement their …
=> serde: fix serde default comparison operator foot gun

src/v/archival/ntp_archiver_service.cc, tests/rptest/tests/tiered_storage_model.py
Since https://github.com/redpanda-data/redpanda/pull/13720, `remote::delete_objects` can handle inputs of any size and will split them in batches of the appropriate size for each backend.
Simplify the code by removing the unnecessary duplication of the batching logic.
* none
=> archival: rely on the batch formation logic in remote

tests/rptest/scale_tests/cloud_storage_compaction_test.py
The log message `s3 - s3_client.cc:426 - The specified S3 bucket, panda-bucket-335a4708-61cc-11ee-9168-bd94df9c8361, could not be found. Ensure that your bucket exists and that the cloud_storage_bucket and cloud_storage_region cluster configs are correct.` sometimes causes the scale test to fail. It's not clear why this happens. The problem is not causing the test to actually fail because it is  transient. The upload is retried and the data is getting uploaded. We can expect things like this to happen on CDT from time to time. It's not an indication of a bug in Redpanda.
Fixes #13921
* none
=> rptest: Ignore transient log error message

src/v/archival/ntp_archiver_service.cc
The 'ntp_archiver_service::upload' method is used by the adjacent segment merger. It's an api for external services that need to upload segments. The problem is that this method doesn't utilize the segment stats to validate segment metadata. Normal upload path uses these stats to check if the replicated metadata is correct.
This PR adds similar check to the 'upload' method.
Fixes https://github.com/redpanda-data/redpanda/issues/13834
* none
=> archival: Audit meta in adjacent merger uploads

src/go/k8s/apis/redpanda/v1alpha1/redpanda_clusterspec_types.go
The Redpanda resource should behave the same as our Helm chart, which enables `storage.persistentVolume` by default.
Currently, if you don't set this explicitly in the Redpanda resource, you get this error:
```
The Redpanda "redpanda" is invalid: spec.clusterSpec.storage.persistentVolume.enabled: Required value
```
Link to change: https://github.com/redpanda-data/redpanda/blob/25f4e7438b1a83855e209a9fbd7d070cdab40a8b/src/go/k8s/apis/redpanda/v1alpha1/redpanda_clusterspec_types.go#L311
* When `storage.persistentVolume.enabled` is omitted in the Redpanda resource, we now fall back to the default in the Redpanda Helm chart.
=> Use Helm default for persistentVolume.enabled

tests/setup.py
Redpanda Ducktape repo has been restructured with new PR workflow and updated to new version from upstream with our changes incorporated into separate branches (details can be found [here](https://github.com/redpanda-data/devprod/issues/836))
* none
=> rptest: Update version of ducktape to the tip of the 0.8.x branch

src/v/cluster/members_backend.cc, src/v/cluster/members_backend.h
When all reallocations are finished and allocator state for node being decommissioned is empty it is possible to remove node from the cluster. The removal is independent from other nodes being recommissioned.
Members backend processes one update at a time and it might happened that decommissioning operation was queued after the recommission one and couldn't have been finished before the recommissioning was finished.
Change the logic in `members_backend` to check if there are any decommission operation that may be finished before executing current node update reconfigurations. This way node decommission operation will be finished independently from other not related operations.
Fixes: #13637
* Faster node decommissioning
=> c/members_backend: prioritize removing nodes when decomm isfinished

src/v/raft/heartbeats.h
Since heartbeats reply/request is deserialized on the RPC connection core
which may differ from the core where it is processed it should copy
buffer while deserializing the request as the underlying buffer might
have been shared on the originating core.
Fixes: #13447
- fixes segmentation fault that may happened when `heartbeat_reply_v2` was used on a different core than it was created.
=> r/heartbeats: do not use iobuf::share in cursor

tests/rptest/redpanda_cloud_tests/cloudv2_object_store_blocked.py, tests/rptest/services/provider_clients/gcp_client.py, tests/setup.py
For HT phase 2 block object store test to support GCP as well as AWS
Requires the gcp ducktape service account to have editor permissions
- none
=> ht-phase2: support blocking gcp object store

src/go/rpk/pkg/cli/root.go, src/go/rpk/pkg/cli/transform/build.go, src/go/rpk/pkg/cli/transform/buildpack/buildpack.go, src/go/rpk/pkg/cli/transform/init.go, src/go/rpk/pkg/cli/transform/transform.go
Introduce a command to build a WASI binary using the tinygo compiler (that we vendor as a "buildpack").
We use performance optimized defaults, but allow users to pass custom flags to tinygo via `--` syntax as documented in the help text.
* none
=> rpk/transform: Introduce build command

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/config/node_config.cc, src/v/config/node_config.h, src/v/features/feature_table.cc, src/v/features/feature_table.h, src/v/redpanda/CMakeLists.txt, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h, src/v/redpanda/application.cc, src/v/redpanda/application.h, src/v/resource_mgmt/io_priority.h, src/v/transform/CMakeLists.txt, src/v/transform/api.cc, src/v/transform/api.h, src/v/transform/fwd.h, src/v/transform/rpc/service.cc, src/v/transform/tests/transform_manager_test.cc, src/v/transform/tests/transform_processor_test.cc, src/v/transform/transform_manager.cc, src/v/transform/transform_manager.h, src/v/transform/transform_processor.cc, src/v/transform/transform_processor.h, src/v/wasm/cache.cc, src/v/wasm/cache.h, src/v/wasm/fwd.h
This PR hooks up the transform subsystem into Redpanda
This introduces the service for the transform subsystem, which essentially wraps all the
dependencies on the rest of the system and injects them into the rest of the transform subsystem.
Additionally, the transform service is responsible for handling admin API commands, two of which
implemented in this PR, deploy + delete.
We also introduce configuration for enabling transforms + wasm, both a feature to protect during rolling upgrades AND a cluster configuration value to turn it on. There is also a node local configuration value to force disable transforms + wasm. In case of some incident where the wasm VM is bringing down the whole cluster, this is a useful safety knob to disable wasm (cluster configuration requires a quorum to be up …
=> transform: hook up transform subsystem

tests/rptest/services/redpanda_installer.py
Try to read the list of releases from the env variable `RP_GIT_RELEASED_VERSIONS`
and fallback to github. 
Increase the TTL of the local cache from 5 min to 30 min, to reduce the overall number of calls to api.github.com
Fixes #13861 
* none
=> Issue/13861/reduce api.github.com calls to fetch releases

tests/rptest/services/templates/omb_workload.yaml
In case workload dict not suppliyng use_randomized_payloads var, use
payload_file to load the sample payload data.
Fixes: #13702 
* none
=> rptest: Fix OMB workload add payload_file for non randomized payloads

tests/rptest/tests/cloud_storage_chunk_read_path_test.py
Tests which use chunk observer should wait for it to stop after the stop command is issued, to avoid the underlying set changing while it is being read from.
FIXES #13233 
* none
=> cloud_storage/ducktape: Wait for chunk observer to stop

tests/rptest/tests/raft_periodic_flush_test.py
Consumer is already starter after returning from
`EndToEndTest::start_consumer` method.
Fixes: #14011
- none
=> tests: do not start consumer twice

src/v/serde/rw/iobuf.h
Just move it instead.
`share()`ing an iobuf is expensive as it will always cause allocations
for the `io_fragment`s and potentially also an extra allocation for the
underlying `ss::temporary_buffer` deleter control block if it hasn't
been shared before.
* none
=> serde: Don't share an EOL iobuf

src/v/cluster/log_eviction_stm.cc, src/v/cluster/partition.cc, src/v/kafka/server/handlers/delete_records.cc, src/v/storage/disk_log_impl.cc, tests/rptest/clients/types.py, tests/rptest/tests/delete_records_test.py, tests/rptest/tests/retention_policy_test.py, tools/offline_log_viewer/kvstore.py
When topics were created with `cleanup.policy=compact` we wouldn't
allocate the `log_eviction_stm` as it wouldn't have any work to do
anyway. However, if the `cleanup.policy` is changed to `delete` or
`compact,delete` we still wouldn't allocate it. This leads to a bug
where trim-prefix command isn't working and neither topic retention
settings are applied until a node is restarted.
Since we don't have a way to enable/disable STMs at runtime, this commit
enables the log eviction stm unconditionally and checks the actual topic
properties whether trim-prefix is support or not.
Additional test coverage for this functionality is in #13780
Fixes #13588 
* none
=> cluster: always create the log eviction stm

tests/setup.py
This reverts commit 74a7799183e9b690841538a8938e4a8ca07f8526.
Slack [thread](https://redpandadata.slack.com/archives/C02LZGSS66M/p1696980673546449).
* none
=> Revert "rptest: Update version of ducktape to the tip of the 0.8.x

src/v/rpc/connection_cache.cc, src/v/rpc/connection_cache.h, src/v/rpc/connection_set.cc
Fixes the following within `rpc::connection_cache`;
- Fixes the assertion failure from #13447 .
- Avoids creating clients when the connection_cache is shutting down.
- Prevents the sharded connection_cache from being stopped while there are
in-flight tasks for it.
- Acquires the mutex before accessing any shared state on the coordinator shard.
* none
=> Various `rpc::connection_cache` fixes

src/v/wasm/tests/wasi_logs_test.cc, src/v/wasm/wasi.cc
Prevent control characters, invalid utf8 and long lines from being logged due to wasm.
Fixes: https://github.com/redpanda-data/core-internal/issues/807
* none
=> wasm: validate wasi logs

src/v/kafka/client/fetcher.cc, src/v/kafka/protocol/fetch.h, src/v/kafka/protocol/schemata/generator.py, src/v/kafka/server/handlers/fetch.cc, src/v/utils/fragmented_vector.h
Avoid oversize allocations by converting `fetchable_partition_response` to ``small_fragment_vector``
Fixes #11017
* Kafka: Avoid very large contiguous allocations during fetch.
=> k/p/gen: Use `fragmented_vector` for  `fetchable_partition_response`

src/v/cloud_storage_clients/s3_client.cc, tests/rptest/services/redpanda.py
On AWS S3 we sometimes getting transient errors like this and it doesn't lead to test failure because Redpanda retries the request. 
Fixes #13696
* none
=> rptest: Add S3 internal server error to allowed log list

tests/rptest/services/admin_ops_fuzzer.py
More fuzzing the better. Now this successfully catches the issue described #13588 too.
* none
=> rptest: fuzz create topic config properties

src/v/cloud_storage_clients/s3_client.cc, tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14033
Fixes: https://github.com/redpanda-data/redpanda/issues/14109,
=> [v23.2.x] rptest: Add S3 internal server error to allowed log list

src/v/raft/recovery_stm.cc
Validation in `suppress_heartbeats_guard` checks if a node is a leader when heartbeat is suppressed. The assertion is triggered if node suppressing heartbeat is no longer a leader. Added a check immediately preceding heartbeat suppression in `recovery_stm`. Recovery STM works outside of the raft mutex and it may be the case that leadership was lost between the fiber scheduling points.
Fixes: #14066
- none
=> r/recovery_stm: check if node is a leader before sending request

src/v/kafka/client/fetcher.cc, src/v/kafka/protocol/fetch.h, src/v/kafka/protocol/schemata/generator.py, src/v/kafka/server/handlers/fetch.cc, src/v/utils/fragmented_vector.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/11181
Fixes: https://github.com/redpanda-data/redpanda/issues/14105,
=> [v23.2.x] k/p/gen: Use `fragmented_vector` for  `fetchable_partition_response`

src/v/cloud_storage/materialized_resources.cc, src/v/cloud_storage/materialized_resources.h, src/v/cloud_storage/read_path_probes.cc, src/v/cloud_storage/read_path_probes.h, src/v/cloud_storage/remote.cc, src/v/cloud_storage/tests/remote_test.cc, src/v/config/configuration.cc, src/v/config/configuration.h, tests/rptest/services/redpanda.py, tests/rptest/tests/e2e_shadow_indexing_test.py
Add new configuration parameters `cloud_storage_max_download_throughput_per_shard` and `cloud_storage_throughput_limit_percent` that adds throughput limits for downloads. 
Implement throttled `input_stream` and use it for segment downloads.
The `cloud_storage_max_download_throughput_per_shard` parameter is a hard limit. By default it's set to 1GiB/second per shard. This value is intentionally too large. The parameter is mostly used for testing (it's difficult to setup the throttling using the value expressed in number of percent).
The `cloud_storage_throughput_limit_percent` is a relative throughput limit. The value is expressed as relative to disk speed. The disk speed is provided to redpanda using the `--io-properties-file` parameter. The code fetches the throughput value for the …
=> cloud_storage: Add S3 download throughput limit

src/v/kafka/server/connection_context.h, src/v/kafka/server/request_context.h, src/v/redpanda/tests/fixture.h, src/v/security/acl.cc, src/v/security/acl_store.h, src/v/security/authorizer.h, src/v/security/tests/authorizer_test.cc
This PR adds the `auth_result` structure and returns it from the authorizer security subsystem.  This structure contains all the necessary metadata needed for audit logging in regards to which ACL and resource pattern was matched that resulted in
the authZ decision (if any matched).
Force push `5cbd88a`:
- Changed auth_result to hold an `ss::sstring` vs `std::string_view`
Force push `e5b05bc`:
- Updates from PR comments
* None
=> Modify authz return path

src/v/storage/disk_log_impl.cc, src/v/storage/disk_log_impl.h, src/v/storage/log.h
Exposed method allowing caller to calculate a new start offset of a log that would provide desired data retention. The API is going to be used by controller backend to establish initial learner offset.
Fixes: #13707
- none
=> s/log: exposed `retention_offset` in `storage::log` api

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/config/tests/validator_tests.cc, src/v/config/validators.cc, src/v/config/validators.h, src/v/kafka/CMakeLists.txt, src/v/kafka/client/CMakeLists.txt, src/v/kafka/client/config_utils.cc, src/v/kafka/client/config_utils.h, src/v/kafka/client/test/CMakeLists.txt, src/v/kafka/client/test/test_config_utils.cc, src/v/kafka/server/audit_log_manager.cc, src/v/kafka/server/audit_log_manager.h, src/v/kafka/server/fwd.h, src/v/kafka/server/server.cc, src/v/kafka/server/server.h, src/v/kafka/server/tests/CMakeLists.txt, src/v/kafka/server/tests/audit_log_test.cc, src/v/kafka/types.h, src/v/model/namespace.h, src/v/pandaproxy/CMakeLists.txt, src/v/pandaproxy/rest/proxy.cc, src/v/pandaproxy/schema_registry/service.cc, src/v/pandaproxy/test/CMakeLists.txt, src/v/redpanda/application.cc, src/v/redpanda/application.h, src/v/redpanda/tests/fixture.h, src/v/security/audit/schemas/application_activity.h, src/v/security/audit/schemas/iam.h, src/v/security/audit/schemas/schemas.h
This pull request adds the backbone for what will eventually be the mechanism for which audit events will be batched and produced onto the audit log. It introduces a new service called the `audit_log_manager` which is responsible for a few things:
1. Managing the lifetime of a single Kafka client, which is allocated/deallocated when the global audit switch is toggled.
2. Creation of the audit topic, its properties and corresponding ACLs
3. Contains a mechanism for coalescing non-unique events to decrease the number of audit messages that will be produced.
4. Spawns new fibers (one per core) to periodically consume the batched audit events and send to the core responsible for producing them. This reduces the number of calls to that core and allows the coalescing logic more time to remove …
=> kafka: Initial work for adding support for audit logging

src/v/ssx/future-util.h
This PR adds `ss::sleep_aborted` to the list of shutdown exceptions which should be explicitly ignored in some contexts. Specifically we've seen (very occasional) "exceptional future ignored" errors of this type during ducktape node shutdown.
Per seastar docs:
```
class seastar::sleep_aborted
exception that is thrown when application is in process of been stopped
```
Fixes: #13272 
- none
=> future-utils: Add ss::sleep_aborted to list of shutdown exceptions

src/v/kafka/client/fetcher.cc, src/v/kafka/protocol/fetch.h, src/v/kafka/protocol/schemata/generator.py, src/v/kafka/server/handlers/fetch.cc, src/v/utils/fragmented_vector.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/11181
Fixes https://github.com/redpanda-data/redpanda/issues/14140
Fixes #14104
=> [v23.1.x] k/p/gen: Use `fragmented_vector` for  `fetchable_partition_response`

src/v/config/configuration.cc
This lets for cluster_config_test pick a valid value for this variable.
* none
=> config: add example for audit events

tests/rptest/redpanda_cloud_tests/observe_test.py, tests/rptest/services/redpanda_cloud.py
requires grafana token and grafana rules url added to duck tape globals - will raise separate PR for vtools changes
will check for redpanda alerts as well as agent alerts
- none
=> ht phase2: observe tests that check for firing alarms

tests/rptest/scale_tests/tiered_storage_cache_stress_test.py
the tests it taking slighlty more than expected. increasing the runtime_grace_factor increases the allowed timeout for the test
Fixes #13648 
* none
=> scale_tests/tiered_storage_cache_stress_test: increased grace_factor

src/go/transform-sdk/internal/testdata/CMakeLists.txt, src/go/transform-sdk/internal/testdata/build_all.sh, src/go/transform-sdk/internal/testdata/dynamic/transform.go, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/application.cc, src/v/wasm/CMakeLists.txt, src/v/wasm/allocator.cc, src/v/wasm/allocator.h, src/v/wasm/api.h, src/v/wasm/cache.cc, src/v/wasm/cache.h, src/v/wasm/tests/CMakeLists.txt, src/v/wasm/tests/wasm_allocator_test.cc, src/v/wasm/tests/wasm_cache_test.cc, src/v/wasm/tests/wasm_fixture.cc, src/v/wasm/tests/wasm_fixture.h, src/v/wasm/tests/wasm_transform_test.cc, src/v/wasm/wasmtime.cc, tests/rptest/tests/cluster_config_test.py
This PR hooks up a simple custom allocator with Wasmtime so that we use the seastar allocator (instead of mmap) to provide memory to wasm VMs.
There are two configuration knobs with buy in from product:
- `wasm_per_core_memory_reservation` the amount of memory to reserve in total per core
- `wasm_per_function_memory_limit` the amount of memory to allow per function to a single VM
The thinking here is that someday we can also allow per function memory limits and then have a more clever allocation scheme. 
See the commits for more details here - for now all functions in a cluster share the same memory limit.
* none
=> wasm: pool memory and limit VM max heap size

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
=> rptest: Add note to the test and mark it as ok_to_fail [ci-skip]

src/v/wasm/ffi.h, src/v/wasm/tests/ffi_helpers_test.cc, src/v/wasm/wasi.cc, src/v/wasm/wasi.h, src/v/wasm/wasmtime.cc
Implement poll_oneoff for sleeping. This allows for "sleeping" which
upstream golang assumes is present for it to work. Only sleeping is
required, which we implement via a noop that does nothing, as the clock
is fixed for each record that is being processed.
Upstream golang uses this function for usleep here:
https://github.com/golang/go/blob/7e1713e93c626f7026d1de09258f03748c726e79/src/runtime/os_wasip1.go#L165-L181
* none
=> wasm: minimal poll_oneoff for golang

src/v/cloud_storage_clients/tests/CMakeLists.txt, src/v/cloud_storage_clients/tests/exception_test.cc, src/v/cloud_storage_clients/util.cc, src/v/cloud_storage_clients/util.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/10909
Fixes: https://github.com/redpanda-data/redpanda/issues/14174,
=> [v23.1.x] cloud_storage: Handle nested benign exception

src/v/cluster/commands.h, src/v/cluster/types.cc, src/v/cluster/types.h
Introduced new extensible command representing requested partition replicas update. The new command is serde serializable and has extensible data structure. Additionally the command contains a flag expressing partition reconfiguration policy. For now the flag can have one of the following values:
```
Moving partition with full local retention policy will deliver all
partition data available locally on the leader to newly joining
learners. If tiered storage is disabled for a partition the move will
alawys be executed with full local retention.
full_local_retention = 0,
With target initial retention parittion move policy controller
backend will calulate the learner start offset based on the configured
learner initial retention configuration (either a global cluster property
or topic …
```
=> c/commands: introduced new update partition replicas command

tests/rptest/tests/cloud_storage_chunk_read_path_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14032
Fixes: https://github.com/redpanda-data/redpanda/issues/14088,
=> [v23.2.x] cloud_storage/ducktape: Wait for chunk observer to stop

src/v/archival/ntp_archiver_service.cc, src/v/archival/segment_reupload.cc, src/v/archival/tests/segment_reupload_test.cc
PR #9404 partially fixed the issue of compacted reupoads of the same size leading to gaps in the cloud log. However, the fix assumed the issue can only happen when one segment is selected for reupload. That's not the case. For example:
Node 1 segment layout: [0-3]
Node 2 segment layout: [0-2][3-3]
Node 1 does the initial upload of the offset range [0-3]. This is covered by just one segment. Then, Node 2 gains leadership. It decides to do a compacted re-upload for the [0-3] range. This is covered by two segments now. If the keys in the [0-3] range are unique, the reupload will have the same size, but our fix doesn't kick in since the reupload contains multiple segments.
PR #9404 was followed up by #9597 which added an additional defence layer for this in the manifest. While the issue …
=> archival: skip reuploads of identical size

src/v/cloud_storage_clients/s3_client.cc
S3 can reply with error even if it's replying using status 200. Most of our parsing is done independent of status code (we're trying to check error fields every time). But in case of delete objects reply we're not trying to parse error fields if the status is 200. This commit fixes this and before any attempt at parsing the response is done we're checking if the 'Error.Code' field is present.
Fixes #14014
* none
=> s3_client: Check if response contains error

tests/rptest/tests/e2e_shadow_indexing_test.py
The test asserts that rpk can describe topic, however there are test runs where the topic creation happens slightly after the topic info is requested.
This change wraps the describe operation in a wait loop so that the describe op is retried until it succeeds.
FIXES #11998 
* none
=> ducktape/cloud_storage: Wait for topic info

tests/rptest/tests/e2e_shadow_indexing_test.py
When creating a manifest for reset we drop the first spillover and then use the rest of the spillovers to craft a new manifest. If only one spillover has been uploaded, then after dropping the first entry nothing is left to craft the manifest.
This change makes the test wait until more than one manifest is spilled over.
FIXES #13425 
* none
=> ducktape/cloud_storage: Wait for at least two spillovers

tests/rptest/tests/e2e_shadow_indexing_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14183
Fixes: https://github.com/redpanda-data/redpanda/issues/14192,
=> [v23.2.x] ducktape/cloud_storage: Wait for at least two spillovers

tests/rptest/redpanda_cloud_tests/cloudv2_object_store_blocked.py, tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/services/cloud_cluster_utils.py, tests/rptest/services/provider_clients/ec2_client.py, tests/rptest/services/redpanda_cloud.py
In case of BYOC cloud, account that handled VPCs are the same as
ducktape running on and ec2 can be used
In case of FMC, there is no direct access to Cloud AWS account from
ducktape AWS Account.
* none
=> rptest: Update s3 blocking for cloud tests and fix BYOC cluster deletion

tests/rptest/services/cloud_cluster_utils.py, tests/rptest/services/redpanda_cloud.py
Addresses https://github.com/redpanda-data/cloudv2/issues/9720
Replace hard-coded urls with values passed in from ducktape global config settings.
* none
=> rptest: use cloud variables in `CloudClusterUtils` init

src/v/cluster/partition.h, src/v/kafka/server/partition_proxy.h, src/v/kafka/server/replicated_partition.cc, src/v/transform/rpc/client.cc, src/v/transform/rpc/service.cc
This fixes wasm binary fetching by not adding a debounce wait for new data to come along. This causes the request to timeout. The parameter `deadline` to `make_reader` is renamed to clarify semantics, then the bug is fixed (we should not pass a timeout to `make_reader`).
* none
=> transform/rpc: fix wasm binary fetches

src/go/k8s/go.mod, src/go/k8s/go.sum
Backport of PR https://github.com/redpanda-data/redpanda/pull/13412
=> [v23.2.x] build(deps): bump github.com/moby/moby from 24.0.5+incompatible to 24.0.6+incompatible in /src/go/k8s

src/v/archival/purger.cc
sorting the node ids was probably done to achieve an early exit while iterating over all the nodes, but the loop using the id does a full scan so sorting does not influence the results
* none
=> archival/purger: removed unused sort operation

src/go/rpk/pkg/cli/group/describe.go, src/go/rpk/pkg/config/params.go, src/go/rpk/pkg/config/redpanda_yaml.go, src/go/rpk/pkg/config/rpk_yaml.go, src/go/rpk/pkg/config/rpk_yaml_test.go, src/go/rpk/pkg/config/weak.go, src/go/rpk/pkg/kafka/client_franz.go, tests/rptest/clients/rpk.py
* `rpk` now supports `insecure_skip_verify` when talking to tls endpoints
* `rpk` now supports `globals.command_timeout` to control total command timeout for certain commands
=> rpk: misc improvements

src/go/k8s/go.mod, src/go/k8s/go.sum
Backport of PR https://github.com/redpanda-data/redpanda/pull/14243
=> [v23.2.x] build(deps): bump github.com/fluxcd/source-controller/api from 1.1.1 to 1.1.2 in /src/go/k8s

cmake/dependencies.cmake, licenses/third_party.md, src/v/redpanda/application.cc, src/v/wasm/allocator.cc, src/v/wasm/allocator.h, src/v/wasm/api.h, src/v/wasm/tests/wasm_allocator_test.cc, src/v/wasm/tests/wasm_fixture.cc, src/v/wasm/wasmtime.cc
Introduce a custom stack allocator that we plugin to wasmtime using the APIs added in https://github.com/bytecodealliance/wasmtime/pull/7209.
See the individual commits on the overall design and implementation details, as well as the tradeoffs of other options.
* none
=> wasm: introduce custom stack allocator for wasmtime

src/go/k8s/go.mod, src/go/k8s/go.sum
Backport of PR https://github.com/redpanda-data/redpanda/pull/14245
=> [v23.2.x] build(deps): bump github.com/twmb/franz-go from 1.14.3 to 1.15.0 in /src/go/k8s

src/v/storage/key_offset_map.h
This will be used in sliding window compaction.
* none
=> storage: add simple map from key to latest offset

src/go/rpk/pkg/adminapi/api_transform.go, src/go/rpk/pkg/cli/transform/list.go, src/go/rpk/pkg/cli/transform/list_test.go, src/v/model/CMakeLists.txt, src/v/model/tests/CMakeLists.txt, src/v/model/tests/transform_test.cc, src/v/model/transform.cc, src/v/model/transform.h, src/v/redpanda/admin/api-doc/transform.json, src/v/redpanda/admin_server.cc, src/v/redpanda/application.cc, src/v/transform/api.cc, src/v/transform/api.h, src/v/transform/fwd.h, src/v/transform/rpc/client.cc, src/v/transform/rpc/client.h, src/v/transform/rpc/deps.cc, src/v/transform/rpc/deps.h, src/v/transform/rpc/rpc.json, src/v/transform/rpc/serde.h, src/v/transform/rpc/service.cc, src/v/transform/rpc/service.h, src/v/transform/rpc/tests/transform_rpc_test.cc, src/v/transform/tests/transform_manager_test.cc, src/v/transform/transform_manager.cc, src/v/transform/transform_manager.h
Implement the transform list API for the Admin API.
This is consumed in RPK and the last bit needed to start writing ducktape tests (we need this to ensure all the processors have started).
* none
=> transform/list: implement list admin API

src/v/cluster/distributed_kv_stm.h, src/v/cluster/tests/distributed_kv_stm_tests.cc, src/v/model/transform.h
Instead of reasoning about the amount of memory that the offset tracker
for wasm could use as number of keys constant, we instead compute the
max number of keys from the number of entries that we're OK with
storing.
Instead of a blanket 10K keys we can keep in the distributed_kv_stm, we
now default to 1MB worth of data can be stored. To keep the
implementation fast and simple, we assert that the memory usage for
each object is fixed at compile time.
In our specific case, for offset metadata we now can store ~40k
transform offsets instead of 10k.
If we ever need key value pairs with dynamic memory usage, we can
evolve the implementation.
The nice thing about this change is that we know can easily account 
for about how much memory offset tracking can use in the system.
* none
=> cluster/kv: track kv limit using bytes

src/go/k8s/config/crd/kustomization.yaml, src/go/k8s/config/crd/patches/re-add-checksum-field_in_gitrepositories.source.toolkit.fluxcd.io.yaml, src/go/k8s/config/crd/patches/re-add-checksum-field_in_ocirepositories.source.toolkit.fluxcd.io.yaml, src/go/k8s/config/crd/patches/re-add-checksum-field_in_source.toolkit.fluxcd.io.yaml
=> operator: patch back in the checksum field into the flux crds

src/go/k8s/go.mod, src/go/k8s/go.sum, src/go/k8s/internal/controller/redpanda/console_controller.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/14244
=> [v23.2.x] build(deps): bump github.com/docker/distribution from 2.8.2+incompatible to 2.8.3+incompatible in /src/go/k8s

src/go/rpk/pkg/cli/transform/list.go, src/go/rpk/pkg/cli/transform/list_test.go
This ensures that the JSON/YAML outputs for list don't return `null`,
but `[]`.
* none
=> rpk/transform/list: handle empty list responses

tests/rptest/services/redpanda_cloud.py, tests/rptest/services/rp_config_profiles/redpanda.cloud-tiers-config.yml
Addresses issue https://github.com/redpanda-data/cloudv2/issues/9811
The tier definitions were taken from https://github.com/redpanda-data/cloudv2/pull/9676
A future follow-up PR will hit a cloud api to get these values so they don't have to be hardcorded.
* none
=> add new redpanda cloud tiers for testing

tests/rptest/scale_tests/high_throughput_test.py
fixes the error:
Failed to import rptest.scale_tests.high_throughput_test,
which may indicate a broken test that cannot be loaded:
NameError: name 'ok_to_fail' is not defined
ref https://github.com/redpanda-data/devprod/issues/878
* none
=> tests/scale: import missing `ok_to_fail` decorator

src/go/k8s/config/crd/kustomization.yaml
`kustomize edit fix` moved yaml around, breaking the in-line comments needed for kubebuilder.
This just moves those comments back where they belong
* none
=> operator: move kubebuilder comments back

src/v/hashing/secure.h, src/v/storage/CMakeLists.txt, src/v/storage/key_offset_map.cc, src/v/storage/key_offset_map.h
storage: offset key map housekeeping
* none
=> storage: offset key map housekeeping

tests/rptest/tests/usage_test.py
- The failing assertion checks that the time elapsed between two invocations of `usage_aggregator::rearm_window_timer` is exactly 1 usage_window_width_interval long.
- The test always fails detecting a 1 second skew, never a value greater then 1. It is also relatively infrequent and only occurring in debug builds. Options to resolve were to skip the test when running in debug builds or add an exception for small skews of 1 second.
- Fixes: #13520
* none
=> Fix for CI Failure (invalid timer interval) in `UsageTest.test_usage_metrics_collection`

src/go/k8s/pkg/resources/certmanager/type_helpers.go, src/go/k8s/pkg/resources/statefulset.go
Add a readiness check to the old statefulset so it will be able to be tracked by the PodDisruptionBudget.
* none
=> operator: add readiness check to Cluster statefulset

src/v/cluster/log_eviction_stm.cc, src/v/storage/disk_log_impl.cc, tests/rptest/tests/full_disk_test.py
Currently, under disk pressure, we evict local data that was uploaded to
the cloud storage only for topics with `cleanup.policy` equal to
`delete` or `delete,compact`.
Due to an oversight, data for topics with the policy set to `compact` is
never evicted. This commit ensures consistent eviction behavior for all
cleanup policies.
Since Redpanda doesn't run compaction for data that is present only in
the cloud storage, this change introduces a potential regression in
compaction quality. This choice is considered better than running out of
disk space.
If we decide to backport, this depends on #13856 and #13935.
Fixes #14015.
* Evict local data that was uploaded to the cloud storage under disk pressure for topics with `cleanup.policy=compact`. Now all cleanup policies have consistent eviction …
=> storage: evict data from compactible topics under disk pressure

src/go/k8s/go.mod, src/go/k8s/go.sum
Backport of PR https://github.com/redpanda-data/redpanda/pull/14290
=> [v23.2.x] build(deps): bump github.com/jcmturner/gokrb5/v8 from 8.4.3 to 8.4.4 in /src/go/k8s

src/go/k8s/go.mod, src/go/k8s/go.sum
Backport of PR https://github.com/redpanda-data/redpanda/pull/14288
=> [v23.2.x] build(deps): bump github.com/prometheus/common from 0.44.0 to 0.45.0 in /src/go/k8s

src/v/cluster/partition_balancer_planner.cc, tests/rptest/tests/partition_balancer_test.py
The test executes a workload similar to the one in the full node test but it uses configuration that allows the new storage space manager to kick in. 
- Fixed a bug in which partition movement wouldn't take into account reclaimable space, preventing data movement
=> tests: added test validating if balancer can cooperate with space mgmnt

src/v/security/jwt.h, src/v/security/tests/CMakeLists.txt, src/v/security/tests/jwt_test.cc
Introduce a small JWT lib for:
* Authentication Server Metadata
* JWKS (JSON Web Key Sets)
* JWS (JSON Web Signatures)
* JWT (JSON Web Tokens)
Bring it all together with `oidc_validator` that holds keys for verification and can verify and decode a JWT signed with `RS256`.
* none
=> security/oidc: JWT Lib

src/v/cluster/metadata_cache.cc, src/v/cluster/metadata_cache.h, src/v/cluster/topic_recovery_service.cc, src/v/cluster/topic_table.cc, src/v/cluster/types.cc, src/v/cluster/types.h, src/v/compat/cluster_compat.h, src/v/compat/cluster_generator.h, src/v/compat/cluster_json.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/kafka/server/handlers/alter_configs.cc, src/v/kafka/server/handlers/create_topics.cc, src/v/kafka/server/handlers/describe_configs.cc, src/v/kafka/server/handlers/incremental_alter_configs.cc, src/v/kafka/server/handlers/topics/types.cc, src/v/kafka/server/handlers/topics/types.h, src/v/kafka/server/tests/alter_config_test.cc, src/v/migrations/cloud_storage_config.cc, src/v/pandaproxy/schema_registry/service.cc, src/v/storage/ntp_config.h, src/v/storage/types.cc, tests/rptest/clients/types.py, tests/rptest/tests/describe_topics_test.py, tests/rptest/tests/topic_creation_test.py, tools/offline_log_viewer/controller.py
Add topic config for fast partition movement:
```
initial.retention.local.target.bytes
initial.retention.local.target.ms
```
Fixes #13708
* none
=> Add topic config for fast partition movement

src/v/cloud_roles/signature.cc, src/v/cloud_roles/signature.h, src/v/cloud_roles/tests/signature_test.cc, src/v/http/client.cc, src/v/http/client.h
Do not print values of sensitive headers when printing the string representation of an http request.
FIXES https://github.com/redpanda-data/core-internal/issues/839
* none
=> cloud_roles: redact fields from request string representation

tests/rptest/tests/retention_policy_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12129
Fixes: https://github.com/redpanda-data/redpanda/issues/12158,
=> [v23.2.x] ducktape: set small upload interval in retention_policy_test

src/v/model/model.cc
right now, this is what it printed for a topic_namespace
```
DEBUG 2023-10-10 07:52:43,894 [shard 0:main] cluster - topic_table.cc:166 - Created lifecycle marker for topic {{kafka}/{topic-jizgvjvxsg}} 30
```
this pr makes it consistent with what is printed for topic_namespace_partition, from `{{kafka}/{test_topic}}` to `{kafka/test_topic}`
* none
=> model/model: fix topic_namespace formatting

src/v/cloud_roles/signature.cc
The boost::core::string_view returned by boost::beast helpers seems to break OSS build.
* none
=> cloud_roles: replace boost::string_view with std::string_view

src/v/cluster/types.cc, src/v/kafka/server/handlers/alter_configs.cc, src/v/kafka/server/handlers/configs/config_utils.h, src/v/kafka/server/handlers/incremental_alter_configs.cc, src/v/kafka/server/tests/config_utils_test.cc, tests/rptest/tests/replication_factor_change_test.py
This PR expands on some existing config validation machinery and adds
validators for replication factor config, rejecting any value which is not both
positive and odd.
The general idea was to do this in the least invasive way possible while
resolving the basic bug (config API accepts a replication factor that the
create API rejects. This PR does not address:
1. Auditing/aligning other configs with respect to existing validations on the create API
-  NOTE: covered by #13443 
2. Unifying validation _mechanism_ between create and config APIs
3. Adding validation to the topic/config controller frontends
(1) straightforward to implement, building on this PR. (2) seems desirable but could require a fair bit of refactoring due to disparate data structures between APIs. (3) also desirable; …
=> Introduce validation for replication factor config

src/v/cluster/security_frontend.cc, tests/rptest/tests/scram_test.py
This changes `RP_BOOTSTRAP_USER` handling so that 3 values are parsed: username, password, and mechanism.
- Rejects empty username or password
- Selects SCRAM-SHA-512 if and only if there is a 3rd part that matches the mechanism name
- Is backwards compatible
The following values are acceptable:
```
username:password:SCRAM-SHA-512
username:password:SCRAM-SHA-256 
username:password:SCRAM-SHA-xxx # defaults to SCRAM-SHA-256
username:password:scramSha512 # defaults to SCRAM-SHA-256
username:password:scram-sha-512 # defaults to SCRAM-SHA-256
username:password: # defaults to SCRAM-SHA-256
```
The following values will result in a warning thrown to the log (and no user created):
```
username:password::
username
:password
```
Fixes #8820 
* The SASL mechanism of the bootstrap SCRAM user can now …
=> Allow setting mechanism for bootstrap user

src/v/model/transform.cc, src/v/model/transform.h, src/v/transform/probe.cc, src/v/transform/probe.h, src/v/transform/transform_manager.cc
Add metrics for transform::processor state and when processors run into failures.
* none
=> transform: add processor metrics

src/go/k8s/go.mod, src/go/k8s/go.sum
Backport of PR https://github.com/redpanda-data/redpanda/pull/14346
=> [v23.2.x] build(deps): bump github.com/twmb/franz-go/pkg/kmsg from 1.6.1 to 1.7.0 in /src/go/k8s

src/v/cloud_roles/signature.cc, src/v/cloud_roles/signature.h, src/v/cloud_roles/tests/signature_test.cc, src/v/http/client.cc, src/v/http/client.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/14271
=> [v23.1.x] cloud_roles: redact fields from request string representation

src/v/archival/tests/CMakeLists.txt, src/v/archival/tests/archival_metadata_stm_gtest.cc, src/v/cluster/archival_metadata_stm.cc, src/v/cluster/archival_metadata_stm.h, src/v/cluster/persisted_stm.cc, src/v/cluster/persisted_stm.h, src/v/raft/tests/CMakeLists.txt, src/v/raft/tests/basic_raft_fixture_test.cc, src/v/raft/tests/raft_fixture.cc, src/v/raft/tests/raft_fixture.h, src/v/raft/tests/raft_reconfiguration_test.cc, src/v/raft/tests/stm_manager_test.cc
Previously, the archival STM used `persisted_stm::sync` in order to
ensure that its log is up to date before issuing new commands. This
works fine for leadership changes since they imply a term change.
However, the archiver may need to sync during the same term. We've seen
scenarios like this:
> Upload loop picks 4 candidates, uploads to cloud storage and
replicates a batch with 4 new segments. After the replication command
succeeds, the topic retention is updated. This re-starts the archiver.
When the archiver restarts it picks the same 4 segments and replicates
the addition commands again. Finally, the partition manifest detects
this, refuses the commands and prints the error log.
The previous sync method does not support such cases sync they happen in
the same term. To fix this, the …
=> archival: same term sync-ing

src/go/k8s/go.mod, src/go/k8s/go.sum
Backport of PR https://github.com/redpanda-data/redpanda/pull/14344
=> [v23.2.x] build(deps): bump github.com/twmb/franz-go/pkg/kadm from 1.9.1 to 1.10.0 in /src/go/k8s

.github/workflows/lint.yml, .github/workflows/transform-sdk-build.yml, src/go/rpk/.golangci.yml, src/go/rpk/pkg/cli/container/common/common.go
PR #14275 is failing because it uses `min` and `max`, which were added in go1.21. Our builds use go1.21, but the currently installed golangci-lint is old and does not recognize min / max.
* none
=> .github: use latest golangci-lint; rpk: remove dead linters

src/go/rpk/pkg/adminapi/api_config.go, src/go/rpk/pkg/cli/cluster/config/set.go, tests/rptest/tests/cluster_config_test.py
while setting a config, this pr extends the check of the key on the aliases for properties, and adds a test for it
Fixes #13389 
* `rpk cluster config set` can use the property alias
=> rpk: accept property aliases for cluster config set

src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/schema_registry/handlers.cc, src/v/pandaproxy/schema_registry/handlers.h, src/v/pandaproxy/schema_registry/seq_writer.cc, src/v/pandaproxy/schema_registry/seq_writer.h, src/v/pandaproxy/schema_registry/service.cc, src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h, src/v/pandaproxy/schema_registry/storage.h, src/v/pandaproxy/schema_registry/store.h, src/v/pandaproxy/schema_registry/test/store.cc, src/v/pandaproxy/schema_registry/types.h, tests/rptest/tests/schema_registry_test.py
Introduces `DELETE /config/{subject}` endpoint for Schema Registry.
This makes use of (mostly) existing primitives on the sequenced write path to avoid duplicating critical code. Key observation is that a config write message with k: `{subject}`, v: `std::nullopt` results in durably (I think) clearing the compatibility config for that subject.
Fixes #13229
* Schema Registry: Add `DELETE /config/{subject}` endpoint
=> schema_registry: Add support for `DELETE /config/{subject}`

src/go/k8s/go.mod, src/go/k8s/go.sum
Backport of PR https://github.com/redpanda-data/redpanda/pull/14345
=> [v23.2.x] build(deps): bump github.com/twmb/franz-go from 1.15.0 to 1.15.1 in /src/go/k8s

src/v/archival/ntp_archiver_service.cc, src/v/archival/ntp_archiver_service.h, src/v/archival/scrubber.cc, src/v/cloud_storage/anomalies_detector.cc, src/v/cloud_storage/anomalies_detector.h, src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/partition_manifest.h, src/v/cloud_storage/tests/anomalies_detector_test.cc, src/v/cloud_storage/tests/partition_manifest_test.cc, src/v/cluster/archival_metadata_stm.cc, src/v/cluster/archival_metadata_stm.h, tests/rptest/tests/cloud_storage_scrubber_test.py
For large partitions, one should not expect the scrubber to complete in one iteration
while respecting the allocated quota. This PR teaches the scrubber how to resume
from where the previous scrub stopped.
To this end we persist the last scrubbed offset in the manifest and feed it
into the anomalies detector, which will skip already scrubbed offsets. Conversely,
the anomalies detector reports the offset at which it stopped. Note that the
last scrubbed offset is not linear. We scrub manifest from newest to oldest, but
within a manifest we iterate from the beginning to the end (this is because the
columns in the cstore are encoded and reverse iteration is not possible).
Fixes #13884
* none
=> cloud_storage: resume scrubbing from last scrubbed offset

src/v/cluster/scheduling/allocation_state.cc, src/v/cluster/scheduling/partition_allocator.h, src/v/cluster/tests/partition_allocator_tests.cc
Previously, in case of failed allocation of partitions for new topics, we tried to revert `_highest_group` value as well. When a large number of topics were allocated in a single request concurrently (e.g. when MirrorMaker creates required topics on the destination cluster) and some of these requests bump into partition allocation limits, this could lead to duplicate group_ids.
As there is no reason to try to reuse group_ids, simply remove the code moving `_highest_group` backwards.
Fixes https://github.com/redpanda-data/redpanda/issues/12610
* Fix a bug that could lead to crashes with `double registration of group` assertion after trying to create a lot of topics in a single CreateTopics request when some of these topics could not be allocated (e.g. due to bumping into partition count …
=> c/partition_allocator: make `_highest_group` updates monotonic

src/v/transform/probe.cc, src/v/transform/probe.h, src/v/transform/transform_manager.cc, src/v/transform/transform_processor.h
A followup to https://github.com/redpanda-data/redpanda/pull/14327 to prevent number of processors from becoming a stat performance issue.
* none
=> transform/probe: precompute processor state counts

src/go/rpk/pkg/cli/transform/deploy.go
Without this prompt doing the following set of commands fails with an
error about missing topics:
```
rpk transform init
<follow prompts>
rpk transform build
rpk transform deploy
<error!>
```
* none
=> rpk/transform/deploy: prompt if missing input/output topic

src/v/cluster/scheduling/allocation_state.cc, src/v/cluster/scheduling/partition_allocator.h, src/v/cluster/tests/partition_allocator_tests.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14375
Fixes: https://github.com/redpanda-data/redpanda/issues/14390,
=> [v23.2.x] c/partition_allocator: make `_highest_group` updates monotonic

tests/rp_cloud_cleanup.py, tests/rptest/services/provider_clients/rpcloud_client.py, tests/rptest/services/redpanda_cloud.py
To minimize code duplication, util is using the same RpCloudApiClient
class that is used in redpanda_cloud class. Also, to isolate it from
ducktape runtime, its placed in tests folder to utilize rptest as an
external module and prevent any CI-related modifications.
* none
=> ci: Add util to test structure to clean cloudv2 after testrun

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
Related to issue https://github.com/redpanda-data/cloudv2/issues/9613
First, have this test run on the scheduled buildkite jobs so we can determine which instance type is best to use. A follow-up PR will remove the `@ok_to_fail`.
* none
=> rptest: ok_to_fail test_ts_resource_utilization

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
Related issue https://github.com/redpanda-data/cloudv2/issues/9935
Now that the test infrastructure is setup to run BYOC, enable the redpanda cloud test `HighThroughputTest.test_disrupt_cloud_storage`.
* none
=> rptest: enable test_disrupt_cloud_storage

src/v/cluster/distributed_kv_stm.h, src/v/transform/rpc/client.cc, src/v/transform/rpc/client.h, src/v/transform/rpc/deps.cc, src/v/transform/rpc/deps.h, src/v/transform/rpc/serde.cc, src/v/transform/rpc/serde.h, src/v/transform/rpc/service.cc, src/v/transform/rpc/service.h, src/v/transform/rpc/tests/CMakeLists.txt, src/v/transform/rpc/tests/transform_rpc_test.cc
Make transform RPCs more robust via retries.
* none
=> transform/rpc: add retries to client

src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/schema_registry/handlers.cc, src/v/pandaproxy/schema_registry/handlers.h, src/v/pandaproxy/schema_registry/seq_writer.cc, src/v/pandaproxy/schema_registry/seq_writer.h, src/v/pandaproxy/schema_registry/service.cc, src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h, src/v/pandaproxy/schema_registry/storage.h, src/v/pandaproxy/schema_registry/store.h, src/v/pandaproxy/schema_registry/test/store.cc, src/v/pandaproxy/schema_registry/types.h, tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/13557
Fixes: https://github.com/redpanda-data/redpanda/issues/14381,
=> [v23.1.x] schema_registry: Add support for `DELETE /config/{subject}`

tests/docker/ducktape-deps/kgo-verifier, tests/rptest/services/kgo_repeater_service.py, tests/rptest/services/kgo_verifier_services.py
Update the code at kgo-verifier and kgo-repeater to workaround tests starting in a "dirty" environment (#883). In particular, after launching the services in background (`nohup ... &`), until for status endpoint to be ready and double check that the background service we launched is still running.
* none
=> tests: improve the orchestration of the kgo-verifier and kgo-repeater

src/v/cluster/health_manager.cc
To ensure that the replication is correctly set if a cluster ever goes
from 1 -> 3+ nodes
* none
=> cluster/health_manager: add transform offset topic

src/v/kafka/server/replicated_partition.cc, tests/rptest/tests/offset_for_leader_epoch_read_replica_test.py
Read-replica uses local Raft group as a source of information for `OffsetForLeaderEpoch` request. This PR fixes this problem and adds a reproducer in form of ducktape test.
Fixes #14402 
* Fix OffsetForLeaderEpoch for read-replicas
=> cloud_storage: Fix offset for leader epoch request for read-replica

src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h, src/v/redpanda/application.cc, src/v/security/CMakeLists.txt, src/v/security/audit/audit_log_manager.h, src/v/security/audit/schemas/iam.h, src/v/security/audit/schemas/schemas.h, src/v/security/audit/schemas/tests/CMakeLists.txt, src/v/security/audit/schemas/tests/ocsf_schemas_test.cc, src/v/security/audit/schemas/types.h, src/v/security/audit/schemas/utils.cc, src/v/security/audit/schemas/utils.h, src/v/security/audit/tests/audit_log_test.cc, src/v/utils/request_auth.cc, src/v/utils/request_auth.h, tests/rptest/tests/audit_log_tests.py, tests/rptest/utils/audit_schemas.py, tests/setup.py
This PR adds the functionality to audit the admin server - enabled only when the proper configuration options are set. Th publish of an audit record occurs in the background that way the request handling path is not affected. The only way normal request processing will be modified is in the case the audit background queues are full. If so , the request is interrupted and a 500 response will be returned to the client.
Additional logic has been introduced to catch and handle authorization failures. Now upon observation of an authorization failure, redpanda will log the client IP and auth failure reason. If auditing is enabled this will also generate an audit log message, with all of the appropriate fields filled.
Ducktape tests have been written which test end to end functionality. Tests …
=> security: Audit all admin server requests

src/go/rpk/go.mod, src/go/rpk/go.sum, src/go/rpk/pkg/cli/topic/produce.go, src/go/rpk/pkg/serde/avro.go, src/go/rpk/pkg/serde/avro_test.go, src/go/rpk/pkg/serde/proto.go, src/go/rpk/pkg/serde/proto_test.go, src/go/rpk/pkg/serde/serde.go
This PR introduces a way to encode messages in rpk while producing, using Schema Registry:
It introduces `--schema-id`/`--schema-key-id`, a new set of flags in `rpk topic produce` that lets rpk know that you want to use the schema with the given ID to encode your message. rpk will query the schema registry for the schema, and decode accordingly.
For PROTOBUF messages, there is an additional flag `--proto-msg-type` that lets you select which message you want to use to encode the message since in Proto, it is ok to have multiple message types in a single schema.
rpk expects JSON messages and produces binary encoded messages to the topic.
**AVRO**
Let's say you have the following schema in `/tmp/sample.avro`:
```
{
"type": "record",
"name": "sensor_sample",
"fields": [
{
"name": "timestamp", …
```
=> rpk: support producing using Schema Registry

src/v/storage/key_offset_map.cc, src/v/storage/key_offset_map.h, src/v/storage/tests/CMakeLists.txt, src/v/storage/tests/key_offset_map_test.cc, src/v/utils/fragmented_vector.h, src/v/utils/tests/CMakeLists.txt, src/v/utils/tests/fragmented_vector_async_test.cc, tools/format-cc
Introduces a new offset key map implementation that maps compaction key space into sha256(key) space.
* none
=> Compaction lossy hash

src/v/raft/tests/raft_fixture.cc
If we don't hold the gate open while the exchange is going on, we can
call `set_exception` twice on the resp_data promise, which erronously
reports a dropped exception to seastar.
Fixes: #13299
* none
=> r/tests: hold gate open during exchange

cmake/dependencies.cmake, src/go/rpk/pkg/cli/transform/buildpack/buildpack.go
Upgrades tinygo in rpk (the vendored toolchain) and for our test programs
* none
=> tinygo: upgrade to v0.30.0

src/v/transform/tests/transform_manager_test.cc, src/v/transform/transform_manager.cc
Since we can break out of the loop, it's possible that we move an entry
out of the btree_set secondary index and then that breaks the container,
causing assertion errors later on with the invalid index.
I wrote a unit test that caught this issue, then had to dump the index
multiple times to find what was going on.
* none
=> transform/manager: don't move during erase

src/v/storage/CMakeLists.txt, src/v/storage/compacted_index_reader.h, src/v/storage/compaction_reducers.cc, src/v/storage/compaction_reducers.h, src/v/storage/disk_log_impl.cc, src/v/storage/disk_log_impl.h, src/v/storage/fwd.h, src/v/storage/key_offset_map.cc, src/v/storage/key_offset_map.h, src/v/storage/segment.h, src/v/storage/segment_deduplication_utils.cc, src/v/storage/segment_deduplication_utils.h, src/v/storage/segment_utils.cc, src/v/storage/tests/CMakeLists.txt, src/v/storage/tests/segment_deduplication_test.cc, src/v/storage/types.h
Adds utility methods that will be used in sliding window comapction. There are a few pieces to this:
- Selecting the "sliding range", the range of segments that are eligible for compaction in a given round of compaction. Only "traditionally" compactible segments (i.e. stable, can't be active) are viable, and segments that have had their keys deduplicated in a previous been sliding window compaction no longer need deduplication unless new non-compacted data shows up.
- Building the offset map, a mapping of keys to the latest offset seen for that key, with keys from multiple segments. Within the sliding range, we look at the newest segment and add all keys to the map, iterating on older and older segments. We keep track of the earliest segment that has been fully indexed, and in the next …
=> storage: utilities to implement sliding window compaction

src/v/kafka/server/tests/produce_consume_utils.cc, src/v/kafka/server/tests/produce_consume_utils.h, src/v/storage/disk_log_impl.cc, src/v/storage/disk_log_impl.h, src/v/storage/tests/CMakeLists.txt, src/v/storage/tests/compaction_e2e_test.cc, src/v/storage/tests/utils/disk_log_builder.cc
This commit introduces sliding window compaction as a method to be used in `disk_log_impl`. The high level algorithm is as follows:
- collect the compactible set of segments (i.e. don't compact the active segment, don't compact segments that have done sliding window compaction)
- self compact all collected segments
- build an offset map over the collected segments
- deduplicate each segment, rewriting it and swapping it with the old segment
There is a key difference in approach approach compared to the existing merge-self-compact implementation: it doesn't reduce the number of segments. For that reason, this commit doesn't enable this behavior by default. A later PR will introduce reducing the number of segments, and enable the new implementation by default.
Fixes #14364
* none
=> storage: implement sliding window compaction

tests/rptest/tests/delete_records_test.py
- Adds a retry when calling rpk consume, it may be the case due to a concurrent node failure that rpk will not retry and return an error, causing the test to fail.
- Fixes: #14151
* none
=> Fix for CI Failure (Failed bounds check: offset 1823 not consumable) in DeleteRecordsTest.test_delete_records_segment_deletion

tests/rptest/services/redpanda.py
In `RedpandaService.metrics_samples`, sample extraction was broken due to re-use of a generator initialized outside a for loop. The generator was consumed on the first iteration of the loop, so each subsequent iteration would produce no samples.
* none
=> rptest/services/redpanda: Move metrics generator inside loop

tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/services/openmessaging_benchmark.py
During a test run of CloudV2 tests there is a series of tests that run OMB on the same cluster. If two tests are creating topics with specific parameters fast one after another OMB node startup takes longer than default 60 sec
* none
=> rptest: Make OMB startup timeout configurable

src/go/k8s/go.mod, src/go/k8s/go.sum
Backport of PR https://github.com/redpanda-data/redpanda/pull/14453
=> [v23.2.x] build(deps): bump github.com/onsi/gomega from 1.28.1 to 1.29.0 in /src/go/k8s

cmake/v_library.cmake, src/v/archival/upload_housekeeping_service.cc, src/v/kafka/server/handlers/describe_configs.cc
I believe this to be a good practice. And I've seen plenty of cases
where reviewers ask for explicit attribute anyway. Handing this job to
the compiler from now on.
* none
=> cmake: enable implicit fallthrough warning

src/v/cluster/tx_gateway_frontend.cc, src/v/cluster/tx_gateway_frontend.h, src/v/redpanda/admin_server.cc
Changed the logic in `init_tm_tx` not to retry when current node is not leader for partition hosting particular transactional id. Previously when current node wasn't a leader for partition host the transactional id the logic retired finding `tx_id` hosting `ntp` in the same way as it would be missing in metadata cache.
- Do not retry waiting for `tx_id` hosting partition when current node is not leader
=> c/tx_gt_frontend: do not retry when not leader for `tx` topic partition

src/v/transform/transform_processor.cc, src/v/transform/transform_processor.h
This makes a number of performance improvements to the transform processor.
We attempt to pipeline operations as much as possible, so one step doesn't stop other parts from making progress. 
This is done by splitting the processor into multiple fibers, one for reading, one for writing and one for transforming.
Additionally, we try not to keep intermidiate buffers of batches unless there is natural backpressure from the system
(for example because writes are slow or the transform is running slow).
This is a prerequisite to overall transform subsystem memory caps, mostly by ensuring this "inflight" data all transform
processors is accounted for (next PR).
* none
=> transform/processor: streamline transforms

src/v/cluster/tm_stm.cc, src/v/cluster/tm_stm.h, src/v/cluster/tm_tx_hash_ranges.h, src/v/cluster/tx_gateway_frontend.cc, src/v/cluster/tx_gateway_frontend.h, src/v/kafka/server/server.cc, src/v/redpanda/admin_server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14401
Backport of PR https://github.com/redpanda-data/redpanda/pull/14420
Fixes: https://github.com/redpanda-data/redpanda/issues/14437
Fixes: https://github.com/redpanda-data/redpanda/issues/14463
=> [v23.2.x] [backport] tx: add more trace logging in init_producer_id code path

src/v/cluster/scheduling/allocation_state.cc, src/v/cluster/tests/partition_allocator_tests.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14375
=> [v22.3.x] c/partition_allocator: make `_highest_group` updates monotonic

tests/rp_cloud_cleanup.py, tests/rptest/services/provider_clients/rpcloud_client.py
=> ci: Handle errors on cloud namespaces cleanup

src/v/cluster/scheduling/allocation_state.cc, src/v/cluster/tests/partition_allocator_tests.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14375
=> [v23.1.x] c/partition_allocator: make `_highest_group` updates monotonic

src/v/wasm/allocator.cc, src/v/wasm/allocator.h, src/v/wasm/wasmtime.cc
Add limits to an underlying store. The primary goal of this is to not have tables grow beyond our recommended allocation size, memory is already limited, but now we plug that value into a store for better error messages and not needing to ask for a new memory before OOM'ing a VM.
* none
=> wasm: add store limits

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
CloudV2 Tiers have enforced minimal segment size of 16MB. Due to this traffic heavy tests needs to be updated, so they run in a reasonable timeframe along with other tests (less than ~30min). 
This PR updated several parameters along with some timeout tweaks:
- Reducing cloud segments per partition from 1,000 to 100 in the segment upload stress test.
- Increasing the initial segment size from 4KiB to 16MiB.
- Decreasing the failed consumers from 10,000 to 5,000.
- Increasing message size from 128KiB to 256KiB.
- Increase Failed consumer step from 10 to 50. Which results in 100 steps total (5000/50)
Test that fills up the cache still takes a significant time to run, though and there is almost no workarounds here rather than force RP to process huge amounts of data and do cache-misses in …
=> rptest: Updates to traffic heavy cloud tests

tests/docker/Dockerfile, tests/docker/Dockerfile.dockerignore, tests/docker/ducktape-deps/tinygo, tests/docker/ducktape-deps/tinygo-wasi-transforms, tests/rptest/clients/rpk.py, tests/rptest/tests/data_transforms_test.py
Writing my first ducktape test - this adds most of the boilerplate to inject a Wasm binary into the docker image we build,
adding the commands to `RpkTool` then a minimal example of the system working by verifying all the lifecycle commands work
as intended.
I've tried to write these tests with lots of error context and to be robust, but as I noted this is my first pass at a ducktape
test, so please let me know if I'm doing anything abormal.
* none
=> ducktape/transform: verify transform lifecycle

src/v/raft/configuration_bootstrap_state.cc, src/v/raft/tests/bootstrap_configuration_test.cc, src/v/raft/tests/simple_record_fixture.h
When Raft starts it may have to recover some of the stored
configurations from the log. Fixed deserializing configurations when
their version is greater than 6 and `serde` is being used to serialize the configuration object. 
Fixes: #14442
- none
=> Fixed reading raft configuration when `serde` serialized

tests/rptest/services/redpanda_cloud.py
Fixes https://github.com/redpanda-data/cloudv2/issues/10044
verified fix by running test:
```console
ducktape --debug --globals=/home/ubuntu/redpanda/tests/globals.json --cluster=ducktape.cluster.json.JsonCluster --cluster-file=/home/ubuntu/redpanda/tests/cluster.json --test-runner-timeout=3600000 tests/rptest/tests/rpk_topic_test.py::RpkToolTest.test_consume_from_partition
```
which showed cluster being created with `productName`:
```
...
[INFO  - 2023-10-27 06:35:37,640 - redpanda_cloud - create - lineno:809]: creating cluster name rp-ducktape-cluster-069a9cd4
[DEBUG - 2023-10-27 06:35:37,641 - redpanda_cloud - create - lineno:812]: body: {"cluster": {"name": "rp-ducktape-cluster-069a9cd4", "spec": {"productName": "tier-1-aws-sbdg", "clusterType": "BYOC", "connectors": {"enabled": …
```
=> rptest: use productName instead of productId for cloud api

src/go/rpk/pkg/cli/redpanda/mode.go, src/go/rpk/pkg/config/config.go, src/go/rpk/pkg/config/redpanda_yaml.go, src/go/rpk/pkg/config/weak.go
It enables `redpanda.recovery_mode_enable` in the node redpanda.yaml.
We also turn off this knob in Dev and Prod mode.
Solves the first bullet point of #14394 
* `rpk redpanda mode recovery` lets you set redpanda in recovery mode.
=> rpk: add `rpk redpanda mode recovery`.

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
Following on PR #14389, need to ignore the test for now since it is causing ducktape [timeouts](https://buildkite.com/redpanda/vtools/builds/10272#018b7211-03c7-4645-9bf0-98ee93fbba4f/8783-8893):
```
...
[INFO:2023-10-27 17:54:49,317]: RunnerClient: rptest.redpanda_cloud_tests.high_throughput_test.HighThroughputTest.test_ts_resource_utilization: Running...
[ERROR:2023-10-27 20:54:49,516]: Exception receiving message: <class 'ducktape.errors.TimeoutError'>: runner client unresponsive, active_tests:
[TestKey(test_id='rptest.redpanda_cloud_tests.high_throughput_test.HighThroughputTest.test_ts_resource_utilization', test_index=1)]
...
```
Related issue: https://github.com/redpanda-data/cloudv2/issues/9613
* none
=> rptest: ignore HighThroughputTest.test_ts_resource_utilization for now

tests/rptest/tests/partition_balancer_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14460
Fixes: https://github.com/redpanda-data/redpanda/issues/14475,
=> [v23.2.x] tests: do not reserve disk space in full_node_test

tests/rptest/services/failure_injector.py, tests/rptest/services/redpanda.py, tests/rptest/tests/random_node_operations_test.py
Enabled tiered storage in random node operations test. 
Fixes: https://github.com/redpanda-data/core-internal/issues/455
- none
=> Added tiered storage to random node operations test

tests/rptest/services/redpanda.py
=> ducktape: Infer rp-storage-tool backend from URL

src/v/archival/ntp_archiver_service.cc, src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/partition_manifest.h, src/v/cluster/archival_metadata_stm.cc, src/v/config/configuration.cc, src/v/config/configuration.h
Currently, both STM and upload loop are checking segments for consistency violations. This may create problems when we're replaying the log generated by old redpanda version. In order to be able to enable checks only for new segments we need two different configuration options. 
This PR also unifies all consistency checks by introducing plural version of the `safe_segment_meta_to_add` method. This method accepts list of segments and performs consistency checks on them. Method returns number of segments that passed the check. The caller of the method then can remove segments that didn't pass the check by truncating the list of segments.
Fixes #14504
* Improved Tiered-Storage metadata consistency
=> Control consistency checks in the upload loop and STM independently

tests/rptest/redpanda_cloud_tests/observe_test.py
should be using a Requests response decoder that handles compression
- none
=> rptest:ht observe test fix response decode from grafana

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
Follow-on for issue https://github.com/redpanda-data/cloudv2/issues/9554
* none
=> rptest: Remove ignore from expensive tests

src/go/transform-sdk/internal/testdata/dynamic/transform.go, src/v/wasm/tests/wasm_transform_test.cc, src/v/wasm/wasmtime.cc
This PR adds support for forcing Wasmtime to yield control periodically so that we don't hit reactor stalls running expensive transforms (or bugs with infinite loops in the user's transform).
* none
=> wasm: ensure CPU usage is limited

src/v/transform/api.cc, src/v/transform/io.h, src/v/transform/tests/test_fixture.cc, src/v/transform/tests/test_fixture.h, src/v/transform/tests/transform_manager_test.cc, src/v/transform/tests/transform_processor_test.cc, src/v/transform/transform_processor.cc
The transform subsystem only uses kafka::partition_proxy and above for
the data path, so use kafka::offset internally for that type - it's safe
to cast to that type.
* none
=> transform: switch over to kafka::offset

src/v/transform/rpc/client.cc, src/v/transform/rpc/client.h, src/v/transform/rpc/tests/transform_rpc_test.cc
If an offset isn't stored, then we'll get a success, but a nullopt.
Ensure we're bubbling that up correctly.
* none
=> transform/rpc/client: fix loading missing offsets

tests/rp_cloud_cleanup.py, tests/rptest/services/cloud_cluster_utils.py, tests/rptest/services/provider_clients/rpcloud_client.py
After BYOC test runs and native CloudV2 daily cleanups. Agents left untouched, which consumes resources.
It needs to be handled
* none
=> ci: Cleanup BYOC agent after test runs

src/v/config/configuration.cc, tests/rptest/tests/log_segment_ms_test.py, tests/rptest/tests/tiered_storage_model.py, tests/rptest/tests/workload_upgrade_config_defaults.py, tests/rptest/tests/workload_upgrade_runner_test.py
Set the default value for log_segment_ms_min to 10 minutes to reduce the chance of accidentally overloading the system with a low segment.ms value. Tests are updated to explicitly set log_segment_ms_min to 60 seconds.
Fixes #13468
* default value for log_segment_ms_min is now 10 minutes. This means that if time-based rolling is active on a segment, the threshold will be silently clamped to at least 10 minutes
=> default log_segment_ms_min to 10 min

tests/docker/ducktape-deps/tinygo
CDT runs this script not at `/` but somewhere else, so this script
fails when run in CDT.
* none
=> ducktape/deps: use absolute path to tinygo

CMakeLists.txt, CMakePresets.json
build: add sanitizer option to open-source build
* none
=> build: add sanitizer option to open-source build

CMakeLists.txt, CMakePresets.json, tools/gcovr
build: add coverage helper
* none
=> build: add coverage helper

src/go/rpk/pkg/cli/topic/consume.go, src/go/rpk/pkg/serde/avro.go, src/go/rpk/pkg/serde/avro_test.go, src/go/rpk/pkg/serde/proto.go, src/go/rpk/pkg/serde/proto_test.go, src/go/rpk/pkg/serde/serde.go, tests/rptest/clients/rpk.py, tests/rptest/tests/rpk_registry_test.py
This PR introduces a new flag to `rpk topic consume`: `--use-schema-registry`. This flag allows the user to inform rpk that they want to decode the message using the schema registry.
**Usages:**
- `--use-schema-registry`: decodes key and value.
-  `--use-schema-registry=key`: decodes only the key.
- `--use-schema-registry=value`: decodes only the value.
If rpk fails to decode a message, it will print it to stderr and log the error.
**Example:**
```
$ rpk topic consume test -o 96:end                       
{
"topic": "test",
"value": "\u0000\u0000\u0000\u0000\u0006\u0000\u0012\u0007vasquez\n\u0006Rogger",
"timestamp": 1698207671816,
"partition": 0,
"offset": 96
}
$ rpk topic consume test -o 96:end --use-schema-registry                      
{
"topic": "test",
"value": …
```
=> rpk: support decoding schema registry encoded messages in `rpk topic consume`

src/go/rpk/pkg/cli/container/start.go
The output looks like this:
```
NODE-ID  STATUS   KAFKA-ADDRESS    ADMIN-ADDRESS    PROXY-ADDRESS    SCHEMA-REGISTRY-ADDRESS
0        running  127.0.0.1:42629  127.0.0.1:46853  127.0.0.1:40787  127.0.0.1:42233
```
Users will see this in the output of `rpk container start` and `rpk container status`.
* rpk container: the exposed schema registry port will now be available in the output of `start` and `status`.
=> rpk: add schema registry port to rpk container table

src/v/model/fundamental.h, src/v/transform/api.cc, src/v/transform/io.h, src/v/transform/tests/test_fixture.cc, src/v/transform/tests/test_fixture.h, src/v/transform/tests/transform_manager_test.cc, src/v/transform/tests/transform_processor_test.cc, src/v/transform/transform_processor.cc, src/v/transform/transform_processor.h
Track and commit the offset at which transforms have progressed on the input topic.
Currently, this is a very naive implementation to split up the reviews. There are two pieces of followup work:
* Batch commits per core at a 3s interval
* Handle retention removing the data at the committed offset (by restarting at the low watermark).
* none
=> transform: track processor progress

src/v/wasm/cache.cc, src/v/wasm/tests/wasm_cache_test.cc
This assertion in the wasm cache is invalid - we could be replacing a weak nullptr (hence using `insert_or_assign`). Remove the assertion and add a test for replacing an engine.
* none
=> wasm: fix cache assertion

conf/redpanda.yaml, src/go/rpk/pkg/config/params_test.go
We don't allow advertised addresses of `0.0.0.0` so in our example
configuration explicitly set localhost configuration values.
This allows Redpanda to boot using this configuration.
* none
=> conf: update Redpanda configuration file

tests/rptest/tests/rpk_registry_test.py
It's failing constantly and we are working on a solution. Issue reported: #14619
* none
=> test: temporary mark ok_to_fail registry tests

tests/rptest/perf/ts_read_openmessaging_test.py, tests/rptest/services/openmessaging_benchmark_configs.py
The tail latencies for TS reads can be pretty high and variable. So to avoid a bunch of test failures we're removing the checks for p95+ tail latencies and instead relying on checks for p75 or less latencies.
* none
=> Remove tail-latency checks from ts_read perf test

src/v/pandaproxy/schema_registry/handlers.cc, src/v/pandaproxy/schema_registry/seq_writer.cc, src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h
A common use of `POST /subjects/{subject}/versions` is to get the schema ID of an existing subject-version.
This case can be optimised by not taking the write_sem unless a new schema or version needs to be written to the topic.
Split out `get_schema_version` from `project_ids` to facilitate that.
* Schema Registry: Don't hold the write semaphore if the schema posted to `POST /subjects/{subject}/versions` already exists.
=> schema_registry: Split project_ids

src/v/transform/rpc/client.cc
I've seen some of these errors come up in ducktape tests I'm writing and we should
handle these RPC errors by retrying.
* none
=> transform/rpc/client: better error handling

src/v/archival/ntp_archiver_service.cc, src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/partition_manifest.h, src/v/cluster/archival_metadata_stm.cc, src/v/config/configuration.cc, src/v/config/configuration.h
Currently, both STM and upload loop are checking segments for consistency violations. This may create problems when we're replaying the log generated by old redpanda version. In order to be able to enable checks only for new segments we need two different configuration options. 
This PR also unifies all consistency checks by introducing plural version of the `safe_segment_meta_to_add` method. This method accepts list of segments and performs consistency checks on them. Method returns number of segments that passed the check. The caller of the method then can remove segments that didn't pass the check by truncating the list of segments.
Fixes #14504
* Improved Tiered-Storage metadata consistency
=> [v23.2.x] Control consistency checks in the upload loop and STM independently

tests/rptest/tests/topic_recovery_test.py
When running the topic recovery test, occassionally we see accessdenied errors when the following sequence is seen:
1. Node A issues delete request for key recovery_state/.../A
2. Node B PUTs key recovery_state/.../B
Node B gets access-denied. This seems to be a quirk of MinIO, they have multiple issues documenting PUT failure because of locking, eg
https://github.com/minio/minio/issues/12914
Since AWS guarantees that parallel DELETE and PUT for different keys under the same root path are possible, we should ignore the error for MinIO based environments.
FIXES #8388 
* none
=> ducktape/cloud_storage: Ignore accessdenied errors

src/v/archival/ntp_archiver_service.h, src/v/cluster/partition.cc, src/v/cluster/partition.h, src/v/redpanda/admin/api-doc/shadow_indexing.json, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h, tests/rptest/services/admin.py, tests/rptest/tests/e2e_shadow_indexing_test.py
This PR introduces a new escape hatch for cloud storage. It's and admin API endpoint
which resets the in-memory manifest for all replicas to the latest manifest present
in cloud storage: `/v1/cloud_storage/unsafe_reset_metadata_from_cloud/{ns}/{tp}/{pid}`.
Under the hood, the manifest is downloaded, packaged in an archival STM command
and replicated. For this to be safe, no other cloud storage commands should be replicated
at the same time. We achieve this by pausing the archiver and it's housekeeping jobs (scrubber
and segment merger).
* Add a new admin API endpoint which can reset the in-memory cloud storage partition metadata the latest uploaded one in cloud storage: `/v1/cloud_storage/unsafe_reset_metadata_from_cloud/...`
=> cloud_storage: reset in-memory partition manifest to uploaded manifest

src/v/wasm/engine_probe.cc, src/v/wasm/engine_probe.h, src/v/wasm/tests/wasm_probe_test.cc, src/v/wasm/wasmtime.cc
The last resource that we need metrics for within WebAssembly is CPU usage. This adds to our existing engine probe CPU metrics, and then adds the reporting in Wasmtime. We don't report CPU time of async host functions, only for sync host functions since the scheduler gets involved and it's tricky to correctly measure.
Benchmarks showed that the time measurement performance impact is negligible (within the noise of variability between runs).
* none
=> wasm: add metrics for wasm CPU time

tests/rptest/services/provider_clients/rpcloud_client.py, tests/rptest/services/redpanda.py, tests/rptest/services/redpanda_cloud.py
Couple of fixes that collected during tier-5 ARM runs
- free_preallocated_nodes does not works in cloudv2 env as it should when called from the test
- rpclient logger calls mistyped during adding functions for a cleanup
- Segment sizes has been updates in tier configuration to 16MB-128MB almost in all tiers
* none
=> rptest: fix expensive tests config and timeout issues

src/go/rpk/pkg/cli/acl/acl.go
This adds a few that RP does not yet support but may someday sooner than later.
Closes #12229.
* none
=> rpk acl --help-operations: update for new requests

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/kafka/sasl_probe.h, src/v/kafka/server/connection_context.cc, src/v/kafka/server/connection_context.h, src/v/kafka/server/request_context.h, src/v/kafka/server/requests.cc, src/v/kafka/server/server.cc, src/v/kafka/server/server.h, src/v/security/gssapi_authenticator.cc, src/v/security/gssapi_authenticator.h, src/v/security/oidc_authenticator.cc, src/v/security/oidc_authenticator.h, src/v/security/request_auth.cc, src/v/security/sasl_authentication.h, tests/docker/Dockerfile, tests/docker/ducktape-deps/librdkafka, tests/rptest/clients/python_librdkafka.py, tests/rptest/services/kerberos.py, tests/rptest/services/keycloak.py, tests/rptest/tests/redpanda_kerberos_test.py, tests/rptest/tests/redpanda_oauth_test.py, tests/rptest/tests/sasl_reauth_test.py, tests/rptest/tests/scram_test.py, tests/setup.py
This PR implements most of [KIP-368](https://cwiki.apache.org/confluence/display/KAFKA/KIP-368%3A+Allow+SASL+Connections+to+Periodically+Re-Authenticate).
This PR also bumps kafka client ducktape dependencies to a version that supports reauthentication.
Fixes https://github.com/redpanda-data/core-internal/issues/775
TODO:
- Punt to https://github.com/redpanda-data/core-internal/issues/802
- ~~CI not currently supported. Needs a manual smoke test. Results to follow~~
- ~~Update: Some challenges here:~~
-  ~~Had some issues setting up ADDS last week - as yet unresolved~~
- ~~Ducktape/kerberos bits are working fine, but we don't have a client available that supports both GSSAPI and kip-368~~
* Add broker support for SASL reauthentication. To enable, config `connections_max_reauth_ms > 0`.
=> Kip 368 (SASL reauthentication)

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
`test_max_connections` should be updated to detect errors in logs and handle unresponsive cluster
* none
=> Update max connections test for Tier-5

tests/rptest/tests/topic_recovery_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14302
Fixes: https://github.com/redpanda-data/redpanda/issues/14737,
=> [v23.2.x] ducktape/cloud_storage: Ignore accessdenied errors

tests/rptest/tests/usage_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14144
Fixes: https://github.com/redpanda-data/redpanda/issues/14292,
=> [v23.1.x] Fix for CI Failure (invalid timer interval) in `UsageTest.test_usage_metrics_collection`

tests/rptest/tests/timequery_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12127
Fixes: https://github.com/redpanda-data/redpanda/issues/13214,
=> [v22.3.x] ducktape: extend timeout in timequery_test

tests/rptest/tests/memory_stress_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12497
Fixes: https://github.com/redpanda-data/redpanda/issues/14752,
=> [v23.1.x] dt/memory_stress_test: Mark `test_fetch_with_many_partitions` `@ok_to_fail`

tests/rptest/tests/memory_stress_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/12497
Fixes: https://github.com/redpanda-data/redpanda/issues/14754,
=> [v23.2.x] dt/memory_stress_test: Mark `test_fetch_with_many_partitions` `@ok_to_fail`

src/v/cloud_storage/materialized_resources.cc, src/v/cloud_storage/materialized_resources.h, src/v/cloud_storage/remote_partition.cc, src/v/utils/adjustable_semaphore.h
Partially fixes https://github.com/redpanda-data/redpanda/issues/12382
When waiting for resource during creation of a remote partition/segment reader, we wait for semaphore units at some places. During this wait if the client disconnects the wait is not interrupted. 
The log reader config used to create readers has an optional reference to an abort source, which is connected to the kafka connection, and is triggered when the connection shuts down.
This change wires in the abort source to the waiting for units, so we can abort the wait if the connection is killed. 
Part of the delay in connections going down in https://github.com/redpanda-data/redpanda/issues/12382 is due to several readers' creation blocked on acquiring units, while the rpk process had been killed several seconds ago. …
=> cloud_storage: Use abort source when waiting for semaphore units

tests/rptest/scale_tests/high_throughput_test.py
CDT fails with `Failed to import rptest.scale_tests.high_throughput_test, which may indicate a broken test that cannot be loaded: NameError: name 're' is not defined` leading our nightlies to fail. ref https://redpandadata.slack.com/archives/C0365QZSTLM/p1698901767072869
https://buildkite.com/redpanda/redpanda/builds/40276
* none
=> [v23.2.x] tests/htt: import missing regex package that breaks tests

src/v/archival/ntp_archiver_service.h, src/v/cluster/archival_metadata_stm.cc, src/v/cluster/archival_metadata_stm.h, src/v/cluster/partition.cc, src/v/cluster/partition.h, src/v/cluster/persisted_stm.cc, src/v/cluster/persisted_stm.h, src/v/redpanda/admin/api-doc/shadow_indexing.json, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h, tests/rptest/services/admin.py, tests/rptest/tests/e2e_shadow_indexing_test.py
Backport of :
* #13896: I had to omit the tests added in the original PR since they use gtest and support for that was not back ported.
* #14597: This mostly back ported fine. In v23.2 `partition::start` does not construct the archiver. That's done in the constructor instead. This means that the we don't have to grab the new archiver lock in `partition::start` for the backport.
=> [v23.2.x] archival: reset in-memory partition manifest to uploaded manifest

src/v/cloud_storage/materialized_resources.cc, src/v/cloud_storage/materialized_resources.h, src/v/cloud_storage/remote_partition.cc, src/v/utils/adjustable_semaphore.h
Partially fixes https://github.com/redpanda-data/redpanda/issues/12382
Fixes #14757
Backport of the #14637
When waiting for resource during creation of a remote partition/segment reader, we wait for semaphore units at some places. During this wait if the client disconnects the wait is not interrupted. 
The log reader config used to create readers has an optional reference to an abort source, which is connected to the kafka connection, and is triggered when the connection shuts down.
This change wires in the abort source to the waiting for units, so we can abort the wait if the connection is killed. 
Part of the delay in connections going down in https://github.com/redpanda-data/redpanda/issues/12382 is due to several readers' creation blocked on acquiring units, while the rpk process had …
=> [v23.2.x] cloud_storage: Use abort source when waiting for semaphore units

src/v/archival/ntp_archiver_service.cc, src/v/archival/ntp_archiver_service.h, src/v/archival/scrubber.cc, src/v/archival/scrubber.h, src/v/archival/scrubber_scheduler.h, src/v/archival/tests/scrubber_scheduler_test.cc, src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/partition_manifest.h, src/v/cloud_storage/tests/anomalies_detector_test.cc, src/v/cloud_storage/types.cc, src/v/cloud_storage/types.h, src/v/cluster/archival_metadata_stm.cc, src/v/cluster/archival_metadata_stm.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/admin/api-doc/shadow_indexing.json, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h, tests/rptest/services/admin.py, tests/rptest/services/cluster.py, tests/rptest/services/redpanda.py, tests/rptest/tests/cloud_storage_scrubber_test.py
This patch set has the goal of performing an internal (as opposed to external via rp-storage-tool) scrub
for each partition at the end of each tiered storage tests. This change is made in the final commit, but
there are a number of prerequisites:
1. Split the `cloud_storage_scrubbing_interval_ms` config into two separate configs: `cloud_storage_{partia|full}_scrub_interval_ms`. The partial interval is applied for scrubs
which continue the work of a previous scrub. The full interval is applied after a scrub which
has reached the end of the log. In production, I expect these values to always be the same,
but they're very useful for testing as it allows us to pause scrubbing after the end of the log was reached.
2. An endpoint for resetting scrubbing metadata is also added to clear any …
=> cloud_storage: perform a full internal scrub at the end of TS tests

src/v/cloud_storage_clients/s3_client.cc
`DeleteRecords` response sometimes do not contain `DeleteResult` XML field. Log the XML object on trace level in this case.
It's not clear why this might happen. This behavior is clearly outside of the S3 REST API spec. We should probably just ignore this on CI. But to know for sure we need to actually know what was the content of the reply.
* none
=> s3: Log xml body in case of ill-formed reply

src/v/cluster/commands.h, src/v/cluster/controller_log_limiter.h, src/v/cluster/controller_snapshot.cc, src/v/cluster/controller_snapshot.h, src/v/cluster/topic_table.cc, src/v/cluster/topic_table.h, src/v/cluster/topic_updates_dispatcher.cc, src/v/cluster/topic_updates_dispatcher.h, src/v/cluster/topics_frontend.cc, src/v/cluster/topics_frontend.h, src/v/cluster/types.cc, src/v/cluster/types.h, src/v/features/feature_table.cc, src/v/features/feature_table.h, src/v/redpanda/admin/api-doc/cluster.json, src/v/redpanda/admin/api-doc/partition.json, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h, tests/rptest/services/admin.py, tests/rptest/tests/recovery_mode_test.py
Add admin APIs for setting the disabled flag and storing it in the topic table.
Also add APIs for viewing the cluster-wide list of partitions/list of partitions of a single topic with filtering by the `disabled` flag.
* Added admin APIs for viewing the cluster-wide list of partitions/list of partitions of a single topic.
=> APIs for disabling topics/partitions and listing them

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
Fixes #14760
Follow-up to PR #14640
fix usage of _partitions_min
* none
=> rptest: fix use of partitions_min in htt

src/go/rpk/pkg/serde/proto_test.go, src/go/rpk/pkg/serde/serde.go
rpk now will auto-select the fully qualified name of the message when running 'rpk topic produce' if the schema only contains a single message.
No release notes here since this is a feature that is not yet released:
* none
=> rpk: select FQN of msg in SR schema when producing

cmake/dependencies.cmake
We want to support Ubuntu in our open-source build.
The version of Abseil in Ubuntu Mantic is compatible with the version we use in our private build. However, for reasons not yet known, the installation of Abseil in Ubuntu is configured to not auto-detect absl::string_view replacement for std::string_view, breaking several things in cloud storage and wasm which assume that these types are the same.
Update. In the Debian package configure patch:
```
- To minimize the possibility of future ABI breakage, treat absl::any,
absl::optional, absl::string_view, and absl::variant as their own types
(rather than aliases for the std:: versions), and compile everything in an
inline namespace.
```
Which I guess is a fine policy. But we want to build from source, so here we are.
* none
=> build: install abseil for the open-source build

tests/docker/Dockerfile, tests/docker/ducktape-deps/librdkafka, tests/setup.py
Addresses issue https://github.com/redpanda-data/devprod/issues/903
for running tests on cdt against v23.2.x rc release, unable to build packer image with error:
```
==> redpanda-testing.amazon-ebs.ubuntu:          66 | #error "confluent-kafka-python requires librdkafka v2.2.0 or later. Install the latest version of librdkafka from the Confluent repositories, see http://docs.confluent.io/current/installation.html"
```
seems like we need commit e09c68ad40a23a9f15178615cbd053a2cde288d4 from PR #13822 to be backported:
```console
git cherry-pick -x e09c68ad40a23a9f15178615cbd053a2cde288d4
```
backport was clean:
```
Auto-merging tests/docker/Dockerfile
Auto-merging tests/setup.py
[v23.2.x-confluent-kafka-v2.2.0 e66e0f14da] ducktape: Update librdkafka and confluent-kafka to v2.2.0
Author: …
```
=> [v23.2.x] ducktape: Update librdkafka and confluent-kafka to v2.2.0

src/v/raft/state_machine.cc
state_machine::apply():
elevate the logging for an unknown exception to error.
The behavior of redpanda is unchanged, but this will make this kind of exception visible in the logs and ducktape.
* none
=> raft/state_machine: log error for unknown exception

src/v/cluster/distributed_kv_stm.h, src/v/cluster/distributed_kv_stm_types.h, src/v/cluster/tests/distributed_kv_stm_tests.cc, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/ssx/sleep_abortable.h, src/v/test_utils/async.h, src/v/transform/CMakeLists.txt, src/v/transform/api.cc, src/v/transform/api.h, src/v/transform/commit_batcher.cc, src/v/transform/commit_batcher.h, src/v/transform/fwd.h, src/v/transform/io.h, src/v/transform/rpc/client.cc, src/v/transform/rpc/client.h, src/v/transform/rpc/serde.h, src/v/transform/rpc/tests/transform_rpc_test.cc, src/v/transform/tests/CMakeLists.txt, src/v/transform/tests/commit_batcher_test.cc, src/v/transform/tests/test_fixture.cc, src/v/transform/tests/test_fixture.h, src/v/transform/tests/transform_manager_test.cc, src/v/transform/transform_processor.cc
In order to scale the number of processors that can concurrently run in a cluster, we create a batcher for commit requests so that commits scale with the number of cores, not the number of processors.
There is an unfortunate effect here that we delay processors for a commit interval before starting up, as we need to wait for other nodes to potenially flush the latest commit information. Otherwise everytime there is a leadership transfer it becomes very likely that we process duplicates, while we can't prevent duplicates in the current architecture, we can reduce their likelyhood with this approach.
The main benefit of this work is that we can punt further down the road the need to dynamically scale (and migrate existing data of) the internal topic we use for tracking offset positions.
* …
=> transform: batch offset commits per core

tests/docker/ducktape-deps/ocsf-server, tests/rptest/services/ocsf_server.py
Fixes: #14749
Fixes: #14750
Fixes: #14751
* none
=> dt/audit: Wait for OCSF server to really come up

src/v/model/tests/transform_test.cc, src/v/model/transform.cc, src/v/model/transform.h, src/v/transform/rpc/client.cc, src/v/transform/tests/test_fixture.cc, src/v/transform/tests/test_fixture.h, src/v/transform/tests/transform_processor_test.cc, src/v/transform/transform_processor.cc, src/v/wasm/wasmtime.cc
This patchset cleans up the way we create batches from transformed records and fixes an issue with writing empty batches.
* none
=> wasm: cleanup batching

tests/rp_cloud_cleanup.py, tests/rptest/services/redpanda_cloud.py
related to issue https://github.com/redpanda-data/redpanda/issues/14765
to get some of the fixes from WIP PR #14787 merged first, cherry-picking:
```console
git cherry-pick -x 8091429aa3303edcb569fc277b3f5bae0871c9bc 35eae8825b528aaf9f2461760a553a0bf528eee6 53e93dd472d2abd1bd562956e52d75b9ea436ff6 600849d1d384bc5d41b79b355e745bc8f1ca8a3d
```
no conflicts:
```
[hotfix-cdt-cloudv2 14de049acb] ci: Cloud cleanup hotfix
Author: Alex Savatieiev <a.savex@gmail.com>
Date: Mon Nov 6 16:12:00 2023 -0600
1 file changed, 1 insertion(+), 1 deletion(-)
[hotfix-cdt-cloudv2 c6a5b4f24a] rptest: Cloud install_pack_version hotfix
Author: Alex Savatieiev <a.savex@gmail.com>
Date: Mon Nov 6 16:12:53 2023 -0600
1 file changed, 2 insertions(+)
[hotfix-cdt-cloudv2 396480a6b7] ci: Fix deletion of FMC clouds …
```
=> tests: hotfixes for running cdt tests on cloudv2

src/v/cluster/plugin_frontend.cc, src/v/cluster/tests/plugin_frontend_validation_test.cc, src/v/cluster/topics_frontend.cc, src/v/redpanda/application.cc, src/v/transform/api.cc, src/v/transform/api.h
Remove copartitioning requirement from transforms, we do this by round robin style assigning input partitions to output partitions.
This will support filter use cases that want to take a 100 partition topic and write to a 1 partition output topic (assuming the filter removes 99% of data).
* none
=> transform: remove copartitioning requirement

src/v/coding-style.md
This style guide was not updated in any meaningful way for >4 years. We had started a github discussion, but that is too unstructured. I've copied over parts of that discussion and will close the github discussion. Making this be committed into the tree will force consensus in the context of PRs.
* none
=> doc: update style guide from discussion

src/v/cluster/topics_frontend.cc
The missing argument caused logging to fail, which somehow caused a
crash. I'm still figuring out why fail to log caused a crash, but at 
least this prevents that code path from happening.
Fixes: #14804
* none
=> cluster/topics_frontend: fix log statement

tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/services/redpanda_cloud.py
When there is not enough instances of needed type on provider side, initial cluster creation struggles to even add cluster to CloudV2 API listing. To eliminate 1h wait, fail after 2 min if initial cluster spec not created
* none
=> User friendly errors on cluster creation and initial cluster check to fail fast on resource limitations

src/v/cluster/rm_stm.cc
When `rm_stm` is stopped it should release all used resources including metrics name. This will allow partition to be recreated if required.
- none
=> rm_stm: clear metrics when stopping rm_stm

src/v/cloud_roles/aws_refresh_impl.cc, src/v/cloud_roles/aws_sts_refresh_impl.cc, src/v/cloud_roles/gcp_refresh_impl.cc, src/v/cloud_roles/refresh_credentials.cc, src/v/cloud_roles/refresh_credentials.h, src/v/cloud_storage_clients/configuration.cc, src/v/cluster/metrics_reporter.cc, src/v/net/probes.cc, src/v/net/tls_certificate_probe.h, src/v/pandaproxy/server.cc, src/v/redpanda/admin_server.cc, src/v/redpanda/application.cc, tests/docker/ducktape-deps/tool-pkgs, tests/rptest/services/tls.py, tests/rptest/tests/tls_metrics_test.py
This PR introduces a number of new Prometheus metrics allowing administrators
to track and monitor TLS issues as they arise. The metrics are
- `truststore_expires_at_timestamp_seconds`
- The expiration time (unix timestamp) of the shortest-lived CA in
the installed CA chain
- `certificate_expires_at_timestamp_seconds`
- The expiration time (unix timestamp) of the installed server cert
- `certificate_serial`
- The serial number of the installed server cert
- `loaded_at_timestamp_seconds`
- The last time (unix timestamp) certificates were loaded for a given
service.
- `certificate_valid`
- Whether the installed certificate is still valid
This PR also introduces a new ducktape pseudo-service to generate and manage CA
for the purpose of testing the above.
Fixes …
=> TLS Certificate Metrics

src/v/cluster/tm_stm.cc, tests/rptest/tests/transactions_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14784
Fixes: https://github.com/redpanda-data/redpanda/issues/14800,
=> [v23.1.x] tm_stm: add tx to cache on create

src/v/cluster/tm_stm.cc, tests/rptest/tests/transactions_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14784
Fixes: https://github.com/redpanda-data/redpanda/issues/14799,
=> [v23.2.x] tm_stm: add tx to cache on create

src/v/ssx/future-util.h, src/v/ssx/tests/future_util.cc, src/v/transform/api.cc, src/v/transform/io.h, src/v/transform/tests/test_fixture.cc, src/v/transform/tests/test_fixture.h, src/v/transform/transform_processor.cc
Two improvements to reading data in the transform subsystem:
1. Support log truncation by always starting reads at the beginning of the log
2. Limit the amount of bytes we get back from the reader. The limit is hardcoded
(and also a soft limit), but is better than the previous unlimited maximum.
* none
=> transform: reader improvements

src/v/kafka/latency_probe.h, src/v/kafka/server/handlers/fetch.cc
Adds a histogram metric to measure the time it takes to create the fetch
plan and execute it - aka a single fetch poll.
It's an approximation for the time it takes to process the data in a
fetch request once it is available.
I have separated two series one which is tracking empty fetches and one
that isn't.
Further the count of the histogram can be used to calculate the ratio of
fetch requests to polls like so:
```
sum(irate(vectorized_kafka_handler_requests_completed_total{...,
handler="fetch"}[$__rate_interval])) by ($aggr_criteria) /
sum(irate(vectorized_fetch_stats_plan_and_execute_latency_us_count{...}[$__rate_interval])) by
($aggr_criteria)
```
Looking at some scenarios we get the following values:
- 500MB/s, 4P/4C, 288P, ~110k batch, 1ms debounce: ~0.37
- 500MB/s, 4P/4C, 288P, …
=> kafka: Add fetch plan and execute latency metric

src/v/cluster/tm_stm.cc, src/v/cluster/tm_stm_cache.cc, src/v/cluster/tx_gateway_frontend.cc, src/v/cluster/types.cc, src/v/cluster/types.h
Made transaction related logs more structured. Now each log line is prefixed with `[tx_id=<value>]` which allows to easily query for the transaction id flow.
- easier to understand transaction related logs
=> Improved logging around tx processing

src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_segment.cc, src/v/kafka/server/connection_context.h, src/v/kafka/server/handlers/fetch.cc, src/v/kafka/server/handlers/fetch.h, src/v/model/fundamental.h, src/v/net/server.cc, src/v/storage/types.cc, src/v/storage/types.h
The tiered storage read path has several points where a kafka connection has to block for resources such as semaphore units, downloads, copying files around etc. The reader config which links the kafka API to tiered storage read path only shares log offsets, which makes it hard to identify which specific connection may be blocked for resources in the read path.
In this changeset the client address is added to the kafka fetch config and the log reader config, and the address is then used in the read path to log when waiting for resources at trace level. This makes it somwhat easier to identify in logs as to which connections are stuck.
The client address is optional.
* none
=> cloud_storage: Add client address to fetch and log reader config

src/go/rpk/pkg/adminapi/api_transform.go, src/go/rpk/pkg/cli/transform/list.go, src/go/rpk/pkg/cli/transform/list_test.go, src/v/model/transform.cc, src/v/model/transform.h, src/v/redpanda/admin/api-doc/transform.json, src/v/redpanda/admin_server.cc, src/v/transform/probe.cc, src/v/transform/probe.h, src/v/transform/transform_manager.cc, src/v/transform/transform_processor.cc, src/v/transform/transform_processor.h, tests/rptest/clients/rpk.py
Create metrics for how far behind transforms are. This is important to
know if a user needs to scale up or improve the performance of their
transforms.
* none
=> transform/processor: lag metrics

src/v/cluster/controller.cc, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/json/pointer.h, src/v/security/CMakeLists.txt, src/v/security/config_rcl.cc, src/v/security/fwd.h, src/v/security/jwt.h, src/v/security/oidc_authenticator.cc, src/v/security/oidc_authenticator.h, src/v/security/oidc_error.h, src/v/security/oidc_principal_mapping.cc, src/v/security/oidc_principal_mapping.h, src/v/security/oidc_service.cc, src/v/security/oidc_service.h, src/v/security/tests/CMakeLists.txt, src/v/security/tests/jwt_test.cc, src/v/security/tests/oidc_principal_mapping_test.cc, tests/rptest/tests/cluster_config_test.py
Fixes https://github.com/redpanda-data/core-internal/issues/847
New cluster configuration options:
| option | description | default |
| -- | -- | -- |
| `oidc_principal_mapping` | "Rule for mapping JWT Payload claim to a Redpanda User Principal" | `$.sub` |
The rule mapping is as follows:
```
rule                = "$" segments [ mapping ]
segments            = "." fieldname { "." fieldname }
mapping             = "/" regex_pattern "/" replacement_pattern "/" [ case_modifier ]
replacement_pattern = replacement_element { replacement_element }
replacement_match   = "$" digit
replacement_element = replacement_match | arbitrary_text
case_modifier       = "L" | "U"
```
The mapping part is very similar to the [mtls principal mapping](https://docs.redpanda.com/current/manage/security/authenticatio …
=> security/oidc: Allow mapping of principals

src/v/net/connection.cc, tests/rptest/tests/rpk_registry_test.py
Add `GNUTLS_E_DECRYPTION_FAILED` to `is_reconnect_error`.
This error has been seen at the end of consume with rpk.
Fixes https://github.com/redpanda-data/redpanda/issues/14619
* Redpanda: Lower the log level if `GNUTLS_E_DECRYPTION_FAILED` is encountered.
=> net: GNUTLS_E_DECRYPTION_FAILED is_reconnect_error

src/v/archival/segment_reupload.cc, src/v/archival/tests/segment_reupload_test.cc
After a delete-records request, when collecting segments to determine the next upload candidate, we could end up trying to build an upload candidate with a start offset lower than the local log. Consider the following sequence:
- Segment [0, 200)[200-400) are merge compacted ==> [0, 400).
- Delete records ==> start offset is now 1.
- Reupload our first compacted segment so we look up offset 1, realign the collection start target to a remote segment 200.
- We collect segments starting from 200, getting [0, 400).
- Collector gets realigned to 0 since it's the first segment. The collector now thinks it should be uploading [0, 400).
- In building the upload candidate, we try to translate the range start and fail because the range start 0 is lower than the translation range start 1.
This fixes …
=> archival: start reupload range after log start

src/v/CMakeLists.txt, src/v/io/CMakeLists.txt, src/v/io/cache.h, src/v/io/tests/CMakeLists.txt, src/v/io/tests/cache_test.cc, tools/gcovr
implementation of s3-fifo cache eviction algorithm for use in unified i/o proposal proof-of-concept.
coverage report 💯.
```
[nwatkins@fedora coverage]$ src/v/io/tests/io_rpunit
[nwatkins@fedora coverage]$ ../../tools/gcovr -f ../../src/v/io/
------------------------------------------------------------------------------
GCC Code Coverage Report
Directory: ../..
------------------------------------------------------------------------------
File                                       Lines    Exec  Cover   Missing
------------------------------------------------------------------------------
src/v/io/cache.h                             108     108   100%
src/v/io/tests/cache_test.cc                 492     492   100%
----------------------------------------------------------------------------- …
```
=> s3-fifo cache eviction algorithm

tests/rptest/test_suite_cloud.yml
this PR is no urgent. `HighThroughputTest2` class no longer exists, but tests still run.
* none
=> rptest: cleanup unused tests in test_suite_cloud.yml

src/v/cloud_storage_clients/s3_client.cc, src/v/cloud_storage_clients/s3_client.h, src/v/cloud_storage_clients/tests/s3_client_test.cc
FIXES: #14014 
When searching for error codes in an XML tree, ptree::count which we used does not honor dot paths. The change uses get_optional and adds some tests for the method.
* none
=> cloud_storage_clients: Fix xml parsing when searching for error code in response

src/v/transform/probe.cc
As I was reading over these to announce, I realized there is an issue
that lag is a guage, and also took a stab at improving the documentation
for metrics.
* none
=> transform/probe: cleanup metrics

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
set as `@ok_to_fail` for now while we work out details of how the operation should perform
related issue: https://github.com/redpanda-data/redpanda/issues/14766
* none
=> rptest: ok_to_fail test_decommission_and_add

src/v/rpc/rpc_server.cc
More visibility will allow identify which method is not doing exhausting exception handling. E.g. for cases like this
https://github.com/redpanda-data/redpanda/issues/13456
* none
=> rpc: log method_id on service handler errors

src/v/pandaproxy/schema_registry/storage.h, src/v/pandaproxy/schema_registry/test/storage.cc
An example of a config record to be supported.
```json
{
"topic": "_schemas",
"key": "{\"keytype\":\"CONFIG\",\"subject\":\"test-ben1234\",\"magic\":0}",
"value": "{\"subject\":\"test-ben1234\",\"compatibilityLevel\":\"FULL_TRANSITIVE\"}",
"timestamp": 1699574968787,
"partition": 0,
"offset": 2
}
```
The subject field in the value is not checked against the key.
Fixes: https://github.com/redpanda-data/core-internal/issues/882
* Schema Registry: Improve compatibility of reading schemas that were created by another registry.
=> schema_registry: Support the compatible format for CONFIG value

src/v/net/connection.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14823
Fixes #14833
=> [v23.1.x] net: GNUTLS_E_DECRYPTION_FAILED is_reconnect_error

src/v/net/connection.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14823
Fixes #14834
=> [v22.3.x] net: GNUTLS_E_DECRYPTION_FAILED is_reconnect_error

src/v/pandaproxy/schema_registry/storage.h, src/v/pandaproxy/schema_registry/test/storage.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14866
=> [v23.2.x] schema_registry: Support the compatible format for CONFIG value

src/v/pandaproxy/schema_registry/storage.h, src/v/pandaproxy/schema_registry/test/storage.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14866
=> [v23.1.x] schema_registry: Support the compatible format for CONFIG value

src/v/kafka/server/server.cc, tests/rptest/tests/transaction_kafka_api_test.py
Previously the status was rendered directly as a string representation
of Redpanda internal status. Changed it to Kafka used status strings.
All the credits goes to @bharathv as he found this issue
- Fixed transaction status being incorrectly reported when listing transactions via Kafka API
=> fixed rendering transaction status

.github/workflows/build-redpanda.yml
ci: put a time limit on redpanda build job
* none
=> ci: put a time limit on redpanda build job

src/v/transform/tests/test_fixture.cc, src/v/transform/tests/test_fixture.h, src/v/transform/tests/transform_processor_test.cc, src/v/transform/transform_processor.cc, src/v/wasm/cache.cc
It's possible that a stopped processor (due to errors) is
stopped again because of shutdown or removal. This messes up the ref
counting in the cached engine. To guard against this we need to not call
stop twice on the engine.
Two options: Make the processor guard against double stops, don't call
stop twice in the processor. I think it's a the safer option to guard
against double stops in the processor, as the bookkeeping in the
processor is already fairly complex and this seems simpler.
Happy to take suggestions for alternative fixes.
* none
=> transform: guard against double stops

src/v/io/interval_map.h, src/v/io/tests/interval_map_test.cc
A bit more explicit, hard to make mistakes and easier to read.
* none
=> io: use structured interface for interval map

src/v/raft/consensus.cc, tests/rptest/tests/simple_e2e_test.py
When Raft handles replicate requests of mixed consistency levels it has
to separately track the visibility of both type of replicate requests.
i.e. `quorum_ack` requests should not be visible to readers until they
are successfully replicated and flushed on the majority of nodes while
for `leader_ack` requests it is enough to have them acknowledged and not
flushed by majority of nodes. When `quorum_ack` batch is committed then
all subsequent majority replicated `leader_ack` batches may become
immediately visible to consumers if they are majority confirmed. Fixed
bug in Raft where the majority replication wasn't validated correctly
and 'dirty' batches were made visible to the consumer. It might lead to
situation in which consumer read batches which were then not available
on newly elected …
=> Fix for `leader_ack` consistency level (do not advance last visible offset beyond majority replicated)

src/v/io/cache.h, src/v/io/tests/cache_test.cc
Provides a fmt::formatter for io::cache.
* none
=> io: make io::cache formattable

src/v/cluster/cluster_utils.h, src/v/cluster/commands.h, src/v/cluster/config_frontend.cc, src/v/cluster/controller.cc, src/v/cluster/feature_manager.cc, src/v/cluster/members_frontend.cc, src/v/cluster/members_frontend.h, src/v/cluster/members_manager.cc, src/v/cluster/security_frontend.cc, src/v/cluster/tests/commands_serialization_test.cc, src/v/cluster/tests/serialization_rt_test.cc, src/v/cluster/tests/topic_updates_dispatcher_test.cc, src/v/cluster/topics_frontend.cc, src/v/features/feature_table.cc, src/v/features/feature_table.h, src/v/features/tests/feature_table_test.cc
As the feature was introduced in cluster version `5` we may retire it and make code a little simpler. Another benefit is releasing one bit for future features.
- none
=> features: retire serde controller commands feature

src/v/redpanda/application.cc
It's monotonically increasing; conceptually it's a counter.
* redpanda: Make `redpanda_cpu_busy_seconds_total` metric a counter instead of a gauge.
=> redpanda: Make `redpanda_cpu_busy_seconds_total` a counter

tests/rptest/services/redpanda.py, tests/rptest/services/redpanda_monitor.py
This method is used often to identify if redpanda is still running. If
the error is not propagated then the caller can't differentiate between
redpanda process not existing vs call failing.
Should help debug issues like #7679.
* none
=> rptest: improve redpanda_pid method

cmake/dependencies.cmake, licenses/third_party.md
ada uses CPM: https://github.com/cpm-cmake/CPM.cmake
Disable ADA_TESTING, ADA_TOOLS, ADA_BENCHMARKING to prevent CPM from downloading 3rdparty repositories.
I'm still seeing this message:
```
Generating ada.cpp, ada.h, ada_c.h, demo.cpp, demo.c, README.md
fatal: detected dubious ownership in repository at '/var/lib/buildkite-agent/builds/buildkite-amd64-builders-i-0d17fc136ea6bdd74-1/redpanda/redpanda'
```
Also add the license.
* none
=> 3rdparty: Disable tests and tools for ada

tests/rptest/tests/partition_balancer_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14181
Fixes: https://github.com/redpanda-data/redpanda/issues/14933,
=> [v23.2.x] tests: retry on timeout in partition balancer test

src/v/redpanda/application.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14905
=> [v22.3.x] redpanda: Make `redpanda_cpu_busy_seconds_total` a counter

src/v/redpanda/application.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14905
=> [v23.2.x] redpanda: Make `redpanda_cpu_busy_seconds_total` a counter

src/v/redpanda/application.cc, src/v/security/audit/audit_log_manager.cc, src/v/security/audit/audit_log_manager.h, src/v/security/audit/schemas/tests/ocsf_schemas_test.cc, src/v/security/audit/schemas/types.h, src/v/security/audit/schemas/utils.cc, src/v/security/audit/schemas/utils.h, src/v/security/audit/tests/audit_log_test.cc, tests/rptest/tests/audit_log_test.py
Add audit messages to monitor the life cycle of the application and audit log manager.
Force push [`62f8fcc`](https://github.com/redpanda-data/redpanda/compare/577babafe622040e06ee23b4bfc11155faf91148..62f8fcc37ab5b91563fcfc419377eced2469b281):
* Rebased off of dev
Force push [`0829549`](https://github.com/redpanda-data/redpanda/compare/62f8fcc37ab5b91563fcfc419377eced2469b281..0829549f80dc1dfa7671b5d7e1a8bd1125b9d086):
* Removed `audit_schemas.py` file that snuck in from rebase
Force push [`4824ad3`](https://github.com/redpanda-data/redpanda/compare/0829549f80dc1dfa7671b5d7e1a8bd1125b9d086..4824ad361d4e26f16842aa379efdd15873693586):
* Fixed flaky test
Force push `77bef0a`:
* Updates from PR comments
Force push `d935717`:
* Fix for flakey unit test
Force push `a743b7f`:
* Rebase off dev …
=> Audit app lifecycle

src/go/rpk/pkg/cli/cloud/byoc/install.go, src/go/rpk/pkg/cli/cloud/login.go, src/go/rpk/pkg/oauth/load.go, src/go/rpk/pkg/oauth/load_test.go, src/go/rpk/pkg/oauth/oauth.go, src/go/rpk/pkg/oauth/oauth_test.go
This PR:
- 1e302e426a35dfba827b989512f1718d77505e15 : adds `--no-browser` flag to `rpk cloud login` for non-UI users who are trying to login to Redpanda cloud using rpk. Fixes #14837
-  4c21514ddac9574bf936c3887e4c8addf5ca13c2 : Provides better error messages and hints in case of failure of `rpk cloud login` or when executing rpk cloud commands. Fixes #13980
* add `--no-browser` flag to `rpk cloud login` for non-UI users of rpk.
=> rpk: add no-browser to `cloud login`

src/v/archival/segment_reupload.cc, src/v/archival/tests/segment_reupload_test.cc
This updates the segment_collector collection to only move its collection start offset forward. Previously we were susceptible to the following issue:
- Say our manifest has [0, 10)[10,20)[20,25)[25,30), and we do one compacted upload [0, 25).
- Before we move onto persisting that fact into our manifest, we schedule our next upload, starting at 25.
- Schedule and compacted reupload starting from range 25.
- Locally, merge compact data such that we end up with local segment [20, 30).
- Locally, we only have a segment with [20, 30) that also happens to align with a remote segment in our manifest.
- We try to align the segment’s base offset 20, and get 20
- The new upload candidate is [20, 30).
- Total, we upload [0,25) [20,30).
* Fixes a bug in compacted segment reuploads that could result …
=> archival: always move reupload start forward

.github/workflows/build-redpanda.yml, install-dependencies.sh
Enables ccache for open-source build.
* none
=> build: enable ccache for open-source build

src/go/rpk/pkg/cli/transform/deploy.go
Instead of --env-var, just use the simpler --var flag
* none
=> rpk/transform/deploy: shorter env-var flag

src/v/archival/archival_policy.cc, src/v/archival/archival_policy.h, src/v/archival/ntp_archiver_service.cc, src/v/archival/segment_reupload.cc, src/v/archival/tests/ntp_archiver_reupload_test.cc, src/v/archival/tests/ntp_archiver_test.cc, src/v/archival/tests/segment_reupload_test.cc, src/v/archival/tests/service_fixture.cc, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/storage/disk_log_impl.cc, src/v/storage/disk_log_impl.h, src/v/storage/segment.cc, src/v/storage/segment_deduplication_utils.cc, src/v/storage/tests/storage_e2e_test.cc, tests/rptest/tests/cloud_storage_timing_stress_test.py
This commit enables sliding window compaction by default, including a few tweaks and fixes to make that possible:
- Fixed a segment locking issue (missing co_await).
- Runs adjacent segment merging if no segments are window compacted, ensuring a reduction in the number of segments (expected by many tests).
- Passes an abort source to compaction, allowing partition movement and deletion to abort compaction.
- Adds a cluster config to control whether sliding window compaction is used.
- Updates archival policy to look for window compacted segments instead of self compacted segments.
- Updates existing unit tests to account for this change (we're no longer always going to compact down to 2 segments, instead, we're just going to merge adjacent segments when we perform sliding window …
=> storage: enable sliding window compaction by default

src/go/rpk/pkg/cli/cloud/byoc/install.go, src/go/rpk/pkg/cli/cloud/login.go, src/go/rpk/pkg/oauth/load.go, src/go/rpk/pkg/oauth/load_test.go, src/go/rpk/pkg/oauth/oauth.go, src/go/rpk/pkg/oauth/oauth_test.go
Manual backport of #14939
Fixes #14943
* none
=> [v23.2.x] rpk: add no-browser to cloud login

src/v/cloud_storage/segment_meta_cstore.cc, src/v/cloud_storage/segment_meta_cstore.h, src/v/cloud_storage/tests/segment_meta_cstore_test.cc
segment_meta_cstore assumes that the segments form a continuous sequence (no gaps) and that replacements are aligned to pre-existing segments. 
a segment landing on a gap would erroneously end up appended to the store, due to the use of exact search to find the insertion point. the fix for this is to switch to lower_bound to search for the insertion point.
overlaps would ruin the merge loop, due to the assumption that [n].committed_offset <[n+i].base_offset. the fix for this is to switch to base_offset only check for the "<" operation.
the insert operation, that uses a map as a buffer, is also updated to allow for overlaps. the buffer is empty most of the time, due to the usage pattern in redpanda that triggers frequent flushes, so a bug here would go likely unnoticed.
before, the code …
=> segment_meta_cstore: handle gaps and overlaps

src/v/cloud_storage/segment_meta_cstore.cc, src/v/cloud_storage/segment_meta_cstore.h, src/v/cloud_storage/tests/segment_meta_cstore_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14856
=> [v23.2.x] segment_meta_cstore: handle gaps and overlaps

src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_segment.cc, src/v/kafka/server/connection_context.h, src/v/kafka/server/handlers/fetch.cc, src/v/kafka/server/handlers/fetch.h, src/v/model/fundamental.h, src/v/net/server.cc, src/v/storage/types.cc, src/v/storage/types.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/14821
=> [v23.2.x] cloud_storage: Add client address to fetch and log reader config

src/v/cloud_storage/remote_segment.cc
The client address is added to the remote segment batch parser logs. The address cannot be set as a member because a remote segment reader may be cached and have its configuration reset. The client address is always read from the configuration to make sure we get the latest address.
* none
=> cloud_storage: Log client address in batch parser

src/v/cloud_storage/remote_segment.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14957
=> [v23.2.x] cloud_storage: Log client address in batch parser

src/v/wasm/wasmtime.cc
This lowers the amount of fuel before we switch back to allowing the
reactor to run. Effectively simple tests show this limits wasm to ~1ms
of blocking time.
I am also thinking about making these tunables, but I'm not sold on us
using fuel long term (we may switch to time based limiting). So I'm holding 
off on that. Maybe it will make sense to convert a time unit into fuel and 
just make the tunable based on time, I suspect we'd only want this available
as an emergency hatch if user code is timing out on new input.
* none
=> wasm: lower fuel interval

src/v/pandaproxy/schema_registry/service.h, src/v/wasm/schema_registry.cc
Ensure that we start the schema registry if the first thing to use it is wasm.
* none
=> wasm/sr: initialize internal topic

src/v/redpanda/admin_server.cc
These are expected transform errors that means the user tried to do
something wrong with transforms, we should return 400s in this case.
* none
=> admin: handle transform errors with 400s

src/v/config/configuration.cc
This is how a user specifies how much memory they can give wasm and how
much a single function has, so make it more visible for them.
* none
=> config: make wasm memory user configurable

src/v/kafka/server/fwd.h, src/v/model/record_batch_reader.cc, src/v/model/record_batch_reader.h, src/v/random/generators.h, src/v/transform/CMakeLists.txt, src/v/transform/api.cc, src/v/transform/io.h, src/v/transform/tests/CMakeLists.txt, src/v/transform/tests/txn_reader_test.cc, src/v/transform/txn_reader.cc, src/v/transform/txn_reader.h
Use read committed isolation level for transforms.
Fixes an issue where we don't filter out control messages nor
do we drop aborted transactions before we surface batches to
the WebAssembly transform.
* none
=> transform: read committed isolation

src/v/cluster/service.cc
It's not safe to access the reference across scheduling points.
We should probably modify the RPC generator script to pass these by value.
* none
=> cluster/service: fix plugin RPCs

src/v/model/tests/transform_test.cc, src/v/model/transform.cc
We need to set this value correctly otherwise we create invalid batches
* none
=> model/transform: fix last_offset_delta for transformed batches

src/v/storage/disk_log_impl.cc, src/v/storage/segment_deduplication_utils.cc
Adds some log lines that should be helpful in identifying different stages done and decisions made in windowed compaction, and demotes a couple info log lines to debug level.
* none
=> storage: clean up logging in compaction code

cmake/testing.cmake, src/v/io/CMakeLists.txt, src/v/io/persistence.cc, src/v/io/persistence.h, src/v/io/tests/CMakeLists.txt, src/v/io/tests/common.cc, src/v/io/tests/common.h, src/v/io/tests/persistence_test.cc, tools/cmake_test.py
Adds disk and in-memory providers for the unified io proof-of-concept.
The storage provider gives access to storage for the io subsystem. There are two implementations, one that passes directly to Seastar I/O's subsystem and is intended for production cases. The second is an in-memory implementation that is useful in testing for speed and for enabling parameter exploration (e.g. alignments) that would not work on a real file system.
In addition to testing, the provider abstraction is a centralized location to implementation fault injection, tracking open-files, and allowing users (code) of I/O to be easier to identify.
One thing you may notice is that the disk-baesd file system of course provides cross-core uniqueness of files with no effort because this is enforced by the OS. This is not …
=> io: add storage provider

src/v/cluster/archival_metadata_stm.cc
When `persisted_stm::sync()` method fails it is indicating that the current node is not longer a leader. The `sync()` executed before `replicate` call in archival stm `command_batch_builder` prevents replicate from being called. The end result for such an error is deterministic and we can translate the sync error to `not_leader` error code.
Fixes: #14898
- none
=> c/archival_stm: translate sync error to not_leader error code

tests/rptest/tests/cluster_config_test.py
Issues #13787 and #13507 fail because they may observe a config being propagated to the nodes.
From the test executor's point of view, this interleaving is possible:
1. successfully set value on node 1, operation is propagated to the controller log of the cluster
2. read the correct value from node 1
3. read the old value from node 2
4. the test fails because of an eager assert
5. node 2 applies new value from its controller log
This pr waits for the config_version to be the same on all the nodes, with a 5s timeout, before checking that the config value is the same on all the nodes.
Fixes #13507 
Fixes #13787 
* none
=> tests/cluster_config_test: _check_value_everywhere retry and better error message

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
=> rptest: use thread to do rapid swarm start

src/go/rpk/pkg/adminapi/admin.go, src/go/rpk/pkg/adminapi/api_partition.go, src/go/rpk/pkg/cli/cluster/partitions/cancel.go, src/go/rpk/pkg/cli/cluster/partitions/cancel_hidden.go, src/go/rpk/pkg/cli/cluster/partitions/list.go, src/go/rpk/pkg/cli/cluster/partitions/move_status.go, src/go/rpk/pkg/cli/cluster/partitions/partitions.go, src/go/rpk/pkg/cli/cluster/partitions/status.go, src/go/rpk/pkg/cli/generate/app.go, src/go/rpk/pkg/cli/registry/schema/get.go
This PR introduces a new `rpk cluster partitions list` that uses the recently introduced admin API endpoint (https://github.com/redpanda-data/redpanda/pull/14461)
**EXAMPLES**
```
$ rpk cluster partitions list -a                  
NAMESPACE       TOPIC         PARTITION  LEADER-ID  REPLICA-CORE   DISABLED
kafka           bar           0          -          [1-4]          false
kafka           baz           0          -          [0-1 1-1 2-1]  false
kafka           baz           2          -          [0-3 1-3 2-3]  false
kafka           foo           0          -          [0-4]          false
kafka_internal  id_allocator  0          -          [0-5 1-5 2-4]  false
$ rpk cluster partitions list baz   
NAMESPACE  TOPIC  PARTITION  LEADER-ID  REPLICA-CORE   DISABLED
kafka      baz    0 …
```
=> rpk: add `rpk cluster partitions list` 

src/v/kafka/server/handlers/fetch.cc, src/v/kafka/server/request_context.h, tests/rptest/tests/audit_log_test.py
Analysis on LRC showed that fetch audit events were driving up consume and produce latencies due to the excessive number of events being generated for the same successful authz event.
This change adds new authorized method in request_context.h that will only audit successful commands when a flag is set.
Fetch handler will only enable that flag on the initial fetch pass.
Fixes: #14988
* none
=> k/server: Audit successful fetch authz only onces

src/v/storage/disk_log_impl.cc, src/v/storage/tests/compaction_e2e_test.cc
When the final segments in a sliding range contains only non-data
batches, we could previously end up recompacting the same range over and
over again. Consider the given sliding range, where segment [20, 25) is
all non-data batches.
[0, 10)[10, 20)[20, 25)
The compacted indices only contains data keys, so the key offset map
will only reflect data up to offset 20. Because of this, we would skip
compacting [20, 25) and leave the segment as is.
Subsequent attempts to compact would see that there is an uncompacted
segment, and attempt to compact the sliding range again, thinking that
the uncompacted data is new data to be merged in.
* none
=> storage: consider segments with only non-data batches as compacted

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
change from `@ok_to_fail` to `@ignore` since the test is now taking so long to run that it is affecting subsequent tests.
* none
=> rptest: ignore test_consume_miss_cache for now

src/v/cloud_storage/cache_probe.cc
This commit improves the description of
`redpanda_cloud_storage_cache_op_miss` to indicate cache is evicted unexpectedly.
Discussion with @abhijat https://redpandadata.slack.com/archives/C02BDN76HUK/p1697173009089389
* Improve description of `redpanda_cloud_storage_cache_op_miss`
=> cloud_storage: improve description of cache_op_miss

tests/rptest/services/redpanda_cloud.py
fix ducktape testing on cloud using FMC
https://buildkite.com/redpanda/vtools/builds/10641
```
File "/usr/local/lib/python3.10/dist-packages/ducktape/tests/runner_client.py", line 182, in _do_run
self.setup_test()
File "/usr/local/lib/python3.10/dist-packages/ducktape/tests/runner_client.py", line 260, in setup_test
self.test.setup()
File "/usr/local/lib/python3.10/dist-packages/ducktape/tests/test.py", line 91, in setup
self.setUp()
File "/home/ubuntu/redpanda/tests/rptest/tests/services_self_test.py", line 250, in setUp
self.redpanda.start()
File "/home/ubuntu/redpanda/tests/rptest/services/redpanda.py", line 1549, in start
cluster_id = self._cloud_cluster.create(superuser=superuser)
File "/home/ubuntu/redpanda/tests/rptest/services/redpanda_cloud.py", …
```
=> rptest: fix exception in getting init cluster spec

src/v/model/transform.h, src/v/transform/api.cc, src/v/transform/rpc/service.cc, src/v/transform/transform_processor.cc
Fixes some out of range translation errors I was seeing for empty topics. This is due to `model::prev_offset(0) == model::offset::min()`, and when passed as a max range throws an error as it cannot be translated. This doesn't happen in the fetch path due to short circuiting of empty reads before translation.
Additionally, fix an off by one error in loading wasm binaries. This isn't an issue in practice due to the bytes limit we have, but this clarifies the code. Also correct an issue in the data transform test. Lots of off by one errors :sigh:
* none
=> transform: fix translation errors

tests/rptest/tests/tiered_storage_model_test.py
During the model test the expectation is that at least seven or eight segments will be downloaded for TS_Read. The test produces 10MiB of data, 1MiB segment size and sets 3MiB as local retention size. The actual segments uploaded are roughly 2MiB each, resulting in fewer downloads.
This change doubles producer message count so that we need to produce and later download more segments to consume.
partially fixes #14266 (this issue wraps multiple CI failures)
* none
=> ducktape/cloud_storage: Increase producer msg count

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
change from `@ok_to_fail` to `@ignore` since this test is taking over 1 hr to run and is possibly affecting the subsequent test's test result.
related issue https://github.com/redpanda-data/cloudv2/issues/10373
* none
=> rptest: ignore test_decommission_and_add for now

src/v/storage/disk_log_impl.cc, src/v/storage/segment_deduplication_utils.cc, src/v/storage/segment_deduplication_utils.h, src/v/storage/segment_utils.cc, src/v/storage/segment_utils.h, src/v/storage/tests/log_truncate_test.cc, src/v/storage/tests/segment_deduplication_test.cc
This PR addresses some races between suffix truncation and compactions:
- A race between truncation and self compaction where the compacted index is removed during compaction. This would result in a thrown exception during compaction, but is somewhat benign since subsequent self compaction attempts will rebuild the compacted index. Still, this PR fixes this race by tweaking some segment locking.
- The above same race, but with windowed compaction. Unlike above, windowed compaction wouldn't subsequently try to rebuild the compacted index. Instead, it would to compact the same sequence of segments over and over, failing once it got to the segment with no compacted index. To address this, this PR adds the behavior of self compaction to windowed compaction, where if the compaction sees a …
=> storage: fix some compaction races with suffix truncation

src/v/archival/segment_reupload.cc, src/v/archival/tests/segment_reupload_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14816
=> [v23.2.x] archival: start reupload range after log start

src/v/cluster/archival_metadata_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/14978
Fixes: https://github.com/redpanda-data/redpanda/issues/14996,
=> [v23.2.x] c/archival_stm: translate sync error to not_leader error code

src/v/cluster/partition.h, src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h, src/v/cluster/tests/rm_stm_tests.cc, src/v/cluster/tx_snapshot_utils.cc, src/v/cluster/tx_snapshot_utils.h
Across recoveries of a cluster, the next producer_id used by the id_allocator needs to be reset to avoid using any that may have been used previously. So, this commit begins tracking the highest seen so far, and exposes it for use by the upload path (to come in a subsequent commit).
* none
=> rm_stm: interface for highest producer_id

src/v/cluster/cluster_utils.cc, src/v/cluster/node_status_backend.cc, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/raft/tests/raft_group_fixture.h, src/v/redpanda/application.cc, src/v/rpc/connection_cache.cc, src/v/rpc/connection_cache.h
See https://github.com/redpanda-data/redpanda/pull/11345 for details about changes.
* Adds `rpc_client_connections_per_shard` cluster property that allows for the number of clients a broker opens to a given peer to be user configurable.
=> Allow for `rpc_client_connections_per_peer` to be configured in v23.2.x

src/v/kafka/protocol/add_partitions_to_txn.h, src/v/kafka/server/handlers/txn_offset_commit.cc, src/v/kafka/server/server.cc, tests/rptest/clients/rpk.py, tests/rptest/tests/transactions_test.py
This PR adds authorization checks to transaction related API handlers.
Requirements were culled from the reference implementation, as follows:
- WRITE permissions for TRANSACTIONAL_ID
- TRANSACTIONAL_ID_AUTHORIZATION_FAILED
- WRITE permissions for TRANSACTIONAL_ID
- TRANSACTIONAL_ID_AUTHORIZATION_FAILED
- READ permissions for GROUP_ID
- GROUP_AUTHORIZATION_FAILED
- NOTE: Calls `handleAddPartitionsToTransaction` for the offset topic
- Presumably no check expected here as the topic is internal?
- WRITE permissions for TRANSACTIONAL_ID
- Filters topics by WRITE permission 
- TOPIC AUTHORIZATION_FAILED for those partitions
- Failed checks cause the whole transaction to fail
- WRITE permissions for TRANSACTIONAL_ID
- TRANSACTIONAL_ID_AUTHORIZATION_FAILED
- READ permissions for GROUP_ID
- …
=> Transactions API Authorization

src/v/cluster/partition_balancer_state.cc, src/v/cluster/scheduling/partition_allocator.cc, src/v/cluster/topic_table.cc, src/v/cluster/topic_table.h, src/v/cluster/topic_updates_dispatcher.cc, src/v/cluster/types.h
Introduce `is_cancelled_state` predicate that determines if the partition replicas update is cancelled and use it everywhere. This fixes the bug where `replicas_revisions` map in the topic table was not updated after force-update was finished.
* none
=> c/topic_table: fix force_update replicas_revisions update

src/v/kafka/protocol/kafka_batch_adapter.h, tests/rptest/services/admin.py, tests/rptest/services/redpanda.py, tests/rptest/tests/node_pool_migration_test.py
Extended node pool migration test with tiered storage and different cleanup policies.
- none
=> tests: added tiered storage to node pool migration test

src/v/cluster/controller.cc, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/admin/api-doc/security.def.json, src/v/redpanda/admin/api-doc/security.json, src/v/redpanda/admin/server.cc, src/v/redpanda/admin/server.h, src/v/security/exceptions.h, src/v/security/oidc_service.cc, src/v/security/oidc_service.h, src/v/security/request_auth.cc, src/v/security/request_auth.h, tests/rptest/tests/redpanda_oauth_test.py
| option | description | default |
| -- | -- | -- |
| `oidc_keys_refresh_interval` | "The frequency of refreshing the JSON Web Keys (JWKS) used to validate access tokens." | `1h` |
```json
"/v1/security/oidc/whoami": {
"get": {
"summary": "Obtain the principal and details of the JWT passed in the bearer token",
"operationId": "oidc_whoami",
"responses": {
"200": {
"description": "Successful response",
"schema": {
"description": "Details of the provided bearer token.",
"type": "object",
"properties": {
"id": {
"description": "Mapped principal for autherization.",
"type": "string"
},
"expire": {
"description": "Unix timestamp of the expiry of the token.",
"format": "uint64",
"type": "int"
}
}
}
},
"401": {
"description": "Unauthorized"
}
}
}
},
"/v1/security/oidc/keys/cache_invalidate": { …
```
=> security/oidc: Add metrics, JWKS refresh and Some admin endpoints

src/v/storage/disk_log_impl.cc
(cherry picked from commit 7a61a7edc9b2355406cc81d4b433c14c61b7697c)
* none
=> storage: fix variable name typo in gc logging statement

src/go/rpk/pkg/cli/transform/init.go, src/go/rpk/pkg/cli/transform/template/golang/transform.gosrc, src/transform-sdk/go/example_mirror_test.go, src/transform-sdk/go/example_regexp_filter_test.go, src/transform-sdk/go/example_transcoding_test.go, src/transform-sdk/go/go.mod, src/transform-sdk/go/internal/cache/cache_test.go, src/transform-sdk/go/internal/testdata/dynamic/transform.go, src/transform-sdk/go/internal/testdata/go.mod, src/transform-sdk/go/internal/testdata/identity/transform.go, src/transform-sdk/go/internal/testdata/schema-registry/transform.go, src/transform-sdk/go/internal/testdata/transform-error/transform.go, src/transform-sdk/go/internal/testdata/transform-panic/transform.go, src/transform-sdk/go/internal/testdata/wasi/transform.go, src/transform-sdk/go/processor.go, src/transform-sdk/go/serialize.go, src/transform-sdk/go/serialize_test.go, src/transform-sdk/go/sr/client.go, src/transform-sdk/go/sr/encoding.go, src/transform-sdk/go/sr/encoding_test.go
These were missed in: https://github.com/redpanda-data/redpanda/pull/14843
* none
=> transform-sdk/go: correct module path

src/v/features/feature_table.cc, src/v/features/feature_table.h, src/v/features/tests/feature_table_test.cc
The `serde_raft0` feature can not be completely retried from the feature table as the feature presence is checked in the previous versions of Redpanda. We need to first remove the checks validating if feature is active and only then retire the feature completely in the next version.
Retiring a feature caused the upgrade test to fail as the feature is expected to be active when some other subsequent features are active.
Fixes: #15046
- none
=> features: do not retire serde_raft0 feature

src/go/rpk/pkg/adminapi/api_partition.go, src/go/rpk/pkg/cli/cluster/partitions/move.go, src/go/rpk/pkg/cli/cluster/partitions/move_test.go, src/go/rpk/pkg/cli/cluster/partitions/partitions.go
In this PR, we add 'rpk cluster partitions move' that reassigns given partition replicas across brokers and cores. The command wraps the `/v1/partitions/{ns}/{topic}/{partition}/replicas` endpoint. Pasting the help text here:
```
This command changes replica assignments for given partitions. By default, it
assumes the "kafka" namespace, but you can specify an internal namespace using
the "{namespace}/" prefix.
To move replicas, use the following syntax:
rpk cluster partitions move foo --partition 0:1,2,3 -p 1:2,3,4
Here, the command assigns new replicas for partition 0 to brokers [1, 2, 3] and
for partition 1 to brokers [2, 3, 4] for the topic "foo".
You can also specify the core id with "-{core_id}" where the new replicas
should be placed:
rpk cluster partitions move foo -p 0:1-0,2-0,3-0 …
```
=> rpk: add 'partitions move' command

src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/tests/partition_manifest_test.cc, src/v/raft/state_machine_manager.cc, tests/rptest/tests/random_node_operations_test.py
Fixed errors leading to spurious error log lines being reported in `RandomNodeOperations` test
- none
=> `RandomNodeOperation` test improvements and fixes

tests/rptest/tests/redpanda_test.py, tests/rptest/utils/mode_checks.py
rptest: ignore instead of short-circuiting skip_debug_mode tests
By now I have run a few times tests with `@skip_debug_build` decoration and cheered when I saw them as passed in the report table. Only to learn later that no tests were actually run... With this change, the result 
table will actually indicate that tests were ignored.
Before:
```
run time:         8.493 seconds
tests run:        1
passed:           1
```
After:
```
run time:         0.009 seconds
tests run:        1
passed:           0
ignored:          1
```
* none
=> rptest: ignore instead of short-circuiting skip_debug_mode tests

src/v/transform/rpc/client.cc, src/v/transform/rpc/client.h
Use the same pattern for topic creation, and retry if we successfully
created the topic
* none
=> transform/rpc: uniform topic creation

src/v/cluster/topic_table.cc, src/v/cluster/topic_table.h, src/v/cluster/topics_frontend.cc, src/v/cluster/types.h, src/v/redpanda/admin/server.cc, tests/rptest/tests/recovery_mode_test.py
Previously we incorrectly assumed that fully enabling a partially disabled topic is a no-op. This is a no-op only if the topic was previously fully enabled.
* none
=> Fix enabling whole topic no-op check

src/v/compression/internal/lz4_frame_compressor.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15059
Fixes: https://github.com/redpanda-data/redpanda/issues/15087,
=> [v23.2.x] compression: correctly compute the output buffer size for lz4

src/v/wasm/allocator.cc, src/v/wasm/allocator.h, src/v/wasm/tests/wasm_allocator_test.cc, src/v/wasm/wasmtime.cc
Wasmtime assumes that memory returned from allocators is zero filled. We need to do this for our custom allocators too.
* none
=> wasm/alloc: zero fill memory

src/go/rpk/pkg/cli/topic/produce.go, tests/rptest/clients/rpk.py
Fxes #13874 
This change allows the user to follow the topicNameStrategy when producing to a topic using `rpk topic produce`. The idea is to pass a value of 'topic' to either schema-ID flag:
**Example:**
Full flow:
```
$ cat ~/code/tmp/sample.proto
syntax = "proto3";
package foo.bar;
message Person {
string name = 1;
int32 id = 2;  // Unique ID number for this person.
string email = 3;
enum PhoneType {
PHONE_TYPE_UNSPECIFIED = 0;
PHONE_TYPE_MOBILE = 1;
PHONE_TYPE_HOME = 2;
PHONE_TYPE_WORK = 3;
}
message PhoneNumber {
string number = 1;
PhoneType type = 2;
}
repeated PhoneNumber phones = 4;
}
message AddressBook {
repeated Person people = 1;
}
$ rpk registry schema create test-value --schema ~/code/tmp/sample.proto
SUBJECT     VERSION  ID    TYPE
test-value  1        10    PROTOBUF
$ echo …
```
=> rpk: support topic name strategy in `rpk topic produce`

src/go/rpk/pkg/adminapi/api_partition.go, src/go/rpk/pkg/cli/cluster/partitions/list.go, src/go/rpk/pkg/cli/cluster/partitions/partitions.go, src/go/rpk/pkg/cli/cluster/partitions/toggle.go, src/go/rpk/pkg/cli/cluster/partitions/toggle_test.go
This allows users to enable/disable either all partitions of a topic in a cluster or select which partitions to disable.
Fixes #14394 
There is a comment that needs to be resolved first: https://github.com/redpanda-data/redpanda/issues/14394#issuecomment-1804953589 
* rpk: add `rpk cluster partitions enable/disable`: now users can disable or enable partitions of a topic using rpk.
=> rpk: add `cluster partitions enable/disable`

src/v/cluster/plugin_frontend.cc, src/v/cluster/plugin_frontend.h, src/v/cluster/tests/plugin_frontend_validation_test.cc
This prevents folks writing to `__audit` from transforms
* none
=> cluster/plugin: prevent transforms to internal kafka topics

src/go/rpk/pkg/adminapi/api_partition.go
Redpanda's admin API interprets the absence of the 'disabled' query parameter differently from when its value is set to false.
If it's absent, it will list _all_ partitions, including disabled.
EXAMPLES:
```
$ rpk cluster partitions list -a 
NAMESPACE       TOPIC               PARTITION  LEADER-ID  REPLICA-CORE   DISABLED
kafka           __consumer_offsets  0          -          [0-5 1-6 2-5]  false
kafka           __consumer_offsets  1          -          [0-6 1-7 2-6]  false
kafka           __consumer_offsets  2          -          [0-7 1-8 2-7]  false
kafka           bar                 0          -          [0-1 1-2 2-1]  false
kafka           bar                 1          -          [0-2 1-3 2-2]  true   <--- #disabled included
kafka           bar                 2          - …
```
=> rpk: list all partitions, including disabled

src/v/transform/rpc/client.cc, src/v/transform/rpc/deps.cc, src/v/transform/rpc/serde.cc, src/v/transform/rpc/serde.h, src/v/transform/rpc/service.cc, src/v/transform/rpc/tests/transform_rpc_test.cc
In the future (ie a later release) we may want to request/batch multiple
offset fetches in a single RPC, this allows us to do that without any
breaking wire changes.
* none
=> transform/rpc: support batch offset loading

src/go/rpk/pkg/cli/cloud/login.go, src/go/rpk/pkg/cli/debug/bundle/bundle.go, src/go/rpk/pkg/cli/debug/bundle/bundle_k8s_linux.go, src/go/rpk/pkg/cli/debug/bundle/bundle_linux.go, tests/rptest/tests/rpk_cluster_test.py
This PR:
- 67406299fd76291311c985ed442680ba654b0dd0 Save the debug bundle to a directory with the same name as the generated zip, before compressing. This will allow the user to freely unzip the file without worrying that doing so will clutter their working directory:
```
$ rpk debug bundle 
Creating bundle file...
Debug bundle saved to '1700522672-bundle.zip'
$ unzip -q 1700522672-bundle.zip 
$ ls -l 1700522672-bundle 
total 102M
drwxr-xr-x. 2 rvasquez rvasquez  260 Nov 20 15:26 admin
drwxr-xr-x. 2 rvasquez rvasquez 123K Nov 20 15:26 controller
...
```
- 0bc87e83e5adf593fe3c0e8c455c38106d1e6814 Now we group linux commands and utilities in a folder `/utils` inside the bundle.
```
$ ls -l 1700602020-bundle/utils 
total 3032
-rw-r--r--. 1 rvasquez rvasquez    2120 Nov 21 13:27 dig.txt …
```
=> rpk bundle: rearrange and gather more runtime system information in rpk debug bundle

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
with the latest install pack version `23.2.20231120180358`
https://buildkite.com/redpanda/vtools/builds/10723
```
AssertionError: ['Metric aggregatedEndToEndLatency50pct, value 59.166, Expected to be <= 51, check failed.']
```
and previous install pack versions had similar failure with latency around `53`. so, in this pr, bumping assertion check by almost 50% to `75` so we're well within the range of deviation.
Fixes https://github.com/redpanda-data/cloudv2/issues/10411
* none
=> rptest: bump 50pct latency assertion for test_htt_partitions_omb

src/v/cluster/CMakeLists.txt, src/v/cluster/cloud_metadata/cluster_recovery_backend.cc, src/v/cluster/cloud_metadata/cluster_recovery_backend.h, src/v/cluster/cloud_metadata/error_outcome.h, src/v/cluster/cloud_metadata/producer_id_recovery_manager.cc, src/v/cluster/cloud_metadata/producer_id_recovery_manager.h, src/v/cluster/cloud_metadata/tests/CMakeLists.txt, src/v/cluster/cloud_metadata/tests/cluster_recovery_backend_test.cc, src/v/cluster/cloud_metadata/tests/producer_id_recovery_test.cc, src/v/cluster/cluster_recovery_table.h, src/v/cluster/controller.cc, src/v/cluster/controller.h, src/v/cluster/controller.json, src/v/cluster/id_allocator.cc, src/v/cluster/id_allocator.h, src/v/cluster/id_allocator.json, src/v/cluster/id_allocator_frontend.cc, src/v/cluster/id_allocator_frontend.h, src/v/cluster/id_allocator_stm.cc, src/v/cluster/id_allocator_stm.h, src/v/cluster/service.cc, src/v/cluster/service.h, src/v/cluster/tests/id_allocator_stm_test.cc, src/v/cluster/tests/tx_compaction_utils.h, src/v/cluster/types.h, src/v/redpanda/application.cc, src/v/redpanda/application.h
This PR restores the highest producer ID used by any uploaded segment data in the previous cluster. To accomplish this, there are a few major components:
- At restore time, the highest producer ID is queried across all nodes, loaded from their manifests, sending out an RPC to all nodes to aggregate the highest producer ID of any partition across all shards.
- To make the above step reliable, a sync point is added just after restoring topics from the controller snapshot, using `wait_for_topics()` to wait for partitions to be bootstrapped before proceeding.
- An RPC is then sent to the id_allocator partition to reset the next ID. A new method is used to persist this next ID using the existing STM commands, and the same routing logic is used to direct the requests to the leader.
- Finally, …
=> Restore highest producer ID during cluster recovery

tests/rptest/redpanda_cloud_tests/omb_validation_test.py
Make this test calculate the producer and consumer client count in the same way as test_common, as this is essentially the same test but with frequent segment cleanup.
This bring it into line with the other tests and will use fewer clients in T1.
* none
=> rptest: adjust omb test_retention client count

src/v/transform/probe.cc
Drop the processor lingo as we don't use in docs and it was requested by
product to drop.
* none
=> transform/probe: rename metrics

src/v/config/node_config.h, src/v/redpanda/admin/api-doc/broker.json, src/v/redpanda/admin/server.cc, src/v/redpanda/admin/server.h, src/v/redpanda/application.cc, tests/rptest/services/admin.py, tests/rptest/tests/crash_loop_checks_test.py
Adds a couple more ways to reset crash tracking, main changes in the PR are following.
* Every time the broker starts in recovery mode, the tracking is reset. Booting in recovery mode shows user intent to fix things, so it doesn't make sense to abort with a crash loop limit check, rather we reset the tracking metadata.
* Adds a new admin API that can explicitly reset tracking, probably an escape hatch one can call when they are close to hitting the limits.
* Adds an admin API to reset crash tracking. Additionally the tracking metadata is reset every time the broker boots up in recovery mode.
=> new ways to reset crash loop tracking metadata

src/v/cluster/partition_balancer_state.cc, src/v/cluster/scheduling/partition_allocator.cc, src/v/cluster/topic_table.cc, src/v/cluster/topic_table.h, src/v/cluster/topic_updates_dispatcher.cc, src/v/cluster/types.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15031
=> [v23.2.x] c/topic_table: fix force_update replicas_revisions update

tests/rptest/archival/s3_client.py, tests/rptest/services/redpanda.py
This PR:
Tweaks the s3 client in order to communicate with an s3 API compatible storage backend, using an authorization token. In that case, the signature must be `unsigned`. The authorization headers are added before making the call to the storage backend; using the `before-call.s3.*` event name. For reference, https://boto3.amazonaws.com/v1/documentation/api/latest/guide/events.html#before-call.
This is used only when the `gcp_instance_metadata` is proviced as`cloud_storage_credentials_source` which is the case of running cdt on gcp. In any other case, our s3 client handles the requests as it used to.
In summary, in order to authenticate with a token against gcp buckets, it needs:
* `UNSIGNED` signature
* Authorization header
* google project id header
ref redpanda-data/vtools#1510
* …
=> SiSettings: run cdt on GCP using IAM roles

src/go/rpk/pkg/adminapi/api_cluster.go, src/go/rpk/pkg/cli/cluster/health.go
Only if it's present:
```
$ rpk cluster health
CLUSTER HEALTH OVERVIEW
=======================
Healthy:                          false
Unhealthy reasons:                [under_replicated_partitions]
Controller ID:                    1
All nodes:                        [0 1 2]
Nodes down:                       []
Nodes in recovery mode:           [0]
Leaderless partitions (0):        []
Under-replicated partitions (4):  [kafka/bar/1 kafka/bar/3 kafka/foo/1 kafka/foo/2]
$ rpk cluster health
CLUSTER HEALTH OVERVIEW
=======================
Healthy:                          true
Unhealthy reasons:                []
Controller ID:                    1
All nodes:                        [1]
Nodes down:                       []
Leaderless partitions (0):        []
Under-replicated partitions (0): …
```
=> rpk: add nodes in recovery mode to cluster health

src/go/rpk/pkg/cli/transform/build.go, src/go/rpk/pkg/cli/transform/init.go, src/go/rpk/pkg/cli/transform/project/project.go
Split tinygo into two "language" options, one with the scheduler and one
without. This prevents the need from remembering to always enable the
scheduler and instead one can just pick this at initialization time.
* none
=> rpk/transform: split tinygo

src/v/cloud_storage/materialized_resources.cc, src/v/raft/recovery_memory_quota.cc, src/v/redpanda/application.cc, src/v/redpanda/tests/fixture.h, src/v/resource_mgmt/CMakeLists.txt, src/v/resource_mgmt/memory_groups.cc, src/v/resource_mgmt/memory_groups.h, src/v/resource_mgmt/tests/CMakeLists.txt, src/v/resource_mgmt/tests/memory_groups_test.cc, src/v/storage/chunk_cache.h
Expand out memory group reservation system for data transforms.
Data transforms is the first item here that is fully optional (well isn't TS optional too and we're still carving out 10% for it?) and has a decent impact on memory usage in Redpanda.
In order to support more use cases and subsystems switch a "share" model where the memory is divided up between the different subsystems that ask for memory. With data transforms off, this is a no-op. However when wasm enabled we split the remaining system memory between the rest of the subsystems according to the shares they ask for.
* none
=> resource_mgmt: memory group shares with data transforms

src/v/bytes/details/io_iterator_consumer.h
Multiple paths can lead to this exception, so it can be helpful to log the backtrace for debugging purposes
* none
=> bytes/io_iterator_consumer: add backtrace to std::out_of_range error

src/v/cloud_storage/tests/remote_partition_fuzz_test.cc
Add logging around the steps of test_scan_while_shutting_down. 99% of the log is just data preparation; the last 10 log lines contain the active part of the test.
This increase in logging should help discover what steps are hanging. 
Related to #11271 
* none
=> cloud_storage_fuzzy_rpfixture.test_scan_while_shutting_down

src/v/kafka/latency_probe.h, src/v/kafka/server/handlers/fetch.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13485 
Fixes https://github.com/redpanda-data/redpanda/issues/14826
=> [v23.2.x] kafka: Add fetch plan and execute latency metric

src/go/rpk/pkg/cli/transform/deploy.go
Fixes an error where we assign to a nil map when specifying environment
variables.
* Fixes an issue assigning environment variables to data transforms during deploys
=> rpk/transform/deploy: fix nil map assignment

src/v/io/persistence.cc, src/v/io/persistence.h, src/v/io/tests/persistence_test.cc
io: use config to avoid swappable params warning
* none
=> io: use config to avoid swappable params warning

src/go/rpk/pkg/cli/transform/project/project.go
Previously one could just use `tinygo`, instead of updating anything
someone wrote during the sandbox period, just translate that option to
the no goroutines version.
* none
=> rpk/transform/build: support old tinygo lang opt

src/v/redpanda/application.cc
If we're in recovery mode, don't start the transform or wasm subsystem up.
* none
=> transform: don't start transform in recovery mode

src/v/cluster/bootstrap_backend.cc, src/v/cluster/bootstrap_backend.h, src/v/cluster/cloud_metadata/cluster_recovery_backend.cc, src/v/cluster/cluster_recovery_manager.cc, src/v/cluster/cluster_recovery_state.h, src/v/cluster/cluster_recovery_table.cc, src/v/cluster/cluster_recovery_table.h, src/v/cluster/controller.cc, src/v/cluster/controller.h, src/v/cluster/tests/cluster_recovery_table_test.cc, src/v/cluster/types.h, src/v/config/configuration.cc, src/v/config/configuration.h, tests/rptest/tests/cluster_recovery_test.py
The idea here is that in automated deployments where we don't have a human to run RPK, Redpanda should detect upon starting up a new cluster that a cluster metadata manifest exists in the configured bucket, and should use it to form the basis for cluster recovery automatically by adding the cluster metadata manifest to the cluster recovery table when applying the cluster bootstrap command.
This PR does just that, in the following changes:
- Addition of cluster metadata in the bootstrap cmd. When applied, the state is added to the `cluster_recovery_table`.
- In the cluster creation hook, the leader will look in the configured bucket for any cluster metadata and attempt to use it if any exists, replicating it with the bootstrap cmd.
- Now that cluster recovery can be initialized immediately …
=> Config to attempt cluster recovery when bootstrapping cluster

src/v/archival/tests/archival_metadata_stm_test.cc, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/tests/async_manifest_view_test.cc, src/v/cloud_storage/tests/delete_records_e2e_test.cc, src/v/cloud_storage/tests/partition_manifest_test.cc, src/v/cloud_storage/tests/util.cc, src/v/cluster/topics_frontend.cc, src/v/kafka/server/replicated_partition.cc, src/v/kafka/server/tests/config_utils_test.cc, src/v/raft/consensus_utils.cc, src/v/utils/named_type.h, src/v/utils/tests/named_type_tests.cc
Implemented defaulted comparison operators for base_named_type. 
Adding these fixed #15027 and exposes some disallowed comparisons in the codebase (mostly tests). 
The first commit is about fixing uint8_t <=> named_type(int8_t) comparison in raft/consensus utils. It's done by unwrapping the named_type and allowing comparison by integer promotion to a common wider type.
The second commit handles model::offset <=> kafka::offset, either unwrapping or changing the type when possible.
The third commit is the change itself and a static assert that two distinct named_type cannot be compared. The check fails without this commit
Fixes https://github.com/redpanda-data/redpanda/issues/15027
* none
=> base_named_type: defaulted comparison operators

src/v/kafka/server/handlers/fetch.cc, src/v/kafka/server/partition_proxy.h, src/v/kafka/server/replicated_partition.h, src/v/transform/rpc/tests/transform_rpc_test.cc
Fetch offset is validated against the log end offset. In order to get the full view of partition added log end offset to log entry indicating offset out of range error.
- more information when investigating offset out of range errors
=> Added log end offset to out of range log entry

src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/tests/partition_manifest_test.cc, src/v/cluster/config_manager.cc, src/v/cluster/config_manager.h, src/v/cluster/rm_stm.cc, src/v/cluster/tm_stm.cc, src/v/cluster/tm_stm_cache.cc, src/v/cluster/tx_gateway_frontend.cc, src/v/cluster/types.cc, src/v/cluster/types.h, src/v/raft/consensus.cc, src/v/raft/recovery_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13964
Backport of PR https://github.com/redpanda-data/redpanda/pull/14739
Backport of PR https://github.com/redpanda-data/redpanda/pull/14803
Backport of PR https://github.com/redpanda-data/redpanda/pull/15049
Backport of PR https://github.com/redpanda-data/redpanda/pull/15032
Fixes: https://github.com/redpanda-data/redpanda/issues/13992
Fixes: https://github.com/redpanda-data/redpanda/issues/15080
Fixes: https://github.com/redpanda-data/redpanda/issues/14829
Fixes: https://github.com/redpanda-data/redpanda/issues/14820
=> [v23.2.x] Backport of #13964 #14739 #14803 #15049 #15032

src/v/archival/tests/ntp_archiver_test.cc
If `test_manifest_spillover` fails, its archiver is destroyed without stopping. This also destroys the scrubber, which may have requests active keeping its gate open.
This triggers an assertion from seastar related to gate destroyed while requests active. Usually this is prominently visible but when running multiple tests the SIGABRT results in the ctest invocation hanging in CI. This causes the build to hang and timeout. 
NOTE: The root cause is the `test_manifest_spillover` sometimes not being able to add segments to the archival meta STM, which can be investigated separately. This change should enable that test to fail in a visible manner with logs seen in CI instead of hanging.
FIXES #14254 
* none
=> archival/test: Ensure archiver is stopped

tests/rptest/redpanda_cloud_tests/cloudv2_object_store_blocked.py, tests/rptest/redpanda_cloud_tests/config_profile_verify_test.py, tests/rptest/redpanda_cloud_tests/observe_test.py, tests/rptest/services/redpanda.py, tests/rptest/services/redpanda_cloud.py
In CDT logic, if cluster id was initially empty, cluster will be auto-recreated if health check will fail. 
If original globals.json had cluster id selected, tests would generate error that cluster is no longer usable.
* none
=> rptest: Update cluster creation logic

tests/rptest/tests/delete_records_test.py
Backport 
- https://github.com/redpanda-data/redpanda/pull/14434
- https://github.com/redpanda-data/redpanda/pull/14481
Issue: https://github.com/redpanda-data/redpanda/issues/14492
which depends on: https://github.com/redpanda-data/redpanda/commit/5eb3a9100cc5772e9baa52f770fc501bcd10ae72
* none
=> Backport pr 14434 v23.2.x 808

src/v/cluster/feature_manager.cc, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/features/feature_table.cc, src/v/features/feature_table.h, src/v/kafka/client/client.cc, src/v/kafka/client/configuration.cc, src/v/kafka/client/configuration.h, src/v/kafka/client/producer.cc, src/v/kafka/client/producer.h, src/v/redpanda/application.cc, src/v/security/audit/audit_log_manager.cc, src/v/security/audit/audit_log_manager.h, src/v/security/audit/schemas/schemas.h, src/v/security/audit/schemas/tests/ocsf_schemas_test.cc, src/v/security/audit/tests/audit_log_test.cc, tests/rptest/tests/audit_log_test.py
This PR compiles a few unrelated auditing changes into a single PR.  Listed, they are:
- Integration with `v/feature` so auditing can only truly be enabled when the cluster is fully upgraded: [#868](https://github.com/redpanda-data/core-internal/issues/868)
- Best effort attempt to drain audit log on clean shutdown of node or disable of audit feature flag: [#901](https://github.com/redpanda-data/core-internal/issues/901)
- Bugfix preventing copies of OCSF structures
- Implemented audit queue backpressure by size bytes removing previous method of accounting by raw number of elements enqueued: [#14099](https://github.com/redpanda-data/redpanda/issues/14099)
- Misc. test refactor 
Fixes: #14099 
Fixes: https://github.com/redpanda-data/core-internal/issues/868
Fixes: …
=> security/audit: More audit enhancements 

src/v/model/namespace.h
There seems to be some issues using the `redpanda` namespace that I'm
still chasing, but while I'm tracking that down, switching to
`kafka_internal` seems to fix the errors I'm seeing, so I am going to move
to that in the meantime.
* none
=> model: store wasm binaries in kafka_internal namespace

src/v/io/CMakeLists.txt, src/v/io/page.cc, src/v/io/page.h, src/v/io/page_set.cc, src/v/io/page_set.h, src/v/io/tests/CMakeLists.txt, src/v/io/tests/page_set_test.cc, src/v/io/tests/page_test.cc
Add page and page set.
```
[nwatkins@fedora coverage]$ ../../tools/gcovr src/v/io
------------------------------------------------------------------------------
GCC Code Coverage Report
Directory: ../..
------------------------------------------------------------------------------
File                                       Lines    Exec  Cover   Missing
------------------------------------------------------------------------------
src/v/io/cache.h                             116     116   100%
src/v/io/interval_map.h                       50      50   100%
src/v/io/page.cc                               8       8   100%
src/v/io/page.h                                1       1   100%
src/v/io/page_set.cc                          17      16    94%   43
src/v/io/page_set.h …
```
=> io: add page set index

src/v/transform/api.cc, src/v/transform/io.h, src/v/transform/tests/test_fixture.cc, src/v/transform/tests/transform_processor_test.cc, src/v/transform/transform_processor.cc
This fixes an off by one error with lag. _source->latest_offset() is LSO
which is last_produced_offset + 1, we want to compare this with the last
produced offset.
NOTE: that latest_offset can return 0 if there is an empty log, but we
don't have to worry about that here because if the transform read
something the log isn't empty :)
* Fixes off by one issue with reported transform lag
=> transform/processor: fix off by one lag error

src/v/wasm/allocator.cc, src/v/wasm/allocator.h, src/v/wasm/tests/CMakeLists.txt, src/v/wasm/tests/wasm_allocator_test.cc, src/v/wasm/tests/wasm_transform_bench.cc, src/v/wasm/wasmtime.cc
Zeroing memory can cause reactor stalls if a user has configured dozens of MB of memory for a single transform. Prevent this from happening by chunking zeroing into many tasks.
Followup from https://github.com/redpanda-data/redpanda/pull/15063
* none
=> wasm: asynchronously zero deallocated heaps

src/v/cluster/tx_gateway_frontend.cc
This was missing an arg - causing error logs in a transaction test I'm
writing for Data Transforms.
* none
=> cluster: fix tx_gateway_frontend log statement

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/storage/disk_log_impl.cc, src/v/storage/key_offset_map.cc, src/v/storage/key_offset_map.h, src/v/storage/log_manager.cc, src/v/storage/log_manager.h, src/v/storage/tests/key_offset_map_test.cc, src/v/storage/types.h
Uses a `hash_key_offset_map` in sliding window compaction. When configured to use windowed compaction, each shard will initialize 128MiB dedicated for the map, and pass it to the compaction implementations to be reused. Each  compaction zeroes out the entries before starting.
* none
=> storage: use hash map in compaction

src/v/archival/tests/ntp_archiver_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15169
Fixes: https://github.com/redpanda-data/redpanda/issues/15176,
=> [v23.2.x] archival/test: Ensure archiver is stopped

src/v/cluster/controller_backend.cc, src/v/cluster/controller_snapshot.cc, src/v/cluster/controller_snapshot.h, src/v/cluster/errc.h, src/v/cluster/metadata_cache.cc, src/v/cluster/metadata_cache.h, src/v/cluster/partition_balancer_planner.cc, src/v/cluster/plugin_frontend.cc, src/v/cluster/rm_partition_frontend.cc, src/v/cluster/scheduling/leader_balancer.cc, src/v/cluster/topic_table.cc, src/v/cluster/topics_frontend.cc, src/v/cluster/tx_gateway_frontend.cc, src/v/cluster/types.cc, src/v/cluster/types.h, src/v/kafka/server/errors.h, src/v/kafka/server/handlers/delete_records.cc, src/v/kafka/server/handlers/fetch.cc, src/v/kafka/server/handlers/list_offsets.cc, src/v/kafka/server/handlers/metadata.cc, src/v/kafka/server/handlers/offset_for_leader_epoch.cc, src/v/kafka/server/handlers/produce.cc, src/v/kafka/server/server.cc, src/v/redpanda/admin/server.cc, src/v/transform/api.cc, tests/rptest/tests/recovery_mode_test.py
* Shut down disabled partitions in `controller_backend`
* Skip disabled partitions in balancers
* Forbid partition replica reconfiguration commands for disabled topics/partitions
* Return appropriate error codes for kafka requests related to disabled partitions
* Added the ability do *disable* whole topics and specific topic partitions. Disabled partitions are ignored by Redpanda and producing/consuming to them is impossible. This is useful when only a handful of partitions prevent the cluster from becoming healthy (e.g. if the data in them is corrupted in a way that causes Redpanda to crash).
=> Disabled partitions implementation

src/v/cluster/tx_gateway_frontend.cc, src/v/raft/consensus.cc, src/v/storage/offset_translator_state.cc, src/v/storage/segment_appender.cc
Fixes some log command missing parameters; these would cause an exception at runtime if hit, but the codepaths are likely cold.
They could be a compile-time error with an update to seastar/util/log.hh to use fmt::format_string
* none
=> format exception fixes 

src/go/rpk/pkg/cli/cluster/storage/recovery/recovery.go, src/go/rpk/pkg/cli/cluster/storage/recovery/start.go, src/go/rpk/pkg/cli/cluster/storage/recovery/status.go
We are introducing a new recovery mode and this can lead to confusion.
Fixes https://github.com/redpanda-data/core-internal/issues/842
* rpk: rename `rpk cloud storage recovery` to `rpk cloud storage restore`, but kept recovery as an alias.
=> rpk: rename storage recovery to restore.

src/v/cluster/tx_gateway_frontend.cc, src/v/raft/consensus.cc, src/v/storage/offset_translator_state.cc, src/v/storage/segment_appender.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15193
=> [v23.2.x] format exception fixes 

src/go/rpk/pkg/cli/debug/bundle/bundle.go, src/go/rpk/pkg/cli/debug/bundle/bundle_k8s_linux.go, src/go/rpk/pkg/cli/debug/bundle/bundle_linux.go
- a63bf66185bccdc6670a9e2510589baec3fd56d4 adds a new flag `--label-selector` to `rpk debug bundle` and have a way to filter the bundled resources by label, by default this is the label `app.kubernetes.io/name: redpanda`. Fixes #14362
- 444f2dc62f5c441ece91e7cd687687aa558cf3ed makes rpk fall back to localhost in the case that we are not able to get the admin API addresses by calling the k8s API. Fixes https://github.com/redpanda-data/core-internal/issues/925
- 6ed92b5000637f176f98c5da815903318361f70a adds a new field `size_bytes` to the generated `data_dir.txt` file.
* rpk: Introduce a new flag `--label-selector` to `rpk debug bundle` and have a way to filter the bundled resources by label.
=> rpk debug bundle: k8s bundle improvements

src/v/cloud_storage/tests/cloud_storage_e2e_test.cc, src/v/cloud_storage/tests/manual_fixture.h, src/v/cloud_storage/tests/topic_recovery_service_test.cc, src/v/cluster/cloud_metadata/tests/cluster_recovery_backend_test.cc, src/v/cluster/cloud_metadata/tests/manifest_downloads_test.cc, src/v/cluster/cloud_metadata/tests/manual_mixin.h, src/v/cluster/cloud_metadata/tests/uploader_test.cc, src/v/config/configuration.cc, tests/rptest/scale_tests/cloud_storage_compaction_test.py, tests/rptest/tests/cluster_config_test.py, tests/rptest/tests/offset_for_leader_epoch_read_replica_test.py, tests/rptest/tests/read_replica_e2e_test.py, tests/rptest/tests/timequery_test.py
* In addition to topic data, Redpanda will now upload cluster-related metadata, such as cluster configs, security settings, and consumer offsets. This metadata can be restored along side topic data, allowing for the functional recovery of the entire cluster.
=> config: enable cluster metadata uploads by default

.clang-tidy, src/v/io/cache.h, src/v/io/page_set.h, src/v/io/persistence.cc, src/v/io/persistence.h, src/v/io/tests/common.cc, src/v/io/tests/page_set_test.cc, src/v/io/tests/page_test.cc, src/v/test_utils/test.h, src/v/units.h
Fix some clang tidy warnings.
* none
=> Fix some clang-tidy warnings

src/v/transform/api.cc, src/v/transform/api.h
It's possible to get empty reports often for transforms, which is very
confusing because there is a deploy ongoing or leadership transfers.
Fix that by reporting the transform as being in an unknown state.
* Report pending transforms in an unknown state when generating reports via `rpk transform list`.
=> transform: report unknown transforms as unknown

src/v/redpanda/admin/transform.cc
A small devex papercut that can be improved if you try to use wasm on a
disabled cluster.
* none
=> admin/transform: tell how to enable transforms

src/v/cloud_storage/tests/remote_partition_fuzz_test.cc
logging shows that test_scan_while_shutting_down completes in a few seconds, 
but the shutdow_connections() call starts way after the 10ms sleep interval.
In this log, `test - waiting on close future with timeout` is called in the same fiber as ss::with_timeout, just before starting the timer, and `test - shutting down connections` is called in the same fiber as shutdown_connections(). The call happens more than 1 minute later, even though it should be ~10ms apart. 
```
INFO  2023-11-29 07:23:28,121 [shard 0:main] test - waiting on close future with timeout
INFO  2023-11-29 07:24:30,321 [shard 0:main] test - shutting down connections
INFO  2023-11-29 07:24:30,321 [shard 0:main] test - closing gate
INFO  2023-11-29 07:24:30,329 [shard 0:main] test - done scan loop 0
INFO  2023-11-29 …
```
=> remote_partition_fuzz_test: measure shutdown time directly

src/v/cloud_storage/types.cc, src/v/cloud_storage/types.h, src/v/cluster/partition.cc, src/v/cluster/partition_probe.cc, src/v/cluster/partition_probe.h, tests/rptest/tests/cloud_storage_scrubber_test.py, tests/rptest/tests/services_self_test.py, tests/rptest/tests/topic_recovery_test.py, tests/rptest/utils/si_utils.py
This PR introduces a number of new metrics which report cloud
storage anomalies for a topic. They are all bundled under the same
metric name, but use different labels. This commit only adds them to
public metrics and the granularity is topic level.
Overall, the cardinality should increase by 9 * topic_count *
broker_count. The metrics are reported from each broker, but only the
leader can report non-zero values.
The metric has the following form: `redpanda_cloud_storage_anomalies redpanda_namespace={} redpanda_topic={} redpanda_type={} redpanda_severity={}`.
Fixes #14796
* none
=> cloud_storage: add metrics from cloud storage scrubber

src/v/cloud_storage_clients/s3_client.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15220
Fixes: https://github.com/redpanda-data/redpanda/issues/15239,
=> [v23.1.x] cloud_storage_clients: handle both gcp and s3 request ids

src/v/security/audit/audit_log_manager.cc, src/v/security/audit/audit_log_manager.h, tests/rptest/tests/audit_log_test.py
Fixes: #15226
Audit logging is not able to function in recovery mode as produce messages are rejected.  In this situation, it's possible the cluster may become unusable if audit messages are generated and the queues are unable to drain.
Also fixed a logic error in the ducktape tests.
* none
=> audit: Disable auditing in recovery mode

src/v/transform/tests/transform_processor_test.cc, src/v/transform/transform_processor.cc, tests/go/transform-verifier/consume/consumer.go, tests/go/transform-verifier/produce/producer.go, tests/rptest/services/transform_verifier_service.py, tests/rptest/tests/data_transforms_test.py
Add automated tests that transforms only process read committed records.
* none
=> ducktape: add transaction tests for transforms

tests/rptest/services/cloud_broker.py
Add methods to query broker inside pod directly, w/o Proxy Console URL
* none
=> rptest: Update CloudBroker with query methods

tests/rptest/tests/random_node_operations_test.py
When not all nodes in the cluster are up to date the fast partition movement topic properties are not present. Added check that will prevent fast movement workload topic from being created when not all nodes are up to date.
Fixes: #15147
- none
=> Do not use fast partition movement whith upgrades in `RandomNodesOperationsTest`

src/go/rpk/pkg/serde/serde.go
When guessing the proto message name (i.e, just
1 message in a schema), we need to use the
fullName, the difference between this and Name is
that the fullName includes the package name as
well.
Person = Name
foo.bar.Person = FullName
* none
=> rpk/serde: use fullName for proto decoding.

.clang-tidy-strict, .clang-tidy-strict-tests, .github/workflows/build-redpanda.yml, CMakeLists.txt, CMakePresets.json, install-dependencies.sh, src/v/CMakeLists.txt, src/v/io/.clang-tidy, src/v/io/CMakeLists.txt, src/v/io/clang-tidy-helper.cc, src/v/io/tests/.clang-tidy
Adds macros for selectively enabling a strict set of clang-tidy checks. Then enables this for the io subsystem which passes all the checks. Exact set of checks expected to be a topic of much debate as folks work towards getting sub-directories to pass checks.
* none
=> build: enable strict clang-tidy for sub-directory

tests/rptest/tests/random_node_operations_test.py
Fixed verifying if fast partition movement is supported. Previously the check was incorrectly asserting previous version string.
- none
=> tests: fixed version check in random node operations test

src/v/bytes/details/io_iterator_consumer.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15122
=> [v23.2.x] bytes/io_iterator_consumer: add backtrace to std::out_of_range error

tests/rptest/tests/random_node_operations_test.py, tests/rptest/utils/node_operations.py
Made progress timeout longer in the tests that enables failure injection. With random failure injection it may be the case that the node which is currently controller leader will be restarted/suspended multiple times before being able to finish balancing operation. In this pessimistic case it may happen that the tick will not be scheduled frequent enough for the decommission to make progress.
Fixes: #8657
- none
=> tests: made progress timeout dependent on failure injection

src/v/raft/state_machine.cc
Sleeping in case of apply error helps avoiding busy-looping that leads to 100% reactor util and hard-to-investigate incidents.
* Avoid 100% reactor utilization in case of state machine errors.
=> [v23.1.x] raft/state_machine: sleep after apply error

src/v/cluster/producer_state.h, src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h, src/v/kafka/server/handlers/describe_producers.cc, src/v/model/fundamental.h, src/v/model/model.cc, src/v/model/record.h, tests/rptest/tests/describe_producers_test.py
Change the way how describe producers request handler list active
producers. Before it was deriving producer state from the ongoing
transaction list. This is incorrect as it didn't include the idempotent
producers and the one with finished transactions.
Now the handler uses producer state directly.
Fixes: #15247
- fixed `DescribeProducers` API output
=> Fixed describe producers to include all data

src/v/storage/disk_log_impl.cc, src/v/storage/disk_log_impl.h, src/v/storage/scoped_file_tracker.h, src/v/storage/segment_deduplication_utils.cc, src/v/storage/segment_utils.cc, src/v/storage/tests/CMakeLists.txt, src/v/storage/tests/scoped_file_tracker_test.cc, src/v/storage/tests/storage_e2e_test.cc, src/v/storage/types.h
This PR attempts to unify the cleaning up of intermediary files (mostly "staging" files) left behind by aborted compactions. We were already going this to a degree by manually cleaning up files in a couple of specific places. This is an attempt to iron out all remaining cases.
A new scoped class is added to be able to track files left behind by early exits. This is used at the key places in which staging files (and in one case, regular compacted index) are created. The scoped class spans the point in time before the intermediary files are created and is cleared when these files are removed, typically by renaming them to the base segment names.
Each instance of housekeeping will now track a set of files to be erased once the compaction completes.
Along the way there were a couple tweaks:
- …
=> storage: track intermediary files and clear them if compaction fails

src/v/cluster/partition_probe.cc, src/v/net/probes.cc
Exposes the total sent and received bytes server metrics on public
metrics.
Right now there is only the partition probes which can be used to
approximate the bytes sent and received. However, they actually
represent the amount of bytes read for a fetch request and hence can be
massively off if only a part of it is returned to the client because of
`fetch.max.bytes` reasons.
We already track the total aggregated number of bytes returned to
clients. On internal metrics they are exposed as
`vectorized_[kafka|interna]_rpc_[sent|received]_bytes`.
Expose them on public metrics as well. They will follow the existing
server probe metrics pattern for public metrics:
```
$ curl -s localhost:9644/public_metrics | grep -E "sent_bytes|received_bytes"
// HELP redpanda_rpc_received_bytes internal: …
```
=> net: Expose total sent/recv bytes on public_metrics

src/v/redpanda/admin_server.cc, src/v/security/scram_algorithm.cc, src/v/security/scram_algorithm.h, tests/rptest/tests/scram_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15253 
Fixes #15279
=> [v23.2.x] Validation and url_decode for SCRAM usernames

tests/rptest/redpanda_cloud_tests/omb_validation_test.py
Use a 1.5 multiplier for latencies in max partitions test.
We now allow latencies to be 50% higher in the max partitions test as we
expect poorer performance when we max out one dimension, in this case
partitions.
With this change and @StephanDollberg's change to linearize small packets when using TLS the test passes consistently in T1 Arm.
* none
=> Use a 1.5 multiplier for latencies in max partitions test

src/v/cluster/node/local_monitor.cc, src/v/cluster/node/local_monitor.h, src/v/cluster/tests/local_monitor_test.cc, src/v/redpanda/application.cc
=> Remove local_monitor::_min_free_bytes

tests/rptest/services/redpanda.py, tests/rptest/tests/data_transforms_test.py
Split out the base test so that it can be reused for other scenarios. 
Add a scenario where multiple topics are chained together.
Add a scenario where leadership changes while producing.
* none
=> ducktape/transform: add more transform tests

src/v/cluster/partition_balancer_planner.cc, src/v/cluster/tests/partition_balancer_simulator_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15270
=> [v23.2.x] c/partition_balancer: prioritize full-disk constraint over rack repair

tests/rptest/test_suite_cloud.yml
Following on from PR #13655, this PR includes the 4 tests in `omb_validation_test.py` to run on the scheduled jobs against cloud.
* none
=> rptest: include omb_validation_test.py tests in cloud test suite

src/v/cluster/cluster_discovery.cc
When Join request fails the node is unable to become a cluster member. Added logging Join request failure. This will enable debugging the underlying problem.
- none
=> c/cluster_discovery: log an error when join request failed

src/v/kafka/client/producer.cc, src/v/kafka/client/producer.h
CI issue was caused due to gate close exception not being properly handled in producer::send.  When gate was closed, the proper response future was never generated.  Now gate will be held by a ss::with_gate and the exception properly caught and handled.
Fixes: #15314
* none
=> k/client: Move gate in producer::send

tests/rptest/clients/kubectl.py, tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/services/redpanda.py
Fixes https://github.com/redpanda-data/cloudv2/issues/10373
Updated the `test_decommission_and_add` test to decommissions a node and then adds a node back to the cluster using `kubectl` commands.
Restrictions (test will exit with warning if not satisified):
* only works with operator-v1 because the kubectl cmds will be different with operator-v2
* requires more than 3 nodes in the config profile of the tier being tested because the first operation will be a decomm and can't have less than 3 nodes in the k8s cluster
example of test run:
```console
ducktape \
--debug \ …
```
=> rptest: update `test_decommission_and_add` to decomm and add on cloudv2

src/go/rpk/pkg/cli/cluster/cluster.go, src/go/rpk/pkg/cli/cluster/txn/describe.go, src/go/rpk/pkg/cli/cluster/txn/describe_producers.go, src/go/rpk/pkg/cli/cluster/txn/list.go, src/go/rpk/pkg/cli/cluster/txn/txn.go, src/go/rpk/pkg/out/out.go, tests/rptest/clients/rpk.py, tests/rptest/tests/rpk_transaction_test.py
For #7308 
Adds:
```
rpk cluster txn 
rpk cluster txn list
rpk cluster txn describe
rpk cluster txn describe-producers
```
* rpk now has a `cluster txn` command space
=> rpk: add `cluster txn` commands

src/v/resource_mgmt/storage.cc, src/v/resource_mgmt/storage.h
Helps to avoid bias towards partitions that appear reliably sooner in the reclaim list. The sorting applies per shard, rather than a node-wide global ordering.
Fixes: #14865
* Improves space management by helping to reduce bias towards certain partitions when reclaiming space.
=> storage: sort reclaimable partitions by size

.github/workflows/lint.yml, src/go/rpk/pkg/cli/container/common/common.go
We use `latest` in dev, but v22.3 was using an old
version that was causing errors in CI
**Why?**
Our GH actions:
- Download Go's `stable` version.
- Download the pinned version of golangci-lint. (Previously 1.52)
From the GH Actions [Doc](https://github.com/actions/setup-go#using-stableoldstable-aliases), Go's `stable` version comes from the go-version [repository manifest](https://github.com/actions/go-versions/blob/main/versions-manifest.json) and this was updated yesterday to 1.21.5, and `golangci-lint@1.52` is incompatible with this new version.
* none
=> [v23.2.x] rpk: manually update golangci-lint version

src/v/kafka/server/handlers/fetch.cc, src/v/kafka/server/partition_proxy.h, src/v/kafka/server/replicated_partition.cc, src/v/kafka/server/replicated_partition.h, src/v/raft/consensus.cc, src/v/transform/rpc/tests/transform_rpc_test.cc, tests/rptest/services/kafka_cli_consumer.py, tests/rptest/tests/follower_fetching_test.py
Previously _last_leader_visible_offset was updated only from info in append_entries requests. This meant that on a leader that was stepping down there was a small window between stepping down and receiving the first append_entries from the new leader, where _last_leader_visible_offset value was bogus. This led offset_out_of_range errors when serving valid fetch requests as a follower. Fix this by updating _last_leader_visible_offset value while we are the leader as well.
* Fix a bug that resulted in `offset_out_of_range` errors for valid fetch offsets when fetching from followers that had recently lost leadership.
=> r/consensus: update _last_leader_visible_offset on leader as well

src/v/kafka/server/handlers/fetch.cc, src/v/kafka/server/partition_proxy.h, src/v/kafka/server/replicated_partition.cc, src/v/kafka/server/replicated_partition.h, src/v/raft/consensus.cc, tests/rptest/services/kafka_cli_consumer.py, tests/rptest/tests/follower_fetching_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/14620
Backport of PR https://github.com/redpanda-data/redpanda/pull/15357
Fixes https://github.com/redpanda-data/redpanda/issues/15173
Fixes https://github.com/redpanda-data/redpanda/issues/15367
=> [v23.2.x] r/consensus: update _last_leader_visible_offset on leader as well

src/v/cluster/cluster_utils.cc, src/v/cluster/scheduling/partition_allocator.cc, src/v/cluster/tests/partition_balancer_simulator_test.cc, src/v/cluster/tests/serialization_rt_test.cc, src/v/compat/json.h, src/v/model/metadata.h, src/v/model/model.cc, src/v/model/tests/randoms.h, src/v/raft/tests/type_serialization_tests.cc, tests/rptest/scale_tests/many_partitions_test.py, tests/rptest/services/kgo_repeater_service.py, tests/rptest/services/kgo_verifier_services.py
There's a desire to see how close to the memory limits we can push the shard count and memory per partition. But the current checks in `check_cluster_limits()` only use GiB-granular calculations for the cluster memory which results in overly-pessimistic partition counts if nodes have fractional memory sizes, e.g. 15.9GiB. Add a new `available_memory_bytes` field to `broker_properties` to make these calculations more accurate. Also, update `ManyPartitionsTest` to constrain the available node memory based on the number of partitions and memory per partition. MPT now gives us a solid baseline for further tweaks.
Fixes #13573 
* Allow users to create more partitions and allocate fractional GiB memory sizes (e.g. 15.9GiB)
=> Add byte-granular memory size to broker properties

tests/rptest/tests/random_node_operations_test.py
Increased number of admin operation retires in RandomNodeOperations test. Since the test is executed in highly unstable environment connection resets and unavailable nodes are the first class citizens. Made admin operations fuzzer more permissive by increasing number of retries to reduce false positive test failures.
Fixes: #15339
- none
=> tests: increased number of admin operation retries

tools/redpanda-gdb.py
`ss::memory::allocation_site::backtrace` has changed type and no longer has a `_main` field, so the manual heap profiling tool was broken.
* none
=> tools/redpanda-gdb: Fix backtrace struct

tests/docker/ducktape-deps/kgo-verifier
- Will include latest changes to make the kgo-repeater multi topic aware
* none
=> tests/docker: Bump kgo-verifier version

src/v/redpanda/application.cc
Reverts redpanda-data/redpanda#14926
This breaks metrics integrations that don't support the types of metrics changing.
* none
=> Revert "[v23.2.x] redpanda: Make `redpanda_cpu_busy_seconds_total` a counter"

src/v/redpanda/application.cc
Reverts redpanda-data/redpanda#14927
This breaks metrics integrations that don't support the types of metrics changing.
* none
=> Revert "[v22.3.x] redpanda: Make `redpanda_cpu_busy_seconds_total` a counter"

src/v/redpanda/application.cc
Reverts redpanda-data/redpanda#14928
This breaks metrics integrations that don't support the types of metrics changing.
* none
=> Revert "[v23.1.x] redpanda: Make `redpanda_cpu_busy_seconds_total` a counter"

tests/rptest/e2e_tests/workloads/flink_consume_workload.py, tests/rptest/e2e_tests/workloads/flink_produce_workload.py, tests/rptest/e2e_tests/workloads/flink_simple_workload.py, tests/rptest/e2e_tests/workloads/flink_workload_config.json, tests/rptest/services/flink.py, tests/rptest/tests/flink_basic_test.py
This PR creates Flink service, basic workloads and a simple produce test
- Flink Service uses similar structure to other services, for example kgo_verifier
- Standalone mode is used when starting a cluster. I.e. no HA or connections to/from Flink services on other nodes
- Support for flink/java embedded Python environments is not yet implemented. I.e. workloads that generates python subtasks are not currently supported
* none
=> rptest: Basic flink service, workload and test

src/v/redpanda/CMakeLists.txt, src/v/redpanda/admin/server.cc, src/v/redpanda/admin/server.h, src/v/redpanda/admin/transaction.cc, src/v/redpanda/admin/usage.cc
Splits out admin endpoints for:
* Usage
* Transactions
* none
=> admin: split out handlers for usage, transactions

src/v/storage/disk_log_impl.cc, src/v/storage/disk_log_impl.h, src/v/storage/index_state.cc, src/v/storage/index_state.h, src/v/storage/segment_deduplication_utils.cc, src/v/storage/segment_index.h, src/v/storage/tests/compaction_e2e_test.cc
Segments may contain records that won't be compacted:
- when all batches are non-data batches, or
- when the only data record is the last record
In either of the above cases, a windowed compaction will repeatedly
result in the same resulting segment, since we only remove non-data
batches and we do not remove the last record.
This commit introduces a new field to the index_state to keep track of
the first data batch in the segment. This is used to determine whether
either of the conditions are true before compacting them. If so, the
segment is skipped for compaction.
Along the way in debugging this issue, I noticed a couple things:
- The compaction ratios weren't being reported by the windowed compaction implementation. This PR includes a fix for this.
- Some logging can be particularly …
=> storage: don't recompact segments with no compactible data

tests/rptest/scale_tests/many_partitions_test.py
Allows parameterizing the MPT tests such that we can easily test it at
other `topic_partition_per_shard` and `topic_memory_per_partition`
values.
We keep the defaults as is. Later we can maybe always test different
dimensions.
* none
=> tests: Parameterize the ManyPartitionTests

src/v/redpanda/application.cc
Reverts redpanda-data/redpanda#14905
This breaks metrics integrations that don't support the types of metrics changing.
* none
=> Revert "redpanda: Make `redpanda_cpu_busy_seconds_total` a counter"

tests/rptest/tests/nodes_decommissioning_test.py
Shutdown node after it is decommissioned. This will prevent tiered storage scrubber from querying node which metadata may be stale
Fixes: #15038
- none
=> tests: shutdown node after decommissioning

src/v/cluster/partition.cc
If local log is empty `committed_offset` is smaller than the start offset. In this case log end offset should not be translated to kafka offset domain as it is outside of the translation range and it is not valid.
- none
=> c/partition: do not try to translate log end offset if log is empty

src/v/cluster/controller.cc, src/v/config/configuration.cc, src/v/config/configuration.h, tests/rptest/tests/cluster_recovery_test.py
To avoid confusion with the new "recovery mode", cluster recovery-related commands/configs are being renamed to "restore". This commit changes the `cloud_storage_attempt_cluster_recovery_on_bootstrap` property accordingly.
* none
=> config: rename recovery bootstrap property to restore

src/v/model/record.h, src/v/storage/compaction_reducers.cc, src/v/storage/compaction_reducers.h, src/v/storage/disk_log_impl.cc, src/v/storage/index_state.cc, src/v/storage/index_state.h, src/v/storage/offset_to_filepos.cc, src/v/storage/offset_to_filepos.h, src/v/storage/segment.cc, src/v/storage/segment.h, src/v/storage/segment_index.cc, src/v/storage/segment_index.h, src/v/storage/segment_utils.h, src/v/storage/tests/offset_index_utils_tests.cc, src/v/storage/tests/segment_deduplication_test.cc, src/v/storage/types.h
This PR adds a few improvements to the recently added short-circuit in windowed compaction. Previously we would skip over compacting segments in the sliding range when we could tell that there was one or zero data batches. The tweaks here are:
- Tweaking the short-circuit condition to consider "compactible" records (those that are removed during compaction) rather than `raft_data` records only.
- Updating the start of the sliding range to be the first segment that has compactible records, so we don't needlessly iterate through such segments, add them to the key-offset map, etc.
- Resetting the "first compactible offset" field when it is suffix truncated.
- Various non-functional cleanup in adjacent code
* none
=> storage: further improvements to windowed compaction short circuit

src/v/cluster/archival_metadata_stm.cc, src/v/cluster/archival_metadata_stm.h
Last replicate future is an internal barrier for sync operations. Ignore its value if we're shutting down to prevent seastar logging warnings for unhandled exception.
Couldn't come up with a CI test for this. Happened in ManyPartitionsTest with TS.
See https://github.com/redpanda-data/redpanda/pull/13896 if you are looking for context on what is `_last_replicate`.
* none
=> cluster: ignore _last_replicate value in destructor

src/go/rpk/pkg/cli/debug/bundle/bundle_k8s_linux.go, src/go/rpk/pkg/cli/debug/bundle/bundle_linux.go, src/go/rpk/pkg/cli/redpanda/mode.go, src/go/rpk/pkg/cli/registry/compatibility_level.go, src/go/rpk/pkg/tuners/factory/factory.go
- 02482a82dc74f62e97f3c6d9e6bfcb705c04f764 Fixes #14357 
- Added extended help text for `rpk redpanda mode` and `rpk registry compatibility-level`
* rpk debug bundle: now collects the output of /proc/kallsyms
=> rpk: add /proc/kallsyms to debug bundle and extend help texts

src/go/rpk/pkg/cli/transform/build.go, src/go/rpk/pkg/cli/transform/init.go, src/go/rpk/pkg/cli/transform/project/project.go, src/go/rpk/pkg/cli/transform/template/rust/README.md, src/go/rpk/pkg/cli/transform/template/rust/main.rustsrc, src/go/rpk/pkg/cli/transform/template/rust_template.go
Now that we have a Rust SDK, add support for using it in rpk 🦀
* Support authoring WebAssembly Data Transforms in Rust
=> rpk/transform: Rust SDK support

src/v/cluster/partition_balancer_backend.cc, src/v/cluster/partition_balancer_planner.cc, src/v/cluster/partition_balancer_types.h
If a controller snapshot is installed in the middle of the planning session, nodes can suddenly disappear from the partition_allocator state. We handle this case by aborting the planning session.
Fixes https://github.com/redpanda-data/redpanda/issues/13698
* none
=> c/partition_balancer: handle members_table update during planning

tests/rptest/services/kafka_cli_consumer.py, tests/rptest/tests/follower_fetching_test.py
KgoVerifierProducer under-reports the number of produced messages after it stops (because it could have made some progress after the last status report got queried). Rely on the reported high watermark instead to get the number of produced messages.
* none
=> tests: fix FollowerFetchingTest.test_with_leadership_transfers

tests/rptest/services/kafka_cli_consumer.py, tests/rptest/tests/follower_fetching_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15406 
Backport of PR https://github.com/redpanda-data/redpanda/pull/15091
=> [v23.2.x] tests: fix FollowerFetchingTest.test_with_leadership_transfers

.github/workflows/transform-sdk-build.yml, .github/workflows/transform-sdk-release.yml
Add a workflow to automatically publish the transform SDKs when a release is tagged.
* none
=> gha: add release workflow for transform-sdks

src/v/kafka/client/broker.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15414
Fixes: https://github.com/redpanda-data/redpanda/issues/15431,
=> [v22.3.x] kafka/client: Stop the broker if `do_authenticate` failed

src/v/kafka/client/broker.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15414
Fixes: https://github.com/redpanda-data/redpanda/issues/15433,
=> [v23.1.x] kafka/client: Stop the broker if `do_authenticate` failed

src/v/kafka/client/broker.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15414
Fixes: https://github.com/redpanda-data/redpanda/issues/15435,
=> [v23.2.x] kafka/client: Stop the broker if `do_authenticate` failed

src/v/security/audit/audit_log_manager.cc
Fix bug with incorrect calculation in audit probe buffer usage ratio. Bug was likely introduced when the PR to bound audit queue by size bytes instead of number of elements was introduced
* none
=> s/audit: Fix bug with incorrect calculation in audit probe buffer usage ratio

src/v/cluster/controller.cc, src/v/cluster/controller.h, src/v/cluster/controller.json, src/v/cluster/security_frontend.cc, src/v/cluster/security_frontend.h, src/v/cluster/service.cc, src/v/cluster/service.h, src/v/cluster/types.h, src/v/kafka/server/handlers/describe_acls.cc, src/v/redpanda/application.cc, tests/rptest/clients/rpk.py, tests/rptest/tests/rpk_acl_test.py
Backport of #12716
- Modifications to avoid stale responses returned from DescribeACLs requests
=> Backport of #12716 avoid returning stale describeACL responses

src/v/kafka/client/client.cc, src/v/kafka/client/client_fetch_batch_reader.cc, src/v/kafka/client/configuration.cc, src/v/kafka/client/configuration.h, src/v/kafka/client/consumer.cc, src/v/kafka/client/fetcher.cc, src/v/kafka/client/fetcher.h
The goal is to mitigate a potential "No records returned" in Schema Registry.
The defaults are as before, except for the non-consumer fetch which now has min_bytes set to 1 instead of 0.
`min_bytes` and `max_bytes` are a bounded_property with min 0.
* kafka/client: Configuration for consume min and max bytes
=> kafka/client: Configuration for consume min and max bytes

src/v/cloud_storage/tests/remote_partition_fuzz_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15142
Backport of PR https://github.com/redpanda-data/redpanda/pull/15200
Fixes https://github.com/redpanda-data/redpanda/issues/15234
=> [v23.2.x] remote_partition_fuzz_test: measure shutdown time directly

src/v/raft/consensus.cc, src/v/raft/consensus.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15294
Fixes: https://github.com/redpanda-data/redpanda/issues/15331,
=> [v23.2.x] Made leader_id and term changes atomic

src/go/rpk/pkg/cli/topic/produce.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/15371
Fixes: https://github.com/redpanda-data/redpanda/issues/15379,
=> [v23.2.x] rpk produce: Adjust timeout and maxBytes options

tests/docker/ducktape-deps/kafka-tools
This helps understand better where the process is stuck during normal operations. Lately I'm fetching from S3 with few KB/s.
Let's see if we get more complaints after making this visible.
* none
=> t/docker: log curl progress when fetching kafka-tools

src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment.h, src/v/cloud_storage/tests/remote_partition_test.cc, src/v/cloud_storage/tests/s3_imposter.cc, src/v/cloud_storage/tests/s3_imposter.h, src/v/cloud_storage/tests/util.cc, src/v/cloud_storage/tests/util.h
The reader can get stuck while reading from tiered-storage if the segment is replaced concurrently.
The mechanism of the failure:
- the reader creates the `remote_segment` that refers to segment A in the cloud
- concurrently, the segment A gets replaced with segment B
- another reader is trying to read the offset range covered by both A and B and finds that A is already materialized
- the reader checks that the committed offset is the same and tries to reuse A which triggers failure
We had the protection from this in the `remote_partition` but the code assumed that reupload will always merge segments. This is not always the case because compaction can reupload segment without merging it with its neighbor. The PR fixes this by adding size check. The reupload may have the same offset range …
=> cloud_storage: Fix stuck reader problem

tests/rptest/tests/audit_log_test.py
=> Fix for CI Failure (TimeoutError) in AuditLogTestKafkaApi.test_management

src/v/raft/state_machine.cc
Seastar `broken_semaphore` and `broken_condition_variable` exceptions are thrown from when Redpanda is shutting down. Those exceptions doesn't have to be logged with error severity.
- none
=> r/state_machine: ignore broken semaphore and condition var exceptions

tests/rptest/scale_tests/many_partitions_test.py
Was lacking two parameters in the ScalaParameters after adding
parameterization to the other MPT tests.
Fixes https://github.com/redpanda-data/redpanda/issues/15444
* none
=> tests: Fix broken OMB MPT

tests/rptest/tests/e2e_shadow_indexing_test.py
the test has no time to actually run:
it waits for "segments" in manifest
but this is the first manifest retrieved
'cloud_log_size_bytes': 0,
'insync_offset': 0,
'last_offset': 0,
'namespace': 'kafka',
'partition': 0,
'replaced': {},
'revision': 9,
'segments': {},
'topic': 'panda-topic',
'version': 3} 
and has an empty segment list.
check that segments contains at least an entry
Fixes #15151 
* none
=> tests/e2e_shadow_indexing_test: wait until segments has one entry

src/v/archival/adjacent_segment_merger.cc, src/v/archival/tests/segment_reupload_test.cc, src/v/archival/types.cc, src/v/archival/types.h
Avoid merging adjacent segments if they have different terms. 
Currently, the adjacent segment merger can pick up segments that have different term id and merge them into one. The term id of the first segment will be used for the resulting merged segment. Going forward, we need to disable this because it may cause some kafka clients to erroneously detect the data loss.
* none
=> archival: Disable cross term merging of adjacent segments

src/v/storage/disk_log_impl.cc, src/v/storage/tests/disk_log_builder_test.cc
if _segs is empty (not in the precondition) size() -1 would underflow and we would access garbage
if _segs has size 1, we would underflow afther the loop check (i-->0) and access garbage
if _segs is bigger than 1, we would exclude from the count the active segment
Fixes #15417 
* none
=> storage/disk_log_impl: defensive reverse iteration of _segs

src/v/security/config_rcl.cc
`as_string` got removed in recent re2 versions, because StringPiece became an
alias for std::string_view.
* none
=> Replace deprecated re2::StringPiece::as_string method

src/v/kafka/client/broker.h, src/v/kafka/client/logger.h, src/v/kafka/protocol/logger.cc, src/v/kafka/protocol/metadata.h, src/v/kafka/protocol/schemata/generator.py, src/v/kafka/server/logger.h, src/v/kafka/server/request_context.h, src/v/kafka/server/requests.cc, src/v/utils/truncating_logger.h
Introduces a specialized logger for situations where `fmt` output might be extremely large and wires it into Kafka API request and response logging.
Also adds code gen for custom `fmt::formatter` specializations for `metadata_response_data` and associated types.
Usually formatters for generated kafka API types are defined as `operator<<` overloads. When fmtlib encounters a format arg of "custom" type `T`, it first looks for a matching `fmt::formatter<T>` specialization. Failing that, it constructs a `fallback_formatter<T>`, which, in our case (assuming `operator<<(os, const T&)` exists), constructs an ostream backed by an expandable buffer and streams the arg value into it.
The purpose of this PR is to limit the memory footprint of logging large (i.e. >1MiB formatted) …
=> Add truncating_logger and formatter specializations for `metadata_*` API types

src/v/cluster/errc.h, src/v/cluster/plugin_frontend.cc, src/v/cluster/plugin_frontend.h, src/v/cluster/tests/plugin_frontend_validation_test.cc, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/kafka/server/errors.h, src/v/redpanda/admin/server.cc, src/v/redpanda/application.cc, src/v/resource_mgmt/memory_groups.cc
There is a cap on the number of functions that can be deployed due to memory resources, make that cap explicit with directions if a user hits the limit.
Additionally, we rename the memory config settings so they are consistent with other `data_transforms` settings (a product ask).
* Produce a better error message when deploying the maximum number of data transforms configured.
=> wasm: enforce memory limits on number of deployed functions

src/v/kafka/client/broker.h, src/v/kafka/client/logger.h, src/v/kafka/protocol/logger.cc, src/v/kafka/protocol/metadata.h, src/v/kafka/protocol/schemata/generator.py, src/v/kafka/server/logger.h, src/v/kafka/server/request_context.h, src/v/kafka/server/requests.cc, src/v/utils/truncating_logger.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15327
=> [v23.2.x] Add truncating_logger and formatter specializations for `metadata_*` API types

src/v/kafka/server/tests/produce_consume_utils.h, src/v/storage/compaction_reducers.cc, src/v/storage/disk_log_impl.cc, src/v/storage/index_state.cc, src/v/storage/index_state.h, src/v/storage/segment.cc, src/v/storage/segment.h, src/v/storage/segment_index.cc, src/v/storage/segment_index.h, src/v/storage/tests/compaction_e2e_test.cc, src/v/storage/tests/offset_index_utils_tests.cc, src/v/storage/tests/segment_deduplication_test.cc
The [previous short-circuit check](https://github.com/redpanda-data/redpanda/pull/15404) for compaction aimed to compare the
first compactible offset against the max offset, which would supposedly
tell us whether the only data record were the last record, indicating a
sole data record that wouldn't be compacted.
This check didn't take into account batches of size > 1, whose first
data batch base offset would never equal the max offset (a batch end
offset).
This commit fixes this by changing this field to count the number of
compactible records appended. This value is sometimes an overestimate,
e.g. in cases where the segment is truncated and we don't count the
number of compactible records removed to subtract. But, that should be
sufficient since our check for having compactible records …
=> storage: fix compaction short circuit check, redux

src/v/raft/persisted_stm.cc, src/v/raft/persisted_stm.h
As the log directory name contains the partition revision, any file-based snapshots that we'll find there for a newly created log are not coming from the previous incarnation of this ntp (and were likely put there deliberately). Therefore we skip initial cleanup phase for file-based snapshots.
* none
=> r/persisted_stm: do initial cleanup only for kvstore-backed snapshots

src/v/archival/segment_reupload.cc, src/v/archival/tests/segment_reupload_test.cc
Backport of https://github.com/redpanda-data/redpanda/pull/14911
CONFLICT:
- removes the piece of the max() equation that was added for delete-records, since that was added after 23.1.
This updates the segment_collector collection to only move its collection start offset forward. Previously we were susceptible to the following issue:
- Say our manifest has [0, 10)[10,20)[20,25)[25,30), and we do one compacted upload [0, 25).
- Before we move onto persisting that fact into our manifest, we schedule our next upload, starting at 25.
- Schedule and compacted reupload starting from range 25.
- Locally, merge compact data such that we end up with local segment [20, 30).
- Locally, we only have a segment with [20, 30) that also happens to align with a remote segment in our manifest.
- We try to …
=> [v22.3.x] archival: always move reupload start forward

src/v/archival/segment_reupload.cc, src/v/archival/tests/segment_reupload_test.cc
Backport of https://github.com/redpanda-data/redpanda/pull/14911
CONFLICT:
- removed setting the windowed compaction bit in tests, since windowed compaction is not in this branch
This updates the segment_collector collection to only move its collection start offset forward. Previously we were susceptible to the following issue:
- Say our manifest has [0, 10)[10,20)[20,25)[25,30), and we do one compacted upload [0, 25).
- Before we move onto persisting that fact into our manifest, we schedule our next upload, starting at 25.
- Schedule and compacted reupload starting from range 25.
- Locally, merge compact data such that we end up with local segment [20, 30).
- Locally, we only have a segment with [20, 30) that also happens to align with a remote segment in our manifest.
- We try to align …
=> [v23.2.x] archival: always move reupload start forward

src/v/cluster/tests/cluster_test_fixture.h, src/v/storage/compaction_reducers.cc, src/v/storage/tests/CMakeLists.txt, src/v/storage/tests/compaction_e2e_multinode_test.cc, src/v/storage/tests/compaction_e2e_test.cc, src/v/storage/tests/manual_mixin.h
We were previously comparing a given offset with the segment's last
offset, which in theory is the last record's offset, but across
compactions across multiple nodes, may end up not corresponding to a
real record. Take for example the following sequence:
node 1:
- Appends in order, end up with a segment [1707, 2000]. This segment contains
batch [1785, 1799] with 15 records.
- Compaction runs, batch [1785, 1799] maintains its batch boundaries,
but now has 6 records, e.g. the last one being 1790.
- The batches are replicated to node 2.
node 2:
- We have a different segment layout, but the batch ends up in segment
[1230, 1799], still with only 6 records, the last one being 1790.
- We compact, and try to keep offset 1799, since this supposed to be the
last offset.
- The last offset in the …
=> storage: fix comparison against last record in segment

src/v/archival/segment_reupload.cc, src/v/archival/tests/segment_reupload_test.cc
Backport of https://github.com/redpanda-data/redpanda/pull/14911
CONFLICT:
- removes the piece of the max() equation that was added for delete-records, since that was added after 23.1.
This updates the segment_collector collection to only move its collection start offset forward. Previously we were susceptible to the following issue:
- Say our manifest has [0, 10)[10,20)[20,25)[25,30), and we do one compacted upload [0, 25).
- Before we move onto persisting that fact into our manifest, we schedule our next upload, starting at 25.
- Schedule and compacted reupload starting from range 25.
- Locally, merge compact data such that we end up with local segment [20, 30).
- Locally, we only have a segment with [20, 30) that also happens to align with a remote segment in our manifest.
- We try to …
=> [v23.1.x] archival: always move reupload start forward

src/v/cluster/partition.cc, src/v/cluster/rm_stm.cc, src/v/cluster/tests/tx_compaction_tests.cc, src/v/cluster/tests/tx_compaction_utils.h, src/v/model/record.h, src/v/storage/disk_log_impl.cc, src/v/storage/segment.cc
Adjacent compaction works by concatenating compaction indexes of
adjacent segments. When a segment has transactional batches, we
prematurely close the compaction index during segment append because
we do not know upfront whether a batch will be committed/aborted. We
recompute the index at the time of self compaction as it guarantees all
the batches are either committed/aborted.
Adjacent compacting a non self compacted index can result in incomplete
concatenated index, this fix avoids it.
This issue was exposed by running house keeping in a tight loop with low segment.ms but
has a very low probability of occurrence in practice.
Fixes: https://github.com/redpanda-data/redpanda/issues/15376
* Fixes an issue where adjacent segment compaction concatenates with an empty index resulting in …
=> compaction: do not adjacent compact non self compacted segements

src/v/kafka/client/broker.h, src/v/kafka/client/logger.h, src/v/kafka/protocol/logger.cc, src/v/kafka/protocol/metadata.h, src/v/kafka/protocol/schemata/generator.py, src/v/kafka/server/logger.h, src/v/kafka/server/request_context.h, src/v/kafka/server/requests.cc, src/v/utils/truncating_logger.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15327
=> [v23.1.x] Add truncating_logger and formatter specializations for `metadata_*` API types

src/v/security/audit/audit_log_manager.cc, src/v/security/audit/schemas/application_activity.h, src/v/security/audit/schemas/iam.h, src/v/security/audit/schemas/schemas.h, src/v/security/audit/schemas/utils.cc, tests/rptest/scale_tests/audit_log_test.py, tests/rptest/scale_tests/many_partitions_test.py, tests/rptest/services/kgo_repeater_service.py, tests/rptest/tests/cpu_profiler_admin_api_test.py, tests/rptest/tests/services_self_test.py, tests/rptest/utils/functional.py, tests/rptest/utils/scale_parameters.py
Introduce a new scale test for audit logging. The test environment leverages the kgo-repeater to generate traffic over a set number of topics so that many unique audit messages are generated, making a sort of almost worst-case scenario event for the system.
This would be a case where auditing doesn't have the oppurtunity to combine like messages. These for example would be produce messages coming from the same topic on the same shard (since partition_id is not part of the audit message payload only topic name).  Therefore this test differes from other scale tests which typically use one topic and a large number of partitions. Instead the audit scale test ensures a topic can only have as many partitions as CPUs exist in the cluster, if more are desired, they must be spread across multiple …
=> New scale test for audit logging

src/v/cluster/cloud_metadata/cluster_recovery_backend.cc, src/v/cluster/cluster_recovery_table.h, src/v/cluster/controller.cc
The recovery table would previously be destructed first, leaving the backend to potentially access destructed state.
Related https://github.com/redpanda-data/redpanda/issues/15402
* none
=> cluster: fix order of cluster recovery shutdown

src/go/rpk/pkg/adminapi/api_cloud_storage.go, src/go/rpk/pkg/adminapi/api_cloud_storage_test.go, src/go/rpk/pkg/cli/cluster/storage/recovery/start.go
Whole cluster restore doesn't currently support filtering topics, and we don't have immediate plans to support it. This field was never formally documented, so to avoid confusion, this commit deprecates it.
* none
=> rpk: deprecate topic-name-pattern in cluster restore

src/go/rpk/pkg/cli/debug/bundle/bundle_k8s_linux.go
This request was failing in pods that had more
than 1 container. Now we default to get the
logs from the 'redpanda' container.
Fixes Helm Chart test: https://github.com/redpanda-data/helm-charts/blob/main/charts/redpanda/templates/tests/test-rpk-debug-bundle.yaml
This feature is only in v23.2
* rpk: Redpanda log collection now is possible in pods where you have multiple containers, by default, rpk will gather logs from the 'redpanda' container.
=> rpk: gather k8s bundle logs of redpanda container

src/v/cluster/partition.cc
Fixes https://github.com/redpanda-data/redpanda/issues/15617
* none
=> c/partition: fix acquiring _archiver_reset_mutex

tests/rptest/services/redpanda_installer.py, tests/rptest/tests/cluster_config_test.py
test: check upgrade legacy default with restart
After changing a legacy value upgrade upgrade, restart and make sure the
change persists.
* none
=> Legacy default upgrade test

src/v/cloud_storage/tests/topic_manifest_test.cc, src/v/cloud_storage/topic_manifest.cc, src/v/cluster/types.h, src/v/tristate.h, tests/rptest/tests/retention_policy_test.py
fix for topic_manifest deserialization for disabled tristate (retention_bytes and retention_duration).
the serialization format is described here: https://github.com/redpanda-data/redpanda/blob/7ef7a17be289ebbf513b3bf5d6c09c9e79bdd6ee/src/v/cloud_storage/topic_manifest.cc#L424-L445
| tristate key |  json  |
| ------------- | ------------- |
| `disabled`  | nothing in the json  |
| `nullopt`   | `"key": null`  |
| some value   | `"key": value`  |
to deserialize this, the starting value has to be disabled (the default constructor for topic_properties would [set it to nullopt](https://github.com/redpanda-data/redpanda/blob/512a595d0983c9f31f4d03000fab9768ac19a6d5/src/v/cloud_storage/types.h#L132-L141) )
and the Null deserialization handler has to be used.
the ducktape test reproduces the …
=> fix topic_manifest.json deserialization for disabled tristate 

.github/pull_request_template.md
- v22.3.x is no longer supported and v23.3.x becomes the newest supported version
* none
=> Modify github template backport versions

src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment.h, src/v/cloud_storage/tests/remote_segment_test.cc, src/v/config/configuration.cc, src/v/config/configuration.h, tests/rptest/tests/e2e_shadow_indexing_test.py
When a consumer is waiting for hydration, the underlying kafka connection may disconnect. The read path will still wait for the hydration to finish.
This change adds a subscription to the abort source wired in with the kafka connection - if that abort source is triggered, which happens when the consumer disconnects, the read path fiber waiting for the hydration is notified by setting the promise to aborted exception.
A new setting `cloud_storage_hydration_timeout_ms` is added which defaults to 10 minutes, to control the time the fiber will wait for hydration.
* If the consumer disconnects before `cloud_storage_hydration_timeout_ms` passes, the wait for hydration is aborted. 
* If the timeout equal to `cloud_storage_hydration_timeout_ms` passes, and the consumer has not yet disconnected, …
=> cloud_storage: Make wait for hydration abortable

src/v/cluster/partition_balancer_backend.cc, tests/rptest/tests/partition_force_reconfiguration_test.py
Earlier the test was failing because controller leadership transfer injection conflicted with the poller that checked the status of nodewise recovery. This PR introducees a pause/resumable injector that the poller users to pause before checking the status.
Fixes https://github.com/redpanda-data/redpanda/issues/15337
* none
=> ducktape: deflake node wise recovery test

src/v/cloud_storage/remote_segment.cc
Most places were already holding the gate external to calls of hydrate() with the exception of aborted_transactions(). This commit fixes this by:
- holding the gate during aborted_transactions()
- making hydrate() hold the gate for the duration of its future
Fixes: https://github.com/redpanda-data/redpanda/issues/15696
* none
=> cloud_storage: hold gate in hydration

src/v/storage/segment_appender.cc, src/v/storage/tests/log_segment_appender_test.cc
In test_concurrent_append_flush, which is a fuzzer style test,
we now get() all futures returned by flush calls during the fuzz
portion, instead of only the last flush.
It is possible in some cases for prior futures to be unavailable
even after the last future has resolved which caused occasional
CI failures. See 13035 for more analysis.
Fixes #13035.
* none
=> Fix CI failure in test_concurrent_append_flush

tests/rptest/services/redpanda.py
Fixes https://github.com/redpanda-data/devprod/issues/965
For specifically the `v23.1.x` branch, azurite should not be running when running CDT tests on EC2, so we should be marking those types of test as `OFAIL`. We cannot expect `globals.json` to have `s3_secret_key` set when run on EC2 because of a change in getting CDT tests to use IAM roles. Instead, can assume `cloud_store_cred_source` is set on EC2 runs of CDT.
* none
=> [v23.1.x] rptest: change detection of when to run with azurite

tests/rptest/scale_tests/many_partitions_test.py
- 'topic' has been deprecated for 'topics' it is now also an array of strings
- Fixes: #15712
- Fixes: #15713
* none
=> Fix bad argument passed to kgo-repeater constructor

tests/rptest/scale_tests/many_partitions_test.py
Fixes: https://github.com/redpanda-data/redpanda/issues/15741
* none
=> [v23.3.x] Fix bad argument passed to kgo-repeater constructor #15741

src/go/rpk/pkg/adminapi/api_cloud_storage.go, src/v/redpanda/admin/server.cc
For robustness of the endpoint, it's expected that the restore and subsequent status calls are directed to the leader. Otherwise, a random stale node could indicate that no recovery is in progress, while it actually is.
* none
=> cluster_recovery: direct requests to controller leader

src/v/storage/segment_appender.cc, src/v/storage/tests/log_segment_appender_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15271
Fixes: https://github.com/redpanda-data/redpanda/issues/15728,
=> [v23.3.x] Fix CI failure in test_concurrent_append_flush

tests/rptest/archival/s3_client.py
In CDT we examine each bucket hash and use that to determine the list of objects to delete. This wasn't taking into account the new cluster metadata prefix. The result is that we would not completely empty the bucket before attempting to delete it, resulting in a failed bucket deletion.
* none
=> rptest: clean up cluster metadata in CDT

src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment.h, src/v/cloud_storage/tests/remote_segment_test.cc, src/v/config/configuration.cc, src/v/config/configuration.h, tests/rptest/tests/e2e_shadow_indexing_test.py
Backport of https://github.com/redpanda-data/redpanda/pull/15351
Conflicts:
- surrounding test in ducktape test was different, resulting in a conflict
* none
=> [v23.2.x] cloud_storage: Make wait for hydration abortable

src/v/cluster/config_manager.cc, src/v/config/config_store.h, src/v/config/configuration.cc, src/v/config/node_config.cc, src/v/config/tests/config_store_test.cc
Property aliases are not included in the ignored items when reading a node yaml config or cluster yaml config.
This pr fixes 3 distinct but related bugs:
1. aliases not being being applied
- solved with the first commit. when searching for a property with an alias, do not skip applying the value
2. aliases in bootstrapping redpanda.yaml causing std::illegal_argument exceptions
- with commit 4-5 include aliases in the list of names to be ignored when setting node config
~~3. properties set with aliases reverting to a previous value after a restart, under some conditions.~~ 
~~- with commit 6 translate aliases to the main name before applying it to the controller log. this is more a workaround than a proper fix of the underlying issue, as described in …
=> allow property aliases in redpanda.yaml, fix aliases not being applied

src/v/cluster/cloud_metadata/key_utils.cc, src/v/cluster/cloud_metadata/key_utils.h, src/v/cluster/cloud_metadata/offsets_snapshot.h, src/v/cluster/cloud_metadata/offsets_uploader.cc, src/v/cluster/cloud_metadata/tests/offsets_recovery_test.cc, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/kafka/server/group_manager.cc, src/v/kafka/server/group_manager.h
We currently serialize the entirety of the consmer offsets partition
into a single iobuf. This imposes a fundamental limit on the scale of
the number of groups that can be snapshotted.
The cluster manifest previously accounted for this by allowing multiple
snapshots per offsets partition in the manifest, even though existing
callers would only ever pass a single snapshot for the entire partition.
This commit begins batching the group snapshots with a configured value
for the number of groups (default 1000).
Fixes https://github.com/redpanda-data/redpanda/issues/15749
* none
=> cloud_metadata: upload consumer groups in batches

src/go/rpk/pkg/adminapi/api_cloud_storage.go, src/v/redpanda/admin/server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15740
=> [v23.3.x] cluster_recovery: direct requests to controller leader

src/v/cluster/config_manager.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15725
Fixes: https://github.com/redpanda-data/redpanda/issues/15733,
=> [v23.3.x] cluster/config_manager: use property's main name in store_delta

src/v/cluster/config_manager.cc, src/v/config/config_store.h, src/v/config/configuration.cc, src/v/config/node_config.cc, src/v/config/tests/config_store_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15605
Fixes: https://github.com/redpanda-data/redpanda/issues/15759,
=> [v23.3.x] allow property aliases in redpanda.yaml, fix aliases not being applied

src/v/cluster/log_eviction_stm.cc
Taking a snapshot is an asynchronous process which may interleave with Raft protocol receiving an install snapshot request. This way Raft start offset may already progress beyond what was requested by `log_eviction_stm`. This is correct but `log_eviction_stm` should skip writing a snapshot as it would fail either way.
Fixes: #15705
- none
=> c/log_eviction_stm: do not take the snapshot if start offset progressed

src/transform-sdk/rust/scripts/publish.py
Rust doesn't like the `v` prefix we add to tags, so remove it.
* none
=> transform-sdk/rust: fix publishing

src/v/cluster/controller_backend.cc, src/v/cluster/members_manager.cc, src/v/raft/consensus.cc
A new clang tidy check I'm developing caught that we're not awaiting for
the future `f` to finish. I've converted it into a coroutine and
co_awaited this future, which I assume is the intended semantics.
* none
=> c/members_member: don't ignore update_broker_client future

src/transform-sdk/rust/scripts/publish.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15726
=> [v23.3.x] transform-sdk/rust: fix publishing

src/v/cloud_storage_clients/util.cc, src/v/http/client.cc
No functionality changes except the log messages. While testing Redpanda against real S3 endpoint I got concerned by log messages looking like this: `Server disconnected: 'unexpected eof in body [beast.http:26]', retrying HTTP request`.
As a result, spent 3 hours debugging why S3 would close connection mid-message. The problem was that we were using a bit of an inappropriate message to indicate cleanly closed connection. Use a more appropriate error code to avoid confusion in the future.
* none
=> cloud_storage_clients: use appropriate beast error for end of stream

src/v/kafka/client/topic_cache.cc, src/v/kafka/client/topic_cache.h, src/v/kafka/protocol/schemata/generator.py, src/v/kafka/server/handlers/metadata.cc, src/v/kafka/server/tests/delete_topics_test.cc
For workloads with a large amount of topics, this topics vector can grow
to be an oversized allocation.
* Prevent metadata oversized allocations when requesting many topics.
=> k/h/metadata: use fragmented vec for topic metadata

tests/rptest/scale_tests/audit_log_test.py
10x-ing the buffer sizes ( defaults are 1 and 10Mib respectively) and doubling the audit log runloop interval to give time to catch duplicate records
Also changing the order of the runs, so the firstline run will be the run without auditing, to get a baseline of what the CDT system can do with the given number of topics/partitions, producers & consumers
* none
=> Increase audit buffer sizes for audit scale test

src/v/kafka/client/topic_cache.cc, src/v/kafka/client/topic_cache.h, src/v/kafka/protocol/schemata/generator.py, src/v/kafka/server/handlers/metadata.cc, src/v/kafka/server/tests/delete_topics_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15751
=> [v23.2.x] k/h/metadata: use fragmented vec for topic metadata

src/v/bytes/iobuf.h, src/v/bytes/tests/iobuf_tests.cc
Fix iobuf zero-copy for full fragments
When appending one large iobuf to another (or a large temporary_buffer
to an iobuf) one would expect that this is mostly a zero-copy operation,
as the underlying temporary buffers can be shared and iobuf is designed
to accommodate this case.
However, a check in the existing logic which tries to avoid creating
many small iobufs also kicks in when we append a series of full-sized
fragments to the iobuf, resulting in a full copy of each of them.
This change is a relatively conservative change to this logic where
we will now do zero-copy when a full-sized (or larger) temporary
buffer is appended. We don't otherwise change the heuristic though one
could argue that a future improvement where we also zero-copy some
"large but not totally full" buffers would …
=> Fix 128K iobuf zero-copy

src/v/archival/tests/archival_metadata_stm_gtest.cc, src/v/cluster/archival_metadata_stm.cc, src/v/cluster/archival_metadata_stm.h
For same term syncing we store the replicate commands future so that it can be awaited in the next sync call. However, the `std::exchange(_last_replicate, std::nullopt)` before the wait is problematic as it "forgets" the last replicate. If sync times out and we retry it then it behaves as if the last replicate command succeeded. This is not necessarily true as the newly added test assertion shows.
Use a shared future for _last_replicate so that it can be awaited multiple times and reset it only after it is resolved. This guarantees that sync will only return after last replicate command actually resolved.
`ignore_ready_future` call is removed as the shared future does not issue a warning if it wasn't consumed (basically a revert of e221a0aab8).
* none
=> c/archival_stm: do not reset _last_replicate on timeout

src/v/cloud_storage_clients/client_pool.cc, src/v/cloud_storage_clients/client_pool.h, src/v/cloud_storage_clients/tests/CMakeLists.txt, src/v/cloud_storage_clients/tests/client_pool_mt_test.cc, src/v/cloud_storage_clients/tests/client_pool_test.cc, src/v/cloud_storage_clients/tests/s3_client_test.cc
* Fix a rare bug where http client connections would vanish from the connection pool leading to various operations hanging while waiting for an http client.
=> cloud_storage_clients: stricter but simpler invariants for the pool

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/application.cc, src/v/resource_mgmt/storage.cc, src/v/resource_mgmt/storage.h, src/v/storage/disk_log_impl.cc
This PR works around an issue where certain configs could be impossible to move durably off their legacy defaults after an upgrade by providing override config properties without legacy defaults (and with default values _matching_ the legacy default value).
Fixes #15674 
* Fix an issue where new configs would continually revert to legacy defaults after an upgrade.
=> Overrides for space_management_enable and retention_local_strict

src/v/cluster/cloud_metadata/tests/cluster_recovery_backend_test.cc, src/v/cluster/cloud_metadata/tests/producer_id_recovery_test.cc, src/v/cluster/tests/tx_compaction_tests.cc, src/v/cluster/tests/tx_compaction_utils.h, src/v/storage/tests/CMakeLists.txt, src/v/storage/tests/compaction_e2e_multinode_test.cc, src/v/test_utils/test_macros.h
This reproduces a bug fixed by e8e9ab7f27056d31b5287b2f6bc6cccae0e703fa
wherein an aborted transaction was visible by a consumer after
compaction and replication.
The bug was caused by the fact that we would skip over segments of size
1, rather than self compacting them.
The sequence is roughly:
node 1:
- begin tx 1 (seg 1)
- roll segment
- data batch in tx 1 (seg 2)
- roll segment
- abort tx 1 (seg 3)
- begin tx 2, data batch in tx 2, abort tx 2 (seg 3)
- run compaction: skips first two segments from tx 1, removes abort
marker tx 1 because it's deduplicated in favor of abort tx 2's abort
marker (all aborts markers have the same key)
- replicate to node 2
node 2:
- gets everything remaining in a single segment, now including just
[begin tx 1, data tx 1, abort tx 2]
- self compaction runs, …
=> tests: repro for zombie txs after compaction

src/v/cluster/topic_table.cc
It is possible that the drop topic lifecycle marker replicate request would timeout. In this case requester has no other option than to retry dropping lifecycle marker. Logic in `cluster::topic_table` is idempotent and duplicate marker drop command does not harm to Redpanda. Changed log level of an entry notifying about duplicated drop command from an error to info level.
- none
=> c/topic_table: do not log duplicated lifecycle marker command

src/v/cluster/rm_stm.cc
We never cleanup tx_locks, clear_old_tx_pids seems like the right place
to be doing this. Two things:
1. We should be ensuring the tx_lock isn't held when expiring, this
mirrors the logic in `is_producer_expired`.
2. We actually need to erase the pid from the tx_lock. Right now it
grows unboundedly.
So when we collect our pids to delete we break the mutex so that if that
pid is ever used again before deleting it from the map we will not allow
progress. I am not sure if we need error handling someplace special for
this potentially broken semaphore.
* Fix a memory leak when transactions are used with many different producer IDs.
=> c/rm_stm: cleanup tx_locks

src/v/cluster/controller_backend.cc, src/v/cluster/members_manager.cc, src/v/raft/consensus.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15738
=> [v23.2.x] c/members_member: don't ignore update_broker_client future

tests/rptest/tests/controller_availability_test.py
/home/ubuntu/redpanda/tests/rptest/tests/controller_availability_test.py:75: SyntaxWarning: assertion is always true, perhaps remove parentheses?
* none
=> rptest: fix an always true assertion

src/v/raft/state_machine.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15426
=> [v23.2.x] r/state_machine: ignore broken semaphore and condition var exceptions

tests/rptest/tests/e2e_shadow_indexing_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15579
Fixes: https://github.com/redpanda-data/redpanda/issues/15598,
=> [v23.2.x] tests/e2e_shadow_indexing_test: wait until segments has one entry

src/v/storage/disk_log_impl.cc, src/v/storage/tests/disk_log_builder_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15440
Fixes: https://github.com/redpanda-data/redpanda/issues/15601,
=> [v23.2.x] storage/disk_log_impl: defensive reverse iteration of _segs

src/v/cluster/topic_table.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15407
=> [v23.2.x] c/topic_table: do not log duplicated lifecycle marker command

src/v/syschecks/syschecks.cc
Assume that ext filesystems are ext4
Due to scylladb/seastar#251 all of ext2, ext3 and ext4 will be
detected as ext2 (they shared the same superblock magic number).
This leads to an erroneous warning claiming that you are not running
on ext4 nor XFS. For now, we will simply that assume any ext detection
means ext4, as ext2 and 3 use is very limited as ext4 was rolled out
more than 15 years ago and almost entirely supplanted use of the
earlier variants.
A partial fix for:
https://github.com/redpanda-data/redpanda/issues/13469
A more involved fix may follow to resolve seastar#251.
* ext4 is no longer incorrectly detected as ext2 (all of ext2, 3 and 4 are assumed to be ext4).
=> Ext4 detection

src/v/cluster/config_manager.cc, tests/rptest/tests/cluster_config_test.py
Config aliases:
Part of the fix for https://github.com/redpanda-data/redpanda/issues/15263 requires ensuring that a cluster property is saved only once in the config_manager::_raw_values map. 
When storing a property, the name is converted to the main property name and any aliases are removed from the map, in case the node inherits the snapshot from an old version.
the fix make sure that the cleanup part is always performed, before this it would be skipped the incoming key was already the main name
* none
=> cluster/config_manager: ensure cleanup of old aliases

tests/rptest/tests/topic_delete_test.py
Partition shutdown and purger run asynchronously and can race since \#11873. 5ms grace period for tests is too as TS requests for final manifest upload can take many milliseconds, especially with real TS backend.
Fixes #13510
* none
=> rptest: increase grace period for finalize

src/go/rpk/pkg/adminapi/api_cluster.go, src/go/rpk/pkg/adminapi/api_partition.go, src/go/rpk/pkg/cli/cluster/partitions/partitions.go, src/go/rpk/pkg/cli/cluster/partitions/status.go, src/go/rpk/pkg/cli/cluster/partitions/unsafe_recover.go, tests/rptest/clients/rpk.py, tests/rptest/tests/partition_force_reconfiguration_test.py
Adding `rpk cluster partitions unsafe-recover`:  This command will let the user forcefully recover data adversely affected by irrecoverable nodes.
Core's PRs: 
- https://github.com/redpanda-data/redpanda/pull/15394
- https://github.com/redpanda-data/redpanda/pull/13943
Changes introduced in this PR:
- New `rpk cluster partitions unsafe-recover` command. (Usage below)
- A new field: `Partitions Pending Recovery (<Number of partitions>)` in `rpk cluster partitions balancer-status` response.
You must pass the dead-nodes list to execute the command, the command will print the "plan" (i.e the partitions that lost majority) and has and interactive prompt to confirm you want to perform the unsafe recovery:
```
$ rpk cluster partitions unsafe-recover --from-nodes 1
NAMESPACE  TOPIC  PARTITION …
```
=> rpk: add 'rpk cluster partitions unsafe-recover'

tests/rptest/test_suite_cloud.yml
Just enable a subset of tests that are currently OK'ed to run.
Related issue: https://github.com/redpanda-data/cloudv2/issues/11277
* none
=> rptest: update cloud test suite to subset

src/v/cluster/controller.cc, src/v/cluster/topics_frontend.cc, src/v/cluster/topics_frontend.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/kafka/server/handlers/alter_configs.cc, src/v/kafka/server/handlers/configs/config_utils.h, src/v/kafka/server/handlers/create_topics.cc, src/v/kafka/server/handlers/incremental_alter_configs.cc, src/v/kafka/server/handlers/topics/validators.h, src/v/kafka/server/tests/config_utils_test.cc, tests/rptest/tests/audit_log_test.py, tests/rptest/tests/cluster_config_test.py, tests/rptest/tests/internal_topic_protection_test.py, tests/rptest/tests/replication_factor_change_test.py, tests/rptest/tests/topic_creation_test.py, tests/rptest/utils/schema_registry_utils.py
This PR adds a new cluster configuration parameter `minimum_topic_replications` which permits a user to
force all newly created topics to have a replication factor of at least that value.  By default this cluster config
is set to 1.
Any existing topics that have RFs less than the specified value will continue to function as normal however a WARN level
log from the cluster logging facility will be generated indicating that the specified topic has an RF less than the specified
config.  This message will be generated at start up and whenever the cluster config option is changed.
The new configuration option _does not_ have any effect on internal topics (topics outside of the `kafka` namespace or on `__audit_log`, `__consumer_offsets`, or `_schemas`).
Fixes: …
=> Support for clamping replication factor

src/v/cluster/config_manager.cc, tests/rptest/tests/cluster_config_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15815
=> [v23.3.x] cluster/config_manager: ensure cleanup of old aliases

src/go/rpk/pkg/adminapi/api_cluster.go, src/go/rpk/pkg/adminapi/api_partition.go, src/go/rpk/pkg/cli/cluster/partitions/partitions.go, src/go/rpk/pkg/cli/cluster/partitions/status.go, src/go/rpk/pkg/cli/cluster/partitions/unsafe_recover.go, tests/rptest/clients/rpk.py, tests/rptest/tests/partition_force_reconfiguration_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15300
Fixes: https://github.com/redpanda-data/redpanda/issues/15825,
=> [v23.3.x] rpk: add 'rpk cluster partitions unsafe-recover'

src/v/cluster/partition_probe.cc, src/v/cluster/partition_probe.h, src/v/kafka/server/handlers/fetch.cc, tests/rptest/services/redpanda.py, tests/rptest/tests/follower_fetching_test.py
Since it is hard to validate if Follower Fetching feature is working
correctly we add a separate `bytes_fetched_from_follower_total` metric
that counts bytes that were read from the follower. This will make it
very easy to validate if consumers are reading from the closest replica.
Note: follower fetched bytes are also accounted to overall bytes read.
Important note: 
Follower fetched bytes may not be incremented if consumer closest replica is current partition leader.
Fixes: #14814
* Added new metric to provide Follower Fetching feature observability
=> Added metric representing bytes read from follower

tests/rptest/scale_tests/high_throughput_test.py
causing cdt to fail with the import error
ref redpanda-data/devprod#972
* none
=> [v23.2.x] tests/scale: htt import missing ignore mark

src/v/cluster/archival_metadata_stm.cc
Some operations try to sync with relatively low timeouts. Under stress, they are expected to time out occasionally. This is a warning at most.
Downgrade the log level to avoid spooking users and ducktape tests.
---
This should have been part of #15677 but I forgot to push local changes...
* none
=> c/archival_stm: downgrade timeout log to warn

.github/workflows/transform-sdk-release.yml
Remove invalid permission, this check should only need write access to the repo to push the tag.
* none
=> gha: remove invalid permission

src/go/rpk/pkg/cli/topic/create.go
With the introduction of `minimum_topic_replications`, topic creation using `rf=-1` (therefor relying on `default_topic_replications`) may now fail because the default is less than the minimum.  Originally, rpk would assume that the failure was because `default_topic_replications` was not odd.  This change will now display the error message, if
one was provided, in this situation.
* [rpk] more informative error message display on create topic failure
=> rpk: Print create topics error message if available

src/v/redpanda/application.cc
Some customers have run into issues where they set `rack: ''` in their node config.  This change will convert an empty string for the rack node config to a `std::nullopt`.
* Redpanda used to accept an empty string in `redpanda.rack` in node config.  This would cause issues in Kafka operations.  Redpanda will now error on startup if `redpanda.rack` is set to an empty string.
=> node_config: Disallow empty rack

src/v/config/configuration.cc, tests/rptest/services/redpanda.py
Keep it enabled for all the tests. Need some extra time to understand the cost implications for high usage clusters.
* none
=> archival: disable scrubber by default

src/v/cluster/cloud_metadata/cluster_recovery_backend.cc, src/v/cluster/cloud_metadata/uploader.cc, src/v/cluster/cluster_recovery_manager.cc, src/v/cluster/controller.cc, src/v/cluster/controller.h, src/v/redpanda/admin/server.cc, tests/rptest/tests/recovery_mode_test.py
=> Disable cloud metadata upload and cluster restore in recovery mode

src/v/config/node_config.cc, src/v/config/node_config.h, src/v/redpanda/admin/api-doc/config.def.json, src/v/redpanda/admin/api-doc/config.json, src/v/redpanda/admin/server.cc, src/v/redpanda/admin/server.h, tests/rptest/services/admin.py, tests/rptest/tests/log_level_test.py
This PR introduces `verbose_logging_timeout_max`, which, if set, causes expiration times included in set_log_level requests to be clamped before timeouts are calculated.
Includes an assortment of minor improvements to the logic around setting log levels and managing timeouts around those settings.
Fixes https://github.com/redpanda-data/core-internal/issues/938
Fixes https://github.com/redpanda-data/core-internal/issues/931
Fixes https://github.com/redpanda-data/core-internal/issues/930
* `verbose_logging_timeout_max` node config, to prevent setting TRACE and DEBUG log level indefinitely
=> verbose_logging_timeout_max
