redpanda-data/redpanda

src/v/kafka/server/handlers/fetch.cc
Take into consideration that if the fetch request's rack ID is an empty string, act as if no rack ID was provided.
* Redpanda will now correctly handle an empty rack ID provided in a fetch request
=> kafka: Don't set rack ID if empty

src/v/kafka/server/handlers/fetch.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15846
=> [v23.3.x] kafka: Don't set rack ID if empty

src/v/kafka/server/handlers/fetch.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15846
=> [v23.2.x] kafka: Don't set rack ID if empty

tests/rptest/archival/s3_client.py
In general this seems like an unexpected case. Perhaps it's sometimes an S3 issue, but it's certainly possible this is caused by a ducktape bug (see https://github.com/redpanda-data/redpanda/pull/15754).
In either case, it seems worthwhile to flag, if anything, to inform us when to expect artifacts to show up in our S3 account.
* none
=> rptest: log error on failure to delete bucket

src/v/cluster/scheduling/leader_balancer_constraints.h
When there are many topics within in a system we can get oversized
allocations, so switch to a btree_map. In particular this is while
rebuilding the index for `_topic_replica_index`, but presumably all 
these data structures have a similar order of magnitude.
* none
=> c/s/leader_balancer: prevent oversized alloc

src/v/cluster/config_manager.cc, tests/rptest/services/admin.py, tests/rptest/tests/cluster_config_test.py
cfg.get() can throw std::out_of_range if the name is not known by redpanda.
this can be the case for unknown properties that nonetheless gets written to the controller log, and later loaded again during startup
Fixes #15839
* safer handle unknown properties in local state
=> cluster/config_manager: protect cfg.get() behind cfg.contains()

src/v/cloud_storage_clients/client_pool.cc, src/v/cloud_storage_clients/client_pool.h, src/v/cloud_storage_clients/tests/CMakeLists.txt, src/v/cloud_storage_clients/tests/client_pool_mt_test.cc, src/v/cloud_storage_clients/tests/client_pool_test.cc, src/v/cloud_storage_clients/tests/s3_client_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15681 
Fixes #15785
=> [v23.2.x] cloud_storage_clients: stricter but simpler invariants for the pool

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15853
=> [v23.3.x] rptest: allow the new version of xfs/ext4 fs error msg

.github/workflows/transform-sdk-release.yml
I really wish there was a better way to test these GHA other than
needing to do an actual release 😢
* none
=> gha: s/git.ref_name/github.ref_name

tests/docker/ducktape-deps/kgo-verifier
Backport of PR https://github.com/redpanda-data/redpanda/pull/15852
Fixes: https://github.com/redpanda-data/redpanda/issues/15875,
=> [v23.3.x] t/kgo: upgrade kgo to do a full run after /last_pass

tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/services/redpanda.py, tests/rptest/services/redpanda_cloud.py
Fixes https://github.com/redpanda-data/cloudv2/issues/10807
Blocked by PR: https://github.com/redpanda-data/vtools/pull/2407
Example command to run new test:
```console
ducktape \
--debug \
tests/rptest/redpanda_cloud_tests/high_throughput_test.py::HighThroughputTest.test_add_and_decommission
```
output from test run:
```
test_id:    rptest.redpanda_cloud_tests.high_throughput_test.HighThroughputTest.test_add_and_decommission
run time:   11 minutes 35.892 seconds
------------------------------------------------------------------------------------------------------------------------------ …
```
=> rptest: add `test_add_and_decommission()`

src/v/kafka/server/handlers/fetch.cc
* Have fetch handler ensure rack awareness is enabled before performing follower fetching
=> kafka: Disable FF if rack awareness is disabled

.github/workflows/backport-command.yml, .github/workflows/scripts/backport-command/create_issue.sh, .github/workflows/scripts/backport-command/create_pr.sh
In the case of a clean backport, the original PR author is the reviewer,
otherwise when creating an issue, we don't list reviewers, as we assume
the reviewer will assign them appropriately.
* none
=> gha: improve backport reviewers

src/v/cluster/partition_leaders_table.cc, src/v/cluster/partition_leaders_table.h, src/v/cluster/tests/metadata_dissemination_test.cc, src/v/cluster/topic_updates_dispatcher.cc, src/v/cluster/topic_updates_dispatcher.h, src/v/kafka/server/handlers/metadata.cc, tests/rptest/tests/consumer_group_recovery_tool_test.py, tests/rptest/tests/partition_force_reconfiguration_test.py, tests/rptest/tests/upgrade_test.py
Updating leadership metadata before the topic is ready to serve traffic is not desired. It prevents waiting for leader to be reported by raft group when it is actually ready.
Fixes: #14673
- none
=> c/topics_dispatcher: do not guesstimate leader ids

src/v/cluster/archival_metadata_stm.cc, src/v/cluster/archival_metadata_stm.h, tests/rptest/services/redpanda.py
Backport of:
*  https://github.com/redpanda-data/redpanda/pull/15677
Fixes #15783
* none
=> [v23.2.x] c/archival_stm: do not reset _last_replicate on timeout

src/v/kafka/protocol/offset_fetch.h, src/v/kafka/protocol/schemata/generator.py, src/v/kafka/server/group.cc, src/v/kafka/server/server.cc
We've seen oversized allocs with this field when group fetches are used.
This switches to a frag vec for partitions.
Fixes: https://github.com/redpanda-data/redpanda/issues/15909
* Prevent oversized allocs when group fetching from many partitions.
=> kafka/protocol: use frag vec for offset fetch

tests/rptest/scale_tests/audit_log_test.py
From the most recent run of the audit log scale tests:
```
File "/home/ubuntu/redpanda/tests/rptest/services/cluster.py", line 82, in wrapped
r = f(self, *args, **kwargs)
File "/home/ubuntu/redpanda/tests/rptest/scale_tests/audit_log_test.py", line 413, in test_audit_log
assert pct_difference(audit_disabled_results.p90,
AssertionError
```
The test ended up failing because the results beat the baseline by greater then the hardcoded 10% threshold:
```
[INFO  - 2023-12-20 13:02:43,395 - audit_log_test - test_audit_log - lineno:402]: audit_disabled_results: {'time_elapsed': 163.91215109825134, 'total_produced': 837362, 'total_consumed': 837330, 'p50': 15477.83203125, 'p90': 134794.0625, 'p99': 839466.16796875}
[INFO  - 2023-12-20 13:02:43,395 - …
```
=> Skip assertion in audit log tests if results beat the baseline

src/go/.goreleaser.yaml
Only patch versions of latest stable release should be uploaded
fixes redpanda-data/vtools#2424
* none
=> [v23.2.x] goreleaser: disable homebrew uploads for go builds

tests/rptest/scale_tests/cloud_storage_compaction_test.py
Removes check in test whose failure is normal.
Fixes: #15744
* none
=> test: remove source of false positive failure

src/go/rpk/pkg/cli/transform/template/golang/transform.gosrc, src/transform-sdk/go/transform/example_mirror_test.go, src/transform-sdk/go/transform/example_regexp_filter_test.go, src/transform-sdk/go/transform/example_transcoding_test.go, src/transform-sdk/go/transform/internal/testdata/dynamic/transform.go, src/transform-sdk/go/transform/internal/testdata/identity/transform.go, src/transform-sdk/go/transform/internal/testdata/schema-registry/transform.go, src/transform-sdk/go/transform/internal/testdata/transform-error/transform.go, src/transform-sdk/go/transform/internal/testdata/transform-panic/transform.go, src/transform-sdk/go/transform/internal/testdata/wasi/transform.go, src/transform-sdk/go/transform/processor.go, src/transform-sdk/go/transform/sdk.go
We've recieved good feedback that a more idiomatic interface for
transforms is using a pattern similar to http.HandlerFunc. This is much
cleaner IMO and allows for emitting records without buffering, as slices
are sometimes akward to work with.
* Data Transforms written in Golang now use a non-buffered write mechanism. Transforms that used to be written as
```
func myTransform(e transform.WriteEvent) ([]transform.Record, error) {
return transform.Record[]{e.Record()}, nil
}
```
Can now be written as
```
func myTransform(e transform.WriteEvent, w transform.RecordWriter) error {
return w.Write(e.Record())
}
```
=> transform-sdk/go: introduce RecordWriter

src/go/rpk/pkg/cli/transform/template/rust/main.rustsrc, src/transform-sdk/rust/core-sys/src/lib.rs, src/transform-sdk/rust/core-types/src/lib.rs, src/transform-sdk/rust/examples/identity.rs, src/transform-sdk/rust/examples/jaq/src/main.rs, src/transform-sdk/rust/examples/json2avro/src/main.rs, src/transform-sdk/rust/src/lib.rs
In a similar change to our Golang SDK (https://github.com/redpanda-data/redpanda/pull/15922), also have a non-buffering record writer to output transformed records to.
* Data Transforms written in Rust now use a non-buffered write mechanism. Transforms that used to be written as
```
fn my_transform(event: WriteEvent) -> Result<Vec<Record>> {
Ok(vec![
Record::new(
event.record.key().map(|k| k.to_owned()),
event.record.value().map(|v| v.to_owned()),
)
])
}
```
Can now be written as
```
fn my_transform(event: WriteEvent, writer: &mut dyn RecordWriter) -> Result<()> {
writer.write(Record::new(
event.record.key().map(|k| k.to_owned()),
event.record.value().map(|v| v.to_owned()),
))?;
Ok(())
}
```
=> transform-sdk/rust: introduce RecordWriter

src/v/transform/tests/transform_processor_test.cc, src/v/transform/transform_processor.cc
It's possible to get a double start of the processor if the wasm VM immediately stops, as we check to see if the task is running in the manager to decide if we start a processor or not. Fix that by correcting the predicate to be "have I called start without calling stop". Since the consequence of messing up reference counting is a crash, I've also added another cautionary check to start to prevent double starts.
I will followup with some ducktape tests around failing modules to hopefully check this kind of thing in the future.
* Prevent an assertion from being triggered when Wasm VMs fail immediately.
=> transform: prevent double processor starts

.github/workflows/stale.yml
A Github action to mark all bug reports that haven't had activity in 3 months as stale. Stale issues are closed after 2 weeks. This is setup using https://github.com/actions/stale
* none
=> gha: create stale issue workflow

.github/workflows/stale.yml
=> gha: mark ci-failures as stale

src/v/cluster/config_manager.cc, tests/rptest/services/admin.py, tests/rptest/tests/cluster_config_test.py
cfg.get() can throw std::out_of_range if the name is not known by redpanda.
this can be the case for unknown properties that nonetheless gets written to the controller log, and later loaded again during startup
Backport of PR #15840
* safer handle unknown properties in local state
=> [v23.3.x] cluster/config_manager: protect cfg.get() behind cfg.contains()

src/v/ssx/tests/work_queue_test.cc, src/v/ssx/work_queue.cc, src/v/ssx/work_queue.h
There are situations where we need to support recursive tasks for the
transform subsystem, and in order to do that we can't keep a single
variable of the tail, as it's possible for recursive tasks to try to
tail off a single future. Fix this by tracking the pending work in an
explicit data structure.
* Fixes a crash if a WebAssembly function is deployed that immediately crashes.
=> ssx/work_queue: support recursive tasks

src/go/rpk/pkg/cli/transform/template/golang/transform.gosrc, src/transform-sdk/go/transform/example_mirror_test.go, src/transform-sdk/go/transform/example_regexp_filter_test.go, src/transform-sdk/go/transform/example_transcoding_test.go, src/transform-sdk/go/transform/internal/testdata/dynamic/transform.go, src/transform-sdk/go/transform/internal/testdata/identity/transform.go, src/transform-sdk/go/transform/internal/testdata/schema-registry/transform.go, src/transform-sdk/go/transform/internal/testdata/transform-error/transform.go, src/transform-sdk/go/transform/internal/testdata/transform-panic/transform.go, src/transform-sdk/go/transform/internal/testdata/wasi/transform.go, src/transform-sdk/go/transform/processor.go, src/transform-sdk/go/transform/sdk.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/15922
=> [v23.3.x] transform-sdk/go: introduce RecordWriter

src/v/config/tests/config_store_test.cc
This test is mainly concerned with showing how to use config_store::read_yaml and how to ignore unknown keys that need to be interpreted by a separate config_store
related to #15759
followup for #15605 
* none
=> follow-up: config/config_store_test: ignored_keys test

src/v/ssx/tests/work_queue_test.cc, src/v/ssx/work_queue.cc, src/v/ssx/work_queue.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15939
=> [v23.3.x] ssx/work_queue: support recursive tasks

src/go/rpk/pkg/cli/transform/template/rust_template.go
We will manually add the package to get the latest version when using
`cargo add redpanda-transform-sdk`
* Fix an issue with `Cargo.toml` when initializing a Rust Data Transform project via `rpk transform init`
=> rpk/transform/init: fix cargo.toml template

src/go/rpk/pkg/cli/transform/deploy.go, tests/rptest/clients/rpk.py
Instead of having the positional arg for a binary to deploy, use a flag,
so we can support other (mutually exclusive) binary sources.
* `rpk transform deploy` takes a `--file` flag to deploy a compiled WebAssembly binary.
=> rpk/transform/deploy: introduce --file flag

src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h
mem_state::expected - This map is never written to, after commit
https://github.com/redpanda-data/redpanda/commit/d7fe6e796a732282a105959b7bbf59bb5f2673ae
mem_state::tx_start(s) - Unused after is_tx_ga=true 
mem_state::preparing - preparing phase is no longer used as a part of the protocol.
* none
=> rm_stm: remove dead code

src/v/net/connection.cc, src/v/net/connection.h
- Performance testing has shown excessive CPU time is spent when local_address() is called within a tight loop, this has been tracked down to the fact that ss::file_desc::local_address() invokes a system call, getsockname.
- To mitigate this issue, the connection class now caches the value of local address upon instantiation.
- Relates to: #15898
* Caches the connections local address preventing the need to make a system calls to grab this value when auditing events.
=> net: Cache value of local address

src/v/syschecks/syschecks.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/13496
=> [v23.3.x] Ext4 detection

src/v/cluster/config_manager.cc, tests/rptest/services/admin.py, tests/rptest/tests/cluster_config_test.py
cfg.get() can throw std::out_of_range if the name is not known by redpanda.
this can be the case for unknown properties that nonetheless gets written to the controller log, and later loaded again during startup
Backport of PR https://github.com/redpanda-data/redpanda/pull/15840
=> [v23.2.x] Fix/v23.2.x/cfg unchecked test

src/v/kafka/client/produce_batcher.h, src/v/kafka/client/produce_partition.h, src/v/kafka/client/test/produce_batcher.cc, src/v/kafka/client/test/produce_partition.cc, src/v/storage/record_batch_builder.cc, src/v/storage/record_batch_builder.h
Fixes: #15900 
Utilize asynchronous compression in kafka client to reduce possibility of oversized allocation.
* Internal kafka client now uses asynchronous compression (when possible) to reduce possibility of oversized allocations and reactor stalls
=> Use async compression in kafka client

src/v/cluster/leader_router.h, src/v/cluster/migrations/tx_manager_migrator_handler.h
When leader table is stale (say at startup or during failures), the
current code can result in a ping pong of requests between two brokers
in a tight loop.
Example
- tx_migration_replicate dispatched from node 1 to node 2 (because node 1
thinks node 2 is the leader)
- node 2 dispatches the request back to node 1 because it thinks node 1
is the leader.
Until leadership stabilizes this results in a huge pile up of requests
which manifested as an oversized allocation.
Don't think a router is the right choice in the handler as the handler
is supposed to process the request locally. If it returns an error, it
is propagated to the source router which dispatches to the correct
leader. This also breaks the ping pong loop as the source router has
sleeps induced for retry backoff.
Fixes: …
=> tx_migration: avoid ping pong of requests between brokers

src/v/cluster/bootstrap_service.cc, src/v/cluster/bootstrap_service.h, src/v/cluster/cloud_metadata/offsets_recovery_service.h, src/v/cluster/ephemeral_credential_service.cc, src/v/cluster/ephemeral_credential_service.h, src/v/cluster/id_allocator.cc, src/v/cluster/id_allocator.h, src/v/cluster/metadata_dissemination_handler.cc, src/v/cluster/metadata_dissemination_handler.h, src/v/cluster/migrations/tx_manager_migrator_handler.h, src/v/cluster/node_status_rpc_handler.cc, src/v/cluster/node_status_rpc_handler.h, src/v/cluster/partition_balancer_rpc_handler.cc, src/v/cluster/partition_balancer_rpc_handler.h, src/v/cluster/self_test_rpc_handler.cc, src/v/cluster/self_test_rpc_handler.h, src/v/cluster/service.cc, src/v/cluster/service.h, src/v/cluster/topic_recovery_status_rpc_handler.cc, src/v/cluster/topic_recovery_status_rpc_handler.h, src/v/cluster/tx_gateway.cc, src/v/cluster/tx_gateway.h, src/v/raft/service.h, src/v/rpc/rpc_compiler.py, src/v/rpc/test/rpc_gen_cycling_test.cc, src/v/transform/rpc/service.cc, src/v/transform/rpc/service.h
Pass RPC requests by value, as we start to write some handlers using
coroutines, it can be a footgun to access have a suspension point, then
the request is destroyed. An example that motivated this:
```c++
ss::future<reply> service::handle(request&& r, rpc::streaming_context&) {
co_await ss::coroutine::switch_to(get_scheduling_group());
co_return co_await handle_request(std::move(r));
}
```
In this case `r` is destroyed because the coroutine does not own the
value, and handle request would have a stack-use-after-return issue.
Now that we pass by value, we don't have to remember to move the value
into the current method.
Fixes: https://github.com/redpanda-data/core-internal/issues/898
* none
=> rpc: pass requests by value

tests/rptest/perf/small_batches_test.py
Adds a nightly regression test with many clients and partitions test where producers send small batches to Redpanda. This sort of workload will help us track performance improvements of a few future projects.
* none
=> Add small batches nightly regression test

src/v/utils/memory_data_source.h
utils: allow memory data source to take tmpbuf
* none
=> utils: allow memory data source to take tmpbuf

src/v/kafka/client/produce_batcher.h, src/v/kafka/client/produce_partition.h, src/v/kafka/client/test/produce_batcher.cc, src/v/kafka/client/test/produce_partition.cc, src/v/storage/record_batch_builder.cc, src/v/storage/record_batch_builder.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15920
Fixes: https://github.com/redpanda-data/redpanda/issues/15974,
=> [v23.3.x] Use async compression in kafka client

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/application.cc, src/v/transform/rpc/client.cc, src/v/transform/rpc/client.h, src/v/transform/rpc/deps.cc, src/v/transform/rpc/deps.h, src/v/transform/rpc/tests/transform_rpc_test.cc, src/v/wasm/api.h, src/v/wasm/tests/wasm_fixture.cc, src/v/wasm/tests/wasm_transform_bench.cc, src/v/wasm/wasmtime.cc
Support 2 new cluster tunables:
- Max wasm binary size
- Wasm function max runtime
Before these were not tunables, but hardcoded. This allows overriding these if needed.
Note that the max wasm binary size isn't dynamic, and is harder to do that without passing a sharded config property. So as a stop gap, it's marked as needing a restart.
* Support dynamically changing the limit for WebAssembly binary size
* Support changing the timeout for WebAssembly functions
=> wasm: add runtime and max binary configs

src/v/cluster/log_eviction_stm.cc
It is perfectly possible that the install snapshot request will reach the follower right before the `log_eviction_stm` asks for the snapshot creation. In this case an `stm_manager` would do the check and throw an exception informing that the snapshot can not be taken. In order to handle the situation gracefully added a check in log eviction stm to skip taking snapshot if start offset already progressed.
Fixes: #14220
- none
=> c/log_eviction_stm: do not request snapshot if already progressed

src/v/archival/tests/ntp_archiver_test.cc, src/v/raft/consensus.cc, src/v/raft/offset_translator.cc, src/v/raft/offset_translator.h, src/v/raft/tests/offset_translator_tests.cc
When the corresponding kvstore state is not found, we should recover offset_translator state from the log, not use configuration_manager state - the latter is incorrect because there are other batch types contributing to offset delta, not just configuration batches. This code is a vestige from the time when the separate offset_translator component was just introduced and its kvstore state needed to be bootstrapped from configuration_manager state.
* none
=> r/offset_translator: remove unsafe bootstrap code

src/v/kafka/server/handlers/metadata.cc
When partition is first created in Redpanda some of the cluster nodes which are not hosting partition replicas may not yet have leadership metadata. In this case Redpanda still has to return partition metadata. In order not to disturb the client (returning -1 as a leader id may cause some clients to stop) Redpanda has to return a leader id. If the information is not present we will always return the first node from replica set in leader epoch equal to 0. This way client will either communicate with the actual leader or issue a metadata request to other node that may contain up to date information.
Fixes: #15949
Fixes: #15972
- none
=> k/metadata: guesstimate leader when information is not yet present

src/v/cluster/leader_router.h, src/v/cluster/migrations/tx_manager_migrator_handler.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15953
Fixes: https://github.com/redpanda-data/redpanda/issues/15979,
=> [v23.3.x] tx_migration: avoid ping pong of requests between brokers

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15853
=> [v23.2.x] rptest: allow the new version of xfs/ext4 fs error msg

src/v/cluster/partition_balancer_planner.cc
In order to be consistent and more careful changed the policy of partition reconfiguration issued by partition balancer when moving partition as a result of disk space exhaustion.
- none
=> c/partition_balancer: use full partition move when disk is full

src/v/cluster/feature_manager.cc, src/v/cluster/metrics_reporter.cc, src/v/cluster/metrics_reporter.h, src/v/config/validators.cc, src/v/config/validators.h, tests/rptest/tests/metrics_reporter_test.py, tests/rptest/tests/redpanda_oauth_test.py
* Add oidc to the licence nag
* Add a new field to the report: `has_oidc`
E.g.:
```json
{
"cluster_uuid": "3d53d84c-69d3-4c5e-9098-9c3e4af079e6",
"cluster_created_ts": 1673994399728,
"topic_count": 5,
"partition_count": 24,
"nodes": [
{
"node_id": 1,
"cpu_count": 2,
"version": "no_version - 000-dev",
"uptime_ms": 10223,
"is_alive": true,
"disks": [
{
"free": 153149313024,
"total": 930158792704
}
]
}
],
"has_kafka_gssapi": true,
"has_oidc": true
}
```
* none
=> securit/:OIDC: Enable licence check and telemetry

tests/rptest/utils/si_utils.py
quiesce_uploads() can timeout for several reasons. 
These reasons are logged but the final timeout error does not capture this message.
This pr reports the last message produced while waiting for the last kafka offset to read the high watermark.
hopefully, this should make it slightly easier to differentiate between failure modes 
Related to https://github.com/redpanda-data/redpanda/issues/15310#issuecomment-1840278478
* none
=> tests/si_utils: error message for quiesce_uploads timeouts

src/v/archival/tests/ntp_archiver_test.cc, src/v/raft/consensus.cc, src/v/raft/offset_translator.cc, src/v/raft/offset_translator.h, src/v/raft/tests/offset_translator_tests.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15919
=> [v23.3.x] r/offset_translator: remove unsafe bootstrap code

SECURITY.md
=> security: update supported version

src/v/config/configuration.cc, src/v/resource_mgmt/storage.cc, src/v/storage/disk_log_impl.cc, tests/rptest/tests/cluster_config_test.py
Make the following configuration options have these default values regardless of the upgrade history of the cluster
space_management_enable=true
retention_local_strict=false
Additionally these options used to work around an issue in v23.2 which prevented changes to the above options from being sticky in an upgraded cluster no longer have any affect.
space_management_enable_override
retention_local_strict_override
They'll be fully deprecated at a later time.
Fixes: https://github.com/redpanda-data/redpanda/issues/15995
Space management is now enabled by default for upgraded clusters starting in v23.3, unless the feature has been explicitly disabled.
=> storage: enable space management by default

src/v/config/configuration.cc, src/v/resource_mgmt/storage.cc, src/v/storage/disk_log_impl.cc, tests/rptest/tests/cluster_config_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15996
Fixes: https://github.com/redpanda-data/redpanda/issues/16051,
=> [v23.3.x] storage: enable space management by default

tests/rptest/redpanda_cloud_tests/omb_validation_test.py
Many kafka client libraries (java, librdkafka) perform poorly when
producing to very high partition topics. This leads to one thread not
being fast enough to produce at a reasonable batch size.
In a tier 6 test we were seeing batch size slowly growing all the way to
85K. This isn't great because it means we are not running the test in a
stable state and this becomes more a client benchmark. Further lower
batch sizes are actually more demanding for RP itself.
To avoid this problem we split the total partition count up across
multiple topics and limit each to a max of 5000. Each producer will only
produce to one topic and hence it's easier on them.
This is similar to a pattern that we have already seen employed by
customers with similar high partition counts.
With this change batch size …
=> tests: Use multiple topics in OMBValidationTest.test_max_partitions

src/v/features/feature_table.cc
Update to version 12 for 24.1
Fixes failing upgrade tests.
* none
=> features: Update to version 12

src/v/cloud_storage/tests/anomalies_detector_test.cc, src/v/cloud_storage/types.cc, src/v/cloud_storage/types.h, src/v/config/configuration.cc, src/v/redpanda/admin/api-doc/shadow_indexing.json, src/v/redpanda/admin/server.cc
Limit number of scrubber anomalies in memory to 100.
Limit full scrub interval to 10h.
* none
=> cloud_storage: Improve scrubber

tests/docker/ducktape-deps/flink, tests/rptest/e2e_tests/workloads/flink_table_transactions_basic.py, tests/rptest/e2e_tests/workloads/flink_workload_config.json, tests/rptest/services/flink.py, tests/rptest/tests/flink_basic_test.py
Basic produce tests and some fixes for consume basic tests.
* none
=> rptest: Basic transaction produce test

src/v/cloud_storage/remote_probe.h
These weren't being initialized and could report garbage.
* Fixes an an improper initialization of metrics related to controller snapshot uploads.
=> metrics: fix controller snapshot upload metrics

src/v/raft/group_manager.cc
set_ready() may race with group creation if it is called after a consensus instance is created, but before it is added to the _groups collection.
* Protect against a very rare scenario where after node restart, some of the partition replicas hosted on that node could not take part in leader elections.
=> r/group_manager: protect against race with set_ready()

src/v/config/configuration.cc, src/v/storage/disk_log_impl.cc, tests/rptest/tests/cluster_config_test.py
In https://github.com/redpanda-data/redpanda/pull/15996 a change was made that enabled space management and non-strict retention mode when upgrading (unlike v23.1 -> v23.2 upgrade in which the features were disabled by default). It also maintained the behavior that new clusters would have the features enabled (the same behavior as a new v23.2 cluster). Only part of this behavior is desired, so this PR reverts the behavior for strict retention setting.
A new 23.3 cluster will have the same behavior as a new 23.2 cluster
* sm=true
* strict_retention=false
An upgrade sequence 23.1, 23.2, 23.2 will have
* sm=true
* strict_retention=true
**NOTE:** this requires the same workaround that we deployed for v23.2 to make upgrade options sticky. That is, `.retention_local_strict_override` needs to be …
=> storage: don't enable non-strict retention by default

src/v/cluster/partition_manager.cc, src/v/cluster/partition_manager.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/application.cc
Introduced a watchdog that is tracking partition shutdown state. The
watchdog is intended to provide a mechanism that will ease debugging of
partition shutdown issues. The watchdog tracks state of partitions that
were requested to be stopped or removed. When there was no state update
for the time longer than the configurable threshold (by default 30
seconds) the watchdog will emit error log entry which will inform user
about the problem.
- none
=> Introduced partition shutdown watchdog timer

src/v/raft/group_manager.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16068
=> [v23.3.x] r/group_manager: protect against race with set_ready()

tests/rptest/redpanda_cloud_tests/omb_validation_test.py
Drop the assumed number of nodes from 12 to 10 in OMB validation tests as that's the default number of nodes in duck.py and also the number we want to standardize on for all HTT tests.
* none
=> rptest: use 10 nodes in OMB validation tests

src/v/raft/group_manager.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16068 
Fixes #16081
=> [v23.1.x] r/group_manager: protect against race with set_ready()

src/v/cluster/partition_probe.cc, src/v/cluster/rm_stm.cc, src/v/raft/consensus.cc, src/v/storage/probe.cc
This series adds partition label aggregation to some metrics that were missing it.
When metrics aggregation is turned on, we want to aggregate away the partition labels on most metrics: this wasn't occurring in some cases, perhaps due to oversight (this logic needs to be applied at each metrics registration site), or because it was believed that the metrics were not suitable for aggregation.
This change enable aggregation on the partition label for most metrics, leaving 3+1 unaggregated as detailed in this comment:
https://github.com/redpanda-data/core-internal/issues/677#issuecomment-1879103823
It affects only the internal `/metrics` endpoint.
Fixes #15811.
Fixes redpanda-data/core-internal#677.
* Several additional metrics will have their "partition" label aggregated away (i.e., into a …
=> Add partition aggregation to some metrics

.github/workflows/transform-sdk-release.yml, src/transform-sdk/rust/scripts/publish.py
Decouple the broker releases. Transform SDK releases will be in the
format of `transform-sdk/v0.0.0`. We can release these at any time
and all SDKs are released together.
* none
=> transform-sdk: decouple releases from broker

src/v/cluster/controller.cc, src/v/cluster/controller_backend.cc, src/v/cluster/controller_backend.h, src/v/config/configuration.cc, src/v/ssx/event.h, src/v/ssx/tests/CMakeLists.txt, src/v/ssx/tests/event_test.cc
In the future, when partitions will be assigned to shards by a node-level component (as opposed to topic table), controller backend will have to accept notifications from several sources. To support this it is more convenient to have per-ntp fibers doing reconciliation, as opposed to a single housekeeping fiber that periodically launches reconciliation for all pending ntps and waits for all reconciliation attempts to finish.
* none
=> Controller backend: reconcile each ntp in individual fibers

src/v/cluster/partition_probe.cc, src/v/cluster/rm_stm.cc, src/v/raft/consensus.cc, src/v/storage/probe.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15966
Fixes https://github.com/redpanda-data/redpanda/issues/16093
=> [v23.3.x] Add partition aggregation to some metrics

src/v/redpanda/application.cc, src/v/syschecks/syschecks.cc, src/v/syschecks/syschecks.h
If you start up Redpanda point to a data dir that doesn't exist, the error is fairly obscure: a std::system_error mentioning failed to open but no indication of _what_ we were trying to open.
This has tripped up several people, including externally (and yours truly) so let's just fix it.
* A clearer error message when the data directory does not exist or is the wrong type
=> Check that the data dir exists

src/v/resource_mgmt/memory_sampling.cc, src/v/resource_mgmt/memory_sampling.h
When we OOM we output the top-N alloc sites and a one-line backtrace.
However, sesatar-addr2line fails to recognize it because the one-line regex requires backtrace: or another suitable token in order to understand that it's a one-line backtrace.
So we add at:.
Fixes #15615.
* none
=> Add at: in Top-N alloc site output

src/v/archival/ntp_archiver_service.cc
Previously, the housekeeping jobs were started in the c-tor of the ntp_archiver. This allowed them to 'see' potentially stale manifest. To avoid this this commit forces STM sync in the 'ntp_archiver::start' and enables housekeeping jobs after that.
Fixes #14222 
* none
=> archival: Start housekeeping jobs after STM sync

tests/rptest/services/openmessaging_benchmark.py, tests/rptest/services/openmessaging_benchmark_configs.py
The OMB validator was not validating p999 even though it was specified
in the validator requirements.
There was two reasons for that:
- We were using the data from the output of the `generate_charts`
command which is incomplete and doesn't return p999 e2e latency
- This wasn't fatal because the validator logic silently failed to
validate requested validation metrics if they were not in the metrics
output
This patch fixes both by switching to actually using the `result.json`
file and further invert the validation loop such that it errors out if a
requested validation metric does not exist.
* none
=> tests: Make the OMB validator use result.json

.github/workflows/stale.yml
Following on PR #15935 
Unless there is a specific reason to use the older `v5` release (feel free to close this PR if so), we should use the latest `v9` [release](https://github.com/actions/stale/releases).
* none
=> gha: use latest action for stale

tests/rptest/tests/delete_records_test.py
- The rpk consume single record test to verifiy a given offset has the exact same timeout as the retry logic that surrounds it.
- This commit bumps the timeout so that the retry logic may actually be implemented.
- Adding additional logs for debugging visibility
Link to underlying issue: https://github.com/redpanda-data/redpanda/issues/14641
* none
=> Fix for CI Failure (Failed to make list_offsets request, unknown broker) in DeleteRecordsTest.test_delete_records_segment_deletion

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/pandaproxy/reply.h, src/v/pandaproxy/rest/proxy.cc, src/v/pandaproxy/rest/proxy.h, src/v/pandaproxy/schema_registry/service.cc, src/v/pandaproxy/schema_registry/service.h, src/v/pandaproxy/server.cc, src/v/pandaproxy/server.h, src/v/redpanda/application.cc, src/v/utils/adjustable_semaphore.h
Fixes: #14116 
Cross shard calls in SR/PP utilize an SMP resource group to limit the number of cross shard calls that
are made.  However, if the semaphore has been fully consumed, the call simply hangs.  Customers have
experienced issues where, under heavy load, SR appears to hang and not response.  Now, instead, once the
semaphore has been completely exhausted, new HTTP requests that attempt cross shard calls will be
rejected with a 500 error.
* SR/PP will now reply with a 500 error if an internal service semaphore has been completely exhausted
=> Reject PP/SR HTTP requests if cross shard semaphore has been exhausted

tests/rptest/tests/delete_records_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16078
=> [v23.3.x] Fix for CI Failure (Failed to make list_offsets request, unknown broker) in DeleteRecordsTest.test_delete_records_segment_deletion

src/v/redpanda/application.cc, src/v/resource_mgmt/CMakeLists.txt, src/v/resource_mgmt/cpu_scheduling.h, src/v/resource_mgmt/smp_groups.cc, src/v/resource_mgmt/smp_groups.h, src/v/ssx/work_queue.cc, src/v/ssx/work_queue.h, src/v/transform/api.cc, src/v/transform/api.h, src/v/transform/rpc/deps.cc, src/v/transform/rpc/deps.h, src/v/transform/rpc/service.cc, src/v/transform/tests/transform_manager_test.cc, src/v/transform/transform_manager.cc, src/v/transform/transform_manager.h
Introduce SMP and CPU scheduling groups for transforms.
The main motivation for this is to allow for internal metrics on CPU usage for the transform subsystem. While doing this change, I also see that we generally also have smp groups too, so I created one for the internal data path, where there are a few cross shard calls to produce.
* Add a dedicated CPU scheduling policy for Data Transforms
=> transform: create smp and scheduling groups

.github/workflows/build-redpanda.yml
Run mon-fri at 00:00 hrs for now; it'll be moved to BK shortly
* none
=> gha: run build-redpanda workflow once per day

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
We used the log field which doesn't exist, should be logger.
This was presumably mostly working because it is on an error type.
This bug was found through typing.
* none
=> rptest: bad field use in test_consume_miss_cache

tests/rptest/services/openmessaging_benchmark_configs.py
The predicates in OMBSampleConfigurations are static methods but are not marked as such.
This bug was detected by typing.
* none
=> OMBSampleConfigurations predicates are static

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
We comared a list to a float, which will fail at runtime. Presumably we don't hit this case when the test passes but we can hit it for some failures.
This bug was found through typing.
* none
=> rptest: invalid comparison in test_max_connections

src/v/cluster/partition_probe.cc, src/v/cluster/partition_probe.h, src/v/kafka/server/handlers/fetch.cc, tests/rptest/services/redpanda.py, tests/rptest/tests/follower_fetching_test.py, tests/rptest/tests/raft_recovery_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15799
Fixes: https://github.com/redpanda-data/redpanda/issues/15829,
=> [v23.2.x] Added metric representing bytes read from follower

tests/docker/ducktape-deps/flink
For ARM64 architecture JAVA_HOME env var is empty for some reason.
Flink installation expects it. Safety wise, no checking of arch, and extracting JAVA_HOME from java app itself if target var is empty
Fixes: redpanda-data/devprod#1015
* none
=> ci: Fix flink install on ARM64

src/v/kafka/server/replicated_partition.cc
When consumer is requesting a fetch from the broker being a follower for given replica the fetch offset validation logic changes comparing to the validation on a leader. The out of range error should only be returned if an offset is not available locally and it is not known to be committed. That was not the case with the current code. The current code returned out of range error every time the offset was not committed on leader. This lead to many not necessary errors returned and resulted in consumer offsets being reset.
- fixed incorrect fetch offset validation
=> k/replicated_partition: fixed fetch offset validation for follower fetching

src/v/archival/ntp_archiver_service.cc
Previously, if the spillover was enable we weren running normal GC during the housekeeping run. Normal housekeeping is responsible for removing segments evicted due to retention (which is not happening if spillover region is not empty). But it also removes replaced segments. So essentially, we have to run both types of GC on every spillover housekeeping run.
* Fix tiered-storage housekeeping problem that may cause replaced segments to pile up if the spillover is enabled.
=> archival: Delete replaced segments during spillover GC

tests/rptest/clients/rpk.py, tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/services/admin.py, tests/rptest/services/kgo_verifier_services.py, tests/rptest/services/openmessaging_benchmark.py, tests/rptest/services/redpanda.py, tests/rptest/tests/prealloc_nodes.py, tests/rptest/tests/redpanda_test.py
Type more parts of rptest, concentrating on getting high_throughput_test to type fully at pyright "basic" setting.
After this change it types fully with some additional ducktape stubbing (not part of this change).
This change is largely pure typing (which can't affect runtime) though there are a handful of small runtime changes to assist in the typing, e.g., asserts that properties are not None immediately prior to using them which would otherwise be a typing failure. This only changes a crash at use to a crash immediately before at the assert.
* none
=> rptest: more typing 2

src/v/rpc/netbuf.cc, src/v/rpc/transport.cc
It is possible that in an active RPC client connection, `correlation_id` (which is uint32_t) will overflow  - at, say, 5k req/s (high, but not unreasonable value) overflow happens after 10 days. This isn't particularly bad, because it will just wrap around to 0, but we treat `correlation_id=0` as an invalid value and throw an exception. Because this exception gets thrown from an unexpected place, the connection send loop stalls and the connection becomes unusable afterwards.
Remove this check as it doesn't add much value, and also ensure that connections get shut down after these unexpected exceptions.
* Fix internal RPC client connection stall after more than 2^32 requests are sent.
=> rpc: fix correlation_id overflow

tests/rptest/scale_tests/audit_log_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16125
Fixes: https://github.com/redpanda-data/redpanda/issues/16130,
=> [v23.3.x] rptest/scale_test: Remove p50 check in audit test

tests/rptest/redpanda_cloud_tests/omb_validation_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16028
=> [v23.3.x] rptest: use 10 nodes in OMB validation tests

src/v/archival/ntp_archiver_service.cc
Previously, if the spillover was enable we weren running normal GC during the housekeeping run. Normal housekeeping is responsible for removing segments evicted due to retention (which is not happening if spillover region is not empty). But it also removes replaced segments. So essentially, we have to run both types of GC on every spillover housekeeping run.
* Fix tiered-storage housekeeping problem that may cause replaced segments to pile up if the spillover is enabled.
=> [v23.3.x] archival: Delete replaced segments during spillover GC

src/v/archival/ntp_archiver_service.cc
Previously, if the spillover was enable we weren running normal GC during the housekeeping run. Normal housekeeping is responsible for removing segments evicted due to retention (which is not happening if spillover region is not empty). But it also removes replaced segments. So essentially, we have to run both types of GC on every spillover housekeeping run.
* Fix tiered-storage housekeeping problem that may cause replaced segments to pile up if the spillover is enabled.
=> [v23.2.x] archival: Delete replaced segments during spillover GC

src/v/transform/api.cc, src/v/transform/transform_logger.h, src/v/wasm/api.h, src/v/wasm/cache.cc, src/v/wasm/cache.h, src/v/wasm/fwd.h, src/v/wasm/tests/wasi_logs_test.cc, src/v/wasm/tests/wasm_cache_test.cc, src/v/wasm/tests/wasm_fixture.cc, src/v/wasm/tests/wasm_logger.h, src/v/wasm/tests/wasm_transform_bench.cc, src/v/wasm/wasi.cc, src/v/wasm/wasi.h, src/v/wasm/wasmtime.cc
This PR introduces `wasm::logger`, which is intended to subsume `ss::logger` for transform logging purposes. 
Closes https://github.com/redpanda-data/core-internal/issues/997
* none
=> Introduce `wasm::logger`

src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/partition_manifest.h, src/v/cluster/archival_metadata_stm.cc, src/v/cluster/archival_metadata_stm.h
Observed a large 1 to 2 MB allocation due to 50K plus segments in the replaced segments field of the manifest.
* Fix large allocation in partition manifest.
=> cloud_storage: use fragvec to hold replaced segments

src/v/kafka/server/replicated_partition.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16146
=> [v23.3.x] k/replicated_partition: fixed fetch offset validation for follower fetching

src/v/cluster/log_eviction_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15945
Fixes: #15985
=> [v23.3.x] c/log_eviction_stm: do not request snapshot if already progressed

src/v/resource_mgmt/memory_sampling.cc, src/v/resource_mgmt/memory_sampling.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/15616
Fixes: https://github.com/redpanda-data/redpanda/issues/16102,
=> [v23.2.x] Add at: in Top-N alloc site output

tests/rptest/services/openmessaging_benchmark.py
generate_charts.py takes the min of the `publishLatencyMin` and `endToEndLatencyMin` metrics in `result.json`. See https://github.com/redpanda-data/openmessaging-benchmark/blob/main/bin/generate_charts.py#L300 . Our validators for OMB results expect a single value for these metrics as well and not the list of values present in `result.json`. This PR changes our metrics validator to match this behavior and makes `publishLatencyMin` and `endToEndLatencyMin`  a single value that is the min of their lists in `result.json`
* none
=> Change metrics to match generate_charts.py

src/go/rpk/pkg/cli/transform/template/rust/main.rustsrc
The wrong Error import was used, and we need to specify the error type
as we don't import anyhow for users.
* Fix the starter code for Rust projects in `rpk transform init`
=> rpk/transform/init: fix rust template

src/v/redpanda/application.cc, src/v/redpanda/application.h, src/v/resource_mgmt/scheduling_groups_probe.h
Currently we only report the breakdown by scheduling group for core 0, it's probably useful for all cores.
* Report runtime public metrics by task queue for all cores, not just core 0
=> scheduling_groups: report cpu usage for all cores

src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/partition_manifest.h, src/v/cluster/archival_metadata_stm.cc, src/v/cluster/archival_metadata_stm.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16160 
https://github.com/redpanda-data/redpanda/issues/16187
=> [v23.2.x] cloud_storage: use fragvec to hold replaced segments

src/v/archival/tests/ntp_archiver_test.cc, src/v/config/configuration.cc, tests/rptest/perf/ts_read_openmessaging_test.py, tests/rptest/perf/ts_write_openmessaging_test.py, tests/rptest/scale_tests/tiered_storage_single_partition_test.py, tests/rptest/services/redpanda.py, tests/rptest/tests/archive_retention_test.py, tests/rptest/tests/cloud_retention_test.py, tests/rptest/tests/cloud_storage_scrubber_test.py, tests/rptest/tests/cloud_storage_timing_stress_test.py, tests/rptest/tests/e2e_shadow_indexing_test.py, tests/rptest/tests/offset_for_leader_epoch_archival_test.py, tests/rptest/tests/read_replica_e2e_test.py, tests/rptest/tests/tiered_storage_model.py, tests/rptest/tests/tiered_storage_model_test.py, tests/rptest/tests/timequery_test.py, tests/rptest/tests/topic_delete_test.py
this enable splitting the partition_manifest into spillovers once it reaches 2*cloud_storage_spillover_manifest_size
Fixes https://github.com/redpanda-data/core-internal/issues/1012
* spillover manifests are enabled by default for clusters that did not explicit set a value or null
=> config/configuration: set cloud_storage_spillover_manifest_size

src/v/archival/tests/ntp_archiver_test.cc, src/v/config/configuration.cc, tests/rptest/perf/ts_read_openmessaging_test.py, tests/rptest/perf/ts_write_openmessaging_test.py, tests/rptest/scale_tests/tiered_storage_single_partition_test.py, tests/rptest/services/redpanda.py, tests/rptest/tests/archive_retention_test.py, tests/rptest/tests/cloud_retention_test.py, tests/rptest/tests/cloud_storage_scrubber_test.py, tests/rptest/tests/cloud_storage_timing_stress_test.py, tests/rptest/tests/e2e_shadow_indexing_test.py, tests/rptest/tests/offset_for_leader_epoch_archival_test.py, tests/rptest/tests/read_replica_e2e_test.py, tests/rptest/tests/tiered_storage_model.py, tests/rptest/tests/tiered_storage_model_test.py, tests/rptest/tests/timequery_test.py, tests/rptest/tests/topic_delete_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16172
=> [v23.3.x] config/configuration: set cloud_storage_spillover_manifest_size

tests/rptest/services/redpanda_cloud.py
If our health check fails, expose the reason in the exception message.
Also, downgrade the logging on the success path of the health check to info from warning.
* none
=> rptest: expose health check reason

src/v/transform/api.cc, src/v/transform/transform_logger.h, src/v/wasm/api.h, src/v/wasm/cache.cc, src/v/wasm/cache.h, src/v/wasm/fwd.h, src/v/wasm/tests/wasi_logs_test.cc, src/v/wasm/tests/wasm_cache_test.cc, src/v/wasm/tests/wasm_fixture.cc, src/v/wasm/tests/wasm_logger.h, src/v/wasm/tests/wasm_transform_bench.cc, src/v/wasm/wasi.cc, src/v/wasm/wasi.h, src/v/wasm/wasmtime.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16153
=> [v23.3.x] Introduce wasm::logger

tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/redpanda_cloud_tests/omb_validation_test.py, tests/rptest/services/redpanda.py
related issue: https://github.com/redpanda-data/cloudv2/issues/11563
Have `OMBValidationTest` and `HighThroughputTest` clean cluster in `tearDown()` and `startup()` by deleting topics that may have been leftover from a test case. The `clean_cluster()` method can be added to later to clean more things we want to ensure is gone before the next test case runs.
Since `clean_cluster()` simply deletes all topics, it should only be called if there are no other tests running at the same time expecting topics to be there.
example run:
```console
ducktape \ 
--debug \ 
--globals=/home/ubuntu/redpanda/tests/globals.json \ 
--cluster=ducktape.cluster.json.JsonCluster \ 
--cluster-file=/home/ubuntu/redpanda/tests/cluster.json \   …
```
=> rptest: clean cloudv2 cluster topics in `tearDown()`

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
Fixes https://github.com/redpanda-data/core-internal/issues/986
Reduce to a range between 1K to 16K which is what we usually want to test within.
example test run:
```console
ducktape \ 
--debug \ 
--globals=/home/ubuntu/redpanda/tests/globals.json \ 
--cluster=ducktape.cluster.json.JsonCluster \ 
--cluster-file=/home/ubuntu/redpanda/tests/cluster.json \  
tests/rptest/redpanda_cloud_tests/high_throughput_test.py::HighThroughputTest.test_throughput_simple
```
output:
```
test_id:    rptest.redpanda_cloud_tests.high_throughput_test.HighThroughputTest.test_throughput_simple
run time:   1 minute 5.736 seconds
-----------------------------------------------------------------------
=====================================================
SESSION …
```
=> rptest: reduce HighThroughputTests.msg_size

src/v/io/page_set.h, src/v/io/persistence.cc, src/v/io/persistence.h, src/v/io/tests/persistence_test.cc
io: add fault injection helpers to persistence layer
* none
=> io: add fault injection helpers to persistence layer

src/v/cluster/persisted_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15145 
Fixes: https://github.com/redpanda-data/redpanda/issues/15198
=> [v23.2.x] Fixed skipping application of raft snapshot

src/v/cluster/archival_metadata_stm.cc
Apply feedback from PR review.
* none
=> archival: apply PR feedback

src/v/cluster/distributed_kv_stm.h, src/v/model/transform.h, src/v/redpanda/admin/api-doc/transform.json, src/v/redpanda/admin/server.cc, src/v/redpanda/admin/server.h, src/v/redpanda/admin/transform.cc, src/v/redpanda/admin/util.cc, src/v/redpanda/admin/util.h, src/v/transform/api.cc, src/v/transform/api.h, src/v/transform/rpc/client.cc, src/v/transform/rpc/client.h, src/v/transform/rpc/deps.cc, src/v/transform/rpc/deps.h, src/v/transform/rpc/rpc.json, src/v/transform/rpc/serde.cc, src/v/transform/rpc/serde.h, src/v/transform/rpc/service.cc, src/v/transform/rpc/service.h, src/v/transform/rpc/tests/transform_rpc_test.cc, tests/rptest/services/admin.py, tests/rptest/tests/data_transforms_test.py
We need to cleanup committed offsets when transforms are deleted. At the moment we do not do that. In an effort to do that and ensure we have tests for this, I've broken up that change into two parts, this one, which exposes the ability to view committed offsets, and another to do the cleanup. We'll use the infrastructure from this PR to enable the tests for ensuring that the offsets are cleaned up.
* Add an internal debugging endpoint to see the committed progress of data transforms.
=> transform: list committed offsets

tests/rptest/redpanda_cloud_tests/omb_validation_test.py, tests/rptest/services/openmessaging_benchmark.py
Bump latency multiplier (fudge factor) for `test_max_partitions()` from 1.5 to 2.0 and log warning if latency is above expected max latency, i.e. fudge factor 1.0.
This is a workaround for addressing issue #15459
example run:
```console
ducktape \ 
--debug \ 
--globals=/home/ubuntu/redpanda/tests/globals.json \ 
--cluster=ducktape.cluster.json.JsonCluster \ 
--cluster-file=/home/ubuntu/redpanda/tests/cluster.json \  
tests/rptest/redpanda_cloud_tests/omb_validation_test.py::OMBValidationTest.test_max_partitions
```
output:
```
[INFO  - 2024-01-18 20:53:10,924 - omb_validation_test - test_max_partitions - lineno:390]: latency_metrics: {'aggregatedEndToEndLatency50pct': 26.589, 'aggregatedEndToEndLatency75pct': 32.568, 'aggregatedEndToEndLatency99pct': …
```
=> rptest: bump multiplier to 2.0 for `test_max_partitions()`

tests/rptest/services/redpanda.py
This will cause a ducktape test to fail if an allocation of 400KiB or more occurs during it. 
* none
=> Add oversized allocation to bad log lines

tests/docker/ducktape-deps/flink
Since the old version is not longer available on Apache servers we must upgrade to v1.18.1.
- none
=> tests: updated flink to 1.18.1

tests/rptest/tests/tiered_storage_model_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16226
Fixes #16245
=> [v23.3.x] tests/rptest/tests/tiered_storage_model_test: ignore

tests/rptest/clients/kubectl.py, tests/rptest/tests/services_self_test.py
Capture kubectl stderr and ensure stdout and stderr are logged when a command fails, since otherwise you'll just have the return code to go on.
* none
=> rptest: log kubectl errors

src/v/redpanda/admin/server.cc
fetching partition information via health report API is heavy and brokers API doesn't really use it. This patch avoids fetching that information.
* none
=> admin api: skip partition info in /brokers end point

.github/workflows/scripts/backport-command/create_pr.sh
=> gha: don't mark backports as drafts

src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_types.cc, src/v/cluster/health_monitor_types.h, src/v/cluster/tests/health_monitor_test.cc, src/v/cluster/tests/partition_balancer_simulator_test.cc, src/v/cluster/tests/randoms.h, src/v/cluster/tests/serialization_rt_test.cc, src/v/compat/cluster_json.h, src/v/compat/json.h, src/v/json/json.h, src/v/utils/to_string.h
With large number of topics that contain a small amount of partitions we
may end up wasting a lot of memory using the default `ss::chunked_fifo`
chunk size of 128.
Change the chunk size of `partition_status` `chunked_fifo` collection to
8 to minimize a waste with large number of small topics.
- smaller memory footprint when using with large number of topics with small partition count
=> Changed the `partition_status` `chunked_fifo` chunk size to `8`

src/v/cluster/partition_leaders_table.cc, src/v/cluster/partition_leaders_table.h, src/v/cluster/tests/metadata_dissemination_test.cc, src/v/cluster/topic_updates_dispatcher.cc, src/v/cluster/topic_updates_dispatcher.h, src/v/kafka/server/handlers/metadata.cc, tests/rptest/tests/consumer_group_recovery_tool_test.py, tests/rptest/tests/partition_force_reconfiguration_test.py, tests/rptest/tests/upgrade_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15678
Backport of PR https://github.com/redpanda-data/redpanda/pull/15981
Fixes: #16237
=> [v23.2.x] c/topics_dispatcher: do not guesstimate leader ids

tests/docker/ducktape-deps/flink
Backport of PR https://github.com/redpanda-data/redpanda/pull/16242
=> [v23.3.x] tests: updated flink to 1.18.1

tests/rptest/tests/consumer_group_test.py
- Its been observed many times in the ConsumerGroupTests that an unbalanced consumer consumes all messages and and some type of assertion that expects at least all members to consume some records fails by way of timing out.
* none
=> rptest: Wait for the group to be in a stable state before starting tests

tests/docker/ducktape-deps/flink
Current URL throws a 404 and 1.18.0 is not hosted anywhere. Also switching the download URL as per
https://github.com/apache/flink-docker/pull/170
* none
=> ducktape: fix flink URL 404

src/v/cluster/partition_leaders_table.cc, src/v/cluster/partition_leaders_table.h, src/v/cluster/tests/metadata_dissemination_test.cc, src/v/cluster/topic_updates_dispatcher.cc, src/v/cluster/topic_updates_dispatcher.h, src/v/kafka/server/handlers/metadata.cc, tests/rptest/tests/consumer_group_recovery_tool_test.py, tests/rptest/tests/partition_force_reconfiguration_test.py, tests/rptest/tests/upgrade_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/15678
Fixes: https://github.com/redpanda-data/redpanda/issues/16235,
=> [v23.3.x] c/topics_dispatcher: do not guesstimate leader ids

src/v/cluster/partition_manager.cc, src/v/cluster/partition_manager.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/application.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16067
Fixes: https://github.com/redpanda-data/redpanda/issues/16088
=> [v23.3.x] Introduced partition shutdown watchdog timer

src/v/cluster/partition_probe.cc, tests/rptest/services/redpanda.py, tests/rptest/tests/read_replica_e2e_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16263
Fixes: https://github.com/redpanda-data/redpanda/issues/16271,
=> [v23.3.x] metrics: fix kafka_max_offset on read replicas

tests/rptest/tests/consumer_group_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16127
=> [v23.3.x] rptest: Wait for the group to be in a stable state before starting tests

src/v/cluster/partition_probe.cc, tests/rptest/services/redpanda.py, tests/rptest/tests/read_replica_e2e_test.py
Backport of https://github.com/redpanda-data/redpanda/pull/16263
CONFLICT:
- removed the ducktape changes required for the cloud service since that infra isn't in v23.2.x
Fixes https://github.com/redpanda-data/redpanda/issues/16274
* Fixes a bug that would previously cause read replicas to report the wrong value for the `redpand_kafka_max_offset` metric.
=> [v23.2.x] metrics: fix kafka_max_offset on read replicas

src/v/cloud_storage/remote_segment.cc
Most places were already holding the gate external to calls of hydrate() with the exception of aborted_transactions(). This commit fixes this by:
- holding the gate during aborted_transactions()
- making hydrate() hold the gate for the duration of its future
(cherry picked from commit 0aefe35edc2d4a693ed23135bc957d01ff1d6319)
Fixes https://github.com/redpanda-data/redpanda/issues/15708
* none
* none
=> [v23.2.x] cloud_storage: hold gate in hydration

src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_types.cc, src/v/cluster/health_monitor_types.h, src/v/cluster/tests/health_monitor_test.cc, src/v/cluster/tests/partition_balancer_simulator_test.cc, src/v/cluster/tests/randoms.h, src/v/cluster/tests/serialization_rt_test.cc, src/v/compat/cluster_json.h, src/v/compat/json.h, src/v/json/json.h, src/v/redpanda/admin_server.cc, src/v/serde/serde.h, src/v/utils/to_string.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16247
=> [v23.2.x] Changed the `partition_status` `chunked_fifo` chunk size to `8`

src/v/config/property.h, src/v/redpanda/admin/api-doc/debug.json, src/v/redpanda/admin/debug.cc, src/v/resource_mgmt/cpu_profiler.cc, src/v/resource_mgmt/cpu_profiler.h, src/v/resource_mgmt/tests/cpu_profiler_test.cc, tests/rptest/services/admin.py, tests/rptest/tests/cpu_profiler_admin_api_test.py
This PR adds the `wait_ms` parameter to the admin API for the CPU profiler. When this parameter is set the API will enable the profiler, wait until `wait_ms` has passed, disabled the profiler, then return the samples collected during that period. 
Fixes #14069
* Adds `wait_ms` parameter to CPU profiler admin API. The API will wait for `wait_ms` milliseconds then return the profile samples collected during that period of time.
=> Add enable override to the CPU profiler API

tests/rptest/infinite_retention/infinite_retention_test.py, tests/rptest/scale_tests/tiered_storage_single_partition_test.py, tests/rptest/services/admin.py, tests/rptest/services/redpanda.py, tests/rptest/tests/tiered_storage_model_test.py, tests/rptest/tests/timequery_test.py, tests/rptest/tests/upgrade_test.py
adds `cloud_storage_spillover_manifest_size`: None when a test sets `cloud_storage_spillover_manifest_max_segments`.
`cloud_storage_spillover_manifest_size` takes precedence over the `cloud_storage_spillover_manifest_max_segments` variant https://github.com/redpanda-data/redpanda/blob/cc6bae525e5acdc24397f266876e2d5511a9fe3a/src/v/archival/ntp_archiver_service.cc#L2471-L2483
Now that the *size variant has a default value, the tests were failing because they were expecting a fast spillover while Redpanda behaves in a more "production mode" manner.
additionally, revert an old change in `RedpandaService.set_cluster_config()`: {prop_name: None} values were interpreted as properties to remove from the cluster config, but that reverts the value to the default value. the correct way to set an …
=> "enable by default spillover manifest" testing followups

.github/labeler.yml
When working on transform or wasm subsystems, I would like to see those
on my GitHub project, which auto adding this label allow me to automate
that process.
* none
=> labeler: apply wasm label for Redpanda subsystems

src/go/rpk/pkg/cli/transform/template/rust/main.rustsrc, src/transform-sdk/rust/Cargo.lock, src/transform-sdk/rust/Cargo.toml, src/transform-sdk/rust/core-sys/src/lib.rs, src/transform-sdk/rust/core-sys/src/serde.rs, src/transform-sdk/rust/core-types/src/lib.rs, src/transform-sdk/rust/examples/identity.rs, src/transform-sdk/rust/examples/jaq/src/main.rs, src/transform-sdk/rust/examples/json2avro/src/main.rs, src/transform-sdk/rust/examples/transcoder.rs, src/transform-sdk/rust/examples/validation_filter.rs, src/transform-sdk/rust/src/lib.rs
We only need to borrow the output record. To do that we make the writer
take `Into<BorrowedRecord<'_>>`, so that it can take any type of record
for transforms (we can now do no copy transforms!).
Since `Into<_>` is a trait, we can't have a monomorphic trait take a
monomorphic trait as a function argument (see
https://doc.rust-lang.org/reference/items/traits.html#object-safety). So
we wrap our current trait in a struct that handles resolving the trait
argument to the concrete type our write function will take.
* none
=> transform-sdk/rust: borrow output record

src/v/model/transform.h, src/v/transform/CMakeLists.txt, src/v/transform/logging/CMakeLists.txt, src/v/transform/logging/event.cc, src/v/transform/logging/event.h, src/v/transform/logging/tests/CMakeLists.txt, src/v/transform/logging/tests/model_test.cc, src/v/transform/logging/tests/utils.cc, src/v/transform/logging/tests/utils.h
This PR introduces `transform_log_event` for in-memory storage of transform logs.
Also Includes RapidJSON serialization for a mapping of the OpenTelemetry
[logging format](https://opentelemetry.io/docs/specs/otel/logs/data-model/) and some internal helper types to that end.
Example JSON:
```json5
{
"body": {
"stringValue": "my message goes here...",
},
"timeUnixNano": 1705462202516000000,
"severityNumber": 9, // 9 for stdout, 13 for stderr
"attributes": [
{"key": "node", "value": {"intValue": 1}},
{"key": "transform_name", "value": {"stringValue": "<xform name>"}}
]
}
```
This will be the structure of log event records, as stored on the `transform_logs` redpanda topic.
Closes https://github.com/redpanda-data/core-internal/issues/999
* none
=> Transform logging data model

src/go/rpk/pkg/cli/transform/template/rust/main.rustsrc, src/transform-sdk/rust/Cargo.lock, src/transform-sdk/rust/Cargo.toml, src/transform-sdk/rust/core-sys/src/lib.rs, src/transform-sdk/rust/core-sys/src/serde.rs, src/transform-sdk/rust/core-types/src/lib.rs, src/transform-sdk/rust/examples/identity.rs, src/transform-sdk/rust/examples/jaq/src/main.rs, src/transform-sdk/rust/examples/json2avro/src/main.rs, src/transform-sdk/rust/examples/transcoder.rs, src/transform-sdk/rust/examples/validation_filter.rs, src/transform-sdk/rust/src/lib.rs
Backport of PR https://github.com/redpanda-data/redpanda/pull/16210
=> [v23.3.x] transform-sdk/rust: borrow output record

src/v/cloud_storage/async_manifest_view.cc, src/v/cloud_storage/remote_partition.cc
Consider this trace:
A list_offsets request with a timestamp hits the spillover region, but at the same time, retention happens, and the first few spillover manifests become eligible for GC.
In this case, the timequery will still start from the first spillover manifest, but if it hits one of the collectible manifests, this will be logged as an error, and no result will be returned.
The kafka client is okay with this result, but the ERROR line will trigger the tests.
In theory, we could restrict the search space (like it was attempted [here](https://github.com/redpanda-data/redpanda/pull/16288) ), but we are dealing with suspension points in an unstable moment. We could hit various edge cases (what if retention hits the whole spillover region?)
So this pr recognize this category of …
=> demote ERROR message to DEBUG for timequerys at the edge of spillover retention

tests/rptest/infinite_retention/infinite_retention_test.py, tests/rptest/scale_tests/tiered_storage_single_partition_test.py, tests/rptest/services/admin.py, tests/rptest/services/redpanda.py, tests/rptest/tests/tiered_storage_model_test.py, tests/rptest/tests/timequery_test.py, tests/rptest/tests/upgrade_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16248
Fixes https://github.com/redpanda-data/redpanda/issues/16291
=> [v23.3.x] "enable by default spillover manifest" testing followups

tests/rptest/scale_tests/cloud_storage_compaction_test.py
There were a couple issues with this test:
- we were previously using the wrong cluster's metrics to determine whether the read replica cluster was uploading anything
- the read replica cluster _was_ uploading (or trying to) since the consumer offsets topic was created with the default tiered storage configuration for that cluster
Fixes #16008
* none
=> cloud_storage_compaction_test: a couple test fixes

src/transform-sdk/rust/core-types/src/lib.rs
=> transform-sdk/rust: update rustdocs

src/transform-sdk/rust/core-types/src/lib.rs
Backport of PR https://github.com/redpanda-data/redpanda/pull/16314
=> [v23.3.x] transform-sdk/rust: update rustdocs

tests/docker/Dockerfile, tests/setup.py
e09c68a moved installation of the confluent-kafka package to the ducktape Dockerfile to avoid an unfortunate config in the prebuilt wheels from PyPi.
Apparently, `--no-binary` works equally well to specify individual
dependencies in a normal setuptools build. This has the added benefit
that the dependency is picked up by dev environments outside docker.
Fixes https://github.com/redpanda-data/core-internal/issues/1019
* none
=> dt/deps: Use setuptools for confluent-kafka source build

src/v/resource_mgmt/tests/CMakeLists.txt
This test is consistenly failing by hanging in debug mode for an unknown reason. Let's disable until we track it down.
Related: https://github.com/redpanda-data/redpanda/issues/16308
* none
=> resource_mgmt: disable flaky test

src/v/cluster/partition_manager.cc, src/v/cluster/partition_manager.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/application.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16067
=> [v23.2.x] Introduced partition shutdown watchdog timer

src/v/archival/probe.cc
This PR adds the partition label to the aggregated labels in `ntp_level_probe`. This is done to bring the behavior of `ntp_level_probe` in line with other NTP metrics in TS and storage. 
* Aggregates partitions in some cloud storage metrics when the `aggregate_metrics` cluster config is set to true.
=> Aggregate partition label in `ntp_level_probe`

src/v/cluster/partition_manager.cc, src/v/rpc/rpc_server.cc, src/v/rpc/transport.cc
Added missing `vlog` macros in places where logger was used without it. This way we will have log entry format consistent. 
- none
=> Wrapped logging with `vlog` macro in places that missed it

src/v/cloud_storage/async_manifest_view.cc, src/v/cloud_storage/remote_partition.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16302
Fixes #16306
=> [v23.3.x] demote ERROR message to DEBUG for timequerys at the edge of spillover retention

src/go/rpk/pkg/config/params.go, tests/rptest/clients/rpk.py, tests/rptest/tests/rpk_acl_test.py
We were giving priority to old back compatibility
flags (like --user, --password) over the new
configuration (-X) flags. So if a user used both,
the old ones got priority.
This introduced a bug in rpk acl user create
where we have a flag that collides with an old
flag name: --password.
Fixes #16251 
* rpk: fixed a bug where the `--password` flag could not be used along with the new configuration flag `-X pass` in clusters where basic authentication was enabled.
=> rpk: fix mixed use of backcompat flags with -X

src/go/rpk/pkg/config/params.go, tests/rptest/clients/rpk.py, tests/rptest/tests/rpk_acl_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16278
Fixes: https://github.com/redpanda-data/redpanda/issues/16350,
=> [v23.3.x] rpk: fix mixed use of backcompat flags with -X

tests/rptest/e2e_tests/workloads/flink_table_transactions_basic.py, tests/rptest/services/flink.py, tests/rptest/tests/flink_basic_test.py
Since Table API consumer waits for the index indefinitely, update validation to
- first wait for data file to be created
- then wait for data files to have proper index value
This PR also fixes logs copy for docker envs by properly getting hostname
Fixes: redpanda-data/devprod#1031
* none
=> rptest: Refactor consumer validation and tune table idle settings

src/v/container/include/container/zip.h, src/v/model/record.h, src/v/model/tests/transform_test.cc, src/v/model/transform.cc, src/v/model/transform.h, src/v/transform/tests/CMakeLists.txt, src/v/transform/tests/test_fixture.cc, src/v/transform/tests/test_fixture.h, src/v/transform/tests/transfer_queue_test.cc, src/v/transform/tests/transform_processor_test.cc, src/v/transform/transfer_queue.h, src/v/transform/transform_processor.cc, src/v/transform/transform_processor.h, src/v/wasm/api.h, src/v/wasm/cache.cc, src/v/wasm/tests/wasm_cache_test.cc, src/v/wasm/tests/wasm_fixture.cc, src/v/wasm/tests/wasm_transform_bench.cc, src/v/wasm/transform_module.cc, src/v/wasm/transform_module.h, src/v/wasm/wasmtime.cc
Instead of buffering in the wasm layer we will have a callback for when data is emitted from the VM.
This will allow us to account for memory easier and will allow us to recieved additional data in the callback like which topic it should be output to.
Additional benefits/bug fixes:
* Fixes timing of execution for a single transform.
* Will allow us to batch independant of the transform, which will be important in the future as we need to handle output batches being over the size limit.
* none
=> wasm: transform callback

tests/rptest/tests/consumer_group_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16127
=> [v23.2.x] rptest: Wait for the group to be in a stable state before starting tests

tests/rptest/redpanda_cloud_tests/config_profile_verify_test.py, tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/redpanda_cloud_tests/observe_test.py, tests/rptest/redpanda_cloud_tests/omb_validation_test.py, tests/rptest/services/cluster.py, tests/rptest/services/openmessaging_benchmark.py, tests/rptest/services/redpanda.py, tests/rptest/tests/redpanda_cloud_test.py, tests/rptest/tests/redpanda_test.py, tests/rptest/tests/services_self_test.py, tests/rptest/utils/test_mixins.py
This change changes a bit the inheritance structure of the
RedpandaService tree, and introduces the RedpandaCloudTest.
On the service side, we split RedpandaServiceCloud out so that it is
not a subclass of Service (as it does not use Service nodes nor have
a typical Service lifecycle). It shares some common interface with
RedpandaService but this is currently much smaller than the existing
RedpandaServiceBase.
RedpandaCloudTest is the base class for tests which run in the cloud,
analagous to RedpandaTest for tests which run in vanilla environments.
It automatically creates a RedpandaServiceCloud as the .redpanda
property, giving you type safe access to only the methods which make
sense in the cloud.
Issue https://github.com/redpanda-data/core-internal/issues/1002.
* none
=> Change cloud test hierarchy, introduce cloud test base

src/go/rpk/pkg/cli/cluster/health.go
--exit-when-healthy flag only makes sense with the --watch flag, so we enable now --watch if --exit-when-healthy is set.
Fixes #15818
* rpk cluster health: now `--exit-when-healthy` enables `--watch` when provided.
=> rpk: improve --exit-when-healthy in cluster health

tests/rptest/tests/rpk_tuner_test.py
The test failure root cause is that the env `CDT_CLOUD_PROVIDER` is no longer present in the image that runs the CDT tests and this was used to determine an expected output. 
This PR introduces a better and more future-proof method of getting the provider.
Work in progress, I'll update once it's done.
Fixes #15215 
* none
=> CDT: fix `rpk tune list` test in GCP.

tests/rptest/tests/cloud_retention_test.py
Fixes #15893
The test has race condition. It starts consumer before all data is produced and before retention kicks in. The original intention was to let the consumer validate the data after retention. Basically, to check that the data is readable. But because of that the consumer were reading data that was removed by retention. It was racing with the producer. Largely simplifed version of what was happening there. 
* The producer produces offsets in range [0...1000]. 
* The retention removes offsets in range [0...500).
* The consumer is started concurrently with the producer with the expectation that it will consume offsets in range [500...1000]. We're validating the number of messages consumed.
* The consumer actually manages to consume offsets in range [0...600]. So the check based on …
=> rptest: Fix race condition in CloudRetentionTest

src/v/model/transform.h, src/v/transform/CMakeLists.txt, src/v/transform/logging/CMakeLists.txt, src/v/transform/logging/event.cc, src/v/transform/logging/event.h, src/v/transform/logging/tests/CMakeLists.txt, src/v/transform/logging/tests/model_test.cc, src/v/transform/logging/tests/utils.cc, src/v/transform/logging/tests/utils.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16190
=> [v23.3.x] Transform logging data model

tests/rptest/e2e_tests/flink_scale_test.py, tests/rptest/e2e_tests/workloads/flink_transactions_scale.py, tests/rptest/services/flink.py, tests/rptest/tests/flink_basic_test.py
Implementation of test and workload that can be scaled to any number of tasks and jobs inside flink with no job overhead while running it, comparing to Table API.
Java version of similar workload is [here](https://github.com/redpanda-data/flink-repro/blob/main/src/main/java/com/redpanda/flink/Job.java).
* none
=> rptest: Transaction workload with scaling in mind

src/v/kafka/server/tests/fetch_plan_bench.cc, src/v/kafka/server/tests/fetch_test.cc, src/v/redpanda/tests/fixture.h
=> Make the request context fixture code work with produce requests

tests/rptest/tests/e2e_shadow_indexing_test.py
Increase the throughput of the TS and increase the time limit to avoid timeout.
Fixes #16379
* none
=> rptest: Fix throttling e2e test

src/v/archival/ntp_archiver_service.cc, src/v/cloud_storage_clients/client_pool.cc
_self_config_barrier is a semaphore used as a barrier for the self config step.
at shutdown_connections/stop it's broken (like it's done for _cvar the condition_variable), so it's not useful to bubble up the broken_named_semaphore exception.
the code after this will convert it to a gate_closed_exception
see https://github.com/redpanda-data/redpanda/pull/12632/files#r1293657997
This removes some failures from https://github.com/redpanda-data/redpanda/issues/15150
happening because this ERROR line appearing in the log
```
ERROR 2024-01-30 09:22:56,880 [shard 2:au  ] cloud_storage - [fiber76~122|0|29632ms] - remote.cc:1243 - Failed to delete keys: Semaphore broken: self_config_barrier
```
* none
=> cloud_storage_clients/client_pool: handle broken _self_config_barrier

tests/rptest/tests/rpk_tuner_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16353
Fixes: https://github.com/redpanda-data/redpanda/issues/16365,
=> [v23.3.x] CDT: fix `rpk tune list` test in GCP.

src/go/rpk/pkg/cli/transform/build.go
Both Rust + Tinygo use LLVM toolchains, enable the autovectorizer in
clang to generate SIMD instructions. It looks like the auto vectorizer
is able to recognize some of our record parsing loops and generate SIMD
instructions, so this likely will improve the SDK performance.
* SIMD instructions are generated by default for WebAssembly binaries when building with `rpk`.
=> rpk/transform/build: enable SIMD

src/v/kafka/server/handlers/configs/config_utils.h
- incremental_alter_configs requests were killing connections when requests supplied an invalid string as a compression_type argument.
- The method lexical_cast invokes to convert a compression to a string contains a string_switch method without a default clause, this throws when no matches are found. The solution is to wrap the call to lexical_cast in a try/catch clause.
- Fixes: #16281
* Fixes issue that causes the connection to hang when an unsupported compression type is passed via an incremental_alter_configs request
=> kafka: Wrap call to lexical_cast in try block

tests/rptest/scale_tests/audit_log_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16347
=> [v23.3.x] rptest: Bump audit logging scale test run time

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/config/mock_property.h, src/v/transform/fwd.h, src/v/transform/logging/CMakeLists.txt, src/v/transform/logging/io.h, src/v/transform/logging/log_manager.cc, src/v/transform/logging/log_manager.h, src/v/transform/logging/logger.cc, src/v/transform/logging/logger.h, src/v/transform/logging/tests/CMakeLists.txt, src/v/transform/logging/tests/log_manager_test.cc, src/v/transform/logging/tests/utils.cc, src/v/transform/logging/tests/utils.h, src/v/utils/absl_sstring_hash.h
This PR introduces transform::logging::manager whose primary responsibility is to buffer transform logs, periodically flushing them to some transform::logging::sink as chunked_fifo<iobuf> of JSON-serialized OpenTelemetry-compatible log events.
Closes https://github.com/redpanda-data/core-internal/issues/1035
Closes https://github.com/redpanda-data/core-internal/issues/998
* none
=> Introduce `transform::logging::manager`

src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_types.h, src/v/cluster/partition.h, src/v/resource_mgmt/storage.cc, src/v/storage/disk_log_impl.cc, src/v/storage/disk_log_impl.h, src/v/storage/log.h
SM publishes reclaimable space up to the local retention level to the cluster balancer. However, it may be the case that a disk is nearly full even at the local retention target, causing the balancer to believe that any space is not available for reclaim. This is problematic for decommission which needs to be able to find some place to create new replicas.
This change swaps out the reclaimable space at local retention level for total reclaimable space. The balancer policy will be expanded further to also take into account the local retention targets and optimize decisions. Changes for that are here https://github.com/redpanda-data/redpanda/pull/16372.
Related https://github.com/redpanda-data/core-internal/issues/719
* Publish total reclaimable space to avoid stuck decommission scenario.
=> cluster: publish total available reclaim size to balancer

src/v/kafka/server/handlers/topics/topic_utils.cc, src/v/kafka/server/handlers/topics/topic_utils.h, tests/rptest/tests/topic_creation_test.py
Previously we used a simple `std::vector` of futures to make
waiting for partition leaders concurrent. Using a vector has a drawback
when dealing with large number of topics and partitions since it may be
required to allocate large contiguous chunk of memory for a future
vector. In this particular case we may not use a fragmented vector or
chunked fifo as the `when_all` uses a plain vector internally.
To make sure no large chunk of memory is allocated to wait for the
partition leaders changed the logic to use
`seastar::max_concurrent_for_each`.
Fixes: #15908, #16270
Fixes: #16036
- none
=> Fixed large allocation in `kafka::wait_for_leaders`

src/v/cluster/distributed_kv_stm.h, src/v/cluster/tests/distributed_kv_stm_tests.cc
The read lock held in `list` is for snapshots, and doesn't protect
against concurrent writes. If we yield when copying the kv_data, then
re-lookup the position we were at when resuming so that we don't access
an invalidated iterator.
FIXES: https://github.com/redpanda-data/redpanda/issues/16402
* Fix invalidate iterator access when yielding control to the scheduler in data transforms debug endpoint.
=> c/distributed_kv_stm: prevent invalidated iterators during list

src/v/kafka/client/produce_partition.h, src/v/kafka/client/producer.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16315
Fixes: https://github.com/redpanda-data/redpanda/issues/16391,
=> [v23.3.x] kafka/client: Fix for stall during client shutdown

.github/workflows/scripts/backport-command/pr_details.sh, tests/docker/ducktape-deps/flink
`--jq` arg of gh graphql returns multiline string in case of multiple fixing issues. Fixing by joining the results in a single line string
* none
=> slash-cmd: fix /backport command

src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h
It looks like last_end_tx was added to fix a violation when the code had lazy catchup on an abort transaction.
This field was added in commit [1] when the abort code looked like this [2]
```
if (_mem_state.last_end_tx < r.value().last_offset) {
_mem_state.last_end_tx = r.value().last_offset;
}
// don't need to wait for apply because tx is already aborted on the
// coordinator level - nothing can go wrong
co_return tx_errc::none;
}
```
This sort of seemed like an optimization where we could skip the wait and defer it to next command if needed.
However the code changed later in this commit [3] where an explicit wait after abort added thus obviating the need for this field.
Just looking at the code, anywhere this field is updated, we immediately have a wait for state machine to catchup until …
=> rm_stm: remove mem_state::last_end_tx

tests/rptest/archival/s3_client.py
When running boto3 client versus AWS it uses own header to point to object that needs to be copied.
The same function is usable for GCP's storage, but with custom header.
This PR adds custom_headers handling to CopyObject function
Backport needed only to v23.3.x due to GCP runs only supported for that version
Also v23.1.x will reach end of support soon.
Fixes: #15211 
* none
=> rptest: Fix s3.copy_object when running on GCP

src/v/kafka/server/handlers/configs/config_utils.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16399
Fixes: https://github.com/redpanda-data/redpanda/issues/16405,
=> [v23.2.x] kafka: Wrap call to lexical_cast in try block

src/v/model/fundamental.h, src/v/model/timeout_clock.h, src/v/storage/disk_log_impl.cc, src/v/storage/disk_log_impl.h, src/v/storage/log.h, src/v/storage/readers_cache.cc, src/v/storage/segment_index.cc, src/v/storage/segment_index.h, src/v/storage/tests/storage_e2e_test.cc, src/v/storage/types.h
This PR adds a `offset_range_size` methods to the `storage::log`. The implementation in `storage::disk_log_impl` uses segment indexes to find approximate location of the start of the range and approximate location of the last batch. Then it performs short scan to find the precise location.
There are two overloads of the method.
- First one accepts two offsets and returns the size of the range.
- Second one accepts start offset and target size. It finds the last offset of the range and its size.
The method is supposed to be used to create S3 uploads. Currently, the code reads from disk directly and therefore is coupled with the storage format and a lot of internal storage details. Our goal is to decouple local and remote storage by providing clear API boundary.
* none
=> archival: Add offset_range_size method to the storage::log

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/config/mock_property.h, src/v/transform/fwd.h, src/v/transform/logging/CMakeLists.txt, src/v/transform/logging/io.h, src/v/transform/logging/log_manager.cc, src/v/transform/logging/log_manager.h, src/v/transform/logging/logger.cc, src/v/transform/logging/logger.h, src/v/transform/logging/tests/CMakeLists.txt, src/v/transform/logging/tests/log_manager_test.cc, src/v/transform/logging/tests/utils.cc, src/v/transform/logging/tests/utils.h, src/v/utils/absl_sstring_hash.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16301
=> [v23.3.x] Introduce `transform::logging::manager`

src/v/kafka/server/handlers/create_topics.cc, src/v/kafka/server/handlers/topics/types.cc, tests/rptest/clients/kcl.py, tests/rptest/tests/topic_creation_test.py
This commit makes some changes to the create_topics path to ensure that partition count and replication factor of created (or already existing) topics are correctly populated in responses.
Includes a small change to ensure that topic configs are serialized correctly with respect to existing formatters (e.g. the default cleanup.policy should appear in create topics results as "delete" where previously it was "1").
Fixes #15722 
Fixes #7946 
* Fix an issue where create topics responses would show incorrect partition count and replication factor
=> Return accurate partition count and replication factor in CreateTopics response

src/go/rpk/pkg/adminapi/admin.go, src/go/rpk/pkg/adminapi/api_debug.go, src/go/rpk/pkg/cli/debug/bundle/bundle.go, src/go/rpk/pkg/cli/debug/bundle/bundle_k8s_linux.go, src/go/rpk/pkg/cli/debug/bundle/bundle_linux.go, tests/rptest/clients/rpk_remote.py, tests/rptest/tests/rpk_cluster_test.py
This PR adds the raw response of the CPU profile admin endpoint to the bundle generated by `rpk debug bundle`. 
It introduces a new flag: `--cpu-profiler-wait` with a default of `30s`,  which sets the internal `wait_ms` of the Admin API's `GET /v1/debug/cpu_profile`
**File Location:** `bundle/admin/cpu_profile_<node_address>.json` 
Fixes #13175
* `rpk debug bundle` now includes a CPU profile of the requested nodes.
=> rpk: add `cpu_profile` to `rpk debug bundle`

src/v/kafka/server/handlers/create_topics.cc, src/v/kafka/server/handlers/topics/types.cc, tests/rptest/clients/kcl.py, tests/rptest/tests/topic_creation_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16410
Fixes: https://github.com/redpanda-data/redpanda/issues/16450, Fixes: https://github.com/redpanda-data/redpanda/issues/16451,
=> [v23.3.x] Return accurate partition count and replication factor in CreateTopics response

src/v/kafka/server/handlers/topics/topic_utils.cc, src/v/kafka/server/handlers/topics/topic_utils.h, tests/rptest/tests/topic_creation_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16287
Fixes: https://github.com/redpanda-data/redpanda/issues/16430, Fixes: https://github.com/redpanda-data/redpanda/issues/16431,
=> [v23.3.x] Fixed large allocation in `kafka::wait_for_leaders`

src/v/archival/ntp_archiver_service.cc, src/v/cloud_storage_clients/client_pool.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16385
=> [v23.3.x] cloud_storage_clients/client_pool: handle broken _self_config_barrier

src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_types.h, src/v/cluster/partition.h, src/v/resource_mgmt/storage.cc, src/v/storage/disk_log_impl.cc, src/v/storage/disk_log_impl.h, src/v/storage/log.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16354 
Fixes: https://github.com/redpanda-data/redpanda/issues/16423
=> [v23.2.x] cluster: publish total available reclaim size to balancer

src/v/cloud_storage/async_manifest_view.cc, src/v/cloud_storage/remote_partition.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16302
Fixes https://github.com/redpanda-data/redpanda/issues/16305
=> [v23.2.x] demote ERROR message to DEBUG for timequerys at the edge of spillover retention

src/v/cluster/cloud_metadata/cluster_recovery_backend.cc, src/v/cluster/cloud_metadata/cluster_recovery_backend.h, src/v/cluster/cloud_metadata/tests/controller_snapshot_reconciliation_test.cc, src/v/cluster/cluster_recovery_reconciler.h, src/v/cluster/controller.cc, src/v/container/include/container/fragmented_vector.h, src/v/container/tests/CMakeLists.txt, src/v/container/tests/fragmented_vector_test.cc, src/v/container/tests/vector_bench.cc
Introduce chunked_vector: like a fragmented_vector but with a better allocation profile for small vectors.
Additionally improve the implementation by making indexing faster (removing bounds checks) and adding a debug mode that checks for invalid iterator usage.
* none
=> container: introduce chunked vector

src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_partition.h, src/v/cloud_storage/remote_segment.cc, src/v/ssx/tests/CMakeLists.txt, src/v/ssx/tests/watchdog_test.cc, src/v/ssx/watchdog.h
Sometimes we want to detect situations when things are get stuck. Every
Redpanda service usually have a stop method which is invoked during
shutdown and which could prevent graceful shutdown when it hangs.
Another example is all types of eviction/housekeeping loops in the code.
When these loops are stuck Redpanda is running out of resources. We want
to be able to detect this.
The 'watchdog' utitily is a simple safeguard. When the object is created
it takes a timeout and a callback. When timeut expires the callback is
invoked. The watchdog can be created on a stack before the asynchronous
operation that can potentially get stuck.
Usage:
```
ss::future<> service: stop() {
watchdog wd(10s, [] {
vlog(logger.error, "service::stop hang");
});
_as.request_abort();
co_await _gate.close();  //<-- …
```
=> cloud_storage: Add watchdog utility and use it to detect stuck eviction loop

src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_partition.h, src/v/cloud_storage/remote_segment.cc, src/v/ssx/tests/CMakeLists.txt, src/v/ssx/tests/watchdog_test.cc, src/v/ssx/watchdog.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16466
=> [v23.3.x] cloud_storage: Add watchdog utility and use it to detect stuck eviction loop

src/v/transform/logging/tests/log_manager_test.cc
I saw a test flake in CI for another PR and dove in to debug this test
via: `transform_logging_rpunit --gtest_repeat=1000 --gtest_break_on_failure`
Running that I quickly saw failures, and after turning on logs and added
a couple logs of my own, I saw that in debug mode because the scheduler
can reorder tasks, that there is a concurrent flush running when we
advance our manual clock (from the LWM flush), so the clock advance
doesn't do anything. Fix that by always awaiting for pending tasks to
finish before triggering the next flush.
After performing this change, I can now run 1000 iterations of this
test on debug mode without failures.
* none
=> transform/logging/test: deflake TransformLogManagerTest.LargeBuffer

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/config/convert.h, src/v/config/property.h, src/v/config/rjson_serialization.cc, src/v/config/rjson_serialization.h, src/v/kafka/server/handlers/fetch.cc, src/v/kafka/server/handlers/fetch.h, src/v/kafka/server/tests/fetch_test.cc, src/v/model/metadata.h, src/v/model/model.cc, src/v/raft/tests/basic_raft_fixture_test.cc, src/v/ssx/abort_source.h
This PR implements a new `fetch_plan_executor` that doesn't repeatedly poll every partition in the fetch for new data. Instead it relies on registering callbacks with `raft:consensus::visible_offset_monitor` to know when a partition has new data and therefore would be worth querying once again.
The gist of how this is implemented is as follows;
- A fetch "coordinator"(see `kafka::nonpolling_fetch_plan_executor::execute_plan`) is created on the shard that received the fetch request. This coordinator is responsible for creating fetch workers and determining when a fetch request is completed.
- A fetch "worker"(see `kafka::nonpolling_fetch_plan_executor::shard_fetch_worker`) is created on every shard that has a partition from the request. It's responsible for querying partitions for data. …
=> Non-polling fetch implementation

tests/rptest/perf/small_batches_test.py, tests/rptest/perf/ts_read_openmessaging_test.py
Changes and removes validation from the `small_batches_test` and `ts_read_openmessaging_test` to remove more false negatives and therefore making failures a more accurate signal for regression. 
* none
=> Stabilize OMB regression tests

cmake/dependencies.cmake, licenses/third_party.md, src/v/redpanda/admin/server.cc, src/v/redpanda/admin/transform.cc, src/v/transform/api.cc, src/v/transform/api.h, src/v/wasm/CMakeLists.txt, src/v/wasm/api.h, src/v/wasm/cache.cc, src/v/wasm/cache.h, src/v/wasm/errc.h, src/v/wasm/parser/CMakeLists.txt, src/v/wasm/parser/README.md, src/v/wasm/parser/include/wasm/parser/parser.h, src/v/wasm/parser/leb128.h, src/v/wasm/parser/parser.cc, src/v/wasm/parser/tests/CMakeLists.txt, src/v/wasm/parser/tests/leb128_test.cc, src/v/wasm/parser/tests/parser_test.cc, src/v/wasm/tests/wasm_cache_test.cc, src/v/wasm/tests/wasm_fixture.cc, src/v/wasm/wasmtime.cc, tests/docker/ducktape-deps/tinygo-wasi-transforms, tests/rptest/clients/rpk.py, tests/rptest/tests/data_transforms_test.py
As part of the multiple output topics project, we will be supporting multiple ABI versions.
To help reduce user confusion when the case of when the SDK is newer than Redpanda, we will
validate the versions we support at deploy time. As we currently will provide backwards compatibility,
but not forwards compatibility.
* Validate transform code at deploy time to ensure the correct SDK is used.
=> transform: validate wasm binaries at deploy time

src/v/transform/logging/tests/log_manager_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16478
=> [v23.3.x] transform/logging/test: deflake TransformLogManagerTest.LargeBuffer

src/v/raft/consensus.cc, src/v/storage/disk_log_impl.cc, src/v/storage/disk_log_impl.h, src/v/storage/log.h, src/v/storage/tests/storage_e2e_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16105
Fixes: https://github.com/redpanda-data/redpanda/issues/16500,
=> [v23.3.x] Fix/inconsistent flushed offset

src/v/container/include/container/fragmented_vector.h, src/v/container/tests/fragmented_vector_test.cc
The main thing this patch does is catch a bug with `pop_back` in chunked vector now that we don't always use full fragment sizes when there is only a single fragment.
There are also a couple of other small improvements and fixes for `chunked_vector`, such as calling `reserve` for the iterator constructor, making `memory_size` more accurate.
* none
=> container: chunked_vector improvements

tests/rptest/clients/kubectl.py
Follow on to PR #16505
Fix missing comma. The code "works" because the strings get just appended to each
other but then form an invalid cli arg.
* none
=> Fix missing comma in kubectl.py

src/v/cluster/partition_manager.cc, src/v/rpc/rpc_server.cc, src/v/rpc/transport.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16304
=> [v23.2.x] Wrapped logging with `vlog` macro in places that missed it

src/v/kafka/server/handlers/metadata.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15981
Fixes: https://github.com/redpanda-data/redpanda/issues/16490, Fixes: https://github.com/redpanda-data/redpanda/issues/16491,
=> [v23.3.x] k/metadata: guesstimate leader when information is not yet present

tests/rptest/clients/kubectl.py
Fixes https://github.com/redpanda-data/cloudv2/issues/12090
clean teleport data dir before each use so the expired identity is not reused.
verified with simple test:
```console
ducktape \
--debug \
tests/rptest/tests/services_self_test.py::SimpleSelfTest.test_cloud
```
output:
```
...
[INFO  - 2024-01-30 05:06:02,510 - kubectl - _setup_tbot - lineno:257]: cleaning teleport data dir
[INFO  - 2024-01-30 05:06:02,511 - kubectl - _setup_tbot - lineno:259]: starting tbot to generate identity
WARN [TBOT]      CLI parameters are overriding onboarding config from  config/config.go:472
INFO [TBOT]      Created directory "/tmp/tbot-data" …
```
=> rptest: clean teleport data dir before use

tests/rptest/tests/prefix_truncate_recovery_test.py
During the recovery test in `test_prefix_truncate_recovery`, a node is restarted, and metrics are queried to wait until no partitions are under-replicated.
The test occasionally fails at `assert len(metric.samples) == len(nodes)` due to a missing metric for the test topic on the just-restarted node.
The redpanda server allows metrics to be queried very early in the server startup flow but the controller log which instructs the server which partition topics it manages is applied asynchronously.
To resolve this issue, we remove the assertion and instead rely on the fact that other servers will correctly report under-replicated partitions using `all(map(lambda s: s.value == 0, metric.samples))`.
Thus, the assert statement is both incorrect and redundant.
Fixes #16115
* none
=> rptest: tolerate missing topic metrics after start

tests/rptest/clients/kubectl.py, tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/redpanda_cloud_tests/rolling_restart_test.py, tests/rptest/services/redpanda.py, tests/rptest/test_suite_cloud.yml
Fixes https://github.com/redpanda-data/core-internal/issues/1001
Add `RedpandaServiceCloud.restart_pod()` and `RedpandaServiceCloud.rolling_restart_pods()` to aid in tests that need to simulate a graceful restart of these k8s resources.
Implemented using the `kubectl delete pod` command to allow [k8s to gracefully manage the termination process](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination).
Also added a simple self test of these 2 methods in `redpanda_cloud_tests/rolling_restart_test.py` to the cloud test suite.
verified with a `tier-3-aws-v2-arm` cluster:
```console
ducktape \
--debug \ …
```
=> rptest: add ability to restart pods in `RedpandaServiceCloud`

src/v/cloud_storage/read_path_probes.h, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/tests/common_def.h, src/v/cloud_storage/tests/remote_partition_test.cc, src/v/cloud_storage/tests/util.cc, src/v/cloud_storage/tests/util.h
Timequery can trigger full partition scan if the query overshoots the last segment. In this case if `log_reader_config.start_offset` is below the first segment in the manifest and `log_reader_config.max_offset` is above last offset in the manifest we will initialize the scan from the beginning which is very expensive.
This PR adds
- New partition level metrics which are used to detect skipped bytes generated by futile partition scan. This metrics are not exposed to metrics endpoint and only used internally (mostly for testing and will be used for alerts).
- New test suite in the `remote_partition_test` that performs timequery (TODO: add fuzz test).
- One line fix for the bug.
Fixes #16479
* Fix timequery error that triggered full partition scan
=> cloud_storage: Fix timequery bug that triggers full scan

src/v/raft/consensus.cc, src/v/raft/tests/basic_raft_fixture_test.cc
If an offset was already visible a follower must not be allowed to
truncate it as it may lead to a situation in which an offset is visible
and not readable.
Visible batches has the same replication guarantees as committed batches
as leader still waits for the majority to acknowledge message at given
offset before making it visible to the readers. This makes it possible
not to truncate offsets which were previously visible.
- Improved handling of follower fetching offset validation when used with relaxed consistency
=> Improved handling of truncation with ACKS=1

src/v/README.md, src/v/coding-style.md
In an effort to prioritize documentation, add expectations to the coding guide on what should
be documented.
As an example of existing codebase that I think is fairly well documented is CockroachDB:
They have "package" level documentation (which we'll solve with README): 
https://github.com/cockroachdb/cockroach/blob/b876c990bbd40af075dda6ab6b28b392ec6da19f/pkg/gossip/doc.go#L12-L15
If you look through the entry point to that exact package, I think it's pretty solid:
https://github.com/cockroachdb/cockroach/blob/master/pkg/gossip/gossip.go
Other package examples from CockroachDB:
* https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/doc.go
* https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sqlstats/ssprovider.go
As for our own codebase, I think we have parts that are …
=> coding-style: propose documentation recommendations

tests/rptest/services/redpanda.py
Follow-up to e567d63 (#16263) to simplify the metrics_sum filtering.
* none
=> rptest: simplify metric_sum filtering

src/v/cloud_storage/read_path_probes.h, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/tests/common_def.h, src/v/cloud_storage/tests/remote_partition_test.cc, src/v/cloud_storage/tests/util.cc, src/v/cloud_storage/tests/util.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16503
Fixes: https://github.com/redpanda-data/redpanda/issues/16517,
=> [v23.3.x] cloud_storage: Fix timequery bug that triggers full scan

src/v/raft/consensus.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16475
=> [v23.2.x] Improved handling of truncation with ACKS=1

src/v/config/configuration.cc
This change aligns the default value of `rpc_client_connections_per_peer` to what we set it to by default via k8s on Cloud clusters. 
* none
=> Increase default value of `rpc_client_connections_per_peer` to 32

src/v/config/configuration.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16527
=> [v23.3.x] Increase default value of `rpc_client_connections_per_peer` to 32

src/v/kafka/server/handlers/topics/topic_utils.cc, src/v/kafka/server/handlers/topics/topic_utils.h, tests/rptest/tests/topic_creation_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16287
Fixes: https://github.com/redpanda-data/redpanda/issues/16433, Fixes: https://github.com/redpanda-data/redpanda/issues/16434,
=> [v23.2.x] Fixed large allocation in `kafka::wait_for_leaders`

src/v/cloud_storage/remote_partition.cc
Timequery can trigger full partition scan if the query overshoots the last segment. In this case if `log_reader_config.start_offset` is below the first segment in the manifest and `log_reader_config.max_offset` is above last offset in the manifest we will initialize the scan from the beginning which is very expensive.
Fixes #16479 #16516
* Fix timequery error that triggered full partition scan
=> [v23.2.x] cloud_storage: Fix timequery bug that triggers full scan

tests/rptest/test_suite_cloud.yml
follow on to PR #15701
enable test to run on the scheduled jobs
* none
=> rptest: enable test_add_and_decommission

tests/rptest/services/cluster.py, tests/rptest/services/redpanda.py, tests/rptest/tests/cloud_storage_scrubber_test.py, tests/rptest/utils/allow_logs_on_predicate.py, tests/rptest/utils/si_utils.py
FIXES https://github.com/redpanda-data/redpanda/issues/16474
This test removes a segment from the manifest to generate anomalies. A side effect of this is that the validation in manifest done during spillover which checks that the start of the manifest and the start of spillover must match can fail, because the first segment of the manifest has been force reset away.
Effectively, spillover manifest is creating by iterating over segment list in main manifest. This main manifest is missing its first segment because of the anomaly injection.
When applying the spillover command, the manifest compares the start offsets of the spillover meta and the main manifest. The start offset has not changed during the anomaly injection. As a result the apply-spillover command fails.
This is acceptable …
=> rptest: Ignore error logs generated by anomaly injection

tests/rptest/test_suite_cloud.yml
exclude just `OMBValidationTest.test_retention` from cdt cloud runs for now while it is being investigated
related to issue https://github.com/redpanda-data/redpanda/issues/15334
* none
=> rptest: exclude OMBValidationTest.test_retention

src/v/io/CMakeLists.txt, src/v/io/io_queue.cc, src/v/io/io_queue.h, src/v/io/page.cc, src/v/io/page.h, src/v/io/tests/CMakeLists.txt, src/v/io/tests/common.cc, src/v/io/tests/common.h, src/v/io/tests/io_queue_test.cc, src/v/io/tests/page_test.cc
Adds `io_queue` which manages and dispatches submitted reads and writes. It's underlying file description can safely be closed and re-opened at anytime which forms the basis for enforcing open-file limits (next PR) across all `io_queues`.
Reviewers will observe the complete lack of I/O optimization opportunities such as combining adjacent physical pages into larger I/O requests. The other feature lacking in this version which we will want is some amount of support for retrying failed I/Os and applying backpressure for certain scenarios such as ENOSPC, but that isn't in this version. Failures opening and closing are not fatal, and are used by the scheduler (next PR) to deal with transient issues opening and closing io queue files.
* none
=> io: add io queue manager

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/rpc/rpc_server.cc
Add a flag to allow disabling internal rpc reply compression.
Right now we unconditionally enable compression for rpc replies if they
are above the min compression size (1Kib).
In this commit we don't change the default and keep compression on but
we might change that in a follow up commit as the cpu overhead from
compressing/uncompressing larger messages has shown to be detrimental to
overall performance.
* none
=> rpc: Add config flag to enable/disable compression for replies

cmake/dependencies.cmake, licenses/third_party.md, src/v/redpanda/admin/server.cc, src/v/redpanda/admin/transform.cc, src/v/transform/api.cc, src/v/transform/api.h, src/v/wasm/CMakeLists.txt, src/v/wasm/api.h, src/v/wasm/cache.cc, src/v/wasm/cache.h, src/v/wasm/errc.h, src/v/wasm/parser/CMakeLists.txt, src/v/wasm/parser/README.md, src/v/wasm/parser/leb128.h, src/v/wasm/parser/parser.cc, src/v/wasm/parser/parser.h, src/v/wasm/parser/tests/CMakeLists.txt, src/v/wasm/parser/tests/leb128_test.cc, src/v/wasm/parser/tests/parser_test.cc, src/v/wasm/tests/wasm_cache_test.cc, src/v/wasm/tests/wasm_fixture.cc, src/v/wasm/wasmtime.cc, tests/docker/ducktape-deps/tinygo-wasi-transforms, tests/rptest/clients/rpk.py, tests/rptest/tests/data_transforms_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16290 the main conflicts were because #16185 was not backported, so I just had to remove those conflicts, and also fix some includes
=> [v23.3.x] transform: validate wasm binaries at deploy time

tests/rptest/redpanda_cloud_tests/cloud_self_test.py, tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/redpanda_cloud_tests/omb_validation_test.py, tests/rptest/services/redpanda.py, tests/rptest/test_suite_cloud.yml, tests/rptest/tests/redpanda_cloud_test.py
Fixes https://github.com/redpanda-data/core-internal/issues/1003
New method`RedpandaServiceCloud.cluster_healthy()` according to [instructions](https://docs.redpanda.com/current/manage/kubernetes/k-rolling-restart/#perform-a-rolling-restart) on ensuring cluster is healthy.
Added assertions with `cluster_healthy()` to the start and end of the heavy tests that target cloud clusters.
Also added a simple self test for the new method:
```console
ducktape \
--debug \
tests/rptest/redpanda_cloud_tests/cloud_self_test.py
```
output:
```
test_id:    rptest.redpanda_cloud_tests.cloud_self_test.SelfRedpandaCloudTest.test_simple …
```
=> rptest: fix cluster healthy check

tests/rptest/clients/kubectl.py
following on PR #16359, this PR fixes [error](https://buildkite.com/redpanda/vtools/builds/11765) in running ducktape tests on cloudv2:
```
...
File "/home/ubuntu/redpanda/tests/rptest/clients/kubectl.py", line 271, in _setup_tbot
shutil.rmtree(self.TELEPORT_DATA_DIR)
File "/usr/lib/python3.10/shutil.py", line 715, in rmtree
onerror(os.lstat, path, sys.exc_info())
File "/usr/lib/python3.10/shutil.py", line 713, in rmtree
orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tbot-data'
```
by forcing deletion of the teleport data dir.
i validated this by running test without `/tmp/tbot-data` dir to simulate buildkite's scheduled job scenario:
```console
ducktape \
--debug \ …
```
=> rptest: force cleaning of teleport data dir

src/v/container/include/container/fragmented_vector.h, src/v/container/tests/fragmented_vector_test.cc, src/v/kafka/protocol/schemata/generator.py, src/v/kafka/server/handlers/create_topics.cc, src/v/kafka/server/tests/create_topics_test.cc, src/v/kafka/server/tests/delete_topics_test.cc, src/v/kafka/server/tests/topic_recreate_test.cc
Override the decode path to use chunked_vector for createable_topic as we may have 10,000s of these in a single API request.
Arguably, we could use chunked_vector everywhere now in schemata and get rid of this override, but let's do that later.
Fixes #16521.
* Avoid a large contiguous allocation when creating thousands of topics in a single CreateTopics request.
=> schemata: use chunked_vector for createable_topic

tests/rptest/tests/controller_erase_test.py
When testing partial deletion the test selects a segment to remove from controller log. Before deleting the segment but after it was selected it may be accounted in the controller snapshot.
Disabled controller snapshot to prevent the test racing with snapshot creation.
Fixes: #8217
- none
=> tests: disable snapshots when testing partial controller deletion

tests/rptest/tests/controller_erase_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16495
Fixes: https://github.com/redpanda-data/redpanda/issues/16555,
=> [v23.3.x] tests: disable snapshots when testing partial controller deletion

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/rpc/rpc_server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16525
Fixes https://github.com/redpanda-data/redpanda/issues/16549
=> [v23.2.x] rpc: Add config flag to enable/disable compression for replies

src/v/config/configuration.cc
On the internal rpc send side compression is enabled selectively via
opts parameters but on the reply side we compress all replies that are
above 1Kib unconditionally by default.
Compression is usually useful for trading compute for IO. There seems
little point in doing this for internal rpc. Brokers are mostly
connected on low latency/high throughput links so compression just adds
needless CPU overhead.
In the higher cloud tiers at the partition limits we see the health
report infra cause overhead and latency degregation in higher
percentiles.
A large chunk of this comes from compressing and decoding the massive
health report messages.
This patch disables compression which measurably improves the situation
as per above reasoning.
This change has little impact on normal append_entries …
=> rpc: Disable compression for internal rpc replies

tests/rptest/services/provider_clients/instance_utils.py
=> rptest: Fix instance type getter for GCP

src/v/transform/api.cc
The previous handling was incorrect (awaiting on an invalid future),
this probably shouldn't fail silently, and everything in logging::manager::start
is noexcept anyway.
* none
=> xform/service: Remove exception handling from _log_manager->start

src/v/kafka/server/replicated_partition.h, src/v/raft/consensus.cc, src/v/raft/consensus.h
A leader epoch is used by Kafka clients to determine if a replica is up
to date with the leader and to detect truncation.
The leader epoch differs from Raft term as the term is updated when
leader election starts. Whereas the leader epoch is updated after the
state of the replica is determined. Therefore the leader epoch uses
confirmed term instead of the simple term which is incremented every
time the leader election starts.
- Prevent detecting leader epoch advancement when state is not up to date
=> Use confirmed term as a source of leader epoch

src/v/cluster/cloud_metadata/cluster_recovery_backend.cc, src/v/cluster/cloud_metadata/cluster_recovery_backend.h, src/v/cluster/cloud_metadata/tests/controller_snapshot_reconciliation_test.cc, src/v/cluster/cluster_recovery_reconciler.h, src/v/cluster/controller.cc, src/v/utils/fragmented_vector.h, src/v/utils/tests/CMakeLists.txt, src/v/utils/tests/fragmented_vector_test.cc
=> [v23.3.x] introduce chunked_vector

src/v/archival/ntp_archiver_service.cc, src/v/archival/purger.cc, src/v/cloud_storage/recovery_utils.cc, src/v/cloud_storage/remote.cc, src/v/cloud_storage/remote.h, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/tests/remote_segment_test.cc, src/v/cloud_storage/tests/remote_test.cc, src/v/cloud_storage/types.cc, src/v/cloud_storage/types.h, src/v/cluster/cloud_metadata/offsets_uploader.cc
This is a refactor of the `upload_object` api in remote.cc. This method is used to upload small files to cloud storage as an iobuf payload. The method is a little rough in that it accepts strings to classify the upload kind and has code paths to update metrics of the remote probe depending on which object kind was uploaded (this is checked via string comparison).
The changes here are a pre-requisite to being able to use this API to create inventory configuration objects which are a PUT request with an XML payload. 
The following changes are made:
* scoped enum values are used to represent upload kind
* The caller specifies callbacks to use (optionally) when the upload succeeds, fails or backs off, with the remote probe supplied as argument
* The many arguments are collected into a POD …
=> cloud_storage: update upload_object api

tests/rptest/services/openmessaging_benchmark.py
Set KAFKA_OPTS to a single space in OMB, which is required to use newer OMB versions as otherwise we try to use a -javaagent from a location that doesn't exist in DT OMB setup (see
bin/benchmark-workers script).
Single empty space is because a totally empty KAFKA_OPTS will still be overridden by the bin/benchmark-workers script.
Issue redpanda-data/core-internal#1016.
* none
=> Set KAFKA_OPTS to empty in OMB

src/go/rpk/.golangci.yml, src/go/rpk/pkg/cli/redpanda/tune/tune.go, src/go/rpk/pkg/tuners/executors/commands/write_sized_file.go, src/go/rpk/pkg/tuners/executors/commands/write_sized_file_test.go
This PR fixes:
- Missing new line in output script.
- Improves the file handling behavior, now it creates a file if the provided string does not exist. 
Fixes #16552 
Fixes #16064 
* `rpk tune --output-script`: Add a missing new line in the ballast file tuner when using the `--output-script` flag
* `rpk tune --output-script`: rpk now creates a file for you if the provided file does not exist.
=> rpk: Improve tuner output script

src/v/cloud_storage/CMakeLists.txt, src/v/cloud_storage/inventory/aws_ops.cc, src/v/cloud_storage/inventory/aws_ops.h, src/v/cloud_storage/inventory/inv_ops.cc, src/v/cloud_storage/inventory/inv_ops.h, src/v/cloud_storage/inventory/tests/CMakeLists.txt, src/v/cloud_storage/inventory/tests/create_inventory_config_test.cc, src/v/cloud_storage/inventory/types.cc, src/v/cloud_storage/inventory/types.h, src/v/cloud_storage/remote.h, src/v/cloud_storage/types.cc, src/v/cloud_storage/types.h
The inventory API is introduced for AWS. The primary object introduced here is `cloud_storage::inventory::inv_ops` which is not wired into any service yet. Eventually it will be used by the scrubber-inventory download service (yet to be created) to schedule and download reports.
This PR contains the `create_inventory_configuration` method. The method added here schedules reports to be created for the given frequency and format by creating a report configuration. It calls [PutBucketInventoryConfiguration](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketInventoryConfiguration.html)
The API is divided into high level (vendor agnostic router) and low level (vendor specific) objects. The low level APIs, of which only AWS is implemented here, will hide the vendor specific actions …
=> cloud_storage/inventory: Add inventory create-config API for AWS

src/v/archival/tests/ntp_archiver_test.cc, src/v/cloud_storage/tests/remote_partition_fuzz_test.cc, src/v/cloud_storage/tests/remote_partition_test.cc, src/v/cloud_storage/tests/util.cc, src/v/cluster/config_manager.cc, src/v/config/property.h, src/v/config/tests/config_store_test.cc, src/v/net/conn_quota.cc
Previously we just set the value without notifying bindings. This led to ignoring property value updates when the property was reset to its default value as a result of a patch_cluster_config request with non-empty "remove" section.
* Fix a bug that resulted in Redpanda ignoring until the next restart config values that were reset to their defaults.
=> config: update bindings when properties are reset

src/v/config/configuration.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16548
=> [v23.3.x] rpc: Disable compression for internal rpc replies

src/v/archival/tests/ntp_archiver_test.cc, src/v/cloud_storage/tests/remote_partition_fuzz_test.cc, src/v/cloud_storage/tests/remote_partition_test.cc, src/v/cloud_storage/tests/util.cc, src/v/cluster/config_manager.cc, src/v/config/property.h, src/v/config/tests/config_store_test.cc, src/v/net/conn_quota.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16504
=> [v23.3.x] config: update bindings when properties are reset

src/v/kafka/server/replicated_partition.h, src/v/raft/consensus.cc, src/v/raft/consensus.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16560
=> [v23.3.x] Use confirmed term as a source of leader epoch

src/v/raft/tests/CMakeLists.txt, src/v/test_utils/test.h
Added timeout to for the `gtest_raft_rpunit`. This will allow us to retrieve logs from failed test. 
- none
=> Added timeout to `gtest_raft_rpunit`

tests/rptest/services/redpanda.py
Doesn't seem to be used anywhere and just creates confusion.
* none
=> rptest: remove config_file credential source support

src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/partition_manifest.h, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/tests/cloud_storage_e2e_test.cc, src/v/cloud_storage/tests/s3_imposter.cc
This fixes a bug for timequeries that could result in a removed segment being
unsuccessfully downloaded during a timequery. The sequence of events is as
follows:
1. Spillover manifest [7278, 8592]
2. Spillover more manifests... [...13574]
3. Eventually our stm manifest is [13875, 15802]
4. We housekeep and truncate to 7804. This is the new archive start offset and
archive clean offset
5. A timequery comes in whose timestamp falls in manifest [7278, 8592]
6. Segment [7278-7410] is attempted to be downloaded, which has already been
removed
To fix this, as we're seeking within a given manifest, we'll now check against
the overall start offset of the partition, skipping any segments that fall
below the start.
Fixes #15042
* Fixes a bug in the tiered storage time-based query implementation …
=> cloud_storage: skip over segments below archive start

src/v/archival/ntp_archiver_service.cc, src/v/archival/purger.cc, src/v/archival/upload_housekeeping_service.cc, src/v/cloud_storage/inventory/aws_ops.cc, src/v/cloud_storage/inventory/tests/create_inventory_config_test.cc, src/v/cloud_storage/recovery_utils.cc, src/v/cloud_storage/remote.cc, src/v/cloud_storage/remote.h, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/tests/remote_segment_test.cc, src/v/cloud_storage/tests/remote_test.cc, src/v/cloud_storage/types.cc, src/v/cloud_storage/types.h, src/v/cluster/cloud_metadata/offsets_uploader.cc
A `download_object` method is added to `cloud_storage::remote` to download small objects intended to remain in memory and not written to disk via a stream etc.
The upload_object_request is generalized into a transfer_request type with variants for upload and download.
The download_index method is refactored to use download_object.
The new method will be used in a follow up PR to check if an inventory configuration is present or not.
* none
=> cloud_storage: Add `download_object` method for downloading small objects

src/v/ssx/async_algorithm.h, src/v/ssx/tests/CMakeLists.txt, src/v/ssx/tests/async_algorithm_test.cc
Same as std::for_each, but which yields periodically. Written in a style which keeps in inner loop fast, equivalent to the non-async version (optimizer willing, but seems to be true in the case I checked).
For the simplest use cases we offer async_for_each, which is the same as std::for_each except that it yields every Traits::Interval iterations: every call starts the "work counter" anew.
For more complicated cases, like nested loops, it may be convenient to carry the counter from one iteration to the next, in order to yield at the correct times. For example, in a doubly nested loop where the inner loop always ran for less than Interval iterations, we would not yield with the simple functions.
Issue redpanda-data/core-internal#1061.
* none
=> Implement async_for_each

src/v/kafka/server/handlers/produce.cc, src/v/kafka/server/handlers/produce.h, src/v/kafka/server/tests/CMakeLists.txt, src/v/kafka/server/tests/produce_partition_bench.cc, src/v/redpanda/tests/fixture.h
=> tests: Add produce microbenchmark

src/v/cluster/tests/tx_compaction_utils.h, src/v/features/feature_table.cc, src/v/features/feature_table.h, src/v/kafka/protocol/batch_consumer.h, src/v/model/model.cc, src/v/model/record.h, src/v/model/record_batch_types.h, src/v/storage/compaction_reducers.cc, src/v/storage/compaction_reducers.h, src/v/storage/disk_log_impl.cc, src/v/storage/segment_deduplication_utils.cc, src/v/storage/segment_deduplication_utils.h, src/v/storage/segment_utils.cc, src/v/storage/segment_utils.h, src/v/storage/tests/segment_deduplication_test.cc, tests/java/verifiers/src/main/java/io/vectorized/compaction/tx/TxUniqueKeysWorkload.java, tests/java/verifiers/src/main/java/io/vectorized/compaction/tx/TxWorkload.java, tests/rptest/services/compacted_verifier.py, tests/rptest/tests/compaction_e2e_test.py
Control batches (tx_commit, tx_abort) are special data batches that indicate the completion of a transaction. Because these are technically data batches, they participate in deduplication.
It was previously thought that as long as we kept the last control batch in a segment, that deduplicating such records was safe. However, consider the following sequence:
```
node 1:
1. begin tx 1, write data batch in tx 1
2. write many non-tx data batches, up to offset 100
3. abort tx 1
4. begin tx 2, write data batch in tx 2, abort tx 2 which is offset 110
5. begin recovery, replicating data to node 2, sending records [0, 50]
6. roll segment
node 2:
7. receives data [0, 50], including [begin tx 1, data tx 1, data]
node 1:
8. self compact segment: since all abort records have the same key, only abort …
```
=> tx/compaction: don't deduplicate control batches

tests/rptest/tests/cpu_profiler_admin_api_test.py
Only core 0 was checked for samples in the test. We can see here in the result of querying the cpu profiler endpoint that only core 1 had samples.
```
[DEBUG - 2024-02-16 02:04:02,865 - admin - _request - lineno:383]: Response OK, JSON: [{'shard_id': 0, 'dropped_samples': 0}, {'shard_id': 1, 'dropped_samples': 0, 'samples': [{'user_backtrace': '0xef666 /opt/redpanda_installs/ci/lib/libseastar.so+0x597c482 /opt/r
```
```
KeyError('samples')
File "/usr/local/lib/python3.10/dist-packages/ducktape/tests/runner_client.py", line 184, in _do_run
data = self.run_test()
File "/usr/local/lib/python3.10/dist-packages/ducktape/tests/runner_client.py", line 269, in run_test
return self.test_context.function(self.test)
File "/root/tests/rptest/services/cluster.py", …
```
=> test: check for non-empty samples from any core

tests/docker/ducktape-deps/client-swarm
Latest changes needed in large topic numbers tests that being developed.
See history: https://github.com/redpanda-data/client-swarm/commits/main/
* none
=> ci: Bump client-swarm to latest commit

src/v/cloud_storage/inventory/aws_ops.cc, src/v/cloud_storage/inventory/aws_ops.h, src/v/cloud_storage/inventory/inv_ops.cc, src/v/cloud_storage/inventory/inv_ops.h, src/v/cloud_storage/inventory/tests/create_inventory_config_test.cc, src/v/cloud_storage/inventory/types.cc, src/v/cloud_storage/inventory/types.h, src/v/cloud_storage/remote.h
Introduces helpers to check if inventory configuration exists, and to conditionally create one. Maps the result of the individual calls to `inventory_creation_result` states: 
* `success`
* `failure`
* `already_exists`
The creation of config is expected to be performed by any node in cluster at startup. Instead of simply attempting to create and relying on the server side validation to prevent duplicates, we first do a check before creating the config. One node creates the config and the others see that the config is present and move on.
It is possible that multiple nodes try to create the config after they observe that the config is missing, since the calls to check and create are separate. In this case all but one nodes will fail to create the config. The failing nodes should return the …
=> cst/inv: Create helpers to conditionally create inventory config

src/v/ssx/async_algorithm.h, src/v/ssx/tests/async_algorithm_test.cc
async_for_each originally assumed random access iterators, but we can also support forward iterators at the cost of some complexity.
The main limitation with forward iterators is that we cannot do arithmetic on the iterators to determine the size of the range and to pre-calculate end iterators. So we use counted loops instead when those iterators are used (we dispatch to a separate path for random access iterators).
* none
=> Add forward iterator to async_for_each

src/v/ssx/async_algorithm.h
Backport of https://github.com/redpanda-data/redpanda/pull/16662.
Fixes #16672.
* none
=> [v23.2.x] Implement async_for_each

src/v/ssx/async_algorithm.h, src/v/ssx/tests/CMakeLists.txt, src/v/ssx/tests/async_algorithm_test.cc
Backport of https://github.com/redpanda-data/redpanda/pull/16662.
Fixes #16673.
* none
=> [v23.3.x] Implement async_for_each

src/v/utils/tests/CMakeLists.txt, src/v/utils/tests/vint_bench.cc
Test some different methods of decoding vints and also some general coroutine costs.
* none
=> vint_bench

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
Presumably if the cluster isn't yet fully initialized then jsonpath query for readyReplicas will return an empty string and converting that to an integer will fail. The entire process is in a wait_until, so we'll just ignore these errors.
test_id:    HighThroughputTest.test_add_and_decommission
status:     FAIL
run time:   2629.113 seconds
ValueError("invalid literal for int() with base 10: ''")
File "/usr/local/lib/python3.10/dist-packages/ducktape/tests/runner_client.py", line 184, in _do_run
data = self.run_test()
File "/usr/local/lib/python3.10/dist-packages/ducktape/tests/runner_client.py", line 269, in run_test
return self.test_context.function(self.test)
File "/home/ubuntu/redpanda/tests/rptest/services/cluster.py", line 104, in wrapped
r = …
=> test: retry on readyReplicas test

src/v/kafka/server/handlers/fetch.cc
Exceptions from outside the Kafka handler context can bubble up to the catch present in the handler. This seems to be the way some subsystems communicate issues with the requests. There is no current listing of what exceptions subsystems may throw, if/how to recover from these exceptions, or if a fetch should end as a result of the exception. Hence for the time being the fetch impl will revert to the behavior of further bubbling up unknown exceptions to outside of the handler context.
Fixes #16532
* none
=> Rethrow on unknown exceptions in fetch handler

src/v/cluster/types.h, src/v/utils/CMakeLists.txt, src/v/utils/named_type.h, src/v/utils/tests/CMakeLists.txt, src/v/utils/tests/named_type_tests.cc, src/v/utils/tests/xid_test.cc, src/v/utils/xid.cc, src/v/utils/xid.h
Defined a type representing a virtual cluster label. The `vcluster_id` is going to be used to identify partitions and connections and enrich  them with virtual cluster context.
Virtual cluster id is underlaid by XID type as defined in https://github.com/rs/xid.
- none
=> Introduced `cluster::vcluster_id` type underlied by XID

src/v/io/CMakeLists.txt, src/v/io/README.md, src/v/io/cache.h, src/v/io/scheduler.cc, src/v/io/scheduler.h, src/v/io/tests/CMakeLists.txt, src/v/io/tests/cache_test.cc, src/v/io/tests/io_queue_test.cc, src/v/io/tests/scheduler_test.cc
Adds a simple scheduler to the I/O subsystem. The purpose of the scheduler is to manage all of the active I/O queues (e.g. implementing global policies like preventing starvation or priority). However, this initial version of the scheduler only implements a policy that limits the total number of open file handles.
* none
=> io: add scheduler

src/v/ssx/async_algorithm.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16676
=> [v23.2.x] Add forward iterator to async_for_each

src/v/ssx/async_algorithm.h, src/v/ssx/tests/async_algorithm_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16676
=> [v23.3.x] Add forward iterator to async_for_each

src/v/config/configuration.cc, src/v/config/configuration.h
for correctness, limit the accepted range for log_segment_ms_min/max to only positive values
* ensure only positive values are accepted for log_segment_ms_min/max
=> config/configuration: bounded_property log_segment_ms_min/max

src/v/cluster/controller_probe.cc, src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_backend.h, src/v/cluster/health_monitor_types.cc, src/v/cluster/health_monitor_types.h, src/v/cluster/metadata_dissemination_handler.cc, src/v/cluster/metadata_dissemination_handler.h, src/v/cluster/metadata_dissemination_service.cc, src/v/cluster/metadata_dissemination_types.h, src/v/cluster/ntp_callbacks.h, src/v/cluster/partition_leaders_table.cc, src/v/cluster/partition_leaders_table.h, src/v/cluster/tests/CMakeLists.txt, src/v/cluster/tests/health_monitor_test.cc, src/v/cluster/tests/partition_balancer_planner_fixture.h, src/v/cluster/tests/partition_leaders_table_test.cc, src/v/cluster/tests/randoms.h, src/v/cluster/tests/serialization_rt_test.cc, src/v/compat/cluster_json.h, src/v/compat/json.h, src/v/compat/metadata_dissemination_compat.h, src/v/compat/metadata_dissemination_generator.h, src/v/container/include/container/fragmented_vector.h, src/v/model/namespace.h, src/v/test_utils/randoms.h, src/v/test_utils/test.h
Using a hierarchical data structure to store leader metadata in `cluster::partition_leaders_table`. Using a map of maps to store topic partition information as a value in top level topic only map. This way we do not need to keep a separate copy of topic name for each partition and can leverage the same hierarchical structure of `node_health_report` to reduce number of hash table look ups. 
Fixes: https://github.com/redpanda-data/core-internal/issues/1061
- optimized updating leadership metadata with health reports
=> Refactored `cluster::partition_leaders_table` to use hierarchical structure of metadata

tests/rptest/tests/redpanda_cloud_test.py
Fixup for cfe28f5b23dabd73db35fc3268f1349daba8b11c
* none
=> tests: Fix missing include in redpanda_cloud_test

src/v/serde/test/CMakeLists.txt, src/v/serde/test/bench.cc
Adds a benchmark for `node_health_report` de-serialization across the
topic and partitions dimensions.
| test                                                             |  iterations |      median |         mad |         min |         max |      allocs |       tasks |        inst |
| -                                                                |           - |           - |           - |           - |           - |           - |           - |           - |
| node_health_report.serialize_many_partitions                     |         824 |     1.040ms |     3.470us |     1.036ms |     1.068ms |      66.000 |       0.000 |  23326378.6 |
| node_health_report.serialize_many_topics                         |         214 |     2.865ms |   510.776ns |     2.865ms |     2.870ms |      90.000 | …
=> serde: Add node_health_report ser/de benchmark

src/v/http/client.cc, src/v/http/client.h, src/v/http/demo/client.cc, src/v/http/tests/http_client_test.cc, src/v/pandaproxy/test/utils.h
* Adds request() method that takes an iobuf
* Updates users of make_request() to use the new interface
* Sets HTTP/1.1 version explicitly
* none
=> http/client: add request interface that takes an iobuf

src/go/rpk/pkg/cli/redpanda/config.go, src/go/rpk/pkg/cli/redpanda/config_test.go, src/go/rpk/pkg/config/config.go, tests/rptest/tests/rpk_start_test.py
Fixes #16623 
This PR introduces both Advertised RPC and Kafka addresses to our defaults. Given that these values are now added to our default config file (see #14600) we must handle them properly during bootstrap.
Now `bootstrap` supports overriding the default address with the private IP or the one passed via `--self` flag.
Also, it adds flags to override this behavior and lets the user select which `address:port` to use in the advertised addresses.
rpk will preemptively fail if the resulting advertised host is `0.0.0.0` to avoid a validation error during startup.
**Example**:
Starting with the default Redpanda configuration file (https://github.com/redpanda-data/redpanda/blob/dev/conf/redpanda.yaml):
```
$ rpk redpanda config bootstrap --self 192.168.1.70 --advertised-kafka …
```
=> rpk: support advertised addresses in `rpk redpanda config bootstrap`

src/v/cluster/namespaced_cache.h, src/v/cluster/tests/CMakeLists.txt, src/v/cluster/tests/namespaced_cache_test.cc
The cache allows to maintain per namespace lru cache with fair distribution of available cache slots across all namespaces. Cache size is controlled by setting maximum number of entries. If adding new namespace to the cache would result in other namespace to have less than min_slots_per_namespace cache slots an exception is thrown.
Maximum number of namespaces that cache can handle can be calculated as:
```
floor(_max_size/_min_slots_per_namespace)
```
With cache EvictionPredT template parameter it is possible to prevent some entries from being evicted. A predicate should return 'false' if an entry is not evictable.
Eviction policy can be controlled with the CacheT parameter. The CacheT parameter allow to tune per namespace caching policy.
For now the only provided eviction policy is a …
=> c/namespaced_cache: added implementation of namespaced cache

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
For HighThroughputTest::test_decomm_and_add we used a fixed value of 10,000 messages to warm up the test, but with 4K messages and high tiers this could result in a warmup time of < 1 second, which rounded to zero, causing the test to time out immediately (in addition to being an unsuitably small warmup even if it didn't time out).
Instead, use a time-based workload calculation, i.e., use the number of messages we expect to be able to produce in a given time period: this will naturally scale with tier size as expected throughput increases.
Fixes #16470.
* none
=> cloud-tests: use a time-based calculation of load

src/v/io/tests/common.cc, src/v/io/tests/common.h, src/v/io/tests/common_test.cc
Adds an io input stream comparison utility for testing.
* none
=> io: add input stream equality test helper

src/v/cluster/partition_leaders_table.cc, src/v/cluster/partition_leaders_table.h
Since leaders table might have been modified during the execution of iteration over the topic partitions we must check the version of topics table after the asynchronous iteration finished.
- none
=> c/p_leaders: check if leaders table was modified after async iteration

src/v/cluster/controller_probe.cc, src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_backend.h, src/v/cluster/health_monitor_types.cc, src/v/cluster/health_monitor_types.h, src/v/cluster/metadata_dissemination_handler.cc, src/v/cluster/metadata_dissemination_handler.h, src/v/cluster/metadata_dissemination_service.cc, src/v/cluster/metadata_dissemination_types.h, src/v/cluster/ntp_callbacks.h, src/v/cluster/partition_leaders_table.cc, src/v/cluster/partition_leaders_table.h, src/v/cluster/tests/CMakeLists.txt, src/v/cluster/tests/health_monitor_test.cc, src/v/cluster/tests/partition_balancer_planner_fixture.h, src/v/cluster/tests/partition_leaders_table_test.cc, src/v/cluster/tests/randoms.h, src/v/cluster/tests/serialization_rt_test.cc, src/v/compat/cluster_json.h, src/v/compat/json.h, src/v/compat/metadata_dissemination_compat.h, src/v/compat/metadata_dissemination_generator.h, src/v/model/namespace.h, src/v/test_utils/randoms.h, src/v/test_utils/test.h, src/v/utils/fragmented_vector.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16512
Backport of PR https://github.com/redpanda-data/redpanda/pull/16711
=> [v23.3.x] Refactored `cluster::partition_leaders_table` to use hierarchical structure of metadata

src/v/cluster/metrics_reporter.cc, src/v/cluster/metrics_reporter.h, src/v/http/client.cc, src/v/http/client.h, src/v/http/tests/http_client_test.cc
Adds a `http::client::post` method which handles preparation of a post request as a convenience for the metrics reporter which is switched over to use this method.
* none
=> http/client: add `post()` method helper

src/v/wasm/parser/CMakeLists.txt, src/v/wasm/parser/include/wasm/parser/parser.h, src/v/wasm/parser/parser.cc, src/v/wasm/parser/tests/parser_test.cc
We've seen our launch demo run into these limits, so make the containers
non-contiguous and allow up to 1MiB of memory usage during parsing. This
fits the compiled ML framework's function count (~17k), as now we allow
~21k functions.
* Fix large wasm module deployments
=> wasm/parser: bump limits

tests/rptest/tests/topic_recovery_test.py
We were previously validating the HWM with the assumption that non-data records were exactly 1:1 with the number of archival segments. While such an assumption isn't unreasonable, it isn't very future proof.
I ran into a test failure where we the highest_producer_id record included to archival made this condition fail:
```
AssertionError: Unexpected high watermark 5025 (min expected: 5026, max expected: 5029)
```
This commit updates the check be more future-proof, simply validating how HWM is computed:
hwm = rp_last_offset + 1 - delta
Fixes #16769
* none
=> rptest: fix hwm computation in topic_recovery_test

src/v/redpanda/admin/debug.cc, src/v/redpanda/admin/partition.cc, src/v/redpanda/admin/transaction.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16551 
Fixes: #16717
=> [v23.3.x] admin: stream more json results

src/v/redpanda/admin_server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16551 
Fixes: #16716
=> [v23.2.x] admin: stream more json results

src/v/cluster/config_manager.cc, src/v/cluster/partition_leaders_table.cc, src/v/cluster/partition_leaders_table.h, src/v/cluster/scheduling/leader_balancer.cc, src/v/cluster/scheduling/leader_balancer.h, src/v/cluster/tests/partition_leaders_table_test.cc
When term changes but leader stays on the same we should still trigger the leadership notification.
Downstream components like `leadership_balancer` rely on this information to be triggered after successful leader election i.e. stable term change.
Fixes: #16142
- none
=> c/leaders: trigger leadership notification when term changes

tests/rptest/tests/consumer_group_balancing_test.py
Refactor consumer group balancing test to directly validate `__consumer_offsets` partition replicas placement instead of validating consumer groups coordinators.
Fixes: #9697
- none
=> tests: refactor consumer group balancing test

src/v/cluster/config_manager.cc, src/v/cluster/partition_leaders_table.cc, src/v/cluster/partition_leaders_table.h, src/v/cluster/scheduling/leader_balancer.cc, src/v/cluster/scheduling/leader_balancer.h, src/v/cluster/tests/partition_leaders_table_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16776
Fixes: https://github.com/redpanda-data/redpanda/issues/16783,
=> [v23.3.x] c/leaders: trigger leadership notification when term changes

src/v/cloud_storage/tests/partition_manifest_test.cc, src/v/cloud_storage/tests/topic_manifest_test.cc, src/v/cluster/cloud_metadata/tests/cluster_manifest_test.cc, src/v/kafka/server/tests/group_test.cc, src/v/kafka/server/tests/member_test.cc, src/v/utils/named_type.h
`named_type` was previously using a standard stream operator when being printed. This required any type wrapped with `named_type` to have `opertor<<` defined instead of relaying on `fmt::formatter` like a lot of types does. Changed the implementation of named type stream output operator to use `fmt` library.
- none
=> u/named_type: use fmt to format named type

src/v/cluster/topic_table_probe.h
Replaced `absl::flat_hash_map` that was used in `topic_table_probe` with the `btree_map` to avoid large allocations when we deal with large number of topics.
Fixes: #16779 
- none
=> c/topic_table_probe: use btree_map in topic table probe

tests/rptest/clients/kubectl.py, tests/rptest/redpanda_cloud_tests/cloud_self_test.py, tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/redpanda_cloud_tests/omb_validation_test.py, tests/rptest/services/openmessaging_benchmark.py, tests/rptest/services/redpanda.py, tests/rptest/services/redpanda_cloud.py, tests/rptest/services/redpanda_types.py
This series mostly deals with better health checks to catch cases where test failures (or tests that don't clean up after themselves even on success) may leave the cluster in an unusable state.
Individual commit messages have more details.
* none
=> rptest: better health check

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/kafka/server/snc_quota_manager.cc, src/v/kafka/server/snc_quota_manager.h, src/v/kafka/server/tests/produce_consume_test.cc, src/v/redpanda/application.cc, src/v/redpanda/application.h, src/v/ssx/sharded_ptr.h, src/v/ssx/tests/CMakeLists.txt, src/v/ssx/tests/sharded_ptr_test.cc, tests/rptest/perf/ts_write_openmessaging_test.py
When `kafka_throughput_throttling_v2` is enabled (true by default), use an `ss::internal::shared_token_bucket` for requests across all shards, instead of balancing quota between shards.
Fixes https://github.com/redpanda-data/core-internal/issues/929
Fixes https://github.com/redpanda-data/core-internal/issues/1021
Fixes https://github.com/redpanda-data/core-internal/issues/1022
Fixes https://github.com/redpanda-data/core-internal/issues/1023
MaybeFixes: https://github.com/redpanda-data/redpanda/issues/8809
|config|description|default|
|---|---|---|
| `kafka_throughput_throttling_v2` |   Use throughput throttling based on a shared token bucket <br> instead of balancing quota between shards | `true` | <br>
| `kafka_throughput_replenish_threshold` | Threshold for refilling the token …
=> Improve throughput throttling

tests/docker/ducktape-deps/flink
[Manual Backport of #16260]
This was missed in a force merge
Signed-off-by: Tyler Rockwood <rockwood@redpanda.com>
(cherry picked from commit 6f274dc24f80016818d52e9899dfe55a2073ba4a)
Fixes #16262 
* none
=> [v23.3.x] lint: fix linter error

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/kafka/server/connection_context.cc, src/v/kafka/server/connection_context.h, src/v/kafka/server/server.h, tests/rptest/tests/connection_virtualizing_test.py
Implemented virtualization of Kafka connections on top of one physical
TCP connection. Requests processed in a virtual connection context are
independent from other requests in different virtual connections. This
way we prevent requests from different virtual connections from blocking
each other.
Virtual connections are only available if first requests handled by the
connection has the `__redpanda_mpx` client id set and Redpanda MPX
extensions are enabled.
- none
=> Virtual connections in Kafka server

src/go/rpk/pkg/cli/redpanda/admin/brokers/decommission-status.go
Since 23.3, the ALLOCATION FAILURE field is available with any values in `partition_autobalancing_mode`. Prior to that, it was available only with `continuous`. This PR removes the following help text:
```
Note that the command reports allocation failed partitions only when
'partition_autobalancing_mode' is set to 'continuous'. See the current value
using 'rpk cluster config get partition_autobalancing_mode'.
```
https://redpandadata.slack.com/archives/C03GJ5HV8P9/p1704387906405199?thread_ts=1704384519.063189&cid=C03GJ5HV8P9
https://redpandadata.slack.com/archives/C01ND4SVB6Z/p1708664638156689?thread_ts=1708652713.078249&cid=C01ND4SVB6Z
* none
=> rpk: update help text of decommission-status

src/v/redpanda/admin/server.cc, tests/rptest/tests/admin_operations_test.py, tests/rptest/tests/cluster_metadata_upload_test.py
Unwrap the cluster_uuid_t type when formatting the response  
Fixes #16162
* get_cluster_uuid returns a correctly formatted string
=> admin/server: fix get_cluster_id response formatting

src/v/cloud_storage/remote.cc
Looked like the partition was being moved and we were letting an abort error leak out.
* none
Fixes: https://github.com/redpanda-data/redpanda/issues/16726
Fixes: https://github.com/redpanda-data/redpanda/issues/16635
=> Cloud Storage: Ignore abort_requested_exception on shutdown

tests/docker/ducktape-deps/client-swarm, tests/rptest/services/producer_swarm.py, tests/rptest/tests/services_self_test.py
Adds methods for accessing client_swarm's metrics API to the produce_swarm service class.
* none
=> Add support for client_swarm's metrics api to produce_swarm

tests/rptest/clients/python_librdkafka.py, tests/rptest/scale_tests/many_partitions_test.py
Splits methods for native python produce/consume to separate method for reusability. Also makes logger in get_config in librdkafka interface to debug to avoid spamming of info log
* none
=> PESDLC-895 Split produce/consume methods

src/go/rpk/pkg/cli/cloud/byoc/byoc.go, src/go/rpk/pkg/cli/cloud/byoc/install.go, src/go/rpk/pkg/config/params.go, src/go/rpk/pkg/oauth/load.go, src/go/rpk/pkg/oauth/oauth.go
This PR solves a bug that prevented `rpk` to show debug logs when executing `rpk cloud byoc` and adds extra debug logs to the login and plugin download process.
Example:
```
$ rpk cloud byoc aws apply --redpanda-id <my-id> -v 
20:34:39.809  DEBUG  logging in using OAUTH flow
20:34:39.809  DEBUG  using existing authorization token
20:34:39.815  DEBUG  looking for existing byoc plugin  {"exists": false}
20:34:39.815  DEBUG  requesting https://cloud-api.prd.cloud.redpanda.com/api/v1/clusters/<my-id>
20:34:40.899  DEBUG  got response for https://cloud-api.prd.cloud.redpanda.com/api/v1/clusters/<my-id>
20:34:40.899  DEBUG  requesting https://cloud-api.prd.cloud.redpanda.com/api/v1/clusters-resources/install-pack-versions/23.3.xxx
20:34:41.003  DEBUG  got response for …
```
=> rpk: add debug logs to BYOC

src/v/cluster/producer_state_manager.cc, src/v/cluster/producer_state_manager.h, tests/rptest/tests/transactions_test.py
When the producer count is at peak, there could be a heavy churn of producers due to constant eviction which is not reflected by total # of producers alone. Adds a counter that tracks total number of evictions separately.
* Adds observability into producer evictions in each shard.
=> producer_state_manager: add a metric for eviction

src/v/config/node_config.cc, tests/rptest/services/redpanda.py, tests/rptest/services/templates/redpanda.yaml
We already have the reactor stall warnings on in "prod" and arguably the
large allocs are more important as they actually might result in a
crash.
Further the large alloc threshold automatically increases after each
warning so it's unlikely for this to be very spamy.
* Large allocations are now logged by default (similar to reactor stalls)
=> Enable large alloc warnings above 128KiB by default 

src/v/cluster/producer_state_manager.cc, src/v/cluster/producer_state_manager.h, tests/rptest/tests/transactions_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16724
=> [v23.3.x] producer_state_manager: add a metric for eviction

src/v/config/node_config.cc, tests/rptest/services/redpanda.py, tests/rptest/services/templates/redpanda.yaml
Backport of PR https://github.com/redpanda-data/redpanda/pull/16828
=> [v23.3.x] Enable large alloc warnings above 128KiB by default 

src/v/cluster/rm_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16706
=> [v23.3.x] rm_stm/idempotency: fix the producer lock scope

.github/pull_request_template.md
Remove v23.1.x backport option as v23.1.x goes out of support.
* none
=> Remove v23.1 from the PR template.

src/v/cluster/topic_table_probe.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16798
Fixes: https://github.com/redpanda-data/redpanda/issues/16800,
=> [v23.3.x] c/topic_table_probe: use btree_map in topic table probe

src/go/rpk/pkg/cli/profile/create.go
Instead, we will add a timeout to the client
that requests all the information needed to
populate the client
This is to avoid erroring `request context deadline exceeded` after the user took more than 10 seconds to pick their Cluster.
* rpk: Remove 10s timeout in `rpk profile create`
=> rpk: remove timeout for profile create

src/go/rpk/pkg/cli/profile/create.go
We are migrating from cloudv2 -> cloud.
* none
=> rpk: replace web UI url for cloud clusters

src/v/redpanda/admin/server.cc, tests/rptest/tests/admin_operations_test.py, tests/rptest/tests/cluster_metadata_upload_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16183
Fixes: https://github.com/redpanda-data/redpanda/issues/16831,
=> [v23.3.x] admin/server: fix get_cluster_id response formatting

src/v/redpanda/admin/api-doc/security.def.json, src/v/redpanda/admin/api-doc/security.json, src/v/redpanda/admin/security.cc, tests/rptest/services/admin.py, tests/rptest/tests/rbac_test.py
This PR introduces swagger JSON describing Admin API extensions for RBAC. 
Includes stub handlers for the new API surface and stub integration tests.
Closes https://github.com/redpanda-data/core-internal/issues/1103
* none
=> RBAC Admin API Swagger and handler stubs

src/v/cluster/distributed_kv_stm.h, src/v/cluster/distributed_kv_stm_types.h, src/v/cluster/tests/distributed_kv_stm_tests.cc, src/v/redpanda/admin/api-doc/transform.json, src/v/redpanda/admin/server.h, src/v/redpanda/admin/transform.cc, src/v/transform/api.cc, src/v/transform/api.h, src/v/transform/rpc/client.cc, src/v/transform/rpc/client.h, src/v/transform/rpc/deps.cc, src/v/transform/rpc/deps.h, src/v/transform/rpc/rpc.json, src/v/transform/rpc/serde.cc, src/v/transform/rpc/serde.h, src/v/transform/rpc/service.cc, src/v/transform/rpc/service.h, src/v/transform/rpc/tests/transform_rpc_test.cc, tests/rptest/services/admin.py, tests/rptest/tests/data_transforms_test.py
Prior to this patch set - it was not possible to cleanup committed offsets. This means that if lots of transforms were created and then deleted one could run into the limit with no escape hatch. This patch set implements an escape hatch to cleanup offsets.
This is implemented as a manual GC mechanism because this can race with deploys and delete offsets that are still in use. A way to get around that is to expose a max transform id or something from the controller log so that we don't ever delete any ids that the target shard has not yet seen. Since IDs are assigned from the first deploy and their offset within the controller log, we could do this by the committed offset of the controller log. However, instead of implementing that and running it periodically, we just make it a manual …
=> transform: gc committed offsets

src/go/rpk/pkg/adminapi/api_transform.go, src/v/redpanda/admin/transform.cc
Fixes: https://github.com/redpanda-data/redpanda/issues/16643, https://github.com/redpanda-data/redpanda/issues/16810
* Fixed deleting Data Transforms with names that had URL unsafe characters
=> admin/transform/delete: path decode names

src/go/rpk/pkg/cli/transform/buildpack/buildpack.go
Upgrade to the latest tinygo so that our users can use go1.22 with
transforms
Fixes: https://github.com/redpanda-data/redpanda/issues/16771
* Data Transform builds in rpk now uses tinygo v0.31.1
=> rpk/transform/buildpack: upgrade tinygo

cmake/dependencies.cmake
To the latest version so we can upgrade to golang 1.22
* none
=> cmake: upgrade tinygo compiler

src/v/cloud_storage/tests/remote_partition_test.cc, src/v/cloud_storage/tests/util.cc
The test failed ocasionally when the test suite generated replacement segments with the same size as original. The test replaced segments 1:1. 30 segments were replaced with 30 new randomly generated segments. This caused the test to fail ocasionally when the size of the replacment matced the size of the original segment.
This PR fixes that by replacing and merging segments. Every two old segments are replaced with one new. The manifest allows replacement segments to have any size if they are replacing more than one segment so the test can no longer fail this way.
Fixes #15679 
* none
=> cloud_storage: Improve stale_reader test

src/go/rpk/pkg/cli/acl/common.go, src/v/kafka/server/handlers/details/security.h, src/v/security/acl.cc, src/v/security/acl.h, tests/rptest/clients/kafka_cli_tools.py, tests/rptest/tests/kafka_cli_client_compat_test.py, tests/rptest/tests/librdkafka_test.py, tests/rptest/tests/rpk_acl_test.py
This PR introduces a new type of security principal for RBAC. 
Updates `security::to_acl_principal` and `security::to_kafka_principal` to support "Role:" prefix.
Includes a small `rpk` update to respect the "Role:" prefix when creating/deleting ACLs
Closes https://github.com/redpanda-data/core-internal/issues/1100
* none
=> Introduce `principal_type::role`

src/v/transform/logging/CMakeLists.txt, src/v/transform/logging/fwd.h, src/v/transform/logging/log_manager.cc, src/v/transform/logging/log_manager.h, src/v/transform/logging/probes.cc, src/v/transform/logging/probes.h, tests/rptest/tests/data_transforms_test.py
This PR introduces some metrics for transform logging:
logger_probe for tracking metrics specific to individual transform
loggers:
- data_transforms_logger_events_total
- Total # of log events emitted by some transform.
- data_transforms_logger_events_dropped_total
- Total # of some transform's log events that were dropped due
to buffer capacity constraint.
- exported to BOTH /metrics and /public_metrics
manager_probe for tracking metrics generic to the logging::manager:
- data_transforms_log_manager_buffer_usage_ratio
- Current occupancy of the logging::manager's queues as a fraction
of total capacity. [0.0..1.0]
- data_transforms_log_manager_write_errors_total
- Total number of failures to produce log events to the transform
logs topic.
- exported ONLY to /metrics
Closes …
=> Metrics for transform logging

cmake/dependencies.cmake
Backport of PR https://github.com/redpanda-data/redpanda/pull/16857
=> [v23.3.x] cmake: upgrade tinygo compiler

src/go/rpk/pkg/cli/transform/buildpack/buildpack.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/16856
Fixes: https://github.com/redpanda-data/redpanda/issues/16888,
=> [v23.3.x] rpk/transform/buildpack: upgrade tinygo

src/v/raft/state_machine_manager.cc, src/v/raft/state_machine_manager.h, src/v/raft/tests/stm_manager_test.cc, src/v/raft/tests/stm_test_fixture.h
`raft::state_machine_manager` uses background apply fiber to
individually apply batches to state machines which are behind the main
apply fiber. When background apply fiber is active it reads and apply
batches up to current committed offset. When background apply fiber is
active it acquires the mutex. When mutex is acquired the main apply
fiber do not consider the stm as up to date.
The code was prone to very rare race condition as the background apply
was finished in one continuation but the units were release in
subsequent `finally` block. Normally this approach is harmless as the
semaphore is waited for and it will be signalled after the `finally`
fiber is executed. In `state_machine_manager` we only check if the
semaphore is available, this makes the solution vulnerable to timing.
- …
=> Fixed background apply fiber race condition in `raft::state_machine_manager`

src/v/cluster/CMakeLists.txt, src/v/cluster/fwd.h, src/v/cluster/tests/CMakeLists.txt, src/v/cluster/tests/tx_topic_test.cc, src/v/cluster/tx_gateway_frontend.cc, src/v/cluster/tx_gateway_frontend.h, src/v/cluster/tx_topic_manager.cc, src/v/cluster/tx_topic_manager.h, src/v/redpanda/application.cc, src/v/redpanda/application.h
Added possibility to change the `__kafka_internal/tx` topic properties.
The topic properties are reconciled with `cluster::tx_topic_manager`.
Previously changing configuration properties related with `tx` topic
had no effect despite being a properties that did not require restart.
Fixes: https://github.com/redpanda-data/redpanda/issues/16795
- Added ability to change transactional manage topic properties
=> Added support for changing tx topic properties

src/v/wasm/parser/parser.cc, src/v/wasm/parser/parser.h, src/v/wasm/parser/tests/parser_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16722 
Manual changes: fix #includes to 23.3 import paths.
=> [v23.3.x] wasm/parser: bump limits

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/raft/consensus.cc
The property was added as a workaround to a bug, but has since (presumably) gone unused.
I have some upcoming changes to bring offset translation into the storage layer, and this property raises a complication since it allows Raft to start up with a mismatch between the storage log and Raft state. Maintaining the property moving forward would make startup a bit more difficult to reason about, and the property itself doesn't seem particularly safe nonetheless.
This commit removes it outright.
* The `full_raft_configuration_recovery_pattern` cluster config property is now deprecated and will be ignored by Redpanda.
=> raft: remove full_raft_configuration_recovery_pattern config property

src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_segment.cc
Some non-functional changes that I noticed while reading through the read path:
- renames segment readers to `_seg_reader`, rather than `_parent` or `_reader`
- removes some dead code
* none
=> cloud_storage: various non-functional changes

.github/CODEOWNERS, src/v/CMakeLists.txt, src/v/base/CMakeLists.txt, src/v/bytes/include/bytes/bytes.h, src/v/crypto/CMakeLists.txt, src/v/crypto/README.md, src/v/crypto/crypto.cc, src/v/crypto/digest.cc, src/v/crypto/hmac.cc, src/v/crypto/include/crypto/crypto.h, src/v/crypto/include/crypto/exceptions.h, src/v/crypto/include/crypto/types.h, src/v/crypto/internal.h, src/v/crypto/key.cc, src/v/crypto/key.h, src/v/crypto/random.cc, src/v/crypto/signature.cc, src/v/crypto/ssl_utils.cc, src/v/crypto/ssl_utils.h, src/v/crypto/test/CMakeLists.txt, src/v/crypto/test/crypto_test_utils.h, src/v/crypto/test/digest_tests.cc, src/v/crypto/test/hmac_tests.cc, src/v/crypto/test/key_tests.cc, src/v/crypto/test/random_tests.cc, src/v/crypto/test/signature_tests.cc
Implementation of a cryptographic middleware that abstracts away the underlying cryptographic library.
See the [README](https://github.com/redpanda-data/redpanda/pull/src/v/crypto/README.md) for information on how to use the library.
Fixes: https://github.com/redpanda-data/core-internal/issues/1096
This replaces #16752 
* none
=> Crypto lib

src/v/cluster/rm_stm.cc
Reverts redpanda-data/redpanda#16706
We don't have enough evidence that this caused the correctness issue and on the flip side it caused a performance regression. 
- none
=> Revert "rm_stm/idempotency: fix the producer lock scope"

src/v/test_utils/tests/gtest_test.cc
Followup on https://github.com/redpanda-data/redpanda/pull/16637#discussion_r1501150306
* none
=> tests: add test for GTEST_SKIP_CORO

src/v/redpanda/CMakeLists.txt, src/v/redpanda/admin/util.cc, src/v/redpanda/admin/util.h, src/v/redpanda/admin_server.cc, src/v/redpanda/tests/CMakeLists.txt, src/v/redpanda/tests/util_tests.cc, tests/rptest/clients/rpk.py, tests/rptest/tests/rpk_acl_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16694
=> [v23.2.x] admin: fix path param parsing in admin api

src/v/security/CMakeLists.txt, src/v/security/jwt.h, src/v/security/tests/jwt_test.cc
Fixes: https://github.com/redpanda-data/core-internal/issues/1123
* none
=> crypto: Updated jwt to use crypto lib

src/v/transform/logging/CMakeLists.txt, src/v/transform/logging/fwd.h, src/v/transform/logging/log_manager.cc, src/v/transform/logging/log_manager.h, src/v/transform/logging/probes.cc, src/v/transform/logging/probes.h, tests/rptest/tests/data_transforms_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16566 
Closes https://github.com/redpanda-data/redpanda/issues/16895
=> [v23.3.x] Metrics for transform logging

tests/rptest/redpanda_cloud_tests/cloud_self_test.py, tests/rptest/services/redpanda.py, tests/rptest/tests/follower_fetching_test.py
Fixes https://github.com/redpanda-data/core-internal/issues/993
added metrics gathering methods to `RedpandaServiceCloud` that complement the metrics gathering methods in `RedpandaService`:
* `RedpandaServiceCloud.metrics_sample()`
* `RedpandaServiceCloud.metrics_samples()`
* `RedpandaServiceCloud.metric_sum()`
also added simple self tests to verify each of these.
verified with:
```console
ducktape \
--debug \
tests/rptest/redpanda_cloud_tests/cloud_self_test.py::SelfRedpandaCloudTest
```
output:
```
test_id:    rptest.redpanda_cloud_tests.cloud_self_test.SelfRedpandaCloudTest.test_metric_sum
run time:   41.296 …
```
=> PESDLC-109 rptest: add metrics gathering methods to `RedpandaServiceCloud`

src/v/security/CMakeLists.txt, src/v/security/fwd.h, src/v/security/role.cc, src/v/security/role.h, src/v/security/role_store.h, src/v/security/tests/CMakeLists.txt, src/v/security/tests/role_store_bench.cc, src/v/security/tests/role_store_test.cc, src/v/security/types.h
This PR introduces the backing in-memory store for Redpanda Roles Based Access Control (RBAC). Not yet consumed anywhere outside unit tests.
Closes https://github.com/redpanda-data/core-internal/issues/1098
```
$ llvm-cov report ./vbuild/debug/clang/bin/test_kafka_security_rpunit --instr-profile=/tmp/test_kafka_security_rpunit.profdata  -sources src/v/security/role*
Filename                      Regions    Missed Regions     Cover   Functions  Missed Functions  Executed       Lines      Missed Lines     Cover    Branches   Missed Branches     Cover
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
role.cc …
```
=> Introduce RBAC data model

src/v/raft/tests/basic_raft_fixture_test.cc
Added context to assertion that fails when test should fail. The context will help to identify potential issues.
- none
=> r/tests: added context to visible offset validating test assertion

src/v/hashing/CMakeLists.txt, src/v/hashing/include/hashing/secure.h, src/v/net/CMakeLists.txt
Fixes: https://github.com/redpanda-data/core-internal/issues/1121
* none
=> Use cryptolib instead of gnutls for HMAC and secure digests

src/v/cluster/rm_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16907
=> Revert "[v23.3.x] rm_stm/idempotency: fix the producer lock scope"

src/v/cloud_storage/tests/remote_partition_test.cc, src/v/cloud_storage/tests/util.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16853
Fixes: https://github.com/redpanda-data/redpanda/issues/16893,
=> [v23.3.x] cloud_storage: Improve stale_reader test

src/v/raft/state_machine_manager.cc, src/v/raft/state_machine_manager.h, src/v/raft/tests/stm_manager_test.cc, src/v/raft/tests/stm_test_fixture.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16850
=> [v23.3.x] Fixed background apply fiber race condition in `raft::state_machine_manager`

src/v/kafka/server/group.cc, src/v/kafka/server/group.h, src/v/kafka/server/group_manager.cc, src/v/kafka/server/group_manager.h
Consumer groups are removed when a topic that they are related with is removed from topics table. Previously the code cleaning up consumer groups was using a plain `std::vector` to store deltas coming from the `cluster::topics_table` notification. That lead to large allocation. Replaced the `std::vector` with chunked vector to make allocation size controlled.
Fixes: #15946
- none
=> k/group_manager: used chunked_vector when cleaning groups

src/v/cluster/scheduling/leader_balancer.cc, src/v/cluster/scheduling/leader_balancer.h, src/v/cluster/scheduling/leader_balancer_constraints.cc, src/v/cluster/scheduling/leader_balancer_constraints.h, src/v/cluster/scheduling/leader_balancer_greedy.h, src/v/cluster/scheduling/leader_balancer_random.h, src/v/cluster/scheduling/leader_balancer_strategy.h, src/v/cluster/scheduling/leader_balancer_types.h, src/v/cluster/tests/leader_balancer_constraints_test.cc, src/v/cluster/tests/leader_balancer_constraints_utils.h, src/v/cluster/tests/leader_balancer_test.cc
The muted group index was using a `absl::flat_has_set` the use of flat data structure lead to oversized allocation when the number of muted/skipped raft group was large. Replaced a hash set with roaring bitmap. The roaring bitmap is efficient and compressed leading to better performance and smaller allocation.
- preventing large allocation in partition balancer code
=> c/leader_balancer: replaced muted group index with roaring bitmap

src/v/archival/ntp_archiver_service.cc, src/v/cloud_storage/topic_manifest.cc, src/v/cloud_storage/types.h, src/v/cluster/topic_recovery_service.cc, src/v/cluster/types.cc, src/v/cluster/types.h, src/v/compat/cluster_compat.h, src/v/compat/cluster_generator.h, src/v/compat/cluster_json.h, src/v/compat/json.h, src/v/kafka/server/handlers/create_topics.cc, src/v/kafka/server/handlers/describe_configs.cc, src/v/kafka/server/handlers/topics/types.cc, src/v/kafka/server/handlers/topics/types.h, src/v/kafka/server/handlers/topics/validators.h, src/v/model/metadata.h, tests/rptest/clients/types.py, tests/rptest/tests/topic_recovery_test.py, tests/rptest/tests/vcluster_topic_property_test.py, tools/offline_log_viewer/controller.py
Added redpanda.virtual.cluster.id topic property which affiliates the topic with virtual cluster. The property is only settable during topic creation and can not be modified.
- none
=> Added `redpanda.virtual.cluster.id` topic property

src/v/model/transform.cc, src/v/model/transform.h, src/v/ssx/future-util.h, src/v/transform/api.cc, src/v/transform/io.h, src/v/transform/probe.cc, src/v/transform/probe.h, src/v/transform/rpc/tests/transform_rpc_test.cc, src/v/transform/tests/commit_batcher_test.cc, src/v/transform/tests/test_fixture.cc, src/v/transform/tests/test_fixture.h, src/v/transform/tests/transform_processor_test.cc, src/v/transform/transfer_queue.h, src/v/transform/transform_manager.cc, src/v/transform/transform_processor.cc, src/v/transform/transform_processor.h, src/v/wasm/api.h, src/v/wasm/ffi.cc, src/v/wasm/ffi.h, src/v/wasm/tests/wasm_cache_test.cc, src/v/wasm/tests/wasm_fixture.cc, src/v/wasm/tests/wasm_transform_bench.cc, src/v/wasm/transform_module.cc, src/v/wasm/transform_module.h, src/v/wasm/wasmtime.cc
Update the data path of transforms to support multiple output topics, here is a summary of the changes:
- Extend our ABI to add a function that can emit to a specific topic.
- Pass that back from the wasm subsystem to transform subsystem
- Track offsets per output topic, this includes lag metrics.
- Resume from the offset that has the most lag and have other transforms that are ahead suppress duplicates 
Next up we need to support using these new methods in the SDKs, and remove validation in the deploy path that a single output is used. 
* none
=> transform: data path for multiple output topics

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/storage/disk_log_impl.cc, src/v/storage/readers_cache.cc, src/v/storage/readers_cache.h, src/v/storage/tests/CMakeLists.txt, src/v/storage/tests/readers_cache_test.cc
Added size based eviction to `storage::readers_cache`. Previously the
eviction was only time based which may lead to a problem when multiple
readers were created for the same NTP. Now with the size based eviction
the readers cache size is bounded and will not grow indefinitely.
Note on backward compatibility:
Previously the size of cache was unbounded. In this commit we change the
policy to keep up to 200 readers per ntp. This number is still large
enough not cause any issues as it would mean that there are 200
concurrent readers reading a single partition at the same time.
- better control of memory usage in storage layer.
=> Made `storage::readers_cache` size limitted

src/v/crypto/CMakeLists.txt
Will not look for an exact version in the OSS build
Fixes: #16932
Look to https://github.com/redpanda-data/vtools/pull/2552 to see how the exact OpenSSL version is selected
* none
=> crypto/cmake: Fixed exact versioning

src/v/cluster/scheduling/leader_balancer.cc, src/v/cluster/scheduling/leader_balancer.h, src/v/cluster/scheduling/leader_balancer_constraints.cc, src/v/cluster/scheduling/leader_balancer_constraints.h, src/v/cluster/scheduling/leader_balancer_greedy.h, src/v/cluster/scheduling/leader_balancer_random.h, src/v/cluster/scheduling/leader_balancer_strategy.h, src/v/cluster/scheduling/leader_balancer_types.h, src/v/cluster/tests/leader_balancer_constraints_test.cc, src/v/cluster/tests/leader_balancer_constraints_utils.h, src/v/cluster/tests/leader_balancer_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16917
=> [v23.3.x] c/leader_balancer: replaced muted group index with roaring bitmap

src/v/storage/compaction_reducers.cc, src/v/storage/compaction_reducers.h, src/v/storage/disk_log_impl.cc, src/v/storage/fs_utils.cc, src/v/storage/segment_deduplication_utils.cc, src/v/storage/segment_deduplication_utils.h, src/v/storage/segment_utils.cc, src/v/storage/segment_utils.h, src/v/storage/tests/segment_deduplication_test.cc, src/v/storage/tests/utils/disk_log_builder.h
Backport of [#16928](https://github.com/redpanda-data/redpanda/pull/16928)
Fixes https://github.com/redpanda-data/redpanda/issues/16937
Also pulls in https://github.com/redpanda-data/redpanda/pull/16295/commits/5ad9e142b1b9c3d6ee76ced767e324193335a2d9
CONFLICT:
- some reducer code in this branch has a default argument, but not on dev
We were previously using the l-value-variant of
model::record_batch_reader::consume(), which doesn't have a built-in
call to finally(). For a log_reader, this meant that in some scenarios
(e.g. if the reducer were to fail) we could end up not calling
finally(), and therefore wouldn't clear the underlying segment reader.
This is exactly what happened, as we hit:
std::runtime_error (lz4f_compressend:ERROR_dstMaxSize_tooSmall)
errors as we …
=> [v23.3.x] storage: fix windowed compaction error handling

src/v/container/include/container/fragmented_vector.h
Previously `fragment_vector<T>::pow2_floor(size_t size)` wouldn't correctly calculate the nearest power of 2 `<= size`. This resulted in cases such as;
```
sizeof(cluster::topic_status) * chunked_vector<cluster::topic_status>::elems_per_frag <= 128UL * 1024
```
not being true. This PR replaces `pow2_floor` with a standard library equivalent and adds a static assertion to ensure the size of fragments is always `<= 128KiB`.
Fixes https://github.com/redpanda-data/redpanda/issues/16957
* none
=> Ensure `fragment_vector` fragments are always <= 128KiB

.github/workflows/build-redpanda.yml
We would like to be able to manually test a PR against the open source build and this allows that.
* none
=> gha: allow manually dispatching the open source build

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/storage/disk_log_impl.cc, src/v/storage/readers_cache.cc, src/v/storage/readers_cache.h, src/v/storage/tests/CMakeLists.txt, src/v/storage/tests/readers_cache_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16846
Fixes: #16947
=> [v23.3.x] Made `storage::readers_cache` size limited

src/v/utils/fragmented_vector.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16958
Fixes: https://github.com/redpanda-data/redpanda/issues/16964,
=> [v23.3.x] Ensure `fragment_vector` fragments are always <= 128KiB

src/v/cluster/CMakeLists.txt, src/v/cluster/fwd.h, src/v/cluster/tests/CMakeLists.txt, src/v/cluster/tests/tx_topic_test.cc, src/v/cluster/tx_gateway_frontend.cc, src/v/cluster/tx_gateway_frontend.h, src/v/cluster/tx_topic_manager.cc, src/v/cluster/tx_topic_manager.h, src/v/redpanda/application.cc, src/v/redpanda/application.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16797
=> [v23.3.x] Added support for changing tx topic properties

src/v/cluster/plugin_frontend.cc, src/v/cluster/tests/plugin_frontend_validation_test.cc, src/v/transform/api.cc, src/v/wasm/tests/wasi_test.cc, src/v/wasm/wasmtime.cc
The control plane already mostly supports multiple output topics, this patchset removes the last of the validation needed to deploy transforms with multiple outputs. However there are currently no SDKs with support for multiple outputs, so there isn't a way to write tests yet. Those tests will come in followups once the SDKs are updated.
* Data Transforms now support writing to multiple output topics. The `REDPANDA_OUTPUT_TOPIC` environment variable exposed in transforms is now removed for `REDPANDA_OUTPUT_TOPIC_%d` for each output topic specified.
=> transform: multiple output topics control plane

src/v/config/configuration.cc
prev: 100_KiB
new:  500_KiB
Integration tests have started failing due to the buffer being full.
* Increase `data_transforms_logging_buffer_capacity_bytes` from 100KiB to 500KiB
=> config: Increase transform logs buffer cap

src/v/transform/transform_processor.cc, tests/rptest/services/transform_verifier_service.py, tests/rptest/tests/data_transforms_test.py
Fixes: #16955, #16961
(Note it doesn't actually fix anything with #16961, but improves logging, next time we see a related error we'll have better logs to debug).
* none
=> rptest: improve data transform tests

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
Buildkite HTT failure: 12163
* none
This change should make sure that HTT tests pass when checking for cluster replicas status. Based on logs, 10 minutes seems to be not enough.
This change should make sure that HTT tests pass when checking for cluster replicas status. Based on logs, 10 minutes seems to be not enough.
[INFO - 2024-03-07 06:11:53,073 - high_throughput_test - _stage_add_and_decommission - lineno:1259]: scaling out cluster rp-cnkk9q2vmreg2bvgr9jg from 3 to 4 [INFO - 2024-03-07 06:11:53,645 - high_throughput_test - _stage_add_and_decommission - lineno:1264]: waiting for cluster rp-cnkk9q2vmreg2bvgr9jg to have ready replicas 4 ... ... [INFO - 2024-03-07 06:21:58,549 - kubectl - _cmd - lineno:161]: Command failed (rc=1). --------- stdout ----------- --------- stderr ----------- …
=> increased a timeout for cluster replicas

tests/rptest/tests/cloud_retention_test.py
Fix retention test. Previously, the throughput parameter was passed to the parameter that limited max number of messages. Because of that the test was only able to consume fixed number of messages in CDT. This commit fixes this and improves few other aspects (error handling and logging).
Fixes #15893 
* none
=> rptest: Fix cloud_retention_test

src/v/crypto/digest.cc, src/v/crypto/hmac.cc, src/v/crypto/signature.cc
Otherwise they still see an incomplete type.
Spotted with Clang 18
* none
=> crypto: Move special members after impl definition

src/v/io/tests/common.cc, src/v/kafka/client/test/partitioners.cc, src/v/kafka/server/handlers/handler_probe.cc, src/v/kafka/server/tests/offset_for_leader_epoch_utils.cc, src/v/kafka/server/tests/produce_consume_test.cc, src/v/pandaproxy/schema_registry/validation.cc, src/v/raft/configuration_manager.cc, src/v/raft/consensus_utils.cc, src/v/redpanda/admin/security.cc, src/v/redpanda/admin/server.cc, src/v/rpc/connection_cache.cc, src/v/utils/tests/retry_test.cc
=> treewide: Address some warnings

src/v/cloud_storage/tests/topic_recovery_service_test.cc, src/v/cluster/cloud_metadata/cluster_recovery_backend.cc, src/v/cluster/cluster_utils.cc, src/v/cluster/cluster_utils.h, src/v/cluster/service.cc, src/v/cluster/service.h, src/v/cluster/tests/autocreate_test.cc, src/v/cluster/tests/cluster_test_fixture.h, src/v/cluster/tests/controller_api_tests.cc, src/v/cluster/tests/health_monitor_test.cc, src/v/cluster/tests/metadata_dissemination_test.cc, src/v/cluster/tests/serialization_rt_test.cc, src/v/cluster/topic_recovery_service.cc, src/v/cluster/topics_frontend.cc, src/v/cluster/topics_frontend.h, src/v/cluster/types.cc, src/v/cluster/types.h, src/v/compat/check.h, src/v/compat/cluster_compat.h, src/v/compat/cluster_generator.h, src/v/kafka/server/handlers/configs/config_utils.h, src/v/kafka/server/handlers/topics/topic_utils.h, src/v/redpanda/tests/fixture.h, src/v/test_utils/randoms.h
Convert some types from `std::vector` to `chunked_vector` to avoid oversize allocations
* `topic_configuration` (392 bytes)
* `custom_assignable_topic_configuration` (416 bytes)
* `topic_properties_update` (456 bytes)
Fixes #16758 
* cluster: Avoid oversize allocs for topic creation and configuration
=> cluster: Avoid oversize allocs for topic creation and configuration

src/go/rpk/pkg/cli/transform/deploy.go, src/go/rpk/pkg/cli/transform/project/project.go
* `rpk transform deploy` now supports multiple output topics
=> rpk/transform/deploy: support deploying to multiple output topics

src/v/net/connection.cc
Fixes: #16901
* Added `EHOSTUNREACH` to retry-able error code list
=> net: Added EHOSTUNREACH to retry list

tests/docker/ducktape-deps/ocsf-server
Fixes [error](https://buildkite.com/redpanda/redpanda/builds/45869#018e20ad-5d8b-4717-b1ae-a5867d5cf343/6-11976):
```
Cannot allocate 976733209832459912 bytes of memory (of type "heap_frag").
Crash dump is being written to: erl_crash.dump...beam/erl_term.h:1492:tag_val_def() Assertion failed: tag_val_def error
./build_server.sh: line 4: 34609 Aborted                 (core dumped) MIX_ENV=prod mix do deps.get, deps.compile
```
Using temp workaround: https://github.com/erlang/otp/issues/8238#issuecomment-1987173291
related issue: https://redpandadata.atlassian.net/browse/PESDLC-948
* none
=> ducktape: temp fix for erlang 26.2.3 arm

src/v/cluster/controller.cc, src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_types.cc, src/v/cluster/health_monitor_types.h, src/v/cluster/scheduling/leader_balancer.cc, src/v/cluster/scheduling/leader_balancer.h, src/v/features/feature_table.cc, src/v/features/feature_table.h, tests/rptest/tests/leadership_transfer_test.py
After node-local partition-core assignment becomes enabled, we can no longer rely on global replica shard info from the topic table. Use shard info from the health report instead.
* none
=> Prepare leader_balancer for node-local core assignment

src/v/net/connection.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16902
Fixes: https://github.com/redpanda-data/redpanda/issues/16995,
=> [v23.2.x] net: Added EHOSTUNREACH to retry list

src/v/cloud_storage/tests/topic_recovery_service_test.cc, src/v/cluster/cloud_metadata/cluster_recovery_backend.cc, src/v/cluster/cluster_utils.cc, src/v/cluster/cluster_utils.h, src/v/cluster/service.cc, src/v/cluster/service.h, src/v/cluster/tests/autocreate_test.cc, src/v/cluster/tests/cluster_test_fixture.h, src/v/cluster/tests/controller_api_tests.cc, src/v/cluster/tests/health_monitor_test.cc, src/v/cluster/tests/metadata_dissemination_test.cc, src/v/cluster/tests/serialization_rt_test.cc, src/v/cluster/topic_recovery_service.cc, src/v/cluster/topics_frontend.cc, src/v/cluster/topics_frontend.h, src/v/cluster/types.cc, src/v/cluster/types.h, src/v/compat/check.h, src/v/compat/cluster_compat.h, src/v/compat/cluster_generator.h, src/v/kafka/server/handlers/configs/config_utils.h, src/v/kafka/server/handlers/topics/topic_utils.h, src/v/redpanda/tests/fixture.h, src/v/test_utils/randoms.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16982
Fixes: https://github.com/redpanda-data/redpanda/issues/16993
=> [v23.3.x] cluster: Avoid oversize allocs for topic creation and configuration

src/v/redpanda/admin/server.cc
When deploying a data transform, the input and output topics must
already exist. Currently the validation catches this error, but the
result is a 500, when it should be a 400.
* Return a HTTP 400 error code when deploying a transform to a topic that doesn't exist instead of a 500
=> admin/transform: 400 for missing topics

src/v/cluster/commands.h, src/v/cluster/controller.cc, src/v/cluster/controller.h, src/v/cluster/controller_log_limiter.h, src/v/cluster/errc.h, src/v/cluster/security_frontend.cc, src/v/cluster/security_frontend.h, src/v/cluster/security_manager.cc, src/v/cluster/security_manager.h, src/v/cluster/tests/CMakeLists.txt, src/v/cluster/tests/security_frontend_test.cc, src/v/cluster/types.h, src/v/features/feature_table.cc, src/v/features/feature_table.h, src/v/kafka/server/errors.h, src/v/model/model.cc, src/v/model/record_batch_types.h
This PR introduces a new record batch type for replicated management of the in-memory `role_store`
`model::record_batch_type::role_management_cmd` governs four new controller commands:
- `create_role_cmd`
- `delete_role_cmd`
- `update_role_cmd`
- `rename_role_cmd`
Includes integration of the role_store itself into `cluster::controller`, `cluster::security_manager` as a sharded service, handlers for the commands, and `cluster::security_frontend` API.
Also includes a feature gate for the new commands (`feature::role_based_access_control`) and a fixture test for the whole kit.
Closes https://github.com/redpanda-data/core-internal/issues/1099
* Introduce `feature::role_based_access_control`
=> Cluster integration for `role_store` and related structures.

src/v/cluster/cloud_metadata/offsets_recovery_service.h, tests/rptest/tests/recovery_mode_test.py
In a mixed-mode clusters RPC requests for uploading consumer offsets to cloud storage could be issued from a node in normal mode to a node in recovery mode. Previously this resulted in a segfault.
* Fix a crash that happened when a cluster that was partially in recovery mode tried to upload consumer offsets to cloud storage.
=> Fix a segfault when recovery mode is partially enabled

src/go/rpk/pkg/cli/redpanda/config.go, src/go/rpk/pkg/cli/redpanda/config_test.go, src/go/rpk/pkg/config/config.go, tests/rptest/tests/rpk_start_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16652
Fixes: https://github.com/redpanda-data/redpanda/issues/16941,
=> [v23.3.x] rpk: support advertised addresses in `rpk redpanda config bootstrap`

tests/docker/ducktape-deps/ocsf-server
Follow-on to PR #17000
Addresses https://redpandadata.atlassian.net/browse/PESDLC-960
* none
=> ducktape: lint ocsf-server

src/v/cluster/tests/rebalancing_tests_fixture.h, src/v/cluster/tests/topic_table_test.cc, src/v/cluster/tests/topic_updates_dispatcher_test.cc, src/v/cluster/topic_table.cc, src/v/cluster/topic_table.h, src/v/container/CMakeLists.txt, src/v/container/include/container/contiguous_range_map.h, src/v/container/tests/CMakeLists.txt, src/v/container/tests/bench_utils.h, src/v/container/tests/contiguous_range_map_test.cc, src/v/container/tests/map_bench.cc, src/v/container/tests/vector_bench.cc
A set of partition ids in each topic is a monotonically increasing sequence of numbers without gaps. This allows us to use a vector instead of an associative container to keep the partition metadata in topics table. Usage of `chunked_vector` prevents large memory allocations.
Fixes: #15610
```
test                             iterations      median         mad         min         max      allocs       tasks        inst
full_1000.SequentialFill           15959000    36.492ns     0.017ns    36.431ns    36.539ns       3.587       0.000       520.6
full_1000.RandomFill                8883000    70.880ns     0.036ns    70.844ns    70.952ns       3.587       0.000       448.6
full_1000.LookUp                    1622000    27.718ns     0.028ns    27.687ns    27.756ns       0.000       0.000 …
```
=> c/topic_table: replaced partition metadata map with chunked_vector

src/transform-sdk/go/transform/abi.go, src/transform-sdk/go/transform/doc.go, src/transform-sdk/go/transform/example_validation_test.go, src/transform-sdk/go/transform/processor.go, src/transform-sdk/go/transform/sdk.go, src/transform-sdk/go/transform/serialize.go, src/transform-sdk/go/transform/serialize_test.go, src/transform-sdk/go/transform/stub_abi.go
Add support for the new method to write options in v2 of the broker's
ABI. This includes specifying write options in the RecordWriter
interface that can then be used to call the new writeRecordWithOptions
method with the specified topic name.
* The golang transform-sdk gains the ability to write to multiple output topics.
This feature can only be used in Redpanda v24.1.x or newer.
=> transform-sdk/go: add support for multiple output topics

src/v/crypto/include/crypto/exceptions.h, src/v/crypto/ssl_utils.h
=> crypto: Cleanup includes

tests/rp_cloud_cleanup.py
CDT tests are failing for GCP, since cleanup stage uses AWS specific implementation. It is used only for log message, so commenting it out to get tests running again
* none - not a bug fix
* none
CDT tests are failing for GCP, since cleanup stage uses AWS specific implementation. It is used only for log message, so commenting it out to get tests running again
=> Commented out this log info since it is AWS specific and affects GCP

src/v/cloud_storage/inventory/aws_ops.cc, src/v/cloud_storage/inventory/aws_ops.h, src/v/cloud_storage/inventory/inv_ops.cc, src/v/cloud_storage/inventory/inv_ops.h, src/v/cloud_storage/inventory/tests/CMakeLists.txt, src/v/cloud_storage/inventory/tests/common.h, src/v/cloud_storage/inventory/tests/create_inventory_config_test.cc, src/v/cloud_storage/inventory/tests/fetch_report_tests.cc, src/v/cloud_storage/inventory/types.cc, src/v/cloud_storage/inventory/types.h, src/v/cloud_storage/remote.cc, src/v/cloud_storage/remote.h, src/v/cloud_storage/types.cc, src/v/cloud_storage/types.h
Adds a utility to scan through all the dates available for a given inventory config and find the latest report which has been generated and is ready for download.
Returns the path to manifest describing the report found as well as report paths and the datetime.
The caller can then use the metadata to download the actual report.
* none
=> cst/inv: locate latest report

tests/rptest/scale_tests/many_topics_test.py
Ducktape uses method naming to decide what is a test and our ManyTopicsTest had a _lifecycle_test method which is a helper called by tests and not a standalone test itself, but DT will call it as a standalone test causing a CI failure.
Rename it to _lifecycle_test_impl to avoid this.
Fixes #17040.
* none
=> rptest: fix _lifecycle_test naming

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/kafka/server/snc_quota_manager.cc, src/v/kafka/server/snc_quota_manager.h, src/v/kafka/server/tests/produce_consume_test.cc, src/v/redpanda/application.cc, src/v/redpanda/application.h, src/v/ssx/sharded_ptr.h, src/v/ssx/tests/CMakeLists.txt, src/v/ssx/tests/sharded_ptr_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16441
Fixes: https://github.com/redpanda-data/redpanda/issues/16815
=> [v23.3.x] Improve throughput throttling

src/v/cluster/cloud_metadata/offsets_recovery_manager.cc, src/v/cluster/cloud_metadata/offsets_recovery_service.h, src/v/cluster/controller_backend.cc, src/v/cluster/distributed_kv_stm.h, src/v/cluster/leader_router.h, src/v/cluster/partition_recovery_manager.cc, src/v/cluster/rm_stm.cc, src/v/cluster/self_test/netcheck.cc, src/v/cluster/service.cc, src/v/cluster/tests/partition_balancer_planner_fixture.h, src/v/cluster/tests/partition_balancer_planner_test.cc, src/v/cluster/tests/partition_balancer_simulator_test.cc, src/v/cluster/tests/topic_updates_dispatcher_test.cc, src/v/cluster/topic_recovery_service.cc, src/v/cluster/tx_gateway_frontend.cc, src/v/raft/tests/offset_translator_tests.cc
=> raft|cluster: Address some warnings

src/v/storage/segment.cc, src/v/storage/tests/storage_e2e_test.cc
This change is similar to
https://github.com/redpanda-data/redpanda/pull/1826 but for stable offsets this time.
* none
=> storage: ensure monotonic stable offset updates

tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/utils/si_utils.py
Improvements to internal high thougput tests to be able to specify and count topic-specific segments
* none
This is internal testing HTT and release notes not required.
NOTE: This has NOT been tested locally yet. I would need to pull this code to my AWS EC2 instance and test it. Submitting PR for initial discussion and comments
=> Add an option to specify topic name for nodes_report_cloud_segments

src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h, src/v/pandaproxy/schema_registry/storage.h, src/v/pandaproxy/schema_registry/store.h, src/v/pandaproxy/schema_registry/test/consume_to_store.cc, src/v/pandaproxy/schema_registry/types.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/17091
=> [v23.2.x] schema_registry: Override soft-delete checks for consume_to_store

src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h, src/v/pandaproxy/schema_registry/storage.h, src/v/pandaproxy/schema_registry/store.h, src/v/pandaproxy/schema_registry/test/consume_to_store.cc, src/v/pandaproxy/schema_registry/types.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/17091
=> [v23.3.x] schema_registry: Override soft-delete checks for consume_to_store

src/v/storage/segment.cc
Register the inflight write before calling append on the segment. Append
may dispatch a background write and a subsequent call to
`maybe_advance_stable_offset` before the append continuation may run.
This was happening in CI when running with a RAM disk (very fast
storage).
When appender advances stable offset, a callback for advancing stable
stable offset at segment level is also called,
`segment::advance_stable_offset`. This method uses the inflight writes
to determine how far the segment stable offset can be advanced. Because
the last inflight write wasn't registered yet, the stable offset can get
stuck.
In theory, because we use the segment stable offset as reader upper
bound, this can lead to a situation where acked data is not visible and
worse consequences.
* none
=> storage: assert no inflight writes when closing segment

src/v/cluster/tests/rebalancing_tests_fixture.h, src/v/cluster/tests/topic_table_test.cc, src/v/cluster/tests/topic_updates_dispatcher_test.cc, src/v/cluster/topic_table.cc, src/v/cluster/topic_table.h, src/v/utils/contiguous_range_map.h, src/v/utils/tests/CMakeLists.txt, src/v/utils/tests/bench_utils.h, src/v/utils/tests/contiguous_range_map_test.cc, src/v/utils/tests/map_bench.cc, src/v/utils/zip.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16919
=> [v23.3.x] c/topic_table: replaced partition metadata map with chunked_vector

src/v/cloud_storage_clients/s3_client.cc
Seen random_node_operations_test
```
<BadLogLines nodes=ip-172-31-1-9(1) example="ERROR 2024-03-14 11:55:32,224 [shard 0:au  ] s3 - s3_client.cc:469 - Accessing panda-bucket-b3a2fc8c-e1f8-11ee-8182-c3cdd68eb941, unexpected REST API error "" detected, code: RequestTimeout, request_id: E6840FAB839FF7F5, resource:">
```
* none
=> cloud_storage_clients: classify request_timeout as retriable

tests/rptest/test_suite_ec2.yml
https://github.com/redpanda-data/redpanda/issues/16818 it's unstable for now (and requires more hardware I think)
* none
=> test: Don't run MTT in CDT

src/v/crypto/crypto.cc, src/v/crypto/hmac.cc, src/v/crypto/internal.h, src/v/crypto/ssl_utils.h, src/v/crypto/test/CMakeLists.txt, src/v/crypto/test/crypto_bench.cc
This change improves the performance of the crypto library by pre-fetching the MD and HMAC operations.
See the performance section in [OpenSSL's docs](https://www.openssl.org/docs/man3.1/man7/crypto.html#performance)
Fixes: https://github.com/redpanda-data/core-internal/issues/1152
Fixes: https://github.com/redpanda-data/core-internal/issues/1154
[CORE-8]
* none
[CORE-8]: https://redpandadata.atlassian.net/browse/CORE-8?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CORE-6: Pre-fetching algorithms

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
This is a HTT cloud type check for:
https://github.com/redpanda-data/core-internal/issues/990
This test was designed for BYOC only, and code already has a message:
Using it against FMC clouds will cause it to fail as
there is no access to S3 account that is used inside
cloudv2 API to create/update buckets and its
properties/policies
This improvement would check if test is being executed on FMC and show a warning in logs as well is would not be executed
* none
* See above
=> Check cloud type and do not run if FMC

src/go/rpk/pkg/cli/cloud/login.go, src/go/rpk/pkg/cli/profile/create.go, src/go/rpk/pkg/cli/profile/profile.go, src/go/rpk/pkg/config/params.go, src/go/rpk/pkg/oauth/load.go, src/go/rpk/pkg/oauth/load_test.go
* Deletes some old logic that avoided prompting if only one cluster existed
* Made some testing branch _much_ more foolproof. Turns out we use an empty cloud URL always, which then defaults to prod inside the cloud API package.
* none
=> rpk profile: a few more fixes

src/v/cluster/tests/tx_compaction_utils.h, src/v/storage/compaction_reducers.cc, src/v/storage/segment_utils.h
This is a select backport of commit from https://github.com/redpanda-data/redpanda/pull/16295
Fixes: https://github.com/redpanda-data/redpanda/issues/16679
* Retains control batches from transactions to preserve transaction boundaries. This prevents some (very unlikely) scenarios where aborted data is read.
=> [backport][v23.3.x] tx/compaction: don't deduplicate control batches

src/go/rpk/pkg/cli/cloud/login.go, src/go/rpk/pkg/cli/profile/create.go, src/go/rpk/pkg/cli/profile/profile.go, src/go/rpk/pkg/config/params.go, src/go/rpk/pkg/oauth/load.go, src/go/rpk/pkg/oauth/load_test.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/17117
=> [v23.3.x] rpk profile: a few more fixes

src/v/cluster/partition_leaders_table.cc, src/v/cluster/partition_leaders_table.h, src/v/utils/contiguous_range_map.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/17092
=> [v23.3.x] Using `contiguous_range_map` in `partition_leaders_table`

.github/workflows/transform-sdk-build.yml, src/transform-sdk/cpp/.clang-tidy, src/transform-sdk/cpp/.gitignore, src/transform-sdk/cpp/CMakeLists.txt, src/transform-sdk/cpp/README.md, src/transform-sdk/cpp/examples/CMakeLists.txt, src/transform-sdk/cpp/examples/identity.cc, src/transform-sdk/cpp/include/redpanda/transform_sdk.h, src/transform-sdk/cpp/src/transform_sdk.cc
Add experimental C++ SDK. It's currently not going to be more formally supported in docs or RPK at the moment.
Most of the implementation here falls out from mirroring similar patterns from the Rust SDK.
* none
=> transform-sdk: experimental C++ support

src/v/cloud_storage_clients/s3_client.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17101
=> [v23.3.x] cloud_storage_clients: classify request_timeout as retriable

tests/rptest/remote_scripts/topic_operations.py
When script is creating >2k topics in one batch and Broker coaches - resulting error message contains whole topic creation request, which is very long. Trim it at 512 chars per formatted exception line to preserve actual proper traceback.
* none
=> PESDLC-983 Trim errors and add Broker exception

src/v/container/include/container/interval_set.h, src/v/container/tests/CMakeLists.txt, src/v/container/tests/interval_set_test.cc
This adds an interval_set class, similar to interval_map with a couple key differences:
- it is a set type, and only tracks the intervals rather than an additional value type
- it supports inserting overlapping intervals by coalescing them
This will be a used in an upcoming change to track regions within a file to skip over, which will be key to a append-only log implementation that truncates by appending metadata to the log.
The structure and some of the implementation of the interval_set is copied directly from interval_map, though the insert() method is significantly different, given the above behavioral differences.
* none
=> container: add interval_set

tests/rptest/tests/leadership_transfer_test.py
The test is failing in debug mode as raft RPCs are timing out,
presumably due to slow debug build and large partition count. Reduced
the # of topics when running in debug mode.
* none
=> ducktape: deflake test_topic_aware_rebalance in debug mode 

src/v/compression/internal/lz4_frame_compressor.cc
Before this change the code assumed that the destination temp. buffer always had enough free space for `LZ4F_compressEnd` operation. This change checks the free size before calling `LZ4F_compressEnd` and allocates a new buffer if necessary.
Note that the free space required is computed using `LZ4F_compressBound` with a `srcSize` of 0. By looking at `LZ4F_compressEnd` code, it may seem as if we can just check if 12 bytes are free in the destination buffer, whereas `LZ4F_compressBound` always assumes at least 65443 ie 65535 + block header size (4) + frame footer (4) possibly resulting in much larger allocation.
However, lz4frame docstring for `LZ4F_compressBound` states that:
> When srcSize==0, LZ4F_compressBound() provides an upper bound for LZ4F_flush() and LZ4F_compressEnd() instead. …
=> compression: Allocate memory for LZ4_compressEnd

.github/workflows/transform-sdk-release.yml, src/transform-sdk/go/transform/sr/client.go, src/transform-sdk/rust/Cargo.lock, src/transform-sdk/rust/Cargo.toml, src/transform-sdk/rust/core-sys/Cargo.toml, src/transform-sdk/rust/core-sys/src/lib.rs, src/transform-sdk/rust/core-sys/src/serde.rs, src/transform-sdk/rust/core-types/src/lib.rs, src/transform-sdk/rust/scripts/publish.py, src/transform-sdk/rust/sr-sys/Cargo.toml, src/transform-sdk/rust/sr-sys/README.md, src/transform-sdk/rust/sr-sys/src/abi.rs, src/transform-sdk/rust/sr-sys/src/lib.rs, src/transform-sdk/rust/sr-sys/src/serde.rs, src/transform-sdk/rust/sr-sys/src/stub_abi.rs, src/transform-sdk/rust/sr-types/Cargo.toml, src/transform-sdk/rust/sr-types/README.md, src/transform-sdk/rust/sr-types/src/lib.rs, src/transform-sdk/rust/sr/Cargo.toml, src/transform-sdk/rust/sr/README.md, src/transform-sdk/rust/sr/src/lib.rs, src/transform-sdk/rust/varint/Cargo.toml, src/transform-sdk/rust/varint/src/lib.rs
Fixes: https://github.com/redpanda-data/redpanda/issues/16075
* Data Transform's Rust SDK now supports a Schema Registry Client.
=> Data Transforms Schema Registry Rust SDK

src/v/compression/internal/lz4_frame_compressor.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17156
=> [v23.3.x] compression: Allocate memory for LZ4_compressEnd

src/v/compression/internal/lz4_frame_compressor.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17156
=> [v23.2.x] compression: Allocate memory for LZ4_compressEnd

src/v/cluster/archival_metadata_stm.cc, src/v/cluster/log_eviction_stm.cc, src/v/cluster/rm_stm.cc, src/v/cluster/tm_stm.cc, src/v/cluster/tm_stm.h, src/v/config/configuration.cc, src/v/kafka/protocol/schemata/produce_request.json, src/v/kafka/server/handlers/produce.cc, src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/group_manager.cc, src/v/raft/group_manager.h, src/v/raft/recovery_stm.cc, src/v/raft/replicate.h, src/v/raft/replicate_batcher.cc, src/v/raft/replicate_batcher.h, src/v/raft/replicate_entries_stm.cc, src/v/raft/replicate_entries_stm.h, src/v/raft/tests/CMakeLists.txt, src/v/raft/tests/basic_raft_fixture_test.cc, src/v/raft/tests/raft_fixture.cc, src/v/raft/tests/raft_fixture.h, src/v/raft/tests/simple_raft_fixture.h, src/v/raft/vote_stm.cc, src/v/redpanda/application.cc, tests/rptest/tests/raft_periodic_flush_test.py, tests/rptest/tests/simple_e2e_test.py, tests/rptest/tests/write_caching_test.py
Implements raft side of things for write caching. Summary of changes
* Decouples flush decision from acks level. Currently quorum_ack requests are automatically flushed. 
* Implement background flushing based on flush.ms/bytes
* Preliminary test coverage in unit tests / ducktape.
Next set of patches:
* More tests (failure injection, node_operations)
* Metrics/instrumentation.
* raft_flush_timer_interval_ms is deprecated, use raft_replica_max_flush_delay_ms instead. The latter supports periodic flushing for any un flushed bytes and carries the same default as raft_flush_timer_interval_ms.
=> write caching - raft implementation

src/v/redpanda/admin/security.cc, src/v/redpanda/admin/server.h, tests/rptest/tests/rbac_test.py
This implements the `create_role_handler` which will allow the creation of
an empty role to which users can later be assigned to.
Closes https://github.com/redpanda-data/core-internal/issues/1104
* none
=> admin: implement create role API

tests/rptest/services/machinetype.py
=> test: Add n2d-standard-32 machinetype

src/go/rpk/pkg/cli/cloud/auth/use.go, src/go/rpk/pkg/cli/profile/create.go, src/go/rpk/pkg/cli/profile/rename.go, src/go/rpk/pkg/cli/profile/use.go, src/go/rpk/pkg/config/params.go, src/go/rpk/pkg/config/rpk_yaml.go, src/go/rpk/pkg/oauth/load.go
=> rpk profile double pointer fixes

tests/docker/ducktape-deps/omb
Current version is quite outdated and missing some of recent improvements (e.g.: client stats)
* none
=> tests: Update OMB version on CDT

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
HTT.test_disrupt_cloud_storage stage_block_s3 may not create cloud segments #989
This check should be topic-specific
- [X ] none - not a bug fix
* none
We recently added an option to specify topic name when we get segments. Some tests were already updated as part of that work GH ticket:
https://github.com/redpanda-data/redpanda/pull/16925
This is another place where we use `nodes_report_cloud_segments` in HTT, so this should close our 
https://github.com/redpanda-data/core-internal/issues/989
=> added topic parameter

src/v/archival/ntp_archiver_service.h
Fixed a typo in `ntp_archiver_service.h` as a first task! 
- None
=> Fixed typo in comment in ntp_archiver

tests/docker/Dockerfile, tests/docker/ducktape-deps/python-deps, tests/docker/ducktape-deps/tool-pkgs
- Creates a venv in /opt/.ducktape-venv that is used for ducktape installation
- Adds /opt/.ducktape-venv/bin to global path so all shells will utilize the venv for python operations
- Conditionally install python3.10 from deadsnakes ppa if installation script detects that Ubuntu OS in use is 20.04
* none
=> CORE-20: Use a venv to install and use ducktape

src/v/storage/batch_cache.cc, src/v/storage/batch_cache.h, src/v/storage/disk_log_impl.cc, src/v/storage/log_manager.h, src/v/storage/log_reader.cc, src/v/storage/segment.cc, src/v/storage/segment.h, src/v/storage/tests/batch_cache_reclaim_test.cc, src/v/storage/tests/batch_cache_test.cc, src/v/storage/tests/common.h, src/v/storage/tests/storage_e2e_test.cc, src/v/storage/tests/storage_test_fixture.h
Cover letter is in the first commit of the PR https://github.com/redpanda-data/redpanda/pull/16954/commits
* none
=> storage: support dirty entries in batch cache

src/v/cluster/controller.cc, src/v/cluster/feature_manager.cc, src/v/cluster/feature_manager.h, src/v/cluster/metrics_reporter.cc, src/v/cluster/metrics_reporter.h, tests/rptest/tests/metrics_reporter_test.py, tests/rptest/tests/rbac_test.py
First 2 commits are from https://github.com/redpanda-data/redpanda/pull/17089
* none
=> rbac: Add Telemetry and Licence nag

src/v/cluster/cloud_metadata/tests/uploader_test.cc, src/v/cluster/config_frontend.cc, src/v/cluster/config_frontend.h, src/v/cluster/config_manager.cc, src/v/cluster/metrics_reporter.cc, src/v/cluster/service.cc, src/v/kafka/server/handlers/incremental_alter_configs.cc, src/v/kafka/server/tests/alter_config_test.cc, src/v/redpanda/admin/server.cc
Various places in the code were calling do_patch directly without regard
to the requirement that do_patch has to be called on the controller
shard.
This caused a fixture test to fail because it tried to invoke do_patch
on all shards and this violates the assertion in do_patch of
config_frontend.cc, causing it to fail with the error message "Must be
called on version_shard".
This fixes it by changing config_fronter::patch() to invoke do_patch on
the controller shard, and moving all calls of do_patch to call patch
instead.
* Fixes a bug of config_frontend methods getting called on shards other than the controller shard.
=> cluster: invoke config_frontend methods on controller shard

.gitignore
This is where ./tools/dev-cluster.py writes data by default if you run it from the root
* none
=> git: ignore top level data/ dir

src/v/wasm/wasi.cc
When simplifying updating the wasi logging code, we missed setting the number of written bytes.
Fix that so that write doesn't continue to try to write in a loop.
I will followup with some tests here, but wanted to get this out.
* Fix a bug where logging in a transform could cause the transform to not make progress.
=> wasm/wasi: properly return number of written bytes

src/v/cloud_roles/refresh_credentials.cc, src/v/compat/tests/compat_test.cc, src/v/storage/tests/storage_e2e_test.cc
A couple creeped in because we weren't crashing on UBSAN diagnostics for a while. That is being fixed too in https://github.com/redpanda-data/redpanda/pull/17027
* none
=> Fix UBSAN diagnostics

src/v/archival/archival_policy.cc
archival::candidate_creation_error enum is also used in codepaths specifics to non-compacted topics.
this commit removes the word "compacted" to remove confusion when reading WARN or ERROR log lines relative to non-compacted topics
* better ERROR|WARN messages for candidate_creation_error
=> archival/archival_policy: change operator<< for candidate_creation_error

.clang-tidy
This was deprecated in clang-tidy-16 and removed in v18, see: https://github.com/llvm/llvm-project/issues/62020
* none
=> clang-tidy: remove deprecated option

src/v/io/tests/io_queue_test.cc, src/v/io/tests/scheduler_test.cc
New in clang-tidy-17
https://clang.llvm.org/extra/clang-tidy/checks/bugprone/empty-catch.html
* none
=> io/tests: fix bugprone-empty-catch

src/v/cluster/config_frontend.cc, src/v/cluster/config_frontend.h, src/v/cluster/config_manager.cc, src/v/cluster/metrics_reporter.cc, src/v/cluster/service.cc, src/v/kafka/server/handlers/incremental_alter_configs.cc, src/v/kafka/server/tests/alter_config_test.cc, src/v/redpanda/admin_server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17088
=> [v23.2.x] cluster: invoke config_frontend methods on controller shard

src/v/raft/coordinated_recovery_throttle.cc
Adds a new public metric `redpanda_raft_recovery_partition_movement_consumed_bandwidth`  for recovery throttle that tracks how much bandwidth is consumed for raft recovery.
This is more useful because it helps tune raft_learner_recovery_rate. If the entire bandwidth is in use, time to bump recovery rate.
With this change, `partition_movement_available_bandwidth` is obsolete but retaining it so we donot break the public metrics contract. 
*  Adds a new public metric redpanda_raft_recovery_partition_movement_consumed_bandwidth that tracks how much bandwidth is currently in use for raft recovery.  This helps tune raft_learner_recovery_rate.
=> raft/recovery: better metric for recovery bandwidth consumption

src/transform-sdk/go/transform/sr/client.go, src/transform-sdk/rust/Cargo.lock, src/transform-sdk/rust/Cargo.toml, src/transform-sdk/rust/core-sys/Cargo.toml, src/transform-sdk/rust/core-sys/src/lib.rs, src/transform-sdk/rust/core-sys/src/serde.rs, src/transform-sdk/rust/core-types/src/lib.rs, src/transform-sdk/rust/scripts/publish.py, src/transform-sdk/rust/sr-sys/Cargo.toml, src/transform-sdk/rust/sr-sys/README.md, src/transform-sdk/rust/sr-sys/src/abi.rs, src/transform-sdk/rust/sr-sys/src/lib.rs, src/transform-sdk/rust/sr-sys/src/serde.rs, src/transform-sdk/rust/sr-sys/src/stub_abi.rs, src/transform-sdk/rust/sr-types/Cargo.toml, src/transform-sdk/rust/sr-types/README.md, src/transform-sdk/rust/sr-types/src/lib.rs, src/transform-sdk/rust/sr/Cargo.toml, src/transform-sdk/rust/sr/README.md, src/transform-sdk/rust/sr/src/lib.rs, src/transform-sdk/rust/varint/Cargo.toml, src/transform-sdk/rust/varint/src/lib.rs
Backport of PR https://github.com/redpanda-data/redpanda/pull/16464
=> [v23.3.x] Data Transforms Schema Registry Rust SDK

src/v/redpanda/admin/api-doc/security.def.json, src/v/redpanda/admin/api-doc/security.json, src/v/redpanda/admin/security.cc, src/v/redpanda/admin/server.h, src/v/security/role.cc, src/v/security/tests/role_store_test.cc, tests/rptest/services/admin.py, tests/rptest/tests/rbac_test.py
This PR implements the members Admin endpoint for roles. 
- GET /v1/security/roles/{role}/members
- operationID: list_role_members
- POST /v1/security/roles/{role}/members
- operationID: update_role_members
Closes https://github.com/redpanda-data/core-internal/issues/1108
Closes https://github.com/redpanda-data/core-internal/issues/1109
* Introduces `/v1/security/roles/{role}/members` Admin API endpoint for reading and updating RBAC role members.
=> RBAC: /v1/security/roles/{role}/members

.clang-tidy, .clang-tidy-strict, .clang-tidy-strict-tests
This clang tidy very buggy, and has false positives.
See: https://github.com/search?q=repo%3Allvm%2Fllvm-project+misc-include-cleaner&type=issues
* none
=> clang-tidy: disable misc-include-cleaner

tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/services/redpanda.py, tests/rptest/services/redpanda_cloud.py
It didn't work (it uses redpanda.nodes which doesn't exist) and doesn't type check.
Issue redpanda-data/core-internal#988.
* none
=> rptest: remove vestigial CloudTierName.DOCKER

tests/rptest/redpanda_cloud_tests/omb_validation_test.py
Minor tweaks to make this more stable:
- Assign more nodes to client-swarm than OMB: The OMB workload is
actually very gentle. The "hard" part is on the client-swarm side so
more cores help there.
- Reduce the wait time: This seems quite high and slows down the test a
lot at higher connetion counts
- Adjust client-wait ordering: The test is fundamentally broken in how
it works as it doesn't properly calculate the amount of clients that
can connect. We need to fix client-swarm such that we can wait for all
clients connect and then just explicitly stop them at the end of the
test. For now rearrange the waiting of the clients to finish such that
it's more likely to pass (wait for OMB first and then for client
swarms).
* none
=> tests: Tweak OMBValidationTest.test_max_connections

src/v/cluster/controller.cc, src/v/security/acl.cc, src/v/security/acl.h, src/v/security/acl_store.h, src/v/security/authorizer.h, src/v/security/role.cc, src/v/security/role.h, src/v/security/role_store.h, src/v/security/tests/authorizer_test.cc, src/v/security/tests/role_store_bench.cc
This PR wires roles into the authorization flow in redpanda.
closes https://github.com/redpanda-data/core-internal/issues/1101
Preliminary benchmarks:
| test                                                               |  iterations |      median |         mad |         min |         max |      allocs |       tasks |        inst |
| -                                                                  |           - |           - |           - |           - |           - |           - |           - |           - |
| role_store_bench.get_member_roles                                  |    12917749 |    49.132ns |     0.044ns |    48.993ns |    49.264ns |       0.000 |       0.000 |         0.0 |
| role_store_bench.get_member_roles_bare_query                       |    13760304 |    49.146ns | …
=> Role based authorization

src/v/archival/archival_metadata_stm.cc, src/v/archival/scrubber.cc, src/v/cluster/distributed_kv_stm.h, src/v/cluster/log_eviction_stm.cc, src/v/cluster/types.h, src/v/cluster/version.h, src/v/features/feature_state.h, src/v/features/feature_table.h, src/v/raft/heartbeat_manager.h, src/v/raft/offset_translator.h, src/v/raft/recovery_scheduler.cc, src/v/raft/types.cc, src/v/storage/compaction_reducers.h, src/v/storage/index_state.cc
Feature table is included all over the tree, yet it included
cluster/types.h which has a large number of other dependencies. Feature
table only needs the cluster_version definition. In affect feature table
was being used around the tree as an implicit alias for cluster/types.h.
```
In file included from src/v/storage/segment_reader.cc:16:
In file included from src/v/storage/segment_utils.h:20:
In file included from src/v/storage/readers_cache.h:20:
In file included from src/v/storage/log_reader.h:20:
In file included from src/v/storage/segment.h:20:
In file included from src/v/storage/segment_index.h:13:
In file included from src/v/features/feature_table.h:14:
In file included from src/v/cluster/types.h:14:
In file included from src/v/cluster/cloud_metadata/cluster_manifest.h:13:
In file …
```
=> feature_table: remove dependency on cluster/types.h

.github/workflows/transform-sdk-build.yml, src/transform-sdk/cpp/examples/CMakeLists.txt, src/transform-sdk/cpp/examples/identity_logging.cc, src/transform-sdk/go/transform/internal/testdata/dynamic/transform.go, src/transform-sdk/rust/examples/identity_logging.rs, src/transform-sdk/tests/integration_test.go, src/v/wasm/tests/wasm_fixture.cc, src/v/wasm/tests/wasm_fixture.h, src/v/wasm/tests/wasm_logger.h, src/v/wasm/tests/wasm_transform_test.cc, src/v/wasm/wasi.cc
Followup to https://github.com/redpanda-data/redpanda/pull/17186
* none
=> wasm: logging tests

src/transform-sdk/cpp/examples/identity_logging.cc, src/transform-sdk/cpp/include/redpanda/transform_sdk.h, src/transform-sdk/cpp/src/transform_sdk.cc
A small QoL improvement for the C++ SDK.
* none
=> transform-sdk/cpp: add string_view conversion from bytes_view

src/v/storage/disk_log_impl.cc
A crash was observed in CI caused by storage layer metadata inconsistency and accompanied by data loss.
```
Assert failure: (src/v/raft/consensus.cc:2434) 'last_included_term.has_value()' Unable to get term for snapshot last included offset: 9499, log: {
offsets: {start_offset:9457, committed_offset:11164, committed_offset_term:2, dirty_offset:11164, dirty_offset_term:2},
is_closed: false, segments: [
{size: 12, [
{offset_tracker:{term:2, base_offset:9500, committed_offset:9669, dirty_offset:9669},
```
Notice that `start_offset` as reported by the storage layer is lower than the `base_offset` of the first segment. `start_offset` must be great-or-equal.
In the logs the following lines were observed:
```
Compacting 2 adjacent segments: [
Segment 1: {offset_tracker:{term:1, base_offset:9190, …
```
=> storage: mutex compaction and prefix truncation

src/v/cloud_storage_clients/client_pool.cc, tools/cmake_test.py
This nuked the above set environment variables. Noticed this because unit tests were succeeded with UBSAN warnings which meant that `halt_on_error=1:abort_on_error=1` didn't take effect.
* none
=> tools/cmake_test: remove accidental env override

tests/rptest/services/redpanda.py
Sometimes things are slow on bootup (like hella page faults), so provide a mechanism to allow tests to proceed without having to first solve the slow bootup process.
* none
=> tests: allow node ready timeout to be adjusted

src/v/redpanda/admin/security.cc, src/v/redpanda/admin/server.h, tests/rptest/services/admin.py, tests/rptest/tests/rbac_test.py
- GET /v1/security/users/roles
- operationID: list_user_roles
Closes https://github.com/redpanda-data/core-internal/issues/1172
* Introduces GET /v1/security/users/roles (Admin API)
=> RBAC: /v1/security/users/roles 

src/v/cluster/scheduling/leader_balancer.cc, src/v/features/feature_table.cc, src/v/features/feature_table.h
Rename node_local_core_assignment to partition_shard_in_health_report as it will govern only the leader balancer behavior and actual node-local core assignment will be controlled by a separate feature flag.
* none
=> features: rename node_local_core_assignment

src/v/archival/archival_metadata_stm.cc, src/v/archival/archival_metadata_stm.h, src/v/archival/ntp_archiver_service.cc, src/v/archival/tests/archival_metadata_stm_gtest.cc, src/v/archival/tests/archival_metadata_stm_test.cc, src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/partition_manifest.h, src/v/cloud_storage/tests/partition_manifest_test.cc, src/v/cloud_storage/types.h, src/v/cluster/errc.h, src/v/cluster/partition.cc, src/v/kafka/server/errors.h
Currently, the archival STM doesn't propagate errors from the background loop to the caller. The background loop applies record batches to the in-memory state of the STM. Recently, the admission control mechanism was introduced. The background loop checks if the batch can be safely applied and only after that it can apply any changes to the in-memory state of the STM. This is needed to avoid metadata inconsistencies. If the batch can't be safely applied it gets discarded. The problem is that the caller is not receiving the error code.
This PR fixes error propagation. The caller now receives an `inconsistent_stm_update` error in case if metadata inconsistency have been detected. 
Apart from this the PR changes the `sync` method implementation. The `sync` method of the `persisted_stm` …
=> archival: Improve archival STM concurrency control

src/v/storage/disk_log_impl.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17019
=> [v23.2.x] storage: mutex compaction and prefix truncation

src/v/cluster/tests/randoms.h, src/v/cluster/tests/serialization_rt_test.cc, src/v/compat/acls_generator.h, src/v/model/tests/randoms.h, src/v/net/tests/randoms.h, src/v/raft/persisted_stm.cc, src/v/raft/tests/configuration_serialization_test.cc, src/v/security/tests/ephemeral_credential_store_test.cc, src/v/security/tests/randoms.h, src/v/storage/log_manager.cc, src/v/storage/log_manager.h, src/v/storage/offset_translator.cc, src/v/storage/tests/compaction_index_format_tests.cc, src/v/test_utils/randoms.h, src/v/transform/tests/test_fixture.cc, src/v/wasm/tests/wasm_fixture.cc, src/v/wasm/tests/wasm_transform_bench.cc
split up test_utils header for greater good
* none
=> Remove global dependencies from test_utils/random

src/v/kafka/protocol/schemata/generator.py, src/v/kafka/protocol/tests/protocol_test.cc, src/v/kafka/protocol/wire.h, src/v/kafka/server/handlers/configs/config_response_utils.h, src/v/kafka/server/handlers/create_topics.cc, src/v/kafka/server/handlers/topics/topic_utils.cc, src/v/kafka/server/handlers/topics/topic_utils.h, src/v/kafka/server/handlers/topics/types.cc, src/v/kafka/server/handlers/topics/types.h, src/v/kafka/server/tests/alter_config_test.cc
This updates the `CreateTopics` and `DescribeConfigs` kafka api handlers to use `chunked_vector` instead of `std::vector` for the creation of their responses. This is to avoid fragmentation-related issues when the number of topics or partitions is large and so large allocations are necessary to generate the response.
Closes https://github.com/redpanda-data/core-internal/issues/1174
* none
=> kafka: chunked_vector for config responses

src/go/rpk/pkg/tuners/iotune/data.go
Add more EC2 instance types to the "well known IO" mapping, which maps an instance type to the seastar IO scheduler parameters associted with the local SSD performance for that instance.
This change includes iotune numbers for i4i, is4gen and im4gn. iotune did show an unusual sloping off of performance at the highest instance sizes, so beyond some threshold we just mulitply the measurement from the last-good instance type by the instance size multiplier: this is similar to what we were doing for the existing instance i3en.
Issue #13582.
* `rpk redpanda start` know knows about io characteristics on EC2 instance types i4i, is4gen and im4gn in addition to i3en and i3, allowing more effective IO scheduling even if `rpk iotune` has not been run.
=> rpk: add newer EC2 instance types

src/v/transform/tests/test_fixture.cc, src/v/transform/tests/test_fixture.h, src/v/transform/tests/transform_processor_test.cc
We now batch variably in the processor, so if we schedule tasks just
right we can end up with a case where there is an unexpected size
according to our assertions, but that is still valid.
Fixes: https://github.com/redpanda-data/redpanda/issues/17367
* none
=> transform/processor test: prevent batching flakes

tests/rptest/e2e_tests/flink_scale_test.py, tests/rptest/e2e_tests/workloads/flink_transactions_topic_swarm.py, tests/rptest/services/flink.py
Goal is to generate as many topics as possible until RP starts to fail.
Flink workload is used with auto-sized task managers and flexible failure rate settings.
Workloads should generate low to low-moderate data to random topics. Data rate should be controllable.
Milestones
- 1k tops
Fixes: redpanda-data/devprod#1013
* none
=> rptest: Create multi-node test with 1k topics and >10M events

src/v/cluster/archival_metadata_stm.h, src/v/cluster/distributed_kv_stm.h, src/v/cluster/id_allocator_stm.h, src/v/cluster/log_eviction_stm.h, src/v/cluster/partition.cc, src/v/cluster/rm_stm.h, src/v/cluster/tests/CMakeLists.txt, src/v/cluster/tests/tx_topic_test.cc, src/v/cluster/tm_stm.h, src/v/raft/state_machine_base.h, src/v/raft/state_machine_manager.cc, src/v/raft/state_machine_manager.h, src/v/raft/tests/persisted_stm_test.cc, src/v/raft/tests/stm_manager_test.cc, src/v/raft/tests/stm_test_fixture.h
We previously didn't register the eviction stm before returning from
partition creation of tx coordinator partitions. This meant that despite
the efforts of storage housekeeping and space management, tx coordinator
partitions would never evict data.
NOTE: this bug[1] doesn't exist on dev, but does in v23.3, and not in v23.2[2].
[1] https://github.com/redpanda-data/redpanda/blob/3ce012f9ccb64810eafcc4b8b2e0df7340172879/src/v/cluster/partition.cc#L446-L471
[2] https://github.com/redpanda-data/redpanda/blob/f1216cd484063a44e9b25d206a43a1eeda6d2155/src/v/cluster/partition.cc#L79-L94
Includes a backport of https://github.com/redpanda-data/redpanda/pull/17379
Partially includes a backport of https://github.com/redpanda-data/redpanda/pull/15424 for testing
* Fixes a bug that would prevent the …
=> [v23.3.x] cluster: initialize eviction stm for tx coordinator

src/v/redpanda/admin/security.cc, src/v/redpanda/admin/server.h, tests/rptest/services/admin.py, tests/rptest/tests/rbac_test.py
This builds on https://github.com/redpanda-data/redpanda/pull/17089 to implement more of the RBAC admin API endpoints. It implements listing roles, getting a role (describing the role), updating the role (renaming it), and deleting the role.
Closes https://github.com/redpanda-data/core-internal/issues/1104
Closes https://github.com/redpanda-data/core-internal/issues/1105
Closes https://github.com/redpanda-data/core-internal/issues/1106
Closes https://github.com/redpanda-data/core-internal/issues/1107
Closes https://github.com/redpanda-data/core-internal/issues/1173
* none
=> admin: implement RBAC List/Get/Rename/Delete APIs

cmake/dependencies.cmake, src/v/cluster/scheduling/leader_balancer_random.h, src/v/container/CMakeLists.txt, src/v/container/include/container/chunked_hash_map.h, src/v/container/include/container/fragmented_vector.h, src/v/container/tests/CMakeLists.txt, src/v/container/tests/chunked_hash_map_test.cc
Introduces `chunked_hash_map` which is a type alias for the segmented
version of https://github.com/martinus/unordered_dense/ using our
`chunked_vector` as a backing array.
This allows us to use a hashmap in scenarios where the map may grow
large (i.e.: scale with partition/topic counts) similar to `chunked_vector`
and avoids us having to fall back to the suboptimal `absl::btree_map`.
Below are some numbers from our leader balanacer benchmark comparing the
different map types:
| test                                                                  |  iterations |      median |         mad |         min |         max |      allocs |       tasks |        inst |
| -                                                                     |           - |           - |           - |           - | …
=> container: Introduce chunked_hash_map

src/v/cluster/cluster_utils.cc, src/v/cluster/cluster_utils.h, src/v/cluster/controller_backend.cc, src/v/cluster/controller_backend.h, src/v/cluster/errc.h, src/v/cluster/raft0_utils.h, src/v/cluster/shard_placement_table.cc, src/v/cluster/shard_placement_table.h, src/v/cluster/shard_table.h, src/v/cluster/tests/CMakeLists.txt, src/v/cluster/tests/shard_placement_table_test.cc, src/v/kafka/server/errors.h
Add stress test testing the logic in `shard_placement_table` and fix a few bugs that it found.
* none
=> `shard_placement_table`: stress test and fixes

src/v/cluster/tests/shard_placement_table_test.cc
There is an issue with PRs that raced and the build is broken. Fix it by
explicitly adding in chrono literals
* none
=> c/test: fix shard_placement_table_test

src/v/cluster/tests/CMakeLists.txt, src/v/cluster/tests/tx_topic_test.cc
We've seen in older versions of Redpanda that despite the 'delete' cleanup policy being enabled, eviction may not be triggered. This is because in older versions of Redpanda[1], we would not register the eviction STM for tx coordinator partitions.
NOTE: this bug[1] doesn't exist on dev, but does in v23.3, and not in v23.2[2].
[1] https://github.com/redpanda-data/redpanda/blob/3ce012f9ccb64810eafcc4b8b2e0df7340172879/src/v/cluster/partition.cc#L446-L471
[2] https://github.com/redpanda-data/redpanda/blob/f1216cd484063a44e9b25d206a43a1eeda6d2155/src/v/cluster/partition.cc#L79-L94
* none
=> cluster/tests: add test case for eviction of the tx coordinator

src/v/kafka/server/group_manager.cc, tests/java/e2e-verifiers/src/main/java/org/apache/kafka/tools/VerifiableConsumer.java, tests/rptest/tests/consumer_group_test.py
From my understanding, this can cause a problem only when write caching is enabled.
It could also apply to ACKS=1 in an edge case but haven't thought it through. We make data available only after majority replicated so it’s very unlikely for a truncation to happen after that and trigger KIP-320
This was discovered while testing write caching feature. After leadership change or node restart we would reply with default field value `-2147483648` which breaks the KIP-320 logic.
`check_leader_epoch` in redpanda treats negative epoch values as "not set" and, I believe, franz-go behaves the same.
As result, KIP-320 fencing is not being applied and the client ends up with `OFFSET_OUT_OF_RANGE` error.
* none
=> k/group: recover leader epoch on leader change

.github/workflows/transform-sdk-build.yml, src/transform-sdk/cpp/src/transform_sdk.cc, src/transform-sdk/go/transform/internal/testdata/tee/transform.go, src/transform-sdk/rust/core-sys/src/abi.rs, src/transform-sdk/rust/core-sys/src/lib.rs, src/transform-sdk/rust/core-sys/src/stub_abi.rs, src/transform-sdk/rust/core-types/src/lib.rs, src/transform-sdk/rust/examples/tee.rs, src/transform-sdk/rust/sr-types/src/lib.rs, src/transform-sdk/tests/admin_client.go, src/transform-sdk/tests/integration_test.go, src/transform-sdk/tests/test_util.go
Add support for the new method to write options in v2 of the broker's
ABI. This includes specifying write options in the RecordWriter
interface that can then be used to call the new `write_with_options`
method with the specified topic name.
* The rust transform-sdk gains the ability to write to multiple output topics.
This feature can only be used in Redpanda v24.1.x or newer.
=> transform-sdk/rust: multiple output topics

tests/rptest/services/cluster.py, tests/rptest/services/redpanda.py
Detect pod restarts and treat them as crashes
* none
=> PESDLC-985 Raise crash errors on pod restarts

tests/rptest/redpanda_cloud_tests/omb_validation_test.py
As discussed on latest meeting, bumping this value to 60 ms
* none
=> PESDLC-1009 Bump latency for e2e p99

src/v/redpanda/admin/api-doc/security.def.json, src/v/redpanda/admin/api-doc/security.json
The motivation for this is that one of the properties specified in the outward facing API spec has a name collision in generated code, so the name used in the def didn't match. Since we don't actually use the generated code, we can remove the definition altogether and define the structure inline in security.json.
* none
=> admin/api-doc: Remove role_member_update def

src/v/cluster/distributed_kv_stm.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/17383
=> [v23.3.x] stm/dist_kv_stm: missing co_awaits on snapshot lock

src/v/kafka/server/group_manager.cc, tests/java/e2e-verifiers/src/main/java/org/apache/kafka/tools/VerifiableConsumer.java, tests/rptest/tests/consumer_group_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/17260
=> [v23.2.x] k/group: recover leader epoch on leader change

src/v/cluster/controller_backend.cc, src/v/raft/consensus_utils.cc, src/v/storage/disk_log_impl.cc, src/v/storage/disk_log_impl.h, src/v/storage/fwd.h, src/v/storage/offset_translator.cc, src/v/storage/offset_translator.h, src/v/storage/tests/offset_translator_tests.cc
Now that the build pieces have landed for storage:: taking ownership of the offset_translator, this updates its namespace to follow suit.
This is follow-up to https://github.com/redpanda-data/redpanda/pull/16892
* none
=> storage: adopt offset_translator in namespace

src/v/cluster/partition_balancer_planner.cc
Previously we were copying the whole metadata (including partition assignments) just to query the topic revision.
`partition_balancer_bench` results before:
```
test                                                   iterations      median         mad         min         max      allocs       tasks        inst
partition_balancer_planner_fixture.unavailable_nodes           27    24.481ms   161.139us    24.320ms    35.441ms 1235710.104      93.852 425407989.4
partition_balancer_planner_fixture.counts_rebalancing           1      1.857s     7.421ms      1.846s      1.888s 118912546.400    7424.600 33427470288.6
```
and after:
```
test                                                   iterations      median         mad         min         max      allocs       tasks        inst …
```
=> c/partition_balancer: don't copy topic metadata on each partition visit

src/v/cluster/distributed_kv_stm.h, src/v/cluster/tests/distributed_kv_stm_tests.cc
Currently remove_all takes a write lock for the entire duration that
prevents replicate_and_wait() to make progress because it needs a read
lock. Fix this by making remove_all best effort, so it can just grab
a read lock.
* Fixes lock starvation during transform offset commits.
=> stm/dist_kv_stm: fix locking sequence for remove_all

src/v/security/acl.cc, src/v/security/tests/authorizer_test.cc
acl_store: Sub node_hash_map for flat_hash_map in remove_bindings
We maintain a running vector of roles principal views to delete from a small
cache maintained by each matched acl_entry_set. The value type is a view to
avoid excessive copying, but that view is always into the principal component
of a key entry (acl_binding) in a flat_hash_map.
This is problematic because any insertion into flat_hash_map might result in
a rehash, invalidating key pointers (including the pointer to key struct member
contained in the principal_view), resulting in use-after-free errors whenever
the following conditions are met:
- More than one binding is deleted from the ACL store
- i.e. > 1 binding matches the provided filters
- One of those bindings is to a role principal
This commit also adds a test for …
=> RBAC: Fix use-after-free in security::acl_store

src/v/raft/state_machine_manager.cc, src/v/raft/state_machine_manager.h, src/v/raft/tests/persisted_stm_test.cc, tests/rptest/tests/tiered_storage_enable_test.py
State machine manager manages the aggregated Raft snapshot for all the
state machines created based on one Raft instance. The managed snapshot
is a map containing individual snapshot data for each state machine.
When a new STM is created while the managed snapshot was already taken
the `state_machine_base::apply_raft_snapshot` should still be called
even if the snapshot doesn't exists in the managed snapshot map.
This way an STM will be informed that the log doesn't start from 0.
Previously when snapshot was not present in the managed snapshot map we
skipped calling `apply_snapshot` on the STM and didn't advance it's
`_next` offset which lead to stuck background apply fiber loop.
Fixes: #17086 
- fixed enabling cloud storage in existing clusters
=> Fixed not applying snapshot for new stms

src/v/cluster/partition_balancer_planner.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17413
=> [v23.3.x] c/partition_balancer: don't copy topic metadata on each partition visit

src/v/container/include/container/fragmented_vector.h, src/v/container/tests/chunked_hash_map_test.cc
Added `get_allocator()` method to fragmented vector to be able to move the `chunked_hash_map` as in its move assignment operator it queries the allocator from index underlying data structure.
- none
=> c/frag_vector: added `get_allocator()` method to fragmented vector

src/v/cluster/errc.h, src/v/cluster/scheduling/partition_allocator.cc, src/v/cluster/tests/create_partitions_test.cc, src/v/cluster/tests/partition_allocator_fixture.h, src/v/cluster/tests/partition_allocator_tests.cc, src/v/cluster/topics_frontend.cc, src/v/compat/cluster_generator.h, src/v/kafka/server/errors.h, src/v/kafka/server/handlers/create_partitions.cc, src/v/kafka/server/handlers/topics/types.h, src/v/kafka/server/tests/error_mapping_test.cc
This change improves the error response for when Redpanda is provided an invalid number of partitions during either topic creation or when the user is requesting an increase in the number of partitions.  Now, instead of just returning back `invalid_partitions` and error message is also provided explaining why.
Fixes: #17368 
* Improves error feedback when Redpanda is given an invalid number of partitions during either topic creation or when the partition count for a topic is increased.
=> Improve error response for invalid partition count

src/v/cluster/cluster_utils.cc, src/v/cluster/types.h, src/v/kafka/server/group.cc, src/v/kafka/server/handlers/produce.cc, src/v/raft/CMakeLists.txt, src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/errc.h, src/v/raft/replicate_entries_stm.cc, src/v/raft/replicate_entries_stm.h, src/v/raft/replication_monitor.cc, src/v/raft/replication_monitor.h, src/v/raft/tests/CMakeLists.txt, src/v/raft/tests/basic_raft_fixture_test.cc, src/v/raft/tests/replication_monitor_tests.cc, src/v/redpanda/admin/api-doc/debug.json, src/v/redpanda/admin/debug.cc, src/v/ssx/future-util.h, src/v/storage/types.cc
Summary of changes:
* QoL fixes like better debug/trace logging around voting/notifications etc.
* Generic code cleanup in raft without any logical changes.
* Adds replication_monitor, a new way to track replication status of a locally appended offsets. This data structure unifies tracking of all waiters (write caching/otherwise) in one place. This was needed because majority replication needs to rely on committed offset updates to detect truncation (see individual commits for details) but it was awkward for the write caching code to listen for committed offset updates. The new data structure tracks everything in one place streamlining the logic.
* none
=> write caching - raft - follow up fixes

tests/rptest/clients/rpk.py, tests/rptest/services/admin.py, tests/rptest/tests/rbac_test.py
Closes https://github.com/redpanda-data/core-internal/issues/1110
* none
=> RBAC End to End Integration Test

src/v/cluster/scheduling/leader_balancer_random.h, src/v/utils/CMakeLists.txt, src/v/utils/chunked_hash_map.h, src/v/utils/fragmented_vector.h, src/v/utils/tests/CMakeLists.txt, src/v/utils/tests/chunked_hash_map_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17182
Needs manual backporting because v::container is not a thing on v23.3 and it's all still in utils.
=> [v23.3.x] Introduce chunked_hash_map

src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_backend.h, src/v/cluster/tests/CMakeLists.txt, src/v/cluster/tests/health_monitor_bench.cc, src/v/cluster/tests/health_monitor_test.cc, tests/rptest/tests/recovery_mode_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/17158
=> [v23.3.x] Distribute health report collection

src/v/utils/fragmented_vector.h, src/v/utils/tests/chunked_hash_map_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17421
=> [v23.3.x] c/frag_vector: added `get_allocator()` method to fragmented vector

tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/services/redpanda.py
PESDL-942 Concurrent pods restart (hard restart)
* none
* Added ability to restart all of the pods at the same time, without waiting for each pod to come up (hard restart)
* Moved some of the code into separate functions, so they could be reused and avoid code duplication
* Updated rolling restart function to also avoid code duplication
* Removed old function of nodes restart as we needed to move to pods, and created a separate function to verify basic producer_consumer that could be reused, moved it from HTT to redpanda service
NOTE: Need to perform more tests before merging
=> PESDL-942 concurrent pods restart

src/v/cluster/controller_snapshot.h, src/v/cluster/partition_leaders_table.h, src/v/cluster/shard_table.h, src/v/cluster/topic_table.cc, src/v/cluster/topic_table.h
Replaced `absl::node_hash_map` with the newly introduced `chunked_hash_map` to prevent oversized allocation needed for the indexing array. 
Fixes: #16960
Fixes: #16959
Fixes: #16951
- none
=> Fixed `node_hash_map` caused oversized allocations in cluster module

src/v/io/CMakeLists.txt, src/v/io/README.md, src/v/io/io_queue.cc, src/v/io/io_queue.h, src/v/io/page.cc, src/v/io/page.h, src/v/io/page_cache.cc, src/v/io/page_cache.h, src/v/io/pager.cc, src/v/io/pager.h, src/v/io/paging_data_source.cc, src/v/io/paging_data_source.h, src/v/io/tests/CMakeLists.txt, src/v/io/tests/common.cc, src/v/io/tests/page_test.cc, src/v/io/tests/pager_test.cc
Add io::pager which provides an append-only abstraction on top of the files using io::scheduler for the write-back process.
* none
=> io: add pager for append-only file abstraction

src/v/cluster/errc.h, src/v/cluster/namespaced_cache.h, src/v/cluster/producer_state.cc, src/v/cluster/producer_state.h, src/v/cluster/producer_state_manager.cc, src/v/cluster/producer_state_manager.h, src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h, src/v/cluster/tests/namespaced_cache_test.cc, src/v/cluster/tests/producer_state_tests.cc, src/v/cluster/tests/randoms.h, src/v/cluster/tests/rm_stm_test_fixture.h, src/v/cluster/tests/rm_stm_tests.cc, src/v/cluster/tests/tx_compaction_tests.cc, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/kafka/server/errors.h, src/v/kafka/server/handlers/produce.cc, src/v/raft/tests/mux_state_machine_test.cc, src/v/raft/tests/simple_raft_fixture.h, src/v/redpanda/application.cc, src/v/test_utils/randoms.h, tests/rptest/tests/idempotency_stress_test.py, tests/rptest/tests/transactions_test.py
Change implementation of `producer_state_manager` to keep separate producer state LRU cache for each `v_cluster_id.` This approach isolates each virtual cluster queue and guarantees fair distribution of producer state slots among them. 
- none
=> Shard producer state manager with `v_cluster_id`

src/v/security/role.h, src/v/security/role_store.h
- role_member::name should return a const& for flexibility
- still satisfies concept RoleMember b/c/ const sstring& is convertible to std::string_view
- role::members&& should return a value type to express sensible move semantics
- role_store::put can take the members range as const&, rather than &&
- since we're taking members from the range and copying them into internal containers anyway
* none
=> security/role: Minor cleanups

src/v/io/pager.cc, src/v/io/tests/pager_test.cc
=> io: clang tidy fixes

src/v/cluster/errc.h, src/v/cluster/scheduling/partition_allocator.cc, src/v/cluster/tests/create_partitions_test.cc, src/v/cluster/tests/partition_allocator_fixture.h, src/v/cluster/tests/partition_allocator_tests.cc, src/v/cluster/topics_frontend.cc, src/v/compat/cluster_generator.h, src/v/kafka/server/errors.h, src/v/kafka/server/handlers/create_partitions.cc, src/v/kafka/server/handlers/topics/types.h, src/v/kafka/server/tests/error_mapping_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17369 
Fixes: https://github.com/redpanda-data/redpanda/issues/17428
=> [v23.3.x] Improve error response for invalid partition count

src/v/net/probes.cc, src/v/net/tls_certificate_probe.h, tests/rptest/tests/tls_metrics_test.py
What it says on the box.
Fixes https://github.com/redpanda-data/redpanda/issues/16840
* Fixes a bug with TLS metrics where expiration timestamps would not advance on certificate reload
=> TLS Metrics: Ensure that recorded expiries advance on credentials reload

tests/rp_cloud_cleanup.py
Buckets and NATs need cleaning after actual test runs.
This commit adds option to call specific cleanup.
Before cleaning any NAT, it is checked that it is 36h old and is present in records of current Cloud API (preprod/integration). This is done in order to avoid cleaning wrong NATs.
Buckets will be cleaned after 36h and all of mentioned names hold no critical information to be preserved, only test data
```
cleaner.clean_buckets(mask="panda-bucket-")
cleaner.clean_buckets(mask="redpanda-cloud-storage-")
cleaner.clean_buckets(mask="redpanda-network-logs-")
```
* none
=> PESDLC-1021 Update cloud cleanup with options

src/v/security/audit/schemas/tests/ocsf_schemas_test.cc, src/v/security/audit/schemas/types.h, src/v/security/audit/schemas/utils.cc, tests/rptest/tests/audit_log_test.py
Fixes https://github.com/redpanda-data/core-internal/issues/1102
* none
=> security: Wire up RBAC role to OCSF user::groups

src/v/serde/rw/sstring.h
`src/v/serde/rw/sstring.h` include itself.
so far it did not cause problem thanks to the leading `#pragma once`
fixed by including `<seastar/core/sstring.hh>`
* none
=> serde/rw/sstring: fix header self inclusion

tests/rptest/services/producer_swarm.py
When is_alive check is done and gives YES the merics endpoint is not ready yet
and subsequent try to get them with await_progress will result in Exception.
This adds fake metrics getter/waiter that serves as an indication that metrics
is available
Fixes: #16865
* none
=> PESDLC-1036 Wait for metrics at startup of producer_swarm

src/v/security/CMakeLists.txt, src/v/security/acl.cc, src/v/security/acl_entry_set.h, src/v/security/acl_store.h, src/v/security/authorizer.cc, src/v/security/authorizer.h, src/v/security/fwd.h, src/v/security/role.cc, src/v/security/role.h, src/v/security/role_store.h
This PR refactors acl_store slightly to return prefix ACL matches as a view. This saves a vector allocation on the authZ path.
Also breaks some header dependencies in an effort to isolate view templates to the specific compilation units where they are needed.
* none
=> acl_store: Return prefix matches as a view

src/v/archival/ntp_archiver_service.cc, src/v/archival/probe.cc, src/v/archival/probe.h
adds new probe `repdanda_cloud_storage_cloud_log_size` to report the total size of the user-visible log.
uses information already tracked in the partition manifest
Fixes https://github.com/redpanda-data/core-internal/issues/1214
* new metric redpanda_cloud_storage_cloud_log_size reports size in bytes of the log in cloud storage
=> report cloud log size in redpanda_cloud_storage_cloud_log_size probe

src/v/cluster/security_frontend.h, src/v/redpanda/admin/api-doc/security.json, src/v/redpanda/admin/security.cc, tests/rptest/clients/rpk.py, tests/rptest/services/admin.py, tests/rptest/tests/rbac_test.py
Closes https://github.com/redpanda-data/core-internal/issues/1203
* none
=> RBAC: Add ability to delete role ACLs when deleting the role itself in the Admin API

tests/rptest/tests/offset_for_leader_epoch_test.py
Offset for leader epoch test uses large number of partitions, running it in debug mode is flaky as it may happen that the nodes will step down due to timeouts when receiving heartbeats leading to the test being unstable.
Fixes: #12062
- none
=> tests: do not run offsets for leader epoch test in debug mode

src/v/model/record_batch_reader.cc, src/v/model/record_batch_reader.h, src/v/raft/replicate_batcher.cc, src/v/raft/replicate_batcher.h
Using `fragmented_vector` to store batches in `raft::replicate_batcher` to avoid large allocations.
Fixes: #16944
Fixes: #16945
- none
=> use chunked vector as batches cache in `raft::replicate_batcher`

src/v/cluster/types.h
remote_topic_properties declares operator<< twice. this pr deletes one of them
* none
=> cluster/types: removed redundant operator<< declaration

src/v/security/authorizer.cc, src/v/security/authorizer.h
Fixes https://github.com/redpanda-data/core-internal/issues/1185
* none
=> s/authorizer: Comments about allow_empty_matches

src/v/kafka/server/replicated_partition.cc, src/v/storage/disk_log_impl.cc, src/v/storage/log_reader.cc, src/v/storage/log_reader.h, src/v/storage/segment_utils.cc, src/v/storage/tests/readers_cache_test.cc, src/v/storage/types.h
Previously offset translation on the read path was done in the Kafka layer, with the storage layer providing primitives to help translate. As we clarify the requirements of the storage log implementation, offset translation has made its way into the purview of storage.
To allow the storage layer to own offset translation end-to-end on the read path, and allow for future log implementations that translate offsets differently (e.g. by storing translated offsets), this adds an option to the log reader to translate. The corresponding code is removed from the Kafka layer.
* none
=> storage: add log_reader option to translate offsets

src/v/net/probes.cc, src/v/net/tls_certificate_probe.h, tests/rptest/tests/tls_metrics_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/17233
Fixes: https://github.com/redpanda-data/redpanda/issues/17459,
=> [v23.3.x] TLS Metrics: Ensure that recorded expiries advance on credentials reload

src/v/cluster/commands.h, src/v/cluster/controller_log_limiter.h, src/v/cluster/security_frontend.cc, src/v/cluster/security_frontend.h, src/v/cluster/security_manager.cc, src/v/cluster/security_manager.h, src/v/cluster/tests/security_frontend_test.cc, src/v/cluster/types.h, src/v/redpanda/admin/api-doc/security.json, src/v/redpanda/admin/security.cc, tests/rptest/services/admin.py, tests/rptest/tests/rbac_test.py
After some discussion with product, UI, and console teams, we determined that, absent the ability to redirect existing ACLs to the new role, the act of renaming a Role is not particularly useful. So we're removing it.
Closes https://github.com/redpanda-data/core-internal/issues/1204
* none
=> RBAC: remove update role and friends

tests/rptest/tests/e2e_shadow_indexing_test.py
Avoid restarting redpanda durint the e2e test. Restart resets the metrics and the second run of the consumer after restart is not guaranteed to hit throttling because the data is cached.
Fixes: https://github.com/redpanda-data/redpanda/issues/14139
* none
=> rptest: Fix throttling test

src/v/cluster/controller.cc, src/v/cluster/members_backend.cc, src/v/cluster/members_backend.h, src/v/cluster/partition_balancer_backend.cc, src/v/cluster/partition_balancer_backend.h, src/v/cluster/partition_balancer_planner.cc, src/v/cluster/partition_balancer_planner.h, src/v/cluster/scheduling/allocation_node.cc, src/v/cluster/scheduling/allocation_node.h, src/v/cluster/scheduling/allocation_strategy.cc, src/v/cluster/scheduling/allocation_strategy.h, src/v/cluster/scheduling/constraints.cc, src/v/cluster/scheduling/constraints.h, src/v/cluster/scheduling/partition_allocator.cc, src/v/cluster/scheduling/partition_allocator.h, src/v/cluster/scheduling/types.cc, src/v/cluster/scheduling/types.h, src/v/cluster/tests/partition_allocator_tests.cc, src/v/cluster/tests/partition_balancer_planner_fixture.h, src/v/cluster/tests/partition_balancer_simulator_test.cc, src/v/cluster/topics_frontend.cc, src/v/cluster/topics_frontend.h, src/v/config/configuration.cc, src/v/config/configuration.h, tests/rptest/tests/topic_creation_test.py
Create new topics/partitions and balance partitions based on topic-wise node replica counts, not on total replica counts.
* Create new topics/partitions and balance partitions based on topic-wise node replica counts, not on total replica counts. This behavior is controlled by the `partition_autobalancing_topic_aware` config property (enabled by default).
=> Topic-aware topic/partition creation and partition balancing

src/v/security/authorizer.cc, src/v/security/authorizer.h
A metric for authorization duration / latency doesn't make much sense; it measures at around 1µs, and the cost of the measurement (based on a std::chrono::high_resolution_clock) possibly outweighs the cost of the operation.
We're better off using the CPU profiler to spot hotspots.
Fixes https://github.com/redpanda-data/core-internal/issues/1135
Note: `allow` is the only positive result, `empty` and `deny` are both authZ failures.
```
vectorized_authorization_result{type="empty"} 16
vectorized_authorization_result{type="deny"} 0
vectorized_authorization_result{type="allow"} 22
```
```
redpanda_authorization_result{type="empty"} 16
redpanda_authorization_result{type="deny"} 0
redpanda_authorization_result{type="allow"} 22
```
* none
=> security/rbac: Add metrics

src/v/wasm/wasmtime.cc
As a nice way to interop with out ptrs introduce out_handle
similar to [std::out_ptr_t](https://en.cppreference.com/w/cpp/memory/out_ptr_t/out_ptr) but for handle.
* none
=> wasm: add out_handle

src/go/.goreleaser.yaml
fixes https://redpandadata.atlassian.net/browse/PESDLC-1005
add goreleaser build id `rpk-linux-microsoft-go` for use with microsoft's golang compiler. this configures the compiler to dynamically link `rpk` for deb/rpm packages.
the `zip` files of `rpk` generated by goreleaser that are attached as assets to redpanda github releases are left as statically compiled.
~this PR needs to be merged in sync with PR https://github.com/redpanda-data/vtools/pull/2588~
EDIT: i added git commit e6e39e7 so existing vtools can work without changes
* none
=> goreleaser: adjust goreleaser to dynamically link rpk on linux 

src/v/cluster/metrics_reporter.cc, src/v/security/CMakeLists.txt, src/v/security/acl_store.h, src/v/security/authorizer.cc, src/v/security/authorizer.h, src/v/security/fwd.h, src/v/security/role_store.h
Some PR comments from #17152, and a small related change to metrics_reporter
* none
=> security: Various minor cleanups

src/v/raft/consensus.cc, src/v/raft/probe.cc, src/v/raft/probe.h, tests/rptest/tests/write_caching_test.py
Adds a couple of simple metrics for visibility into write caching and raft in general
vectorized_raft_replicate_ack_all_requests_no_flush - # of quorum ack requests without flush (aka with write caching)
vectorized_raft_batch_size_bytes - a histogram of batch sizes as flushed by the replicate batcher, gives visibility into batching at raft layer.
Both are internal metrics at partition scope.
* Adds metric for number of quorum ack requests with write caching.
=> write caching - raft - metrics

src/go/rpk/go.mod, src/go/rpk/pkg/cli/cluster/config/edit.go, src/go/rpk/pkg/cli/cluster/config/edit_test.go
When doing `rpk cluster config edit` leverage the editor options. For example if the `EDITOR` is set to `code -w`, then the `rpk cluster config edit` should run a editor command like `code -w <cluster config tempfile`.
The commit splits the `EDITOR` environment variable with options and appends the tempfile as the last argument.
Fixes: 17386
Leverage the editor(`$EDITOR`) options  using comand`rpk cluster config edit`.
The developer can now set editor to something like EDITOR='code -w` and run the `rpk cluster config edit` to be able to make the editor wait for the editing to be saved/discarded.
=> (fix): Handle EDITOR with options

src/v/security/authorizer.cc
To silence -Wlogical-op-parentheses warning (which oddly only occurs on remote icecc machines though it looks to me like it should always fire).
* none
=> authorizer: add parens

src/v/cloud_storage/materialized_resources.cc, src/v/cloud_storage/read_path_probes.cc, src/v/utils/token_bucket.h
Fix the throttling ducktape test. The test was failing because additional restart reset the metric.
Additionally, the PR improves the way the metric is collected and updates the token bucket implementation to improve observability.
Fixes #14139
* None
=> cloud_storage: Fix download throttling ducktape test

install-dependencies.sh
This is a prerequisite for PR #17385 which depends on lz4 being linked statically. The package list for debian already pulls in liblz4-dev which adds the static lib.
* none
=> deps: Add lz4-static for fedora

tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/utils/rpenv.py
* none
* Ability to skip tests based on provider FMC (dedicated) or BYOC. We also have a check at runtime to skip certian tests if on dedicated, but this notation allows to specify if test should be skipped. We would have similar decorators/notations for aws/gcp/azure in case some tests would be only related to specific cloud
=> Add a way to skip the test based on cloud_type GH:1169 Jira:PESDLC-971

tests/rp_cloud_cleanup.py
Main cleanup script can’t handle very big buckets and goes deep into recursive deletions. Example: https://buildkite.com/redpanda/vtools-cleanups
Actions: 
- switch to per-bucket deletions using s3clean.sh 
- add option to use 8h delay to rp_cloud_cleanup.py
* none
=> PESDLC-1021 Add optional 8h delay to bucket cleaning

tests/rptest/clients/types.py
In https://github.com/redpanda-data/redpanda/commit/ce8095e10edc49ef1eb2b0a959ace6d10d084d53 we removed data policy support but there are a couple of pieces left in the test code.
* none
=> rptest: delete vestigial datapolicy stuff

src/v/io/tests/pager_test.cc
By not having empty catches.
* none
=> io: fix clang-tidy warning

tests/rptest/tests/offset_for_leader_epoch_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/17457
Fixes: https://github.com/redpanda-data/redpanda/issues/17469,
=> [v23.3.x] tests: do not run offsets for leader epoch test in debug mode

src/v/cloud_storage/anomalies_detector.cc, src/v/cloud_storage/anomalies_detector.h, src/v/cloud_storage/remote.cc, src/v/cloud_storage/remote.h, src/v/cloud_storage/tests/anomalies_detector_test.cc, src/v/cloud_storage/types.cc, src/v/cloud_storage/types.h, src/v/cluster/CMakeLists.txt, src/v/cluster/errc.h, src/v/cluster/partition_manager.cc, src/v/cluster/topic_recovery_validator.cc, src/v/cluster/topic_recovery_validator.h, src/v/cluster/topics_frontend.cc, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/config/convert.h, src/v/config/property.h, src/v/config/rjson_serialization.cc, src/v/config/rjson_serialization.h, src/v/kafka/server/errors.h, src/v/model/metadata.h, src/v/model/model.cc, src/v/model/tests/lexical_cast_tests.cc, tests/rptest/tests/cluster_config_test.py, tests/rptest/tests/topic_recovery_test.py
Introduced a new function to perform metadata validation for a remote topic to be used during the process of topic recovery.
For each partition, checks if the manifest exists in the cloud and optionally checks if the file can be decoded and self-consistent up to N most recent segment_meta,
For each partition, the S3 cost is 1 HeadObject request for the partition_manifest OR 1Get + 1HeadObject request for N segment_meta.
in general, we could limit the depth of the check by
- num segments
- offset
- total time
num segments correlates directly with the speed of the operation while being deterministic.
offset could map better with what the user wants, but it's more challenging to implement with the current reverse iteration implementation of segment_meta_cstore.
total time, it's a strong …
=> remote partition_manifest validation for topic recovery

src/v/kafka/server/handlers/configs/config_response_utils.cc, tests/rptest/services/redpanda_installer.py, tests/rptest/tests/controller_snapshot_test.py, tests/rptest/tests/describe_topics_test.py, tests/rptest/tests/topic_creation_test.py
This fixes a bug in the reported config source of `cleanup.policy`. If I create a topic without a cleanup policy, the default cleanup policy is as configured on the broker (initially, cleanup.policy=delete). Describing a topic's configs shows:
```
cleanup.policy          delete      DYNAMIC_TOPIC_CONFIG
```
when it should show
```
cleanup.policy          delete      DEFAULT_CONFIG
```
Fixes https://github.com/redpanda-data/redpanda/issues/2225
* Fix reported config source for cleanup.policy by reporting DEFAULT_CONFIG instead of DYNAMIC_TOPIC_CONFIG for the default value.
=> kafka: fix config source for default cleanup.policy config

src/v/kafka/server/replicated_partition.cc, src/v/raft/consensus.cc, src/v/raft/tests/basic_raft_fixture_test.cc, src/v/raft/tests/raft_fixture.cc
Changed the way how we handle Raft log truncation beyond majority_replicated_index. This PR reverts the change where we disallowed truncating offsets which were made visible. This change makes recovery from the situation in which the newly elected leader has shorter log problematic as the node which prevented truncation will not make progress. This change doesn't really influence the end user view of partition replicas as the producers are able to produce immediately after the new leader is elected. 
```
+ entries from term n
- entries from term n + 1
$ entries from term n + 2 
node 0: +++---------
=========== <- isolated
node 1:  +++$$$$ \
selects a new leader
node 2:  +++$$$$ /
``` 
With the previous mechanism we wouldn't allow the node 0 to be truncated which would effectively prevent …
=> Improved validation of Fetch requests when reading from follower

src/v/cluster/metrics_reporter.cc, src/v/cluster/metrics_reporter.h, src/v/security/authorizer.cc, src/v/security/authorizer.h, tests/rptest/tests/rbac_test.py
Update metrics_reporter to show the number of rbac roles rather than a bool for whether there are _any_ roles present.
Closes https://github.com/redpanda-data/core-internal/issues/1213
* none
=> Update metrics_reporter to show the number of rbac roles

.github/workflows/lint-golang.yml, src/go/.goreleaser.yaml
follow-on to PR #17230, this PR adds check for the goreleaser configuration file and updates to latest actions to bring in bug fixes and perf optimizations for lint-golang:
* https://github.com/actions/checkout/releases/tag/v4.1.1
* https://github.com/actions/setup-go/releases/tag/v5.0.0
* https://github.com/golangci/golangci-lint-action/releases/tag/v4.0.0
* https://github.com/goreleaser/goreleaser-action/releases/tag/v5.0.0
* none
=> gha: update lint-golang

src/v/cluster/types.cc, src/v/config/configuration.cc, src/v/kafka/server/handlers/alter_configs.cc, src/v/kafka/server/handlers/configs/config_utils.h, src/v/kafka/server/handlers/create_topics.cc, src/v/kafka/server/handlers/topics/types.cc, src/v/kafka/server/handlers/topics/validators.h, src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/serde/rw/chrono.h, tests/rptest/clients/types.py, tests/rptest/tests/write_caching_test.py
Allows having write caching property overrides at topic creation time.
* none
=> k/topics: make write caching configs settable at creation

tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/utils/rpenv.py
This reverts commit 01647218d4d12fbd65d027ef7da659762b49df81.
- [X ] none - not a bug fix
* none
=> Revert "Add a way to skip the test based on cloud_type GH:1169

src/v/cluster/metadata_cache.cc, src/v/cluster/metadata_cache.h, src/v/cluster/partition_leaders_table.cc, src/v/cluster/partition_leaders_table.h, src/v/redpanda/admin/debug.cc
On a many topic/partition cluster this could lead to reactor stalls,
instead use the async version. This does mean that we could fail due to
concurrent modification, so return a 503 in that case to signal a retry.
* Prevent reactor stalls querying leadership information for large clusters
=> admin/debug/leader_info: prevent reactor stalls

src/v/storage/offset_translator_state.cc
offset_translator_state uses vector to store entries. This may create oversized allocations when the struct is serialized/deserialized. This commit replaces vector with chunked_vector.
Both serialized data structure and serialization code path are updated. The version of the data structure is not changed because serde treats any vector-like structure the same and uses the same format.
Fixes #16650
* Fix oversized allocation in storage.
=> storage: Use fragmented_vector in OT-state

tests/rptest/tests/cloud_storage_timing_stress_test.py
The timeing_stress_test performs a lot of TS operations in short time and in some cases it has to upload manifest frequently (more often than once per second). The manifest uploads are driven by segment uploads and retention. Normally, we will try to upload less often (once per 60s or less) even if we're writing into the partition constantly. But under the local storage pressure the ntp-archiver is forced to upload the manifest mroe frequently. The local storage pressure means that the local storage wants to evict some data but it can't do this unless the manifest is uploaded and the clean offset is moved forward.
The timing stress test introduces local storage pressure and uploads manifests frequently. The GCS may throttle us when we're trying to reupload the manifest faster than once …
=> rptest: Increase backoff interval for GCS

tests/rptest/tests/rbac_test.py
Verify that created roles survive a restart.
* none
=> dt/rbac_test: Add RolePersistenceTest

tests/docker/Dockerfile, tests/docker/Dockerfile.dockerignore, tests/rptest/services/redpanda.py, ubsan_suppressions.txt
Currently the test continues despite a violation and includes a single log line that the violation has occurred which makes it difficult to debug further especially narrowing down the exact source that caused it..
This change makes the test halt on first violation include a full stack trace in the broker logs.
* none
=> ducktape: improve ubsan violation handling in dt tests

ubsan_suppressions.txt
Running ducktape on arm64 causes crc32 ubsan violations, so add a suppression file to track these.
* none
=> rptest: add ubsan suppressions

src/v/CMakeLists.txt, src/v/cloud_roles/tests/credential_tests.cc, src/v/cloud_roles/tests/signature_test.cc, src/v/cluster/bootstrap_backend.cc, src/v/cluster/tests/feature_barrier_test.cc, src/v/cluster/tests/partition_allocator_fixture.h, src/v/cluster/tests/partition_balancer_planner_fixture.h, src/v/cluster/tests/partition_balancer_simulator_test.cc, src/v/cluster/tests/topic_table_test.cc, src/v/cluster/tests/topic_updates_dispatcher_test.cc, src/v/config/property.h, src/v/storage/log_manager.cc
Running the public build with clang 17 and clang-tidy picks up some new warnings.
There are way too many to fix the not used rvalue warnings, but hopefully we can chip away at those overtime.
* none
=> treewide: address newer clang-tidy warnings

src/v/base/include/base/seastarx.h
IWYU in clangd always suggests to remove seastarx.h because it thinks no
symbols are being used (sort of correct), I guess it can't understand
the alias usage in this file. Add a suppression that clangd respects to
never remove the header.
* none
=> iwyu: add pragma to always keep

src/v/cluster/bootstrap_backend.cc
This adds a conservative check for in-progress recoveries at bootstrap time: if a recovery is in progress, we will log an error message instead of throwing.
In practice we don't expect this error code to be hit, but in case of a bug or somesuch, this seems preferable over throwing and blocking applying controller messages.
Note that update_in_progress is the only error code to come out of cluster_recovery_table::apply().
* none
=> cluster: avoid throwing on duplicate recovery

install-dependencies.sh
This is a prerequisite for PR 17385 which depends on lz4 being linked statically. The package list for debian already pulls in liblz4-dev which adds the static lib.
(cherry picked from commit 59a6be34524fc8d35475cd36022a03abeb769c03)
manual backport of https://github.com/redpanda-data/redpanda/pull/17520
FIXES https://github.com/redpanda-data/redpanda/issues/17521
* none
=> [v23.2.x] deps: Add lz4-static for fedora (manual backport)

src/v/cluster/service.cc, src/v/cluster/topics_frontend.cc, src/v/cluster/topics_frontend.h
Changed handling of `finish_partition_update_request` to break the dispatch loop when one node leader information is stale. Now when node receives the `finish_partition_update_request` via RPC service it will not redirect if further to the current controller preventing the request to be infinitely redirected when node leader information is stale.
- none
=> c/topics_frontend: break the loop when dispatching to current leader

src/v/cluster/rm_stm.cc
The lock ensures that the concurrent idempotent requests do not reorder at the raft layer, i.e if one of the requests within a concurrent batch of dempotent requests fail to replicate, the subsequent ones fail too.
Upon hitting an OOOSN, we do not need to hold the lock as we are waiting for the barrier as we know for a fact that request that acquired this lock is of invalid sequence and does not affect the concurrently running requests. Holding the lock while the barrier returns just delays legit concurrent requests.
* none
=> rm_stm: do not hold producer lock for the duration of the barrier

tests/rptest/clients/kubectl.py, tests/rptest/services/cluster.py, tests/rptest/services/redpanda.py, tests/rptest/services/utils.py
To eliminate code duplication and offload some of the methods to external class, new util classes is introduced with abstract approach to reuse checks for both local run and cloud
* none
=> PESDLC-995 Create means to search logs in cloud pods

src/go/rpk/pkg/cli/profile/create.go
If the cluster state is != ready, the cloud
response wont contain the kafkaAPI field, resulting in a segfault.
Now, we will limit the profile creation to only
clusters that are "ready".
* rpk: prevent a segfault when creating a profile from a cloud that is not in ready state.
=> rpk: prevent segfault by checking ready-clusters

src/v/model/record_batch_reader.cc, src/v/model/record_batch_reader.h, src/v/raft/replicate_batcher.cc, src/v/raft/replicate_batcher.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/17425
=> [v23.3.x] use chunked vector as batches cache in `raft::replicate_batcher`

src/v/kafka/server/replicated_partition.cc, src/v/raft/consensus.cc, src/v/raft/tests/basic_raft_fixture_test.cc, src/v/raft/tests/raft_fixture.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17498
=> [v23.3.x] Improved validation of Fetch requests when reading from follower

src/v/net/probes.cc, src/v/net/tls_certificate_probe.h, tests/rptest/tests/tls_metrics_test.py
Compute the crc32c checksum on the complete binary contents of the
trust file on certificate creation and reload. Export this value on
the metric iff a trust file is present AND certs are otherwise valid.
Otherwise export 0.
This will be particularly useful for cloud clients who want to verify
the contents of the trust store but don't have direct access to the
filesystem of the host.
Closes https://github.com/redpanda-data/core-internal/issues/1184
* Introduce "trust_file_crc32c" metric to export a checksum for each trust file in the system.
=> net/tls_probe: Introduce "trust_file_crc32c" metric

.github/workflows/lint-golang.yml
latest goreleaser v1.25.0 deprecated things that need to be changed here and in vtools. this is a quick fix for now.
related: https://redpandadata.atlassian.net/browse/PLATENG-28
* none
=> gha: lock to goreleaser v1.24.0

src/v/kafka/server/group.cc, src/v/kafka/server/group.h, src/v/kafka/server/group_manager.cc, src/v/kafka/server/group_manager.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/16920
Fixes: https://github.com/redpanda-data/redpanda/issues/17583,
=> [v23.3.x] k/group_manager: used chunked_vector when cleaning groups

src/v/cluster/controller_snapshot.cc, src/v/cluster/controller_snapshot.h, src/v/cluster/security_manager.cc, tests/rptest/tests/rbac_test.py
Snapshot machinery for roles was missing previously. 
Updates a ducktape test to ensure that a controller snapshot occurs before restarting the cluster.
Validator (test should fail absent these changes): https://github.com/redpanda-data/redpanda/pull/17560
* none
=> RBAC: Enable the role store to survive a controller snapshot

src/go/rpk/pkg/cli/profile/create.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/17553
=> [v23.3.x] rpk: prevent segfault by checking ready-clusters

tests/docker/ducktape-deps/tinygo-wasi-transforms, tests/rptest/clients/rpk.py, tests/rptest/tests/data_transforms_test.py
Add a ducktape test for multiple output topics
Fixes: CORE-1928
* none
=> rptest/transform: add multiple output topics test

src/v/http/client.cc, src/v/kafka/client/transport.h, src/v/net/client_probe.h, src/v/net/conn_quota.cc, src/v/net/conn_quota.h, src/v/net/transport.cc, src/v/net/transport.h, src/v/rpc/transport.cc, src/v/storage/mvlog/CMakeLists.txt
net: allow transport logger to be customized
* none
=> CORE-2055: net: allow transport logger to be customized

src/go/rpk/pkg/adminapi/api_security.go
This commit includes a new function
`UpdateRoleMembership` to admin API client that
can be used to add and remove principals to a
role in a single operation.
* Adds `UpdateRoleMembership` function to rpk admin API client.
=> rpk: add `UpdateRoleMembership` to admin API client

src/v/cluster/controller_snapshot.cc, src/v/cluster/controller_snapshot.h
More flexible if we decide to change the encoding in the future.
* none
=> c/controller_snapshot: Add serde envelope for named_role

src/go/rpk/pkg/cli/acl/acl.go, src/go/rpk/pkg/cli/acl/common.go, src/go/rpk/pkg/cli/acl/create.go, src/go/rpk/pkg/cli/acl/delete.go, src/go/rpk/pkg/cli/acl/list.go, tests/rptest/clients/rpk.py, tests/rptest/tests/rpk_acl_test.py
Closes https://github.com/redpanda-data/core-internal/issues/1149
* Introduce `--allow-role` and `--deny-role` flags for `rpk acl` commands
=> RBAC/rpk: Introduce `--{allow,deny}-role` flags for ACL create/describe/delete

src/v/cloud_storage/remote.cc
Catching the exception with `const std::exception&` as the type forces the compiler to understand the error's type as `std::exception`, and trips up our shutdown-error-checking[1].
This change updates the code to pass the `std::current_exception()` `exception_ptr` directly to `is_shutdown_exception()`.
This previously showed up as an error log:
```
cloud_storage - [fiber28~216|0|29845ms] - remote.cc:1293 - Failed to delete keys: Sleep is aborted
```
Fixes #17506
[1] https://godbolt.org/z/xqeabz35r
* none
=> remote: fix exception checking in delete_objects_sequentially

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
Some investigation results on the above error
This error here prevents cluster from be connected to the CloudV2 API
```
test_id:    rptest.redpanda_cloud_tests.high_throughput_test.HighThroughputTest.test_add_and_decommission
status:     FAIL
run time:   17 minutes 48.719 seconds
...
subprocess.CalledProcessError: Command '['tsh', 'ssh', '--proxy=proxy.tp.redpanda.com:443', '--auth=okta', '--identity=/tmp/machine-id/identity', 'redpanda@co53q695otfeo26a3q80-agent', 'sudo', 'systemctl', 'enable', '--now', 'redpanda-agent.service', 'redpanda-agent-boot.service', 'redpanda-agent-init.service']' returned non-zero exit status 1.
```
As a result, cloud can't be deleted and stays intact on the account. This is happening for at least a week. So the actual Clusters in the CDT account were not …
=> PESDLC-1069 Disable decomission tests

src/v/net/probes.cc, src/v/net/tls_certificate_probe.h, tests/rptest/tests/tls_metrics_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/17539
=> [v23.3.x] net/tls_probe: Introduce "trust_file_crc32c" metric

src/transform-sdk/go/transform/sr/abi.go, src/transform-sdk/go/transform/sr/client.go, src/transform-sdk/go/transform/sr/stub_abi.go, src/transform-sdk/rust/sr-sys/src/abi.rs, src/transform-sdk/rust/sr-sys/src/lib.rs, src/transform-sdk/rust/sr-sys/src/stub_abi.rs
A followup to https://github.com/redpanda-data/redpanda/pull/17591
* Transform SDKs for Schema Registry now publish their ABI version for compatibility checks with the broker.
=> transform-sdk/sr: add ABI check

src/v/redpanda/admin/server.cc, src/v/wasm/include/wasm/errc.h, src/v/wasm/schema_registry_module.cc, src/v/wasm/schema_registry_module.h, src/v/wasm/wasmtime.cc, tests/rptest/tests/data_transforms_test.py
Introduce a versioning schema to schema registry in data transforms, a [followup PR](https://github.com/redpanda-data/redpanda/pull/17593) will add these methods to the SDKs.
Fixes: CORE-2007
* Add error messages when an unsupported Schema Registry client is used in Data Transforms
=> wasm: check schema registry ABI

tests/docker/ducktape-deps/kgo-verifier, tests/rptest/services/kgo_verifier_services.py
=> rptest: upgrade kgo

src/v/cluster/feature_manager.cc, src/v/cluster/security_frontend.cc, src/v/features/feature_table.cc, src/v/features/feature_table.h, src/v/migrations/CMakeLists.txt, src/v/migrations/rbac_migrator.cc, src/v/migrations/rbac_migrator.h, src/v/redpanda/application.cc, src/v/security/types.h, tests/rptest/services/admin.py, tests/rptest/tests/rbac_upgrade_test.py
This implements a one-time convenience functionality. On the first upgrade to an RBAC-supporting build, this creates a "Users" role that contains all the existing SASL/SCRAM users to help customers get started with RBAC.
It uses the already implemented feature migrator to create a role when the feature first becomes active.
Finally, it implements a suppression to the license nag to not show the license nag for this auto-generated role.
Closes https://github.com/redpanda-data/core-internal/issues/1205
* none
=> cluster: create default "Users" role when RBAC is activated

src/go/.goreleaser.yaml
fixes https://redpandadata.atlassian.net/browse/PESDLC-1079
* none
=> goreleaser: remove GOEXPERIMENT=systemcrypto

tests/rp_cloud_cleanup.py
Enabled cleaning of orphaned networks by default.
* none
=> PESDLC-1064 Enable cloud network clean

.github/workflows/scripts/jira_helper.py
- Jira doesn't permit labels with spaces, so replace spaces with '-' for GH labels
- Do not automatically create issues if the event is just a labeling or unlabeling event or if the issue is already closed and being edited
* none
=> gh: Improve workflow script

src/go/.goreleaser.yaml
follow-on to PR #17676, this PR fixes https://redpandadata.atlassian.net/browse/PESDLC-1079
* none
=> goreleaser: default to CGO_ENABLED=0 allow override

tests/rptest/clients/kafka_cat.py, tests/rptest/clients/kafka_cli_tools.py, tests/rptest/clients/python_librdkafka.py, tests/rptest/clients/rpk.py, tests/rptest/clients/types.py, tests/rptest/e2e_tests/flink_scale_test.py, tests/rptest/redpanda_cloud_tests/cloud_self_test.py, tests/rptest/services/cloud_cluster_utils.py, tests/rptest/services/kafka.py, tests/rptest/services/redpanda.py, tests/rptest/services/redpanda_types.py, tests/rptest/services/serde_client.py, tests/rptest/tests/flink_basic_test.py, tests/rptest/tests/internal_topic_protection_test.py, tests/rptest/tests/pandaproxy_test.py, tests/rptest/tests/redpanda_test.py, tests/rptest/tests/schema_registry_test.py, tests/rptest/util.py
The primary thrust of this change is to consolidate the way our "client wrappers" (i.e., the python code that wraps a Kafka client) get their security credentials to authenticate to the Kafka endpoint. This change only changes ducktape test framework and test code, and does not touch Redpanda itself.
Specifically we want to:
- Use a strongly typed class to represent credentials (`KafkaClientSecurity`)
- Expose a method on RedpandaService which exposes "default" credentials that are suitable to connect to the cluster: these will depend on how the cluster is configured. This is similar to the existing `security_config()` method (removed in this series) but using `KafkaClientSecurity` and supporting more server-side configuration
The primary motivation is that ducktape tests running against …
=> Update approach to kafka security for clients

src/v/net/conn_quota.cc, src/v/net/conn_quota.h, src/v/net/tests/conn_quota_test.cc, src/v/redpanda/application.cc
net: allow conn_quota logger to be configured 
* none
=> CORE-2056: net: allow conn_quota logger to be configured 

src/transform-sdk/cpp/include/redpanda/transform_sdk.h, src/transform-sdk/cpp/src/transform_sdk.cc
When working with external libraries (in my case a json library)
the output is often a string, so make it easy to write a string out to
the output topic.
* none
=> transform-sdk/cpp: add string conversion operators

src/go/rpk/pkg/cli/security/acl/common.go, src/go/rpk/pkg/cli/security/acl/delete.go, src/go/rpk/pkg/cli/security/acl/list.go
Example output:
```
$ ./linux-amd64/rpk security acl list --format=text
PRINCIPAL  HOST  RESOURCE-TYPE  RESOURCE-NAME  RESOURCE-PATTERN-TYPE  OPERATION  PERMISSION  ERROR
User:bar   *     TOPIC          foo            LITERAL                ALL        ALLOW
User:bar   *     GROUP          g              LITERAL                ALL        ALLOW
$ ./linux-amd64/rpk security acl list -f --format=text
FILTERS
=======
PRINCIPAL  HOST  RESOURCE-TYPE  RESOURCE-NAME  RESOURCE-PATTERN-TYPE  OPERATION  PERMISSION  ERROR
ANY                           ANY                    ANY        ANY
MATCHES
=======
PRINCIPAL  HOST  RESOURCE-TYPE  RESOURCE-NAME  RESOURCE-PATTERN-TYPE  OPERATION  PERMISSION  ERROR
User:bar   *     TOPIC          foo            LITERAL                ALL        ALLOW
User:bar   * …
```
=> rpk/security/acl/list: support --format=json

.github/workflows/rpk-build.yml, src/go/rpk/pkg/tuners/executors/commands/backup_file.go
issue https://redpandadata.atlassian.net/browse/PESDLC-1040
follow-on to PR #17568, this PR changes the way tune scripts are generated so that `sha256sum` is used instead of `md5sum`.
```console
rpk redpanda tune disk_irq --output-script=tune_disk_irq.sh
```
```
bash$ head tune_disk_irq.sh
#!/bin/bash
file_hash=$(sha256sum /etc/default/irqbalance | cut -c -32)
cp /etc/default/irqbalance /etc/default/irqbalance.vectorized.${file_hash}.bk
cat << EOF > /etc/default/irqbalance
```
this PR does not change dependency requirements of the user because like `md5sum`, `sha256sum` is also provided by `coreutils` package.
* rpk: tune script uses sha256sum instead of md5sum
=> rpk: generate script with sha256sum instead of md5sum

tests/rptest/tests/consumer_group_test.py
After broker restart it might take a while before the group offsets are available during which redpanda will reply with
`error_code::not_coordinator`[^0]. The test didn't handle the top level error, now it does. We also retry it.
Introduced in #17260
Fixes #17466
[^0]: https://github.com/redpanda-data/redpanda/blob/501b9d35882a303def6061bdc522f67f0502ac1c/src/v/kafka/server/group_manager.cc#L1653
* none
=> rptest: handle errors and retry them in list offsets request

src/v/raft/tests/basic_raft_fixture_test.cc, src/v/storage/segment.cc
Empty batches have been seen to be not handled well in some cases (e.g. in v23.1 and below, read replicas could produce empty batches). This introduces an assert ensuring we no longer produce them.
* none
=> storage: assert when appending empty batch

src/go/rpk/pkg/cli/redpanda/start.go, src/go/rpk/pkg/cli/redpanda/start_test.go
* Enables write caching by default in dev container mode.
=> rpk/defaults: enable write caching in dev container by default

tests/rptest/tests/consumer_group_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/17494
Fixes: https://github.com/redpanda-data/redpanda/issues/17690,
=> [v23.2.x] rptest: handle errors and retry them in list offsets request

src/go/rpk/go.mod, src/go/rpk/go.sum
Using the forked changes brought in from https://github.com/redpanda-data/go-avro/pull/1, this PR replaces `crypto/md5` with https://pkg.go.dev/github.com/cloudflare/cfssl@v1.6.5/scan/crypto/md5
fixes https://redpandadata.atlassian.net/browse/PESDLC-1040
* none
=> rpk: use fork of avro

src/v/wasm/tests/wasm_transform_test.cc, src/v/wasm/transform_module.cc
In the case of an error we still need to reset the call context or things could break when restarting the module.
* none
=> wasm: reset call context on failure

src/v/wasm/tests/wasm_transform_test.cc, src/v/wasm/transform_module.cc
Backport of #17695
* Fixes a crash when data transforms error and restart
=> [v23.3.x] wasm: reset call context on error

tests/rptest/clients/kubectl.py
When creating pod in GKE long suffixes braking the limit of 63 chars enforced by K8s.
This shortens the name and adds a check for the future
* none
=> PESDLC-1095 Fix and check len limits when creating shell

src/v/net/connection.cc, src/v/net/connection.h, src/v/net/server.cc
net: remove rpc logger from server connection
* none
=> CORE-2061: net: remove rpc logger from server connection

tests/rptest/services/redpanda.py
```
WARN  2024-01-09 10:35:44,813 [shard 1:au  ] s3 - s3_client.cc:865 - S3 DeleteObject request failed: Not Found [X-GUploader-UploadID: ABPtcPrc00gQJdiBKftrKBkHq7lfgurC3j5DPPe1b4TgpjlI0EbSEGVEioXFhqISUy5IrVWlHOeZ94krXQ];[Content-Type: application/xml; charset=UTF-8];[Content-Length: 279];[Vary: Origin];[Date: Tue, 09 Jan 2024 10:35:44 GMT];[Expires: Tue, 09 Jan 2024 10:35:44 GMT];[Cache-Control: private, max-age=0];[Server: UploadServer];
```
Here,
`ABPtcPrc00gQJdiBKftrKBkHq7lfgurC3j5DPPe1b4TgpjlI0EbSEGVEioXFhqISUy5IrVWlHOeZ94krXQ` contains "SEGV", but is coming from GCP. This commit adds handling of such header strings tailored for GCP headers[1].
[1] https://cloud.google.com/storage/docs/xml-api/reference-headers#xguploaderuploadid
* none
=> CORE-1705 rptest: filter abort strings from  GCP headers

tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/services/metrics_check.py
With recent changes in RedpandaServiceCloud class, ensure that mentioned test is working and make necessary updates
* none
=> PESDLC-1063 Refactor test_consume_miss_cache

src/v/cluster/cluster_utils.cc, src/v/cluster/controller.cc, src/v/cluster/feature_manager.cc, src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_frontend.cc, src/v/cluster/health_monitor_frontend.h, src/v/cluster/health_monitor_types.cc, src/v/cluster/health_monitor_types.h, src/v/cluster/metadata_cache.cc, src/v/cluster/metrics_reporter.cc, src/v/cluster/node_isolation_watcher.cc, src/v/cluster/node_status_backend.cc, src/v/cluster/node_status_backend.h, src/v/cluster/service.cc, src/v/cluster/service.h, src/v/cluster/tests/health_monitor_test.cc, src/v/cluster/tests/randoms.h, src/v/cluster/tests/serialization_rt_test.cc, src/v/compat/cluster_json.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/admin/server.cc, src/v/redpanda/application.cc, src/v/rpc/errc.h, src/v/rpc/test/rpc_gen_cycling_test.cc, src/v/rpc/transport.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/17625
=> [v23.3.x] Use `node_status_table` as a single source of truth about node liveness

src/v/kafka/server/group_manager.cc, src/v/kafka/server/group_recovery_consumer.cc, src/v/kafka/server/group_recovery_consumer.h
If storage layer will return early from the reader the group stm is not fully recovered. In this case a consumer offset coordinator can not start replying to client requests as the in memory consumer group representation may be incomplete. Added a code preventing this situation from happening.
When incomplete read happened the group manager requests the underlying partition leader to step down. This will trigger another leader election and will trigger leadership notification leading to group recovery.
- prevents partial consumer group recovery
=> Abort recovery when the recovery read is incomplete

src/v/serde/rw/variant.h, src/v/serde/test/serde_test.cc
I have an upcoming change to add a variant for a serde transforms
struct, so I am in advance sending out this change to support variant in
serde.
Variants are tricky w.r.t. compatibility, they are forward compatible if new
discriminants are appended to the variant.
Concretely that means that you can only read old versions of a variant if new
options are appended. Writing a new variant option should happen with a
feature barrier, so that an older reader will never read a newly written
variant.
This works by creating a compile time lookup table of variant index ->
a lambda that creates the variant for the type at the given index. Then
we do a runtime dispatch to the static function based on the index of
the function (with a bounds check).
The stuff you can do with templates are 🤯
Related: …
=> serde: support variant

tests/rptest/tests/consumer_group_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/17494
Fixes: https://github.com/redpanda-data/redpanda/issues/17692,
=> [v23.3.x] rptest: handle errors and retry them in list offsets request

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/17705
=> [v23.3.x] CORE-1705 rptest: filter abort strings from  GCP headers

src/v/raft/tests/basic_raft_fixture_test.cc, src/v/test_utils/gtest_main.cc
Default death test style (fast) forks the test process and runs the test immediately after forking. This does not play well with the seastar environment, leading to hangs and weird errors. Switch to 'threadsafe' style instead that runs the test binary from the beginning in the child process.
Fixes (latest incarnation of) https://github.com/redpanda-data/redpanda/issues/14425
* none
=> gtest: set death_test_style=threadsafe

src/v/cluster/controller.cc, src/v/cluster/health_manager.cc, src/v/cluster/health_manager.h, src/v/cluster/partition_balancer_planner.cc, src/v/cluster/scheduling/partition_allocator.cc, src/v/cluster/scheduling/partition_allocator.h, src/v/cluster/tests/partition_allocator_tests.cc, src/v/cluster/topics_frontend.cc
Add topic awareness to `partition_allocator::reallocate_partition` and enable it in the usage sites of this API. Additionally, update `health_manager` to use `topics_frontend::do_update_topic_properties` instead of dispatching partition reconfigurations manually.
* none
=> Topic-aware replica placement in `partition_allocator::reallocate_partition`

src/v/archival/archival_metadata_stm.cc, src/v/archival/archival_metadata_stm.h, src/v/archival/ntp_archiver_service.cc, src/v/archival/probe.cc, src/v/archival/probe.h, src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/partition_manifest.h, src/v/cloud_storage/tests/partition_manifest_test.cc, tests/rptest/tests/shadow_indexing_compacted_topic_test.py
`vectorized_ntp_archiver_compacted_replaced_bytes` is a gauge metric updated inside `ntp_archiver::upload_manifest` after the manifest is observable in cloud storage.
The value is updated when `archival_metadata_stm` adds a segment to the partition manifest and the operation results in a replacement operation.
The value is not part of the archival_metadata_stm state; it's only there for observability. As such, it is not replicated and is not part of the snapshot.
The value will reset when the manifest is created or deserialized.
Fixes https://github.com/redpanda-data/core-internal/issues/1236 
* new metric vectorized_ntp_archiver_compacted_replaced_bytes
=> CORE-2070: cloud storage probe for compacted away bytes `vectorized_ntp_archiver_compacted_replaced_bytes`

src/v/storage/disk_log_impl.cc, src/v/storage/probe.cc, src/v/storage/probe.h, src/v/storage/segment_utils.cc, tests/rptest/tests/compaction_e2e_test.py
ntp metrics for compaction observability:
`vectorized_storage_log_compaction_removed_bytes`
a counter metric that hooks in `self_compact_segments()` `and sliding_window_compact()` to record `size_before - size_after` at each successful invocation. 
Fixes https://github.com/redpanda-data/core-internal/issues/1232
* new metric vectorized_storage_log_compacted_away_bytes for compaction observability in local storage
=> CORE-2024: local storage probe for compacted away bytes `vectorized_storage_log_compaction_removed_bytes`

src/v/transform/rpc/deps.cc, src/v/transform/rpc/include/transform/rpc/deps.h, src/v/transform/rpc/include/transform/rpc/service.h, src/v/transform/rpc/service.cc, src/v/transform/rpc/tests/transform_rpc_test.cc
[transform/rpc: prevent cross shard memory writes](https://github.com/redpanda-data/redpanda/pull/17702/commits/aac5e671f8daa36f887ca130f4c76489992120d1)
Currently there is code in the transform/rpc layer that does something
along the following:
```
iobuf somedata;
co_await seastar::submit_to(shard_id, [&somedata] {
somedata = fetch_some_data();
});
```
This executes a function on another CPU and writes memory to a stack
location on the requesting CPU. It's not clear if this is safe to do.
Instead change to use standard seastar mechanisms to pass memory between
cores:
```
iobuf somedata = co_await seastar::submit_to(shard_id, [] {
return fetch_some_data();
});
```
The actual pieces here are more complicated than the above example, but
this is what motivates the change itself.
* none
=> transform/rpc: prevent cross shard memory writes

src/v/archival/upload_housekeeping_service.cc, src/v/archival/upload_housekeeping_service.h, src/v/cloud_storage/segment_chunk_api.cc, src/v/cloud_storage/tests/anomalies_detector_test.cc, src/v/cloud_storage_clients/client_pool.cc, src/v/cloud_storage_clients/test_client/abs_test_client_main.cc, src/v/cloud_storage_clients/tests/exception_test.cc, src/v/cluster/cloud_metadata/offsets_uploader.cc, src/v/cluster/topic_recovery_validator.cc, src/v/net/client_probe.h, src/v/net/probes.cc, src/v/net/transport.cc, src/v/net/transport.h, src/v/rpc/transport.cc, src/v/rpc/transport.h, src/v/security/oidc_service.cc
The net::transport metrics managed a superset of metrics for all specializations (e.g. rpc, kafka client). This commit separates them so that the client transport specializations can manage their own metrics.
It's not pretty, but there is also only one user of it in the tree: the rpc transport. With at least one more example the pattern could likely be made more tasty.
The basic strategy is to have a transport probe inherit from the base transport probe. The specialization owns the probe, and passes in a reference to the base transport which will update the metrics common to all transports.
When the specialization sets up metrics it collects its own and passes them to the base transport metrics setup function which combines all of them together and registers them.
* none
=> CORE-2059: net: separate rpc metrics from generic transport

src/v/kafka/server/fetch_session.h, src/v/kafka/server/fetch_session_cache.cc, src/v/kafka/server/handlers/fetch.cc, src/v/kafka/server/tests/fetch_plan_bench.cc, src/v/kafka/server/tests/fetch_session_test.cc, src/v/kafka/server/tests/fetch_test.cc
* Fix initial_leader_epoch/KIP-320 handling in fetch requests. It was ignored until now which prevented consumers to correctly detect suffix truncation. For Redpanda (and Raft), this is a minor problem since suffix truncation is a very improbable event.
=> k/fetch: handle initial_leader_epoch correctly

src/v/cloud_storage_clients/s3_client.cc
I noticed in some clusters that some NotFound errors show up a lot, and it's hard to tell whether they're alarming or not without more context.
```
2024-04-04 23:15:41,069 [shard 0:au  ] s3 - s3_client.cc:866 - S3 DeleteObject request failed: Not Found [X-GUploader-UploadID: ABPtcPo1Yr9tl-T0lj12Bu-qfbQN8GJVz9KSjvNVfHQef8LQmrwLIoGBvteJdNLTQRqrE0fbVcA];[Content-Type: application/xml; charset=UTF-8];[Content-Length: 289];[Vary: Origin];[Date: Thu, 04 Apr 2024 23:15:41 GMT];[Expires: Thu, 04 Apr 2024 23:15:41 GMT];[Cache-Control: private, max-age=0];[Server: UploadServer];",
```
This commit adds the object key to several existing (mostly) warn and error level logs.
* none
=> s3_client: add keys to log messages

tests/rptest/tests/recovery_mode_test.py
In disabling partition test we were not waiting for stable partition leadership but we required the partition high-watermark to be reported. In some cases this lead to an error and made the test unstable.
Fixes: #17223
- none
=> tests: wait for partition leaders before querying hwm

src/v/kafka/server/handlers/topics/types.cc, src/v/kafka/server/handlers/topics/validators.h, tests/rptest/tests/write_caching_test.py
=> kafka: fix write caching validation during topic creation

src/v/model/transform.cc, src/v/model/transform.h, src/v/redpanda/admin/transform.cc, src/v/transform/api.cc, src/v/transform/io.h, src/v/transform/tests/test_fixture.cc, src/v/transform/tests/test_fixture.h, src/v/transform/tests/transform_processor_test.cc, src/v/transform/transform_processor.cc, tests/rptest/tests/data_transforms_test.py
This makes testing transforms easier as the offset that we start from is relative to the deploy and not when the VM starts. This means you can do:
```
rpk transform deploy
rpk topic produce input-topic
rpk topic consume output-topic
```
Without dropping records (there is a 3 second injected delay between deploy and processor start, so today everything in the first 3 seconds is dropped).
Ducktape tests will be written in a followup.
Fixes: CORE-1927, https://github.com/redpanda-data/redpanda/issues/17370
* Transforms now start at a record relative to the deploy time instead of the time at which the VM starts.
This allows for easier testing of transforms, as one does not have to wait for the VM to boot before producing.
=> transforms: fix offset at deploy time

src/v/test_utils/gtest_main.cc
```
/*
* if the test is being passed --gtest_list_tests then do not start Seastar.
* this is an important optimization for using `gtest_discover_tests`
* because every test exectuable is queried in parallel, and the result is
* that listing would timeout or seastar would exhaust some kind of resource
* like aio-max-nr.
*/
```
* none
=> CORE-2212: test: do not start seastar for --gtest_list_tests

src/v/storage/compaction_reducers.cc
The `compaction_placeholder` batch wasn't initialized properly and because of that the invalid timestamps equal to -1 leaked into the TS layer. The `rp-storage-tool` crashed while trying to parse the list of timestamps. 
Fixes #15312
* none
=> CORE-1614 storage: Initialize timestamps in the compaction_placeholder

src/v/archival/tests/archival_metadata_stm_gtest.cc, src/v/raft/consensus.cc, src/v/raft/tests/basic_raft_fixture_test.cc, src/v/raft/tests/raft_fixture.cc, src/v/raft/tests/raft_fixture.h, src/v/raft/tests/raft_reconfiguration_test.cc, src/v/raft/tests/replication_monitor_tests.cc
Otherwise we may add several new voters in quick succession, that the old voters will not know of, resulting in a possibility of non-intersecting quorums.
Example scenario:
1. we start with leader id 1, committed configuration: voters:1,2,3; learners:4,5
2. 1,4,5 are partitioned from 2,3
3. 1 finishes recovery of 4 and 5 and adds them as voters
4. now 1 can remain the leader getting responses from 1,4,5 (that form a quorum in the new voter set 1,2,3,4,5) and 2,3 can elect a leader among themselves, say 2 (because 2,3 is a quorum in the old voter set 1,2,3)
5. now 1 and 2 both think that they are legitimate leaders and can commit new entries, resulting in divergent logs.
To prevent this, in step 3 we don't add 5 as voter until the configuration with voter 4 is committed (or vice versa).
* …
=> raft: don't promote to voter if previous config is not committed

src/v/kafka/server/replicated_partition.cc, src/v/kafka/server/tests/CMakeLists.txt, src/v/kafka/server/tests/replicated_partition_test.cc
When querying offset translator we are relying on the property of the end offset or high watermark being exclusive. Changed the behavior of log end offset to increment offset in Raft offset space and then translate to achieve correct behavior when log is ended with a batch subjected to offset translation.
Fixes: #16612
Credits for @ztlpn for pointing me in the right direction.
- fixes small inconsistency between Kafka and Redpanda when trying to query end_offset of an empty log
=> k/replicated_partition: fixed querying end offset of an empty log

tests/rptest/tests/shadow_indexing_compacted_topic_test.py
decribe_topic can be flaky and does not return elements. This change minimizes the risk by using wait_until
Followup for https://github.com/redpanda-data/redpanda/pull/17627
* none
=> test/shadow_indexing_compacted_topic_test: factored out rpk.describe_topic

src/v/cluster/tests/allocation_bench.cc
Bench test is called many times, but register_node will throw if the node is registered the second time. Modify bench tests so that they register nodes only once at the beginning.
* none
=> c/partition_allocator: fix bench test

tests/java/verifiers/src/main/java/io/vectorized/compaction/tx/TxUniqueKeysWorkload.java, tests/java/verifiers/src/main/java/io/vectorized/compaction/tx/TxWorkload.java
Kafka client has this optimization where if there is unflushed data while aborting a transaction, it is silently dropped on the client side and only the abort request is sent.
With verifiers we want the aborted data in the partition log so the test code invariants (like no aborted data is read etc) are actually doing meaningful work.
This patch explicitly flushes the data before aborting the transaction to ensure data ends up in the log.
* none
=> verifier/tx: explicit flush before aborting transaction

src/v/compression/CMakeLists.txt, src/v/compression/include/compression/internal/lz4_frame_compressor.h, src/v/compression/include/compression/lz4_decompression_buffers.h, src/v/compression/internal/lz4_frame_compressor.cc, src/v/compression/lz4_decompression_buffers.cc, src/v/compression/tests/CMakeLists.txt, src/v/compression/tests/lz4_buf_tests.cc, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/application.cc, src/v/storage/parser_utils.cc
LZ4 decompression uses malloc to allocate memory for temporary buffers. The size allocated depends on the input and can range upto two buffers of slightly over 4MiB each per decompression. 
In cases where contiguous space of 4MiB is not available after redpanda has been running for a while, this can result in a OOM. This is usually seen in context of compaction where a segment needs to be read through to discard old values for a key, requiring decompression of the record batches.
This PR switches LZ4 to use a custom memory allocator and a pair of preallocated 4MiB+128KiB buffers per shard. The custom memory allocator intercepts calls to malloc and returns the preallocated buffers if the allocation size is larger than a threshold. In corresponding calls to `free` the state of managed …
=> CORE-1722: compression: Use preallocated decompression buffers for lz4

src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_segment.h, src/v/cloud_storage/tests/remote_partition_fuzz_test.cc, src/v/cloud_storage/tests/util.cc, src/v/cloud_storage/tests/util.h
This PR adds new fuzz test that reproduces that stuck reader problem and adds a fix. The fix resets the reader in case it reached the max_offset.
Fixes #17788
* Fix problem in Tiered-Storage that could potentially cause consumers to get stuck
=> CORE-2321: cloud_storage: Fix remote_partition stuck reader

src/v/cluster/controller.cc, src/v/cluster/metrics_reporter.cc, src/v/cluster/metrics_reporter.h, src/v/cluster/plugin_table.cc, src/v/cluster/plugin_table.h, tests/rptest/tests/metrics_reporter_test.py
=> cluster: add number of transform to metrics reporter

src/v/migrations/feature_migrator.h, src/v/migrations/rbac_migrator.cc
If the leader running the feature migration loses leadership after
the role is created but before the feature migration is successfully
completed, the next leader will redo the feature migration. In that
case, we will get a `role_exists` error, which we can safely ignore.
This was discovered through the following CI failure: https://ci-artifacts.dev.vectorized.cloud/redpanda/47611/018ec8a8-1fa5-49b2-8d82-1577c14d20bf/vbuild/ducktape/results/final/report.html
Fixes https://redpandadata.atlassian.net/browse/CORE-2287
Fixes https://github.com/redpanda-data/redpanda/issues/17736
* none
=> rbac_migrator: suppress error on role_exists

.github/workflows/buildkite-slash-commands.yml, .github/workflows/slash-commands.yml
used for PRs. It'll publish redpanda packages to repos, and it'll create install-packs that will reference that packages
ref
https://redpandadata.atlassian.net/browse/PESDLC-1057
* none
=> slash-cmds: add `/publish-to-install-pack` command

src/v/archival/tests/archival_metadata_stm_gtest.cc, src/v/raft/consensus.cc, src/v/raft/tests/basic_raft_fixture_test.cc, src/v/raft/tests/raft_fixture.cc, src/v/raft/tests/raft_fixture.h, src/v/raft/tests/raft_reconfiguration_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17675
Fixes https://github.com/redpanda-data/redpanda/issues/17791
=> [v23.3.x] raft: don't promote to voter if previous config is not committed

src/v/raft/consensus.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17675
Fixes https://github.com/redpanda-data/redpanda/issues/17790
=> [v23.2.x] raft: don't promote to voter if previous config is not committed

src/v/kafka/server/handlers/configs/config_response_utils.cc, tests/rptest/services/redpanda_installer.py, tests/rptest/tests/controller_snapshot_test.py, tests/rptest/tests/describe_topics_test.py, tests/rptest/tests/topic_creation_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/17456
Fixes: https://github.com/redpanda-data/redpanda/issues/17718,
=> [v23.3.x] kafka: fix config source for default cleanup.policy config

src/go/rpk/pkg/cli/transform/logs.go
* Handle missing data transform logs topic in `rpk transform logs`
=> rpk/transform/logs: handle missing logs topic

tests/rptest/tests/write_caching_fi_test.py
Depends on https://github.com/redpanda-data/redpanda/pull/17674
* none
=> rptest: write caching tests with failure injection

tests/rptest/tests/compaction_e2e_test.py
previously, the TX_UNIQUE_KEYS workload would generate mostly non-compactible segments, 
so the metric check needed to be <=
This is not a bug but a known behavior of Kafka + compaction: We need to preserve "tx abort" batches across compaction, and the workload generator would generate mostly only "tx abort" batches without any intermediate data.
A recent pr https://github.com/redpanda-data/redpanda/pull/17773 fixes this behavior so this test can be strict
* none
=> test/compaction_e2e_test: strict check

src/go/rpk/pkg/cli/transform/logs.go
* Fix an issue where `rpk transform logs` waits for records without the `--follow` flag specified.
=> rpk/transform/logs: don't hang if the topic is empty

tests/docker/ducktape-deps/tinygo
When retrying we re-emit the data to gzip, which breaks gzip encoding.
Stream the data to a file first.
* none
=> ducktape: more robust tinygo downloads

tests/rptest/services/kgo_verifier_services.py, tests/rptest/services/redpanda.py, tests/rptest/tests/write_caching_fi_e2e_test.py
Depends on https://github.com/redpanda-data/redpanda/pull/17674
Closes https://github.com/redpanda-data/core-internal/issues/1247
* none
=> CORE-2177: rptest: e2e write caching tests with failure injection

cmake/FindLZ4.cmake, src/v/net/connection.cc, src/v/net/types.h, src/v/rpc/service.h
net: remove dependence on rpc parsing exception type
* none
=> CORE-2347: net: remove dependence on rpc parsing exception type

src/v/cloud_storage/segment_chunk.cc, src/v/cloud_storage/segment_chunk.h, src/v/cloud_storage/segment_chunk_api.cc, src/v/cloud_storage/segment_chunk_data_source.cc
Backport of PR #17785 
fixes https://github.com/redpanda-data/redpanda/issues/17793
* none
=> [v23.2.x] CORE-1752: cst: improved logging (manual backport)

src/v/compression/CMakeLists.txt, src/v/compression/internal/lz4_frame_compressor.cc, src/v/compression/internal/lz4_frame_compressor.h, src/v/compression/lz4_decompression_buffers.cc, src/v/compression/lz4_decompression_buffers.h, src/v/compression/tests/CMakeLists.txt, src/v/compression/tests/lz4_buf_tests.cc, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/application.cc
Manual backport with several changes to use appropriate header paths etc.
FIXES https://github.com/redpanda-data/redpanda/issues/17815
Backport of #17385
* none
=> [v23.3.x] CORE-1722: compression: Use preallocated decompression buffers for lz4

src/go/rpk/pkg/cli/transform/init.go
Now you don't need to specify --install-deps=true but can use the naked
boolean flag version
Fixes: CORE-2210
* Fixes `rpk transform init --install-deps` so that an explicit true value is not needed.
=> rpk/transform/init: fix --install-deps flag

tests/rptest/tests/cloud_storage_chunk_read_path_test.py
Fixes https://github.com/redpanda-data/redpanda/issues/16342
* none
=> rptest: fix flaky metric check by disabling leader balancer

src/v/compression/CMakeLists.txt, src/v/compression/internal/lz4_frame_compressor.cc, src/v/compression/internal/lz4_frame_compressor.h, src/v/compression/lz4_decompression_buffers.cc, src/v/compression/lz4_decompression_buffers.h, src/v/compression/tests/CMakeLists.txt, src/v/compression/tests/lz4_buf_tests.cc, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/application.cc
Backport of PR #17385
Fixes https://github.com/redpanda-data/redpanda/issues/17816
Manual backport because of changes since v23.2.x and missing googletest support
* none
=> [v23.2.x] CORE-1722: compression: Use preallocated decompression buffers for lz4

src/go/rpk/go.mod, src/go/rpk/go.sum, src/go/rpk/pkg/cli/container/common/client.go, src/go/rpk/pkg/cli/container/common/common.go, src/go/rpk/pkg/cli/container/common/test.go, src/go/rpk/pkg/cli/container/purge.go, src/go/rpk/pkg/cli/container/start.go
This new version removed the previously deprecated type aliases. (see https://github.com/moby/moby/releases/tag/v26.0.0)
* none
=> rpk: bump docker version

src/v/cluster/controller.cc, src/v/cluster/feature_manager.cc, src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_backend.h, src/v/cluster/health_monitor_frontend.cc, src/v/cluster/health_monitor_frontend.h, src/v/cluster/health_monitor_types.cc, src/v/cluster/health_monitor_types.h, src/v/cluster/partition_balancer_backend.cc, src/v/cluster/service.cc, src/v/cluster/tests/health_monitor_test.cc, src/v/cluster/tests/serialization_rt_test.cc, src/v/compat/get_node_health_compat.h, src/v/compat/get_node_health_generator.h, tests/rptest/utils/node_operations.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/17715
=> [v23.3.x] Health report collection improvements

src/v/storage/key_offset_map.h
With a fragmented_vector configured with 32KB fragments, the actual fragment will be the largest (given T) that doesn't exceed 32KB. For the offset key map the size of T=entry gave a fragment size of 20KB.
The default target size of the entire offset key map is roughly 128KB which works out to a achieved capacity of 8192 fragments when adding entries to the fragmented vector. Given that a vector is 24 bytes, this means that the allocation was 8192 * 24 ~ 190K allocation and this triggered the large allocation warning.
This PR changes the fragmented vector used in the offset key map to have
be a chunked_vector, which end up being around 80KB allocations when
fragment vector decides on the actual fragment size, so the final
allocation for the default configuration is around 45K.
Of course …
=> CORE-2365: storage: increase size of offset key map fragment size

src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h, tests/rptest/tests/transactions_test.py
fence_pid_epoch maps a producer id to its latest epoch. Current cleanup code does not do a epoch check before cleaning up the pid state. This can result in removing the state related to the latest epoch. Consider the following series of events..
[x, y] = pid[id=x, epoch=y]
[1, 0] begin_tx - fence_pid_epoch[1] = 0
[1, 1] begin_tx - fence_pid_epoch[1] = 1
evict [1, 0]
erase(fence_pid[1]) ==> removes (1)
This results in a messed up state stalling the state of the transaction because the partition cannot make progress until it verifies the epoch.
This is a long pending bug that was exposed by racy evictions.
note: this whole code is going to be revamped soon and the plan is to add a self contained unit test fixture that supports transactions end-to-end, that should have better test coverage. …
=> rm_stm: fix fence_pid_epoch cleanup

tests/docker/ducktape-deps/tinygo
curl in ubuntu 20.04 doesn't support `--retry-all-errors` so this was causing the FIPS AMI to fail to build.  This change will check for Ubuntu 20.04 and if found, use `--retry-connrefused`.
* none
=> dt: Updated tinygo to work on Ubuntu 20.04

src/go/rpk/pkg/adminapi/admin.go, src/go/rpk/pkg/cli/debug/bundle/bundle.go, src/go/rpk/pkg/cli/root.go, src/go/rpk/pkg/cli/security/acl/acl.go, src/go/rpk/pkg/cli/security/acl/create.go, src/go/rpk/pkg/cli/security/acl/delete.go, src/go/rpk/pkg/cli/security/acl/list.go, src/go/rpk/pkg/cli/security/role/assign.go, src/go/rpk/pkg/cli/security/role/describe.go, src/go/rpk/pkg/cli/security/role/list.go, src/go/rpk/pkg/cli/security/role/unassign.go, src/go/rpk/pkg/cli/security/user/create.go, src/go/rpk/pkg/cli/security/user/user.go, src/go/rpk/pkg/cli/version/version.go, src/go/rpk/pkg/httpapi/httpapi.go
This PR:
- Matches our internal help text to our online docs (see https://github.com/redpanda-data/docs/pull/393)
- Reduce the timeout and retries for `rpk version`
- Improves our logging of the `httpapi` package
**Logs examples:**
```
15:57:46.189  DEBUG  requesting POST https://cloud-api.prd.cloud.redpanda.com/oauth/token
15:57:46.262  DEBUG  got response for POST https://cloud-api.prd.cloud.redpanda.com/oauth/token: 400 Bad Request
15:57:53.409  DEBUG  requesting GET https://cloud-api.prd.cloud.redpanda.com/api/v1/organization
15:57:53.409  DEBUG  requesting GET https://cloud-api.prd.cloud.redpanda.com/api/v1/namespaces
15:57:53.409  DEBUG  requesting GET https://cloud-api.prd.cloud.redpanda.com/api/v1/virtual-clusters
15:57:53.498  DEBUG  got response for GET …
```
=> rpk: doc updates and small QOL improvements

src/v/cluster/id_allocator.cc
A tight forward-to-leader loop has been discovered in a test where metadata about leader is out of date:
https://github.com/redpanda-data/redpanda/issues/17873.
Instead, we remove the forwarding from the request handler and do it only once on the original invoker. In
`id_allocator_frontend::allocate_id` we call
`allocate_router::process_or_dispatch` which will do the redirect and retry if the target node returns an error/does not respond. It also has backoff built in.
This is a fix very similar to one described in
https://github.com/redpanda-data/redpanda/pull/15953.
Fixes https://github.com/redpanda-data/redpanda/issues/17873
* none
=> id_allocator: do not forward requests beyond first hop
