src/v/kafka/protocol/schemata/generator.py, src/v/kafka/server/handlers/create_topics.cc, src/v/kafka/server/tests/create_topics_test.cc, src/v/kafka/server/tests/delete_topics_test.cc, src/v/kafka/server/tests/topic_recreate_test.cc, src/v/utils/fragmented_vector.h, src/v/utils/tests/fragmented_vector_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16529
Fixes: https://github.com/redpanda-data/redpanda/issues/16621,
=> [v23.3.x] schemata: use chunked_vector for createable_topic

src/v/cluster/members_manager.h, src/v/redpanda/admin/api-doc/broker.json, src/v/redpanda/admin/api-doc/debug.json, src/v/redpanda/admin/debug.cc, src/v/redpanda/admin/server.cc, src/v/redpanda/admin/server.h, src/v/utils/uuid.cc, src/v/utils/uuid.h, tests/rptest/services/admin.py, tests/rptest/tests/admin_uuid_operations_test.py
Added few REST Admin APIs to help dealing with the need to override the node UUID and node id in failure scenarios. 
Following REST APIs were added:
__Querying current mapping between node UUID and node_id__
```
GET /v1/broker_uuids
```
__Querying node assigned node id and UUID__
```
GET /v1/debug/node_uuid
```
__Overriding node UUID and node id__
```
POST /v1/debug/node_uuid
```
- none
=> Node UUID admin

src/go/rpk/.golangci.yml, src/go/rpk/pkg/cli/redpanda/tune/tune.go, src/go/rpk/pkg/tuners/executors/commands/write_sized_file.go, src/go/rpk/pkg/tuners/executors/commands/write_sized_file_test.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/16576
Fixes: https://github.com/redpanda-data/redpanda/issues/16627, Fixes: https://github.com/redpanda-data/redpanda/issues/16628,
=> [v23.3.x] rpk: Improve tuner output script

src/v/archival/tests/ntp_archiver_test.cc, src/v/cloud_storage/tests/remote_partition_fuzz_test.cc, src/v/cloud_storage/tests/util.cc, src/v/cluster/config_manager.cc, src/v/config/bounded_property.h, src/v/config/property.h, src/v/config/tests/bounded_property_test.cc, src/v/config/tests/config_store_test.cc, src/v/net/conn_quota.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16504
Backport of PR https://github.com/redpanda-data/redpanda/pull/12952
=> [v23.2.x] config: update bindings when properties are reset

tests/rptest/perf/ts_write_openmessaging_test.py
Historical data for this test has shown the p75 end-to-end latency to always be around 4 to 6ms. This commit changes the validator to allow for p75 latency of 6ms or less to reduce the number of false positives in the nightly regression tests.
* none
=> Increase allowed p75 e2e latency for ts_write OMB test

src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/partition_manifest.h, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/tests/cloud_storage_e2e_test.cc, src/v/cloud_storage/tests/s3_imposter.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16645
Fixes: https://github.com/redpanda-data/redpanda/issues/16659,
=> [v23.3.x] cloud_storage: skip over segments below archive start

tests/rptest/archival/abs_client.py, tests/rptest/archival/s3_client.py, tests/rptest/scale_tests/many_partitions_test.py, tests/rptest/services/cluster.py, tests/rptest/services/redpanda.py, tests/rptest/test_suite_ec2.yml, tests/rptest/utils/scale_parameters.py
=> rptest/scale_test: enable test_many_partitions

tests/rptest/services/redpanda.py
=> Revert "rptest: remove config_file credential source support"

src/v/raft/tests/raft_fixture.cc, src/v/raft/tests/raft_reconfiguration_test.cc
The infinite loop trying to read batches that might have been out of range caused the test to timeout. Added a condition validating if read end offset in still in readable range.
- none
=> r/tests: removed infinite loop from raft test

src/v/raft/tests/raft_fixture.cc, src/v/raft/tests/raft_reconfiguration_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16675
=> [v23.3.x] r/tests: removed infinite loop from raft test

src/v/redpanda/admin/security.cc, src/v/redpanda/admin/server.cc, src/v/redpanda/admin/util.cc, src/v/redpanda/admin/util.h, src/v/redpanda/tests/CMakeLists.txt, src/v/redpanda/tests/util_tests.cc, tests/rptest/clients/rpk.py, tests/rptest/tests/rpk_acl_test.py
This PR fixes the bug that currently the + symbol is being improperly decoded to become a space character when it's found in a path parameter when path parameters are decoded using seastar's url decode method.
This PR solves this issue by introducing a `path_decode` method to properly decode path parameters and it starts using it throughout the admin API.
Fixes: https://github.com/redpanda-data/redpanda/issues/16129
* Fixes a bug in SASL user deletion and update where usernames with a + symbol in the username were prevented from being deleted
=> admin: fix path param parsing in admin api

src/go/rpk/pkg/cli/redpanda/admin/brokers/decommission-status.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/16693
=> [v23.3.x] rpk: update help text of decommission-status

tests/rptest/remote_scripts/topic_operations.py
Use lower timeout when creating topics
* none
=> PESDLC-890 Use timeout when creating topics

.github/workflows/scripts/backport-command/pr_details.sh, tests/docker/ducktape-deps/flink
Backport of PR https://github.com/redpanda-data/redpanda/pull/16427
=> [v23.3.x] slash-cmd: fix /backport command

src/go/rpk/pkg/cli/cloud/byoc/byoc.go, src/go/rpk/pkg/cli/cloud/byoc/install.go, src/go/rpk/pkg/config/params.go, src/go/rpk/pkg/oauth/load.go, src/go/rpk/pkg/oauth/oauth.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/16826
=> [v23.3.x] rpk: add debug logs to BYOC

src/v/redpanda/admin/security.cc, src/v/redpanda/admin/server.cc, src/v/redpanda/admin/util.cc, src/v/redpanda/admin/util.h, src/v/redpanda/tests/CMakeLists.txt, src/v/redpanda/tests/util_tests.cc, tests/rptest/clients/rpk.py, tests/rptest/tests/rpk_acl_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16694
=> [v23.3.x] admin: fix path param parsing in admin api

src/go/rpk/pkg/cli/profile/create.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/16836
=> [v23.3.x] rpk: remove timeout for profile create

src/go/rpk/pkg/cli/profile/create.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/16835
=> [v23.3.x] rpk: replace web UI url for cloud clusters

src/go/rpk/pkg/cli/profile/create.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/16835
=> [v23.2.x] rpk: replace web UI url for cloud clusters

src/go/rpk/pkg/adminapi/api_transform.go, src/v/redpanda/admin/transform.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16858
Fixes: https://github.com/redpanda-data/redpanda/issues/16884,
=> [v23.3.x] admin/transform/delete: path decode names

tests/rptest/scale_tests/many_topics_test.py, tests/rptest/scale_tests/topic_scale_profiles.py, tests/rptest/utils/node_operations.py
=> Add decomission lifecycle tests to topic scale tests

tests/rptest/scale_tests/many_topics_test.py, tests/rptest/scale_tests/topic_scale_profiles.py
=> Additional changes to ManyTopicsTest

src/v/crypto/key.cc, src/v/security/CMakeLists.txt, src/v/security/license.cc
Fixes: https://github.com/redpanda-data/core-internal/issues/1097
* none
=> security/license: Use crypto library

src/v/bytes/include/bytes/random.h, src/v/bytes/random.cc, src/v/crypto/include/crypto/crypto.h, src/v/crypto/random.cc, src/v/random/CMakeLists.txt, src/v/random/generators.cc, src/v/random/include/random/generators.h, src/v/security/scram_algorithm.h, src/v/security/scram_authenticator.cc
Fixes: https://github.com/redpanda-data/core-internal/issues/1124
* none
=> Add support for cryptolib RNG

src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_segment.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16886
=> [v23.3.x] cloud_storage: various non-functional changes

README.md
=> docs: update version in README

tests/rptest/tests/cluster_config_test.py
When setting a new configuration, the response is the new configuration version.
Before reading back we need to wait for this version to propagate to the whole cluster.
Extract from the result of rpk.cluster_config_set the new config version and wait for propagation before trying to reread it.
redpanda.set_cluster_config internally does the same wait
Fixes #16143 
* none
=> fix for cluster_config_test.py::test_aliasing 

tests/rptest/tests/cluster_config_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16931
Fixes: https://github.com/redpanda-data/redpanda/issues/16934,
=> [v23.3.x] fix for cluster_config_test.py::test_aliasing 

tests/rptest/scale_tests/many_topics_test.py, tests/rptest/services/consumer_swarm.py
Adds the remaining lifecycle tests to the `ManyTopicsTest`. Requires https://github.com/redpanda-data/redpanda/pull/16980 to be merged first.
* none
=> Additional topic scale lifecycle tests

src/v/config/configuration.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16972
=> [v23.3.x] config: Increase transform logs buffer cap

tests/rptest/tests/cloud_retention_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16943
Fixes: https://github.com/redpanda-data/redpanda/issues/16983,
=> [v23.3.x] rptest: Fix cloud_retention_test

install-dependencies.sh
=> dependencies: Added missing OpenSSL dependencies

tests/rptest/tests/tls_metrics_test.py
`tls_metrics_test.py::TLSMetricsTestExpiring.test_detect_expired_cert`
This test configures a 3-node cluster with _very_ short lived certificates.
Previously this test would check metrics for VALID certs, sleep 20s (the nominal lifetime of configured certs), then check metrics for INVALID certs. This flaked at least once under CDT when the certs had already expired by the time metrics became available.
In this case, we don't actually care about the initial VALID reporting, which is tested elsewhere, so we can remove the initial check and explicit sleep. Instead, just wait_until metrics report invalid certs.
Fixes #16462
* none
=> dt: Fix flaky TLS metrics test

src/v/net/connection.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16902
Fixes: https://github.com/redpanda-data/redpanda/issues/16997,
=> [v23.3.x] net: Added EHOSTUNREACH to retry list

tests/rptest/services/transform_verifier_service.py, tests/rptest/tests/data_transforms_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/16973
=> [v23.3.x] rptest: improve data transform tests

src/v/redpanda/admin/server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17011
=> [v23.3.x] admin/transform: 400 for missing topics

.github/workflows/buildkite-slash-commands.yml, .github/workflows/slash-commands.yml
=> Add /microbench slash command for running microbenchmarks

tests/rptest/services/consumer_swarm.py
Following up to merging of lifecycle tests, this PR fixes some consumer related issues that was missing from previous mega branch.
* none
=> PESDLC-953 ConsumerSwarm fixes

tests/docker/ducktape-deps/ocsf-server
Backport of PR https://github.com/redpanda-data/redpanda/pull/17024
=> [v23.3.x] ducktape: lint ocsf-server

src/v/cluster/cloud_metadata/offsets_recovery_service.h, tests/rptest/tests/recovery_mode_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/17013
=> [v23.3.x] Fix a segfault when recovery mode is partially enabled

src/v/storage/segment.cc, src/v/storage/tests/storage_e2e_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17039
=> [v23.3.x] storage: ensure monotonic stable offset updates

src/v/cluster/partition_leaders_table.cc, src/v/cluster/partition_leaders_table.h, src/v/container/include/container/contiguous_range_map.h
The partition leaders table contains all partition per topic. We may
replace the `btree_map` we used to hold per partition information with
more effective `contiguous_range_map`.
- none
=> Using `contiguous_range_map` in `partition_leaders_table`

src/v/cluster/types.cc
=> c/types: fix typo in operator<< for topic_properties

src/go/rpk/pkg/cli/cloud/auth/use.go, src/go/rpk/pkg/cli/profile/create.go, src/go/rpk/pkg/cli/profile/rename.go, src/go/rpk/pkg/cli/profile/use.go, src/go/rpk/pkg/config/params.go, src/go/rpk/pkg/config/rpk_yaml.go, src/go/rpk/pkg/oauth/load.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/17170
=> [v23.3.x] rpk profile double pointer fixes

tests/rptest/services/redpanda.py
Add pod status getter and update health checking/asserting to check for status
Fixes: #16956
* none
=> PESDLC-978 Add status check when conducting a health assertion of the cluster

src/v/wasm/wasi.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17186
=> [v23.3.x] wasm/wasi: properly return number of written bytes

src/v/cluster/cloud_metadata/tests/uploader_test.cc, src/v/cluster/config_frontend.cc, src/v/cluster/config_frontend.h, src/v/cluster/config_manager.cc, src/v/cluster/metrics_reporter.cc, src/v/cluster/service.cc, src/v/kafka/server/handlers/incremental_alter_configs.cc, src/v/kafka/server/tests/alter_config_test.cc, src/v/redpanda/admin/server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17088
=> [v23.3.x] cluster: invoke config_frontend methods on controller shard

src/v/cluster/security_frontend.h
Just a bit of documentation.
* none
=> cluster: Documentation for security_frontend.h

tests/rptest/remote_scripts/topic_operations.py
Related jira ticket: [PESDLC-986](https://redpandadata.atlassian.net/browse/PESDLC-986)
Fixes: #17132 
* none
[PESDLC-986]: https://redpandadata.atlassian.net/browse/PESDLC-986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PESDLC-986 Introduce randomized name checking mechanism

src/v/raft/coordinated_recovery_throttle.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16842
=> [v23.2.x] raft/recovery: better metric for recovery bandwidth consumption

src/v/storage/disk_log_impl.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17019
=> [v23.3.x] storage: mutex compaction and prefix truncation

tests/setup.py
Fixes: https://github.com/redpanda-data/core-internal/issues/1190
* none
=> CORE-31 dt: Use version of ducktape with updated paramiko

src/v/raft/coordinated_recovery_throttle.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/16842
=> [v23.3.x] raft/recovery: better metric for recovery bandwidth consumption

src/v/cluster/distributed_kv_stm.h
* Fixes a concurrency issue in transform offset commits pertaining to taking/applying snapshots.
=> stm/dist_kv_stm: missing co_awaits on snapshot lock

src/v/kafka/server/group_manager.cc, tests/java/e2e-verifiers/src/main/java/org/apache/kafka/tools/VerifiableConsumer.java, tests/rptest/tests/consumer_group_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/17260
=> [v23.3.x] k/group: recover leader epoch on leader change

licenses/third_party.md
Add license for unordered_dense
* none
=> licenses: Add unordered_dense license

src/v/raft/state_machine_manager.cc, src/v/raft/state_machine_manager.h, src/v/raft/tests/persisted_stm_test.cc, tests/rptest/tests/tiered_storage_enable_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/17112
Fixes: https://github.com/redpanda-data/redpanda/issues/17419,
=> [v23.3.x] Fixed not applying snapshot for new stms

src/v/cluster/tx_gateway_frontend.cc
=> tx: fix param ordering in log statement

tests/rptest/services/redpanda_installer.py, tests/rptest/tests/audit_log_test.py, tests/setup.py
Add support for disabling tests in FIPS mode
* None
=> CORE-14 disable tests that fail in fips

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/config/convert.h, src/v/config/property.h, src/v/config/rjson_serialization.cc, src/v/config/rjson_serialization.h, src/v/kafka/latency_probe.h, src/v/kafka/server/handlers/fetch.cc, src/v/model/metadata.h, src/v/model/model.cc
This PR removes the code for the old polling fetch implementation and marks the `fetch_read_strategy` property as deprecated. The property its self was only ever added to enable backporting the fetch implementation change to 23.3.x so there is no need to have it in 24.1.x.
* Marks the `fetch_read_strategy` cluster configuration property as deprecated 
* Removes `plan_and_execute_latency_us` histograms from internal metrics
=> Mark `fetch_read_strategy` cluster config property as deprecated

src/v/cluster/tx_gateway_frontend.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17433
=> [v23.3.x] tx: fix param ordering in log statement

src/v/archival/tests/ntp_archiver_reupload_test.cc, src/v/archival/tests/ntp_archiver_test.cc, src/v/cloud_storage/tests/cloud_storage_e2e_test.cc, src/v/cloud_storage/tests/delete_records_e2e_test.cc, src/v/cloud_storage/tests/read_replica_test.cc, src/v/cluster/cloud_metadata/tests/cluster_metadata_utils.h, src/v/cluster/cloud_metadata/tests/cluster_recovery_backend_test.cc, src/v/cluster/cloud_metadata/tests/offsets_recovery_test.cc, src/v/cluster/cloud_metadata/tests/producer_id_recovery_test.cc, src/v/cluster/controller_backend.cc, src/v/cluster/fwd.h, src/v/cluster/partition.cc, src/v/cluster/partition.h, src/v/cluster/partition_manager.h, src/v/cluster/partition_probe.cc, src/v/cluster/rm_partition_frontend.cc, src/v/cluster/rm_stm.h, src/v/cluster/tx_topic_manager.cc, src/v/kafka/server/replicated_partition.cc, src/v/kafka/server/tests/group_test.cc, src/v/redpanda/admin/partition.cc, src/v/redpanda/application.cc
Moved implementation to `.cc` file not to depend on full consensus and stm definitions.
- none
=> c/partition: cleaned up files included in partition.h

tests/rptest/tests/e2e_shadow_indexing_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/17474
Fixes: https://github.com/redpanda-data/redpanda/issues/17495,
=> [v23.3.x] rptest: Fix throttling test

src/v/archival/tests/async_data_uploader_test.cc
=> archival/tests: add include for archival_metadata_stm

src/v/raft/replication_monitor.cc, src/v/raft/replication_monitor.h
In cases of no waiters for majority replication index, it is wasteful to loop through all the waiters upon majority replication index notifications. This may happen because majority replication index can potentially move faster than committed index. This patch adds a small optimization to fix this gap by tracking if there are any pending waiters for majority replication.
* none
=> c/replication_monitor: majority replication optimization

install-dependencies.sh
Backport of PR https://github.com/redpanda-data/redpanda/pull/17520
=> [v23.3.x] deps: Add lz4-static for fedora

tests/rptest/tests/read_replica_e2e_test.py
Handle empty describe_topic result gracefully.
Fixes #17354
* none
=> rptest: Improve RRR end to end test

src/v/cluster/service.cc, src/v/cluster/topics_frontend.cc, src/v/cluster/topics_frontend.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/17544
=> [v23.3.x] c/topics_frontend: break the loop when dispatching to current leader

tests/rptest/remote_scripts/topic_operations.py
=> PESDLC-1084 Add copyright to topic_operations.py

src/v/storage/segment.h
=> storage: document semantics of the read interface

src/v/kafka/protocol/schemata/generator.py, src/v/kafka/protocol/tests/protocol_test.cc, src/v/kafka/protocol/wire.h, src/v/kafka/server/handlers/configs/config_response_utils.h, src/v/kafka/server/handlers/create_topics.cc, src/v/kafka/server/handlers/topics/topic_utils.cc, src/v/kafka/server/handlers/topics/topic_utils.h, src/v/kafka/server/handlers/topics/types.cc, src/v/kafka/server/handlers/topics/types.h, src/v/kafka/server/tests/alter_config_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17245
Fixes: CORE-2298
=> [v23.3.x] kafka: chunked_vector for config responses

tests/rptest/tests/cluster_config_test.py, tests/rptest/tests/control_character_flag_test.py
Previously some of the tests were updating Redpanda from some old unsupported version to the HEAD. This may cause any unexpected issues as we do not support such upgrade pattern. Change the test to work through all major versions from the requested one all the way to the most recent.
- none
=> tests: do not upgrade more than one feature version at a time

tests/rptest/tests/simple_e2e_test.py
There are no tests for the case where batch cache disabled. Add one into the mix.
* none
=> rptest: mix write caching with disabled batch cache

src/v/cloud_storage/segment_chunk.cc, src/v/cloud_storage/segment_chunk.h, src/v/cloud_storage/segment_chunk_api.cc, src/v/cloud_storage/segment_chunk_data_source.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17785
=> [v23.3.x] CORE-1752: cst: improved logging

tests/rptest/tests/controller_snapshot_test.py
The fix for changing the source type of the cleanup.policy config from DYNAMIC_TOPIC_CONFIG to DEFAULT_CONFIG is backported to v23.3.x now, and so we need to relax the check in the test_upgrade_compat test to allow observing this config difference in the backported versions as well.
Relates to: https://redpandadata.atlassian.net/browse/CORE-2205
* none
=> dt: allow cleanup.policy config diff in backport

src/go/rpk/pkg/cli/transform/logs.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/17832
=> [v23.3.x] rpk/transform/logs: don't hang if the topic is empty

src/go/rpk/pkg/cli/transform/logs.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/17830
=> [v23.3.x] rpk/transform/logs: handle missing logs topic

src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_segment.h, src/v/cloud_storage/tests/remote_partition_fuzz_test.cc, src/v/cloud_storage/tests/util.cc, src/v/cloud_storage/tests/util.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/17805
Fixes: https://github.com/redpanda-data/redpanda/issues/17817,
=> [v23.3.x] CORE-2321: cloud_storage: Fix remote_partition stuck reader

tests/rptest/tests/recovery_mode_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/17708
Fixes: https://github.com/redpanda-data/redpanda/issues/17732,
=> [v23.3.x] tests: wait for partition leaders before querying hwm

src/go/rpk/pkg/cli/transform/init.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/17831
=> [v23.3.x] rpk/transform/init: fix --install-deps flag

src/v/cloud_storage_clients/s3_client.cc
Introduced in https://github.com/redpanda-data/redpanda/pull/17666 Fixes https://github.com/redpanda-data/redpanda/issues/17862
Also,
Fixes https://github.com/redpanda-data/redpanda/issues/17842
Fixes https://github.com/redpanda-data/redpanda/issues/17858 
Fixes https://github.com/redpanda-data/redpanda/issues/17849
Fixes https://github.com/redpanda-data/redpanda/issues/17843
* none
=> s3_client: fix typo in log statement format specifier

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/17705
=> [v23.2.x] CORE-1705 rptest: filter abort strings from  GCP headers

src/v/cluster/tx_gateway_frontend.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17433
=> [v23.2.x] tx: fix param ordering in log statement

src/v/cloud_storage_clients/client_pool.cc, tools/cmake_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/17027
=> [v23.2.x] tools/cmake_test: remove accidental env override

tests/rptest/services/cluster.py, tests/rptest/services/redpanda.py, tests/rptest/services/utils.py
=> PESDLC-1121 Use test start time to capture proper logs

src/v/kafka/server/group_manager.cc, src/v/kafka/server/group_recovery_consumer.cc, src/v/kafka/server/group_recovery_consumer.h, src/v/kafka/server/replicated_partition.cc, src/v/kafka/server/replicated_partition.h, src/v/raft/consensus.cc, src/v/raft/consensus.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/17498
Backport of PR https://github.com/redpanda-data/redpanda/pull/17673
Backport of PR https://github.com/redpanda-data/redpanda/pull/16560
=> Backport of #17673  #17498 #16560 

src/v/kafka/protocol/logger.cc
Fixes include file compilation bug
* none
=> kafka: Fix utils.h include path

src/v/kafka/protocol/logger.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17931
=> [v23.2.x] kafka: Fix utils.h include path

tests/docker/ducktape-deps/client-swarm
Pull in the "paced" producer/consumer spawn change
* none
=> ducktape: Update client-swarm deps

src/v/cloud_storage/segment_chunk_api.cc, src/v/cloud_storage/segment_chunk_data_source.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17828
=> [v23.2.x] CORE-1752: cst: Downgrade error logs to debug

src/v/cloud_storage/segment_chunk_api.cc, src/v/cloud_storage/segment_chunk_data_source.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17828
=> [v23.3.x] CORE-1752: cst: Downgrade error logs to debug

src/v/kafka/server/group_manager.cc, src/v/kafka/server/group_recovery_consumer.cc, src/v/kafka/server/group_recovery_consumer.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/17673
=> [v23.3.x] Abort recovery when the recovery read is incomplete

src/v/cluster/health_monitor_backend.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17912
=> [v23.3.x] c/hm_backend: cache the collected report

src/v/cluster/members_manager.h, src/v/redpanda/admin/api-doc/broker.json, src/v/redpanda/admin/api-doc/debug.json, src/v/redpanda/admin/debug.cc, src/v/redpanda/admin/server.cc, src/v/redpanda/admin/server.h, src/v/utils/uuid.cc, src/v/utils/uuid.h, tests/rptest/services/admin.py, tests/rptest/tests/admin_uuid_operations_test.py
=> [v23.3.x] Backport of #16243

src/v/cluster/controller_backend.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/18021
Fixes: https://github.com/redpanda-data/redpanda/issues/18037,
=> [v23.3.x] c/controller_backend: try to force-abort reconfiguration only on leaders

cmake/dependencies.cmake
=> cmake: upgrade wasmtime

cmake/dependencies.cmake
Backport of PR https://github.com/redpanda-data/redpanda/pull/18069
=> [v24.1.x] cmake: upgrade wasmtime

src/v/config/configuration.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17906
=> [v23.3.x] [CORE-2400] kafka/server: Disable quota balancer

src/v/storage/log_reader.cc
Switches out the recursive implementation of do_load_slice for one that
uses coroutines and a while loop. It has been seen that the recursion
can result in a stack overflow when the number of segments is very high.
Note to reviewers: there are no major functional changes intended by this PR, beyond the removal of recursion.
* Fixes a crash that could happen when reading from local storage with a large number of segments that all do not contain user data.
=> storage: coroutinize/de-recursify log_reader::do_load_slice

src/v/storage/log_reader.cc
Switches out the recursive implementation of do_load_slice for one that uses coroutines and a while loop. It has been seen that the recursion can result in a stack overflow when the number of segments is very high.
(cherry picked from commit 41a7a1a473b92e4006e29d1c319f75538e7feafc)
Backport of https://github.com/redpanda-data/redpanda/pull/18073
Note, this is a preemptive backport, and was a clean backport.
* Fixes a crash that could happen when reading from local storage with a large number of segments that all do not contain user data.
=> [v24.1.x] storage: coroutinize/de-recursify log_reader::do_load_slice

.github/workflows/lint-cpp.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/18087
=> [v23.3.x] gh: fix lint-cpp for ubuntu noble

.github/workflows/lint-cpp.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/18087
=> [v24.1.x] gh: fix lint-cpp for ubuntu noble

src/v/wasm/parser/parser.cc, src/v/wasm/parser/tests/parser_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/18077
=> [v23.3.x] wasm/parser: fix global parsing

src/v/wasm/parser/parser.cc, src/v/wasm/parser/tests/parser_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/18077
=> [v24.1.x] wasm/parser: fix global parsing

src/go/rpk/pkg/cli/cluster/partitions/list.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/17945
=> [v23.3.x] rpk: add --node-ids option to rpk cluster partitions list

src/go/kreq-gen/go.mod, src/go/kreq-gen/go.sum, src/go/kreq-gen/kafka-request-generator.go, src/v/kafka/CMakeLists.txt, src/v/kafka/protocol/alter_client_quotas.h, src/v/kafka/protocol/describe_client_quotas.h, src/v/kafka/protocol/fwd.h, src/v/kafka/protocol/schemata/CMakeLists.txt, src/v/kafka/protocol/schemata/alter_client_quotas_request.json, src/v/kafka/protocol/schemata/alter_client_quotas_response.json, src/v/kafka/protocol/schemata/describe_client_quotas_request.json, src/v/kafka/protocol/schemata/describe_client_quotas_response.json, src/v/kafka/protocol/schemata/generator.py, src/v/kafka/protocol/tests/field_parser_test.cc, src/v/kafka/protocol/tests/protocol_test.cc, src/v/kafka/protocol/types.cc, src/v/kafka/protocol/types.h, src/v/kafka/protocol/wire.h, src/v/kafka/server/handlers/alter_client_quotas.cc, src/v/kafka/server/handlers/alter_client_quotas.h, src/v/kafka/server/handlers/describe_client_quotas.cc, src/v/kafka/server/handlers/describe_client_quotas.h, src/v/kafka/server/handlers/handlers.h, src/v/security/audit/schemas/utils.cc, tests/rptest/clients/kafka_cli_tools.py, tests/rptest/tests/quota_management_test.py
This PR starts the work for implementing the AlterClientQuotas and DescribeClientQuotas Kafka API endpoints for managing client quotas in Redpanda.
It introduces a new native type (float64) that these APIs use, it imports the schemata corresponding to these APIs, and it implements two minimal handlers for these endpoints.
Closes https://redpandadata.atlassian.net/browse/CORE-2405
* none
=> CORE-2405 - kafka: add noop AlterClientQuotas/DescribeClientQuotas handlers

src/go/rpk/pkg/cli/container/common/common.go, src/go/rpk/pkg/cli/container/start.go, src/go/rpk/pkg/cli/container/start_test.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/17908
=> [v24.1.x] rpk container: offer port selection on start

src/v/cluster/cluster_discovery.cc
=> Fix typo in cluster_discovery.cc

tests/rptest/tests/simple_e2e_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/18131
Fixes: https://github.com/redpanda-data/redpanda/issues/18136,
=> [v24.1.x] tests: adjust time between failures in relaxed consistency test

src/go/rpk/pkg/cli/container/common/common.go, src/go/rpk/pkg/cli/container/purge.go, src/go/rpk/pkg/cli/container/start.go, src/go/rpk/pkg/cli/container/stop.go, src/go/rpk/pkg/config/config.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/18066
Fixes #18163
=> [v24.1.x] rpk: Start a Redpanda Console container with `rpk container start`

src/v/cluster/topic_table.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/15407
=> [v23.3.x] c/topic_table: do not log duplicated lifecycle marker command

src/v/redpanda/admin/server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/18094
Fixes: https://github.com/redpanda-data/redpanda/issues/18101,
=> [v23.3.x] admin: fixed mapping of service unavailable error code

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/kafka/server/tests/consumer_groups_test.cc, src/v/storage/disk_log_impl.cc, tests/rptest/tests/transactions_test.py
This a special configuration some select users can use to enable
delete retention on CO topic because the compaction logic is ineffective
and they would like to use retention as a stop gap until that is fixed.
This configuration will be deprecated once we address the compaction gaps.
Should be untouched for all practical purposes.
* none
=> configuration to enable delete retention for consumer offsets

src/v/storage/log_reader.cc
CONFLICT:
- removed logic for ghost batches, offset translation, and depth logging
Switches out the recursive implementation of do_load_slice for one that uses coroutines and a while loop. It has been seen that the recursion can result in a stack overflow when the number of segments is very high.
(cherry picked from commit 41a7a1a473b92e4006e29d1c319f75538e7feafc)
Backport of https://github.com/redpanda-data/redpanda/pull/18073
Fixes https://github.com/redpanda-data/redpanda/issues/18081
* Fixes a crash that could happen when reading from local storage with a large number of segments that all do not contain user data.
=> [v23.3.x] storage: coroutinize/de-recursify log_reader::do_load_slice

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/kafka/server/tests/consumer_groups_test.cc, src/v/storage/disk_log_impl.cc, tests/rptest/tests/transactions_test.py
This a special configuration some select users can use to enable
delete retention on CO topic because the compaction logic is ineffective
and they would like to use retention as a stop gap until that is fixed.
This configuration will be deprecated once we address the compaction gaps.
Should be untouched for all practical purposes.
Fixes https://github.com/redpanda-data/redpanda/issues/18188
* none
=> [backport][23.3.x] configuration to enable delete retention for consumer offsets #18140

src/v/cloud_storage/remote_partition.cc
Improve logging and error handling in the remote_partition. In the remote partition reader we're checking two abort_source instances. One belongs to the remote_partition instance and another belongs to the sharded_abort_source that belongs to the kafka request ctx. The last abort source is used to propagate exceptions from kafka layer. The abort_source in the remote_partition is not used for this purpose. It's only used to shutdown and therefore its 'check' method only throws 'abort_requested_exception'.
Because of that any kafka disconnection error triggers error level logging in TS. This commit changes behavior a bit. In case if the exception from the kafka layer is triggered by the disconnect the error is converted to simple shutdown error.
* none
=> cloud_storage: Improve logging and error handling

src/transform-sdk/README.md, src/transform-sdk/go/transform/README.md, src/transform-sdk/rust/scripts/publish.py, src/v/transform/README.md, src/v/transform/logging/README.md, src/v/transform/rpc/README.md, src/v/transform/rpc/include/transform/rpc/client.h, src/v/transform/stm/README.md, src/v/wasm/README.md
=> transform: add documentation to the transform subsystem

src/v/redpanda/admin/server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/18094
Fixes: https://github.com/redpanda-data/redpanda/issues/18100,
=> [v24.1.x] admin: fixed mapping of service unavailable error code

src/v/wasm/wasmtime.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/18225
=> [v24.1.x] wasm: fix host function arg translation

src/v/wasm/wasmtime.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/18225
=> [v23.3.x] wasm: fix host function arg translation

tests/rptest/services/redpanda_cloud.py
Cluster creation does not validates value of CIDR network from globals.yaml.
This PR adds the validation.
Fixes: #18183, #18175, #18177, #18178, #18179, #18180, #18181, #18182
* none
=> PESDLC-1317 Fix cluster creation with private network

src/v/cluster/tests/tm_stm_tests.cc, src/v/cluster/tm_stm.cc, src/v/cluster/tm_stm.h, src/v/cluster/tx_gateway_frontend.cc, src/v/cluster/tx_gateway_frontend.h, src/v/config/configuration.cc, tests/rptest/tests/transactions_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/18198
=> [v24.1.x] tx/tm_stm: fix unboundedness of _pid_tx_id

src/v/cloud_storage/tests/topic_manifest_test.cc, src/v/cloud_storage/topic_manifest.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/17461
=> [v24.1.x] [CORE-2161] cloud_storage/topic_manifest: force negative retention to mean infinite retention

tests/rptest/services/redpanda_cloud.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/18230
Fixes: https://github.com/redpanda-data/redpanda/issues/18249,
=> [v24.1.x] PESDLC-1317 Fix cluster creation with private network

src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment.h, src/v/cloud_storage/segment_chunk_api.cc, src/v/cloud_storage/segment_chunk_api.h, tests/rptest/tests/cloud_storage_chunk_read_path_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/18093
=> [v23.3.x] [CORE-2581] cst: move chunk downloads to remote segment bg loop

tests/rptest/tests/e2e_shadow_indexing_test.py
Since latest seastar upgrade it seems that downloads are sligthly slower. Adjust throughput limit so that throttling is still hit.
* none
=> rptest: adjust test throughput limit

tests/rptest/clients/offline_log_viewer.py, tests/rptest/tests/transactions_test.py, tools/offline_log_viewer/kafka.py, tools/offline_log_viewer/viewer.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/18246
=> [v24.1.x] offline_log_viewer: fix get_control_record_type

src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h, src/v/cluster/tests/rm_stm_test_fixture.h, src/v/cluster/tests/rm_stm_tests.cc
In some very rare cases there may be transaction that is marked begun but hasn't produced
any data batches. If the client goes awol at this point, the transaction may never be expired
due to the current expiration logic thus stalling the LSO.
This is not an issue in dev due to https://github.com/redpanda-data/redpanda/pull/18076
Fixes https://github.com/redpanda-data/redpanda/issues/18317
* Fixes expiration for transactions that have begun and not produced any data batches. This prevents a stalling LSO.
=> [backport] [v24.1.x] rm_stm: consider transactions without data batches for expiration 

tests/rptest/services/redpanda_installer.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/18387
=> [v24.1.x] [dt] add retries to remote curl call

src/v/archival/ntp_archiver_service.cc, src/v/archival/ntp_archiver_service.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/18285
=> [v24.1.x] archival: clamp uploads to committed offset

tests/rptest/services/redpanda_installer.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/18387
=> [v23.2.x] [dt] add retries to remote curl call

src/v/ssx/include/ssx/task_local_ptr.h
Use task counter instead of the task pointer.
Fixes #18421
* none
=> ssx: Update task local ptr

tests/rptest/services/redpanda.py
=> CORE-2931 Fix wrong version in is_fips_capable

tests/rptest/services/redpanda_installer.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/18387
=> [v23.3.x] [dt] add retries to remote curl call

tests/rptest/tests/cpu_stress_injection_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/18463
Fixes: https://github.com/redpanda-data/redpanda/issues/18474,
=> [v24.1.x] rptest: be more permissive with errors in stress fibers test

src/v/raft/consensus.cc, src/v/raft/vote_stm.cc, src/v/raft/vote_stm.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/18394
=> [v24.1.x] Do not request votes if term changed in prevote phase

tests/rptest/tests/cloud_storage_scrubber_test.py
The scrubber test may remove the first segment in the manifest. This causes a difference between the manifest start offset and the first segment start offset. The mismatch causes a validation to fail when spillover is applied (which is correct behavior).
To avoid the test failing due to this expected set of events, the error log is accepted in the test.
FIXES https://github.com/redpanda-data/redpanda/issues/17535
FIXES https://github.com/redpanda-data/redpanda/issues/16474
* none
=> cst/ducktape: Accept errors due to gap in manifest

src/v/cluster/tests/partition_balancer_simulator_test.cc
Added an edge case test where a cluster is almost at the capacity. Multiple topics with different partition count and replication factors are used in the test.
The test validates adding and then decommissioning a single node.
- none
=> c/tests: added an edge case test for partition balancer

src/v/utils/file_io.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/18303
Fixes: https://github.com/redpanda-data/redpanda/issues/18443,
=> [v23.3.x] [CORE-2814]: utils/file_io: fix double closing of ss::file in write_fully

src/go/rpk/pkg/adminapi/api_partition.go, src/go/rpk/pkg/cli/cluster/partitions/partitions.go, src/go/rpk/pkg/cli/cluster/partitions/transfer_leadership.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/18026
Fixes: https://github.com/redpanda-data/redpanda/issues/18460,
=> [v23.3.x] rpk: add transfer-leadership command

src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/schema_registry/handlers.cc, src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h, tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/18391
=> [v23.3.x] [CORE-2831] schema_registry: Allow deleted=true for post_subject

src/v/archival/ntp_archiver_service.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/18526
Fixes: https://github.com/redpanda-data/redpanda/issues/18532, Fixes: https://github.com/redpanda-data/redpanda/issues/18534, Fixes: https://github.com/redpanda-data/redpanda/issues/18536, Fixes: https://github.com/redpanda-data/redpanda/issues/18538, Fixes: https://github.com/redpanda-data/redpanda/issues/18540, Fixes: https://github.com/redpanda-data/redpanda/issues/18542, Fixes: https://github.com/redpanda-data/redpanda/issues/18532, Fixes: https://github.com/redpanda-data/redpanda/issues/18544, Fixes: https://github.com/redpanda-data/redpanda/issues/18546, Fixes: https://github.com/redpanda-data/redpanda/issues/18548, Fixes: https://github.com/redpanda-data/redpanda/issues/18550, Fixes: …
=> [v24.1.x] archival: Disable housekeeping jobs on startup

tests/rptest/tests/topic_recovery_test.py
Previously we incorrectly calculated replaced segment keys in cloud storage, and replaced segments weren't marked as such, resulting in incorrect cloud storage size calculation.
* none
=> tests: fix replaced segments accounting in TopicRecoveryTest

tests/rptest/tests/topic_recovery_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/18603
=> [v23.3.x] tests: fix replaced segments accounting in TopicRecoveryTest

src/v/storage/log_manager.cc, src/v/storage/log_manager.h
Fixes the broken promise resulting from a race during shutdown.
Backport of PR https://github.com/redpanda-data/redpanda/pull/17910
Fixes https://github.com/redpanda-data/redpanda/issues/17929
* none
=> [backport][v23.3.x] log_manager: gate orphan file cleanup #17910

src/v/cluster/scheduling/types.cc, src/v/cluster/topic_table.cc, src/v/cluster/topic_table.h, src/v/utils/exceptions.h, src/v/utils/stable_iterator_adaptor.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/18305
=> [v23.2.x] Fix some concurrent memory access problems in partition balancer

src/v/raft/state_machine_manager.cc, src/v/raft/state_machine_manager.h, src/v/raft/tests/stm_manager_test.cc, src/v/raft/tests/stm_test_fixture.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/18626
=> [v23.3.x] Fixed `state_machine_manager` stall

src/go/rpk/pkg/adminapi/api_partition.go, src/go/rpk/pkg/cli/cluster/partitions/partitions.go, src/go/rpk/pkg/cli/cluster/partitions/transfer_leadership.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/18026
Fixes: https://github.com/redpanda-data/redpanda/issues/18458,
=> [v24.1.x] rpk: add transfer-leadership command

src/go/rpk/pkg/cli/cloud/login.go, src/go/rpk/pkg/cli/profile/create.go, src/go/rpk/pkg/cli/topic/consume.go, src/go/rpk/pkg/cli/transform/deploy.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/18628
Fixes: https://github.com/redpanda-data/redpanda/issues/18631,
=> [v24.1.x] rpk: small fixes.

src/v/pandaproxy/schema_registry/configuration.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/18635
=> [v24.1.x] schema_registry: Make mode_mutability: true by default

tests/rptest/archival/s3_client.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/18491
=> [v24.1.x] PESDLC-876 Add Filehandlers to boto3 loggers

src/v/utils/base64.cc, src/v/utils/tests/CMakeLists.txt, src/v/utils/tests/base64_test.cc
Removed hand written implementation of base64 url decode with Abseil version: 
https://github.com/redpanda-data/redpanda/pull/18195#issuecomment-2098146957
* None
=> CORE-2812: utils/b64: Replaced implementation with abseil

src/v/raft/recovery_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/18680
=> [v24.1.x] r/recovery_stm: log taking on demand snapshot at info level

tests/rptest/perf/openmessaging_perf_test.py, tests/rptest/perf/ts_read_openmessaging_test.py, tests/rptest/perf/ts_write_openmessaging_test.py
Reduces throughput in perf regression tests to cap reactor utilization to around 80-90% per test.
* none
=> rptest: reduce throughput in perf tests

src/v/cluster/CMakeLists.txt, src/v/cluster/client_quota_serde.cc, src/v/cluster/client_quota_serde.h, src/v/cluster/client_quota_store.cc, src/v/cluster/client_quota_store.h, src/v/cluster/tests/CMakeLists.txt, src/v/cluster/tests/client_quota_store_test.cc
This introduces the basic blocks of the quota store data model. It introduces the `entity_key` and `entity_value` which are going to be used to store client quota configurations. It also introduces the in-memory `quota_store` which is going to store the quota configurations and expose the latest state of client quota configurations to Kafka handlers and the `quota_manager`. 
Fixes https://redpandadata.atlassian.net/browse/CORE-2698
* none
=> CORE-2698 `quota_store` data model and in-memory storage

src/go/rpk/pkg/cli/plugin_cmds.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/18723
=> [v24.1.x] rpk: explicitly add Arg validation to plugins

src/v/kafka/server/quota_manager.cc
Follow up to https://github.com/redpanda-data/redpanda/pull/18098 to reduce allocations during `gc` in the quota map, this computes the set intersection in-place in the reducer.
Context: https://github.com/redpanda-data/redpanda/pull/18098#discussion_r1601557961
Fixes https://redpandadata.atlassian.net/browse/CORE-376
* none
=> CORE-376 kafka/quota_mgr: gc with in-place set intersection

src/v/cloud_storage_clients/configuration.cc, src/v/config/configuration.cc, src/v/config/configuration.h
Minimal change to configure a CRL file for cloud storage clients. Not sure exactly how this will work as the general approach is to use system trust. Perhaps we should be pointing to a "system" CRL instead...
* none
=> CORE-2441 - Introduce `cloud_storage_crl_file` config

src/v/archival/fwd.h, src/v/archival/types.h, src/v/cloud_storage/remote.cc, src/v/cloud_storage/remote.h, src/v/cloud_storage/remote_segment_index.h, src/v/config/configuration.cc, src/v/container/include/container/fragmented_vector.h, src/v/model/fundamental.h, src/v/model/ktp.h, src/v/storage/batch_consumer_utils.h, src/v/storage/tests/CMakeLists.txt, src/v/storage/tests/batch_consumer_utils_test.cc
Various utilities and fixes for ntp-archiver rework
* None
=> archival: Data upload path groundwork

src/v/cluster/scheduling/leader_balancer_constraints.cc, src/v/cluster/scheduling/leader_balancer_constraints.h, src/v/cluster/scheduling/leader_balancer_greedy.h, src/v/cluster/scheduling/leader_balancer_random.h, src/v/cluster/scheduling/leader_balancer_types.h, src/v/cluster/tests/leader_balancer_bench.cc, src/v/cluster/tests/leader_balancer_constraints_test.cc, src/v/cluster/tests/leader_balancer_test.cc, src/v/cluster/tests/leader_balancer_test_utils.h
By changing the indexes from per node to per shard we avoid getting stuck in local minimas where topics are even distributed across the nodes, but the partition leadership isn't evenly distributed across the shards.
Fixes: https://github.com/redpanda-data/core-internal/issues/1282
* none
=> Change even topic constraint indexes to per shard

src/go/rpk/pkg/cli/cluster/config/get.go, tests/rptest/tests/cluster_config_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/18841
=> [v24.1.x] rpk: display float values as float in cluster config get

src/go/rpk/pkg/cli/cluster/config/get.go, tests/rptest/tests/cluster_config_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/18841
=> [v23.3.x] rpk: display float values as float in cluster config get

.github/workflows/backport-command.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/19793
=> [v24.1.x] gha: fix backport-command type-branch job to retrieve aws sm token

src/v/json/schema.h, src/v/pandaproxy/schema_registry/json.cc, src/v/pandaproxy/schema_registry/test/test_json_schema.cc
use json schema draft 4 [metaschema](https://json-schema.org/draft-04/schema) to validate input schemas
Fixes https://redpandadata.atlassian.net/browse/CORE-3180
* none
=> [CORE-3180] json schema registry validate input schema

src/v/storage/disk_log_impl.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/19790
=> [v23.3.x] s/disk_log_impl: don't prefix-truncate empty segments

src/v/redpanda/admin/debug.cc, src/v/resource_mgmt/cpu_profiler.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/18736
=> [v24.1.x] cpu_profiler: prealloc result buffers

tests/rptest/tests/scaling_up_test.py
Previously the test was using an on disk size to validate the correctness of move policy. Switched to use partition size metrics as they are more accurate and it is easier to assert the correct result.
- none
=> tests: use partition size metrics in test verifying local retention move

tests/rptest/clients/offline_log_viewer.py, tests/rptest/tests/random_node_operations_test.py, tests/rptest/tests/upgrade_test.py, tools/offline_log_viewer/controller.py, tools/offline_log_viewer/model.py, tools/offline_log_viewer/reader.py, tools/offline_log_viewer/viewer.py
Added support for decoding controller snapshots to offline metadata viewer.
- none
=> Offline viewer ctrl snapshot

src/v/cluster/CMakeLists.txt, src/v/cluster/tests/tm_stm_tests.cc, src/v/cluster/tm_stm.cc, src/v/cluster/tm_stm.h, src/v/cluster/tm_stm_cache.cc, src/v/cluster/tm_stm_cache.h, src/v/cluster/tm_stm_types.cc, src/v/cluster/tm_stm_types.h, src/v/cluster/tx_gateway.cc, src/v/cluster/tx_gateway_frontend.cc, src/v/cluster/tx_gateway_frontend.h, src/v/kafka/server/server.cc, src/v/model/record.h, src/v/redpanda/admin/partition.cc, src/v/redpanda/admin/transaction.cc
Cleaned up some code in transaction manager area including:
- reduced number of transactional id copies for lookups
- aligned transaction state print format with rest of the code
- using strong `named_type` in `model::producer_identity` 
- none
=> Minor refactoring of transactional coordinator code

src/v/kafka/server/handlers/client_quotas.cc, tests/rptest/tests/quota_management_test.py
This adds more tests around the kafka client quota api with kafka-configs.sh which is the main non-rpk client that we expect this api to be used with. This testing also discovered a bug in the alter implementation where the `entries[].entity` field in the response was not filled -- kafka-configs.sh expects this to be set.
Note that kafka-configs.sh won't see any responses with the client-id-prefix entity type, so we won't and can't test that. This is because kafka-configs.sh only sends requests with the `strict` field set to `true` (See [here](https://github.com/apache/kafka/blob/768e90f6673fd484f0ca64a628cda4cb8383c385/core/src/main/scala/kafka/admin/ConfigCommand.scala#L690) only `ClientQuotaFilter.containsOnly(...)` is ever used).
As an alternative way of testing against …
=> CORE-2700 quotas: validate with non-rpk clients

src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/api/api-doc/schema_registry_header.json, src/v/pandaproxy/schema_registry/handlers.cc, tests/rptest/tests/schema_registry_test.py
Improve handling of Accept and Content-Type
* Schema Registry: Improve handling of Accept and Content-Type
=> [CORE-4204] schema_registry: Improve handling of Accept and Content-Type

src/v/pandaproxy/schema_registry/errors.h, src/v/pandaproxy/schema_registry/json.cc, src/v/pandaproxy/schema_registry/json.h, src/v/pandaproxy/schema_registry/test/test_json_schema.cc
Implementation of `bool check_compatible(const json_schema_definition& reader, const json_schema_definition& writer);` 
for string, numeric JSON types, to allow checking compatibility of a subset of JSON schema draft 4
The checking is done by traversing both schemas, looking for a rule in the writer schema that is less strict than its counterpart in the reader schema. 
If no such rule is found, then the result is true
Fixes: https://redpandadata.atlassian.net/browse/CORE-3183
* none
=> [CORE-3183] schema registry json compatibility checks for primitive types

src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/api/api-doc/schema_registry_header.json, src/v/pandaproxy/schema_registry/handlers.cc, tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/19866
=> [v23.3.x] [CORE-4204] schema_registry: Improve handling of Accept and Content-Type

src/v/raft/consensus.cc, src/v/raft/probe.cc, tests/rptest/tests/raft_availability_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/19873
=> [v23.3.x] Refined leadership changed metrics

src/v/kafka/server/client_quota_translator.h, src/v/kafka/server/quota_manager.cc, src/v/kafka/server/quota_manager.h, src/v/utils/log_hist.cc, src/v/utils/log_hist.h, tests/rptest/tests/cluster_quota_test.py
This adds two new metrics that provide insight into why and how throttling is happening inside `quota_manager`.
* `client_quota_throttle_time`: shows how much delay is being applied to client requests because of throttling.
* `client_quota_throughput`: shows the throughput that is used to calculate the throttling delays from
Both metrics are at the granularity of per rule and per quota type, to provide a high-level view into why and where throttling is happening. For client-id-specific insight, the trace level logger (`kafka_quotas`) can be used.
Fixes https://redpandadata.atlassian.net/browse/CORE-2715
* none
=> CORE-2715 Quotas: add metrics on client throttling

src/v/cluster/cluster_utils.cc, src/v/cluster/controller_probe.cc, src/v/cluster/tests/serialization_rt_test.cc, src/v/config/types.h, src/v/model/fundamental.h, src/v/model/metadata.h, src/v/model/model.cc, src/v/redpanda/admin/api-doc/broker.json, src/v/redpanda/admin/server.cc, src/v/redpanda/application.cc, tests/rptest/services/redpanda.py, tests/rptest/tests/redpanda_startup_test.py
Adds two metrics:
* `fips_mode`
* `non_homogenous_fips_mode`
* None
=> CORE-2443 FIPS metrics

src/v/raft/consensus.cc, src/v/raft/probe.cc, tests/rptest/tests/raft_availability_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/19873
=> [v24.1.x] Refined leadership changed metrics

tests/rptest/tests/archival_test.py, tests/rptest/tests/control_character_flag_test.py, tests/rptest/tests/partition_movement_test.py, tests/rptest/tests/random_node_operations_test.py, tests/rptest/tests/read_replica_e2e_test.py, tests/rptest/tests/tiered_storage_model_test.py, tests/rptest/tests/upgrade_test.py, tests/rptest/tests/workload_upgrade_runner_test.py
=> PESDLC-1564: Moved location of ok_to_fail_fips mark on tests

tests/rptest/tests/scaling_up_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/19932
Fixes: https://github.com/redpanda-data/redpanda/issues/19962,
=> [v24.1.x] tests: fixed test validating disk size when moving with local retention

tests/rptest/services/redpanda.py
=> dt: Fix pickle error

tests/rptest/tests/redpanda_startup_test.py
To be addressed by CORE-4283
* None
=> CORE-3241 Mark RedpandaFIPSStartupTests as ok_to_fail

src/v/crypto/CMakeLists.txt
=> CORE-4199 split ossl build

src/go/rpk/pkg/cli/container/start.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/19948
=> [v24.1.x] rpk: improve help text and minor bug fix

src/v/crypto/CMakeLists.txt
Backport of PR https://github.com/redpanda-data/redpanda/pull/19943
=> [v24.1.x] CORE-4199 split ossl build

src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/schema_registry/handlers.cc, src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h, tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/18391
=> [v23.2.x] [CORE-2831] schema_registry: Allow deleted=true for post_subject

src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/schema_registry/handlers.cc, src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h, src/v/pandaproxy/schema_registry/store.h, tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/20145
=> [v23.3.x] [CORE-4442] schema_registry: Support subjectPrefix for get_subjects

tests/rptest/services/redpanda.py
Redpanda can self-discover that in FIPS mode, it will connect to s3-fips.<region>.amazonaws.com.  Much of the code to force it in redpanda.py was removed except for this conditional.
* None
=> [CORE-4598] Fix bug causing CDT FIPS failure

src/v/http/client.cc
Previously, we would call `client::stop()` upon encountering TLS errors in `client::send_some()`, `client::recv_some()` and `client::make_request()`. These stopped `client`s would not be removed from the `client_pool`, resulting in erroneous use for future requests.
Change the default behaviour from calling `stop()` to `shutdown()`, which leaves `client` in a usable state for the future, after a connection is re-attempted.
Also improve logging around TLS errors, `_connect_gate`, and add checks around the state of `_stopped` in `client::make_request()` and `get_connected()`.
* none
=> http: change `stop()` to `shutdown()` on TLS errors in `client`

src/v/cloud_roles/apply_abs_credentials.cc, src/v/cloud_roles/apply_abs_oauth_credentials.cc, src/v/cloud_roles/apply_gcp_credentials.cc, src/v/cloud_storage_clients/util.cc, src/v/json/json.h, src/v/net/include/net/transport.h, src/v/rpc/include/rpc/parse_utils.h, src/v/utils/unresolved_address.h
Some header improvements.
* none
=> chore: header improvements

src/v/http/client.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/20157
=> [v24.1.x] http: change `stop()` to `shutdown()` on TLS errors in `client`

tests/rptest/remote_scripts/topic_operations.py
For the sake of using it in transaction test workflow it is needed to have an ability to mass delete topics while in the middle of the test.
* none
=> PESDLC-1562 Implement topic delete in topic-operations

src/v/config/configuration.cc, src/v/config/convert.h, src/v/kafka/server/handlers/fetch.cc, src/v/model/metadata.h, src/v/model/model.cc
In workloads that are RPS-bound introducing back-pressure at strategic locations can help improve latency. Specifically this PR allows for fetches to be delayed before they begin work. This results in the fewer/larger fetch responses, reducing overall reactor utilization, and allowing for other requests such as produces to increase.
* Adds a new `fetch_read_strategy` option `non_polling_with_debounce`. This option will add a fixed delay specified by `fetch_reads_debounce_timeout` to the start of every fetch.
=> Add support for debounce in non-polling fetch

tests/rptest/tests/raft_availability_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/20378
Fixes: https://github.com/redpanda-data/redpanda/issues/20581,
=> [v23.3.x] tests: fixed querying new leader node in leadership transfer test

src/v/raft/tests/raft_fixture.cc, src/v/raft/tests/raft_fixture.h, src/v/raft/tests/raft_reconfiguration_test.cc
Raft force reconfiguration test is designed to skip one of the nodes when force updating configuration. In this scenario it may sometimes happen that the node which wasn't updated with the configuration override will become a leader. In this situation controller backend in Redpanda will retry. Added retries to the test to make sure the test will retry reconfiguration if it was reverted by node which was missing update.
Fixes: #19938
- none
=> tests: added retries to raft force reconfiguration test

tests/rptest/tests/shard_placement_test.py
Use `wait_shard_map_stationary` where appropriate because after node restart partitions can take some time to start and therefore a shard map queried after restart can be incomplete.
Fixes https://github.com/redpanda-data/redpanda/issues/20593
Fixes https://github.com/redpanda-data/redpanda/issues/19905
* none
=> tests: deflake shard_placement_test

src/v/raft/follower_stats.h, src/v/raft/heartbeat_manager.cc, src/v/raft/heartbeat_manager.h
When collecting heartbeat requests the heartbeat manager must iterate
over every single raft instance on the shard and then over all followers
of instances which are the leader. The request collection logic is now
synchronous. For now the loop do not cause reactor stalls but as we
increase the partition density it may eventually lead to stalling
reactor.
Changed the implementation to use `ssx::async_for_each` to yield
occasionally if needed.
- none
=>  Use `async_for_each` when collecting heartbeat requests

src/v/raft/state_machine_manager.cc, src/v/raft/state_machine_manager.h, src/v/raft/tests/stm_manager_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/18576
Fixes: https://github.com/redpanda-data/redpanda/issues/21252,
=> [v24.1.x] stm_manager: tighten interaction between bg application and snapshots 

tests/rptest/tests/controller_snapshot_test.py
The test is no longer relevant for 24.2 because 23.1 is already out of support and by the time 24.2 is released, 23.2 will be as well.
Fixes https://github.com/redpanda-data/redpanda/issues/18797
Fixes https://github.com/redpanda-data/redpanda/issues/18802
* none
=> tests: remove controller snapshot upgrade test

src/v/pandaproxy/error.cc, src/v/pandaproxy/error.h, src/v/pandaproxy/schema_registry/error.cc, src/v/pandaproxy/schema_registry/error.h, src/v/pandaproxy/schema_registry/errors.h, src/v/pandaproxy/schema_registry/store.h
=> pandaproxy: fix spelling of `operation`

src/v/raft/state_machine_manager.cc
followup to
https://github.com/redpanda-data/redpanda/pull/18576/commits/c8290e598e8ef527dda8dbe5ee7195c07bcede04#r1670879362
* none
=> stm_manager: do not explicitly clear units

src/v/redpanda/admin/debug.cc, src/v/resource_mgmt/cpu_profiler.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/18736
=> [v23.3.x] cpu_profiler: prealloc result buffers

src/v/cluster/partition.cc, tests/rptest/tests/timequery_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/21312
=> [v24.1.x] kafka: fix timequery when local log is empty

tests/rptest/tests/crl_test.py
There appears to be a slight timing issue between reloading the CRL and expecting the HTTP request to be rejected due to the certificate being revoked.
* None
=> CORE-4860: Add retry to expected exception

src/v/cluster/rm_stm.cc, src/v/redpanda/admin/partition.cc, src/v/redpanda/admin/server.cc, tests/rptest/transactions/tx_admin_api_test.py
The test does duplicate expirations which results in a ERROR log
in the brokers. The duplicate expirations stem from the fact that the
previous test logic explicitly marked a producer for expiration on every
ntp involved in the transaction. This is not needed as the expiration is
routed through the coordinator and that aborts the transaction on all
participants. Refactored the test logic accordingly.
Fixes https://github.com/redpanda-data/redpanda/issues/19322
* none
=>  tx/tests: deflake test_mark_transaction_expire

tests/rptest/tests/rbac_test.py
=> CORE-5548 Ignore license nag test in FIPS mode

src/v/crypto/tests/crypto_bench.cc
OpenSSL doesn't appear to like being initialized, uninitialized, and then re-initialized by the same process over and over again.  This results in some memory being left around and reused even after being freed which is what was causing the crypto bench test to segfault and fail.  The solution is to only bring up the OpenSSL context service once per run and then bring it down when the Seastar engine is finishing up.
Fixes: CORE-4207
* None
=> crypto/bench: Only load context once per run

tests/rptest/services/kerberos.py, tests/rptest/tests/redpanda_kerberos_test.py
Default encryption algorithm uses HMAC-SHA1 which isn't permitted in FIPS mode.  Tests updated to use HMAC-SHA384.
Fixes: CORE-5579
Fixes: CORE-4869
Fixes: CORE-4547
Fixes: CORE-4546
* None
=> Fix kerberos in FIPS mode

cmake/FindAvro.cmake, cmake/v_library.cmake, src/v/CMakeLists.txt, src/v/iceberg/CMakeLists.txt, src/v/iceberg/avroschemas/manifest_entry.schema.json, src/v/iceberg/avroschemas/manifest_file.schema.json, src/v/iceberg/tests/CMakeLists.txt, src/v/iceberg/tests/manifest_serialization_test.cc
Apache Iceberg writes various metadata in Avro format. This commit
introduces Avro schema files that will be used for Iceberg manifest
files[1] and manifest entries[2].
With this commit, C++ classes are generated to interact with the fields,
and serialize/deserialize them as Avro format.
[1] https://iceberg.apache.org/spec/#snapshots
[2] https://iceberg.apache.org/spec/#manifests
Also includes a basic test for serializing to and from iobufs.
* none
=> iceberg: generate Avro C++ code for metadata

src/v/utils/delta_for.h, src/v/utils/tests/delta_for_bench.cc, src/v/utils/tests/delta_for_test.cc
* unused headers
* narrower scoped serde headers
* signed-compare warning fixes
* none
=> tests: delta_for_test improvements

tests/rptest/tests/scaling_up_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/21342
Fixes: https://github.com/redpanda-data/redpanda/issues/21364,
=> [v24.1.x] tests: increase tolerance in local retention movement test

tests/rptest/archival/s3_client.py
=> rptest: fix log message typo

src/v/cluster/scheduling/leader_balancer.cc, tests/rptest/tests/maintenance_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/21435
Fixes: https://github.com/redpanda-data/redpanda/issues/21453, Fixes: https://github.com/redpanda-data/redpanda/issues/21454, Fixes: https://github.com/redpanda-data/redpanda/issues/21455, Fixes: https://github.com/redpanda-data/redpanda/issues/21457, Fixes: https://github.com/redpanda-data/redpanda/issues/21459,
=> [v24.1.x] Maintenance mode test fixes

src/v/pandaproxy/schema_registry/validation.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/21478
=> [v24.1.x] schema_registry: Remove extraneous log

MODULE.bazel.lock, bazel/repositories.bzl, bazel/thirdparty/avro.BUILD, bazel/thirdparty/avro.bzl, src/v/iceberg/BUILD, src/v/iceberg/tests/BUILD
Add iceberg bazel build
* none
=> iceberg: add bazel support

tests/rptest/tests/cloud_storage_chunk_read_path_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/21344
=> [v24.1.x] rptest: tolerate leadership changes in chunk read tests

src/v/cluster/log_eviction_stm.cc, src/v/cluster/log_eviction_stm.h, src/v/cluster/partition.cc, src/v/cluster/partition.h, src/v/kafka/server/replicated_partition.cc, src/v/raft/persisted_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/19161
=> [v24.1.x] Optimize `replicated_partition::validate_fetch_offset`

src/v/utils/log_hist.cc, src/v/utils/log_hist.h
Currently log_hist implementation is tightly coupled with duration and latency measurements. Not all histograms are duration measurements, so the current structure makes it difficult to add such histograms. This commit decouples latency specific histograms from the base histogram implementation by making a separate wrapper class with all the measurement utilities.
* none
=> utils/log_hist: decouple latency measturements from histogram impl

src/v/raft/tests/raft_reconfiguration_test.cc
The test ran into an OOM (without any diagnostics), logging suggests that it is somewhere around offset translator validation. This commit rewrites the validation part to not cache all the offsets in memory.
* none
=> raft/tests: deflake test_force_reconfiguration

src/go/rpk/pkg/cli/security/user/update.go, tests/rptest/clients/rpk.py, tests/rptest/tests/rpk_acl_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/21452
=> [v24.1.x] rpk: make mechanism flag required in user update

src/go/rpk/pkg/cli/acl/user/update.go, tests/rptest/clients/rpk.py, tests/rptest/tests/rpk_acl_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/21452
=> [v23.2.x] rpk: make mechanism flag required in user update

src/go/rpk/pkg/cli/acl/user/update.go, tests/rptest/clients/rpk.py, tests/rptest/tests/rpk_acl_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/21452
=> [v23.3.x] rpk: make mechanism flag required in user update

src/v/raft/tests/raft_reconfiguration_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/21506
=> [v24.1.x] raft/tests: deflake test_force_reconfiguration

tests/rptest/tests/scaling_up_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/21342
Fixes: https://github.com/redpanda-data/redpanda/issues/21362,
=> [v23.3.x] tests: increase tolerance in local retention movement test

tests/rptest/tests/cloud_storage_chunk_read_path_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/21344
=> [v23.3.x] rptest: tolerate leadership changes in chunk read tests

tests/rptest/archival/s3_client.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/18491
=> [v23.3.x] PESDLC-876 Add Filehandlers to boto3 loggers

tests/docker/ducktape-deps/ocsf-server
Backport of PR https://github.com/redpanda-data/redpanda/pull/18200
=> [v23.3.x] PESDLC-1295  Remove unstable launchpad repo after install

tests/rptest/tests/scaling_up_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/17956
=> [v23.3.x] ducktape: deflake test_adding_nodes_to_cluster

src/v/cluster/tx_gateway_frontend.cc
Changed the way how the error returned from update transaction in
`do_add_parititons_to_txn` is handled. Previously every error in state
update resulted in `invalid_txn_state` error. This not the case for most
of the errors as client should simply retry the request. Beginning
transaction on data and group partitions is idempotent so it can be
safely done once again when handling request retry.
Fixes: CORE-5698
- none
=> [CORE-5698] Fixed issue with error mapping in `add_partitions_to_txn`

src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/vote_stm.cc, src/v/raft/vote_stm.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/21361
=> [v24.1.x] Guard from concurrent elections

tests/rptest/tests/crl_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/21563
=> [v24.2.x] dt: Updated RPC test log allow list

src/v/cluster/metrics_reporter.cc, src/v/cluster/metrics_reporter.h, src/v/http/client.cc, src/v/http/include/http/client.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/21579
=> [v24.2.x] Fix http client segfault in `metrics_reporter`

tests/rptest/services/cluster.py, tests/rptest/services/failure_injector.py, tests/rptest/tests/e2e_finjector.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/21307
=> [v24.1.x] tests/ducktape: check redpanda can stop

src/v/cloud_storage/cache_service.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/21606
=> [v24.2.x] cst/cache: fix in mem trim termination condition

src/v/cloud_storage/cache_service.cc, src/v/cloud_storage/tests/cache_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/21569
=> [v24.2.x] cloud storage: Fix deleted_count in clean_up_at_start

src/v/cluster/topics_frontend.cc, src/v/kafka/server/handlers/alter_configs.cc, src/v/kafka/server/handlers/incremental_alter_configs.cc, tests/rptest/tests/topic_creation_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/21291
=> [v24.2.x] CORE-3091 Fix non-incremental AlterConfig resetting

tests/rptest/tests/scaling_up_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22317
Fixes: https://github.com/redpanda-data/redpanda/issues/22321,
=> [v24.1.x] Increased tolerance in fast addition tests

tests/rptest/tests/scaling_up_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22317
Fixes: https://github.com/redpanda-data/redpanda/issues/22323,
=> [v24.2.x] Increased tolerance in fast addition tests

tests/rptest/tests/schema_registry_test.py
This PR adds a set of tests that run against the confluent schema registry client. Customers often use this client, so we want to have a test suite against this client to ensure the redpanda Schema Registry is compatible with the python client. The tests aim to exercise each method on the public API of the `SchemaRegistryClient` with a reasonable set of input parameters.
https://redpandadata.atlassian.net/browse/CORE-3189
* none
=> CORE-3189 dt/schema_registry: smoketests with python client

src/v/pandaproxy/schema_registry/json.cc, src/v/pandaproxy/schema_registry/test/test_json_schema.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/21354
=> [v24.2.x] [CORE-3187] schema registry - json schema: support `allOf oneOf anyOf`

src/v/kafka/server/handlers/client_quotas.cc
The AlterClientQuotas handler requires alter configs ACL privileges on the cluster. Whereas the DescribeClientQuotas handler required describe configs ACL privileges on the cluster. Corresponding Kafka code: [KafkaApis.scala#L3480-L3524](https://github.com/apache/kafka/blob/93068264a1ac6381592f33a649f7784629131b9b/core/src/main/scala/kafka/server/KafkaApis.scala#L3480-L3524).
This fixes a bug introduced in https://github.com/redpanda-data/redpanda/pull/19822 where the AlterClientQuotas handler incorrectly required describe configs privileges instead of alter configs privileges on the cluster.
* none
=> CORE-2074 k/quotas: fix alter configs acl requirement

src/v/kafka/client/broker.cc, src/v/net/connection.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22327 
Fixes: CORE-6661
=> [v23.3.x] CORE-5749 retry on dns failure

src/v/kafka/client/broker.cc, src/v/net/connection.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22327 
Fixes: CORE-6662
=> [v24.1.x] CORE-5749 retry on dns failure

src/v/pandaproxy/schema_registry/json.cc, src/v/pandaproxy/schema_registry/test/test_json_schema.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22326
=> [v24.2.x] [CORE-6464] schema_registry/json: compatibility check for `$schema`

src/v/pandaproxy/schema_registry/json.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22534
=> [v24.2.x] Schema registry/json: Ignore some keywords

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/parsing/from_chars.h, src/v/pandaproxy/schema_registry/avro.cc, src/v/pandaproxy/schema_registry/handlers.cc, src/v/pandaproxy/schema_registry/json.cc, src/v/pandaproxy/schema_registry/json.h, src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h, src/v/pandaproxy/schema_registry/types.cc, src/v/pandaproxy/schema_registry/types.h, tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22519
Fixes #22602
=> [v24.2.x] [CORE-3181] Schema Registry: Normalization

src/v/cloud_storage_clients/tests/xml_sax_parser_test.cc, src/v/cloud_storage_clients/xml_sax_parser.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22331
=> [v23.3.x] cloud_storage_clients: fix `abs_parse_impl` error

src/v/cloud_storage_clients/tests/xml_sax_parser_test.cc, src/v/cloud_storage_clients/xml_sax_parser.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22331
=> [v24.1.x] cloud_storage_clients: fix `abs_parse_impl` error

src/v/archival/purger.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22335
=> [v23.3.x] archival: fix `purger::collect_manifest_paths()`

tests/rptest/tests/consumer_group_test.py
Added basic test validating that the when a consumer with group instance id assigned leaves the group it does not cause rebalance.
- none
=> tests: added test verifying group rebalance with static assignment

src/go/rpk/pkg/cli/debug/bundle/bundle_k8s_linux.go, src/go/rpk/pkg/cli/debug/bundle/bundle_linux.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/22334
Fixes: https://github.com/redpanda-data/redpanda/issues/22629,
=> [v24.2.x] rpk: Add uname -a to debug bundle

tests/rptest/tests/data_transforms_test.py
Previously, the test would produce some random data to the input topic,
leading to an arbitrary distribution of records across partitions and
an upredictable distribution of buffered log data across nodes. The test
condition was whether any log buffer usage increased as a result but
relied on some obscure behavior of the franz-go consumer to verify that
the produce was making progress.
The test has been reformulated to instead produce enough data to exceed
log buffer capacity on a given partition, and the assertion softened to
ensure that no metrics indicate buffers filling up. This is more a test
of the LWM mechanism in the logger than it is a test of the metrics, but
we still get some coverage on probe code paths under some load.
Fixes …
=> [CORE-4599] dt/x: Clean up log manager metrics values test

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/parsing/from_chars.h, src/v/pandaproxy/schema_registry/avro.cc, src/v/pandaproxy/schema_registry/handlers.cc, src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h, src/v/pandaproxy/schema_registry/types.cc, src/v/pandaproxy/schema_registry/types.h, tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22519
Fixes https://github.com/redpanda-data/redpanda/issues/22600
=> [v23.3.x] [CORE-3181] Schema Registry: Normalization

src/go/rpk/pkg/cli/debug/bundle/bundle_k8s_linux.go, src/go/rpk/pkg/cli/debug/bundle/bundle_linux.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/22334
Fixes: https://github.com/redpanda-data/redpanda/issues/22628,
=> [v24.1.x] rpk: Add uname -a to debug bundle

src/v/pandaproxy/schema_registry/json.cc, src/v/pandaproxy/schema_registry/test/test_json_schema.cc
adds support for exclusiveMinimum/exclusiveMaximum for >=draft6
fixes an edge case for draft4
Fixes https://redpandadata.atlassian.net/browse/CORE-6750
* none
=> [CORE-6750] schema registry exclusiveMinumum/exclusiveMaximum double support

src/go/rpk/pkg/cli/debug/bundle/bundle_k8s_linux.go, src/go/rpk/pkg/cli/debug/bundle/bundle_linux.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/22334
Fixes: https://github.com/redpanda-data/redpanda/issues/22626,
=> [v23.3.x] rpk: Add uname -a to debug bundle

src/v/pandaproxy/schema_registry/protobuf.cc, src/v/pandaproxy/schema_registry/test/compatibility_protobuf.cc, src/v/pandaproxy/schema_registry/test/compatibility_protobuf.h, src/v/redpanda/application.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22633
Fixes: https://github.com/redpanda-data/redpanda/issues/22651,
=> [v24.1.x] [CORE-2144] schema_registry/protobuf: Disable protobuf logging

src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/api/api-doc/schema_registry_definitions.def.json
Backport of PR https://github.com/redpanda-data/redpanda/pull/22620
=> [v24.1.x] [CORE-3148] schema_registry: Fix Swagger for `POST /compatibility`

src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/api/api-doc/schema_registry_definitions.def.json
Backport of PR https://github.com/redpanda-data/redpanda/pull/22620
=> [v23.3.x] [CORE-3148] schema_registry: Fix Swagger for `POST /compatibility`

src/v/pandaproxy/schema_registry/protobuf.cc, src/v/pandaproxy/schema_registry/test/compatibility_protobuf.cc, src/v/pandaproxy/schema_registry/test/compatibility_protobuf.h, src/v/redpanda/application.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22633
Fixes: https://github.com/redpanda-data/redpanda/issues/22649,
=> [v24.2.x] [CORE-2144] schema_registry/protobuf: Disable protobuf logging

src/v/pandaproxy/schema_registry/protobuf.cc, src/v/pandaproxy/schema_registry/test/compatibility_protobuf.cc, src/v/pandaproxy/schema_registry/test/compatibility_protobuf.h, src/v/redpanda/application.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22633
Fixes: https://github.com/redpanda-data/redpanda/issues/22653,
=> [v23.3.x] [CORE-2144] schema_registry/protobuf: Disable protobuf logging

src/v/cluster/controller_backend.cc, src/v/cluster/shard_placement_table.cc, src/v/cluster/shard_placement_table.h, src/v/cluster/tests/shard_placement_table_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22636
=> [v24.2.x] Shard placement table: add metrics

src/v/cluster/data_migrated_resources.cc, src/v/cluster/data_migration_backend.cc, src/v/cluster/data_migration_backend.h, src/v/cluster/data_migration_table.cc, src/v/cluster/data_migration_types.cc, src/v/cluster/data_migration_types.h, src/v/cluster/data_migration_worker.cc, src/v/cluster/tests/data_migration_table_test.cc, src/v/redpanda/admin/migrations.cc, src/v/ssx/include/ssx/async_algorithm.h, tests/rptest/tests/data_migrations_api_test.py
Originally backend+worker were designed for operations on partitions,
however some operations such as topic deletion or creation are topic-scoped.
They need to be organised nevertheless, such as:
- proceed a migration into the next state if all topics have been processed,
- only spawn work on the controller leader,
- retry if failed.
Adding logic for this.
* none
=> Migrations infra, part 4: topic-scoped work

src/v/cloud_storage/cache_service.cc, src/v/cloud_storage/tests/cache_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/21569
=> [v23.3.x] cloud storage: Fix deleted_count in clean_up_at_start

tests/rptest/services/cluster.py, tests/rptest/services/failure_injector.py, tests/rptest/tests/e2e_finjector.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/21307
=> [v23.3.x] tests/ducktape: check redpanda can stop

tests/rptest/services/failure_injector.py, tests/rptest/tests/availability_test.py, tests/rptest/tests/e2e_finjector.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22619
=> [v24.2.x] tests/availability: fix resuming of suspended nodes

src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/api/api-doc/schema_registry_definitions.def.json
Backport of PR https://github.com/redpanda-data/redpanda/pull/22665
=> [v23.3.x] schema_registry: Sync Swagger with docs

src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/api/api-doc/schema_registry_definitions.def.json
Backport of PR https://github.com/redpanda-data/redpanda/pull/22665
=> [v24.2.x] schema_registry: Sync Swagger with docs

src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/api/api-doc/schema_registry_definitions.def.json
Backport of PR https://github.com/redpanda-data/redpanda/pull/22665
=> [v24.1.x] schema_registry: Sync Swagger with docs

tests/rptest/services/failure_injector.py, tests/rptest/tests/availability_test.py, tests/rptest/tests/e2e_finjector.py
Cherry-picked cleanly, so I'm not sure why @vbotbuildovich needs me
Backport of PR https://github.com/redpanda-data/redpanda/pull/22619
JIRA Link: [CORE-6768](https://redpandadata.atlassian.net/browse/CORE-6768)
[CORE-6768]: https://redpandadata.atlassian.net/browse/CORE-6768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [v23.3.x] tests/availability: fix resuming of suspended nodes

src/go/rpk/go.mod, src/go/rpk/go.sum, src/go/rpk/pkg/cli/registry/mode/get.go, src/go/rpk/pkg/cli/registry/mode/mode.go, src/go/rpk/pkg/cli/registry/mode/reset.go, src/go/rpk/pkg/cli/registry/mode/set.go, src/go/rpk/pkg/cli/registry/registry.go, tests/rptest/clients/rpk.py, tests/rptest/tests/rpk_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22675
=> [v24.2.x] rpk: add `rpk registry mode` command

.github/workflows/transform-sdk-build.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/22731
=> [v24.2.x] gha/transform-sdk: pin and centralize language versions

src/v/transform/api.cc, src/v/transform/io.h, src/v/transform/tests/test_fixture.cc, src/v/transform/tests/test_fixture.h, src/v/transform/transform_processor.cc, tests/rptest/tests/data_transforms_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/20127 
Fixes https://github.com/redpanda-data/redpanda/issues/20135
=> [v24.1.x] Transforms: Fix deploy-time timequery bug

src/v/cluster/raft0_utils.h, src/v/security/audit/audit_log_manager.cc, tests/rptest/tests/controller_partition_invariants_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22747
=> [v24.2.x] Disable log cleanup policy for controller log

src/v/kafka/server/tests/CMakeLists.txt
=> Increase number of cores used in fetch micro-benchmark

src/v/cluster/raft0_utils.h, src/v/security/audit/audit_log_manager.cc, tests/rptest/tests/controller_partition_invariants_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22747
=> [v24.1.x] Disable log cleanup policy for controller log

src/v/cloud_storage/tests/cloud_storage_e2e_test.cc, src/v/cluster/controller_api.cc, src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_backend.h, src/v/cluster/health_monitor_frontend.cc, src/v/cluster/health_monitor_frontend.h, src/v/cluster/health_monitor_types.cc, src/v/cluster/health_monitor_types.h, src/v/cluster/partition_balancer_planner.cc, src/v/cluster/partition_leaders_table.cc, src/v/cluster/scheduling/leader_balancer.cc, src/v/cluster/service.cc, src/v/cluster/tests/health_bench.cc, src/v/cluster/tests/health_monitor_bench.cc, src/v/cluster/tests/health_monitor_test.cc, src/v/cluster/tests/partition_balancer_planner_fixture.h, src/v/cluster/tests/partition_balancer_planner_test.cc, src/v/cluster/tests/partition_balancer_simulator_test.cc, src/v/cluster/tests/randoms.h, src/v/cluster/tests/serialization_rt_test.cc, src/v/cluster/topics_frontend.cc, src/v/compat/cluster_json.h, src/v/compat/get_node_health_compat.h, src/v/compat/get_node_health_generator.h, src/v/redpanda/admin/server.cc, tests/rptest/services/admin.py, tests/rptest/tests/shard_placement_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22695
=> [v24.2.x] Use shards from health report in Admin API cluster partition results

.github/workflows/scripts/jira_helper.py
=> gh: Fixed wrong transition name when reopening issues

src/v/cluster/data_migrated_resources.cc, src/v/cluster/data_migration_backend.cc, src/v/cluster/data_migration_backend.h, src/v/cluster/data_migration_table.cc, src/v/cluster/data_migration_types.cc, src/v/cluster/data_migration_types.h, src/v/cluster/data_migration_worker.cc, src/v/cluster/tests/data_migration_table_test.cc, src/v/redpanda/admin/migrations.cc, src/v/ssx/include/ssx/async_algorithm.h, tests/rptest/tests/data_migrations_api_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/21500
=> [v24.2.x] Migrations infra, part 4: topic-scoped work

tools/offline_log_viewer/controller.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22724
=> [v24.2.x] tools/olv: fixed a bug in reading ntp

src/v/rpc/include/rpc/errc.h, tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22776
=> [v24.2.x] CORE-6479 dt/random_node_ops: suppress method_not_found log 

src/v/redpanda/application.cc
The reactor has a reactor::_io_sink::_io_pending buffer which holds pending IOs after they have been drained from the io queues, and in some cases this can get very large, causing a large allocation.
While we pursue a longer-term solution, we work around this by reserving a large number of elements at startup, which avoids the need to grow the array later as long as we stay below that number. This change sets it 10,000 which is effectively 480K, larger than the 450K allocations we have seen as a maximum. Since it doubles, this gives us 2x headroom.
See CORE-2956 and https://github.com/scylladb/seastar/pull/2357.
Fixes: CORE-6814
* none
=> CORE-6814: increase io_sink size to 10000 at startup

src/v/test_utils/test.h
Cherry-picked from a feature branch.
* none
=> test_utils: add CORO variant for ASSERT_NO_FATAL_FAILURE

src/v/raft/state_machine_manager.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22752
=> [v24.1.x] r/stm_manager: do not warn when some of the stms did not make progress

src/v/rpc/errc.h, tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22776
=> [v24.1.x] CORE-6479 dt/random_node_ops: suppress method_not_found log 

src/v/rpc/errc.h, tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22776
=> [v23.3.x] CORE-6479 dt/random_node_ops: suppress method_not_found log 

src/v/archival/tests/service_fixture.cc, src/v/cluster/bootstrap_backend.cc, src/v/cluster/controller.cc, src/v/cluster/controller_backend.cc, src/v/cluster/controller_backend.h, src/v/cluster/members_backend.cc, src/v/cluster/members_manager.cc, src/v/cluster/members_manager.h, src/v/cluster/members_table.cc, src/v/cluster/partition_manager.cc, src/v/cluster/partition_manager.h, src/v/cluster/raft0_utils.h, src/v/features/feature_table.cc, src/v/features/feature_table.h, src/v/raft/consensus_utils.cc, src/v/raft/consensus_utils.h, src/v/raft/fundamental.h, src/v/raft/group_configuration.h, src/v/raft/group_manager.cc, src/v/raft/group_manager.h, src/v/raft/tests/simple_raft_fixture.h, tests/rptest/utils/si_utils.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22701
=> [v24.2.x] Retire old membership updates based on Raft configuration

src/v/datalake/protobuf_to_arrow_converter.cc
=> datalake: remove override annotation

src/v/kafka/server/group.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22797
=> [v24.2.x] k/group: do not replicate empty offsets commit batch

src/v/cluster/members_manager.cc, src/v/cluster/members_table.cc, tests/rptest/services/redpanda.py, tests/rptest/tests/nodes_decommissioning_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22677
=> [v24.2.x] Logging improvements in cluster `members` subsystem

src/v/kafka/server/group.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22330
=> [v24.2.x] Allow beginning transaction in completing rebalance

src/v/cloud_storage/tests/topic_mount_handler_test.cc, src/v/cloud_storage/topic_mount_handler.cc, src/v/cloud_storage/topic_mount_handler.h
Needed for topic migrations: prepare, replicate the fact we've prepared,
commit. Otherwise we cannot distinguish between two situations:
a) the cluster has mounted a topic but forgot about it as the calling
node went down shortly after
b) the topic was never available for mount
* none
=> Topic mount manifest 2fc mount

src/v/cloud_storage/tests/topic_mount_handler_test.cc, src/v/cloud_storage/topic_mount_handler.cc, src/v/cloud_storage/topic_mount_handler.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/22821
=> [v24.2.x] Topic mount manifest 2fc mount

src/v/pandaproxy/schema_registry/protobuf.cc, src/v/pandaproxy/schema_registry/test/compatibility_protobuf.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22798
=> [v24.1.x] CORE-6824 Schema Registry/Proto: add 5 missing checks

src/v/pandaproxy/schema_registry/protobuf.cc, src/v/pandaproxy/schema_registry/test/compatibility_protobuf.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22798
=> [v23.3.x] CORE-6824 Schema Registry/Proto: add 5 missing checks

MODULE.bazel.lock, bazel/repositories.bzl
bazel: upgrade libxml2 to 2.13.3
* none
=> bazel: upgrade libxml2 to 2.13.3

tests/rptest/tests/data_transforms_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/21375
Fixes: https://github.com/redpanda-data/redpanda/issues/22833,
=> [v24.2.x] [CORE-4599] dt/x: Clean up log manager metrics values test

src/v/pandaproxy/schema_registry/json.cc, src/v/pandaproxy/schema_registry/test/test_json_schema.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22739
=> [v24.2.x] [CORE-6656] schema registry json schema: unions extended case

src/v/config/configuration.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22664
=> [v24.2.x] config: update docs for cloud_storage_azure_hierarchical_namespace_enabled

src/v/cluster/errc.h, src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_types.cc, src/v/cluster/health_monitor_types.h, src/v/cluster/node_status_backend.cc, src/v/cluster/node_status_backend.h, src/v/cluster/service.cc, src/v/kafka/server/errors.h, tests/rptest/tests/node_folder_deletion_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22811
=> [v23.3.x] CORE-5766 Validate target node id when collecting health report

src/v/pandaproxy/schema_registry/json.cc, src/v/pandaproxy/schema_registry/test/test_json_schema.cc
1. removes `definitions` from the list of unhandled keywords, because it does not require a compat check
2. adds support for `dependencies` for `type: object`.
"dependencies" is a dictionary <string, string_array | schema>.
the compat check has two levels:
1. every key in `older` needs to be in `newer`
2. for each matching key:
a. if both are string arrays, older needs to be a subset of newer
b. if both are schemas, they need to be compatible
Fixes https://redpandadata.atlassian.net/browse/CORE-5770
* none
=> [CORE-5770] schema registry: support for `dependencies` in `type: object`

tests/rptest/services/provider_clients/instance_utils.py
When instance is starts there is not always an IMDS available. Use default specs if metadata failed to be excracted
Fixes: #16321 , #16377 
* none
=> CORE-6756 Use 'default' specs when IMDS not available

src/v/pandaproxy/schema_registry/json.cc, src/v/pandaproxy/schema_registry/test/test_json_schema.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22878
=> [v24.2.x] [CORE-5770] schema registry: support for `dependencies` in `type: object`

src/v/storage/logger.cc, src/v/storage/logger.h, src/v/storage/storage_resources.cc, tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22791
=> [v24.2.x] Tests logging improments

MODULE.bazel.lock, bazel/repositories.bzl
Backport of PR https://github.com/redpanda-data/redpanda/pull/22901 
JIRA Link: [CORE-6981](https://redpandadata.atlassian.net/browse/CORE-6981)
Closes https://github.com/redpanda-data/redpanda/issues/22936
[CORE-6981]: https://redpandadata.atlassian.net/browse/CORE-6981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [v24.2.x] CORE-6859 bazel: update seastar with prometheus fix

src/v/cluster/producer_state.cc, src/v/cluster/rm_stm.cc
...to make forward progress. We noticed in some clusters the logs may be
force reconfigured resulting in truncation of some committed entries that
invalidate these asserts. Asserting on the log contents is dangerous as
it can cause cascading failures.
* none
=> tx: relax some asserts to error logs for forward progress.

.bazelrc, src/v/wasm/schema_registry_module.h, src/v/wasm/transform_module.h, src/v/wasm/wasi.h
=> bazel: fix local toolchain selection

src/v/cluster/producer_state.cc, src/v/cluster/rm_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22921
=> [v24.2.x] tx: relax some asserts to error logs for forward progress.

src/v/archival/archival_policy.cc, src/v/archival/tests/ntp_archiver_test.cc, tests/rptest/tests/shadow_indexing_compacted_topic_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22812
=> [v24.1.x] CORE-6835 Fix first time compacted segment upload

tests/rptest/services/redpanda.py, tests/rptest/tests/cluster_self_config_test.py
In a CDT run with `GCP` as the cloud provider, the `cloud_storage_api_endpoint` will be overridden by `storage.googleapis.com`, even if specified by the user.
Change the logic to allow user's choice of `cloud_storage_api_endpoint` to be the final override value.
Default value for `SISettings.cloud_storage_api_endpoint` is still `minio-s3`, if not otherwise specified by user or test context.
This PR fixes the recently added `test_s3_oracle_self_config` test, which would previously fail in a CDT run with `GCP` as the cloud provider due to the above, unexpected override by the global test context. Also adds a sanity check to the test to ensure the cluster setting is properly set.
* none
=> `rptest`: allow user to override `cloud_storage_api_endpoint`

src/v/cluster/members_manager.cc, src/v/cluster/members_table.cc, tests/rptest/services/redpanda.py, tests/rptest/tests/nodes_decommissioning_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22677
=> [v24.1.x] Logging improvements in cluster `members` subsystem

src/v/storage/disk_log_impl.cc, src/v/storage/tests/log_retention_tests.cc, src/v/storage/tests/storage_e2e_fixture_test.cc, tests/rptest/tests/retention_policy_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22686
Fixes: https://github.com/redpanda-data/redpanda/issues/22931,
=> [v24.1.x] `storage`: fix condition in `disk_log_impl::have_segments_to_evict()`

src/v/kafka/server/group.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22797
=> [v24.1.x] k/group: do not replicate empty offsets commit batch

src/v/cluster/members_table.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22725
=> [v24.1.x] c/members_table: fixed typo in applying remove node command

MODULE.bazel, MODULE.bazel.lock
bazel: upgrade to latest abseil lts version
* none
=> bazel: upgrade to latest abseil lts version

src/v/cluster/producer_state.cc
=> tx/logging: fix mismatch between format string and args

src/v/archival/tests/service_fixture.cc, src/v/cluster/bootstrap_backend.cc, src/v/cluster/controller.cc, src/v/cluster/controller_backend.cc, src/v/cluster/controller_backend.h, src/v/cluster/members_backend.cc, src/v/cluster/members_manager.cc, src/v/cluster/members_manager.h, src/v/cluster/members_table.cc, src/v/cluster/partition_manager.cc, src/v/cluster/partition_manager.h, src/v/cluster/raft0_utils.h, src/v/features/feature_table.cc, src/v/features/feature_table.h, src/v/raft/consensus_utils.cc, src/v/raft/consensus_utils.h, src/v/raft/fundamental.h, src/v/raft/group_configuration.h, src/v/raft/group_manager.cc, src/v/raft/group_manager.h, src/v/raft/tests/simple_raft_fixture.h, tests/rptest/utils/si_utils.py
Reverts redpanda-data/redpanda#22772
- none
=> Revert "[v24.2.x] Retire old membership updates based on Raft configuration"

src/v/cluster/producer_state.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22970
=> [v24.2.x] tx/logging: fix mismatch between format string and args

src/v/raft/tests/CMakeLists.txt, src/v/raft/tests/stm_manager_test.cc, src/v/raft/tests/stm_test_fixture.h
* uses retries to replicate
* propagate replicate exception and not dereference value from failed result
* proper cleanup and wait for all fibers to finish using when_all
* none
=> raft/tests: deflake stm_manager_test

src/go/rpk/pkg/cli/topic/trim.go
Fix long text of `rpk topic trim-prefix` per https://github.com/redpanda-data/docs/pull/697
* none
=> rpk: fix long text for rpk-topic-trim-prefix

src/v/archival/archival_metadata_stm.cc, src/v/archival/archival_metadata_stm.h, src/v/cluster/distributed_kv_stm.h, src/v/cluster/id_allocator_stm.cc, src/v/cluster/id_allocator_stm.h, src/v/cluster/log_eviction_stm.cc, src/v/cluster/log_eviction_stm.h, src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h, src/v/cluster/tests/rm_stm_test_fixture.h, src/v/cluster/tm_stm.cc, src/v/cluster/tm_stm.h, src/v/kafka/server/group_tx_tracker_stm.cc, src/v/kafka/server/group_tx_tracker_stm.h, src/v/raft/persisted_stm.cc, src/v/raft/persisted_stm.h, src/v/raft/tests/persisted_stm_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22969
=> [v24.2.x] r/persisted_stm: serialize apply and taking local snapshot with a mutex

src/go/rpk/pkg/cli/registry/schema/check_compatibility.go, src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/api/api-doc/schema_registry_definitions.def.json, src/v/pandaproxy/schema_registry/CMakeLists.txt, src/v/pandaproxy/schema_registry/avro.cc, src/v/pandaproxy/schema_registry/avro.h, src/v/pandaproxy/schema_registry/compatibility.cc, src/v/pandaproxy/schema_registry/compatibility.h, src/v/pandaproxy/schema_registry/handlers.cc, src/v/pandaproxy/schema_registry/protobuf.cc, src/v/pandaproxy/schema_registry/protobuf.h, src/v/pandaproxy/schema_registry/requests/compatibility.h, src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h, src/v/pandaproxy/schema_registry/test/compatibility_avro.cc, src/v/pandaproxy/schema_registry/types.h, tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22877 
Fixes https://github.com/redpanda-data/redpanda/issues/22956
Fixes https://redpandadata.atlassian.net/browse/CORE-6996
=> [v24.1.x] CORE-6860 SR: Wire up support for  compatibility checks

src/v/pandaproxy/schema_registry/json.cc, src/v/pandaproxy/schema_registry/types.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/23003
=> [v24.2.x] schema_registry/json: Refactoring to add a context with schema version

src/go/rpk/pkg/cli/topic/trim.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/22994
=> [v24.1.x] rpk: fix long text for rpk-topic-trim-prefix

src/go/rpk/pkg/cli/topic/trim.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/22994
=> [v23.3.x] rpk: fix long text for rpk-topic-trim-prefix

bazel/test.bzl, src/v/raft/tests/CMakeLists.txt, tools/cmake_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23019
=> [v24.2.x] raft: increase memory limit for gtest_raft_rpunit

tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22985
=> [v24.2.x] [CORE-3188] schema registry DT tests for various compatibility modes

src/v/pandaproxy/schema_registry/json.cc, src/v/pandaproxy/schema_registry/test/test_json_schema.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/23031
=> [v24.2.x] Feat/core/6657/schema registry remove schemas requirement

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/22946
Closes https://github.com/redpanda-data/redpanda/issues/23014
=> [v24.1.x] [rptest] always clean up object stores (that are small) for non-GCP

src/go/rpk/pkg/cli/cluster/health.go, src/go/rpk/pkg/cli/registry/schema/get.go
Updates the descriptions of rpk flags for 
- `rpk registry schema get`
- `rpk cluster health`
* none
=> Update descriptions for rpk flags

src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h, src/v/model/record.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/23008
=> [v24.2.x] c/rm_stm: optimized taking rm_stm snapshot

src/v/kafka/server/connection_context.h, src/v/kafka/server/handlers/details/security.h, src/v/kafka/server/handlers/metadata.cc, src/v/kafka/server/handlers/metadata.h, src/v/kafka/server/request_context.h, src/v/kafka/server/tests/CMakeLists.txt, src/v/kafka/server/tests/metadata_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22669
=> [v24.2.x] CORE-3092 support metadata v8

src/v/raft/heartbeat_manager.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/23055
=> [v24.2.x] r/hb_mgr: check if current replica is a leader when collecting hbeats

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
Fixes #23060
Backport of PR #23040
* none
=> [v24.1.x] Fix cloud operator_v2 check

src/v/redpanda/admin/migrations.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/23004
=> [v24.2.x] admin/migrations: fixed HTTP body JSON validation

src/v/bytes/tests/BUILD, src/v/bytes/tests/iobuf_utils_tests.cc, src/v/utils/delta_for.h
chore: add missing headers
* none
=> chore: add missing headers

tests/rptest/tests/mirror_maker_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23075
=> [v24.2.x] tests: wait for topic to be present before starting producer

src/v/cluster/rm_stm.cc, src/v/cluster/tests/rm_stm_tests.cc
if a tx is in progress, any other sequence numbers are rejected until the tx is sealed (committed/aborted).
if a tx is already sealed, older tx_sequences are rejected and only newer sequences are accepted.
The reason this is best effort is because sealed transaction's producer state is prone to eviction (eg: producer limits are hit), so we are not guaranteed to enforce this fencing all cases (which is why it was not implemented in the first place).
* none
=> tx/rm_stm: add best effort sequence number based fencing

src/v/cluster/rm_stm.cc, src/v/cluster/tests/rm_stm_tests.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/22992
=> [v24.2.x] tx/rm_stm: add best effort sequence number based fencing

tests/rptest/services/admin_ops_fuzzer.py, tests/rptest/tests/random_node_operations_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23057
=> [v24.2.x] Refactored upgrades executed in random node operations test

tests/rptest/services/cluster.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23090
=> [v24.2.x] Fix class instance check for raise_on_crash

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
Fixes #23059
Backport of PR #23040
* none
=> [v24.2.x] Fix cloud operator_v2 check

src/v/utils/tests/uuid_test.cc
=> utils/test: serde_fields for uuid_test::uuid_struct

src/v/features/feature_table.h
=> feat: serde_fields for feature_table::version_fence

tests/rptest/services/cluster.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23090
=> [v24.1.x] Fix class instance check for raise_on_crash

src/v/pandaproxy/schema_registry/store.h, src/v/pandaproxy/schema_registry/test/CMakeLists.txt, src/v/pandaproxy/schema_registry/test/mt_sharded_store.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/23114
=> [v24.1.x] [CORE-7061] sr/store: Deep copy schema_def iobufs at the interface

src/go/rpk/pkg/cli/cluster/health.go, src/go/rpk/pkg/cli/registry/schema/get.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/16444
=> [v23.3.x] Update descriptions for rpk flags

src/go/rpk/pkg/cli/cluster/health.go, src/go/rpk/pkg/cli/registry/schema/get.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/16444
=> [v24.1.x] Update descriptions for rpk flags

.github/workflows/release-rp-storage-tool.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/23058
=> [v24.2.x] ci/github: build and publish rp-storage-tool

.github/workflows/release-rp-storage-tool.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/23058
=> [v24.1.x] ci/github: build and publish rp-storage-tool

.github/workflows/release-rp-storage-tool.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/23058
=> [v23.3.x] ci/github: build and publish rp-storage-tool

tests/rptest/tests/data_migrations_api_test.py
Added test validating if the topic can be released and acquired back and
the topic data are preserved. The test checks if the data that were
previously produced to the topic are available after the topic ownership was
acquired in the process of inbound migration.
- none
=> Migraitions e2e test

src/go/rpk/pkg/cli/cluster/health.go, src/go/rpk/pkg/cli/registry/schema/get.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/16444
=> [v24.2.x] Update descriptions for rpk flags

src/v/cluster/tm_stm.cc, src/v/cluster/tm_stm.h, src/v/cluster/tx_gateway_frontend.cc, src/v/cluster/tx_gateway_frontend.h, tests/rptest/transactions/transactions_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23131
=> [v24.2.x] Fixed producer fencing when transaction is expired

.github/workflows/p.yml, tools/p/Dockerfile, tools/p/README.md, tools/p/p
github: add plang workflow
* none
=> github: add plang workflow

src/v/iceberg/datatypes_json.cc, src/v/iceberg/json_utils.cc, src/v/iceberg/json_utils.h
I've got a PR coming up that will serialize table metadata. There are some optional fields, some map/array fields, etc. that will benefit from utility methods that handle type checking.
Adds:
- optional getters for ints (required getters already exist)
- optional getters for arrays/maps
- required getters for arrays/maps
- pulls in some existing code for parsing between brackets (not JSON related, but it's a common in Iceberg JSON serialized strings)
- swaps `const char*` for `string_view`
* none
=> iceberg: JSON utilities for parsing optional values

tests/rptest/tests/shard_placement_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23158
=> [v24.2.x] tests/shard_placement_test: check total counts in rebalance_finished predicate

src/v/pandaproxy/schema_registry/json.cc, src/v/pandaproxy/schema_registry/test/test_json_schema.cc
fixes two proper bugs in the compact checks,
and removes the check for `patternProperties`, because the legacy software does not perform this check (likely an oversight but we are trying to match behavior)
the first commit is a followup from the previous PR 
Fixes https://redpandadata.atlassian.net/browse/CORE-7037
* none
=> [CORE-7037] schema registry json schema: fixes for some compatiblity bugs

src/v/pandaproxy/schema_registry/json.cc, src/v/pandaproxy/schema_registry/types.h, src/v/pandaproxy/schema_registry/validation.cc, tests/rptest/remote_scripts/python_librdkafka_serde_client.py, tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23139
=> [v24.2.x] [CORE-6665] schema registry - json schema get_record_name

src/v/cluster/data_migrated_resources.cc, src/v/cluster/data_migration_backend.cc, src/v/cluster/data_migration_backend.h, src/v/cluster/data_migration_types.h, src/v/cluster/data_migration_worker.cc, src/v/cluster/data_migration_worker.h, src/v/cluster/metadata_cache.cc, src/v/cluster/metadata_cache.h, src/v/kafka/server/handlers/fetch.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/23140
=> [v24.2.x] Migrations infra part 6: cancelations, retries, blocking reads

src/v/kafka/CMakeLists.txt, src/v/kafka/utils/BUILD, src/v/kafka/utils/CMakeLists.txt, src/v/kafka/utils/tests/BUILD, src/v/kafka/utils/tests/CMakeLists.txt, src/v/kafka/utils/tests/txn_reader_test.cc, src/v/kafka/utils/txn_reader.cc, src/v/kafka/utils/txn_reader.h, src/v/transform/BUILD, src/v/transform/CMakeLists.txt, src/v/transform/api.cc, src/v/transform/tests/CMakeLists.txt
.. to be used by datalake components in future patches.
* none
=> kafka: move transforms/txn_reader to kafka/utils

src/v/crypto/BUILD
crypto: set implementation deps
* none
=> crypto: specify Bazel implementation deps

src/v/iceberg/BUILD, src/v/iceberg/CMakeLists.txt, src/v/iceberg/snapshot.h, src/v/iceberg/snapshot_json.cc, src/v/iceberg/snapshot_json.h, src/v/iceberg/tests/BUILD, src/v/iceberg/tests/CMakeLists.txt, src/v/iceberg/tests/snapshot_json_test.cc
Adds a snapshot type (effectively, a pointer to a file containing a manifest list, similar to the Rust impl here[1]). These snapshots end up being serialized in table metadata as JSON. Code for serialization is included in this PR.
[1] https://github.com/apache/iceberg-rust/blob/7aa8bddeb09420b2f81a50112603de28aeaf3be7/crates/iceberg/src/spec/snapshot.rs
* none
=> iceberg: introduce snapshot type

tests/rptest/services/redpanda.py, tests/rptest/tests/shard_placement_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23153
=> [v24.2.x] tests/shard_placement_test: increase node rebalance timeout

src/v/iceberg/BUILD, src/v/iceberg/CMakeLists.txt, src/v/iceberg/manifest_avro.cc, src/v/iceberg/partition_json.cc, src/v/iceberg/partition_json.h, src/v/iceberg/tests/BUILD, src/v/iceberg/tests/CMakeLists.txt, src/v/iceberg/tests/manifest_serialization_test.cc, src/v/iceberg/tests/partition_json_test.cc, src/v/iceberg/tests/transform_json_test.cc, src/v/iceberg/transform_json.cc, src/v/iceberg/transform_json.h
Table metadata JSON files will require the serialization of partition specs, and by extension, transforms. This PR adds serialization code for these types.
Partition specs are also supposed to be serialized as JSON in manifest Avro headers[1], so this uses the new serialization code in that area.
[1] https://iceberg.apache.org/spec/#manifests
* none
=> iceberg: preparatory serialization code for table metadata

src/v/iceberg/BUILD, src/v/iceberg/CMakeLists.txt, src/v/iceberg/table_metadata.h, src/v/iceberg/table_metadata_json.cc, src/v/iceberg/table_metadata_json.h, src/v/iceberg/tests/BUILD, src/v/iceberg/tests/CMakeLists.txt, src/v/iceberg/tests/table_metadata_json_test.cc
Introduces a type to represent table metadata, and code to translate it to/from JSON. When committing new files to the tables, the commits will occur by adding new snapshots to the table metadata and then making the serialized metadata available to readers: it be either written to S3 directly, or pushed to the Iceberg REST catalog.
I didn't include a few optional fields, given their serialization was a tad non-trivial, and given they don't appear critical to getting the end-to-end flow working.
Here's the Iceberg Rust implementation, for reference: https://github.com/apache/iceberg-rust/blob/7aa8bddeb09420b2f81a50112603de28aeaf3be7/crates/iceberg/src/spec/table_metadata.rs
* none
=> iceberg: add table metadata

tests/rptest/remote_scripts/compute_storage.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23150
Fixes: https://github.com/redpanda-data/redpanda/issues/23200,
=> [v24.2.x] [CORE-7010] ducktape: adapt segment parsing for partial batch headers

src/v/cluster/tests/topic_table_test.cc, src/v/cluster/topic_table.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/23191
=> [v24.2.x] `cluster`: don't apply invalid property change in `topic_table`

src/go/rpk/pkg/cli/topic/trim.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/22994
=> [v24.2.x] rpk: fix long text for rpk-topic-trim-prefix

tests/rptest/tests/mirror_maker_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23075
=> [v24.1.x] tests: wait for topic to be present before starting producer

src/v/cluster/archival/ntp_archiver_service.cc
=> Migrations storage improvements

src/v/cloud_io/CMakeLists.txt, src/v/cloud_io/tests/BUILD, src/v/cloud_io/tests/CMakeLists.txt, src/v/cloud_io/tests/scoped_remote.cc, src/v/cloud_io/tests/scoped_remote.h, src/v/cloud_storage/tests/BUILD, src/v/cloud_storage/tests/s3_imposter.cc, src/v/cloud_storage/tests/s3_imposter.h
Several tests exist that require them together, and require that the
initialization/destruction order is as expected (pool outlives the
remote).
This commit adds a test utility to manage a client pool and a remote
together to abide by these constraints.
Separately (but somewhat relatedly), removes s3_imposter's unused reliance on cloud_storage.
* none
=> cloud_io: add scoped_remote test util

src/v/cloud_storage/inventory/inv_consumer.cc, src/v/cloud_storage/inventory/tests/inv_consumer_tests.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/23240
=> [v24.2.x] cst/inv: Minor fixes for issues found during scrubber integration

src/v/archival/ntp_archiver_service.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/23203
=> [v24.2.x] Migrations storage improvements

tests/rptest/services/redpanda.py
In ClusterConfigTest we chose to use fake AWS credentials to test cloud configuration multi-property validation. When running on non-AWS clouds with metadata service running but not expecting AWS valid metadata API calls, the API calls we make to get credentials will fail with surprising errors. Add these errors to the allow list.
In this test we are only interested in the config validation behavior.
CORE-6965
* none
=> rptest: add iam roles error to allow list

src/v/iceberg/BUILD, src/v/iceberg/table_requests.h, src/v/iceberg/table_requirement.h, src/v/iceberg/table_update.h
Adds some basic structs for metadata that needs to be sent to the Iceberg catalog: updates, requirements, and request wrappers around them.
My goal is to establish the interface so multiple work streams can begin using these (one to build the updates, the other to send the updates to the catalog).
Note that these structs will need to be serialized into JSON. That serialization is not done in this PR. Also note that only a subset of the updates and requirements are included in this PR (just the ones that seem immediately useful for appending and creating tables).
Open API spec for reference:
https://github.com/apache/iceberg/blob/main/open-api/rest-catalog-open-api.yaml
* none
=> iceberg: add initial catalog metadata structs

MODULE.bazel.lock, bazel/repositories.bzl
=> bazel: Updated seastar ref

tools/BUILD
tools: add note about using dev cluster data dir
* none
=> tools: add note about using dev cluster data dir

src/v/cloud_io/remote.h, src/v/cloud_io/transfer_details.cc, src/v/cloud_io/transfer_details.h, src/v/cloud_storage/inventory/types.h, src/v/cloud_storage/recovery_utils.h, src/v/cloud_storage/segment_state.h, src/v/cluster/cloud_metadata/manifest_downloads.h, src/v/utils/retry_chain_node.cc, src/v/utils/retry_chain_node.h
This PR changes `remote` to allow it to be more suitable for deterministic testing.  The `remote` now implements `remote_api` which is a template that depends on clock type. The clock can be either `ss::lowres_clock` or `ss::manual_clock`.
The `remote` implements `remote_api<ss::lowres_clock>` but tests should depend on `remote_api<ss::manual_clock>`. Some dependencies of the `remote` also got the same treatment. The `retry_chain_node` being the largest change in the PR.
* none
=> cloud_io: Improve remote for tests

tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/services/machinetype.py
=> ducktape: Add m7gd machine types for cloud tests

src/v/archival/archival_policy.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/23268
=> [v24.2.x] archival_policy: skip if no data at desired start_offset

bazel/test.bzl, src/v/compression/tests/BUILD, src/v/http/tests/BUILD, src/v/io/tests/BUILD, src/v/io/tests/scheduler_test.cc, src/v/utils/tests/external_process_test.cc, src/v/utils/tests/retry_test.cc, src/v/utils/tests/tracking_allocator_tests.cc
Fix remaining unit tests in Bazel.
* none
=> bazel: fix unit tests

src/v/iceberg/tests/BUILD
Previous PR was slightly out of date and missed this one in upstream.
* none
=> iceberg: use test cpu parameter

tests/rptest/tests/audit_log_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23260
=> [v23.3.x] CORE-6896 dt/audit: enable oauth after keycloak is up

.github/workflows/release-rp-storage-tool.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/23307
=> [v24.2.x] gha: reduce execution frequency (on cheap runner)

src/v/kafka/server/connection_context.cc, src/v/kafka/server/server.cc, src/v/security/audit/audit_log_manager.cc, tests/rptest/tests/audit_log_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23245
=> [v24.2.x] kafka: Fixed segfault issue with auditing and mTLS

src/v/CMakeLists.txt, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/debug_bundle/BUILD, src/v/debug_bundle/CMakeLists.txt, src/v/debug_bundle/debug_bundle_service.cc, src/v/debug_bundle/debug_bundle_service.h, src/v/debug_bundle/error.cc, src/v/debug_bundle/error.h, src/v/debug_bundle/fwd.h, src/v/debug_bundle/tests/BUILD, src/v/debug_bundle/tests/CMakeLists.txt, src/v/debug_bundle/tests/debug_bundle_service_test.cc, src/v/debug_bundle/tests/rpk-shim.sh, src/v/debug_bundle/tests/types_test.cc, src/v/debug_bundle/types.cc, src/v/debug_bundle/types.h, src/v/redpanda/BUILD, src/v/redpanda/CMakeLists.txt, src/v/redpanda/application.cc, src/v/redpanda/application.h, tests/rptest/services/redpanda.py
Adds the debug bundle service and defines its API.  It additionally hooks it into the redpanda application for later use.
* None
=> CORE-7092 initial debug bundle service

src/v/container/include/container/contiguous_range_map.h, src/v/kafka/server/tests/fetch_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/23301
Fixes: https://github.com/redpanda-data/redpanda/issues/23316,
=> [v24.2.x] kafka: fix fetching from partitions with negative indexes

.github/workflows/release-rp-storage-tool.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/23307
=> [v23.3.x] gha: reduce execution frequency (on cheap runner)

.github/workflows/release-rp-storage-tool.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/23307
=> [v24.1.x] gha: reduce execution frequency (on cheap runner)

src/v/cluster/data_migrated_resources.cc, src/v/cluster/data_migrated_resources.h, src/v/cluster/data_migration_table.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/23306
=> [v24.2.x] CORE-7268 fix migrated resources raft snapshot application

src/v/iceberg/manifest_io.cc, src/v/iceberg/manifest_io.h, src/v/iceberg/tests/manifest_io_test.cc, src/v/iceberg/tests/manifest_serialization_test.cc
A couple more small changes within v/iceberg:
- sets one test to be more permissive about O_DIRECT, since I don't want to remount my working directory
- makes uploads return the size of the serialized bytes, since this will be important to record in metadata
* none
=> iceberg: miscellaneous minor changes

README.md
Add link to redpanda university
* none
=> README.md: link to redpanda uni

src/v/debug_bundle/BUILD, src/v/debug_bundle/debug_bundle_service.cc, src/v/debug_bundle/debug_bundle_service.h, src/v/debug_bundle/error.cc, src/v/debug_bundle/error.h, src/v/debug_bundle/tests/debug_bundle_service_test.cc, src/v/debug_bundle/tests/rpk-shim.sh, src/v/debug_bundle/types.cc, src/v/debug_bundle/types.h
Adds implementation to the debug bundle service to:
* start the rpk debug bundle process
* get the status of the process
* terminate the process
* None
=> CORE-7093: debug bundle proc

tests/rptest/tests/shard_placement_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23250
=> [v24.2.x] tests/shard_placement: fix waiting for shard map consistency

src/v/archival/ntp_archiver_service.cc, src/v/cloud_storage/tests/cloud_storage_e2e_test.cc
Preemptive backport of https://github.com/redpanda-data/redpanda/pull/23358
CONFLICT:
- updated test for GTest
Compact-only topics should never apply retention. This wasn't the case for the spillover region in tiered storage.
Note, for the STM region, we do correctly no-op when trying to apply retention for compacted topics.
(cherry picked from commit 26df815465dc2cfd68e716e0936d1bdc99bb248b)
* Fixes a bug that would cause retention to be applied to compact-only tiered storage topics.
=> [v24.1.x] archival: skip spillover retention if not collectable

tests/rptest/tests/data_migrations_api_test.py
until known issues are resolved
* none
=> tests/migrations: allow e2e test to fail

tests/rptest/clients/rpk.py, tests/rptest/services/rpk_producer.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23324
=> [v24.1.x] Remove some warnings and ignored errors from ducktape log

tests/rptest/clients/rpk.py, tests/rptest/services/rpk_producer.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23324
=> [v24.2.x] Remove some warnings and ignored errors from ducktape log

tests/rptest/clients/rpk.py, tests/rptest/services/rpk_producer.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23324
=> [v23.3.x] Remove some warnings and ignored errors from ducktape log

src/v/cluster/data_migrated_resources.cc, src/v/cluster/data_migration_backend.cc, src/v/cluster/data_migration_backend.h, src/v/cluster/data_migration_table.cc, src/v/cluster/data_migration_types.cc, src/v/cluster/data_migration_types.h, src/v/redpanda/admin/api-doc/migration.def.json, src/v/redpanda/admin/migrations.cc, src/v/redpanda/admin/topics.cc, tests/rptest/services/admin.py, tests/rptest/tests/data_migrations_api_test.py
Implement API to create auto-advancing migrations.
* none
=> Migrations (topic un-/mount) high level api implementation

tests/rptest/tests/enterprise_features_license_test.py
What it says on the tin. Test case isn't high enough value to work around in my opinion.
TODO:
- See https://github.com/redpanda-data/redpanda/pull/23396#issuecomment-2362714988
Example of a broken CDT run: Example of a broken run: https://buildkite.com/redpanda/redpanda/builds/54769#01920c2f-b590-45d2-b8fa-0255ffcde890
* none
=> dt/enterprise_features: Skip fips tests because they break CDT

tests/rptest/redpanda_cloud_tests/omb_validation_test.py
=> Vary latency limits in cloud tests depending on provider.

tests/rptest/tests/enterprise_features_license_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23396
=> [v24.2.x] dt/enterprise_features: Skip fips tests because they break CDT

src/v/debug_bundle/tests/debug_bundle_service_test.cc
Process status is set in a background fiber that is concurrent to the test case. So we'll busy wait with a very generous (30s) timeout at a 200ms interval.
If this test blows the 30s timeout, that's probably indicative of a real bug in app code and should be addressed in due course. This commit seeks only to address intermittent test failures arising from the the common case race condition.
Fixes [CORE-7678]
* none
[CORE-7678]: https://redpandadata.atlassian.net/browse/CORE-7678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> debug_bundle/test: Busy wait for terminated process status

src/v/storage/log_manager.cc
The log line `INFO  2024-09-20 15:27:58,391 [shard  7:lc  ] storage - log_manager.cc:438 - Error processing housekeeping(): seastar::gate_closed_exception (gate closed)` is almost always found upon shutting down `redpanda`.
To prevent a `seastar::gate_closed_exception` being thrown on shutdown and presenting itself as an error, `catch` the exception and allow the `housekeeping()` background fiber to end quietly in the `log_manager`.
Backporting to `v24.1.x` and `v24.2.x`.
* none
=> `storage`: catch `ss::gate_closed_exception` in `log_manager`

src/v/cluster/health_monitor_types.h, src/v/cluster/partition_balancer_types.h
cluster: misc header/declaration fixes
* none
=> cluster: misc header/declaration fixes

src/v/kafka/server/handlers/fetch.cc, src/v/model/record_batch_reader.cc, src/v/raft/consensus_utils.h
=> fmt: some fmt fixes

src/v/redpanda/admin/api-doc/migration.def.json
As far as I understand allowed values for "type" are only built in ones like "object" or "array" or "string". We already use it on line 33. Please correct me if I'm wrong.
* none
=> docs/api/migrations: refer to objects with defined schemas via $ref

src/v/cloud_storage/tests/topic_manifest_test.cc, src/v/cluster/cluster_utils.cc, src/v/cluster/tests/topic_properties_generator.h, src/v/cluster/topic_configuration.cc, src/v/cluster/topic_properties.cc, src/v/cluster/topic_properties.h, src/v/cluster/topic_table.cc, src/v/cluster/types.cc, src/v/cluster/types.h, src/v/compat/cluster_generator.h, src/v/compat/cluster_json.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/kafka/server/handlers/alter_configs.cc, src/v/kafka/server/handlers/configs/config_response_utils.cc, src/v/kafka/server/handlers/create_topics.cc, src/v/kafka/server/handlers/incremental_alter_configs.cc, src/v/kafka/server/handlers/topics/types.cc, src/v/kafka/server/handlers/topics/types.h, src/v/kafka/server/tests/alter_config_test.cc, src/v/redpanda/admin/api-doc/debug.json, src/v/redpanda/admin/debug.cc, src/v/storage/ntp_config.h, src/v/storage/types.cc, tests/rptest/tests/describe_topics_test.py, tools/offline_log_viewer/controller.py
Adds the following
* Topic property: iceberg.enabled = {true, false} -- to enable or disable iceberg translation at a topic scope.
* Cluster configuration iceberg_enabled = {true, false} -- to enable or disable iceberg feature at the cluster scope. 
Note: cluster configuration `iceberg_enabled` = `true` only enables the feature and requires each topic to explicitly opt-in by setting `iceberg.enabled`=`true`.  `iceberg_enabled` = `false` disables the feature cluster wide irrespective of the topic overrides.
Property/config names are taken from [here](https://docs.google.com/document/d/12f334Ll4WeLC_djmwNm9zLfMBMP8a73iAmhn6KC8OwE/edit) 
* none
=> datalake: iceberg topic property and cluster configuration

src/v/datalake/BUILD, src/v/datalake/CMakeLists.txt, src/v/datalake/conversion_outcome.h, src/v/datalake/schema_protobuf.cc, src/v/datalake/schema_protobuf.h, src/v/datalake/tests/BUILD, src/v/datalake/tests/CMakeLists.txt, src/v/datalake/tests/schema_protobuf_test.cc, src/v/datalake/tests/testdata/iceberg_ready_test_messages_edition2023.proto, src/v/iceberg/BUILD
Added translation of Protocol buffer schema to Redpanda internal icberg schema.
- none
=> Added protocol buffers schema translation 

src/v/iceberg/snapshot.h, src/v/iceberg/snapshot_json.cc, src/v/iceberg/snapshot_json.h, src/v/iceberg/table_metadata.h, src/v/iceberg/table_metadata_json.cc, src/v/iceberg/table_requirement.h, src/v/iceberg/table_update.h, src/v/iceberg/tests/snapshot_json_test.cc, src/v/iceberg/tests/table_metadata_json_test.cc
Iceberg has the concept of snapshot references, which are basically named pointers at snapshots in metadata. This adds the definition for this, and adds the structure of the table update/requirement that will use it.
https://iceberg.apache.org/spec/#snapshot-references
* none
=> iceberg: add snapshot references

src/v/iceberg/BUILD, src/v/iceberg/CMakeLists.txt, src/v/iceberg/tests/BUILD, src/v/iceberg/tests/CMakeLists.txt, src/v/iceberg/tests/values_bytes_test.cc, src/v/iceberg/values_bytes.cc, src/v/iceberg/values_bytes.h
Adds byte serialization for primitive types[1].
Manifests and manifest lists will need to store serialized partition keys, and thus, need to serialize various primitive values as bytes.
The implementation for the most part is lifted from the implementation in serde/rw/scalar.h, which also stores values as little endian.
[1] https://iceberg.apache.org/spec/#binary-single-value-serialization
* none
=> iceberg: value serialization to/from bytes

src/v/iceberg/BUILD, src/v/iceberg/manifest_list_avro.cc, src/v/iceberg/schema.cc, src/v/iceberg/schema.h, src/v/iceberg/snapshot.h, src/v/iceberg/snapshot_json.cc, src/v/iceberg/table_requirement.h, src/v/iceberg/tests/schema_test.cc
This includes a few miscellaneous pieces of functionality that will be useful for adding data to an Iceberg table:
- Method to get the highest column id in a schema. This is useful for when we set the schema for a table, as the Iceberg table metadata must track the latest column ID.
- Make snapshots default copyable. This will allow for adding snapshots to table metadata while also serializing snapshots into a catalog request.
- Fix for serializing manifest lists, which didn't correctly set a field.
* none
=> iceberg: miscellaneous preparatory code for commit protocol

src/v/cluster/cluster_utils.cc, src/v/redpanda/admin/debug.cc
=> admin: fix copy paste mistake leading to incorrect value for max_collectible_offset

src/v/debug_bundle/debug_bundle_service.cc, src/v/debug_bundle/debug_bundle_service.h, src/v/debug_bundle/tests/debug_bundle_service_test.cc, src/v/debug_bundle/tests/rpk-shim.sh
Implements handling of files for debug bundle service
* None
=> CORE-7094 implement file handling

src/v/storage/tests/compaction_e2e_test.cc
Adjust the `sleep` time as well as the `tombstone_retention_ms` value used to ensure self-compaction and tombstone removal occurs as expected.
Running with `--gtest_repeat --gtest_break_on_failure` locally shows no flakes post fix.
* none
=> `storage`: fix flakey `TestTombstonesCompletelyEmptyLog`

src/v/debug_bundle/debug_bundle_service.cc, src/v/debug_bundle/debug_bundle_service.h, src/v/debug_bundle/json.h, src/v/debug_bundle/tests/debug_bundle_service_test.cc, src/v/debug_bundle/tests/json_test.cc, src/v/debug_bundle/types.h, src/v/redpanda/admin/api-doc/debug_bundle.def.json, src/v/redpanda/admin/api-doc/debug_bundle.json
Added new parameters for debug bundle
* None
=> CORE-7723 add new params

src/v/storage/disk_log_impl.cc, tests/rptest/tests/full_disk_test.py
For reasons not well understood each partition needs to have at least 2 segments for eviction to be triggered. We have tried to change this condition in https://github.com/redpanda-data/redpanda/pull/22686 but had to revert it in
https://github.com/redpanda-data/redpanda/pull/22995.
For now, produce more data to increase the chance of each partition having at least 2 segments worth of data.
Fixes #18014
* none
=> rptest: produce more data in FullDiskReclaimTest to trigger gc conditions

src/v/datalake/tests/CMakeLists.txt, tools/cmake_test.py, ubsan_suppressions.txt
=> chore: sanitizer fixes

src/v/kafka/server/handlers/alter_configs.cc, src/v/kafka/server/handlers/configs/config_utils.h, src/v/kafka/server/handlers/incremental_alter_configs.cc, src/v/kafka/server/tests/alter_config_test.cc
... so users cannot enable it for non user topics.
Follow up for https://github.com/redpanda-data/redpanda/pull/23443
* none
=> iceberg/config: add a config validator for the property

src/v/iceberg/table_update_applier.cc
Review followup from
https://github.com/redpanda-data/redpanda/pull/23488.
* none
=> iceberg: clarify error log in update applier

src/v/iceberg/BUILD, src/v/iceberg/CMakeLists.txt, src/v/iceberg/action.cc, src/v/iceberg/action.h, src/v/iceberg/tests/BUILD, src/v/iceberg/tests/CMakeLists.txt, src/v/iceberg/tests/update_schema_action_test.cc, src/v/iceberg/transaction.cc, src/v/iceberg/transaction.h, src/v/iceberg/update_schema_action.cc, src/v/iceberg/update_schema_action.h
Introduces the concept of a transaction, which is a collection of
updates to a table to be sent to the catalog together. Updates and their
corresponding requirements are generated via a new `action` abstraction,
which are constructed and run in the context of a single transaction.
The actions update in-memory table_metadata owned by the transaction,
but the actual update to the table is only committed when the
transaction's updates are sent to a catalog (not included in this
commit).
To demonstrate, one such action is included in this commit, for schema
updates.
* none
=> iceberg: initial transactions + update_schema_action

src/v/iceberg/table_update_applier.cc
Review followup from https://github.com/redpanda-data/redpanda/pull/23488
* none
=> iceberg: review follow-up for #23488

src/v/cluster/cluster_utils.cc, src/v/redpanda/admin/debug.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/23458
=> [v24.2.x] admin: fix copy paste mistake leading to incorrect value for max_collectible_offset

src/v/iceberg/table_update_applier.cc, src/v/iceberg/transaction.h
Review follow-up for #23488, #23496
* none
=> iceberg: review follow-up for #23488, #23496

src/v/archival/ntp_archiver_service.cc, src/v/storage/disk_log_impl.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/23399
=> [v24.2.x] archival: use correct segment size in adjacent segment merger

src/v/cloud_topics/CMakeLists.txt, src/v/cloud_topics/reconciler/BUILD, src/v/cloud_topics/reconciler/CMakeLists.txt, src/v/cloud_topics/reconciler/range_batch_consumer.cc, src/v/cloud_topics/reconciler/range_batch_consumer.h, src/v/cloud_topics/reconciler/reconciler.cc, src/v/cloud_topics/reconciler/reconciler.h, src/v/cloud_topics/reconciler/tests/BUILD, src/v/cloud_topics/reconciler/tests/range_batch_consumer_test.cc, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/BUILD, src/v/redpanda/CMakeLists.txt, src/v/redpanda/application.cc, src/v/redpanda/application.h, tests/rptest/tests/cloud_topics_test.py
Adds a minimal reconciler designed to be as simple as possible for the cloud topics PoC.
* none
=> cloud_topics poc: add reconciler

src/v/cloud_storage/inventory/aws_ops.cc
Avoid ducktape failures due to bad log lines.
* none
=> cs/inventory: downgrade shutdown exception to warn

tests/rptest/services/redpanda_installer.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23429
Backport of PR https://github.com/redpanda-data/redpanda/pull/23518 
Fixes https://github.com/redpanda-data/redpanda/issues/23526
=> [v23.3.x] CORE-7689 dt/rp_installer: ensure cache directory exists

src/v/storage/disk_log_impl.cc, tests/rptest/tests/full_disk_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23512
Fixes: https://github.com/redpanda-data/redpanda/issues/23516,
=> [v24.2.x] rptest: produce more data in FullDiskReclaimTest to trigger gc conditions

tests/rptest/clients/kafka_cli_tools.py, tests/rptest/tests/full_disk_test.py
Fixes [CORE-6919](https://redpandadata.atlassian.net/browse/CORE-6919) 
* none
[CORE-6919]: https://redpandadata.atlassian.net/browse/CORE-6919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> rptest: make target_min_capacity_wanted more deterministic

tests/rptest/tests/full_disk_test.py
Another take on fixing
rptest.tests.full_disk_test.FullDiskReclaimTest.test_full_disk_triggers_gc.
Previous one was https://github.com/redpanda-data/redpanda/pull/23512 but I found another case where it fails. It is possible that after eviction a leadership transfer or election will happen thus creating a new log segment...
We can't wait for that segment to be eventually evicted because we currently do not evict last segment. We could disable leadership balancer but there might be a network issue causing a leader election in a CDT test. It is hard to impossible to account for all conditions.
Instead, change the thresholds on the test such that it is acceptable to have at least one segment still on disk per partition.
While it is possible for this test to pass with a partition having 5 …
=> rptest: increase threshold for test_full_disk_triggers_gc

tests/docker/Dockerfile, tests/docker/ducktape-deps/java-dev-tools, tests/docker/ducktape-deps/polaris, tests/rptest/services/polaris_catalog.py, tests/rptest/services/templates/polaris-server.yml, tests/rptest/tests/polaris_catalog_smoke_test.py, tests/rptest/tests/polaris_catalog_test.py, tests/setup.py
Added a service maintaining Polaris open source iceberg catalog. 
- none
=> Polaris catalog in ducktape

tests/rptest/tests/redpanda_binary_test.py
=> test: add ubsan suppression to redpanda invocation

src/v/cluster/controller.cc, src/v/cluster/metrics_reporter.cc, src/v/cluster/metrics_reporter.h, src/v/features/enterprise_features.cc, src/v/features/enterprise_features.h, tests/rptest/tests/metrics_reporter_test.py
PR adds boolean field to phone home telemetry:
- `has_valid_license` - True iff license is present and not expired
- `has_enterprise_features` - True iff ANY enterprise feature is in use
* none
=> [CORE-7719] Add `has_valid_license` & `has_enterprise_features`  to phone-home metrics

src/v/cluster/archival/archiver_operations_impl.cc, src/v/cluster/archival/ntp_archiver_service.cc, src/v/cluster/archival/tests/archival_service_fixture.h, src/v/cluster/archival/tests/archiver_manager_test.cc
The test is failing when the controller leadership is moving. This commit modifies the test to ignore 'not_leader' errors.
* none
=> archival: Fix torture test

tests/rptest/tests/write_caching_fi_test.py
In debug builds futures reordering causes out-of-order message delivery which triggers raft recovery. Raft recovery fsync writes to disk which prevents data loss.  Continue trying until we hit the data loss scenario.
Investigated in https://github.com/redpanda-data/redpanda/issues/21395#issuecomment-2245300248
* none
=> rptest: attempt data loss scenario a few times

tests/rptest/tests/write_caching_fi_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23568
=> [v24.2.x] rptest: attempt data loss scenario a few times

tests/rptest/tests/full_disk_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23550
=> [v24.2.x] rptest: increase threshold for test_full_disk_triggers_gc

src/v/cluster/tests/BUILD, src/v/cluster/tests/leader_balancer_test_utils.h, src/v/cluster/tests/partition_leaders_table_test.cc, src/v/cluster/tests/plugin_frontend_validation_test.cc, src/v/storage/BUILD
Fixes: CORE-7454
Fixes: CORE-7445
Fixes: CORE-7413
Fixes: CORE-7439
Fixes: CORE-7446
Fixes: CORE-7447
Fixes: CORE-7438
Fixes: CORE-7433
Fixes: CORE-7434
* none
=> cluster: bazel test backfill

src/v/cloud_topics/BUILD, src/v/cloud_topics/batcher/batcher.cc, src/v/cloud_topics/batcher/batcher.h, src/v/cloud_topics/batcher/tests/BUILD, src/v/cloud_topics/batcher/tests/batcher_test.cc, src/v/cloud_topics/batcher/tests/remote_mock.h
This PR implements time limitation for write requests. If for some reason any write request got expired we will ack the client with error and avoid adding data from this write request to the next L0 upload.
Also, this PR improves testability by splitting logic out of the background fiber and driving uploads from the test itself. This allows the test (in combination with `ss::manual_clock`) to test different interleavings without relying on real-time delays. 
* none
=> ct: Refactor batcher for improved testability and implement timeouts

tests/rptest/tests/rpk_generate_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23607
=> [v23.3.x] tests: fix rpk generate test

tests/rptest/tests/rpk_generate_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23607
=> [v24.1.x] tests: fix rpk generate test

tests/rptest/tests/rpk_generate_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23607
=> [v24.2.x] tests: fix rpk generate test

src/v/iceberg/BUILD, src/v/iceberg/CMakeLists.txt, src/v/iceberg/catalog.h, src/v/iceberg/filesystem_catalog.cc, src/v/iceberg/filesystem_catalog.h, src/v/iceberg/tests/BUILD, src/v/iceberg/tests/CMakeLists.txt, src/v/iceberg/tests/filesystem_catalog_test.cc
Adds a very simple implementation of a file system catalog, meant for
operating on Iceberg tables only using object storage. This closely
resembles the concept of "file system tables"[1] (though
recently deprecated by the Iceberg spec). This will still be useful for
tests and demos that don't have a catalog service like Polaris.
There are some caveats called out in the header around concurrency.
Without additional polish, use of this catalog is unsafe and not
recommended for production.
[1] https://iceberg.apache.org/spec/#file-system-tables
* none
=> iceberg: add filesystem catalog

src/v/cluster/members_backend.cc
The log line `INFO  2024-09-13 13:53:24,030 [shard 0:main] cluster - members_backend.cc:178 - error encountered while handling cluster state reconciliation - seastar::broken_condition_variable (Condition variable is broken)` is almost always found upon shutting down `redpanda`.
To prevent a `seastar::broken_condition_variable` exception being thrown on shutdown and presenting itself as an error, wrap condition variable `wait()`s in a `try/catch` block, and return a standard `errc::shutting_down` error code (or simply `co_return` in the `ss::future<>` case) in `members_backend`.
* none
=> `cluster`: add `try/catch` blocks to `members_backend`

src/go/rpk/Makefile, src/go/rpk/pkg/cli/topic/utils.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/23487
=> [v24.1.x] rpk: bring back Makefile and add support for internal topics in `describe`

src/go/rpk/Makefile, src/go/rpk/pkg/cli/topic/utils.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/23487
=> [v24.2.x] rpk: bring back Makefile and add support for internal topics in `describe`

.bazelrc, MODULE.bazel, MODULE.bazel.lock, bazel/toolchain/Dockerfile.llvm, src/v/cluster/tests/shard_placement_table_test.cc
=> bazel: upgrade to clang-18

src/v/cluster/metrics_reporter.cc, tests/rptest/tests/metrics_reporter_test.py
We were asserting an expired license when we should have asserted non-expired.
* none
=> c/metrics: Fix snapshot::has_valid_license inverted condition

src/v/base/vassert.h, src/v/cloud_io/auth_refresh_bg_op.h, src/v/cloud_roles/types.h, src/v/cloud_storage/tests/BUILD, src/v/cluster/BUILD, src/v/cluster/tests/BUILD, src/v/config/broker_endpoint.h, src/v/crypto/tests/test_values.h, src/v/datalake/coordinator/BUILD, src/v/datalake/protobuf_utils.h, src/v/debug_bundle/utils.cc, src/v/features/feature_table.h, src/v/iceberg/BUILD, src/v/json/validator.h, src/v/kafka/client/test/BUILD, src/v/kafka/protocol/BUILD, src/v/kafka/protocol/tests/BUILD, src/v/pandaproxy/schema_registry/subject_name_strategy.h, src/v/raft/BUILD, src/v/raft/fundamental.h, src/v/random/generators.h, src/v/security/audit/BUILD, src/v/security/tests/BUILD, src/v/serde/BUILD, src/v/serde/envelope.h, src/v/serde/rw/chrono.h, src/v/syschecks/syschecks.h, src/v/utils/BUILD, src/v/utils/adjustable_semaphore.h
various clang-tidy fixes
* none
=> clang-tidy: various fixes

src/v/redpanda/application.cc
This reverts commit d8402c6376f2ca10f261da454ac3163edff7278b. Originally it was intended to fix an oversized allocation in `io_sink`. However, a more permanent fix has been added to the upstream as a result of https://github.com/scylladb/seastar/pull/2357 . Hence this commit will no longer be needed once Redpanda switches to the `v24.3.x` seastar branch.
Fixes CORE-7009
* none
=> Revert "increase io_sink size to 10000 at startup"

src/v/cluster/errc.h
=> chore: fix error message type

tests/rptest/clients/rpk.py, tests/rptest/tests/rpk_generate_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23638
=> [v24.1.x] tests: test legacy dashboard in rpk generate

src/v/cluster/feature_manager.cc, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/features/enterprise_features.cc, src/v/features/enterprise_features.h, src/v/kafka/server/handlers/configs/config_utils.h, src/v/kafka/server/handlers/create_topics.cc, src/v/kafka/server/handlers/topics/types.h, src/v/kafka/server/handlers/topics/validators.h, src/v/kafka/server/tests/alter_config_test.cc, src/v/redpanda/application.cc, src/v/redpanda/application.h, src/v/resource_mgmt/memory_groups.cc, src/v/resource_mgmt/memory_groups.h, src/v/resource_mgmt/tests/memory_groups_test.cc, tests/rptest/tests/describe_topics_test.py, tests/rptest/tests/enterprise_features_license_test.py
See individual commit messages for details.
* none
=> datalake/config: miscellaneous changes

tests/rptest/clients/rpk.py, tests/rptest/tests/rpk_generate_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23638
=> [v23.3.x] tests: test legacy dashboard in rpk generate

src/v/cluster/controller.cc, src/v/cluster/metrics_reporter.cc, src/v/cluster/metrics_reporter.h, src/v/features/enterprise_features.cc, src/v/features/enterprise_features.h, tests/rptest/tests/metrics_reporter_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23492  and https://github.com/redpanda-data/redpanda/pull/23622
Fixes #23573
=> [v24.2.x] [CORE-7719] Add has_valid_license & has_enterprise_features  to phone-home metrics

tests/rptest/clients/rpk.py, tests/rptest/tests/rpk_generate_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23638
=> [v24.2.x] tests: test legacy dashboard in rpk generate

src/v/cluster/data_migration_backend.cc, src/v/ssx/include/ssx/future-util.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/23559
=> [v24.2.x] Migrations: fix shutdown busyloop

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23274
=> [v24.2.x] rptest: Enable scrubber only if not explicitly disabled

src/v/cloud_storage/remote_path_provider.cc, src/v/cloud_storage/topic_mount_handler.h
=> cloud_storage: avoid copying topic mount handler

src/v/cloud_storage/tests/BUILD
=> bazel: add cloud storage remote path provider test

.github/workflows/release-rp-storage-tool.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/23649
=> [v24.2.x] gha: rm use of rp_storage_tool_uploader

.github/workflows/release-rp-storage-tool.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/23649
=> [v24.1.x] gha: rm use of rp_storage_tool_uploader

.github/workflows/release-rp-storage-tool.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/23649
=> [v23.3.x] gha: rm use of rp_storage_tool_uploader

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
Added custom options for load_many_segments function, these are optional params and should not brake any current tests that use this function. We should be able to optionally specify target_segments, timeout_segments, num_segments_per_partition
We should be able to optionally specify target_segments, timeout_segments, num_segments_per_partition
This would be useful for custom workloads where we need to load specific number of segments
* none
=> Added custom options for load_many_segments function

src/v/cluster/data_migration_backend.cc, src/v/cluster/data_migration_backend.h, tests/rptest/tests/data_migrations_api_test.py
The underlying issue was not waiting deleting a topic work entry before it completes.
Some tests fixes and improvements too.
* none
=> fix crash when canceling an inbound migration stuck because there is no data for the topic

tests/rptest/tests/random_node_operations_test.py
The error log entry:
```
upload housekeeping job purger error: std::__1::system_error (error
generic:32, System error during SSL read: [error:FFFFFFFF80000020:system
library::Broken pipe]: Broken pipe)
```
should not cause the test to fail as it is not correctness issue.
- none
=> tests: ignore archival ssl error log entry

src/v/cluster/data_migration_backend.cc
When migrations backend has ensured all the work for a migration has been done it sends a request to advance the migration to the new stage. This request may fail, in particular when controller leader changes. Previously they were only retried when the node becomes leader and therefore migration coordinator again. This has two problems:
1) The node may lose leadership only briefly, so that it never ceases to be the migration coordinator. We might solve it by always retrying advance requests on leadership notifications.
2) The request may fail for another reason, such as a timeout.
So we retry them indefinitely with 5s sleep. We only stop doing so if we receive a successful reply from migration frontend, or if the migration is known to have advanced, whether as a result of our actions or …
=> c/migrations: retry advance requests

src/v/iceberg/BUILD, src/v/iceberg/CMakeLists.txt, src/v/iceberg/manifest.cc, src/v/iceberg/manifest.h, src/v/iceberg/manifest_entry.cc, src/v/iceberg/manifest_entry.h, src/v/iceberg/manifest_list.h, src/v/iceberg/metadata_query.cc, src/v/iceberg/metadata_query.h, src/v/iceberg/tests/BUILD, src/v/iceberg/tests/CMakeLists.txt, src/v/iceberg/tests/metadata_query_test.cc
Introduced a read counterpart of `iceberg:transaction` the `iceberg::metadata_query`.
Metadata query representing data structure. Query result_type template
parameter controls what information should be returned after query is
executed. The matchers are predicates returning `true` if an entry
should be included in the result. Empty matcher matches all entities. Matchers are
applied one after another i.e first the snapshot if it matches, the
manifest file matcher and finally the manifest matcher. The matchers are related
with AND relationship i.e. if snapshot matcher is set the snapshot containing
a manifest_file must match. Returned result is an outcome of depth first
search traversal of metadata tree.
- none
=> Introducing an Iceberg metadata query

src/v/datalake/coordinator/BUILD, src/v/datalake/coordinator/state_update.cc, src/v/datalake/coordinator/state_update.h, src/v/datalake/coordinator/tests/BUILD, src/v/datalake/coordinator/tests/CMakeLists.txt, src/v/datalake/coordinator/tests/state_test_utils.cc, src/v/datalake/coordinator/tests/state_test_utils.h, src/v/datalake/coordinator/tests/state_update_test.cc, src/v/model/model.cc, src/v/model/record_batch_types.h
Miscellaneous not yet functional changes, mostly for the sake of observability.
* none
=> datalake/coordinator: miscellaneous changes

src/v/cluster/controller.cc, src/v/cluster/feature_manager.cc, src/v/cluster/feature_manager.h, src/v/features/enterprise_features.cc, src/v/features/enterprise_features.h, tests/rptest/tests/enterprise_features_license_test.py
=> Leadership pinning: add to enterprise features

src/v/cluster/controller.cc, src/v/cluster/feature_manager.cc, src/v/cluster/feature_manager.h, src/v/features/enterprise_features.cc, src/v/features/enterprise_features.h, tests/rptest/tests/enterprise_features_license_test.py
=> [WIP] Leadership pinning

src/v/debug_bundle/BUILD, src/v/debug_bundle/debug_bundle_service.cc, src/v/debug_bundle/json.h, src/v/debug_bundle/tests/debug_bundle_service_test.cc, src/v/debug_bundle/tests/json_test.cc, src/v/debug_bundle/types.cc, src/v/debug_bundle/types.h, src/v/redpanda/admin/api-doc/debug_bundle.json, tests/rptest/services/admin.py
Added ability to select labels via rpk debug bundle by providing a key and value for labels.
Using this will pass the key value pairs as key=value to the --label-selector option of rpk debug bundle.
Fixes: CORE-7859
* None
=> debug_bundle: Added label_select option

src/v/cloud_io/BUILD, src/v/cloud_io/CMakeLists.txt, src/v/cloud_io/basic_cache_service_api.cc, src/v/cloud_io/basic_cache_service_api.h, src/v/cloud_storage/BUILD, src/v/cloud_storage/cache_service.cc, src/v/cloud_storage/cache_service.h
Extract `basic_cache_service_api` ineterface out of `cache_service`.
* none
=> cloud_storage: Extract cache interface

.github/workflows/jira_issue_manage.yml, .github/workflows/lint-python.yml, .github/workflows/transform-sdk-release.yml
=> [24.2.x] gha: fix pip install on python actions

src/v/datalake/BUILD, src/v/datalake/CMakeLists.txt, src/v/datalake/coordinator/BUILD, src/v/datalake/coordinator/CMakeLists.txt, src/v/datalake/coordinator/file_committer.h, src/v/datalake/coordinator/iceberg_file_committer.cc, src/v/datalake/coordinator/iceberg_file_committer.h, src/v/datalake/coordinator/tests/BUILD, src/v/datalake/coordinator/tests/CMakeLists.txt, src/v/datalake/coordinator/tests/iceberg_file_committer_test.cc, src/v/datalake/schemaless_translator.cc, src/v/datalake/table_definition.cc, src/v/datalake/table_definition.h, src/v/iceberg/BUILD, src/v/iceberg/CMakeLists.txt, src/v/iceberg/catalog.cc, src/v/iceberg/catalog.h
Adds an class to be used by the coordinator to encapsulate committing
files to the Iceberg catalog. It takes as inputs the STM state for a
given topic, and returns the resulting STM updates that capture the
catalog updates it has performed.
The separate abstraction isn't strictly required, but it does make it
easier to test, and helps avoid making the coordinator control loop very
bloated.
* none
=> datalake/coordinator: add file committer

src/v/cluster/producer_state.cc, tests/rptest/tests/idempotency_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23692
=> [v24.2.x] Keep producer inflight requests queue bounded

src/v/cluster/partition_manager.cc, src/v/redpanda/application.cc
Followups to https://github.com/redpanda-data/redpanda/pull/23720
Fixes a couple of bugs found during integration.
* none
=> datalake/coordinator: followups to #23720

src/v/kafka/server/group.cc, src/v/kafka/server/group.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/23687
=> [v24.2.x] tx/group: ignore replay requests if producer/tx is not found

.github/workflows/lint-python.yml, .github/workflows/render-pr-body-release-notes.yml
=> [v23.3.x] gha: fix pip install on python actions

tests/rptest/services/failure_injector.py, tests/rptest/tests/data_migrations_api_test.py, tests/rptest/tests/e2e_finjector.py
Finjector may be overzealous, especially for a 3-node cluster.
This is to make it nicer where needed and also to fix final repairs in it.
* none
=> Chasten finjector3

bazel/test.bzl, src/v/test_utils/BUILD
- a build for test_utils/scoped_config
- IS_GTEST definition, without which macros in test_macros.h were no-ops
* none
=> bazel: miscellaneous improvements

src/v/cloud_topics/reconciler/BUILD, src/v/cloud_topics/reconciler/reconciler.cc, src/v/cloud_topics/reconciler/reconciler.h, src/v/redpanda/application.cc, tests/rptest/tests/cloud_topics_test.py
CORE-7820 test: fix cloud assumption failure in cdt
* none
=> CORE-7820 test: fix cloud assumption failure in cdt

tests/docker/Dockerfile, tests/docker/ducktape-deps/iceberg-rest-catalog, tests/rptest/services/apache_iceberg_catalog.py, tests/rptest/tests/datalake/__init__.py, tests/rptest/tests/datalake/iceberg_rest_catalog.py, tests/rptest/tests/datalake/iceberg_rest_catalog_smoke_test.py
Adding simple Java based REST iceberg catalog to ducktape
- none
=> Iceberg rest catalog cleanup

tests/docker/ducktape-deps/kgo-verifier, tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/services/kgo_verifier_services.py, tests/rptest/tests/delete_records_test.py, tests/rptest/tests/mirror_maker_test.py
_See individual commits please._
* none
=> rptest: upgrade kgo and fix its usage

src/v/cloud_topics/batcher/tests/serializer_test.cc
cloud_topics: use existing random batch generator
* none
=> cloud_topics: use existing random batch generator

tests/rptest/tests/audit_log_test.py
Did not replace the ok_to_fail_fips flags in the other tests, as that's begin done in
https://github.com/redpanda-data/redpanda/pull/23644
* None
=> dt/audit: Added missing skip_fips_mode

src/v/debug_bundle/debug_bundle_service.cc, tests/rptest/services/admin.py, tests/rptest/services/redpanda.py, tests/rptest/services/templates/redpanda.yaml, tests/rptest/tests/debug_bundle_test.py
Expanded integration testing of the debug bundle
* None
=> CORE-7792: Expand debug bundle tests

src/v/cloud_topics/reader/placeholder_extent.cc, src/v/cloud_topics/reader/placeholder_extent.h, src/v/cloud_topics/reader/placeholder_extent_reader.cc, src/v/cloud_topics/reader/placeholder_extent_reader.h, src/v/cloud_topics/reader/tests/placeholder_extent_test.cc
Followup fixes for #23629
* none
=> ct: Read path followup

src/v/datalake/coordinator/BUILD, src/v/datalake/coordinator/coordinator.cc, src/v/datalake/coordinator/coordinator.h, src/v/datalake/coordinator/coordinator_manager.cc, src/v/datalake/coordinator/coordinator_manager.h, src/v/datalake/coordinator/state_machine.cc, src/v/datalake/coordinator/tests/BUILD, src/v/datalake/coordinator/tests/coordinator_test.cc, src/v/redpanda/application.cc, src/v/redpanda/application.h, tests/rptest/tests/enterprise_features_license_test.py
Adds a background loop to the coordinator that periodically commits to files to Iceberg and replicates the updates to the coordinator STM.
As is, the plumbing is in to interact with a file system catalog, and is hard coded to commit at a fixed interval, though followup work will make both of these configurable. Some other follow-on improvements include things like more aggressively stopping the loop when leadership is lost, or deduplicating files that are already in the catalog. For now this PR just focuses on some initial plumbing and getting the structure of the background loop up.
* none
=> datalake/coordinator: add file committer background loop

tests/docker/ducktape-deps/kgo-verifier, tests/rptest/redpanda_cloud_tests/high_throughput_test.py, tests/rptest/services/kgo_verifier_services.py, tests/rptest/tests/delete_records_test.py, tests/rptest/tests/mirror_maker_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23793
=> [v24.2.x] rptest: upgrade kgo and fix its usage

src/v/cloud_io/remote.cc, src/v/datalake/BUILD, src/v/datalake/CMakeLists.txt, src/v/datalake/cloud_data_io.cc, src/v/datalake/cloud_data_io.h, src/v/datalake/fwd.h, src/v/datalake/tests/CMakeLists.txt, src/v/datalake/tests/translation_task_test.cc, src/v/datalake/translation_task.cc, src/v/datalake/translation_task.h
Introduced `datalake::translation_task` a type wrapping around action of
translating Kafka data to parquet files and uploading them to the cloud.
The translation task is an entry point for the translation process. The
translation task returns information required to update the datalake
coordinator.
- none
=> Introduced data translation task

src/v/kafka/server/handlers/list_offsets.cc, src/v/ssx/include/ssx/when_all.h, src/v/ssx/tests/CMakeLists.txt, src/v/ssx/tests/when_all_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/23792
=> [v24.2.x] kafka: oversized alloc in list_offsets_topic

src/v/redpanda/admin/api-doc/migration.json
=> admin/doc/migrations: describe GET request return structure

src/v/kafka/client/CMakeLists.txt, src/v/kafka/client/record_batcher.cc, src/v/kafka/client/record_batcher.h, src/v/kafka/client/test/CMakeLists.txt, src/v/kafka/client/test/record_batcher_test.cc, src/v/kafka/client/test/utils.cc, src/v/kafka/client/test/utils.h, src/v/redpanda/application.cc, src/v/security/audit/CMakeLists.txt, src/v/security/audit/audit_log_manager.cc, src/v/security/audit/audit_log_manager.h, src/v/transform/logging/CMakeLists.txt, src/v/transform/logging/rpc_client.cc, src/v/transform/logging/tests/CMakeLists.txt, src/v/transform/logging/tests/utils.cc, src/v/transform/logging/tests/utils.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/23775 
Closes https://github.com/redpanda-data/redpanda/issues/23864
=> [v24.2.x] [CORE-7803] Audit Log Manager: Refactoring - use  and reduce retries.

src/v/kafka/server/handlers/list_offsets.cc, src/v/ssx/tests/CMakeLists.txt, src/v/ssx/tests/when_all_test.cc, src/v/ssx/when_all.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/23792
=> [v23.3.x] kafka: oversized alloc in list_offsets_topic

src/v/datalake/BUILD, src/v/datalake/CMakeLists.txt, src/v/datalake/arrow_translator.cc, src/v/datalake/arrow_translator.h, src/v/datalake/batching_parquet_writer.cc, src/v/datalake/batching_parquet_writer.h, src/v/datalake/data_writer_interface.h, src/v/datalake/partitioning_writer.cc, src/v/datalake/partitioning_writer.h, src/v/datalake/record_multiplexer.cc, src/v/datalake/tests/BUILD, src/v/datalake/tests/CMakeLists.txt, src/v/datalake/tests/partitioning_writer_test.cc, src/v/datalake/tests/test_data_writer.h, src/v/iceberg/BUILD, src/v/iceberg/tests/BUILD, src/v/iceberg/tests/CMakeLists.txt
Adds yet another abstraction to be used on the data path: the new partitioning writer will be in charge of collecting records that correspond to a single schema and grouping them by their appropriate partition key.
The default partitioning specification will be to partition timestamps by the hour. A test is added that demonstrates this.
This is not yet plugged into the record multiplexer, but the expectation is that the multiplexer will construct one partitioning_writer per Parquet schema, instead of instantiating data writers directly.
* none
=> datalake: add partitioning_writer

src/v/storage/tests/storage_e2e_test.cc
regression test for preventing compaction of offset translation batches
Compacting offset translation batches can mess up the offset translation state and hence Kafka offsets. Adds a simple test that serves as a regression test to avoid such scenario.
* none
=> storage/tests: regression test for preventing compaction of offset translation batches

src/v/datalake/translation/BUILD
=> bazel: fix wrong translation:stm dependency

src/v/cloud_storage/BUILD, src/v/cloud_storage/CMakeLists.txt, src/v/cloud_storage/remote_path_provider.cc, src/v/cloud_storage/tests/BUILD, src/v/cloud_storage/tests/CMakeLists.txt, src/v/cloud_storage/tests/remote_path_provider_test.cc, src/v/cloud_storage/tests/topic_mount_handler_test.cc, src/v/cloud_storage/tests/topic_mount_manifest_path_test.cc, src/v/cloud_storage/topic_mount_handler.cc, src/v/cloud_storage/topic_mount_handler.h, src/v/cloud_storage/topic_mount_manifest_path.cc, src/v/cloud_storage/topic_mount_manifest_path.h, src/v/cluster/BUILD, src/v/cluster/controller.cc, src/v/cluster/controller.h, src/v/cluster/data_migration_backend.cc, src/v/cluster/data_migration_backend.h, src/v/cluster/data_migration_frontend.cc, src/v/cluster/data_migration_frontend.h, src/v/redpanda/admin/api-doc/migration.def.json, src/v/redpanda/admin/api-doc/migration.json, src/v/redpanda/admin/server.h, src/v/redpanda/admin/topics.cc, tests/rptest/services/admin.py, tests/rptest/tests/data_migrations_api_test.py
=> c/migrations: list mountable topics

tests/rptest/tests/controller_log_limiting_test.py
Previously the test assumed that it could make each request within 1/3 of a second from the previous one. Relax this assumption.
* none
=> tests: relax assumptions in test_create_user_limit

src/v/utils/tracking_allocator.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/23511
=> [v24.2.x] utils: fix container-overflow in tracking allocator

src/go/rpk/pkg/cli/cloud/login.go, src/go/rpk/pkg/cli/connect/client.go, src/go/rpk/pkg/cli/registry/schema/get.go, src/go/rpk/pkg/cli/version/version.go, src/go/rpk/pkg/plugin/plugin.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/23886
=> [v24.2.x] rpk: small improvements prior v24.2

tests/rptest/tests/controller_log_limiting_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23894
=> [v24.2.x] tests: relax assumptions in test_create_user_limit

src/v/cluster/controller.cc, src/v/cluster/metrics_reporter.cc, src/v/cluster/metrics_reporter.h, src/v/features/enterprise_features.cc, src/v/features/enterprise_features.h, tests/rptest/tests/metrics_reporter_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23492 
Closes https://github.com/redpanda-data/redpanda/issues/23574
=> [v24.1.x] [CORE-7719] Add has_valid_license & has_enterprise_features to phone-home metrics

src/go/.goreleaser.yaml
Backport of PR https://github.com/redpanda-data/redpanda/pull/23865
=> [v24.2.x] goreleaser: rm publish brews

src/v/redpanda/admin/server.cc, tests/docker/ducktape-deps/kgo-verifier, tests/rptest/services/failure_injector.py, tests/rptest/services/kgo_verifier_services.py, tests/rptest/tests/data_migrations_api_test.py, tests/rptest/tests/e2e_finjector.py
=> testing migrations

README.md
Update the README to: 
- modified introdutory text to match https://www.redpanda.com/what-is-redpanda
-  include Table of contents
-  and reestructure heading order
- add resources links 
- make small edits
https://github.com/Deflaimun/redpanda/tree/update-readme
* none
=> readme: Reestructure readme and add resources link

src/go/rpk/pkg/cli/profile/create.go, src/go/rpk/pkg/cloudapi/api_virtual_cluster.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/23910
=> [v24.1.x] rpk: fill schema registry information in cloud profiles

src/go/rpk/pkg/cli/profile/create.go, src/go/rpk/pkg/cloudapi/api_virtual_cluster.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/23910
=> [v24.2.x] rpk: fill schema registry information in cloud profiles

src/v/redpanda/admin/api-doc/migration.def.json, src/v/redpanda/admin/data_migration_utils.cc, src/v/redpanda/admin/migrations.cc, src/v/redpanda/admin/topics.cc, tests/rptest/services/admin.py, tests/rptest/tests/data_migrations_api_test.py
As discussed [on Slack](https://redpandadata.slack.com/archives/C07NRB78NCC/p1729625564534409?thread_ts=1729619320.195469&cid=C07NRB78NCC) with @weeco
It'll require changes in docs, rpk and cloud api.
Also removing location component of inbound topic, as it is never used or supported. Location hints are part of source topic reference now.
* none
=> Migrations: rename source topic to source topic reference

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/datalake/coordinator/coordinator_manager.cc, src/v/datalake/coordinator/coordinator_manager.h, src/v/redpanda/application.cc
Replaces a mock property and static string previously baked into coordinator_manager.
* none
=> config: Add iceberg_catalog_commit_interval_ms and iceberg_catalog_base_location

src/v/datalake/coordinator/iceberg_file_committer.cc, src/v/iceberg/BUILD, src/v/iceberg/catalog.cc, src/v/iceberg/catalog.h, src/v/iceberg/field_collecting_visitor.h, src/v/iceberg/schema.cc, src/v/iceberg/schema.h, src/v/iceberg/tests/BUILD, src/v/iceberg/tests/filesystem_catalog_test.cc, src/v/iceberg/tests/merge_append_action_test.cc, src/v/iceberg/tests/metadata_query_test.cc, src/v/iceberg/tests/rest_catalog_test.cc, src/v/iceberg/tests/schema_test.cc, src/v/iceberg/tests/update_schema_action_test.cc, src/v/iceberg/transaction.cc, src/v/iceberg/transaction.h, src/v/iceberg/update_schema_action.cc
Miscellaneous preparatory changes for supporting schemas along the datalake write path.
- Made transactions not take the manifest_io by default, and instead pushed it to callers of the merge_append. This lets us test schema updates without depending on manifest_io.
- Method to reassign field IDs before sending a schema to the catalog.
- Moved implementation of load_and_create into the catalog, so it can be used by the abstraction that will manage Iceberg schemas.
* none
=> iceberg: miscellaneous changes for Iceberg schemas

src/v/datalake/schema_registry.cc, src/v/datalake/schema_registry.h, src/v/datalake/tests/BUILD, src/v/datalake/tests/schema_registry_test.cc, src/v/pandaproxy/schema_registry/protobuf.cc, src/v/pandaproxy/schema_registry/protobuf.h
Miscellaneous improvements I found useful when writing support for parsing protobuf out of records bodies:
- Rejiggers some pandaproxy code to expose the protobuf Descriptor (before we just exposed the name)
- Reworked some code to get protobuf offsets from an iobuf (before we always got the schema ID and offsets together, but my upcoming code will parse them separately)
- Adds a guardrail when accessing a Descriptor
- Bazel build for datalake/schema_registry_test
* none
=> datalake: miscellaneous improvements around protobuf

src/v/config/configuration.cc
The configuration constructor takes about 90KB of stack space in debug.
This can lead to us running out of stack space with the default
`ss::thread` stack size of 128KiB.
To avoid this construct the object in a separate thread with increased
stack size.
* none
=> config: Create configuration on a separate ss::thread

src/v/datalake/BUILD, src/v/datalake/CMakeLists.txt, src/v/datalake/record_schema_resolver.h, src/v/datalake/schema_identifier.h, src/v/datalake/schemaless_translator.cc, src/v/datalake/table_definition.cc, src/v/datalake/tests/CMakeLists.txt, src/v/iceberg/catalog.cc, src/v/iceberg/schema_avro.cc, src/v/serde/avro/tests/BUILD, src/v/serde/avro/tests/CMakeLists.txt, src/v/serde/avro/tests/data_generator.cc, src/v/serde/avro/tests/data_generator.h, src/v/serde/avro/tests/parser_test.cc
This contains a few small improvements made while working on per-schema per-partition file writing.
- CMake build for record_schema_resolver
- moves serde::avro's data generator to be reused
- allows iceberg::values_avro to be permissive for missing element-ids (stop gap until serde::avro is ready to use)
- bug fix to pass ValidSchema (which wraps a ref-counted node) around instead of a reference
- hashing function for schema_identifier
- changes key/value in the default schema to be binary
* none
=> datalake: miscellaneous fixes and preparatory changes for multiplexing

src/go/rpk/go.mod, src/go/rpk/go.sum, src/go/rpk/pkg/cli/cluster/storage/BUILD, src/go/rpk/pkg/cli/cluster/storage/list-mount.go, src/go/rpk/pkg/cli/cluster/storage/list-mountable.go, src/go/rpk/pkg/cli/cluster/storage/mount.go, src/go/rpk/pkg/cli/cluster/storage/storage.go, src/go/rpk/pkg/cli/cluster/storage/unmount.go
DRAFT: Currently using an unreleased version of common-go. 
Adds support for list-mountable
* Adds list-mountable to allow listing mountable topics
=> List mountable

src/v/config/property.h, src/v/redpanda/admin/server.cc
What it says on the tin.
- better use of `std::ranges` in `config::enterprise`
- less wordy log message in `admin_server::patch_cluster_config_handler`
* none
=> Minor fixups for `config::enterprise` and associated Admin API logging

src/go/rpk/pkg/adminapi/admin.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/23987
=> [v24.2.x] rpk: fix printing new lines

src/go/rpk/pkg/adminapi/admin.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/23987
=> [v24.1.x] rpk: fix printing new lines

tests/docker/Dockerfile, tests/docker/ducktape-deps/spark
cdt expects java dependencies in path /opt/redpanda-tests/java/ as that is the location to which the directories are copied from the redpanda tests directory.
* none
=> cdt: fix spark-iceberg-dependencies location

src/v/cloud_topics/BUILD, src/v/cloud_topics/CMakeLists.txt, src/v/cloud_topics/dl_overlay.cc, src/v/cloud_topics/dl_overlay.h, src/v/cloud_topics/dl_stm/BUILD, src/v/cloud_topics/dl_stm/CMakeLists.txt, src/v/cloud_topics/dl_stm/dl_stm.cc, src/v/cloud_topics/dl_stm/dl_stm.h, src/v/cloud_topics/dl_stm/dl_stm_api.cc, src/v/cloud_topics/dl_stm/dl_stm_api.h, src/v/cloud_topics/dl_stm/dl_stm_commands.h, src/v/cloud_topics/dl_stm/dl_stm_state.cc, src/v/cloud_topics/dl_stm/dl_stm_state.h, src/v/cloud_topics/dl_stm/tests/BUILD, src/v/cloud_topics/dl_stm/tests/dl_stm_state_test.cc, src/v/cloud_topics/dl_stm/tests/dl_stm_test.cc, src/v/cloud_topics/dl_version.h, src/v/cloud_topics/tests/types_test.cc, src/v/cloud_topics/types.cc, src/v/cloud_topics/types.h, src/v/cluster/BUILD, src/v/cluster/CMakeLists.txt, src/v/cluster/partition.cc, src/v/cluster/partition.h
See individual commits. This PR mostly defines the dl_overlay related types and adds basic push_overlay/lower_bound methods.
Future commits will extend the functionality as needed. I.e.
reconciler must ensure push_overlay implementation is correct, recovery
will extend the stm and stm_state with snapshotting mechanisms, etc.
* none
=> ct: dl_stm basic mvcc overlays

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/config/convert.h, src/v/config/property.h, src/v/config/rjson_serialization.cc, src/v/config/rjson_serialization.h, src/v/config/types.h, src/v/config/validators.cc, src/v/config/validators.h, src/v/datalake/coordinator/BUILD, src/v/datalake/coordinator/CMakeLists.txt, src/v/datalake/coordinator/catalog_factory.cc, src/v/datalake/coordinator/catalog_factory.h, src/v/datalake/coordinator/coordinator_manager.cc, src/v/datalake/coordinator/coordinator_manager.h, src/v/iceberg/BUILD, src/v/iceberg/manifest_entry.h, src/v/iceberg/merge_append_action.cc, src/v/iceberg/rest_client/BUILD, src/v/iceberg/rest_client/json.cc, src/v/redpanda/BUILD, src/v/redpanda/application.cc, tests/rptest/tests/cluster_config_test.py, tests/rptest/tests/datalake/rest_catalog_connection_test.py, tests/setup.py
Added logic responsible for instantiating Iceberg REST catalog together with corresponding configuration properties. 
- none
=> Integrating rest Iceberg catalog implementation in Redpanda

src/v/raft/configuration_bootstrap_state.h, src/v/raft/configuration_manager.cc, src/v/raft/configuration_manager.h, src/v/raft/consensus.cc, src/v/raft/consensus_utils.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/24002
=> [v24.2.x] r/consensus_utils: use chunked vector when extracting configurations

src/v/raft/configuration_bootstrap_state.h, src/v/raft/configuration_manager.cc, src/v/raft/configuration_manager.h, src/v/raft/consensus.cc, src/v/raft/consensus_utils.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/24002
=> [v24.1.x] r/consensus_utils: use chunked vector when extracting configurations

src/v/datalake/BUILD, src/v/datalake/record_multiplexer.cc, src/v/datalake/record_multiplexer.h, src/v/datalake/tests/record_multiplexer_test.cc
I have an upcoming change to plug schema management into the datalake workers. As a precursor, this change is required to route bad records as binary records, since now it's very easy for data with an unintentional magic 0 byte to land and for Redpanda to mistake it for confluent serde.
Longer term, we should make this expectation for confluent serde more explicit, and perhaps route invalid data to a separate table. But for now this is a stop-gap to get schema support working with the same code that works with non-structured data as well.
* none
=> datalake: write bad data as binary records

src/transform-sdk/go/transform/internal/testdata/CMakeLists.txt
Backport of PR https://github.com/redpanda-data/redpanda/pull/23978
=> [v24.2.x] transform-sdk/go/tests: remove -quiet flag

src/transform-sdk/go/transform/internal/testdata/CMakeLists.txt
Backport of PR https://github.com/redpanda-data/redpanda/pull/23978
=> [v24.1.x] transform-sdk/go/tests: remove -quiet flag

src/v/storage/BUILD, src/v/storage/CMakeLists.txt, src/v/storage/log_manager.cc, src/v/storage/log_manager.h, src/v/storage/log_manager_probe.cc, src/v/storage/log_manager_probe.h, tests/rptest/tests/full_disk_test.py
=> storage: housekeeping metrics

src/v/cluster/metrics_reporter.cc, src/v/cluster/metrics_reporter.h, tests/rptest/tests/metrics_reporter_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/24004
=> [v24.2.x] metrics: Add list of enterprise features to call-home POST

src/v/cluster/metrics_reporter.cc, src/v/cluster/metrics_reporter.h, tests/rptest/tests/metrics_reporter_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/24004 
Fixes https://github.com/redpanda-data/redpanda/issues/24011
=> [v24.1.x] metrics: Add list of enterprise features to call-home POST

src/v/cluster/metrics_reporter.cc, src/v/cluster/metrics_reporter.h, tests/rptest/tests/metrics_reporter_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/24023
Fixes: CORE-8173
=> [v24.2.x] [CORE-8141] Add host information to metrics report

src/v/redpanda/application.cc
Only should happen once at brokers startup but gives visibility into sequence of events.
* none
=> app/log: bump log line's level to info

README.md
Add a note about bazelisk
* none
=> readme: Add note about bazelisk

src/v/storage/BUILD, src/v/storage/CMakeLists.txt, src/v/storage/log_manager.cc, src/v/storage/log_manager.h, src/v/storage/log_manager_probe.cc, src/v/storage/log_manager_probe.h, tests/rptest/tests/full_disk_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/24007 
Fixes #24036
=> [v24.2.x] storage: housekeeping metrics

.bazelrc, bazel/thirdparty/krb5.BUILD
=> bazel: fix building krb5 with sanitizers

src/v/redpanda/application.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/24033
=> [v24.2.x] app/log: bump log line's level to info

src/v/storage/CMakeLists.txt, src/v/storage/log_manager.cc, src/v/storage/log_manager.h, src/v/storage/log_manager_probe.cc, src/v/storage/log_manager_probe.h, tests/rptest/tests/full_disk_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/24007 
Fixes #24035
=> [v24.1.x] storage: housekeeping metrics

tests/rptest/services/apache_iceberg_catalog.py, tests/rptest/tests/datalake/datalake_e2e_test.py, tests/rptest/tests/datalake/iceberg_rest_catalog_smoke_test.py, tests/rptest/tests/datalake/rest_catalog_connection_test.py, tests/rptest/tests/datalake/spark_sql_server_smoke_test.py, tests/rptest/tests/datalake/trino_smoke_test.py, tests/rptest/tests/datalake/utils.py, tests/rptest/tests/polaris_catalog_smoke_test.py
Fixes https://redpandadata.atlassian.net/browse/CORE-8154
* none
=> datalake: limit datalake tests to s3

src/v/raft/consensus.cc, src/v/raft/heartbeat_manager.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/23916 
Fixes https://github.com/redpanda-data/redpanda/issues/23929
=> [v23.3.x] Fix ghost node handling in raft heartbeats

tests/rptest/tests/cloud_storage_timing_stress_test.py
The test seems to be flaky especially on Azure. The check itself racy
for an active partition. Instead, do the next best thing: assert the
size matches at the end of the test.
The failure is easy to reproduce (10 out of 10) by introducing some
delays which are present when testing against a real cloud storage
backend:
```
diff --git a/tests/rptest/tests/cloud_storage_timing_stress_test.py b/tests/rptest/tests/cloud_storage_timing_stress_test.py
index f78c21472d..fb92881b96 100644
--- a/tests/rptest/tests/cloud_storage_timing_stress_test.py
+++ b/tests/rptest/tests/cloud_storage_timing_stress_test.py
@@ -59,9 +59,13 @@ def cloud_storage_usage_check(test):
test.logger.debug(
f"Cloud log usage inferred from manifests: {manifest_usage}")
+            time.sleep(1)
+
reported_usage = …
```
=> rptest: verify cloud storage usage report only at the end of the test

src/v/cluster/topics_frontend.cc, src/v/kafka/server/tests/alter_config_test.cc
This PR implements license enforcement sanctions on schema ID validation, on the alter configs path.
Sanctioned alter config actions:
- Enabling schema ID validation
- Changing the subject name strategy while validation is enabled
Still allowed:
- Disabling schema ID validation
Includes updated fixture tests for these cases.
There is an edge case with regard to enabling key vs value validation. followup to address it staged here: https://github.com/redpanda-data/redpanda/pull/24107
TODO:
- It's a real error [debug-build](https://buildkite.com/redpanda/redpanda/builds/57862#01930de4-851d-4eca-b7cb-268c05664493)
- It was a bad optional access that asan was picking up as stack-use-after-return. After disabling that check the root cause was pretty obvious - if the topic doesn't exist, we …
=> [CORE-8102] c/topics: Sanctions for schema ID validation (alter config)

src/go/rpk/pkg/cli/connect/connect.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/24068
=> [v24.2.x] rpk connect: show rpk help text with --help/-h

tests/rptest/tests/data_migrations_api_test.py
Test stability improvements:
- allow legit errors in log
- fix an incorrect validate_topic_access check and refactor its interface
- ignore topic describe errors where we only describe for logging, as finjector can make them fail
* none
=> Migrations test fixes

src/v/cluster/rm_partition_frontend.cc, src/v/cluster/tm_stm.cc, src/v/cluster/tm_stm.h
Previously logic in tm_stm verified if the transaction was removed from
the transactions map after it was replicated. This logic caused a lot of
spurious warning logs and was very hard to understand. Additionally the
check is not required as now all the updates of the transactions cache
are replicated. Simplified the logic by skipping the check of the
transaction cache when replicating transaction tombstone. This way a
warning message will only be logged when the regular transaction state
update refers to not existing transaction.
- none
=> Refactored error handling when expiring transactions

src/v/cluster/rm_partition_frontend.cc, src/v/cluster/tm_stm.cc, src/v/cluster/tm_stm.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/24123
=> [v24.2.x] Refactored error handling when expiring transactions

tests/rptest/tests/write_caching_test.py
=> rptest: wait for 3 replicas before verifying config

tests/rptest/tests/controller_availability_test.py
https://redpandadata.atlassian.net/issues/CORE-3243
In an ideal world with no network or app latency this configuration is guaranteed to re-elect raft0 leader in 9.75s. In reality in may be slightly above 10s, which makes test fail. This is to bump it till 15s.
* none
=> tests/controller_availability: increase timeout

src/v/kafka/server/tests/BUILD, src/v/kafka/server/tests/list_offsets_test.cc, src/v/kafka/server/tests/metadata_test.cc, src/v/kafka/server/tests/produce_consume_test.cc, src/v/kafka/server/tests/quota_manager_test.cc, src/v/kafka/server/tests/topic_properties_helpers.h
Fixes: CORE-7511
Fixes: CORE-7528
Fixes: CORE-7529
Fixes: CORE-7526
Fixes: CORE-7531
Fixes: CORE-7506
Fixes: CORE-7496
Fixes: CORE-7495
Fixes: CORE-7497
Fixes: CORE-7514
Fixes: CORE-7509
Fixes: CORE-7524
Fixes: CORE-7501
Fixes: CORE-7516
Fixes: CORE-7493
Fixes: CORE-7530
Fixes: CORE-7499
Fixes: CORE-7507
Fixes: CORE-7512
Fixes: CORE-7527
Fixes: CORE-7504
Fixes: CORE-7508
Fixes: CORE-7518
Fixes: CORE-7525
Fixes: CORE-7515
Fixes: CORE-7523
Fixes: CORE-7494
* none
=> kafka: add server bazel tests

.github/pull_request_template.md
=> gh: Updated PR template for v24.3.x backports

src/v/features/feature_table.cc, tests/rptest/tests/rpk_cluster_test.py
=> license: Reduced evaluation period to 30 days

src/v/iceberg/catalog.h, src/v/iceberg/filesystem_catalog.cc, src/v/iceberg/filesystem_catalog.h, src/v/iceberg/rest_catalog.cc, src/v/iceberg/rest_catalog.h, src/v/iceberg/rest_client/catalog_client.cc, src/v/iceberg/rest_client/catalog_client.h
=> Iceberg: `drop_table` implementation for REST catalog

src/v/iceberg/catalog.h, src/v/iceberg/filesystem_catalog.cc, src/v/iceberg/filesystem_catalog.h, src/v/iceberg/rest_catalog.cc, src/v/iceberg/rest_catalog.h, src/v/iceberg/rest_client/catalog_client.cc, src/v/iceberg/rest_client/catalog_client.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/24160
=> [v24.3.x] Iceberg: `drop_table` implementation for REST catalog

src/v/kafka/server/protocol_utils.cc, src/v/kafka/server/protocol_utils.h, src/v/net/connection.cc, src/v/net/types.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/24110
=> [v24.1.x] fix "Unexpected EOF" log errors

src/v/kafka/server/protocol_utils.cc, src/v/kafka/server/protocol_utils.h, src/v/net/connection.cc, src/v/net/include/net/types.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/24110
=> [v24.2.x] fix "Unexpected EOF" log errors

src/v/kafka/server/protocol_utils.cc, src/v/kafka/server/protocol_utils.h, src/v/net/connection.cc, src/v/net/types.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/24110
=> [v24.3.x] fix "Unexpected EOF" log errors

tests/rptest/services/redpanda.py
In order to enable stress fiber run ducktape test with `ENABLE_STRESS_FIBER=ON` env var. The number of stress fiber can be controlled via `NUM_STRESS_FIBERS` env var. `STRESS_FIBER_MIN_MS` and `STRESS_FIBER_MAX_MS` are controlling the duration of the reactor stall produced by stress fiber.
It goes without saying that all this stress fiber business is turned off by default. 
Enabled by https://github.com/redpanda-data/vtools/pull/3318
* none
=> rptest: Start stress fiber in any test

src/v/cluster/tm_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/24180
=> [v24.3.x] tm_stm: fixed use after move in tm_stm

src/v/datalake/BUILD, src/v/datalake/CMakeLists.txt, src/v/datalake/schema_parquet.cc, src/v/datalake/serde_parquet_writer.cc, src/v/datalake/serde_parquet_writer.h, src/v/datalake/tests/BUILD, src/v/datalake/tests/serde_parquet_writer_test.cc, src/v/datalake/translation/partition_translator.cc, src/v/serde/parquet/CMakeLists.txt, tests/rptest/services/redpanda.py, tests/rptest/tests/datalake/datalake_e2e_test.py, tests/rptest/tests/datalake/rest_catalog_connection_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/24136
=> [v24.3.x] Added ability to use datalake with `serde::parquet`

src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/vote_stm.cc, src/v/raft/vote_stm.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/21361
=> [v24.2.x] Guard from concurrent elections

tests/rptest/services/redpanda.py, tests/rptest/tests/cluster_config_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/24186
=> [v24.1.x] dt/config_test: Add OIDC_ALLOW_LIST

src/v/iceberg/rest_catalog.cc, src/v/iceberg/rest_client/catalog_client.cc, src/v/iceberg/rest_client/catalog_client.h, src/v/iceberg/rest_client/entities.cc, src/v/iceberg/rest_client/entities.h, src/v/iceberg/table_requests.h, src/v/iceberg/table_requests_json.cc, src/v/iceberg/table_requests_json.h, tests/rptest/tests/datalake/rest_catalog_connection_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/24190
=> [v24.3.x] iceberg: create namespace on demand

tests/rptest/services/redpanda.py, tests/rptest/tests/cluster_config_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/24186
=> [v24.3.x] dt/config_test: Add OIDC_ALLOW_LIST

tests/rptest/services/redpanda.py, tests/rptest/tests/cluster_config_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/24186
=> [v24.2.x] dt/config_test: Add OIDC_ALLOW_LIST

tests/rptest/services/redpanda.py
=> rptest: validate the shape of node_config_overrides

src/v/cloud_storage/inventory/tests/BUILD, src/v/cloud_storage/inventory/tests/inv_svc_tests.cc, src/v/cloud_storage/tests/BUILD, src/v/cloud_storage/tests/cloud_storage_e2e_test.cc, src/v/cloud_storage/tests/delete_records_e2e_test.cc, src/v/cloud_storage/tests/produce_utils.h, src/v/cloud_storage/tests/read_replica_e2e_fixture.h, src/v/cloud_storage/tests/read_replica_test.cc, src/v/cloud_storage/tests/remote_partition_test.cc, src/v/cloud_storage/tests/remote_test.cc, src/v/cloud_storage/tests/topic_manifest_downloader_test.cc, src/v/cloud_storage/tests/topic_namespace_override_recovery_test.cc, src/v/cloud_storage/tests/util.cc, src/v/cluster/cloud_metadata/tests/BUILD, src/v/cluster/tests/BUILD, src/v/kafka/server/tests/BUILD, src/v/test_utils/BUILD
Fixes: CORE-7360
Fixes: CORE-7361
Fixes: CORE-7364
Fixes: CORE-7362
Fixes: CORE-7363
Fixes: CORE-7386
Fixes: CORE-7383
Fixes: CORE-7381
Fixes: CORE-7372
Fixes: CORE-7376
Fixes: CORE-7374
Fixes: CORE-7385
Fixes: CORE-7366
Fixes: CORE-7365
Fixes: CORE-7370
Fixes: CORE-7380
Fixes: CORE-7384
Fixes: CORE-7373
* none
=> cloud_storage: add bazel tests

src/v/archival/archival_metadata_stm.cc, src/v/archival/tests/archival_metadata_stm_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/24210
=> [v24.2.x] [CORE-8010] cluster: Fix race condition in the `archival_metadata_stm`

src/v/cluster/archival/archival_metadata_stm.cc, src/v/cluster/archival/tests/archival_metadata_stm_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/24210
=> [v24.3.x] [CORE-8010] cluster: Fix race condition in the `archival_metadata_stm`

src/v/datalake/fwd.h, src/v/datalake/record_multiplexer.cc, src/v/datalake/record_multiplexer.h, src/v/datalake/record_translator.cc, src/v/datalake/record_translator.h, src/v/datalake/table_definition.cc, src/v/datalake/tests/BUILD, src/v/datalake/tests/gtest_record_multiplexer_test.cc, src/v/datalake/tests/record_multiplexer_test.cc, src/v/datalake/tests/translation_task_test.cc, src/v/datalake/translation/partition_translator.cc, src/v/datalake/translation/partition_translator.h, src/v/datalake/translation_task.cc, src/v/datalake/translation_task.h, tests/rptest/tests/datalake/datalake_e2e_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/24220
=> [v24.3.x] datalake: split record translator into distinct modes 

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/datalake/coordinator/BUILD, src/v/datalake/coordinator/state.cc, src/v/datalake/coordinator/state.h, src/v/datalake/coordinator/state_machine.cc, src/v/datalake/coordinator/state_machine.h, src/v/datalake/coordinator/tests/BUILD, src/v/datalake/coordinator/tests/CMakeLists.txt, src/v/datalake/coordinator/tests/coordinator_test.cc, src/v/datalake/coordinator/tests/state_machine_test.cc, src/v/datalake/coordinator/tests/state_test_utils.h, src/v/datalake/coordinator/types.h, src/v/raft/persisted_stm.h, tests/rptest/tests/datalake/coordinator_retention_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/24174
=> [v24.3.x] datalake/coordinator: snapshots

src/v/cluster/scheduling/partition_allocator.cc, src/v/cluster/scheduling/partition_allocator.h, src/v/cluster/scheduling/types.cc, src/v/cluster/scheduling/types.h, src/v/cluster/tests/partition_allocator_fixture.h, src/v/cluster/tests/partition_allocator_tests.cc, src/v/cluster/topics_frontend.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/24135
=> [v24.3.x] [CORE-7750] Creating topic with huge number of partitions leads to segfault

CONTRIBUTING.md
As per [slack discussion](https://redpandadata.slack.com/archives/C044RD18NMV/p1732123426157609), allowing up to 72 characters in commit subject line, not only in the commit message body. The number was chosen because Github wraps at 72.
* none
=> CONTRIBUTING.md: allow longer commit subject lines

src/v/config/configuration.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/24184
=> [v24.2.x] rpc: Change max internal rpc connection count limit

src/v/config/configuration.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/24184
=> [v24.3.x] rpc: Change max internal rpc connection count limit

tests/rptest/services/apache_iceberg_catalog.py
=> rptest/s: use abfss (secure) scheme for iceberg catalog

src/v/cluster/cluster_utils.cc, src/v/redpanda/admin/debug.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/23458
=> [v24.1.x] admin: fix copy paste mistake leading to incorrect value for max_collectible_offset

src/v/iceberg/metadata_io.h, src/v/iceberg/rest_client/BUILD, src/v/iceberg/rest_client/catalog_client.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/24225
=> [v24.3.x] iceberg: couple miscellaneous fixes found in prolonged testing

tests/rptest/tests/topic_delete_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/24245
=> [v24.2.x] [CORE-8249] Allow more time for segment clean up

tests/rptest/tests/topic_delete_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/24245
=> [v24.3.x] [CORE-8249] Allow more time for segment clean up

src/v/cluster/data_migration_frontend.cc, src/v/cluster/data_migration_table.cc, src/v/cluster/data_migration_types.cc, src/v/cluster/data_migration_types.h, src/v/redpanda/admin/api-doc/migration.def.json, src/v/redpanda/admin/migrations.cc, tests/rptest/tests/data_migrations_api_test.py
When a migration is created remember the time it happened, and similarly when it reaches finished* or cancelled state. 
`*` -- when using high level API the migration will be deleted as soon as it reaches finished state.
Output these in GET requests.
* none
=> Save and show creation and completion time in migrations

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/datalake/coordinator/BUILD, src/v/datalake/coordinator/catalog_factory.cc, src/v/datalake/coordinator/catalog_factory.h, src/v/datalake/coordinator/coordinator_manager.cc, src/v/datalake/coordinator/coordinator_manager.h, src/v/datalake/datalake_manager.cc, src/v/datalake/datalake_manager.h, src/v/datalake/fwd.h, src/v/redpanda/application.cc, tests/docker/ducktape-deps/polaris, tests/rptest/services/polaris_catalog.py, tests/rptest/services/templates/polaris-server.yml, tests/rptest/tests/polaris_catalog_smoke_test.py
Allowing Redpanda to connect to TLS secured REST Catalog.
- none
=> Support TLS in datalake rest catalog

src/v/cluster/cloud_metadata/tests/cluster_recovery_backend_test.cc, src/v/cluster/partition_manager.cc, src/v/cluster/partition_manager.h, src/v/model/BUILD, src/v/model/ktp.h, src/v/ssx/BUILD, src/v/ssx/async-clear.h, src/v/storage/log_manager.cc, src/v/storage/log_manager.h, src/v/transform/rpc/tests/transform_rpc_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/24193
=> [v24.3.x] Avoid some oversized allocs at high partition density

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/datalake/coordinator/BUILD, src/v/datalake/coordinator/catalog_factory.cc, src/v/datalake/coordinator/catalog_factory.h, src/v/datalake/coordinator/coordinator_manager.cc, src/v/datalake/coordinator/coordinator_manager.h, src/v/datalake/datalake_manager.cc, src/v/datalake/datalake_manager.h, src/v/datalake/fwd.h, src/v/redpanda/application.cc, tests/docker/ducktape-deps/polaris, tests/rptest/services/polaris_catalog.py, tests/rptest/services/templates/polaris-server.yml, tests/rptest/tests/polaris_catalog_smoke_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/24226
=> [v24.3.x] Support TLS in datalake rest catalog

src/v/pandaproxy/probe.cc, src/v/pandaproxy/schema_registry/store.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/23794
=> [v24.3.x] schema_registry: Add metrics

src/v/datalake/BUILD
datalake: add missing bazel dep
* none
=> datalake: add missing bazel dep

src/go/rpk/pkg/adminapi/admin.go, src/go/rpk/pkg/adminapi/admin_test.go, src/go/rpk/pkg/cli/cluster/license/BUILD, src/go/rpk/pkg/cli/cluster/license/info.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/24264
=> [v24.3.x] rpk: license warning text changes.

tests/rptest/services/redpanda_connect.py, tests/rptest/tests/redpanda_connect_test.py
Added basic tooling to run Redpanda Connect in ducktape.
- none
=> Redpanda Connect in ducktape

src/v/pandaproxy/probe.cc, src/v/pandaproxy/schema_registry/store.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/23794
=> [v24.2.x] schema_registry: Add metrics

tests/rptest/tests/alter_topic_configuration_test.py
The test is running with mixed version RP and fips require virtual host style paths to be enabled.
* none
=> [CORE-8345] rptest: Disable fips in one of the upgrade tests

src/v/cluster/BUILD, src/v/cluster/feature_manager.cc, src/v/cluster/partition_balancer_backend.cc, src/v/cluster/scheduling/leader_balancer.cc, src/v/cluster/security_frontend.cc, src/v/cluster/shard_balancer.cc, src/v/cluster/topics_frontend.cc, src/v/config/BUILD, src/v/config/property.h, src/v/features/BUILD, src/v/features/enterprise_feature_messages.h, src/v/kafka/server/BUILD, src/v/kafka/server/handlers/fetch.cc, src/v/kafka/server/server.cc, src/v/kafka/server/tests/alter_config_test.cc, src/v/kafka/server/tests/create_partition_test.cc, src/v/kafka/server/tests/create_topics_test.cc, src/v/redpanda/admin/BUILD, src/v/redpanda/admin/security.cc, src/v/redpanda/admin/server.cc, src/v/redpanda/admin/server.h, tests/rptest/services/redpanda.py, tests/rptest/tests/audit_log_test.py, tests/rptest/tests/rbac_test.py, tests/rptest/tests/rbac_upgrade_test.py, tests/rptest/tests/redpanda_kerberos_test.py, tests/rptest/tests/redpanda_oauth_test.py, tests/rptest/tests/redpanda_startup_test.py, tests/rptest/tests/schema_registry_test.py, tests/rptest/tests/workload_license.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/24261
Fixes https://github.com/redpanda-data/redpanda/pull/24279
=> [v24.3.x] [CORE 8273] Adjust license warning text to include trial license links

src/v/kafka/data/CMakeLists.txt, src/v/kafka/data/test/CMakeLists.txt
Backport of PR https://github.com/redpanda-data/redpanda/pull/24275
=> [v24.3.x] k/data: Add CMakeLists for record_batcher test

src/v/storage/disk_log_appender.cc, src/v/storage/disk_log_impl.cc, src/v/storage/tests/storage_e2e_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/21324
Fixes: https://github.com/redpanda-data/redpanda/issues/24280,
=> [v24.3.x] Fixed race condition in `disk_log_impl::truncate_prefix`

src/v/cloud_storage/cache_service.h, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/tests/cloud_storage_fixture.h, src/v/cloud_storage/tests/remote_segment_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/24265
=> [v24.2.x] [CORE-7257] cloud_storage: Remove assertion in `remote_segment`

src/v/cloud_io/remote.cc, tests/docker/ducktape-deps/spark, tests/java/spark-iceberg-dependencies/pom.xml, tests/rptest/context/cloud_storage.py, tests/rptest/services/apache_iceberg_catalog.py, tests/rptest/services/spark_service.py, tests/rptest/services/trino_service.py, tests/rptest/tests/datalake/datalake_e2e_test.py, tests/rptest/tests/datalake/utils.py
Tests which use apache iceberg rest catalog with file system catalog are failing due to missing dependencies. Will fix in a later PR.
* none
=> datalake: gcs support

tests/rptest/tests/full_disk_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23550
=> [v24.1.x] rptest: increase threshold for test_full_disk_triggers_gc

src/v/cluster/data_migration_frontend.cc, src/v/cluster/data_migration_table.cc, src/v/cluster/data_migration_types.cc, src/v/cluster/data_migration_types.h, src/v/redpanda/admin/api-doc/migration.def.json, src/v/redpanda/admin/migrations.cc, tests/rptest/tests/data_migrations_api_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/24142
=> [v24.3.x] Save and show creation and completion time in migrations

src/v/iceberg/filesystem_catalog.cc, src/v/iceberg/table_io.cc, src/v/iceberg/table_io.h, src/v/iceberg/tests/filesystem_catalog_test.cc, tests/rptest/tests/datalake/datalake_e2e_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/24299
=> [v24.3.x] iceberg: add simple drop_table support for filesystem_catalog

src/v/datalake/coordinator/coordinator.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/24315
=> [v24.3.x] d/coordinator: fixed possible iterator generation mismatch

src/v/cloud_io/remote.cc, tests/docker/ducktape-deps/spark, tests/java/spark-iceberg-dependencies/pom.xml, tests/rptest/context/cloud_storage.py, tests/rptest/services/apache_iceberg_catalog.py, tests/rptest/services/spark_service.py, tests/rptest/services/trino_service.py, tests/rptest/tests/datalake/datalake_e2e_test.py, tests/rptest/tests/datalake/utils.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/24298
=> [v24.3.x] datalake: gcs support

src/v/datalake/record_multiplexer.cc, src/v/datalake/record_multiplexer.h, src/v/datalake/record_schema_resolver.cc, src/v/datalake/record_schema_resolver.h, src/v/datalake/record_translator.cc, src/v/datalake/record_translator.h, src/v/datalake/tests/gtest_record_multiplexer_test.cc, src/v/model/record.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/24288
=> [v24.3.x] Misc fixes for Datalake data path

src/v/storage/disk_log_impl.cc, src/v/storage/tests/storage_e2e_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/24306
=> [v24.3.x] Fixed race condition between appends and prefix truncation

src/v/cluster/partition_probe.cc, src/v/cluster/partition_probe.h, src/v/datalake/coordinator/coordinator.cc, src/v/datalake/coordinator/coordinator.h, src/v/datalake/coordinator/frontend.cc, src/v/datalake/coordinator/tests/coordinator_test.cc, src/v/datalake/coordinator/tests/state_machine_test.cc, src/v/datalake/coordinator/types.h, src/v/datalake/translation/partition_translator.cc, src/v/datalake/translation/partition_translator.h, tests/rptest/tests/datalake/datalake_e2e_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/24305
=> [v24.3.x] datalake/metrics: lag metrics

src/v/iceberg/tests/CMakeLists.txt
=> cmake: remove duplicate arguments as these are implict for bench

src/v/iceberg/tests/CMakeLists.txt
Backport of PR https://github.com/redpanda-data/redpanda/pull/24337
=> [v24.3.x] cmake: remove duplicate arguments as these are implict for bench

tests/rptest/redpanda_cloud_tests/omb_validation_test.py
Adds write caching to cloud tier OMB validation tests.
* none
=> Add write caching to OMB validation tests

src/v/cluster/partition_balancer_planner.cc
It may happen that when collecting topic replica counts per node the topic, which is taken into account during planning partition moves did not exist. In this case balancer planner should throw an exception indicating concurrent modification. This will allow  backend to retry the planning operation.
- none
=> c/balancer_planner: check if topic exists in node count map

tests/java/iceberg-rest-catalog/build.gradle, tests/rptest/services/apache_iceberg_catalog.py
=> rptest/s: apache iceberg rest catalog with fs mode on gcp

src/v/cluster/archival/ntp_archiver_service.cc
The 'cache::put' method can throw 'nested_exception' during the shutdown. The 'ntp_archiver' now handles nested exception and if both inner and outer exceptions are shutdown exceptions the error is not logged and we're returning correct error code (canceled).
The code inside `cache::put` uses `fianlly` to close the stream. During the shutdown both the coroutine and a continuation may throw a shutdown error and we will get a nested exception. 
* none
=> [CORE-6936] archival: Handle nested shutdown errors

tests/docker/Dockerfile, tests/docker/ducktape-deps/client-swarm, tests/docker/ducktape-deps/rp-storage-tool
Backport of PR https://github.com/redpanda-data/redpanda/pull/24334
=> [v24.3.x] tests/docker: increase cargo retry and verbosity

MODULE.bazel.lock, bazel/repositories.bzl
Updated to use Seastar commit with error stack clearing fix
* None
=> bazel: Updated Seastar commit

src/v/cluster/archival/ntp_archiver_service.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/24341
=> [v24.3.x] [CORE-6936] archival: Handle nested shutdown errors

src/v/cluster/topic_table.cc, src/v/datalake/coordinator/iceberg_file_committer.cc, src/v/datalake/coordinator/tests/iceberg_file_committer_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/24339
=> [v24.3.x] datalake: make purging table idempotent

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/23274
=> [v24.1.x] rptest: Enable scrubber only if not explicitly disabled

src/v/cluster/archival/async_data_uploader.cc, src/v/storage/disk_log_impl.cc
Pull requests in a series:
- https://github.com/redpanda-data/redpanda/pull/21309
- https://github.com/redpanda-data/redpanda/pull/21409
- https://github.com/redpanda-data/redpanda/pull/23322
This PR extends segment index lookup. Previously, `find_above_size_bytes` method was only taking into account the `distance` parameter during the lookup. This PR adds a second optional parameter that allows the caller to pass the max log offset. The functionality is supposed to be used by the uploader to constrain the upload candidate search by LSO.
* none
=> archival: Update ntp_archiver (pt.4)

src/v/cluster/partition_balancer_planner.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/24336
=> [v24.3.x] c/balancer_planner: check if topic exists in node count map

src/v/utils/tracking_allocator.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/23511
=> [v24.1.x] utils: fix container-overflow in tracking allocator

tests/rptest/redpanda_cloud_tests/config_profile_verify_test.py
Changes the node list command for Azure to one that works properly on larger (tier-4, tier-5) BYOC clusters.
Updates variable names to be less cryptic and more self-explanatory.
* none
=> [rptest] clean up ConfigProfileVerifyTest

src/v/config/configuration.cc
Update the doc string for the partition memory, fd and per-shard limits to clarify:
1. That it's a cluster-wide limit
2. That it applies at topic creation time
3. That it counts partiton _replicas_ not partitions
* none
=> Update config doc for partition limits

tests/rptest/scale_tests/many_clients_test.py
Added idempotent producers to many clients test. This way a test will execute idempotent produce related code paths. 
- none
=> tests/many_clients: run many clients test with idempotent producers

src/v/raft/BUILD, src/v/raft/CMakeLists.txt, src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/follower_stats.cc, src/v/raft/group_configuration.cc, src/v/raft/group_configuration.h, src/v/raft/group_manager.cc, src/v/raft/replicate_entries_stm.cc, src/v/raft/tests/basic_raft_fixture_test.cc, src/v/raft/types.h, src/v/raft/vote_stm.cc, src/v/raft/vote_stm.h, src/v/raft/voter_priority_tracker.cc, src/v/raft/voter_priority_tracker.h
We should always prefer an availability over the governance to the maintenance mode rules. 
- none
=> r/consensus: do not block leadership completely in maintenance mode
