redpanda-data/redpanda

tests/docker/ducktape-deps/tinygo-wasi-transforms

Retry tinygo, it sometimes fails due to https://github.com/tinygo-org/tinygo/issues/4206
* none

ducktape: retry tinygo

---

tests/rptest/tests/audit_log_test.py

After investigation its been determined that the failure isn't really an indication of auditing not working properly.
The test verifies that on shutdown all stop application_lifecycle messages are observed, and during shutdown there is a short grace period in which shutdown will be held until these messages can be successfully produced, however there is no guarantee that the produce will succeed as shutdown is random and it may be the case that nodes that host the audit partition to produce to have already been shutdown.
Therefore the produce fails after the grace period and the message fails to make it to the audit log, making the test fail.
A potential fix is to have the audit log subsystem be partition agnostic when producing messages, but this means it must have the ability to …

tests: Marking test_drain_audit_disabled as ok_to_fail

---

cmake/dependencies.cmake
src/v/wasm/tests/wasm_transform_test.cc
src/v/wasm/wasmtime.cc

Currently trying to take a backtrace while the CPU profiler is running
results in a deadlock, because taking a backtrace segfaults, as we don't
write any debug symbols during JIT compilation (which causes other
deadlocks in libgcc). To fix this, disable the profile's backtracing
when within Wasm. In the future we should use Wasmtime's profiling APIs
to get a stacktrace within the guest program that is running. For more
information on that API see:
https://docs.wasmtime.dev/api/wasmtime/struct.GuestProfiler.html
FIXES: CORE-486
* Fixes an issue where using the CPU profiler with running Data Transforms could cause the process to deadlock.

wasm: fix CPU profiler deadlock

---

src/v/cloud_roles/refresh_credentials.cc
src/v/compat/tests/compat_test.cc
src/v/kafka/server/replicated_partition.h
src/v/kafka/server/tests/CMakeLists.txt
src/v/kafka/server/tests/replicated_partition_test.cc
src/v/storage/tests/storage_e2e_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/17789
Backport of PR #17026
Fixes: https://github.com/redpanda-data/redpanda/pull/17881

[v23.2.x] k/replicated_partition: fixed querying end offset of an empty log

---

src/v/cluster/rm_stm.cc
src/v/cluster/rm_stm.h
tests/rptest/tests/transactions_test.py

fence_pid_epoch maps a producer id to its latest epoch. Current cleanup code does not do a epoch check before cleaning up the pid state. This can result in removing the state related to the latest epoch. Consider the following series of events..
[x, y] = pid[id=x, epoch=y]
[1, 0] begin_tx - fence_pid_epoch[1] = 0
[1, 1] begin_tx - fence_pid_epoch[1] = 1
evict [1, 0]
erase(fence_pid[1]) ==> removes (1)
This results in a messed up state stalling the state of the transaction because the partition cannot make progress until it verifies the epoch.
This is a long pending bug that was exposed by racy evictions.
note: this whole code is going to be revamped soon and the plan is to add a self contained unit test fixture that supports transactions end-to-end, that should have better test coverage. …

[backport] [v23.3.x] rm_stm: fix fence_pid_epoch cleanup #17880

---

src/v/cloud_storage/tests/cloud_storage_e2e_test.cc
src/v/cluster/controller_api.cc
src/v/cluster/feature_manager.cc
src/v/cluster/health_monitor_backend.cc
src/v/cluster/health_monitor_backend.h
src/v/cluster/health_monitor_types.cc
src/v/cluster/health_monitor_types.h
src/v/cluster/metrics_reporter.cc
src/v/cluster/partition_balancer_backend.cc
src/v/cluster/partition_balancer_backend.h
src/v/cluster/partition_balancer_planner.cc
src/v/cluster/partition_leaders_table.cc
src/v/cluster/partition_leaders_table.h
src/v/cluster/scheduling/leader_balancer.cc
src/v/cluster/service.cc
src/v/cluster/tests/health_bench.cc
src/v/cluster/tests/health_monitor_test.cc
src/v/cluster/tests/partition_balancer_planner_fixture.h
src/v/cluster/tests/partition_balancer_planner_test.cc
src/v/cluster/tests/partition_balancer_simulator_test.cc
src/v/cluster/tests/randoms.h
src/v/cluster/tests/serialization_rt_test.cc
src/v/cluster/topics_frontend.cc
src/v/compat/cluster_json.h
src/v/redpanda/admin/server.cc

Every time the `health_monitor_backend::get_cluster_health` was called we returned a copy of each node health report. The health report data structure maybe large as it contains all partition replica information.
To reduce the number of copies while still not interrupting asynchronous iteration over the health report changed the API to return a list of shared pointers.
Node health reports aren't modified in place by health monitor backend rather than that they are completely replaced. This makes it easy to share the underlying data without worrying about concurrent access.
- largely reduced number of health report copies

c/health: reduced number of health_node_report copies

---

src/v/storage/key_offset_map.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/17879
Fixes: https://github.com/redpanda-data/redpanda/issues/17887,

[v23.3.x] CORE-2365: storage: increase size of offset key map fragment size

---

src/v/archival/ntp_archiver_service.cc
src/v/cloud_storage_clients/s3_client.cc
tests/rptest/tests/cloud_storage_scrubber_test.py

Currently, the housekeeping jobs are enabled in the 'start' method. First the 'sync' method of the archival metadata stm is called. We don't check the result of the 'sync' call which is a mistake. Normally, we're calling 'start' method of the 'ntp_archiver' when the partition is already a leader so this code works as expected. But if the partition is moved to another shard we could potentially create and start archiver when the partition is not a leader yet. In this case the 'sync' call returns 'nullopt'. The housekeeping jobs are not enabled because _parent.is_leader() returns 'false' in this case.
Then, when the partition becomes a leader the 'notify_leadership' method is invoked. This method enables the housekeeping jobs. The problem is that the 'sync' method of the archival STM may …

archival: Start housekeeping jobs only on a leader

---

tests/rptest/tests/audit_log_test.py

Fixes: https://github.com/redpanda-data/redpanda/issues/17907
* none

Backport of PR 17894 - tests: Marking test_drain_audit_disabled as ok_to_fail

---

.github/CODEOWNERS

gh: Add docs team as CODEOWNERS for configs

---

src/v/kafka/protocol/logger.cc

Fixes: CORE-2409
* Reduces maximum log line size from `1MiB` to `128KiB` to reduce occurrences of memory allocation failures

kafka: Reduced maximum log line size to 128KiB

---

src/v/kafka/protocol/logger.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/17922

[v23.2.x] kafka: Reduced maximum log line size to 128KiB

---

src/v/kafka/protocol/logger.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/17922

[v23.3.x] kafka: Reduced maximum log line size to 128KiB

---

src/v/cluster/health_monitor_backend.cc

When report is collected by the fiber requesting current node health report it should be cached in the reports cache to prevent the next collection. Added caching of the current node health report.
- none

c/hm_backend: cache the collected report

---

tests/rptest/clients/types.py
tests/rptest/tests/random_node_operations_test.py

Tests day-2 ops in the presence of write caching topics.
* none

ducktape: add write caching to random_node_ops test

---

src/v/storage/log_manager.cc
src/v/storage/log_manager.h

Fixes the broken promise resulting from a race during shutdown.
Fixes https://github.com/redpanda-data/redpanda/issues/17614
* none

log_manager: gate orphan file cleanup

---

tests/rptest/tests/write_caching_fi_test.py

We have a wrapper RedpandaService.wait_until which is used to wait for
conditions as long as the cluster is "healthy". Healthy is defined as
all "started nodes" being up.
When we call signal_redpanda to kill a particular node on purpose. In
this case, we also need to remove the node from the started nodes list
otherwise the above check will trip thinking that a node is crashed or
something similar.
I have tried to add this logic inside the signal_redpanda method in
[https://github.com/redpanda-data/redpanda/pull/17889][1] but discovered that there are tests which rely on the
existing behavior already.
@bharathv noticed that stop_node can be used instead so this PR does
that.
Fixes https://github.com/redpanda-data/redpanda/issues/17886
[1]: …

rptest: remove node from started list after kill

---

tests/rptest/clients/kafka_cli_tools.py

KafkaCliTools.produce didn't work if SASL or TLS was enabled because
it failed to pass along the relevant configuration. This command does
not accept a config file via --command-config like many other cli tools
(this is how we pass this information to those tools), but it does
accept a --producer.config argument which serves the same purpose.
Set if additional security config needs to be passed in this way,
which fixes this test in the cloud.
Fixes https://github.com/redpanda-data/core-internal/issues/1256
* none

Fix KafkaCliTools.produce in cloud tests

---

src/v/rpc/transport.cc

The values of these metrics were reversed at some point. This PR switches them back.
* none

Fix rpc client [in, out]_bytes metrics

---

src/v/cloud_roles/apply_abs_credentials.h
src/v/cloud_roles/apply_abs_oauth_credentials.h
src/v/cloud_roles/apply_aws_credentials.h
src/v/cloud_roles/apply_gcp_credentials.h
src/v/cloud_roles/include/cloud_roles/apply_credentials.h
src/v/cloud_storage_clients/abs_client.cc
src/v/cloud_storage_clients/abs_client.h
src/v/cloud_storage_clients/configuration.cc
src/v/config/configuration.cc
src/v/config/configuration.h
src/v/redpanda/admin/server.cc
tests/rptest/tests/cluster_config_test.py

summary:
- tunable cluster property `cloud_storage_azure_hierarchical_namespace_enabled` optional<bool>. If set, will skip abs_client::self_configure and use the value of the property (set it to true if the azure_container has HNS enabled)
- if using oauth on azure (`cloud_storage_credentials_source= azure_aks_oidc_federation or azure_vm_instance_metadata`) , discover if HNS is enabled via [Set Blob Expiry endpoint](https://learn.microsoft.com/en-us/rest/api/storageservices/set-blob-expiry?tabs=microsoft-entra-id)
- bugfixes in configuration validation
HNS (Hierarchical Namespace) is an ABS feature that changes the behavior of some APIs, like deleting/listing.
The current implementation for ABS checks with [Get Account Information](https://learn.microsoft.com/en-us/rest/api/storageservices …

CORE-2369: Fix/azure managed identities hns detection

---

src/v/cluster/controller_backend.cc
src/v/cluster/tests/shard_placement_table_test.cc

In case when we need to wait before shard_placement_table and topic_table become consistent (i.e. the expected log_revision of an ntp is the same), the concept of "current operation" doesn't make much sense because we may not yet know what we are required to do for reconciliation. Therefore we shouldn't require the current_operation to be non-null after a reconciliation step returns an error.
* none

c/controller_backend: don't require cur_operation after reconciliation step

---

.clang-tidy
.clang-tidy-strict
.clang-tidy-strict-tests
CMakeLists.txt
src/v/archival/async_data_uploader.cc
src/v/cluster/service.cc
src/v/cluster/tests/partition_balancer_simulator_test.cc
src/v/cluster/topic_recovery_validator.cc

A variety of fixes so the OSS builds cleanly on clang-18
* none

cleanup: clang 18 fixes

---

tests/rptest/tests/connection_limits_test.py

ConnectionLimitsTest.test_exceed_broker_limit had a spurious failure in CI. This test starts 2 consumers which (should) consume all 6 available connections, then checks that a producer started after that fails to produce (due to connection limit being hit).
However the consumer & producer starts are all async, so the producer can race ahead of one of the consumers and grab the connections for itself, failing the test.
Change the test to wait for the consumers to connect, by waiting until the connection metric hits 6, then starts the producer.
Fixes #17897.
* none

rptest: fix test_exceed_broker_limit flake

---

src/v/cloud_roles/apply_abs_oauth_credentials.cc
src/v/cloud_roles/apply_abs_oauth_credentials.h
src/v/cloud_storage_clients/abs_client.cc
src/v/cloud_storage_clients/abs_client.h
src/v/redpanda/admin/server.cc
tests/rptest/tests/cluster_config_test.py

**abs_client::self_configure:**
Use Set Expiry header `x-ms-error-code:  HierarchicalNamespaceNotEnabled`  for a stricter check.
the current behavior is: HTTP 400 → HNS not enabled
with this PR:  HTTP 400 && `x-ms-error-code:  HierarchicalNamespaceNotEnabled`-> HNS not enabled
Otherwise, bubble up the error and let redpanda stop gracefully.
The escape hatch cloud_storage_azure_hierarchical_namespace_enabled can be used if this header response changes without notice. 
**apply_abs_oauth_credentials:**
add required header `x-ms-date`
https://learn.microsoft.com/en-us/rest/api/storageservices/delete-blob?tabs=microsoft-entra-id#request-headers 
ABS requires x-ms-date header, in our codebase is set by credential_applier and apply_abs_oauth_credentials does not set it.
Did not trigger errors in …

CORE-2452 followup for azure managed identities #17840

---

src/v/cloud_roles/apply_abs_oauth_credentials.h

Make the includes linter happy
* none

cloud_roles: fix includes

---

src/v/transform/api.cc

Let's make sure we start the log manager before we start loading Wasm
VMs. Probably not going to cause an issue, but just to be safe.
* none

transform: start loading VMs after logs are started

---

src/v/cloud_storage_clients/abs_client.cc

fixed a missing error_code_it != headers.end() check
Normally on Azure, the HTTP 400 error response has a `x-ms-error-code` header, so `headers.find("x-ms-error-code")->value()` is well-behaved, but it's not safe to not check the iterator before accessing it. 
Fixes CORE-2451
* none

CORE-2451 cloud_storage_clients/abs_clients: fix iterator check

---

src/v/wasm/README.md

wasm: add a README explaining the architecture of the Wasm subsystem

---

src/v/kafka/server/handlers/fetch.cc

We were formatting the ip and port of the client for each partition in
the fetch plan. This is unneeded as it obviously doesn't change by topic
or partition.
The formatting is fairly expensive and amounts for ~2-3% of total
reactor time in a high partition count scenario.
This could be further optimized by moving the formatted version to the
connection context to avoid having this copy alive many times but that's
a bit larger change for another PR.
Before:
After:
* none

fetch: Avoid formatting client ip and port for each partition

---

tests/rptest/redpanda_cloud_tests/high_throughput_test.py

Ignore test_cloud_cache_thrash to avoid wasting resources on a test which does nothing. See code comment for rationale.
* none

rptest: ignore test_cloud_cache_thrash

---

src/v/cluster/partition_balancer_planner.cc
src/v/cluster/scheduling/allocation_state.cc
src/v/cluster/scheduling/allocation_state.h
src/v/cluster/scheduling/partition_allocator.cc
src/v/cluster/scheduling/partition_allocator.h
src/v/cluster/scheduling/types.cc
src/v/cluster/scheduling/types.h
src/v/cluster/tests/partition_allocator_tests.cc
src/v/cluster/tests/partition_balancer_bench.cc
src/v/cluster/tests/partition_balancer_planner_fixture.h
src/v/cluster/tests/partition_balancer_simulator_test.cc
src/v/cluster/tests/topic_updates_dispatcher_test.cc
src/v/cluster/topics_frontend.cc
tests/rptest/tests/topic_creation_test.py

Previously, we allocated new replicas of a partition and rebalanced existing ones together - i.e. all replicas of a single partition one by one. This can lead to having some replica sets repeated over and over - and undesirable pattern because these nodes will replicate data mostly between each other.
To prevent this, allocate and rebalance replicas in true random order - a replica of partition P1, then a replica of partition P2, then maybe a replica of P1 again, etc.
Fixes https://github.com/redpanda-data/redpanda/issues/17925
* Allocate and rebalance partition replicas in random order to prevent an undesirable pattern when many partitions have the same replica set.

Allocate and rebalance replicas for different partitions in random order

---

src/v/kafka/server/handlers/fetch.cc
src/v/kafka/server/handlers/fetch.h

The `kafka_latency_fetch_latency` metric originally measured the time
it'd take to complete one fetch poll. A fetch poll would create a fetch
plan then execute it in parallel on every shard. On a given shard
`fetch_ntps_in_parallel` would account for the majority of the execution time
of the plan.
Since fetches are no longer implemented by polling there isn't an
exactly equivalent measurement that can be assigned to the metric.
This commit instead records the duration of the first call to
`fetch_ntps_in_parallel` on every shard to the metric. This first call takes
as long as it would during a fetch poll. Hence the resulting measurement
should be close to the duration of a fetch poll.
* Changes what the `kafka_latency_fetch_latency` metric measures to be the time the first …

Change the` kafka_latency_fetch_latency` metric 

---

src/v/config/configuration.cc
src/v/config/configuration.h
src/v/raft/consensus.cc
src/v/raft/consensus.h
src/v/raft/group_manager.cc
src/v/raft/group_manager.h
src/v/raft/tests/basic_raft_fixture_test.cc
src/v/raft/tests/raft_fixture.cc
src/v/raft/tests/raft_fixture.h
src/v/raft/tests/raft_group_fixture.h
src/v/raft/tests/replication_monitor_tests.cc
src/v/raft/tests/simple_raft_fixture.h
src/v/raft/vote_stm.cc
src/v/raft/vote_stm.h
src/v/redpanda/application.cc

Making Raft leader election unsuccessful if one of the votes has log which is more up to data than the current candidate. This solution will allow us to minimise the data loss risk when using relaxed consistency writes. With the optimisation included in this PR a candidate will wait up to election timeout for the replies from all of the nodes and will fail the leader election if any of the voters log is more up to date. The solution included in this PR favour the nodes with longest log to become a leader without compromising availability as it is still enough for the majority to vote for the candidate for it to become a leader. 
Another way of seeing this solution is that the candidate will use information about voter logs if they are available instead of ignoring the one with longest log …

Added detection of the node with longest log during leader election process

---

src/v/config/configuration.cc

v2 was enabled by default in https://github.com/redpanda-data/redpanda/pull/16441
Running the balancer doesn't do anything other than waste cpu cycles.
* none

[CORE-2400] kafka/server: Disable quota balancer

---

src/v/cluster/topic_table_partition_generator.cc

Topic table partition generator is a simple helper to asynchronously iterate over a topic table which may have a lot of elements. The generator validates if `topic_table` changed while the loop yield for the other tasks. The check was incorrect as it was validating the topic table revision which is updated after the snapshot is applied.
Fixed the issue by validating it `_topics_map_revision` changed during the scheduling point.
Fixes: #core-internal/1259
- fixed a problem leading to UAF error while calculating cloud stage usage

[CORE-2461] c/topics: use topic table revision to detect changes in generator

---

.github/workflows/transform-sdk-build.yml
src/transform-sdk/js/.clang-tidy
src/transform-sdk/js/.gitignore
src/transform-sdk/js/CMakeLists.txt
src/transform-sdk/js/CMakePresets.json
src/transform-sdk/js/README.md
src/transform-sdk/js/generate_js_provider.py
src/transform-sdk/js/identity.js
src/transform-sdk/js/identity_logging.js
src/transform-sdk/js/js_vm.cc
src/transform-sdk/js/js_vm.h
src/transform-sdk/js/js_vm_test.cc
src/transform-sdk/js/main.cc

Implement a QuickJS VM based Data Transforms SDK building on top of our C++ SDK.
This is still experimental and not ready for consumption, there is a lot of work
to plug this into RPK and get it easy to use.
Fixes: CORE-2371
* none

transform-sdk: Introduce QuickJS based JS SDK

---

src/v/cloud_storage_clients/abs_client.cc
src/v/cluster/tests/partition_balancer_simulator_test.cc

There is no == operator found for std::string_view and
boost::beast::string_view when using stdlibc++
* none

treewide: fix oss build with clang-18

---

src/v/cluster/topic_table_partition_generator.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/17975

[v23.2.x] [CORE-2461] c/topics: use topic table revision to detect changes in generator

---

.github/pull_request_template.md

Add v24.1.x backport option to PR template.
* none

Add v24.1.x backport option.

---

src/v/archival/ntp_archiver_service.cc
src/v/cloud_storage_clients/s3_client.cc
tests/rptest/tests/cloud_storage_scrubber_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/17839
Fixes: https://github.com/redpanda-data/redpanda/issues/17916,

[v23.3.x] archival: Start housekeeping jobs only on a leader

---

src/v/cloud_storage/segment_chunk_api.cc
src/v/cloud_storage/segment_chunk_data_source.cc

Recently added error logs do not take into account sleep aborted and other shutdown related errors. Since the logs print exception details which are already logged down the call chain, and the new logs are for debugging hang in chunk read path, the new logs are downgraded to debug level in this change.
* none

CORE-1752: cst: Downgrade error logs to debug

---

src/v/cloud_storage/tests/cloud_storage_e2e_test.cc
src/v/cluster/controller_api.cc
src/v/cluster/feature_manager.cc
src/v/cluster/health_monitor_backend.cc
src/v/cluster/health_monitor_backend.h
src/v/cluster/health_monitor_types.cc
src/v/cluster/health_monitor_types.h
src/v/cluster/metrics_reporter.cc
src/v/cluster/partition_balancer_backend.cc
src/v/cluster/partition_balancer_backend.h
src/v/cluster/partition_balancer_planner.cc
src/v/cluster/partition_leaders_table.cc
src/v/cluster/partition_leaders_table.h
src/v/cluster/service.cc
src/v/cluster/tests/health_bench.cc
src/v/cluster/tests/health_monitor_test.cc
src/v/cluster/tests/partition_balancer_planner_fixture.h
src/v/cluster/tests/partition_balancer_planner_test.cc
src/v/cluster/tests/partition_balancer_simulator_test.cc
src/v/cluster/tests/randoms.h
src/v/cluster/tests/serialization_rt_test.cc
src/v/cluster/topics_frontend.cc
src/v/compat/check.h
src/v/compat/cluster_json.h
src/v/redpanda/admin/server.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/17863

[v23.3.x] c/health: reduced number of health_node_report copies

---

src/v/features/feature_table.cc

Mark 24.2 as version 13.
Needed for upgrade tests at this point.
* none

features: Upgrade latest to version 13

---

src/v/cloud_storage_clients/client_pool.cc

`client_pool::do_client_self_configure`:
In case of retriable failure, print a warning-level message instead of error-level.
This message does not need to be at error level, in case this function fails to produce a result, the caller will print an ERROR message anyway
Fixes CORE-2490
Fixes #17995
JIRA Link: [CORE-2490](https://redpandadata.atlassian.net/browse/CORE-2490)
* none 
[CORE-2490]: https://redpandadata.atlassian.net/browse/CORE-2490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CORE-2490 cloud_storage_clients/client_pool: error->warn

---

src/v/cloud_storage_clients/client_pool.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18022
Fixes: https://github.com/redpanda-data/redpanda/issues/18024,

[v24.1.x] CORE-2490 cloud_storage_clients/client_pool: error->warn

---

src/v/config/configuration.cc
src/v/config/configuration.h
src/v/redpanda/application.cc
src/v/transform/CMakeLists.txt
src/v/transform/api.cc
src/v/transform/include/transform/api.h
src/v/transform/memory_limiter.cc
src/v/transform/memory_limiter.h
src/v/transform/tests/CMakeLists.txt
src/v/transform/tests/memory_limiter_test.cc
src/v/transform/tests/transfer_queue_test.cc
src/v/transform/tests/transform_manager_test.cc
src/v/transform/tests/transform_processor_test.cc
src/v/transform/transfer_queue.h
src/v/transform/transform_manager.cc
src/v/transform/transform_manager.h
src/v/transform/transform_processor.cc
src/v/transform/transform_processor.h

Currently all buffers in the transform subsystem (well the larger ones that hold the bulk of the data coming in and out of the transforms), have fixed size buffers that are overly small to prevent transforms from using too much memory. Allow using the full amount of memory for the transform subsystem but introducing a semaphore like accounting for memory. We can't use a real semaphore here due to a bug with semaphores and abort sources.
We split the transform subsystem's memory into two chunks. One for reads and writes so they can't starve each other (this is very bad if the read side starved writes as then we'd have a deadlock), these are tunables if set too high (45% of transform subsystem memory in general).
Fixes: CORE-2151
* Data transforms better respect overall system memory usage …

transform: enforce subsystem memory limits

---

src/v/cluster/controller_backend.cc

Previously, when force-aborting a reconfiguration, we appended an aborting configuration on all replicas. This can lead to log inconsistencies as on followers the configuration will be duplicated (one from own append, one replicated by the leader). Although these inconsistencies are expected for force-abort, if the leader is alive we can minimize the chance of their appearance by waiting on followers for the aborting config to be replicated from the leader.
Fixes https://github.com/redpanda-data/redpanda/issues/17847
* none

c/controller_backend: try to force-abort reconfiguration only on leaders

---

src/v/cloud_roles/CMakeLists.txt
src/v/cloud_roles/azure_aks_refresh_impl.cc
src/v/cloud_roles/azure_aks_refresh_impl.h
src/v/cloud_roles/tests/role_client_tests.cc

AZURE_AUTHORITY_HOST contains URLs in the form of "https://somehostname.com/"
use ada::parse to convert this string to net::unresolved_address.
Fixes CORE-2627
* correctly convert URL strings  to net::unresolved_address in azure_aks_refresh_impl

CORE-2627 fix AZURE_AUTHORITY_HOST parsing in azure_ask_refresh_impl

---

src/v/archival/tests/archival_metadata_stm_gtest.cc
src/v/archival/tests/archival_metadata_stm_test.cc
src/v/archival/tests/archival_service_fixture.h
src/v/archival/tests/service_fixture.cc
src/v/cloud_storage/tests/anomalies_detector_test.cc
src/v/cloud_storage/tests/s3_imposter.cc
src/v/cloud_storage/types.cc
src/v/cloud_storage_clients/configuration.cc
src/v/cloud_storage_clients/configuration.h
src/v/cloud_storage_clients/s3_client.cc
src/v/cloud_storage_clients/s3_client.h
src/v/cloud_storage_clients/test_client/s3_test_client_main.cc
src/v/cloud_storage_clients/tests/client_pool_mt_test.cc
src/v/cloud_storage_clients/tests/client_pool_test.cc
src/v/cloud_storage_clients/tests/s3_client_test.cc
src/v/cloud_storage_clients/types.h
src/v/config/configuration.cc
src/v/config/configuration.h
src/v/config/convert.h
src/v/config/property.h
src/v/config/rjson_serialization.cc
src/v/config/rjson_serialization.h
src/v/redpanda/tests/fixture.h
tests/rptest/services/redpanda.py

Fixes #2183.
This PR adds support for path-style requests to S3 cloud storage.
`cloud_storage_url_style` is a configurable option in `redpanda`. It defaults to the existing `virtual_host` style, but can be set to `path`. The `s3_client` will now have its headers for requests generated based on the configured URL style.
Support for ducktape has been included, and path-style requests have been verified as working using the `s3_test_client_main` test. Ideally, the cloud storage self-test in PR #17586 would be integrated with these changes so as to verify both virtual-hosted style requests and path style requests.
* Adds path-style addressing to S3 client requests. 
* This option is configurable through `rpk cluster config edit`:
```
cloud_storage_url_style: path
```

CORE-2157: cloud_storage_clients: add support for path-style addressing

---

tests/rptest/services/cloud_broker.py
tests/rptest/services/redpanda.py
tests/rptest/services/utils.py

Original code for `raise_on_bad_logs` uses the BadlogLines class which assumes that it will be initialized with Ducktape's `node` object. And subsequent `__str__` methon, which is used in creating summary. For this it gets hostname from original ducktape `Node` object.
For Cloud deployments there is two ways to solve it similarly: 
- pass pod dict and prepare similar summary by detecting which type has been passed to the Original BadLogLines exception
- Use CloudBroker class that works as a comparable substitution for RP Nodes in local runs and use it in preparing summary.
Since RedpandaServiceCloud uses Cloud broker class to handle raise_on_crash, use it for bad log lines as well.
Also, when generating summary from Exception class's __str__ method add child class to override hostname …

Update handling of bad logs for cloud deployments

---

src/v/model/transform.cc
src/v/model/transform.h
src/v/redpanda/admin/transform.cc
src/v/transform/api.cc
src/v/transform/include/transform/api.h
src/v/transform/rpc/client.cc
src/v/transform/rpc/deps.cc
src/v/transform/rpc/include/transform/rpc/client.h
src/v/transform/rpc/include/transform/rpc/deps.h
src/v/transform/rpc/include/transform/rpc/serde.h
src/v/transform/rpc/include/transform/rpc/service.h
src/v/transform/rpc/serde.cc
src/v/transform/rpc/service.cc
src/v/transform/rpc/tests/transform_rpc_test.cc
src/v/wasm/cache.cc
src/v/wasm/include/wasm/api.h
src/v/wasm/include/wasm/cache.h
src/v/wasm/tests/wasm_cache_test.cc
src/v/wasm/tests/wasm_fixture.cc
src/v/wasm/tests/wasm_transform_bench.cc
src/v/wasm/wasmtime.cc

Wasm binaries are large so we don't want to copy them between cores,
instead use a foreign_ptr instead of the slow cross core free memory
path in the seastar allocator
Fixes: CORE-2208
* none

wasm: use foreign_ptr for wasm binaries

---

src/v/cluster/topic_table_partition_generator.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/17975

[v23.3.x] [CORE-2461] c/topics: use topic table revision to detect changes in generator

---

tests/rptest/tests/rbac_upgrade_test.py

The intent of this test is to show that upgrading from a non-RBAC
supporting version to an RBAC supporting build creates the Users
role.
Previously, we would install v24.1.x explicitly. This broke because
we have tagged v24.2.0-dev (which bumps the head version) but have
NOT yet tagged v24.1.1 (so 24.1 doesn't appear in released_versions).
Simplest solution here is to upgrade directly to head version from
a non-RBAC supporting version, which should have the same effect
functionally but is more general.
Fixes CORE-2629
* none

dt/rbac_upgrade: Upgrade to head version instead of a specific 24.x 

---

src/v/config/configuration.cc
src/v/config/configuration.h
src/v/storage/log_reader.cc
src/v/storage/log_reader.h

We have observed an instance of deep recursion in the log reader followed by a segfault suspected of being a stack overflow. This commit tracks the recursion depth and uses a configured threshold depth to gate additional logging to aid in debugging.
* none

storage: add additional logging for deep log_reader recursion

---

src/v/config/configuration.cc
src/v/config/configuration.h
src/v/storage/log_reader.cc
src/v/storage/log_reader.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/18067

[v24.1.x] storage: add additional logging for deep log_reader recursion

---

src/v/cloud_roles/CMakeLists.txt
src/v/cloud_roles/azure_aks_refresh_impl.cc
src/v/cloud_roles/azure_aks_refresh_impl.h
src/v/cloud_roles/tests/role_client_tests.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18035

[v24.1.x] CORE-2627 fix AZURE_AUTHORITY_HOST parsing in azure_ask_refresh_impl

---

src/go/rpk/pkg/cli/container/common/common.go
src/go/rpk/pkg/cli/container/start.go

To let the user select their network configuration and avoid conflicts.
Fixes #9008 
* `rpk container start`: You can now select the subnet and gateway to create your 'redpanda' network.

rpk container start: add subnet/gateway flags

---

src/v/cloud_roles/tests/role_client_tests.cc

use of setenv under seastar requires to run under a initialized seastar context, since internal memory management functions will be called
https://buildkite.com/redpanda/redpanda/builds/48184#018f0cd6-3087-493c-bed2-d02e69fc3496
```
TRACE 2024-04-23 23:14:55,759 [shard 0:main] http - / - client.cc:314 - chunk received, chunk length 505
DEBUG 2024-04-23 23:14:55,759 [shard 0:main] http - iobuf_body.cc:82 - reader - finish called
test_cloud_roles_rpunit: /v/build/v_deps_build/seastar-prefix/src/seastar/src/core/memory.cc:1155: void seastar::memory::cpu_pages::shrink(void *, size_t): Assertion `object_cpu_id(ptr) == cpu_id' failed.
Aborting.
Backtrace:
0xac39f3
0xb1850b
```
backported here: https://github.com/redpanda-data/redpanda/pull/18042
* none

cloud_roles/role_clients_tests: use SEASTAR_THREAD_TEST_CASE

---

.github/workflows/scripts/jira_helper.py

Jira uses '{code}' for code blocks so convert all "```" to "{code}".
* none

gh: Adjust workflow for code blocks

---

src/transform-sdk/js/module/index.d.ts
src/transform-sdk/js/module/index.js
src/transform-sdk/js/module/package.json

Add an NPM package for our javascript SDK, this mostly is to provide
typings and documentation in IDEs/LSPs
Fixes: [CORE-2372](https://redpandadata.atlassian.net/browse/CORE-2372)
* none
[CORE-2372]: https://redpandadata.atlassian.net/browse/CORE-2372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

transform-sdk/js: add typings

---

src/v/kafka/server/handlers/fetch.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/17720

[v23.3.x] Change the` kafka_latency_fetch_latency` metric 

---

.github/workflows/lint-cpp.yml

ubuntu noble has clang-format-16. llvm repo seems to not be there yet.
* none

gh: fix lint-cpp for ubuntu noble

---

src/go/rpk/pkg/cli/container/common/common.go
src/go/rpk/pkg/cli/container/purge.go
src/go/rpk/pkg/cli/container/start.go
src/go/rpk/pkg/cli/container/stop.go
src/go/rpk/pkg/config/config.go

This PR adds a Redpanda Console container when starting a cluster with `rpk container start`
Fixes #7867 
```
$ rpk container start -n 3
Checking for a local image...
Creating network "redpanda"
Starting cluster...
Waiting for the cluster to be ready...
Cluster ready!
Starting Redpanda Console...
Waiting for Redpanda Console to be ready...
Console ready!
NODE-ID  STATUS   KAFKA-ADDRESS    ADMIN-ADDRESS    PROXY-ADDRESS    SCHEMA-REGISTRY-ADDRESS
0        running  127.0.0.1:9092   127.0.0.1:9644   127.0.0.1:8082   127.0.0.1:8081
1        running  127.0.0.1:10092  127.0.0.1:10644  127.0.0.1:9082   127.0.0.1:9081
2        running  127.0.0.1:11092  127.0.0.1:11644  127.0.0.1:10082  127.0.0.1:10081
Redpanda Console started in: http://localhost:8080
Created "rpk-container" profile.
You can use …
```

rpk: Start a Redpanda Console container with `rpk container start`

---

.github/CODEOWNERS

Automatically tag doc team member in charge of rpk doc changes.
* none

codeowner: add doc team member for rpk changes

---

src/v/redpanda/admin/server.cc

Previously the service_unavailable error code was mapped to generic unexpected server error. This lead to a situation in which a lot of errors were logged when broker was restarted as it has an RPC server running but without the services registered. Changed the mapping of `rpc::errc::service_unavailable` to HTTP service unavailable error.
Fixes: #17739
- Better mapping of REST error codes

admin: fixed mapping of service unavailable error code

---

src/go/rpk/pkg/cli/cluster/partitions/list.go

When using `rpk cluster partitions list`, it's useful if we could filter the list of partitions with broker IDs. I've added a new `--node-ids` option to the command.
```
List partitions which replicas are assigned to brokers 1 and 2.
rpk cluster partitions list foo --node-ids 1,2
```
* rpk: `rpk cluster partitions list` now supports filtering with broker IDs.

rpk: add --node-ids option to rpk cluster partitions list

---

src/v/cluster/cloud_metadata/tests/cluster_recovery_backend_test.cc

The test iterates over partitions across scheduling points, even though the partitions() container is explicitly documented to not support this. This commit makes a copy of the container before iterating.
Fixes #17920
* none

cluster_recovery_backend_test: fix unsafe iteration

---

src/v/cluster/partition_balancer_backend.cc

This change is a part of an effort to identify and fix rare segmentation fault in Redpanda that happens after it was suspended with `SIGSTOP` signal.
According to the C++ standard the temporary should be kept alive until the expression ends. The crash we are observing indicates the UAF issue. The only way the variable, that access causes the segfault, can be deleted is by getting out of scope which in this situation should be guaranteed.
Given our experience with coroutines and different types of lifecycle bugs that we found in past this is a poor man's effort to avoid the issue.
Related issues:
https://github.com/redpanda-data/redpanda/issues/17751
https://github.com/redpanda-data/redpanda/issues/16510
https://github.com/redpanda-data/redpanda/issues/16533 …

c/balancer_backend: first initialize planner and then call plan

---

cmake/sccache.cmake

Add cmake include file to enable sccache
* none

cmake: Add support for sccache

---

src/v/cloud_storage/cache_probe.cc
src/v/cloud_storage/cache_probe.h
src/v/cloud_storage/cache_service.cc
src/v/cloud_storage/cache_service.h
src/v/cloud_storage/materialized_resources.cc
src/v/cloud_storage/materialized_resources.h
src/v/cloud_storage/recursive_directory_walker.cc
src/v/cloud_storage/tests/cache_test.cc
src/v/cloud_storage/tests/cache_test_fixture.h
src/v/config/configuration.cc
src/v/config/configuration.h

The `carryover` is a collection of deletion candidates found during the previous trim. The trim collects full list of objects in the directory and sorts them in LRU order. Then it deletes first N objects. We're saving first M objects that remain in the list after the trim. These objects are deletion candidates.
During the next trim the cache service first uses `carryover` list to a quick cache trim. This trim doesn't need a directory scan and it can quickly decrease bytes/objects counts so other readers could reserve space successfully. The trim doesn't delete objects from the `carryover` list blindly. It compares access time recorded in the carryover list to the access time stored in the `accesstime_tracker`. If the time is different then the object was accessed and the trim is not …

cloud_storage: Implement "carryover" cache trimming mechanism 

---

src/v/cluster/producer_state.h
src/v/cluster/rm_stm.cc
src/v/cluster/rm_stm.h

Another step towards consolidated state management.
This PR removes `mem_state` struct from rm_stm entirely. Main change in this PR is to get rid of mem_state::estimated map that is supposed to hold the estimated offset of the first data batch in a transaction while its replication is in progress. This estimate is in place so that any racy LSO computation on the partition does not exceed the (future) replicated offset.  We remove that by redefining the transaction boundary to include the begin/fence batch in the transaction. first data batch is guaranteed to `happen after` the fence batch, so clamping the LSO at the fence batch by redefining the transaction boundaries ensures that in replication batches are not accounted for LSO.
The advantage of removing mem state is that the entire …

tx/rm_stm: remove mem_state

---

src/v/cluster/cloud_metadata/tests/cluster_recovery_backend_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18119
Fixes: https://github.com/redpanda-data/redpanda/issues/18122,

[v23.3.x] cluster_recovery_backend_test: fix unsafe iteration

---

src/v/cloud_storage/cache_probe.cc
src/v/cloud_storage/cache_probe.h
src/v/cloud_storage/cache_service.cc
src/v/cloud_storage/cache_service.h
src/v/cloud_storage/materialized_resources.cc
src/v/cloud_storage/materialized_resources.h
src/v/cloud_storage/recursive_directory_walker.cc
src/v/cloud_storage/tests/cache_test.cc
src/v/cloud_storage/tests/cache_test_fixture.h
src/v/config/configuration.cc
src/v/config/configuration.h
src/v/utils/adjustable_semaphore.h

Backport of the #18056
Fixes #18133 
The `carryover` is a collection of deletion candidates found during the previous trim. The trim collects full list of objects in the directory and sorts them in LRU order. Then it deletes first N objects. We're saving first M objects that remain in the list after the trim. These objects are deletion candidates.
During the next trim the cache service first uses `carryover` list to a quick cache trim. This trim doesn't need a directory scan and it can quickly decrease bytes/objects counts so other readers could reserve space successfully. The trim doesn't delete objects from the `carryover` list blindly. It compares access time recorded in the carryover list to the access time stored in the `accesstime_tracker`. If the time is different then the object …

[v23.3.x] cloud_storage: Implement "carryover" cache trimming mechanism

---

src/v/resource_mgmt/cpu_profiler.cc
src/v/resource_mgmt/cpu_profiler.h
src/v/resource_mgmt/tests/cpu_profiler_test.cc

Fixes two bugs in the cpu profiler wait_ms implementation:
- Actually enable the profiler on all shards not just the Admin API shard
- Work for short and arbitrary sample periods. Previously it would only collect samples for multiples of ~13 seconds.
* none

Fixes for wait_ms cpu profiler mode

---

.github/workflows/buildkite-slash-commands.yml
.github/workflows/slash-commands.yml

Register `/test-tc-pipeline` slash command to exercise the RC pipeline
* none

slash-cmds: register /test-rc-pipeline

---

src/v/cluster/controller_backend.cc
src/v/cluster/controller_backend.h
src/v/cluster/shard_balancer.cc
src/v/cluster/shard_placement_table.cc
src/v/cluster/shard_placement_table.h
src/v/cluster/tests/shard_placement_table_test.cc
src/v/cluster/tests/topic_table_fixture.h
src/v/cluster/tests/topic_table_test.cc
src/v/cluster/tests/topic_updates_dispatcher_test.cc
src/v/cluster/topic_table.cc
src/v/cluster/topic_table.h

When bootstrapping controller_backend, we don't really need to try and reconcile all ntps in the cluster, we can start with the set that is in shard_placement_table (i.e. all ntps with some relation to the current shard). This also allows us to use non-consuming topic_table notifications.
* none

c/controller_backend: bootstrap from shard_placement_table

---

tests/rptest/redpanda_cloud_tests/omb_validation_test.py
tests/rptest/services/openmessaging_benchmark.py
tests/rptest/services/openmessaging_benchmark_configs.py

Detect latency spikes that could be due to underlying disks go through periods of 300-1000ms, and retry the test up to R number of times.
* none
* The issue is that the underlying disks go through periods of 300-1000ms where they have greatly reduced throughput and this produces a latency spike. This may eventually be solved by https://github.com/redpanda-data/core-internal/issues/1142 but in the meantime we should implement a workaround so that the tests can run giving a reasonable signal but not spuriously failing due to this issue.
My suggestion is that if a test fails due to p99/p999 threshold breach, we check if it looks like it has spikes using a simple heuristic based on the time-series percentiles (see eg …

PESDLC-1025 Retry when spikes occur in OMB

---

src/go/rpk/pkg/adminapi/api_debug.go
src/go/rpk/pkg/cli/cluster/selftest/selftest_test.go
src/go/rpk/pkg/cli/cluster/selftest/start.go
src/go/rpk/pkg/cli/cluster/selftest/status.go
src/v/cloud_storage/inventory/tests/common.h
src/v/cloud_storage/inventory/tests/fetch_report_tests.cc
src/v/cloud_storage/remote.cc
src/v/cloud_storage/remote.h
src/v/cluster/CMakeLists.txt
src/v/cluster/self_test/cloudcheck.cc
src/v/cluster/self_test/cloudcheck.h
src/v/cluster/self_test/metrics.h
src/v/cluster/self_test_backend.cc
src/v/cluster/self_test_backend.h
src/v/cluster/self_test_frontend.cc
src/v/cluster/self_test_frontend.h
src/v/cluster/self_test_rpc_types.cc
src/v/cluster/self_test_rpc_types.h
src/v/redpanda/admin/api-doc/debug.json
src/v/redpanda/admin/server.cc
src/v/redpanda/application.cc
tests/rptest/clients/rpk.py
tests/rptest/tests/self_test_test.py

Adds a cloud storage check to the cluster self test, as requested in #9225.
Depending on read/write permissions, the cloud storage test uses the `cloud_storage::remote` object configured at the application layer to:
- Upload an object to S3.
- List objects in a bucket.
- Download an object from the bucket.
- Delete the original object, if it was uploaded.
* A cloud storage check as part of the cluster's self test.
To run, use `rpk cluster self-test start`. The following flags have also been added to `rpk` for use with the cloud storage test:
- `--cloud-backoff-ms uint`, the backoff in milliseconds for a cloud storage request.
- `--cloud-timeout-ms uint`, the timeout in milliseconds for a cloud storage request.
- `--only-cloud-test`, in order to run only the cloud storage test.

[CORE-1198] cluster: cloud storage self test

---

src/v/cloud_storage/tests/cloud_storage_e2e_test.cc
src/v/cluster/partition.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/17533
Fixes: https://github.com/redpanda-data/redpanda/issues/18158,

[v24.1.x] CORE-1412: cluster: remote read check in partition timequery

---

src/v/config/configuration.cc
src/v/config/configuration.h
src/v/config/convert.h
src/v/config/property.h
src/v/config/rjson_serialization.cc
src/v/config/rjson_serialization.h
src/v/kafka/server/handlers/fetch.cc
src/v/kafka/server/handlers/fetch.h
src/v/model/metadata.h
src/v/model/model.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18090

[v24.1.x] Stephan/revert polling removal

---

tests/rptest/services/flink.py

FIPS image has python version of 3.8.x installed by default. When running flink, it should detect currently running version that was added via env.
Fixes: #17504 
* none

PESDLC-1250 Add python interpreter detection

---

tests/rp_cloud_cleanup.py
tests/rptest/services/provider_clients/ec2_client.py

Improve bucket cleaning and use key object date instead of bucket one. Bucket date hold latest bucket modification that includes policy updates, uploads of new oblects, etc.
* none

PESDLC-1275 Use last modified date to clean bucket

---

tests/rptest/services/redpanda.py

Upgrade tests in ducktape are failing due to incorrect feature-gating around the configuration parameter `cloud_storage_url_style`. 
This PR corrects that.
* none

rptest: fix feature-gating of `cloud_storage_url_style`

---

.github/workflows/transform-sdk-release.yml
src/go/rpk/pkg/cli/transform/build.go
src/go/rpk/pkg/cli/transform/buildpack/buildpack.go
src/go/rpk/pkg/cli/transform/init.go
src/go/rpk/pkg/cli/transform/project/project.go
src/go/rpk/pkg/cli/transform/template/js/README.md
src/go/rpk/pkg/cli/transform/template/js/esbuild.js
src/go/rpk/pkg/cli/transform/template/js/transform.jssrc
src/go/rpk/pkg/cli/transform/template/js/transform.tssrc
src/go/rpk/pkg/cli/transform/template/js/tsconfig.json
src/go/rpk/pkg/cli/transform/template/js_template.go
src/transform-sdk/js/CMakeLists.txt
src/transform-sdk/js/module/index.d.ts
src/transform-sdk/js/module/index.js
src/transform-sdk/js/module/package-lock.json
src/transform-sdk/js/module/package.json
src/transform-sdk/js/package_toolchain.py

Support JS and TS for Data Transforms.
We still have work to do here, mainly a deploy pipeline for the JS buildpack, otherwise I have proof this is working end to end.
Closes: CORE-2370 and CORE-2373
* Support JavaScript and TypeScript as languages for Data Transforms.

rpk/transform: support javascript and typescript

---

.github/workflows/transform-sdk-release.yml

yq has wildly different syntax depending on the version, so just use the dumb and simple sed.
* none

gha: fix js sdk release

---

src/transform-sdk/js/CMakeLists.txt

This reverts commit bf885756e148becb261c69eaddd6abe4ffc8cc11.
* none

transform-sdk/js: reverting "disable thinLTO"

---

tests/rptest/redpanda_cloud_tests/omb_validation_test.py

Fixes test issue #PESDLC-1305
* none

Fixing a function calling typo

---

src/v/cluster/controller_backend.cc
src/v/cluster/shard_placement_table.cc
src/v/cluster/tests/shard_placement_table_test.cc

Previously, in the interval between topic_table update and shard_placement_table update, controller_backend busy-looped by "successfully removing" a partition that already wasn't there (the only thing remaining was the assignment marker that remained until the shard_placement_table update fully completed). Return a wait_for_target_update error instead that will put the reconciliation fiber to sleep.
* none

controller_backend: prevent busy-looping when removing partitions

---

src/v/cluster/tests/tm_stm_tests.cc
src/v/cluster/tm_stm.cc
src/v/cluster/tm_stm.h
src/v/cluster/tx_gateway_frontend.cc
src/v/cluster/tx_gateway_frontend.h
src/v/config/configuration.cc
tests/rptest/tests/transactions_test.py

If there is a new producer_id, we do not need older incarnations of the
same id as the corresponding transactions are sealed before
re-registration.
* none

tx/tm_stm: fix unboundedness of _pid_tx_id

---

src/v/cluster/rm_stm.cc

Chaos logs showed that there can be duplicate (back to back) begin_tx requests due to certain client quirks beyond our control. We had some checks in place to ignore them but they were invalidated by https://github.com/redpanda-data/redpanda/pull/18076 which redefined the transaction boundaries. After #18076 an entry in the ongoing_map does not mean the data has been replicated as a part of the transaction. This PR adjusts the checks accordingly.
Note: This code is going away soon, so we will have better API in the producer_state to make the code more easily understandable. This PR is to make chaos happy until then.
* none

tx/rm_stm: deal with duplicate begin_tx requests

---

tests/docker/ducktape-deps/ocsf-server

PPA repositories is occasionally returns 503 when overloaded
preventing pipelines from normal run. These are queries in all
subsequent dependencies and must be removed to eliminate
instability
* none

PESDLC-1295  Remove unstable launchpad repo after install

---

src/v/wasm/wasmtime.cc

Expand the try/catch block in async host functions to catch arg translation exceptions (from out of bounds buffers being passed).
Otherwise this gets bubbled up over an ABI boundary which is not good (causes an abort).
* Fix a bug where an invalid buffer passed into the WebAssembly host from the guest could cause Redpanda to abort.

wasm: fix host function arg translation

---

src/v/cluster/controller_backend.cc
src/v/cluster/shard_placement_table.cc
src/v/cluster/tests/shard_placement_table_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18157

[v24.1.x] controller_backend: prevent busy-looping when removing partitions

---

src/v/cloud_storage/segment_chunk_api.cc
src/v/cloud_storage/segment_chunk_data_source.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/17828

[v24.1.x] CORE-1752: cst: Downgrade error logs to debug

---

src/v/cluster/cloud_metadata/tests/cluster_recovery_backend_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18119
Fixes: https://github.com/redpanda-data/redpanda/issues/18124,

[v24.1.x] cluster_recovery_backend_test: fix unsafe iteration

---

src/v/cluster/partition_balancer_backend.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18091

[v24.1.x] c/balancer_backend: first initialize planner and then call plan

---

src/v/cloud_storage/remote_partition.cc
src/v/cloud_storage/tests/remote_partition_test.cc

It's possible that when a client disconnects, the abort source subscription associated with the client connection ends up evicting the current segment reader.
1. Remote partition reader is in the process of reading a segment
2. The read eventually scans past the LSO, and stops. This stop() is asynchonous, closing IO streams, etc.
3. The Kafka client disconnects, triggering the abort source subscription callback to call evict_segment_reader(), moving the segment reader to the remote partition's eviction list
4. The remote partition's eviction loop sees this reader and runs stop(), and destructs the underlying parser
5. The read fiber, still stopping, resumes control, but the underlying parser is destructed
This is roughly the sequence of events seen below.
```
DEBUG 2024-05-02 14:55:06,231 …
```

cloud_storage: avoid possible double stop in segment reader

---

src/v/cloud_storage/tests/topic_manifest_test.cc
src/v/cloud_storage/topic_manifest.cc

this mirrors what's done for retention_bytes. the reasoning is that if somebody performs a manual edit of the topic manifest and writes "retention_duration" : -1, it's probably done to mirror the retention.ms semantic of meaning infinite retention
this a followup on
https://github.com/redpanda-data/redpanda/pull/14355#discussion_r1428255190
* allow interpreting `'retention_duration' = -1` in a topic_manifest.json file as infinite time retention

[CORE-2161] cloud_storage/topic_manifest: force negative retention to mean infinite retention

---

src/v/config/configuration.cc
src/v/config/configuration.h
src/v/kafka/server/tests/consumer_groups_test.cc
src/v/storage/disk_log_impl.cc
tests/rptest/tests/transactions_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18140

[v24.1.x] configuration to enable delete retention for consumer offsets

---

src/v/resource_mgmt/cpu_profiler.cc
src/v/resource_mgmt/cpu_profiler.h
src/v/resource_mgmt/tests/cpu_profiler_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18089

[v24.1.x] Fixes for wait_ms cpu profiler mode

---

src/v/cloud_storage/cache_probe.cc
src/v/cloud_storage/cache_probe.h
src/v/cloud_storage/cache_service.cc
src/v/cloud_storage/cache_service.h
src/v/cloud_storage/materialized_resources.cc
src/v/cloud_storage/materialized_resources.h
src/v/cloud_storage/recursive_directory_walker.cc
src/v/cloud_storage/tests/cache_test.cc
src/v/cloud_storage/tests/cache_test_fixture.h
src/v/config/configuration.cc
src/v/config/configuration.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/18056

[v24.1.x] cloud_storage: Implement "carryover" cache trimming mechanism 

---

src/v/cloud_storage/remote_partition.cc
src/v/cloud_storage/tests/remote_partition_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18229
Fixes: https://github.com/redpanda-data/redpanda/issues/18237,

[v23.3.x] cloud_storage: avoid possible double stop in segment reader

---

src/v/cloud_storage/remote_partition.cc
src/v/cloud_storage/tests/remote_partition_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18229
Fixes: https://github.com/redpanda-data/redpanda/issues/18240,

[v24.1.x] cloud_storage: avoid possible double stop in segment reader

---

.github/workflows/lint.yml

Manual backport of https://github.com/redpanda-data/redpanda/pull/18087.
[This backport could not be applied](https://github.com/redpanda-data/redpanda/pull/18087#issuecomment-2086991558) because `lint-cpp.yml` did not exist in `v23.2.x`.
I have made the same change found in the above PR to the appropriate command in `lint.yml`.
* none

[v23.2.x] gh: fix lint-cpp for ubuntu noble (manual backport)

---

tests/rptest/clients/kubectl.py
tests/rptest/services/redpanda.py

These commands didn't have their output captured so they were spamming stdout during test runs, drowning out the useful logs.
Switch them to using the _cmd helper which captures stdout and stderr and emits them to the log if the command fails.
* none

rptest: capture tbot and ./breakglass output

---

tests/rp_cloud_cleanup.py
tests/rptest/services/provider_clients/ec2_client.py
tests/rptest/services/provider_clients/rpcloud_client.py

Cleaning of VPC includes dependency cleaning.
Once of the caveats is that if some public IPs still mapped to the networks/VPC, it will be skipped.
* none

PESDLC-1082 Add VPC Cleaning to rp_cloud_cleanup.py

---

src/go/.goreleaser.yaml

Now that 24.1.1 is out, no more 23.3.x releases should be uploaded
fixes https://redpandadata.atlassian.net/browse/PESDLC-1310
* none

goreleaser: stop updating tap for 23.3

---

src/v/cluster/tests/tm_stm_tests.cc
src/v/cluster/tm_stm.cc
src/v/cluster/tm_stm.h
src/v/cluster/tx_gateway_frontend.cc
src/v/cluster/tx_gateway_frontend.h
src/v/config/configuration.cc
tests/rptest/tests/transactions_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18198

[v23.3.x] tx/tm_stm: fix unboundedness of _pid_tx_id

---

src/v/cloud_storage/tests/topic_manifest_test.cc
src/v/cloud_storage/topic_manifest.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/17461

[v23.3.x] [CORE-2161] cloud_storage/topic_manifest: force negative retention to mean infinite retention

---

src/v/cloud_storage/remote_segment.cc
src/v/cloud_storage/remote_segment.h
src/v/cloud_storage/segment_chunk_api.cc
src/v/cloud_storage/segment_chunk_api.h
tests/rptest/tests/cloud_storage_chunk_read_path_test.py

Chunk downloads are moved into the remote segment background loop. Previously any fiber could request chunk download directly by calling the API methods on remote segment.
The remote segment is structured so that its public API enables callers to enqueue downloads, which are serviced via a single download loop which starts in its c-tor. This enables the remote segment to abort pending downloads in case of an error, as well as managing the shut down process cleanly. 
Before this change chunk downloads did not follow this pattern, any chunk download request could directly trigger a download and materialization from any fiber without going through the loop. While this works ok in most cases, it spreads downloads across multiple fibers and makes it harder to debug hangs while downloading …

[CORE-2581] cst: move chunk downloads to remote segment bg loop

---

src/v/cloud_storage/remote_segment.cc
src/v/cloud_storage/remote_segment.h
src/v/cloud_storage/segment_chunk_api.cc
src/v/cloud_storage/segment_chunk_api.h
tests/rptest/tests/cloud_storage_chunk_read_path_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18093

[v24.1.x] [CORE-2581] cst: move chunk downloads to remote segment bg loop

---

src/v/cluster/self_test/cloudcheck.cc
src/v/cluster/self_test/cloudcheck.h
tests/rptest/tests/self_test_test.py

Completes test coverage for remote object API by adding `verify_head()` and `verify_deletes()` to `cloudcheck.cc`.
Some stylistic changes to the other existing verification tests as well.
The cloud storage self test now covers:
* Get
* Put
* Head
* List
* Delete
* Plural Delete
JIRA Issue: https://redpandadata.atlassian.net/browse/CORE-2418
* None

CORE-2418: cluster/self_test: extend cloud storage self test

---

src/v/security/CMakeLists.txt
src/v/security/jwt.cc
src/v/security/jwt.h
src/v/utils/base64.cc
src/v/utils/base64.h
src/v/utils/tests/CMakeLists.txt
src/v/utils/tests/base64_test.cc

Creates a base64 URL decoder in utils to replace the one in CryptoPP.
* none

CORE-548 base64 url decode

---

src/v/cloud_storage/remote_partition.cc
src/v/cloud_storage/tests/cloud_storage_e2e_test.cc
src/v/cluster/partition.cc
src/v/cluster/partition.h
src/v/kafka/server/handlers/list_offsets.cc
src/v/kafka/server/replicated_partition.cc
src/v/model/offset_interval.h
src/v/model/tests/random_batch.cc
src/v/model/tests/random_batch.h
src/v/storage/disk_log_impl.cc
src/v/storage/lock_manager.cc
src/v/storage/log_reader.cc
src/v/storage/log_reader.h
src/v/storage/tests/storage_e2e_test.cc
src/v/storage/tests/timequery_test.cc
src/v/storage/types.cc
src/v/storage/types.h
src/v/transform/api.cc
tests/rptest/tests/timequery_test.py

The fix works only if compression is not in use. We need follow-up work which would decompress the batches to find the exact offset to return, or (!) we could to prevent trim-offset inside a batch in that case.
* Fix a scenario where list_offset with a timestamp could return a lower offset than partition start after a trim-prefix command. This could lead to consumers being stuck with an out-of-range-offset exception if they began consuming from an offset below the one which was used in the trim-prefix command.

Fix timequery returning wrong offset after trim-prefix which could lead to stuck consumers

---

src/v/config/node_config.cc
src/v/redpanda/application.cc

Updates from post review comments in #17616 
* none

CORE-2742 post review updates

---

src/v/cluster/shard_balancer.cc
src/v/cluster/shard_balancer.h
src/v/cluster/shard_placement_table.cc
src/v/cluster/shard_placement_table.h
src/v/cluster/tests/shard_placement_table_test.cc
src/v/container/include/container/chunked_hash_map.h

For now, when assigning shards only involves modifying in-memory state, we can get away with assigning each ntp sequentially. But in the future it will also involve kvstore writes (with their associated 10ms latency), and for the case of 1000s of partitions this will lead to noticeable delays. Assign shards concurrently to deal with this problem.
* none

c/shard_balancer: assign shards concurrently

---

tests/rptest/tests/scaling_up_test.py

`test_adding_nodes_to_cluster` assumes all internal topics are `rf=1`. As the test keeps adding nodes to the cluster,  health monitor up-replicates the internal topics like `__consumer_offsets` to `rf=3` violating the assumptions and thus failing the test invariants. 
* none

ducktape: deflake test_adding_nodes_to_cluster

---

src/v/cluster/rm_stm.cc
src/v/cluster/rm_stm.h
src/v/cluster/tests/rm_stm_test_fixture.h
src/v/cluster/tests/rm_stm_tests.cc

In earlier versions we were not considering transactions without data
batches as candidates for expiry, thats not the case any more with
https://github.com/redpanda-data/redpanda/pull/18076, adding a regression test to future proof.
* none

rm_stm/tests: add test for producer expiration without data batches

---

tests/rptest/clients/offline_log_viewer.py
tests/rptest/tests/transactions_test.py
tools/offline_log_viewer/kafka.py
tools/offline_log_viewer/viewer.py

Noticed this was broken while parsing some logs.
* none

offline_log_viewer: fix get_control_record_type

---

src/go/rpk/pkg/cli/cloud/cluster/select.go

There might be cases where the user is using
rpk cloud cluster select in a single-cluster org
and args will be null, causing a panic.
Fixes #18270
* none

rpk: stop using args[0] in cloud cluster select

---

src/v/cluster/scheduling/leader_balancer_constraints.cc
src/v/cluster/scheduling/leader_balancer_constraints.h
src/v/cluster/tests/leader_balancer_constraints_test.cc

` _topic_node_index` originally stored a bunch of metadata about every group a node led. However, this information was only ever used in `even_topic_distributon_constraint::recommended_reassignment`. A method which isn't used anywhere outside of unit tests.
This PR changes the information stored in `_topic_node_index` to be just the count of leaders on a given node. And removes the implementation of `even_topic_distributon_constraint::recommended_reassignment`.
Fixes #17349 
* none

Change information stored in ` _topic_node_index` to avoid oversized alloc

---

src/v/cluster/scheduling/leader_balancer_constraints.cc
src/v/cluster/scheduling/leader_balancer_constraints.h
src/v/cluster/tests/leader_balancer_constraints_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/17350
Fixes: https://github.com/redpanda-data/redpanda/issues/18327,

[v24.1.x] Change information stored in ` _topic_node_index` to avoid oversized alloc

---

tests/rptest/tests/consumer_group_test.py
tests/rptest/tests/transactions_test.py
tools/offline_log_viewer/consumer_offsets.py
tools/offline_log_viewer/viewer.py

offline_log_viewer: support transactional offset commit parsing

---

src/go/rpk/pkg/cli/cloud/cluster/select.go

Backport of PR https://github.com/redpanda-data/redpanda/pull/18274
Fixes: https://github.com/redpanda-data/redpanda/issues/18320,

[v24.1.x] rpk: stop using args[0] in cloud cluster select

---

src/go/rpk/pkg/cli/container/start.go

This has always worked but it is hidden. We now document it.
This is unnecessary but may be a good alternative for testing config properties on start.
* none

rpk: document --set flag in rpk container start

---

src/v/cloud_storage/remote_partition.cc
src/v/cloud_storage/tests/cloud_storage_e2e_test.cc
src/v/cluster/partition.cc
src/v/cluster/partition.h
src/v/kafka/server/handlers/list_offsets.cc
src/v/kafka/server/replicated_partition.cc
src/v/model/offset_interval.h
src/v/model/tests/random_batch.cc
src/v/model/tests/random_batch.h
src/v/storage/disk_log_impl.cc
src/v/storage/lock_manager.cc
src/v/storage/log_reader.cc
src/v/storage/log_reader.h
src/v/storage/tests/storage_e2e_test.cc
src/v/storage/tests/timequery_test.cc
src/v/storage/types.cc
src/v/storage/types.h
src/v/transform/api.cc
tests/rptest/tests/timequery_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18112

[v24.1.x] Fix timequery returning wrong offset after trim-prefix which could lead to stuck consumers

---

src/v/archival/ntp_archiver_service.cc
src/v/archival/ntp_archiver_service.h

The archival/tiered storage correctness assumption builds on the (wrong) assumption that LSO is monotonic. Tiered storage doesn't have a concept of suffix truncation so if that would happen it would lead violations of correctness properties and diverging logs/undefined behavior.
However, we have discovered that property does not hold if there are no in-progress transaction and acks=0/1 or write caching is in use because LSO falls back to "last visible index"[^1] which can get truncated.
Ref https://github.com/redpanda-data/redpanda/issues/18244
[^1]: https://github.com/redpanda-data/redpanda/blob/88ac775f9f7954330732024abfa6e9ed5c9c11fd/src/v/cluster/rm_stm.cc#L1322
* none

archival: clamp uploads to committed offset

---

tests/rptest/services/redpanda_installer.py

During RP installation within Ducktape tests, we use curl to download RP from S3.  This can fail due to intermittent network issues.  Adding retries is a good idea to prevent inevitable test flakes.
* none

[dt] add retries to remote curl call

---

src/v/cluster/scheduling/types.cc
src/v/cluster/tests/partition_balancer_planner_fixture.h
src/v/cluster/tests/partition_balancer_planner_test.cc
src/v/cluster/topic_table.cc
src/v/cluster/topic_table.h
src/v/cluster/topics_frontend.cc
src/v/utils/exceptions.h
src/v/utils/stable_iterator_adaptor.h

Partition balancer relies on `_topics_map_revision` checks to safely iterate over topic table collections with partition granularity (i.e. references to partition data and replica sets are stored and accessed across yield points). To make this safe, increment `_topics_map_revision` every time `_topics`, `_updates_in_progress`, `_disabled_partitions` or nested collections are modified in a way that invalidates references or iterators.
Likely fixes:
* https://github.com/redpanda-data/redpanda/issues/18130
* https://github.com/redpanda-data/redpanda/issues/17751
* https://github.com/redpanda-data/redpanda/issues/16533
* https://github.com/redpanda-data/redpanda/issues/16510
* https://github.com/redpanda-data/redpanda/issues/13301
* none

Fix some concurrent memory access problems in partition balancer

---

src/v/storage/mvlog/CMakeLists.txt
src/v/storage/mvlog/batch_collecting_stream_utils.cc
src/v/storage/mvlog/batch_collecting_stream_utils.h
src/v/storage/mvlog/entry_stream.cc
src/v/storage/mvlog/entry_stream.h
src/v/storage/mvlog/errc.h
src/v/storage/mvlog/readable_segment.cc
src/v/storage/mvlog/readable_segment.h
src/v/storage/mvlog/segment_reader.cc
src/v/storage/mvlog/segment_reader.h
src/v/storage/mvlog/tests/CMakeLists.txt
src/v/storage/mvlog/tests/batch_collecting_stream_utils_test.cc
src/v/storage/mvlog/tests/entry_stream_utils_test.cc
src/v/storage/mvlog/tests/segment_io_test.cc
src/v/storage/mvlog/tests/segment_reader_test.cc

Introduces a few abstractions to be used as a part of the upcoming
new log_reader implementation. These abstractions are:
- entry_stream: A utility class to parse input_streams as a contiguous run of
entries.
- readable_segment: A long-lived representation of a segment file, used to
construct segment_readers.
- segment_reader: A short-lived accessor to the file used to construct
input_streams. This doesn't enforce any lifecycle relationships
between segment_readers and input_streams, but it is expected that the
readers will outlive the streams.
These abstractions are pretty bare bones compared to the existing
storage::segment, storage::segment_reader, and reader handle. There is
some basic accounting done for the readers, but the complexity of a
ref-counted handle doesn't seem critical …

[CORE-1912] mvlog: add basic segment reader

---

src/v/resource_mgmt/storage.cc
src/v/storage/disk_log_impl.cc
src/v/storage/disk_log_impl.h
src/v/storage/log_manager.cc
src/v/storage/log_manager.h

Refactors and renames some methods, and tweaks comments and logs to clarify the space management and retention code.
There are no major functional changes in this PR.
* none

storage: various space management non-functional changes

---

src/v/redpanda/admin/server.cc
tests/rptest/services/admin.py
tests/rptest/tests/leaders_redirect_test.py

Fixes #17149 
Certain requests made to the admin `server.cc` require that they be executed on the leader node.
A CI failure ran into the corner case of stale leadership metadata in the `metadata_cache`, resulting in a ping-pong of `reader_to_leader()` and HTTP requests between two nodes. This very quickly (on the order of ~`50ms`) resulted in exceeding the maximum allowable redirects.
This PR appends a `Retry-After` header to every other redirected HTTP request of this nature, and keeps track of the number of redirects in the url's query string (`?redirect=#`).
More intricate heuristics or actions for the timeout could be implemented in the future, such as cycle detection. My rationale for the current behaviour of sleeping on every other redirect is:
1. An initial redirect to a leader …

CORE-1882: admin: add backoff to redirect_to_leader requests

---

src/v/model/fundamental.h

model::offset::max() is often used to indicate "no upper bound" on operations. E.g. for tiered storage uploads[^1], for reading from local storage[^2], etc.
We also do often convert from closed to opened offset intervals representations. E.g. committed offset to LSO and the other way around.
When combined, these can result in unexpected behaviors. In particular, if on a read path the max offset is specified as model::offset_max() but at lower level this is converted into an exclusive offset by calling next_offset(model::offset::max()), the result is model::offset::min() aka -2^63.
This is dangerous. Let's instead saturate the offset similar to how we saturate prev_offset.
We also have a few cases where we just do `o + model::offset(1)`. These should be refactored to use next_offset too. …

model: make next_offset saturate rather than overflow

---

src/v/archival/ntp_archiver_service.cc
src/v/archival/ntp_archiver_service.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/18285

[v23.3.x] archival: clamp uploads to committed offset

---

src/v/base/include/base/outcome.h
src/v/cluster/id_allocator_frontend.cc
src/v/cluster/id_allocator_stm.cc
src/v/cluster/id_allocator_stm.h
src/v/cluster/tests/CMakeLists.txt
src/v/cluster/tests/id_allocator_stm_test.cc
src/v/raft/tests/raft_fixture.h
src/v/test_utils/test.h

As part of deprecating `simple_raft_fixture` in favour of raft_fixture, making `id_allocator_stm_test` to use the latter. For compatibility with `raft_fixture::retry_with_leader` I had to change `id_allocator_stm` return type to `result`. I had to improve `raft_fixture::retry_with_leader` to accept more data types too. I also created some test helper macros, they are only used occasionally here but will get more use in my next PR(s).
* none

tests: base id_allocator_stm_test on raft_fixture

---

src/v/archival/tests/ntp_archiver_test.cc

Adding a segment takes ~1ms. Adding multiple segments in a single batch
can stall the reactor for a while. This, together with a recent seastar
change[^1] caused some timeouts to fire very frequently[^2].
Fix the problematic test by splitting the batch passed to add_segments
so that we execute more finer grained tasks and yield more often to the
scheduler.
[^1]: https://github.com/scylladb/seastar/issues/2238
[^2]: https://github.com/redpanda-data/redpanda/issues/13275
Fixes https://github.com/redpanda-data/redpanda/issues/13275
* none

archival/tests: yield more often to the scheduler

---

src/v/storage/segment_index.h
src/v/storage/tests/storage_e2e_test.cc

In the e2e storage test the index step size of 32KiB is used as possible deviation from expected results. An allowance of 50KiB is used to prevent the test failing because of index step size.
The change computes max step size across all segment indices and uses that as the deviation.
FIXES #18396
* none

storage/tests: Adjust step size deviation used in test

---

src/v/http/client.cc
src/v/http/include/http/client.h

http::client::stop() can be called twice in the event the client is used via the `with_client` method.
The method had unconditionally called stop() in a finally clause with the intention to have users not have to manually do this and forget to call stop.
However stop() can also be called within certain exception handlers within methods invoked by http::client, ones that handle tls::verification_error exceptions.
This patch skips the call to stop() in the event a tls::verification_error exception was encountered.
* Fixes a bug in the http client where a crash may occur in the event certain tls verification errors are observed

http: Fix double call to stop() in http::client

---

src/v/redpanda/admin/server.cc
src/v/redpanda/admin/server.h
tests/rptest/tests/log_level_test.py

This PR fixes this two behaviors
one logger expiration could shadow another logger expiration
`log-level set kafka -l trace -e 30`
`log-level set raft -l trace -e 30`
.. 30+ secs later
`log-level get kafka -> info`
`log-level get raft -> trace` <- not being reset
both loggers are reset correctly
`log-level set kafka -l trace -e 30`
`log-level set raft -l trace -e 30`
.. 30+ secs later
`log-level get kafka -> info`
`log-level get raft -> info` <- correctly reset
a logger expiration could influence a subsequent request to set a level without expiration 
note: this case in practice is probably never triggered, since the only level that shows anomalous behavior is `error` and `warn`, and they are not levels that are normally used
`log-level set raft -l trace -e 30`
`log-level set raft -l …

[CORE-96]: admin/server fix set_log_level handling of overlapping expirations

---

src/v/utils/file_io.cc

ss::output_stream internally keeps track of in-flight exceptions. In the close() method, it will close the underlying ss::file and rethrow the exception.
ss::with_file_close_on_failure will too close the underlying ss::file if the future fails, this can result in a double close triggering an assertion like
```
seastar-prefix/src/seastar/include/seastar/core/future.hh:1917: future<T> seastar::promise<>::get_future() [T = void]: Assertion `!this->_future && this->_state && !this->_task' failed
```
This unit test shows how this assert could be triggered, if ss::output_stream as an active exception:
```cpp
SEASTAR_THREAD_TEST_CASE(test_with_file_close_on_failure) {
auto flags = ss::open_flags::rw | ss::open_flags::create
| ss::open_flags::truncate;
ss::with_file_close_on_failure( …
```

[CORE-2814]: utils/file_io: fix double closing of ss::file in write_fully

---

src/v/pandaproxy/api/api-doc/schema_registry.json
src/v/pandaproxy/schema_registry/handlers.cc
src/v/pandaproxy/schema_registry/sharded_store.cc
src/v/pandaproxy/schema_registry/sharded_store.h
tests/rptest/tests/schema_registry_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18391

[v24.1.x] [CORE-2831] schema_registry: Allow deleted=true for post_subject

---

cmake/dependencies.cmake
src/go/kreq-gen/go.mod
src/v/net/probes.cc

The open source build is currently failing because of various errors.
1. We need to upgrade the seastar version used by the open source build to match what we use in the vtools-based build.
2. We need to downgrade the golang version used by kreq-gen to 1.21
3. We need to prevent seastar from upgrading the C++ version used by the build.
The open source build is that it tries to use golang version 1.21 to build kreq-gen because that is what is available on `ubuntu:mantic` and `fedora:38`. Unfortunately, we can't upgrade to the newer OS yet because that would upgrade clang to clang-18 as well, which we are not ready for. So for the meantime, I have reverted to using go v1.21 for kreq-gen.
Fixes https://redpandadata.atlassian.net/browse/CORE-2708
* none

CORE-2708 - chore: fix open source CI build

---

src/go/rpk/pkg/adminapi/api_partition.go
src/go/rpk/pkg/cli/cluster/partitions/partitions.go
src/go/rpk/pkg/cli/cluster/partitions/transfer_leadership.go

Fixes https://github.com/redpanda-data/redpanda/issues/17418
In this implementation, I decided to make the functionality simple for a start. In #17418, I reckoned to support `--partition` and `--from` options, but only `--partition` flag is supported at this moment. 
Here's the help text:
```
This command allows you to transfer leaderships for given partitions.
To move a leadership, use the following syntax:
rpk cluster partitions transfer-leadership foo --partition 0:2
Here, the command transfers the leadership for the partition "kafka/foo/0"
to broker 2. By default, it assumes the "kafka" namespace, but you can specify
an internal namespace using the "{namespace}/" prefix.
The following command transfers the leadership for the partition "kafka/foo/0"
to broker 2 and the leadership for …
```

rpk: add transfer-leadership command

---

src/v/cluster/controller_backend.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18021 
Fixes https://github.com/redpanda-data/redpanda/issues/18040

[v23.2.x] c/controller_backend: try to force-abort reconfiguration only on leaders

---

src/v/raft/consensus.cc
src/v/raft/vote_stm.cc
src/v/raft/vote_stm.h

In vote stm we didn't mark the vote replies with greater term as not granted votes. This may lead to unnecessary leader elections and longer recovery after failures. Change the logic in `vote_stm` to explicitly mark vote responses with greater term as failed. Additional check was added in consensus to recognise if a candidate state changed in between the pre-vote and vote phase.
- Made electing a leader faster

Do not request votes if term changed in prevote phase

---

src/v/net/probes.cc

`char_traits<unsigned T>` is deprecated in LLVM 18, slated for removal in LLVM 19. Having replaced the only instance of `basic_sstring<unsigned>` in seastar with a `vector<byte>`, we need to account for that change here.
Requires redpanda-data/seastar: d96474c6a96919b4f260dbd5ba22827948c4e000
* none

net/probes: Expect vector<byte> from cert_info

---

src/v/archival/tests/archival_service_fixture.h
src/v/archival/tests/service_fixture.cc
src/v/cloud_storage/tests/common_def.h
src/v/cluster/tests/idempotency_tests.cc
src/v/cluster/tests/rebalancing_tests_fixture.h
src/v/cluster/tests/serialization_rt_test.cc
src/v/compat/raft_generator.h
src/v/kafka/protocol/tests/batch_reader_test.cc
src/v/kafka/server/tests/fetch_test.cc
src/v/kafka/server/tests/topic_recreate_test.cc
src/v/model/tests/random_batch.cc
src/v/model/tests/random_batch.h
src/v/raft/tests/append_entries_test.cc
src/v/raft/tests/configuration_serialization_test.cc
src/v/raft/tests/foreign_entry_test.cc
src/v/raft/tests/raft_group_fixture.h
src/v/raft/tests/term_assigning_reader_test.cc
src/v/raft/tests/type_serialization_tests.cc
src/v/storage/mvlog/tests/batch_collecting_stream_utils_test.cc
src/v/storage/mvlog/tests/segment_appender_test.cc
src/v/storage/mvlog/tests/segment_io_test.cc
src/v/storage/opfuzz/opfuzz.cc
src/v/storage/tests/log_manager_test.cc
src/v/storage/tests/log_replayer_test.cc
src/v/storage/tests/log_segment_reader_test.cc
src/v/storage/tests/offset_assignment_test.cc
src/v/storage/tests/produce_consume_test.cc
src/v/storage/tests/storage_e2e_test.cc
src/v/storage/tests/storage_test_fixture.h
src/v/storage/tests/utils/disk_log_builder.cc

Yield periodically to ensure that when replicating large payloads (with lots of batches), reactor is not stalled. Adds some additional debug logging in raft fixture that attempts leader retries.
(probably) fixes https://github.com/redpanda-data/redpanda/issues/18329
* none

tests/random: futurize make_random_batches

---

.github/workflows/lint-sh.yml

Adds missing path to shell linter GHA workflow
* none

Add missing paths to GHA shell linter workflow

---

src/v/test_utils/CMakeLists.txt
src/v/test_utils/gtest_main.cc
src/v/test_utils/gtest_utils.cc
src/v/test_utils/gtest_utils.h
src/v/test_utils/tests/gtest_test.cc

This adds a utility method to get the pathname for a directory that should be uniquely used by a single test case iteration.
I intend on using this for unit testing the new storage layer, as it helps prevent failed or crashed tests from interfering with other tests (e.g. some tests may expect an empty directory, which may not be the case if tests reuse the same directory but crash before cleaning up).
* none

test_utils: utility for getting a test directory

---

.github/CODEOWNERS

Add documentation team as CODEOWNERS of Swagger.
* none

[CORE-2952] Add docs as CODEOWNERS for Swagger

---

src/transform-sdk/rust/sr-sys/src/lib.rs
src/transform-sdk/rust/sr-sys/src/stub_abi.rs

n/a
* Unbreak building `sr-sys` crate for `wasm32-wasi` target
n/a
n/a

Wrap certain `wasm32-wasi` ABI unsafe calls in `unsafe` to fix the build.

---

tests/rptest/tests/cpu_stress_injection_test.py

The test could previously fail after enabling stress fibers because the admin endpoint could become unresponsive with heavy stress. This commit attempts to fix this in a couple ways:
- ignoring errors when enabling stress fibers: the tests condition on seeing a specific log line to ensure stress is enabled so the response from the HTTP endpoint doesn't matter for the correctness of the test
- retrying on failure when trying to stop stress fibers
Fixes #13701
* none

rptest: be more permissive with errors in stress fibers test

---

src/v/kafka/server/tests/fetch_test.cc

Drift in seastar lowres clock may lead to situation in which a leader election will not trigger in 1.5 seconds. Increased a wait for leader timeout to eliminate test spurious failures.
Fixes: #17943
Fixes: #18059
- none

t/fetch_test: wait longer for leadership after stepping down

---

tests/rptest/tests/nodes_decommissioning_test.py

In the `test_decommissioning_rebalancing_node` test case we check if a node that joined the cluster and have some partitions assigned to it in the process of data rebalancing can be successfully decommissioned.
The test was flaky as sometimes all the partition rebalance actions were finished before we validated if rebalance started.
Added a condition to make sure that we wait for more data before adding the node to cluster to make sure rebalance will last long enough for the decommission to interrupt it.
Fixes: #13522
- none

tests: wait for messages before adding a node to cluster

---

src/v/storage/mvlog/CMakeLists.txt
src/v/storage/mvlog/file.cc
src/v/storage/mvlog/file.h
src/v/storage/mvlog/tests/CMakeLists.txt
src/v/storage/mvlog/tests/file_test.cc

Adds a barebones abstraction around the io:: paging abstractions that
looks more like a file, with the goal in mind to abstract away the
details of the underlying io:: subsystem.
For now, this file abstraction supports appends, reads, and various file
lifecycle operations, which is enough to get started using it in
development of the new local log.
This begins to address https://github.com/redpanda-data/redpanda/issues/17566 but doesn't address if fully. More work will be needed to flesh out concurrency, flushes, etc.
* none

mvlog: wrap pager with file abstraction

---

src/v/cloud_storage/materialized_resources.cc

When setting read-path tput limit increase disk limit by 6%
Fixes #14139 
After the Seastar update the throttling test started to fail because disk limit is now more strict. This PR relaxes the limit a bit so the network could be throttled in the test. This should also improve observability a bit because Seastar does not expose any disk throttling metrics but we do have network throttling metrics. By having disk limit slightly higher we will be always hitting throttling in our net layer which has better metrics. There should be no impact for anything else.
* none

cloud_storage: Increase disk tput limit a bit

---

src/go/rpk/pkg/cli/cluster/info.go

Related https://github.com/redpanda-data/docs/pull/493
This PR renames the file from `metadata` to `info`. 
Change the main command from metadata to info, so it appears in the available commands list.
Add metadata as an alias.
* none

rpk: rename cluster metadata to info

---

install-dependencies.sh
tools/docker/Dockerfile

Changes to make public cpp toolchain dockerfile image portable on ubuntu and fedora
* none

tools: tweaks to make public build dockerfile portable between fedora/ubuntu distros

---

src/go/rpk/pkg/adminapi/api_transform.go
src/go/rpk/pkg/cli/transform/meta.go
src/go/rpk/pkg/cli/transform/transform.go
src/v/cluster/plugin_frontend.cc
src/v/cluster/plugin_frontend.h
src/v/model/transform.cc
src/v/model/transform.h
src/v/redpanda/admin/api-doc/transform.json
src/v/redpanda/admin/server.h
src/v/redpanda/admin/transform.cc
src/v/transform/api.cc
src/v/transform/include/transform/api.h
src/v/transform/tests/transform_manager_test.cc
src/v/transform/transform_manager.cc
tests/rptest/clients/rpk.py
tests/rptest/services/admin.py
tests/rptest/tests/data_transforms_test.py

Introduce an Admin API endpoint for patching transform metadata
- update environment vars with PUT semantics
- pause/resume transform
Also adds rpk experience for pause/resume (no env manipulation for now)
TODO:
- Went with a patch-like endpoint instead
Docs issue: https://github.com/redpanda-data/documentation-private/issues/2437
Closes CORE-1653
* Adds the ability to pause a deployed data transform w/o removing it from the system

PUT /v1/transform/{name}/meta

---

tests/rptest/clients/kubectl.py
tests/rptest/services/redpanda.py

Since _local_cmd now returns str instead of bytes,
update get_node_disk_free with proper symbol types.
Also update type hints for exec function
* none

PESDLC-1362 Update type hints and change char type to str

---

src/v/storage/kvstore.h

In an effort to move to fragmented data structures, the `absl::btree_map` type used in the `kvstore` is now replaced by a `chunked_hash_map`.
We do not rely on the ordering or any sort of pointer/reference/iterator stability provided by `absl::btree_map` in our current uses of `_db`, so this is a painless swap.
Fixes #15906
Fixes #10744 
* none

storage: change map type for `_db` in `kvstore`

---

src/v/cluster/scheduling/types.cc
src/v/cluster/topic_table.cc
src/v/cluster/topic_table.h
src/v/cluster/topics_frontend.cc
src/v/utils/exceptions.h
src/v/utils/stable_iterator_adaptor.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/18305

[v23.3.x] Fix some concurrent memory access problems in partition balancer

---

src/v/cloud_storage/types.cc
src/v/cloud_storage_clients/client_pool.cc
src/v/cloud_storage_clients/configuration.cc
src/v/cloud_storage_clients/configuration.h
src/v/cloud_storage_clients/s3_client.cc
src/v/cloud_storage_clients/s3_client.h
src/v/cloud_storage_clients/test_client/s3_test_client_main.cc
src/v/config/configuration.cc
src/v/config/configuration.h
src/v/redpanda/tests/fixture.h
tests/rptest/tests/cluster_self_config_test.py

Allows the `s3_client` to self configure its addressing style for S3 requests.
If `cloud_storage_url_style` is not specified (left `nil` in cluster config), upon start-up, the `s3_client` will attempt to self configure a working addressing style.
First, `virtual_host` addressing is tested. 
* A `list_objects()` request using is attempted, if `cloud_storage_enable_remote_read` is `true`. 
* If `cloud_storage_enable_remote_write` is enabled, `put_object()` and `delete_object()` requests are used to verify instead.
If the request is unsuccessful, the client reattempts the request with `path` style. If both requests fail, start-up is terminated.
JIRA Issue: https://redpandadata.atlassian.net/browse/CORE-2417
* none

CORE-2417: cloud_storage_clients: self configure `s3_url_style`

---

src/v/cluster/distributed_kv_stm.h
src/v/cluster/tests/CMakeLists.txt
src/v/cluster/tests/distributed_kv_stm_tests.cc
src/v/cluster/tests/id_allocator_stm_test.cc
src/v/raft/tests/raft_fixture.h

As part of deprecating simple_raft_fixture in favour of `raft_fixture`, making `distributed_kv_stm_tests` to use the latter. 
To avoid code duplication here and in future when porting further tests, a new test fixture template was created. It is a raft fixture equipped with one or multiple replicated STMs, and it provides a helper function to call STM functions on the leader node.
A minor change was made to the tested code in a separate commit.
* none

Base distributed_kv_stm_tests on raft fixture

---

src/v/cluster/partition_balancer_planner.cc
tests/rptest/tests/end_to_end.py
tests/rptest/tests/partition_balancer_test.py

Previously, we finished counts rebalance if no new moves could be found, even when some partitions were not moveable. This could lead to finishing too early and not achieving balanced distribution when many partitions were not moveable (e.g. because they are disabled due to recovery mode).
* Don't mark partition rebalance complete if some partitions are not moveable (e.g. due to partial recovery mode)

CORE-1972 don't mark rebalance complete if some partitions are not moveable

---

src/v/kafka/server/connection_context.cc
src/v/kafka/server/connection_context.h
src/v/kafka/server/request_context.h
src/v/utils/xid.cc
src/v/utils/xid.h
tests/rptest/tests/connection_virtualizing_test.py
tests/rptest/tests/vcluster_topic_property_test.py
tests/rptest/utils/xid_utils.py

Previously Redpanda virtualized Kafka connections based on the full
client_id string and the string was used as a client id in all
downstream processing.
Change the parsing logic to add context to the parsed client id.
The client id format expected by Redpanda has the following structure:
```
[vcluster_id][connection_id][actual client id]
```
where:
`vcluster_id` - string encoded XID representing virtual cluster
(20 characters)
`connection_id` - hex encoded 32 bit integer representing virtual
connection id (8 characters)
`client_id` - standard protocol defined client id
If Redpanda fails to parse the client id while working with virtualized
connections the whole connection is closed.
- none

Made client id parsing vcluster aware

---

src/v/cluster/partition_balancer_planner.cc
tests/rptest/tests/end_to_end.py
tests/rptest/tests/partition_balancer_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18489

[v24.1.x] CORE-1972 don't mark rebalance complete if some partitions are not moveable

---

.github/workflows/comment_added.yml
.github/workflows/jira_issue_manage.yml
.github/workflows/scripts/jira_helper.py

GH markdown is very different than Jira's.  Luckily pandoc exists and can be used to reformat issue and comment body text.
* None

gh: Now using pandoc to format issues

---

src/v/storage/kvstore.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/18499
Fixes: https://github.com/redpanda-data/redpanda/issues/18501, Fixes: https://github.com/redpanda-data/redpanda/issues/18502,

[v24.1.x] storage: change map type for `_db` in `kvstore`

---

cmake/testing.cmake
install-dependencies.sh

Fedora's default OpenSSL config file has some weird stuff in there that conflicts with OpenSSL 3.  For now, just set OPENSSL_CONF to /dev/null
* None

cmake: FIxup for OpenSSL command on Fedora

---

tests/rptest/tests/controller_erase_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/16495
Fixes: https://github.com/redpanda-data/redpanda/issues/18524,

[v23.2.x] tests: disable snapshots when testing partial controller deletion

---

src/v/archival/ntp_archiver_service.cc

When the archiver is created there is a small window of opportunity for it to run some housekeeping jobs before the manifest is synced. This commit disables the housekeeping jobs in the constructor to avoid this.
Fixes #18482 
Fixes #18386
Fixes #18385
Fixes #18384
Fixes #18381
Fixes #18312
Fixes #18254
Fixes #18031
Fixes #17986
Fixes #17916
Fixes #17753
Fixes #17752
Fixes #17510
Fixes #17412
Fixes #17366
Fixes #17364
Fixes #14221
Fixes #13995
* None

archival: Disable housekeeping jobs on startup

---

src/v/container/include/container/interval_set.h
src/v/container/tests/interval_set_test.cc
src/v/storage/mvlog/readable_segment.h
src/v/storage/mvlog/segment_appender.cc
src/v/storage/mvlog/segment_appender.h
src/v/storage/mvlog/segment_reader.cc
src/v/storage/mvlog/skipping_data_source.cc
src/v/storage/mvlog/skipping_data_source.h
src/v/storage/mvlog/tests/segment_appender_test.cc
src/v/storage/mvlog/tests/segment_io_test.cc
src/v/storage/mvlog/tests/segment_reader_test.cc
src/v/storage/mvlog/tests/skipping_data_source_test.cc

This PR includes a few small non-functional changes related to the mvlog.
- adds a size() call to the interval_set (not quite in mvlog subsystem, but it is the only user at the moment)
- migrates mvlog to use mvlog::file instead of io::pager and friends directly
- expands some test coverage
There are no functional changes in this PR.
* none

mvlog: miscellaneous non-functional changes

---

tests/rptest/tests/cloud_storage_scrubber_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18472
Fixes: https://github.com/redpanda-data/redpanda/issues/18558, Fixes: https://github.com/redpanda-data/redpanda/issues/18559,

[v24.1.x] cst/ducktape: Accept errors due to gap in manifest

---

src/v/cluster/partition_balancer_planner.cc
tests/rptest/tests/end_to_end.py
tests/rptest/tests/partition_balancer_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18489 
Fixes https://github.com/redpanda-data/redpanda/issues/18517

[v23.3.x] CORE-1972 don't mark rebalance complete if some partitions are not moveable

---

src/v/cluster/cloud_metadata/tests/cluster_recovery_backend_test.cc

The test was previously flaky because it reset all configs immediately after restarting the application, which could race with initialization of some cloud storage services. Instead, we'll now only reset the specific that the test conditions on.
Fixes #17813
* none

cluster_recovery_backend_test: only reset relevant config

---

src/v/archival/ntp_archiver_service.cc
src/v/archival/tests/archival_service_fixture.h
src/v/archival/tests/service_fixture.cc
src/v/archival/types.cc
src/v/archival/types.h
src/v/cloud_storage/async_manifest_view.cc
src/v/cloud_storage/async_manifest_view.h
src/v/cloud_storage/remote_partition.cc
src/v/cloud_storage/tests/async_manifest_view_test.cc
src/v/cloud_storage/tests/remote_partition_test.cc
src/v/cloud_storage/tests/util.cc
src/v/cloud_storage/tests/util.h
src/v/kafka/server/replicated_partition.cc
src/v/redpanda/tests/fixture.h
tests/rptest/tests/timequery_test.py
tests/rptest/util.py

The meat of the PR:
Tiered Storage physically has a superset of the addressable data. This
can be caused at least by the following: a) trim-prefix, b) retention
being applied but garbage collection not finishing yet.
For offset queries this isn't problematic because the bounds can be
applied at higher level. In particular, partition object does validate
that offset is in range before passing control to the remote partition.
For timequeries prior to this commit such bounds were not enforced
leading to a bug where cloud storage would return an offset -1 (no data
found) in result when there actually was data or returning a wrong
offset.
Wrong offset: it would be returned because reads could have started prior
to the partition visible/addressable offset. E.g. after retention was
applied but …

Fix timequery not returning results when racing with archival retention and gc

---

src/v/kafka/server/connection_context.cc
src/v/kafka/server/connection_context.h
src/v/kafka/server/quota_manager.cc
src/v/kafka/server/quota_manager.h
src/v/kafka/server/snc_quota_manager.cc
src/v/kafka/server/snc_quota_manager.h
tests/rptest/tests/cluster_quota_test.py

Quota enforcement is currently done in a complicated and
not-Kafka-compatible way in Redpanda, and this intends to fix
that.
In Kafka >=2.0, client throttling is implemented in a simple way.
Brokers are meant to return how long the client is supposed to be
throttled when there is a quota violation. Then, the Kafka client is
supposed to wait until this throttling time passed, or else the broker
applies the throttle on its side.
However, currently in Redpanda the delay is enforced differently. For
produce, we enforce the throttle we would send in the response if there
was a throttle in the last response (regardless of whether the client
obeyed that throttle or not). For fetch, we always enforce the current
throttle. For ingress/egress quotas we correctly track how long the
client was …

CORE-2752 - Fix Kafka quota throttling delay enforcement

---

.github/workflows/buildkite-slash-commands.yml
.github/workflows/slash-commands.yml

registers the `/rp-unit-test` slash command so it can trigger the steps as implemented in PR https://github.com/redpanda-data/vtools/pull/2753
* none

register `/rp-unit-test` github slash command

---

src/v/cluster/id_allocator.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/17892
Fixes: https://github.com/redpanda-data/redpanda/issues/17897,

[v23.3.x] id_allocator: do not forward requests beyond first hop

---

tests/rptest/tests/nodes_decommissioning_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18426
Fixes: https://github.com/redpanda-data/redpanda/issues/18485,

[v23.3.x] tests: wait for messages before adding a node to cluster

---

src/v/redpanda/admin/server.cc
src/v/redpanda/admin/server.h
tests/rptest/tests/log_level_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18397

[v23.3.x] [CORE-96]: admin/server fix set_log_level handling of overlapping expirations

---

src/v/kafka/server/connection_context.cc
src/v/kafka/server/connection_context.h
src/v/kafka/server/quota_manager.cc
src/v/kafka/server/quota_manager.h
src/v/kafka/server/snc_quota_manager.cc
src/v/kafka/server/snc_quota_manager.h
tests/rptest/tests/cluster_quota_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18218

[v24.1.x] CORE-2752 - Fix Kafka quota throttling delay enforcement

---

src/v/net/CMakeLists.txt
src/v/net/connection.cc
src/v/net/probes.cc

Removes use of GnuTLS from `net`.  Uses instead the error codes exposed from Seastar.
* None

CORE-2425 add additional tls error codes

---

src/v/kafka/server/connection_context.cc
src/v/kafka/server/connection_context.h
src/v/kafka/server/request_context.h
src/v/utils/xid.cc
src/v/utils/xid.h
tests/rptest/tests/connection_virtualizing_test.py
tests/rptest/tests/vcluster_topic_property_test.py
tests/rptest/utils/xid_utils.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18464

[v24.1.x] Made client id parsing vcluster aware

---

src/v/storage/mvlog/tests/file_test.cc

I noticed that death tests were leaving behind some directories, even
though the test appears to be exiting successfully.
It turns out that because death tests run a separate process[1], it was
creating an extra directory, but not running the teardown because of the
process crash.
So this hacks the tests to clean up in the test body before the crash.
[1] https://github.com/google/googletest/blob/main/docs/advanced.md#death-tests-and-threads
* none

mvlog/tests: clean up files in test body

---

src/v/cluster/producer_state.cc
src/v/cluster/producer_state.h
src/v/cluster/rm_stm.cc
src/v/cluster/rm_stm.h
src/v/cluster/rm_stm_types.cc
src/v/cluster/rm_stm_types.h
src/v/cluster/tests/producer_state_tests.cc
src/v/cluster/tests/randoms.h
src/v/cluster/tests/rm_stm_test_fixture.h
src/v/cluster/tests/rm_stm_tests.cc
src/v/kafka/server/handlers/describe_producers.cc

As I was prototyping the port I identified some things that could facilitate an easier porting, factoring those fixes out into this separate PR for reviewers' convenience. 
* none

rm_stm: prepping for log_state port

---

src/v/kafka/server/connection_context.cc
src/v/kafka/server/connection_context.h
src/v/kafka/server/quota_manager.cc
src/v/kafka/server/quota_manager.h
src/v/kafka/server/snc_quota_manager.cc
src/v/kafka/server/snc_quota_manager.h
tests/rptest/tests/cluster_quota_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18218 
Fixes https://github.com/redpanda-data/redpanda/issues/18569
Fixes https://redpandadata.atlassian.net/browse/CORE-3019

[v23.3.x] CORE-2752 - Fix Kafka quota throttling delay enforcement

---

tests/rptest/services/machinetype.py

Required for n2-standard based T5/6
* none

test: Add n2-standard-16 machinetype

---

src/v/archival/ntp_archiver_service.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18526
Fixes: https://github.com/redpanda-data/redpanda/issues/18533, Fixes: https://github.com/redpanda-data/redpanda/issues/18535, Fixes: https://github.com/redpanda-data/redpanda/issues/18537, Fixes: https://github.com/redpanda-data/redpanda/issues/18539, Fixes: https://github.com/redpanda-data/redpanda/issues/18541, Fixes: https://github.com/redpanda-data/redpanda/issues/18543, Fixes: https://github.com/redpanda-data/redpanda/issues/18533, Fixes: https://github.com/redpanda-data/redpanda/issues/18587, Fixes: https://github.com/redpanda-data/redpanda/issues/18589, Fixes: https://github.com/redpanda-data/redpanda/issues/18549, Fixes: https://github.com/redpanda-data/redpanda/issues/18551, Fixes: …

[v23.3.x] archival: Disable housekeeping jobs on startup

---

tests/rptest/perf/openmessaging_perf_test.py
tests/rptest/perf/small_batches_test.py
tests/rptest/perf/ts_read_openmessaging_test.py
tests/rptest/perf/ts_write_openmessaging_test.py

This PR modifies the existing perf CDT tests to use a much small 3x  `im4gn.xlarge`. The hope of doing this is to allow us to run more regression tests at the same cost as the existing tests.
* none

Modify perf CDT tests to use the `im4gn.xlarge` instance type

---

tests/rptest/tests/archive_retention_test.py

The `retention_value` for `retention.bytes` in
`archive_retention_test.test_delete` was being set to a value of `1KiB` by default. Sometimes, a segment smaller than `1KiB` would be produced, and thus would not be garbage collected.
The `retention_value` is now set using the minimum segment size to ensure all segments are properly deleted per the expectations of the test.
Fixes #13841.
* none

[CORE-1478] rptest: fix retention value in `archive_retention_test`

---

install-dependencies.sh

Minor tweak to make dependencies work on fedora 40.
* none

deps: change name of regel package on RPM distros

---

src/v/kafka/server/fetch_session.h
src/v/kafka/server/fetch_session_cache.cc
src/v/kafka/server/handlers/fetch.cc
src/v/kafka/server/tests/fetch_plan_bench.cc
src/v/kafka/server/tests/fetch_session_test.cc
src/v/kafka/server/tests/fetch_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/17674

[v23.3.x] k/fetch: handle initial_leader_epoch correctly

---

tests/rptest/tests/topic_recovery_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18603

[v24.1.x] tests: fix replaced segments accounting in TopicRecoveryTest

---

src/v/cluster/tests/CMakeLists.txt
src/v/cluster/tests/distributed_kv_stm_tests.cc
src/v/cluster/tests/id_allocator_stm_test.cc
src/v/cluster/tests/tm_stm_tests.cc
src/v/raft/tests/CMakeLists.txt
src/v/raft/tests/mux_state_machine_test.cc
src/v/raft/tests/raft_fixture.h

Improve raft_fixture and stm_raft_fixture, base mux_state_machine_test and  tm_stm_tests on them.
* none

base tests on raft_fixture

---

src/go/rpk/pkg/cli/cloud/login.go
src/go/rpk/pkg/cli/profile/create.go
src/go/rpk/pkg/cli/topic/consume.go
src/go/rpk/pkg/cli/transform/deploy.go

This PR addresses a couple of small fixes:
- Missing new line for `rpk cloud login` when you attempted to log in and had an `rpk-container` profile.
- Change the error checking for empty organizations in the login flow
- Removes unnecessary `[WASM]` input help text in `rpk transform deploy`
- Fixes a regression in the `--regex` flag in `rpk topic consume`
Fixes #18602 
* rpk: fixes an error in `rpk topic consume` that prevented the usage of the `--regex` flag.

rpk: small fixes.

---

src/v/raft/state_machine_manager.cc
src/v/raft/state_machine_manager.h
src/v/raft/tests/stm_manager_test.cc
src/v/raft/tests/stm_test_fixture.h

Do not allow reading beyond next offset  In state machine manager the background apply fiber is there to apply  batches to state machines which are behind the main apply fiber. The  background apply fiber is only active if an stm is behind what is  currently being applied by the main fiber. A bug in reader configuration  lead to a situation in which a background apply could read up to `_next`  offset of the state machine manager leading to the situation in which a  stm `last_applied_offset` is equal to `_next` therefore the stm next  offset is actually equal to `state_machine_manager::_next + 1`. This  lead to a situation in which there may be no stms suitable to be  handled in main apply fiber but also they are not recoverable by  background apply fiber as their `_next` offset is greater …

Fixed `state_machine_manager` stall

---

src/v/raft/consensus.cc
src/v/raft/prevote_stm.cc
src/v/raft/prevote_stm.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/18394

[v23.3.x] Do not request votes if term changed in prevote phase

---

src/v/raft/state_machine_manager.cc
src/v/raft/state_machine_manager.h
src/v/raft/tests/stm_manager_test.cc
src/v/raft/tests/stm_test_fixture.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/18626

[v24.1.x] Fixed `state_machine_manager` stall

---

src/v/utils/file_io.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18303
Fixes: https://github.com/redpanda-data/redpanda/issues/18439,

[v24.1.x] [CORE-2814]: utils/file_io: fix double closing of ss::file in write_fully

---

src/v/http/client.cc
src/v/http/include/http/client.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/18304

[v24.1.x] http: Fix double call to stop() in http::client

---

src/v/cluster/producer_state.cc
src/v/cluster/producer_state.h
src/v/cluster/producer_state_manager.cc
src/v/cluster/producer_state_manager.h
src/v/cluster/rm_stm.cc
src/v/cluster/tests/producer_state_tests.cc
src/v/cluster/tests/rm_stm_test_fixture.h
src/v/cluster/tests/rm_stm_tests.cc
src/v/raft/tests/simple_raft_fixture.h

On a cluster with a large pile up of historical producer_ids, a sudden down scale of the configuration resulted in crashes.
* eviction logic spins up too many concurrent tasks in the same scheduling point (in this case its > 1M) and that is resulting in a 16MB allocation in the reactor path.
* Loading too many snapshots at once (during bootstrap) was causing a big spike in memory usage and we can potentially save some memory by aggressively releasing any unused memory from the snapshot structures that are already loaded in the desired destination..
TBD: Link GH issues.

rm_stm: couple of stability fixes noticed when down scaling max_concurrent_producer_ids

---

src/v/pandaproxy/schema_registry/configuration.cc

schema_registry: Make mode_mutability: true by default
* none

schema_registry: Make mode_mutability: true by default

---

src/v/cloud_storage/tests/CMakeLists.txt
src/v/cloud_storage/tests/anomalies_detector_test.cc
src/v/cloud_storage/tests/cloud_storage_fixture.h
src/v/cloud_storage/tests/remote_file_test.cc
src/v/cloud_storage/tests/remote_partition_fuzz_test.cc
src/v/cloud_storage/tests/remote_partition_test.cc
src/v/cloud_storage/tests/remote_segment_test.cc
src/v/cloud_storage/tests/remote_test.cc
src/v/cloud_storage/tests/s3_imposter.cc
src/v/cloud_storage/tests/s3_imposter.h
src/v/cloud_storage/tests/topic_recovery_service_test.cc
src/v/cloud_storage/tests/util.cc
src/v/redpanda/tests/fixture.h
src/v/test_utils/test_macros.h
tests/rptest/services/redpanda.py
tests/rptest/tests/archival_test.py
tests/rptest/tests/read_replica_e2e_test.py
tests/rptest/tests/tiered_storage_model_test.py

Adds path-style test coverage to existing tiered storage fixture and ducktape tests.
JIRA Issues: 
- https://redpandadata.atlassian.net/browse/CORE-2153
- https://redpandadata.atlassian.net/browse/CORE-2154
- https://redpandadata.atlassian.net/browse/CORE-2155
- https://redpandadata.atlassian.net/browse/CORE-2156
- https://redpandadata.atlassian.net/browse/CORE-2416
* none

CORE-2154: cloud_storage: path-style verification tests

---

src/go/rpk/pkg/cli/topic/describe.go

`rpk topic describe` now supports multiple topics and also regex. 
If multiple topics are specified or matched, print all sections to distinguish the output.
Examples:
```
describe foo bar            # describe topics foo and bar
describe -r '^f.*' '.*r$'   # describe any topic starting with f and any topics ending in r
describe -r '*'             # describe all topics
describe -r .               # describe any one-character topics
```
Fixes https://github.com/redpanda-data/redpanda/issues/18152
* rpk: topic describe supports `--regex` flag

rpk: topic describe supports --regex flag

---

src/go/rpk/pkg/cli/cloud/login.go
src/go/rpk/pkg/cli/profile/create.go
src/go/rpk/pkg/cli/topic/consume.go
src/go/rpk/pkg/cli/transform/deploy.go

Backport of PR https://github.com/redpanda-data/redpanda/pull/18628
Fixes: https://github.com/redpanda-data/redpanda/issues/18633,

[v23.3.x] rpk: small fixes.

---

src/v/cloud_storage/types.cc
src/v/cloud_storage_clients/tests/CMakeLists.txt
src/v/cloud_storage_clients/tests/types_test.cc
src/v/cloud_storage_clients/types.h
src/v/config/configuration.cc
src/v/config/configuration.h
src/v/config/convert.h
src/v/config/property.h
src/v/config/rjson_serialization.cc
src/v/config/rjson_serialization.h
src/v/config/types.h
src/v/redpanda/tests/fixture.h

Defines a new config::s3_url_style type and converts between this type and the cloud_storage_clients sub-system specific type.
* none

config: break dependency on cloud_storage_clients

---

src/v/crypto/ossl_context_service.cc
src/v/redpanda/application.cc

Was not using the correct instance of node_config when determining whether to put the OpenSSL context service into FIPS mode or not.
* None

app/crypto: Fixed issue with RP not going into FIPS mode

---

src/v/storage/mvlog/CMakeLists.txt
src/v/storage/mvlog/segment_identifier.h
src/v/storage/mvlog/tests/CMakeLists.txt
src/v/storage/mvlog/tests/active_segment_test.cc
src/v/storage/mvlog/versioned_log.cc
src/v/storage/mvlog/versioned_log.h

Introduces the beginnings of a log implementation that is able to roll
new segments with segment.bytes or segment.ms.
The log, similar to the disk_log_impl, is backed by a circular buffer of
segments, with the noteable difference that the active segment is
managed explicitly and separately from the others.
I'm not fully sold on this approach (e.g. vs only managing the segment
appender separately but keeping the underlying readable segment with the
rest of the segments), but for now it makes reasoning about segment
rolling concurrency a bit more straightforward, and down the line it
will make it easier to reason about segment removals (e.g. the active
segment cannot be removed).
This implementation is still missing quite a bit (e.g. it doesn't flush,
doesn't implement the exact log …

mvlog: log basics for segment rolls

---

src/v/redpanda/admin/server.cc
src/v/redpanda/admin/server.h
tests/rptest/tests/log_level_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18397

[v24.1.x] [CORE-96]: admin/server fix set_log_level handling of overlapping expirations

---

src/v/model/fundamental.h

This is similar to change introduced in
8c3777bb15df27a49d086e28dead63f5278946f7 but this time for kafka::offset.
Quoting from the previous commit message:
model::offset::max() is often used to indicate "no upper bound" on
operations. E.g. for tiered storage uploads[^1], for reading from local
storage[^2], etc.
We also do often convert from closed to opened offset intervals
representations. E.g. committed offset to LSO and the other way around.
When combined, these can result in unexpected behaviors. In particular,
if on a read path the max offset is specified as model::offset_max() but
at lower level this is converted into an exclusive offset by calling
next_offset(model::offset::max()), the result is model::offset::min()
aka -2^63.
This is dangerous. Let's instead saturate the offset …

model: make kafka::next_offset saturate rather than overflow

---

tests/rptest/archival/s3_client.py

This adds FileHandlers to boto3 loggers using
the same filenames and levels that is used in ducktape
Also, adds the logger name manually to easily identify
the source of the message next to the module name
* none

PESDLC-876 Add Filehandlers to boto3 loggers

---

src/go/rpk/pkg/cli/topic/describe.go

Backport of PR https://github.com/redpanda-data/redpanda/pull/18221
Fixes: https://github.com/redpanda-data/redpanda/issues/18645,

[v23.3.x] rpk: topic describe supports --regex flag

---

src/go/rpk/pkg/cli/topic/describe.go

Backport of PR https://github.com/redpanda-data/redpanda/pull/18221
Fixes: https://github.com/redpanda-data/redpanda/issues/18643,

[v24.1.x] rpk: topic describe supports --regex flag

---

src/go/rpk/pkg/cli/group/seek.go

It should be possible to set commits for a group that does not yet exist. This was not previously possible because the first thing rpk did when seeking was to query old offsets. If old offsets did not exist, rpk would exit with an error that offsets were unable to be fetched.
* It is now possible to use `rpk group seek` to set commits on a group that does not yet exist

rpk: allow seeking a non-existent group

---

src/go/rpk/pkg/cli/cloud/auth/create.go
src/go/rpk/pkg/cli/cloud/auth/rename.go
src/go/rpk/pkg/cli/cloud/byoc/byoc.go
src/go/rpk/pkg/cli/cluster/config/export.go
src/go/rpk/pkg/cli/cluster/config/import.go
src/go/rpk/pkg/cli/cluster/config/lint.go
src/go/rpk/pkg/cli/cluster/config/status.go
src/go/rpk/pkg/cli/cluster/partitions/unsafe_recover.go
src/go/rpk/pkg/cli/cluster/storage/recovery/start.go
src/go/rpk/pkg/cli/cluster/storage/recovery/status.go
src/go/rpk/pkg/cli/cluster/txn/describe.go
src/go/rpk/pkg/cli/cluster/txn/describe_producers.go
src/go/rpk/pkg/cli/container/purge.go
src/go/rpk/pkg/cli/container/start.go
src/go/rpk/pkg/cli/container/status.go
src/go/rpk/pkg/cli/container/stop.go
src/go/rpk/pkg/cli/debug/bundle/bundle.go
src/go/rpk/pkg/cli/generate/app.go
src/go/rpk/pkg/cli/generate/grafana.go
src/go/rpk/pkg/cli/generate/prometheus.go
src/go/rpk/pkg/cli/iotune/iotune.go
src/go/rpk/pkg/cli/redpanda/check.go
src/go/rpk/pkg/cli/redpanda/stop.go
src/go/rpk/pkg/cli/root.go
src/go/rpk/pkg/cli/security/role/describe.go
src/go/rpk/pkg/cli/security/user/list.go
src/go/rpk/pkg/cli/version/version.go

Cobra won't recognize unknown commands unless
cobra.NoArg is set as an Arg validation parameter
in the command definition.
This means that running 'rpk cluster unknowncommand'
won't return an 'unknown command' error, therefore,
exit as a successful command execution.
See: https://github.com/spf13/cobra/issues/706
Now, cobra will return an 'unknown error' and exit
with code 1.
Fixes #18627 
* rpk now will exit (1) when running rpk with unknown commands

rpk: add error for unknown command execution

---

src/go/rpk/pkg/cli/cloud/auth/create.go
src/go/rpk/pkg/cli/cloud/auth/rename.go
src/go/rpk/pkg/cli/cloud/byoc/byoc.go
src/go/rpk/pkg/cli/cluster/config/export.go
src/go/rpk/pkg/cli/cluster/config/import.go
src/go/rpk/pkg/cli/cluster/config/lint.go
src/go/rpk/pkg/cli/cluster/config/status.go
src/go/rpk/pkg/cli/cluster/partitions/unsafe_recover.go
src/go/rpk/pkg/cli/cluster/storage/recovery/start.go
src/go/rpk/pkg/cli/cluster/storage/recovery/status.go
src/go/rpk/pkg/cli/cluster/txn/describe.go
src/go/rpk/pkg/cli/cluster/txn/describe_producers.go
src/go/rpk/pkg/cli/container/purge.go
src/go/rpk/pkg/cli/container/start.go
src/go/rpk/pkg/cli/container/status.go
src/go/rpk/pkg/cli/container/stop.go
src/go/rpk/pkg/cli/debug/bundle/bundle.go
src/go/rpk/pkg/cli/generate/app.go
src/go/rpk/pkg/cli/generate/grafana.go
src/go/rpk/pkg/cli/generate/prometheus.go
src/go/rpk/pkg/cli/iotune/iotune.go
src/go/rpk/pkg/cli/redpanda/check.go
src/go/rpk/pkg/cli/redpanda/stop.go
src/go/rpk/pkg/cli/root.go
src/go/rpk/pkg/cli/security/role/describe.go
src/go/rpk/pkg/cli/security/user/list.go
src/go/rpk/pkg/cli/version/version.go

Backport of PR https://github.com/redpanda-data/redpanda/pull/18650
Fixes: https://github.com/redpanda-data/redpanda/issues/18675,

[v24.1.x] rpk: add error for unknown command execution

---

.gitignore

This is part of the "rpk connect" / "benthos" integration effort. Benthos aka rpk connect plugin will be built and bundled with Redpanda. During build workflows, we will checkout benthos code and build it. We will follow a similar pattern to vtools, where the cloned vtools repo is saved as redpanda/vtools.
Therefore benthos/ also needs to be .gitignore'd, just like vtools/. Otherwise goreleaser may complain that the local git repo is dirty and fail rpk build.
Companion vtools PR https://github.com/redpanda-data/vtools/pull/2787 (private).
TBD: needed if we decide to persist with the "bundle plugin with redpanda" model for rpk connect. This one is trivial to port (unlike the https://github.com/redpanda-data/vtools/pull/2787).
* none

[v24.1.x] ignore benthos local repo dir

---

src/v/raft/recovery_stm.cc

When on demand snapshot is taken it may be helpful to check the difference between configured learner start offset and current leader start offset.
- made fast partition movements easier to debug.

r/recovery_stm: log taking on demand snapshot at info level

---

src/v/raft/recovery_stm.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18680

[v23.3.x] r/recovery_stm: log taking on demand snapshot at info level

---

tests/rptest/services/redpanda.py

CDT fails during RC testing.  Suspicion is that `/var/lib/redpanda/.cache` exists.  It causes us to want to do `rm -r /var/lib/redpanda/*`, but the glob does not expand to hidden name like `.cache`.  rm explodes.  Not clear why this is happening now, but not before.
About 1400 failures during RC1 CDT:
https://buildkite.com/redpanda/redpanda/builds/49610#018fc0ea-2aab-4846-a112-67c1676793f3
```
[DEBUG - 2024-05-29 00:11:51,468 - remoteaccount - _log - lineno:183]: root@ip-172-31-9-170: Running ssh command: rm -r /var/lib/redpanda/*
[ERROR - 2024-05-29 00:11:51,515 - redpanda - clean_one - lineno:2488]: Error cleaning node ip-172-31-9-170:
File "/home/ubuntu/redpanda/tests/rptest/services/redpanda.py", line 2483, in clean_one
self.clean_node(node, …
```

[v24.1.x] CDT- remove /var/lib/redpanda/.cache before proceeding to clean regular entries

---

tests/rptest/archival/abs_client.py
tests/rptest/archival/s3_client.py
tests/rptest/clients/rpk.py
tests/rptest/perf/ts_read_openmessaging_test.py
tests/rptest/redpanda_cloud_tests/high_throughput_test.py
tests/rptest/redpanda_cloud_tests/omb_validation_test.py
tests/rptest/services/action_injector.py
tests/rptest/services/admin.py
tests/rptest/services/admin_ops_fuzzer.py
tests/rptest/services/cluster.py
tests/rptest/services/compatibility/example_base.py
tests/rptest/services/compatibility/example_runner.py
tests/rptest/services/openmessaging_benchmark.py
tests/rptest/services/openmessaging_benchmark_configs.py
tests/rptest/services/producer_swarm.py
tests/rptest/services/provider_clients/client_utils.py
tests/rptest/services/provider_clients/rpcloud_client.py
tests/rptest/services/redpanda.py
tests/rptest/services/redpanda_types.py
tests/rptest/utils/type_utils.py

Additional typing in rptest.
Most changes are pure typing, but there a few asserts etc added here and there to satisfy the type checking. No intentional functional changes.
* none

More typing 4

---

src/v/http/client.cc
src/v/http/client.h

Backport of https://github.com/redpanda-data/redpanda/pull/18304
- http::client::stop() can be called twice in the event the client is used via the `with_client` method.
- The method had unconditionally called stop() in a finally clause with the intention to have users not have to manually do this and forget to call stop.
- However stop() can also be called within certain exception handlers within methods invoked by http::client, ones that handle tls::verification_error exceptions.
- This patch adds a boolean to our http client so that stop() can early exit if it has already been called.
(cherry picked from commit 2ed203deceffa1d560cdee64131b88f302069318)
Fixes: https://redpandadata.atlassian.net/browse/CORE-2933
* Fixes a bug where crashes within the redpanda http client could occur when …

[v23.2.x] http: Fix double call to stop() in http::client

---

src/v/http/client.cc
src/v/http/client.h

Backport of https://github.com/redpanda-data/redpanda/pull/18304
- http::client::stop() can be called twice in the event the client is used via the `with_client` method.
- The method had unconditionally called stop() in a finally clause with the intention to have users not have to manually do this and forget to call stop.
- However stop() can also be called within certain exception handlers within methods invoked by http::client, ones that handle tls::verification_error exceptions.
- This patch adds a boolean to our http client so that stop() can early exit if it has already been called.
Fixes: https://redpandadata.atlassian.net/browse/CORE-2932
* Fixes a bug where crashes within the redpanda http client could occur when encountering tls exceptions

[v23.3.x] http: Fix double call to stop() in http::client

---

tests/rptest/tests/control_character_flag_test.py

- This upgrade test failed because the iterative upgrade through rp version loop wasn't waiting until the cluster active version had changed, between each install and upgrade of a new version.
- It therefore isn't enough to wait until all binaries report the desired version, but for the cluster logical version to also have been bumped.
- The solution is to use the already existing method `upgrade_through_versions` which properly waits between installs of the next redpanda version before starting another install and restart.
Fixes: https://redpandadata.atlassian.net/browse/CORE-2503
Fixes: https://redpandadata.atlassian.net/browse/CORE-2631
* none

[CORE-2503] Fix for CI failure: `ControlCharacterPermittedAfterUpgrade.test_upgrade_from_pre_v23_2`

---

src/v/kafka/server/quota_manager.cc
src/v/kafka/server/quota_manager.h
src/v/kafka/server/tests/quota_manager_test.cc

Client quota configuration is now dynamic.
Previously, changes to the rate would not be taken into account for existing tracked clients.
* Client qroup quotas now support dynamic configuration of the rate.

[CORE-2741] Client Quotas: support dynamic rate configuration

---

tests/rptest/tests/control_character_flag_test.py

[v23.3.x] Fix for failing tests in `control_character_flag_test.py`

---

src/go/rpk/pkg/cli/plugin_cmds.go

In #18650 we added Arg validations for every
comman and an automatic "walk" through the command space to add cobra.NoArgs.
Plugins were not taken into account, this commit
explicitly set the cobra.MinimumArg(0) to avoid
adding "NoArgs" on execution.
* none

rpk: explicitly add Arg validation to plugins

---

.gitignore

This is a forward port of https://github.com/redpanda-data/redpanda/pull/18663, which is needed for vtools build pipelines to function without complaints from goreleaser that the repo is dirty.
* none

[rpk connect] add /benthos to .gitignore

---

src/v/cloud_storage/cache_service.cc
src/v/redpanda/admin/server.cc

- Fixes incorrect ordering of arguments.
- Also adds some info-level logging of the requested arguments.
- Fixes a couple type conversions that incorrectly used stoi
* Fixes incorrect ordering of arguments in the cloud cache trim admin endpoint.

admin: fix cache trim parameter order

---

src/v/storage/mvlog/file_gap.h
src/v/storage/mvlog/readable_segment.cc
src/v/storage/mvlog/readable_segment.h
src/v/storage/mvlog/segment_reader.cc
src/v/storage/mvlog/segment_reader.h
src/v/storage/mvlog/tests/segment_reader_test.cc

Adds a gap set to the readable segment so that readers can iterate as
of a specific version.
The full set of gaps in the segment is long-lived, so this is owned by
the readable segment. Segment readers make of copy of this set (expected
to be small) when constructed, before iterating.
Longer term, multiple segments may have gaps added to them at a time,
but this commit focuses only on introducing the per-segment gaps.
* none

mvlog: add gaps to the segment reader

---

src/v/cloud_storage_clients/abs_client.cc
src/v/cloud_storage_clients/abs_error.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18700

[v23.3.x] cloud_storage_clients: check for `BlobNotFound` in `abs_client::do_delete_path()`

---

src/v/cloud_storage_clients/abs_client.cc
src/v/cloud_storage_clients/abs_error.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18700

[v24.1.x] cloud_storage_clients: check for `BlobNotFound` in `abs_client::do_delete_path()`

---

src/v/config/rjson_serialization.cc
src/v/config/tests/tls_config_convert_test.cc
src/v/config/tls_config.h
src/v/rpc/test/rpc_gen_cycling_test.cc
tests/rptest/services/redpanda.py
tests/rptest/services/templates/redpanda.yaml
tests/rptest/services/tls.py
tests/rptest/tests/crl_test.py

This PR adds the ability to configure Certificate Revocation Lists in redpanda along with a variety of tests and 
test infrastructure (the bulk of the change.
Closes CORE-2440
TODO:
- currently `std::nullopt` to make the `tls_config` constructor happy
- ~can't get it to pass locally (incl on `dev`), so I'm holding off for the moment~
- PUNT: https://redpandadata.atlassian.net/browse/CORE-3144
* Add an optional TLS config field for CRL (Certificate Revocation List)

CORE-2440 Add config for CRL and plumb it into seastar

---

tests/docker/ducktape-deps/client-swarm
tests/rptest/redpanda_cloud_tests/omb_validation_test.py
tests/rptest/services/producer_swarm.py
tests/rptest/services/redpanda_cloud.py
tests/rptest/tests/services_self_test.py
tests/rptest/tests/topic_creation_test.py

The thrust of these changes is to enhance OMBValidationTest.text_max_connections to be more reliable when testing high connection counts. Specifically to work around redpanda-data/redpanda#15475.
* none

Test changes to support increased connection counts

---

tests/rptest/tests/control_character_flag_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18695

[v24.1.x] [CORE-2503] Fix for CI failure: `ControlCharacterPermittedAfterUpgrade.test_upgrade_from_pre_v23_2`

---

src/v/cluster/CMakeLists.txt
src/v/cluster/client_quota_backend.cc
src/v/cluster/client_quota_backend.h
src/v/cluster/client_quota_frontend.cc
src/v/cluster/client_quota_frontend.h
src/v/cluster/client_quota_serde.h
src/v/cluster/client_quota_store.cc
src/v/cluster/client_quota_store.h
src/v/cluster/commands.h
src/v/cluster/controller.cc
src/v/cluster/controller.h
src/v/cluster/controller_snapshot.cc
src/v/cluster/controller_snapshot.h
src/v/cluster/controller_stm.cc
src/v/cluster/controller_stm.h
src/v/cluster/fwd.h
src/v/cluster/tests/client_quota_store_test.cc
src/v/kafka/server/handlers/alter_client_quotas.cc
src/v/kafka/server/handlers/describe_client_quotas.cc
src/v/kafka/server/request_context.h
src/v/kafka/server/server.cc
src/v/kafka/server/server.h
src/v/model/model.cc
src/v/model/record_batch_types.h
src/v/redpanda/application.cc
src/v/redpanda/tests/fixture.h

This adds a controller frontend/backend for the quota store, introduces the client quota controller commands and integrates the quota store and quota frontend into the controller and kafka server.
It also includes a small fixup cherry-pick of nits from the previous PR https://github.com/redpanda-data/redpanda/pull/18681.
Fixes https://redpandadata.atlassian.net/browse/CORE-2698
* none

CORE-2698 `quota_store` controller frontend/backend

---

src/v/archival/tests/archival_metadata_stm_gtest.cc
src/v/archival/tests/service_fixture.cc
src/v/cloud_storage/tests/anomalies_detector_test.cc
src/v/cloud_storage/tests/s3_imposter.cc
src/v/cloud_storage/tests/s3_imposter.h
src/v/cloud_storage/types.cc
src/v/cloud_storage_clients/configuration.cc
src/v/cloud_storage_clients/configuration.h
src/v/cloud_storage_clients/s3_client.cc
src/v/cloud_storage_clients/test_client/s3_test_client_main.cc
src/v/cloud_storage_clients/tests/client_pool_mt_test.cc
src/v/cloud_storage_clients/tests/client_pool_test.cc
src/v/cloud_storage_clients/tests/s3_client_test.cc
src/v/http/include/http/tests/http_imposter.h
src/v/http/tests/http_imposter.cc
src/v/redpanda/tests/fixture.h
tests/docker/dns/Dockerfile
tests/docker/dns/dnsmasq.conf
tests/docker/docker-compose.yml
tests/rptest/archival/s3_client.py
tests/rptest/services/redpanda.py
tests/rptest/tests/archival_test.py
tests/rptest/tests/control_character_flag_test.py
tests/rptest/tests/partition_movement_test.py
tests/rptest/tests/random_node_operations_test.py
tests/rptest/tests/read_replica_e2e_test.py
tests/rptest/tests/tiered_storage_model_test.py
tests/rptest/tests/upgrade_test.py
tests/rptest/tests/workload_upgrade_runner_test.py

Changes to testing and cloud storage infrastructure in order to be able to point Redpanda at [FIPS compliant S3 endpoints in AWS](https://aws.amazon.com/compliance/fips/) (go to "Amazon Simple Storage Service (S3)" row on the table in the linked page).
Changes in redpanda:
When constructing s3_config
- `url_style=virtual_host`, server_addr will be set to `[bucket].[endpoint_url]`. Before, it was `[endpoint_url]`. This is a requirement for fips mode
- `url_style=path`, `fips_mode=true`, and `client=s3` are incompatible for now and will stop the process. This is because the current implementation of fips mode is meant to work with AWS, and that requires virtual host URLs
- `url_style=nullopt` (self configure) and `fips_mode=true` will force `url_style=virtual`, and at startup s3_client will …

[CORE-2069]:  Changes to support using S3 FIPS Endpoints 

---

tests/rptest/services/redpanda.py

`rpk connect` implementation as a preinstalled plugin `.rpk.ac-connect` was shipped as part of `v24.1.2`.  In this setup, when `rpk` is invoked (say with `--help-autocomplete`, or `start`), `$HOME/.cache/snowflake/oscp_response_cache.json` is written.
This trips up CDT node cleanup (because `.cache` is a hidden file, exposing a gap in the logic for "only `rm *` if there is something there)".  I.e.
* `sftp_client.listdir()` sees the hidden entry
* But `rm -r *` does not... CDT blows up.
This PR allows CDT to handle `.cache` gracefully.  This is a forward port of https://github.com/redpanda-data/redpanda/pull/18687
It is currently considered acceptable (ala v24.1.4) to have this `.cache` exist for now - work may be prioritized on connect / rpk side to improve this logic (like not create the …

[rpk connect / CDT] CDT - remove /var/lib/redpanda/.cache before proceeding to clean regular entries

---

src/v/kafka/server/handlers/details/security.h
tests/rptest/clients/rpk.py
tests/rptest/tests/acls_test.py

Within create_acls requests, requests to create acls for resources that are topics would succeed even when the resource name was not a valid kafka topic name. This patch adds validation that makes the request fail with the appropriate error code. 
Fixes: https://redpandadata.atlassian.net/browse/CORE-2845
* Fixes a bug that would allow requests to complete that created acls for topics with invalid kafka topic names

[CORE-2845]: Ensure create_acls requests return an error when resources as topics are non valid kafka topic names 

---

src/v/kafka/CMakeLists.txt
src/v/kafka/server/client_quota_translator.cc
src/v/kafka/server/client_quota_translator.h
src/v/kafka/server/quota_manager.cc
src/v/kafka/server/quota_manager.h
src/v/kafka/server/tests/CMakeLists.txt
src/v/kafka/server/tests/client_quota_translator_test.cc
src/v/kafka/server/tests/quota_manager_test.cc

This introduces a new class `quota_translator` that handles two things:
* Translating a client id (or more generally a request context) into the `tracker_key` that should be used.
* Finding the quota limits that apply to a `tracker_key`
This code is extracted because while for now `quota_translator` only reads quota configurations from cluster configs, in follow-up PRs we intend to integrate the new `quota_store` into `quota_translator` as well. `quota_translator` is going to handle the merging of these two source of quota configurations.
Fixes https://redpandadata.atlassian.net/browse/CORE-2699
* none

CORE-2699 kafka/quota_mgr: extract keys and limit logic into `client_quota_translator`

---

tests/rptest/tests/control_character_flag_test.py

[v23.2.x] Fix for failing tests in `control_character_flag_test.py`

---

src/v/config/configuration.cc
src/v/config/validators.cc
src/v/config/validators.h
tests/rptest/tests/cluster_config_test.py

Fixes #17014.
A new validation function is added in order to prevent configuration issues where users set a `cloud_storage_api_endpoint` starting with `http://` or `https://`.
* none

[CORE-1867] config: add `validate_cloud_storage_api_endpoint`

---

.github/CODEOWNERS
src/go/.goreleaser_rp_connect.yaml

This creates a new `.goreleaser_rpk_connect.yaml` file for releasing `v24.1.x`.  Our internal release pipeline will leverage this file to release using the `prebuilt` feature of Goreleaser, which is [available only in Goreleaser Pro](https://goreleaser.com/customization/builds/#import-pre-built-binaries).
Creating a separate file like this introduces some duplication which is sad.  However it avoids the "Goreleaser Pro" requirement to any OSS developers or Redpanda developers working locally.  Using "Pro" means:
* installing a different goreleaser binary, AND
* having a `GORELEASER_KEY`.
The prevent code drift between the two yaml files, I added @redpanda-data/devprod as joint CODEOWNERS, so devprod can help review changes (which hopefully are not too frequent).
This will need to be …

[release process] automate rpk connect plugin bundling

---

src/v/cloud_storage/cache_service.cc
src/v/redpanda/admin/server.cc

Backport of #18732
Fixes https://github.com/redpanda-data/redpanda/issues/18735
CONFLICTS:
- uses [] instead of params due to lack of https://github.com/redpanda-data/redpanda/commit/45ba8c941c511628907ea7d13234c8b75c2838d8
* Fixes incorrect ordering of arguments in the cloud cache trim admin endpoint.

[v24.1.x] admin: fix cache trim parameter order

---

src/v/cloud_storage/cache_service.cc
src/v/redpanda/admin/server.cc

Backport of #18732
Fixes https://github.com/redpanda-data/redpanda/issues/18734
CONFLICTS:
- uses [] instead of params due to lack of https://github.com/redpanda-data/redpanda/commit/45ba8c941c511628907ea7d13234c8b75c2838d8
* Fixes incorrect ordering of arguments in the cloud cache trim admin endpoint.

[v23.3.x] admin: fix cache trim parameter order

---

src/v/cloud_storage/cache_service.cc
src/v/redpanda/admin_server.cc

Backport of #18732
Fixes https://github.com/redpanda-data/redpanda/issues/18733
CONFLICTS:
- uses [] instead of params due to lack of https://github.com/redpanda-data/redpanda/commit/45ba8c941c511628907ea7d13234c8b75c2838d8 (backporting this one to v23.2.x is tedious)
* Fixes incorrect ordering of arguments in the cloud cache trim admin endpoint.

[v23.2.x] admin: fix cache trim parameter order

---

src/v/cloud_storage/cache_service.cc
src/v/cloud_storage/cache_service.h
src/v/cloud_storage/tests/cache_test.cc
src/v/config/configuration.cc
src/v/config/configuration.h

Currently, the cache uses segment object names as file paths. This means that we have series of nested directories to store every file. Also, the first directory is a randomized prefix. This creates very large number of nonsense directories in the root of the cache.
This PR adds new configuration option `cloud_storage_cache_num_buckets`. When this property is set the cache will check if the object name starts with randomized prefix (8-character hex number). If this is the case it will replace it with a different prefix that has much smaller cardinality. Basically, it will put all object names into `cloud_storage_cache_num_buckets` buckets.
* Split cache into buckets using `cloud_storage_cache_num_buckets` configuration parameter.

cloud_storage: Rehash segment name prefixes

---

src/v/raft/consensus.cc

Previously it looked like this:
```
WARN  2024-05-24 12:38:33,690 [shard 0:clus] raft - [group_id:0, {redpanda/controller/0}] consensus.cc:357 - Received append entries response node_id doesn't match expected node_id (received: 8, expected: {id: {8}, revision: {0}})
```
which is very confusing
* none

raft: fix node_id mismatch log message

---

src/v/cloud_storage_clients/configuration.cc
tests/rptest/services/redpanda.py

cloud_storage_clients/configuration: use `s3-fips` subdomain if in fips mode
Before this change, a fips cluster would have to set
`cloud_storage_api_endpoint` manually to `s3-fips.[zone].amazonaws.com`
This change makes it optional; the default endpoint will be constructed as 
```
s3-fips.[zone].amazonaws.com if in fisp mode and
s3.[zone].amazonaws.com otherwise
```
Fixes [CORE-3177](https://redpandadata.atlassian.net/browse/CORE-3177)
* none 
[CORE-3177]: https://redpandadata.atlassian.net/browse/CORE-3177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CORE-3177] automatic s3 endpoint for fips

---

src/v/kafka/server/handlers/details/security.h
tests/rptest/clients/rpk.py
tests/rptest/tests/acls_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18701

[v24.1.x] [CORE-2845]: Ensure create_acls requests return an error when resources as topics are non valid kafka topic names 

---

src/v/raft/consensus.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18776

[v23.3.x] raft: fix node_id mismatch log message

---

src/v/cloud_storage/types.cc
src/v/cloud_storage_clients/s3_client.cc
src/v/cluster/cluster_utils.cc
src/v/config/convert.h
src/v/config/node_config.cc
src/v/config/node_config.h
src/v/config/property.h
src/v/config/rjson_serialization.cc
src/v/config/rjson_serialization.h
src/v/config/types.h
src/v/redpanda/application.cc
tests/rptest/services/redpanda.py
tests/rptest/services/templates/openssl.cnf
tests/rptest/tests/redpanda_startup_test.py

This PR changes the behavior of the `fips_mode` node config flag:
* Converts from `bool` to an `enum`
* Adds three new values:
* `disabled` - FIPS mode disabled
* `enabled` - FIPS mode enabled and `/proc/sys/crypto/fips_enabled` must equal `1` or Redpanda will exit
* `permissive` - FIPS mode enabled and `/proc/sys/crypto/fips_enabled` is checked for `1` but if not `1`, Redpanda will log a warning
* None

CORE-3167 relax fips enabled behavior

---

src/v/raft/consensus.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18776

[v23.2.x] raft: fix node_id mismatch log message

---

src/v/archival/ntp_archiver_service.cc
src/v/archival/tests/archival_service_fixture.h
src/v/archival/tests/service_fixture.cc
src/v/archival/types.cc
src/v/archival/types.h
src/v/config/configuration.cc
src/v/redpanda/tests/fixture.h

Fixes #14779 
A number of properties in the `archival::configuration` object do not require restarts, and have been updated to `config::binding<>` types in order to reflect updates made to the cluster config during runtime.
* none

[CORE-1562] config: update `archive::configuration` types to `config::binding<>`

---

src/v/kafka/server/client_quota_translator.cc
src/v/kafka/server/client_quota_translator.h
src/v/kafka/server/quota_manager.cc
src/v/kafka/server/quota_manager.h
src/v/kafka/server/tests/CMakeLists.txt
src/v/kafka/server/tests/client_quota_translator_test.cc
src/v/kafka/server/tests/quota_manager_bench.cc
src/v/kafka/server/tests/quota_manager_test.cc
src/v/redpanda/application.cc

A set of fixup commits and refactors that lead up to the next PR which will start using the `client_quota::store` inside `client_quota_translator`. These commits are extracted to aid review.
* none

CORE-2699 Quotas: prepare for using the quota store in `client_quota_translator`

---

src/v/kafka/server/group.cc
src/v/kafka/server/group.h
src/v/kafka/server/group_manager.cc
src/v/kafka/server/group_metadata.cc
src/v/kafka/server/group_metadata.h
src/v/kafka/server/group_recovery_consumer.cc
src/v/kafka/server/group_stm.cc
src/v/kafka/server/group_stm.h
src/v/kafka/server/tests/CMakeLists.txt
src/v/kafka/server/tests/consumer_group_recovery_test.cc

Added a test validating recovery of consumer group state from log.
- none

Added basic test validating consume group recovery

---

tests/rptest/redpanda_cloud_tests/high_throughput_test.py

Enable these tests to check if agent is recovering from being shut down. Investigate more if needed
* none

PESDLC-1494 Remove ignore from cloud decomission tests

---

src/v/cluster/controller_backend.cc
src/v/raft/configuration_manager.cc
src/v/raft/configuration_manager.h
src/v/raft/consensus.cc
src/v/raft/consensus.h
src/v/raft/tests/CMakeLists.txt
src/v/raft/tests/raft_reconfiguration_test.cc

Changed the way how Redpanda raft handles force reconfigurations. Instead of appending configuration to the log we keep a volatile in memory override for the configuration that was forced. The override is dropped whenever a node receives different configuration. This approach allow us to avoid discrepancies as not data are appended to the log without the active leader. 
Fixes: #17847
- none

Fixed possible log discrepancy when using forced reconfiguration 

---

src/go/rpk/pkg/cli/cluster/selftest/status.go
src/v/cluster/self_test/cloudcheck.cc
tests/rptest/tests/self_test_test.py

Cloud storage self-test doesn't have `IOPS`, `THROUGHPUT`,or `LATENCY` results, so these fields are skipped in the output of `rpk cluster self-test status`.
Before, the output of `rpk cluster self-test status` would include these fields for the cloud storage self-test.
```
NODE ID: 0 | STATUS: IDLE
=========================
NAME        Cloud Storage Test
INFO        Put
TYPE        cloud_storage
TEST ID     60ff3286-4701-4aea-8c56-9862045d34d1
TIMEOUTS    0
DURATION    18ms
IOPS        0 req/sec
THROUGHPUT  0B/sec
LATENCY     P50   P90   P99   P999  MAX
0us   0us   0us   0us   0us
NAME        Cloud Storage Test
INFO        List
TYPE        cloud_storage
TEST ID     60ff3286-4701-4aea-8c56-9862045d34d1
TIMEOUTS    0
DURATION    0ms
IOPS        0 req/sec
THROUGHPUT  0B/sec
LATENCY     P50 …
```

cluster: Reduce cloud storage self-test output

---

src/v/cluster/controller_backend.cc
src/v/raft/configuration_manager.cc
src/v/raft/configuration_manager.h
src/v/raft/consensus.cc
src/v/raft/consensus.h
src/v/raft/tests/CMakeLists.txt
src/v/raft/tests/raft_reconfiguration_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18153
Fixes: https://github.com/redpanda-data/redpanda/issues/18834,

[v24.1.x] Fixed possible log discrepancy when using forced reconfiguration 

---

tests/rptest/redpanda_cloud_tests/omb_validation_test.py
tests/rptest/services/producer_swarm.py
tests/rptest/services/redpanda_cloud.py

Adjust the warmup time buffer to 2.5x the nominal value, in part because the sleep duration is addition to any other delay in the startup loop in producer swarm.
Fix log message (missing f-string). Adjust some logging.
Add additional details when we fail to get the product.
* none

rptest: test_max_connections fixes

---

src/go/rpk/pkg/cli/cluster/cluster.go
src/go/rpk/pkg/cli/cluster/quotas/alter.go
src/go/rpk/pkg/cli/cluster/quotas/describe.go
src/go/rpk/pkg/cli/cluster/quotas/quotas.go
tests/rptest/clients/rpk.py

This PR adds rpk support to DescribeClientQuotas and AlterClientQuotas under the `rpk cluster quotas` command.
**Creating a Quota**
```
$ rpk cluster quotas alter --add consumer_byte_rate=12000 --name client-id=foo --default user
ENTITY                        STATUS
client-id=foo,user=<default>  OK
```
**Describing Quotas**
```
$ rpk cluster quotas describe --name client-id=testclient                                    
ENTITY                               QUOTA-TYPE          QUOTA-VALUE
client-id=testclient,user=user2      producer_byte_rate  130000
client-id=testclient,user=<default>  producer_byte_rate  140000
```
All new commands now include support for `--format` json|yaml flag.
* rpk: now you can manage client quotas using `rpk cluster quotas`.

rpk: add client quotas support to rpk

---

src/go/rpk/pkg/cli/cluster/config/get.go
tests/rptest/tests/cluster_config_test.py

In 610e3ad8 we introduced a fix for #6070, to avoid printing large numbers with scientific notation, we treated all numbers as integers.
Now, the API uses float values and they are rounded by rpk, this change introduces a mod check to determine whether the number is an integer or a float.
```
$ rpk cluster config get kafka_memory_share_for_fetch
0
$ rpk cluster config get kafka_memory_share_for_fetch
0.5
```
* rpk cluster config get: does not round float numbers anymore.

rpk: display float values as float in cluster config get

---

tests/rptest/clients/kubectl.py

Update Kubectl client to support Azure and capture tbot output
Fixes PESDLC-1433
* none

Update Kubectl client to support Azure and capture tbot output

---

src/v/kafka/server/handlers/configs/config_utils.h
src/v/kafka/server/handlers/create_topics.cc

On the node serving the request, the result of `create_topics` requests and `alter_configs` requests will be logged. Errors will be logged at the `WARN` level
JIRA Link: https://redpandadata.atlassian.net/browse/CORE-1355
* Improved logging around create_topics and alter_configs requests

Improve logging around topic creation and update topic properties events

---

src/go/rpk/pkg/adminapi/api_debug.go
src/go/rpk/pkg/cli/cluster/selftest/selftest_test.go
src/go/rpk/pkg/cli/cluster/selftest/status.go
src/v/cluster/self_test/diskcheck.cc
src/v/cluster/self_test/metrics.h
src/v/cluster/self_test/netcheck.cc
src/v/cluster/self_test_rpc_types.h
src/v/redpanda/admin/api-doc/debug.json
src/v/redpanda/admin/server.cc

Adding start/end times to self test results. Modifying the `DURATION` field to be `AVG DURATION` since it really represents the average the of all of the runs which may or may not run concurrently depending on the test type. Start and end represent (respectively) the moments the first sub-test started and the last one ended.
JIRA Link: https://redpandadata.atlassian.net/browse/CORE-381
* Self-test results will now also include start and end timestamps of test runs

Add start/end times to self test results

---

tests/rptest/redpanda_cloud_tests/omb_validation_test.py

Before test_max_connections starts the main body of the test we assert that there are a "small" number of connections.
This number is not zero because various things maintain or make occasional connections to cloud clusters like kminion, so we need to choose a higher value.
I observed typically ~45 connections on an idle T1 and 450 on an idle T7 cluster. This led to an initial SWAG of 100 + 1% of the connection target as the threshold above which we complain.
However, this check failed on a GCP T4 run with 320 connections, versus 250 allowed. So just double the calculation to 2% + 100. This threshold will automatically become much larger once the connection count increase makes it into the product data.
Ref: Ref: https://redpandadata.slack.com/archives/C06MCRY75U7/p1717697617572749?thread_ …

rptest: increase initial connections threshold

---

src/go/rpk/pkg/cli/debug/bundle/bundle.go
src/v/storage/segment_appender.cc
src/v/storage/tests/log_retention_tests.cc
src/v/storage/tests/log_segment_appender_test.cc
tests/rptest/remote_scripts/compute_storage.py
tests/rptest/services/redpanda.py
tests/rptest/tests/full_disk_test.py
tests/rptest/utils/si_utils.py

In the segment_appender we adaptively increase the file size of log
segments using `ss::file::allocate`.
This however doesn't immediately do what's intended. Internally it calls
`fallocate` with the `FALLOC_FL_KEEP_SIZE|FALLOC_FL_ZERO_RANGE` flags.
The former leads to the logical file size not being extended.
Extending the logical file size however seems to have been the intention
of https://github.com/redpanda-data/redpanda/commit/7d7706778918772336dda3a5cc7f63b665f106bf. We do already handle zero
bytes at the end fine either way as we are writing zero appended 4k
chunks anyway.
Besides this side effect there is other reasons why we want to update
the logical file size immediately.
First, this means that on every write we will need to update the file
size which makes both the write and …

segment_appender: truncate in addition to allocate

---

src/go/rpk/pkg/cli/cluster/config/get.go
tests/rptest/tests/cluster_config_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18841

[v23.2.x] rpk: display float values as float in cluster config get

---

src/v/cluster/client_quota_store.h
src/v/cluster/tests/client_quota_store_test.cc
src/v/kafka/server/client_quota_translator.cc
src/v/kafka/server/client_quota_translator.h
src/v/kafka/server/tests/client_quota_translator_test.cc

This follows https://github.com/redpanda-data/redpanda/pull/18777 and is the PR that implements the lookups to the `quota_store` on the request path and handles the merging of the various quotas configured through the quota store and cluster configs at various priority levels.
Fixes https://redpandadata.atlassian.net/browse/CORE-2699
* none

CORE-2699 Quotas: act on quotas from `quota_store`

---

src/v/redpanda/admin/debug.cc
src/v/resource_mgmt/cpu_profiler.cc

Preallocated result buffers at startup to avoid oversized allocs later
down the line.
* none

cpu_profiler: prealloc result buffers

---

src/v/raft/consensus.cc
src/v/raft/consensus.h
src/v/raft/group_manager.cc
src/v/raft/group_manager.h
tests/rptest/tests/nodes_decommissioning_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18691

[v24.1.x] Added `vectorized_raft_learners_gap_bytes` metric

---

src/v/cloud_storage/cache_service.cc
src/v/cloud_storage/cache_service.h
src/v/cloud_storage/tests/cache_test.cc
src/v/cloud_storage/tests/cache_test_fixture.h
src/v/config/configuration.cc
src/v/config/configuration.h

When the cloud storage cache is completely filled, puts to the cache are blocked. This prevents readers from progressing. In some clusters the trim operation can take a long time, up to hours. When this happens, readers will time out, generating errors.
This commit adds two configuration options that control when the trim is triggered. By setting these to less than 100%, cloud storage can begin a trim operation before the cache is completely filled, allowing readers to progress as the trim is going on in the background. If they remain unset, the original behavior remains, and trim will not start until the cache is full.
- cloud_storage_cache_trim_threshold_percent_size
- cloud_storage_cache_trim_threshold_percent_objects
* Adds configuration options to trigger cache trim before the cache …

cloud: Add config options to trigger cache trim

---

src/v/cluster/raft0_utils.h

Enable eviction of the snapshotted part of the controller log so that it doesn't grow uncontrollably.
* Enable controller log eviction - now the snapshotted part of the controller log will be deleted.

cluster: enable controller log eviction

---

src/v/cluster/client_quota_serde.h
src/v/cluster/tests/client_quota_store_test.cc
src/v/kafka/server/client_quota_translator.cc
src/v/kafka/server/tests/client_quota_translator_test.cc

Add a small utility to help constructing an `entity_key`.
* none

kafka/quotas: Improve API for entity_key

---

src/v/cloud_storage/tests/tx_range_manifest_test.cc
src/v/cluster/fwd.h
src/v/cluster/producer_state.cc
src/v/cluster/producer_state.h
src/v/cluster/rm_stm.cc
src/v/cluster/rm_stm.h
src/v/cluster/rm_stm_types.cc
src/v/cluster/rm_stm_types.h
src/v/cluster/tests/producer_state_tests.cc
src/v/cluster/tests/randoms.h
src/v/cluster/tests/rm_stm_tests.cc
src/v/config/configuration.cc
src/v/features/feature_table.cc
src/v/features/feature_table.h
src/v/kafka/server/handlers/describe_producers.cc
src/v/kafka/server/replicated_partition.cc
src/v/model/record.h
tests/rptest/transactions/transactions_test.py

Summary of changes in this PR
* Consolidates state management into producer_state definition. Currently all the transactions state is scattered across a bunch of maps and the resulting state changes are very error prone and not easy to follow.
* Adds a new snapshot version (v6) based on the state consolidation. V6 moves to serde unlike its predecessors which are reflection based.
* The snapshot version is behind a feature flag for downgrade scenarios (after a partial upgrade).
Some developer/reviewer oriented notes:
* Got rid of mem_tracker and related allocation tracking the stm. We no longer need it as we do not use allocator friendly data structures to store the state.
* Got rid of  "current_txn_start_offset" based start offset tracking in favor of new transaction state tracking.
* …

transactions: port log state into producer state struct

---

src/v/kafka/server/handlers/fetch.cc
tests/rptest/services/kgo_verifier_services.py
tests/rptest/tests/e2e_topic_recovery_test.py
tests/rptest/tests/shadow_indexing_tx_test.py

When a consumer issues a fetch request with `read_uncommitted` isolation level it doesn't need the aborted transactions information. Some clients ignore the range if reading uncommitted batches some of them do not. In Kafka aborted transaction ranges are not returned for uncommitted reads. Change Redpanda fetch handler not to return aborted transactions when `read_uncommitted` isolation level is requested by the consumer in `FetchRequest`.
- do not return aborted transaction ranges when reading with `read_uncommitted` isolation level.

k/fetch: do not return aborted txs for read uncommitted requests

---

src/v/kafka/server/client_quota_translator.cc
src/v/kafka/server/tests/client_quota_test_helpers.h
src/v/kafka/server/tests/client_quota_translator_test.cc
src/v/kafka/server/tests/quota_manager_test.cc
tests/rptest/tests/cluster_quota_test.py

After the client quotas are made per-node, we need to multiply up the per-shard configs by the core count to keep the intent of what the configs are set to.
Fixes https://redpandadata.atlassian.net/browse/CORE-3078
* none

CORE-3078 Quotas: scale up cluster configs by core count

---

src/v/cloud_storage/cache_service.cc
src/v/cloud_storage/cache_service.h
src/v/cloud_storage/recursive_directory_walker.cc
src/v/cloud_storage/recursive_directory_walker.h
src/v/cloud_storage/tests/cache_test_fixture.h
src/v/cloud_storage/tests/cloud_storage_fixture.h
src/v/cloud_storage/tests/directory_walker_test.cc
src/v/config/configuration.cc
src/v/config/configuration.h
src/v/redpanda/application.cc

I wonder what the effect of this would be on tail latencies for non-pathological scenarios (lower number of cache objects / larger cache objects; not-too-busy reactors).
* Run directory walking during cache trimming concurrently. On some deployments it was observed that it can take hours for 600K objects with busy reactor during which fetch operations that need to cache data are blocked.

cloud_storage: concurrent directory walking

---

src/v/kafka/server/tests/quota_manager_test.cc

Fixed usage of `entity_key` constructor in `quota_manager` fixture test.
- none

k/tests: fixed use of entity_key constructor

---

tests/rptest/tests/nodes_decommissioning_test.py

The test using decommission operation to validate the correctness of learner gap metrics used random properties for topic partition count and replication. This made the test flaky as in some circumstances the `redpanda/controller/0` was the only partition on the decommissioned node. This partition is removed from the node and not moved anywhere else hence it does not contribute to learner gap but it still contributes to overall data on the decommissioned node.
Fixes: #19067
- none

tests: adjusted topic settings to make learner gap test stable

---

.github/labeler.yml

The v5 of labeler has breaking change that needs update to the configuration file:
https://github.com/actions/labeler/tree/v5.0.0?tab=readme-ov-file#breaking-changes-in-v5
This fixes it and retains existing behavior. Just syntax differences.
Unfortunately, the gha job `triage` will fail using label v5 until this PR is merged to `dev` branch because of known issue https://github.com/actions/labeler/issues/712#issuecomment-1852440098, so needs a force merge.
I recommend merging this PR to keep the fixes for nodejs that were brought in with labeler v5. But if this PR is merged, then PR #19626 should not be merged.
* none

gha/labeler: fix format of yml file for v5

---

.github/labeler.yml

Backport of PR #19625 
no conflicts in cherry-pick
jira: https://redpandadata.atlassian.net/browse/PESDLC-1510
* none

[v24.1.x] gha/labeler: fix format of yml file for v5

---

src/v/storage/disk_log_impl.cc

Consider the following sequence of events:
1. there is a single segment in the log, with offsets [0-9]
2. we call prefix_truncate(10)
3. concurrently, another batch of 5 messages is being appended.
4. empty segment with base_offset=10, dirty_offset=9 is created
5. the appended batch is placed at offsets 10-14
Previously, the empty segment would have passed the dirty_offset check and (after waiting for the append to finish) would get deleted (including the data at offsets 10-14). Check also the segment base_offset to prevent that.
Fixes https://github.com/redpanda-data/redpanda/issues/19632
* none

s/disk_log_impl: don't prefix-truncate empty segments

---

src/v/bytes/CMakeLists.txt
src/v/bytes/bytes.cc
src/v/bytes/iobuf.cc
src/v/bytes/iostream.cc
src/v/bytes/scattered_message.cc
src/v/cluster/tests/randoms.h
src/v/container/include/container/chunked_hash_map.h
src/v/container/include/container/interval_set.h
src/v/container/tests/bench_utils.h
src/v/container/tests/interval_set_test.cc
src/v/container/tests/vector_bench.cc
src/v/serde/test/serde_test.cc
src/v/ssx/include/ssx/thread_worker.h
src/v/storage/mvlog/segment_reader.cc
src/v/storage/mvlog/tests/active_segment_test.cc
src/v/test_utils/gtest_utils.cc
src/v/test_utils/randoms.h

* Minor updates to headers / code organization
* In support of bazel investigation, but generally universal.
* none

chore: minor updates for build system improvements

---

src/v/cluster/partition_balancer_types.h

Replicas eviction policy is asynchronously applied to each partition it may happen that the size of individual partitions is not exactly equal to the total usage size reported. In this case the individual partition sizes that are moved out of the node may sum up to a value larger than the total used bytes. Added a code preventing overflowing the final ratio in this case
- fixed overflow that may lead to unnecessary moves

c/p_balancer: fixed possible overflow of final used ration

---

.github/workflows/backport-command.yml

follow-on to PR #18857
fixes https://redpandadata.atlassian.net/browse/PESDLC-1511
There are 2 jobs defined in this file and initially access to AWS SM was added to just the first one. This commit adds it to the second job, "type-branch", as well since it also needs access.
backports are not strictly necessary for this PR because the workflow file runs on `repository_dispatch` which only runs on the default branch (`dev`), but doing a backport would be good to verify it works after this is merged.
* none

gha: fix backport-command type-branch job to retrieve aws sm token

---

src/v/cluster/controller_backend.cc
src/v/raft/configuration_manager.cc
src/v/raft/configuration_manager.h
src/v/raft/consensus.cc
src/v/raft/consensus.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/18153

[v23.3.x] Fixed possible log discrepancy when using forced reconfiguration 

---

.github/labeler.yml

Backport of PR #19625 
conflict resolution in cherry-pick was simple (just for `area/wasm`)
jira: https://redpandadata.atlassian.net/browse/PESDLC-1510
* none

[v23.3.x] gha/labeler: fix format of yml file for v5

---

src/v/cluster/partition_balancer_types.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/19794

[v23.3.x] c/p_balancer: fixed possible overflow of final used ration

---

.github/labeler.yml

Backport of PR #19625 
resolved conflict by only transforming what was already in v23.2.x branch
jira: https://redpandadata.atlassian.net/browse/PESDLC-1510
* none

[v23.2.x] gha/labeler: fix format of yml file for v5

---

src/v/storage/disk_log_impl.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/19790
Fixes: https://github.com/redpanda-data/redpanda/issues/19800,

[v24.1.x] s/disk_log_impl: don't prefix-truncate empty segments

---

src/v/kafka/server/tests/fetch_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18468
Fixes: https://github.com/redpanda-data/redpanda/issues/19806, Fixes: https://github.com/redpanda-data/redpanda/issues/19807,
Fixes: CORE-4179
Fixes: CORE-4174

[v24.1.x] t/fetch_test: wait longer for leadership after stepping down

---

src/v/pandaproxy/schema_registry/CMakeLists.txt
src/v/pandaproxy/schema_registry/json.cc
src/v/pandaproxy/schema_registry/json.h
src/v/pandaproxy/schema_registry/test/CMakeLists.txt
src/v/pandaproxy/schema_registry/test/test_json_schema.cc
src/v/pandaproxy/schema_registry/types.h

Some cleanup from the [initial PoC](https://github.com/redpanda-data/redpanda/compare/dev...BenPope:redpanda:schema_registry/json/PoC), but drops some commits, too.
* none

[CORE-4180] schema_registry/json: Initial commits for JSON Schema

---

src/v/cloud_storage_clients/configuration.cc
src/v/config/CMakeLists.txt
src/v/config/tls_config.cc
src/v/config/tls_config.h
src/v/rpc/rpc_utils.cc
tests/rptest/services/tls.py
tests/rptest/tests/crl_test.py

Adds support for OpenSSL configuration for Redpanda
* None

CORE-2426 support ossl cipher strings

---

src/v/kafka/server/tests/fetch_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18468
Fixes: https://github.com/redpanda-data/redpanda/issues/19811, Fixes: https://github.com/redpanda-data/redpanda/issues/19813,
Fixes: CORE-4175
Fixes: CORE-4176

[v23.3.x] t/fetch_test: wait longer for leadership after stepping down

---

src/v/kafka/server/handlers/details/security.h
tests/rptest/clients/rpk.py
tests/rptest/tests/acls_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18701 
Fixes https://github.com/redpanda-data/redpanda/issues/18770

[v23.3.x] [CORE-2845]: Ensure create_acls requests return an error when resources as topics are non valid kafka topic names 

---

src/v/kafka/server/tests/fetch_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18468
Fixes: https://github.com/redpanda-data/redpanda/issues/19809, Fixes: https://github.com/redpanda-data/redpanda/issues/19810,
Fixes: CORE-4177
Fixes: CORE-4178

[v23.2.x] t/fetch_test: wait longer for leadership after stepping down

---

src/go/rpk/pkg/cli/debug/bundle/bundle_k8s_linux.go
src/go/rpk/pkg/cli/debug/bundle/bundle_linux.go

Debug bundles are often collected when things are not working properly, so it is normal that `rpk debug bundle` hits some errors along the collection steps. This PR aims to improve the error messages and provide better hints when errors occur, it focuses on the Kubernetes experience.
Fixes #18057 
1. rpk uses the k8s API to 'find' the admin API addresses and collect the logs, this is the first step that leads many other steps, if the service account does not have the authorization to access some resources it will fail. Now we check for the authorization before executing the steps, reducing the clutter and providing a better error message:
```
* unable to get pods in the "redpanda" namespace: pods is forbidden: User "system:serviceaccount:redpanda:default" cannot list resource "pods" in …
```

rpk: Improve k8s bundle errors + better admin API fallback 

---

src/v/cluster/scheduling/leader_balancer.cc
src/v/cluster/scheduling/leader_balancer.h
tests/rptest/tests/topic_recovery_test.py

Mute just restarted nodes in leader_balancer, as their health reports can have incomplete partition info, and they are probably busy recovering partitions anyway.
Fixes https://github.com/redpanda-data/redpanda/issues/17150
* Don't try to transfer leadership to just restarted nodes when balancing leaders.

Mute just restarted nodes in leader_balancer

---

src/v/cloud_storage/cache_service.cc
src/v/cloud_storage/cache_service.h
src/v/cloud_storage/tests/cache_test.cc
src/v/cloud_storage/tests/cache_test_fixture.h
src/v/config/configuration.cc
src/v/config/configuration.h
src/v/config/property.h

[v23.3.x] cloud: Add config options to trigger cache trim

---

src/v/cluster/partition_balancer_types.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/19794

[v24.1.x] c/p_balancer: fixed possible overflow of final used ration

---

src/v/cluster/controller.cc
src/v/cluster/controller_backend.cc
src/v/cluster/controller_backend.h
tests/rptest/tests/scaling_up_test.py

With non strict local retention the storage manager will not trigger
data eviction immediately when partition is eligible for eviction but
will allow local data to use the whole available disk space. Using
standard partition movement policy would force raft to deliver all local
data over the network which is not necessary and might take long time.
Changed the controller backend to always override the learner start
offset when non strict retention is enabled and deliver over the network
only data that would normally be retained if strict local retention is
turned on.
- reduced the amount of data required to transfer over the network

Respect target local retention settings when moving cloud enabled partition replicas

---

src/v/cluster/controller.cc
src/v/cluster/controller_backend.cc
src/v/cluster/controller_backend.h
tests/rptest/tests/scaling_up_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/19820

[v24.1.x] Respect target local retention settings when moving cloud enabled partition replicas

---

src/v/cluster/controller.cc
src/v/cluster/controller_backend.cc
src/v/cluster/controller_backend.h
tests/rptest/tests/scaling_up_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/19820

[v23.3.x] Respect target local retention settings when moving cloud enabled partition replicas

---

src/v/storage/disk_log_impl.cc
src/v/storage/tests/storage_e2e_test.cc

Fixes #18396 (again)
When finding the `max_step_size()`, consider the final step between last position index value and segment size.
Also avoids an uninitialized value in `offset_range_size()`, which _might_ fix #18496 - I haven't seen the error appear in `debug` mode since making the change.
* none

storage/tests: fix `max_step_size()` in `test_offset_range_size_incremental`

---

src/v/cluster/scheduling/leader_balancer.cc
src/v/cluster/scheduling/leader_balancer.h
tests/rptest/tests/topic_recovery_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18497
Fixes: https://github.com/redpanda-data/redpanda/issues/19831,

[v24.1.x] Mute just restarted nodes in leader_balancer

---

src/v/cluster/producer_state.cc
src/v/cluster/producer_state.h
src/v/cluster/rm_stm.cc

A request can be marked as errored multiple times, consider the example
below.
```
replicate_f : waiting for replication
term change and leadership change
requests from old terms gc-ed: set_err(ec) -- separate fiber
replicate_f: set_err(ec)
```
Current assert assumes that a request can be set only once, which is
true for setting a successful result but not for errors. This commit
splits set_value() into set_value() and set_error() and adjusts
assert conditions accordingly.
This was identified in a chaos build. Also included some logging improvements noticed while debugging, most notably printing the transaction state correctly (currently printing the pointer instead of value).
Also fixes https://github.com/redpanda-data/redpanda/issues/18267
* none

producer_state: add request::set_error and make it idempotent 

---

src/v/cloud_storage/cache_service.cc
src/v/cloud_storage/cache_service.h
src/v/cloud_storage/recursive_directory_walker.cc
src/v/cloud_storage/recursive_directory_walker.h
src/v/cloud_storage/tests/cache_test_fixture.h
src/v/cloud_storage/tests/cloud_storage_fixture.h
src/v/cloud_storage/tests/directory_walker_test.cc
src/v/config/configuration.cc
src/v/config/configuration.h
src/v/redpanda/application.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18758

[v24.1.x] cloud_storage: concurrent directory walking

---

src/v/storage/file_sanitizer.h
src/v/storage/segment_appender.cc
src/v/storage/segment_appender.h

We are about to run out of ids.
Also, the static assert as it was wouldn't work as it's off by one.
* none

storage: use uint64_t for batch type map

---

tests/rptest/tests/scaling_up_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/19845

[v23.3.x] tests: use partition size metrics in test verifying local retention move

---

tests/rptest/tests/scaling_up_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/19845

[v24.1.x] tests: use partition size metrics in test verifying local retention move

---

src/v/cloud_storage/cache_service.cc
src/v/cloud_storage/cache_service.h
src/v/cloud_storage/recursive_directory_walker.cc
src/v/cloud_storage/recursive_directory_walker.h
src/v/cloud_storage/tests/cache_test_fixture.h
src/v/cloud_storage/tests/cloud_storage_fixture.h
src/v/cloud_storage/tests/directory_walker_test.cc
src/v/config/configuration.cc
src/v/config/configuration.h
src/v/redpanda/application.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18758

[v23.3.x] cloud_storage: concurrent directory walking

---

src/v/kafka/protocol/logger.cc
src/v/kafka/server/client_quota_translator.cc
src/v/kafka/server/client_quota_translator.h
src/v/kafka/server/connection_context.cc
src/v/kafka/server/logger.h
src/v/kafka/server/quota_manager.cc
src/v/kafka/server/tests/client_quota_translator_test.cc

This creates a trace-level logger to enable us and customers to debug client quota behaviour. It introduces the enum type `client_quota_rule` which is used to describe which quota rule was used to configure the quota that applies to the given request, so that we can tell using the logger which quotas are being actively used to throttle requests, what limits apply, what tracking key is being used, how big the requests are, and what delays are being returned to the client.
The log lines generated look like this:
```
TRACE 2024-06-14 15:36:05,240 [shard  2:main] kafka_quotas - quota_manager.cc:361 - request: ctx:{quota_type: produce_quota, client_id: {rpk}}, key:k_client_id{rpk}, value:{limit: {1111}, rule: kafka_client_default}, bytes: 1316, delay:184518451ns, capped_delay:184518451ns
TRACE …
```

CORE-2715 Quotas: add trace-level logger

---

src/transform-sdk/go/transform/internal/testdata/schema-registry/transform.go
src/transform-sdk/go/transform/sr/serde.go
src/transform-sdk/go/transform/sr/serde_test.go
src/transform-sdk/rust/examples/schema_registry/main.rs
src/transform-sdk/tests/integration_test.go

Includes unit tests.
The primary purpose here is to generate a correct subject name based
on user-provided info:
- output topic name
- subject name strategy
- whether it is a key or a value
- record name (depending on SNS)
Users may include a nameless function, parameterized by the derived
subject name, where they can perform the actual creation of the subject
version in SR. The idea here is to keep Serde[T] more ore less decoupled
from the particular schema it's working on.
Closes CORE-3123
* Golang Transforms SDK (Serde): Adds the ability to specify subject name strategy for output topics. Transforms can also provide a function to be called after the subject name is derived - e.g. to ensure that the subject is created before emitting records.

golang SDK: Introduce serde opts for subject auto(ish)-creation

---

src/v/cluster/client_quota_serde.h
src/v/kafka/server/handlers/client_quotas.cc
tests/rptest/clients/kcl.py
tests/rptest/tests/quota_management_test.py

This implements the AlterClientQuotas and DescribeClientQuotas Kafka endpoints. These endpoints can be used to configure client quotas stored in the quota store state. Customers will be able to use the `rpk cluster quotas alter/describe` cli tool to access these endpoints.
Fixes https://redpandadata.atlassian.net/browse/CORE-2073
Fixes https://redpandadata.atlassian.net/browse/CORE-2077
* Implements the Kafka client quota management APIs of KIP 546: AlterClientQuotas and DescribeClientQuotas.

CORE-2073 quotas: implement alter/describe quotas

---

src/transform-sdk/go/transform/internal/testdata/schema-registry/transform.go

Recently changed the schema creation logic in the SR example transform
to create the schema on first record receipt, to flex recent subject
autocreation logic. This breaks some assumptions in the Wasm unit tests,
so we'll just restore the original behavior and reassess testing strategy
for the new code.
* none

wasm/tests: Fix SR unit test

---

tests/rptest/services/tls.py
tests/rptest/tests/tls_metrics_test.py

The TLSChainCACertManager class in ducktape is updated to chain CRLs for each individual CA.
This PR is required to fix DT tests before enabling OpenSSL in Seastar which will be done in a subsequent vtools PR
* None

CORE-4182: dt/tls: Create chain of CRLs

---

src/go/rpk/pkg/cli/debug/bundle/bundle.go
src/go/rpk/pkg/cli/debug/bundle/bundle_all.go
src/go/rpk/pkg/cli/debug/bundle/bundle_linux.go
src/go/rpk/pkg/cli/debug/bundle/bundle_test.go
tests/rptest/tests/rpk_cluster_test.py

- 0c68485875298cfddb6b433abbd1cb3f9291c0e8 Changes the default log collection (in bare metal) to grab the logs since `yesterday`. Fixes #18640 Fixes #15683
- 3b746bbfddf7463d6cffde5c45a1a8a0babf8a5a Moves 'trimming file' DEBUG message to WARN.
- d93ff83cc95ab912fba25095795f4b5f6a8db092 Uses the `redpanda.advertised_rpc_api.address` to mark the file name of the debug bundle. Fixes #11857
- 9ae144f5e76e39d3758fbeac89091d44c94fdce7 Mimics the redpanda data directory structure to our debug bundle so we can easily use our decoding tool w/o any hacks or extra steps. It does not fix #16575 but it's a QOL improvement until we decide the best way to handle the request.
* rpk debug bundle now collects the log since `yesterday` by default, you can still change them with `--logs-since`.
* rpk debug …

rpk: more debug bundle improvements

---

src/v/cluster/client_quota_store.cc
src/v/cluster/client_quota_store.h
src/v/kafka/server/client_quota_translator.cc
src/v/kafka/server/quota_manager.cc
src/v/kafka/server/tests/quota_manager_test.cc

This provides an observer mechanism to `quota_store` to allow updating the trackers in `quota_manager` whenever there are changes in the `quota_store`.
Previously, we only watched for quota changes through cluster configs but not through the quota_store. This meant that if the limit of a quota configured through the Kafka API changed, this limit update would not propagate to existing trackers (and would only update if either the tracker expires or a quota cluster config change triggers a reevaluation of the quotas). This PR fixes that.
Fixes https://redpandadata.atlassian.net/browse/CORE-4200
* none

CORE-4200 quotas: watch quota store changes

---

src/go/rpk/pkg/cli/debug/bundle/bundle_k8s_linux.go
src/go/rpk/pkg/cli/debug/bundle/bundle_linux.go

Backport of PR https://github.com/redpanda-data/redpanda/pull/19473
Fixes: https://github.com/redpanda-data/redpanda/issues/19877,

[v24.1.x] rpk: Improve k8s bundle errors + better admin API fallback 

---

src/v/raft/consensus.cc
src/v/raft/consensus.h
src/v/raft/group_manager.cc
src/v/raft/group_manager.h
tests/rptest/tests/nodes_decommissioning_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18691

[v23.3.x] Added  `vectorized_raft_learners_gap_bytes` metric

---

src/v/raft/consensus.cc
src/v/raft/probe.cc
tests/rptest/tests/raft_availability_test.py

Previously the leadership changed metric was incremented every time a group leader was updated with the new leader or the leader was currently unknown. Technically the change from leader to no leader is a leadership change but it was confusing to users.
Change the metric updates to only account the changes when leader is present. This way after each successful leader election the metric is incremented by one on all partition replicas.
- refined `vectorized_raft_leadership_changes_total` metric

Refined leadership changed metrics

---

tests/docker/ducktape-deps/kafka-tools
tests/rptest/services/kafka.py
tests/rptest/tests/basic_kafka_compat_tests.py

Sometimes it may be hard to find the Kafka protocol specification. In
this cases we treat Kafka implementation as a in code specification.
Added a simple test stub to prove that executing the same set of
commands yield the same result on both Redpanda and Kafka.
- none

Added basic compatibility test for handling concurrent producers with the same `transactional.id`

---

src/v/pandaproxy/schema_registry/json.cc
src/v/pandaproxy/schema_registry/test/test_json_schema.cc

extend check_compatible() to support the "enum" keyword.
check_compatible(reader, writer) iff
both are not "enum" schema
or
both are "enum" schema and every value in writer["enum"] is also in reader["enum"]
the current implementation is an O(n²) lookup, and for object values the equality is implemented as a O(n²) recursive operation.
The cardinality is usually low so this operation is ok, but this will be improved once normalization (field sorting) and <=> on normalized objects are implemented
Fixes https://redpandadata.atlassian.net/browse/CORE-3185
* none

[CORE-3185] schema registry - json compatibility checks for "enum"

---

src/go/rpk/pkg/cli/debug/bundle/bundle.go
src/go/rpk/pkg/cli/debug/bundle/bundle_all.go
src/go/rpk/pkg/cli/debug/bundle/bundle_linux.go
src/go/rpk/pkg/cli/debug/bundle/bundle_test.go
tests/rptest/tests/rpk_cluster_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/19843
Fixes: https://github.com/redpanda-data/redpanda/issues/19881, Fixes: https://github.com/redpanda-data/redpanda/issues/19882, Fixes: https://github.com/redpanda-data/redpanda/issues/19883, Fixes: https://github.com/redpanda-data/redpanda/issues/19884,

[v24.1.x] rpk: more debug bundle improvements

---

src/v/kafka/server/handlers/list_offsets.cc
tests/rptest/tests/timequery_test.py

This bug was introduced accidentally while trying to fix another off-by-one bug in commit ref 8f2de964c0e915f4f10ae8eb74400e6288c5680f. I forgot to account that for an empty topic the "start offset" is equal to "last offset" so calling `model::prev_offset` would result in an offset below the start which is invalid and throws an exception if passed downstream.
To avoid the problem, we short-circuit with a "offset not found" response straight away if that's the case.
https://github.com/redpanda-data/redpanda/pull/18112/commits/8f2de964c0e915f4f10ae8eb74400e6288c5680f
* Fix timequery failing with exceptions when the queried partition is empty.

kafka: fix timequery failing for empty topics

---

cmake/testing.cmake
src/v/crypto/tests/CMakeLists.txt

Now that OpenSSL libraries are installed in lib, update OPENSSL_ENV to use correct library path.
* None

CORE-4264: cmake: Change LD_LIBRARY_PATH for OpenSSL

---

src/v/kafka/server/handlers/list_offsets.cc
tests/rptest/tests/timequery_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/19937

[v24.1.x] kafka: fix timequery failing for empty topics

---

src/go/rpk/pkg/cli/registry/schema/check_compatibility.go
src/go/rpk/pkg/cli/registry/schema/create.go
src/go/rpk/pkg/cli/registry/schema/get.go
src/go/rpk/pkg/cli/registry/schema/schema.go

This allows `rpk registry` to read/create/list JSON schemas.
First step to support JSON schemas in `rpk`. Next step is to support producing and consuming.
I'll add release notes with the PR that introduce support for producing and consuming (once we have the JSON schema support in Redpanda)
* none

rpk registry: accept JSON files when creating schemas

---

src/v/kafka/server/handlers/list_offsets.cc
tests/rptest/tests/timequery_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/19937

[v23.3.x] kafka: fix timequery failing for empty topics

---

tests/rptest/tests/scaling_up_test.py

Previously the test wasn't waiting for metrics to be reported leading to failures.
Fixes: #19920
- none

tests: fixed test validating disk size when moving with local retention

---

tests/rptest/tests/scaling_up_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/19932
Fixes: https://github.com/redpanda-data/redpanda/issues/19960,

[v23.3.x] tests: fixed test validating disk size when moving with local retention

---

src/v/kafka/server/tests/CMakeLists.txt
src/v/kafka/server/tests/quota_manager_bench.cc

The existing benchmarks around quota manager are effectively measuring
the throughput of recording client quotas because they measure an
average latency across a large number of runs on multiple cores.
This adds more microbenchmarks around quota manager that are more aimed
at measuring the latency of recording client quotas because they make a
low number of calls to quota_manager and measure it many times. The new
benchmarks also cover a wider range of scenarios, trying to trigger
various worst cases of client quota throttling.
The latency benchmarks clearly highlight that with >=1000 client ids in the map, the map copying becomes very expensive. I have a follow-up PR to avoid this (https://github.com/redpanda-data/redpanda/pull/19941). The next biggest latency factor is the cross-shard …

CORE-4269 Quotas: add latency benchmarks

---

src/v/pandaproxy/schema_registry/handlers.cc
src/v/pandaproxy/schema_registry/sharded_store.cc
src/v/pandaproxy/schema_registry/test/get_schema_types.cc
src/v/pandaproxy/schema_registry/types.h
tests/rptest/tests/rpk_registry_test.py
tests/rptest/tests/schema_registry_test.py

Support is currently quite restricted, it's not ready yet.
* none

[CORE-4729] schema_registry: Wire up JSON Schema support

---

src/v/raft/tests/jitter_tests.cc
src/v/raft/timeout_jitter.h

raft: fix changing raft_election_timeout_ms without restart

---

src/v/pandaproxy/schema_registry/seq_writer.cc
src/v/pandaproxy/schema_registry/store.h
tests/rptest/tests/schema_registry_test.py

`store::get_versions` was ignoring `include_deleted`, which meant that
the new schema was detected as existing, but not a candidate for
being added as a new version.
A test was fixed up, as schema id 1 is not compatible with id v2,
compatibility must be set to NONE before adding back id 1, as it
will become version 3.
When the last version is soft-deleted, the config should be cleared.
* Schema Registry: Improve handling of deleted schema

[CORE-3008] schema_registry: Improve handling of deleted schema

---

src/v/pandaproxy/schema_registry/seq_writer.cc
src/v/pandaproxy/schema_registry/store.h
tests/rptest/tests/schema_registry_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/19944

[v23.3.x] [CORE-3008] schema_registry: Improve handling of deleted schema

---

src/v/pandaproxy/schema_registry/seq_writer.cc
src/v/pandaproxy/schema_registry/store.h
tests/rptest/tests/schema_registry_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/19944

[v24.1.x] [CORE-3008] schema_registry: Improve handling of deleted schema

---

src/v/storage/tests/storage_e2e_test.cc

We were undershooting a `min_size` target for one of the storage test cases consistently in CI. Reduce its value to be more permissive for the test case.
Fixes #18496 
* none

storage/tests: fix `min_size` value in `test_offset_range_size_incremental`

---

src/v/ssx/include/ssx/single_sharded.h
src/v/ssx/tests/CMakeLists.txt
src/v/ssx/tests/single_sharded.cc

For services running on one shard but exposing invocation helper to callers from other shards.
It might be a bit simpler with `sharded<Service>::start_single`, but it has shard number hardcoded as 0.
* none

ssx: create single_sharded<Service> template

---

src/v/kafka/server/quota_manager.cc
src/v/kafka/server/quota_manager.h
src/v/kafka/server/tests/quota_manager_bench.cc
src/v/kafka/server/tests/quota_manager_test.cc
src/v/redpanda/application.cc
src/v/redpanda/application.h

This PR changes the way client quota tracking is implemented inside quota_manager in order to avoid taking copies of the quota tracker map on the request path, since this was identified as high-latency during benchmarking (see https://github.com/redpanda-data/redpanda/pull/19940 for data).
The problem with representing the quota tracker map as a single `ssx::sharded_ptr<map_t>` of immutable `map_t`'s is that we need to make sure that updates to the map are done on copies, all cores are referencing the same map. Instead, what we can do is we can have 2 types of maps: a single "global" map that contains references to all the existing quota trackers and local maps on each shard that only reference quotas that the local core comes across. Updates to the global map are only done on shard 0 (a …

CORE-4269 Quotas: avoid map copies when adding new quota trackers

---

src/v/transform/api.cc
src/v/transform/io.h
src/v/transform/tests/test_fixture.cc
src/v/transform/tests/test_fixture.h
src/v/transform/transform_processor.cc
tests/rptest/tests/data_transforms_test.py

Default behavior is for transforms to start processing input from an offset
equivalent to "the latest committed offset at deploy time". However, in
situations where no records are committed between the moment the transform
was deployed and the moment the transform starts, the timequery servicing
this logic returns nullopt and we erroneously start processing at the
beginning of the topic.
This commit corrects the handling of the timequery result to commit the
latest offset (computed at start time) in the situation described above.
* Fix an issue where transforms would miscalculate their initial start offset, leading to consuming the whole input topic.

Transforms: Fix deploy-time timequery bug

---

src/go/rpk/pkg/cli/container/start.go

This brings the documentation changes from https://github.com/redpanda-data/docs/pull/559/files to rpk codebase.
Also fixes a bug that prevented `--any-port` from working with console when using a cluster with more than 1 node.
* rpk: fixed a bug that prevented `--any-port` from working with Redpanda Console when using a cluster with more than 1 node.

rpk: improve help text and minor bug fix

---

tools/offline_log_viewer/storage.py

* none
A minor tweak, but olv can be confusing in how it reports this error. It expected that the dir passed to `--path` is a "true" Redpanda data dir. That means that if you pass it a dir that just happens to have (e.g.) `redpanda/controller/0_0/<segment_files>` in it, although it has all the data there, it may fail if there are other dirs present in the path you passed.
Until #19843, when processing controller logs in a debug bundle, you need to manually build up the dir structure. Depending on how you do this, this behaviour can be a gotcha.
Before:
```
$ python ~/repos/redpanda/tools/offline_log_viewer/viewer.py --type controller --path .
/Users/jflath/repos/redpanda/tools/offline_log_viewer/storage.py:43: SyntaxWarning: invalid escape sequence '\d' …
```

Add error message on olv dir assert

---

tests/rptest/tests/full_disk_test.py

After https://github.com/redpanda-data/redpanda/commit/7d0d283abeacdad8177e4fc4a2cfb95a52654e18 the expected size in
LocalDiskReportTimeTest.test_target_min_capacity_wanted_time_based
changed slightly.
The test is already time based and has some flakiness leeway but the
above change seems to have made it flake more often.
Hence, adapt the size to get a more accurate calculation.
Fixes https://github.com/redpanda-data/redpanda/issues/14320
* none

tests: Adapt size in LocalDiskReportTimeTest

---

cmake/dependencies.cmake
install-dependencies.sh
licenses/third_party.md
src/CMakeLists.txt
src/v/cloud_roles/refresh_credentials.cc
src/v/cloud_roles/tests/signature_test.cc
src/v/cloud_storage_clients/configuration.cc
src/v/cloud_storage_clients/s3_client.cc
src/v/cloud_storage_clients/test_client/abs_test_client_main.cc
src/v/cloud_storage_clients/test_client/s3_test_client_main.cc
src/v/config/tls_config.cc
src/v/crypto/tests/CMakeLists.txt
src/v/crypto/tests/crypto_bench.cc
src/v/net/include/net/tls.h
src/v/storage/key_offset_map.h

CORE-4263 Removed any use of GnuTLS

---

src/v/raft/consensus.cc
src/v/raft/tests/basic_raft_fixture_test.cc
src/v/raft/tests/raft_fixture.h

When install snapshot request in processed by the follower it may not
always replace the follower log content. If the snapshot last included
offset is smaller than the follower dirty offset the follower should
prefix truncate all the data up to the snapshot last included offset but
keep all the entries which offset is greater than snapshot last included
offset.
Fixed the update of follower metadata state as it was always using the
snapshot configuration instead the latest from the configuration
manager.
Fixes: https://github.com/redpanda-data/core-internal/issues/1310
- fixed handling of delayed snapshot requests that might lead to an assertion

Always use the latest configuration for followers metadata

---

src/v/kafka/group_probe.h
src/v/kafka/server/group.cc
src/v/kafka/server/group.h
src/v/kafka/server/group_manager.cc
src/v/kafka/server/group_metadata.cc
src/v/kafka/server/group_metadata.h
src/v/kafka/server/group_recovery_consumer.cc
src/v/kafka/server/group_stm.cc
src/v/kafka/server/group_stm.h
src/v/kafka/server/tests/consumer_group_recovery_test.cc
tests/rptest/transactions/tx_atomic_produce_consume_test.py
tests/rptest/transactions/tx_verifier_test.py

Previously transaction state was kept in several map data structures.
It made it harder to understand the transaction flow in consumer group
state machine. Refactored the transaction handling to use a single
source of truth about the transaction state. The group state machine is
now using a `_transactions` map to store the information about all
ongoing transactions. The map is populated when the transaction starts
and the entry in the map is updated throughout the transaction
lifecycle. Finally the entry is removed when transaction resolves and it
is either committed or aborted.
The `group::ongoing_transaction` structure contains all information
about transaction state, pending offset commits and expiration.
- none

Refactored handling of consumer group transactions in Redpanda

---

src/v/pandaproxy/schema_registry/handlers.cc
tests/rptest/tests/schema_registry_test.py

This is an undocumented compatibility "feature".
* Schema Registry: `GET /subject/<subject>/versions/` now supports `-1` as an alias for `latest`.

[CORE-3245] schema_registry: Support -1 as latest for get_subject_version

---

src/v/pandaproxy/schema_registry/handlers.cc
tests/rptest/tests/schema_registry_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/20146

[v23.3.x] [CORE-3245] schema_registry: Support -1 as latest for get_subject_version

---

src/v/config/configuration.cc
src/v/config/configuration.h
src/v/kafka/server/client_quota_translator.cc
src/v/kafka/server/client_quota_translator.h
src/v/kafka/server/tests/client_quota_translator_test.cc
tests/rptest/tests/client_quota_deprecated_configs_test.py

This adds a warning log message to remind operators that the client quotas are now node-wide and that they are going to be deprecated in v25.1.
Fixes https://redpandadata.atlassian.net/browse/CORE-3046
* none

CORE-3046 Quotas: implement deprecated notice for quota configs

---

src/v/cluster/controller.cc
src/v/cluster/feature_manager.cc
src/v/cluster/shard_balancer.cc
src/v/cluster/shard_balancer.h
src/v/cluster/shard_placement_table.cc
src/v/cluster/shard_placement_table.h
src/v/cluster/topics_frontend.cc
src/v/cluster/topics_frontend.h
src/v/config/configuration.cc
src/v/config/configuration.h
src/v/redpanda/admin/api-doc/partition.json
src/v/redpanda/admin/partition.cc
src/v/redpanda/admin/server.h
tests/rptest/services/admin.py
tests/rptest/tests/shard_placement_test.py
tests/rptest/tests/topic_delete_test.py
tools/offline_log_viewer/kvstore.py

Introduce rebalancing partitions across cores triggered by the following events:
* core count change (only increase currently supported)
* partition replica removal from the node
* manually triggerred with admin API
* If the `node_local_core_assignment` flag is enabled, Redpanda will try to maintain balanced distribution of partition replicas across cores.

Node-local core assignment: rebalancing

---

src/v/pandaproxy/api/api-doc/schema_registry.json
src/v/pandaproxy/schema_registry/handlers.cc
src/v/pandaproxy/schema_registry/sharded_store.cc
src/v/pandaproxy/schema_registry/sharded_store.h
src/v/pandaproxy/schema_registry/store.h
tests/rptest/tests/schema_registry_test.py

Support `subjectPrefix` for `GET /subjects`
* Schema Registry: Support `subjectPrefix` for `GET /subjects`

[CORE-4442] schema_registry: Support subjectPrefix for get_subjects

---

.gitignore

During bundling of the `.rpk.ac.connect` plugin with `rpk`, we will now checkout code from https://github.com/redpanda-data/connect instead of https://github.com/redpanda-data/benthos.  We must add `/connect` to `.gitignore` to ensure local redpanda repo looks clean during packaging operations.
* none

[rpk connect] add /connect to .gitignore

---

src/v/cloud_storage/CMakeLists.txt
src/v/cloud_storage/fwd.h
src/v/cloud_storage/partition_manifest.h
src/v/cloud_storage/partition_path_utils.cc
src/v/cloud_storage/partition_path_utils.h
src/v/cloud_storage/remote_label.h
src/v/cloud_storage/remote_path_provider.cc
src/v/cloud_storage/remote_path_provider.h
src/v/cloud_storage/segment_path_utils.cc
src/v/cloud_storage/segment_path_utils.h
src/v/cloud_storage/spillover_manifest.h
src/v/cloud_storage/tests/CMakeLists.txt
src/v/cloud_storage/tests/remote_path_provider_test.cc
src/v/cloud_storage/topic_path_utils.cc
src/v/cloud_storage/topic_path_utils.h

Redpanda's current hash-prefixing naming scheme for objects leaves us open to collisions when multiple clusters point at the same bucket. We intend on moving away from this scheme in favor of one that includes the cluster UUID.
To this end, this PR adds various utility methods for generating paths for topic manifests, partition manifests, and remote segments. It also introduces a new `remote_path_provider` to be the centralized place where paths are created.
A later PR will plumb the path provider from partitions to the underlying archivers, purgers, anomaly detectors, etc.
* none

cloud_storage: add remote path provider

---

src/v/pandaproxy/schema_registry/sharded_store.cc
tests/rptest/clients/serde_client_utils.py
tests/rptest/tests/schema_registry_test.py

Wire up schema_registry support for json schema. 
this pr enables json schema inputs and adds a ducktape test for json schema compatibility 
* none

[CORE-4279] Wire up schema_registry/json

---

src/go/rpk/pkg/adminapi/api_transform.go
src/go/rpk/pkg/cli/transform/deploy.go
src/go/rpk/pkg/cli/transform/list.go
src/go/rpk/pkg/cli/transform/list_test.go
src/go/rpk/pkg/cli/transform/project/project.go
src/v/cloud_storage/topic_manifest.cc
src/v/model/model.cc
src/v/model/tests/lexical_cast_tests.cc
src/v/model/transform.cc
src/v/model/transform.h
src/v/redpanda/admin/api-doc/transform.json
src/v/redpanda/admin/transform.cc
src/v/transform/api.cc
src/v/transform/transform_processor.cc
tests/rptest/clients/rpk.py
tests/rptest/tests/data_transforms_test.py

This PR adds the ability to configure output batch compression on WASM transforms at deploy time or via metadata patch request. Includes rpk experience for the former. The latter case (metadata patch) is available via direct admin API invocation only.
TODO:
Closes CORE-2736
* Add output batch compression for Data Transforms (configurable per deployed transform)

[CORE-2736] Adds output batch compression for Data Transforms

---

tests/rptest/tests/raft_availability_test.py

The test was using an api expecting the node ordinal to query for the node that was elected as a leader. The query was based on the node id. This lead to the validation being invalid.
Fixes: #19953
- none

tests: fixed querying new leader node in leadership transfer test

---

src/v/archival/archival_policy.cc
src/v/archival/archival_policy.h
src/v/archival/ntp_archiver_service.cc
src/v/archival/ntp_archiver_service.h
src/v/archival/tests/CMakeLists.txt
src/v/archival/tests/ntp_archiver_test.cc
src/v/archival/tests/service_fixture.cc
src/v/archival/tests/service_fixture.h
src/v/cloud_storage/tests/s3_imposter.cc
src/v/http/include/http/tests/http_imposter.h
src/v/http/tests/http_imposter.cc

Adds a flushing mechanism to the `ntp_archiver` to allow for the forceful upload of all local data to cloud storage. Users can call `flush()` and then `wait()` in order to synchronize with the upload of a partition's data to cloud storage.
The uploads still take place in the `ntp_archiver`'s background upload loop, and when a `flush()` is issued, the `archival_policy` forces uploads in the same branch of logic to that of the `archival_configuration::time_limit` being reached.
A `flush()` is considered finished when the `partition_manifest`'s `_insync_offset` is greater or equal to the value of the `max_uploadable_offset_exclusive()` at the time `flush()` was called.
* none

archival: add `ntp_archiver::flush()`

---

.github/CODEOWNERS
.gitignore
src/go/.goreleaser_rp_connect.yaml

`.rpk.ac-connect` bundling to support `rpk connect` out of box was first introduced in `v24.1.x`.  We plan to continue with this bundling pattern until at least `v24.2.x`, our next minor release.  Therefore changes relevant to bundling support must be ported over.
This PR must land before any related vtools forward port PRs.  E.g. vtools will depend on `.goreleaser_rp_connect.yml`.
Specifically, I checked that `.goreleaser.yml` did not change between `v24.1.x` and `dev`, which means `.goreleaser_rp_connect.yml` could be safely picked from `v24.1.x` without any changes.  In other words, the delta between `.goreleaser.yml` and `.goreleaser_rp_connect.yml` did not change between `v24.1.x` and in this `dev` PR.
Original changes in `v24.1.x` branch:
* …

[rpk connect] fwd port .rpk.ac-connect bundling changes from v24.1.x

---

src/v/config/configuration.cc
src/v/config/configuration.h
src/v/kafka/server/client_quota_translator.cc
src/v/kafka/server/client_quota_translator.h
src/v/kafka/server/quota_manager.cc
src/v/kafka/server/tests/client_quota_translator_test.cc

During performance testing it became apparent that the overhead of quota management, while small, is non-negligible (~400ns/request). It is believed that some of our latency sensitive customers would prefer to avoid having this overhead on the request path. Therefore, this PR adds the ability to disable the produce quota config and sets it to disabled by default.
This is implemented without changing the configuration type (from `bounded_property<uint32_t>` to `property<std::optional<uint32_t>>`), instead I opted to use 0 as a sentinel value for disabled. Locally, I tested the change to `property<std::optional<uint32_t>>` as well, and it seems to work since the values are serialized to `ss::sstring` into the controller log and the serialized values of `uint32` seem to be a subset of those …

CORE-4600 - Quotas: disable produce quota by default 

---

src/v/cluster/cluster_utils.cc
src/v/features/feature_table.cc
src/v/features/feature_table.h
src/v/raft/consensus.cc
src/v/raft/consensus.h
src/v/raft/heartbeat_manager.cc
src/v/raft/heartbeat_manager.h
src/v/raft/recovery_stm.cc
src/v/raft/replicate_entries_stm.cc
src/v/raft/replicate_entries_stm.h
src/v/raft/tests/basic_raft_fixture_test.cc
src/v/raft/tests/replication_monitor_tests.cc
src/v/raft/types.cc
src/v/raft/types.h

If there are appends in flight and are stuck (eg: disk pressure on the follower), that may result in a spurious leadership step down due to heartbeat loss as the hbs are suppressed for the duration of the append. This commit switches to using lw heartbeats when there are inflight appends to avoid this scenario.
* Avoid spurious step downs if the append_entries are blocked for longer than usual on the followers.

lw heartbeats during inflight appends

---

src/v/cloud_storage/partition_path_utils.h
src/v/cloud_storage/segment_path_utils.h
src/v/cloud_storage/topic_path_utils.h

Adds some comments describing labeled and prefixed paths.
This is review follow-up from #20149
* none

cloud_storage: add clarifying comments around naming and versions

---

src/v/bytes/include/bytes/iobuf.h
src/v/cloud_storage/CMakeLists.txt
src/v/cloud_storage/base_manifest.h
src/v/cloud_storage/partition_manifest.h
src/v/cloud_storage/remote.cc
src/v/cloud_storage/remote.h
src/v/cloud_storage/tests/CMakeLists.txt
src/v/cloud_storage/tests/topic_manifest_downloader_test.cc
src/v/cloud_storage/tests/topic_manifest_test.cc
src/v/cloud_storage/topic_manifest.cc
src/v/cloud_storage/topic_manifest.h
src/v/cloud_storage/topic_manifest_downloader.cc
src/v/cloud_storage/topic_manifest_downloader.h
src/v/cluster/cloud_metadata/manifest_downloads.cc
src/v/cluster/remote_topic_configuration_source.cc

When performing topic recovery, Redpanda looks for topic manifests for
the target topic, first looking for a binary manifest, and then looking
for a JSON manifest (see cluster/remote_topic_configuration_source.cc).
With the upcoming naming scheme changes, this will need to change to
account for cluster UUID labels.
This commit introduces a topic manifest downloader for this purpose.
A later commit will replace most of `download_topic_manifest()` in
cluster/remote_topic_configuration_source.cc with this new downloader.
For now, this just adds the class and adds some tests.
Note that the new downloader has an optional "hint" that can be used to
differentiate topic manifests from different clusters (or even from
different revisions in the same cluster).
* none

cloud_storage: add topic manifest downloader

---

src/v/http/client.cc

Previously, we would call `client::stop()` upon encountering TLS errors in `client::send_some()`, `client::recv_some()` and `client::make_request()`. These stopped `client`s would not be removed from the `client_pool`, resulting in erroneous use for future requests.
Change the default behavior from calling `stop()` to `shutdown()`, which leaves `client` in a usable state for the future, after a connection is re-attempted.
Also improve logging around TLS errors, `_connect_gate`, and add checks around the state of `_stopped` in `client::make_request()` and `get_connected()`.
(cherry picked from commit b6621fe5330487b6d652657deac001f55b35692f)
Fixes #20588 
* none

[CORE-4878] [v23.3.x] http: change `stop()` to `shutdown()` on TLS errors in `client` (manual backport)

---

src/v/cloud_storage/partition_manifest.cc
src/v/cloud_storage/partition_manifest.h
src/v/cloud_storage/remote_path_provider.cc
src/v/cloud_storage/remote_path_provider.h
src/v/cloud_storage/spillover_manifest.h
src/v/cloud_storage/tests/remote_path_provider_test.cc
src/v/cloud_storage/topic_manifest.cc
src/v/cloud_storage/topic_manifest.h

- adds some methods to partition_manifest and topic_manifest to ease the transition towards using path provider everywhere
- adds to the path provider a method to get the topic manifest JSON path, if supported (similar to the one for partition manifests)
* none

cloud_storage: add some convenience methods for working with path provider

---

tests/rptest/tests/raft_availability_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/20378
Fixes: https://github.com/redpanda-data/redpanda/issues/20579,

[v24.1.x] tests: fixed querying new leader node in leadership transfer test

---

src/v/cloud_storage/CMakeLists.txt
src/v/cloud_storage/partition_manifest_downloader.cc
src/v/cloud_storage/partition_manifest_downloader.h
src/v/cloud_storage/tests/CMakeLists.txt
src/v/cloud_storage/tests/partition_manifest_downloader_test.cc

There are various calls to download partition manifests (e.g. read replicas,
partition recovery, Raft snapshot recovery) where the application
doesn't necessarily care about the format or path of the manifest. These
callers typically use remote::try_download_partition_manifest(), which
checks for both the binary and JSON manifest.
Since the naming scheme of objects is changing, this introduces a
downloader that performs this same operation, but also takes into
account the naming scheme.
A later commit will plug this into the various users to replace
try_download_partition_manifest().
I considered moving this logic into the remote, but generally the remote
seems to have grown crowded with business logic. Naming scheme seems
like it should fall outside of the remote's concern, considering …

cloud_storage: add partition manifest downloader

---

tests/rptest/transactions/transactions_test.py
tests/rptest/transactions/tx_coordinator_migration_test.py

Most of our transactions tests were build based with the same code which often were copy pasted. The test were setting the default transaction timeout to 10 seconds as they might have been based on the test that validated the transactions expiration. Updated the tests to make sure that the timeout is set in the test that need it.
The timeout made some tests to fail intermittently.
Fixes: #18184
- none

Do not set transaction timeout in tests that do not need it

---

src/v/raft/consensus.cc
src/v/raft/consensus.h
src/v/raft/tests/basic_raft_fixture_test.cc
src/v/raft/tests/raft_fixture.cc
src/v/raft/tests/raft_fixture.h

When a node currently being a raft group leader is not a part of new
configuration it must step down and become a follower. When stepping
down a leader stops sending heartbeats to the followers allowing them to
trigger election. The election starts only after an election timeout
elapsed on on of the followers. This makes the whole process
slow and during the whole time clients can not write and read from the
raft group as it is leaderless. To address this issue a new method of
step down was introduced. The new stepdown implementation which is
going to be used for reconfiguration requests one of the followers to
timeout immediately and trigger leader election. This speeds up the
whole process and makes it much less disruptive as the stepdown is now
comparable to leadership transfer.
Time …

Transfer leadership before stepping down after reconfiguration

---

src/v/pandaproxy/schema_registry/json.cc
src/v/pandaproxy/schema_registry/test/test_json_schema.cc

Implements `is_array_superset`, the function that performs compatibility checks for `"type": "array"` json schemas.
Note1: `"type": "array"` can express proper arrays or tuples. Tuples have a validation logic similar to `"type": "object"` schemas, so the compatibility check, too, has a similar logic.
Note 2: for tuples, the syntax changed between Draft 4 and later drafts. To prevent erroneous validation, `"prefixItems"` keyword is added to the list of not implemented features.
Last commit fixed an edge case for `"min__"` properties. these have a default value of 0, so these two schemas
`{"type": "string"}` and `{"type": "string", "minLength": 0 }` should be considered compatible (equivalent, in fact)
* none

[CORE-3186] schema registry json schema: array compatibility checks

---

src/v/cluster/rm_stm.h
src/v/features/feature_table.cc
src/v/features/feature_table.h
src/v/kafka/CMakeLists.txt
src/v/kafka/server/group.cc
src/v/kafka/server/group.h
src/v/kafka/server/group_data_parser.h
src/v/kafka/server/group_manager.h
src/v/kafka/server/group_recovery_consumer.cc
src/v/kafka/server/group_recovery_consumer.h
src/v/kafka/server/group_tx_tracker_stm.cc
src/v/kafka/server/group_tx_tracker_stm.h
src/v/kafka/server/tests/CMakeLists.txt
src/v/kafka/server/tests/group_tx_compaction_test.cc
src/v/model/model.cc
src/v/model/record_batch_types.h
src/v/redpanda/application.cc
src/v/storage/compaction_reducers.cc
src/v/storage/compaction_reducers.h
src/v/storage/segment_utils.h
src/v/storage/types.h

Fixes two main issues related to compaction of group transactions:
* There was no enforcement of max_collectible_offset, so open transactions were candidates for compaction
* https://github.com/redpanda-data/redpanda/pull/16295 disabled compaction of all control batches (all transactional batches in group topic are control batches) effectively disabling compaction of the topic.
These issues are addressed by adding a new state machine that enforces max_collectible_offset and then allowing compaction of control batch types from group transactions.
* Fixes compaction related issues of transactional data in groups topic. This prevents a case where groups topic was growing unbounded due to ineffective compaction.

group/transactions: compaction fixes

---

tests/rptest/perf/openmessaging_perf_test.py
tests/rptest/perf/small_batches_test.py
tests/rptest/perf/ts_write_openmessaging_test.py

Leader balancer only kicks after 0-2 minutes. If it kicks in after the
warmup period ends it will cause noisy results.
Up the warmup to two minutes to make sure it falls into the warmup
period.
We don't have any many partition tests here so the process should finish
relatively fast. Also there is a little bit of leeway as the warmup
doesn't immediatley start after the topic has been created.
Note I am not changing the TS read test because I first need to confirm
it still behaves fine in regards to the backlog.
* none

cdt-perf: Put OMB warmup to two minutes

---

src/v/cluster/cluster_utils.cc
src/v/cluster/cluster_utils.h
src/v/cluster/controller.cc
src/v/cluster/controller.h
src/v/cluster/controller_backend.cc
src/v/cluster/controller_backend.h
src/v/cluster/scheduling/allocation_node.cc
src/v/cluster/shard_balancer.cc
src/v/cluster/shard_balancer.h
src/v/cluster/shard_placement_table.cc
src/v/cluster/shard_placement_table.h
src/v/cluster/tests/shard_placement_table_test.cc
src/v/raft/consensus_utils.cc
src/v/raft/consensus_utils.h
src/v/raft/persisted_stm.cc
src/v/raft/persisted_stm.h
src/v/storage/api.h
src/v/storage/disk_log_impl.cc
src/v/storage/disk_log_impl.h
src/v/storage/kvstore.cc
src/v/storage/kvstore.h
src/v/storage/offset_translator.cc
src/v/storage/offset_translator.h
src/v/storage/tests/kvstore_fixture.h
src/v/storage/tests/offset_translator_tests.cc
src/v/storage/tests/storage_test_fixture.h
tests/rptest/tests/node_resize_test.py
tests/rptest/tests/shard_placement_test.py

Implement copying partition data from extra kvstore shards (i.e. kvstore shards with ids >= current shard count) and use it to allow decreasing core count.
* Allow decreasing core count if node-local core assignment is enabled.

Node-local core assignment: core count decrease

---

src/v/cloud_storage/tests/remote_path_provider_test.cc
src/v/cloud_storage/tests/topic_manifest_downloader_test.cc
src/v/cloud_storage/topic_manifest_downloader.cc
src/v/cloud_storage/topic_manifest_downloader.h
src/v/cloud_storage/topic_path_utils.cc
src/v/cloud_storage/topic_path_utils.h

This adds a find_manifests() method to the topic_manifest_downloader.
This will subsume the logic currently in topic_recovery_service, that
lists objects in the buckets looking for objects that look like topic
manifests. With our object naming scheme changing, this will need to
account for the new naming scheme.
Admittedly, there's somewhat of an impedence mismatch since the
topic_manifest_downloader expects to target one topic, so this just
makes the method static. But it still feels natural for this logic and
its tests to be coupled to topic_manifest_downloader.
The code isn't as optimal as it could be in terms of number of list/get
operations performed, since I wanted to rely on the downloader to
duplicating some of the path-related complexity. But this endpoint is
likely not going to …

cloud_storage: topic_manifest_downloader::find_manifests

---

src/v/cluster/commands.h
src/v/cluster/controller_log_limiter.h
src/v/cluster/tests/serialization_rt_test.cc
src/v/cluster/types.cc
src/v/cluster/types.h
src/v/kafka/server/handlers/alter_configs.cc
src/v/kafka/server/handlers/configs/config_response_utils.cc
src/v/v8_engine/data_policy.h

Remove some data policy bits. There are still data types lingering around in some of the controller log types which aren't so easy to remove, but we can create some kind of deprecation area for such types which Ill do in a separate PR.
But this PR removes what appears to be trivial to remove as the types are not references anywhere except tests.
* none

cluster: remove some data policy bits

---

tools/rp_storage_tool/src/bucket_reader.rs
tools/rp_storage_tool/src/fundamental.rs
tools/rp_storage_tool/src/main.rs
tools/rp_storage_tool/src/ntp_mask.rs
tools/rp_storage_tool/src/remote_types.rs
tools/rp_storage_tool/src/repair.rs

Upcoming changes will enable supplying a cluster UUID to a topic to change the remote paths that get used. To account for this, this changes rp_storage_tool to look for the new path format and collect the cluster UUID labels. This will allow us to continue running rp_storage_tool in ducktape tests once the feature is enabled.
The high level approach taken here is to collect and serialize labels as a part of the NTPR and NTR objects that are associated with objects and anomalies. The label is optional, and a None label will refer to hash-prefixed objects.
This has change has been seen to allow CI to pass in a feature branch I'm working in: https://buildkite.com/redpanda/redpanda/builds/50695#_
* none

rp_storage_tool: account for labels

---

src/v/cluster/cluster_utils.cc
src/v/raft/consensus.cc
src/v/raft/consensus.h
src/v/raft/heartbeat_manager.cc
src/v/raft/heartbeat_manager.h
src/v/raft/recovery_stm.cc
src/v/raft/replicate_entries_stm.cc
src/v/raft/replicate_entries_stm.h
src/v/raft/tests/basic_raft_fixture_test.cc
src/v/raft/tests/replication_monitor_tests.cc
src/v/raft/types.cc
src/v/raft/types.h

If there are appends in flight and are stuck (eg: disk pressure on the follower), that may result in a spurious leadership step down due to heartbeat loss as the hbs are suppressed for the duration of the append. This commit switches to using lw heartbeats when there are inflight appends to avoid this scenario.
Fixes https://github.com/redpanda-data/redpanda/issues/20591
* Avoid spurious step downs if the append_entries are blocked for longer than usual on the followers.

[backport] [v24.1.x] lw heartbeats during inflight appends

---

src/v/compression/tests/zstd_tests.cc
src/v/container/tests/fragmented_vector_async_test.cc
src/v/container/tests/fragmented_vector_test.cc
src/v/container/tests/interval_set_test.cc
src/v/container/tests/map_bench.cc
src/v/random/tests/random_test.cc
src/v/utils/tests/uuid_test.cc
src/v/utils/tests/vint_bench.cc

chore: fix -Wsign-compare warnings
* none

chore: fix -Wsign-compare warnings

---

tests/rptest/tests/transactions_test.py
tests/rptest/tests/tx_coordinator_migration_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/20743
Fixes: https://github.com/redpanda-data/redpanda/issues/20745,

[v23.3.x] Do not set transaction timeout in tests that do not need it

---

src/v/cluster/client_quota_serde.h
src/v/cluster/tests/client_quota_store_test.cc
src/v/kafka/server/quota_manager.h

This addresses some comments from @dotnwat on previous PRs:
* https://github.com/redpanda-data/redpanda/pull/19795#discussion_r1656138146
> you can drop int8_t -- serde will always store them as 32-bit integers.
* https://github.com/redpanda-data/redpanda/pull/19941#discussion_r1655233044:
> where is the use of std::shared_ptr being documented? there is probably what like 1 or 2 uses in the entire tree, and its always discouraged. this use case is fine, but how will future developers learn about the usage? a good place for it would be in the code as a comment, or in the commit message, but i don't see any information in either place. can you please point me at the documentaiton or submit a pr that adds it?
* none

Quotas: address post merge code review comments

---

src/v/cluster/controller_api.cc
src/v/cluster/controller_backend.cc
src/v/cluster/metadata_cache.cc
src/v/cluster/partition_balancer_planner.cc
src/v/cluster/scheduling/leader_balancer.cc
src/v/cluster/shard_balancer.cc
src/v/cluster/shard_placement_table.cc
src/v/cluster/tests/cluster_test_fixture.h
src/v/cluster/tests/metadata_dissemination_test.cc
src/v/cluster/tests/partition_balancer_simulator_test.cc
src/v/cluster/tests/rebalancing_tests_fixture.h
src/v/cluster/tests/replicas_rebalancing_tests.cc
src/v/cluster/tests/topic_table_test.cc
src/v/cluster/topic_table.cc
src/v/cluster/topic_table_partition_generator.cc
src/v/cluster/topic_updates_dispatcher.cc
src/v/cluster/topics_frontend.cc
src/v/cluster/tx_gateway_frontend.cc
src/v/cluster/types.cc
src/v/cluster/types.h
src/v/container/include/container/contiguous_range_map.h
src/v/kafka/server/handlers/metadata.cc
src/v/kafka/server/handlers/topics/topic_utils.cc
src/v/redpanda/admin/partition.cc
src/v/redpanda/admin/server.cc
src/v/redpanda/tests/fixture.h

The partition assignments set is a great candidate to use the
`contiguous_range_map` as it always contains all the topic partitions
starting from 0 up to the partition count.
- none

Using `contiguous_range_map` to store partitions assignments

---

src/go/rpk/pkg/cli/registry/schema/schema.go
src/go/rpk/pkg/cli/registry/schema/schema_test.go

jsonschema will introduce URIs as valid reference names.
* none

rpk: allow names to be URIs in the reference flag when creating a schema.

---

src/v/cluster/client_quota_frontend.cc
src/v/cluster/client_quota_frontend.h
src/v/cluster/client_quota_serde.h
src/v/cluster/controller.cc
src/v/cluster/controller.json
src/v/cluster/service.cc
src/v/cluster/service.h
src/v/kafka/server/handlers/client_quotas.cc
src/v/redpanda/application.cc
tests/rptest/clients/rpk.py
tests/rptest/tests/quota_management_test.py

While testing client quotas on real clusters I noticed that the alter command was failing occasionally when the alter request was sent to a node that wasn't the controller leader. I was previously under the impression that kafka admin requests are automatically redirected to the controller leader, however, that is not the case. Neither rpk nor kafka-configs.sh redirects kafka admin requests to the controller leader. It is only the admin API requests that rpk automatically sends to the controller leader.
This PR implements redirecting alter client quota commands to the controller leader and improves the error reporting on update failures.
https://redpandadata.atlassian.net/browse/CORE-2074
* none

CORE-2074 Quotas: redirect alter quotas command to leader

---

src/v/kafka/server/handlers/fetch.cc

The use of `ss::when_any` and `ss::promise<>` for each progress condition resulted in unneeded allocations as well as expensive broken promises and exception propagation. This commit changes all progress conditions to signal the same `ss::condition_variable` instead. This simplifies their handling and greatly reduces their cost.
The profile for progress conditions before this PR;
And then after this PR;
* none

Improve handling of progress conditions in non-polling fetch

---

src/go/rpk/pkg/adminapi/api_transform.go
src/go/rpk/pkg/cli/transform/deploy.go
src/go/rpk/pkg/cli/transform/project/project.go
src/v/features/feature_table.cc
src/v/features/feature_table.h
src/v/model/fundamental.h
src/v/model/transform.cc
src/v/model/transform.h
src/v/redpanda/admin/api-doc/transform.json
src/v/redpanda/admin/transform.cc
src/v/transform/api.cc
src/v/transform/io.h
src/v/transform/tests/test_fixture.cc
src/v/transform/tests/test_fixture.h
src/v/transform/transform_processor.cc
tests/rptest/clients/rpk.py
tests/rptest/tests/data_transforms_test.py

This PR wires up the ability to configure the start offset of a transform at deploy time. This can be either a unix timestamp (ms since epoch) or an offset delta (+oo from start offset of -oo from end).
Includes rpk experience.
* Adds the ability to start transform processing from an arbitrary offset on the input topic.

[CORE-2841] Transforms: Start consuming from an arbitrary offset (numeric from start/end or timestamp)

---

src/v/config/configuration.cc
src/v/config/property.h
src/v/config/tls_config.cc
src/v/security/CMakeLists.txt
src/v/security/acl.cc
src/v/security/config.h
src/v/security/config_bsl.cc
src/v/security/config_rcl.cc
src/v/security/gssapi_principal_mapper.cc
src/v/security/gssapi_principal_mapper.h
src/v/security/gssapi_rule.cc
src/v/security/gssapi_rule.h
src/v/security/logger.cc
src/v/security/mtls.cc
src/v/security/mtls.h
src/v/security/mtls_rule.cc
src/v/security/mtls_rule.h
src/v/security/oidc_authenticator.cc
src/v/security/oidc_principal_mapping.h
src/v/security/oidc_principal_mapping_applicator.cc
src/v/security/oidc_principal_mapping_applicator.h
src/v/security/tests/oidc_principal_mapping_test.cc

Fixes circular dependency between security and config libraries.
* none

security: fix security-config circular dependency

---

tests/rptest/transactions/tx_atomic_produce_consume_test.py

The exactly once delivery semantic tests was using a stop condition where a size of the finished processing partition set was compared with the size of high watermark list. Sometimes the high watermark list may not contain all the partitions as they are not reported when there is no leader. This lead to test stopping to early and desitination topic missing some messages.  Changed the test to use the topic partition count in the stop condition instead.
Fixes: #20315
- none

tests: made atomic consume-transform-produce test more robust

---

src/v/raft/tests/replication_monitor_tests.cc

Additionally reduces sleep durations to make the test faster.
* none

replication_monitor/test: add diagnostic on assertion failure

---

src/go/rpk/go.mod
src/go/rpk/go.sum
src/go/rpk/pkg/serde/avro.go
src/go/rpk/pkg/serde/avro_test.go
src/go/rpk/pkg/serde/jsonschema.go
src/go/rpk/pkg/serde/jsonschema_test.go
src/go/rpk/pkg/serde/serde.go

Now rpk support "encoding" and "decoding" records using JSON schemas in the schema registry. rpk will validate the record before decoding or encoding it.
Along with https://github.com/redpanda-data/redpanda/pull/19947 and https://github.com/redpanda-data/redpanda/pull/20757 this completes the support of JSON schemas in rpk.
* rpk: Add support to JSON Schema to rpk, now supported in `rpk registry` and `rpk topic produce/consume`

rpk: add support to produce/consume with jsonschema

---

tests/rptest/services/redpanda.py

Lots of tests implicitly trigger the non-fatal cases as they don't wait
for all uploads to finish.
It being a warning means it gets output on the main DT output (the one
with all the test results) and hence causes quite a bit of noise.
* none

tests: Downgrade warning for non-fatal anomalies

---

tests/rptest/services/metrics_check.py
tests/rptest/tests/raft_availability_test.py

Instead of asserting right away added a wait for the leadership change metric to be updated.
Fixes: #20574
- none

tests: wait for the leadership change metric to be updated

---

src/v/raft/state_machine_manager.cc
src/v/raft/state_machine_manager.h
src/v/raft/tests/stm_manager_test.cc

wait for background applicators to finish before applying raft
snapshots, else there is a danger of next_to_apply offset moving
backwards with interleaved bg_apply and snapshot fibers.
Fixes https://github.com/redpanda-data/redpanda/issues/18415
* Fixes incorrect updates to next offset to be applied when racing with applying raft snapshots.

stm_manager: tighten interaction between bg application and snapshots 

---

src/v/kafka/server/tests/group_tx_compaction_test.cc

When a group boots up and recovers, a version fence batch is asynchronously written to the log. In slow debug builds, this can happen in the middle of a test run and is conflicting with offset expecations. This fix waits for the version fence batch to be written before the test execution begins.
* none

group/tx/tests: deflake group_tx_compaction_test

---

src/v/utils/tests/CMakeLists.txt
src/v/utils/tests/coro_bench.cc
src/v/utils/tests/vint_bench.cc

bench: split out coro_rpbench from vint_rpbench
Split vint_bench into vint_bench and coro_bench, with the latter having
the generic coroutine/continuation type benches and vint only being
left with the specific vint stream decoding stuff.
coro_bench: updates with more patterns
Test a few more call patterns such as chaining vs nesting when the first
future is non-ready.
* none

Coroutine bench updates

---

src/v/raft/state_machine_manager.cc
src/v/raft/state_machine_manager.h
src/v/raft/tests/stm_manager_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18576
Fixes: https://github.com/redpanda-data/redpanda/issues/21253,

[v23.3.x] stm_manager: tighten interaction between bg application and snapshots 

---

src/v/model/tests/transform_test.cc
src/v/model/transform.cc

s/transform_offset_options/legacy_transform_offset_options/
Also adds unit tests to try prove out the theory of selectively writing out older versions of the serde::variant. Works as expected.
Also worth noting that this works regardless of the serde::envelope CRTP param fixed by this diff...perhaps that's due to the narrow scope of the legacy struct - only ever being written out explicitly in transform_metadata::serde_write.
* none

model/x: Fix typo in legacy offset_options envelope template

---

src/v/pandaproxy/schema_registry/sharded_store.cc
src/v/pandaproxy/schema_registry/sharded_store.h
src/v/pandaproxy/schema_registry/store.h
tests/rptest/tests/schema_registry_test.py

When the last subject version corresponding to a schema is deleted, schema registry should also remove the schema.
On the topic, the schema is already considered deleted when the last subject version is deleted, and compaction takes care of removing it. However, without this change, compaction needs to happen and then a node restart needs to happen before the schema is removed from memory. This is not ideal for use cases where schemas are frequently created and deleted (eg. Serverless), so instead we can remove the schema from memory when its last subject version is deleted.
Fixes https://redpandadata.atlassian.net/browse/CORE-5083
* Schema Registry: remove the schema from memory when the last subject version referencing it is deleted.

CORE-5083 schema_registry: last subject deletes schema

---

src/v/pandaproxy/schema_registry/error.cc
src/v/pandaproxy/schema_registry/errors.h
src/v/pandaproxy/schema_registry/json.cc
src/v/pandaproxy/schema_registry/test/test_json_schema.cc
src/v/pandaproxy/schema_registry/types.cc
src/v/pandaproxy/schema_registry/types.h

This is a small part of CORE-3182
* none

[CORE-3182] Schema registry/json: Reject a schema if a reference doesn't exist

---

src/v/pandaproxy/schema_registry/json.cc
src/v/pandaproxy/schema_registry/test/test_json_schema.cc

- break recursion for `is_superset(get_true_schema(), ...)` and `is_superset(..., get_false_schema())` these two cases can happens for properties that don't have a default value: for example `{"type": "array"}` has no `"items"`, so it gets the default value of `{}`. without this early break, we get in an infinite recursion where `{}` is passes through `is_array_superset` and that in turn will call `is_superset` and so on
- add support for draft5: according to the official documentation, this dialect reuses the metaschema for draft4, and so does the code
- support for draft6 : the metaschema is adapted to draft4, because the current version of rapidjson implements only draft4
- support for draft7 : the metaschema is adapted to draft4, same reasons
- support for schemas uris without …

[CORE-4181] schema registry json support validating drafts 5 6 and 7 

---

src/go/rpk/pkg/cli/cloud/byoc/byoc.go

Mark `rpk cloud byoc azure` as a registered command for rpk. It activates the current login + download flow.
* none

rpk cloud byoc: register azure as valid option

---

src/v/cluster/types.h

cluster: remove unused code

---

src/v/io/tests/interval_map_test.cc

io: fix -Wsign-compare errors
* none

io: fix -Wsign-compare errors

---

tests/rptest/services/redpanda_cloud.py

[tests] Add public_api_url to CloudClusterConfig

---

src/v/net/tests/conn_quota_test.cc

net: fix unused parameter warnings
* none

net: fix unused parameter warnings

---

src/v/pandaproxy/schema_registry/sharded_store.cc
src/v/pandaproxy/schema_registry/sharded_store.h
src/v/pandaproxy/schema_registry/store.h
tests/rptest/tests/schema_registry_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/20847

[v24.1.x] CORE-5083 schema_registry: last subject deletes schema

---

src/v/pandaproxy/schema_registry/sharded_store.cc
src/v/pandaproxy/schema_registry/sharded_store.h
src/v/pandaproxy/schema_registry/store.h
tests/rptest/tests/schema_registry_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/20847

[v23.3.x] CORE-5083 schema_registry: last subject deletes schema

---

src/v/cloud_storage/CMakeLists.txt
src/v/cloud_storage/inventory/inv_consumer.cc
src/v/cloud_storage/inventory/inv_consumer.h
src/v/cloud_storage/inventory/ntp_hashes.cc
src/v/cloud_storage/inventory/ntp_hashes.h
src/v/cloud_storage/inventory/report_parser.cc
src/v/cloud_storage/inventory/report_parser.h
src/v/cloud_storage/inventory/tests/CMakeLists.txt
src/v/cloud_storage/inventory/tests/common.cc
src/v/cloud_storage/inventory/tests/common.h
src/v/cloud_storage/inventory/tests/inv_consumer_tests.cc
src/v/cloud_storage/inventory/tests/report_parser_tests.cc
src/v/compression/CMakeLists.txt
src/v/compression/gzip_stream_decompression.cc
src/v/compression/include/compression/gzip_stream_decompression.h
src/v/compression/tests/CMakeLists.txt
src/v/compression/tests/gzip_stream_decompression_tests.cc

The following three utilities are added in this PR:
* inventory report parser
* inventory report consumer
* ntp hash loader
A report parser is added which will accept an input stream created during a report download, and fetch lines from it and provide them to a consumer. The report may optionally be gzip compressed, in this case it is decompressed while being read from the stream.
The inventory report consumer takes an input stream (or potentially multiple streams one after another) created from a report download, extracts rows from the stream using the report parser and converts them to path hashes. It then writes the path hashes to files per NTP on disk, making sure that total size held in memory is kept below a threshold by periodically flushing contents to disk.
The hash loader given …

cst/inv: Add tooling for parsing, writing and reading inventory reports

---

tests/rptest/test_suite_cloud.yml

This test was disabled while we were trying to get all the cloud tests green and we had the latency spike issue. Per redpanda-data/redpanda#15334 we now have retry logic and in any case this test is only "just as affected" as test_common which are successfully running (for the most part).
So re-enable it by specifying the entire OMBValidationTest class in the suite.
* none

cloud tests: run all OMB validation tests

---

src/v/cloud_storage/remote_partition.cc
src/v/cloud_storage/remote_path_provider.cc
src/v/cloud_storage/remote_path_provider.h
src/v/cloud_storage/topic_manifest_downloader.cc
src/v/cloud_storage/topic_manifest_downloader.h
src/v/cluster/partition_manager.cc
src/v/cluster/topics_frontend.cc
tools/offline_log_viewer/controller.py

Review follow-up to https://github.com/redpanda-data/redpanda/pull/20778
- Adds logging to the topic_manifest_downloader. I considered adding more logging to the partition_manifest_downloader, which is in contrast much simpler, but it seems less complicated and has less context to log.
- Fixes typo in offline_log_viewer.
- Makes remote_path_provider harder to copy around, to encourage code authors to hopefully make it clearer that the archival metadata STM is the primary provider used across archival and cloud_storage subsystems.
- Adds a comment clarifying usage of path provider at partition-creation time.
- Adds a comment clarifying condition of setting the remote lable.
* none

cloud_storage: miscellaneous non-functional changes

---

src/v/raft/tests/raft_fixture.cc
src/v/raft/tests/raft_fixture.h
src/v/raft/tests/raft_reconfiguration_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/20816
Fixes: https://github.com/redpanda-data/redpanda/issues/20842,

[v24.1.x] tests: added retries to raft force reconfiguration test

---

src/v/cluster/partition.cc
tests/rptest/tests/timequery_test.py

Before querying local log we bump the `timequery_config::min_offset`. This offset is inclusive. When local log is empty, the min_offset points one unit above the end of the log. In this PR, we add a check to return early when this is the case.
* Fix timequery failing when requested timestamp is in the future and local log is empty.

kafka: fix timequery when local log is empty

---

src/v/transform/api.cc
src/v/transform/io.h
src/v/transform/tests/test_fixture.cc
src/v/transform/tests/test_fixture.h
src/v/transform/transform_processor.cc
tests/rptest/tests/data_transforms_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/20127

[v24.1.x] Transforms: Fix deploy-time timequery bug

---

tests/docker/Dockerfile

Docker warns on mixed case now so use FROM ... AS to silence this spam.
* none

testing/Dockerfile: use AS not as

---

src/v/cluster/rm_stm.cc

A commit replay can happen in the following cases for example:
1. Coordinator marked the tx as prepared, dispatched remote commit_tx and
crashed. Recovers notices the transaction as prepared and attempts to
roll forward the transaction (recommit).
2. Coordinator lost leadership as it was dispatching remote commit_tx,
got frozen, a new leader takes over, commits and bumps the sequence
number to start a new transaction. Meanwhile the original coordinator
recovers from frozen state and starts retrying for a brief period
(rare case).
Prior to this commit, in case of replayed commits, if the partition lost
the transaction state, it was rejecting the request as invalid. The
transaction state can be lost due to producer eviction or with the
sequence number advancing. This can result in a stuck …

tx/rm_stm: fix handling of replay commit requests

---

.github/workflows/build-bazel.yml

There is an issue loading secrets from repository forks. The only real viable solution is to ask all engineers to submit PRs from branches pushed to the upstream repo, but this is a major change given that we'll move to buildkite soon anyway. So the plan now is to just re-home the workflow to buildkite in the short term.
* none

bazel: disable github workflow for pull requests

---

src/v/archival/archiver_operations_api.cc
src/v/archival/archiver_operations_api.h
src/v/archival/archiver_operations_impl.cc
src/v/archival/archiver_operations_impl.h
src/v/archival/tests/CMakeLists.txt
src/v/archival/tests/archiver_operations_impl_gtest.cc
src/v/cloud_storage/partition_manifest.cc
src/v/cloud_storage/partition_manifest.h
src/v/cloud_storage/tx_range_manifest.cc
src/v/cloud_storage/tx_range_manifest.h
src/v/cluster/CMakeLists.txt

Introduce `archiver_operations_api` interface. The interface is responsible for the data upload operations. There are three main steps there
- find upload candidates (find offset range that exists only locally and has to be uploaded to the cloud)
- schedule uploads (for every upload candidate upload the segment object, the index and transactional manifest)
- admit uploads (check results of the previous operations, validate the metadata and replicate archival STM commands)
This interface can use read-write fence for concurrency control. 
The PR also adds implementation `archiver_operations_impl` but implements only the first operation. The implementation uses `storage::log_reader` to get data from disk instead of reading data directly.
* none

archival: Update ntp_archiver (pt.1)

---

tests/rptest/tests/scaling_up_test.py

Increased tolerance for the size of partitions on a node added to the cluster. The expected partition size may vary as it is dependent from the segment size and non log data. The tolerance allow us to account for the variability without compromising the test correctness.
Fixes: #20225
- none

tests: increase tolerance in local retention movement test

---

conf/redpanda.yaml

We have been supporting Ext4 for awhile now. This changes the verbiage in our default configuration file to reflect that as well as corrects some typos. While here, updates the year in the copyright line.
* none

Correct verbiage about data partition in redpanda.yaml

---

src/v/cluster/self_test/cloudcheck.cc
src/v/cluster/self_test/cloudcheck.h
src/v/cluster/self_test/metrics.h

The start/end times for tests ran with the `self-test` tool were [recently added](https://github.com/redpanda-data/redpanda/commit/bc7d5bfdd831447f5dbb5b364dbf74272cad0dc3) to the output of `rpk config self-test status`.
These times were not being set in the cloud storage `self-test`, and thus the `START` and `END` times would both be epoch time, i.e
```
NAME          Cloud Storage Test
INFO          Put
TYPE          cloud
TEST ID       2cf3b181-3cb8-4502-a987-28dfd60f4f12
TIMEOUTS      0
START TIME    Thu Jan  1 00:00:00 UTC 1970
END TIME      Thu Jan  1 00:00:00 UTC 1970
AVG DURATION  7ms
```
This PR fixes the start and end time outputted for the result of the test, for either failed or successful tests.
```
NAME          Cloud Storage Test
INFO          Put
TYPE          cloud
TEST ID …
```

cluster: fix cloud storage `self-test` start/end time output

---

tests/rptest/services/kgo_verifier_services.py

There are 2 ways to stop a kgo service. One is graceful shutdown and another one is hard stop. We use 2 `threading.Event` objects to signal this.
Before this change, the polling thread would only wait on the `_stop_requested` and if it was set or if a timeout is hit (self.INTERVAL=5s) it would run the loop again and check if stop or shutdown was requested.
This leads for shutdown taking 5s more than it should in worst case.
We avoid this extra wait but settling on a single threading.Event object (_shutdown_requested) for signaling that the loop should run again. Then we signal that event from both, shutdown and hard stop.
* none

rptest/kgo: avoid extra wait on shutdown

---

src/v/cloud_storage/tests/cloud_storage_e2e_test.cc
src/v/cluster/partition.cc
src/v/cluster/partition.h
src/v/cluster/partition_recovery_manager.cc
src/v/cluster/topics_frontend.cc
src/v/config/convert.h
src/v/kafka/server/handlers/alter_configs.cc
src/v/kafka/server/handlers/configs/config_response_utils.cc
src/v/kafka/server/handlers/delete_records.cc
src/v/kafka/server/tests/consumer_groups_test.cc
src/v/model/fundamental.h
src/v/model/model.cc
src/v/storage/disk_log_impl.cc
src/v/storage/disk_log_impl.h
src/v/storage/log.h
src/v/storage/ntp_config.h
src/v/storage/tests/storage_e2e_test.cc
src/v/storage/tests/utils/disk_log_builder.h
tests/rptest/clients/types.py
tests/rptest/tests/archival_test.py
tests/rptest/tests/controller_snapshot_test.py
tests/rptest/tests/describe_topics_test.py
tests/rptest/tests/topic_creation_test.py

This fixes a bug in the kafka layer where redpanda would set the `cleanup.policy` config for every new topic even if this was not explicitly specified by the topic creation request. Instead, the expected behaviour is that this topic-level config is not set, but instead, redpanda should fall back in the case of an unset `cleanup.policy` to the cluster-level default without hardcoding that default at the topic-level.
Fixes https://redpandadata.atlassian.net/browse/CORE-526
Fixes https://redpandadata.atlassian.net/browse/CORE-2807
* This fixes a bug in kafka topic configs, where the `cleanup.policy` config was always set at the topic-level to the cluster default even when the topic creation request did not specify this.

CORE-526 k/configs: dont override topic-level cleanup policy

---

src/go/rpk/pkg/cli/cluster/quotas/describe.go
src/go/rpk/pkg/cli/cluster/quotas/import.go
src/go/rpk/pkg/cli/cluster/quotas/quotas.go
src/go/rpk/pkg/out/in.go
tests/rptest/clients/rpk.py
tests/rptest/tests/quota_management_test.py
tests/rptest/tests/rpk_cluster_quota_test.py

This PR introduces a new command: `rpk cluster quotas import`
`import` uses a string source that should be formatted as the output of `rpk cluster quotas describe --format <json/yaml>`. It accepts either the string, or a file containing the json (or yaml) representation of the import source:
```
$ rpk cluster quotas import --from {quotas:[...]}
$ rpk cluster quotas import --from /path/to/file
```
The command issues an alterQuotas request, deleting the old quotas, hence, a confirmation prompt is needed:
```
$ rpk cluster quotas import --from /tmp/foo.json
ENTITY                 QUOTA-TYPE          OLD-VALUE  NEW-VALUE
client-id=<default>    consumer_byte_rate  3333       -
client-id-prefix=bar-  consumer_byte_rate  32333123   23123123
? Confirm client quotas import above? Yes
Successfully …
```

rpk: add `rpk cluster quotas import`

---

src/v/utils/BUILD
src/v/utils/tests/BUILD
src/v/utils/tests/directory_walker_test.cc
tools/docker/bazel.dockerfile

* Adds some v::utils bits to Bazel
* Adds a dockerfile for buildkite CI
* none

bazel: add additional utils libraries

---

tests/rptest/services/kgo_verifier_services.py
tests/rptest/tests/random_node_operations_test.py

When set to tolerate data loss, we should ignore idempotency bugs, as they may happen because data recently produced has been lost.
Fixes https://github.com/redpanda-data/redpanda/issues/18272, which seems to be a combination of node failure injections, node decommissions and write caching. The latter was introduced in April 2024.
* none

test/random_node_operations: tolerate lost produces

---

tests/rptest/tests/cloud_storage_chunk_read_path_test.py

DeleteRandomChunks worker must refresh knowledge about current leader otherwise it might act on an unrelated node, report that it was unable to delete any chunks, and fail the test.
Spotted in a backport build https://buildkite.com/redpanda/redpanda/builds/51354#0190a1a8-8687-4687-b3c6-e0ac3c9f55cc
* none

rptest: tolerate leadership changes in chunk read tests

---

src/v/cluster/log_eviction_stm.cc
src/v/cluster/log_eviction_stm.h
src/v/cluster/partition.cc
src/v/cluster/partition.h
src/v/kafka/server/replicated_partition.cc
src/v/raft/persisted_stm.cc

In the common fetch path where Redpanda is reading batches from the batch cache `validate_fetch_offset` can consume ~33%(or 3.8% of overall reactor utilization) of the total time spent reading from a given NTP as seen in;
After applying the changes in this PR this is reduced to ~9%(0.9% of overall reactor utilization);
* none

Optimize `replicated_partition::validate_fetch_offset`

---

tests/rptest/tests/rpk_registry_test.py

This ducktape tests validates that we can produce/consume with schema registry using json schemas. Also checks that rpk properly validates the record and fail when the validation fails.
* none

tests: add rpk produce/consume test with jsonschema

---

tests/rptest/remote_scripts/stream_verifier_txn.py

PR implements StreamVerifier as a remote python app that can be run from cli either as a message generator right away, or used as a RESTful web server to sent produce/consume commands and get current status
Examples.
Cli:
```
python3 stream_verifier_txn.py --brokers localhost:19092 --debug --topic-prefix topic-stream-verifier-tx --topic-count 16 produce --rps 0 --total 64
python3 stream_verifier_txn.py --brokers localhost:19092 --debug --topic-prefix topic-stream-verifier-tx --topic-count 16 consume
python3 stream_verifier_txn.py --brokers localhost:19092 webservice --port 8090
```
Webservice:
```
curl -s -X GET http://localhost:8090
curl -X POST http://localhost:8090 -d "{\"topic_count\": 256, \"msg_rate\": 0, \"msg_total\": 5000, \"worker_threads\": 6}"
curl -s -X GET …
```

PESDLC-1488 Implement StreamsVerifierTx

---

src/transform-sdk/js/README.md
src/transform-sdk/js/js_vm.cc

This PR adds a `Process` class and injects an instance into the global namespace as `globalThis.process`. Currently we implement a top-level `env` object that reflects the contents of `environ` at init time, but in principle this could take on [other process stuff](https://nodejs.org/api/process.html).
* none

Transforms JS SDK: plumb `environ` down into `process.env`

---

src/v/storage/compaction_reducers.cc
src/v/storage/compaction_reducers.h
src/v/storage/segment_deduplication_utils.cc
src/v/storage/segment_utils.cc

We've seen that during compaction, the step that reads a segment and deduplicates each record can take a long time. During this span, we do not check the compaction abort source, and this can result in compactions blocking partition shutdown.
This commit plumbs the compaction abort source into the copy reducer and uses it for both self compaction and windowed compaction.
Fixes https://github.com/redpanda-data/redpanda/issues/13451
* Speeds up the shutdown time of partition replicas when compactions are happening.

storage: plumb abort source to compaction copy reducer

---

src/v/utils/tests/delta_for_test.cc
src/v/utils/tests/input_stream_fanout_test.cc
src/v/utils/tests/token_bucket_test.cc
src/v/utils/timed_mutex.h

* Signed comparison warning fixes
* Remove dependency on redpanda_version
* none

test: misc cleanups

---

tests/rptest/transactions/tx_atomic_produce_consume_test.py
tests/rptest/utils/node_operations.py

Added failure injection in order to test the exactly once delivery scenario in face of Redpanda crashes and suspends
- none

Added failure injection to atomic consume transform produce test

---

src/v/raft/tests/basic_raft_fixture_test.cc
src/v/utils/to_string.h

I came across this problem when testing a modification in `vote_stm`. It would fail intermittently, but never with much of a gap.
I gathered some stats and came to a conclusion that we should allow for a little glitch:
```
Modified:
4 leadership_transfer 43ms
40 leadership_transfer 44ms
110 leadership_transfer 45ms
238 leadership_transfer 46ms
336 leadership_transfer 47ms
67 leadership_transfer 48ms
9 leadership_transfer 49ms
3 leadership_transfer 50ms
2 leadership_transfer 51ms
*     1 leadership_transfer 57ms
*     1 leadership_transfer 58ms
*     2 leadership_transfer 60ms
*     1 leadership_transfer 61ms
1 reconfiguration 42ms
11 reconfiguration 45ms
44 reconfiguration 46ms
205 reconfiguration 47ms
299 reconfiguration 48ms
150 reconfiguration 49ms
86 reconfiguration 50ms
9 …
```

Leadership transfer delay test fix

---

tests/rptest/tests/write_caching_fi_test.py

Sometimes redpanda needs a bit more time to start.
* none

rptest: wait for leader after restart

---

tests/rptest/tests/cloud_storage_chunk_read_path_test.py

Because chunk readers keep open the handle to a chunk file even if the file itself is deleted, during the test_read_chunks it is possible that the sequential consumer is entirely served by these open file handles while all chunk files in the directory have been removed. This results in the assertion that some chunks must have been removed during sequential consumer to fail.
As the count of chunks deleted is not important as an assertion and the purpose of deleting chunks randomly was to exercise failed materialization code path which should happen during the random consumer run, the assertion is changed to only test once for both seq and random consumers.
Another alternative would be a more fine grained check, eg assert if some chunks are removed only if some files are written to the …

cst/ducktape: Change assertion for deleted chunks

---

src/v/cluster/scheduling/leader_balancer.cc
tests/rptest/tests/maintenance_test.py

Please see commit descriptions for explanations.
Fixes https://github.com/redpanda-data/redpanda/issues/20592
Fixes https://github.com/redpanda-data/redpanda/issues/20297
Fixes https://github.com/redpanda-data/redpanda/issues/19928
Fixes https://github.com/redpanda-data/redpanda/issues/19926
Fixes https://github.com/redpanda-data/redpanda/issues/13650
* none

Maintenance mode test fixes

---

src/v/kafka/server/group_data_parser.h

Raft configuration batches are integral part of Raft managed log. Emitting warn log message that Redpanda ignore them when parsing consumer group state machine data may be confusing as this is expected and not something that the users should worry about.
- none

k/group: do not log ignoring raft configuration batches

---

src/v/cloud_storage/materialized_resources.cc
tests/rptest/tests/e2e_shadow_indexing_test.py

rptest: actual e2e throttling test

---

src/v/cluster/scheduling/leader_balancer.cc
tests/rptest/tests/maintenance_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/21435
Fixes: https://github.com/redpanda-data/redpanda/issues/21456, Fixes: https://github.com/redpanda-data/redpanda/issues/21458, Fixes: https://github.com/redpanda-data/redpanda/issues/21460, Fixes: https://github.com/redpanda-data/redpanda/issues/21462, Fixes: https://github.com/redpanda-data/redpanda/issues/21463,

[v23.3.x] Maintenance mode test fixes

---

tests/rptest/services/admin.py
tests/rptest/tests/controller_snapshot_test.py

Sometimes new controller leader won't be elected until a few seconds after a controller restart. This can confuse subsequent leadership transfers that will try to move controller leadership to the old controller and falsely think that it will be a no-op. Wait for the new leader after the joiner node is restarted to fix that.
Fixes https://github.com/redpanda-data/redpanda/issues/20572
* none

tests/controller_snapshot: fix no-op controller leadership transfers

---

src/v/base/include/base/outcome.h
src/v/cluster/id_allocator_frontend.cc
src/v/cluster/id_allocator_stm.cc
src/v/cluster/id_allocator_stm.h
src/v/cluster/tests/CMakeLists.txt
src/v/cluster/tests/id_allocator_stm_test.cc
src/v/raft/consensus.cc
src/v/raft/tests/basic_raft_fixture_test.cc
src/v/raft/tests/raft_fixture.h
src/v/test_utils/test.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/19964

[v24.1.x] Always use the latest configuration for followers metadata

---

src/v/crypto/tests/crypto_bench.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/21326
Fixes https://github.com/redpanda-data/redpanda/issues/21470

[v24.1.x] [CORE-5672] crypto/bench: Only load context once per run

---

src/v/pandaproxy/schema_registry/validation.cc

The log was used for debugging during https://github.com/redpanda-data/redpanda/pull/21323 and should not have been pushed.
I removed it from the [backport to v23.3](https://github.com/redpanda-data/redpanda/pull/21469)
* none

schema_registry: Remove extraneous log

---

src/transform-sdk/cpp/examples/CMakeLists.txt
src/transform-sdk/cpp/examples/schema_registry.cc
src/transform-sdk/cpp/include/redpanda/transform_sdk.h
src/transform-sdk/cpp/src/transform_sdk.cc

Primarily in service of extending Schema Registry support to the JavaScript SDK, this commit implements the full SR ABI v0 in the C++ SDK.
TODO (exclusive of mundane cleanup):
* Add schema registry support to experimental Data Transforms C++ SDK

[CORE-5092] Transform SDK: Schema Registry client in C++

---

tests/rptest/services/admin.py
tests/rptest/tests/controller_snapshot_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/21428
Fixes: https://github.com/redpanda-data/redpanda/issues/21476,

[v24.1.x] tests/controller_snapshot: fix no-op controller leadership transfers

---

src/go/rpk/pkg/cli/cluster/quotas/alter.go

--default flag should not have a name
* none

rpk: fix --default example in alter quotas command

---

src/v/iceberg/avroschemas/manifest_entry.schema.json

Adds the file_sequence_number to the manifest_entry schema, as indicated by the spec[1].
It's unclear why the schema didn't have them in the first place (the schema was taken from DuckDB), but it's clearly defined upstream[2] and is important for efficiently writing metadata[3].
There is another field, distinct_counts, in the spec that is not in the manifest_entry schema. Interestingly enough, it doesn't appear to be defined at all in upstream Java code[4] (it is defined in iceberg-go, but not iceberg-python or iceberg-rust), so I'm leaving it out.
[1] https://iceberg.apache.org/spec/#manifests
[2] https://github.com/apache/iceberg/blob/319f29ea860e42e7cc21cda8c05d882134e6431f/core/src/main/java/org/apache/iceberg/ManifestEntry.java#L48-L49
[3] …

iceberg: add missing field to manifest_entry avro

---

src/go/rpk/pkg/cli/transform/build.go
src/go/rpk/pkg/cli/transform/buildpack/buildpack.go
src/transform-sdk/js/package_toolchain.py

Mac builds dynamically link the executable instead of static linking on
linux. Make sure the mac builds include the required dylib (in the right
directories too so rpath fiddling is not needed).
I packaged a new toolchain using `package_toolchain.py`, uploaded that
to the tinygo repo (still need a better place to upload that stuff), and
fixed the paths now that they changed in the tarball.
Fixes: CORE-5594
* Fix transform JavaScript SDK tools on Darwin

rpk/transform/build: fix js sdk tooling

---

tests/rptest/tests/cloud_storage_chunk_read_path_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/21427
Fixes: https://github.com/redpanda-data/redpanda/issues/21433,

[v24.1.x] cst/ducktape: Change assertion for deleted chunks

---

src/v/storage/compaction_reducers.cc
src/v/storage/compaction_reducers.h
src/v/storage/segment_deduplication_utils.cc
src/v/storage/segment_utils.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/21366
Fixes: https://github.com/redpanda-data/redpanda/issues/21421,

[v24.1.x] storage: plumb abort source to compaction copy reducer

---

src/v/cluster/controller.cc
src/v/cluster/data_migration_backend.cc
src/v/cluster/data_migration_backend.h
src/v/cluster/data_migration_types.h
src/v/cluster/data_migration_worker.cc
src/v/cluster/data_migration_worker.h

Backend to gather from migration definition and to provide to worker information necessary to perform per-partition work.
Worker to spawn, retry and gather results from partition operations.
* none

Migrations infra, part 3: shard-local worker logic

---

src/v/cloud_roles/refresh_credentials.cc
src/v/cloud_storage_clients/configuration.cc
src/v/cluster/metrics_reporter.cc
src/v/config/configuration.cc
src/v/config/configuration.h
src/v/config/convert.h
src/v/config/property.h
src/v/config/rjson_serialization.cc
src/v/config/rjson_serialization.h
src/v/config/tls_config.cc
src/v/config/tls_config.h
src/v/config/types.h
src/v/security/oidc_service.cc
tests/rptest/tests/cluster_config_test.py
tests/rptest/tests/tls_version_test.py

* Adds new cluster config `tls_min_version` that allows users of Redpanda to specify the minimum version of TLS Redpanda will support.  By default, the value is TLS v1.2.

CORE-5589 Add config to select minimum TLS version

---

src/go/rpk/pkg/cli/group/group.go
src/v/kafka/protocol/schemata/generator.py
src/v/kafka/protocol/schemata/list_groups_request.json
src/v/kafka/protocol/schemata/list_groups_response.json
src/v/kafka/server/group.cc
src/v/kafka/server/group.h
src/v/kafka/server/group_manager.cc
src/v/kafka/server/group_manager.h
src/v/kafka/server/group_router.cc
src/v/kafka/server/group_router.h
src/v/kafka/server/handlers/list_groups.h
src/v/kafka/server/server.cc
tests/rptest/clients/rpk.py
tests/rptest/tests/consumer_group_recovery_test.py
tests/rptest/tests/consumer_group_recovery_tool_test.py
tests/rptest/tests/consumer_group_test.py
tests/rptest/tests/consumer_offsets_consistency_test.py
tests/rptest/tests/mirror_maker_test.py
tests/rptest/tests/recovery_mode_test.py
tests/rptest/tests/rpk_group_test.py

This adds support for [KIP-518](https://cwiki.apache.org/confluence/display/KAFKA/KIP-518%3A+Allow+listing+consumer+groups+per+state) in the ListGroups handler, that is:
* Filtering consumer groups returned by ListGroups based on a list of group states in the request.
* Returning the group state of each group in the response
Fixes: https://redpandadata.atlassian.net/browse/CORE-781
Same as: https://github.com/redpanda-data/redpanda/issues/2903
* KIP-518 (ListGroups v4): adds redpanda and rpk support for printing consumer group states with `rpk group list` and filtering for specific group states with `--states`.

CORE-781 k/groups: list groups v4 (group state filtering)

---

src/go/rpk/pkg/cli/cluster/selftest/start.go
src/go/rpk/pkg/cli/cluster/selftest/status.go

Updated with changes made in docs here:
https://github.com/redpanda-data/docs/pull/599
* none

rpk/cluster: update `rpk self-test` docs

---

src/go/rpk/pkg/cli/security/user/update.go
tests/rptest/clients/rpk.py
tests/rptest/tests/rpk_acl_test.py

Without this, a user could inadvertently change the mechanism because we default the flag to
SCRAM-SHA-256.
* rpk: --mechanism flag is now required to update users when using `rpk security user update`.

rpk: make mechanism flag required in user update

---

src/v/cloud_storage/access_time_tracker.cc
src/v/cloud_storage/access_time_tracker.h
src/v/cloud_storage/cache_probe.cc
src/v/cloud_storage/cache_probe.h
src/v/cloud_storage/cache_service.cc
src/v/cloud_storage/cache_service.h
src/v/cloud_storage/recursive_directory_walker.cc
src/v/cloud_storage/recursive_directory_walker.h
src/v/cloud_storage/tests/cache_bench.cc
src/v/cloud_storage/tests/cache_test.cc
src/v/cloud_storage/tests/cache_test_fixture.h
tests/rptest/scale_tests/tiered_storage_cache_stress_test.py
tests/rptest/tests/cloud_storage_chunk_read_path_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18786
Fixes: https://github.com/redpanda-data/redpanda/issues/21501,

[v24.1.x] cst/cache: tracker based trim

---

tests/rptest/services/kgo_verifier_services.py
tests/rptest/tests/random_node_operations_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/21305
Fixes: https://github.com/redpanda-data/redpanda/issues/21373,

[v24.1.x] test/random_node_operations: tolerate lost produces

---

tests/rptest/services/metrics_check.py
tests/rptest/tests/raft_availability_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/20813
Fixes: https://github.com/redpanda-data/redpanda/issues/20836,

[v24.1.x] tests: wait for the leadership change metric to be updated

---

src/v/pandaproxy/error.cc
src/v/pandaproxy/error.h
src/v/pandaproxy/schema_registry/error.cc
src/v/pandaproxy/schema_registry/error.h
src/v/pandaproxy/schema_registry/errors.h
src/v/pandaproxy/schema_registry/store.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/21256

[v24.1.x] pandaproxy: fix spelling of `operation`

---

tests/rptest/tests/transactions_test.py
tests/rptest/tests/tx_coordinator_migration_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/20743
Fixes: https://github.com/redpanda-data/redpanda/issues/20746,

[v24.1.x] Do not set transaction timeout in tests that do not need it

---

src/v/cloud_storage/inventory/inv_consumer.cc
src/v/cloud_storage/inventory/inv_consumer.h
src/v/cloud_storage/inventory/ntp_hashes.cc
src/v/cloud_storage/inventory/tests/inv_consumer_tests.cc
src/v/cloud_storage/inventory/tests/report_parser_tests.cc
src/v/compression/tests/gzip_stream_decompression_tests.cc

Follow ups to review comments on https://github.com/redpanda-data/redpanda/pull/19887
* Adds comments
* Fixes test name order
* Other minor changes
* none

cst/inv: report parser follow ups

---

src/v/archival/archival_metadata_stm.cc
src/v/archival/tests/archival_metadata_stm_gtest.cc

Closes #21315, #20780, #20780, #18254 and many more with bad log lines like the following.
Potentially also covers #18753
> New replacement segment has the same size as replaced segment
* none

archival: keep locks until outcome is known

---

src/v/archival/tests/service_fixture.cc
src/v/cluster/controller_backend.cc
src/v/cluster/controller_backend.h
src/v/cluster/partition.cc
src/v/cluster/partition.h
src/v/cluster/partition_manager.cc
src/v/cluster/partition_manager.h
src/v/cluster/raft0_utils.h
src/v/cluster/shard_placement_table.cc
src/v/raft/consensus.cc
src/v/raft/consensus.h
src/v/raft/group_manager.cc
src/v/raft/group_manager.h
src/v/raft/tests/raft_group_fixture.h
src/v/raft/types.h
tests/rptest/scale_tests/shard_placement_scale_test.py
tests/rptest/services/templates/omb_workload.yaml

When we move a partition that was a leader to another core, it will cease to be a leader and we will have to wait for the full re-election timeout before the leader is elected again. Instead, we can use the fact that it was the leader to start re-election immediately upon startup on the new core.
Note that we could continue with the same term instead (without re-election), but this looks a bit dangerous as downstream users (such as STMs) could be unprepared for the leader in the same term to reappear on another core.
Also add scale tests that allow observing latencies associated with x-core movements in the presence of substantial client load (openmessaging benchmark).
* none

Node-local core assignment: fast leader re-election

---

src/go/rpk/pkg/cli/cluster/selftest/start.go
src/v/cluster/self_test/diskcheck.cc
src/v/cluster/self_test_rpc_types.h
tests/rptest/tests/self_test_test.py

rpk: add additional disk self tests
Add 16K block size disk tests, a common block size written by Redpanda,
at varying IO depths: 1, 8 and 32 times the shard count (the
multiplication by the shard count happens in Redpanda and is
inevitable).
This will help better assess the performance of block storage which is
a bit outside the usual, in particular how it response to io depth
changes.
Additionally, add a 4K test which is the same as the existing one but
with dsync off. This is critical to assess the impact of fdatasync
on the storage layer: locally, _for me_ on my consumer SSD this makes a
257x difference (!!) in throughput though the effect is much more muted,
perhaps close to zero on other SSD types.
On the redpanda side, when we complete a self test the API returns
info about the …

self-test disk test enhancements

---

src/v/cluster/self_test_rpc_types.h

Effectively turning the original change into an append and obviating the need for a compat version bump.
It's not immediately clear why the struct was laid out this way in the first place. A reasonable guess is some balance of:
- The original ordering makes good sense for the aggregate in-memory
- It's an rpc format and not intended for on-disk persistence
Still, the compat version change means that if a self test goes off during an upgrade across the compat boundary, that rpc will fail. Adjusting the layout via envelope::serde_fields means that we can maintain the nice field order semantics in the aggregate while ensuring that the diff looks like a field append from serde's view.
* none

c/st: self_test_result rpc: move {start,end}_time to end of layout

---

.github/pull_request_template.md

Add v24.2.x and remove v23.2.x from PR template for backports
* None

Add v24.2.x and remove v23.2.x from PR template for backports

---

src/v/archival/archival_metadata_stm.cc
src/v/archival/tests/archival_metadata_stm_gtest.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/21348
Fixes: https://github.com/redpanda-data/redpanda/issues/21520,

[v24.1.x] archival: keep locks until outcome is known

---

src/v/cluster/partition.cc
tests/rptest/tests/timequery_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/21312

[v23.3.x] kafka: fix timequery when local log is empty

---

src/v/pandaproxy/error.cc
src/v/pandaproxy/error.h
src/v/pandaproxy/schema_registry/error.cc
src/v/pandaproxy/schema_registry/error.h
src/v/pandaproxy/schema_registry/errors.h
src/v/pandaproxy/schema_registry/store.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/21256

[v23.3.x] pandaproxy: fix spelling of `operation`

---

tests/rptest/clients/offline_log_viewer.py
tests/rptest/tests/transactions_test.py
tools/offline_log_viewer/kafka.py
tools/offline_log_viewer/viewer.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18246

[v23.3.x] offline_log_viewer: fix get_control_record_type

---

src/v/cluster/partition_manager.cc
src/v/raft/group_manager.cc
src/v/raft/group_manager.h

Individual raft groups shutdown operations are not correlated and do not
need coordination with mutex. The `group_manager::_groups` vector is
always updated in synchronous parts of code therefore it do not require
the mutex either.
Removed the mutex to make shutting down different Raft groups
independent from each other.
Fixes CORE-5686
- none

CORE-5686 Decouple different raft group shutdown sequences

---

src/v/cluster/tx_errc.cc
src/v/cluster/tx_errc.h
src/v/cluster/tx_gateway_frontend.cc
src/v/config/configuration.cc
src/v/config/configuration.h
src/v/kafka/server/errors.h
tests/java/verifiers/src/main/java/io/vectorized/tx_verifier/Verifier.java
tests/rptest/transactions/transactions_test.py
tests/rptest/transactions/tx_admin_api_test.py

Adds a new configuration `transaction_max_timeout_ms` defaulting to 15mins.
Producers with transaction timeout greater than this configuration are rejected.
Hanging transactions (from producers with unset transaction timeouts) can potentially
cause blocked consumer due to LSO being blocked, so enforcing this limit on how long
a transaction can hang before it is auto aborted prevents such situations.
Fixes https://github.com/redpanda-data/redpanda/issues/17984
* Adds a new broker configuration transaction_max_timeout_ms. The configuration controls the maximum allowed user set timeout for transactions. If a client requested transaction timeout exceeds this configuration, the broker will return
an error during transactional producer initialization. This guardrail prevents hanging …

tx: enforce limit on client set transaction timeout

---

src/v/cluster/producer_state.cc
src/v/cluster/producer_state.h
src/v/cluster/rm_stm.cc

A request can be marked as errored multiple times, consider the example
below.
```
replicate_f : waiting for replication
term change and leadership change
requests from old terms gc-ed: set_err(ec) -- separate fiber
replicate_f: set_err(ec)
```
Current assert assumes that a request can be set only once, which is
true for setting a successful result but not for errors. This commit
splits set_value() into set_value() and set_error() and adjusts
assert conditions accordingly.
This was identified in a chaos build. Also included some logging improvements noticed while debugging, most notably printing the transaction state correctly (currently printing the pointer instead of value).
Fixes https://github.com/redpanda-data/redpanda/issues/19842
* none

[v23.3.x] producer_state: add request::set_error and make it idempotent

---

src/v/cluster/producer_state.cc
src/v/cluster/producer_state.h
src/v/cluster/rm_stm.cc

A request can be marked as errored multiple times, consider the example
below.
```
replicate_f : waiting for replication
term change and leadership change
requests from old terms gc-ed: set_err(ec) -- separate fiber
replicate_f: set_err(ec)
```
Current assert assumes that a request can be set only once, which is
true for setting a successful result but not for errors. This commit
splits set_value() into set_value() and set_error() and adjusts
assert conditions accordingly.
This was identified in a chaos build. Also included some logging improvements noticed while debugging, most notably printing the transaction state correctly (currently printing the pointer instead of value).
Fixes: https://github.com/redpanda-data/redpanda/issues/19841
* none

 [v24.1.x] producer_state: add request::set_error and make it idempotent

---

src/v/raft/consensus.cc
src/v/raft/consensus.h
src/v/raft/vote_stm.cc
src/v/raft/vote_stm.h

At the moment nothing prevents a raft node from being a candidate in two elections at the same time, two `vote_stm`s actively working. This may lead to a nasty race condition where one of them has succeeded (becoming a leader, last heartbeat goes max), and then the other one fails (role becomes follower, no changes to last heartbeat). As a result, a node never becomes a candidate, as it's not a leader but has max last heartbeat.
This PR is mostly should guard against concurrent elections with the same candidate. Some minor fixes and refactorings included.
* none

Guard from concurrent elections

---

src/v/cloud_storage/tests/cache_test.cc
src/v/config/configuration.cc

The trim carryover feature remembers items to be trimmed to quickly free up space on trim without going to disk.
With access tracker based trim, carryover can remove files, the updates to the inner data structure of access tracker can be pending and the tracker can try to delete these files again. This can potentially result in error logs due to double-delete of files.
The carryover limit is set to 0 so that the list does not carry any items. A user can still set the list to some value and enable the feature, but this can result in error logs.
* none

cst/config: Disable trim carryover

---

src/v/cloud_storage/tests/cache_test.cc
src/v/config/configuration.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/21556

[v24.1.x] cst/config: Disable trim carryover

---

src/v/iceberg/BUILD
src/v/iceberg/CMakeLists.txt
src/v/iceberg/schema.h
src/v/iceberg/schema_json.cc
src/v/iceberg/schema_json.h
src/v/iceberg/tests/BUILD
src/v/iceberg/tests/CMakeLists.txt
src/v/iceberg/tests/datatypes_json_test.cc
src/v/iceberg/tests/schema_json_test.cc
src/v/iceberg/tests/test_schemas.cc
src/v/iceberg/tests/test_schemas.h

Adds a schema struct to represent the schema[1] that will be included in Iceberg manifests and table metadata. In the Iceberg spec, the schema is composed of a struct type, and a few other fields that get serialized as JSON[2].
Compared to other Iceberg implementations, this is fairly minimal, only including state that gets serialized explicitly as a part of the spec. My intent is that that as additional maps become needed (as is the case for other implementations), they are added in wrapper structs, leaving this struct as is, focused on just state that needs to be serialized.
A future PR will exercise serializing the schema's JSON as a part of manifest metadata.
Here are some reference implementations of a schemas in other languages:
- Rust: …

iceberg: add initial schema struct

---

src/v/cloud_storage/tests/cache_test.cc
src/v/config/configuration.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/21556

[v24.2.x] cst/config: Disable trim carryover

---

src/v/cluster/tx_gateway_frontend.cc

If transactional coordinator sync fails the returned result should be forwarded to the client. This way a client can correctly handle the error and retry a request if necessary. With the current code the `end_txn` outcome promise was not set when sync failed, leading to Redpanda returning an `unknown_server_error` to client.
- none

tx/gateway: set outcome result when sync in end_txn failed

---

tests/rptest/tests/crl_test.py

Added "certificate verify failed" to the list of allowed log entries in the RPC CRL test.
* None

dt: Updated RPC test log allow list

---

tests/rptest/tests/tiered_storage_model.py
tests/rptest/tests/tiered_storage_model_test.py

the `test_case` parametrization of `test_tiered_storage` test is of a custom type `TestCase`. that doesn't work when we need to run a specific parametrization of that test (eg `ducktape tests/rptest/tests/tiered_storage_model_test.py::TieredStorageTest.test_tiered_storage@{"test_case": {"name": "(TS_Read == True, SegmentRolledByTimeout == True)"}}`). So, ducktape can't retry a failed test_case of that test
This PR adds the ability to get the test_case object given a name to enable retries on that test
* none

tests/tiered_sotage: ability to get test case from name

---

src/v/cloud_storage/cache_service.cc
src/v/cloud_storage/tests/cache_test.cc

`clean_up_at_start` deletes files that are not in the access time tracker. While doing so it keeps a count of the total bytes deleted as well as the number of files deleted. Before this change, the number of files deleted was tracked incorrectly, causing the cache to start with incorrect values for `_current_cache_size` and `_current_cache_objects`.
* none

cloud storage: Fix deleted_count in clean_up_at_start

---

src/transform-sdk/js/CMakeLists.txt
src/transform-sdk/js/js_vm.cc
src/transform-sdk/js/js_vm.h
src/transform-sdk/js/main.cc
src/transform-sdk/js/sr-module/index.d.ts
src/transform-sdk/js/sr-module/index.js
src/transform-sdk/js/sr-module/package.json

This PR introduces `@redpanda-data/sr`, a C++-backed node module offering a client and various related types for accessing Redpanda Schema Registry from JavaScript or TypeScript transforms.
Includes TypeScript type descriptions, primarily for developer QoL (LSP support).
Also Closes CORE-5577
* Adds Schema Registry support for the JavaScript Data Transforms SDK

[CORE-5093] Data Transforms SDK: Schema Registry Support for JavaScript

---

src/v/cluster/tx_gateway_frontend.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/21559

[v24.2.x] tx/gateway: set outcome result when sync in end_txn failed

---

src/v/cluster/tx_gateway_frontend.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/21503

[v24.2.x] [CORE-5698] Fixed issue with error mapping in `add_partitions_to_txn`

---

tests/rptest/services/cluster.py
tests/rptest/services/failure_injector.py
tests/rptest/tests/e2e_finjector.py

Stop redpanda explicitly to fail if it times out. Ducktape swallows this.

tests/ducktape: check redpanda can stop

---

src/v/cluster/metrics_reporter.cc
src/v/cluster/metrics_reporter.h
src/v/http/client.cc
src/v/http/include/http/client.h

In case of exceptions, destroying the client may not be safe because the underlying output stream may not be fully flushed.
An alternative fix would be to ensure that `http::client` can always be destroyed if no method calls are in progress, but that seems complicated and other usage sites seem to follow the convention of always stopping it anyway.
Fixes https://github.com/redpanda-data/core-internal/issues/1323
Fixes https://github.com/redpanda-data/core-internal/issues/1325
* none

Fix http client segfault in `metrics_reporter`

---

src/v/cloud_storage/cache_service.cc

At the end of an in-memory trim if the size to delete is equal to or less than undeletable bytes the trim should finish, because further trimming will not result in extra space being freed up. The undeletable bytes are from the access tracker size. 
In particular where tracker is not yet saved to disk, the size to delete and undeletable bytes can both be zero and the existing `0 < 0` check fails, resulting in an expensive disk based walk being wasted as the subsequent trim runs with 0 size to delete.
* none

cst/cache: fix in mem trim termination condition

---

src/v/cloud_storage/read_path_probes.h
src/v/cluster/partition.cc

The probe has access to the global state so it's not safe to keep it after the partition is stopped and `remove_persistent_state` method is invoked. In cases when the partition is recreated with different revision id the 'double metric registration' error could be triggered.
When the exception is triggered the `partition_manager` is not able to remove the partition from the collection and subsequent re-creation of the partition with different ntp produces assertion because ntp already exists.
* none

[CORE-5632] cluster: Reset cloud storage metric in the `cluster::partition::remove_persistent_state`

---

src/v/cluster/metrics_reporter.cc
src/v/cluster/metrics_reporter.h
src/v/http/client.cc
src/v/http/include/http/client.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/21579

[v24.1.x] Fix http client segfault in `metrics_reporter`

---

src/v/cloud_storage/cache_service.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/21606

[v24.1.x] cst/cache: fix in mem trim termination condition

---

src/v/cluster/partition_manager.cc
src/v/raft/group_manager.cc
src/v/raft/group_manager.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/21517

[v24.2.x] CORE-5686 Decouple different raft group shutdown sequences

---

src/v/cluster/topics_frontend.cc
src/v/kafka/server/handlers/alter_configs.cc
src/v/kafka/server/handlers/incremental_alter_configs.cc
tests/rptest/tests/topic_creation_test.py

The AlterConfigs API differs from the IncrementalAlterConfigs API in that it is supposed to clear all configs not specified in the request. This was implemented incorrectly, so this PR fixes the behaviour by:
* Removing the topic-level config overrides for unspecified fields instead of setting them to their type's default value.
* Doing this for all topic configs, including the currently missing ones:
- `remote_delete`
- `segment_ms`
- `batch_max_bytes`
- `retention_local_target_ms`
- `retention_local_target_bytes`
- `initial_retention_local_target_ms`
- `initial_retention_local_target_bytes`
- `write_caching`
- `flush_ms`
- `flush_bytes`
Note that an exception is made for the shadow indexing topic configs `redpanda.remote.(read|write|delete)` to not reset them. These configs  are …

CORE-3091 Fix non-incremental AlterConfig resetting

---

cmake/dependencies.cmake
licenses/third_party.md
src/v/pandaproxy/schema_registry/CMakeLists.txt
src/v/pandaproxy/schema_registry/json.cc
src/v/pandaproxy/schema_registry/test/test_json_schema.cc

rapidjson does not support validating schemas above draft 5, so previously we have been rewriting newer schemas in draft 4's metaschema in order to validate them. This is error prone and gets increasingly complicated for later drafts.
Instead, here we implement validating schemas against their metaschemas using the jsoncons library which has support for drafts 4, 6, 7, 2019-09, 2020-12, which covers our expected use cases.
As part of this, we also extend support for the 2019-09 and 2020-12 drafts.
Fixes https://redpandadata.atlassian.net/browse/CORE-5088
Fixes https://redpandadata.atlassian.net/browse/CORE-5089
Depends on https://github.com/redpanda-data/vtools/pull/2963
* none

sr/json: support drafts 201909 and 202012 with jsoncons

---

tests/rptest/tests/scaling_up_test.py

In order to make the test stable increased a tolerance on the size of data on a node that joins the cluster. The slight increase doesn't influence the test correctness but makes it less vulnerable to small changes in size of partition metadata.
Fixes: #20224
- none

Increased tolerance in fast addition tests

---

cmake/dependencies.cmake
licenses/third_party.md
src/v/pandaproxy/schema_registry/CMakeLists.txt
src/v/pandaproxy/schema_registry/json.cc
src/v/pandaproxy/schema_registry/test/test_json_schema.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/21473

[v24.2.x] sr/json: support drafts 201909 and 202012 with jsoncons

---

src/transform-sdk/rust/Cargo.lock
src/transform-sdk/rust/Cargo.toml
src/transform-sdk/rust/examples/schema_registry/main.rs
src/transform-sdk/rust/sr-types/src/lib.rs
src/transform-sdk/rust/sr/Cargo.toml
src/transform-sdk/rust/sr/src/lib.rs

.
* Add an LRU caching layer to Rust transform SDK Schema Registry client

Transforms Rust SDK: Add caching layer to Schema Registry client (LRU)

---

src/go/rpk/go.mod
src/go/rpk/go.sum
src/go/rpk/pkg/cli/cluster/partitions/move.go
src/go/rpk/pkg/cli/cluster/partitions/move_test.go

Redpanda clusters are switching to node-local core assignments, which means that the API for dispatching cross-core partition moves will be different.
This is guarded behind the new feature: node_local_core_assignment. Those clusters with the feature enabled will issue the core movements independently from the node change.
If it's not enabled/present, we still do the old API calls.
Fixes #21562 
* none

rpk: support node-local core assignment API

---

src/v/cluster/metrics_reporter.cc
src/v/cluster/metrics_reporter.h
src/v/http/client.cc
src/v/http/client.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/21579

[v23.3.x] Fix http client segfault in `metrics_reporter`

---

src/go/rpk/pkg/cli/transform/buildpack/buildpack.go
src/transform-sdk/js/README.md
src/transform-sdk/js/package_toolchain.py

Use the latest WASI SDK and JS Runtime in JS Buildpack
* none

transform/js: package latest js runtime

---

tests/rptest/scale_tests/shard_placement_scale_test.py

Producer retries lead to increased load for two reasons:
1) they are additional requests
2) for some reason, new batches that are formed during the period of retries are smaller than usual and lead to "small batches problem"
This can lead to OMB failing to achieve desired throughput and therefore to test failure.
Another reason why they may lead to a test failure is this client bug: https://issues.apache.org/jira/browse/KAFKA-7848 - it looks like for very large linger.ms values, old batches can get stuck in the producer queue until after the idempotency window slides past them. These batches will be rejected by the broker, therefore the client will get stuck.
Fix both of these problems by limiting the number of concurrent requests per connection.
Fixes …

tests: minimize OMB producer retries in shard_placement_scale_test

---

src/v/pandaproxy/schema_registry/json.cc
src/v/pandaproxy/schema_registry/test/test_json_schema.cc

this PR implements a basic check:
If both schemas have a "$schema" member, it must be the same dialect.
Different dialects could be conditionally compatible, but this check is not implemented here
Fixes https://redpandadata.atlassian.net/browse/CORE-6464
* none

[CORE-6464] schema_registry/json: compatibility check for `$schema`

---

src/go/rpk/go.mod
src/go/rpk/go.sum
src/go/rpk/pkg/cli/cluster/partitions/move.go
src/go/rpk/pkg/cli/cluster/partitions/move_test.go

Backport of PR https://github.com/redpanda-data/redpanda/pull/21573
Fixes: https://github.com/redpanda-data/redpanda/issues/22336,

[v24.2.x] rpk: support node-local core assignment API

---

tests/rptest/tests/schema_registry_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22328

[v24.2.x] CORE-3189 dt/schema_registry: smoketests with python client

---

src/v/cloud_storage/remote.cc
src/v/cloud_storage_clients/abs_client.cc
src/v/cloud_storage_clients/abs_error.cc
src/v/cloud_storage_clients/abs_error.h
src/v/cloud_storage_clients/types.h

Previously, a `Delete Blob` request made on a directory in ABS would result in an `error_outcome` being returned, and propagated outwards due to the `OperationNotSupportedOnDirectory` response when HNS is not enabled.
This would be particularly noisy and harmful when `redpanda` is not configured for HNS in ABS, while the Azure account is, due to the use of `remote::delete_objects()` in various locations in the code.
Add the `error_outcome::operation_not_supported` value, and ignore this error when encountered within `abs_client::delete_object()`. We still make sure to issue a debug log to `abs_log`.
Tested manually on personal ABS account.
* none

cloud_storage: add `error_outcome::operation_not_supported`

---

src/v/cloud_storage_clients/tests/xml_sax_parser_test.cc
src/v/cloud_storage_clients/xml_sax_parser.cc

We ran into a case in which the `xml_sax_parser` would throw an exception when processing a ABS `List Blobs` response like the following:
```
<?xml version="1.0" encoding="utf-8"?>
<EnumerationResults ServiceEndpoint="https://blob.core.windows.net/" ContainerName="container">
<Prefix>cluster_metadata/bb7527f1-3227-4d55-86da-c133ec955ea9/manifests/
</Prefix>
<Delimiter>/</Delimiter>
<Blobs>
<BlobPrefix>
<Name>cluster_metadata/bb7527f1-3227-4d55-86da-c133ec955ea9/manifests/2/
</Name>
<Properties>
<Creation-Time>Thu, 25 Jul 2024 14:07:26 GMT
</Creation-Time>
</Properties>
</BlobPrefix>
</Blobs>
</EnumerationResults>
```
resulting in logged output:
```
redpanda-0  | ERROR 2024-07-19 13:51:29,995 [shard 0:main] abs - util.cc:108 - Unexpected error cloud_storage_clients::xml_parse_exception …
```

cloud_storage_clients: fix `abs_parse_impl` error

---

src/v/cluster/archival/purger.cc

Before, the `purger` would push back what it assumed was the spillover manifest file by default to its list of `collected_manifests`.
In the case of ABS, `_api.list_objects` might actually return the directory itself as a `Blob`. This would lead to the `purger` attempting to download the directory as if it were a manifest, which would always fail.
This would completely block the `purger` from progressing and deleting other partitions in the deleted topic, as it would retry the same doomed manifest download.
Correct the logic in `collect_manifest_paths()` by checking the path for `manifest.bin`, which should be contained within the spillover filename (e.g `.../5_21/manifest.bin.10.11.0.1.999.1000`).
* Fixes a bug in the `purger`, which when used with `ABS` may attempt to download a …

archival: fix `purger::collect_manifest_paths()`

---

src/v/kafka/server/handlers/client_quotas.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/22520

[v24.2.x] CORE-2074 k/quotas: fix alter configs acl requirement

---

src/v/config/configuration.cc
src/v/config/configuration.h
src/v/pandaproxy/api/api-doc/schema_registry.json
src/v/pandaproxy/parsing/from_chars.h
src/v/pandaproxy/schema_registry/avro.cc
src/v/pandaproxy/schema_registry/handlers.cc
src/v/pandaproxy/schema_registry/json.cc
src/v/pandaproxy/schema_registry/json.h
src/v/pandaproxy/schema_registry/sharded_store.cc
src/v/pandaproxy/schema_registry/sharded_store.h
src/v/pandaproxy/schema_registry/types.cc
src/v/pandaproxy/schema_registry/types.h
tests/rptest/tests/schema_registry_test.py

TODO: Add some more tests
* Schema Registry: Support `normalize=true`
* Schema Registry: Improve AVRO Normalization

[CORE-3181] Schema Registry: Normalization

---

src/v/pandaproxy/schema_registry/json.cc

Increase compatibility of compatibility checks for JSON by not being overly strict by rejecting keywords.
* none

Schema registry/json: Ignore some keywords

---

src/v/cloud_storage/read_path_probes.h
src/v/cluster/partition.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/21581

[v24.2.x] [CORE-5632] cluster: Reset cloud storage metric in the `cluster::partition::remove_persistent_state`

---

src/v/cloud_storage/remote.cc
src/v/cloud_storage_clients/abs_client.cc
src/v/cloud_storage_clients/abs_error.cc
src/v/cloud_storage_clients/abs_error.h
src/v/cloud_storage_clients/types.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/22339

[v24.1.x] cloud_storage: add `error_outcome::operation_not_supported`

---

src/v/cloud_storage/remote.cc
src/v/cloud_storage_clients/abs_client.cc
src/v/cloud_storage_clients/abs_error.cc
src/v/cloud_storage_clients/abs_error.h
src/v/cloud_storage_clients/types.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/22339

[v23.3.x] cloud_storage: add `error_outcome::operation_not_supported`

---

src/v/cloud_storage_clients/tests/xml_sax_parser_test.cc
src/v/cloud_storage_clients/xml_sax_parser.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/22331

[v24.2.x] cloud_storage_clients: fix `abs_parse_impl` error

---

src/v/archival/purger.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/22335

[v24.2.x] archival: fix `purger::collect_manifest_paths()`

---

src/v/cloud_storage/remote.cc
src/v/cloud_storage_clients/abs_client.cc
src/v/cloud_storage_clients/abs_error.cc
src/v/cloud_storage_clients/abs_error.h
src/v/cloud_storage_clients/types.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/22339

[v24.2.x] cloud_storage: add `error_outcome::operation_not_supported`

---

src/v/archival/purger.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/22335

[v24.1.x] archival: fix `purger::collect_manifest_paths()`

---

src/v/cloud_storage/inventory/aws_ops.cc
src/v/cloud_storage/remote.cc
src/v/cloud_storage/types.h
src/v/cloud_storage_clients/s3_client.cc
src/v/cloud_storage_clients/s3_error.cc
src/v/cloud_storage_clients/s3_error.h

A `NoSuchConfiguration` response code is returned by AWS S3 when an inventory configuration does not exist. It should be treated the same as a generic 404 response code because it indicates that the entity does not exist. 
The changes here ensure that when the presence of an inventory config is checked by the inventory service using `remote::download_object`, and a `NoSuchConfiguration` response is returned because the config does not yet exist, the code path correctly handles it like 404 and lets the inventory service ignore it rather than treating it as an error. 
This issue was seen during manual testing of the inventory config PUT api against a real S3 bucket.
* none

cst/clients: Add no such config response handling

---

src/v/cloud_storage/inventory/aws_ops.cc
src/v/cloud_storage/inventory/tests/fetch_report_tests.cc
src/v/cloud_storage/inventory/tests/inv_svc_tests.cc
src/v/cloud_storage/inventory/types.h

The aws ops methods assumed that if a prefix is supplied to listv2, the result contains common-prefixes which start after the prefix. The result actually contains the full path from the bucket root.
For example if prefix=foo/bar and there is a directory called 1 within foo/bar then the common-prefix in list-result is foo/bar/1/ and not 1/. This mistake is fixed in this change, and the associated tests are also fixed.
Note on backports: while aws ops is present in previous branches, it is not wired into the service which is not present, and one of the tests changed in this PR is inventory service test. So backporting this PR as it is would not work and is not required as the service is not wired up.
* none

cst/inv: Fix aws ops prefix handling

---

src/v/features/feature_table.h
tests/rptest/scale_tests/shard_placement_scale_test.py
tests/rptest/services/redpanda.py
tests/rptest/tests/partition_move_interruption_test.py
tests/rptest/tests/partition_movement.py
tests/rptest/tests/partition_movement_test.py
tests/rptest/tests/shard_placement_test.py
tests/rptest/tests/topic_delete_test.py

features: make node_local_core_assignment explicit-only

---

bazel/thirdparty/wasmtime.BUILD

bazel: allow wasmtime build to access network
* none

bazel: allow wasmtime build to access network

---

src/v/kafka/server/group.cc
src/v/kafka/server/group.h

When replication of transactional control batch fails group coordinator steps down and return an error to transaction coordinator. Fixed the incorrect mapping of replication errors which may lead to returning an `unknown_server_error` to client.
With the new mapping policy the error handling in consistent for all the replication batches. All the errors are translated to `not_coordinator_error`. The errors indicating uncertain outcome like shutting down and timeout are translated to timeout to let the client know that the outcome of operation must be verified.
- none

k/group: fixed mapping of transactional control batch replication errors

---

src/go/rpk/pkg/cli/debug/bundle/bundle_k8s_linux.go
src/go/rpk/pkg/cli/debug/bundle/bundle_linux.go

Fixes #22333 
* rpk debug bundle: include the result of `uname -a`

rpk: Add uname -a to debug bundle

---

bazel/build.bzl
src/v/hashing/BUILD
src/v/utils/BUILD

Adds some misc libraries. Unfortunately there are no tests in the trees for these, but they are dependencies to other code which will be added in subsequent PRs.
* none

bazel: add misc libraries

---

src/v/kafka/server/group.cc
src/v/kafka/server/group.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/22618

[v24.2.x] k/group: fixed mapping of transactional control batch replication errors

---

tests/rptest/scale_tests/shard_placement_scale_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/21615
Fixes: https://github.com/redpanda-data/redpanda/issues/22527,

[v24.2.x] tests: minimize OMB producer retries in shard_placement_scale_test

---

src/v/kafka/protocol/flex_versions.cc
src/v/kafka/protocol/types.h

kafka: minor fixes from pr feedback
* none

kafka: minor fixes

---

src/v/kafka/protocol/schemata/generator.py

Fixes stuff like this which show up with newer version of python like 3.12.
```
generator.py:1949: SyntaxWarning: invalid escape sequence '\/'
```
* none

kafka: use raw strings in kafka protocol generator

---

src/v/pandaproxy/api/api-doc/schema_registry.json
src/v/pandaproxy/api/api-doc/schema_registry_definitions.def.json

schema_registry: Fix Swagger for `POST /compatibility/subjects/{subject}/versions/{version}`
* Schema Registry: Fix Swagger for `POST /compatibility/subjects/{subject}/versions/{version}`

[CORE-3148] schema_registry: Fix Swagger for `POST /compatibility`

---

src/v/raft/consensus.cc
src/v/raft/consensus.h
src/v/raft/vote_stm.cc
src/v/raft/vote_stm.h

backport of https://github.com/redpanda-data/redpanda/pull/21361
the [first commit](https://github.com/redpanda-data/redpanda/pull/21361/commits/cafb4458f7fe29071ddc2d4e9ffa1a4224b6cfae) of the original PR is not relevant here (and actually explains where the removed dead code came from)
* none

Backport for "Merged Guard from concurrent elections" #21361 

---

src/v/pandaproxy/schema_registry/protobuf.cc
src/v/pandaproxy/schema_registry/test/compatibility_protobuf.cc
src/v/pandaproxy/schema_registry/test/compatibility_protobuf.h
src/v/redpanda/application.cc

Fixes https://github.com/redpanda-data/redpanda/issues/17682
There are a few (not necessarily orthogonal) options here:
* Set the sink to nullptr
* Set the log_level
* Make the log_level configurable
* Implement a new Sink.
I went with the simplest. Some of the options are not thread-safe.
* Schema Registry: Remove spurious log entry: `No syntax specified for the proto file`

[CORE-2144] schema_registry/protobuf: Disable protobuf logging

---

src/v/cluster/controller_backend.cc
src/v/cluster/shard_placement_table.cc
src/v/cluster/shard_placement_table.h
src/v/cluster/tests/shard_placement_table_test.cc

Add metrics tracking the number of partition replicas assigned to a shard, hosted on a shard, and the number of partitions needing reconciliation of shard-local state.
* none

Shard placement table: add metrics

---

src/v/config/configuration.cc
src/v/config/configuration.h
src/v/pandaproxy/api/api-doc/schema_registry.json
src/v/pandaproxy/parsing/from_chars.h
src/v/pandaproxy/schema_registry/avro.cc
src/v/pandaproxy/schema_registry/handlers.cc
src/v/pandaproxy/schema_registry/sharded_store.cc
src/v/pandaproxy/schema_registry/sharded_store.h
src/v/pandaproxy/schema_registry/types.cc
src/v/pandaproxy/schema_registry/types.h
tests/rptest/tests/schema_registry_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22519
Fixes https://github.com/redpanda-data/redpanda/issues/22603

[v24.1.x] [CORE-3181] Schema Registry: Normalization

---

src/go/rpk/pkg/cli/cluster/selftest/start.go

Updates `rpk` docs with updates made in https://github.com/redpanda-data/docs/pull/604.
Correct `bits` to `bytes`, update list of `cloudcheck` operations, and re-word phrasing around cloud-storage self-test from "benchmark" to "verification", as that is its currently intended purpose.
* none

rpk: update cloudcheck `self-test` docs

---

src/go/rpk/pkg/cli/cluster/selftest/start.go

Backport of PR https://github.com/redpanda-data/redpanda/pull/22656

[v24.2.x] rpk: update cloudcheck `self-test` docs

---

src/go/rpk/pkg/cli/cluster/selftest/start.go
src/v/cluster/self_test/cloudcheck.cc
src/v/cluster/self_test/cloudcheck.h
tests/rptest/tests/self_test_test.py

Previously, we would check the values of the cluster config properties `cloud_storage_enable_remote_read` and `cloud_storage_enable_remote_write` in order to determine which operations the cloud storage self-test should run.
These checks have proven to be a source of confusion and ultimately undesirable. Remove them, and only check `cloud_storage_enabled` before proceeding with all operations in the cloud storage self-test.
* none

`cluster`: remove cloud storage self-test checks

---

src/go/rpk/pkg/cli/cluster/selftest/start.go
src/v/cluster/self_test/cloudcheck.cc
src/v/cluster/self_test/cloudcheck.h
tests/rptest/tests/self_test_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22667

[v24.2.x] `cluster`: remove cloud storage self-test checks

---

src/v/cluster/members_manager.cc
src/v/cluster/members_table.cc
tests/rptest/services/redpanda.py
tests/rptest/tests/nodes_decommissioning_test.py

Added some improvements making it easier to track the cluster membership issues. Additionally,  added a test decommissioning each cluster node and then adding it back to the cluster, either with an overridden node id or with the new node id assigned by the controller. This test is similar to the chaos tests using `recycle_all` failure.
- none

Logging improvements in cluster `members` subsystem

---

src/v/cloud_storage/CMakeLists.txt
src/v/cloud_storage/base_manifest.cc
src/v/cloud_storage/base_manifest.h
src/v/cloud_storage/fwd.h
src/v/cloud_storage/remote.cc
src/v/cloud_storage/remote_path_provider.cc
src/v/cloud_storage/remote_path_provider.h
src/v/cloud_storage/remote_probe.h
src/v/cloud_storage/tests/CMakeLists.txt
src/v/cloud_storage/tests/remote_path_provider_test.cc
src/v/cloud_storage/tests/topic_mount_handler_test.cc
src/v/cloud_storage/tests/topic_mount_manifest_test.cc
src/v/cloud_storage/topic_mount_handler.cc
src/v/cloud_storage/topic_mount_handler.h
src/v/cloud_storage/topic_mount_manifest.cc
src/v/cloud_storage/topic_mount_manifest.h
src/v/model/fundamental.h
src/v/model/metadata.h
src/v/model/model.cc
src/v/utils/tests/uuid_test.cc

Backport of https://github.com/redpanda-data/redpanda/pull/21582
Fixes #22681
* none

[v24.2.x] `cloud_storage`: add `topic_mount_manifest` (manual backport)

---

src/v/cloud_storage/tests/topic_mount_handler_test.cc
src/v/cloud_storage/topic_mount_handler.cc
src/v/cloud_storage/topic_mount_handler.h

Fixes for minor feedback from PR https://github.com/redpanda-data/redpanda/pull/21582.
* none

`cloud_storage`: minor fixes in `topic_mount_handler`

---

tests/rptest/services/failure_injector.py
tests/rptest/tests/availability_test.py
tests/rptest/tests/e2e_finjector.py

Resuming on test teardown is too late, introducing context managers for failure injection to do repair earlier
* none

tests/availability: fix resuming of suspended nodes

---

src/go/rpk/go.mod
src/go/rpk/go.sum
src/go/rpk/pkg/cli/registry/mode/get.go
src/go/rpk/pkg/cli/registry/mode/mode.go
src/go/rpk/pkg/cli/registry/mode/reset.go
src/go/rpk/pkg/cli/registry/mode/set.go
src/go/rpk/pkg/cli/registry/registry.go
tests/rptest/clients/rpk.py
tests/rptest/tests/rpk_registry_test.py

This PR adds the new `rpk registry mode` command
Fixes https://github.com/redpanda-data/devex/issues/29
**Set a mode**
```
$ rpk registry mode set foo bar --mode READWRITE        
SUBJECT  MODE      ERROR
foo      READWRITE  
bar      READWRITE  
```
**Set the global mode**
```
$ rpk registry mode set --mode READONLY 
SUBJECT   MODE      ERROR
{GLOBAL}  READONLY  
```
**Get the mode of foo, bar, and the global mode**
```
$ rpk registry mode get foo bar --global
SUBJECT   MODE       ERROR
foo       READWRITE
bar       READWRITE  
{GLOBAL}  READONLY  
```
All new commands include support for the `--format` flag.
* rpk: Add `rpk registry mode` to manage the schema registry mode.

rpk: add `rpk registry mode` command

---

src/go/rpk/go.mod
src/go/rpk/go.sum
src/go/rpk/pkg/cli/cluster/config/get.go
src/v/config/config_store.h
src/v/redpanda/admin/api-doc/cluster_config.json
src/v/redpanda/admin/server.cc
tests/rptest/services/admin.py
tests/rptest/tests/cluster_config_test.py

Fixes https://github.com/redpanda-data/redpanda/issues/22666, depends on https://github.com/redpanda-data/common-go/pull/11
`rpk cluster config get` makes a request for a single property from the cluster. However, `redpanda` currently returns the cluster `configuration` in whole, and allows `rpk` to index the desired property.
This makes dealing with aliased property names tricky, as the `configuration` json contains only key-value information.
Since `rpk cluster config get` is only concerned with one parameter, we add the optional `key` query parameter, which will be used to handle the possibility of an aliased property name internally by `redpanda` and return only one key-value pair in the regular json object. 
The returned JSON will reference the alias's name, i.e a `GET` request to …

`admin`: add `key` param to `get_cluster_config` endpoint

---

src/v/cluster/self_test/cloudcheck.cc
src/v/cluster/self_test_backend.cc
src/v/cluster/self_test_backend.h
src/v/cluster/self_test_frontend.cc
src/v/cluster/self_test_rpc_types.h
src/v/redpanda/admin/server.cc
tests/rptest/tests/self_test_test.py

To help with compatibility for clusters with mixed versions of `redpanda`, the `throw` statement in `admin_server::self_test_start_handler` has been removed.
Previously, in a cluster with mixed versions including `24.1.x` and `24.2.x`, this `throw` would prevent the `self-test` from running, due to the addition of `cloudcheck` in `24.2.x`, resulting in a `Bad Request, 400` code.
```
unable to start self test: request POST http://127.0.0.1:9644/v1/debug/self_test/start failed: Bad Request, body: "{\"message\": \"Unknown self_test 'type', valid options are 'disk' or 'network'\", \"code\": 400}"
```
We now `push_back()` unknown test types to `self_test_request::unknown_checks`, and include the unknown test in `rpk cluster self-test status` with a generic error message:
```
NODE ID: 0 | …
```

admin: remove `throw` on unknown self test type in `admin_server`

---

src/v/cloud_storage/tests/topic_mount_handler_test.cc
src/v/cloud_storage/topic_mount_handler.cc
src/v/cloud_storage/topic_mount_handler.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/22676

[v24.2.x] `cloud_storage`: minor fixes in `topic_mount_handler`

---

src/v/cluster/self_test/cloudcheck.cc
src/v/cluster/self_test_backend.cc
src/v/cluster/self_test_backend.h
src/v/cluster/self_test_frontend.cc
src/v/cluster/self_test_rpc_types.h
src/v/redpanda/admin/server.cc
tests/rptest/tests/self_test_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/21370

[v24.2.x] admin: remove `throw` on unknown self test type in `admin_server`

---

src/v/pandaproxy/api/api-doc/schema_registry.json
src/v/pandaproxy/api/api-doc/schema_registry_definitions.def.json

Sync Swagger with docs: See https://github.com/redpanda-data/docs/pull/646
* none

schema_registry: Sync Swagger with docs

---

src/v/cloud_storage/remote.cc
src/v/cloud_storage/types.h
src/v/cloud_storage_clients/abs_client.cc
src/v/cloud_storage_clients/abs_client.h
src/v/cloud_storage_clients/client.h
src/v/cloud_storage_clients/s3_client.cc
src/v/cloud_storage_clients/s3_client.h
src/v/cloud_storage_clients/tests/s3_client_test.cc

The changes in this PR optionally make 204 an acceptable response on a PUT operation, which is sometimes returned by the PutBucketInventoryConfiguration AWS operation instead of 201.
Additionally some tests are added in the same area of code to cover a previously added mapping of NoSuchConfiguration to 404 which did not have test coverage (https://github.com/redpanda-data/redpanda/pull/22529)
* none

cst/clients: accept responses from inv api

---

tests/rptest/services/failure_injector.py
tests/rptest/tests/availability_test.py
tests/rptest/tests/e2e_finjector.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22619

[v24.1.x] tests/availability: fix resuming of suspended nodes

---

tests/rptest/clients/kubectl.py
tests/rptest/redpanda_cloud_tests/config_profile_verify_test.py
tests/rptest/redpanda_cloud_tests/high_throughput_test.py
tests/rptest/services/cloud_broker.py
tests/rptest/services/cloud_cluster_utils.py
tests/rptest/services/machinetype.py
tests/rptest/services/provider_clients/__init__.py
tests/rptest/services/provider_clients/azure_client.py
tests/rptest/services/provider_clients/rpcloud_client.py
tests/rptest/services/redpanda.py
tests/rptest/services/redpanda_cloud.py
tests/rptest/tests/services_self_test.py

Bug fixes to tests and test infrastructure for running CDT on Azure. (Note: Currently includes commit from #18827, which this PR continues and builds upon.)
* none
- replaces several instances of deprecated Cloud API usage with new Public API (because the old endpoints don't return Azure resources)
- successfully installs BYOC Azure agent
- allow override headers on POST requests for rpcloud_client
- workaround for /snap/bin not showing up in $PATH (making `az` CLI not show up as an available command)
- Azure support for config_profile_verify test

[rptest] Azure CDT bringup

---

src/v/cluster/self_test_backend.cc
src/v/cluster/self_test_backend.h
src/v/cluster/self_test_frontend.cc
src/v/cluster/self_test_rpc_types.h
src/v/redpanda/admin/server.cc
tests/rptest/tests/self_test_test.py

Manual backport of https://github.com/redpanda-data/redpanda/pull/21370. Fixes https://github.com/redpanda-data/redpanda/issues/22699.
Some cloudcheck related conflicts, due to it not existing in `v24.1.x`. 
We are still interested in having the other changes, namely `unknown_check` support, in this previous version of `redpanda` for compatibility.
* none

[v24.1.x] `admin`: remove throw on unknown self test type in `admin_server` (manual backport)

---

install-dependencies.sh
licenses/third_party.md
src/v/CMakeLists.txt
src/v/README.md
src/v/datalake/CMakeLists.txt
src/v/datalake/errors.h
src/v/datalake/logger.h
src/v/datalake/proto_to_arrow_interface.h
src/v/datalake/proto_to_arrow_scalar.cc
src/v/datalake/proto_to_arrow_scalar.h
src/v/datalake/proto_to_arrow_struct.cc
src/v/datalake/proto_to_arrow_struct.h
src/v/datalake/protobuf_to_arrow_converter.cc
src/v/datalake/protobuf_to_arrow_converter.h
src/v/datalake/tests/CMakeLists.txt
src/v/datalake/tests/proto_to_arrow_gtest.cc
src/v/datalake/tests/proto_to_arrow_test_utils.h

Splitting up https://github.com/redpanda-data/redpanda/pull/18313 into multiple PRs. This is a self-contained PR for the Protobuf to Arrow conversion code.
I have also made a slight refactoring: there was some duplicate code between the protobuf_to_arrow_converter and proto_to_arrow_struct classes. I eliminated this by making the converter contain an instance of protobut_to_arrow_struct

Protobuf to Arrow converter

---

src/v/cloud_storage/cache_service.cc
src/v/cloud_storage/tests/cache_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/21569

[v24.1.x] cloud storage: Fix deleted_count in clean_up_at_start

---

src/v/cluster/members_table.cc

Fixed typo in applying remove node command.
- none

c/members_table: fixed typo in applying remove node command

---

tools/offline_log_viewer/controller.py

OLV reported the following error when reading controller snapshot being generated by Redpanda v24.1.8. This commit addressed the `TypeError`. 
```
INFO:viewer:starting metadata viewer with options: Namespace(path='data', type='controller_snapshot', topic=None, verbose=False, dump=False, force=False)
File "/redpanda/src/dev-redpanda/tools/offline_log_viewer/viewer.py", line 235, in <module>
main()
File "/redpanda/src/dev-redpanda/tools/offline_log_viewer/viewer.py", line 215, in main
print_controller_snapshot(store, options.dump)
File "/redpanda/src/dev-redpanda/tools/offline_log_viewer/viewer.py", line 70, in print_controller_snapshot
SerializableGenerator(snap.to_dict().items()))
File "/redpanda/src/dev-redpanda/tools/offline_log_viewer/controller.py", …
```

tools/olv: fixed a bug in reading ntp

---

src/transform-sdk/rust/Cargo.lock
src/transform-sdk/rust/Cargo.toml
src/transform-sdk/rust/examples/jaq/Cargo.toml
src/transform-sdk/rust/examples/json2avro/Cargo.toml
src/transform-sdk/rust/examples/schema_registry/Cargo.toml
src/transform-sdk/rust/examples/schema_registry/main.rs

transform-sdk/rust: upgrade crates

---

.github/workflows/transform-sdk-build.yml

[v24.1.x] gha: pin rustc for transform SDK builds

---

src/go/.goreleaser.yaml
src/go/.goreleaser_rp_connect.yaml

24.1.x is not latest stable release anymore
* none

[v24.1.x] rpk: remove homebrew publishing

---

src/v/cloud_storage/tests/segment_chunk_test.cc
src/v/cloud_storage_clients/tests/s3_client_test.cc

Fix some clang-18 warnings
* none

tests: fix some unused parameter warnings in clang-18

---

src/v/cluster/producer_state.cc

In some racy situations it may happen that the request is already errored out. Consider the following sequence of actions.
replicate_f - succeeded but set_value() not called -- scheduling point --
term change -> sync() -> GC of inflight requests, request is marked timedout
now set_value() is called in the original fiber, this triggers an assert.
Relaxing the assert condition to make it idempotent. Subsequent client retry of the request will be marked success (once the change is applied in the stm and the request state is populated).
Unable to reproduce in a unit test mainly due to lack of an idempotent client in the unit test fixture.
* Fixes a rare race condition triggering an assert (crash) with idempotent producers.

[backport][24.1.x] producer/request_state: make set_value() idempotent

---

.github/workflows/transform-sdk-build.yml

gha/transform-sdk: pin and centralize language versions

---

src/v/kafka/server/handlers/fetch.cc
src/v/kafka/server/handlers/fetch.h
src/v/kafka/server/tests/CMakeLists.txt
src/v/kafka/server/tests/fetch_bench.cc

Results from running locally;
```
[brandonallard@fedora redpanda-4]$ sudo cset shield -c 1,2,13,14 -k on              
cset: --> activating shielding:                                                                                                                                                               
cset: moving 300 tasks from root into system cpuset...                                                                                                                                        
[==================================================]%                                                                                                                                         
cset: kthread shield activated, moving 133 tasks into system cpuset... …
```

Add fetch path micro-benchmark

---

src/v/cluster/BUILD
src/v/cluster/CMakeLists.txt
src/v/cluster/errc.h
src/v/cluster/errors.cc
src/v/cluster/producer_state.cc
src/v/cluster/producer_state.h
src/v/cluster/producer_state_manager.cc
src/v/cluster/producer_state_manager.h
src/v/cluster/rm_stm.cc
src/v/cluster/rm_stm.h
src/v/cluster/tests/idempotency_tests.cc
src/v/cluster/tests/producer_state_tests.cc
src/v/cluster/tests/rm_stm_test_fixture.h
src/v/cluster/tx_gateway_frontend.cc
src/v/redpanda/application.cc
tests/java/verifiers/pom.xml
tests/java/verifiers/src/main/java/idempotency/App.java
tests/rptest/transactions/idempotency_test.py
tests/rptest/transactions/transactions_test.py
tests/rptest/transactions/verifiers/idempotency_load_generator.py

Two main changes in this patch
* Broker can now handle epoch bumps for idempotent producers. A client can independently bump the producer epoch in certain situations (check kip-360 and related code) as idempotency only pertains to the single session. The broker code had issues handling epoch bumps which is fixed.
* For evicted producer state on the broker (eg: log prefix truncation, producer expiration etc), there are subtle differences among clients around how they handle the producer reset scenario. Java client, for example bumps the epoch on OOOSN and if there are no other requests in flight while librdkafka is pretty strict and only does it on UNKNOWN_PRODUCER_ID error code (which explicitly tells the client that the broker has no state for the producer and it should reset). Changed …

miscellaneous idempotency fixes

---

src/v/cluster/raft0_utils.h
src/v/security/audit/audit_log_manager.cc
tests/rptest/tests/controller_partition_invariants_test.py

Previously the controller log was created without the cleanup policy,
this make it vulnerable to change of cluster default cleanup policy.
When the cluster cleanup policy was set to compaction the controller log
was compacted which might lead to inconsistency in cluster metadata.
- none

Disable log cleanup policy for controller log

---

src/v/cluster/CMakeLists.txt
src/v/cluster/errc.h
src/v/cluster/errors.cc
src/v/cluster/producer_state.cc
src/v/cluster/producer_state.h
src/v/cluster/producer_state_manager.cc
src/v/cluster/producer_state_manager.h
src/v/cluster/rm_stm.cc
src/v/cluster/rm_stm.h
src/v/cluster/tests/idempotency_tests.cc
src/v/cluster/tests/producer_state_tests.cc
src/v/cluster/tests/rm_stm_test_fixture.h
src/v/cluster/tx_gateway_frontend.cc
src/v/redpanda/application.cc
tests/java/verifiers/pom.xml
tests/java/verifiers/src/main/java/idempotency/App.java
tests/rptest/transactions/idempotency_test.py
tests/rptest/transactions/transactions_test.py
tests/rptest/transactions/verifiers/idempotency_load_generator.py

Two main changes in this patch
* Broker can now handle epoch bumps for idempotent producers. A client can independently bump the producer epoch in certain situations (check kip-360 and related code) as idempotency only pertains to the single session. The broker code had issues handling epoch bumps which is fixed.
* For evicted producer state on the broker (eg: log prefix truncation, producer expiration etc), there are subtle differences among clients around how they handle the producer reset scenario. Java client, for example bumps the epoch on OOOSN and if there are no other requests in flight while librdkafka is pretty strict and only does it on UNKNOWN_PRODUCER_ID error code (which explicitly tells the client that the broker has no state for the producer and it should reset). Changed …

[backport] [v24.2.x] miscellaneous idempotency fixes #22687 

---

tests/rptest/services/metrics_check.py
tests/rptest/tests/raft_availability_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/20813

[CORE-5099] [v23.3.x] tests: wait for the leadership change metric to be updated

---

src/v/raft/state_machine_manager.cc

When a partition is created without the batch cache, the write may not be immediately visible for the reader. In this case the `raft::state_machine_manager` identifies it as an issue with the state machine not being able to make progress. Added a differentiation of the log level based on the cache configuration of the partition. For the partitions that uses the cache the `WARN` log level is kept to make it easy to recognize possibly stuck state machines.
- fixed spurious warning log entries that may be altering users

r/stm_manager: do not warn when some of the stms did not make progress

---

src/v/cluster/archival/tests/service_fixture.cc
src/v/cluster/bootstrap_backend.cc
src/v/cluster/controller.cc
src/v/cluster/controller_backend.cc
src/v/cluster/controller_backend.h
src/v/cluster/members_backend.cc
src/v/cluster/members_manager.cc
src/v/cluster/members_manager.h
src/v/cluster/members_table.cc
src/v/cluster/partition_manager.cc
src/v/cluster/partition_manager.h
src/v/cluster/raft0_utils.h
src/v/features/feature_table.cc
src/v/features/feature_table.h
src/v/raft/consensus_utils.cc
src/v/raft/consensus_utils.h
src/v/raft/fundamental.h
src/v/raft/group_configuration.h
src/v/raft/group_manager.cc
src/v/raft/group_manager.h
src/v/raft/tests/simple_raft_fixture.h
tests/rptest/utils/si_utils.py

At some time in the past we removed the broker properties from the Raft protocol configuration and change the cluster membership to be driven by controller commands. At this point it is safe to assume that the command based membership is always active. 
- none

Retire old membership updates based on Raft configuration

---

src/v/cloud_storage/tests/cloud_storage_e2e_test.cc
src/v/cluster/controller_api.cc
src/v/cluster/health_monitor_backend.cc
src/v/cluster/health_monitor_backend.h
src/v/cluster/health_monitor_frontend.cc
src/v/cluster/health_monitor_frontend.h
src/v/cluster/health_monitor_types.cc
src/v/cluster/health_monitor_types.h
src/v/cluster/partition_balancer_planner.cc
src/v/cluster/partition_leaders_table.cc
src/v/cluster/scheduling/leader_balancer.cc
src/v/cluster/service.cc
src/v/cluster/tests/health_bench.cc
src/v/cluster/tests/health_monitor_bench.cc
src/v/cluster/tests/health_monitor_test.cc
src/v/cluster/tests/partition_balancer_planner_fixture.h
src/v/cluster/tests/partition_balancer_planner_test.cc
src/v/cluster/tests/partition_balancer_simulator_test.cc
src/v/cluster/tests/randoms.h
src/v/cluster/tests/serialization_rt_test.cc
src/v/cluster/topics_frontend.cc
src/v/compat/cluster_json.h
src/v/compat/get_node_health_compat.h
src/v/compat/get_node_health_generator.h
src/v/redpanda/admin/server.cc
tests/rptest/services/admin.py
tests/rptest/tests/shard_placement_test.py

If node-local core assignment is enabled, return core assignments from health report in `/v1/cluster/partitions` admin API output. These will better reflect reality, instead of obsolete assignments queried from the topic table.
Additionally, do some `node_health_report` refactoring that enables more efficient querying of node health reports.
* Return core assignments from health report in `/v1/cluster/partitions` admin API output.

Use shards from health report in Admin API cluster partition results

---

src/v/raft/consensus.cc
src/v/raft/consensus.h
src/v/raft/tests/basic_raft_fixture_test.cc
src/v/raft/tests/raft_fixture.cc
src/v/raft/tests/raft_fixture.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/19966

[v24.1.x] Transfer leadership before stepping down after reconfiguration

---

src/v/raft/state_machine_manager.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/22752

[v24.2.x] r/stm_manager: do not warn when some of the stms did not make progress

---

src/v/cluster/partition_manager.cc
src/v/raft/group_manager.cc
src/v/raft/group_manager.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/21517

[v24.1.x] CORE-5686 Decouple different raft group shutdown sequences

---

src/v/config/configuration.cc

Since https://github.com/redpanda-data/redpanda/pull/17840/ we should be able to always infer the correct setting. Update the docs accordingly to avoid confusing users into thinking that they must set this setting if `cloud_storage_azure_shared_key` is not set.
* none

config: update docs for cloud_storage_azure_hierarchical_namespace_enabled

---

src/v/rpc/include/rpc/errc.h
tests/rptest/services/redpanda.py

We recently had the `RandomNodeOperationsTest` fail in CI because the following error-level log showed up in the redpanda node logs. After inspecting the test flow, I believe this error log line and the failure it represents is expected, and so this PR fixes the CI failure by suppressing the error log.
```
<BadLogLines nodes=ip-172-31-9-208(1) example="ERROR 2024-07-24 23:13:14,081 [shard 1:admi] admin_api_server - server.cc:655 - [_anonymous] exception intercepted - url: [http://ip-172-31-9-208:9644/v1/brokers/7/decommission] http_return_status[500] reason - seastar::httpd::server_error_exception (Unexpected error: rpc::errc::unknown(6))">
File "/opt/.ducktape-venv/lib/python3.10/site-packages/ducktape/tests/runner_client.py", line 184, in _do_run
data …
```

CORE-6479 dt/random_node_ops: suppress method_not_found log 

---

tests/rptest/tests/timequery_test.py

Disable time-based retention so that we can use synthetic timestamps that may fall outside of the default retention window.
CORE-4284
Closes #19978
* none

rptest: Disable time based retention in TimeQueryTest

---

src/v/pandaproxy/schema_registry/protobuf/CMakeLists.txt

The latest version of protobuf has some unused aliases, disable the
warning because we don't control the output of protoc.
* none

pp/sr/proto: disable unused alias warning

---

src/v/datalake/protobuf_to_arrow_converter.cc
src/v/datalake/protobuf_to_arrow_converter.h

See: #22777
This is needed so we can upgrade protobuf in vtools
* none

datalake: support newer protobuf versions

---

src/v/cloud_storage/read_path_probes.h
src/v/cluster/partition.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/21581

[v24.1.x] [CORE-5632] cluster: Reset cloud storage metric in the `cluster::partition::remove_persistent_state`

---

tests/rptest/tests/test_si_cache_space_leak.py

This test is too slow with default configuration making the test flaky. Instead of raising the timeouts I'm trying to reduce the cache eviction throttling which makes the test 3x faster.
The test became flaky after in-memory trim was introduced in https://github.com/redpanda-data/redpanda/pull/21556.
The main insight was provided by https://github.com/abhijat in a private exchange:
> I think it might be the extra throttling. With the carry over
> disabled, we always have to do a trim when reserving space, which
> results in a lot more throttling and sleep:
>
> ```
> $ grep -Ri "Cache trimming throttled" * | grep -c cache
> 139
> ```
>
> With the carryover list in place, about half of the calls to reserve
> space end up in an early return because the list provides enough room
> to clear up …

rptest: reduce cache eviction throttling for space leak test

---

src/v/net/include/net/server_probe.h
src/v/net/probes.cc
src/v/net/server.cc

Add connections_rejected_rate_limit which counts connections rejected
due to the rate limit, analogously to the existing metric which counts
rejected connections due to the hitting the open connection limit.
Some additional renaming & clarification of these two connection related limits.
* Added vectorized_kafka_rpc_connections_rejected_rate_limit metric which counts incoming Kafka connections rejected due to the connection rate limit (if set), analogously to the existing vectorized_kafka_rpc_connections_rejected metric which counts rejected connections due to the hitting the open connection limit.

Add rate-rejected connection metric

---

src/v/kafka/server/group.cc

If an ongoing transactions has no offsets to update we must skip creating offset store batch as it leads to replication of an empty batch and assertion.
- none

k/group: do not replicate empty offsets commit batch

---

src/v/raft/tests/basic_raft_fixture_test.cc
src/v/storage/segment.cc

We've seen at least one instance where empty batches are pushed to the log. Rather than bringing down the process, this updates a couple vasserts to throw instead (converted a couple that seemed related to data inputs, and left in a vassert that seems much more problematic related to being on the correct shard).
Fix for the codepath in offsets commit that caused the vassert to fire is here https://github.com/redpanda-data/redpanda/pull/22824
* Avoids a crash in Redpanda's layer that could be triggered by empty offset commits.

storage: convert some vasserts to exceptions

---

src/v/raft/tests/basic_raft_fixture_test.cc
src/v/storage/segment.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/22822

[v24.1.x] storage: convert some vasserts to exceptions

---

src/v/cluster/errc.h
src/v/cluster/errors.cc
src/v/cluster/health_monitor_backend.cc
src/v/cluster/health_monitor_types.cc
src/v/cluster/health_monitor_types.h
src/v/cluster/node_status_backend.cc
src/v/cluster/node_status_backend.h
src/v/cluster/service.cc
src/v/kafka/server/errors.h
tests/rptest/tests/node_folder_deletion_test.py

The health report is used to determine if a cluster node is online and
available. When a node id changes but the RPC endpoint does not change
the requester may incorrectly assume that the node with the previous
node_id but the same endpoint is still operational. Added validation of
the node that the request was sent to before collecting the health
report. This way a sender will have correct information about the node
availability as only the request targeted to the node with the correct
node id will be replied with success.
Fixes: CORE-5766
- fixes problem of a node being reported as alive after its node_id has changed

CORE-5766 Validate target node id when collecting health report

---

src/v/net/include/net/server_probe.h
src/v/net/probes.cc
src/v/net/server.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/22803

[v24.2.x] Add rate-rejected connection metric

---

src/v/cluster/errc.h
src/v/cluster/errors.cc
src/v/cluster/health_monitor_backend.cc
src/v/cluster/health_monitor_types.cc
src/v/cluster/health_monitor_types.h
src/v/cluster/node_status_backend.cc
src/v/cluster/node_status_backend.h
src/v/cluster/service.cc
src/v/kafka/server/errors.h
tests/rptest/tests/node_folder_deletion_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22811

[v24.2.x] CORE-5766 Validate target node id when collecting health report

---

src/v/raft/tests/basic_raft_fixture_test.cc
src/v/storage/segment.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/22822

[v24.2.x] storage: convert some vasserts to exceptions

---

src/v/pandaproxy/schema_registry/protobuf.cc
src/v/pandaproxy/schema_registry/test/compatibility_protobuf.cc

This implements 5 new compatibility checks for protobuf:
* ONEOF_FIELD_REMOVED
* MULTIPLE_FIELDS_MOVED_TO_ONEOF
* REQUIRED_FIELD_{ADDED,REMOVED}
* FIELD_NAMED_TYPE_CHANGED
* MESSAGE_REMOVED
This gap was discovered and initially implemented on @oleiman's draft PR (https://github.com/redpanda-data/redpanda/pull/18332) aiming to add support for verbose logging. This PR extracts the changes of adding these new compatibility checks to make the review easier. Some unit tests are also added.
Fixes https://redpandadata.atlassian.net/browse/CORE-6824
* Schema Registry: 5 new compatibility checks are added for protobuf (ONEOF_FIELD_REMOVED, MULTIPLE_FIELDS_MOVED_TO_ONEOF, REQUIRED_FIELD_{ADDED,REMOVED}, FIELD_NAMED_TYPE_CHANGED, MESSAGE_REMOVED)

CORE-6824 Schema Registry/Proto: add 5 missing checks

---

src/v/config/configuration.cc

We have the topic_partitions_reserve_shard0 property which makes the partition allocator have as if there are that many partitions allocated to shard0, beyond the amount actually allocated. The idea is to slightly bias the partition related work on shard 0 in order to account for extra duties it has to do.
This is by default set to 2. This change sets it to 0 instead. In general the default value of 2 does not do a good job of accounting for the bias: it will either be much too high or much too low in most cases. I.e., if every shard has 500 partitions, putting "only" 498 makes no difference, despite that shard 0 might be doing significantly more work in this case. On the other hand, if someone takes our "recommendation" of using 1 or 2 shards per partition for maximum tput, they might be …

partition-allocator: default shard 0 reserved partitions to 0

---

bazel/thirdparty/seastar.BUILD

These seastar options are referenced in public header files, so not
defining them could cause strange errors vs the seastar library and
external consumers of this header. Namely the debug one causes
`need_preempt` to differ from seastar internally and most of those
checks.
* none

bazel: Globally set some seastar options

---

CMakeLists.txt
tools/cmake_test.py

Needs to be merged after `main` is made the default branch in vtools, so that builds work with the new trunk-based development model in vtools.
* none

cmake: tweaks for vtools trunk-based development

---

CMakeLists.txt
tools/cmake_test.py

Needs to be merged after `main` is made the default branch in vtools so that builds against the 23.3.x branch work with the new trunk-based development model in vtools.
Manual backport of https://github.com/redpanda-data/redpanda/pull/19853. Done manually to have it ready to be merged right after the switch of vtools default branch
* none

[v23.3.x] cmake: tweaks for vtools trunk-based development

---

CMakeLists.txt
tools/cmake_test.py

Needs to be merged after `main` is made the default branch in vtools so that builds against the 24.1.x branch work with the new trunk-based development model in vtools.
Manual backport of https://github.com/redpanda-data/redpanda/pull/19853. Done manually to have it ready to be merged right after the switch of vtools default branch
* none

[v24.1.x] cmake: tweaks for vtools trunk-based development

---

CMakeLists.txt
tools/cmake_test.py

Needs to be merged after `main` is made the default branch in vtools so that builds against the 24.2.x branch work with the new trunk-based development model in vtools.
Manual backport of https://github.com/redpanda-data/redpanda/pull/19853. Done manually to have it ready to be merged right after the switch of vtools default branch
* none

[v24.2.x] cmake: tweaks for vtools trunk-based development

---

src/v/pandaproxy/schema_registry/protobuf.cc
src/v/pandaproxy/schema_registry/test/compatibility_protobuf.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/22798

[v24.2.x] CORE-6824 Schema Registry/Proto: add 5 missing checks
