src/v/cluster/shard_placement_table.cc

If `prepare_transfer` is called concurrently with shard reassignment that increases log revision, `placement_state::_is_initial_for` can change while we were checking that the destination shard is ready. In this case we shouldn't reset `_is_initial_for`.
Example test run where this happens: https://buildkite.com/redpanda/redpanda/builds/52605#01912cd3-d868-4dba-adcd-d619c3a416d2
* none

c/shard_placement_table: fix rare race condition during x-shard transfer

---

MODULE.bazel.lock
bazel/repositories.bzl
bazel/thirdparty/avro.BUILD
cmake/dependencies.cmake

This updates the avro dependency after we have rebased it to the 1.12 release.
The primary motivation was pulling in support for name aliases.
Ref:
* https://github.com/redpanda-data/avro/pull/272
* https://github.com/redpanda-data/vtools/pull/3043
Fixes https://redpandadata.atlassian.net/browse/CORE-6845
* none

CORE-6845 cmake: update avro rebased to 1.12

---

src/v/cloud_storage/inventory/tests/common.h
src/v/cluster/archival/tests/archiver_operations_impl_gtest.cc

For whatever reason these only get caught when compiling with sccache.
Missing in any case so add accordingly.
* none

tests: Add missing override labels where needed

---

CMakeLists.txt
tools/cmake_test.py

Reverts redpanda-data/redpanda#19858
* none

Revert "[v24.1.x] cmake: tweaks for vtools trunk-based development"

---

CMakeLists.txt
tools/cmake_test.py

Reverts redpanda-data/redpanda#22715
* none

Revert "[v24.2.x] cmake: tweaks for vtools trunk-based development"

---

src/v/redpanda/BUILD
src/v/redpanda/application.cc

Somehow we've gotten away without printing the command line all this time. In some contexts it is printed out by some other component but we should print it out ourselves in Redpanda too.
Ref CORE-6746.
* The command line is now printed to the log at startup by the Redpanda process.

application: print command line

---

src/v/cloud_storage/tests/cloud_storage_e2e_test.cc
src/v/cluster/partition.cc

`may_read_from_cloud()` was modified with a sanity check with `remote_fetch_enabled()` to assert that `remote.read` is enabled for a topic before serving a timequery from cloud storage. However, it failed to consider the case of a remote read replica, which should always be able to read from cloud, even with `remote.read=false`.
Fix the condition by adding an `or` statement to `may_read_from_cloud()` which checks `is_read_replica_mode_enabled()`.
* Fixes timequeries not being served to remote read replica topics with `remote.read=false`.

[CORE-6898] `cluster`: fix `partition::may_read_from_cloud()` for remote read replicas

---

src/v/kafka/server/group.cc
src/v/kafka/server/tests/consumer_groups_test.cc

Redpanda generally does not permit empty batches to make their way to
the log. This is problematic in case of an empty offset commit requests.
Kafka returns immediately for empty requests[1], so this tweaks the
return store_offsets() method to do the same. I considered putting this
higher up in the Kafka layer, but there didn't seem to be a specialized
handler for offsets commits where such an early return would be natural.
[1] https://github.com/apache/kafka/blob/98cdf9717049e87ba34bb5161276577fcb8bd1c4/core/src/main/scala/kafka/server/KafkaApis.scala#L504-L505
* Fixes a bug in which empty offset commit requests could result in a crash.

kafka/group: don't replicate empty batch on offset commit

---

src/v/cloud_storage/tests/cloud_storage_e2e_test.cc
src/v/cluster/partition.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/22868

[v24.2.x] [CORE-6898] `cluster`: fix `partition::may_read_from_cloud()` for remote read replicas

---

src/v/cloud_storage/tests/cloud_storage_e2e_test.cc
src/v/cloud_storage/tests/read_replica_fixture.h
src/v/cloud_storage/tests/read_replica_test.cc
src/v/cluster/partition.cc

Manual backport of https://github.com/redpanda-data/redpanda/pull/22868. 
Conflict with Boost -> GTest migration that occurred in `cloud_storage_e2e_test.cc` post version `v24.2.x`.
Fixes https://github.com/redpanda-data/redpanda/issues/22884.
* none

[v24.1.x] `cluster`: fix `partition::may_read_from_cloud()` for remote read replicas (manual backport)

---

src/v/cloud_storage/tests/cloud_storage_e2e_test.cc
src/v/cloud_storage/tests/read_replica_fixture.h
src/v/cloud_storage/tests/read_replica_test.cc
src/v/cluster/partition.cc

Manual backport of https://github.com/redpanda-data/redpanda/pull/22868. 
Conflict with Boost -> GTest migration that occurred in `cloud_storage_e2e_test.cc` post version `v24.2.x`.
Fixes https://github.com/redpanda-data/redpanda/issues/22883.
* none

[v23.3.x] `cluster`: fix `partition::may_read_from_cloud()` for remote read replicas (manual backport)

---

src/v/kafka/protocol/schemata/generator.bzl
src/v/rpc/compiler.bzl

[CORE-5696] bazel: use execpath
* none
[CORE-5696]: https://redpandadata.atlassian.net/browse/CORE-5696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CORE-5696] bazel: use execpath

---

bazel/install-deps.sh

Now that Bazel provides a toolchain we don't need to install a system
wide one.
* none

bazel: remove clang and ldd from deps

---

bazel/build.bzl
src/v/wasm/BUILD
src/v/wasm/tests/BUILD

implementation deps hide the headers to transitive targets, which is
really handy for keeping private headers private. The layering check can
be used in some cases to prevent transitive dependencies leaking when
coupled with bazel visibility, but headers can still accidently leak if
one is not careful. Implementation deps is a much better solution.
* none

bazel: introduce implementation deps

---

src/v/cluster/CMakeLists.txt
src/v/cluster/errc.h
src/v/cluster/errors.cc
src/v/cluster/producer_state.cc
src/v/cluster/producer_state.h
src/v/cluster/producer_state_manager.cc
src/v/cluster/producer_state_manager.h
src/v/cluster/rm_stm.cc
src/v/cluster/rm_stm.h
src/v/cluster/tests/idempotency_tests.cc
src/v/cluster/tests/producer_state_tests.cc
src/v/cluster/tests/rm_stm_test_fixture.h
src/v/cluster/tx_gateway_frontend.cc
src/v/redpanda/application.cc
tests/java/verifiers/pom.xml
tests/java/verifiers/src/main/java/idempotency/App.java
tests/rptest/services/idempotency_load_generator.py
tests/rptest/tests/idempotency_recovery_test.py
tests/rptest/tests/transactions_test.py

Two main changes in this patch
* Broker can now handle epoch bumps for idempotent producers. A client can independently bump the producer epoch in certain situations (check kip-360 and related code) as idempotency only pertains to the single session. The broker code had issues handling epoch bumps which is fixed.
* For evicted producer state on the broker (eg: log prefix truncation, producer expiration etc), there are subtle differences among clients around how they handle the producer reset scenario. Java client, for example bumps the epoch on OOOSN and if there are no other requests in flight while librdkafka is pretty strict and only does it on UNKNOWN_PRODUCER_ID error code (which explicitly tells the client that the broker has no state for the producer and it should reset). Changed …

[backport] [v24.1.x] miscellaneous idempotency fixes #22687

---

src/v/kafka/server/group.cc
src/v/kafka/server/tests/consumer_groups_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/22824

[v24.2.x] kafka/group: don't replicate empty batch on offset commit

---

tests/rptest/services/provider_clients/gcp_client.py
tests/rptest/services/redpanda_cloud.py

* none
* Fixing zones formatting for cluster API requirements. Making it consistent across cloud provider clients
This should fix multiple CI jobs for different cloud providers

Fixing zones format for clusters API requirement

---

src/v/cloud_storage/cache_service.cc
tests/rptest/services/redpanda.py

* none
* Debugging CI failures where redpanda service could not be started within 20 seconds. Added capturing memroy details on top 3 memory-consuming processes

Added capturing details on top 3 memory-consuming processes

---

src/v/config/configuration.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/22664

[v24.1.x] config: update docs for cloud_storage_azure_hierarchical_namespace_enabled

---

tests/rptest/tests/cluster_self_config_test.py

Some nightly CDT runs were reporting failed tests, due to running the `test_s3_self_config` ducktape test on the Azure backend.
Correct this by adding the injection parameter: `get_cloud_storage_type(applies_only_on=[CloudStorageType.S3]`.
Also migrates the test from `RedpandaTest` to `EndToEndTest` fixture.
* none

`rptest`: only apply `test_s3_self_config` on `S3` storage

---

src/v/kafka/server/group.cc
src/v/kafka/server/tests/consumer_groups_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/22824

[v24.1.x] kafka/group: don't replicate empty batch on offset commit

---

src/v/storage/logger.cc
src/v/storage/logger.h
src/v/storage/storage_resources.cc
tests/rptest/services/redpanda.py

Storage resource manager logs are very verbose. Added separate logger for the resource manager logging to be able to mute the logs while preserving other relevant log messages.
Muted `dns_resolver` and `storage-resources` loggers in tests.
- none

Tests logging improments

---

src/v/wasm/parser/BUILD
src/v/wasm/parser/parser.cc
src/v/wasm/parser/tests/BUILD

Add some tests to Bazel
* none

bazel: add tests for wasm/parser

---

src/v/cloud_storage/remote.cc
src/v/cloud_storage_clients/configuration.cc
src/v/cloud_storage_clients/configuration.h
src/v/cloud_storage_clients/s3_client.cc
src/v/config/configuration.cc
src/v/config/convert.h
src/v/model/metadata.h
tests/rptest/services/redpanda.py
tests/rptest/tests/cluster_self_config_test.py

As a first step in improving compatibility with OCI, help the `s3_client` properly self-configure itself for the newly added `cloud_storage_backend::oracle` value.
The `s3_client::self_configure()` function performs a check with a `ListObjects()` request that currently succeeds for OCI, even in the unsupported `virtual_host` mode. This would result in improper self-configuration, and every other cloud storage API call made to `OCI` in this configuration fails.
Correct this behavior by inferring the `oraclecloud` backend through the `access_point_uri` used, and always self-configure for `path`-style requests when it is in use. 
* Adds the `cloud_storage_backend::oracle` value, and helps the `s3_client` properly configure for OCI storage.

`cloud_storage_clients`: add `cloud_storage_backend::oracle` and fix `s3_client::self_configure()`

---

src/v/cloud_storage/cache_service.h

Slightly improve readability of the constructor.
* none

cloud_storage: add param names to cache ctor

---

bazel/test.bzl
src/v/transform/logging/BUILD
src/v/transform/logging/tests/BUILD
src/v/transform/logging/tests/log_manager_test.cc
src/v/transform/logging/tests/model_test.cc
src/v/transform/tests/BUILD

bazel: breakup transform/logging and add tests

---

src/v/cluster/tx_gateway_frontend.cc
tests/rptest/transactions/transactions_test.py

Instead return INVALID_PRODUCER_ID_MAPPING like Apache Kafka https://github.com/apache/kafka/blob/cd47b3c1cce7a9f1881e40d38742b9ec8b30cf32/core/src/main/scala/kafka/coordinator/transaction/TransactionCoordinator.scala#L513C23-L513C50
* none

tx: do not throw USE on expired transaction_ids

---

src/v/cluster/self_test_backend.cc
src/v/cluster/self_test_backend.h
src/v/cluster/self_test_frontend.cc
src/v/cluster/self_test_rpc_types.cc
src/v/cluster/self_test_rpc_types.h
src/v/redpanda/admin/server.cc
tests/rptest/tests/self_test_test.py

To allow for compatibility between clusters of mixed version nodes (in the case of a rolling upgrade), we add the `parse_unknown_checks()` function to the `self_test_backend`.
There are two possibilities in a mixed version cluster:
1. The `rpk cluster self-test start` request is sent to the controlling node, which is a higher version than the other nodes in the cluster. They do not recognize some of the tests in the `start_test_request` json, and push back an error to `self_test_result`. This case is covered by a previous PR, https://github.com/redpanda-data/redpanda/pull/21370.
2. The `rpk cluster self-test start` request is sent to the controlling node, which is a lower version than the other nodes in the cluster. Previously, this request would not be propagated to the other nodes, …

`cluster`: Parse unknown self-test checks

---

src/v/cluster/self_test_rpc_types.h

[v24.1.x] `cluster`: add `serde_fields()` to `start_test_request`

---

src/v/resource_mgmt/storage.cc
src/v/storage/BUILD
src/v/storage/api.cc
src/v/storage/api.h
src/v/storage/chunk_cache.h
src/v/storage/directories.h
src/v/storage/node.cc
src/v/storage/offset_to_filepos.cc
src/v/storage/offset_to_filepos.h
src/v/storage/probe.cc
src/v/storage/probe.h
src/v/storage/readers_cache.cc
src/v/storage/snapshot.cc

storage: make logger a Bazel private library
* none

storage: make logger a Bazel private library

---

src/v/cluster/self_test_backend.cc
src/v/cluster/self_test_backend.h
src/v/cluster/self_test_frontend.cc
src/v/cluster/self_test_rpc_types.cc
src/v/cluster/self_test_rpc_types.h
src/v/redpanda/admin/server.cc
tests/rptest/tests/self_test_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22831

[v24.2.x] `cluster`: Parse unknown self-test checks

---

src/v/cloud_storage/remote.cc
src/v/cloud_storage_clients/configuration.cc
src/v/cloud_storage_clients/configuration.h
src/v/cloud_storage_clients/s3_client.cc
src/v/config/configuration.cc
src/v/config/convert.h
src/v/model/metadata.h
tests/rptest/services/redpanda.py
tests/rptest/tests/cluster_self_config_test.py

Manual backport of https://github.com/redpanda-data/redpanda/pull/22902.
Cherry-pick conflict due to migration from `RedpandaTest` to `EndToEndTest` fixture in `cluster_self_config_test.py` that wasn't yet present in branch `v24.2.x`. 
Conflicts fixed, no major changes outside test file.
Fixes https://github.com/redpanda-data/redpanda/issues/22915
* none

[v24.2.x] `cloud_storage_clients`: add `cloud_storage_backend::oracle` and fix `s3_client::self_configure()` (manual backport)

---

src/v/cluster/archival/archival_policy.cc
src/v/cluster/archival/tests/ntp_archiver_test.cc
tests/rptest/tests/shadow_indexing_compacted_topic_test.py

This PR fixes the issue which manifests if the TS is enabled for pre-existing compacted topic. Normally, the TS prevents compaction from compacting any offset range which is not uploaded to the cloud storage yet. Our upload path always deals with non-compacted data without gaps. The only exception is when the compaction is enabled for existing compacted topic. In this case the data is already compacted but has to be uploaded to the cloud storage anyway. And the upload is performed by the normal upload path (not compacted reupload).
The problem is that there is a bug in the `archival_policy::find_segment` which makes it skip compacted segment. If the segment that the policy have found is compacted it just increments the iterator once and creates a gap. The segment can't be added to the …

CORE-6835 Fix first time compacted segment upload

---

MODULE.bazel

Similar to Rust and Clang allow bazel to manage the toolchain instead of
the host.
* none

bazel: auto download golang SDK

---

src/v/cloud_storage_clients/s3_client.cc
src/v/cloud_storage_clients/s3_client.h
tests/rptest/tests/cluster_config_test.py
tests/rptest/tests/cluster_self_config_test.py
tests/rptest/tests/self_test_test.py

These permission checks were unnecessary and lead to confusing behaviour.
Default to using a `ListObjects` request for self-configuring the addressing style used for the `s3_client`.
* none

`cloud_storage_clients`: remove remote perm checks from `s3_client::self_configure()`

---

src/v/cloud_storage_clients/s3_client.cc
src/v/cloud_storage_clients/s3_client.h
tests/rptest/tests/cluster_config_test.py
tests/rptest/tests/cluster_self_config_test.py
tests/rptest/tests/self_test_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22923

[v24.2.x] `cloud_storage_clients`: remove remote perm checks from `s3_client::self_configure()`

---

src/v/storage/disk_log_impl.cc
src/v/storage/tests/log_retention_tests.cc
src/v/storage/tests/storage_e2e_fixture_test.cc
tests/rptest/tests/retention_policy_test.py

Currently, we check that there is more than one segment in a `disk_log_impl`'s `segment_set` for determining it as having segments for eviction.
This gets us into a situation in which we can evict all segments in a log if we were to have `_segs.size() > 1`, but none if `_segs.size() == 1`.
This is an overly restrictive condition, and is corrected here.
We openly admit that we may delete the active segment [here in `disk_log_impl::do_truncate_prefix()`](https://github.com/redpanda-data/redpanda/blob/35cedc84bcb553b5adb08bd6dc172252e8b34291/src/v/storage/disk_log_impl.cc#L2555-L2558), so there is no reason to be so restrictive with the condition in `request_eviction_until_offset()`
Fixes https://github.com/redpanda-data/redpanda/issues/18014.
* Fixes a condition in `disk_log_impl` that …

`storage`: fix condition in `disk_log_impl::have_segments_to_evict()`

---

MODULE.bazel.lock
bazel/repositories.bzl

Uses:
* https://github.com/redpanda-data/seastar/pull/136
* https://github.com/redpanda-data/seastar/pull/139
Fixes https://redpandadata.atlassian.net/browse/CORE-6859
* Fixes a bug in metrics reporting where label values containing special characters (`"`, `\`, `\n`) could lead to a malformed metrics response.

CORE-6859 bazel: update seastar with prometheus fix

---

src/go/rpk/pkg/tuners/iotune/data.go

Adds io properties for m7gd.
Same effect as in other instances is noted where measured read IOPS perf
doesn't match advertised. We stick to the advertised values.
* none

iotune: Add ioprops for m7gd

---

src/v/cluster/errc.h
src/v/cluster/errors.cc
src/v/cluster/health_monitor_backend.cc
src/v/cluster/health_monitor_types.cc
src/v/cluster/health_monitor_types.h
src/v/cluster/node_status_backend.cc
src/v/cluster/node_status_backend.h
src/v/cluster/service.cc
src/v/kafka/server/errors.h
tests/rptest/tests/node_folder_deletion_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22811

[v24.1.x] CORE-5766 Validate target node id when collecting health report

---

src/v/archival/archival_policy.cc
src/v/archival/tests/ntp_archiver_test.cc
tests/rptest/tests/shadow_indexing_compacted_topic_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22812

[v24.2.x] CORE-6835 Fix first time compacted segment upload

---

src/v/cluster/tx_gateway_frontend.cc
tests/rptest/transactions/transactions_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22912

[v24.2.x] tx: do not throw USE on expired transaction_ids

---

src/v/cluster/tx_gateway_frontend.cc

When transaction is committed the process may be interrupted in any of the steps i.e. before replicating the `preparing_commit` state update, before requesting data partitions to commit transaction or before replicating `completed_commit` state update. When an `end_txn` request is retried by the client `tx_gateway` try to progress the transaction before it is returned for further processing in either commit or abort handling method. It may be the case that the transaction progress all the way to `completed_commit` state, in this case Redpanda should return a success to client as the transaction was finished.
Fixed a bug leading to the situation in which an invalid transaction state error was returned when transaction was progressed to `completed_commit` phase before entering a commit …

c/tx_gateway: made `end_txn` fully idempotent when committing transaction

---

src/v/kafka/server/replicated_partition.cc
tests/rptest/clients/kafka_cli_tools.py
tests/rptest/tests/delete_records_test.py

Previously, we would return an `error_code::offset_out_of_range` for a request where `kafka_truncation_offset <= start_offset`.
This is a divergence from the current Kafka behaviour, and can lead to errors with certain Kafka clients/consumers.
Remove the condition that throws an `offset_out_of_range` error if `kafka_truncation_offset <= start_offset()`, instead returning `error_code::none`.
More context and details in the JIRA link below.
JIRA Link: https://redpandadata.atlassian.net/browse/CORE-6807
* Allows `DeleteRecords` requests from Kafka clients or `rpk topic trim-prefix` to be called with `truncation_offset <= start_offset` without returning an error. The request is instead treated as a no-op.

[CORE-6807] `kafka`: change `offset_out_of_range` condition in `replicated_partition::prefix_truncate()`

---

src/v/storage/compacted_index_chunk_reader.cc
src/v/storage/compacted_index_chunk_reader.h
src/v/storage/compacted_index_reader.h
src/v/storage/segment_deduplication_utils.cc
src/v/storage/segment_utils.cc
src/v/storage/tests/compaction_index_format_tests.cc

Segment compaction is a process that may take a significant amount of time, especially when segment size is large as it was merged with other segments during compaction. Added checking an abort source while reading the compacted index to make the operation interruptible. This way when requested Redpanda will be able to stop faster.
Fixes: CORE-5542
Fixes: CORE-5532
Fixes: CORE-1994
- none

[CORE-5542] s/segment_utils: pass abort source into compacted index reader

---

src/v/cluster/tx_gateway_frontend.cc
tests/rptest/tests/transactions_test.py

Backport of https://github.com/redpanda-data/redpanda/pull/22912
Instead return INVALID_PRODUCER_ID_MAPPING like Apache Kafka https://github.com/apache/kafka/blob/cd47b3c1cce7a9f1881e40d38742b9ec8b30cf32/core/src/main/scala/kafka/coordinator/transaction/TransactionCoordinator.scala#L513C23-L513C50
(cherry picked from commit 84f42dba01dc3c1633145e14dd0c64a6ff61a59c)
Fixes https://github.com/redpanda-data/redpanda/issues/22918
* none

[backport] [24.1.x] tx: do not throw USE on expired transaction_ids

---

src/v/kafka/server/replicated_partition.cc
tests/rptest/clients/kafka_cli_tools.py
tests/rptest/tests/delete_records_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22905

[v24.1.x] [CORE-6807] `kafka`: change `offset_out_of_range` condition in `replicated_partition::prefix_truncate()`

---

src/v/iceberg/BUILD
src/v/iceberg/CMakeLists.txt
src/v/iceberg/logger.cc
src/v/iceberg/logger.h
src/v/iceberg/tests/BUILD
src/v/iceberg/tests/CMakeLists.txt
src/v/iceberg/tests/values_test.cc
src/v/iceberg/values.cc
src/v/iceberg/values.h

This adds a representation of record values, for use in Iceberg
integration. Some expected usage of these values are:
- When converting Kafka data records to an intermediary format before
converting to parquet, that format can be these values, rather than a
thirdparty representation like Arrow (which may not play well with
Seastar's allocator, e.g. doesn't use iobufs).
- We can represent manifest entries as these values, and then serialize
the values to Avro dynamically, rather than using fixed-schema
codegen. This allows us to include a partition key to the manifest
entries, which we wouldn't be able to do with the current codegen.
The latter here is my primary motivator, but the implementation is
enough to serve the former use case too.
The structure of the values roughly resembles the …

iceberg: add value representation

---

src/v/kafka/server/replicated_partition.cc
tests/rptest/clients/kafka_cli_tools.py
tests/rptest/tests/delete_records_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22905

[v24.2.x] [CORE-6807] `kafka`: change `offset_out_of_range` condition in `replicated_partition::prefix_truncate()`

---

src/v/cluster/tx_gateway_frontend.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/22937

[v24.2.x] c/tx_gateway: made `end_txn` fully idempotent when committing transaction

---

src/v/storage/compacted_index_chunk_reader.cc
src/v/storage/compacted_index_chunk_reader.h
src/v/storage/compacted_index_reader.h
src/v/storage/segment_deduplication_utils.cc
src/v/storage/segment_utils.cc
src/v/storage/tests/compaction_index_format_tests.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/22938

[v24.1.x] [CORE-5542] s/segment_utils: pass abort source into compacted index reader

---

src/v/storage/compacted_index_chunk_reader.cc
src/v/storage/compacted_index_chunk_reader.h
src/v/storage/compacted_index_reader.h
src/v/storage/segment_deduplication_utils.cc
src/v/storage/segment_utils.cc
src/v/storage/tests/compaction_index_format_tests.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/22938

[v24.2.x] [CORE-5542] s/segment_utils: pass abort source into compacted index reader

---

tests/rptest/tests/cloud_storage_inventory_test.py

Previously the test did not wait for hashes to appear to disk. Now it waits for 60 seconds for the report to be processed so the test has time to finish.
FIXES #22934
* none

ducktape/cst-inv: wait for hashes to appear

---

tests/rptest/services/redpanda.py
tests/rptest/tests/cluster_self_config_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22928

[v24.2.x] `rptest`: allow user to override `cloud_storage_api_endpoint`

---

src/v/storage/BUILD
src/v/storage/batch_cache.cc
src/v/storage/batch_cache.h
src/v/storage/tests/BUILD
src/v/storage/tests/batch_cache_test.cc

storage: split batch_cache into separate bazel library and adds bazel test for batch cache.
* none

storage: split batch_cache into separate bazel library

---

src/v/storage/index_state.h
src/v/storage/tests/index_state_test.cc

In cases of lots of small indexes the overhead of many of these
fragmented_vectors can be quite high. Reduce the overhead by using
chunked_vector so the first chunk isn't full length.
* Reduce the memory overhead of many small segments.

storage/index_state: use chunked_vector

---

src/v/storage/index_state.h
src/v/storage/tests/index_state_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/22962

[v24.1.x] storage/index_state: use chunked_vector

---

src/v/storage/index_state.h
src/v/storage/tests/index_state_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/22962

[v24.2.x] storage/index_state: use chunked_vector

---

tests/rptest/tests/tiered_storage_model.py

This is a test fix: in the runs linked to https://redpandadata.atlassian.net/browse/CORE-2632 the failure reason is a too-strict timeout while collecting these metrics:
SegmentRolledByTimeout looks for "segment.ms applied" in the log. in a 100 secs window, this line can appear only ~10 times (for each topic),
and this is close to the previous threshold of 8.
TS_Read keeps track of vectorized_cloud_storage_successful_download_count
Decrease the threshold for both of them to 4 to make the test less flaky
Fixes [CORE-2632
](https://redpandadata.atlassian.net/browse/CORE-2632)
* none

[CORE-2632] tiered_storage_model_test: relax requirements for SegmentRolledByTimeout TS_Read 

---

src/v/cluster/metadata_dissemination_handler.cc
src/v/cluster/metadata_dissemination_handler.h
src/v/cluster/metadata_dissemination_service.cc
src/v/cluster/metadata_dissemination_types.h
src/v/cluster/tests/serialization_rt_test.cc
src/v/compat/metadata_dissemination_generator.h

Previously each time the leadership update request was received by the
`metadata_dissemination_handler` it created a copy for each of the shard
on the shard handling the request. This is inefficient and may lead to
OOM on the handler shard (especially for very large machines).
Instead of creating a copy for each shard we can simply use the const
reference as the updates vector doesn't change and it is safe to access
it from other cores.
- optimized memory usage with large core count nodes

Fix dissemination large shard count

---

src/v/kafka/server/replicated_partition.cc
tests/rptest/tests/delete_records_test.py

As a follow-up to a previous commit which failed to consider the cases for a negative `truncation_offset`.
In Kafka, a `truncation_offset = -1` [indicates a `DeleteRecords` call up to the `high_watermark`](https://github.com/apache/kafka/blob/fb7e47f6e28cc325bbb354348d2abde4696d7915/core/src/main/scala/kafka/cluster/Partition.scala#L1683), [whereas all other negative values result in an `offset_out_of_range` error.](https://github.com/apache/kafka/blob/fb7e47f6e28cc325bbb354348d2abde4696d7915/core/src/main/scala/kafka/cluster/Partition.scala#L1688-L1689)
Correct the cases here, and add tests for both of them.
This will potentially require new messaging from docs, indicating the corner case for -1: https://docs.redpanda.com/current/reference/rpk/rpk-topic/rpk-topic-trim-prefix/.
Holding …

`kafka`: deal with `truncation_offset < 0` cases in `prefix_truncate()`

---

src/v/kafka/server/replicated_partition.cc
tests/rptest/tests/delete_records_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22968

[v24.1.x] `kafka`: deal with `truncation_offset < 0` cases in `prefix_truncate()`

---

src/v/kafka/server/replicated_partition.cc
tests/rptest/tests/delete_records_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22968

[v24.2.x] `kafka`: deal with `truncation_offset < 0` cases in `prefix_truncate()`

---

src/go/rpk/go.mod
src/go/rpk/go.sum
src/go/rpk/pkg/cli/cluster/partitions/balancer_run.go
src/go/rpk/pkg/cli/cluster/partitions/partitions.go

Although the continuous balancer has been becoming smart, there's still needs where we need to invoke the on-demand balancer to balance partitions across brokers. This commit adds a new `rpk cluster partitions balance` command that wraps the `POST /v1/partitions/rebalance` endpoint.
Internal discussion: https://redpandadata.slack.com/archives/C04LYNJQUGN/p1722580784813209
* rpk: supports triggering on-demand partition balancer

rpk: supports triggering on-demand balancer

---

src/v/cluster/archival/tests/service_fixture.cc
src/v/cluster/bootstrap_backend.cc
src/v/cluster/controller.cc
src/v/cluster/controller_backend.cc
src/v/cluster/controller_backend.h
src/v/cluster/members_backend.cc
src/v/cluster/members_manager.cc
src/v/cluster/members_manager.h
src/v/cluster/members_table.cc
src/v/cluster/partition_manager.cc
src/v/cluster/partition_manager.h
src/v/cluster/raft0_utils.h
src/v/features/feature_table.cc
src/v/features/feature_table.h
src/v/raft/consensus_utils.cc
src/v/raft/consensus_utils.h
src/v/raft/fundamental.h
src/v/raft/group_configuration.h
src/v/raft/group_manager.cc
src/v/raft/group_manager.h
src/v/raft/tests/simple_raft_fixture.h
tests/rptest/utils/si_utils.py

The PR has to be reverted as it is not possible to retire a `command_based_membership` feature without bumping the `earliest_version`
Reverts redpanda-data/redpanda#22701
- none

Revert "Retire old membership updates based on Raft configuration"

---

src/v/storage/disk_log_impl.cc
src/v/storage/tests/log_retention_tests.cc

Reverts functional changes in https://github.com/redpanda-data/redpanda/pull/22686.
The associated test with this is deadlocking in every ~1/30-40 runs. 
Revert the change for now, until a proper investigation can be made towards making this a demonstrably safe change.
* none

Revert `storage`: fix condition in `disk_log_impl::have_segments_to_evict()`

---

src/v/storage/disk_log_impl.cc
src/v/storage/tests/log_retention_tests.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/22995

[v24.2.x] Revert `storage`: fix condition in `disk_log_impl::have_segments_to_evict()`

---

src/v/storage/disk_log_impl.cc
src/v/storage/tests/log_retention_tests.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/22995

[v24.1.x] Revert `storage`: fix condition in `disk_log_impl::have_segments_to_evict()`

---

src/v/cluster/rm_stm.cc
src/v/cluster/rm_stm.h

sync() before creating producers so the latter sees the latest state immediately after a leadership transfer. This was fixed during the rm_stm rewrite in `dev` branch but was not backported to 24.1.x
* none

[backport] [v24.1.x] rm_stm: fix race during leadership transfer

---

src/v/cluster/archival/archival_metadata_stm.cc
src/v/cluster/archival/archival_metadata_stm.h
src/v/cluster/distributed_kv_stm.h
src/v/cluster/id_allocator_stm.cc
src/v/cluster/id_allocator_stm.h
src/v/cluster/log_eviction_stm.cc
src/v/cluster/log_eviction_stm.h
src/v/cluster/rm_stm.cc
src/v/cluster/rm_stm.h
src/v/cluster/tests/rm_stm_test_fixture.h
src/v/cluster/tm_stm.cc
src/v/cluster/tm_stm.h
src/v/kafka/server/group_tx_tracker_stm.cc
src/v/kafka/server/group_tx_tracker_stm.h
src/v/raft/persisted_stm.cc
src/v/raft/persisted_stm.h
src/v/raft/tests/persisted_stm_test.cc

When a local snapshot is taken by the `persisted_stm` it should not
interleave with apply. Added a lock to make sure that both the apply and
`take_local_snapshot` do not overlap.
* none

r/persisted_stm: serialize apply and taking local snapshot with a mutex

---

src/v/storage/BUILD
src/v/storage/compacted_index.h
src/v/storage/compaction.h
src/v/storage/key_offset_map.h
src/v/storage/tests/BUILD
src/v/storage/tests/key_offset_map_test.cc

* storage: build key offset map as separate bazel library
* adds the offset map test to bazel build
* none

storage: build key offset map as separate bazel library

---

src/v/pandaproxy/schema_registry/json.cc
src/v/pandaproxy/schema_registry/types.h

No functional changes, just refactoring.
This is groundwork for references support in CORE-6836
* none

schema_registry/json: Refactoring to add a context with schema version

---

src/v/cluster/metadata_dissemination_handler.cc
src/v/cluster/metadata_dissemination_handler.h
src/v/cluster/metadata_dissemination_service.cc
src/v/cluster/metadata_dissemination_types.h
src/v/cluster/tests/serialization_rt_test.cc
src/v/compat/metadata_dissemination_generator.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/22977

[v24.2.x] Fix dissemination large shard count

---

src/v/redpanda/admin/migrations.cc

Rapidjson does not support if-then-else and just ignores these. Rewrote using anyOf.
see https://redpandadata.slack.com/archives/C01ND4SVB6Z/p1724279350465689 for discussion
* none

admin/migrations: fixed HTTP body JSON validation

---

tests/rptest/services/redpanda.py

We want to scale up CDT parallelism by way of increasing number of nodes.  One existing risk today is the number of S3 storage buckets that get accumulated during a test session (about 300).  With a hard limit of 1000 buckets per AWS account, we cannot safely run more than 3 CDT runs in between our async cleanup schedules (hours).  This is too limiting - with much faster CDT runs, we may run more frequently and hit the bucket count limit more often (heck even today we hit it sometimes).
Cleaning buckets inline as part of each test case teardown was always ideal.  But we know that certain buckets become very populous and can take a long time (many tens of minutes for millions of objects even with batch requests).
This PR provides a compromise.  The important thing is keeping bucket …

[rptest] always clean up object stores (that are small) for non-GCP

---

src/v/datalake/CMakeLists.txt
src/v/datalake/data_writer_interface.h
src/v/datalake/record_multiplexer.cc
src/v/datalake/record_multiplexer.h
src/v/datalake/schemaless_translator.cc
src/v/datalake/schemaless_translator.h
src/v/datalake/tests/CMakeLists.txt
src/v/datalake/tests/gtest_record_multiplexer_test.cc
src/v/datalake/tests/test_data_writer.h

This is a skeleton implementation of the event multiplexer. This is a log consumer that will determine the schema ID and type (Protobuf, JSON, Avro) of each event, and sends them to the correct translator and writer.
In this version it translates schemaless events and sends them to a test writer that simply counts them.
* none

datalake: add event multiplexer

---

tests/rptest/tests/tiered_storage_model.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22849

[v24.2.x] [CORE-2632] tiered_storage_model_test: relax requirements for SegmentRolledByTimeout TS_Read 

---

tests/rptest/scale_tests/tiered_storage_cache_stress_test.py

This is similar to the fix applied in
https://github.com/redpanda-data/redpanda/pull/22796/ commit 7763669 which is needed after carryover trim was disabled and we hit cache trimming throttling making the test slower than our threshold
Fixes #13648
CORE-1464
* none

rptest: reduce cache eviction throttling for tiny cache stress test

---

src/v/raft/tests/stm_test_fixture.h

Fixes https://github.com/redpanda-data/redpanda/issues/23012
* none

raft/tests: fix use-after-move when replication is retried

---

tests/rptest/tests/schema_registry_test.py

Add SchemaRegistryCompatibilityModes for JSON and AVRO
This test will register a list of `schemas` using compatibility=`mode`.
Optionally, if `antimode` is specified, 
it will check that each schema will fail to register with compatibility=`antimode`
the test is parametrized for JSON schema, and mode
`BACKWARD, BACKWARD_TRANSITIVE, FORWARD, FORWARD_TRANSITIVE, NONE, FULL, FULL_TRANSITIVE`
the schemas themself are extremely basic
Fixes https://redpandadata.atlassian.net/browse/CORE-3188
* none

[CORE-3188] schema registry DT tests for various compatibility modes

---

src/go/rpk/pkg/cli/registry/schema/check_compatibility.go
src/v/pandaproxy/api/api-doc/schema_registry.json
src/v/pandaproxy/api/api-doc/schema_registry_definitions.def.json
src/v/pandaproxy/schema_registry/CMakeLists.txt
src/v/pandaproxy/schema_registry/avro.cc
src/v/pandaproxy/schema_registry/avro.h
src/v/pandaproxy/schema_registry/compatibility.cc
src/v/pandaproxy/schema_registry/compatibility.h
src/v/pandaproxy/schema_registry/handlers.cc
src/v/pandaproxy/schema_registry/json.cc
src/v/pandaproxy/schema_registry/json.h
src/v/pandaproxy/schema_registry/protobuf.cc
src/v/pandaproxy/schema_registry/protobuf.h
src/v/pandaproxy/schema_registry/requests/compatibility.h
src/v/pandaproxy/schema_registry/sharded_store.cc
src/v/pandaproxy/schema_registry/sharded_store.h
src/v/pandaproxy/schema_registry/test/compatibility_avro.cc
src/v/pandaproxy/schema_registry/test/test_json_schema.cc
src/v/pandaproxy/schema_registry/types.h
tests/rptest/tests/schema_registry_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22877
Fixes https://github.com/redpanda-data/redpanda/pull/22955

[v24.2.x] CORE-6860 SR: Wire up support for ?verbose compatibility checks

---

tests/rptest/scale_tests/tiered_storage_cache_stress_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23006
Fixes: https://github.com/redpanda-data/redpanda/issues/23024,

[v24.2.x] rptest: reduce cache eviction throttling for tiny cache stress test

---

bazel/test.bzl
src/v/raft/tests/CMakeLists.txt
tools/cmake_test.py

Since this test uses 8 cores, by default each shard gets only 128M, which is barely enough and sometimes leads to bad allocs.
Also, turn `--abort-on-seastar-bad-alloc` on in tests, so that bad_allocs are more visible.
* none

raft: increase memory limit for gtest_raft_rpunit

---

src/go/rpk/pkg/cli/registry/schema/check_compatibility.go
src/v/pandaproxy/api/api-doc/schema_registry.json
src/v/pandaproxy/api/api-doc/schema_registry_definitions.def.json
src/v/pandaproxy/schema_registry/CMakeLists.txt
src/v/pandaproxy/schema_registry/avro.cc
src/v/pandaproxy/schema_registry/avro.h
src/v/pandaproxy/schema_registry/compatibility.cc
src/v/pandaproxy/schema_registry/compatibility.h
src/v/pandaproxy/schema_registry/handlers.cc
src/v/pandaproxy/schema_registry/protobuf.cc
src/v/pandaproxy/schema_registry/protobuf.h
src/v/pandaproxy/schema_registry/requests/compatibility.h
src/v/pandaproxy/schema_registry/sharded_store.cc
src/v/pandaproxy/schema_registry/sharded_store.h
src/v/pandaproxy/schema_registry/test/compatibility_avro.cc
src/v/pandaproxy/schema_registry/types.h
tests/rptest/tests/schema_registry_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22877 
Fixes https://github.com/redpanda-data/redpanda/issues/22957
Fixes https://redpandadata.atlassian.net/browse/CORE-6997

[v23.3.x] CORE-6860 SR: Wire up support for  compatibility checks

---

src/v/kafka/server/connection_context.h
src/v/kafka/server/handlers/details/security.h
src/v/kafka/server/handlers/metadata.cc
src/v/kafka/server/handlers/metadata.h
src/v/kafka/server/request_context.h
src/v/kafka/server/tests/CMakeLists.txt
src/v/kafka/server/tests/metadata_test.cc

Adds support for metadata API version 8
* Added support for Metadata API v8

CORE-3092 support metadata v9

---

src/v/redpanda/admin/server.cc
tests/rptest/tests/cluster_config_test.py

Requesting a key that does not exist in the `config_store::get()` function throws an `std::out_of_range` exception.
This would lead to retries on an invalid request made to `get_cluster_config` in the admin server, and what seems like a short hang to the user on the `rpk` side.
Improve the UX by wrapping this in a `try/catch` block, and throw a `ss::httpd::bad_param_exception` instead in case of an invalid key.
The admin request will not be retried, and the user on the `rpk` side will immediately get a proper `400` response.
* none

`admin`: improve `cluster config get` UX for invalid requests

---

tools/rp_storage_tool/Cargo.lock

Rust `1.80.0` broke backwards compatibility with older versions of the `time` crate: https://github.com/rust-lang/rust/issues/127343
Users with an updated compiler will be unable to build `rp-storage-tool` with the previous dependency versions.
Update `Cargo.lock` with updated dependencies generated from `cargo build --release` and Rust compiler version
`rustc 1.80.1 (3f5fd8dd4 2024-08-06)`.
* none

`tools/rp_storage_tool`: bump dependencies

---

src/v/iceberg/BUILD
src/v/iceberg/CMakeLists.txt
src/v/iceberg/partition.h
src/v/iceberg/partition_key.cc
src/v/iceberg/partition_key.h
src/v/iceberg/partition_key_type.cc
src/v/iceberg/partition_key_type.h
src/v/iceberg/schema.cc
src/v/iceberg/schema.h
src/v/iceberg/struct_accessor.cc
src/v/iceberg/struct_accessor.h
src/v/iceberg/tests/BUILD
src/v/iceberg/tests/CMakeLists.txt
src/v/iceberg/tests/partition_key_test.cc
src/v/iceberg/tests/partition_key_type_test.cc
src/v/iceberg/tests/schema_test.cc
src/v/iceberg/tests/struct_accessor_test.cc
src/v/iceberg/tests/transform_utils_test.cc
src/v/iceberg/tests/value_generator.cc
src/v/iceberg/tests/value_generator.h
src/v/iceberg/time_transform_visitor.cc
src/v/iceberg/time_transform_visitor.h
src/v/iceberg/transform.cc
src/v/iceberg/transform.h
src/v/iceberg/transform_utils.cc
src/v/iceberg/transform_utils.h

This PR adds the capability to group together Iceberg values with a partition spec.
At a high level, the partition spec defines a set of fields and transforms to be applied to those fields that can be used to generate a "partition key" for a given record. The partition key needs to be serialized as Avro with each manifest, where each manifest file contains data that all have the same partition key.
To that end, this PR introduces a few things:
- utilities to get the types from a schema, so that the types can be transformed and a partition key schema can be constructed based on these types (also required by the Iceberg spec to be in the manifests)
- accessors to be able to get a specific field from a given value, so we can transform specific values
- types for the partition key and …

iceberg: introduce partition keys

---

src/v/cluster/rm_stm.cc
src/v/cluster/rm_stm.h
src/v/model/record.h

Changed the structure of the method taking an `rm_stm` snapshot not to keep the STM apply units while persisting/removing aborted transactions snapshots. This makes the snapshot taking latency impact negligible. With the previous solution the `rm_stm` snapshot taking might negatively influence performance.
- none

c/rm_stm: optimized taking rm_stm snapshot

---

MODULE.bazel.lock
bazel/repositories.bzl
bazel/thirdparty/avro.BUILD
cmake/dependencies.cmake

Backport of PR https://github.com/redpanda-data/redpanda/pull/22848 
Fixes https://github.com/redpanda-data/redpanda/issues/22874
Fixes https://redpandadata.atlassian.net/browse/CORE-6902
The conflict was on the bazel lock file.

[v24.2.x] CORE-6845 cmake: update avro rebased to 1.12

---

tests/rptest/services/redpanda.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22946

[v24.2.x] [rptest] always clean up object stores (that are small) for non-GCP

---

tests/docker/ducktape-deps/rust

After bumping dependencies in https://github.com/redpanda-data/redpanda/pull/23036, we must update the rust version from `1.70.0` to `1.80.1`.
* none

`docker`: bump `rust` version

---

.bazelrc
bazel/thirdparty/seastar.BUILD
src/v/hashing/tests/BUILD
src/v/storage/tests/BUILD

- **bazel: require openssl for seastar**
- **bazel: make boost test a test only dep**
* none

bazel: remove test dep from seastar

---

bazel/thirdparty/krb5.BUILD

Looking at `ldd` of the bazel build, we were missing a library, so I'm
adding it here.
* none

bazel: add missing shared library for krb5

---

src/v/raft/heartbeat_manager.cc

Some time ago we made collecting heartbeats an asynchronous process (added yields in between creating hb requests for individual nodes). This made it possible for leadership to be already lost while the request for group is created as the yield happened and previously validated condition no longer holds. Trying to suppress the heartbeat while the replica is not leader lead to assertion.
Added a check to make sure the leadership is not lost when actually creating a heartbeat request for the follower.
- fixes rare assertion that might have been triggered in the `raft::heartbeat_manager`

r/hb_mgr: check if current replica is a leader when collecting hbeats

---

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
tests/rptest/services/redpanda.py

Slack [thread](https://redpandadata.slack.com/archives/C03DEVA3JM7/p1724433122332119?thread_ts=1724424116.431729&cid=C03DEVA3JM7).
* none

Fix cloud operator_v2 check

---

src/go/rpk/pkg/cli/cloud/login.go
src/go/rpk/pkg/cli/security/user/create.go
src/go/rpk/pkg/cli/security/user/delete.go
src/go/rpk/pkg/cli/security/user/list.go
src/go/rpk/pkg/cli/security/user/update.go
src/go/rpk/pkg/config/config.go

- 572ad197a68ffdbc3b12ec6aaaabb83503bd981a Fixes a bug that prevented `--no-profile` from working with SSO.
- fe4768522c9fb954c5d4d42896452c722091a4ed Adds a cloud check (better error message) for `rpk security user` which is a command that cannot be used in cloud clusters (except for serverless)
* rpk: fix a bug in `rpk cloud login` that prevented `--no-profile` from working when used with SSO login.

rpk: fix --no-profile and add cloud checks for `rpk security user` commands.

---

MODULE.bazel.lock
bazel/repositories.bzl
bazel/thirdparty/hdrhistogram.BUILD

bazel: port hdrhistogram to a native bazel build

---

src/v/bytes/bytes.cc
src/v/bytes/bytes.h
src/v/bytes/iobuf_parser.h
src/v/bytes/random.cc
src/v/bytes/tests/iobuf_tests.cc
src/v/cluster/distributed_kv_stm.h
src/v/cluster/types.cc
src/v/crypto/tests/hmac_tests.cc
src/v/iceberg/transform.h
src/v/kafka/protocol/flex_versions.cc
src/v/kafka/protocol/tests/protocol_test.cc
src/v/rpc/test/rpc_gen_cycling_test.cc
src/v/security/jwt.h
src/v/security/scram_authenticator.cc
src/v/serde/rw/inet_address.h
src/v/storage/compacted_index.h
src/v/storage/kvstore.cc
src/v/storage/tests/compaction_index_format_tests.cc
src/v/storage/tests/index_state_test.cc
src/v/storage/tests/log_segment_appender_test.cc
src/v/utils/vint.h

clang-18 (well, more specifically libc++18) is going to deprecate char_traits<T> for T not equal to char and some other types. This makes it difficult to use a ss::sstring-based bytes implementation because ss::sstring tries to interoperate with std::string and std::string_view, causing deprecation warnings which will turn into errors in clang-19.
so we'll need to build a replacement (or at least a wrapper). this PR simplifies some of the surface area of the `bytes` api to make the resulting wrapper a bit simpler.
* none

bytes: simplify surface area of `bytes` api

---

tests/rptest/redpanda_cloud_tests/high_throughput_test.py

Fixes #23061
Backport of PR #23040
Note LOC is less than in #23040 because `v23.3.x` contains less instances of the bad opv2 check.
* none

[v23.3.x] Fix cloud operator_v2 check

---

src/go/rpk/pkg/cli/cloud/login.go
src/go/rpk/pkg/cli/security/user/create.go
src/go/rpk/pkg/cli/security/user/delete.go
src/go/rpk/pkg/cli/security/user/list.go
src/go/rpk/pkg/cli/security/user/update.go
src/go/rpk/pkg/config/config.go

Backport of PR https://github.com/redpanda-data/redpanda/pull/23047

[v24.2.x] rpk: fix --no-profile and add cloud checks for `rpk security user` commands.

---

src/v/cloud_storage/cache_service.cc
src/v/cloud_storage/recursive_directory_walker.cc
src/v/cluster/archival/ntp_archiver_service.cc
src/v/cluster/cloud_metadata/offsets_recoverer.cc
src/v/cluster/cloud_metadata/uploader.cc
src/v/cluster/cluster_recovery_manager.cc
src/v/cluster/config_manager.cc
src/v/cluster/drain_manager.cc
src/v/cluster/feature_manager.cc
src/v/cluster/leader_router.h
src/v/cluster/partition_probe.cc
src/v/features/feature_table.cc
src/v/kafka/protocol/types.h
src/v/kafka/server/handlers/configs/config_utils.h
src/v/net/connection.cc
src/v/net/server.cc
src/v/raft/consensus.cc
src/v/redpanda/admin/server.cc
src/v/redpanda/admin/server.h
src/v/redpanda/admin/util.cc
src/v/redpanda/monitor_unsafe_log_flag.cc
src/v/storage/api.cc
src/v/storage/segment_utils.cc
src/v/test_utils/async.h

Clean up `catch` call sites throughout the codebase to use constant references.
* none

`misc`: `const&` exception catch clean-up 

---

src/v/pandaproxy/schema_registry/requests/post_subject_versions.h
tests/rptest/tests/schema_registry_test.py

In the absence of supporting these features, it's friendly to tolerate clients that explicitly set them to `null`, such as the latest DotNet client.
Fixes #23038
* Schema Registry: Tolerate `null` `metadata` and `ruleSet` when registering or querying a schema

[CORE-7039] schema_registry: Tolerate null metadata and ruleSet

---

tests/rptest/tests/mirror_maker_test.py

The `KgoVerifierProducer` expect topic to be present when starting. In Kafka that is used as a source cluster in the mirror maker setup test the topic information is propagated slowly. Added waiting for the topic to be discoverable before proceeding with the next steps in the test.
Fixes: CORE-1639
- none

tests: wait for topic to be present before starting producer

---

src/go/rpk/pkg/cli/cloud/login.go
src/go/rpk/pkg/cli/security/user/create.go
src/go/rpk/pkg/cli/security/user/delete.go
src/go/rpk/pkg/cli/security/user/list.go
src/go/rpk/pkg/cli/security/user/update.go
src/go/rpk/pkg/config/config.go

Backport of PR https://github.com/redpanda-data/redpanda/pull/23047

[v24.1.x] rpk: fix --no-profile and add cloud checks for `rpk security user` commands.

---

src/v/pandaproxy/schema_registry/requests/post_subject_versions.h
tests/rptest/tests/schema_registry_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23044
Fixes: https://github.com/redpanda-data/redpanda/issues/23077,

[v24.2.x] [CORE-7039] schema_registry: Tolerate null metadata and ruleSet

---

src/v/kafka/server/tests/CMakeLists.txt
src/v/kafka/server/tests/fetch_bench.cc

Allocates the partitions that are being fetched from to specific shards. This ensures that we're always measuring the same thing in the instruction counts.
Fixes [CORE-6907](https://redpandadata.atlassian.net/browse/CORE-6907)
* none
[CORE-6907]: https://redpandadata.atlassian.net/browse/CORE-6907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

kafka: allocate partitions to specific shards

---

bazel/thirdparty/krb5.BUILD

- **bazel/krb5: disable extra libraries**
- **bazel/krb5: support parallel compilation via flag**
* none

bazel: improve krb5 build

---

tests/rptest/services/cluster.py

Fix class instance check for raise_on_crash

---

src/v/raft/tests/raft_fixture.cc
src/v/raft/tests/raft_fixture.h

Added possibility co configure the election timeout and heartbeats in runtime when using `raft_test_fixture` 
- none

Made `raft_test_fixture` election timeout and `heartbeat_interval` runtime configurable

---

tests/rptest/services/admin_ops_fuzzer.py
tests/rptest/tests/random_node_operations_test.py

Change the `RandomNodeOperationsTest` upgrades handling. Previously, as
a result of membership changes during the test, it was perfectly possible
for the cluster to upgrade its cluster version while executing the test.
This might lead to a test failure as the node with previous version
wasn't able to rejoin the cluster.
Refactored the test to work with mixed versions in a way that the
majority of nodes is not upgraded throughout the test to prevent cluster
version from being updated. This way both new and old version Redpanda
nodes are able to join the cluster. Full upgrade is now executed at the
end of the test to validate if the cluster can be fully upgraded.
- none

Refactored upgrades executed in random node operations test

---

src/v/storage/BUILD
src/v/storage/batch_cache.cc
src/v/storage/batch_cache.h
src/v/storage/segment.cc

Clearing a `batch_cache` asynchronously to prevent reactor stalls when
stopping partition or closing a segment with lots of active cache
entries.
- none

Fixed reactor stalls occurring when clearing batch cache entries 

---

src/v/pandaproxy/schema_registry/avro.cc
src/v/pandaproxy/schema_registry/compatibility.cc
src/v/pandaproxy/schema_registry/protobuf.cc
src/v/pandaproxy/schema_registry/sharded_store.cc
src/v/pandaproxy/schema_registry/test/compatibility_avro.cc
src/v/pandaproxy/schema_registry/test/compatibility_common.h
src/v/pandaproxy/schema_registry/test/compatibility_protobuf.cc
tests/rptest/tests/schema_registry_test.py

This implements detailed compatibility checks for protobuf and avro in schema registry. This enabled the schema registry and rpk to surface more specific information about the cause of the incompatibility between a new schema and the existing schemas by pointing the user to the exact incompatibility. This PR aims only to change the error reporting behaviour of the check compatibility endpoint when the `?verbose=true` parameter is explicitly specified and does not change the rules of what schema pairs are (in)compatible.
This PR was cherry-picked and then adapted from @oleiman's earlier PR https://github.com/redpanda-data/redpanda/pull/18332.
Fixes https://redpandadata.atlassian.net/browse/CORE-6860
* none

CORE-6860 Schema Registry: add detailed verbose compatibility checks

---

src/v/iceberg/tests/manifest_serialization_test.cc

For reasons I don't fully understand (likely some flavor uninitialiezd data), the serialized Avro bytes have a bit of non-deterministic bytes in between the Avro header and records.
```
diff serialized_buf roundtrip_buf
255,256c255,256
<   00000fe0 | 22 3a 22 69 6e 74 22 7d  5d 7d 7d 5d 7d 00 23 ce  | ":"int"}]}}]}.#.
<   00000ff0 | dc 68 f6 a8 f1 4c ff 9b  6c fb 9e 11 8c 51 c8 01  | .h...L..l....Q..
---
>   00000fe0 | 22 3a 22 69 6e 74 22 7d  5d 7d 7d 5d 7d 00 2d 91  | ":"int"}]}}]}.-.
>   00000ff0 | 01 c3 65 57 53 38 21 39  28 ed cd a7 55 ab c8 01  | ..eWS8!9(...U...
```
Here, the ":"int"}]}}]}" is the end of the Avro header. I tried 0-initializing the buffers in avro_iobuf_ostream, but this didn't fix the issue.
Since the issue doesn't appear to affect serialization, I'm punting on …

iceberg/tests: deflake TestSerializeManifestData

---

src/v/storage/mvlog/entry.h
src/v/storage/offset_translator_state.cc
src/v/storage/segment_utils.h

storage: serde_fields for several structs

---

src/v/cluster/controller_snapshot.h
src/v/cluster/members_table.cc

Members table version is updated only when cluster membership is updated. The version must be included in the snapshot as it not always equal to the snapshot last applied offset.
This PR makes the `members_table::version` consistent across the nodes even if controller snapshot was applied. The version is exposed to end users in `/v1/brokers/cluster_view` endpoint.
Fixes: CORE-6783
- none

c/members_table: include members table version in the snapshot

---

src/v/redpanda/application.h

rp: serde_fields for application::crash_tracker_metadata

---

.github/workflows/release-rp-storage-tool.yml

Build and publish rp-storage-tool by using building the rp-storage-tool target of the test docker image; so that we don't duplicate things like the toolchain version, dependencies etc
builds:
* linux amd64
* linux arm64
Publishes on `push` to upstream `dev` and `v*` branches, and on tags
* none

ci/github: build and publish rp-storage-tool

---

src/v/pandaproxy/schema_registry/store.h
src/v/pandaproxy/schema_registry/test/CMakeLists.txt
src/v/pandaproxy/schema_registry/test/mt_sharded_store.cc

sharded_store's main purpose is to supply a consistent interface to an underlying (sharded) in-memory store. So to process a given request, it must first work out the home shard for the desired schema ID or subject, dispatching requests to that shard.
Recently, schema registry was refactored to store schema definitions as iobufs (rather than contiguous strings) to avoid large allocations. To avoid semantically unnecessary _copies_, get_schema_definition was implemented to return a iobuf share across a shard boundary. This is an unsafe operation, as the reference counting and deletion machinery of the underlying temporary buffers is totally unsynchronized. This is UB in principle (data race) and leads to memory access faults (UAF, etc.) in practice.
So this commit changes …

[CORE-7061] sr/store: Deep copy schema_def iobufs at the interface

---

src/v/pandaproxy/schema_registry/store.h
src/v/pandaproxy/schema_registry/test/CMakeLists.txt
src/v/pandaproxy/schema_registry/test/mt_sharded_store.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/23114

[v24.2.x] [CORE-7061] sr/store: Deep copy schema_def iobufs at the interface

---

src/v/iceberg/BUILD
src/v/iceberg/CMakeLists.txt
src/v/iceberg/manifest_list.h
src/v/iceberg/manifest_list_avro.cc
src/v/iceberg/manifest_list_avro.h
src/v/iceberg/tests/BUILD
src/v/iceberg/tests/manifest_serialization_test.cc

The avrogen::manifest_file is pretty difficult to operate on, on account
of Avro's codegen heavily using std::any and representing optional
values as unions. To manifest list operations easier (and to decouple
metadata from the Avro library) this introduces a manifest_list class
that uses simpler types to represent metadata.
Calls into the avrogen serialization of avrogen::manifest_files but with
the members of the non-avrogen manifest_files.
* none

iceberg: add non-codegened manifest_list implementation

---

src/v/cluster/tm_stm.cc
src/v/cluster/tm_stm.h
src/v/cluster/tx_gateway_frontend.cc
src/v/cluster/tx_gateway_frontend.h
tests/rptest/transactions/transactions_test.py

If transaction expires all the subsequent requests from the producer
with the same producer id should fail with `FENCED` error forcing
producer to bump the producer epoch and retry the request.
During the transactional coordinator refactoring this critical behavior
was missed. This way a producer wasn't able to learn about the expired
transactions.
- fixes not fencing subsequent producer requests after its transaction has been expired

Fixed producer fencing when transaction is expired

---

src/v/cluster/topic_configuration.h

Since we need a default constructor to keep serde happy.
This PR adds some default initializers to `cluster::topic_configuration` to avoid UB when the default constructor is used as in [this function](https://github.com/redpanda-data/redpanda/blob/f6958c8f59a37fc9f8503073779ae58634326caa/src/v/cluster/tests/serialization_rt_test.cc#L563-L570). We could/should adjust the test code to avoid this pattern, but precluding the invalid state at the struct definition is probably sufficient here.
* none

c/topic_config: Explicitly initialize non-class fields

---

src/go/rpk/pkg/cli/acl/user/create.go
src/go/rpk/pkg/cli/acl/user/delete.go
src/go/rpk/pkg/cli/acl/user/list.go
src/go/rpk/pkg/cli/acl/user/update.go
src/go/rpk/pkg/cli/cloud/login.go
src/go/rpk/pkg/config/config.go

Manual backport of https://github.com/redpanda-data/redpanda/pull/23047
Had to be done manually as in v23.3.x we didn't have the `security` command and `user` was under `acl`.
* none

[v23.3.x] rpk: fix --no-profile and add cloud checks for rpk security user commands.

---

src/v/redpanda/BUILD
src/v/storage/BUILD
src/v/storage/CMakeLists.txt
src/v/storage/chunk_cache.cc
src/v/storage/chunk_cache.h
src/v/storage/segment_appender_chunk.h
src/v/storage/tests/BUILD
src/v/storage/tests/appender_chunk_manipulations.cc

bazel: split out chunk cache into bazel library
* none

bazel: split out chunk cache into bazel library

---

src/go/rpk/pkg/tuners/iotune/data.go

This reverts commit https://github.com/redpanda-data/redpanda/commit/cb801c1acb76f5ff00236af595cb7205e881418b.
Io properties don't work as is for two reasons:
- We need to set the `duplex` flag otherwise reads massively affect
writes and vice versa
- The io-queue keeps the effective IOPS limit way below what the disk
can do (70 to 80%) which on disks with less IOPS can make quite the
difference
* none

Revert "iotune: Add ioprops for m7gd"

---

src/v/cluster/data_migrated_resources.cc
src/v/cluster/data_migration_backend.cc
src/v/cluster/data_migration_backend.h
src/v/cluster/data_migration_types.h
src/v/cluster/data_migration_worker.cc
src/v/cluster/data_migration_worker.h
src/v/cluster/metadata_cache.cc
src/v/cluster/metadata_cache.h
src/v/kafka/server/handlers/fetch.cc

- abort/retry topic-scoped work where needed
- promptly abort when delaying partition-scoped work retry, and the work is not needed any more
- implement migration cancellation
- block topic reads where needed
* none
* not sure TBH, this PR may be final apart from tests

Migrations infra part 6: cancelations, retries, blocking reads

---

src/v/pandaproxy/schema_registry/json.cc
src/v/pandaproxy/schema_registry/types.h
src/v/pandaproxy/schema_registry/validation.cc
tests/rptest/remote_scripts/python_librdkafka_serde_client.py
tests/rptest/tests/schema_registry_test.py

Support JSON for Schema ID Validation by implementing `get_record_name` for json
Fixes https://redpandadata.atlassian.net/browse/CORE-6665
* none

[CORE-6665] schema registry - json schema get_record_name

---

src/v/pandaproxy/schema_registry/avro.cc
src/v/pandaproxy/schema_registry/compatibility.cc
src/v/pandaproxy/schema_registry/protobuf.cc
src/v/pandaproxy/schema_registry/sharded_store.cc
src/v/pandaproxy/schema_registry/test/compatibility_avro.cc
src/v/pandaproxy/schema_registry/test/compatibility_common.h
src/v/pandaproxy/schema_registry/test/compatibility_protobuf.cc
tests/rptest/tests/schema_registry_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22958 
Fixes https://github.com/redpanda-data/redpanda/issues/23107
Fixes https://redpandadata.atlassian.net/browse/CORE-7073
Conflicts:
* False conflict around `proto_compatibility_result check_compatible(std::filesystem::path)` in https://github.com/redpanda-data/redpanda/pull/23110/commits/4520d587095343d3fbe2c76920354c7fdfd76209. The commits should be identical to the one being cherry-picked.

[v24.2.x] CORE-6860 Schema Registry: add detailed verbose compatibility checks

---

src/v/pandaproxy/schema_registry/avro.cc
src/v/pandaproxy/schema_registry/compatibility.cc
src/v/pandaproxy/schema_registry/protobuf.cc
src/v/pandaproxy/schema_registry/sharded_store.cc
src/v/pandaproxy/schema_registry/test/compatibility_avro.cc
src/v/pandaproxy/schema_registry/test/compatibility_common.h
src/v/pandaproxy/schema_registry/test/compatibility_protobuf.cc
tests/rptest/tests/schema_registry_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22958 
Fixes https://github.com/redpanda-data/redpanda/issues/23108
Fixes https://redpandadata.atlassian.net/browse/CORE-7075
Conflicts:
* False conflict around `proto_compatibility_result check_compatible(std::filesystem::path)` in https://github.com/redpanda-data/redpanda/pull/23170/commits/352cdd1f1a067a30142059916489317dc7289a0e. The commits should be identical to the one being cherry-picked.

[v23.3.x] CORE-6860 Schema Registry: add detailed verbose compatibility checks

---

src/v/pandaproxy/schema_registry/json.cc
src/v/pandaproxy/schema_registry/test/test_json_schema.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/23101

[v24.2.x] [CORE-7037] schema registry json schema: fixes for some compatiblity bugs

---

src/v/pandaproxy/schema_registry/avro.cc
src/v/pandaproxy/schema_registry/compatibility.cc
src/v/pandaproxy/schema_registry/protobuf.cc
src/v/pandaproxy/schema_registry/sharded_store.cc
src/v/pandaproxy/schema_registry/test/compatibility_avro.cc
src/v/pandaproxy/schema_registry/test/compatibility_common.h
src/v/pandaproxy/schema_registry/test/compatibility_protobuf.cc
tests/rptest/tests/schema_registry_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22958 
Fixes https://github.com/redpanda-data/redpanda/issues/23109
Fixes https://redpandadata.atlassian.net/browse/CORE-7074
Conflicts:
* False conflict around `proto_compatibility_result check_compatible(std::filesystem::path)` in https://github.com/redpanda-data/redpanda/pull/23169/commits/340f58b905703d87cc61b166ce9af084b502044e. The commits should be identical to the one being cherry-picked.

[v24.1.x] CORE-6860 Schema Registry: add detailed verbose compatibility checks

---

src/v/pandaproxy/schema_registry/store.h
src/v/pandaproxy/schema_registry/test/CMakeLists.txt
src/v/pandaproxy/schema_registry/test/mt_sharded_store.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/23114

[v23.3.x] [CORE-7061] sr/store: Deep copy schema_def iobufs at the interface

---

src/v/cluster/tm_stm.cc

c/tm_stm: fix log format strings

---

src/v/datalake/CMakeLists.txt
src/v/datalake/arrow_schema_translator.cc
src/v/datalake/arrow_schema_translator.h
src/v/datalake/tests/CMakeLists.txt
src/v/datalake/tests/arrow_writer_test.cc
src/v/datalake/tests/test_data_writer.h

This is the first part of the Arrow writer that will translate abstract
Iceberg types (iceberg::field_type and iceberg::value) to the Arrow and
ultimately Parquet data. This PR adds schema translation that creates an
Arrow schema from the Iceberg types.
* none

datalake: iceberg to arrow schema translation

---

MODULE.bazel.lock
bazel/repositories.bzl

crypto: upgrade to openssl 3.0.15
* none

crypto: upgrade to openssl 3.0.15

---

src/v/cluster/tm_stm.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/23173

[v24.2.x] c/tm_stm: fix log format strings

---

bazel/test.bzl
src/v/iceberg/tests/BUILD
src/v/iceberg/tests/manifest_serialization_test.cc
src/v/test_utils/BUILD
src/v/test_utils/CMakeLists.txt
src/v/test_utils/runfiles.cc
src/v/test_utils/runfiles.h

Fixes bazel test for iceberg and adds helper for getting data into tests.
* none

iceberg: fix bazel test

---

src/v/cluster/archival/archiver_operations_impl.cc
src/v/cluster/archival/tests/archiver_operations_impl_gtest.cc

Pull-requests in a series:
- https://github.com/redpanda-data/redpanda/pull/21309
This PR implements `schedule_uploads` and `admit_uploads` methods. The `schedule_uploads` method accepts the result of the `find_upload_candidates` which contains a series of candidates. It uploads the series of segments with the index and tx manifest.  The method can also upload the manifest concurrently with the segments. The result contains the metadata of the uploaded segments, the upload results and the record-level stats from every upload which is used for validation in the `admit_uploads` method.
The `admit_uploads` accepts the output of the `schedule_uploads` and validates it by comparing metadata of the uploaded segment with its record-level stats. After that it check if the metadata can be safely …

archival: Update ntp_archiver (pt.2)

---

tests/rptest/scale_tests/tiered_storage_cache_stress_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23006
Fixes: https://github.com/redpanda-data/redpanda/issues/23178,

[v24.1.x] rptest: reduce cache eviction throttling for tiny cache stress test

---

src/v/kafka/server/group_manager.cc

`group_manager::attached_partition::catchup_lock` can get blocked for extended periods of time. For example in the following scenario:
1. consumer_offsets partition leader gets isolated
2. some group operation acquires a read lock and tries to replicate a batch to the consumer_offsets partition. This operation hangs for an indefinite period of time.
3. the consumer_offsets leader steps down
4. group state cleanup gets triggered, tries to acquire a write lock, hangs until (2) finishes
Meanwhile, clients trying to perform any tx group operations will get a coordinator_load_in_progress errors and blindly retry, without even trying to find the real coordinator.
Check for leadership without the read lock first to prevent that (this is basically a "double-check" pattern as we have to check the …

k/group_manager: return not_coordinator quickly in tx operations

---

tests/rptest/services/redpanda.py
tests/rptest/tests/shard_placement_test.py

When the test is run on dedicated nodes, client workload can produce substantial amout of data and 60 seconds is not enough for the rebalance triggered by node addition to finish.
Increase the timeout if the test runs on dedicated nodes.
Fixes https://redpandadata.atlassian.net/browse/CORE-6779
* none

tests/shard_placement_test: increase node rebalance timeout

---

src/v/kafka/utils/BUILD
src/v/kafka/utils/tests/txn_reader_test.cc
src/v/kafka/utils/txn_reader.cc
src/v/kafka/utils/txn_reader.h

kafka: clean up txn_reader dependencies
* none

kafka: clean up txn_reader dependencies

---

tests/rptest/remote_scripts/compute_storage.py

There are cases where compute_storage.py reads a batch header with some fields > 0 (mostly CRC) while all other fields, especially the batch size is 0. In such cases the record size is computed to -61, which when passed to the python read function reads the entire file.
It is possible that this header is read in this way because it is being written to while the file is parsed. There are two supporting pieces of evidence:
* The same segment, parsed by the same script, after the test finishes, does not show any errors. The header where previously failure was seen has all non zero, consistent fields now including batch sizes.
* The CRC matches both when the rest of the fields are 0 and in the final version of the segment, in both cases it is non zero.
Header when the script fails:
``` …
```

[CORE-7010] ducktape: adapt segment parsing for partial batch headers

---

tests/rptest/tests/rbac_upgrade_test.py
tests/rptest/tests/redpanda_oauth_test.py
tests/rptest/tests/schema_registry_test.py

Similar to https://github.com/redpanda-data/redpanda/pull/21350. Ignore all of the license nag tests in FIPS mode because the license nag always shows up due to running in FIPS mode.
Fixes https://redpandadata.atlassian.net/browse/CORE-6952
Fixes https://redpandadata.atlassian.net/browse/CORE-6953
* none

dt: skip license nag tests in fips mode

---

src/v/kafka/server/group_manager.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/23176

[v24.2.x] k/group_manager: return not_coordinator quickly in tx operations

---

src/v/serde/test/bench.cc
src/v/serde/test/serde_test.cc
src/v/serde/test/struct_gen.py

serde/test: serde_fields for various structs

---

bazel/test.bzl
src/v/test_utils/BUILD
src/v/test_utils/test.h
src/v/test_utils/tests/BUILD
src/v/utils/BUILD
src/v/utils/CMakeLists.txt
src/v/utils/external_process.cc
src/v/utils/external_process.h
src/v/utils/tests/BUILD
src/v/utils/tests/CMakeLists.txt
src/v/utils/tests/external_process_test.cc
src/v/utils/tests/handle-sigterm.sh

Created an "external_process" class that wraps around Seastar's process utility.  It provides methods to assign stdout and stderr consumers as well as the ability to automate the termination of the child process.
* None

utils: Added external_process library

---

src/v/kafka/server/group_manager.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/23176

[v24.1.x] k/group_manager: return not_coordinator quickly in tx operations

---

src/v/kafka/server/group_manager.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/23176

[v23.3.x] k/group_manager: return not_coordinator quickly in tx operations

---

src/v/kafka/server/partition_proxy.cc
src/v/kafka/server/partition_proxy.h

I may have a non-null partition pointer that I want to wrap.
* none

kafka: add proxy factory for partition in hand

---

src/v/storage/disk_log_impl.cc
src/v/storage/disk_log_impl.h
src/v/storage/segment_deduplication_utils.cc
src/v/storage/segment_utils.cc
src/v/storage/segment_utils.h

A small number of mostly non-functional changes to help clean-up compaction utilities ahead of improvements made with tombstone removal.
The changes are enumerated here:
1. Changes to log messages in compaction related functions.
2. Refactoring of repeated code into new function, `do_compact_adjacent_segments()`.
3. Improved code comments around various compaction related functions.
4. Refactoring of repeated code into new function, `maybe_rebuild_compaction_index()`.
* none

`storage`: compaction utils cleanup

---

src/v/cluster/tests/topic_table_test.cc
src/v/cluster/topic_table.cc

We check that the updated topic properties post `topic_table::apply(update_topic_properties_cmd)` is valid with the `schema_id_validation_validator`. However, this early `co_return` with an error code does not actually prevent the invalid configuration from being persisted in the `topic_table`.
Rework the logic in `topic_table::apply()` to prevent persisting of an invalid configuration.
* Fixes a bug that resulted in persisting an invalid `topic_properties` configuration in the `topic_table`.

`cluster`: don't apply invalid property change in `topic_table`

---

src/v/iceberg/partition_key.cc
src/v/iceberg/partition_key.h
src/v/iceberg/tests/partition_key_test.cc
src/v/iceberg/tests/values_test.cc
src/v/iceberg/values.cc
src/v/iceberg/values.h

I have some upcoming changes to serialize partition keys. To that end, it's helpful to be able to copy a partition key, so serialization doesn't move away the contents.
Partition keys themselves are comprised of primitive values, so this introduces a copy method for primitive values. I opted to not implement the same for complex types, since I'm unsure they will be useful.
* none

iceberg: copy method for partition key

---

bazel/thirdparty/krb5.BUILD
bazel/thirdparty/openssl.BUILD

Happy to bikeshed the values here.
* none

bazel: bump configure_make default parallelism

---

.github/labeler.yml

This will let folks concerned about the build quickly filter PRs that are modifying the build system in Bazel.
* none

gha: add build labels for bazel

---

tests/rptest/tests/rbac_test.py

Deflake `RolePersistenceTest.test_role_survives_restart` by waiting for a healthy cluster after the nodes have been restarted. Otherwise, the later `create_role` request may fail. See the example failure in the attached ticket.
Fixes https://redpandadata.atlassian.net/browse/CORE-7049
* none

CORE-7049 dt/rbac: wait for healthy cluster after restart

---

src/v/config/configuration.cc

This property should have been marked with needing a restart, since `redpanda` only attempts to construct archival/tiered storage related objects upon start-up, when it first checks this cluster property.
Correct the property by marking it as `needs_restart::yes`.
* none

`config`: mark `cloud_storage_enabled()` as `needs_restart::yes`

---

tests/rptest/tests/rbac_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23217

[v24.2.x] CORE-7049 dt/rbac: wait for healthy cluster after restart

---

src/v/cluster/controller_snapshot.h
src/v/cluster/members_table.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/23097

[v24.2.x] c/members_table: include members table version in the snapshot

---

tests/rptest/tests/test_si_cache_space_leak.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22796
Fixes: https://github.com/redpanda-data/redpanda/issues/23205,

[v24.2.x] rptest: reduce cache eviction throttling for space leak test

---

src/v/config/configuration.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/23224

[v24.2.x] `config`: mark `cloud_storage_enabled()` as `needs_restart::yes`

---

src/v/kafka/server/handlers/alter_configs.cc
src/v/kafka/server/handlers/configs/config_response_utils.cc
src/v/kafka/server/handlers/topics/types.cc
src/v/utils/tristate.h

Some minor things I came across in the `kafka` and `tristate` subsystems that I thought could be improved for the reader.
* none

`kafka`: misc non-functional changes

---

tests/rptest/tests/rbac_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23217

[v24.1.x] CORE-7049 dt/rbac: wait for healthy cluster after restart

---

src/v/config/configuration.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/23224

[v24.1.x] `config`: mark `cloud_storage_enabled()` as `needs_restart::yes`

---

src/v/cluster/controller_snapshot.h
src/v/cluster/members_table.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/23097

[v24.1.x] c/members_table: include members table version in the snapshot

---

src/v/cloud_io/io_result.cc
src/v/cloud_io/io_result.h
src/v/cloud_io/remote.cc
src/v/cloud_io/remote.h
src/v/cloud_storage/inventory/types.h
src/v/cloud_storage/types.h

Follow-up to https://github.com/redpanda-data/redpanda/pull/23194
I didn't do this originally because I didn't want to update a ton of code via s/cloud_storage::upload_result/cloud_io::upload_result. But instead this just adds a using declaration for cloud_storage, and moves the result types into the cloud_io namespace.
* none

cloud_io: put io_result in cloud_io namespace

---

src/v/cluster/tests/topic_table_test.cc
src/v/cluster/topic_table.cc

Manual backport of https://github.com/redpanda-data/redpanda/pull/23191. Merge conflict due to other unrelated migration additions in `topic_table.cc`.
Closes https://github.com/redpanda-data/redpanda/issues/23221.
* Fixes a bug that resulted in persisting an invalid `topic_properties` configuration in the `topic_table`.

[v24.1.x] `cluster`: don't apply invalid property change in `topic_table` (Manual backport)

---

src/v/cluster/tests/topic_table_test.cc
src/v/cluster/topic_table.cc

Manual backport of https://github.com/redpanda-data/redpanda/pull/23191. Merge conflict due to other unrelated migration additions in `topic_table.cc`.
Closes https://github.com/redpanda-data/redpanda/issues/23222.
* Fixes a bug that resulted in persisting an invalid `topic_properties` configuration in the `topic_table`.

[v23.3.x] `cluster`: don't apply invalid property change in `topic_table` (Manual backport)

---

src/v/config/rjson_serialization.cc
src/v/config/tests/tls_config_convert_test.cc
src/v/config/tls_config.cc
src/v/config/tls_config.h
tests/rptest/services/redpanda.py
tests/rptest/services/tls.py
tests/rptest/tests/pkcs12_test.py

Adds support for using PKCS#12 files in our TLS node config.
* Added support for using PKCS#12 files for TLS services

CORE-3168 support p12

---

tests/rptest/scale_tests/large_messages_test.py

Implement series of tests to ensure RP can process large message sizes: from 1MB to 20MB
Measure effective processing bandwidth.
* none

PESDLC-766 Test large message sizes

---

src/v/cloud_storage/inventory/inv_consumer.cc
src/v/cloud_storage/inventory/tests/inv_consumer_tests.cc

This PR contains two minor fixes for issues found during scrubber integration:
1. fix  an unchecked optional access in inv. consumer
2. allow uuid prefixes to segment paths
* none

cst/inv: Minor fixes for issues found during scrubber integration

---

src/v/config/configuration.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/23224

[v23.3.x] `config`: mark `cloud_storage_enabled()` as `needs_restart::yes`

---

tests/rptest/tests/shard_placement_test.py

When we wait for consistency between shard maps queried using the /cluster/partitions admin API endpoint and the /partitions endpoint on nodes themselves, we need to query for both shard maps at approximately the same time (and not use the one queried in the beginning) because it may change in the process of waiting.
This is the second attempt at fixing https://redpandadata.atlassian.net/browse/CORE-6851
* none

tests/shard_placement: fix waiting for shard map consistency

---

src/v/model/record_batch_reader.cc
src/v/model/record_batch_reader.h
src/v/model/tests/BUILD
src/v/model/tests/record_batch_reader_test.cc

model: add empty batch reader factory
sometimes ya just empty
* none

model: add empty batch reader factory

---

src/v/cluster/archival/archival_policy.cc

In searching for an upload candidate for offset N, we previously allow the archival_policy to return a segment that contained N, but whose committed offset was N-1, e.g. because the segment was the active segment and offset N is still dirty from a storage perspective.
This would previously result in an ERROR log when trying to find N in the segment.
Example:
```
DEBUG 2024-09-09 23:49:47,757 [shard 4:au  ] archival - archival_policy.cc:176 - Upload policy for {kafka/topic-mbxgxbewtz/18} invoked, start offset: 7042
DEBUG 2024-09-09 23:49:47,757 [shard 4:au  ] archival - archival_policy.cc:466 - Upload policy for {kafka/topic-mbxgxbewtz/18}, creating upload candidate: start_offset 7042, segment offsets {term:1, base_offset:4006, committed_offset:7041, dirty_offset:7042}, adjusted LSO 7041 …
```

archival_policy: skip if no data at desired start_offset

---

.bazelrc
MODULE.bazel
MODULE.bazel.lock
bazel/toolchains_llvm_pr_346.patch

This seems more explicit about what has changed from upstream. Also from Michal's original PR
has changed based on some feedback, so update our build to match the feedback.
Hopefully this goes away soon.
* none

bazel: use patch instead of fork of toolchains_llvm

---

src/go/rpk/pkg/cli/cloud/byoc/uninstall.go
src/go/rpk/pkg/cli/connect/client.go
src/go/rpk/pkg/cli/connect/connect.go
src/go/rpk/pkg/cli/connect/install.go
src/go/rpk/pkg/cli/connect/uninstall.go
src/go/rpk/pkg/cli/connect/upgrade.go
src/go/rpk/pkg/cli/root.go
src/go/rpk/pkg/cobraext/cobraext.go
src/go/rpk/pkg/cobraext/cobraext_test.go
src/go/rpk/pkg/httpapi/httpapi.go
src/go/rpk/pkg/plugin/plugin.go
tests/rptest/clients/rpk.py
tests/rptest/tests/rpk_connect_test.py

This PR introduces the required changes to have `rpk connect` as a managed plugin. The main behavior change is that from now on, rpk will try to download `connect` when running for the first time, similar to what we do with `rpk cloud byoc`.
It also introduces 3 new commands to rpk connect: `install`, `uninstall`, `upgrade`.
Fixes https://github.com/redpanda-data/devex/issues/45
```
$ rpk connect run /config.yaml
```
^ That's it, it will download the connect plugin on the fly and then execute the command. 
rpk won't update connect automatically unless you run rpk connect upgrade.
```
$ rpk connect install
```
```
$ rpk connect install --conect-version
```
```
$ rpk connect uninstall
$ rpk connect install --connect-version  <version>
$ rpk connect install --connect version <version> …
```

[ENG-121] rpk: add `rpk connect` as a managed plugin

---

tests/rptest/tests/audit_log_test.py

OAuth has a background loop that polls the OIDC discovery service (configured via the cluster config `oidc_discovery_url`) for updates. This background loop starts as soon as OAuth is enabled via the `sasl_mechanisms` and `http_authentication` cluster configs. `oidc_discovery_url` has a default value pointing to a Redpanda-hosted OIDC configuration. However, we should not rely on this Redpanda-hosted default OIDC endpoint in our tests and CI because it might be temporarily unavailable and cause the tests to be flaky.
To fix this test being flaky, we only enable OAuth once the local keycloak server is up and available to serve the OIDC discovery endpoint.
Without this fix, we might get the following error in the redpanda brokers' logs when the broker fails to poll the Redpanda-provided …

CORE-6896 dt/audit: enable oauth after keycloak is up

---

MODULE.bazel.lock
bazel/repositories.bzl
bazel/thirdparty/seastar-fortify-source.patch

It causes problems with longjmp
*** longjmp causes uninitialized stack frame ***: terminated
Aborting on shard 0.
Backtrace:
which was taken care of in the cmake build, but needs to be fixed in our bazel build. reference: https://github.com/scylladb/seastar/pull/2344
* none

bazel: do not use fortify source in seastar thread.cc

---

.bazelignore
BUILD

- **bazel: exclude vtools from gazelle**
- **bazel: ignore vtools**
* none

bazel: exclude vtools

---

src/v/kafka/server/connection_context.cc
src/v/kafka/server/server.cc
src/v/security/audit/audit_log_manager.cc
tests/rptest/tests/audit_log_test.py

The connection_context::start method enqueues the connect_context instance into the list of connections.  If connection_context::stop is called before the item is inserted, then a segfault will happen.
Fixes: CORE-7245
* Fixed a segfault that will occur if mTLS is in use and the auditing client is not configured correctly

kafka: Fixed segfault issue with auditing and mTLS

---

src/v/kafka/server/handlers/describe_log_dirs.cc

Replaced:
* std::vector -> chunked_vector
* absl::flat_hash_map -> chunked_hash_map
* Fixed possible oversized alloc in the DescribeLogsDir API handler

kafka: Fixed oversized alloc in describe_log_dirs

---

tools/docker/bazel.dockerfile

sysctl is used by CI to bump up max-aio-nr.
* none

bazel: add sysctl to bazel dockerfile

---

src/v/redpanda/CMakeLists.txt
src/v/redpanda/admin/api-doc/migration.def.json
src/v/redpanda/admin/api-doc/migration.json
src/v/redpanda/admin/data_migration_utils.cc
src/v/redpanda/admin/data_migration_utils.h
src/v/redpanda/admin/migrations.cc
src/v/redpanda/admin/server.cc
src/v/redpanda/admin/server.h
src/v/redpanda/admin/topics.cc

backport #23167 (High level topic mount/unmount APIs)
* New REST API for mounting/unmounting topics

Backport pr #23167 to v24.2.x

---

tests/rptest/services/redpanda.py

We want to disable scrubber in a few tests (e.g. specific scale tests, tests without a working cloud storage connection). This worked correctly until we decided to disable it by default but still wanted to keep it enabled in tests
(https://github.com/redpanda-data/redpanda/commit/6a7ff550ce0d1a629cddbf952b24671b9d4a27ce). I forgot to consider the fact that some tests want it disabled anyway.
Update the code so that scrubber is enabled only if not explicitly disabled.
* none

rptest: Enable scrubber only if not explicitly disabled

---

src/v/pandaproxy/schema_registry/compatibility.cc
src/v/pandaproxy/schema_registry/compatibility.h
src/v/pandaproxy/schema_registry/json.cc
src/v/pandaproxy/schema_registry/test/test_json_schema.cc
src/v/pandaproxy/schema_registry/types.cc
src/v/pandaproxy/schema_registry/types.h
tests/rptest/tests/schema_registry_test.py

This implements verbose compatibility reporting for json schema registry. This has already been implemented for Protobuf and Avro, and with this patch it is going to be supported for json as well.
This PR only changes what error message is being reported when there is an incompatibility but the logic of "what sets of schemas are considered compatible" is intended to be unchanged. The changes start with a few commits that introduce helpers and do non-logic-changing refactoring to make the main commit (https://github.com/redpanda-data/redpanda/commit/47d543b8427721118c84c72015dc837d112a2e69) easier to review. While the main commit is large, the changes in it are trivial, most of its complexity lies in verifying that the reported compatibility error type matches the reference implementation. …

CORE-6861 Schema Registry: verbose compat checks for JSON

---

src/v/kafka/server/handlers/describe_log_dirs.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/23279

[v24.1.x] kafka: Fixed oversized alloc in describe_log_dirs

---

src/v/kafka/server/connection_context.cc
src/v/kafka/server/server.cc
src/v/security/audit/audit_log_manager.cc
tests/rptest/tests/audit_log_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23245

[v24.1.x] kafka: Fixed segfault issue with auditing and mTLS

---

tests/rptest/services/redpanda.py

`get_cloud_provider` relies on the environment variable `CLOUD_PROVIDER`
to be set. This doesn't get automatically set in a standard duck.py
setup.
Hence, rather rely on the cloud provider specified in the `global.json`
which does get correctly setup by duck.py/ansible.
* none

tests: Fix cloud tests provider selection

---

src/v/pandaproxy/schema_registry/compatibility.cc
src/v/pandaproxy/schema_registry/compatibility.h
src/v/pandaproxy/schema_registry/json.cc
src/v/pandaproxy/schema_registry/test/test_json_schema.cc
src/v/pandaproxy/schema_registry/types.cc
src/v/pandaproxy/schema_registry/types.h
tests/rptest/tests/schema_registry_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23208

[v24.2.x] CORE-6861 Schema Registry: verbose compat checks for JSON

---

tests/rptest/tests/audit_log_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23260

[v24.2.x] CORE-6896 dt/audit: enable oauth after keycloak is up

---

tests/rptest/tests/audit_log_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23260

[v24.1.x] CORE-6896 dt/audit: enable oauth after keycloak is up

---

tests/rptest/tests/cluster_self_config_test.py

OCI only supports path style requests, meaning FIPS mode will always fail for the oracle backend.
* none

[CORE-6970] `rptest`: mark `test_s3_oracle_self_config` as `ok_to_fail_fips`

---

.github/workflows/release-rp-storage-tool.yml

Since this runs on every push to the target branches, it is incurring excessive CI minutes usage. Only release on tagged commits to reduce consumption. Also, for the arm variant, use 2-core VMs.
fixes https://redpandadata.atlassian.net/browse/PESDLC-2053
* none

gha: reduce execution frequency (on cheap runner)

---

tests/rptest/tests/cluster_self_config_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23300

[v24.2.x] [CORE-6970] `rptest`: mark `test_s3_oracle_self_config` as `ok_to_fail_fips`

---

src/go/rpk/pkg/plugin/plugin.go
tests/rptest/clients/rpk.py

Increased the timeout to 60, we still have room
to grow here since rpk's timeout is 240.
* none

test: increase rpk connect timeout

---

tools/BUILD
tools/clang_format.sh

This adds a command to run clang-format using the version from our bazel
toolchain.
* none

bazel: add clang-format command

---

src/v/container/contiguous_range_map.h
src/v/kafka/server/tests/fetch_test.cc

Since 24.2.x this was triggering an assert. Added a regression test.
Fixes https://github.com/redpanda-data/redpanda/issues/23296
* Fixes crash when consuming from topic partitions with negative indexes

kafka: fix fetching from partitions with negative indexes

---

src/v/kafka/server/handlers/describe_log_dirs.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/23279

[v23.3.x] kafka: Fixed oversized alloc in describe_log_dirs

---

src/v/kafka/server/connection_context.cc
src/v/kafka/server/server.cc
src/v/security/audit/audit_log_manager.cc
tests/rptest/tests/audit_log_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23245

[v23.3.x] kafka: Fixed segfault issue with auditing and mTLS

---

src/v/cluster/topic_configuration.cc
src/v/cluster/topic_configuration.h
src/v/model/transform.cc
src/v/model/transform.h
src/v/serde/rw/envelope.h

If a serde envelope implements either serde_read or serde_write, that envelope may not implement serde_fields.
PR also updates a couple of existing structs to account for this requirement.
* none

serde: Require (serde_fields) XOR (explicit read and/or write)

---

tests/rptest/redpanda_cloud_tests/high_throughput_test.py

Only waiting for 10k messages isn't that much. It's only a few seconds
even on smaller tiers so not really enough time to warm up.
Increase the msg count to hopefully make this less flaky.
Ref CORE-7083
* none

tests: Increase warm msg count in cloud high throughput tests

---

bazel/test.bzl

Without this flag core affinity on lower numbers CPUs would be oversubscribed by seastar. Additionally this flag does some other stuff like disables polling.
* none

bazel: run tests with --overprovisioned

---

tests/rptest/services/redpanda.py
tests/rptest/tests/cluster_self_config_test.py
tests/rptest/tests/redpanda_startup_test.py
tests/rptest/utils/mode_checks.py

For use in ducktape tests that should not be ran in a FIPS-enabled environment (i.e, tests that are always expected to fail due to incompatibilities if FIPS mode is enabled).
Existing tests may still make use of `@ok_to_fail_fips`, but `@skip_fips_mode` offers the ability to not waste CI time on tests that will always fail with FIPS enabled (such as `test_s3_oracle_self_config`, which now makes use of the decorator).
Requested by https://github.com/redpanda-data/redpanda/pull/23300#discussion_r1761050385
* none

`rptest`: add `@skip_fips_mode` decorator

---

src/v/features/feature_table.cc

Bumped `cluster_version` for the next `v24.3.1` major release.
- none

features: bumped cluster version for next major release

---

.git-blame-ignore-revs

chore: add git blame ignore file
* none

chore: add git blame ignore file

---

.git-blame-ignore-revs

Add commit https://github.com/redpanda-data/redpanda/pull/23073/commits/0b64b2c3f7dd62a3770dbca42c11b3e92f71297e from pull request https://github.com/redpanda-data/redpanda/pull/23073 to our `.git-blame-ignore-revs` file.
* none

`dotfiles`: add format commit to `.git-blame-ignore-revs`

---

src/v/serde/CMakeLists.txt
src/v/serde/protobuf/CMakeLists.txt

I initially built this in Bazel only and forgot to add a CMake build so
it's actually usable.
* none

cmake: add serde/protobuf to cmake

---

src/v/cluster/data_migration_backend.h
src/v/cluster/distributed_kv_stm.h
src/v/storage/tests/backlog_controller_test.cc
src/v/utils/stable_iterator_adaptor.h
src/v/utils/tristate.h

chore: remove extra semi-colons
* none

chore: remove extra semi-colons

---

src/go/rpk/pkg/cli/connect/BUILD

bazel: add missing connect dep

---

src/v/cloud_storage/cache_service.cc
src/v/cloud_storage/cache_service.h
src/v/redpanda/admin/server.cc
tests/rptest/tests/cluster_config_test.py

To prevent the invalid configuration of `cloud_storage_cache_size` and `cloud_storage_cache_size_percent` both being equal to `0`, add a new check to the `admin` server validation post `patch_cluster_config_handler()` call.
The following configurations are hereby invalid:
1. `cloud_storage_cache_size` and `cloud_storage_cache_size_percent` cannot both be 0
2. `cloud_storage_cache_size` cannot be `0` while `cloud_storage_cache_size_percent` is `nil` (`std::nullopt`)
Relevant slack thread: https://redpandadata.slack.com/archives/C02BDN76HUK/p1724373318548299
Relevant docs PR: https://github.com/redpanda-data/docs/pull/696#discussion_r1761590425
Backports to versions `v24.1.x` and `v24.2.x` are optional and left to the reviewers to decide if necessary.
* none

`admin`: add `cloud_storage_cache_size` check to `config_multi_property_validation()`

---

tools/BUILD

See: https://bazel.build/reference/be/common-definitions#common-attributes
* none

bazel: mark clang-format as a manual target

---

src/v/cluster/BUILD
src/v/cluster/CMakeLists.txt
src/v/cluster/feature_manager.cc
src/v/cluster/feature_manager.h
src/v/features/BUILD
src/v/features/CMakeLists.txt
src/v/features/enterprise_features.cc
src/v/features/enterprise_features.h
src/v/redpanda/admin/BUILD
src/v/redpanda/admin/api-doc/features.json
src/v/redpanda/admin/server.cc
src/v/redpanda/admin/server.h
tests/rptest/services/admin.py
tests/rptest/tests/enterprise_features_license_test.py

This PR introduces an Admin API endpoint to expose
- Whether or not each enterprise licensed feature is enabled
- The current license status of the cluster (valid, expired, or not present)
- Whether the current set of enabled enterprise features violates the license
- i.e. violation = (any enterprise feature enabled) AND (license status != valid)
Includes integration tests for the endpoint and a "feature report" representation for config state.
Fixes CORE-7152
* Adds admin API endpoint for enterprise feature info `GET /v1/features/enterprise`

[CORE-7152] Admin: Introduce `GET /v1/features/enterprise` endpoint

---

src/go/rpk/pkg/cli/cloud/byoc/uninstall.go
src/go/rpk/pkg/cli/connect/client.go
src/go/rpk/pkg/cli/connect/connect.go
src/go/rpk/pkg/cli/connect/install.go
src/go/rpk/pkg/cli/connect/uninstall.go
src/go/rpk/pkg/cli/connect/upgrade.go
src/go/rpk/pkg/cli/redpanda/admin/brokers/decommission.go
src/go/rpk/pkg/cli/root.go
src/go/rpk/pkg/cobraext/cobraext.go
src/go/rpk/pkg/cobraext/cobraext_test.go
src/go/rpk/pkg/httpapi/httpapi.go
src/go/rpk/pkg/plugin/plugin.go
src/go/rpk/pkg/redpanda/version.go
src/go/rpk/pkg/redpanda/version_test.go
tests/rptest/clients/rpk.py
tests/rptest/tests/rpk_connect_test.py

This is a manual backport of all the PRs that makes the feature `rpk connect` as a managed plugin:
- https://github.com/redpanda-data/redpanda/pull/23117 - Main PR.
- https://github.com/redpanda-data/redpanda/pull/23305 - Ducktape Test timeout increase.
- https://github.com/redpanda-data/redpanda/pull/23336 - UX improvements after UAT.
- 
- `rpk connect` now will be downloaded on the first run.
- rpk: introduce rpk connect install, rpk connect upgrade, and rpk connect uninstall, manual ways to manage rpk connect versioning.

[v24.1.x] rpk connect as a managed plugin

---

src/go/rpk/pkg/cli/cloud/byoc/uninstall.go
src/go/rpk/pkg/cli/connect/client.go
src/go/rpk/pkg/cli/connect/connect.go
src/go/rpk/pkg/cli/connect/install.go
src/go/rpk/pkg/cli/connect/uninstall.go
src/go/rpk/pkg/cli/connect/upgrade.go
src/go/rpk/pkg/cli/redpanda/admin/brokers/decommission.go
src/go/rpk/pkg/cli/root.go
src/go/rpk/pkg/cobraext/cobraext.go
src/go/rpk/pkg/cobraext/cobraext_test.go
src/go/rpk/pkg/httpapi/httpapi.go
src/go/rpk/pkg/plugin/plugin.go
src/go/rpk/pkg/redpanda/version.go
src/go/rpk/pkg/redpanda/version_test.go
tests/rptest/clients/rpk.py
tests/rptest/tests/rpk_connect_test.py

This is a manual backport of all the PRs that makes the feature `rpk connect` as a managed plugin:
- https://github.com/redpanda-data/redpanda/pull/23117 - Main PR.
- https://github.com/redpanda-data/redpanda/pull/23305 - Ducktape Test timeout increase.
- https://github.com/redpanda-data/redpanda/pull/23336 - UX improvements after UAT.
- 
- `rpk connect` now will be downloaded on the first run.
- rpk: introduce rpk connect install, rpk connect upgrade, and rpk connect uninstall, manual ways to manage rpk connect versioning.

[v24.2.x] rpk connect as a managed plugin

---

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
tests/rptest/redpanda_cloud_tests/omb_validation_test.py

Some minor fixes:
- Change connection count fudge factor, it's like 1% off
- Make the high throughput tests handle smaller segment sizes
* none

Minor cloud test fixes for tiers v3

---

src/v/cloud_storage/cache_service.cc
src/v/cloud_storage/cache_service.h
src/v/redpanda/admin/server.cc
tests/rptest/tests/cluster_config_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23337

[v24.2.x] `admin`: add `cloud_storage_cache_size` check to `config_multi_property_validation()`

---

src/v/cloud_storage/cache_service.cc
src/v/cloud_storage/cache_service.h
src/v/redpanda/admin/server.cc
tests/rptest/tests/cluster_config_test.py

Manual backport of https://github.com/redpanda-data/redpanda/pull/23337.
Merge conflict due to unrelated changes in `cluster_config_test.py`.
Closes https://github.com/redpanda-data/redpanda/issues/23356
* none

[v24.1.x] `admin`: add `cloud_storage_cache_size` check to `config_multi_property_validation()` (manual backport)

---

src/v/raft/consensus.cc
src/v/raft/consensus.h
src/v/raft/state_machine.cc

Handle timeout in the Raft `linarizable_barrier` itself instead of
wrapping the call site with `ss::with_timeout`
- none

Handling linearizable barrier timeout directly in Raft

---

src/v/cloud_storage/tests/cloud_storage_e2e_test.cc
src/v/cluster/archival/ntp_archiver_service.cc

Compact-only topics should never apply retention. This wasn't the case for the spillover region in tiered storage.
Note, for the STM region, we do correctly no-op when trying to apply retention for compacted topics.
* Fixes a bug that would cause retention to be applied to compact-only tiered storage topics.

archival: skip spillover retention if not collectable

---

src/v/archival/ntp_archiver_service.cc
src/v/cloud_storage/tests/cloud_storage_e2e_test.cc

Preemptive backport of https://github.com/redpanda-data/redpanda/pull/23358
Compact-only topics should never apply retention. This wasn't the case for the spillover region in tiered storage.
Note, for the STM region, we do correctly no-op when trying to apply retention for compacted topics.
(cherry picked from commit 26df815465dc2cfd68e716e0936d1bdc99bb248b)
* Fixes a bug that would cause retention to be applied to compact-only tiered storage topics.

[v24.2.x] archival: skip spillover retention if not collectable

---

src/v/archival/ntp_archiver_service.cc
src/v/cloud_storage/tests/cloud_storage_e2e_test.cc

Preemptive backport of https://github.com/redpanda-data/redpanda/pull/23358
CONFLICT:
- updated test for GTest
Compact-only topics should never apply retention. This wasn't the case for the spillover region in tiered storage.
Note, for the STM region, we do correctly no-op when trying to apply retention for compacted topics.
(cherry picked from commit 26df815465dc2cfd68e716e0936d1bdc99bb248b)
* Fixes a bug that would cause retention to be applied to compact-only tiered storage topics.

[v23.3.x] archival: skip spillover retention if not collectable

---

tests/rptest/services/redpanda.py
tests/rptest/tests/cluster_self_config_test.py
tests/rptest/tests/redpanda_startup_test.py
tests/rptest/utils/mode_checks.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23331

[v24.2.x] `rptest`: add `@skip_fips_mode` decorator

---

src/v/redpanda/BUILD
src/v/redpanda/CMakeLists.txt
src/v/redpanda/application.cc
src/v/redpanda/application.h
src/v/redpanda/monitor_unsafe.cc
src/v/redpanda/monitor_unsafe.h

Going to reuse the unsafe log monitor to nag on other unsafe states, so rename it to be more general.
* none

redpanda: rename unsafe log monitor to be more general

---

tests/rptest/clients/rpk.py
tests/rptest/services/rpk_producer.py

Remove some lines that pollute the log.
fixes https://redpandadata.atlassian.net/browse/PESDLC-2056
* none

Remove some warnings and ignored errors from ducktape log

---

src/v/cluster/CMakeLists.txt
src/v/cluster/feature_manager.cc
src/v/cluster/feature_manager.h
src/v/features/BUILD
src/v/features/CMakeLists.txt
src/v/features/enterprise_features.cc
src/v/features/enterprise_features.h
src/v/redpanda/admin/api-doc/features.json
src/v/redpanda/admin/server.cc
src/v/redpanda/admin/server.h
tests/rptest/services/admin.py
tests/rptest/tests/enterprise_features_license_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23314

[v24.2.x] [CORE-7152] Admin: Introduce  endpoint

---

src/v/storage/kvstore.cc

Just propagate correct exception type. No visible changes.
* none

storage: rethrow eptr

---

src/v/config/property.h
src/v/net/connection.cc
src/v/net/server.cc
src/v/raft/consensus.cc
src/v/storage/segment.cc

Due to [ADL](https://en.cppreference.com/w/cpp/language/adl) rules, there were some callsites to `std::rethrow_exception` with an unqualified namespace.
Cleanup these callsites with the proper `std::` qualifier and ensure `#include <exception>` is present.
* none

`misc`: `std::rethrow_exception()` cleanup

---

src/v/cluster/cluster_utils.cc
src/v/cluster/cluster_utils.h
src/v/cluster/partition_balancer_planner.cc
src/v/cluster/scheduling/allocation_node.cc
src/v/cluster/scheduling/allocation_node.h
src/v/cluster/scheduling/allocation_state.cc
src/v/cluster/scheduling/allocation_state.h
src/v/cluster/scheduling/constraints.cc
src/v/cluster/scheduling/constraints.h
src/v/cluster/scheduling/partition_allocator.cc
src/v/cluster/scheduling/partition_allocator.h
src/v/cluster/scheduling/types.cc
src/v/cluster/scheduling/types.h
src/v/cluster/tests/allocation_bench.cc
src/v/cluster/tests/partition_allocator_fixture.h
src/v/cluster/tests/partition_allocator_tests.cc
src/v/cluster/tests/partition_balancer_planner_fixture.h
src/v/cluster/tests/topic_table_fixture.h
src/v/cluster/topic_updates_dispatcher.cc
src/v/cluster/topic_updates_dispatcher.h
src/v/cluster/topics_frontend.cc
src/v/cluster/types.h

The original motivation for allocation domains was to ensure balanced distribution of __consumer_offsets partitions that doesn't depend on the distribution of user partitions. After topic-aware partition allocation and balancing got introduced, this is no longer relevant, as the same objective is achieved in a more general way.
* none

cluster: remove allocation domains from the codebase

---

src/go/rpk/pkg/cli/cluster/partitions/balancer_run.go
src/go/rpk/pkg/cli/cluster/partitions/partitions.go

Backport of PR https://github.com/redpanda-data/redpanda/pull/22855
(cherry picked from commit 62031165e3c6867939e182a4066bf6831088248a)
JIRA Link: [CORE-7019](https://redpandadata.atlassian.net/browse/CORE-7019)
* rpk: supports triggering on-demand partition balancer
[CORE-7019]: https://redpandadata.atlassian.net/browse/CORE-7019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[v24.2.x] rpk: supports triggering on-demand balancer

---

src/go/rpk/pkg/adminapi/api_partition.go
src/go/rpk/pkg/cli/cluster/partitions/balancer_run.go
src/go/rpk/pkg/cli/cluster/partitions/partitions.go

(cherry picked from commit 62031165e3c6867939e182a4066bf6831088248a)
Backport of PR https://github.com/redpanda-data/redpanda/pull/22855 
JIRA Link: [CORE-7020](https://redpandadata.atlassian.net/browse/CORE-7020)
* rpk: supports triggering on-demand partition balancer
[CORE-7020]: https://redpandadata.atlassian.net/browse/CORE-7020?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[v24.1.x] rpk: supports triggering on-demand balancer

---

src/v/iceberg/BUILD
src/v/iceberg/datatypes.cc
src/v/iceberg/datatypes.h
src/v/iceberg/manifest_list.h
src/v/iceberg/partition.h
src/v/iceberg/schema.h
src/v/iceberg/schema_json.cc
src/v/iceberg/snapshot.h
src/v/iceberg/snapshot_json.cc
src/v/iceberg/table_requirement.h
src/v/iceberg/tests/datatypes_test.cc
src/v/iceberg/tests/partition_test.cc
src/v/iceberg/tests/schema_test.cc
src/v/iceberg/tests/snapshot_json_test.cc

Adds some miscellaneous small changes, and a few copy methods (types, schema, partition_spec) that will be helpful in building metadata.
* none

iceberg: miscellaneous changes, copy methods

---

src/v/config/node_overrides.cc

Fix formatting in `config/node_overrides.cc`
* none

config: Make clang-format happy

---

src/v/kafka/protocol/kafka_batch_adapter.cc
src/v/kafka/protocol/kafka_batch_adapter.h
src/v/model/adl_serde.h
src/v/model/record.h
src/v/model/record_utils.cc
src/v/model/record_utils.h
src/v/storage/record_batch_utils.cc

Unlike what the code comments say Kafka protocol specifies using
uint32_t for crc in the header, this change avoids decoding it as
int32_t and then a later cast during comparison.
Java has no 32-bit unsigned int, so they use long to represent the
checksum value to avoid overflow (checksum > int32_max) but the actual
checksum is always a uint32_t (as per CRC32C definition).
There are no functional changes in the patch.
* none

kafka/protocol: use uint32_t for crc decoding in the header

---

src/v/cluster/archival/ntp_archiver_service.cc

Instead of logging every possible `candidate_creation_error` at the `warn` level, use the existing `log_level_for_error()` function.
Relevant Slack thread: https://redpandadata.slack.com/archives/C02BDN76HUK/p1722881949600539
Backporting to `v24.1.x` and `v24.2.x`.
* none

`archival`: use `log_level_for_error()` for failed reupload candidates

---

src/v/storage/tests/BUILD
src/v/storage/tests/record_batch_builder_test.cc
src/v/storage/tests/snapshot_test.cc

bazel: test backfill for storage
* none

bazel: test backfill for storage

---

src/v/transform/rpc/tests/transform_rpc_test.cc

transform: fix narrowing integer conversion warning
* none

transform: fix narrowing integer conversion warning

---

src/v/archival/ntp_archiver_service.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/23407

[v24.2.x] `archival`: use `log_level_for_error()` for failed reupload candidates

---

src/v/archival/ntp_archiver_service.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/23407

[v24.1.x] `archival`: use `log_level_for_error()` for failed reupload candidates

---

src/v/kafka/server/handlers/fetch.cc
src/v/kafka/server/handlers/fetch.h
src/v/model/fundamental.h

Calling `fmt::format` to create the address string, then copying that string, ends up consuming ~0.5% of overall reactor utilization;
This address string is only used in the cloud storage layer's debug/info logs. So this change defers the formatting of the 
address until then and instead passes around `ss::socket_address`.   This greatly reduces the reactor utilization in the normal case;
* none

Use `ss::socket_address` instead of `ss::sstring` for `client_address_t`

---

src/v/cluster/data_migrated_resources.cc
src/v/cluster/data_migration_backend.cc
src/v/cluster/data_migration_backend.h
src/v/cluster/data_migration_table.cc
src/v/cluster/data_migration_types.cc
src/v/cluster/data_migration_types.h
src/v/cluster/metadata_cache.cc
src/v/cluster/topics_frontend.cc
tests/rptest/tests/data_migrations_api_test.py

1) Make sure resources are locked appropriately by the time backend and worker work on them
2) Make sure a topic is only allowed to be created on the correspondent stage of the inbound migration in order to disallow late backend recreating it after it was deleted on cancelling stage
* none

Migrations race conditions fixes

---

src/v/config/base_property.h
src/v/config/config_store.h
src/v/config/configuration.cc
src/v/config/configuration.h
src/v/config/property.h
src/v/redpanda/admin/cluster_config_schema_util.cc
src/v/redpanda/monitor_unsafe.cc
src/v/redpanda/monitor_unsafe.h
tests/rptest/services/redpanda.py
tests/rptest/tests/cluster_config_test.py

`:%s/experimental/development/g`
This PR adds a notion of _experimental feature property_ to the configuration system whose intent is to provide to Redpanda developers a capability that can help with managing feature development across releases.
Note that this work is intended for development only. It is not intended for managing access to beta features, or any feature that is visible in production. That will require input from product, and is a much bigger project.
The strategy proposed by this PR for managing experimental feature development is to use the configuration system to guard access to experimental features (e.g. blocking services from being enabled, etc...) the same way that we use configuration properties today to control features being enabled/disabled. To create an …

config: add experimental feature properties

---

src/v/cluster/archival/ntp_archiver_service.cc
src/v/storage/disk_log_impl.h

Adjacent segment merger implemented its own logic for determining the segment size. Today, the logic is a bit more complex and also does min/max clamping of the segment size based on cluster configuration.
This commit changes adjacent segment merger to use the same logic as local storage does.
The problematic scenario was one in which cluster wide min-max values were set say to 1MiB-16MiB but the topic level property was set to 128MiB. Local storage would create 16MiB segments which are uploaded as-is by archival. Later, adjacent segment merger would merge them to try and reach the 128MiB target. This resulted in undesired write amplification.
Now, adjacent segment merger properly infers the local segment size so this scenario doesn't happen anymore.
* none

archival: use correct segment size in adjacent segment merger

---

src/v/config/CMakeLists.txt
src/v/config/convert.h
src/v/config/node_config.cc
src/v/config/node_config.h
src/v/config/node_overrides.cc
src/v/config/node_overrides.h
src/v/config/property.h
src/v/config/rjson_serialization.cc
src/v/config/rjson_serialization.h
src/v/config/tests/CMakeLists.txt
src/v/config/tests/node_override_test.cc
src/v/redpanda/application.cc
src/v/redpanda/application.h
src/v/utils/uuid.cc
src/v/utils/uuid.h
tests/rptest/services/redpanda.py
tests/rptest/tests/admin_uuid_operations_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22972 
Closes #23403

[v24.1.x] CORE-7000: Node ID/UUID Override

---

.github/workflows/backport-command.yml
.github/workflows/backport-on-merge.yml
.github/workflows/buildkite-slash-commands.yml
.github/workflows/cloud-installpack-bk-trigger.yml
.github/workflows/comment_added.yml
.github/workflows/jira_issue_manage.yml
.github/workflows/lint-cpp.yml
.github/workflows/lint-golang.yml
.github/workflows/lint-python.yml
.github/workflows/lint-sh.yml
.github/workflows/lint-yaml.yml
.github/workflows/p.yml
.github/workflows/pr-labeler.yml
.github/workflows/promote.yml
.github/workflows/release-rp-storage-tool.yml
.github/workflows/render-pr-body-release-notes.yml
.github/workflows/rp-storage-tool-checks.yml
.github/workflows/rpk-build.yml
.github/workflows/slash-commands.yml
.github/workflows/stale.yml
.github/workflows/transform-sdk-build.yml
.github/workflows/transform-sdk-release.yml
.yamllint

jira: [PESDLC-1736]
update gha workflows to use [oidc](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services) to retrieve secrets
also, cleanup and fixes along the way:
* fixed gha yaml indenting inconsistency so new lines are interpreted at the correct level; added `lint-yaml.yml` workflow to verify from now on
* updated actions to latest versions to incorporate bug fixes and address warning message: `The following actions uses node12 which is deprecated...`
* fixed `actions/setup-go` not finding `go.sum` for dependency caching
* eliminated duplicate PR check run in `transform-sdk-build` workflow
* fixed `release-rp-storage-tool` timeout waiting for arm runner
* none
[PESDLC-1736]: …

gha: use oidc

---

tests/rptest/services/redpanda_installer.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23429

[v24.2.x] CORE-7689 tests: persistent cache of github releases

---

src/v/debug_bundle/BUILD
src/v/debug_bundle/json.h
src/v/debug_bundle/tests/BUILD
src/v/debug_bundle/tests/CMakeLists.txt
src/v/debug_bundle/tests/json_test.cc
src/v/debug_bundle/tests/types_test.cc
src/v/debug_bundle/types.cc
src/v/debug_bundle/types.h
src/v/redpanda/CMakeLists.txt
src/v/redpanda/admin/BUILD
src/v/redpanda/admin/api-doc/debug_bundle.def.json
src/v/redpanda/admin/api-doc/debug_bundle.json
src/v/redpanda/admin/debug_bundle.cc
src/v/redpanda/admin/server.cc
src/v/redpanda/admin/server.h
src/v/redpanda/application.cc

Add support for:
1. `POST /v1/debug/bundle`
1. `GET /v1/debug/bundle`
1. `DELETE /v1/debug/bundle/{jobid}`
1. `GET /debug/bundle/file/{filename}` (returns `not_implemented`)
1. `DELETE /debug/bundle/file/{filename}` (returns `not_implemented`)
* none

[CORE-7095] debug_bundle: Admin API

---

src/v/resource_mgmt/memory_sampling.cc
src/v/resource_mgmt/memory_sampling.h

with fmt>9 and clang18 there were complaints that this method wasn't const qualified.
* none

resource_mgmt: mark method const

---

src/v/iceberg/BUILD
src/v/iceberg/CMakeLists.txt
src/v/iceberg/manifest_file_packer.cc
src/v/iceberg/manifest_file_packer.h
src/v/iceberg/tests/BUILD
src/v/iceberg/tests/CMakeLists.txt
src/v/iceberg/tests/manifest_file_packer_test.cc

Iceberg has two modes for appending data:
- Fast append: new files are always added to a brand new manifest, and the new manifest is added to the manifest list.
- Merge append: manifests are bin-packed to a target size (e.g. 8MiB), and bins of manifests are merged to create larger manifests, thereby reducing the number of manifests in a given manifest list.
While fast appends are easier to implement, they are not scalable for a streaming system like Redpanda, especially while we don't have compaction. To limit the rate of metadata generated, Redpanda will merge append by default.
To that end, this introduces a simple bin packer for manifest files to group together manifests to a target size. The implementation is a simplified version of a more generic version in the Icberg python library …

iceberg: manifest file packing

---

src/v/features/BUILD
src/v/features/CMakeLists.txt
src/v/features/feature_table.cc
src/v/features/feature_table.h
src/v/features/tests/BUILD
src/v/features/tests/feature_table_test.cc
src/v/security/license.cc
src/v/security/license.h
src/v/security/tests/license_test.cc
src/v/storage/tests/BUILD
src/v/storage/tests/segment_deduplication_test.cc
src/v/storage/tests/storage_test_fixture.h
tests/rptest/tests/rpk_cluster_test.py

This introduces a new metric for monitoring the expiry time of the enterprise license.
* Description: “Number of seconds remaining until the Enterprise License expires”
* Endpoints: both public and internal metrics
* Labels: none
Fixes https://redpandadata.atlassian.net/browse/CORE-7338
* A new metric (*cluster_features_enterprise_license_expiry_sec*) is added for easier monitoring of the enterprise license's expiry time.

CORE-7338 license: add `enterprise_license_expiry_sec` metric

---

src/v/cluster/archival/tests/ntp_archiver_reupload_test.cc
src/v/cluster/archival/tests/service_fixture.cc
src/v/storage/disk_log_impl.cc
src/v/storage/kvstore.cc
src/v/storage/log_manager.cc
src/v/storage/log_manager.h
src/v/storage/segment.cc
src/v/storage/segment.h
src/v/storage/segment_utils.cc
src/v/storage/tests/BUILD
src/v/storage/tests/log_manager_test.cc

In the segment appender we dynamically compute the size to which we
fallocate the segment based on the maximum size. When we introduced
segment size clamping, we forgot to apply it here which led to it to use
the non-clamped value leading to unexpected behavior like the one
reported below:
> We see that the current segment has been fallocated/ftruncated to
> 32MiB. The segments still get closed at 16MiB at which point they are
> being shrunk. This still wastes lots of preallocation which isn't cheap
> and obviously also wastes disk space for the active segment.
> —StephanDollberg
* tbd

storage: adaptive falloc respect segment size

---

.github/workflows/backport-command.yml

The `/backport` command will only cherry-pick the first 30 commits of the PR. This PR fixes that by cherry-picking all commits.
Also, reduce commit sha from 40 chars to 10 chars for brevity in displaying cherry-pick command.
jira: [PESDLC-2095]
* none
[PESDLC-2095]: https://redpandadata.atlassian.net/browse/PESDLC-2095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

gha: increase commits cherry-picked in backport

---

src/v/redpanda/admin/debug_bundle.cc

admin: fix unused parameter warning
* none

admin: fix unused parameter warning

---

src/v/security/gssapi_authenticator.cc

It seems that in fmt v8 either a copy of gss::buffer wasn't being made, or the explicit conversion operator to std::string_view was being made prior to a copy of the fmt argument.
Now in fmt v9 it looks like fmt is trying to make a copy before any conversion. So this PR just invokves the conversion up front and passes a std::string_view down into fmt.
external/fmt~/include/fmt/core.h:1735:47: error: call to deleted constructor of 'security::gss::buffer'
1735 |   const auto& arg = arg_mapper<Context>().map(FMT_FORWARD(val));
|                                               ^~~~~~~~~~~~~~~~
external/fmt~/include/fmt/core.h:204:26: note: expanded from macro 'FMT_FORWARD'
204 | #define FMT_FORWARD(...) static_cast<decltype(__VA_ARGS__)&&>(__VA_ARGS__)
| …

security: convert gss::buffer to string for printing

---

src/v/serde/protobuf/BUILD
src/v/serde/protobuf/parser.cc
src/v/serde/protobuf/parser.h
src/v/serde/protobuf/tests/parser_test.cc
src/v/serde/protobuf/tests/three.proto

Maps are weird in proto3. Internally they are a repeated synthetic message type
with a key and value, because we're not checking if the type is a map,
we're outputting those as messages. Fix that by when we complete a
message see if it's a map entry then convert it to the proper internal
map type.
* none

protobuf: actually output map types

---

src/v/features/BUILD
src/v/features/CMakeLists.txt
src/v/features/feature_table.cc
src/v/features/feature_table.h
src/v/features/tests/BUILD
src/v/features/tests/feature_table_test.cc
src/v/security/license.cc
src/v/security/license.h
src/v/security/tests/license_test.cc
src/v/storage/tests/segment_deduplication_test.cc
src/v/storage/tests/storage_test_fixture.h
tests/rptest/tests/rpk_cluster_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23367 
Fixes https://github.com/redpanda-data/redpanda/issues/23455
Conflict was on the storage test bazel BUILD file which was missing the unit test configs on this branch.

[v24.2.x] CORE-7338 license: add  metric

---

src/v/features/CMakeLists.txt
src/v/features/feature_table.cc
src/v/features/feature_table.h
src/v/features/tests/BUILD
src/v/features/tests/feature_table_test.cc
src/v/security/license.cc
src/v/security/license.h
src/v/security/tests/license_test.cc
src/v/storage/tests/segment_deduplication_test.cc
src/v/storage/tests/storage_test_fixture.h
tests/rptest/tests/rpk_cluster_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23367 
Fixes https://github.com/redpanda-data/redpanda/issues/23454
Conflicts were on the storage test bazel BUILD file and on some of the headers in feature_table.cc and feature_table_test.cc.

[v24.1.x] CORE-7338 license: add  metric

---

src/v/features/CMakeLists.txt
src/v/features/feature_table.cc
src/v/features/feature_table.h
src/v/features/tests/feature_table_test.cc
src/v/security/license.cc
src/v/security/license.h
src/v/security/tests/license_test.cc
src/v/storage/tests/segment_deduplication_test.cc
src/v/storage/tests/storage_test_fixture.h
tests/rptest/tests/rpk_cluster_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23367 
Fixes https://github.com/redpanda-data/redpanda/issues/23456
Conflicts were on the storage test bazel BUILD file and on some of the headers in feature_table.cc, feature_table_test.cc and license.cc.

[v23.3.x] CORE-7338 license: add  metric

---

src/v/archival/tests/ntp_archiver_reupload_test.cc
src/v/archival/tests/service_fixture.cc
src/v/storage/disk_log_impl.cc
src/v/storage/kvstore.cc
src/v/storage/log_manager.cc
src/v/storage/log_manager.h
src/v/storage/segment.cc
src/v/storage/segment.h
src/v/storage/segment_utils.cc
src/v/storage/tests/log_manager_test.cc

#23462
In the segment appender we dynamically compute the size to which we fallocate the segment based on the maximum size. When we introduced segment size clamping, we forgot to apply it here which led to it to use the non-clamped value leading to unexpected behavior like the one reported below:
> We see that the current segment has been fallocated/ftruncated to
> 32MiB. The segments still get closed at 16MiB at which point they are
> being shrunk. This still wastes lots of preallocation which isn't cheap
> and obviously also wastes disk space for the active segment.
> —@StephanDollberg
(cherry picked from commit 20d5695c58d4c778724ab47b6eeb3fe3163e4e05)
* none

[v24.2.x] storage: adaptive falloc respect segment size

---

src/v/bytes/iobuf.cc
src/v/bytes/iobuf.h
src/v/bytes/tests/iobuf_tests.cc
src/v/iceberg/tests/values_test.cc
src/v/iceberg/values.cc
src/v/iceberg/values.h
src/v/utils/tests/uuid_test.cc
src/v/utils/uuid.cc
src/v/utils/uuid.h

It will be useful to be able to compare Iceberg values, e.g. to keep track of the lower bound and upper bound of the partition keys kept in each manifest_file. To that end, this adds a less-than operator to iceberg::value, and consequently, to iobuf and uuid as well.
* none

iceberg: add operator< for values

---

src/v/datalake/CMakeLists.txt
src/v/datalake/parquet_writer.cc
src/v/datalake/parquet_writer.h
src/v/datalake/tests/CMakeLists.txt
src/v/datalake/tests/arrow_writer_test.cc
src/v/datalake/tests/parquet_writer_test.cc
src/v/datalake/tests/test_data.h

This adds an arrow_to_iobuf interface that converts Arrow data to iobufs representing Parquet files that can be written to disk. There are two components:
1. An implementation of arrow::io::OutputStream that collects data in iobufs
2. A class that creates a parquet::io::FileWriter using that output stream and allows the caller to extract the generated iobufs.
This allows us to separate the compute side of generating parquet, which still occurs in the Arrow library, from the file io, which can now be made seastar-friednly.
* none

datalake: arrow_to_iobuf interface

---

src/v/cloud_roles/tests/credential_tests.cc

```
/home/nwatkins/src/redpanda-clang-18/src/v/cloud_roles/tests/credential_tests.cc:89:9: error: the value returned by this function should not be disregarded; neglecting it may lead to errors [bugprone-unused-return-value,-warnings-as-errors]
89 |         applier.add_auth(h);
|         ^~~~~~~~~~~~~~~~~~~
/home/nwatkins/src/redpanda-clang-18/src/v/cloud_roles/tests/credential_tests.cc:99:9: error: the value returned by this function should not be disregarded; neglecting it may lead to errors [bugprone-unused-return-value,-warnings-as-errors]
99 |         applier.add_auth(h);
|  
^~~~~~~~~~~~~~~~~~~
```
* none

cloud_roles: fix unused return value warning

---

tests/rptest/services/failure_injector.py
tests/rptest/tests/e2e_finjector.py

to avoid race conditions between test shutting down and timed failure undos
* none

tests/failure_injector: undo the failures on exit

---

tests/rptest/services/failure_injector.py
tests/rptest/tests/e2e_finjector.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23400

[v24.2.x] tests/failure_injector: undo the failures on exit

---

.github/workflows/cloud-installpack-bk-trigger.yml
.github/workflows/promote.yml
.github/workflows/release-rp-storage-tool.yml
.github/workflows/transform-sdk-build.yml
.github/workflows/transform-sdk-release.yml
.yamllint
tests/docker/ducktape-deps/rust
tools/rp_storage_tool/Cargo.lock

Backport of PR #23423
Fixes #23438
jira: [PESDLC-1736]
This PR updates the workflow files triggered from the `v24.2.x` branch that use action `aws-actions/configure-aws-credentials` to run with OIDC tokens.
There were many conflicts when I first attempted to cherry-pick all the commits from PR #23423 that were unrelated to OIDC tokens and/or changed workflow files that wouldn't run on this `v24.2.x` branch, so I only cherry-picked a subset of the commits that are needed. This reduced the changeset to just these files:
1. `cloud-installpack-bk-trigger.yml`
2. `promote.yml`
3. `release-rp-storage-tool.yml`
4. `transform-sdk-release.yml`
EDIT: also backported changes from PRs https://github.com/redpanda-data/redpanda/pull/23036 and https://github.com/redpanda-data/redpanda/pull/23045 to fix …

[v24.2.x] gha: use oidc

---

.github/workflows/cloud-installpack-bk-trigger.yml
.github/workflows/promote.yml
.github/workflows/release-rp-storage-tool.yml
.github/workflows/transform-sdk-build.yml
.github/workflows/transform-sdk-release.yml
.yamllint
tests/docker/ducktape-deps/rust
tools/rp_storage_tool/Cargo.lock

Backport of PR #23423 #23036 #23045
Fixes #23436
jira: [PESDLC-1736]
This PR updates the workflow files triggered from the `v24.1.x` branch that use action `aws-actions/configure-aws-credentials` to run with OIDC tokens.
There were many conflicts when I first attempted to cherry-pick all the commits from PR #23423 that were unrelated to OIDC tokens and/or changed workflow files that wouldn't run on this `v24.1.x` branch, so I only cherry-picked a subset of the commits that are needed. This reduced the changeset to just these files:
1. `cloud-installpack-bk-trigger.yml`
2. `promote.yml`
3. `release-rp-storage-tool.yml`
4. `transform-sdk-release.yml`
also, backported changes from PRs https://github.com/redpanda-data/redpanda/pull/23036 and …

[v24.1.x] gha: use oidc

---

.github/workflows/cloud-installpack-bk-trigger.yml
.github/workflows/promote.yml
.github/workflows/release-rp-storage-tool.yml
.yamllint

Backport of PR #23423
Fixes #23437
jira: [PESDLC-1736]
This PR updates the workflow files triggered from the `v23.3.x` branch that use action `aws-actions/configure-aws-credentials` to run with OIDC tokens.
There were many conflicts when I first attempted to cherry-pick all the commits from PR #23423 that were unrelated to OIDC tokens and/or changed workflow files that wouldn't run on this `v23.3.x` branch, so I only cherry-picked a subset of the commits that are needed. This reduced the changeset to just these files:
1. `cloud-installpack-bk-trigger.yml`
2. `promote.yml`
3. `release-rp-storage-tool.yml`
* none
[PESDLC-1736]: https://redpandadata.atlassian.net/browse/PESDLC-1736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[v23.3.x] gha: use oidc

---

src/v/iceberg/BUILD
src/v/iceberg/CMakeLists.txt
src/v/iceberg/schema.h
src/v/iceberg/table_update_applier.cc
src/v/iceberg/table_update_applier.h
src/v/iceberg/tests/BUILD
src/v/iceberg/tests/CMakeLists.txt
src/v/iceberg/tests/table_update_applier_test.cc

Adds a method to apply a given update to a table_metadata. There are some basic, mechanical validations that are performed (e.g. to avoid adding a duplicate schema).
These updates will be generated as a result of various actions (e.g. appending to the table) and sent to the catalog. The applying of these updates to an in-memory table_metadata allows us to validate and build up multi-action transactions whose updates can be grouped together and sent to the catalog together.
Note for reviewers: similar apply operations can be found in the python library [here](https://github.com/apache/iceberg-python/blob/e5a58b34dd830c6ffea11649613b693f70f7cbb4/pyiceberg/table/update/__init__.py), see all implementations of `_apply_table_update`.
* none

iceberg: table update applier

---

src/v/cluster/cloud_metadata/tests/cluster_recovery_backend_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/18553
Fixes: https://github.com/redpanda-data/redpanda/issues/23504,

[v24.1.x] cluster_recovery_backend_test: only reset relevant config

---

src/v/utils/tracking_allocator.cc

```
=================================================================
==524==ERROR: AddressSanitizer: container-overflow on address 0x52100028a100 at pc 0x7f29c0bf51fd bp 0x7ffda75397d0 sp 0x7ffda75397c8 READ of size 4 at 0x52100028a100 thread T0
#0 0x7f29c0bf51fc in util::mem_tracker::pretty_print_ascii() const /var/lib/buildkite-agent/builds/buildkite-amd64-builders-i-024f8676eb7b139e9-1/redpanda/vtools/src/v/utils/tracking_allocator.cc:75:31
#1 0x55be1ac7eb7b in mem_tracker_pretty_printing::test_method() /var/lib/buildkite-agent/builds/buildkite-amd64-builders-i-024f8676eb7b139e9-1/redpanda/vtools/src/v/utils/tests/tracking_allocator_tests.cc:82:5
#2 0x55be1ac7d651 in mem_tracker_pretty_printing_invoker() /var/lib/buildkite-agent/builds/buildkite-amd64-builders-i-024f8676eb7b139e9-1/red …
```

utils: fix container-overflow in tracking allocator

---

tests/rptest/services/redpanda_installer.py

Fixes a bug in e78099a6952213830735273f430a64be82d0a727 which caused the nightly cdt run of the v24.2.x branch to fail.
If the directory containing the redpanda installer cache file does not exist the test currently fails, so this commit fixes that by creating the containing directory if it doesn't exist.
While the dockerized ducktape environment used in PRs and in local development ensures that the container directory exists by mounting it into the ducktape docker container (see https://github.com/redpanda-data/vtools/pull/3156), the directory is not created in CDT.
Fixes https://redpandadata.atlassian.net/browse/PESDLC-2105
Fixes https://redpandadata.atlassian.net/browse/CORE-7689
* none

CORE-7689 dt/rp_installer: ensure cache directory exists

---

tests/rptest/services/redpanda.py

When running `redpanda --version` apply ubsan suppressions like we do when we run redpanda normally.
* none

test: apply ubsan suppressions to all redpanda invocations

---

tests/rptest/scale_tests/tiered_storage_reader_stress_test.py

This assertion fails from time to time. It seems perfectly fine there not to be any cached readers available.
If there aren't any running queries using readers and we are under memory pressure the next query will likely evict all segment readers to free up resources. Reader eviction (and memory accounting) is asynchronous but the metric/probe update is synchronous.
If we get metrics in-between last query acquiring memory resources (or slightly after) and before the actual physical eviction happened then we expect the metric to be 0.
It is possible for the last query to be aborted altogether in-between requesting resources and actually creating a reader which would also lead to metric being 0.
I consider this acceptable behavior so removing the assert.
* none

rptest: do not expect cached segment readers at the end of the test

---

tests/rptest/redpanda_cloud_tests/high_throughput_test.py
tests/rptest/services/redpanda.py

We were not passing a resource type to get (`pod` missing) and hence the
command would fail.
Fix this and replace some usages with the existing helper function.
* none

cloud-tests: Fix incomplete kubectl command

---

tests/rptest/scale_tests/tiered_storage_reader_stress_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23509

[v24.2.x] rptest: do not expect cached segment readers at the end of the test

---

tests/rptest/scale_tests/tiered_storage_reader_stress_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23509

[v24.1.x] rptest: do not expect cached segment readers at the end of the test

---

tests/rptest/services/redpanda_installer.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23518

[v24.2.x] CORE-7689 dt/rp_installer: ensure cache directory exists

---

tests/rptest/services/redpanda_installer.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23518

[v24.1.x] CORE-7689 dt/rp_installer: ensure cache directory exists

---

tests/rptest/tests/data_migrations_api_test.py

Namely "failed to lock pidfile": it's a race condition between two starts of Redpanda. There are some pgrep-based scripts around but they are not bulletproof. Ideally these scripts should have their own lock files to avoid race conditions between them but it sounds overengineering to me.
* none

tests/migrations: allow bad log line that happen because of failure injector

---

src/v/cloud_topics/dl_placeholder.h
src/v/cloud_topics/errc.h
src/v/cloud_topics/logger.cc
src/v/cloud_topics/logger.h
src/v/cloud_topics/tests/types_test.cc
src/v/cloud_topics/types.cc
src/v/cloud_topics/types.h

ct: add experimental namespace prefix
* none

ct: add experimental namespace prefix

---

src/v/pandaproxy/parsing/httpd.h
tests/rptest/tests/schema_registry_test.py

seastar::http::request::get_path_param performs URL decoding automatically. When this path was updated to use the new method, the pre-existing URL decode behavior was left in place.
This is usually not noticeable because decoding an un-encoded string is a no-op. However, that's not the case if the decoded string itself contains URL escape sequences.
For example, given the path parameter "foo%252Fbar":
- decoded once:   "foo%2Fbar"
- decoded twice:  "foo/bar"
So this commit removes the "extra" decode step from the PP httpd module and adds a ducktape test to confirm that URL escape sequences are preserved in a client-provided subject name, the specific case that led to this fix.
Unfortunately, get_path_param destroys some information such that distinguishing between an absent parameter and …

CORE-7738: pp/httpd: Remove extra decode on path param get

---

src/v/iceberg/BUILD
src/v/iceberg/CMakeLists.txt
src/v/iceberg/merge_append_action.cc
src/v/iceberg/merge_append_action.h
src/v/iceberg/tests/BUILD
src/v/iceberg/tests/CMakeLists.txt
src/v/iceberg/tests/merge_append_action_test.cc
src/v/iceberg/tests/update_schema_action_test.cc
src/v/iceberg/transaction.cc
src/v/iceberg/transaction.h

Implements a new merge_append action that adds a given group of data
files to the table, potentially merging them to an existing manifest if
there are too many manifests.
This resembles the implementation in the pyiceberg library[1]: we
bin-pack manifest_files into groups of 8MiB and merge all bins but the
latest one. If the latest bin contains fewer than 100 manifests, it is
left alone, otherwise it is also merged. In the future, these will be
configurable, but for now, this commit adds these default parameters.
Unlike the python implementation, which groups together merges based on
partition spec, this implementation throws if there is more than one
partition spec. This is left as short-term future work.
[1] https://github.com/apache/iceberg-python/blob/e5a58b34dd830c6ffea11649613b693f70 …

iceberg: add merge append action

---

src/v/pandaproxy/parsing/httpd.h
tests/rptest/tests/schema_registry_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23529

[v24.2.x] CORE-7738: pp/httpd: Remove extra decode on path param get

---

src/v/iceberg/tests/BUILD

I don't fully understnad why but tests that use remote_io trip up when run with multiple cores.
```
ERROR 2024-09-28 17:36:49,541 [shard 1:main] seastar - shared_ptr accessed on non-owner cpu, at: 0x796ee6 /home/andrew/xfs/vbuild/debug/clang/rp_deps_install/lib/libseastar.so+0x220536b /home/andrew/xfs/vbuild/debug/clang/rp_deps_install/lib/libseastar.so+0x2206e58 /home/andrew/xfs/vbuild/debug/clang/rp_deps_install/lib/libseastar.so+0x22077f0 /home/andrew/x build/debug/clang/rp_deps_install/lib/libseastar.so+0x1994272 /home/andrew/xfs/vbuild/debug/clang/rp_deps_install/lib/libseastar.so+0x1994aaf 0x98afbb 0x98a069 /home/andrew/xfs/vbuild/debug/clang/lib/libv_v_cloud_io_utils.so+0xbcd71 /home/andrew/xfs/vbuild/debug/clang/lib/libv_v_cloud_io_utils.so+0xbc86d …
```

iceberg: deflake update_schema_action_test

---

src/v/ssx/sleep_abortable.h
src/v/ssx/tests/sleep_abortable_test.cc

Caught a few shutdown hangs in unit tests which I tracked down to sleep_abortable being invoked with high durations after abort sources where already aborted.
Do not try to sleep if abort source is already set. ss::sleep_abortable behaves similarly from what I can read.
```
sleeper(typename Clock::duration dur, abort_source& as)
...
auto sc_opt = as.subscribe // returns empty optional if abort source is
already set
...
if (sc_opt) {...} else {
done.set_exception(sleep_aborted());
}
```
* none

ssx: exit early from sleep_abortable if already aborted

---

tests/rptest/services/failure_injector.py
tests/rptest/tests/e2e_finjector.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23400

[v24.1.x] tests/failure_injector: undo the failures on exit

---

src/v/ssx/include/ssx/sleep_abortable.h
src/v/ssx/tests/sleep_abortable_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/23540

[v24.1.x] ssx: exit early from sleep_abortable if already aborted

---

src/v/debug_bundle/debug_bundle_service.cc
src/v/debug_bundle/tests/debug_bundle_service_test.cc
src/v/debug_bundle/types.h
src/v/redpanda/admin/api-doc/debug_bundle.def.json
src/v/redpanda/admin/debug_bundle.cc

Added a file_size entry to the status that will report the size of the debug bundle after being successfully created.
Fixes: CORE-7733
* None

debug_bundle: Added file size to status

---

src/v/iceberg/values.h

iceberg: add comment about struct field ordering

---

tests/rptest/redpanda_cloud_tests/high_throughput_test.py

kubectl.cmd is not guaranteed to return type bytes, it can also return a str so only call decode() if the type is bytes. This is causing intermittent CI failures. 
* None

Deployment args formatting fix

---

src/v/ssx/include/ssx/sleep_abortable.h
src/v/ssx/tests/sleep_abortable_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/23540

[v24.2.x] ssx: exit early from sleep_abortable if already aborted

---

src/v/debug_bundle/json.h
src/v/debug_bundle/tests/json_test.cc
src/v/redpanda/admin/BUILD
src/v/redpanda/admin/debug_bundle.cc
src/v/redpanda/admin/debug_bundle.h
src/v/redpanda/admin/server.cc
src/v/redpanda/admin/server.h
tests/rptest/services/admin.py
tests/rptest/tests/debug_bundle_test.py

Continuation of [CORE-7095](https://github.com/redpanda-data/redpanda/pull/23366)
Implement:
1. `GET /debug/bundle/file/{filename}`
1. `DELETE /debug/bundle/file/{filename}`
Add ducktape tests for all endpoints:
1. `POST /v1/debug/bundle`
1. `GET /v1/debug/bundle`
1. `DELETE /v1/debug/bundle/{jobid}`
1. `GET /debug/bundle/file/{filename}` (returns `not_implemented`)
1. `DELETE /debug/bundle/file/{filename}` (returns `not_implemented`)
* none
[CORE-7095]: https://redpandadata.atlassian.net/browse/CORE-7095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CORE-7096] Hook admin API to debug bundle service

---

tests/rptest/tests/debug_bundle_test.py

Thanks to some merge ordering schenangians, these tests started failing when #23557 merged after #23508.  This change addresses the test bug by properly obtaining the configuration property and handling a situation when the debug bundle directory configuration is empty.
* None

dt/debug-bundle: Fixed tests

---

src/v/cluster/data_migration_backend.cc
src/v/ssx/future-util.h

On shutdown there's a hot loop between abort and gate close. Fix it by stopping the loop on abort.
* none

Migrations: fix shutdown busyloop

---

tests/rptest/services/redpanda.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23579

[v24.2.x] rptest: request feature state from each node in await_feature

---

TODO
src/v/cluster/controller.cc
src/v/cluster/data_migration_frontend.cc
src/v/cluster/data_migration_frontend.h
src/v/cluster/data_migration_table.cc
src/v/cluster/data_migration_table.h
src/v/cluster/errc.h
src/v/cluster/partition.cc
src/v/cluster/tests/data_migration_table_test.cc
src/v/config/property.h
src/v/redpanda/admin/migrations.cc
src/v/redpanda/admin/server.cc
src/v/redpanda/admin/server.h
tests/rptest/services/admin.py
tests/rptest/tests/data_migrations_api_test.py

1) implement API to show a single migration
2) on migration creation validate that cluster and topic config are supported
3) add tests for these and for deleting active migrations
* none

Improve migrations API

---

src/v/cluster/data_migration_backend.cc
src/v/cluster/data_migration_backend.h

A few fixes where objects lifetime was not taken care of.
* none

Migrations memory bugfixes

---

src/v/iceberg/BUILD
src/v/iceberg/datatypes_json.cc
src/v/iceberg/datatypes_json.h
src/v/iceberg/json_writer.h
src/v/iceberg/manifest_avro.cc
src/v/iceberg/partition_json.cc
src/v/iceberg/partition_json.h
src/v/iceberg/schema_avro.cc
src/v/iceberg/schema_avro.h
src/v/iceberg/schema_json.cc
src/v/iceberg/schema_json.h
src/v/iceberg/snapshot_json.cc
src/v/iceberg/snapshot_json.h
src/v/iceberg/table_metadata_json.cc
src/v/iceberg/table_metadata_json.h
src/v/iceberg/tests/BUILD
src/v/iceberg/tests/datatypes_json_test.cc
src/v/iceberg/tests/partition_json_test.cc
src/v/iceberg/tests/schema_json_test.cc
src/v/iceberg/tests/snapshot_json_test.cc
src/v/iceberg/tests/table_metadata_json_test.cc
src/v/iceberg/transform_json.cc
src/v/iceberg/transform_json.h

Swaps out the string-based JSON writer for an iobuf_writer with a chunked_buffer. While we're at it, cleans up some identical to-string code scattered around with a template that uses the new writer.
This will make it trivial to upload JSON, as cloud_io code expects iobufs.
* none

iceberg: use iobuf_writer for json

---

src/v/config/configuration.cc

Updates `iceberg_enable` cluster property with documentation suggestions. 
Introduced on https://github.com/redpanda-data/redpanda/pull/23443
* none

config: updates iceberg property description

---

bazel/thirdparty/Cargo.lock
bazel/thirdparty/Cargo.toml
src/transform-sdk/go/transform/internal/testdata/dynamic/BUILD
src/transform-sdk/go/transform/internal/testdata/identity/BUILD
src/transform-sdk/go/transform/internal/testdata/identity_logging/BUILD
src/transform-sdk/go/transform/internal/testdata/schema-registry/BUILD
src/transform-sdk/go/transform/internal/testdata/setup-panic/BUILD
src/transform-sdk/go/transform/internal/testdata/tee/BUILD
src/transform-sdk/go/transform/internal/testdata/transform-error/BUILD
src/transform-sdk/go/transform/internal/testdata/transform-panic/BUILD
src/transform-sdk/go/transform/internal/testdata/wasi/BUILD
src/v/wasm/tests/BUILD
src/v/wasm/tests/CMakeLists.txt
src/v/wasm/tests/wasi_test.cc
src/v/wasm/tests/wasm_fixture.cc
src/v/wasm/tests/wasm_fixture.h
src/v/wasm/tests/wasm_lifecycle_test.cc
src/v/wasm/tests/wasm_resources_test.cc
src/v/wasm/tests/wasm_sr_test.cc
src/v/wasm/tests/wasm_transform_bench.cc
src/v/wasm/tests/wasm_transform_test.cc

The tests now pass. We were blocked on a wasmtime release to pull in https://github.com/bytecodealliance/wasmtime/pull/9224
* none

bazel/wasm: get tests working

---

.bazelrc
BUILD
MODULE.bazel

Example:
$ bazel build //src/v/bytes:iobuf --config clang-tidy
INFO: Analyzed target //src/v/bytes:iobuf (1 packages loaded, 4 targets configured).
INFO: Found 1 target...
Aspect @@bazel_clang_tidy~//clang_tidy:clang_tidy.bzl%clang_tidy_aspect of //src/v/bytes:iobuf up-to-date:
bazel-bin/src/v/bytes/bazel_clang_tidy_src/v/bytes/iobuf.cc.iobuf.clang-tidy.yaml
bazel-bin/src/v/bytes/bazel_clang_tidy_src/v/bytes/details/io_allocation_size.h.iobuf.clang-tidy.yaml
bazel-bin/src/v/bytes/bazel_clang_tidy_src/v/bytes/details/io_byte_iterator.h.iobuf.clang-tidy.yaml
bazel-bin/src/v/bytes/bazel_clang_tidy_src/v/bytes/details/io_fragment.h.iobuf.clang-tidy.yaml
bazel-bin/src/v/bytes/bazel_clang_tidy_src/v/bytes/details/io_iterator_consumer.h.iobuf.clang-tidy.yaml …

bazel: add initial support for clang-tidy

---

src/v/storage/log_manager.cc

Manual backport of https://github.com/redpanda-data/redpanda/pull/23410.
`git cherry-pick` failed due to unrelated changes in current version of `redpanda` not present in `v24.1.x`. 
Fixes https://github.com/redpanda-data/redpanda/issues/23445/
* none

[v24.1.x] `storage`: catch `ss::gate_closed_exception` in `log_manager` (manual backport)

---

.github/workflows/backport-command.yml

jira: [PESDLC-2118]
The `/backport` command is [broken](https://github.com/redpanda-data/redpanda/actions/runs/11115132569/job/30882995089#step:9:26) if there is more than 1 commit in a PR because the list of git commits have newlines:
```
bash$ backport_commits=$(gh api "repos/redpanda-data/redpanda/pulls/23492/commits" --paginate --jq '.[].sha[0:10]')
bash$ echo "backport_commits=$backport_commits"
backport_commits=c254729c5a
9a5f7d7d58
2bc21e9516
c9223a24ae
```
This patch fixes by having the commits separated by spaces:
```
bash$ backport_commits=$(gh api "repos/redpanda-data/redpanda/pulls/23492/commits" --paginate --jq '[.[].sha[0:10]]|join(" ")')
bash$ echo "backport_commits=$backport_commits"
backport_commits=c254729c5a 9a5f7d7d58 2bc21e9516 c9223a24ae
```
see …

gha: fix /backport command

---

src/v/test_utils/async.h

Seastar has recently purged many unused headers. One of which was the `smp.hh` header in `reactor.hh` which this file had originally relied on to get the complete definition of `smp`. This PR adds the `smp.hh` to the file that needs the definition directly to fix the issue.
* none

Add `smp.hh` header to async test_utils

---

src/v/kafka/server/group.cc
src/v/kafka/server/group.h

When transaction is expired due to a timeout a group coordinator issues
a request to a transaction coordinator to abort the transaction. The
operation may fail as the currently known coordinator may not be a
leader or the request may timeout.
The result of transaction abort operation was previously ignored. This
lead to a situation in which an error when aborting transaction lead to
a tight loop in group coordinator as it instantly dispatched another
abort retry. With the fix the error when aborting ongoing transaction is
not ignored but rather than that if an error happened it is logged with
warn severity and the coordinator waits for the next scheduled timer
ticked (by default ten seconds) before retrying.
- fixes possible high CPU utilisation caused by transactional coordinator …

Fixed a busy loop that was happening when expiring producer state from consumer groups

---

src/v/debug_bundle/BUILD
src/v/debug_bundle/CMakeLists.txt
src/v/debug_bundle/debug_bundle_service.cc
src/v/debug_bundle/debug_bundle_service.h
src/v/debug_bundle/metadata.h
src/v/debug_bundle/probe.cc
src/v/debug_bundle/probe.h
src/v/debug_bundle/tests/debug_bundle_service_test.cc
src/v/debug_bundle/tests/metadata_test.cc
src/v/debug_bundle/types.h
tests/rptest/tests/debug_bundle_test.py

Added metrics to debug bundle service:
* `last_successful_bundle_timestamp_seconds` - timestamp in seconds since epoch of last successful debug bundle generation
* `last_failed_bundle_timestamp_seconds` - timestamp in seconds since epoch of last failed debug bundle generation
* `successful_generation_count` - count of successful generations
* `failed_generation_count` - count of failed generations
* None

CORE-7725 debug bundle metrics

---

src/v/iceberg/BUILD
src/v/iceberg/catalog.h

Adds a bare-bones interface for interacting with external catalogs. The main goal is to wrap an Iceberg REST client, though this interface will also be useful in defining a filesystem catalog (useful for testing).
One implementation can be seen here as a draft: https://github.com/redpanda-data/redpanda/pull/23592
* none

iceberg: add catalog interface

---

src/v/iceberg/schema_avro.cc
src/v/iceberg/tests/test_schemas.cc
src/v/iceberg/tests/test_schemas.h
src/v/iceberg/tests/value_generator.cc
src/v/iceberg/tests/values_avro_test.cc
src/v/iceberg/values_avro.cc

Added Avro schema and value conversion for UUID, fixed length byte array and decimal types. 
- none

Added missing Avro values and schema conversion

---

src/v/cluster/feature_manager.cc
src/v/security/license.cc
src/v/security/license.h
tests/rptest/services/redpanda.py
tests/rptest/tests/license_enforcement_test.py
tests/rptest/utils/rpenv.py

This is part of a series of changes to verify that clusters have a valid enterprise license during major version upgrades if they use enterprise features.
This adds an environment variable that can be used to insert an enterprise license on startup into a non-compliant cluster when it is failing the license enforcement check. This should be an undocumented escape hatch we can use if we ever need to inject a license into this check if we cannot add it into the controller log via `rpk cluster license set` (eg. if we cannot downgrade the broker to a previous version for any reason).
Fixes https://redpandadata.atlassian.net/browse/CORE-7343
* none

CORE-7343 License: add fallback license env var

---

src/transform-sdk/js/js_vm.cc
src/transform-sdk/js/js_vm.h
src/transform-sdk/js/main.cc
src/transform-sdk/js/schema_registry_example/src/index.ts

Adds a `SchemaFormat` "enum" (really a JS object with integer-valued fields) to the schema registry module. 
The enum previously appeared in our TypeScript typings but was left unimplemented by mistake. Usually, the TS compiler will emit a pure JS object corresponding to such an enum, but our setup doesn't do this because the SDK module(s) are all native code, mediated by `quickjs`.
This PR also includes an update to the SR example code (to use the enum rather than a bare int) and some quickjs-oriented helper structs related to constructing and exporting a singleton object into a native module.
* Implements `@redpanda-data/transform-sdk-sr.SchemaFormat` for the WASM Transforms JS module

JavaScript Transforms SDK: Export SchemaFormat 

---

src/v/base/BUILD
src/v/base/unreachable.h
src/v/cloud_topics/batcher/batcher.cc

Add macro wrapper for the `__builtin_unreachable`. The macro adds additional logging and generates a backtrace before terminating the app.
The `__builtin_unreachable` should only be used in places which can't be reached. Example is a switch statement over `enum class` values which uses `return` statement in every case. In this case the compiler will statically check that every possible enum value is present in the `switch` statement so it's guaranteed that we will not reach the `__builtin_unreachable` at the end:
```cpp
switch(e) {
case errc:timedout:
return 0;
default:
return 1;
}
__builtin_unreachable();
```
In some cases the code may depend on some runtime information or could easily be changed in the future in such way that will allow execution to actually invoke …

base: Add unreachable macro

---

src/v/cluster/feature_manager.cc

[features: delay first license nag](https://github.com/redpanda-data/redpanda/commit/27d7c1f1e8fdb1856fbb4ce8635f2198cd4eade7) 
If a customer bootstraps a cluster and immediately installs a license we
still print the license nag today. This is confusing to compliant
customers (eg. RP Cloud).
This change delays the license nag by 1 interval.
Note that this means that a savvy customer could increase the license
nag interval to infinity and thereby disable the nag. But that seems
acceptable given that this is just a log message.
[features: fix enterprise feature list format](https://github.com/redpanda-data/redpanda/commit/b2012c3504e391f690887f4abe75d5e5a81e9ce5) 
The list of enabled enterprise features has been formatted incorrectly.
Bad (old): [rbacpartition_auto_balancing_continuous] …

CORE-7691 License: minor ux improvements

---

.bazelrc
MODULE.bazel
src/v/cloud_io/BUILD
src/v/cluster/BUILD
src/v/cluster/notification.h
src/v/cluster/tests/BUILD
src/v/cluster/version.h
src/v/container/BUILD
src/v/hashing/jump_consistent_hash.h
src/v/kafka/client/test/BUILD
src/v/pandaproxy/BUILD
src/v/pandaproxy/schema_registry/subject_name_strategy.h
src/v/security/audit/BUILD
src/v/security/tests/BUILD
src/v/storage/tests/BUILD
src/v/test_utils/BUILD
src/v/utils/BUILD
src/v/wasm/BUILD

* Brings in fix for implementation_deps
* Brings in fix for missing external header directories
* An assortment of missing bazel dep fixes found by clang-tidy compiling header-only cc_libraries that don't have proper deps set.
* none

clang-tidy: updates

---

src/v/config/configuration.cc
src/v/config/node_config.cc
src/v/kafka/client/configuration.cc
src/v/pandaproxy/rest/configuration.cc
src/v/pandaproxy/schema_registry/configuration.cc
tests/rptest/tests/describe_topics_test.py

Backfeed changes to configuration descriptions that were added to docs. 
* Improve property configuration descriptions.

config: update config descriptions to match docs

---

src/v/ssx/async_algorithm.h

`std::for_each` does not honor `[[nodiscard]]` attributes of functions or return types. Avoiding it to guard from mistakes like passing a future-returning function to `ssx::async_for_each`. `ss::future` is marked `[[nodiscard]]` in Seastar.
separated from https://github.com/redpanda-data/redpanda/pull/23556
* none

ssx/async_algorithm: avoid std::for_each to honor [[nodiscard]]

---

src/v/cluster/controller_backend.cc
src/v/cluster/controller_backend.h
src/v/cluster/data_migration_backend.cc
src/v/cluster/data_migration_backend.h
src/v/cluster/partition_balancer_backend.cc
src/v/cluster/shard_balancer.cc
src/v/cluster/shard_balancer.h
src/v/cluster/tests/topic_table_fixture.h
src/v/cluster/tests/topic_table_test.cc
src/v/cluster/tests/topic_updates_dispatcher_test.cc
src/v/cluster/topic_table.cc
src/v/cluster/topic_table.h
src/v/cluster/types.cc
src/v/cluster/types.h
src/v/kafka/server/group_manager.cc
src/v/kafka/server/group_manager.h

Previously, topic table only had NTP-level notifications. But some clients don't need this granularity and are only interested in topic-level changes. Implement topic-level deltas and notifications to provide that. 
* none

`cluster::topic_table`: topic-level notifications

---

src/v/serde/parquet/BUILD
src/v/serde/parquet/CMakeLists.txt
src/v/serde/parquet/encoding.cc
src/v/serde/parquet/encoding.h
src/v/serde/parquet/tests/BUILD
src/v/serde/parquet/tests/encoding_test.cc
src/v/serde/parquet/tests/value_test.cc
src/v/serde/parquet/value.h

Introduce the value domain for parquet (the subset of types we'll need for iceberg), along with plain encoding.
Plain encoding reference: https://parquet.apache.org/docs/file-format/data-pages/encodings/#plain-plain--0
* none

parquet: plain encoding

---

src/go/rpk/pkg/cli/topic/config.go
src/v/cluster/tests/serialization_rt_test.cc
src/v/cluster/topic_table.cc
src/v/cluster/types.cc
src/v/cluster/types.h
src/v/compat/cluster_compat.h
src/v/compat/cluster_generator.h
src/v/compat/cluster_json.h
src/v/features/feature_table.cc
src/v/features/feature_table.h
src/v/kafka/server/handlers/alter_configs.cc
src/v/kafka/server/handlers/configs/config_utils.h
src/v/kafka/server/handlers/incremental_alter_configs.cc
src/v/kafka/server/tests/alter_config_test.cc
src/v/migrations/cloud_storage_config.cc
tests/rptest/clients/kcl.py
tests/rptest/tests/alter_topic_configuration_test.py
tests/rptest/tests/offset_for_leader_epoch_archival_test.py
tests/rptest/tests/timequery_test.py

Relevant JIRA ticket: https://redpandadata.atlassian.net/browse/CORE-7743
Relevant historical threads: https://github.com/redpanda-data/redpanda/issues/9191, https://github.com/redpanda-data/redpanda/pull/23220#discussion_r1751678405, https://github.com/redpanda-data/redpanda/issues/5846.
This PR fixes some bugs that have been present in how `redpanda` handles `AlterConfig` and `IncrementalAlterConfig` API calls and the tiered storage topic properties `redpanda.remote.read`, `redpanda.remote.write`.
These bugs are well described in the above links, but the TL;DR is that a command like `rpk topic alter-config t --set redpanda.remote.write=true --set redpanda.remote.read=false` cannot properly describe both the addition of write permissions and the removal of read permissions due to the …

[CORE-7743] `cluster`: tiered storage topic property update fixes

---

src/go/rpk/pkg/cli/cluster/license/info.go
tests/rptest/tests/rpk_cluster_test.py

This PR introduces the `license_expired` field for `rpk cluster license info --format` for JSON and YAML.
It also fixes a bug that prevents the `License Expired` field from appearing in `text` format.
**License Expired:**
```
rpk cluster license info 
LICENSE INFORMATION
===================
Organization:      Devex
Type:              enterprise
Expires:           Oct 5 2024
License Expired:   true
$ rpk cluster license info --format json
{"organization":"Devex","type":"enterprise","expires":"Oct 5 2024","expires_unix":1728146392,"checksum_sha256":"090c1cfb7f8c710f4bec10d3cc5d9bc3cdcdbc415a35e73","license_expired":true}
$ rpk cluster license info --format yaml 
organization: Devex
type: enterprise
expires: Oct 5 2024
expires_unix: 1728146392
checksum_sha256: …
```

[DEVEX-25] rpk: add license_expired to rpk cluster license info

---

src/v/serde/parquet/BUILD
src/v/serde/parquet/encoding.cc
src/v/serde/parquet/encoding.h
src/v/serde/parquet/tests/encoding_test.cc

Before data is encoded v2 data pages, the "levels" are written. These
are the definition and repetition levels. These are used for knowing the
nesting depth of values (needed for knowing what level a null value was)
and the index if the value is a repeated type.
You can read more about levels generally here:
https://blog.x.com/engineering/en_us/a/2013/dremel-made-simple-with-parquet
We choose to implement this as simply as possible for the first
iteration by always choosing run length coding for values. The low bit
in the header is used to determine if the run length (0) or bit packing
is used (1). Hence the reason for `unsigned_vint::to_bytes(length <<
1)`.
A more complicated algorithm could be used to alternate between
bitpacking and run length encoding. This is a similar tradeoff to …

serde/parquet: add level encoding

---

src/v/cluster/distributed_kv_stm.h
src/v/cluster/id_allocator_stm.cc
src/v/cluster/log_eviction_stm.cc
src/v/cluster/log_eviction_stm.h
src/v/cluster/rm_stm.cc
src/v/cluster/tests/partition_properties_stm_test.cc
src/v/cluster/tm_stm.cc
src/v/raft/persisted_stm.cc
src/v/raft/persisted_stm.h
src/v/raft/recovery_stm.cc
src/v/raft/recovery_stm.h
src/v/raft/state_machine_base.h
src/v/raft/state_machine_manager.cc
src/v/raft/state_machine_manager.h
src/v/raft/tests/persisted_stm_test.cc
src/v/raft/tests/stm_manager_test.cc
src/v/raft/tests/stm_test_fixture.h

To support fast partition movement in Redpanda the
`raft::state_machine_base` interface requires state machine implementer
to provide support for taking snapshot at arbitrary, already applied
offset. This requirement is easy to achieve for all existing state
machines as they do not require raft snapshots at all.
In future we may leverage the Raft protocol snapshot as they provide a
nice way to maintain the bounded log size without compromising
consistency.
This PR introduces changes to `state_machine_manager` and
`state_machine_base` interfaces allowing state machine implementer to
opt out from the requirement to provide snapshot at offset capability.
Without this feature the partition that the STM is build at will not be
fast movable but the `take_snapshot` implementation will be very …

Giving state machine implementers a way to opt out from being forced to support snapshotting at arbitrary offset. 

---

src/go/rpk/pkg/cli/cluster/license/info.go
tests/rptest/tests/rpk_cluster_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23636
Fixes https://github.com/redpanda-data/redpanda/issues/23663
It had to be done manually as in dev we use rpadmin from common-go but in previous branches, we use the rpk's adminapi package.
* none

[v23.3.x] [DEVEX-25] rpk: add license_expired to rpk cluster license info

---

tests/rptest/clients/rpk.py
tests/rptest/tests/rpk_generate_test.py

The legacy dashboard uses the admin API to get the metrics and auto-generate a dashboard.
Also, remove the Title assertion as this depends on an external repo. We just need to test if rpk is able to download and parse.
* none

tests: test legacy dashboard in rpk generate

---

src/v/datalake/coordinator/BUILD
src/v/datalake/coordinator/CMakeLists.txt
src/v/datalake/coordinator/data_file.h
src/v/datalake/coordinator/state.cc
src/v/datalake/coordinator/state.h
src/v/datalake/coordinator/state_update.cc
src/v/datalake/coordinator/state_update.h
src/v/datalake/coordinator/tests/BUILD
src/v/datalake/coordinator/tests/CMakeLists.txt
src/v/datalake/coordinator/tests/state_update_test.cc
src/v/datalake/coordinator/translated_offset_range.h

Adds deterministic state that will be used as the basis for the upcoming coordinator and its STM. We will use this to keep track of the files pending to be committed to Iceberg for each Kafka partition. As files are committed, the state will be updated accordingly, removing the tracked files.
This only includes the underlying data structures that intend on using for the STM. It isn't yet plugged into the state machine.
Along the way I duplicated a couple structs from the writer: data_file and translated_offset_range. This may be temporary, as the code for the worker is still in flight. Or we may keep it, given it's a nice way to decouple worker from coordinator. For now though it's just helpful to have the coordinator code be entirely separate from the worker.
* none

datalake/coordinator: add deterministic state

---

src/v/http/rest_client/rest_entity.cc
src/v/http/rest_client/rest_entity.h

Make rest entity methods const - addressing feedback for https://github.com/redpanda-data/redpanda/pull/23534#discussion_r1786992306
* none

http: Make rest entity methods const

---

src/v/storage/log_manager.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/23410

[v24.2.x] `storage`: catch `ss::gate_closed_exception` in `log_manager`

---

src/go/rpk/pkg/cli/cluster/license/info.go
tests/rptest/tests/rpk_cluster_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23636

[v24.2.x] [DEVEX-25] rpk: add license_expired to rpk cluster license info

---

src/go/rpk/pkg/cli/cluster/license/info.go
tests/rptest/tests/rpk_cluster_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23636
Fixes #23664
It had to be done manually as in dev we use `rpadmin` from common-go but in previous branches, we use the rpk's `adminapi` package.
* none

[v24.1.x] [DEVEX-25] rpk: add license_expired to rpk cluster license info

---

src/v/kafka/server/handlers/fetch.cc
src/v/kafka/server/handlers/fetch.h
src/v/model/fundamental.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/21605

[v24.2.x] Use `ss::socket_address` instead of `ss::sstring` for `client_address_t`

---

src/go/rpk/go.mod
src/go/rpk/go.sum
src/go/rpk/pkg/cli/redpanda/admin/brokers/list.go

Relevant to https://github.com/redpanda-data/common-go/pull/27.
`rpk redpanda admin brokers list` now exposes additional fields that makes troubleshooting easier.
Before:
```
NODE-ID  NUM-CORES  MEMBERSHIP-STATUS  IS-ALIVE  BROKER-VERSION
0        2          active             true      v24.2.3 - be49068f63acc31d34b9d186cdfa62087fd99222
1        2          active             true      v24.2.3 - be49068f63acc31d34b9d186cdfa62087fd99222
2        2          active             true      v24.2.3 - be49068f63acc31d34b9d186cdfa62087fd99222
```
After:
```
ID    HOST       PORT   RACK  CORES  MEMBERSHIP  IS-ALIVE  VERSION  UUID
0     localhost  33146  a     2      active      true      24.2.3   e4ff0f11-6fc2-4df1-b129-bbf2630e7c18
1     localhost  33147  -     2      active      true      24.2.3 …
```

rpk: brokers list exposing Host/Port/Rack/UUID

---

src/v/config/configuration.cc
src/v/config/configuration.h
src/v/config/convert.h
src/v/kafka/CMakeLists.txt
src/v/kafka/server/BUILD
src/v/kafka/server/fetch_pid_controller.cc
src/v/kafka/server/fetch_pid_controller.h
src/v/kafka/server/handlers/fetch.cc
src/v/kafka/server/server.cc
src/v/kafka/server/server.h
src/v/model/metadata.h
src/v/model/model.cc

Often when Redpanda is at CPU saturation the fetch scheduling group can
starve other operations. In these situations increasing the time a fetch
request waits on the server before starting allows for Redpanda to apply
backpressure to the clients and increase batching for fetch responses.
This increased batching frees up CPU resources for other operations to
use and tends to decrease end-to-end latency.
From testing its been found empirically that when Redpanda is at
saturation restricting the fetch scheduling group to only consume 20% of
overall reactor utilization will improve end-to-end latency for a
variety of workloads.
This commit implements a PID controller that will dynamically adjust
fetch debounce to ensure that the fetch scheduling group is only
consuming 20% of overall reactor …

Dynamically adjust fetch debounce with PID controller

---

src/go/rpk/go.mod
src/go/rpk/go.sum
src/go/rpk/pkg/cli/redpanda/admin/brokers/list.go

Backport of PR https://github.com/redpanda-data/redpanda/pull/23595

[v24.2.x] rpk: brokers list exposing Host/Port/Rack/UUID

---

.github/workflows/release-rp-storage-tool.yml

The IAM role assumed by this workflow runner has permissions to upload.
jira: [DEVPROD-1936]
* none
[DEVPROD-1936]: https://redpandadata.atlassian.net/browse/DEVPROD-1936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

gha: rm use of rp_storage_tool_uploader

---

src/v/datalake/coordinator/BUILD
src/v/datalake/coordinator/CMakeLists.txt
src/v/datalake/coordinator/data_file.cc
src/v/datalake/coordinator/data_file.h
src/v/datalake/coordinator/translated_offset_range.cc
src/v/datalake/coordinator/translated_offset_range.h
src/v/datalake/coordinator/types.h

Updates the coordinator RPC add_file to use translated_offset_range to represent groups of files. Each translated offset range will be analagous to the write of a single translation operation, as it corresponds to a single contiguous Kafka offset range.
Also updates the fetch_lastest to just return the latest Kafka offset.
Along the way, moved the ostream definitions out of the header, which contributed to a failure to build.
Also adds an hour field to the data_file type.
* none

datalake/coordinator: iron out RPC types

---

src/go/rpk/pkg/adminapi/api_broker.go
src/go/rpk/pkg/cli/redpanda/admin/brokers/list.go

Backport of PR https://github.com/redpanda-data/redpanda/pull/23595
(cherry picked from commit 08e30aa37df43bca951a66f6f31ad8bafa517119)
* rpk: `redpanda admin brokers list` exposes Host/Port/Rack/UUID additionally

[v24.1.x] rpk: brokers list exposing Host/Port/Rack/UUID

---

.github/workflows/jira_issue_manage.yml
.github/workflows/lint-python.yml
.github/workflows/transform-sdk-release.yml

The new `ubuntu-latest` complains when system-wide `pip` is invoked.
* none

gha: fix pip install on python actions

---

src/v/cluster/controller_backend.cc
src/v/cluster/controller_backend.h
src/v/cluster/partition_manager.cc
src/v/cluster/topic_table.h
tests/rptest/services/redpanda.py
tests/rptest/tests/partition_force_reconfiguration_test.py

When topic is configured to use remote data the data can be used when
force recovering partitions that lost majority. In this case instead of
creating an empty partition replica instance we customize arguments
passed into the `partition_manger::manage` method to enable remote
recovery of replica data.
- with this improvement the force reconfigured partitions will be backfilled from Tiered Storage even if they lost all local data

Use remote recovery when topic is configured to use remote data

---

tests/rptest/tests/license_enforcement_test.py

The role creation was racing with the node restart. If the target node is restarted before it observes the new role, it won't crash on startup like we would expect it to.
To fix this, we want to ensure that the enabled enterprise feature is observable on all nodes before the restart. We could implement this with roles, but it is simpler to switch to a different enterprise feature and using `redpanda.set_cluster_config`, which implements all-node-observability under the hood.
Fixes https://redpandadata.atlassian.net/browse/CORE-7831
* none

CORE-7831 dt/license: fix flaky license enforcement test

---

tests/rptest/perf/openmessaging_perf_test.py
tests/rptest/perf/small_batches_test.py
tests/rptest/perf/ts_read_openmessaging_test.py
tests/rptest/perf/ts_write_openmessaging_test.py

Reduce the test runtime such that we can instead do an extra run.
Also shorten the TS read bench warmup time which was 5 minutes.
* none

cdt-perf: Reduce OMB test runtime

---

src/v/kafka/server/group.cc
src/v/kafka/server/group.h
src/v/kafka/server/member.h
src/v/kafka/server/tests/group_test.cc
tests/rptest/tests/consumer_group_test.py

Fixes: [CORE-7749](https://redpandadata.atlassian.net/browse/CORE-7749)
When a static group member rejoins, only its protocols were updated based on the rejoin request.
The relevant updateMember functions have been extended to also include the client-id, client-host, session-timeout and rebalance-timeout properties.
* Fixes a bug where only a group static member's protocols would be updated on rejoin, even if more properties had been passed to the rejoin command
[CORE-7749]: https://redpandadata.atlassian.net/browse/CORE-7749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

kafka: Consumer group stale static member properties on rejoin

---

src/v/cluster/data_migration_backend.cc
src/v/cluster/data_migration_worker.cc
src/v/cluster/data_migration_worker.h
src/v/cluster/partition.cc
src/v/cluster/partition.h
src/v/cluster/rm_stm.cc
src/v/cluster/rm_stm.h
src/v/cluster/tm_stm.cc
src/v/kafka/server/tests/replicated_partition_test.cc
src/v/raft/replicate.h
src/v/redpanda/admin/partition.cc
tests/rptest/tests/data_migrations_api_test.py

When a partition is migrated away:
- make sure no writes sneak in after a final flush
- abort any uncommitted transactions affecting this partition
* none

Migrations to block partition writes and abort uncommited transactions

---

src/v/cluster/tx_gateway_frontend.cc

When a transaction is already committed and the client is retrying the request a coordinator may find the transaction outcome already available. In this case the client should receive the result that is known already instead of an error. In the previous code the outcome was not set which resulted in `unknown_server_error` being returned to the client. This in the end caused a chaos tests to fail.
- none

c/tx_gateway: fixed missing set outcome value after tx is committed

---

MODULE.bazel
MODULE.bazel.lock

bazel: update to PGO build clang-18 for x86_64

---

src/v/kafka/server/handlers/create_topics.cc
src/v/kafka/server/handlers/topics/topic_utils.h
src/v/kafka/server/handlers/topics/types.cc
src/v/kafka/server/tests/create_topics_test.cc
tests/rptest/tests/retention_policy_test.py
tests/rptest/tests/topic_creation_test.py

This PR covers three cases:
Previously, invalid boolean property values would be silently ignored during the handling of a `CreateTopics` request, e.g
```
$ rpk topic create tapioca -c redpanda.remote.read=yes_this_is_true
TOPIC    STATUS
tapioca  OK
$ rpk topic describe topic
CONFIGS
=======
KEY                   VALUE   SOURCE
redpanda.remote.read  false   DEFAULT_CONFIG
```
would result in the topic `tapioca` being created instead of returning an error. The topic's value for `redpanda.remote.read` silently defaults to the cluster default (`false` in the example above).
This is unlike Kafka, in which an invalid configuration error is propagated back to the user:
```
$ ./kafka-topics.sh --create --topic tapioca --bootstrap-server localhost:9092 --config preallocate=yes_this_is_true
Error …
```

`kafka`: improve `CreateTopics` error and boolean handling

---

src/v/cluster/tx_gateway_frontend.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/23734

[v24.2.x] c/tx_gateway: fixed missing set outcome value after tx is committed

---

src/v/datalake/coordinator/BUILD
src/v/datalake/coordinator/CMakeLists.txt
src/v/datalake/coordinator/coordinator.cc
src/v/datalake/coordinator/coordinator.h
src/v/datalake/coordinator/state_machine.cc
src/v/datalake/coordinator/state_machine.h
src/v/datalake/coordinator/state_update.cc
src/v/datalake/coordinator/state_update.h
src/v/datalake/coordinator/tests/BUILD
src/v/datalake/coordinator/tests/CMakeLists.txt
src/v/datalake/coordinator/tests/coordinator_test.cc
src/v/datalake/coordinator/tests/state_test_utils.cc
src/v/datalake/coordinator/tests/state_test_utils.h
src/v/datalake/coordinator/tests/state_update_test.cc
src/v/model/model.cc
src/v/model/record_batch_types.h

Based on https://github.com/redpanda-data/redpanda/pull/23714
Adds some initial structure for the coordinator. This commit just adds
wrapper around a couple of calls to the underlying STM, so that it can
be plugged into the frontend.
Later commits will have the coordinator reconcile the STM with the
Iceberg catalog, perform local/Raft snapshots, etc.
* none

datalake/coordinator: initial coordinator base

---

src/v/cloud_storage/tests/topic_manifest_test.cc
src/v/cloud_topics/reconciler/reconciler.cc
src/v/cluster/topic_configuration.cc
src/v/cluster/topic_properties.cc
src/v/cluster/topic_properties.h
src/v/cluster/topics_frontend.cc
src/v/compat/cluster_generator.h
src/v/kafka/server/handlers/alter_configs.cc
src/v/kafka/server/handlers/configs/config_response_utils.cc
src/v/kafka/server/handlers/create_topics.cc
src/v/kafka/server/handlers/incremental_alter_configs.cc
src/v/kafka/server/handlers/topics/types.cc
src/v/kafka/server/handlers/topics/types.h
src/v/kafka/server/handlers/topics/validators.h
src/v/storage/ntp_config.h
src/v/storage/types.cc
tests/rptest/tests/cloud_topics_test.py
tools/offline_log_viewer/controller.py

Adds a new `redpanda.cloud_topic.enable` topic property.
This topic is protected by the `development_enable_cloud_topics` development configuration option. That is, it needs to be turned on in order for this topic property to be active.
The one caveat is that we do reserve a bit on the wire (topic_properties serialization) for this flag which defaults to false.
* none

cloud_topics: add cloud topics topic property

---

src/v/http/BUILD
src/v/http/CMakeLists.txt
src/v/http/client.cc
src/v/http/client.h
src/v/http/tests/BUILD
src/v/http/tests/uri_encoding_test.cc
src/v/http/utils.cc
src/v/http/utils.h
src/v/iceberg/CMakeLists.txt
src/v/iceberg/rest_client/BUILD
src/v/iceberg/rest_client/catalog_client.cc
src/v/iceberg/rest_client/catalog_client.h
src/v/iceberg/rest_client/parsers.cc
src/v/iceberg/rest_client/parsers.h
src/v/iceberg/rest_client/retry_policy.cc
src/v/iceberg/rest_client/retry_policy.h
src/v/iceberg/rest_client/tests/BUILD
src/v/iceberg/rest_client/tests/CMakeLists.txt
src/v/iceberg/rest_client/tests/catalog_client_tests.cc
src/v/iceberg/rest_client/tests/parser_tests.cc
src/v/iceberg/rest_client/tests/retry_policy_tests.cc
src/v/iceberg/rest_client/types.h

Adds a basic rest catalog client impl with oauth token flow. No iceberg API calls are added yet other than token fetch.
Implementation of the catalog client interface will be added in the next PR.
Additionally a couple of supporting constructs are added:
* a retry policy modeled after cloud storage clients retry policy but extracted out for isolated testing
* an abstraction of http client to enable mocking
* oauth token parser and schema validator
The catalog client takes in a reference to the http client interface which can be supplied from a pool. It caches the token acquired from a call for use until the token expires.
A mechanism to shut down the client reference on a transport error is not yet added, it will be implemented in the next PR.
* None

CORE-7747: iceberg: catalog client with oauth flow

---

src/v/kafka/server/group.cc
src/v/kafka/server/group.h
src/v/kafka/server/member.h
src/v/kafka/server/tests/group_test.cc
tests/rptest/tests/consumer_group_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23693

[v24.2.x] kafka: Consumer group stale static member properties on rejoin

---

src/v/kafka/server/group.cc
src/v/kafka/server/group.h
src/v/kafka/server/member.h
src/v/kafka/server/tests/group_test.cc
tests/rptest/tests/consumer_group_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23693

[v24.1.x] kafka: Consumer group stale static member properties on rejoin

---

src/v/kafka/server/group.cc
src/v/kafka/server/group.h

If a producer/transaction is not found, we assume it is replay request
from the coordinator to roll forward/back the transaction and return success.
This is valid because the the current request to commit/abort confirms that the
coordinator sees a corresponding commit/abort respectively in its's log, so the
original request that cleaned up the state should have been the same
too. One particular sequence of events where this is possible is as follows.
- Coordinator - Attempting to commit -- it got a timeout but the group commit actually made it to replica 1
- group leadership changed from replica 1 to replica 2
- replica 2 has a compacted state of the log
- replica 2 recovers and _producers is empty
- replica 2 now rejects the commit request
Note: compaction cleans up the producer ids in …

tx/group: ignore replay requests if producer/tx is not found

---

src/v/datalake/batching_parquet_writer.cc
src/v/datalake/batching_parquet_writer.h
src/v/datalake/data_writer_interface.h
src/v/datalake/record_multiplexer.cc
src/v/datalake/record_multiplexer.h
src/v/datalake/tests/batching_parquet_writer_test.cc
src/v/datalake/tests/gtest_record_multiplexer_test.cc
src/v/datalake/tests/test_data_writer.h
ubsan_suppressions.txt

Adds a factory class for the batching_parquet_writer so it can be created by the multiplexer. This also improves error handling and logging in the data path.
* none

iceberg: add batching parquet writer factory

---

bazel/repositories.bzl
cmake/dependencies.cmake

Updates the bazel and cmake builds to use the v24.3.x branch of seastar.
* none

Switch to the v24.3.x seastar branch

---

MODULE.bazel.lock
bazel/repositories.bzl

Our change to segment the index array has been merged.
* none

bazel: Use upstream unordered_dense

---

src/v/cluster/partition_recovery_manager.cc

Currently, topics with recovery enabled will always have their `remote_topic_properties` and `recovery_enabled` flags set in `topic_properties`. As a result, post topic recovery, partitions added to the topic will still attempt to go through the log recovery process.
This would trigger an `ERROR` level log line, despite the fact it is expected that the partition should not have any data to recover from.
Reduce the log level to `WARN` for now- this can still indicate an error during log recovery.
Future work should add more sophisticated topic recovery improvements which discern partitions that need recovery vs freshly created partitions (which shouldn't reach `maybe_download_log()`), in which case this could again be raised back to `ERROR`.
* none

`cluster`: alter log line in `maybe_download_log()`

---

src/v/datalake/coordinator/BUILD
src/v/datalake/coordinator/CMakeLists.txt
src/v/datalake/coordinator/coordinator.cc
src/v/datalake/coordinator/coordinator.h
src/v/datalake/coordinator/coordinator_manager.cc
src/v/datalake/coordinator/coordinator_manager.h
src/v/datalake/coordinator/frontend.cc
src/v/datalake/coordinator/frontend.h
src/v/datalake/coordinator/state_machine.cc
src/v/datalake/coordinator/state_machine.h
src/v/datalake/coordinator/tests/coordinator_test.cc
src/v/datalake/coordinator/types.h
src/v/datalake/fwd.h
src/v/redpanda/BUILD
src/v/redpanda/application.cc
src/v/redpanda/application.h

Adds a coordinator manager abstraction to instantiate coordinators and plugs it into the frontend, rather than having the frontend call directly into the STM directly.
Note for reviewers, the structure of the coordinator manager resembles the archiver_manager very closely, in all of its hooks into the partition manager.
* none

datalake/coordinator: add coordinator manager

---

src/v/cloud_storage/remote_path_provider.cc
src/v/cloud_storage/tests/remote_path_provider_test.cc
src/v/cloud_storage/tests/topic_mount_handler_test.cc
src/v/cloud_storage/tests/topic_mount_manifest_test.cc
src/v/cloud_storage/topic_mount_handler.cc
src/v/cloud_storage/topic_mount_handler.h
src/v/cloud_storage/topic_mount_manifest.cc
src/v/cloud_storage/topic_mount_manifest.h
src/v/cluster/data_migration_backend.cc

To disambiguate between topics with the same name during the mount process, the `initial_revision_id` is added to the `topic_mount_manifest` path (now of the form `migration/{uuid}/{namespace}/{topic}/{initial_revision_id}`) and relevant data structures.
Also, add a warning log line during the unmount process to warn of a collision between an existing topic mount manifest and one already in cloud storage.
* none

`cloud_storage`: add `initial_revision_id` to `topic_mount_manifest` path

---

.github/workflows/jira_issue_manage.yml
.github/workflows/lint-python.yml
.github/workflows/render-pr-body-release-notes.yml
.github/workflows/transform-sdk-release.yml

[v24.1.x] gha: fix pip install on python actions

---

src/v/iceberg/manifest_io.cc
src/v/iceberg/manifest_io.h
src/v/iceberg/merge_append_action.cc
src/v/iceberg/metadata_io.h
src/v/iceberg/metadata_query.cc
src/v/iceberg/tests/manifest_io_test.cc
src/v/iceberg/tests/merge_append_action_test.cc
src/v/iceberg/tests/metadata_query_test.cc

In general, Iceberg tables use a configurable path style. This is just a first step towards that: as is, the raw object locations in the metadata aren't readable by systems like Spark.
Updates manifest_io and its callers to use path style URIs.
* none

iceberg: serialize path style URIs in metadata

---

tests/rptest/services/failure_injector.py
tests/rptest/tests/data_migrations_api_test.py
tests/rptest/tests/e2e_finjector.py

Finjector may be overzealous, especially for a 3-node cluster.
This is to make it nicer where needed and also to fix final repairs in it.
* none

Chasten finjector to keep redpanda available

---

tests/rptest/services/redpanda.py
tests/rptest/tests/cloud_storage_timing_stress_test.py

* improve reporting on the cloud storage timing stress test
* fix apparent copy-paste mistake
* none

fix test typos

---

src/v/cloud_topics/BUILD
src/v/cloud_topics/README.md
src/v/cloud_topics/batcher/aggregator.cc
src/v/cloud_topics/errc.h
src/v/cloud_topics/reader/BUILD
src/v/cloud_topics/reader/placeholder_extent.cc
src/v/cloud_topics/reader/placeholder_extent.h
src/v/cloud_topics/reader/placeholder_extent_reader.cc
src/v/cloud_topics/reader/placeholder_extent_reader.h
src/v/cloud_topics/reader/tests/BUILD
src/v/cloud_topics/reader/tests/mocks.h
src/v/cloud_topics/reader/tests/placeholder_extent_fixture.cc
src/v/cloud_topics/reader/tests/placeholder_extent_fixture.h
src/v/cloud_topics/reader/tests/placeholder_extent_reader_test.cc
src/v/cloud_topics/reader/tests/placeholder_extent_test.cc
src/v/model/model.cc
src/v/model/record_batch_types.h

The PR implements the reader which consumes `dl_placeholder` batches from the partition and materializes them by downloading the data from the cloud storage or fetching it from the cache.
The PR adds an abstract base class for the `cloud_storage::cache` class. The interface is located in the `cloud_io` package.
WIP, not all code pushed yet.
* none

ct: Add L0 read path

---

src/go/rpk/Makefile
src/go/rpk/pkg/cli/cluster/storage/BUILD
src/go/rpk/pkg/cli/cluster/storage/cancel-mount.go
src/go/rpk/pkg/cli/cluster/storage/list-mount.go
src/go/rpk/pkg/cli/cluster/storage/mount.go
src/go/rpk/pkg/cli/cluster/storage/status-mount.go
src/go/rpk/pkg/cli/cluster/storage/storage.go
src/go/rpk/pkg/cli/cluster/storage/unmount.go

Adds support for mounting and unmounting a topic to and from tiered storage with RPK. Also adds list, status and cancel commands. 
* adds rpk cluster storage topic mount, unmount, list-mount, status-mount, cancel-mount

rpk: Add Support for Topic Mounting and Unmounting

---

src/v/redpanda/admin/debug_bundle.cc
tests/rptest/tests/debug_bundle_test.py

The status check is the admin server is unnecessary.  Allow the service to report any errors based on the request it received.
* None

CORE-7935: admin: Removed status check in get_debug_bundle_job_id

---

tests/rptest/tests/rpk_cluster_test.py

Fixes a flaky assertion that the enterprise_license_expiry_sec metric gives the same value on internal and public endpoints.
Since these values are calculated remotely, we can't make that guarantee, so this commit adds an extremely generous 30s of slop and asserts on the difference.
Fixes CORE-7827
* none

[CORE-7827] dt/rpk_cluster: Add some slop for license metrics tests

---

src/v/cloud_io/basic_cache_service_api.h
src/v/cloud_storage/cache_service.cc
src/v/cloud_storage/cache_service.h
src/v/cloud_storage/tests/BUILD
src/v/cloud_storage/tests/cache_test.cc
src/v/cloud_topics/reader/tests/mocks.h
src/v/cloud_topics/reader/tests/placeholder_extent_fixture.cc

cloud_storage: follow ups to https://github.com/redpanda-data/redpanda/pull/23748
* none

cloud_storage: follow ups to https://github.com/redpanda-data/redpanda/pull/23748

---

tests/rptest/tests/metrics_reporter_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23783

[v24.2.x] [CORE-7812] dt/metrics: Assert on presence of 'has_enterprise_features'

---

src/v/model/fundamental.h
src/v/storage/disk_log_impl.cc
src/v/storage/disk_log_impl.h

Storage is the only place that it used, so it's a bit hard to say that it's a fundamental aspect.
* none

model: move boundary type into storage layer

---

tests/rptest/tests/crl_test.py

Ignores all error log lines for this test since a range of errors can happen across various layers in the brokers when we install a noncogent CRL and cause this test to be flaky in CI.
Fixes https://redpandadata.atlassian.net/browse/CORE-6977
* none

CORE-6977 dt: relax noncogent crl test log whitelist

---

src/v/datalake/CMakeLists.txt
src/v/datalake/batching_parquet_writer.cc
src/v/datalake/batching_parquet_writer.h
src/v/datalake/data_writer_interface.cc
src/v/datalake/data_writer_interface.h
src/v/datalake/record_multiplexer.cc
src/v/datalake/tests/batching_parquet_writer_test.cc
src/v/datalake/tests/gtest_record_multiplexer_test.cc
src/v/datalake/tests/test_data_writer.h

Cleaned up `datalake` writer interface. The change include introduction of remote and local path types definitions and returning `local_file_metadata` from the writer.
- none

Iceberg data writer cleanup

---

src/v/cluster/controller.cc
src/v/cluster/controller.h
src/v/cluster/data_migration_frontend.cc
src/v/cluster/data_migration_frontend.h
src/v/cluster/data_migration_table.cc
src/v/cluster/data_migration_table.h

To avoid ambiguity regarding foreign memory.
It's a net addition performance-wise, just adding a level of indirection. But makes things look cleaner. WDYT?
* none

c/migrations: convert migrations table to an ssx::single_sharded

---

tests/rptest/tests/crl_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23721

[v24.2.x] CORE-6977 dt: relax noncogent crl test log whitelist

---

src/v/raft/persisted_stm.cc
src/v/raft/persisted_stm.h
src/v/raft/state_machine_base.cc
src/v/raft/state_machine_base.h
src/v/raft/state_machine_manager.cc
src/v/raft/tests/persisted_stm_test.cc
src/v/raft/tests/stm_manager_test.cc
src/v/raft/tests/stm_test_fixture.h

Fixes https://redpandadata.atlassian.net/browse/CORE-7943
This is related to recent work in https://github.com/redpanda-data/redpanda/commit/e2720105f1e1c377f47eb15bebe4a80f5c9ac825
This PR redoes synchronization around state_machine_base::apply(batch) so that racing snapshots (local snapshots) see a consistent state of the stm. The invariant that is currently violated without this synchronization is the following example.
Example:
```
* last_applied_offset = 10. [ initial state]
* state_machine_base::apply -- tries to apply offset 11
* persisted_stm::apply  -- grabs [persisted_stm::_apply_lock] for offset 11
* rm_stm::do_apply() -- successfully applies 11
** [scheduling points] control is still not back to state_machine_base::apply.. so set_next() is not called.. last_applied_offset  = …
```

raft/state_machine: revisit synchronization around state_machine_base::apply

---

tests/rptest/scale_tests/audit_log_test.py
tests/rptest/scale_tests/many_clients_test.py
tests/rptest/scale_tests/many_partitions_test.py
tests/rptest/services/kafka_cli_consumer.py
tests/rptest/tests/acls_test.py
tests/rptest/tests/archival_test.py
tests/rptest/tests/audit_log_test.py
tests/rptest/tests/compatibility/arroyo_test.py
tests/rptest/tests/consumer_group_test.py
tests/rptest/tests/control_character_flag_test.py
tests/rptest/tests/data_migrations_api_test.py
tests/rptest/tests/e2e_topic_recovery_test.py
tests/rptest/tests/flink_basic_test.py
tests/rptest/tests/librdkafka_test.py
tests/rptest/tests/memory_stress_test.py
tests/rptest/tests/partition_movement_test.py
tests/rptest/tests/random_node_operations_test.py
tests/rptest/tests/rbac_test.py
tests/rptest/tests/rbac_upgrade_test.py
tests/rptest/tests/read_replica_e2e_test.py
tests/rptest/tests/redpanda_kerberos_test.py
tests/rptest/tests/redpanda_oauth_test.py
tests/rptest/tests/redpanda_startup_test.py
tests/rptest/tests/rpk_plugin_test.py
tests/rptest/tests/schema_registry_test.py
tests/rptest/tests/tiered_storage_model_test.py
tests/rptest/tests/upgrade_test.py
tests/rptest/tests/workload_upgrade_runner_test.py
tests/rptest/transactions/compaction_e2e_test.py

Removes `@ok_to_fail` and `@ok_to_fail_fips` annotations from tests. After this merges, no test will produce `OPASS` or `OFAIL` status. However, the `OPassed | OFailed | OPassedFIPS | OFailedFIPS` columns will still be shown in the report. They will be removed on a future PR that updates the reference to ducktape to an ok-to-fail-less branch of our fork (currently being worked on).
In addition, 5 tests that always fail on all environments are disabled with `@ignore` to avoid running them.
fixes https://redpandadata.atlassian.net/browse/DEVPROD-2154
* none

tests: remove `@ok_to_fail` and `@ok_to_fail_fips` annotations

---

src/v/datalake/BUILD
src/v/datalake/CMakeLists.txt
src/v/datalake/base_types.cc
src/v/datalake/base_types.h
src/v/datalake/batching_parquet_writer.cc
src/v/datalake/batching_parquet_writer.h
src/v/datalake/data_writer_interface.cc
src/v/datalake/data_writer_interface.h
src/v/datalake/record_multiplexer.cc
src/v/datalake/record_multiplexer.h
src/v/datalake/tests/gtest_record_multiplexer_test.cc
src/v/datalake/tests/test_data_writer.h

Changed the interface of `datalake::record_multiplexer` to only be responsible of parsing and translating batches from Kafka to Parquet format. The multiplexer returns a range and data files that were successfully written. 
- none

Loosen coupling of `datalake::record_multiplexer`

---

src/go/rpk/pkg/adminapi/admin.go
src/go/rpk/pkg/adminapi/admin_test.go
src/go/rpk/pkg/cli/cluster/license/BUILD
src/go/rpk/pkg/cli/cluster/license/info.go
tests/rptest/tests/rpk_cluster_test.py

This PR adds the output of `/v1/features/enterprise` to `rpk cluster license info`. It also changes the warning message and the cache to be invalidated after 1 hour:
**License loaded:**
```
WARNING: your license will expire soon.
LICENSE INFORMATION
===================
License status:              valid
License violation:           false
Enterprise features in use:  [partition_auto_balancing_continuous]
Organization:                Devex
Type:                        enterprise
Expires:                     Oct 11 2024
```
**No License, Violation:**
```
LICENSE INFORMATION
===================
License status:              not_present
License violation:           true
Enterprise features in use:  [partition_auto_balancing_continuous]
```
**No License, No Violation:**
```
LICENSE INFORMATION …
```

rpk: Add License violations to `rpk cluster info`

---

src/v/datalake/schema_protobuf.cc
src/v/datalake/tests/datalake_protobuf_tests.cc
src/v/datalake/tests/testdata/complex.proto
src/v/datalake/tests/testdata/not_supported.proto
src/v/datalake/values_protobuf.cc

This is a better experience for users than not being able to support
their schema at all.
* none

datalake/protobuf: fallback to strings for uint64_t

---

src/v/test_utils/CMakeLists.txt
src/v/test_utils/gtest_utils.cc
src/v/test_utils/gtest_utils.h
src/v/test_utils/tests/CMakeLists.txt
src/v/test_utils/tests/gtest_listener_test.cc

This PR tries to address feedback given by Travis Downs
> My biggest gripe about gtest is that its assertion macros are by
> default much less useful than everyone else's because you can't use them
> outside of the test method itself (e.g., in a function called by the
> test method) without jumping through a bunch of error-prone hoops. In
> addition to just being annoying writing new tests, it makes sort of
> "rote" migration of boost tests more difficult because assertions that
> break this rule are common. Not all of the issues are caught at compile
> time either, assertions in void-returning methods will compile but not
> stop the test so you may get a different set of errors or a crash,
> ultimately after conversion.
https://google.github.io/googletest/advanced.html#asserting-on-subrou …

test_utils: throw on gtest assert

---

src/v/cluster/CMakeLists.txt
src/v/cluster/feature_manager.cc
src/v/cluster/feature_manager.h
src/v/features/CMakeLists.txt
src/v/features/enterprise_features.cc
src/v/features/enterprise_features.h
src/v/redpanda/admin/api-doc/features.json
src/v/redpanda/admin/server.cc
src/v/redpanda/admin/server.h
tests/rptest/services/admin.py
tests/rptest/tests/enterprise_features_license_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23314 
Closes #23760

[v24.1.x] [CORE-7152] Admin: Introduce  endpoint

---

MODULE.bazel.lock

Fixed formatting of `MODULE.bazel.lock`
- none

bazel: Updated `MODULE.bazel.lock`

---

bazel/install-deps.sh

Adding `sudo` dependency
* none

bazel: add sudo dependency

---

tests/rptest/tests/audit_log_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23804

[v24.2.x] dt/audit: Added missing skip_fips_mode

---

tests/rptest/scale_tests/audit_log_test.py
tests/rptest/scale_tests/many_clients_test.py
tests/rptest/tests/audit_log_test.py
tests/rptest/tests/data_migrations_api_test.py
tests/rptest/tests/librdkafka_test.py
tests/rptest/tests/redpanda_startup_test.py

These tests were unignored in a previous PR because they were thought to be no longer flaky based on testing. However, they still seem to be flaky, making CI red. Let's revert unignoring them to return to the status quo before the PR.
Partially reverts 3ee9ae6b5308353f2e8cf2051c759caede0665fb
* none

dt: revert unignoring some flaky ducktape tests

---

src/v/model/adl_serde.cc
src/v/model/adl_serde.h
src/v/model/metadata.h
src/v/raft/BUILD
src/v/raft/broker_compat.h
src/v/raft/group_configuration.cc
src/v/raft/tests/configuration_serialization_test.cc

The broker_v0 is used for serialization compat. This commit moves its definition into raft which is the only user of the type, rather than storing it in one of the most used headers in the tree.
broker_v0 may actually not be needed any longer, but that will require a different type of analysis.
* none

raft: move broker_v0 definition into raft subsystem

---

src/v/raft/consensus.cc
src/v/raft/tests/BUILD
src/v/raft/tests/CMakeLists.txt
src/v/raft/tests/raft_fixture.h
src/v/raft/tests/snapshot_recovery_test.cc

If snapshot is available when `raft::consensus` starts the term from snapshot should initialize Raft protocol term. This fixes a bug in which a term might have move backward after recovery.
- fixes the term of recovered topic moving backward

r/consensus: use term from snapshot when it is available at startup

---

tests/setup.py

Update ducktape ref that adds the ability to not fail when no test context was loaded. This is useful when ci is instructed to run a test that is skipped in `debug` mode. In such cases ducktape on debug builds fails with an exception raised by the ducktape framework `No tests to run`. 
* none

tests/setup: update ducktape ref

---

src/v/cloud_topics/BUILD
src/v/cloud_topics/CMakeLists.txt
src/v/cloud_topics/app.cc
src/v/cloud_topics/app.h
src/v/redpanda/BUILD
src/v/redpanda/CMakeLists.txt
src/v/redpanda/application.cc
src/v/redpanda/application.h

Hide cloud topics service implementation using pimpl pattern so that less code is exposed into application.{h,cc}.
* none

ct: add an application hook for cloud topics reconciler

---

tests/rptest/tests/rpk_cluster_test.py

/v1/features/enterprise does not redirect the
request to the leader, so the handler reads
directly from the local controller. The state
may not be synchronized, so it's better to retry.
* none

[CORE-7957] tests: wait for license information comparisons

---

src/v/strings/BUILD
src/v/strings/static_str.h
src/v/strings/tests/BUILD
src/v/strings/tests/CMakeLists.txt
src/v/strings/tests/constexpr_string_switch.cc
src/v/strings/tests/static_str_test.cc

static_str wraps a constant string with known static ("indefinite")
lifetime. This useful because constructing and passing such strings from
character constants is very cheap: just a single "copy" of a
pointer-sized value, which can often even be elided. This opens the door
to using this in hot paths where an allocating string might raise
performance concerns.
In a subsequent series, this is used to enhance logging on the reader
cache path.
Relates to CORE-7865.
* none

Add static_str utility class

---

src/v/cluster/tests/BUILD
src/v/cluster/tests/commands_serialization_test.cc
src/v/cluster/tests/local_monitor_test.cc
src/v/cluster/tests/partition_allocator_tests.cc
src/v/cluster/tests/partition_balancer_planner_fixture.h
src/v/cluster/tests/partition_balancer_planner_test.cc
src/v/cluster/tests/producer_state_tests.cc
src/v/cluster/tests/topic_updates_dispatcher_test.cc
src/v/storage/tests/BUILD
src/v/test_utils/BUILD

Fixes: CORE-7412
Fixes: CORE-7448
Fixes: CORE-7450
Fixes: CORE-7456
Fixes: CORE-7426
Fixes: CORE-7458
Fixes: CORE-7459
Fixes: CORE-7416
Fixes: CORE-7440
Fixes: CORE-7415
Fixes: CORE-7455
Fixes: CORE-7443
Fixes: CORE-7441
* none

bazel: backfill some cluster unit tests

---

src/v/kafka/CMakeLists.txt
src/v/kafka/server/BUILD
src/v/kafka/server/app.cc
src/v/kafka/server/app.h
src/v/kafka/server/queue_depth_monitor.h
src/v/kafka/server/queue_depth_monitor_config.h
src/v/kafka/server/server.cc
src/v/kafka/server/server.h
src/v/redpanda/BUILD
src/v/redpanda/application.cc
src/v/redpanda/application.h

redpanda: hide kafka server implementation from application.cc
* none

redpanda: hide kafka server implementation from application.cc

---

src/v/raft/persisted_stm.cc
src/v/raft/persisted_stm.h
src/v/raft/state_machine_base.cc
src/v/raft/state_machine_base.h
src/v/raft/state_machine_manager.cc
src/v/raft/tests/persisted_stm_test.cc
src/v/raft/tests/stm_manager_test.cc
src/v/raft/tests/stm_test_fixture.h

Fixes https://redpandadata.atlassian.net/browse/CORE-7943
This is related to recent work in https://github.com/redpanda-data/redpanda/commit/e2720105f1e1c377f47eb15bebe4a80f5c9ac825
This PR redoes synchronization around state_machine_base::apply(batch) so that racing snapshots (local snapshots) see a consistent state of the stm. The invariant that is currently violated without this synchronization is the following example.
Example:
```
* last_applied_offset = 10. [ initial state]
* state_machine_base::apply -- tries to apply offset 11
* persisted_stm::apply  -- grabs [persisted_stm::_apply_lock] for offset 11
* rm_stm::do_apply() -- successfully applies 11
** [scheduling points] control is still not back to state_machine_base::apply.. so set_next() is not called.. last_applied_offset  = …
```

[backport][v24.2.x] raft/state_machine: revisit synchronization around state_machine_base::apply #23811

---

tools/offline_log_viewer/controller.py
tools/offline_log_viewer/kafka.py
tools/offline_log_viewer/model.py
tools/offline_log_viewer/reader.py
tools/offline_log_viewer/topic_manifest.py

Before this commit offline log viewer would refuse reading envelopes if their version was higher than max_version. That is an overly restrictive constraint. Our envelopes are designed to be forward and backwards compatible so in most of the cases an older implementation of the log viewer should be able to read newer versions of the envelopes just fine.
This commit implements that. Instead of putting a constraint on version we constrain only compat_version like regular redpanda deserialization would do.
Additional changes include issuing a warning if offline log viewer compat version is lower than envelope version. This means that offline log viewer will be able to decode only a subset of the envelope.
And obviously added code to skip over data that can't be read by the offline log viewer. …

offline_log_viewer: allow reading newer versions of envelopes

---

src/v/cluster/data_migration_backend.cc
src/v/cluster/data_migration_types.cc
src/v/cluster/data_migration_types.h
src/v/redpanda/admin/BUILD
src/v/redpanda/admin/api-doc/migration.def.json
src/v/redpanda/admin/data_migration_utils.cc
src/v/redpanda/admin/migrations.cc
tests/rptest/services/admin.py
tests/rptest/tests/data_migrations_api_test.py

As discussed with Matt, accept location hint as part of source topic name when mounting
* none

Migrations accept hint

---

src/v/kafka/server/BUILD
src/v/kafka/server/handlers/list_offsets.cc
src/v/ssx/BUILD
src/v/ssx/tests/BUILD
src/v/ssx/tests/CMakeLists.txt
src/v/ssx/tests/when_all_test.cc
src/v/ssx/when_all.h

Fixes: [CORE-7778](https://redpandadata.atlassian.net/browse/CORE-7778)
- Replaced `std::vector` instances with `chunked_vector`.
- `seastar::when_all_succeed` is hardcoded to use a `std::vector` internally to receive/store the input range and a `std::vector` to return the result. As this was causing further "big allocations", an `ssx::when_all_succeed` utility is introduced that can accept any type of vector-like input range and can output to any type of vector-like container.
No tests where added in respect to oversized allocation memory warnings. Results where only confirmed locally.
* none
[CORE-7778]: https://redpandadata.atlassian.net/browse/CORE-7778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

kafka: oversized alloc in list_offsets_topic

---

MODULE.bazel.lock
bazel/repositories.bzl
src/v/redpanda/admin/cluster_config_schema_util.cc

After some fixes to the seastar json encoder we can now use
`ss::json::stream_object` avoiding oversized allocs that get triggered by using
plain `ss::json::json_return_type`.
* none

Fix an oversized alloc in cluster_config schema endpoint

---

src/v/cloud_topics/batcher/batcher.cc
src/v/model/record_batch_reader.cc
src/v/model/record_batch_reader.h

Remove record batch reader layout interface. More examples of implementations being able to expose their layout should be accumulated before adding a generic interface.
* none

cloud_topics: Remove record batch reader layout interface

---

src/v/kafka/client/BUILD
src/v/kafka/client/CMakeLists.txt
src/v/kafka/client/record_batcher.cc
src/v/kafka/client/record_batcher.h
src/v/kafka/client/test/BUILD
src/v/kafka/client/test/CMakeLists.txt
src/v/kafka/client/test/record_batcher_test.cc
src/v/kafka/client/test/utils.cc
src/v/kafka/client/test/utils.h
src/v/redpanda/application.cc
src/v/security/audit/BUILD
src/v/security/audit/CMakeLists.txt
src/v/security/audit/audit_log_manager.cc
src/v/security/audit/audit_log_manager.h
src/v/transform/logging/BUILD
src/v/transform/logging/CMakeLists.txt
src/v/transform/logging/rpc_client.cc
src/v/transform/logging/tests/BUILD
src/v/transform/logging/tests/CMakeLists.txt
src/v/transform/logging/tests/utils.cc
src/v/transform/logging/tests/utils.h

TODO:
* Fixes a bug where audit log manager would retry a bad request forever, causing buffers to fill up, blocking audit log appends and preventing authZ.

[CORE-7803] Audit Log Manager: Refactoring - use `client::produce_record_batch` and reduce retries.

---

tests/rptest/tests/rpk_cluster_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23842

[v24.1.x] [CORE-7957] tests: wait for license information comparisons

---

bazel/thirdparty/libpciaccess.BUILD

libpciaccess: quiet deprecated API warnings
* none

libpciaccess: quiet deprecated API warnings

---

tests/setup.py

Bump ducktape version to one that is based on 0.11.x but doesn't have `OPASS`/`OFAIL` reporting.
fixes https://redpandadata.atlassian.net/browse/DEVPROD-2121
* none

tests: bump to `0.11.x-redpanda` without ok-to-fail reporting

---

tests/rptest/tests/alter_topic_configuration_test.py

In a mixed mode cluster the describe output from different nodes could be formatted differently depending on property string lenghts. The current check does not factor that in. Example.
```
redpanda.remote.delete                    true        DEFAULT_CONFIG
redpanda.remote.read                      true        DEFAULT_CONFIG
redpanda.remote.write                     true        DEFAULT_CONFIG
```
and
```
redpanda.remote.delete                true        DEFAULT_CONFIG
redpanda.remote.read                  true        DEFAULT_CONFIG
redpanda.remote.write                 true        DEFAULT_CONFIG
```
are treated as unequal. Normalize the output before comparison.
* none

tests/ducktape: tighten property consistency check

---

src/go/rpk/Makefile
src/go/rpk/pkg/cli/topic/BUILD
src/go/rpk/pkg/cli/topic/list.go
src/go/rpk/pkg/cli/topic/list_test.go

Adds --format to topic list
* rpk: add `--format` JSON/YAML support to `rpk topic list`.

rpk: Add format to `rpk topic list`

---

src/v/kafka/client/CMakeLists.txt
src/v/kafka/client/record_batcher.cc
src/v/kafka/client/record_batcher.h
src/v/kafka/client/test/CMakeLists.txt
src/v/kafka/client/test/record_batcher_test.cc
src/v/kafka/client/test/utils.cc
src/v/kafka/client/test/utils.h
src/v/redpanda/application.cc
src/v/security/audit/CMakeLists.txt
src/v/security/audit/audit_log_manager.cc
src/v/security/audit/audit_log_manager.h
src/v/transform/logging/CMakeLists.txt
src/v/transform/logging/rpc_client.cc
src/v/transform/logging/tests/CMakeLists.txt
src/v/transform/logging/tests/utils.cc
src/v/transform/logging/tests/utils.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/23775 
Closes https://github.com/redpanda-data/redpanda/issues/23863

[v24.1.x] [CORE-7803] Audit Log Manager: Refactoring - use  and reduce retries.

---

tests/rptest/tests/upgrade_test.py

rptest: assert consumer invariants after each upgrade
This improves failure result fidelity because we would spot the error
exactly after a bad upgrade rather than at the end of the test.
This also makes it simple(r) to skip validating old versions of
redpanda with newer versions of consumers which check additional
invariants.
This is to prepare for upgrading kgo to a version where it crashes
instantly on data loss on upgrade through some old versions of Redpanda
(around v21, v22). I plan to skip validating these versions and focus
only on latest supported releases instead.
* none

rptest: assert consumer invariants after each upgrade

---

src/v/kafka/server/handlers/list_offsets.cc
src/v/ssx/include/ssx/when_all.h
src/v/ssx/tests/CMakeLists.txt
src/v/ssx/tests/when_all_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/23792

[v24.1.x] kafka: oversized alloc in list_offsets_topic

---

bazel/thirdparty/openssl.BUILD

Don't build openssl tests. These are just a waste of time as we don't need them.
FIPS build is kept as is for FIPS compliance.
* none

bazel: Don't build openssl tests

---

src/v/raft/consensus.cc
src/v/raft/tests/CMakeLists.txt
src/v/raft/tests/raft_fixture.h
src/v/raft/tests/snapshot_recovery_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/23835 
Fixes: #23846

[v24.2.x] r/consensus: use term from snapshot when it is available at startup

---

tests/rptest/tests/upgrade_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23876

[v24.2.x] rptest: assert consumer invariants after each upgrade

---

.github/workflows/scripts/backport-command/create_issue.sh

jira: [DEVPROD-2219]
Change from using branch name like `vbotbuildovich/backport-23614-v24.1.x-917` to
branch name like `manual-backport-23614-v24.1.x-917` to avoid confusion in branch name and remove `/` from branch name.
* none
[DEVPROD-2219]: https://redpandadata.atlassian.net/browse/DEVPROD-2219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

gha: improve backport instructions

---

src/go/rpk/pkg/cli/debug/bundle/bundle_k8s_linux.go

Backport of PR https://github.com/redpanda-data/redpanda/pull/23614
'rpk debug bundle' collects broker UUIDs using the /v1/broker_uuids endpoint.
(cherry picked from commit b134e74b3f26fa77c8af5b92f4a1f9a3f45cf8fe)
* none

[v24.1.x] rpk: debug bundle collecting broker UUIDs

---

BUILD

easier with `bazel run //:{redpanda,rpk}`
* none

bazel: add redpanda and rpk aliases

---

src/v/cluster/partition.h
src/v/cluster/partition_manager.cc
src/v/cluster/partition_manager.h

If registration occurs while a partition is co_await starting, it will be present in the ntp_table and the upcalls will happen both inline with registration and again after the partition is started.
This patch skips callback at time of registration if the partition is in the process of starting, and relies on the callback that is invoked after the partition is started.
* none

cluster: avoid duplicate partition registration callbacks

---

src/go/rpk/pkg/cli/cloud/login.go
src/go/rpk/pkg/cli/connect/client.go
src/go/rpk/pkg/cli/registry/schema/get.go
src/go/rpk/pkg/cli/version/version.go
src/go/rpk/pkg/plugin/plugin.go

This PR includes small bug fixes and improvements:
- a243704332a482ca2ca08162240d644bf6d51511 adds a missing newline on a login information message
- f8f0b5442d7ad6e0ab17278fad9627acde35b748 prevents using `--format` along with `--print-schema`. Previous behavior was to ignore the `--format` flag, which can lead to confusion.
- 18fbda92cae0de957e4e01638f083b45e50a2592 adds a pointer towards `rpk --version` in the `rpk version` help text, as this may be useful for users who only want the rpk version. (better discoverability)
- c40974399b6b2d32e6aced5b2de8fa4a7bcc7110 Increases the plugin download timeout to 300 and also adds support for `RPK_PLUGIN_DOWNLOAD_TIMEOUT` for the plugin download path.
* `rpk registry schema get` will now fail if is incorrectly invoked using the `--print-schema` …

rpk: small improvements prior v24.2

---

src/v/cluster/BUILD
src/v/datalake/coordinator/BUILD
src/v/kafka/server/BUILD
src/v/transform/stm/BUILD

Less components depend on cluster. Nicer build graph.
(Cherry picked from an upcoming PR with cloud topics STM)
* none

bazel: make state_machine_registry.h a module

---

tests/rptest/tests/debug_bundle_test.py

Fixes: [CORE-7839](https://redpandadata.atlassian.net/browse/CORE-7839)
The querying for debug bundle metrics happened directly after the service generation. Occasionally, this led to retrieving stale data. To protect against this, a waiting period has been added when trying to get updated metrics.
* none
[CORE-7839]: https://redpandadata.atlassian.net/browse/CORE-7839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

debug_bundle: fix flaky test

---

src/v/redpanda/admin/api-doc/debug_bundle.def.json

Values are stored as 64-bit numbers and this was causing overflow issues when copied to a 32-bit value.  This addresses that issue.
* none

admin: Updated create_at and size to long type

---

src/v/cloud_topics/BUILD
src/v/cloud_topics/CMakeLists.txt
src/v/cloud_topics/dl_stm/BUILD
src/v/cloud_topics/dl_stm/CMakeLists.txt
src/v/cloud_topics/dl_stm/dl_stm.cc
src/v/cloud_topics/dl_stm/dl_stm.h
src/v/cloud_topics/dl_stm/dl_stm_factory.cc
src/v/cloud_topics/dl_stm/dl_stm_factory.h
src/v/cloud_topics/dl_stm/tests/BUILD
src/v/cloud_topics/dl_stm/tests/dl_stm_test.cc
src/v/redpanda/BUILD
src/v/redpanda/CMakeLists.txt
src/v/redpanda/application.cc

dl_stm scaffolding providing no functionality just yet. just bare bones stm.
* none

ct: dl_stm scaffolding

---

src/go/.goreleaser.yaml

jira: [DEVPROD-996]
Move the homebrew tap formula update out of goreleaser because goreleaser needs to maintain state between release stages that make it difficult to coordinate with our draft release process. Plus, the `goreleaser release --prepare` is a pro-only feature.
* none
[DEVPROD-996]: https://redpandadata.atlassian.net/browse/DEVPROD-996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

goreleaser: rm publish brews

---

src/v/redpanda/admin/server.cc
tests/docker/ducktape-deps/kgo-verifier
tests/rptest/services/failure_injector.py
tests/rptest/services/kgo_verifier_services.py
tests/rptest/tests/data_migrations_api_test.py
tests/rptest/tests/e2e_finjector.py

I broke migration tests in previous attempts to control failure injector so that it doesn't inject too many failures. This is to fix these and other problems leading to test instability.
Running migration tests in a 10x10 loop in https://github.com/redpanda-data/redpanda/pull/23790
* none

Migrations repair tests

---

tests/rptest/tests/data_migrations_api_test.py

rptest: improve failure reporting when waiting for migration

---

src/go/rpk/pkg/cli/profile/create.go
src/go/rpk/pkg/cloudapi/api_virtual_cluster.go

This is available in all of our cloud deployments.
**Example:**
```
$ rpk cloud cluster select                                
? Which cloud resource-group/cluster would you like to talk to? rogger/test-sr
Updated profile "rpk-cloud" to talk to cloud cluster "rogger/test-sr".
Cluster test-sr
Web UI: https://cloud.redpanda.com/clusters/foo/overview
Redpanda Seed Brokers: [foo.any.us-east-1.mpx.prd.cloud.redpanda.com:9092]
$ rpk profile print                                       
name: rpk-cloud
description: Redpanda Production "rogger/test-sr"
prompt: ""
from_cloud: true
cloud_cluster:
resource_group: rogger
cluster_id: bar
cluster_name: test-sr
auth_org_id: baz
auth_kind: sso
cluster_type: TYPE_SERVERLESS
...
schema_registry:
addresses:
- …
```

rpk: fill schema registry information in cloud profiles

---

src/v/model/record_batch_reader.h
src/v/storage/BUILD
src/v/storage/log_reader.cc
src/v/storage/log_reader.h
src/v/storage/readers_cache.cc
src/v/storage/readers_cache.h
src/v/storage/tests/storage_e2e_test.cc
src/v/storage/types.h

During benchmarking it was observed that the number of disk reads was 2x the expected amount from the fetch throughput, with the difference explained by "dropped readahead" (i.e., the readahead that seastar does on disk-backed ss::input_stream). We use the "readers cache" to try to capture this readahead but it was failing to be hit in this case.
There were two underlying bugs:
- Inside the log reader loop when the last iteration finishes without increasing the start offset (which is common, up to 100% chance, for large batches, due to the way the interaction with the slice boundary works) we close the iterator without trying to re-use it. This is a bug in the ordering of re-use checks.
- When we reset the reader on a cache hit, we fail to reset the "_last_base" member, which causes an …

Fix reader cache misses

---

src/v/pandaproxy/schema_registry/test/BUILD
src/v/pandaproxy/schema_registry/test/mt_sharded_store.cc
src/v/pandaproxy/schema_registry/test/storage.cc
src/v/pandaproxy/schema_registry/test/store.cc

bazel: backfill schema registry unit tests
Fixes: CORE-7556
Fixes: CORE-7559
Fixes: CORE-7560
Fixes: CORE-7557
Fixes: CORE-7554
Fixes: CORE-7558
Fixes: CORE-7551
Fixes: CORE-7550
Fixes: CORE-7547
Fixes: CORE-7548
Fixes: CORE-7561
* none

bazel: backfill schema registry unit tests

---

src/v/raft/consensus.cc
src/v/raft/heartbeat_manager.cc
tests/rptest/tests/admin_uuid_operations_test.py
tests/rptest/tests/license_enforcement_test.py

Fix both the follower-side logic (reply with `group_unavailable` instead of failure), and the leader-side logic (ignore heartbeat replies coming from an unexpected node id).
Jira refs:
* https://redpandadata.atlassian.net/browse/CORE-3104
* https://redpandadata.atlassian.net/browse/INC-282
* Ignore heartbeat requests/replies to/from unexpected node ids.

Fix ghost node handling in raft heartbeats

---

src/v/datalake/BUILD
src/v/datalake/record_schema_resolver.cc
src/v/datalake/record_schema_resolver.h
src/v/datalake/schema_identifier.h
src/v/datalake/tests/BUILD
src/v/datalake/tests/record_schema_resolver_test.cc
src/v/iceberg/BUILD
src/v/iceberg/schema_avro.cc
src/v/iceberg/schema_avro.h
src/v/pandaproxy/BUILD
src/v/pandaproxy/schema_registry/avro.cc
src/v/pandaproxy/schema_registry/avro.h
src/v/pandaproxy/schema_registry/fwd.h
src/v/pandaproxy/schema_registry/json.cc
src/v/pandaproxy/schema_registry/json.h
src/v/pandaproxy/schema_registry/protobuf.cc
src/v/pandaproxy/schema_registry/protobuf.h
src/v/pandaproxy/schema_registry/schema_getter.h
src/v/pandaproxy/schema_registry/sharded_store.h
src/v/schema/registry.cc
src/v/schema/registry.h
src/v/schema/tests/fake_registry.cc
src/v/schema/tests/fake_registry.h

Introduces the record_schema_resolver, which takes an iobuf component of a record (e.g. a key or value), parses any schema-related bytes, and returns the translated schema, if any. If there is no schema, or there is a deterministic error, the input buffer in its entirety is returned from the resolver as a binary field.
This only adds this code for Avro schemas. Protobuf will come in a following PR, and the behavior for JSON is to just return the binary value.
This PR also introduces a schema identifier, which are the Kafka components that uniquely identify the Parquet structure (i.e. the schema ID and optional protobuf offsets). This identifier will be passed to the coordinator and it will be the coordinator's job to re-resolve the schema and register it with the catalog. This identifier …

datalake: Avro schema resolution for record components

---

src/v/raft/consensus.cc
src/v/raft/heartbeat_manager.cc
tests/rptest/tests/admin_uuid_operations_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23916 
Fixes https://github.com/redpanda-data/redpanda/issues/23928

[v24.2.x] Fix ghost node handling in raft heartbeats

---

src/v/raft/consensus.cc
src/v/raft/heartbeat_manager.cc
tests/rptest/tests/admin_uuid_operations_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23916 
Fixes https://github.com/redpanda-data/redpanda/issues/23930

[v24.1.x] Fix ghost node handling in raft heartbeats

---

src/v/serde/avro/parser.cc
src/v/serde/avro/tests/parser_test.cc

The test that used incorrect schema to parse a buffer serialized with
avro library, sometimes failed as the parsing didn't throw an error.
Changed the test to check if the behavior of `serde::parser` is the same
as the `::avro::GenericReader`. The test now validates that the outcome
of both parsers is the same.
Additionally added validation of `AVRO_INT` range when decoding its varlong encoded value.
- none

Fixed intermittently failing `AvroParserTest.TestIncorrectSchema`

---

src/v/datalake/coordinator/frontend.cc
src/v/datalake/translation/state_machine.cc

When last translated offset is not updated an offset translation can not be performed as the requested offset is out of translation range. Fixed the problem by returning `model::offset{}` when last translated offset wasn't yet updated.
- none

datalake/stm: fixed translation of of range error

---

src/v/kafka/server/handlers/incremental_alter_configs.cc

`kafka`: fix typo for `alter_broker_configuration()`

---

src/v/kafka/client/BUILD
src/v/kafka/client/CMakeLists.txt
src/v/kafka/client/test/BUILD
src/v/kafka/client/test/CMakeLists.txt
src/v/kafka/client/test/utils.h
src/v/kafka/data/BUILD
src/v/kafka/data/CMakeLists.txt
src/v/kafka/data/record_batcher.cc
src/v/kafka/data/record_batcher.h
src/v/kafka/data/test/BUILD
src/v/kafka/data/test/record_batcher_test.cc
src/v/kafka/data/test/utils.cc
src/v/kafka/data/test/utils.h
src/v/security/audit/BUILD
src/v/security/audit/CMakeLists.txt
src/v/security/audit/audit_log_manager.cc
src/v/transform/logging/BUILD
src/v/transform/logging/CMakeLists.txt
src/v/transform/logging/rpc_client.cc
src/v/transform/logging/tests/CMakeLists.txt

Followup to https://github.com/redpanda-data/redpanda/pull/23775
* none

k/record_batcher: Move to kafka/data

---

.bazelrc
bazel/thirdparty/seastar.BUILD

As discussed in Slack: https://redpandadata.slack.com/archives/C04B8659KGR/p1729095422516709
* none

bazel: enable seastar debug flags in non release build

---

src/v/datalake/BUILD
src/v/datalake/CMakeLists.txt
src/v/datalake/catalog_schema_manager.cc
src/v/datalake/catalog_schema_manager.h
src/v/datalake/tests/BUILD
src/v/datalake/tests/CMakeLists.txt
src/v/datalake/tests/catalog_schema_manager_test.cc

Adds a new component the catalog_schema_manager to get field IDs from the Iceberg catalog, potentially registering a new schema if there are missing fields in the catalog.
This will be the place we can make decisions about schema evolution. As is, the implemented policy is that as long as fields are added to the end of the table, the schema can be added. This is so that we can support going from the default schema to the default schema + user defined columns, but has the effect of also letting us support schema evolution in a limited form.
In the short term, for simplicity, I expect this to live along side the datalake workers, where each worker will call into the schema manager when constructing a parquet writer with a given schema to get the correct field IDs. Longer term, for scale, …

datalake: add catalog schema manager

---

src/v/cluster/archival/archival_policy.cc
src/v/cluster/archival/archival_policy.h
src/v/cluster/archival/tests/BUILD
src/v/cluster/archival/tests/CMakeLists.txt
src/v/cluster/archival/tests/archival_policy_test.cc
src/v/storage/offset_to_filepos.h

Supersedes https://github.com/redpanda-data/redpanda/pull/19009.
Previous PRs cover letter:
> convert_begin_offset_to_file_pos can undershoot, in which case the
> metadata returned by the archival policy won't perfectly align with the
> caller's expectations. This could result in an offset_overlap when
> applying the upload metadata.
> 
> It's unclear exactly why there are missing batches, given this code is
> used for the non-compacted uploader. But the fix is simple enough, and
> is one that we use in the compacted upload policy already[1].
> 
> [1] https://github.com/redpanda-data/redpanda/blob/4b8135ea5dbdca322ccf8efc85424413a20c5ade/src/v/archival/segment_reupload.cc#L516-L522
* Fixes a bug in which upload candidates made from segments with missing batches would trigger metadata …

`archival`: bump offset if seeking undershoots

---

src/v/serde/parquet/BUILD
src/v/serde/parquet/CMakeLists.txt
src/v/serde/parquet/README.md
src/v/serde/parquet/schema.cc
src/v/serde/parquet/schema.h
src/v/serde/parquet/shredder.cc
src/v/serde/parquet/shredder.h
src/v/serde/parquet/tests/BUILD
src/v/serde/parquet/tests/schema_test.cc
src/v/serde/parquet/tests/shredder_test.cc
src/v/serde/parquet/tests/value_test.cc
src/v/serde/parquet/value.cc
src/v/serde/parquet/value.h

- **parquet/value: support struct types**
- **parquet/value: add formatter for values**
- **parquet/schema: add indexed schema element**
- **serde/parquet: record shredding algorithm implementation**
* none

parquet: dremel record shredding algorithm

---

src/v/raft/persisted_stm.cc
src/v/raft/persisted_stm.h
src/v/raft/state_machine_base.cc
src/v/raft/state_machine_base.h

Allow to wait for offsets to be applied using a const reference to state machine. I have a use-case in another PR where where I want to enforce read-only access to STM state to prevent accidental direct state mutation rather than via consensus::replicate but I need to wait for results to be applied.
* none

raft: const wait and wait_no_throw

---

src/v/cluster/cloud_metadata/tests/cluster_recovery_backend_test.cc
src/v/cluster/cluster_recovery_reconciler.cc
src/v/cluster/controller_stm.cc
src/v/cluster/controller_stm.h
src/v/cluster/feature_manager.cc
src/v/cluster/metrics_reporter.cc
src/v/features/feature_table.cc
src/v/features/feature_table.h
src/v/features/feature_table_snapshot.cc
src/v/features/tests/BUILD
src/v/features/tests/feature_table_test.cc
src/v/model/timestamp.h
src/v/redpanda/admin/server.cc
tests/rptest/services/admin.py
tests/rptest/services/redpanda.py
tests/rptest/tests/cluster_features_test.py
tests/rptest/tests/enterprise_features_license_test.py
tests/rptest/tests/license_enforcement_test.py
tests/rptest/tests/license_upgrade_test.py
tests/rptest/tests/rbac_test.py
tests/rptest/tests/rbac_upgrade_test.py
tests/rptest/tests/redpanda_kerberos_test.py
tests/rptest/tests/redpanda_oauth_test.py
tests/rptest/tests/redpanda_startup_test.py
tests/rptest/tests/rpk_cluster_test.py
tests/rptest/tests/schema_registry_test.py

Create a builtin fallback license that allows customers to trial
Enterprise features for a trial period starting at cluster creation.
Fixes https://redpandadata.atlassian.net/browse/CORE-7996
* After the cluster is first formed, a trial license is automatically loaded to provide an evaluation period of enterprise features.

CORE-7996 Trial: build in an evaluation period license

---

MODULE.bazel
src/go/rpk/go.mod
src/go/rpk/go.sum
src/go/rpk/pkg/adminapi/BUILD
src/go/rpk/pkg/adminapi/admin.go
src/go/rpk/pkg/adminapi/admin_test.go
src/go/rpk/pkg/cli/cluster/license/info.go

If it's a free trial license the expiry warning
check threshold will be set to 15 days instead of
30 for the rest of the license types.
Fixes DEVEX-36 and DEVEX-37
* None

[DEVEX-36] rpk: change expiry check for free_trial

---

src/v/iceberg/manifest_entry_type.cc
src/v/iceberg/manifest_entry_values.cc

The `distinct_count` is not part of iceberg manifest_entry schema definition. Having the field in Redpanda iceberg manifest entry definition lead to issues when querying iceberg metadata with pyicebrg library.
- none

iceberg/manifest_entry: fixed manifest entry avro serialization

---

src/v/iceberg/manifest_entry_values.cc

Iceberg is a bit inconsistent when defining this. Some libraries (pyiceber in particular) requires it to be upper case string. For Redpanda the case doesn't matter as we always lower case the value when parsing it.
- none

iceberg: use uppercase strings to represent data file format

---

src/v/datalake/arrow_translator.cc
src/v/datalake/tests/parquet_writer_test.cc

According to Iceberg specification the `PARQUET:field_id` metadata value is used to find columns using the id of a field in Iceberg schema. Added missing metadata to parquet files written by
`datalake::arrow_translator`.
- none

datalake/arrow: added parquet field_id metadata when writing data files

---

src/v/datalake/BUILD
src/v/datalake/CMakeLists.txt
src/v/datalake/schema_avro.cc
src/v/datalake/schema_avro.h
src/v/datalake/tests/BUILD
src/v/datalake/tests/CMakeLists.txt
src/v/datalake/tests/datalake_avro_tests.cc
src/v/iceberg/datatypes.cc
src/v/iceberg/datatypes.h
src/v/iceberg/tests/datatypes_test.cc

Added conversion of AVRO to Iceberg schema.  
If a top level AVRO type is different than AVRO record the method will return a struct type with single filed being a top level type.
Most important limitations/assumptions:
- do not support recursive types
- avro maps are interpreted as list of key-value pairs
- avro unions are 'flattened' as a structure with optional fields out of
which only one or none are present (i case ther is a field with null type)
- all fields are required by default (avro always sets a default in binary
representation)
- duration logical type is ignored
- avro null type is ignored and not represented in iceberg schema
- different flavours of timestamp and time types are all represented by the
same iceberg type, conversion will be done when parsing avro value
Useful …

AVRO to Iceberg schema conversion for datalake

---

tests/rptest/scale_tests/large_messages_test.py

Disabling large messages test based on Slack conversation:
https://redpandadata.slack.com/archives/C07HL3GJ282/p1729625039588029?thread_ts=1729623975.439799&cid=C07HL3GJ282
Jira: https://redpandadata.atlassian.net/browse/DEVPROD-2066
* none

Disabling large_messages_test

---

src/go/rpk/go.mod
src/go/rpk/go.sum
src/go/rpk/pkg/adminapi/admin.go
src/go/rpk/pkg/adminapi/admin_test.go
src/go/rpk/pkg/cli/cluster/license/info.go

Manual Backport of https://github.com/redpanda-data/redpanda/pull/23951
The difference is the BUILD files.
* none

[v24.2.x] [DEVEX-36] rpk: change expiry check for free_trial

---

src/go/rpk/go.mod
src/go/rpk/go.sum
src/go/rpk/pkg/adminapi/admin.go
src/go/rpk/pkg/adminapi/admin_test.go
src/go/rpk/pkg/cli/cluster/license/info.go

Manual Backport of https://github.com/redpanda-data/redpanda/pull/23951
The difference is the BUILD files and lack of common-go in v24.1.x
* none

[v24.1.x] [DEVEX-36] rpk: change expiry check for free_trial 

---

src/transform-sdk/go/transform/internal/testdata/CMakeLists.txt

This was only added for custom logging we put in tinygo, but we will remove that now that we're using upstream tinygo and not a fork.
* none

transform-sdk/go/tests: remove -quiet flag

---

src/v/config/base_property.h
src/v/config/configuration.cc
src/v/config/configuration.h
src/v/config/property.h
src/v/config/tests/CMakeLists.txt
src/v/config/tests/enterprise_property_test.cc
src/v/redpanda/admin/server.cc
tests/rptest/tests/enterprise_features_license_test.py
tests/rptest/tests/redpanda_kerberos_test.py
tests/rptest/tests/redpanda_oauth_test.py
tests/rptest/tests/schema_registry_test.py

- small change to make a property "enterprise only"
- add the wrapper template and update constructor call w/ restricted values
- change isolated to property _definition_, use as normal throughout codebase
- enforcement is effectively optional from the compiler's perspective
- and the logic to perform it can be isolated to admin
- works for arbitrary types (arrays, optionals, subclasses of `property` etc) and can be extended to others incl support for "custom" check for aggregates or whatever
- Looks bizarre 🙃 
- slightly un-ergonomic to construct. 
- variadic template prevents type deduction on initializer lists, so containers and aggregates need to be  explicit at the call site
- arguably the information encoded here feels a bit unnatural as a property of a `config::property`.
* none

[CORE-7997] Suppress enterprise configs when license is missing or expired

---

tests/rptest/chaos_tests/single_fault_test.py

The chaos suite is about to be added to the daily re-runs of `dev`. Since these are known to likely fail in `debug` releases, it is better to skip these for now
* none

tests: skip chaos tests on debug release

---

src/v/cluster/feature_manager.cc
src/v/features/enterprise_features.h

Ensure that the listed enterprise features are delimited by a comma and that it is not easy to format the collection of enterprise features incorrectly.
This is effectively another round of the same change as https://github.com/redpanda-data/redpanda/pull/23640/commits/b2012c3504e391f690887f4abe75d5e5a81e9ce5, but there this third log line was missed.
* none

cluster: fix log message formatting

---

src/go/rpk/pkg/adminapi/admin.go

If the message was empty, we would print new lines to stderr
* none

rpk: fix printing new lines

---

tests/rptest/tests/enterprise_features_license_test.py

The default OIDC server is flaky in CI, so ignore the related error logs in the background updater using `OIDC_UPDATE_FAILURE_LOGS`.
Alternatively, we could create a local `KeyCloak` OIDC Authorization Server which would be reliably available locally, but it's not simple to configure, so it's simpler to ignore the error logs for the purpose of these tests.
Fixes https://redpandadata.atlassian.net/browse/CORE-7870
* none

CORE-7870 dt: ignore OIDC background errors in license tests

---

src/v/datalake/BUILD
src/v/datalake/CMakeLists.txt
src/v/datalake/catalog_schema_manager.cc
src/v/datalake/catalog_schema_manager.h
src/v/datalake/fwd.h
src/v/datalake/record_multiplexer.cc
src/v/datalake/record_multiplexer.h
src/v/datalake/record_schema_resolver.cc
src/v/datalake/record_schema_resolver.h
src/v/datalake/record_translator.cc
src/v/datalake/record_translator.h
src/v/datalake/tests/BUILD
src/v/datalake/tests/CMakeLists.txt
src/v/datalake/tests/catalog_and_registry_fixture.h
src/v/datalake/tests/catalog_schema_manager_test.cc
src/v/datalake/tests/gtest_record_multiplexer_test.cc
src/v/datalake/tests/record_generator.cc
src/v/datalake/tests/record_generator.h
src/v/datalake/tests/record_multiplexer_test.cc
src/v/datalake/tests/record_schema_resolver_test.cc
src/v/datalake/tests/translation_task_test.cc
src/v/datalake/translation/partition_translator.cc
src/v/datalake/translation_task.cc
src/v/datalake/translation_task.h

This PR fulfills the record_multiplexer's destiny in writing data across multiple files. There are two dimension on which we will write multiple files:
- by Iceberg partition key (the hour of the record timestamp)
- by the record value's schema, as resolved by the
record_schema_resolver
The former is already encapsulated entirely within partitioning_writer, so the record_multiplexer just needs to maintain a collection thereof.
A couple of companions have joined to help the record_multiplexer in its journey: the schema manager, to register new schemas and fetch field IDs; and the type resolver, to determine the schema from a given record.  These will likely be owned by the datalake manager, and for now, have stub implementations where needed.
A follow-up change will plumb the schema …

datalake: write multiple files from record_multiplexer

---

src/v/features/feature_table.h
tests/rptest/scale_tests/shard_placement_scale_test.py
tests/rptest/tests/partition_move_interruption_test.py
tests/rptest/tests/partition_movement.py
tests/rptest/tests/partition_movement_test.py
tests/rptest/tests/shard_placement_test.py
tests/rptest/tests/topic_delete_test.py

Jira ref: https://redpandadata.atlassian.net/browse/CORE-7952
* Enable `node_local_core_assignment` feature by default

features: activate node_local_core_assignment automatically

---

src/v/cluster/feature_manager.cc
tests/rptest/tests/leadership_transfer_test.py

When reporting which features are enabled, for leadership pinning, the "default_leaders_preference" config property and each topic's "redpanda.leaders.preference" property were checked. However, for the latter, it was only checked whether the optional had a value and not what that value actually is.
* none

cluster: Fix leadership pinning minor reporting bug

---

tests/docker/ducktape-deps/java-dev-tools

It appears debian packaging prefers arm64 over aarch64 naming. Fix the check accordingly.
* none

ducktape/java: download java22 for  arm64 arch correctly

---

src/v/redpanda/admin/debug.cc
tests/rptest/tests/memory_sampling_test.py

Fixes an off by one when validating the shard id in both the memory and
cpu profiler.
* none

samplers: Fix off by one shard id check

---

src/v/cluster/data_migration_frontend.cc
src/v/cluster/data_migration_table.cc
src/v/cluster/data_migration_table.h
src/v/cluster/errc.h
src/v/cluster/errors.cc
src/v/cluster/tests/data_migration_table_test.cc
src/v/kafka/server/errors.h
src/v/redpanda/admin/server.cc
tests/rptest/tests/data_migrations_api_test.py

Make migration creation admin API endpoint respond with more distinct errors.
* none

Migrations distinct error codes

---

MODULE.bazel.lock
bazel/repositories.bzl
src/v/net/server.cc

Setting of the TCP receive and send buffers needs to happen prior to
`listen`/`connect`.
However, on the server side we currently set it on the accepted socket.
This results in it only semi working. While the buffers do get sized
correctly it has no effect on the receive/send window which is the main
purpose.
We extended seastar to allow setting the buffers settings on the
listening socket. This patch makes use of that API.
Ref CORE-7753
* none

net: Fix setting of TCP send/recv bufs

---

src/v/raft/configuration_bootstrap_state.h
src/v/raft/configuration_manager.cc
src/v/raft/configuration_manager.h
src/v/raft/consensus.cc
src/v/raft/consensus_utils.h

When extracting configurations from a range of batches the configuration vector may grow pretty large. Replaced `std::vector` with `chunked_vector` to prevent large allocations.
- fixed large allocation in Raft implementation

r/consensus_utils: use chunked vector when extracting configurations

---

src/v/cluster/metrics_reporter.cc
src/v/cluster/metrics_reporter.h
tests/rptest/tests/metrics_reporter_test.py

Flat list of feature names, only those which are currently enabled
Fixes: CORE-8138
* none

metrics: Add list of enterprise features to call-home POST

---

.clang-tidy
BUILD
src/v/CMakeLists.txt
src/v/base/seastarx.h
src/v/cloud_topics/batcher/tests/aggregator_test.cc

clang-tidy: make WarningsAsErrors match cmake clang tidy config

---

src/v/base/vlog.h
src/v/kafka/server/handlers/fetch.cc
tests/rptest/tests/audit_log_test.py

When audit logging is enabled and the license has expired or is absent,
then any attempt to fetch data from the audit log will be denied.
Note that Redpanda will continue to produce data to the audit log even
when the license has expired so customers will be able to see their
historical audit data once a valid license is set.
Fixes https://redpandadata.atlassian.net/browse/CORE-8032
* none

CORE-8032 Audit log sanctioning

---

tests/rptest/services/spark_service.py
tests/rptest/services/trino_service.py
tests/rptest/tests/datalake/datalake_e2e_test.py
tests/rptest/tests/datalake/datalake_services.py
tests/rptest/tests/datalake/query_engine_base.py
tests/rptest/tests/datalake/query_engine_factory.py
tests/rptest/tests/datalake/spark_sql_server_smoke_test.py
tests/rptest/tests/datalake/trino_smoke_test.py

Refactors the interfaces to abstract out query engine specifics into a base class and enables plugging in required SQL engines at test time. Refactored existing end-to-end with parameterization as an example.
* none

datalake/tests: enable parametrizing datalake tests across query engines / catalog modes

---

src/v/serde/parquet/BUILD
src/v/serde/parquet/CMakeLists.txt
src/v/serde/parquet/column_writer.cc
src/v/serde/parquet/column_writer.h
src/v/serde/parquet/encoding.cc
src/v/serde/parquet/encoding.h
src/v/serde/parquet/metadata.cc
src/v/serde/parquet/metadata.h
src/v/serde/parquet/schema.cc
src/v/serde/parquet/schema.h
src/v/serde/parquet/shredder.cc
src/v/serde/parquet/shredder.h
src/v/serde/parquet/tests/encoding_test.cc
src/v/serde/parquet/tests/generate_metadata.cc
src/v/serde/parquet/tests/schema_test.cc
src/v/serde/parquet/tests/shredder_test.cc
src/v/serde/parquet/value.cc
src/v/serde/parquet/value.h

- **parquet: remove logical value types**
- **parquet: use strongly typed crc value from absl**
- **parquet: encode the max rep and def levels in schema nodes**
- **parquet: add validation that required nodes are not null**
- **parquet: add column writer**
- **parquet: use named types for rep and def levels**
Note that there are currently no tests for the column writer. This sucks but there is not an external go library
that directly exposes the ability to read/write pages so it'd be hard to test. There will be test coverage when
we write full parquet files - that's kind of the best I can do for now :shrug:
Thankfully, the code there is not too complex so I feel pretty good about only being able to test indirectly.
* none

parquet: introduce column writer

---

src/v/datalake/CMakeLists.txt
src/v/datalake/datalake_manager.cc
src/v/datalake/datalake_manager.h
src/v/datalake/translation/partition_translator.cc
src/v/datalake/translation/partition_translator.h
src/v/redpanda/application.cc
src/v/redpanda/application.h
tests/rptest/services/spark_service.py
tests/rptest/tests/datalake/datalake_e2e_test.py
tests/rptest/tests/datalake/datalake_services.py
tests/rptest/tests/datalake/query_engine_base.py

Plumbs the schema registry and an Iceberg catalog to the datalake manager so they can be used by translation tasks to resolve schemas and register them with Iceberg.
It's noteworthy that the workers now own another instance of the Iceberg catalog (in addition to the coordinators owning one). Longer term we may want to have workers RPC out to coordinators and have all catalog communication happen on coordinators.
Also adds some updates to ducktape to exercise the new schema registration with Trino and Spark.
* none

datalake: plumb schema management into datalake worker

---

bazel/test.bzl
src/v/datalake/coordinator/tests/BUILD
src/v/datalake/coordinator/tests/CMakeLists.txt
src/v/datalake/tests/BUILD
src/v/datalake/tests/CMakeLists.txt
src/v/iceberg/tests/BUILD
src/v/iceberg/tests/CMakeLists.txt

Preventing tests using `s3_impostor` from running in parallel with each other to prevent listen port conflict. 
- none

Preventing tests using s3_impostor from running in parallel 

---

src/v/datalake/coordinator/frontend.cc
src/v/datalake/coordinator/frontend.h
src/v/datalake/tests/fixture.h
tests/rptest/tests/datalake/datalake_e2e_test.py

An inherent assumption in coordinator implementation is that all topic/table related operations are performed by the same coordinator for correctness (so we have one active writer per table active at most times). This is particularly relevant in filesystem catalog implementation as it relies on the filesystem for concurrency and multiple interleaved writers can leave it in a questionable state.
This expectation is violated in our coordinator hash function that factors in topic and partition as input to the hash function resulting in ntps from same topic hashing to different coordinator partitions.
* none

datalake/translation: fix data partition to coordinator mapping

---

src/v/datalake/coordinator/frontend.cc
src/v/datalake/coordinator/frontend.h
src/v/datalake/coordinator/rpc.json
src/v/datalake/coordinator/service.cc
src/v/datalake/coordinator/service.h
src/v/datalake/coordinator/types.cc
src/v/datalake/coordinator/types.h
src/v/datalake/tests/fixture.h
src/v/datalake/translation/partition_translator.cc

This API evolved over time, originally meant to fetch the latest translated file metadata from the coordinator but later simplified to fetch only the translated offset. Rename the types accordingly, no logic changes.
* none

datalake/coordinator/api: rename fetch_latest_data_file types

---

src/go/rpk/pkg/cli/profile/create.go
src/go/rpk/pkg/config/config.go
src/go/rpk/pkg/config/params.go
src/go/rpk/pkg/config/params_test.go
src/go/rpk/pkg/config/redpanda_yaml.go
src/go/rpk/pkg/config/weak.go
src/go/rpk/pkg/config/weak_test.go

* Adds support for setting schema registry connection parameters in the `rpk` stanza of `redpanda.yaml`.

Allow setting schema registry configuration parameters via the RPK node config block

---

src/v/storage/disk_log_impl.cc
src/v/storage/segment_index.h
src/v/storage/segment_utils.cc
src/v/storage/segment_utils.h

A call to `maybe_set_clean_compact_timestamp()` should be followed by a call to `flush()` in order to persist the clean compact timestamp to disk.
Without a call to `flush()`, a broker failure could potentially make compaction/tombstone removal less efficient than it could be (as the earliest clean compact timestamp could be lost).
Make `mark_segment_as_finished_window_compaction()` async and add a call to `flush()` in case it is required (`maybe_set_clean_compact_timestamp()` now returns a boolean indicating whether or not the timestamp was set).
* none

`storage`: add calls to `segment_index::flush()` in compaction

---

src/v/cluster/metrics_reporter.cc
src/v/cluster/metrics_reporter.h
tests/rptest/tests/metrics_reporter_test.py

Adds a number of new nodes associated with the broker's address to the report:
* `hostname` - the reported hostname of the node sending the report
* `domainname` - the reported domain name of the node sending the report
* `fqdns` - List of FQDN's of the node sending the report
* `nodes.kafka_advertised_listeners` - List of Kafka Advertised listeners for all nodes in the cluster
* None

[CORE-8141] Add host information to metrics report

---

src/v/kafka/group_probe.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/23339

[v24.2.x] Remove shard aggregation on consumer group metrics

---

tests/rptest/services/redpanda.py

The pmap logic often seems to fail (I suspect a race condition between
getting the processe list and checking the processes) but it also seems
quite useless to me. The process memory mappings are only useful in some
niche debugging usecases. Hence remove.
* none

dt: Don't run pmap

---

src/v/cluster/security_frontend.cc
src/v/kafka/server/server.cc
src/v/redpanda/admin/security.cc
src/v/redpanda/admin/server.cc
src/v/redpanda/admin/server.h
tests/rptest/tests/enterprise_features_license_test.py
tests/rptest/tests/rbac_test.py

This PR implements enterprise sanctions on the Core RBAC feature. This includes sanctioning (i.e. preventing users from):
- creating new roles (Admin API)
- adding/removing members from existing roles (Admin API)
- Adding Role-based ACLs (Kafka API)
- ~Deleting Role-based ACLs (Kafka API)~
- ~Error reporting on the security frontend tends to be "all or nothing", so we match that here - if _any_ filter in a DeleteAcls request matches a Role-bound ACL, the whole request must be rejected.~
- ~At some point in the future, we may want to consider something more granular - e.g. requests that fail partially or are rejected only partially, but that would (I think) require revisiting error reporting code beyond the scope of this PR.~
- DeleteACLs sanctions were dropped from the requirements …

[CORE-8029] - RBAC Sanctions

---

src/v/cluster/metrics_reporter.cc
src/v/cluster/metrics_reporter.h
tests/rptest/tests/metrics_reporter_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/24023
Fixes: Fixes: CORE-8174

[v24.1.x] [CORE-8141] Add host information to metrics report

---

tests/rptest/services/redpanda.py
tests/rptest/tests/acls_test.py
tests/rptest/tests/admin_uuid_operations_test.py
tests/rptest/tests/alter_topic_configuration_test.py
tests/rptest/tests/end_to_end.py
tests/rptest/tests/partition_movement_test.py
tests/rptest/tests/prefix_truncate_recovery_test.py
tests/rptest/tests/random_node_operations_test.py
tests/rptest/tests/read_replica_e2e_test.py
tests/rptest/tests/redpanda_test.py
tests/rptest/tests/rpk_cluster_test.py
tests/rptest/tests/self_test_test.py
tests/rptest/tests/upgrade_test.py
tests/rptest/tests/workload_upgrade_runner_test.py
tests/rptest/transactions/transactions_test.py

Now that Redpanda comes with a built-in evaluation period, there is no need to attempt to install a license to run these tests.  This reduces developer effort because they no longer will need to download a sample license and configure it on their system in order to run these ducktape tests locally.
* None

CORE-8106 dt: Removed calls to install_license

---

src/v/storage/tests/compaction_e2e_test.cc

To avoid race-y failures.
Ran locally with `RP_FIXTURE_ENV=1 vbuild/debug/clang/bin/gtest_storage_e2e_rpfixture --gtest_filter="*TestTombstones*" -c 1 --gtest_repeat=1000 --gtest_break_on_failure`
* none

`storage`: modify sleep timers in `compaction_e2e_test`

---

src/v/cluster/topics_frontend.cc
src/v/kafka/server/tests/create_topics_test.cc
src/v/kafka/server/tests/topic_properties_helpers.h

Implement sanctions for tiered storage topic creation.
* none

[CORE-7999] Tiered storage sanctioning for topic creation

---

src/v/cloud_storage/cache_service.cc
src/v/cloud_storage/tests/cache_test.cc
src/v/test_utils/iostream.h
src/v/utils/tests/input_stream_fanout_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/24000 
Closes #24056

[v24.1.x] cleanup tiered storage temporary cache file if exceptions are thrown during download

---

tests/rptest/tests/test_si_cache_space_leak.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/22796
Fixes: https://github.com/redpanda-data/redpanda/issues/24069,

[v24.1.x] rptest: reduce cache eviction throttling for space leak test

---

src/v/cloud_io/remote.cc
src/v/cloud_storage_clients/BUILD
src/v/cloud_storage_clients/util.cc
src/v/cloud_storage_clients/util.h

The call to `drain_response_stream` may throw various transport related errors (see one example below of a broken pipe error observed in CI). These errors should be handled inside the `remote::download_object` method because the caller's expectation is that download-related errors are communicated via the `download_result` return type rather than through an exception. Some of these errors (like the broken pipe error below) could also be retried, whereas with the previous implementation, they were not retried.
These exceptions are often ignored by the caller and may be printed as "Exceptional future ignored" log lines, which cause CI failures and are less useful for debugging.
The below is an example of one such ignored exceptional future in the remote partition finalizing background …

CORE-8082 cloud_io: add missing error handling to `remote::download_object`

---

src/v/cluster/topic_configuration.h
src/v/cluster/topics_frontend.cc
src/v/cluster/types.h
src/v/kafka/server/tests/create_topics_test.cc

Sanctions enabling schema ID validation on the topic create path, building on existing bits and pieces for enforcing a similar policy on tiered storage.
Note that this _only_ sanctions "enable" style properties - the strategy selection props are ignored, since they are effectively no-op without validation enabled.
CORE-8102
* none

c/topics: Implement schema ID validation sanctions (topic create)

---

src/v/cluster/controller_backend.cc
src/v/cluster/partition.cc
src/v/cluster/partition.h
src/v/raft/consensus.cc
tests/rptest/tests/partition_force_reconfiguration_test.py

When force recovering partition the controller backend logic decides
which partition replica should be a voter and by that which partition
replica can become a leader. The default policy in controller backend
added all survivor replicas to the voter set, this way promoting their
local state as the source of truth for the partition data.
In some rare scenarios it may be the case that he survivor local state
is 'behind' the state from the cloud. In this case controller backend
should recognize that is is more beneficial to use cloud data as a
source of truth.
This commit adds a controller backend logic that reconciles with the
cloud and selects whichever state is more up to date when executing
partition force reconfiguration. If cloud offset is greater than the
replica dirty offset, the …

CORE-8172 Changed force recovery logic to select whichever state is more up to date from local and cloud data

---

src/v/net/transport.cc

There were two locations in which the `seastar::logger` was being used directly in `transport.cc` instead of the `vlog()` macro we default to using in `redpanda`.
Alter those two logging sites to use the `vlog()` macro.
* none

`net`: use `vlog()` macro in `transport.cc` logging

---

tests/rptest/tests/delete_records_test.py

This test uses two threads to perform prefix truncations while moving partition leadership around. `rpk.describe_topic()` may return a `NOT_LEADER_FOR_PARTITION` result during this process, leading to a failed assert.
Wrap the command in a `wait_until_result()` call in order to avoid race-y failures.
JIRA Link: https://redpandadata.atlassian.net/browse/CORE-7770
* none

[CORE-7770]: `rptest`: use `wait_until_result` wrapper in `delete_records_test.py`

---

src/v/cluster/controller.cc
src/v/cluster/partition_balancer_backend.cc
src/v/cluster/partition_balancer_backend.h
src/v/cluster/shard_balancer.cc
src/v/cluster/shard_balancer.h
src/v/config/property.h
src/v/config/tests/enterprise_property_test.cc
src/v/features/BUILD
src/v/features/enterprise_features.h
src/v/features/tests/BUILD
src/v/features/tests/CMakeLists.txt
src/v/features/tests/enterprise_features_test.cc
tests/rptest/tests/partition_balancer_test.py
tests/rptest/tests/shard_placement_test.py

Implements: [CORE-8014](https://redpandadata.atlassian.net/browse/CORE-8014)
Implement sanction(s) on partition autobalancer continuous mode. 
If there is no valid license and `partition_autobalancing_mode` is set to `continuous`, the setting will be ignored and it will revert to `node_add` behavior.
Implements: [CORE-8041](https://redpandadata.atlassian.net/browse/CORE-8041)
Implement sanction(s) on core balancing continuous property. 
If there is no valid license and `core_balancing_continuous` is set, the setting will be ignored.
* none
[CORE-8014]: https://redpandadata.atlassian.net/browse/CORE-8014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CORE-8041]: https://redpandadata.atlassian.net/browse/CORE-8041?atlOrigin=eyJpIjoiNWRkNTljNzYxN …

cluster: Implement sanctions on autobalancer features on invalid license

---

tests/rptest/tests/archive_retention_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/18567
Fixes: https://github.com/redpanda-data/redpanda/issues/24061,

[v24.1.x] [CORE-1478] rptest: fix retention value in `archive_retention_test`

---

src/v/cloud_storage/remote.cc
src/v/cloud_storage_clients/util.cc
src/v/cloud_storage_clients/util.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/24059 
Fixes https://github.com/redpanda-data/redpanda/issues/24077
Cherry pick conflicts:
* BAZEL build not present earlier
* `remote.cc` has moved to a different path

[v24.1.x] CORE-8082 cloud_io: add missing error handling to 

---

src/v/iceberg/table_io.cc
src/v/iceberg/uri.h

Azure Blob Storage uses `abs://` as a protocol scheme. For Iceberg metadata locations to work they have to include the correct uri.
- none

iceberg/table_io: support azure protocol scheme

---

src/v/cloud_storage/remote.cc
src/v/cloud_storage_clients/BUILD
src/v/cloud_storage_clients/util.cc
src/v/cloud_storage_clients/util.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/24059 
Fixes https://github.com/redpanda-data/redpanda/issues/24076
Cherry pick conflicts:
* `remote.cc` has moved to a different path

[v24.2.x] CORE-8082 cloud_io: add missing error handling to 

---

src/v/cluster/topic_table.cc
src/v/cluster/topic_table.h
src/v/cluster/topics_frontend.cc
src/v/kafka/server/tests/alter_config_test.cc
src/v/kafka/server/tests/topic_properties_helpers.h

Implement sanctioning for altering tiered storage topic configs.
Notes to reviewer:
* Is it ok that this misses the `validate_only` flag?
* Is it required to check the diff after the `linearizable_barrier`?
* Is it ok that this can now fail? For example `topic_recovery_service::reset_topic_configurations`
* none

[CORE-8000] tiered storage sanctioning for alter topics

---

src/v/storage/disk_log_impl.cc

This assertion can be triggered if a the configuration for a topic is changed between when space management sets the `_cloud_gc_offset` to when gc actually runs on the log. So to avoid crashing in this case the assertion is changed to an early return and a warning is logged instead.
Fixes CORE-8070
* none

storage: remove assertion on `is_cloud_retention_active`

---

MODULE.bazel.lock
bazel/repositories.bzl

bazel: Updated seastar ref

---

src/v/cluster/security_frontend.cc
src/v/kafka/server/server.cc

When a user tries to create a Role-bound ACL, we return an UNKNOWN_SERVER_ERROR to the Kafka API request and print this log message.
This log message should clarify that the reason for rejecting the ACL creation request was that the user was trying to create a Role-bound ACL without a valid enterprise license.
* none

cluster: improve role-acl create sanction message

---

src/v/kafka/utils/tests/txn_reader_test.cc
src/v/kafka/utils/txn_reader.cc
src/v/kafka/utils/txn_reader.h

call finally on the underlying reader for a proper cleanup, else bad things can happen on log reader's closure.
* none

kafka/txn_reader: proper cleanup in finally

---

src/v/datalake/translation/partition_translator.cc
src/v/datalake/translation/partition_translator.h

The files now look like <translation_begin_offset>-\<uuid\>.parquet
visually easier to see the translated offset sequence.
Would be ideal to also have "end offset" but that is lazily decided later in the write pipline, so can be added in a later patch.
* none

datalake/translator: add begin offset prefix to the parquet files

---

src/v/datalake/record_multiplexer.cc
src/v/datalake/translation_task.cc

If the reader doesn't have any process-able batches, both _error and
_result are unset and the code dereferences an unset optional (which
seems to manifest as an UB/segfault when printing the task result).
Fixes https://redpandadata.atlassian.net/issues/CORE-8093
* none

datalake/mux: fix segfault when no batches are processed

---

src/v/cluster/archival/archival_metadata_stm.cc
src/v/cluster/archival/archival_metadata_stm.h
src/v/cluster/archival/archival_policy.cc
src/v/cluster/data_migration_backend.cc
src/v/cluster/partition_manager.cc
src/v/cluster/partition_manager.h
src/v/cluster/partition_recovery_manager.cc
src/v/raft/persisted_stm.h
src/v/storage/snapshot.cc
src/v/storage/snapshot.h
tests/rptest/tests/data_migrations_api_test.py
tests/rptest/tests/topic_recovery_test.py

If a broker goes down in between writing bits of recovered partition metadata it fails to use the half-recovered partition, but does not re-download its logs either. Fix it by always writing raft snapshot after kvstore entries and archival_metadata_stm snapshot, and checking raft snapshot presence when downloading logs.
Also fix an invalid stack use problem.
* none

Migrations bugfixes: topic recovery race, invalid stack use

---

src/go/rpk/pkg/cli/connect/connect.go

Previously we were displaying only the `connect`
plugin help text, and not the rpk one. We were
missing the lifecycle commands (install, uninstall, upgrade).
* none

rpk connect: show rpk help text with --help/-h

---

src/v/raft/consensus.cc
tests/rptest/tests/data_migrations_api_test.py

Tests/migrations: relax migrations tests: do not check for number of migrations when using high level API under failure injector.
Eventual consistency of migrations table may come late, and we'd rather not wait for it to test but move on with other actions to see how a disturbed cluster copes with active use.
Raft/consensus: catch `ss::condition_variable_timed_out` not `ss::timed_out_error` when waiting for a condvar with timeout. Otherwise it bubbles up unhandled appearing in logs and potentially breaking the logic too.
Tests/migrations: run mount/unmount commands without finjector. Otherwise we'd need to be prepared to a situation where we get no successful reply from admin API, but the migration is nevertheless created (node killed right before it has sent a reply). When testing low …

Fixes for migrations tests

---

tests/rptest/services/redpanda.py

In Azure CDT tests we are seeing that starting redpanda occasionally takes longer than 30s. This seems to be because of disk access, in particular creating directories, being slow while redpanda is starting up.
We have increased the timeout from 20s to 30s in the past for this reason, but we are still seeing startup taking longer than 30s, so this increases the timeout further to 40s.
Fixes https://redpandadata.atlassian.net/browse/CORE-8184
* none

dt: increase redpanda start timeout to 40s

---

src/v/cluster/producer_state.cc
tests/rptest/tests/idempotency_test.py
tests/rptest/utils/node_operations.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23692

[v24.1.x] Keep producer inflight requests queue bounded

---

src/v/kafka/group_probe.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/23339

[v24.1.x] Remove shard aggregation on consumer group metrics

---

src/v/bytes/iobuf.cc
src/v/bytes/iobuf.h
src/v/bytes/tests/BUILD
src/v/bytes/tests/CMakeLists.txt
src/v/bytes/tests/iobuf_tests_mt.cc
src/v/kafka/server/handlers/fetch.h
src/v/model/record_batch_reader.cc
src/v/model/transform.cc
src/v/pandaproxy/schema_registry/store.h
src/v/raft/replicate_batcher.cc

This PR removes most of the cases where we use `iobuf::copy` to safely share data across shards. It depends on https://github.com/redpanda-data/vtools/pull/3285 being merged first so that the CI run will use a seastar version with atomically reference counted.
A follow up to this PR should be removing the `record_batch_reader::foreign_data_t` variant from `record_batch_reader` as it no longer has any uses in RP outside of unit tests.
* none

Remove need to copy `iobuf`s across shards

---

src/v/cluster/controller.cc
src/v/cluster/scheduling/leader_balancer.cc
src/v/cluster/scheduling/leader_balancer.h
tests/rptest/tests/leadership_transfer_test.py

Implements: [CORE-8042](https://redpandadata.atlassian.net/browse/CORE-8042) - Sanctions 18,19
Implement sanction(s) on leadership pinning properties when there is no valid license:
- If either the cluster config `default_leaders_preference` or a topic property `redpanda.leaders.preference` are set, the settings will be ignored.
* none
[CORE-8042]: https://redpandadata.atlassian.net/browse/CORE-8042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

cluster: Implement sanctions on pin leadership features on invalid license

---

src/v/cluster/topics_frontend.cc
src/v/kafka/server/tests/create_topics_test.cc

Implements: [CORE-8042](https://redpandadata.atlassian.net/browse/CORE-8042) - Sanction 22
Implement sanction(s) on leadership pinning properties when there is no valid license:
- Requests to create a topic with a restricted `redpanda.leaders.preference` value will be denied.
* none
[CORE-8042]: https://redpandadata.atlassian.net/browse/CORE-8042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

cluster: Sanction redpanda.leaders.preference on invalid license - create topic

---

src/v/cluster/topics_frontend.cc
src/v/kafka/server/tests/alter_config_test.cc

Implements: [CORE-8042](https://redpandadata.atlassian.net/browse/CORE-8042) - Sanctions 20 and 21
Implement sanction(s) on leadership pinning properties when there is no valid license:
- If there is no valid license, request to change `redpanda.leaders.preference` will be accepted only if it is to a non-restricted value.
* none
[CORE-8042]: https://redpandadata.atlassian.net/browse/CORE-8042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CORE-8042] cluster: Sanction redpanda.leaders.preference on invalid license - alter config

---

src/v/archival/archival_policy.cc
src/v/archival/archival_policy.h
src/v/archival/tests/CMakeLists.txt
src/v/archival/tests/archival_policy_test.cc
src/v/storage/offset_to_filepos.h

Manual backport of https://github.com/redpanda-data/redpanda/pull/23937.
Cherry-pick conflicts due to modified bazel `BUILD` file that doesn't exist in `v24.1.x`.
* Fixes a bug in which upload candidates made from segments with missing batches would trigger metadata related errors in the `ntp_archiver_service`, due to assigned start offsets being lower than they should be.

[v24.1.x] `archival`: bump offset if seeking undershoots (manual backport)

---

src/v/datalake/BUILD
src/v/datalake/CMakeLists.txt
src/v/datalake/schema_parquet.cc
src/v/datalake/schema_parquet.h
src/v/datalake/tests/BUILD
src/v/datalake/tests/CMakeLists.txt
src/v/datalake/tests/datalake_parquet_tests.cc
src/v/serde/CMakeLists.txt
src/v/serde/parquet/CMakeLists.txt

Added a function that translates the Iceberg schema to Parquet file schema that is necessary to write the Parquet files.
- none

Iceberg to parquet schema conversion

---

src/v/archival/archival_policy.cc
src/v/archival/archival_policy.h
src/v/archival/tests/CMakeLists.txt
src/v/archival/tests/archival_policy_test.cc
src/v/storage/offset_to_filepos.h

Manual backport of https://github.com/redpanda-data/redpanda/pull/23937.
Cherry-pick conflicts due to modified bazel `BUILD` file that doesn't exist in `v24.2.x`.
* Fixes a bug in which upload candidates made from segments with missing batches would trigger metadata related errors in the `ntp_archiver_service`, due to assigned start offsets being lower than they should be.

[v24.2.x] `archival`: bump offset if seeking undershoots (manual backport)

---

src/v/features/feature_table.cc
tests/rptest/tests/rpk_cluster_test.py

Do not show the built-in trial license in metrics and in the response to `rpk cluster license info` after it has expired. This ensures that existing clusters that are >45 days old that upgrade to v24.3 won't observe the expired trial license.
Fixes https://redpandadata.atlassian.net/browse/CORE-8221
* none

CORE-8221 features: do not show built in trial after expiry

---

src/v/security/audit/audit_log_manager.cc
src/v/security/audit/audit_log_manager.h

Move the construction of the audit probe from service start to service construction. Previously, the audit probe was created as a unique pointer when the service was started and destroyed when the service stopped.
Since the audit service has the same lifespan as the application, creating the probe during service construction reduces the risk of dereferencing a null pointer if the probe is accessed before the service has started.
* Construct audit metrics probe during service initialization to prevent null pointer access.

auditing: construct metrics probe during service construction

---

src/v/iceberg/avro_decimal.h
src/v/iceberg/tests/values_avro_test.cc

In Java `BigInteger.toByteArray()` method is used to encode Avro decimals the method returns an array where the first element is the most significant byte of the encoded decimal. This commit fixes Redpanda Avro Bigdecimal encoding.
- none

datalake/avro: fixed encoding decimal values

---

src/v/cluster/topics_frontend.cc
src/v/kafka/server/tests/alter_config_test.cc

In the previous scheme, enabling record_value schema ID validation
would pass the sanctions check if record_key schema ID validation
was already enabled.
This commit splits an existing check into two, such that changes
to either can be detected and subjected to license policy enforcement
if required.
Builds on https://github.com/redpanda-data/redpanda/pull/24083
* none

[CORE-8102] Separate key and value schema ID validation sanctions

---

src/v/cluster/topics_frontend.cc
src/v/kafka/server/tests/CMakeLists.txt
src/v/kafka/server/tests/alter_config_test.cc
src/v/kafka/server/tests/create_partition_test.cc
src/v/kafka/server/tests/topic_properties_helpers.h

Implement sanctions for create partition
Notes to reviewer:
* Should we check the same set of sanctioned properties for create topic and create partition?
* none

[CORE-8001] Implement sanctions for create partition

---

src/v/datalake/BUILD
src/v/datalake/CMakeLists.txt
src/v/datalake/tests/BUILD
src/v/datalake/tests/datalake_parquet_tests.cc
src/v/datalake/values_parquet.cc
src/v/datalake/values_parquet.h
src/v/iceberg/values.cc
src/v/iceberg/values.h

The value conversion is a necessary step before writing parquet format using `serde::parquet::writer`. Conversion translates the `iceberg::value` types into a corresponding `parquet::value`.
- none

Added conversion from `iceberg::value` to `serde::parquet::value`

---

src/v/config/configuration.cc
src/v/config/configuration.h
src/v/config/convert.h
src/v/config/types.h
src/v/datalake/coordinator/catalog_factory.cc
tests/rptest/tests/cluster_config_test.py
tests/rptest/tests/datalake/rest_catalog_connection_test.py

Renamed properties configuring cliend id and  secret for Iceberg REST catalog connection. Now the naming is aligned with what Iceberg spec and other catalog implementation uses.
- none

config: renamed iceberg rest catalog properties

---

src/v/security/audit/audit_log_manager.cc
tests/rptest/tests/audit_log_test.py

This fixes a bug in the audit client where if the cluster config value `kafka_batch_max_bytes` is greater than `audit_client_max_buffer_size`, the audit client ends up not producing any messages and fills up the audit log buffers.
The problem is the division here could lead to `max_concurrency=0`. In debug mode this is caught by an assert inside
`ss::max_concurrent_for_each` but in release mode stdlibrary `assert`s are disabled and the behaviour ends up being that the background fibre just blocks waiting for a semaphore unit to be available, but it never will become available because it was initialized to 0 and no tasks will ever release any units to it.
Fixes: CORE-8222
* This fixes a bug in the audit client where if the cluster config value `kafka_batch_max_bytes` was greater than …

audit: clamp audit client max parallelism

---

src/v/cluster/tests/rm_stm_test_fixture.h

Before the change ubsan would assert on a signed integer overflow
```
/vectorized/llvm/bin/../include/c++/v1/__chrono/duration.h:92:79: runtime error: signed integer overflow: 9223372036854775807 * 1000 cannot be represented in type '_Ct' (aka 'long long')
cluster::tx::producer_state_manager::evict_excess_producers() at /vectorized/llvm/bin/../include/c++/v1/__chrono/duration.h:92
```
The problem lies in that we try to subtract duration from a time_point with microsecond granularity. When doing that, duration is converted to a common type, microsecond representation and the millisecond::max() being already maximum value that can be represented in a long long can't be converted to micros (multiplied by 1000).
Not sure if this is the perfect fix but avoid the problem by initializing the …

c/tests: avoid ubsan signed integer overflow

---

src/v/cluster/topics_frontend.cc
src/v/cluster/topics_frontend.h
src/v/cluster/types.h
src/v/kafka/server/handlers/configs/config_utils.h
src/v/kafka/server/handlers/create_partitions.cc
src/v/kafka/server/handlers/topics/types.h
src/v/kafka/server/tests/alter_config_test.cc
src/v/kafka/server/tests/create_partition_test.cc
src/v/kafka/server/tests/create_topics_test.cc

Prior to this commit:
```
rpk topic create foo9 -c redpanda.remote.read=true --profile=local
TOPIC  STATUS
foo9   INVALID_CONFIG: Configuration is invalid
```
After this commit:
```
rpk topic create foo9 -c redpanda.remote.read=true --profile=local
TOPIC  STATUS
foo9   INVALID_CONFIG: Configuration is invalid: An enterprise license is required to enable {tiered storage}.
```
* none

[CORE-8187] Propagate an error message into `topic_result`

---

src/v/security/audit/audit_log_manager.cc
src/v/security/audit/audit_log_manager.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/24108
Fixes: CORE-8251

[v24.2.x] auditing: construct metrics probe during service construction

---

src/v/security/audit/audit_log_manager.cc
src/v/security/audit/audit_log_manager.h

Backport of PR https://github.com/redpanda-data/redpanda/pull/24108
Fixes: Fixes: CORE-8252

[v24.1.x] auditing: construct metrics probe during service construction

---

src/v/serde/parquet/BUILD
src/v/serde/parquet/CMakeLists.txt
src/v/serde/parquet/column_writer.cc
src/v/serde/parquet/column_writer.h
src/v/serde/parquet/tests/generate_file.cc
src/v/serde/parquet/writer.cc
src/v/serde/parquet/writer.h

Add the ability to compress parquet column chunks using zstd.
We currently only support zstd because that is the defacto compression
format that seems to be used these days and it's the only compression codec
that we have futurized as to not cause stalls.
* none

parquet: add zstd compression

---

src/v/security/audit/audit_log_manager.cc
tests/rptest/tests/audit_log_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/24137 
Fixes https://github.com/redpanda-data/redpanda/issues/24144
Fixes: CORE-8260
The conflict was on a sanctioning-related test that was present on dev but not on v24.2.x

[v24.2.x] audit: clamp audit client max parallelism

---

tests/rptest/services/redpanda_installer.py

Adds `-v` argument to curl and additional status messages to help debug intermittent RedpandaInstaller failures. See DEVPROD-2406.
* none

[rptest] More verbose _async_download_on_node_unlocked

---

src/v/kafka/server/protocol_utils.cc
src/v/kafka/server/protocol_utils.h
src/v/net/connection.cc
src/v/net/types.h

This PR updates `kafka::server` with a new exception type `malformed_header_exception`, which extends `net::parsing_exception`, and modifies `kafka::parse_v1_header` to raise one of those rather than a `std::runtime_error` when we receive a junk header from a client, which happens occasionally and previously would fail log ERROR checks in ducktape.
These will be identified by `net::is_disconnect_exception` and logged at INFO level, along with other "boring" client errors.
PR also modifies `net::parsing_error` slightly to extend `std::runtime_error` rather than `std::exception` so derived exception types can provide a message.
In principle, fixes:
CORE-8134
CORE-8059
CORE-7883
CORE-7324
CORE-6895
TODO:
* none

fix "Unexpected EOF" log errors

---

src/v/crypto/tests/BUILD

Implements : [CORE-7477](https://redpandadata.atlassian.net/browse/CORE-7477)
Add `crypto/tests/key_tests.cc` to bazel build
* none
[CORE-7477]: https://redpandadata.atlassian.net/browse/CORE-7477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bazel: add crypto unit test key_tests

---

src/v/storage/probe.cc
src/v/storage/probe.h
src/v/storage/segment_deduplication_utils.cc
src/v/storage/segment_utils.cc

This metric records the number of tombstones removed due to `delete.retention.ms` elapsing. It does not account for tombstone records removed by other forms of garbage collection.
* none

`storage`: add `tombstones_removed` metric to `probe`

---

src/v/cluster/node/local_monitor.cc
src/v/storage/disk_log_impl.cc
src/v/storage/node.cc
src/v/storage/probe.cc
src/v/storage/probe.h
tests/rptest/tests/node_metrics_test.py
tests/rptest/utils/node_metrics.py

Additional test in https://github.com/redpanda-data/redpanda/pull/24140
* Previously if redpanda was configured with different mountpoints for data and cache directory we would report metrics only for the cache directory. Now, the original `storage_disk_{total,free}_bytes` metric will report metrics for the data directory mountpoint and a new `storage_cache_disk_{total,free}_bytes` metric will report metrics for the cache directory mountpoint. Metrics will be equivalent if both are on the same mountpoint.

storage: track cache disk metrics separately

---

src/v/datalake/BUILD
src/v/datalake/CMakeLists.txt
src/v/datalake/schema_parquet.cc
src/v/datalake/serde_parquet_writer.cc
src/v/datalake/serde_parquet_writer.h
src/v/datalake/tests/BUILD
src/v/datalake/tests/serde_parquet_writer_test.cc
src/v/datalake/translation/partition_translator.cc
src/v/serde/parquet/CMakeLists.txt
tests/rptest/services/redpanda.py
tests/rptest/tests/datalake/datalake_e2e_test.py
tests/rptest/tests/datalake/rest_catalog_connection_test.py

Added an environment variable that will allow us to use serde parquet
writer in tests. The variable is going to be removed when we are going
to be ready to remove the dependency on the arrow library.
- none

Added ability to use datalake with `serde::parquet`

---

src/v/datalake/BUILD
src/v/datalake/record_multiplexer.cc
src/v/datalake/record_schema_resolver.cc
src/v/datalake/schema_registry.cc
src/v/datalake/schema_registry.h
src/v/datalake/tests/record_generator.cc
src/v/datalake/tests/record_schema_resolver_test.cc
src/v/pandaproxy/schema_registry/schema_getter.h
src/v/pandaproxy/schema_registry/sharded_store.cc
src/v/pandaproxy/schema_registry/sharded_store.h
src/v/schema/registry.cc
src/v/schema/registry.h
src/v/schema/tests/fake_registry.cc
src/v/schema/tests/fake_registry.h

Cleans up some error handling related to schemas in datalake code, by making the schema registry return a specific (nullopt) result when when the schema is not found, rather than throwing.
Other schema registry errors are not considered transient and cause the record multiplexer to exit, expecting further retries.
* none

datalake: cleanup schema registry error handling

---

src/v/cloud_storage/cache_service.cc

cst/cache: fix use-after-move caused by calling get_exception twice
Found by @dotnwat https://github.com/redpanda-data/redpanda/pull/24000#discussion_r1849302646
* none

cst/cache: fix use-after-move caused by calling get_exception twice

---

src/v/iceberg/rest_catalog.cc
src/v/iceberg/rest_client/catalog_client.cc
src/v/iceberg/rest_client/catalog_client.h
src/v/iceberg/rest_client/entities.cc
src/v/iceberg/rest_client/entities.h
src/v/iceberg/table_requests.h
src/v/iceberg/table_requests_json.cc
src/v/iceberg/table_requests_json.h
tests/rptest/tests/datalake/rest_catalog_connection_test.py

Today, we require an explicit call to create an endpoint before creating Iceberg tables. This isn't a great user experience, since it requires an Iceberg client to perform.
This PR adds the REST endpoint for creating namespace, and plugs it into the catalog impl.
Tested this manually against Open Catalog.
* none

iceberg: create namespace on demand

---

tests/rptest/tests/partition_force_reconfiguration_test.py

The `node_config_overrides` is not required for the test to work, it was added by mistake while developing the test.
* none

tests: removed not required node configuration override

---

src/v/cloud_storage/cache_service.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/24189

[v24.1.x] cst/cache: fix use-after-move caused by calling get_exception twice

---

src/v/cluster/archival/archival_metadata_stm.cc
src/v/cluster/archival/tests/archival_metadata_stm_test.cc

Several methods of the `archival_metadata_stm` are invoked by the `ntp_archiver` indirectly and require a lock to be held. The methods are `do_sync`, `do_replicate_commands`, and `do_add_segments`.
The methods are checking the invariant using this code:
```
vassert(
!_lock.try_get_units().has_value(),
"Attempt to replicate STM command while not under lock");
```
So basically if the lock is not taken this assertion will be triggered. Another assertion that indicates that the method `do_sync` was called concurrently with `do_replicate_commands` was triggered. The problem was caused by the code in the `command_batch_builder`. The code was invoking the `do_replicate_commands` method this way:
```cpp
auto units = co_await _stm.get()._lock.get_units(_as);
...!scheduling point!...
auto batch = …
```

[CORE-8010] cluster: Fix race condition in the `archival_metadata_stm`

---

tests/rptest/tests/node_metrics_test.py

They are collected asynchronously so it is ok for them to drift apart. The test is flaky.
* none

rptest: do not compare disk_free_bytes with cache_disk_free bytes

---

src/v/datalake/coordinator/tests/iceberg_file_committer_test.cc
src/v/datalake/record_multiplexer.cc
src/v/datalake/record_multiplexer.h
src/v/datalake/record_translator.cc
src/v/datalake/record_translator.h
src/v/datalake/schema_parquet.cc
src/v/datalake/table_definition.cc
src/v/datalake/table_definition.h
src/v/datalake/tests/gtest_record_multiplexer_test.cc
src/v/datalake/tests/record_multiplexer_test.cc
src/v/model/record.h
src/v/serde/parquet/schema.h
tests/rptest/tests/datalake/datalake_e2e_test.py
tests/rptest/tests/datalake/rest_catalog_connection_test.py

Updates the default table fields:
- wraps all system fields in a top level `redpanda` nested struct
- unwraps user fields instead of having them all be in a nested struct
This isn't the final form of default schemas, as we currently still allow going from "schemaless" to schema-ed, while the desired end state is to use topic configs to force users to choose. Until that is implemented, the `redpanda` struct still contains the `value` field to allow for going between the two modes.
Collisions with `redpanda` user fields are handled by moving the conflicting user fields into the `redpanda` struct as `redpanda.data`.
Also adds a Kafka partition field and headers field.
NOTE: the top level `value` field is still here. That will need to be moved when the enabling topic config learns how to …

datalake: update system fields

---

src/v/datalake/fwd.h
src/v/datalake/record_multiplexer.cc
src/v/datalake/record_multiplexer.h
src/v/datalake/record_translator.cc
src/v/datalake/record_translator.h
src/v/datalake/table_definition.cc
src/v/datalake/tests/BUILD
src/v/datalake/tests/gtest_record_multiplexer_test.cc
src/v/datalake/tests/record_multiplexer_test.cc
src/v/datalake/tests/translation_task_test.cc
src/v/datalake/translation/partition_translator.cc
src/v/datalake/translation/partition_translator.h
src/v/datalake/translation_task.cc
src/v/datalake/translation_task.h
tests/rptest/tests/datalake/datalake_e2e_test.py

Splits the record_translator into two implementations: one that
translates key-value records, and another that expects a schema. The
expectation is that users will explicitly choose which to use based on a
topic property.
With this change, key-value tables will have a redpanda.value column,
while structured tables will only have user-defined columns instead.
A "default translator" is left in with similar properties to the prior
record_translator, but this is just left in to smooth the transition
until we have a topic config.
NOTE: in this commit, we leave as is the invalid record handling, which
previously allowed going between key-value and structured data. Once we
have a more explicit toggle, this handling should replaced with a
dead-letter table or by dropping records on the floor.
* …

datalake: split record translator into distinct modes 

---

src/v/ssx/tests/BUILD
src/v/ssx/tests/async_algorithm_test.cc
src/v/ssx/tests/sformat_bench.cc

Implements:
[CORE-7600](https://redpandadata.atlassian.net/browse/CORE-7600) : async_algorithm_test.cc
[CORE-7602](https://redpandadata.atlassian.net/browse/CORE-7602) : event_test.cc
[CORE-7603](https://redpandadata.atlassian.net/browse/CORE-7603) : sformat_bench.cc
[CORE-7604](https://redpandadata.atlassian.net/browse/CORE-7604) : sharded_ptr_test.cc
[CORE-7605](https://redpandadata.atlassian.net/browse/CORE-7605) : single_sharded_test.cc
[CORE-7606](https://redpandadata.atlassian.net/browse/CORE-7606) : sleep_abortable_test.cc
[CORE-7607](https://redpandadata.atlassian.net/browse/CORE-7607) : task_local_ptr_test.cc
[CORE-7608](https://redpandadata.atlassian.net/browse/CORE-7608) : thread_worker_bench.cc
[CORE-7609](https://redpandadata.atlassian.net/browse/CORE-7609) : watchdog_test.cc …

Bazelize ssx tests

---

src/v/cluster/scheduling/partition_allocator.cc
src/v/cluster/scheduling/partition_allocator.h
src/v/cluster/scheduling/types.cc
src/v/cluster/scheduling/types.h
src/v/cluster/tests/partition_allocator_fixture.h
src/v/cluster/tests/partition_allocator_tests.cc
src/v/cluster/topics_frontend.cc

Fixes: [CORE-7750](https://redpandadata.atlassian.net/browse/CORE-7750)
The size of the `allocation_request` created as part of the partition allocation scales linearly with the number of partitions needed to be created. Currently, the check to see if the request can be accepted happens on the `allocation_request` object. When the number of requested partitions is too big, we run out of memory while creating this object.
The fix is to be lazy on the creation of the `allocation_request`, where possible, and do the first step of the validation before we create the full object.
* Fixed an issue where creating a topic with a huge number of partitions could lead to a crash.
[CORE-7750]: https://redpandadata.atlassian.net/browse/CORE-7750?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …

[CORE-7750] Creating topic with huge number of partitions leads to segfault

---

src/v/config/configuration.cc

Previously we limited this to 32 for fear of connection explosion on
larger core machines but we haven't seen any issues so far and 64 core
machines (e.g.: AWS 16xlarge) are becoming more common so up the default
to account for this.
Having one per shard is important for even load distribution across
shards.
* none

rpc: Change max internal rpc connection count limit

---

src/v/version/expand_with_stamp_vars.bzl

This prevents it from showing up in the packaged tarball for Bazel.
* none

bazel/version: remove version.cc as a runfile

---

src/v/iceberg/metadata_io.h
src/v/iceberg/rest_client/BUILD
src/v/iceberg/rest_client/catalog_client.cc

Addresses a couple issues seen when running the Iceberg integration for a moderate length of time:
- oversized allocs from loading table metadata as a string
- frequent EOSs that wouldn't be retried, and so we'd get stuck when performing many downloads in a row as a part of a merge append
* none

iceberg: couple miscellaneous fixes found in prolonged testing

---

src/v/serde/parquet/column_writer.cc
src/v/serde/parquet/column_writer.h
src/v/serde/parquet/tests/generate_file.cc
src/v/serde/parquet/writer.cc
src/v/serde/parquet/writer.h

- **serde/parquet: add method to flush row group**
- **serde/parquet: add stats for the current row group memory usage**
* none

serde/parquet: support creating multiple row groups

---

src/v/cloud_storage/cache_service.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/24189

[v24.3.x] cst/cache: fix use-after-move caused by calling get_exception twice

---

bazel/test.bzl
src/v/serde/rw/enum.h
src/v/serde/test/BUILD
src/v/serde/test/serde_test.cc

Implements: [CORE-7599](https://redpandadata.atlassian.net/browse/CORE-7599) `serde_test.cc`
In the bazel build we have the flags `-Werror,-Wsign-compare` enabled which requires a few comparisons to be changed to a signed-aware interface.
* none
[CORE-7599]: https://redpandadata.atlassian.net/browse/CORE-7599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ik bazel tests serde

---

src/v/serde/parquet/BUILD
src/v/serde/parquet/CMakeLists.txt
src/v/serde/parquet/column_writer.cc
src/v/serde/parquet/column_writer.h
src/v/serde/parquet/tests/generate_file.cc
src/v/serde/parquet/writer.cc
src/v/serde/parquet/writer.h

[v24.3.x] backport parquet PRs

---

tests/rptest/tests/topic_delete_test.py

I see the last check in ducktape was here when ducktape was expecting this file to have been deleted on the broker:
```
[INFO  - 2024-11-21 01:58:41,459 - topic_delete_test - topic_storage_purged - lineno:114]:   ip-172-31-45-99: 54-1-v1.log
```
Then a timeout occurs because the file isn't removed. But looking at the broker logs, the “removed:” line which happens right before ss::remove is called:
```
DEBUG 2024-11-21 01:58:42,717 [shard 1:main] storage - segment.cc:171 - removed: "/var/lib/redpanda/data/kafka/topic-rmahmpbiye/2_29/54-1-v1.log" size 1048868
```
which was 1 second later. This appears to just be a race. Extend the time allowance before timeout.
* none

[CORE-8249] Allow more time for segment clean up

---

src/v/cluster/cloud_metadata/tests/cluster_recovery_backend_test.cc
src/v/cluster/partition_manager.cc
src/v/cluster/partition_manager.h
src/v/model/BUILD
src/v/model/ktp.h
src/v/ssx/BUILD
src/v/ssx/async-clear.h
src/v/storage/log_manager.cc
src/v/storage/log_manager.h
src/v/transform/rpc/tests/transform_rpc_test.cc

Avoid some oversized allocs in both the cluster and storage subsystem at high partition density.
* none

Avoid some oversized allocs at high partition density

---

tests/rptest/redpanda_cloud_tests/high_throughput_test.py

Implement initial support for actually executing the High Throughput Tests on operator V2/Azure.
* none

[rptest] support opV2 in HTT

---

src/v/pandaproxy/probe.cc
src/v/pandaproxy/schema_registry/store.h

Added metrics (prefixed with `[vectorized|redpanda]_schema_registry_cache_`):
| Metric | Type | Description | Labels | Aggregation labels |
| -- | -- | -- | -- | -- |
| `schema_count` | gauge | The number of schemas in the store | `shard` | `shard` |
| `schema_memory_bytes` | gauge | The memory usage of schemas in the store | `shard` | `shard` |
| `subject_count` | gauge | The number of subjects in the store | `shard`, `deleted` | `shard` |
| `subject_version_count` | gauge | The number of versions for each subject in the store | `shard`, `subject`, `deleted` |`shard` |
Modified metrics (prefixed with `vectorized_pandaproxy`):
| Metric | Type | Description | Labels | Aggregation labels |
| -- | -- | -- | -- | -- |
| `request_latency` | histogram | Request latency | `shard`, `operation` | …

schema_registry: Add metrics

---

MODULE.bazel.lock
bazel/repositories.bzl

Bring it inline with the vtools build
* none

bazel: Update hwloc to 2.11.2

---

src/v/kafka/data/CMakeLists.txt
src/v/kafka/data/test/CMakeLists.txt

This was left out of 3ddb1e38b7 by mistake. This code has been under test in the bazel build on dev, but it has _not_ been under test on v24.3.x since the branch cut, since the bazel build is not run there.
* none

k/data: Add CMakeLists for record_batcher test

---

tests/rptest/services/apache_iceberg_catalog.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/24213

[v24.3.x] rptest/s: use abfss (secure) scheme for iceberg catalog

---

src/v/raft/tests/raft_fixture.cc

Sometimes (rarely) it failed on repeated promise set. Presumably it's a race between stop and normal execution. It looks safe to just ignore repeated sets.
https://redpandadata.atlassian.net/browse/CORE-8318
* none

raft/tests: fix a race condition in raft_fixture

---

tests/rptest/tests/upgrade_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23876

[v24.1.x] rptest: assert consumer invariants after each upgrade

---

tests/docker/ducktape-deps/ocsf-server

jira: [DEVPROD-2443]
[DEVPROD-2443]: https://redpandadata.atlassian.net/browse/DEVPROD-2433
Getting http 404 errors for downloading the v1.0.0 tar.gz asset:
```console 
bash$ curl -L -O -s -S --fail https://github.com/redpanda-data/ocsf-schema/archive/refs/tags/v1.0.0.tar.gz
curl: (56) The requested URL returned error: 404
```
Looks like the release for v1.0.0 does not have a tag but is just a release from the git commit from tip of v1.0.0 branch: https://github.com/redpanda-data/ocsf-schema/tree/refs/tags/v1.0.0
So, change download of asset to just the code at that git commit which is `9608805fe0b61035cb821bb9068096fe47fed12d`.
```console
bash$ curl -L -O -s -S --fail https://github.com/redpanda-data/ocsf-schema/archive/9608805fe0b61035cb821bb9068096fe47fed12d.tar.gz
```
Same as upstream …

ducktape: fix download of redpanda-data/ocsf-schema

---

tests/docker/ducktape-deps/ocsf-server

jira: [DEVPROD-2443]
[DEVPROD-2443]: https://redpandadata.atlassian.net/browse/DEVPROD-2433
Fixes PR #24297 [error](https://buildkite.com/redpanda/redpanda/builds/58737#019365cd-a47c-4b63-a618-d6fa53a8fce0/650-869):
```
#15 1.187 tar (child): v9608805fe0b61035cb821bb9068096fe47fed12d.tar.gz: Cannot open: No such file or directory
```
Uses correct name for tar file.
Needs backport to the same branches as PR #24297
* none

ducktape: follow-up fix download of redpanda-data/ocsf-schema

---

src/v/iceberg/filesystem_catalog.cc
src/v/iceberg/table_io.cc
src/v/iceberg/table_io.h
src/v/iceberg/tests/filesystem_catalog_test.cc
tests/rptest/tests/datalake/datalake_e2e_test.py

This implementation leaves data files as orphans, but is enough for trying iceberg out.
* none

iceberg: add simple drop_table support for filesystem_catalog

---

src/v/serde/test/BUILD
src/v/serde/test/bench.cc

Add bazel target for `serde/test/serde_bench.cc`
* none

serde: bazelize serde/bench

---

tests/rptest/tests/alter_topic_configuration_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/24286

[v24.3.x] [CORE-8361] rptest: Disable fips in one of the upgrade tests

---

tests/docker/ducktape-deps/ocsf-server

Backport of #24297 and #24304
* none

[v24.2.x] ducktape: fix download of redpanda-data/ocsf-schema

---

tests/docker/ducktape-deps/ocsf-server

Backport of #24297 and #24304
* none

[v24.1.x] ducktape: fix download of redpanda-data/ocsf-schema

---

tests/docker/ducktape-deps/ocsf-server

Backport of #24297 and #24304
* none

[v24.3.x] ducktape: fix download of redpanda-data/ocsf-schema

---

src/v/storage/disk_log_impl.cc
src/v/storage/tests/storage_e2e_test.cc

The race condition between prefix truncation and appends was leading to
an issue in which the same offset might have been assigned twiice to
batches that were appended to log. This invalidates the invariant and
may lead to inconsistencies.
The fix has two parts. The first part fixes calculation of next offset
for the newly created log appender. Previously the check incorrectly
validated if the log is empty. The condition was simplified and it is
now based on an invariant that if the `start_offset > dirty_offset` the
log is empty (there is one exception to it when the log is empty and
first initialized, but then the next offset is derived as usual by
incrementing the dirty offset).
The second part of the fix is an addition of check if the segment is
still removable after the segment write …

Fixed race condition between appends and prefix truncation

---

src/go/rpk/pkg/adminapi/admin.go
src/go/rpk/pkg/cli/security/acl/create.go
src/go/rpk/pkg/cli/security/role/create.go
tests/rptest/tests/acls_test.py

Fixes #24278 
- 3d21ec90b42c0132c82c93815179dca66d305b91 Adds the ErrMessage field that comes from the ACLCreate response to our Error:
```
$ rpk security acl create --allow-role "RedpandaRole:admin" --operation read --topic foo
PRINCIPAL           HOST  RESOURCE-TYPE  RESOURCE-NAME  RESOURCE-PATTERN-TYPE  OPERATION  PERMISSION  ERROR
RedpandaRole:admin  *     TOPIC          foo            LITERAL                READ       ALLOW       INVALID_CONFIG: A Redpanda Enterprise Edition license is required to create an ACL with a role binding. To request an Enterprise license, please visit https://redpanda.com/upgrade. To try Redpanda Enterprise for 30 days, visit https://redpanda.com/try-enterprise.
```
- 9625c2ffd6c6ec38dc7b70a8de6dc398cc0101d0 decode the Error Message from the admin API to …

rpk: improve error messages in security/acl

---

MODULE.bazel
src/go/rpk/go.mod
src/go/rpk/pkg/adminapi/admin.go
src/go/rpk/pkg/cli/debug/BUILD
src/go/rpk/pkg/cli/debug/bundle/BUILD
src/go/rpk/pkg/cli/debug/bundle/bundle.go
src/go/rpk/pkg/cli/debug/bundle/bundle_k8s_linux.go
src/go/rpk/pkg/cli/debug/bundle/bundle_linux.go
src/go/rpk/pkg/cli/debug/common/BUILD
src/go/rpk/pkg/cli/debug/common/common.go
src/go/rpk/pkg/cli/debug/common/common_test.go
src/go/rpk/pkg/cli/debug/debug.go
src/go/rpk/pkg/cli/debug/remotebundle/BUILD
src/go/rpk/pkg/cli/debug/remotebundle/cancel.go
src/go/rpk/pkg/cli/debug/remotebundle/download.go
src/go/rpk/pkg/cli/debug/remotebundle/remote.go
src/go/rpk/pkg/cli/debug/remotebundle/start.go
src/go/rpk/pkg/cli/debug/remotebundle/status.go
tests/rptest/clients/rpk.py
tests/rptest/tests/rpk_cluster_test.py
tests/rptest/tests/rpk_debug_bundle_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23986

[v24.3.x] rpk: add `rpk debug remote-bundle`; collect a cluster-wide bundle 

---

src/v/cluster/partition_probe.cc
src/v/cluster/partition_probe.h
src/v/datalake/coordinator/coordinator.cc
src/v/datalake/coordinator/coordinator.h
src/v/datalake/coordinator/frontend.cc
src/v/datalake/coordinator/tests/coordinator_test.cc
src/v/datalake/coordinator/tests/state_machine_test.cc
src/v/datalake/coordinator/types.h
src/v/datalake/translation/partition_translator.cc
src/v/datalake/translation/partition_translator.h
tests/rptest/tests/datalake/datalake_e2e_test.py

Adds lag metrics that track translation and iceberg commit lag. Sample below.
```
vectorized_cluster_partition_iceberg_offsets_pending_commit{namespace="kafka",partition="1",shard="0",topic="foo"} 4.000000
vectorized_cluster_partition_iceberg_offsets_pending_translation{namespace="kafka",partition="1",shard="0",topic="foo"} 4.000000
```
* none

datalake/metrics: lag metrics

---

src/go/rpk/pkg/adminapi/admin.go
src/go/rpk/pkg/cli/security/acl/create.go
src/go/rpk/pkg/cli/security/role/create.go
tests/rptest/tests/acls_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/24296
Fixes: https://github.com/redpanda-data/redpanda/issues/24330,

[v24.3.x] rpk: improve error messages in security/acl

---

src/v/storage/disk_log_impl.cc
src/v/storage/tests/storage_e2e_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/24306

[v24.2.x] Fixed race condition between appends and prefix truncation

---

src/v/cluster/rm_stm.cc

rm_stm: remove always true assert on transaction_ga feature

---

src/v/config/configuration.cc

Changed the declaration to match other config properties. See https://redpandadata.slack.com/archives/C06NQP4LW2C/p1732637739710979 for context
* none

config: remove the meta tag for iceberg_delete

---

src/v/cluster/topic_table.cc
src/v/datalake/coordinator/iceberg_file_committer.cc
src/v/datalake/coordinator/tests/iceberg_file_committer_test.cc

Previously, if we failed to complete topic purging process after dropping the table (e.g. if a topic table update failed), the topic would get stuck in coordinator as the file committer would try to load non-existent table.
Fix this by returning early if there are no files to commit.
* none

datalake: make purging table idempotent

---

src/v/cloud_storage_clients/abs_client.cc
src/v/cloud_storage_clients/s3_client.cc
src/v/cluster/archival/adjacent_segment_merger.cc
src/v/cluster/archival/scrubber.cc
src/v/http/client.cc
src/v/http/client.h

The test cuts off network access to S3 and deletes a topic. It is expected that the topic on local storage is removed. It isn't always removed.
Part of removal of a partition (prior to physically removing segments) is to stop the partition. However, we can see here the long 2 minute delay, which corresponds to _archiver->stop() call.
```
DEBUG 2024-11-23 18:45:37,402 [shard 0:main] cluster - partition.cc:567 - Stopping archiver on partition: {kafka/topic-rhmomazlxk/2}
DEBUG 2024-11-23 18:47:13,085 [shard 0:main] cluster - partition.cc:576 - Stopping cloud_storage_partition on partition: {kafka/topic-rhmomazlxk/2}
```
If we dig in further we'll observe that while the scrubber is promptly stopped, there is an active scrubbing job that needs to finish before scrubber stop will fully close …

[CORE-8249] Shutdown http/client promptly on scrubber exit

---

tests/rptest/services/redpanda.py

This gives a starting redpanda node the same time to fail as we give it to successfully start up. It also allows reusing the timeout parameter to configure how much to wait for redpanda to fail on startup (which some call sites already attempt to do).
Reusing the startup timeout is a better guess than the current static 10s, because tests that expect a timeout typically expect it to happen during the same timeframe as what a normal startup would take.
This also means that the timeout is increased from the current 10s to 40s (`DEFAULT_NODE_READY_TIMEOUT_SEC`) by default. This solves some CI failures on Azure CDT where startup is occasionally slower.
Fixes https://redpandadata.atlassian.net/browse/CORE-8290
* none

CORE-8290 dt/redpanda: increase expect_fail timeout to 40s

---

tests/java/iceberg-rest-catalog/build.gradle
tests/rptest/services/apache_iceberg_catalog.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/24319

[v24.3.x] rptest/s: apache iceberg rest catalog with fs mode on gcp

---

src/v/raft/tests/BUILD
src/v/raft/tests/raft_fixture.h
src/v/raft/tests/replication_monitor_tests.cc

1) added a utility function to raft_fixture to execute a testing coro in `retry_with_leader`
2) made both monitor_test_fixture tests use it
I failed to reproduce the original problem but from the logs it's clear leadership was lost.
https://redpandadata.atlassian.net/browse/CORE-7666
https://buildkite.com/redpanda/redpanda/builds/54755#01920b02-453f-449d-a6fa-ccfa717ca67d/6-82553
I added the facility to raft_fixture because I'm looking to reuse it in other tests.
he testing coro returns a `future<>`, so it has to indicate leadership problems via exception. That's for to use marcos like `ASSERT_NE_CORO`.
The testing coro has to be in a separate subclass. We could clone TEST_P_CORO macro to create a class with two coroutines: the inner one that may throw, and the outer one that calls …

tests/gtest_raft_rpunit: monitor_test_fixture to honour leadership changes

---

src/v/cluster/archival/ntp_archiver_service.cc
src/v/cluster/archival/ntp_archiver_service.h
src/v/cluster/archival/probe.cc
src/v/cluster/archival/probe.h
tests/rptest/tests/usage_test.py

We called update probe only from leaders and after exiting the upload loop which led to inconsistent and stale metrics.
Fix this by introducing a subscription mechanism to the STM which is the source of truth for the manifest state and must be consistent across all replicas.
The first attempt was in
https://github.com/redpanda-data/redpanda/pull/24257 but the feedback suggested that the approach in this commit is better.
* Ensure `redpanda_cloud_storage_cloud_log_size` metric consistent across all replicas. We used to update it seldomly from the leader replica only which lead to inconsistent/stale values.

archival: consistent log size probes across replicas (pull)

---

tests/rptest/clients/kafka_cli_tools.py
tests/rptest/tests/full_disk_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23484

[v24.2.x] rptest: make target_min_capacity_wanted more deterministic

---

tests/rptest/tests/random_node_operations_test.py

Backport of PR https://github.com/redpanda-data/redpanda/pull/23705

[v24.2.x] tests: ignore archival ssl error log entry

---

src/v/cloud_storage/cache_service.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/24189

[v24.2.x] cst/cache: fix use-after-move caused by calling get_exception twice

---

src/v/cluster/controller_backend.cc
src/v/cluster/controller_backend.h

With `ss::gate_closed_exception`. This is to untangle a race condition between partition shutdown and app shutdown. Callers should consider the operation unsuccessful and will probably retry it, as shard_placement_table is not going to be updated.
While this unsuccessful operation will leave the partition in a somewhat orphaned state, i.e. without appropriate shard_table entries, the rest of the system should be able to live with it in the same way as it lives during a successful partition shutdown.
https://redpandadata.atlassian.net/browse/CORE-8371
* none

c/controller_backend: allow `shutdown_partition` to fail on app shutdown

---

src/v/cluster/controller.cc
src/v/cluster/controller_stm.cc
src/v/cluster/controller_stm.h
src/v/raft/state_machine.cc
src/v/raft/state_machine.h
tests/rptest/tests/quick_terminate_test.py

This is to fix `'_id_by_uuid.empty()' will not overwrite existing data` assert that happens if we shut down shortly after startup, which is not uncommon when testing with failure injector.
https://redpandadata.atlassian.net/browse/CORE-7799
* none

Fix race between bootstrap and shutdown

---

tests/rptest/tests/read_replica_e2e_test.py

Add new ducktape test. The test creates two clusters (source and RRR), produces data to the source and consumes from the RRR. The test initiates partition movement for every partition of the RRR cluster.
* none

[CORE-7961] rptest: Add ducktape test for partition movement in RRR cluster

---

tests/rptest/services/spark_service.py
tests/rptest/services/trino_service.py
tests/rptest/tests/datalake/datalake_services.py
tests/rptest/tests/datalake/datalake_verifier.py
tests/rptest/tests/datalake/datalake_verifier_test.py
tests/rptest/tests/datalake/query_engine_base.py
tests/rptest/tests/datalake/simple_connect_test.py

Added an example test using Redpanda Connect to populate Iceberg enabled topic with data and then verify the translation correctness. 
- none

Iceberg Verifier

---

tests/docker/Dockerfile
tests/docker/ducktape-deps/client-swarm
tests/docker/ducktape-deps/rp-storage-tool

fixes: #24346
jira: [DEVPROD-2419]
manual backport of PR https://github.com/redpanda-data/redpanda/pull/24334
skipped cherry-pick 8fd3f60 because changes don't exist on this branch. rest of cherry-pick clean, no conflicts.
* none
[DEVPROD-2419]: https://redpandadata.atlassian.net/browse/DEVPROD-2419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[v24.1.x] tests/docker: increase cargo retry and verbosity

---

tests/docker/Dockerfile
tests/docker/ducktape-deps/client-swarm
tests/docker/ducktape-deps/rp-storage-tool

fixes: #24347
jira: [DEVPROD-2419]
manual backport of PR #24334
skipped cherry-pick 8fd3f60dbbae3c011a52722d647611dfe0da1c75 because changes don't exist on this branch. rest of cherry-pick clean, no conflicts.
* none
[DEVPROD-2419]: https://redpandadata.atlassian.net/browse/DEVPROD-2419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[v24.2.x] tests/docker: increase cargo retry and verbosity

---

src/v/storage/disk_log_impl.cc
src/v/storage/tests/compaction_e2e_test.cc

The behavior of the sliding window considered for compaction was changed in this PR: https://github.com/redpanda-data/redpanda/pull/23380.
> Newly added/closed segments are ignored until the current "round" of sliding window compaction cleanly compacts all segments down to the start of the log. This allows for sliding window compaction to continually produce clean segments, and avoid a situation where clean segments are not being produced due to a high ingress rate or key cardinality (this situation would prevent timely tombstone removal). _last_compaction_window_offset must reach the base offset of the first segment in the log before new segments will be considered in the compaction window.
However, consider the following situation:
```
[0] [1] [2] [3] [4] [5]
^
|----- …
```

`storage`: reset compaction window start offset when offset map isn't built

---

src/v/datalake/datalake_manager.cc
tests/rptest/tests/random_node_operations_test.py
tests/rptest/utils/node_operations.py

Enabling Iceberg in Random Node Operations test to validate its correctness in face of failures and node operations.
- none

Datalake in Random Node Operations test

---

tests/rptest/services/redpanda_installer.py

Adds automatic retry logic to `RedpandaInstaller._avail_for_download`
* none

[rptest] Auto-retry in RedpandaInstaller._avail_for_download

---

src/v/cloud_storage/cache_service.h
src/v/cloud_storage/remote_segment.cc
src/v/cloud_storage/tests/cloud_storage_fixture.h
src/v/cloud_storage/tests/remote_segment_test.cc

Backport of PR https://github.com/redpanda-data/redpanda/pull/24265

[v24.3.x] [CORE-7257] cloud_storage: Remove assertion in `remote_segment`

---

src/v/cloud_topics/BUILD
src/v/cloud_topics/CMakeLists.txt
src/v/cloud_topics/dl_snapshot.cc
src/v/cloud_topics/dl_snapshot.h
src/v/cloud_topics/dl_stm/BUILD
src/v/cloud_topics/dl_stm/dl_stm.cc
src/v/cloud_topics/dl_stm/dl_stm_api.cc
src/v/cloud_topics/dl_stm/dl_stm_api.h
src/v/cloud_topics/dl_stm/dl_stm_commands.h
src/v/cloud_topics/dl_stm/dl_stm_state.cc
src/v/cloud_topics/dl_stm/dl_stm_state.h
src/v/cloud_topics/dl_stm/tests/BUILD
src/v/cloud_topics/dl_stm/tests/dl_stm_state_test.cc
src/v/cloud_topics/dl_stm/tests/dl_stm_test.cc
src/v/cloud_topics/types.cc
src/v/cloud_topics/types.h
src/v/cluster/partition.cc

ct: dl_stm mvcc snapshot

---

tests/rptest/clients/kubectl.py
tests/rptest/services/cloud_broker.py

Azure tier-4 and tier-5 tests failed to launch successfully before these changes, and now (with this commit) the tests actually launch as expected.
* none

[rptest] unbreak Azure T4/T5 tests

---

src/v/storage/disk_log_impl.cc
src/v/storage/probe.cc
src/v/storage/probe.h
src/v/storage/segment_deduplication_utils.cc
src/v/storage/segment_utils.cc
src/v/storage/segment_utils.h
tests/docker/ducktape-deps/kgo-verifier
tests/rptest/clients/kafka_cli_tools.py
tests/rptest/services/kgo_verifier_services.py
tests/rptest/tests/log_compaction_test.py

Serves as a stress test for compaction and tombstone removal.
Depends on changes made in https://github.com/redpanda-data/kgo-verifier/pull/60, and so the commit SHA for `ducktape-deps/kgo-verifier` has been updated (CI will be red if this isn't merged yet)
* none

`rptest`: add `log_compaction_test.py`

---

src/v/datalake/tests/BUILD
src/v/datalake/tests/CMakeLists.txt
src/v/datalake/tests/datalake_avro_tests.cc
src/v/datalake/tests/record_generator.cc
src/v/datalake/tests/record_generator.h
src/v/datalake/tests/record_multiplexer_bench.cc
src/v/datalake/tests/test_data_writer.h
src/v/serde/avro/tests/data_generator.cc
src/v/serde/avro/tests/data_generator.h
src/v/serde/avro/tests/parser_test.cc
src/v/serde/protobuf/CMakeLists.txt
src/v/serde/protobuf/tests/BUILD
src/v/serde/protobuf/tests/CMakeLists.txt
src/v/serde/protobuf/tests/data_generator.cc
src/v/serde/protobuf/tests/data_generator.h
src/v/storage/BUILD
src/v/storage/offset_to_filepos.cc
src/v/utils/BUILD
src/v/utils/null_output_stream.h

This PR adds benchmarks for `record_multiplexer` along with the following that was needed to support that;
- A cmake-build-compatible random Protobuf message generator.
- Protobuf support for `record_generator`.
- A serde parquet writer that writes to a null ostream.
* none

Add `record_multiplexer` microbenchmarks

---

.bazelrc
bazel/BUILD
bazel/test.bzl
src/v/bytes/tests/BUILD
src/v/bytes/tests/iobuf_fuzz.cc

Implements:
[CORE-7353](https://redpandadata.atlassian.net/browse/CORE-7353) : `iobuf_fuzz.cc`
Added extra global linking argument `-stdlib=libc++`:
without this, `libfuzzer.a`, which is included by adding `-fsanitizer=fuzzer`, introduces a dependency on `stdlibc++.so`. This ends up with both `libc++.a` and `stdlibc++.so` being linked.
* none
[CORE-7353]: https://redpandadata.atlassian.net/browse/CORE-7353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bytes: bazelize iobuf_fuzz

---

src/v/config/configuration.cc
src/v/config/configuration.h
src/v/storage/disk_log_impl.cc
tests/rptest/tests/log_compaction_test.py

We have seen in incidents that it can be useful to disable sliding window compaction for a period of time, in order to allow adjacent segment compaction to kick in instead.
Unfortunately, `log_compaction_use_sliding_window` is marked as `needs_restart::yes`, due to the fact memory is only allocated at start-up if it is enabled.
To deal with the common case in which we start `redpanda` with `log_compaction_use_sliding_window=true`, and wish to disable sliding window compaction for a period of time without forcing a cluster restart (usually by cloud operators), add a new cluster config `log_compaction_pause_use_sliding_window`, which doesn't require a restart and can be used to temporarily disable sliding window compaction.
* none

`config`: add `log_compaction_pause_use_sliding_window`
