src/v/kafka/requests/metadata_request.cc, src/v/kafka/tests/metadata_test.cc
=> k/requests: only list topics for kafka namespace

src/v/kafka/requests/fetch_request.cc, src/v/kafka/tests/fetch_test.cc
`.error` is needed for v7+
`.session_id` is needed for v7+
`.partitions.responses.log_start_offset` is needed for v5+
Changed since v1:
- Simplified serialisation for <= v4 since v4 is the minimum
- Fixed a version check for session_id
- Added test
Changed since v2:
- Drop support for v11
=> k/fetch_request: Improve serialisation for v4+

src/v/coproc/errc.h, src/v/coproc/router.cc, src/v/coproc/service.cc, src/v/coproc/tests/script_manager_service_test.cc, src/v/coproc/types.cc, src/v/coproc/types.h
=> Fix failing script-manager unit test

.github/workflows/rpk-build.yml, .gitignore, src/go/rpk/build.sh, src/go/rpk/gen_deps.sh, src/go/rpk/pkg/cli/cmd/wasm/template/vectorized_dependency.go, src/js/generate-entries.sh
Fix the rpk build/ pipeline, including generating the JS files needed to inject their content into rpk template files.
Add a new job to create a new release and publish the latest rpk builds for Linux & Mac as artifacts.
=> Release rpk

.github/workflows/rpk-build.yml
=> ci/rpk: Fix release jobs

.github/workflows/rpk-build.yml
=> ci/rpk: Fix typo in job output

src/v/coproc/router.cc, src/v/coproc/router.h, src/v/coproc/tests/read_materialized_topic_test.cc, src/v/redpanda/tests/fixture.h
=> Replace the while(true) loop within v/copro

CODEOWNERS
=> coproc: update codeowner for coprocessor

src/go/rpk/pkg/cli/cmd/mode_test.go, src/go/rpk/pkg/config/config.go, src/go/rpk/pkg/config/config_test.go
=> rpk/config: enable redpanda.developer_mode if mode=dev

src/js/modules/domain/generatedRpc/entitiesDefinition.json, tools/ts-generator/types/functions.ts, tools/ts-generator/types/test.ts, tools/ts-generator/types/types_gen_js.py
=> crc generator

src/go/rpk/pkg/cli/cmd/container/start.go, src/v/cluster/tests/commands_serialization_test.cc, src/v/storage/log_replayer.cc, tools/ts-generator/types/functions.ts
Changes came from #91, #108, #120 - I think
See: https://github.com/vectorizedio/redpanda/issues/105
=> build: Run vtools fmt

src/v/rpc/test/rpc_gen_cycling_test.cc
The race condition was triggered by the destruction of tmp dir
which removes files in d-tor. File removal triggers a callback
which depends on 'updated'. But at the point when 'tmp' is being
destroyed the 'updated' is already destroyed (because of deterministic
destruction rule). To fix this we have to postprone the destruction of
the 'updated' var.
=> Fix race condition in rpc test

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/coproc/CMakeLists.txt, src/v/coproc/tests/coproc_test_fixture.cc, src/v/coproc/tests/coproc_test_fixture.h, src/v/coproc/tests/router_test.cc, src/v/coproc/tests/router_test_fixture.cc, src/v/coproc/tests/router_test_fixture.h, src/v/coproc/tests/script_manager_service_test.cc, src/v/coproc/tests/supervisor_test_fixture.h, src/v/coproc/tests/utils.cc, src/v/coproc/tests/utils.h, src/v/kafka/requests/fetch_request.cc, src/v/kafka/requests/fetch_request.h, src/v/redpanda/application.cc
=> Copro - refactor unit tests

src/v/coproc/tests/utils.h
=> coproc: update transport for reloadable credentials

CODEOWNERS
=> coproc: fix coprocessor codeowner path

src/v/kafka/requests/fetch_request.cc, src/v/kafka/requests/fetch_request.h, src/v/kafka/types.h
Processing fetch request partitions asynchronously.
=> Async fetch request processing

src/v/kafka/requests/list_offsets_request.cc, src/v/kafka/requests/metadata_request.cc, src/v/kafka/requests/metadata_request.h, src/v/model/fundamental.h
=> Make portions of metadata API copro aware

src/v/pandaproxy/client/test/fetch.cc
=> ppc/test: Don't check high_watermark

licenses/bsl.md
=> Changed date in BSL

.dir-locals.el, src/v/coproc/CMakeLists.txt, src/v/coproc/router.cc, src/v/coproc/router.h, src/v/coproc/router_source_manager.cc, src/v/coproc/router_source_manager.h, src/v/coproc/service.cc, src/v/coproc/tests/two_way_split_copro.h, src/v/coproc/tests/utils.h, src/v/kafka/requests/fetch_request.cc, src/v/kafka/requests/fetch_request.h
=> Copro router lifetime

src/js/modules/supervisors/FileManager.ts, src/js/test/supervisors/FileManager.test.ts
when a file is removed from the active folder, the supervisor implementation
notices that and sends a request to redpanda in order to disable that coprocessor
=> coproc: add disable coprocessor

tests/ci/build-pkg.yml, tests/ci/build-release.yaml, tests/ci/build.yaml
Use the new workflow to archive dev packages to be used in everyday testing & CI.
=> Create dev packages

.github/workflows/lint.yml, tests/docker/ducker-rp
Fixes #105
Before merging we have to host the [dockerfile ](https://gist.github.com/0xdiba/6e91fbe3fb3a84ed0ec0e06fb86b390e) under our organization.
On a next iteration we can create the image using the exact same commit we use for the internal llvm build.
=> actions: Add linting workflow

licenses/bsl.md
=> licence: updated bsl date

src/go/rpk/pkg/config/manager.go
Use different `config.Manager` instances when concurrent writes to the underlying `viper.Viper` instance are likely.
=> rpk: Fix concurrency bugs

src/js/build.sh, src/js/package.json
=> fix build folder path

tests/docker/Dockerfile, tests/docker/ducker-rp, tests/rptest/chaos/redpanda_muservice.py, tests/rptest/services/redpanda.py, tests/rptest/tests/prefix_truncate_recovery_test.py, tools/storage.py
=> Integration test suite fixes

tests/ci/build-pkg.yml, tests/ci/build-release.yaml, tests/ci/build.yaml
This was not used and was causing dirty package builds.
=> remove relic build deps install

docs/www/advanced-configuration.md, docs/www/ansible-terraform.md, docs/www/autotune.md, docs/www/configuration.md, docs/www/monitoring.md, docs/www/rpk-commands.md, docs/www/rpk-modes.md, docs/www/setup-guide.md, docs/www/support.md, docs/www/well-known-io.md
Migrating docs to colocate with redpanda codebase to make it available
for any user to access docs after installation.
=> redpanda: add docs from www repo

src/v/http/client.cc, src/v/http/client.h, src/v/http/iobuf_body.cc, src/v/http/iobuf_body.h, src/v/http/tests/http_client_test.cc
Fix framing issue in http parser. Make iobuf_body more robust to any such issues in the future and add unit-tests that check for similar problems.
=> Fix http chunked decoding

src/consistency-testing/gobekli/gobekli/chaos/analysis.py
Gobekli uses log rotation to prevent log files from uncontrollable growth. This change updates a report generator to use all rotated files (lat.log, lat.log.1 lat.log.2) instead of only the recent one (lat.log).
Example of a long (30 mins) test report generated from several log files: https://redpanda-reports.s3-us-west-2.amazonaws.com/redpanda/1607204879/mrsw/inject-recover/strobe.leader/1607204935/index.html
=> gobekli/reporting: support rotated log files

src/v/kafka/requests/fetch_request.cc, src/v/kafka/requests/fetch_request.h, src/v/kafka/tests/fetch_test.cc
In order to minimize the overhead of cross communication while reading
data requested in fetch request implemented grouping partitions owned by
the same shard into a single cross core dispatch. Previously each NTP
owned by the same shard was read with separate cross core request which
introduced unnecessary cross core communication overhead
Fixes #275
=> k/fetch_request: grouping partition fetch requests by shard

cmake/oss.cmake.in, src/v/bytes/bytes.h, src/v/bytes/tests/CMakeLists.txt, src/v/bytes/tests/bytes_tests.cc, src/v/bytes/tests/utils.h, src/v/cluster/controller_backend.cc, src/v/hashing/secure.h, src/v/kafka/CMakeLists.txt, src/v/kafka/security/scram_algorithm.cc, src/v/kafka/security/scram_algorithm.h, src/v/kafka/tests/CMakeLists.txt, src/v/kafka/tests/scram_algorithm_test.cc
Adds SCRAM message types, algorithm, and tests required for SCRAM-based SASL authentication.
=> Add scram authentication messages and algorithm

src/v/rpc/test/rpc_gen_cycling_test.cc, src/v/rpc/transport.cc, src/v/rpc/transport.h
Added request sequencing in RPC layer to prevent reordering. 
=> Rpc requests sequence

.github/workflows/homebrew-publish.yml
=> github action: Updated the homebrew publish workflow to correct branch

src/v/kafka/requests/requests.cc, src/v/storage/segment_appender.cc
=> Fix typos in logs

src/v/pandaproxy/client/test/fetch.cc, src/v/pandaproxy/client/test/pandaproxy_client_fixture.h
Similar to `redpanda/tests/fixture/make_data` but supports multiple partitions.
Use `make_data` for `fetch`
Use `wait_for_partition_offset` from fixture
=> ppc/fixture: Introduce make_data

src/go/rpk/go.mod, src/go/rpk/go.sum, src/go/rpk/pkg/cli/cmd/status.go, src/go/rpk/pkg/cli/cmd/status_test.go
=> rpk/status: Omit status report if --send is passed

src/js/modules/supervisors/FileManager.ts, src/js/test/supervisors/FileManager.test.ts
remove coprocessor from memory (Repository) before make disable
coprocessor request, instance to after resolve request it.
=> coproc: remove coproc before make disable request

src/v/http/tests/http_client_test.cc
=> http: fix for boost 1.75

src/js/modules/supervisors/Repository.ts, src/js/modules/utilities/IOBuf.ts, src/js/test/rpc/server.test.ts, tools/ts-generator/types/functions.ts
=> Fixing IObuf issue related to reserve

src/v/kafka/security/scram_algorithm.cc
Likely an issue with gcc, memory usage is unacceptably high using c++20 with
these regular expressions and the ctre library. Since this is not a problem
with clang and our release builds use clang, we fall back to slow std::regex
when using gcc. The following ticket is tracking the issue, and the fallback
can be removed once the issue is resolved:
https://github.com/hanickadot/compile-time-regular-expressions/issues/155
=> kafka: use std::regex with gcc to avoid memory bug

src/v/redpanda/application.cc
serves dashboard from `/dashboard` instead of `/`which seems to behave a little more reasonably, and hacks the request metadata to make the built-in seastar directory handler behave more naturally w.r.t. to the url constructions.
```
diff --git a/conf/redpanda.yaml b/conf/redpanda.yaml
index be38ad49b..cdcd71b31 100644
--- a/conf/redpanda.yaml
+++ b/conf/redpanda.yaml
@@ -19,6 +19,7 @@ redpanda:
data_directory: "/var/lib/redpanda/data"
+  dashboard_dir: "/tmp/foobar"
node_id: 1
```
example
```
[nwatkins@gordon redpanda]$ echo index > /tmp/foobar/index.html
[nwatkins@gordon redpanda]$ echo asdf > /tmp/foobar/asdf.html
[nwatkins@gordon redpanda]$ curl localhost:9644/dashboard/
index
[nwatkins@gordon redpanda]$ curl localhost:9644/dashboard//
index
[nwatkins@gordon redpanda]$ curl …
```
=> app: server dashboard under sub-directory

src/v/hashing/tests/xx_tests.cc, src/v/hashing/xx.h
Added override for `incremental_xxhash64::update` method for
`named_type`. The override prevents incorrect override to be selected
when extending hash with named types.
The incorrect override selection caused coordinator to be incorrectly
selected when there is more than one partition in `kafka_internal/group`
topic. The same group name was randomly assigned to different
coordinator.
Fixes: #386
=> h/xx: added update method override for named_type

src/v/pandaproxy/client/CMakeLists.txt, src/v/pandaproxy/client/assignment_plans.cc, src/v/pandaproxy/client/assignment_plans.h, src/v/pandaproxy/client/brokers.cc, src/v/pandaproxy/client/brokers.h, src/v/pandaproxy/client/client.cc, src/v/pandaproxy/client/client.h, src/v/pandaproxy/client/configuration.cc, src/v/pandaproxy/client/configuration.h, src/v/pandaproxy/client/consumer.cc, src/v/pandaproxy/client/consumer.h, src/v/pandaproxy/client/error.h, src/v/pandaproxy/client/test/CMakeLists.txt, src/v/pandaproxy/client/test/consumer_group.cc, src/v/pandaproxy/client/test/pandaproxy_client_fixture.h
=> Pandaproxy consumer groups part1

src/v/http/client.cc, src/v/http/client.h, src/v/http/tests/http_client_test.cc
Naturally, http header is not available until enough data is received
from the server. Existing http::client::response_stream interface
allows to check if the header is available but it doesn't allow
to make sure that this is the case. This makes api client interface
inconvenient because the user of such api have to read from the
response_stream, wait until the header is available and then decide if
the result is OK or an error was triggered.
This commit adds 'prefetch_headers' method that reads data from the
socket until the header becomes available for fetching. It's supposed
to be used for error handling in situations when we need to check
the response status first and then proceed with normal operation.
The 'prefetch_headers' implementation is based on existing 'recv_some'
method. It …
=> http: Add HTTP prefetch

src/v/storage/index_state.cc, src/v/storage/index_state.h, src/v/storage/tests/CMakeLists.txt, src/v/storage/tests/index_state_test.cc
The on-disk size calculation was under counted. Fixed that and added some size checks.
=> Fix index state on-disk size calculation

src/js/test/rpc/server.test.ts, tools/ts-generator/rpc/rpc_gen_js.py
problem: when we send a request that can have multiples process_batch_request,
wasm engine tries to read those process_batch_request, if that request size is
equal to buffer size, the wasm engine hasn't started to read the next request with
another process_batch_request
=> coproc/js: fix read method for read request buffer

.github/workflows/consistency-test.yml, .github/workflows/packages-created.yml, .github/workflows/slash-commands.yml
Change some secret names in workflows to more descriptive ones.
=> ci: change secret names

src/v/bytes/iobuf.cc, src/v/bytes/iobuf.h, src/v/s3/CMakeLists.txt, src/v/s3/client.cc, src/v/s3/client.h, src/v/s3/error.cc, src/v/s3/error.h, src/v/s3/logger.h, src/v/s3/signature.cc, src/v/s3/signature.h, src/v/s3/test_client/CMakeLists.txt, src/v/s3/test_client/s3_test_client_main.cc, src/v/s3/tests/CMakeLists.txt, src/v/s3/tests/s3_client_test.cc, src/v/s3/tests/signature_test.cc
This PR adds S3 REST API client with unit-tests and test-client.
=> S3 REST API client

cmake/oss.cmake.in, src/v/storage/disk_log_impl.cc, src/v/storage/opfuzz/opfuzz.cc, src/v/storage/opfuzz/opfuzz.h, src/v/storage/segment_utils.cc, src/v/storage/segment_utils.h, src/v/storage/tests/storage_e2e_test.cc
* Concurrency treatments for adjacent segment compaction
* Concurrent compaction feature in op fuzzer
=> Compaction concurrency fixes

src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/replicate_batcher.cc, src/v/raft/replicate_batcher.h, src/v/raft/tests/append_entries_test.cc, src/v/raft/tests/raft_group_fixture.h
This reverts commit 0e9b56737a581adb41b88a27d7ba4d715a05808a, reversing
changes made to 5f4fea4896c59ec374052710efa36c373d7eb0fb.
=> Revert "Merge pull request #396 from rystsov/conditional-replicate"

src/v/s3/client.cc, src/v/s3/client.h, src/v/s3/error.cc, src/v/s3/error.h, src/v/s3/logger.h, src/v/s3/signature.cc, src/v/s3/signature.h, src/v/s3/test_client/s3_test_client_main.cc, src/v/s3/tests/s3_client_test.cc, src/v/s3/tests/signature_test.cc
=> s3: change license headers

src/go/k8s/controllers/redpanda/cluster_controller.go, src/go/k8s/controllers/redpanda/cluster_controller_test.go
With this we get automatic cleanup of all created resources (I tested it locally and when we have e2e tests in place, we should also write an automated test).
=> operator/controller: Set ownerReference for created objects

src/v/cluster/controller.h, src/v/raft/id_allocator_stm.h
fixes skewed merge of id_allocator
=> fixes skewed merge of id_allocator

docs/www/faq.md, docs/www/production-deployment.md, docs/www/quick-start-docker.md, docs/www/quick-start-kubernetes.md, docs/www/quick-start-linux.md, docs/www/quick-start-macos.md, docs/www/rpk-container-guide.md
- Added Multiple Quickstarts - Docker, K8, Mac, Linux
- Added a production deployment page
- Added a FAQ
=> Documentation Updates

.dir-locals.el
=> .dir-locals.el add /vbuild to lsp-file-watch-ignored list

docs/www/quick-start-nodejs .md
Add nodejs blog to docs, removed the blog intro
=> Add nodejs blog to docs

docs/www/guide-nodejs.md
=> Updated NodeJS Guide

docs/www/support.md
=> Updated links in support.md

docs/www/advanced-configuration.md
=> docs: Improve advanced-configuration.md

src/v/cluster/controller_backend.cc
We shouldn't ignore background future exception as it will be reported
by seastar.
=> c/controller_backend: do not ignore background exception

src/go/k8s/Makefile
=> operator: Crlfmt should ignore generated files

src/v/cluster/members_manager.cc
Accessing exception of ready future which has result caused segmentation
fault during logging.
Fixes: #519 
=> c/members_manager: fixed incorrect handling of join request exception

src/v/raft/consensus.cc, src/v/raft/tests/CMakeLists.txt, src/v/raft/tests/state_removal_test.cc, src/v/raft/types.h, src/v/storage/snapshot.cc, src/v/storage/snapshot.h
=> Remove snapshot when removing raft state

src/go/rpk/pkg/cli/cmd/topic/create.go, src/go/rpk/pkg/cli/cmd/topic_test.go
=> rpk: improve rpk create topic output

src/go/k8s/controllers/redpanda/cluster_controller.go
=> operator: Fix build error

CODEOWNERS
=> Add owner for docs

src/go/k8s/controllers/redpanda/cluster_controller.go
=> operator/controller: Fix equality/nonequality in error handling

src/go/rpk/pkg/api/api.go, src/go/rpk/pkg/api/api_test.go
=> rpk/api/metrics: Send the value of $REDPANDA_ENVIRONMENT

src/v/kafka/server/handlers/fetch.cc
Several error and success cases did not fill in the high watermark and last stable offset for fetch responses which resulted in some client applications behaving incorrectly in workloads related to tailing a log.
@mmaslankaprv are there other return paths that i may have missed, such as fetch session handling? were these omitted originally on purpose?
cc @rkruze
=> Fix missing partition offset metadata for some fetch responses

src/go/k8s/controllers/redpanda/cluster_controller.go, src/go/k8s/pkg/labels/labels.go, src/go/k8s/pkg/labels/labels_test.go, src/go/k8s/pkg/resources/service.go, src/go/k8s/pkg/resources/statefulset.go
=> operator: label selector creation

src/v/kafka/server/handlers/describe_configs.cc, src/v/kafka/server/handlers/topics/topic_utils.cc, src/v/kafka/server/handlers/topics/topic_utils.h, src/v/kafka/server/tests/topic_utils_test.cc, tests/rptest/clients/kafka_cli_tools.py, tests/rptest/clients/types.py
=> kafka: describe configs should report cleanup policy

src/go/k8s/kuttl-test.yaml, src/go/k8s/tests/e2e/scale-up/00-assert.yaml, src/go/k8s/tests/e2e/scale-up/01-assert.yaml, src/go/k8s/tests/e2e/scale-up/01-one-replica.yaml, src/go/k8s/tests/e2e/scale-up/02-assert.yaml, src/go/k8s/tests/e2e/scale-up/02-two-replicas.yaml
=> operator/tests: test for scaling up redpanda

src/go/k8s/README.md
=> k8s: Update README example path

cmake/oss.cmake.in
=> build: update seastar for http mime-types

src/v/dashboard/package.json, src/v/dashboard/src/App.tsx, src/v/dashboard/src/components/shared/GraphSelector/GraphSelector.tsx, src/v/dashboard/src/components/shared/IconButton/IconButton.scss, src/v/dashboard/src/components/shared/Logo.tsx, src/v/dashboard/src/components/shared/TimeWindowSelector.tsx, src/v/dashboard/src/components/shared/TimeseriesChart/TimeseriesChart.tsx, src/v/dashboard/src/hooks/useInterval.ts, src/v/dashboard/src/hooks/useSnapshots.ts, src/v/dashboard/src/utils/fetchPrometheusSnapshot.ts
- Replace test data with real stream data
- Fix for relative asset paths in package.json
- Added Timewindow selector
=> Dashboard: connect to redpanda prometheus data

docs/www/quick-start-docker.md, docs/www/quick-start-linux.md
=> Update Quick Starts

src/v/raft/tests/raft_group_fixture.h, src/v/rpc/connection_cache.cc, src/v/rpc/connection_cache.h, src/v/rpc/transport.cc
=> Fix use after free socket

src/v/rpc/test/CMakeLists.txt
* Renamed the tests to be more descriptive
=> rpc/test: Use fewer test binaries

src/go/k8s/pkg/resources/statefulset.go
=> operator: Set replicas to desired number

src/v/cluster/cluster_utils.h, src/v/kafka/server/group_manager.cc, src/v/kafka/server/group_manager.h, src/v/raft/id_allocator_stm.cc, src/v/raft/id_allocator_stm.h
=> Accumulated miscellaneous changes

CONTRIBUTING.md
=> doc: fix typo in contributing.md

src/v/coproc/tests/CMakeLists.txt
=> coproc/test: Use fewer test binaries

src/v/model/tests/CMakeLists.txt, src/v/model/tests/ntp_path_test.cc, src/v/model/tests/topic_view_tests.cc
* Renamed the tests to be more descriptive
* Ensure all test have labels
=> model/test: Use fewer test binaries

src/v/kafka/server/tests/CMakeLists.txt, src/v/kafka/server/tests/error_mapping_test.cc, src/v/kafka/server/tests/scram_algorithm_test.cc, src/v/kafka/server/tests/timeouts_conversion_test.cc, src/v/kafka/server/tests/topic_utils_test.cc, src/v/kafka/server/tests/types_conversion_tests.cc
* Renamed the tests to be more descriptive
=> k/server: Use fewer test binaries

src/v/redpanda/application.cc
It may happen that when redpanda starts an exception is thrown and
controller service is not started. We have to prevent shutting down the
controller service input if it was not started as it may cause
segmentation fault. (raft0 pointer is null before starting controller)
Fixes: #657
=> application: shutdown controller only when it was started

docs/www/quick-start-linux.md
Resolving some anamolies from the Linux quick start update
=> docs: fix typo, add code style, remove extra heading

src/v/cluster/controller.cc, src/v/redpanda/application.cc
=> Fix loading credentials for http server

src/v/raft/tests/bootstrap_configuration_test.cc, src/v/raft/tests/mux_state_machine_fixture.h, src/v/redpanda/application.cc, src/v/storage/log_manager.cc, src/v/storage/log_manager.h, src/v/storage/opfuzz/opfuzz_test.cc, src/v/storage/tests/half_page_concurrent_dispatch.cc, src/v/storage/tests/storage_test_fixture.h
=> Compaction io priority

src/go/k8s/apis/redpanda/v1alpha1/cluster_types.go, src/go/k8s/pkg/resources/statefulset.go, src/go/k8s/pkg/resources/statefulset_update.go
=> operator: provide convenience method to get image and label

src/v/kafka/server/handlers/create_topics.cc
Whitelist topic creation options that we explicitly support
Close #249
=> Whitelist topic creation options

src/v/kafka/server/handlers/describe_configs.cc, src/v/kafka/server/requests.cc, src/v/kafka/types.h, tests/docker/Dockerfile, tests/rptest/clients/kafka_cli_tools.py, tests/rptest/tests/kafka_client_compat_test.py
Reports some broker-level configuration settings in the kakfa describe configs API.
fixes: #678
=> kafka: support broker entity type in describe configs

src/go/k8s/Makefile, src/go/k8s/tests/README.md
=> operator/tests: support running single e2e test

docs/www/faq.md, docs/www/quick-start-docker.md, docs/www/quick-start-kubernetes.md, docs/www/quick-start-linux.md, docs/www/quick-start-macos.md
=> docs: Change relative links to permanent

src/go/k8s/pkg/resources/service.go
REF: http://www.dns-sd.org/trailingdotsindomainnames.html
=> operator: Change the service DNS to absolute domain name

src/go/k8s/apis/redpanda/v1alpha1/cluster_webhook.go, src/go/k8s/apis/redpanda/v1alpha1/cluster_webhook_test.go
To help users the webhook now check if ports are the same.
=> operator/webhook: Validate port collision in configuration

src/go/rpk/pkg/cli/cmd/common/common.go
Improve error message when the redpanda client & admin can't be initialized.
Fix #724
=> rpk/cli/common: Improve error msg when the RP client can't be init'd

tests/ci/cloudbuild.yaml
=> gcb: swap order of checkout, task-install steps

src/go/k8s/pkg/resources/configmap.go
=> operator: fix missing fmt import

docs/www/guide-nodejs.md, docs/www/quick-start-docker.md, docs/www/quick-start-linux.md, docs/www/quick-start-macos.md
- Rewrite MacOS Quick Start Guide
- Update code fence syntax and deprecated command in Docker
- Minor style in Linux and NodeJS
Squashes commits from https://github.com/vectorizedio/redpanda/pull/741
=> docs: MacOS Quick Start Guide updates

.github/pull_request_template.md
=> templates: Add section to PR description that explains the feature

docs/www/autotune.md, docs/www/configuration.md, docs/www/guide-nodejs.md, docs/www/guide-rpk-container.md, docs/www/production-deployment.md, docs/www/rpk-commands.md, docs/www/well-known-io.md
Aligns the page titles to the docs table of contents.
=> Change titles to match TOC

docs/www/archival.md
The doc contains basic overview, configuration options for redpanda,
and configuration for cloud storage provider.
=> archival: Add archival doc

tests/rptest/services/redpanda.py
test/rptest: Fixup linting for Redpanda service
=> test/rptest: Fixup linting for Redpanda service

docs/www/guide-wasm-elastic.md
add an example with wasm and elastic
=> coproc/docs: add example wasm + elastic search

tests/ci/cloudbuild.yaml
invert parent-child relationship of vtools and redpanda repositories
=> gcb: invert vtools-redpanda relationship

src/go/k8s/config/rbac/role.yaml, src/go/k8s/controllers/redpanda/cluster_controller.go
=> operator: group resource to reduce yaml size

src/go/k8s/kuttl-helm-test.yaml
Currently we have 2 kuttl suites: for helm and for kustomize.
Last change was applied only for kustomize portion.
=> operator: Align helm e2e kuttl parallelism

.gitignore, taskfiles/dashboard.yml, taskfiles/docker.yml, taskfiles/main.yml, taskfiles/rp.yml, taskfiles/rpk.yml
Adds tasks for building/unit-testing RP and RPK.
=> task: add taskfiles for redpanda build

src/v/cluster/CMakeLists.txt, src/v/cluster/id_allocator_frontend.cc, src/v/cluster/id_allocator_frontend.h, src/v/cluster/id_allocator_stm.cc, src/v/cluster/partition.cc, src/v/cluster/persisted_stm.cc, src/v/cluster/persisted_stm.h, src/v/cluster/seq_stm.cc, src/v/cluster/seq_stm.h, src/v/cluster/tests/CMakeLists.txt, src/v/cluster/tests/seq_stm_tests.cc, src/v/cluster/tests/tm_stm_tests.cc, src/v/cluster/tm_stm.cc, src/v/cluster/tm_stm.h, src/v/cluster/types.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/model/metadata.h, src/v/model/model.cc, src/v/model/record.h, src/v/model/record_batch_types.h, src/v/utils/expiring_promise.h
Adds dependencies for implementing transactions including an implementation of the transaction coordinator (tm_stm).
=> Adds transaction coordinator state machine

.gitignore, .vtools.yml
this file is now dynamically generated with task
=> vtools-py: remove config file

src/go/k8s/controllers/redpanda/cluster_controller.go
The node object is not used when subdomain is provided so we should not be
querying it. This surfaced during testing in kind when nodes does not have name
provided.
ERROR	controller-runtime.manager.controller.cluster	Reconciler error
{"reconciler group": "redpanda.vectorized.io", "reconciler kind": "Cluster",
"name": "cluster-tls", "namespace": "helm-test", "error": "failed to construct
external node list: failed to retrieve node : Node \"\" not found"}
Release note: …
=> operator: when subdomain is provided, don't query node

taskfiles/rp.yml
- properly set build type for cmake
- obtain full path of cmake folder
=> Misc. taskfiles/rp.yml fixes

src/v/kafka/protocol/fetch.h, src/v/kafka/server/handlers/find_coordinator.cc, src/v/raft/heartbeat_manager.cc, src/v/raft/log_eviction_stm.cc, src/v/raft/vote_stm.h, src/v/storage/snapshot.cc, src/v/utils/file_sanitizer.h, src/v/utils/unresolved_address.h
Periodic dump of queued up miscellaneous changes, mostly clang-tidy warnings.
=> Miscellaneous fixes and changes

src/v/redpanda/main.cc
Added community links at the start of the redpanda binary.
=> redpanda: add explicit community links to main

src/v/bytes/iobuf.h, src/v/bytes/tests/iobuf_tests.cc, src/v/model/adl_serde.cc, src/v/model/adl_serde.h, src/v/model/record.h, src/v/redpanda/application.cc, src/v/reflection/adl.h, src/v/resource_mgmt/cpu_scheduling.h, src/v/storage/batch_cache.cc, src/v/storage/batch_cache.h, src/v/storage/log_manager.cc, src/v/storage/tests/batch_cache_reclaim_test.cc, src/v/storage/tests/batch_cache_test.cc
Optimized batch cache to prevent memory fragmentation and reactor stalls. 
=> Batch cache optimizations

.github/workflows/k8s-build-and-test.yml, src/go/k8s/Makefile
Automates publishing of docker images to dockerhub.
fixes #690
=> operator: automate pushing operator images to dockerhub

src/go/k8s/apis/redpanda/v1alpha1/cluster_types.go, src/go/k8s/config/crd/bases/redpanda.vectorized.io_clusters.yaml, src/go/k8s/tests/e2e/create-topic-with-client-auth/00-assert.yaml
Admin certificate was introduced in #875
This adds missing test coverage and documentation.
=> operator: document admin client certificate

docs/www/quick-start-docker.md
=> Add cmd docker single node

src/go/k8s/controllers/redpanda/cluster_controller.go
The reason why we're hitting this is that kubernetes uses optimistic concurrency to deal with parallel updates of the same resource.
This is important to prevent these errors that are very prevalent in our logs:
failed to update cluster status nodes: Operation cannot be fulfilled on clusters.redpanda.vectorized.io \"cluster-tls\": the object has been modified; please apply your changes to the latest version and try again"}
https://github.com/kubernetes/client-go/blob/master/util/retry/util.go#L77
=> operator: retry status update to not hit conflicts

docs/www/intro-to-events.md
This article explains the background of events and streaming to help potential customers see the benefits of streaming.
=> docs: Add intro to streaming article

src/go/rpk/pkg/config/config_test.go, src/go/rpk/pkg/config/schema.go
Adds TLS fields under configuration.
=> rpk/config: add admin api tls

docs/www/archival.md, src/go/rpk/pkg/config/config_test.go, src/go/rpk/pkg/config/schema.go, src/v/archival/service.cc, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/application.cc
Rename configuration parameters related to archival storage
Fixes issues: #961 
Related to issue #961
Fixes documentation, rpk config, redpanda config.
=> archival: Fix archival configuration arguments

src/go/k8s/controllers/redpanda/cluster_controller.go, src/go/k8s/tests/e2e/produce-consume/00-assert.yaml
The condition was wrong for replicas.
=> operator: Fix condition for replicas number

src/go/k8s/pkg/resources/resource.go
I don't fully understand this but this is what the author's recommend. Let's trust them, I verified this solved lots of weird stuff I have saw in logs.
https://github.com/banzaicloud/istio-operator/blob/8bd406e14079ce43fe1908403bb2892c2549ab1e/pkg/k8sutil/resource.go#L109
=> operator: do not set resource version before annotation

src/v/kafka/protocol/fetch.h, src/v/kafka/server/handlers/fetch.cc
Reverts vectorizedio/redpanda#990
=> Revert "Returning log start offset in fetch response"

taskfiles/rp.yml
=> task/rp: fix for permission changes of dockerfile

src/go/k8s/config/crd/bases/redpanda.vectorized.io_clusters.yaml
I forgot to push this in one of the previous PRs. We should prevent this in CI #1013
=> operator: missing generated manifests

cmake/oss.cmake.in
Update seastar to 7b9dbca45617dd04e47b7dec9aa53bcbe900ed23
Required for https://github.com/vectorizedio/redpanda/pull/986
none
=> 3rdparty: Update Seastar to 7b9db

src/v/config/configuration.h, src/v/config/data_directory_path.h, src/v/config/property.h, src/v/kafka/server/handlers/describe_configs.cc
Fixed describing broker configuration resources. Added handling synonyms, missing properties and aligned returned resources names with names returned by Kafka .
=> Describe broker config resources

src/go/k8s/pkg/resources/certmanager/common_name.go, src/go/k8s/pkg/resources/certmanager/common_name_test.go
New files missed copyright notice.
=> operator: adding missing copyright

tests/rptest/test_suite_quick.yml
This test is currently failing. Will get re-enabled soon
=> ducktape: disable failing test

src/go/k8s/tests/e2e/update-image/00-assert.yaml
We can remove it after we finish fighting this flake.
Related to #1030 
=> operator: add additional log collectors for flaky test

cmake/oss.cmake.in
Updated seastar version to the one including recent http server changes
adding more context to http request. Those changes are required to fully
support multiple listeners in Pandaproxy
=> cmake/oss: updated seastar version

src/v/redpanda/admin/api-doc/security.json, src/v/redpanda/application.cc, src/v/security/credential_store.h, tests/rptest/tests/scram_test.py
**_security: add http admin api for listing users_**
=> security: add http admin api for listing users

docs/www/data-archiving.md, docs/www/intro-to-events.md, docs/www/quick-start-docker.md
=> Merge docs changes into dev

src/v/archival/tests/CMakeLists.txt, src/v/bytes/tests/CMakeLists.txt, src/v/cluster/tests/CMakeLists.txt, src/v/config/tests/CMakeLists.txt, src/v/http/tests/CMakeLists.txt, src/v/json/tests/CMakeLists.txt, src/v/random/CMakeLists.txt, src/v/reflection/test/CMakeLists.txt, src/v/s3/tests/CMakeLists.txt, src/v/storage/tests/CMakeLists.txt, src/v/storage/tests/storage_test_fixture.h, src/v/utils/tests/CMakeLists.txt, src/v/utils/tests/base64_test.cc, src/v/utils/tests/named_type_tests.cc, src/v/utils/tests/string_switch_test.cc, src/v/utils/tests/tristate_test.cc
Various test improvements:
* Add labels to all the tests so that the summary is complete.
* Use fewer binaries
* Improve runtimes
* Reduce disk space
* Renamed the tests to be more descriptive
Changes in [force-push](https://github.com/vectorizedio/redpanda/compare/114c141f41f2bebfcb2770bca1630ef2d3122acc..20de4ae341a01a6060adaaf6fbf665e9e55ca0b9)
* Clean rebase
* Split `log_replayer_test` out to it's own test due to ASAN errors when combined with other test files
Changes in [force-push](https://github.com/vectorizedio/redpanda/compare/20de4ae341a01a6060adaaf6fbf665e9e55ca0b9..6c278136e3a0c669677dfc20a5a0ea7d2fbea890)
* Clean rebase
=> Test with fewer binaries

src/v/cluster/commands.h, src/v/cluster/controller.cc, src/v/cluster/controller.json, src/v/cluster/security_frontend.cc, src/v/cluster/security_frontend.h, src/v/cluster/security_manager.cc, src/v/cluster/security_manager.h, src/v/cluster/service.cc, src/v/cluster/service.h, src/v/cluster/types.cc, src/v/cluster/types.h, src/v/kafka/server/handlers/delete_acls.cc, src/v/kafka/server/handlers/details/security.h, src/v/security/acl.h, src/v/security/acl_store.cc, src/v/security/acl_store.h, src/v/security/authorizer.h
Adds support for Kafka's ACL Deletion API.
=> kafka: implement acl deletion

docs/www/intro-to-events.md
=> docs: Update intro to events title

docs/www/intro-to-events.md
=> docs: Fix broken build

src/go/rpk/pkg/config/config_test.go, src/go/rpk/pkg/config/schema.go
Adds `enable_sasl` to rpk's config.
=> rpk/config: add enable_sasl

src/go/rpk/pkg/cli/cmd/redpanda/start.go, src/go/rpk/pkg/cli/cmd/redpanda/start_test.go
Allow passing unknown flags without the need to pass '--' first.
Before:
`rpk redpanda start -- --seastar-flag=1`
After:
`rpk redpanda start --seastar-flag=1`
Fix #1060
Release note: rpk start now allows passing arbitrary flags, which are passed through to redpanda.
=> rpk/start: Allow passing unknown flags

docs/www/configuration.md
=> Docs: Make seed IP generic in config

docs/www/rpk-commands.md
Updates the command help from rpk.
=> Improve rpk command docs

tests/rptest/test_suite_quick.yml
Disable test{_remove_consumer_validation in CI
Fixes issues: CI
Release note: none
=> pp/ducktape: Disable test_remove_consumer_validation

src/v/kafka/server/handlers/sasl_handshake.h, tests/rptest/clients/python_librdkafka.py, tests/rptest/services/admin.py, tests/rptest/services/redpanda.py, tests/rptest/services/templates/redpanda.yaml, tests/rptest/tests/scram_test.py, tests/setup.py
* automatic superuser creation
* fix scram test to deal with ACLs
* adds support for librdkafka python client
=> test: fixes for authentication in ducktape

docs/www/rpk-commands.md
Add --topic-config to the rpk commands in docs.
=> docs: Add topic config to rpk commands

src/v/cluster/members_manager.cc
Added trying another server when requested one returned `success=false`. Additionally added log entry when processing join request returned an error.
none
=> Cluster join sequence improvements

taskfiles/dev.yml, taskfiles/main.yml, taskfiles/wasm.yml
=> Move the javascript build system into the public repo

src/v/kafka/server/handlers/create_topics.cc, src/v/kafka/server/handlers/describe_groups.cc
This PR completes coverage of authorization for the Kafka API set.
=> kafka: add authorization to describe groups and create topics api

src/go/k8s/controllers/redpanda/metric_controller.go
=> operator/metrics: fix metric names

src/v/kafka/protocol/fetch.h
Fixed emptiness check in fetch request handler. Previously when empty fetch request was received by redpanda we returned immediately after first read dispatch even if `max_wait_time` was configured in request
and reads have not returned any data. This behavior is incorrect since some partitions that are requested by the client may be stored in its fetch session. This way redpanda never debounced incremental fetch requests containing no partitions.
Fixed this issue by differentiating handling for incremental and session less fetch requests. Incremental fetch requests is claimed as being empty only when _both_ session partitions and request partitions are empty.
Describe in plain language the motivation (bug, feature, etc.) behind the change in this PR and how the included commits address …
=> k/fetch: fixed incorrect handling of empty incremental fetch requests

src/v/coproc/tests/read_materialized_topic_test.cc, src/v/kafka/protocol/metadata.h, src/v/kafka/server/handlers/metadata.cc, taskfiles/dev.yml, taskfiles/wasm.yml, tests/docker/Dockerfile, tests/rptest/services/redpanda.py, tests/rptest/test_suite_quick.yml, tests/rptest/tests/wasm_identity_test.py, tests/rptest/wasm/background_task.py, tests/rptest/wasm/topics_result_set.py, tests/rptest/wasm/wasm_build_tool.py, tests/rptest/wasm/wasm_test.py
More ducktape tests for wasm, specifically different use cases that arise when multiple scripts are running.
=> Multi-script ducktape tests for wasm

src/go/k8s/apis/redpanda/v1alpha1/cluster_types.go, src/go/k8s/config/crd/bases/redpanda.vectorized.io_clusters.yaml, src/go/k8s/config/samples/external_connectivity.yaml
Describe in the example that subdomain should be managed by different entity. It can be external dns.
Fix end user documentation for external connectivity naming convention.
=> operator: Add aditional comment to Redpanda operator sample

docs/www/data-archiving.md
This PR updates a table in data-archival.md with configuration parameters. Also, it adds MinIO configuration description which is useful for testing.
=> archival: Update configuration parameter names

src/v/cluster/partition.h, src/v/cluster/partition_probe.cc, src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/types.h
Added metrics that were missing to create more useful Grafana dashboard.
Fixes issues: #1116 
Added set of new metrics
=> Missing metrics

docs/www/quick-start-kubernetes.md
Updates the quick start guide for Kubernetes using the operator and sample resources.
=> Update kubernetes docs for operator

src/v/redpanda/application.cc
Print out number of cores, available  & reserved memory on redpanda startup.
Fixes issues: [#1147]
N/A
=> Print available system resources

src/go/k8s/kuttl-test.yaml, src/go/k8s/pkg/resources/statefulset.go, src/go/k8s/tests/e2e/external-connectivity/00-assert.yaml, src/go/k8s/tests/e2e/external-connectivity/00-external-connectivity.yaml, src/go/k8s/tests/e2e/produce-consume/00-assert.yaml
This change removes `check` and `smp` flag. Log level is changed to info
=> operator: Remove redpanda flags

src/v/coproc/tests/read_materialized_topic_test.cc, src/v/kafka/client/assignment_plans.cc, src/v/kafka/client/client.cc, src/v/kafka/client/consumer.cc, src/v/kafka/client/test/produce.cc, src/v/kafka/client/test/reconnect.cc, src/v/kafka/client/topic_cache.cc, src/v/kafka/protocol/metadata.h, src/v/kafka/protocol/schemata/CMakeLists.txt, src/v/kafka/protocol/schemata/generator.py, src/v/kafka/protocol/schemata/metadata_request.json, src/v/kafka/protocol/schemata/metadata_response.json, src/v/kafka/server/handlers/metadata.cc, src/v/kafka/server/tests/create_topics_test.cc, src/v/kafka/server/tests/delete_topics_test.cc, src/v/kafka/server/tests/metadata_test.cc, src/v/kafka/server/tests/request_parser_test.cc, src/v/kafka/server/tests/topic_recreate_test.cc, src/v/pandaproxy/handlers.cc
Use code generation for Kafka's metadata request type.
=> kafka: use code generation for metadata api request

docs/www/monitoring.md
Add metrics definitions so that customers know which metrics are most useful and what they mean.
=> docs: Add metrics definitions

docs/www/quick-start-docker.md
Add `--pull=always` to docker  commands to make sure users get the updated latest image, and other improvements for ease of use.
=> Add `--pull=always` to docker and other improvements

src/js/modules/hashing/crc32.ts, src/js/modules/rpc/require-native.ts, src/js/modules/rpc/server.ts, src/js/package-lock.json, src/js/package.json, src/js/webpack.js, tools/ts-generator/example/functions.ts, tools/ts-generator/rpc/example/generatedServer.ts, tools/ts-generator/rpc/rpc_gen_js.py, tools/ts-generator/types/functions.ts
This PR bundles the entire wasm engine source code into one .js file and a separate .node file. All of the source code and its dependencies are bundled together and can execute on any machine with the minimum nodejs runtime installed.
The purpose of this change is to use it within a wider scope of preparing wasm for rpm and deb packaging.
=> Bundling the wasm engine with webpack 

src/v/pandaproxy/json/requests/fetch.h, src/v/pandaproxy/test/consumer_group.cc, src/v/pandaproxy/test/fetch.cc, tests/rptest/tests/pandaproxy_test.py
Ignore config batches
Release note: pandaproxy: no longer returns kafka configuration batches
=> pandaproxy: Skip config batches

docs/www/quick-start-kubernetes.md
Update the Kubernetes Quick Start to show the simplest way to success.
=> Remove advanced samples; Add link to samples in repo; Change k8s rpk commands to use one-node-cluster

docs/www/guide-nodejs.md
=> docs: Add frontmatter to nodejs guide

docs/www/quick-start-kubernetes.md
Fix the Kubernetes Quick Start to use ordered list instead of bullets.
=> docs/k8s: Change bullets to ordered

docs/www/quick-start-kubernetes.md
Fix formatting that created code block including code fence backticks.
=> docs: Remove code fence formatting from indented code

src/go/k8s/tests/e2e/update-conf-image/00-assert.yaml, src/go/k8s/tests/e2e/update-conf-image/00-configurator.yaml, src/go/k8s/tests/e2e/update-conf-image/02-assert.yaml, src/go/k8s/tests/e2e/update-conf-image/02-new-configurator.yaml
Add availableReplicas check in update-conf-image assert in case it helps pass tests on github. We might need a way to check webhook is ready.
=> operator/tests: add availableReplicas check in update-conf-image assert

docs/www/quick-start-kubernetes.md
=> Change cert-manager command to use helm; 1-node GKE cluster

src/go/k8s/tests/e2e/update-conf-image/00-assert.yaml, src/go/k8s/tests/e2e/update-conf-image/02-assert.yaml, src/go/k8s/tests/e2e/update-conf-image/02-new-configurator.yaml
This fixes the current flake on dev.
=> operator: Properly wait for webhook to be ready

src/go/rpk/pkg/cli/cmd/cloud.go
It's not supposed to be used just yet.
=> rpk/cloud: hide cloud command

src/go/rpk/Makefile
To be able to run formatter locally.
=> rpk/ci: Add makefile target for crlfmt

docs/www/configuration.md
`pandaproxy_client.broker` -> `pandaproxy_client.brokers`
=> docs: Fix pandaproxy_client.brokers

src/go/k8s/docs/external-connectivity-digital-ocean.md
Add steps to run operator on Digital Ocean.
Next steps should be to create 1-click-app for kubernetes on Digital Ocean
=> operator/docs: add steps for external cluster on Digital Ocean

docs/www/configuration.md
The configuration page shows an example of configuration options that you can change. The config-reference shows all configuration options.
=> Add config reference to show all configuration options

docs/www/production-deployment-automation.md, docs/www/production-deployment.md
Highlights manual installation as the primary production install method.
=> Move manual install to primary install method

src/v/cluster/controller_backend.cc
Added logging failed partition reconciliation attempts.
=> c/controller_backend: logging failed reconciliation attempts

src/go/k8s/config/rbac/role.yaml, src/go/k8s/controllers/redpanda/cluster_controller.go, src/go/k8s/pkg/resources/certmanager/certificate.go, src/go/k8s/pkg/resources/cluster_service.go, src/go/k8s/pkg/resources/ingress.go
Adding an ingress resource that gets created when pandaproxy is setup with external connectivity. Also adding a service across the pandaproxy ports, to be used by the ingress.
=> operator: introduce ingress for pandaproxy

docs/www/kubernetes-external-connect.md
Add headings to the article for setting up K8s cluster with external access.
=> docs: Add headings to K8s external article

docs/www/kubernetes-external-connect.md
Fixing some typos in the k8s docs
=> Fix typos k8s

src/v/raft/append_entries_buffer.cc
Append entries buffer collect append entries requests coalesce them and
execute all requests at once under raft `_op_lock` mutex. Callers are
released after batch of request is executed in `raft::consensus`.
Callers promises are stored in `_responses` vector. After requests are
flushed to `consensus` instance promises are set with the results.
Stopping `append_entries_buffer` prevented some of the promises from
being set. This caused a deadlock since `append_entries_buffer` gate was
waiting until all the promises will be notified.
Fixed this problem by setting an exception to all pending promises when
shutting down `append_entries_buffer`.
=> r/append_entries_buffer: fixed shutting down append_entries_buffer

src/v/archival/ntp_archiver_service.cc, src/v/archival/ntp_archiver_service.h, src/v/archival/service.cc, src/v/archival/service.h, src/v/archival/tests/ntp_archiver_test.cc, src/v/archival/tests/service_fixture.cc, src/v/http/client.cc, src/v/http/client.h, src/v/http/tests/http_client_test.cc, src/v/s3/client.cc, src/v/s3/client.h, src/v/s3/tests/s3_client_test.cc
Reverts vectorizedio/redpanda#1296
Causing CI failures.
=> Revert "Persistent http connections"

docs/www/configuration.md, docs/www/kubernetes-external-connect.md, docs/www/quick-start-kubernetes.md, docs/www/quick-start-macos.md
Fix docs bugs in K8s and configuration articles.
=> Fix docs bugs in K8s and configuration articles

docs/www/configuration.md, docs/www/kubernetes-external-connect.md, docs/www/production-deployment-automation.md, docs/www/production-deployment.md, docs/www/quick-start-kubernetes.md, docs/www/quick-start-macos.md
=> Docs to Dev

docs/www/kubernetes-external-connect.md
Remove single quotes so that the variable $VERSION will be replaced with the value.
=> Remove single quotes to allow for variable replacement

src/js/modules/public/Utils.ts, src/js/modules/rpc/errors.ts, src/js/modules/rpc/server.ts, src/js/modules/utilities/IOBuf.ts, src/js/test/rpc/server.test.ts
Using `npx prettier --list-different 'src/**/*.{ts,js}' -w' fixes errors.
None
=> js: Fix prettier linter

docs/www/rpk-commands.md
=> docs: Add 'version' to the list of rpk commands

src/js/modules/rpc/server.ts, src/js/modules/supervisors/Repository.ts, src/js/test/rpc/server.test.ts, src/v/coproc/event_listener.cc, src/v/coproc/event_listener.h, src/v/coproc/pacemaker.cc, src/v/coproc/script_context.cc, src/v/coproc/script_dispatcher.cc, tests/rptest/test_suite_quick.yml, tests/rptest/tests/wasm_failure_recovery_test.py, tests/rptest/tests/wasm_identity_test.py, tests/rptest/wasm/background_task.py, tests/rptest/wasm/native_kafka_consumer.py, tests/rptest/wasm/native_kafka_producer.py, tests/rptest/wasm/topics_result_set.py, tests/rptest/wasm/wasm_test.py
This PR introduces a number of fixes most of are small patches for issues discovered during testing with ducktape.
A number of commits in the PR are fixes with the ducktape kafka consumers/producers which were causing false negative test results.
=> Wasm general fixes and stability 

src/v/s3/client.cc
This commit fixes the following issues:
- The lease can be released when the object is already destroyed due
to the scheduling. The 'stop' call on a 'client_pool' abrots all
code paths that have a lease. But the future that calls 'release'
might be called too late. To fix this we're waiting untill all lesaes
are returned.
- The second problem might happen when two or more fibers call 'acquire'
when the pool is empty. In this case when the lease is returned (and
the pool contains one value) all waiting fibers will be released
and one of them will try to read from empty pool triggering a access
violation.
N/A
=> s3: Fix client_pool

docs/www/quick-start-kubernetes.md
The original heading was confusing because it didn't mention install the cluster.
=> docs: Fix heading in K8s GSG

src/v/kafka/server/handlers/api_versions.cc
Updates api_versions to use feature flags to filter out transactional requests
=> kafka: put transactions behind feature flag

src/v/raft/consensus.cc
We have to wait for all pending replicate calls to finish before closing
consensus instance.
Previously relaxed consistency replicate calls weren't protected with
gate which let to triggering an assertion in storage layer saying that
no operations should be executed on closed log. Waiting for all pending
replicate calls before stopping consensus and deleting log will prevent
assertion from being triggered.
=> r/consensus: protected whole replicate call with gate

docs/www/quick-start-docker.md
Site-wide update of docs to point to  docker.vectorized.io so we start to get analytics of usage
=> Update docker address in quick start

src/go/rpk/pkg/cli/cmd/wasm/template/wasm_test_case.go
Fix wasm test template, now this test works with Promise
=> coproc/js: fix test template

docs/www/acls.md, docs/www/quick-start-docker.md, docs/www/quick-start-kubernetes.md
=> Docs merge to dev

src/go/k8s/config/samples/tls.yaml
=> operator: fix typo in tls sample

README_CN.md
By naming the file wit `_CN`, SCM platforms like [`gitee.com`](https://gitee.com) will render it automatically when user-agent request a Chinese version.
=> doc: add README simple chinese version as README_CN.md

docs/www/quick-start-docker-CN.md, docs/www/quick-start-docker.md
Add tracking image to docker articles.
=> Add scarf tracking image to docker articles

docs/www/guide-wasm-elastic.md
Rewrites the Wasm article to be in tutorial writing style.
=> Rewrite Wasm elastic article for tutorial style

taskfiles/dev.yml, taskfiles/docker.yml, taskfiles/rpk.yml
Don't use golang from system. Install specific version via task and use that to build rpk.
=> task: install golang with task

src/v/cluster/partition.h, src/v/raft/consensus.cc, src/v/raft/consensus.h
Fixed incorrect LSO returned in Fetch request.
NA
=> Fix partition LSO

src/v/coproc/tests/utils/event_publisher.cc, src/v/kafka/client/produce_batcher.h
This change was introduced by accident to have a coproc unit test pass, as it doesn't make much sense to decompress batches before producing. In the future to do this we must explicitly support sending compressed batches with some future mechanism within the client.
=> kafka/client: Remove batch decompression on produce

src/go/rpk/pkg/cli/cmd/topic/consume.go
Fix the code formatting in consume.go
=> rpk topic consume: Fix code formatting

.gitignore, build.sh, cmake/oss.cmake.in, install-dependencies.sh, taskfiles/rp.yml
- Add task for download v8 build tools
- Build v8 in oss.cmake.in
=> v8 open-source build

docs/www/guide-nodejs.md
updating `rpk tune` command, from:
```
Command "tune" is deprecated, use 'rpk redpanda tune' instead.
```
=> Update deprecated commands - guide-nodejs

docs/www/guide-nodejs.md
=> Docs: Update rpk redpanda commands - guide-nodejs

src/js/test/rpc/server.test.ts, tools/ts-generator/rpc/rpc_gen_js.py
Before this changes, when the server starts to read a new request process batch, it doesn't validate if the current buffer has enough space for reading RecordBatchHeader, these changes add validation for it if the current buffer doesn't have enough space for reading RPC header it waiting for the next chunk until to start read next request in the buffer.
example:
```
[0 0 1 1 0 1 0 0 0 1 0 1 ]
^------------------------> finish previous request
^---------------------> server starts to read a new request, but buffer doesn't have 26 
bytes for read the rpc header
-----------------------------fix  ⤵
[ 0 1 0 1 1 0 0 1 0 1 0 .... ] now server waiting for the next chunk 
and start to read request.
```
Fixes: #1605
=> coproc/js: validate next chunk size before start to reading

docs/www/kubernetes-external-connect.md, docs/www/quick-start-kubernetes.md
Change K8s quick start to pull latest version.
=> Auto populate latest k8s version

docs/www/configuration.md
Add additional start flags to rpk section of the configuration file.
=> Add additional start flags to configuration

docs/rfcs/20210223_external_connectivity_in_k8s.md
=> operator: Create RFC for external connectivity

docs/www/support.md
=> docs: Fix bad command formatting

src/v/storage/tests/storage_e2e_test.cc
Added test to check if Redpanda implementation of time based deletion
cleanup policy is correct
=> s/tests: added more detailed test for time based log cleanup

docs/www/quick-start-docker-CN.md, docs/www/quick-start-docker.md
Change entrypoint to command in order to avoid issues with the entrypoint location.
=> Remove entrypoint from Docker compose

docs/www/guide-nodejs.md, docs/www/production-deployment.md, docs/www/quick-start-docker-CN.md, docs/www/quick-start-docker.md
Replace deprecated rpk commands with the new command syntax.
=> docs: Replace deprecated commands

src/go/rpk/pkg/cli/cmd/acl/create.go, src/go/rpk/pkg/cli/cmd/acl/delete.go, src/go/rpk/pkg/cli/cmd/acl/list.go, src/go/rpk/pkg/cli/cmd/acl/list_test.go
Show the name pattern for each ACL listed with `rpk acl list`.
Fix #1631
=> Rpk acl list pattern

src/v/CMakeLists.txt, src/v/v8_engine/CMakeLists.txt, src/v/v8_engine/environment.cc, src/v/v8_engine/environment.h, src/v/v8_engine/script.cc, src/v/v8_engine/script.h, src/v/v8_engine/tests/CMakeLists.txt, src/v/v8_engine/tests/script_test.cc, src/v/v8_engine/tests/scripts/sum.js, src/v/v8_engine/tests/scripts/to_upper.js
Added environment for v8 and  simple interface for instance, which contains context for user function. `run` function will me improved with alien_thread in next pr.
=> Add first version for v8 instance and enviroment for v8

src/v/raft/configuration_manager.h, src/v/raft/event_manager.cc
Greetings from ClickHouse team
Fix style
=> docs: fix typos in comments

taskfiles/dev.yml
=> task/dev: fetch arch-specific precompiled nodejs

docs/www/guide-wasm-elastic.md, src/go/rpk/pkg/cli/cmd/wasm/generate.go, src/go/rpk/pkg/cli/cmd/wasm/generate_test.go
=> use main.js instead of wasm.js

src/v/archival/ntp_archiver_service.cc, src/v/archival/tests/ntp_archiver_test.cc
After leadership transfer the new leader might issue a partial
upload (since the segments are not aligned across nodes). This can
lead to lack of global upload progress.
The bug is caused by the partial upload imprecision. It can start
uploading new segment not from the offset that is required but from
the nearby offset which is smaller than requred (since the index
is used for lookup).
This commit also adds the reproducer for the problem.
Fixes #1791
=> archival: Fix leadership trasfer upload bug

src/js/test/rpc/server.test.ts, src/js/test/utilities/Logging.test.ts
=> wasm/js: fix test

docs/www/quick-start-kubernetes-CN.md
Change the Redpanda version in K8s Chinese article to automatically pull the latest.
=> Fix auto-version for K8s CN

src/go/k8s/controllers/redpanda/cluster_controller.go, src/go/k8s/helm-chart/charts/redpanda-operator/README.md, src/go/k8s/helm-chart/charts/redpanda-operator/templates/certificate.yaml, src/go/k8s/helm-chart/charts/redpanda-operator/templates/deployment.yaml, src/go/k8s/helm-chart/charts/redpanda-operator/values.yaml, src/go/k8s/main.go, src/go/k8s/pkg/resources/headless_service.go, src/go/k8s/pkg/resources/resource_integration_test.go, src/go/k8s/pkg/resources/statefulset.go, src/go/k8s/tests/e2e/external-connectivity/00-assert.yaml, src/go/k8s/tests/e2e/produce-consume/00-assert.yaml
Allows configuring Kubernetes local domain (Kubelet's --cluster-domain)
=> Allow configuring K8s cluster domain

docs/www/rpk-commands.md
Fix icon alt text that shows in the heading TOC so that it makes sense.
=> Fix icon alt in rpk

docs/www/data-archiving.md
Fixed config parameters name to the correct name.
=> Updated config parameters to the correct config name

docs/www/rpk-commands.md
=> docs: Move rpk OS icons to body

src/go/rpk/pkg/cli/cmd/common/common.go, src/go/rpk/pkg/cli/cmd/common/common_test.go
Restore rpk's previous behavior of using the list of brokers in the `redpanda.kafka_api` config field if all other sources (flags, env vars, `rpk.kafka_api`) yield empty values.
Fix #1833
=> rpk: Get redpanda.kafka_api if rpk.kafka_api.brokers is empty

taskfiles/docker.yml
=> task/docker: add purge and stop-containers tasks

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/raft/configuration_bootstrap_state.h, src/v/raft/configuration_manager.cc, src/v/raft/consensus.cc
See https://github.com/vectorizedio/redpanda/issues/1870 for details.
Fixes: #1870
=> raft: workaround for raft recovery bug

docs/www/faq.md
Update the recommended go client to franz-go. Resoved issue #307 in www.
=> Update go client to franz-go

tests/docker/Dockerfile, tests/java/tx-verifier/pom.xml, tests/java/tx-verifier/src/main/java/io/vectorized/kafka/SimpleProducer.java, tests/java/tx-verifier/src/main/java/io/vectorized/kafka/TxConsumer.java, tests/java/tx-verifier/src/main/java/io/vectorized/kafka/TxProducer.java, tests/java/tx-verifier/src/main/java/io/vectorized/kafka/TxRecord.java, tests/java/tx-verifier/src/main/java/io/vectorized/kafka/TxStream.java, tests/java/tx-verifier/src/main/java/io/vectorized/kafka/Verifier.java, tests/rptest/tests/tx_verifier_test.py
Integration tests covering transactional API.
=> Add integration tests covering transactional API

cmake/oss.cmake.in, src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/error.cc, src/v/pandaproxy/error.h, src/v/pandaproxy/schema_registry/avro.cc, src/v/pandaproxy/schema_registry/error.cc, src/v/pandaproxy/schema_registry/error.h, src/v/pandaproxy/schema_registry/handlers.cc, src/v/pandaproxy/schema_registry/handlers.h, src/v/pandaproxy/schema_registry/seq_writer.cc, src/v/pandaproxy/schema_registry/service.cc, src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h, src/v/pandaproxy/schema_registry/store.h, src/v/pandaproxy/schema_registry/test/compatibility_avro.cc, src/v/pandaproxy/schema_registry/test/compatibility_avro.h, src/v/pandaproxy/schema_registry/test/consume_to_store.cc, src/v/pandaproxy/schema_registry/test/store.cc, src/v/pandaproxy/schema_registry/types.h, tests/rptest/tests/schema_registry_test.py
Replaces #1885 and #1886 (they needed to be rebased on #1866)
* Check compatibility on insert.
* Various bug fixes found by running karapace test-suite
* Support AVRO type promotion
Release note: [none]
=> schema_registry: check compat on insert && other bug fixes

src/v/cluster/controller_backend.cc, src/v/cluster/errc.h
Improved logging of partition update process. Propagating meaningful message about the reason why partition operation have failed. 
Fixes: N/A
N/A
=> Controller backend logging

src/v/v8_engine/CMakeLists.txt, src/v/v8_engine/executor.cc, src/v/v8_engine/executor.h, src/v/v8_engine/script.cc, src/v/v8_engine/script.h, src/v/v8_engine/tests/CMakeLists.txt, src/v/v8_engine/tests/executor_test.cc, src/v/v8_engine/tests/script_test.cc, src/v/v8_engine/tests/scripts/compile_timeout.js, src/v/v8_engine/tests/scripts/run_timeout.js
This pr contains executor for run v8 scripts. It uses std::thread
Used https://github.com/vectorizedio/alien_thread for executor
Reopen pr: https://github.com/vectorizedio/redpanda/pull/1735
=> Add executor for v8

docs/www/kubernetes-additional-config.md, docs/www/quick-start-docker-CN.md, docs/www/quick-start-docker.md, docs/www/quick-start-kubernetes-CN.md, docs/www/quick-start-kubernetes.md
Update docker version listed in Docker quick start and update the docker image location.
=> docs: Update docker version and image location

taskfiles/rp.yml, tests/docker/docker-compose.yml, tests/docker/ducktape_cluster.json, tests/rptest/tests/archival_test.py, tests/rptest/tests/archival_upload_test.py, tests/rptest/tests/describe_topics_test.py, tests/rptest/tests/kafka_client_compat_test.py, tests/rptest/tests/log_level_test.py, tests/rptest/tests/produce_bench_test.py, tests/rptest/tests/rpk_cluster_test.py, tests/rptest/tests/rpk_config_test.py, tests/rptest/tests/rpk_topic_test.py
Run ducktape tests in parallel
=> tests: parallelize ducktape tests

src/v/pandaproxy/schema_registry/CMakeLists.txt, src/v/pandaproxy/schema_registry/errors.h, src/v/pandaproxy/schema_registry/schema_util.cc, src/v/pandaproxy/schema_registry/schema_util.h, src/v/pandaproxy/schema_registry/service.cc, src/v/pandaproxy/schema_registry/sharded_store.cc, tests/rptest/tests/schema_registry_test.py
Merge #1960 to [v21.8.x](https://github.com/vectorizedio/redpanda/tree/v21.8.x)
Release note: schema_registry: Validate schema on insert to prevent invalid schemas reaching the topic
=> Merge #1960 to v21.8.x

tools/redpanda-gdb.py
- Adds segment summary
- Adds summary of all segments
=> gdb: improve storage stats reporting

taskfiles/rp.yml, tests/docker/docker-compose.yml, tests/docker/ducktape_cluster.json, tests/rptest/tests/archival_test.py, tests/rptest/tests/archival_upload_test.py, tests/rptest/tests/describe_topics_test.py, tests/rptest/tests/kafka_client_compat_test.py, tests/rptest/tests/log_level_test.py, tests/rptest/tests/pandaproxy_test.py, tests/rptest/tests/produce_bench_test.py, tests/rptest/tests/rpk_cluster_test.py, tests/rptest/tests/rpk_config_test.py, tests/rptest/tests/rpk_topic_test.py, tests/rptest/tests/schema_registry_test.py
merge #1931, #1968, #1997 into v21.8.x
=> merge ducktape fixes into v21.8.x

tools/redpanda-gdb.py
Printing `storage::readers_cache` statistics in `redpanda-gdb.py`
Fixes: N/A
N/A
=> Redpanda gdb readers cache

src/v/storage/tests/kvstore_test.cc
This test was writing out to randomly named (within a
small 4000-wide range) directories.
When a directory name is reused, the next run of a test
expecting an empty store can fail.
Fixes: https://github.com/vectorizedio/redpanda/issues/2005
No user visible change.
=> storage: fix kvstore_test tripping over previous runs' files

tests/docker/Dockerfile, tests/docker/Dockerfile.dockerignore, tests/rptest/services/compatibility/__init__.py, tests/rptest/services/compatibility/compat_example.py, tests/rptest/services/compatibility/compat_helpers.py, tests/rptest/services/compatibility/compat_producer.py, tests/rptest/test_suite_compatibility.yml, tests/rptest/test_suite_quick.yml, tests/rptest/tests/compatibility/__init__.py, tests/rptest/tests/compatibility/sarama_scram_test.py, tests/rptest/tests/compatibility/sarama_test.py
A primary goal of Redpanda is to provide “Kafka compatibility” which means that applications that work with Kafka should also work unmodified with Redpanda. Achieving Kafka compatibility is difficult because there is no formal specification that describes how a library can ensure it works with all of Kafka. At Vectorized, we heavily rely on testing and customer feedback to reveal new incompatibilities. Instead, Vectorized should preemptively test Redpanda in ways that are likely to reveal incompatibilities so they may be addressed before customers encounter them.
I am therefore working on developing test cases for many Kafka clients such as sarama. Full details regarding this effort can be viewed in the compatibility testing document.
Release note: Created test cases for Shopify's Sarama. …
=> compatibility: added sarama tests

docs/www/configuration.md, src/v/cluster/partition.cc, src/v/cluster/partition.h, src/v/cluster/persisted_stm.cc, src/v/cluster/persisted_stm.h, src/v/cluster/rm_partition_frontend.cc, src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h, src/v/cluster/tests/rm_stm_tests.cc, src/v/cluster/tm_stm.cc, src/v/cluster/tm_stm.h, src/v/cluster/tx_gateway_frontend.cc, src/v/cluster/tx_gateway_frontend.h, src/v/cluster/types.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/kafka/server/handlers/add_offsets_to_txn.cc, src/v/kafka/server/handlers/add_partitions_to_txn.cc, src/v/kafka/server/handlers/end_txn.cc, src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/log_eviction_stm.cc, src/v/reflection/adl.h, src/v/storage/disk_log_impl.cc
Backport of
- https://github.com/vectorizedio/redpanda/pull/1787
- https://github.com/vectorizedio/redpanda/pull/1990
- https://github.com/vectorizedio/redpanda/pull/1954
=> backport #1787, #1990, #1954

src/v/kafka/server/connection_context.cc, src/v/kafka/server/handlers/produce.cc, src/v/storage/index_state.cc, src/v/storage/index_state.h, src/v/utils/fragmented_vector.h, src/v/utils/tests/CMakeLists.txt, src/v/utils/tests/fragmented_vector_test.cc
Backporting:
* https://github.com/vectorizedio/redpanda/pull/2014
* https://github.com/vectorizedio/redpanda/pull/1996
=> backport/21.8.x: #2014, #1996

src/v/kafka/server/group_manager.cc
Backporting:
- https://github.com/vectorizedio/redpanda/pull/2039
=> backport/21.8.x: #2039

tools/cmake_test.py
When a unit test failure happens with a seastar backtrace, developers do not have ready access to the binaries that were in use at the time, to reliably translate the backtrace into human readable form.  So let's do it during the test run.
There's also a behavioral change here to have the cmake_test.py script return the error code for the test itself, rather than for the `post_command` as it did before.  I did that so that we could see the test's error code and thereby decide whether to go searching through the stderr looking for backtraces.
The downside of this is that we're going to output all stderr output in one go at the end, rather than it being roughly interleaved with stdout output.  This could be finessed with a bit more python code to stream stderr through at the same time as …
=> tools: improved backtrace capture in cmake_test

taskfiles/rp.yml, tests/rptest/tests/redpanda_test.py, tests/rptest/util.py
Expose `local`, `ci`, `release` settings to ducktape tests.
=> test: add ducktape scaling factor

src/v/cluster/CMakeLists.txt, src/v/cluster/controller.cc, src/v/cluster/controller.h, src/v/cluster/partition.h, src/v/cluster/scheduling/leader_balancer.cc, src/v/cluster/scheduling/leader_balancer.h, src/v/cluster/scheduling/leader_balancer_greedy.h, src/v/cluster/scheduling/leader_balancer_probe.cc, src/v/cluster/scheduling/leader_balancer_probe.h, src/v/cluster/scheduling/leader_balancer_strategy.h, src/v/cluster/tests/CMakeLists.txt, src/v/cluster/tests/leader_balancer_test.cc, src/v/cluster/topic_table.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/model/metadata.h, src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/consensus_client_protocol.h, src/v/raft/errc.h, src/v/raft/group_manager.h, src/v/raft/raftgen.json, src/v/raft/rpc_client_protocol.cc, src/v/raft/rpc_client_protocol.h, src/v/raft/service.h, src/v/raft/types.h, src/v/redpanda/admin_server.cc, src/v/redpanda/application.cc, src/v/rpc/types.h, tests/rptest/tests/leadership_transfer_test.py
=> backport/v21.8.x: leadership balancing #2033

docs/www/kubernetes-additional-config.md
=> Fix 404 from custom configuration link

src/go/k8s/Makefile, src/go/k8s/README.md, src/go/k8s/hack/install-cert-manager.sh
Adds development isntructions to operator README
=> operator: add development instructions to README

docs/www/production-deployment.md
Explicitly state the implications of turning on production mode.
=> Improve production mode language

src/v/cloud_storage/remote.cc
* Fixes handling of ETIMEDOUT in cloud_storage/remote.cc
=> archival: Handle ETIMEDOUT as retryable

src/v/cluster/scheduling/leader_balancer.cc, src/v/raft/group_manager.cc
=> Backport of #2097 and #2100 to v21.8.x

src/v/raft/replicate_batcher.cc, src/v/raft/vote_stm.cc, tests/rptest/tests/node_operations_fuzzy_test.py
Backporting node operation fixes: #2081
=> Backport node operation fixes

src/v/cluster/controller.cc, src/v/cluster/scheduling/leader_balancer.cc, src/v/cluster/scheduling/leader_balancer.h, src/v/cluster/scheduling/leader_balancer_greedy.h, src/v/cluster/tests/leader_balancer_test.cc, src/v/config/configuration.cc, src/v/config/configuration.h
Backport for
* https://github.com/vectorizedio/redpanda/pull/2110
=> backport/v21.8.x: #2110 leadership rebalancing fixes

src/v/cluster/partition_manager.cc, src/v/cluster/partition_manager.h, src/v/kafka/server/group_manager.cc, src/v/kafka/server/group_manager.h, tests/rptest/tests/node_operations_fuzzy_test.py
Support moving internal topic underlying group. 
Fixes: #2089
- Full support for node decommissioning
=> Support for moving internal topic replicas 

src/v/cluster/partition_manager.cc, src/v/cluster/partition_manager.h, src/v/kafka/server/group_manager.cc, src/v/kafka/server/group_manager.h, src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/replicate_batcher.cc, src/v/raft/replicate_batcher.h, src/v/redpanda/application.cc, tests/rptest/services/redpanda.py, tests/rptest/tests/node_operations_fuzzy_test.py
Backport of:
#2108 Support moving internal topic replicas
#2114 Fixing shutting down Raft
=> Backport PR2108 & PR2114

src/v/cluster/controller_backend.cc
* https://github.com/vectorizedio/redpanda/pull/2136
=> backport/v21.8.x: #2136

src/v/cluster/tests/rebalancing_tests_fixture.h, src/v/cluster/tests/replicas_rebalancing_tests.cc, src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/errc.h, src/v/raft/replicate_batcher.cc, src/v/raft/replicate_entries_stm.cc
=> backport/v21.8.x: #2134

docs/www/configuration.md
Fix incorrect syntax for seed servers in configuration.
=> docs: Fix seed server syntax

src/go/k8s/kuttl-helm-test.yaml
extracted from https://github.com/vectorizedio/redpanda/pull/2056
=> k8s/tests: invoke `helm dep up`

src/go/rpk/pkg/config/params.go
On some systems, the user will have downloaded rpk but not installed redpanda. In those cases, it's ok to use the default config.
=> rpk cluster info: Use default config if no config file exists

src/v/cluster/partition.cc, src/v/cluster/persisted_stm.cc, src/v/cluster/persisted_stm.h, src/v/cluster/rm_stm.cc, src/v/config/configuration.cc
backport #2189: tx/sync: fix transaction related pauses
=> v21.8.x backport #2189: Fix transaction related sync pauses

src/v/cluster/rm_group_proxy.h, src/v/cluster/tx_gateway_frontend.cc, src/v/kafka/server/handlers/end_txn.cc, src/v/kafka/server/handlers/init_producer_id.cc, src/v/kafka/server/rm_group_frontend.cc, src/v/kafka/server/rm_group_frontend.h
backport #2184: kafka/tx: add tx_seq to group's abort_tx RPC
=> v21.8.x backport #2184: Add tx_seq to group's abort_tx RPC

docs/www/configuration.md
https://github.com/vectorizedio/redpanda/issues/1909 includes a change to the default value.
=> Update topic replication default for release 21.8.1

src/go/k8s/tests/e2e/additional-configuration/verify-config.sh
Updates the expected config schema in the "additiona-configuration" e2e test.
=> k8s/tests/e2e: Update config schema

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/application.cc, src/v/rpc/server.cc, src/v/rpc/types.h
=> v21.8.x backport 2157

src/v/cluster/scheduling/partition_allocator.cc, src/v/cluster/tests/partition_allocator_tests.cc, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/kafka/server/group_manager.cc, src/v/kafka/server/group_manager.h, src/v/raft/CMakeLists.txt, src/v/raft/consensus.cc, src/v/raft/follower_queue.cc, src/v/raft/follower_queue.h, src/v/raft/follower_stats.cc, src/v/raft/follower_stats.h, src/v/raft/replicate_entries_stm.cc, src/v/redpanda/application.cc, src/v/resource_mgmt/smp_groups.h, tests/docker/Dockerfile, tests/docker/Dockerfile.dockerignore, tests/rptest/clients/kcl.py, tests/rptest/tests/group_membership_test.py
* https://github.com/vectorizedio/redpanda/commit/a9efc061858780266773cd57f9f46cdc3c9258e9
* https://github.com/vectorizedio/redpanda/pull/2210
* https://github.com/vectorizedio/redpanda/pull/2202
* https://github.com/vectorizedio/redpanda/pull/2206
=> Backport #2210, #2202, #2206

docs/www/kubernetes-external-connect.md, docs/www/quick-start-kubernetes.md
A user complained of our commands not working with zsh. This fix addresses this.
=> Updates to use noglob with zsh.

src/v/raft/heartbeat_manager.cc
The heartbeat manager gate was only protecting the dispatch of RPCs, not
the handling of responses.
Fixes: https://github.com/vectorizedio/redpanda/issues/2234
A bug is fixed where redpanda would occasionally crash during shutdown.
=> raft: fix occasional shutdown crash in heartbeat_manager

docs/www/kubernetes-external-connect.md
=> docs: use spaces instead of tabs for <tag>

docs/www/quick-start-kubernetes.md
=> docs: fix more spacing for <tabs>

src/v/rpc/server.cc
Added more context to error logs logged in RPC server to be able to identify client that is misbehaving or causing an errors.
Fixes: #2239 
N/A
=> Added more context to logs in RPC server

src/v/raft/tests/raft_group_fixture.h, src/v/rpc/batched_output_stream.cc, src/v/rpc/batched_output_stream.h, src/v/rpc/server.cc, src/v/rpc/transport.cc
Backport of:
- https://github.com/vectorizedio/redpanda/pull/2215
- https://github.com/vectorizedio/redpanda/pull/2253
- https://github.com/vectorizedio/redpanda/pull/2260
=> Backport 2215, 2253, 2260

src/v/serde/serde.h
=> switch to unsigned size type

tests/java/tx-verifier/src/main/java/io/vectorized/kafka/Verifier.java
=> tx/tests: retry transient Kafka exceptions wrapped in ExecutionException

src/v/pandaproxy/schema_registry/avro.cc, src/v/pandaproxy/schema_registry/avro.h, src/v/pandaproxy/schema_registry/requests/post_subject_versions.h, src/v/pandaproxy/schema_registry/schema_util.cc, src/v/pandaproxy/schema_registry/schema_util.h, src/v/pandaproxy/schema_registry/test/CMakeLists.txt, src/v/pandaproxy/schema_registry/test/sanitize_avro.cc
Backport #2270 
Schema Registry: Sanitize Avro schema before adding to the topic.
=> v21.8.x backport 2270

licenses/third_party.md
=> chore: update js third party licenses

src/v/redpanda/admin_server.cc
Previously, we would orchestrate the entire config change
from one replica list to an identical replica list.  Nothing
further down in the stack can really ignore these things
once they've been committed as an update in the controller
log, so ignore it up-front in the HTTP request handler.
This avoids a situation where an API client could ask for
a no-op change, read the status and see "done" with their
desired state, and then be surprised by the partition
going back into in_progress state a moment later.  Our
tests that try to do random moves (including no-op moves)
encounter this.
Fixes: https://github.com/vectorizedio/redpanda/issues/2323
None.
=> admin: ignore no-op partition movements with 200 response

src/v/storage/chunk_cache.h, src/v/storage/tests/appender_chunk_manipulations.cc
Fixing regressions from PR #2254
None
=> storage: fix regressions from PR #2254

tools/cmake_test.py
Oddly, this CLI option already existed but didn't
do anything.  Implement it as a "run until failure"
mode for reproducing nondeterministic failures.
None
=> tools: implement --repeat in cmake_test.py

src/v/raft/consensus_utils.cc, src/v/raft/mux_state_machine.h, src/v/raft/recovery_throttle.h, src/v/raft/tests/consensus_utils_test.cc, src/v/redpanda/application.cc, tests/rptest/services/redpanda.py
Backport:
- https://github.com/vectorizedio/redpanda/pull/2316
- https://github.com/vectorizedio/redpanda/pull/2328
- https://github.com/vectorizedio/redpanda/pull/2338
=> Backport #2316, #2328, #2338

src/v/kafka/server/offset_translator.h, src/v/kafka/server/tests/translation_test.cc, src/v/raft/configuration_bootstrap_state.cc, src/v/raft/configuration_bootstrap_state.h, src/v/raft/configuration_manager.cc, src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/tests/bootstrap_configuration_test.cc, src/v/raft/tests/configuration_manager_test.cc, tests/rptest/tests/end_to_end.py, tests/rptest/tests/simple_e2e_test.py
Backport of:
- https://github.com/vectorizedio/redpanda/pull/2325
=> Backport #2325

src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h, src/v/cluster/tm_stm.cc, src/v/cluster/tm_stm.h, src/v/cluster/tx_gateway_frontend.cc, src/v/raft/state_machine.cc, src/v/raft/state_machine.h
Backporting
* https://github.com/vectorizedio/redpanda/pull/2235
=> v21.9.x/backport: #2235

tests/rptest/tests/partition_movement_test.py
This tended to fail on the last topic being checked, with a
shortfall in consumed messages.  Iterate on consuming
from the topic to make sure we've drained it before
finalizing the pass/fail.
None
=> tests/partition_movement: refine verification in test_static

src/v/redpanda/admin_server.cc
Previously we included the controller topic in the list
of topics, but a GET on the /partitions/redpanda/controller/0
would return 404.  This behaviour was inconsistent, and also
makes it awkward for any automation/testing that wants a single
API endpoint to use to find topic location/leaders.
Today, then controller topic is replicated on all nodes, but
in future we expect to change to keeping it on a subset of nodes
in order to better support larger system sizes -- at that time
the controller topic would be managed more like a normal topic
and the special casing here would go away.
Fixes: https://github.com/vectorizedio/redpanda/issues/2294
Admin API partition GET requests now work on the redpanda internal controller topic at /v1/partitions/redpanda/controller/0.  Previously the topic …
=> admin: fix GET on partition details for controller topic

src/v/raft/configuration_manager.cc, tests/rptest/tests/retention_policy_test.py
Backporting
* https://github.com/vectorizedio/redpanda/pull/2359
=> backport/v21.9.x: #2359

src/v/storage/disk_log_impl.cc
Bacport of:
- https://github.com/vectorizedio/redpanda/pull/2366
=> Backport #2366

src/go/k8s/kuttl-test.yaml
Work around for https://github.com/vectorizedio/redpanda/issues/2382
None
=> k8s: disable parallel test execution

src/go/rpk/pkg/cli/cmd/wasm/generate.go, src/go/rpk/pkg/cli/cmd/wasm/template/package_json.go
Start to use `--json` in `npm search` to get the newest version `wasm-api`
=> [rpk] Fix rpk wasm generate

src/v/cluster/tests/CMakeLists.txt, tests/rptest/tests/nodes_decommissioning_test.py, tests/rptest/tests/partition_movement_test.py, tests/rptest/tests/retention_policy_test.py
Disabling flaky tests until they're fixed:
- https://github.com/vectorizedio/redpanda/issues/2385
- https://github.com/vectorizedio/redpanda/issues/2388
- https://github.com/vectorizedio/redpanda/issues/2406
None
=> Disable flaky tests

src/v/cluster/members_backend.cc
This area was very light on log messages, which makes
investigating test failures hard.
Related: https://github.com/vectorizedio/redpanda/issues/2388
None
=> cluster: add logging to decommissioning code path

tests/rptest/tests/partition_movement_test.py
Update PartitionMovementTest.test_overlapping_changes for recent changes to admin API client error handling.
None
=> tests: update PartitionMovementTest.test_overlapping_changes

src/v/raft/mux_state_machine.h
Removing promise right after its state has been set. This way we prevent
any other fibers prom setting the promise.
=> r/mux_stm: fixed possible double set of promise

tools/cmake_test.py
Fixes: https://github.com/vectorizedio/redpanda/issues/2153
None
=> tools: fix seastar-addr2line path

src/go/k8s/tests/e2e/produce-consume/00-assert.yaml, src/go/k8s/tests/e2e/produce-consume/00-redpanda-cluster.yaml, src/go/k8s/tests/e2e/produce-consume/01-assert.yaml, src/go/k8s/tests/e2e/produce-consume/01-create-topic.yaml, src/go/k8s/tests/e2e/produce-consume/02-assert.yaml, src/go/k8s/tests/e2e/produce-consume/02-produce-message.yaml, src/go/k8s/tests/e2e/produce-consume/03-assert.yaml, src/go/k8s/tests/e2e/produce-consume/03-consume-message.yaml, src/go/k8s/tests/e2e/produce-consume/04-assert.yaml, src/go/k8s/tests/e2e/produce-consume/04-delete-topic.yaml
=> k8s: add log collectors to debug produce-consume test

tests/rptest/services/kaf_consumer.py, tests/rptest/services/rpk_consumer.py
RpkConsumer was behind a lot of hung test runs recently.  KafConsumer is not broken per-se but cleaning it up while I'm here.
Related: https://github.com/vectorizedio/redpanda/issues/2402
None
=> test: improve consumer service shutdowns

.gitignore, conf/redpanda.yaml
- conf: remove trailing whitespace in redpanda.yaml
- gitignore: allow vtools to be a symlink or a dir
I used the [github cli](https://cli.github.com/manual/gh_pr_create) to create this pull request.
=> Some trivial commits to get started

src/v/kafka/server/handlers/fetch.cc
When partition is moved from one node to another clients should receive
an error indicating that its metadata needs a refresh. In redpanda when
partition instance was not found on current node processing fetch
request we returned `unknown_topic_or_partition_error` indicating that
the partition does not exists in the cluster. Fixed this issue by using
metadata cache to verify if partition exists before processing fetch
request. This way client will receive valid information and refresh
metadata after it receive `not_leader_for_partition` error.
Related: #2490
=> k/fetch: fixed error returned when partition is moved from node

tests/rptest/tests/wasm_identity_test.py
Failure is occurring on every run. Being track here  https://github.com/vectorizedio/redpanda/issues/2514
=> test: ignore failing wasm test

src/js/test/rpc/server.test.ts
The problem seems to be two sets of tests started in parallel.
In this fix these two sets of tests are combined together to see
if the problem is fixed.
Related: #2339 
None
=> Merge conflicting tests in src/js/tests

tests/rptest/services/failure_injector.py, tests/rptest/services/redpanda.py, tests/rptest/tests/availability_test.py, tests/rptest/tests/e2e_finjector.py, tests/rptest/tests/node_operations_fuzzy_test.py
Added simple failure injector to use with ducktape tests. Injecting failures into `node_opearations_tests`
=> Ducktape failure injector

src/v/cluster/controller_backend.cc, src/v/cluster/tests/CMakeLists.txt, tests/rptest/tests/partition_movement_test.py
Fixes for partition movement issues revealed recently in CI. 
Fixes: #2385
=> Partition movement fixes

src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_partition.h, src/v/cloud_storage/remote_segment.h, src/v/raft/log_eviction_stm.cc
Use context logger inside the reader. Update some log messages.
Apply formatting.
N/A
=> cloud_storage: Improve logging in remote_partition

docs/www/quick-start-docker.md, docs/www/quick-start-windows.md
Created windows guide and did some small corrections to the docker guide
=> [VD-19]Doc/windows guide

docs/www/kubernetes-external-connect.md, docs/www/quick-start-kubernetes.md
Fixing the broken tab at 
https://vectorized.io/docs/quick-start-kubernetes/
=> Fix for tabs

tests/rptest/tests/compaction_recovery_test.py
Adjacent segment compaction caused the first phase of the compaction
recovery test to not coverge because it waited for index files to be
present for all segments, but adjacent compaction removes index files as
it compacts.
Fixes: #2455
=> test: update compact recover test for adjacent compaction

src/v/pandaproxy/schema_registry/sharded_store.cc
The subject and the schema may be stored on different shards.
Changes in [force-push](https://github.com/vectorizedio/redpanda/compare/d478cad23a84d542eba09d15f8350c180f8ac47f..a99499bb59a8cc7d7d21169cb56283908b5b3d1a)
* Add back `_smp_opts`
**Bug**
- Schema Registry: Schema may be looked up on the wrong shard, resulting in incorrect 404.
=> schema_registry/store: Use correct shard in get_subject_schema

src/v/pandaproxy/schema_registry/sharded_store.cc
Backport #2850 to v21.10
The subject and the schema may be stored on different shards.
[none] - This bug is a regression that never made it to a release.
=> Backport #2850: schema_registry/store: Use correct shard in get_subject_schema

src/go/k8s/helm-chart/charts/redpanda-operator/README.md
Fixed so that the namespace matches the `create-namespace` value.
=> docs: Fix `helm install` in README for redpanda operator

src/v/cloud_storage/remote.cc
Following up on shadow indexing testing, addressing some alarming log messages that are not that serious.
=> Quiet some frightening log messages

tests/rptest/services/compatibility/kafka_streams_examples.py
Fixes: #2881 
Changes from force-push [5da7c0f](https://github.com/vectorizedio/redpanda/commit/5da7c0f0dcf8366ea84a15f5f5f19f654ad811f9):
- Use regex instead of while loop in `KafkaStreamsWikipedia`
Release note: None
=> compatibility: modified PageViews and Wikipedia

src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_partition.h
=> cloud_storage: Code review fixes

src/v/kafka/server/handlers/join_group.cc, src/v/kafka/server/member.cc, src/v/kafka/server/protocol_utils.cc, src/v/model/model.cc, src/v/utils/human.cc, src/v/utils/to_string.h
Update redpanda to avoid tripping deprecation warnings when building with latest seastar.
None
=> Avoid deprecated seastar functions

src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_partition.h, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment.h, src/v/cloud_storage/tests/common_def.h, src/v/cluster/partition.h
=> cloud_storage: Fix code review issues

src/v/serde/envelope.h, src/v/serde/serde.h, src/v/serde/test/serde_test.cc
Example usage:
```cpp
struct checksummed
: public serde::checksum_envelope<
checksummed,
serde::version<3>,
serde::compat_version<2>> {
// data fields
};
```
Uses crc32c.
=> serde: introduce `checksum_envelope`

tools/docker/README.md
Documentation updates per my newbie community build journey.
=> adding newbie build instructions

docs/rfcs/20200421_raft_recovery.md, src/v/cluster/metadata_cache.cc, src/v/cluster/metadata_cache.h, src/v/cluster/partition_leaders_table.cc, src/v/cluster/partition_leaders_table.h, src/v/kafka/server/handlers/metadata.cc, src/v/raft/append_entries_buffer.cc, src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/heartbeat_manager.cc, src/v/raft/replicate_entries_stm.cc, src/v/raft/tests/type_serialization_tests.cc, src/v/raft/types.cc, src/v/raft/types.h, src/v/raft/vote_stm.cc, src/v/rpc/simple_protocol.cc, src/v/rpc/test/response_handler_tests.cc, src/v/rpc/test/rpc_gen_types.h, src/v/rpc/transport.cc, src/v/rpc/transport.h, src/v/rpc/types.h, tests/rptest/services/failure_injector.py, tests/rptest/tests/raft_availability_test.py
Backport:
- https://github.com/vectorizedio/redpanda/pull/2856
- https://github.com/vectorizedio/redpanda/pull/1576
- https://github.com/vectorizedio/redpanda/pull/2917
- https://github.com/vectorizedio/redpanda/pull/2901
- https://github.com/vectorizedio/redpanda/pull/2937
=> Backport of #2856, #1576, #2917, #2901, #2937

docs/www/autotune.md
There was one relative link left from when we moved from relative to absolute links. This PR fixes the bad link.
=> docs: Fix relative link in autotune

docs/www/acls.md, docs/www/kubernetes-external-connect.md, docs/www/quick-start-kubernetes.md
General revision of this page
https://vectorized.io/docs/acls
Replaces 
https://github.com/vectorizedio/redpanda/pull/2867
=> docs: Auth review

tests/rptest/tests/compatibility/kafka_streams_test.py
Fixes: #2889 
Changes from force-push [dc2faef](https://github.com/vectorizedio/redpanda/commit/dc2faef59b8708d517d1403da962dd828e36ae3c):
- Amend commit message to explain the issue and fix
=> Kstreams wikipedia fix

docs/www/quick-start-docker.md
=> docs: Remove extra space

src/v/storage/opfuzz/opfuzz.cc
Added validation of batches read during fuzzy storage tests. The validation check if batches are passed to the reader when log is not empty and if batches come from a range specified in reader configuration.
=> Opfuzz improvements

src/v/cluster/partition.h, src/v/kafka/server/fetch_session.h, src/v/kafka/server/handlers/fetch.cc, src/v/kafka/server/handlers/list_offsets.cc, src/v/kafka/server/materialized_partition.h, src/v/kafka/server/partition_proxy.h, src/v/kafka/server/replicated_partition.h, src/v/storage/log_reader.cc, tests/rptest/clients/kcl.py, tests/rptest/tests/fetch_fairness_test.py
Backport:
- https://github.com/vectorizedio/redpanda/pull/2949
- https://github.com/vectorizedio/redpanda/pull/2954
=> Backport: #2949, #2954

src/v/coproc/tests/fixtures/coproc_test_fixture.cc, tests/rptest/clients/rpk.py
=> tests: Small fixes in test logs

src/v/finjector/hbadger.cc, src/v/finjector/hbadger.h, src/v/redpanda/admin_server.cc, src/v/storage/failure_probes.h, tools/rpcgen.py
Clarify code and fix a bug found by inspection.
=> Honey Badger / Failure Injection cleanup

src/v/raft/replicate_entries_stm.cc, src/v/raft/replicate_entries_stm.h
Backport of:
- https://github.com/vectorizedio/redpanda/pull/3003
=> Backport: #3003

docs/www/well-known-io.md
This fixes issues in the well known io article found by @travisdowns .
=> docs: Fix AWS instance type and add GCP support

src/v/kafka/client/client.cc, src/v/kafka/client/client.h, src/v/kafka/client/fetcher.cc, src/v/kafka/client/producer.cc, src/v/kafka/client/retry_with_mitigation.h, src/v/kafka/client/test/CMakeLists.txt, src/v/kafka/client/test/retry.cc, src/v/kafka/client/topic_cache.cc, tests/rptest/tests/pandaproxy_test.py
Backport #2926 
kafka/client: Fix retry handling for several operations
=> V21.10.x backport pr2926 v2

src/v/kafka/server/handlers/fetch.cc, tests/java/tx-verifier/pom.xml, tests/java/tx-verifier/src/main/java/io/vectorized/kafka/TxReadsWritesTest.java, tests/java/tx-verifier/src/main/java/io/vectorized/kafka/Verifier.java, tests/rptest/tests/tx_reads_writes_test.py
Backport #3036
Fix transaction visibility problem
=> V21.10.x backport pr3036: Fix transaction visibility problem

src/v/cluster/rm_stm.cc, src/v/cluster/tests/idempotency_tests.cc
Backport #3040
Fix transaction visibility problem
=> V21.10.x backport pr3040: Mitigate idempotency violation

tests/rptest/tests/archival_test.py
This PR fixes ArchivalTest.test_isolate https://github.com/vectorizedio/redpanda/issues/1977
Test was failing because the topic is created before firewall is closed,
and sometimes topic manifest is uploaded to the S3 bucket before the
firewall is blocked. Changed the assertion to allow topic manifest to be
present in the bucket. Neither segments nor partition manifest should be
present in the bucket.
=> test: Fix ArchivalTest.test_isolate

docs/www/configuration.md, docs/www/quick-start-docker-CN.md
This PR fixes two in-page links that were broken.
=> docs: Fix in-page links

docs/www/acls.md
This bug in the docs was reported in: https://vectorizedcommunity.slack.com/archives/C01AJDUT88N/p1637254769236500
=> docs: Fix superuser syntax in acl article

src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_types.cc, src/v/cluster/health_monitor_types.h
Added uptime field to reports collected by health monitor.
- Fixed an error marking node as alive in `cluster::health_monitor`
=> Added uptime to health monitor

docs/www/autotune.md
Changes spelling of filesystem to file system.
This PR is also to test that we can merge PRs directly to dev branch.
=> docs: Change filesystem to file system

src/v/kafka/server/handlers/list_offsets.cc, src/v/kafka/server/materialized_partition.h, src/v/kafka/server/partition_proxy.h, src/v/kafka/server/replicated_partition.h, src/v/raft/configuration_manager.cc, src/v/raft/consensus.cc, src/v/raft/group_configuration.cc, src/v/raft/group_configuration.h, src/v/raft/prevote_stm.cc, src/v/raft/replicate_entries_stm.cc, src/v/raft/tests/group_configuration_tests.cc, src/v/raft/vote_stm.cc
Backporting: 
- https://github.com/vectorizedio/redpanda/pull/3055
- https://github.com/vectorizedio/redpanda/pull/3084
- https://github.com/vectorizedio/redpanda/pull/3087
=> Backport: #3055 #3084 #3087

src/v/kafka/server/handlers/describe_configs.cc, src/v/kafka/server/tests/alter_config_test.cc
Original Kafka supported key specification in describe config requests.
Commit supports this specification in redpanda kafka implementation.
When _describe_config_ request has _configuration_keys_ field, we send only specified keys in response
It was  mentioned  in https://github.com/vectorizedio/redpanda/issues/1108
_describe_config_ now supports key specification in _configuration_keys_ field.
=> kafka: Support configuration_keys in describe_configs handler

src/go/k8s/helm-chart/charts/redpanda-operator/templates/clusterrole.yaml
This has already been added to the operator manifests.
NONE
=> k8s: add delete permissions to helm chart

tests/rptest/tests/wait_for_local_consumer_test.py
Clean this up as a prerequisite to merging https://github.com/vectorizedio/vtools/pull/335
None
=> tests: fix node count on test_wait_for_local_consumer

src/v/raft/consensus.cc
Backport of:
- https://github.com/vectorizedio/redpanda/pull/3110
=> Backport #3110

tests/rptest/clients/rpk.py, tests/rptest/tests/raft_availability_test.py
We should improve the health monitor updates
to not take as long, but in the meantime let's
make the test more tolerant.
I originally wrote this before I'd analyzed the logs
fully because I thought we were just tripping up on
slow elections, but now craftily repurposing the
patch to act as a mitigation for the health monitor
related failures.
Related: https://github.com/vectorizedio/redpanda/issues/3098
None
=> tests: work around issue in test_follower_isolation

src/v/raft/consensus.cc
Backporting: 
- https://github.com/vectorizedio/redpanda/pull/3114
- https://github.com/vectorizedio/redpanda/pull/3117
=> Backport #3114 #3117

src/v/archival/tests/ntp_archiver_test.cc, src/v/raft/offset_translator.cc, src/v/storage/offset_to_filepos_consumer.h, src/v/storage/segment.cc, src/v/storage/segment_index.cc, src/v/storage/segment_set.cc, src/v/storage/tests/log_truncate_test.cc
Backport:
* https://github.com/vectorizedio/redpanda/pull/3125
=> Backport #3125

.gitignore, src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h, src/v/cluster/tests/idempotency_tests.cc, src/v/reflection/adl.h, src/v/reflection/type_traits.h
Backport #3077
Support 5-items wide deduplication window for the idempotent producers
=> V21.10.x backport pr3077: Support 5-items wide deduplication window for the idempotent producers

tests/rptest/tests/fetch_fairness_test.py
Improved fetch fairness test by calculating partitions frequency
returned from multiple fetch requests.
Fixes: #3006
=> tests: improved fetch fairness test to reduce variability

tests/rptest/tests/nodes_decommissioning_test.py
Believed to be stable now, explanation in ticket:
https://github.com/vectorizedio/redpanda/issues/2142
None
=> tests: reinstate NodesDecommissioningTest.test_working node

docs/www/kubernetes-additional-config.md
=> docs: Fix broken link to K8s quick start

src/v/cluster/partition.cc, src/v/cluster/partition.h, src/v/kafka/server/handlers/fetch.cc, src/v/kafka/server/handlers/list_offsets.cc, src/v/kafka/server/materialized_partition.h, src/v/kafka/server/partition_proxy.h, src/v/kafka/server/replicated_partition.cc, src/v/kafka/server/replicated_partition.h, src/v/raft/consensus.cc, src/v/raft/consensus.h, tests/rptest/clients/kafka_cat.py, tests/rptest/clients/rpk.py, tests/rptest/tests/fetch_after_deletion_test.py, tests/rptest/tests/retention_policy_test.py
Backports for v21.11.x:
Fixed querying offset based on timestamp #3161
Fixed assertion triggered when fetching from empty topics with transactions enabled #3159
=> backport/v21.11.x: #3159, #3161

src/v/raft/consensus.cc, src/v/raft/group_configuration.cc, src/v/raft/tests/membership_test.cc, tests/rptest/clients/kcl.py, tests/rptest/services/redpanda.py, tests/rptest/tests/end_to_end.py, tests/rptest/tests/node_operations_fuzzy_test.py
Fixed issues leading to node operations fuzzing test to fail.
Fixes: #2246
=> Fixes for node operations fuzzy tests 

src/v/raft/consensus.cc
- https://github.com/vectorizedio/redpanda/pull/3173
=> Backport: #3173

tools/metadata_viewer/consumer_groups.py, tools/metadata_viewer/viewer.py
Added group metadata printing capability to `metadata_viewer`
=> Added printing consumer group metadata to viewer tool

cmake/oss.cmake.in
This version is a rebase of redpanda-isms
atop upstream commit f8a038a
None
=> cmake: update seastar in community build

docs/www/acls.md, docs/www/configuration.md, docs/www/data-migration.md, docs/www/monitoring.md, docs/www/quick-start-docker-CN.md, docs/www/quick-start-docker.md, docs/www/rpk-commands.md, docs/www/well-known-io.md
=> Merge docs->dev

docs/www/acls.md
=> docs: ACL rewrite

src/v/raft/consensus.cc, src/v/raft/group_configuration.cc, src/v/raft/tests/membership_test.cc, tests/rptest/clients/kcl.py, tests/rptest/services/redpanda.py, tests/rptest/tests/end_to_end.py, tests/rptest/tests/node_operations_fuzzy_test.py
Backporting: 
- https://github.com/vectorizedio/redpanda/pull/2737
- https://github.com/vectorizedio/redpanda/pull/3173
=> Backport of: #2737, #3173

src/go/k8s/README.md
All older versions are not officially supported anymore
none
=> Bump the required k8s version to 1.19

src/v/cluster/rm_stm.cc
Backport #3189
Fix Sarama control record compatibility issue
=> V21.11.x backport pr3189: fix Sarama control record compatibility issue

src/v/pandaproxy/schema_registry/protobuf.cc, src/v/pandaproxy/schema_registry/protobuf.h, src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h
Clean backport of #3214 to v21.11.x
Schema Registry: Fix a crash during compatibility checks.
=> v21.11.x backport pr3214

docs/www/intro-to-events.md
there were a couple periods outside of quotes. Moved the periods inside quotes.
=> edited ". typos

src/v/redpanda/admin_server.cc
Allow reconfiguration of the int. topics to chaos test the effects of reconfiguration of the internal transactional topics
* none
=> admin: allow reconfiguration of int. topics

tests/rptest/services/redpanda.py
The data_checksum helper in the redpanda service executes the following
command remotely on a node:
find <path> -type f -exec md5sum '{}' \; -exec stat -c %s '{}' \;
In https://github.com/vectorizedio/redpanda/issues/3258 it was reported
that parsing of this output had the word `No` in the output where an
integer was expected (see data_checksum for more info). One plausible
explanation for this is that a file was deleted between being discovered
by `find` and being passed to an invocation of `md5sum`, resulting in an
output like this:
>>> "md5sum: {/var/lib/redpanda/data/redpanda/controller/0_0/2-2-v1.log}: No such file or directory".split()
['md5sum:', '{/var/lib/redpanda/data/redpanda/controller/0_0/2-2-v1.log}:', 'No', 'such', 'file', 'or', 'directory']
where `No` appeared in the same …
=> test: handle file removal race in remote checksum

src/v/kafka/server/group.cc, src/v/kafka/server/handlers/produce.cc, src/v/raft/recovery_stm.cc, src/v/raft/replicate_entries_stm.cc
- https://github.com/vectorizedio/redpanda/pull/3205
- https://github.com/vectorizedio/redpanda/pull/3245
=> Backport #3205 #3245

tools/metadata_viewer/kvstore.py, tools/metadata_viewer/reader.py, tools/metadata_viewer/storage.py, tools/metadata_viewer/viewer.py
Added offset translator state printing to `metadata_viewer` 
* none
=> Metadata viewer fixes

src/v/utils/tests/remote_test.cc
It compiles, but leaks memory. A concept check has been added:
https://github.com/scylladb/seastar/commit/d5f9e7c105a81c7349abfa43308f3173017a693e
* none
=> utils/test: Avoid raw pointers with ss::foreign_ptr

docs/www/quick-start-kubernetes.md
This is already updated in readme, we should update www as well.
* none
=> docs: update k8s deps requirements

src/go/k8s/helm-chart/charts/redpanda-operator/templates/test/three_node_cluster.yaml
Enabling this feature could make us catch more regressions in helm chart.
* none
=> k8s: add pandaproxy to helm chart tests

src/v/kafka/client/broker.h
Fix logging introduced in #3256 
* none
=> kafka/client/broker: Fix response logging

src/v/cloud_storage/cache_service.cc, src/v/cloud_storage/cache_service.h, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment.h, src/v/cloud_storage/tests/cache_test.cc, src/v/cloud_storage/tests/remote_partition_test.cc
Backport #3348 "Fix disk space issues"
=> Backport PR #3348

tests/docker/Dockerfile, tests/rptest/services/kaf_consumer.py, tests/rptest/tests/schema_registry_test.py
Fix CI by merging #3375 
An alternative is to merge v21.11.x into this branch, which may be a regular task.
* none
=> v21.11.x-si-testing - merge pr3375

src/v/cloud_storage/remote_partition.cc
The garbage collection of remote_segment objects
was conditional on the reference count in the
segment's sharded_ptr being 1 (i.e. nothing else
is using it).
This is not true if there are entries in the `readers`
attribute of materialized_segment_state, because
readers hold a reference to the segment.
Deal with this by proactively evicting readers
from any materialized_segment_state objects
whose atime makes them elegible for removal.
Fixes: https://github.com/vectorizedio/redpanda/issues/3334
* none
=> cloud_storage: fix file descriptor leak

tools/metadata_viewer/controller.py
=> tools: support create partitions command in metadata viewer

tools/redpanda-gdb.py
These are the things I had to fix to use
the script with gdb 11.1 and the
latest redpanda/seastar code.
* add wrapper for fragmented vector and use
for segment index structures
* handle variants of struct symbol names,
where "struct foo*" may also appear as "foo*"
* change ::debug::app symbol to debug::app, as
it appears in this GDB version.
* remove call to undefined redpanda_rpc
* none
=> tools: updates to redpanda-gdb.py

docs/www/acls.md, docs/www/quick-start-kubernetes.md, docs/www/tls-kubernetes.md
Creating a new guide for TLS on Kubernetes
=> docs: adding new TLS guide for kubernetes

src/v/raft/heartbeat_manager.cc, src/v/raft/recovery_stm.cc, tests/rptest/tests/full_node_recovery_test.py
Added test validating node recovery after data folder wipe. Fixed issue causing recovery to never finish.
* none
=> tests: added node recovery test

src/v/cloud_storage/remote_partition.cc
Backport of https://github.com/vectorizedio/redpanda/pull/3392
Fixes: https://github.com/vectorizedio/redpanda/issues/3334
* none
=> [v21.11.x] cloud_storage: fix file descriptor leak

src/v/bytes/details/io_allocation_size.h
This is the helper for iobuf_copy, that previously would
attempt to allocate huge contiguous extents when copying
large iobufs.
Make it respect the same max_chunk_size as iobuf
append/reserve operations, to avoid bad_allocs when
copying large buffers under memory pressure.
Fixes: https://github.com/vectorizedio/redpanda/issues/3428
* Improved stability when doing large kafka fetch requests under low memory conditions.
=> bytes: impose max chunk size on ss_next_allocation_size

tests/rptest/tests/full_node_recovery_test.py
After: #3476 is fixed this commit should be reverted
=> tests: ignore flaky full_node_recovery_test

src/v/archival/ntp_archiver_service.cc
Fix a bug when error was logged on success.
* none
=> archival: fix bug in logging

src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_partition.h, src/v/cloud_storage/remote_segment.cc
=> Backport #3479 ( Limit remote partition concurrency)

CONTRIBUTING.md
Signed-off-by was replaced by the github+CLA process.
* none
=> CONTRIBUTING: remove Signed-off-by

src/v/coproc/tests/pacemaker_tests.cc
- Modifying call from `redpanda::delete_topics` to manually invoking `topics_frontend::get_topics_frontend()`
- This avoids waiting on the predicate that throws if topic has been observed in topic metadata after 2s of waiting.
- Removing the predicate is perfectly fine for this test, as it doesn't perform any work that must wait until this deletion is done in the first place.
- Added some more logging to make debugging this test easier in the future
For a more detailed write up of how I discovered the cause of the bug, check out issue #3491
=> Fix for rarely failing test_copro_delete_topic unit test

src/v/cluster/metadata_dissemination_service.cc
Handle gate_closed_exception in handle_leadership_notification on shutdown
@jcsp: "Also we should think about another (void)ss::with_gate places in code"
Fixes #3474
=> cluster: Handle gate_closed_exception in handle_leadership_notification

.github/CODEOWNERS
Too many github notifications, i wish i could keep up with all 😢 
* none
=> codeowners: remove ivotron from some subcomponents

tests/rptest/tests/cluster_metadata_test.py, tests/rptest/tests/full_node_recovery_test.py, tests/rptest/tests/interleave_acks_test.py, tests/rptest/tests/scramful_eos_test.py, tests/rptest/tests/scramless_eos_test.py, tests/rptest/tests/tx_admin_api_test.py
These tests raced with the PR for adding log error
scanning.
* none
=> tests: use our @cluster for recently added tests

tests/setup.py
Pull in latest ducktape.
* None
=> test: bump ducktape version

src/v/kafka/server/requests.cc
Currently, RP brokers throw an exception of type `std::runtime_error` when an unexpected SASL authentication failure occurs.
A recent slack conversation discussed that type `std::runtime_error` reads as if the exception was not handled gracefully.
This PR proposes using a wrapper around std::runtime_error with a type name that better reflects the situation for SASL authentication failures in the kafka sub-system.
Changes from force-push `5b5c2d4`:
- lint cpp
Changes from force-push `2d82f15`:
- use `fmt_with_ctx`
=> kafka: use descriptive error type for auth fails

src/v/kafka/server/group_manager.cc
Keeping `attached_partition` instance alive to make sure it is not
deleted before `catchup_lock` units are returned back to the lock
underlying semaphore.
Previously it may happen that the `attached_partition` was destroyed
before units were returned to the semaphore causing
`heap-use-after-free` error.
Fixes: #3539
* fix for possible segmentation fault that might happen when moving group underling partition
=> k/group_manager: extend attached partition lifecycle

src/go/k8s/pkg/resources/certmanager/pki.go, src/go/k8s/pkg/resources/certmanager/pki_test.go, src/go/k8s/pkg/resources/certmanager/schemaregistry_api.go, src/go/k8s/tests/README.md, src/go/k8s/tests/e2e/create-topic-given-cert-secret/00-create-cluster-issuer.yaml, src/go/k8s/tests/e2e/create-topic-given-cert-secret/01-redpanda-cluster.yaml, src/go/k8s/tests/e2e/create-topic-given-cert-secret/04-assert.yaml, src/go/k8s/tests/e2e/create-topic-given-cert-secret/04-create-schema.yaml, src/go/k8s/tests/e2e/create-topic-given-cm-secret-client-auth/00-create-certificate.yaml, src/go/k8s/tests/e2e/create-topic-given-cm-secret-client-auth/01-redpanda-cluster.yaml, src/go/k8s/tests/e2e/create-topic-given-cm-secret-client-auth/04-assert.yaml, src/go/k8s/tests/e2e/create-topic-given-cm-secret-client-auth/04-create-schema.yaml, src/go/k8s/tests/e2e/create-topic-given-issuer/00-create-cluster-issuer.yaml, src/go/k8s/tests/e2e/create-topic-given-issuer/01-redpanda-cluster.yaml, src/go/k8s/tests/e2e/create-topic-given-issuer/04-assert.yaml, src/go/k8s/tests/e2e/create-topic-given-issuer/04-create-schema.yaml
Backport:
*  #3496 
Fixes: https://github.com/vectorizedio/redpanda/issues/3494
=> [v21.11.x] Backport operator schema reg fix certs

src/v/coproc/script_context_frontend.cc
Ducktape failures for wasm have been observed for tests that crash a node. Asserts like this have been observed:
```
ERROR 2022-01-21 19:39:37,563 [shard 0] assert - Assert failure: (../../../src/v/coproc/script_context_frontend.cc:72) 'start <= end' Offset logic error start: 1976 end: 0
```
Since coproc only reads up until the high watermark of a log this seems suspect, how can coproc, be AHEAD of an input?
In the example above the start offset is `1976` after restart of the node due to the offset being read from disk, as this coprocessor is running in `Stored` mode. The `high_watermark` of the log cannot possibly be 0 since work was performed, however at this given moment it is 0, since the partitions haven't yet been hydrated.
If this case is observed, just yield. Eventually the …
=> coproc: Yield if inputs haven't been hydrated

tests/rptest/services/redpanda.py
This is needed because our current CI pipeline does not
retain builds -- on failures with raw backtraces, developers
cannot investigate without getting at the binary.
Work around this by zipping up the binary and saving
it as a 'log' from the test.
* none
=> tests: retain redpanda binary on Sanitizer failures

tests/rptest/tests/pandaproxy_test.py
=> ducktape: Disable test_consumer_group_binary_v2

src/v/kafka/server/handlers/fetch.cc
Recent changes in Fetch request handler introduced to keep reader alive
until aborted transactions are retrieved force a change to use `l-value`
version of `record_batch_reader::consume` method. The `l-value` version
doesn't close the reader correctly so it has to be handled by `consume`
caller.
Fixed error causing an assertion to be triggered saying that the
`log_reader` wasn't properly closed. Introduced deferred action that
closes the reader immediately when it goes out of scope.
* fixed regression that caused an assertion to be triggered during Fetch request handling
=> k/fetch_handler: always close reader before destroying it

src/v/kafka/server/handlers/fetch.cc
Backport of: 
- https://github.com/vectorizedio/redpanda/pull/3587
=> Backport #3587

.github/CODEOWNERS
Ben is gone and I'm the only writer, so I put myself as the documentation code owner.
=> updating documentation code owner in github

docs/www/data-archiving.md
=> docs: data archive - removing old message about upcoming features

docs/www/quick-start-kubernetes.md
Stuff from https://github.com/vectorizedio/documentation/issues/78
=> docs: adding rpk tune info

tools/ts-generator/rpc/rpc_gen_js.py
Backport of:
- https://github.com/vectorizedio/redpanda/pull/3604
(cherry picked from commit c900088)
=> Backport #3604 (coproc: Add on("error") for new connection )

src/v/storage/compaction_reducers.cc
In redpanda we store auxiliary metadata batches in the same log as the data.
The metadata baches may contain important information about raft
configuration transaction state or archival machinery. We can not
guarantee that those batches can be safely deleted during compaction.
This patch prevents compaction of non data batches.
Problem that is fixed with this batch was discovered in chaos testing.
Removal of raft configuration batches during compaction caused the
offset translator state to diverge on the nodes which were added to
partition replica set (offset translator rebuilt its state but
configuration batches were missing).
* none
=> s/compaction: only compact data batches during compaction

src/v/pandaproxy/rest/handlers.cc
Avoid using `rq` after move.
Excluding release notes since there's no evidence this caused an observable bug.
* none
=> pandaproxy/handlers: Don't use moved from value

src/v/cluster/members_backend.cc, src/v/cluster/metadata_dissemination_service.cc, src/v/cluster/metadata_dissemination_service.h, src/v/cluster/topic_table.h, src/v/kafka/server/group.cc, src/v/kafka/server/group.h, src/v/kafka/server/tests/error_mapping_test.cc, src/v/raft/follower_stats.cc, src/v/redpanda/application.cc, tests/rptest/services/failure_injector.py, tests/rptest/tests/node_operations_fuzzy_test.py
Backport of 
- https://github.com/vectorizedio/redpanda/pull/3355
- https://github.com/vectorizedio/redpanda/pull/3487
=> Backporting #3355 #3487

src/v/storage/segment_utils.cc
When we concatenate segments before compaction, temp files from previous
aborted compaction attempts can still be present. We delete these files
so that they don't confuse subsequent compaction stages.
Fixes #2989 (the problem, described in [this comment](https://github.com/vectorizedio/redpanda/issues/2989#issuecomment-1022328679))
* Fix rare data corruption when compacting multiple segments.
=> Storage: remove temp files from previous compaction attempts

tests/rptest/tests/raft_availability_test.py
These checks were a source of test failures when
run in very noisy test environments that had
stalls longer than raft timeouts.
Already disabled but now removing entirely to clean up & avoid
leaving behind stuff that can go stale (e.g. the leadership_changes
metric changed behavior slightly since that was originally written)
Fixes https://github.com/vectorizedio/redpanda/issues/2444
* none
=> tests: remove precise metrics checks in RaftAvailabilityTest

src/go/k8s/apis/redpanda/v1alpha1/cluster_webhook.go, src/go/k8s/apis/redpanda/v1alpha1/cluster_webhook_test.go
This adds a check to prevent users to reduce assigned discrete cores, causing startup issues.
I've tried to figure out if this check could be enforced only in certain cases, but it's hard to detect false positives.
Fixes #3639
* Kubernetes operator: the webhook now guards against decrease of the number of assigned cores
=> operator: disallow reducing the number of cores

tools/metadata_viewer/kafka.py, tools/metadata_viewer/viewer.py
Update metadata_viewer to dump record content (key & value)
Force push:
- fixed lint complaints
* none
=> tools: make viewer dump records

src/v/archival/tests/service_fixture.cc, src/v/cloud_storage/manifest.cc, src/v/cloud_storage/manifest.h, src/v/cloud_storage/offset_translation_layer.cc, src/v/cloud_storage/offset_translation_layer.h, src/v/cloud_storage/partition_recovery_manager.cc, src/v/cloud_storage/partition_recovery_manager.h, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_partition.h, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment.h, src/v/cloud_storage/tests/manifest_test.cc, src/v/cloud_storage/tests/offset_translation_layer_test.cc, src/v/cloud_storage/tests/remote_partition_test.cc, src/v/cloud_storage/tests/remote_segment_test.cc, src/v/cluster/archival_metadata_stm.cc
This PR changes the data structure that shadow indexing uses. Previous version
was prone to memory fragmentation and allocated memory for every uploaded
segment.
The improved version doesn't allocate memory per segment and uses more efficient
memory layout and data structures:
- absl::bree_map in the `manifest` and `remote_partition`
- The key in the manifest is a struct (offset + term) instead of the segment nam (ss::sstring)
- The `model::offset` is used as a key inside the `remote_partition`
- The variant type inside the `remote_partition` which is created per segment stores
the instance of the `offloaded_segment_state` instead of the pointer to it. This eliminates
allocation in case if the segment is not touched by the reader.
The manual tests showed improvement.
I was running …
=> Backport #3607 (Improve SI memory layout)

src/go/k8s/apis/redpanda/v1alpha1/cluster_webhook.go, src/go/k8s/apis/redpanda/v1alpha1/cluster_webhook_test.go
=> Backport fix for #3639

src/go/k8s/controllers/redpanda/cluster_controller.go, src/go/k8s/pkg/resources/configmap.go, src/go/k8s/pkg/resources/configmap_test.go, src/go/k8s/pkg/resources/resource_integration_test.go, src/go/k8s/pkg/resources/statefulset.go, src/go/k8s/pkg/resources/statefulset_test.go, src/go/k8s/pkg/resources/statefulset_update.go, src/go/k8s/pkg/resources/statefulset_update_test.go, src/go/k8s/tests/e2e/additional-configuration/02-assert.yaml, src/go/k8s/tests/e2e/additional-configuration/02-update-config.yaml, src/go/k8s/tests/e2e/additional-configuration/03-verify-config-changed.yaml, src/go/k8s/tests/e2e/additional-configuration/verify-config.sh
=> Backport fix for #2619

src/v/cluster/CMakeLists.txt, src/v/cluster/controller.cc, src/v/cluster/controller.h, src/v/cluster/fwd.h, src/v/cluster/metrics_reporter.cc, src/v/cluster/metrics_reporter.h, src/v/cluster/tests/CMakeLists.txt, src/v/cluster/tests/metrics_reporter_test.cc, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/rpc/CMakeLists.txt, src/v/rpc/tls.cc, src/v/rpc/tls.h, src/v/rpc/transport.cc, src/v/s3/client.cc, tests/docker/Dockerfile, tests/docker/Dockerfile.dockerignore, tests/python/simple_http_server/simple_http_server.py, tests/rptest/services/http_server.py, tests/rptest/services/templates/redpanda.yaml, tests/rptest/tests/metrics_reporter_test.py
Backport of redpanda Metrics Reporter feature
Backport of:
- https://github.com/redpanda-data/redpanda/pull/3066
- https://github.com/redpanda-data/redpanda/pull/3204
- https://github.com/redpanda-data/redpanda/pull/3515
- https://github.com/redpanda-data/redpanda/pull/3675
- https://github.com/redpanda-data/redpanda/pull/3721
=> Metrics reporter backport 

src/v/cluster/metadata_dissemination_service.cc
Previously metadata dissemination service used cluster health snapshot
to update partition leaders metadata. This might lead to situation in
which cluster health report in never requested and eventually metadata
information is not updated. This may lead to situation in which
different subsystems querying `cluster::partitions_leaders_table`
directly would receive stale leadership information. (if dissemination
request was lost)
Changed the metadata dissemination to request cluster health report
refresh. This way leadership information will always be updated and not
older than health monitor max metadata age.
* Querying partition leader via Metadata API will return correct data
=> c/metadata_dissemination: use health  report to udpdate leaders

src/v/cloud_storage/tests/CMakeLists.txt, src/v/cloud_storage/tests/directory_walker_test.cc
Add unit tests for cloud_storage directory walker.
=> cloud_storage: add unit tests for directory walker

.github/CODEOWNERS
=> codeowners: tweak ivotron's ownership of /tests

src/v/kafka/server/group.cc, src/v/kafka/server/group.h, src/v/utils/mutex.h
Improve latency of transactions by making possible to modify the same consumer group concurrently by multiple producers.
* none
* Decrease txn latency
=> Increase parallelism of the consumer groups parts of transacitons

docs/rfcs/20220119_raft_replication_simplification.md
Added an RFC describing raft simplification approach. 
force push:
- applied grammar review suggestions
=> Raft replication simplification RFC

src/v/model/model.cc
This needs for topic_manifest, we should be able to recreate topic
manifest from a serialized json, so operator<< and operator>> should
match
(cherry picked from commit 7fdd31265d122496d3a3ec6cc5c66fbd9aaf3627)
=> model: change << compaction_strategy to match >>

.github/ISSUE_TEMPLATE/03_doc_proposal.md
Adding more sections to our docs template
=> docs: adding more questions to doc template

src/v/cluster/controller_backend.cc, src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_types.cc, src/v/cluster/health_monitor_types.h, src/v/cluster/metadata_dissemination_service.cc, src/v/cluster/partition_leaders_table.cc, src/v/cluster/partition_leaders_table.h, src/v/cluster/service.cc, src/v/cluster/tests/serialization_rt_test.cc, src/v/kafka/server/group.cc, src/v/raft/consensus.cc, src/v/raft/errc.h, src/v/redpanda/admin_server.cc, tests/rptest/clients/rpk.py, tests/rptest/tests/leadership_transfer_test.py, tests/rptest/tests/recreate_topic_metadata_test.py
Backport of:
- https://github.com/redpanda-data/redpanda/pull/3834
- https://github.com/redpanda-data/redpanda/pull/3446
- https://github.com/redpanda-data/redpanda/pull/3182
Fixes: #3836 
Release notes:
- fixed updating leadership metadata of topics which were deleted and then recreated (fixes: #3836)
=> Backport of #3182 #3446 #3834

tests/rptest/tests/tx_admin_api_test.py
We should wait when new_leader is not -1 after admin.transfer_leadership_to
Fixes #3849
* none
=> [ducktape] Fix test_expired_transaction test

src/go/k8s/config/samples/sasl.yaml
adding a sasl.yaml example file (analogous to the existing tls.yaml file)
* none
This is useful for documentation around SASL config. 
-->
=> adding sasl.yaml example file

src/go/rpk/pkg/cli/cmd/topic/produce.go
=> rpk: fix minor typo.

src/v/cluster/topic_table.cc, src/v/redpanda/admin_server.cc, tests/rptest/tests/partition_movement_test.py
Backports
* https://github.com/redpanda-data/redpanda/pull/3846
Backports
* https://github.com/redpanda-data/redpanda/pull/3846
=> backport/v21.11.x: #3846

tests/rptest/tests/group_membership_test.py
Fix group_membership_test.test_topic_recreation test
Previously, we started producing messages without waiting for the topic to be created, this led to an error during producing. 
Now we wait for the topic to be created, and then we start producing
Fixes #3714
=> tests: Fix group_membership topic_recreation

src/v/cluster/tests/CMakeLists.txt, tests/rptest/tests/recreate_topic_metadata_test.py, tests/rptest/tests/wasm_topics_test.py
Related: #2909 #3858 #3859
* none
=> Disable tests that have been flaky in CI

src/go/k8s/config/samples/external_connectivity.yaml, src/go/k8s/config/samples/one_node_cluster.yaml, src/go/k8s/config/samples/one_node_external.yaml
Add schema registry to kubernetes samples
* Add schema registry to kubernetes samples
=> k8s: Add schema registry to samples

docs/rfcs/20220209_leader_epoch_support_rfc.md
=> rfcs: added leader epoch related rfc

src/v/cluster/feature_table.cc, src/v/cluster/feature_table.h, src/v/cluster/members_table.h, src/v/utils/waiter_queue.h
Very similar code was added concurrently in members_table and feature_table in separate PRs -- consolidate it into a shared utility header.
* none
=> cluster: refactor shared waiter_queue into utils

tools/coverage_dash.py
- The coverage stats for individual tests aren't that
interesting: the overall coverage %ge is.  Get it by
inserting a synthetic 'coverage_total' "test" with
a list of all the profraw files.
- Processing hundreds of tests' individual coverage
seriallly takes a long time.  Use a thread pool to
speed it up.  Don't include the total calculation in
the thread pool, because it has enough parallism on
its own (llvm-mergedata is multithreaded) and uses
lots of memory.
Also tidies:
- Check output on the `find` call for data files, so
that if someone gets a ducktape path wrong they
get a slightly more sensible error.
- Use a timestamped logger for output instead of raw prints.
* none
=> tools/coverage: calculate total coverage & speed up

tests/rptest/tests/topic_delete_test.py, tests/rptest/util.py
If something gets left behind we definitely want
to know what!
Related: https://github.com/redpanda-data/redpanda/issues/3924
Related: https://github.com/redpanda-data/redpanda/issues/3884
* none
=> tests: log file listing on failures to delete

src/v/cluster/controller_backend.cc, src/v/cluster/members_backend.cc, src/v/cluster/members_backend.h, src/v/cluster/metadata_dissemination_service.cc, src/v/cluster/tests/partition_moving_test.cc, src/v/raft/consensus.cc, src/v/raft/offset_translator.cc, src/v/raft/offset_translator.h, src/v/raft/tests/offset_translator_tests.cc, src/v/storage/disk_log_impl.cc
Backport of: 
- https://github.com/redpanda-data/redpanda/pull/3722
- https://github.com/redpanda-data/redpanda/pull/3242
- https://github.com/redpanda-data/redpanda/pull/3657
- https://github.com/redpanda-data/redpanda/pull/3433
Release notes:
- fixed issues related with partition movements
=> Backport of #3722 #3242 #3657 #3433

tests/rptest/tests/connection_rate_limit_test.py
This is newly added and appears not to be stable
yet.
Related https://github.com/redpanda-data/redpanda/issues/3975
* none
=> tests: disable connection_rate_limit_test

src/v/utils/tests/CMakeLists.txt, src/v/utils/tests/waiter_queue_test.cc, src/v/utils/waiter_queue.h
Fixed aborting waits in waiters queue.
=> Fix waiters queue abort

src/go/k8s/config/samples/mtls.yaml
I need an example config file for mtls for the doc, analogous to the tls.yaml and sasl.yaml files.
=> adding mtls exaple file

tests/rptest/services/kaf_consumer.py, tests/rptest/tests/connection_rate_limit_test.py
Fix connection_rate_limit_test.
Use the average consuming time in assertion.
Also decrease `backoff_sec` for waitng consuming all data
Fixes: #3975
* none
=> ducktape: Fix connection_rate_limit_test

tests/rptest/services/redpanda.py
Segfaults come with backtraces, but they can't be decoded without the binary the test ran with.
We already detect the crashes: let's keep the binary in the same code paths.
* none
=> tests: save binaries on segfaults and assertions

src/v/cluster/node/local_monitor.cc, src/v/cluster/node/local_monitor.h, src/v/cluster/tests/local_monitor_test.cc
Addressing some (at)dotnwat review comments from pull request 3715.
Mostly non-functional and test changes. **Based off PR#3885, so ignore the first couple commits in review until that is merged.**
* none
=> Address nits from code review

tests/rptest/services/redpanda.py
This PR adds the same level of debug logging that is currently used to start redpanda, when starting the wasm engine, i.e. printing open / listening ports, and active processes on the current node.
Furthermore this PR modifies how ducktape considers the wasm_engine to be `started`. Previously it was considered `started` when the process was up, now it is to be considered `started` when the service it starts is in a listening state.
All of this is to increase debuggability around a newly observed issue #4023 where ducktape failed with error due to the fact that one of 3 wasm engines on a ducktape node failed to start because of an `address already in use` error.
This PR also makes these types of errors easier to debug as now when this type of issue occurs, `redpanda_service` will assert, …
=> Increase debug logging for wasm_engine startup procedure within ducktape

tests/rptest/services/redpanda.py, tests/rptest/tests/node_metrics_test.py
Add integration test for new disk space metrics.
Related: #2166
* none
=> Integration test for new disk metrics

src/go/rpk/pkg/cli/cmd/debug/bundle.go, src/go/rpk/pkg/cli/cmd/debug/info.go
Replace "Vectorized" with "Redpanda Data".
Changes can be seen in output of:
* `rpk debug --help`
* `rpk info --help`
* none
=> rpk: update short description with new company name

src/v/archival/fwd.h, src/v/cloud_storage/fwd.h, src/v/cloud_storage/partition_recovery_manager.cc, src/v/cloud_storage/partition_recovery_manager.h, src/v/cloud_storage/recursive_directory_walker.cc, src/v/cloud_storage/recursive_directory_walker.h, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment.h, src/v/cloud_storage/remote_segment_index.h, src/v/cloud_storage/tests/common_def.h, src/v/cloud_storage/tests/remote_segment_index_test.cc, src/v/cloud_storage/types.cc, src/v/cloud_storage/types.h, src/v/test_utils/tmp_dir.h, src/v/utils/delta_for.h
Fix some issues from #3830
- A bunch of typos
- Use of old Seastar API (get0)
- Incorrect license headers
* none
=> Remote segment index followup

src/v/redpanda/main.cc
To adjust for company rename and clean up the phrasing.
Also reordered the list in the sequence that would be generally recommended for finding answers to questions--putting docs link first.
* none
=> update links and wording of `redpanda --help` output

.github/workflows/rpk-build.yml
=> [v21.11.x] gha/rpk: install gon without homebrew

src/v/storage/failure_probes.h, src/v/storage/tests/log_segment_appender_test.cc, src/v/storage/tests/log_segment_reader_test.cc
A couple of cleanup patches I made to prepare for new file-level failure injection and testing.
=> Unit test and failpoint cleanup.

src/v/dashboard/src/App.tsx
Update links for company name change.
* none
=> dashboard: update footer with new company links

licenses/README.md, licenses/boilerplate.go.txt, licenses/bsl.md, licenses/bsl_header.txt, licenses/cla.md, licenses/rcl.md, licenses/rcl_header.txt
Following on from https://github.com/redpanda-data/redpanda/pull/4037#issuecomment-1075301935
Update the licenses files with new company name.
* none
=> Update licenses files with new company name

src/go/k8s/hack/verify-condition-message.sh, src/go/k8s/tests/e2e/centralized-configuration-bootstrap/00-assert.yaml, src/go/k8s/tests/e2e/centralized-configuration-bootstrap/02-probes.yaml, src/go/k8s/tests/e2e/centralized-configuration-tls/02-probe.yaml, src/go/k8s/tests/e2e/centralized-configuration-tls/05-probe.yaml, src/go/k8s/tests/e2e/centralized-configuration-upgrade/03-probe.yaml, src/go/k8s/tests/e2e/centralized-configuration/02-probe.yaml, src/go/k8s/tests/e2e/centralized-configuration/05-probe.yaml
Trying to fix Kuttl test.
Fixes #4122
=> operator: fix flaky kuttl tests

tests/rptest/tests/many_clients_test.py
Make the test less aggressive until we can make
Redpanda cope better with very low memory condition.
Related: https://github.com/redpanda-data/redpanda/issues/4162
* none
=> tests: increase memory size in ManyClientsTest

src/v/cluster/health_monitor_types.cc
Avoid crashing on receiving a serialized struct with version 1.  Enables rolling upgrades from 21.11.x to 22.1.x, as long as the 21.11.x version includes this change.
* none
=> [v21.11.x] cluster: node_health_report compat with 22.1.x

src/v/cluster/partition_leaders_table.cc, src/v/cluster/partition_leaders_table.h, src/v/raft/kvelldb/kvrsm.cc, src/v/raft/kvelldb/kvrsm.h, src/v/raft/mux_state_machine.h, src/v/raft/state_machine.h, src/v/utils/expiring_promise.h
=> [21.11.x]: backport #4153

src/v/raft/consensus.cc, src/v/raft/consensus.h
=> [21.11.x]: backport #4206

src/v/redpanda/admin_server.cc, src/v/redpanda/request_auth.cc
This is some cleanup from me re-reading the original RFC, where I had planned to have this log output.
* none
=> admin: emit warning on insecure admin API endpoint, log auth failures at WARN level

tests/rptest/wasm/wasm_build_tool.py
- This change exposes the output of `npm install` and `npm run build` to stderr/stdout, exposing possible npm errors within failed ducktape tests
- Meant to debug the error discovered and logged in issue #4061
=> Add additional debugging to npm commands run within wasm duckatpe tests

tests/rptest/tests/topic_recovery_test.py
Related: https://github.com/redpanda-data/redpanda/issues/4202
* none
=> tests: ok_to_fail TopicRecoveryTest unreliable cases

tests/docker/Dockerfile, tests/rptest/clients/rpk.py, tests/rptest/services/kafka.py, tests/rptest/services/mirror_maker2.py, tests/rptest/services/rpk_consumer.py, tests/rptest/services/templates/mirror_maker2.properties, tests/rptest/tests/mirror_maker_test.py, tests/setup.py
Added basic Mirror Maker based tests. The tests contain 2 tests: 
- Redpadna -> Redpanda
- Kafka -> Redpanda
Fixes #4054
=> MirrorMaker2 tests

src/v/cluster/members_backend.cc, src/v/cluster/members_backend.h, src/v/raft/consensus.cc, src/v/raft/types.cc, src/v/rpc/transport.cc, src/v/storage/disk_log_impl.cc, tests/rptest/services/failure_injector.py, tests/rptest/tests/node_operations_fuzzy_test.py
Fixes for failing node operations fuzzy tests. 
Fixes #4045
Fixes #3866
Fixes #1892
Fixes #3884
=> Fixes for node operations fuzzy test

tests/rptest/tests/topic_delete_test.py
Add stress test for topic_delete_test
Use sleep, because `self.redpanda.storage()` is blocked during kaf_producer working
* none
=> Add stress test for test_topic_delete

src/go/k8s/controllers/redpanda/cluster_controller_configuration_test.go
Changes to core should not have affected the test since it uses a mock admin API. What triggers the test is a conflict with the Kubernetes API when trying to apply a change. This should fix it by waiting an additional reconcile loop for things to be settled.
Fix #4267
=> operator: fix conflict in controller test

src/v/kafka/server/handlers/alter_configs.cc, src/v/kafka/server/handlers/incremental_alter_configs.cc, src/v/kafka/server/handlers/topics/types.h, src/v/kafka/server/tests/alter_config_test.cc, tests/rptest/tests/alter_topic_configuration_test.py
Backport https://github.com/redpanda-data/redpanda/pull/4223
Fixes #4209
=> [v21.11.x] backport pr4223

src/v/kafka/server/tests/list_offsets_test.cc, src/v/storage/tests/utils/random_batch.cc, src/v/storage/tests/utils/random_batch.h
=> kafka: Filter timequery for raft_data - test

cmake/oss.cmake.in
This picks up the commit of [21d665aebf7b74371e4527299441812de5eea6c2](https://github.com/redpanda-data/seastar/commit/21d665aebf7b74371e4527299441812de5eea6c2),
which instantiate the template specialization of
template future<> sleep_abortable<manual_clock>(typename manual_clock::duration, abort_source&)
which is used by
net::connection_rate<seastar::manual_clock>::spawn_updating_fiber_if_needed()
in src/v/net/connection_rate.h
without this change, we'd run into following FTBFS:
src/v/net/tests/CMakeFiles/net_connection_rate_rpunit.dir/connection_rate_test.cc.o: in function `net::connection_rate<seastar::manual_clock>::spawn_updating_fiber_if_needed(seastar::lw_shared_ptr<net::connection_rate_counter<seastar::manual_clock> >)::{lambda()#1}::operator()()': …
=> cmake: update seastar to tip of redpanda-data/seastar/master

src/v/kafka/server/handlers/topics/types.h, tests/rptest/clients/kafka_cli_tools.py, tests/rptest/tests/alter_topic_configuration_test.py
=> [v21.11.x] backport pr4313

src/v/cluster/id_allocator_frontend.cc, src/v/cluster/rm_partition_frontend.cc, src/v/config/configuration.cc, src/v/kafka/server/handlers/init_producer_id.cc, src/v/vformat.h, tests/rptest/services/admin.py, tests/rptest/services/redpanda.py, tests/rptest/tests/many_partitions_test.py, tests/rptest/tests/raft_availability_test.py
Enable idempotency by default.
Fixes #3827
* Enable idempotency by default
=> idempotency: enable by default

.github/workflows/backport-command.yml
Following on #4296, no functionality change, just simplifying the error handling and adding log messages to help in debugging.
* none
=> gha: clean up error handling for /backport

src/go/k8s/controllers/redpanda/cluster_controller_configuration_test.go
Fix https://github.com/redpanda-data/redpanda/issues/4267
Making sure that the test code ignores conflicts and retries in all places.
=> operator: fix possible conflicts in controller tests

src/go/rpk/pkg/cli/cmd/redpanda_darwin.go, src/v/cluster/tests/leader_balancer_bench.cc, src/v/cluster/tests/leader_balancer_test_utils.h, src/v/json/_include_first.h, src/v/json/encodings.h, src/v/json/istreamwrapper.h, src/v/json/ostreamwrapper.h, src/v/json/prettywriter.h, src/v/json/reader.h, src/v/json/schema.h, src/v/json/stream.h, src/v/json/stringbuffer.h, src/v/json/types.h, src/v/pandaproxy/json/test/parse.cc, tests/rptest/services/producer_swarm.py, tests/rptest/tests/many_clients_test.py, tests/rptest/tests/rack_aware_replica_placement_test.py
This PR follows on PR #4037 to update more files. Looks like a few PRs were merged with old copyright headers. 
* none
=> update more copyright headers to use Redpanda Data

tests/rptest/services/redpanda.py, tests/rptest/tests/many_partitions_test.py
=> tests: prepare ResourceSettings for use on EC2 nodes, create high scale mode for ManyPartitionsTest

.github/CODEOWNERS
Updates rpk codeowners to include @r-vasquez (and remove Lena who works on the C++ stuff :) )
* none
=> CODEOWNERS: update rpk

tests/rptest/archival/s3_client.py, tests/rptest/services/redpanda.py, tests/rptest/tests/redpanda_test.py
This PR includes various edits to support S3 buckets in ducktape. It also extends the Scale class to count clustered ducktape (CDT) as an option since most tests that use S3 will be on CDT.
To run a test with S3, simply provide your AWS creds via task.
For example:
```
task rp:run-ducktape-tests  S3_ACCESS_KEY="it's a secret" S3_SECRET_KEY="it's a secret"
```
Changes from force-push `7c79845`:
- Removed mods to Scale interface
- Include annotations
- Include asserts where necessary
- Edit SISettings so it is backwards compatible with previous tests
=> ducky: include support for S3

src/v/redpanda/CMakeLists.txt
Simplifies admin server json handling in cmake.
=> build: simplify admin server json handling

tests/rptest/services/redpanda.py, tests/rptest/tests/rack_aware_replica_placement_test.py
Doing individual start_node calls results in skipping
important preparation work that happens in RedpandaService.start,
such as cleaning down the nodes if they were left dirty by
a previous test.
This fixes an issue where this test fails if a previous
test leaves content in /var/lib/redpanda/data.
* none
=> tests: use RedpandaService.start in RackAwareReplicaPlacementTest

src/go/rpk/pkg/api/admin/api_broker.go, src/go/rpk/pkg/cli/cmd/redpanda/admin/brokers/brokers.go
=> V22.1.x Backport for PR 4333

src/v/cluster/members_manager.cc, src/v/cluster/members_manager.h, src/v/cluster/members_table.cc, src/v/cluster/members_table.h, src/v/redpanda/admin/api-doc/broker.json, src/v/redpanda/admin_server.cc, tests/rptest/services/admin.py, tests/rptest/tests/cluster_view_test.py
Backports https://github.com/redpanda-data/redpanda/pull/3370: versioned cluster_view api
=> Backport v21.11.x pr3370

src/go/k8s/controllers/redpanda/cluster_controller_configuration_test.go
Fixes: #4429
Backport of: #4340
Cherry-picked from: d9c00e2ea6291e8b286de86ad62cc7017c78d543
=> [v22.1.1] Backport pr4340 to v22.1.x

src/v/cluster/controller.cc, src/v/cluster/drain_manager.cc, src/v/cluster/drain_manager.h, src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_backend.h, src/v/cluster/health_monitor_frontend.cc, src/v/cluster/health_monitor_frontend.h, src/v/cluster/health_monitor_types.cc, src/v/cluster/health_monitor_types.h, src/v/cluster/id_allocator_frontend.cc, src/v/cluster/metadata_dissemination_service.cc, src/v/cluster/metadata_dissemination_utils.cc, src/v/cluster/metadata_dissemination_utils.h, src/v/cluster/tests/metadata_dissemination_utils_test.cc, src/v/kafka/server/errors.h, src/v/raft/vote_stm.cc, src/v/redpanda/admin/api-doc/broker.json, src/v/redpanda/admin_server.cc, src/v/rpc/transport.h, tests/rptest/services/admin.py, tests/rptest/tests/maintenance_test.py, tests/rptest/tests/raft_availability_test.py, tests/rptest/util.py
Fixes: https://github.com/redpanda-data/redpanda/issues/4422
Fixes: https://github.com/redpanda-data/redpanda/issues/4424
Fixes: https://github.com/redpanda-data/redpanda/issues/4426
Fixes: https://github.com/redpanda-data/redpanda/issues/4428
Fixes: https://github.com/redpanda-data/redpanda/issues/4430
Fixes: https://github.com/redpanda-data/redpanda/issues/4432
=> [v22.1.1] Collection of backports

src/v/cluster/persisted_stm.cc, src/v/cluster/rm_stm.cc, src/v/cluster/tests/tm_stm_tests.cc, src/v/cluster/tm_stm.cc, src/v/cluster/tm_stm.h, src/v/cluster/tx_gateway_frontend.cc, src/v/cluster/tx_gateway_frontend.h
Backports https://github.com/redpanda-data/redpanda/pull/3616/: fixes transaction errors
=> Backport v21.11.x pr3616

tests/docker/Dockerfile, tests/rptest/services/franz_go_verifiable_services.py
Support setting the maximum batch bytes for producers.
The change on the kgo-verifier is here https://github.com/redpanda-data/kgo-verifier/pull/1.
Closes: #4471
=> ducky/FranzGoServices: Add batchmaxbytes option

tests/rptest/services/kafka_cli_consumer.py, tests/rptest/tests/fetch_long_poll_test.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/4506
Fixes https://github.com/redpanda-data/redpanda/issues/4509
=> [v22.1.x] Fetch long poll fix

src/go/rpk/pkg/cli/cmd/cluster/config/import.go, src/go/rpk/pkg/cli/cmd/cluster/config/set.go, tests/rptest/tests/cluster_config_test.py
Improves the output messages when updating configuration options.
Fixes: #4370
* none
=> rpk: improve configuration update message

src/go/rpk/pkg/cli/cmd/cluster/config/import.go, src/go/rpk/pkg/cli/cmd/cluster/config/set.go, tests/rptest/tests/cluster_config_test.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/4512
Fixes https://github.com/redpanda-data/redpanda/issues/4375
=> [v22.1.x] rpk: improve configuration update message

src/go/rpk/pkg/api/admin/api_cluster.go, src/go/rpk/pkg/cli/cmd/cluster.go, src/go/rpk/pkg/cli/cmd/cluster/health.go, src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_backend.h, src/v/cluster/health_monitor_frontend.cc, src/v/cluster/health_monitor_frontend.h, src/v/cluster/health_monitor_types.h, src/v/redpanda/CMakeLists.txt, src/v/redpanda/admin/api-doc/cluster.json, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h, tests/docker/docker-compose.yml, tests/docker/ducktape_cluster.json.j2, tests/rptest/services/admin.py, tests/rptest/tests/cluster_health_overview_test.py
Backport for: #4295
Fixes: https://github.com/redpanda-data/redpanda/issues/4527
=> [v22.1.x] backport #4295

src/v/cluster/archival_metadata_stm.cc, src/v/cluster/partition.cc, src/v/cluster/partition.h, src/v/cluster/persisted_stm.cc, src/v/cluster/rm_stm.cc, src/v/kafka/server/handlers/fetch.cc, src/v/kafka/server/materialized_partition.h, src/v/kafka/server/partition_proxy.h, src/v/kafka/server/replicated_partition.cc, src/v/kafka/server/replicated_partition.h, src/v/model/fundamental.h, src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/consensus_utils.cc, src/v/raft/consensus_utils.h, src/v/raft/offset_translator.cc, src/v/raft/recovery_stm.cc, src/v/raft/tests/consensus_utils_test.cc, src/v/raft/tests/offset_translator_tests.cc, src/v/storage/offset_translator_state.cc, tests/rptest/tests/multi_restarts_with_archival_test.py, tests/rptest/tests/offset_for_leader_epoch_test.py
* Backport of https://github.com/redpanda-data/redpanda/pull/4201
Also contains simple PR to fix a test timeout https://github.com/redpanda-data/redpanda/pull/4559 and another for log severity warning level https://github.com/redpanda-data/redpanda/pull/4561
=> [v22.1.x] backport #4201

src/v/config/configuration.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/4468
=> [v22.1.x] config: adjust visibility of enable_rack_awareness

.github/workflows/slack-messages.yml
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/4500
=> [v22.1.x] Post announcements to internal Slack channels on releases

src/v/kafka/server/group_metadata_migration.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/4487
Fixes https://github.com/redpanda-data/redpanda/issues/4485
=> [v22.1.x] kafka: fix undefined behavior in consumer group topic migration

tests/rptest/tests/franz_go_verifiable_test.py
Currently we have a few tests running on CDT but they use fixed configuration options.
Modify one of the tests to use different combinations of configs such as different segment sizes and time boxed uploads.
Fixes: #4483
Fixes: #4558 - we can ignore that error
=> ducky/FranzGoTest: add a matrix of config options

tests/rptest/clients/rpk.py, tests/rptest/tests/mirror_maker_test.py
Currently, our MM2 consumer groups tests uses a topic with a small amount of data and low partition count. This PR increases those parameters.
Fixes: #4240
=> tests: scale mm2 consumer groups tests for CDT

src/go/rpk/pkg/config/config_test.go, src/go/rpk/pkg/config/schema.go, src/v/config/tls_config.h
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/4603
=> [v22.1.x] rpk/config: Add ServerTLS:Other

.github/workflows/slack-messages.yml
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/4500
=> [v21.11.x] Post announcements to internal Slack channels on releases

src/v/cluster/config_manager.cc, src/v/config/base_property.h, src/v/config/configuration.cc, src/v/config/property.h, src/v/kafka/client/configuration.cc, src/v/redpanda/admin/api-doc/cluster_config.json, src/v/redpanda/admin_server.cc, src/v/redpanda/application.cc, tests/rptest/tests/cluster_config_test.py
Backport of:
- https://github.com/redpanda-data/redpanda/pull/3261
- https://github.com/redpanda-data/redpanda/pull/3219
=> [V21.11.x] Backport of #3261, #3219

src/go/k8s/controllers/redpanda/suite_test.go, src/go/k8s/pkg/resources/configmap.go, src/go/k8s/pkg/resources/configmap_test.go, src/go/k8s/pkg/resources/resource_integration_test.go, src/go/k8s/tests/e2e/additional-configuration/00-redpanda-cluster.yaml, src/go/k8s/tests/e2e/additional-configuration/verify-config.sh
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/4627
=> [v22.1.x] k8s: Remove defaults Redpanda configuration options

src/v/cluster/config_manager.cc
Backport of https://github.com/redpanda-data/redpanda/pull/4654
Fixes #4657
=> [V22.1.x] Backport of #4654

tests/rptest/wasm/wasm_build_tool.py
This reduces spurious test failures if there is a transient
connectivity issue with npm repositories.
Example:
https://buildkite.com/redpanda/redpanda/builds/9929#325ed84d-d839-4253-b5d6-6290baec49ed
* none
=> tests: retry run_npm_cmd on network errors

tests/rptest/tests/topic_recovery_test.py
Fixes #4520 
In topic_recovery_test.TopicRecoveryTest.test_missing_segment when comparing restored data from S3 versus locally generated baseline data, the size of the baseline is reduced by default segment size, to accommodate for the fact that the deleted segment will not be recovered. The assertion is then roughly:
`restored = baseline - <default segment size>`
This change caches the actual size of the deleted segment on S3/minio, and uses that size to adjust the baseline data, so that if the deleted segment was smaller than the default segment size, an assertion failure is not seen later because of the difference between the default segment size and the (smaller) deleted segment size.
* none
=> tests: adjusts assertion size for deleted segment

tests/rptest/wasm/wasm_build_tool.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/4641
=> [v22.1.x] tests: retry run_npm_cmd on network errors

src/v/cluster/config_manager.cc
Backport of https://github.com/redpanda-data/redpanda/pull/4654
Fixes #4656
=> [V21.11.x] Backport of #4654

tests/rptest/tests/franz_go_verifiable_test.py
Fixes https://github.com/redpanda-data/redpanda/issues/4635
* none
=> tests: extend log allow list for kgo-verifier tests

src/v/cloud_storage/remote.cc
S3 doesn't tell us why it's having an InternalError, but
it doesn't indicate an error on our part, so we should
treat it as retryable, _but_ with a backoff to hopefully
sidestep whatever issue the service is happening.  So
treat it like a slowdown.
* Tiered storage uploads are now retried more promptly if the S3 server throws an InternalError
=> cloud_storage: treat S3 InternalError as a backoff

tests/rptest/tests/topic_recovery_test.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/4622
Fixes https://github.com/redpanda-data/redpanda/issues/4689
=> [v22.1.x] tests: adjusts assertion size for deleted segment

src/v/bytes/iobuf_istreambuf.h, src/v/s3/client.cc, src/v/s3/tests/s3_client_test.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/4749
=> [v22.1.x] s3: Improve error handling

tests/rptest/clients/rpk.py
This PR aims to fix the parse error that occurred during the `rptest.tests.mirror_maker_test.TestMirrorMakerService.test_consumer_group_mirroring` ducktape test. This error appears to have occurred due to leadership changes that were happening on the cluster during the rpk describe command. To avoid this error from occurring in the future the test has been changed to make repeated calls to the rpk describe command until a result is received with during a period of stable leadership.
Fixes #4687 
* none
=> tests: retry describe_groups on leadership instability

src/go/rpk/pkg/kafka/client_franz.go
Adds a metadata request during client creation in rpk to check for possible sasl errors.
before
```
$ rpk topic list
unable to request metadata: EOF
$ rpk topic list --sasl-mechanism SCRAM-SHA-256 --user invalid --password invalid
unable to request metadata: SASL authentication failed: security: Invalid credentials: SASL_AUTHENTICATION_FAILED: SASL Authentication failed.
```
after
```
$ rpk topic list                    
unable to initialize kafka client: brokers keep immediately closing connections, which happens when SASL is required but not provided: is SASL expected?
$ rpk topic list --sasl-mechanism SCRAM-SHA-256 --user invalid --password invalid
unable to request metadata: SASL authentication failed: security: Invalid credentials: SASL_AUTHENTICATION_FAILED: SASL Authentication …
```
=> rpk: add metadata request in client creation to control sasl errors

tests/rptest/tests/topic_recovery_test.py
Disable flaky `test_missing_segment`.
* none
=> rptest: Disable test_missing_segment

src/v/bytes/utils.h, src/v/cluster/archival_metadata_stm.cc, src/v/cluster/feature_barrier.h, src/v/cluster/rm_group_proxy.h, src/v/cluster/scheduling/leader_balancer_strategy.h, src/v/hashing/crc32.h, src/v/hashing/crc32c.h, src/v/http/client.cc, src/v/kafka/protocol/schemata/generator.py, src/v/model/record_utils.cc, src/v/random/fast_prng.h, src/v/random/generators.h, src/v/storage/index_state.cc, src/v/storage/log_replayer.cc, src/v/storage/segment_appender.h, src/v/storage/snapshot.cc, src/v/storage/types.h, src/v/test_utils/fixture.h
Miscellaneous chores / improvements made in the course of fiddling with the build system.
* None
=> chore: miscellaneous improvements and fixes

src/v/bytes/details/io_allocation_size.h
To avoid manually counting the arrays, which is error-prone and boring
=> Minor improvement, switch to to_array

src/go/k8s/go.mod, src/go/k8s/go.sum, src/go/rpk/go.mod, src/go/rpk/go.sum, src/go/rpk/pkg/api/api.go, src/go/rpk/pkg/api/api_test.go, src/go/rpk/pkg/cli/cmd/redpanda/start.go, src/go/rpk/pkg/config/config_test.go, src/go/rpk/pkg/config/manager.go
This removes the ability to send json of the config file to metrics api
=> rpk: remove readAsJson from config manager

src/v/kafka/server/group.cc, src/v/kafka/server/group.h, src/v/kafka/server/group_metadata_migration.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/4902
=> [v22.1.x] Fix logging in group_metadata_migration

src/go/rpk/pkg/cli/cmd/debug/bundle.go
rpk blindly reads configuration into an untyped map. We want to make sure that we don't store any of those parameters when using `rpk debug bundle`
Now we redact this "blind parameters", e.g:
original redpanda.yaml
```yaml
config_file: /etc/redpanda/redpanda.yaml
other_unwanted: SECREET
pandaproxy: 
not_needed: UNWANTEEEDDD
pandaproxy_api_tls:
- name: normal
secret: SECREEET
- name: superNormal
secret: SECREEET
redpanda:
admin:
- address: 0.0.0.0
port: 9644
admin_api_tls:
- name: normal
secret: SECREEET
- name: superNormal
secret: SECREEET
data_directory: /var/lib/redpanda/data
developer_mode: true
kafka_api:
- address: 0.0.0.0
name: default
port: 9092
kafka_api_tls:
- name: normal
secret: SECREEET
- name: superNormal
secret: SECREEET
node_id: 1
rpc_server:
address: 0.0.0.0
port: 33145 …
```
=> rpk: redact blindly decoded parameter

src/v/cluster/archival_metadata_stm.cc, src/v/cluster/archival_metadata_stm.h, src/v/cluster/partition_manager.cc, src/v/cluster/persisted_stm.cc, src/v/cluster/persisted_stm.h, tests/rptest/services/redpanda.py, tests/rptest/tests/e2e_topic_recovery_test.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/4801
Fixes https://github.com/redpanda-data/redpanda/issues/4845
=> [v22.1.x] rptest: Add topic recovery end to end test

cmake/oss.cmake.in, src/v/cluster/topics_frontend.cc, src/v/coproc/reconciliation_backend.cc, src/v/kafka/server/handlers/topics/topic_utils.h, src/v/raft/configuration_manager.cc, src/v/raft/replicate_entries_stm.cc, src/v/raft/state_machine.cc, src/v/raft/state_machine.h, src/v/storage/readers_cache.cc
Fixes various typos. Contains no functional changes.
* none
=> fix various typos

tools/metadata_viewer/controller.py
=> md-viewer/controller: added support for centralized configuration

src/v/http/client.cc, src/v/http/client.h, src/v/s3/client.cc, src/v/s3/signature.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/4939
=> [v22.1.x] cloud_storage: redacts fields from header

src/v/serde/serde.h, src/v/serde/test/serde_test.cc
=> serde: added bytes support

tests/docker/Dockerfile
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/4553
fixes https://github.com/redpanda-data/devprod/issues/314
* none
=> [v21.11.x] Pin Go dependency versions for test Dockerfile

tests/rptest/services/redpanda.py, tests/rptest/tests/compatibility/sarama_test.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/4710
=> [v22.1.x] tests: disable topic auto creation by default

tests/rptest/tests/nodes_decommissioning_test.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/4681
Fixes https://github.com/redpanda-data/redpanda/issues/4685
=> [v22.1.x] tests: fix nodes_decommissioning_test

src/v/cloud_storage/remote.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/4706
=> [v22.1.x] cloud_storage: treat S3 InternalError as a backoff

.github/workflows/slack-messages.yml
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/4511
=> [v21.11.x] Post announcements to community Slack channels on releases

src/go/rpk/pkg/cli/cmd/acl/user.go
Edited the rpk acl command help to a) clarify sasl mechanism flag and b) fix bracketing.
=> Clarify sasl mechanism flag usage and fix bracketing

src/v/cluster/tests/CMakeLists.txt, src/v/model/fundamental.h, src/v/model/metadata.h, src/v/reflection/type_traits.h, src/v/serde/serde.h, src/v/serde/test/serde_test.cc, src/v/tristate.h
As we are moving further with serde use we need to add serde support for all abundant types.
=> Added serde support for basic common types

src/go/rpk/pkg/cli/cmd/cluster/config/import.go, src/v/cluster/config_manager.cc, src/v/config/base_property.h, src/v/config/config_store.h, src/v/config/property.h, src/v/config/tests/config_store_test.cc, src/v/coproc/event_listener.cc, src/v/coproc/tests/fixtures/coproc_test_fixture.cc, src/v/pandaproxy/schema_registry/api.cc, src/v/pandaproxy/schema_registry/test/compatibility_3rdparty.cc, src/v/pandaproxy/schema_registry/test/consume_to_store.cc, src/v/redpanda/admin_server.cc, src/v/redpanda/application.cc, src/v/redpanda/tests/fixture.h, tests/rptest/tests/cluster_config_test.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5024.
=> [v22.1.x] admin_server: redact configs in admin API

tests/rptest/tests/topic_recreate_test.py
=> tests: added test validating creating and deleting topic many times

cmake/FindValgrind.cmake, cmake/main.cmake, cmake/oss.cmake.in, src/v/cluster/types.h, src/v/net/connection.h, src/v/net/server.cc, src/v/redpanda/admin_server.cc, src/v/redpanda/tests/cli_parser_tests.cc, src/v/storage/opfuzz/opfuzz.cc
Update seastar and fix the breaking changes.
This should probably be a squash merge.
* none
=> Update seastar v22.2.x

tests/rptest/tests/consumer_offsets_migration_test.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5074.
=> [v22.1.x] tests: Deflake test_migrating_consume_offsets

src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/schema_registry/handlers.cc, src/v/pandaproxy/schema_registry/handlers.h, src/v/pandaproxy/schema_registry/service.cc, tests/rptest/tests/schema_registry_test.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5098.
=> [v21.11.x] schema_registry: Support GET /mode

src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/schema_registry/handlers.cc, src/v/pandaproxy/schema_registry/handlers.h, src/v/pandaproxy/schema_registry/service.cc, tests/rptest/tests/schema_registry_test.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5098.
=> [v22.1.x] schema_registry: Support GET /mode

src/v/cluster/archival_metadata_stm.cc
Backport of #4691.
Fixes #4717 
Issue  #4590: si: reduce severity of warning message
=> [v22.1.x] archival_metadata_stm: return error code instead of throwing

src/go/k8s/controllers/redpanda/cluster_controller_configuration.go, src/go/k8s/controllers/redpanda/suite_test.go, src/go/k8s/pkg/admin/admin.go, src/go/k8s/tests/e2e/centralized-configuration-upgrade/01-assert.yaml, src/go/k8s/tests/e2e/centralized-configuration-upgrade/01-first-upgrade.yaml, src/go/k8s/tests/e2e/centralized-configuration/03-assert.yaml, src/go/k8s/tests/e2e/update-conf-image/00-configurator.yaml, src/go/k8s/tests/e2e/update-conf-image/01-assert.yaml, src/go/k8s/tests/e2e/update-conf-image/03-assert.yaml, src/go/rpk/pkg/api/admin/api_config.go, src/go/rpk/pkg/cli/cmd/cluster/config/status.go
Fix #5146
By backporting #5111 and #5125
=> [v22.1.x] Backport fix for central config management in operator

src/v/cluster/tests/serialization_rt_test.cc, src/v/cluster/types.cc, src/v/cluster/types.h, src/v/model/adl_serde.cc, src/v/model/metadata.h, src/v/model/tests/randoms.h, src/v/net/unresolved_address.h, src/v/raft/tests/configuration_manager_test.cc, src/v/raft/tests/configuration_serialization_test.cc, src/v/raft/tests/foreign_entry_test.cc, src/v/raft/tests/simple_record_fixture.h, src/v/raft/tests/type_serialization_tests.cc, src/v/serde/serde.h, src/v/serde/test/serde_test.cc, src/v/test_utils/randoms.h
Add serde support for cluster::configuration_update_request as part of transition to rpc serde support.
Related: https://github.com/redpanda-data/redpanda/issues/4879
* None
=> cluster: add serde support for cluster::configuration_update_request

src/v/storage/tests/storage_e2e_test.cc
This is a peculiar case.  Having reproduced and traced through
the execution of the futures behind the truncate future, there
is nothing actually blocking, but the future is somehow not
completing until after something else 'kicks' seastar.
In the failing case, that 'kick' comes when the test fails
and stuff is torn down (we can see the truncation completing
in the same millisecond just after the failure message).
The test also succeeds reliably if the success condition is
modified to check .available(), and then wait another millisecond
if it's not ready yet: this is not a timing thing, it's simply
scheduling an additional future that moves things forward.
So we can work around this by breaking up the 200ms wait
into two 100ms waits to create an extra scheduling point.
Fixes …
=> storage: fix intermittent failure in `disposing_in_use_reader`

src/v/cluster/feature_barrier.cc, src/v/cluster/tests/serialization_rt_test.cc, src/v/cluster/types.h, src/v/serde/serde.h
Adds serde support for several controller RPC message types.
* None
=> controller: add serde support for rpc messages

src/v/cluster/scheduling/leader_balancer.cc, src/v/cluster/scheduling/leader_balancer.h
Currently the leadership balancer has a throughput of 3-4 partitions/second. This is mainly due to it synchronously polling for metadata propagation after it issues the transfer request. This can add up to 20 seconds of time between each transfer request. This PR request aims to fix this by removing this wait and instead adding a mechanism to track the in flight request asynchronously. In testing this speeds up the leadership transfer rate to ~250 partitions/second.
Fixes #4359 
* none
=> Speed up leader balancer by removing unneeded waits

src/v/config/configuration.cc, src/v/raft/recovery_stm.cc, src/v/raft/recovery_throttle.h, src/v/raft/tests/mux_state_machine_fixture.h, src/v/raft/tests/raft_group_fixture.h, src/v/redpanda/application.cc
Made `recovery_throttle` runtime configurable
=> Made recovery throttle runtime configurable

tools/metadata_viewer/controller.py, tools/metadata_viewer/storage.py
This adds support for the feature update command in controller log decode, and also makes the general decode a little bit more robust by handling short reads at end of logs.
* none
=> tools: update metadata viewer for features command

src/v/cluster/members_manager.cc, src/v/cluster/tests/serialization_rt_test.cc, src/v/cluster/types.h
Adds support for various controller RPC message types.
* none
=> controller: add serde support for controller rpc messages

src/go/rpk/pkg/cli/cmd/redpanda/tune.go
Now rpk exits with code 1 each time the `rpk redpanda tune` command either fails to run, or it has a tuner enabled but it's not supported
Fixes #5186
Previous behavior: 
```
$ rpk redpanda tune swappiness
got an error while writing 1 to /proc/sys/vm/swappiness: open /proc/sys/vm/swappiness: read-only file system
TUNER                  APPLIED  ENABLED  SUPPORTED  ERROR                                                                               
swappiness             false    true     true       open                                                       
/proc/sys/vm/swappiness:                                   
read-only file system                                      
$ echo $?
0
$ rpk redpanda tune disk_irq
TUNER     APPLIED  ENABLED  SUPPORTED  ERROR …
```
=> rpk: change exit code when rpk tune fails

src/v/cluster/health_monitor_types.h, src/v/cluster/tests/serialization_rt_test.cc, src/v/cluster/types.h, src/v/serde/serde.h, src/v/serde/test/serde_test.cc
Adds serde support to several controller RPC message types.
* none
=> controller: add serde support to controller rpc message types

src/v/storage/tests/index_state_test.cc
accept out_of_bounds exception for corrupt data
accept out_of_bounds exception for corrupt data.
Fixes #5305.
- none
=> accept out_of_bounds exception for corrupt data

src/v/kafka/server/connection_context.cc
Signed-off-by: Jianyong Chen <balus@foxmail.com>
=> kafka/server: add missing placeholder in format string.

cmake/oss.cmake.in, tools/docker/README.md
backport #3223 #3236
fixes #5322 
* Switch Boost, CryptoPP, and HdrHistogram to official upstream repositories.
=> V21.11.x backport pr3223 pr3236

src/v/cloud_storage/cache_service.cc, src/v/cluster/config_manager.cc, src/v/cluster/feature_manager.cc, src/v/coproc/reconciliation_backend.cc, src/v/kafka/client/broker.h, src/v/kafka/server/handlers/handler.h, src/v/kafka/server/handlers/offset_for_leader_epoch.cc, src/v/kafka/server/handlers/topics/types.cc, src/v/serde/serde.h, src/v/ssx/sformat.h, src/v/storage/segment_utils.cc, src/v/storage/utils/transforming_reader.h, src/v/utils/fragmented_vector.h
i happened to be on a host (Rocky Linux 8.6) where only GCC-12 was available. but i wanted to build Redpanda on it to verify my changes. hence this PR.
for those who are curious. yes, in addition to the changes here, we need more (controversial) of them to get Redpanda compiled with GCC-12, among other things:
- `libzstd-static` does not exist.
- `install-dependencies.sh` does not understand "rocky"
- GCC does not allow shared a variable name with a type. but this pattern repeats itself in our source tree in couple places.
- `feature_schema` is considered "defined by not used" despite that it is actually used in `cluster/feature_table.cc`. probably we can move it to that source file as that is the only user of this definition.
- GCC believes that we fail to return a value in a …
=> Cleanups inspired by gcc

src/v/cluster/CMakeLists.txt, src/v/cluster/partition_balancer_planner.cc, src/v/cluster/partition_balancer_planner.h, src/v/cluster/partition_balancer_types.h, src/v/cluster/scheduling/constraints.cc, src/v/cluster/scheduling/constraints.h, src/v/cluster/tests/CMakeLists.txt, src/v/cluster/tests/partition_balancer_planner_fixture.h, src/v/cluster/tests/partition_balancer_planner_test.cc
=> Partition autobalancer planner

tests/rptest/tests/topic_recovery_test.py
=> Backport #5070 (disable flaky tests in TopicRecoveryTest)

src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h
Backport from pull request https://github.com/redpanda-data/redpanda/pull/5026
fixes #5439
=> [v22.1.x] Fix lost update consistency error

src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h
Backport from pull request https://github.com/redpanda-data/redpanda/pull/5027
fixes https://github.com/redpanda-data/redpanda/issues/5442
=> [v22.1.x] Make recovery from memory reset faster

src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h, src/v/cluster/tests/idempotency_tests.cc, src/v/utils/mutex.h
Backport from pull request https://github.com/redpanda-data/redpanda/pull/4669
fixes https://github.com/redpanda-data/redpanda/issues/5446
=> [v22.1.x]  linearize fast idempotency retries

tests/rptest/services/redpanda.py
This could fail spuriously if a process was just about
to terminate anyway: kill_process finds a PID, but then
fails to actually kill it because it died of its own
accord in the intervening time.
Addressing an instance seen in the wild here:
https://buildkite.com/redpanda/redpanda/builds/11895#0181b488-4efb-4529-8cd5-1256a64ec1ec
* none
=> test: make clean_node safer against shutdown/kill race

tests/java/e2e-verifiers/pom.xml
A commit from dependabot to update jackson version broke our build, let's revert for now.
=> Revert "build(deps): bump jackson-databind in /tests/java/e2e-verifiers"

src/v/serde/envelope.h, src/v/serde/envelope_for_each_field.h, src/v/serde/serde.h, src/v/serde/test/fuzz.cc, src/v/serde/test/serde_test.cc
for better readability.
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
=> serde: use concepts instead of type traits implemented using SFINAE

tests/rptest/tests/cluster_features_test.py
The test previously relied on the __REDPANDA_LOGICAL_VERSION environment
variable to simulate upgrades. This commit tweaks the tests that relied
on this to use the RedpandaInstaller to actually perform upgrades and
rollbacks.
* none
=> cluster_features_test: use RedpandaInstaller

src/go/rpk/pkg/api/admin/api_cluster.go
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5523.
Fixes https://github.com/redpanda-data/redpanda/issues/5527,
=> [v22.1.x] Fix json -> object mapping in cluster health

tests/rptest/tests/license_upgrade_test.py
- By a factor of the number of nodes in the cluster
=> rptest: Increase license_upgrade_test timeout

src/go/rpk/pkg/cli/cmd/group/seek.go
Remapping error that you get when trying to perform seek operations in non-empty groups from:
```
$ rpk group seek g1 --to start 
TOPIC      PARTITION  PRIOR-OFFSET  CURRENT-OFFSET  ERROR
test       0          -1            -1              UNKNOWN_MEMBER_ID: The coordinator is not aware of this member.
```
to
```
$ rpk group seek g1 --to start
TOPIC      PARTITION  PRIOR-OFFSET  CURRENT-OFFSET  ERROR
test       0          -1            -1              INVALID_OPERATION: seeking a non-empty group is not allowed.
```
Fixes #5277
=> rpk: remap group seek error on non-empty groups

.buildkite/hooks/pre-exit
cleanup leftover resources from cdt nightly run
* none
=> buildkite: add pre-exit script

.github/workflows/buildkite-slash-commands.yml, .github/workflows/slash-commands.yml
Slash commands for repeating CI tests and running codecov.
=> Add ci-repeat and test-codecov slash commands

.github/workflows/rpk-build.yml
Fixed wrong conditional in Packaging GH action job 
* none
=> gh: fix if conditional for rpk packaging

.github/workflows/rpk-build.yml
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5265.
=> [v21.11.x] gha/rpk: split darwin/linux rpk artifact uploading

.github/workflows/rpk-build.yml
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5265.
=> [v22.1.x] gha/rpk: split darwin/linux rpk artifact uploading

tests/rptest/scale_tests/node_operations_fuzzy_test.py
This parameterizes the fuzz test to do a partial upgrade before running through the workload. As we add more fuzzing, it seems like a good idea to incorporate intermediate states from during a rolling upgrade.
I considered using `MixedVersionWorkloadRunner` but opted not to since the fuzzer isn't currently deterministic in the type or direction of RPCs it sends.
=> node_operations_fuzzy_test: run mixed versions

tests/rptest/tests/archival_test.py, tests/rptest/tests/shadow_indexing_firewall_test.py, tests/rptest/util.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/4478
=> [v22.1.x] ducky: add si test with blocked s3

tests/rptest/clients/rpk.py, tests/rptest/tests/mirror_maker_test.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/4562
Fixes https://github.com/redpanda-data/redpanda/issues/4646
=> [v22.1.x] tests: scale mm2 consumer groups tests for CDT

tests/rptest/services/redpanda.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5569.
Fixes https://github.com/redpanda-data/redpanda/issues/5644,
=> [v21.11.x] test: improve pid regex for matching nodejs

tests/rptest/services/redpanda.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5569.
Fixes https://github.com/redpanda-data/redpanda/issues/5642,
=> [v22.1.x] test: improve pid regex for matching nodejs

cmake/oss.cmake.in
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5660.
Needs https://github.com/redpanda-data/vtools/pull/841 to merge first.
=> [v21.11.x] cmake: pin pex==2.1.100

cmake/oss.cmake.in
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5660.
Needs https://github.com/redpanda-data/vtools/pull/840 to merge first.
=> [v22.1.x] cmake: pin pex==2.1.100

src/v/cluster/partition_balancer_backend.h
Resolves situation in this comment
https://github.com/redpanda-data/redpanda/issues/5471#issuecomment-1194057612
FIxes: #5471 
Fixes: #5531
=> Partition_balancer: fix leader_id if leader not stable

tests/rptest/tests/acls_test.py
auth: Add an upgrade test for `enable_sasl` - the configuration for enabling sasl should work after the changes introduced in:
* #5292
This PR sits on top of:
* https://github.com/redpanda-data/redpanda/pull/5616
* none
=> auth: Redpanda enable_sasl upgrade test

tests/rptest/services/redpanda_installer.py
Previously when the RedpandaInstaller starts up, we would pull a list of
available released versions from Github. This is useful when looking for
valid versions to upgrade from (e.g. when using
`highest_from_prior_feature_version()`), but is not required for every
usage of the installer.
When running upgrade tests hundreds of times to snuff out flakiness, we
may end up needlessly hitting Github's API caps[1]. This commit updates
the behavior to only initializes the releases list when needed.
[1] https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting
Longer term, we should own our means of getting releases, whether it's persisted on disk somewhere and maintained in each release, or some S3-backed endpoint that gets the list of available downloads.
* none
=> redpanda_installer: don't initialize releases unless needed

src/v/net/conn_quota.cc
Shot in the dark trying to debug
https://github.com/redpanda-data/redpanda/issues/5575
* none
=> conn_quota: add leaving put trace message

src/v/archival/service.cc
=> [v22.1.x] archival: Always stop the ntp_archiver on shutdown

src/v/archival/service.cc
Backport #5700 
This required a few changes, most notably changing the `stop().finally()` to `stop.then()` to get the correct return type.
* none
=> [v21.11.x] archival: Always stop the ntp_archiver on shutdown

tests/rptest/tests/partition_movement_test.py
We need to wait for the new controller to be elected if the stopped node
was the one before. Retry policy in admin client would fail as all the
requested nodes would redirect request to old controller which is
unavailable.
Fixes: #5695
=> tests: fixed waiting for new controller to be elected

tests/rptest/clients/rpk.py
=> ducktape: rpk describe group add check for UNKNOWN_TOPIC_OR_PARTITION

cmake/oss.cmake.in
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5744.
=> [v21.11.x] cmake: install pex==2.1.100 not pex=2.1.00

src/v/cluster/feature_manager.cc, src/v/cluster/types.cc, src/v/json/validator.h, src/v/redpanda/admin/api-doc/features.json, src/v/redpanda/admin_server.cc, src/v/security/license.cc, src/v/security/license.h
Modify the license nag message & implement some review feedback that was added post merge of #5190
- None
=> Change license nag message and other small license related changes 

src/v/cluster/health_monitor_backend.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5756.
Fixes https://github.com/redpanda-data/redpanda/issues/5772,
=> [v22.1.x] cluster: fix shutdown hang in health_monitor_backend

src/v/kafka/client/client.cc, src/v/pandaproxy/schema_registry/seq_writer.cc, src/v/pandaproxy/schema_registry/service.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5729.
Fixes https://github.com/redpanda-data/redpanda/issues/5791,
=> [v21.11.x] kafka/client: improve list_offsets response error handling

src/v/kafka/client/client.cc, src/v/pandaproxy/schema_registry/seq_writer.cc, src/v/pandaproxy/schema_registry/service.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5729.
Fixes https://github.com/redpanda-data/redpanda/issues/5789,
=> [v22.1.x] kafka/client: improve list_offsets response error handling

src/v/compat/check.h, src/v/compat/json.h, src/v/compat/raft_compat.h, src/v/compat/raft_generator.h, src/v/compat/run.cc
Adds additional support for raft types into compat framework.
* None
=> Raft rpc compat updates

tests/rptest/clients/default.py, tests/rptest/clients/python_librdkafka.py, tests/rptest/scale_tests/ht_partition_movement_test.py, tests/rptest/scale_tests/node_operations_fuzzy_test.py, tests/rptest/services/failure_injector.py, tests/rptest/services/tc_netem.py, tests/rptest/tests/partition_move_interruption_test.py, tests/rptest/tests/partition_movement.py, tests/rptest/tests/partition_movement_upgrade_test.py
Added tests validating partition movement under high load generated using `kgo-verifier` and test executing partition movement while upgrading Redpanda cluster.
=> Partition movement additional tests

tests/rptest/tests/partition_balancer_test.py
The default 30s is reasonable when just waiting for traffic,
but this test is injecting failures that can cause consumer
groups to renegotiate: that can take longer.
Fixes https://github.com/redpanda-data/redpanda/issues/5806
None
* none
=> test: more permissive timeout in PartitionBalancerTest

src/v/cluster/types.cc, src/v/cluster/types.h, src/v/compat/begin_tx_compat.h, src/v/compat/begin_tx_generator.h, src/v/compat/cluster_json.h, src/v/compat/init_tm_tx_compat.h, src/v/compat/init_tm_tx_generator.h, src/v/compat/json.h, src/v/compat/model_json.h, src/v/compat/prepare_tx_compat.h, src/v/compat/prepare_tx_generator.h, src/v/compat/run.cc, src/v/compat/try_abort_compat.h, src/v/compat/try_abort_generator.h, src/v/model/tests/randoms.h, src/v/test_utils/randoms.h
Add compat types for
init_tm_tx
try_abort
begin_tx
prepare_tx
* None
* none
* none
* none
=> Add TX types to compat

src/v/cluster/partition_manager.cc, src/v/raft/consensus_utils.cc
After topic recovery redpanda initializes raft snapshot and then it
starts raft bootstrap. To create the snapshot we need to provide
last_included_index field. Consensus can truncate configuration up to
last_included_index (and also truncate offset translator state as well)
so when we creating the snapshot we're setting this value to
model::prev_offset(min-recovered-offset) to be safe.
The problem is that group_configuration with offset model::offset{} is
always added in c-tor of the configuration_manager. Also, the
model::prev_offset returns model::offset{} for offset 0. So if the log
downloaded starting from offset 0 we will create a snapshot with
last_indcluded_index set to model::offset{} which could lead to
conflict (we can't add this config to configuration_manager because the …
=> cluster: Fix snapshot initialization for topic recovery

src/go/rpk/pkg/cli/cmd/generate/prometheus.go
Now you can add `tls_config` to generated Prometheus scrape_config via `--ca-file`, `--cert-file` and `--key-file` flags:
```yaml
$ rpk generate prometheus-config --job-name redpanda-metrics-test --node-addrs 'localhost:9644' --ca-file ca.crt --key-file client.key --cert-file client.crt
- job_name: redpanda-metrics-test
static_configs:
- targets:
- localhost:9644
metrics_path: /public_metrics
tls_config:
ca_file: ca.crt
cert_file: client.crt
key_file: client.key
```
Fixes #5622
This behavior is completely optional, if the user doesn't set any tls-related flag, rpk won't generate the `tls_config` object 
* rpk: Now you can add `tls_config` to generated Prometheus scrape_config via `--ca-file`, `--cert-file` and `--key-file` flags.
=> rpk: add tls to generated prometheus scrape_config

.github/workflows/rpk-build.yml
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5815.
=> [v21.11.x] gha/rpk: fix upload of darwin binaries

.github/workflows/rpk-build.yml
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5815.
=> [v22.1.x] gha/rpk: fix upload of darwin binaries

src/v/cluster/partition_balancer_types.h, src/v/cluster/types.h, src/v/compat/acls_compat.h, src/v/compat/acls_generator.h, src/v/compat/check.h, src/v/compat/cluster_compat.h, src/v/compat/cluster_generator.h, src/v/compat/partition_balancer_compat.h, src/v/compat/partition_balancer_generator.h, src/v/compat/run.cc
Add some types to the compat testing framework.
* none
* none
* Short description of how this PR improves redpanda.
=> compat: Add some more types to the framework

tests/rptest/tests/partition_balancer_test.py
Rack awareness is forced in redpanda with soft allocation constraint. It
is done in such a way to make it possible to allocate partitions even if
there are not enough nodes in distinct racks. When the rack awareness
test was running the partition balancer was able to calculate movements
before the node that was previously stopped was reported alive. This way
a partition must have been allocated when two nodes were unavailable
when those two nodes happened to be on the same rack the rack awareness
constraint could not be held.
Fixes #5795
=> tests: wait for node to be reported alive in rack awareness test

src/v/cluster/types.h, src/v/compat/acls_compat.h, src/v/compat/acls_generator.h, src/v/compat/id_allocator_compat.h, src/v/compat/json.h, src/v/compat/partition_balancer_compat.h, src/v/compat/raft_compat.h, src/v/compat/raft_json.h, src/v/compat/run.cc, src/v/security/acl.h, src/v/utils/to_string.h
* none
* 
* none
* none
* none
=> compat: support cluster::delete_acls_request

src/v/cluster/types.h, src/v/compat/cluster_compat.h, src/v/compat/cluster_generator.h, src/v/compat/cluster_json.h, src/v/compat/run.cc, src/v/compat/tests/compat_test.cc
Add compat support for cluster::reconciliation_state_reply
* none
=> compat: add support for cluster::reconciliation_state_reply

src/v/cloud_storage/cache_service.h
fix writebehind on cache-put
partial backport of #5892
=> cloud_storage: use writebehind of 10 in cache service

tests/rptest/clients/rpk.py, tests/rptest/services/franz_go_verifiable_services.py, tests/rptest/tests/mirror_maker_test.py
Migrated mirror maker services to franz-go kgoverifier.
=> Migrated mirror maker 2 tests to use kgo verifier services

tests/rptest/tests/transactions_test.py
Change checks for simple transaction test + add logging for assert
Related: #5867 
* none
* none
=> [transaction] Compare record from input and output

tests/rptest/tests/end_to_end.py
Fixed passing in end to end test validation parameters.
=> Fixed passing parameters into end to end test

src/v/archival/ntp_archiver_service.cc, src/v/archival/ntp_archiver_service.h, src/v/archival/service.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5934.
Fixes https://github.com/redpanda-data/redpanda/issues/5941,
=> [v22.2.x] cloud_storage: adjust condition to remove archiver

src/v/redpanda/admin_server.cc
Added mapping from `rpc::errc` error codes to HTTP response codes.
=> admin_server: added missing mapping from rpc errors to http status codes

src/v/cluster/feature_manager.cc, src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_backend.h, src/v/cluster/health_monitor_frontend.cc, src/v/cluster/health_monitor_frontend.h, src/v/cluster/partition_balancer_backend.cc, src/v/config/configuration.cc, tests/rptest/tests/full_disk_test.py, tests/rptest/tests/metrics_reporter_test.py, tests/rptest/tests/partition_balancer_test.py
=> Backport of  #5922

src/v/config/configuration.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5840.
=> [v22.2.x] archival: tweak description of connection limit

src/v/cloud_storage/offset_translation_layer.cc, src/v/cloud_storage/offset_translation_layer.h, src/v/cloud_storage/partition_recovery_manager.cc, src/v/cloud_storage/partition_recovery_manager.h, src/v/storage/parser.cc, src/v/storage/parser.h
=> [v21.11.x] cloud_storage: interrupt downloading segment

src/v/cloud_storage/offset_translation_layer.cc, src/v/cloud_storage/offset_translation_layer.h, src/v/cloud_storage/partition_recovery_manager.cc, src/v/cloud_storage/partition_recovery_manager.h, src/v/storage/parser.cc, src/v/storage/parser.h
=> [v22.1.x] cloud_storage: interrupt downloading segment

.gitignore, src/go/k8s/Dockerfile, src/go/k8s/Dockerfile.dockerignore, src/go/k8s/Makefile, src/go/k8s/hack/install-cert-manager.sh, src/go/k8s/kuttl-helm-test.yaml, src/go/k8s/kuttl-test.yaml, src/go/k8s/kuttl-unstable-test.yaml
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5684.
=> [v22.2.x] Minor tweaks to k8s operator testing 

src/v/redpanda/admin_server.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5916.
=> [v22.2.x] admin_server: added missing mapping from rpc errors to http status codes

src/v/redpanda/application.cc, src/v/redpanda/application.h, src/v/resource_mgmt/cpu_scheduling.h, src/v/resource_mgmt/scheduling_groups_probe.h, src/v/ssx/metrics.h
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5893.
=> [v22.2.x] Publish runtime metric in seconds

src/v/cluster/feature_manager.cc
The _update_wait wait is conditional on !_updates.empty(). If
there is something in _updates we don't wait. Then in
do_maybe_update_active_version, we don't clear _updates
if we aren't the leader.
The only symptom is that we busy spin + if you have debug
logging switched on, you'll see a spew of "Checking for
active version update..." messages.
Fixes https://github.com/redpanda-data/redpanda/issues/5982
None
* none
=> cluster: fix spinning in feature manager

src/v/cluster/metadata_dissemination_service.cc, src/v/redpanda/application.cc
While looking at a user issue, seemed like having exact timestamp of full shutdown as seen by main would've been helpful to correlate timestamps.
* none
* none
* none
=> logging/observability: Additional log on shutdown.

src/v/cluster/metadata_dissemination_service.cc, src/v/redpanda/application.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6038.
=> [v22.2.x] logging/observability: Additional log on shutdown.

src/CMakeLists.txt, src/v/pandaproxy/schema_registry/CMakeLists.txt
Describe in plain language how this PR affects an end-user. What topic flags, configuration flags, command line flags, deprecation policies etc are added/changed. 
* none
=> build: link against Boost::iostreams explicitly 

src/go/rpk/pkg/api/admin/admin.go, tests/rptest/clients/rpk.py, tests/rptest/services/admin.py, tests/rptest/services/kafka_cli_consumer.py, tests/rptest/services/redpanda.py, tests/rptest/tests/cluster_config_test.py
Mostly derived from things that fell out of https://github.com/redpanda-data/redpanda/pull/5972
Fixes #6008 
Fixes #6033
Fixes #6010
None
* none
=> tests: various bugfixes

src/v/cluster/controller_backend.cc, src/v/cluster/partition.cc, src/v/cluster/partition.h, src/v/cluster/partition_manager.cc, src/v/cluster/partition_manager.h, src/v/cluster/types.h, src/v/compat/cluster_generator.h
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6042.
=> [v22.2.x] cluster: Remove remote_partition_properties

tests/rptest/services/redpanda.py, tests/rptest/tests/read_replica_e2e_test.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6060.
=> [v22.2.x] rptest: Improve read replica test

tests/rptest/services/admin_ops_fuzzer.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5993.
=> [v22.2.x] tests: improve AdminOperationsFuzzer.wait

src/v/cluster/feature_manager.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5983.
Fixes https://github.com/redpanda-data/redpanda/issues/6027,
=> [v22.2.x] cluster: fix spinning in feature manager

src/go/rpk/pkg/api/admin/admin.go, tests/rptest/clients/rpk.py, tests/rptest/services/admin.py, tests/rptest/services/kafka_cli_consumer.py, tests/rptest/services/redpanda.py, tests/rptest/tests/cluster_config_test.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6048.
Fixes https://github.com/redpanda-data/redpanda/issues/6065,
=> [v22.2.x] tests: various bugfixes

src/go/k8s/cmd/configurator/main.go, src/go/k8s/pkg/resources/statefulset.go, src/go/k8s/pkg/resources/statefulset_test.go, src/go/k8s/tests/e2e/additional-configuration/02-update-config.yaml
=> [v21.11.x] operator: add a flag to disable clearing of seeds servers in configurator image

src/v/raft/consensus.cc, src/v/storage/disk_log_impl.cc, src/v/storage/offset_to_filepos_consumer.h, src/v/storage/segment.cc, src/v/storage/segment.h, src/v/storage/segment_utils.cc, src/v/storage/segment_utils.h, src/v/storage/tests/storage_e2e_test.cc
Backport from pull requests:
- https://github.com/redpanda-data/redpanda/pull/5991
- https://github.com/redpanda-data/redpanda/pull/6071
- https://github.com/redpanda-data/redpanda/pull/6101
Fixes https://github.com/redpanda-data/redpanda/issues/6105,
=> [v22.2.x] Fixed truncation for compacted topics

tests/rptest/tests/cluster_config_test.py
Fixes https://github.com/redpanda-data/redpanda/issues/6095
Fixes https://github.com/redpanda-data/redpanda/issues/6010
None
* none
=> tests: make ClusterConfigTest more robust

tests/rptest/tests/offset_for_leader_epoch_test.py
Fixed `offset_for_leader_epoch_test` with waiting for all the nodes to
have up to date metadata about partition leaders.
Fixes: #6097
* none
=> tests: wait for all nodes to be aware of leaders

tests/rptest/tests/partition_movement.py
Waiting for all nodes when verifying the expected condition.
* none
=> tests/partition_movement: wait for all nodes when verifying move

src/v/cluster/config_manager.cc, src/v/cluster/controller.cc, src/v/cluster/service.cc, tests/rptest/tests/cluster_config_test.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/5680.
Fixes https://github.com/redpanda-data/redpanda/issues/5913,
=> [v22.1.x] cluster: fix config status write pre-check

tests/rptest/tests/offset_for_leader_epoch_test.py
Added waiting for all the leader values to be returned from offsets for
leader epoch tests.
Fixes: #6097
- none
=> tests: wait for all offsets in leader epoch tests

tests/rptest/tests/offset_for_leader_epoch_test.py
=> Made offsets for leader epoch tests to wait for all partitions

src/v/kafka/server/handlers/metadata.cc
In kafka metadata handler when guessing a kafka advertised listener we
returned a pointer to function local variable. When the variable was
deleted pointer was dangling.
Fixes: #6144
* none
=> k/metadata: fixed use after free in metadata handler
