src/v/archival/ntp_archiver_service.cc
Fixes #6192
none
* none
* none
* none
=> archival: Fix sync_local_state admin api

src/v/archival/ntp_archiver_service.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6194.
Fixes https://github.com/redpanda-data/redpanda/issues/6204,
=> [v22.2.x] archival: Fix sync_local_state admin api

src/v/archival/ntp_archiver_service.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6194.
Fixes https://github.com/redpanda-data/redpanda/issues/6208,
=> [v22.1.x] archival: Fix sync_local_state admin api

tests/rptest/tests/acls_test.py
This was broken by PR https://github.com/redpanda-data/redpanda/pull/5059
Fixes: https://github.com/redpanda-data/redpanda/issues/6221
None
* none
=> tests: update log allow list for acls_test

src/v/cluster/controller_backend.cc, src/v/raft/consensus.h, src/v/raft/types.h
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6166.
=> [v22.2.x] observability/raft: Simple logging fixes to aid debugging

tests/rptest/tests/topic_recovery_test.py, tests/rptest/utils/si_utils.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6085.
Fixes https://github.com/redpanda-data/redpanda/issues/6102,
=> [v22.2.x] cloud_storage/tests: filter out segments missing in manifest when accumulating non-data batch sizes

tests/rptest/tests/end_to_end.py
Fixed enabling shadow indexing  in `end_to_end.py` test.
* none
=> tests/end_to_end: fixed enabling si in end to end test

tests/rptest/tests/cluster_features_test.py, tests/rptest/tests/rpk_cluster_test.py
As stated in @rystsov 's PR #6003 some ducktape tests perform a common anti-pattern, waiting on a condition on a single node, then assuming that condition has been successfully met across all nodes.
For the license tests, the recurring bug was a check to see if a license exists, followed by a get_license() call. If the license exists on one node but not all 3, rpk may fail on the second request to obtain the license, in the case it asks a different node then it initially had queried, which can occur.
Although failures due to this haven't yet been directly observed in CI, the changes made to speed up `wait_until` (#6003) have triggered failures in the following patched tests.
=> CI fixes for license tests

src/v/compat/tests/compat_test.cc
before this change, we store a string into JSON document with storing
a view of it, namely, to store a pointer to it. but the string being
stored is local variable and is allocated on stack. after the
`if (value.IsString())` ends, the string is destroyed.
that's why we'd have "heap-use-after-free" reported by ASan when testing
using `ctest --output-on-failure -R test_compat_rpunit`.
per https://rapidjson.org/md_doc_tutorial.html#CreateString, we are
allowed to store the string by copying it.
after this change, an additional `doc` parameter is passed into
`perturb()` function, and the `doc` is used for getting the allocator
from it, so the stored string is alive as long as the `doc` is alive.
and the test passes without issues.
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
Describe in …
=> compat/test: store string in json by its value

tests/rptest/scale_tests/node_operations_fuzzy_test.py, tests/rptest/services/redpanda.py
In current version we improved handling errors in RPC layer. Removed
some not longer needed entries from log allow list.
=> tests: updated chaos tests log allow list

src/v/redpanda/application.cc
Transaction coordinator may depend on some underlying partition
operation to finish. In order to prevent the `tx__gateway_frontend` from
waiting for partition operation to finish before shutdown we stop all
the partitions in one of the first shutdown steps. This way all the
partition operations are interrupted before `tx_gateway_frontend` is
asked for shutdown.
Fixes: #6193
* none
=> redpanda: shutdown partitions before transaction coordinator

src/v/archival/service.cc
Convert add_ntp_archiver to coroutine and hold a gate.
Also, add a check that prevents code from using null pointer in case
if ntp is no longer available. Modify 'stop' method by invoking 'stop'
methods of archivers directly and after closing the gate. When the
gate is closed it's guaranteed that reconciliation is not running in the
background fiber so the race condition is prevented.
Fixes #6275
* none
* none
* none
* none
=> archival: Fix lifetime issue

.github/workflows/lint.yml
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6294.
=> [v22.2.x] gha/lint: run lint check on push to any branch

.github/workflows/lint.yml, src/v/kafka/protocol/tests/security_test.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6294.
=> [v22.1.x] gha/lint: run lint check on push to any branch

tests/rptest/services/redpanda.py, tests/rptest/services/storage.py, tests/rptest/tests/e2e_shadow_indexing_test.py, tests/rptest/util.py
Manual backport from pull request (the bot couldn't find the branch): https://github.com/redpanda-data/redpanda/pull/5812.
Fixes https://github.com/redpanda-data/redpanda/issues/6286,
=> [v22.2.x] test: use snapshots for detecting segment removal

src/v/redpanda/admin_server.cc
Fix the maintenance tests to unblock https://github.com/redpanda-data/redpanda/pull/6003
Fixes #6016
* none
=> Fix maintenance tests #6016

src/v/archival/service.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6292.
Fixes https://github.com/redpanda-data/redpanda/issues/6308,
=> [v22.2.x] archival: Fix lifetime issue

README.md, tests/rptest/services/redpanda_installer.py
Update URL for packages
* none
=> Update package download URL

src/v/cluster/health_monitor_backend.cc, src/v/cluster/members_table.cc, tests/rptest/services/admin.py, tests/rptest/services/redpanda_installer.py, tests/rptest/services/rolling_restarter.py, tests/rptest/tests/upgrade_test.py
Some changes that deflake the test or were helpful in debugging.
* none
Fixes https://github.com/redpanda-data/redpanda/issues/6291
Fixes https://github.com/redpanda-data/redpanda/issues/6249
Fixes https://github.com/redpanda-data/redpanda/issues/6333
Adds some logs to help further debug https://github.com/redpanda-data/redpanda/issues/6256
=> tests: deflake back-to-back upgrade test

tests/rptest/tests/compatibility/kafka_streams_test.py, tests/rptest/tests/e2e_shadow_indexing_test.py, tests/rptest/tests/pandaproxy_test.py, tests/rptest/tests/partition_balancer_test.py, tests/rptest/tests/partition_movement_test.py, tests/rptest/tests/prefix_truncate_recovery_test.py
Unmute tests which were stable last week
* none
=> Unmute tests which were stable last week

src/v/s3/client.cc
This is a quirky thing for AWS S3 to give us, but it has been seen to do so.  Treat these responses like a SlowDown, so that we will retry (and because the place we saw it in the field was a 503)
Fixes https://github.com/redpanda-data/redpanda/issues/6061
Not backporting because it's a log hygiene thing more than a correctness thing.
None
* none
=> cloud_storage: tolerate error responses with empty bodies

tests/rptest/tests/offset_for_leader_epoch_test.py
Made the offset for leader epoch test more robust and made it not vulnerable to leadership changes.
Fixes: #6409
* none
=> tests: made offset for leader epoch test more robust

src/v/kafka/server/handlers/offset_for_leader_epoch.cc, tests/rptest/services/admin.py, tests/rptest/tests/offset_for_leader_epoch_test.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6400.
Fixes https://github.com/redpanda-data/redpanda/issues/6404,
=> [v22.2.x] Fixed handling of `offsets_for_leader_epoch` request

src/v/cloud_storage/remote_partition.cc
Previously, when an exception was thrown on the read path,
partition_record_batch_reader_impl would simply reassing the reader
without stopping. This violates the shared reader's invariant that it
must be stopped before the destructor runs.
This patch corrects the mistake by also stopping the reader when handling
an unknown exception.
I tested this by inserting a throw on the read path and checking that the
assertion which checks for the reader being stopped does not fire.
* none
=> cloud_storage: stop shared reader on exception

src/go/k8s/controllers/redpanda/cluster_controller_common_test.go, src/go/k8s/controllers/redpanda/console_controller_test.go
Add retry during tests for updating console resources
Fixes #5400
=> k8s: retry when updating resources in console controller tests

src/v/kafka/server/handlers/offset_for_leader_epoch.cc, tests/rptest/services/admin.py, tests/rptest/tests/offset_for_leader_epoch_test.py
=> [v22.2.x] revert #6405

tests/rptest/tests/transactions_test.py
End phase for last transaction might be during shutdown. So looks like after restart redpanda lost it.
To fix this we will wait before shutdown end for last transaction. It means we can consume all data after produce phase
Fixes #6428
* none
* none
=> ducktape: Waiting last tx end before restart in upgrade_tx_test

.github/workflows/lint.yml, src/v/v8_engine/internal/tests/scripts/compile_timeout.js, src/v/v8_engine/internal/tests/scripts/run_timeout.js, src/v/v8_engine/internal/tests/scripts/sum.js, src/v/v8_engine/internal/tests/scripts/to_upper.js, tools/redpanda-gdb.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6472.
=> [v22.2.x] cleanup github workflow for linting

tests/rptest/services/kgo_verifier_services.py
This is to eliminate the possibility that this
join is a source of test runner timeouts.
Related: https://github.com/redpanda-data/redpanda/issues/6491
None
* none
=> tests: use timeout on status thread join

.github/workflows/lint.yml, src/v/v8_engine/internal/tests/scripts/compile_timeout.js, src/v/v8_engine/internal/tests/scripts/run_timeout.js, src/v/v8_engine/internal/tests/scripts/sum.js, src/v/v8_engine/internal/tests/scripts/to_upper.js, tools/redpanda-gdb.py
Manual backport of PR #6472
Only notable conflict was in 133af30
=> [v22.1.x] cleanup github workflow for linting

tests/rptest/clients/rpk.py, tests/rptest/services/admin_ops_fuzzer.py, tests/rptest/tests/partition_balancer_test.py
Backport from pull request: #6367
=> [v22.2.x] Fix PartitionBalancerTest.test_fuzz_admin_ops

src/go/k8s/pkg/resources/configuration/configuration.go, src/go/k8s/tests/e2e-unstable/centralized-configuration/03-redpanda-cluster-change.yaml, src/go/k8s/tests/e2e-unstable/centralized-configuration/05-assert.yaml, src/go/k8s/tests/e2e-unstable/centralized-configuration/05-probe.yaml, src/go/rpk/pkg/config/config.go, src/go/rpk/pkg/config/config_test.go, src/go/rpk/pkg/config/params_test.go, src/go/rpk/pkg/config/schema.go, src/go/rpk/pkg/config/weak.go, src/go/rpk/pkg/config/weak_test.go
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6519.
Fixes https://github.com/redpanda-data/redpanda/issues/6531,
=> [v22.2.x] Fix issue with changing metrics settings in centralized config

docs/rfcs/20200421_raft_recovery.md, src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/heartbeat_manager.cc, src/v/raft/types.h, src/v/raft/vote_stm.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6546.
=> [v22.2.x] Use cached term value when updating voter state

tests/rptest/clients/rpk.py, tests/rptest/tests/end_to_end.py, tests/rptest/tests/partition_movement_test.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6169.
Fixes https://github.com/redpanda-data/redpanda/issues/6554,
=> [v22.2.x] Fix 6132: retry topic creation on missing controller leader

src/v/raft/recovery_throttle.h, src/v/utils/tests/CMakeLists.txt, src/v/utils/tests/token_bucket_test.cc, src/v/utils/token_bucket.h
Token bucket algorithm will be used later in controller log rate limiting.
For it we need to refactor code and add method for additional usage
Refactor recovery throttle. Separate Token bucket algorithm to separate class
Add try_throttle method to Token bucket algorithm
Add support of burst throttling to Token bucket algorithm
=> Separate Token bucket algorithm from recovery throttle

src/v/cloud_storage/tests/remote_test.cc, src/v/storage/tests/concat_segment_reader_test.cc
Concatenated segment upload test has to be reduced in scope, because the imposter does not yet support byte expectations. 
It has to be extended to support byte expectations (it only supports strings as of now) to be able to assert that we are actually downloading a binary segment file.
In addition fixes the storage stop to use defer instead of stopping at the end of the test, so that if test fails we do not get extra assertion failures due to open storage.
fixes #6567 
* none
* none
=> cloud_storage/storage tests: fixes segment upload test

src/v/storage/batch_cache.cc
In batch_cache::put we did not notify the claimer on an early exit from the function, when a large batch was added, probably because this code path was added later, introducing the early return.
This means that if this code path is always/usually triggered, the background reclaimer won't start up and we may run low on free memory. Ultimately this memory can still be reclaimed but at a latency cost since it happens "inline" with an allocation request, likely during request processing.
Fix it by ensuring notify() is called on all paths.
Fixes #6573.
* none
* none
=> Ensure background reclaimer is always notified

src/v/cluster/controller_backend.cc
Cleaned up `controller_backend` logging. Prefixed each log entry with related `ntp`
=> Controller backend cleanup

src/v/cluster/tests/rm_stm_tests.cc
As we start relying more on the list of aborted txs spanning a given offset range, it is critical to have some regression tests so that we do not break the semantics by mistake.
This patch adds some common scenarios for aborted transactions spanning single and multiple segments.
This is purely a test change and makes no changes to the core tx logic.
* none
* none
=> tx/tests: unit test coverage for aborted tx

src/v/net/transport.h, src/v/rpc/reconnect_transport.h, src/v/rpc/transport.h
- adds high-level comments to the different transports
* none
=> net: non-functional cleanup

src/v/cluster/tx_gateway_frontend.cc
tx coordinator: make logs less noisy
* none
=> tx coordinator: make logs less noisy

src/v/kafka/client/client.cc
If a broken pipe happens, this will now result in the client reconnecting, rather than getting stuck in a broken state.
The error message that drove this fix:
```
2022-10-08T03:38:20.71154456Z stderr F ERROR 2022-10-08 03:38:20,711 [shard 2] pandaproxy - reply.h:109 - exception_reply: std::__1::system_error (error system:32, sendmsg: Broken pipe)
```
Which leads to a response of:
```
{"error_code":500,"message":"HTTP 500 Internal Server Error"}
```
* none
* Improve rebustness of Schema Registry and HTTP Proxy under `std::errc::broken_pipe`.
=> kafka/client: Mitigate `std::errc::broken_pipe`

src/v/kafka/client/client.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6687.
=> [v21.11.x] kafka/client: Mitigate `std::errc::broken_pipe`

src/v/kafka/client/client.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6687.
=> [v22.1.x] kafka/client: Mitigate `std::errc::broken_pipe`

src/v/kafka/client/client.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6687.
=> [v22.2.x] kafka/client: Mitigate `std::errc::broken_pipe`

src/v/serde/serde.h, src/v/serde/test/serde_test.cc, src/v/utils/tests/CMakeLists.txt, src/v/utils/tests/uuid_test.cc, src/v/utils/uuid.h
This is a follow-up PR to https://github.com/redpanda-data/redpanda/pull/6536
- makes underlying member private
- adds a static random generator
* none
=> uuid_t: follow-up changes

src/v/redpanda/admin_server.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6688.
Fixes https://github.com/redpanda-data/redpanda/issues/6706,
=> [v22.2.x] admin: urldecode logger

tests/rptest/services/rpk_consumer.py, tests/rptest/tests/connection_rate_limit_test.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6315.
Fixes https://github.com/redpanda-data/redpanda/issues/6700,
=> [v22.2.x] [ducktape] Fix connection rate test

src/v/model/tests/timeout_adl.cc
Test that `adl` is equivalent before and after the refactoring in #5051
Address https://github.com/redpanda-data/redpanda/pull/5051#pullrequestreview-1083073365
* none
* none
=> model: More tests for adl<model::timeout_clock::duration>

tests/rptest/services/redpanda.py
Manual backport of PR #6665 because there was a conflict in the cherry-pick. Resolved conflict by only taking the line that adds `RpkTool` and not taking`RpkRemoteTool` because it is not used in this commit.
* none
* none
=> [v22.2.x] save cluster config at end of tests

tests/rptest/services/redpanda.py
Manual backport of PR #6665 because there was a conflict in the cherry-pick. Resolved conflict by overriding `stop()` to export the cluster config before calling `super().stop()`.
* none
* none
=> [v22.1.x] save cluster config at end of tests

src/v/pandaproxy/reply.h
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6732.
=> [v22.2.x] pandaproxy: Improve log message for internal server error

tests/java/e2e-verifiers/pom.xml
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6731.
=> [v22.1.x] Remove log4j dependency

src/v/cloud_storage/cache_service.cc, src/v/cloud_storage/cache_service.h, src/v/cloud_storage/recursive_directory_walker.cc, src/v/cloud_storage/recursive_directory_walker.h, src/v/cloud_storage/tests/cache_test.cc, src/v/cloud_storage/tests/cache_test_fixture.h, src/v/cloud_storage/tests/directory_walker_test.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6533.
=> [v22.2.x] cloud_storage: cleanup empty directories on startup

tools/cmake_test.py
Before we were relying on seastar to decode backtrace for asan and
friends. For whatever reason that decoding isn't currently working. It
looks like the only reason that lsan wasn't doing this for us already
was that no symbolizer was available. Since we have one already with our
llvm build, we can just use that.
=> Symbolize sanitizer traces

tests/rptest/tests/partition_balancer_test.py
=> ducky: unmute fixed 5884 test

src/v/cloud_storage/cache_service.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6794.
Fixes https://github.com/redpanda-data/redpanda/issues/6805,
=> [v22.2.x] v/cloud_storage/cache_service.cc: fix a potential race condition

tests/rptest/tests/partition_balancer_test.py
=> tests: fixed missing import for ok_to_fail

cmake/oss.cmake.in
Updated seastar to include dns resolving fixes.
Fixes #5836
* none
=> cmake: updated seastar to include dns resolving fixes

src/v/redpanda/application.cc
This is required for yaml-cpp upgrade.
* none
* none
=> [v21.11.x] redpanda: Explicitly cast YAML::Node to bool

src/v/storage/batch_cache.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6574.
Fixes https://github.com/redpanda-data/redpanda/issues/6599,
=> [v22.2.x] Ensure background reclaimer is always notified

src/go/rpk/pkg/httpapi/httpapi.go, src/go/rpk/pkg/httpapi/httpapi_test.go
This will be used in a follow-up PR to do all of our JSON Http request.
* none
* none
=> rpk: introduce http api package

src/v/cluster/cluster_discovery.cc, src/v/cluster/cluster_discovery.h, src/v/cluster/controller.cc, src/v/cluster/controller.h, src/v/redpanda/application.cc, tests/rptest/services/redpanda.py, tests/rptest/tests/cluster_bootstrap_test.py
The original implementation of seeds-driven bootstrap had pieces of the various validation required for bootstrap strewn about startup. Because of this, I found it difficult to reason about what validations are done when, and what work may be duplicated, while reading through the code.
This commit puts all validations up front so we determine whether we are a founder immediately and use a cached value thereafter.
This is mostly addressing review comments on #6744.
Not sure this is the best structure (maybe some method names can be updated for clarity), but IMO it's a bit easier to reason about.
Describe in plain …
=> cluster_discovery: simplify fetching bootstrap info

src/v/utils/CMakeLists.txt, src/v/utils/directory_walker.cc, src/v/utils/directory_walker.h, src/v/utils/tests/directory_walker_test.cc
Move directory walker impl out of header.
=> Move directory walker impl out of header.

src/v/pandaproxy/rest/CMakeLists.txt, src/v/pandaproxy/rest/api.cc, src/v/pandaproxy/rest/api.h, src/v/pandaproxy/rest/fwd.h, src/v/pandaproxy/rest/handlers.cc, src/v/pandaproxy/rest/handlers.h, src/v/pandaproxy/rest/proxy.cc, src/v/pandaproxy/rest/proxy.h, src/v/pandaproxy/schema_registry/service.h, src/v/pandaproxy/schema_registry/test/CMakeLists.txt, src/v/pandaproxy/schema_registry/util.h, src/v/pandaproxy/server.h, src/v/pandaproxy/test/CMakeLists.txt, src/v/pandaproxy/test/one_shot.cc, src/v/pandaproxy/util.h, src/v/redpanda/application.cc, src/v/redpanda/application.h, tests/rptest/services/templates/redpanda.yaml, tests/rptest/tests/pandaproxy_test.py
=> Automatic Authentication for Schema Registry and HTTP Proxy - part3

tests/rptest/tests/rpk_start_test.py
This adds a test for the new seeds-driven bootstrap feature, as configured using `rpk redpanda start`.
=> tests: seeds-driven bootstrap with rpk

src/v/serde/test/serde_test.cc, src/v/storage/tests/storage_test_fixture.h, src/v/utils/CMakeLists.txt, src/v/utils/directory_walker.cc, src/v/utils/uuid.cc, src/v/utils/uuid.h
Simple test for compilation times
```
[nwatkins@fedora clang]$ cat ../../../src/v/utils/tests/uuid_test2.cc 
#include "utils/uuid.h"
#include <iostream>
void foo() {
uuid_t u;
uuid_t v;
uuid_t z{std::vector<uint8_t>()};
auto same = u == v;
(void)same;
std::cout << u;
}
```
```
**** Time summary:
Compilation (2 times):
Parsing (frontend):            3.1 s
Codegen & opts (backend):      0.4 s
**** Files that took longest to parse (compiler frontend):
2896 ms: src/v/utils/tests/CMakeFiles/uuid_test2.dir/uuid_test2.cc.o
159 ms: src/v/utils/tests/CMakeFiles/uuid_test2.dir/uuid_test2.cc.o
**** Files that took longest to codegen (compiler backend):
446 ms: src/v/utils/tests/CMakeFiles/uuid_test2.dir/uuid_test2.cc.o
```
```
**** Time summary:
Compilation (2 times):
Parsing (frontend): …
```
=> Reduce uuid implementation in header

src/v/cluster/rm_stm.cc, src/v/storage/snapshot.cc
Added log entry for each removed aborted transactions snapshots.
* none
=> c/rm_stm: added log entry for each removed aborted tx snapshots

tests/rptest/services/redpanda_installer.py
This commit adds some basic cleanup when failing to download, e.g. if the network was down while the test run. This previously borked the rest of the upgrade tests in a given test run, as it left remnants of the botched installation.
There are more improvements that can be done in this area (breaking up the single bash command that installs into several, handling failures on a per-node basis, etc), but they typically entail untangling some parallelism for dedicated noes. This commit implements a basic cleanup.
I tested this manually by running an upgrade test while disabling my Internet connection temporarily. Upon completion of the test, the `redpanda_installs` directory didn't have the botched files and I could run the test again successfully upon reenabling the connection.
Fixes #6787 …
=> redpanda_installer: clean up after download failure

src/go/rpk/pkg/cli/cmd/redpanda/config.go
Previously it was unclear what the arguments of `rpk config bootstrap` did. As an effort to support the new mode of bootstrap is underway, this commit cleans up some of the descriptions provided.
=> rpk: update bootstrap descriptions

tests/rptest/services/action_injector.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6989.
Fixes https://github.com/redpanda-data/redpanda/issues/7035,
=> [v22.1.x] Fix node selection for disruptive tests

tests/rptest/services/action_injector.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6989.
Fixes https://github.com/redpanda-data/redpanda/issues/7033,
=> [v22.2.x] Fix node selection for disruptive tests

src/v/kafka/client/fetcher.cc, src/v/kafka/client/types.h, src/v/kafka/protocol/CMakeLists.txt, src/v/kafka/protocol/flex_versions.cc, src/v/kafka/protocol/flex_versions.h, src/v/kafka/protocol/kafka_batch_adapter.h, src/v/kafka/protocol/request_reader.h, src/v/kafka/protocol/schemata/generator.py, src/v/kafka/protocol/types.cc, src/v/kafka/protocol/types.h, src/v/kafka/types.h, src/v/model/record_batch_reader.h, src/v/pandaproxy/parsing/from_chars.h, src/v/utils/named_type.h, src/v/utils/tests/vint_test.cc, src/v/utils/vint.cc, src/v/utils/vint.h, src/v/utils/vint_iostream.h
Reduces the size and compilation time of the kafka protocol intermediate library:
* library size: 464 MB -> 45 MB
* compile time: 133s -> 25s
Before
```
[nwatkins@fedora clang]$ CCACHE_DISABLE=1 time ninja v_kafka_protocol 
[134/134] Linking CXX static library lib/libv_v_kafka_protocol.a
1444.12user 60.24system 2:13.09elapsed 1130%CPU (0avgtext+0avgdata 1040448maxresident)k
[nwatkins@fedora clang]$ ls -lh lib/ | grep protocol
-rw-r--r--. 1 nwatkins nwatkins 464M Oct 31 13:16 libv_v_kafka_protocol.a
```
After
```
[nwatkins@fedora clang]$ CCACHE_DISABLE=1 time ninja v_kafka_protocol 
[4/4] Linking CXX static library lib/libv_v_kafka_protocol.a
37.90user 1.59system 0:25.00elapsed 157%CPU (0avgtext+0avgdata 1393288maxresident)k
[nwatkins@fedora clang]$ ls -lh lib/ | grep protocol
-rw-r--r--. …
```
=> kafka: reduce protocol library build size / time by up to 10x

src/v/storage/batch_cache.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6574.
Fixes https://github.com/redpanda-data/redpanda/issues/6597,
=> [v22.1.x] Ensure background reclaimer is always notified

src/v/cluster/tests/cluster_tests.cc
This could rarely fail when the check for the feature table snapshot executes before the newly started node has made it as far as writing it.
None
* none
=> cluster: tighten up test_feature_table_snapshots

tests/rptest/tests/topic_creation_test.py
This test needed redpanda 22.2.7 to get the fixed behavior
for remote writes disabled at topic level when enabled
at cluster level.
Added an azwait_feature_active to account for the
feature-driven config migration that was added
since the test was first written.
There is also a functional fix for the case highlighted by the test:
features: tweak cloud config upgrade logic
...to account for the case of systems where the cluster
setting for remote.write was True, but the topic
had an explicit False.
None
* none
=> tests: reinstate test_retention_upgrade_with_cluster_remote_write

src/v/cluster/bootstrap_backend.cc, src/v/cluster/bootstrap_backend.h, src/v/cluster/bootstrap_types.h, src/v/cluster/cluster_discovery.cc, src/v/cluster/raft0_utils.h
This PR contains some miscellaneous cleanup around the new bootstrap code including:
- adjusting log statements
- fixing up some comments
- using `coroutine::lambda`
There are no major functional changes in this PR.
=> bootstrap: miscellaneous cleanup

src/v/features/migrators/group_metadata.cc, src/v/features/migrators/group_metadata.h, src/v/storage/utils/transforming_reader.h
Fixes problematic lambda coroutines in the following sub-systems. Problems are potentially clobbered captured `this`.
```
net
rpc
utils
syschecks
v8_engine
test_utils
ssx
serde
security
features
config
bytes
compression
hashing
s3
http
model
storage
cloud_roles
```
=> Coroutine fixes

src/v/kafka/client/broker.h, src/v/kafka/client/client.cc, src/v/pandaproxy/rest/proxy.cc, src/v/pandaproxy/rest/proxy.h, src/v/pandaproxy/schema_registry/service.cc, src/v/pandaproxy/schema_registry/service.h, src/v/pandaproxy/server.h, tests/rptest/clients/kafka_cat.py, tests/rptest/clients/python_librdkafka_serde_client.py, tests/rptest/services/redpanda.py, tests/rptest/tests/pandaproxy_test.py, tests/rptest/tests/schema_registry_test.py
Add auto-auth tests, startup and shutdown improvements and fixes.
* none
* none
=> Schema Registry && REST Proxy: Auto-auth tests & fixes

tests/docker/Dockerfile, tests/rptest/services/librdkafka_test_case.py, tests/rptest/test_suite_quick.yml, tests/rptest/tests/librdkafka_test.py
Enabled librdkafka test suite executing against redpanda cluster.
=> Librdkafka ducktape

src/v/archival/ntp_archiver_service.cc, src/v/cloud_storage/partition_recovery_manager.cc, src/v/coproc/tests/fixtures/fiber_mock_fixture.cc, src/v/raft/tests/offset_translator_tests.cc, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h, src/v/rp_util/main.cc
A batch of lambda-coroutine conversions to not be coroutines.
=> De-coroutinize capturing lambdas

src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h, src/v/kafka/server/handlers/add_offsets_to_txn.cc, src/v/kafka/server/handlers/add_partitions_to_txn.cc, src/v/kafka/server/handlers/end_txn.cc, src/v/kafka/server/handlers/txn_offset_commit.cc, tests/rptest/tests/tx_abort_index_test.py
Added basic transaction logging in rm_stm.
=> Added some basic logging to rm_stm

src/v/cloud_storage/partition_recovery_manager.cc, src/v/cloud_storage/partition_recovery_manager.h, src/v/cloud_storage/recursive_directory_walker.cc, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment.h
Related: https://github.com/redpanda-data/redpanda/issues/7114
=> cloud_storage: remove capturing lambda coroutines

tests/rptest/services/librdkafka_test_case.py, tests/rptest/tests/librdkafka_test.py
Improved rendering errors for failed librdkafka tests. 
=> Librdkafka tests improvements

src/v/storage/disk_log_impl.cc, src/v/storage/disk_log_impl.h
This was unsafe. Adjacent segment compaction takes a write lock across the range of segments it will rerwite, but truncation does not hold a read lock continuously: it dips in and out of read locks inside segment member functions, so compaction can happen between the various steps in truncation.
The segment generation mechanism only protects us in certain cases, where the segment being truncated is modifed by compaction, and not in cases where the segment being truncated is e.g. closed by compaction.
This is a relatively ugly approach, but:
- Correctness: we take the lock early in both functions, before any segment locks are held, so there should not be risk of deadlocks, and it is fairly easy to reason about lock order.
- Performance: truncations are relatively rare events.  If they have …
=> storage: do not run adjacent compaction and truncation concurrently

src/v/cluster/bootstrap_backend.cc, src/v/cluster/bootstrap_backend.h, src/v/cluster/cluster_discovery.cc, src/v/cluster/cluster_discovery.h, src/v/cluster/topics_frontend.cc
Removed potentially problematic capturing lambda coroutines. 
=> cluster: removed capturing coroutine lambdas

src/go/rpk/pkg/cli/cmd/generate/prometheus.go
Now if we use a `--seed-addrs` that require TLS we can set the TLS configuration needed to use that node.
```
rpk generate prometheus-config --seed-addr 127.0.0.1:44471
invalid large response size 352518912 > limit 104857600; the first three bytes received appear to be a tls alert record for TLS v1.2; is this a plaintext connection speaking to a tls endpoint?
```
^ And there was no way to pass the TLS configuration.
```yaml
$ rpk generate prometheus-config --seed-addr 127.0.0.1:44471 --tls-enabled
- job_name: redpanda
static_configs:
- targets:
- 127.0.0.1:44471
metrics_path: /public_metrics
```
```yaml
$ rpk generate prometheus-config --seed-addr 127.0.0.1:44471 --tls-key ~/code/my-certs/certs/node.key --tls-cert ~/code/my-certs/certs/node.crt --tls-truststore …
```
=> rpk: add tls support to generate prometheus-config

src/v/cloud_storage/tests/remote_partition_test.cc, src/v/cloud_storage/tests/remote_segment_test.cc, src/v/cloud_storage/tests/remote_test.cc, src/v/coproc/script_context_backend.cc, src/v/pandaproxy/test/one_shot.cc, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h, src/v/rp_util/main.cc, src/v/s3/tests/s3_client_test.cc
* convert batch of coro-lambda into normal lambda
=> convert batch of coro-lambda into normal lambda

tests/rptest/services/tls.py
Openssl sometimes fails to generate an RSA key on our CI. It is still unclear why `openssl genrsa` reports this problem but the command has `exit status 1`. The openssl manpage does not say anything about the exit status for genrsa but according to the [FreeBSD manpage](https://man.openbsd.org/openssl.1), exit status 1 may refer to problems in parsing the command line arguments for S/MIME messages.
Additionally it is unclear if the error occurs because of disk space.
Therefore, this PR adds a retry loop to executing openssl commands and will output the disk space for the temporary directory upon exceptions.
Closes #7065 
* none
* none
=> tests/tls: add a retry loop

tests/rptest/tests/rpk_start_test.py
In systems that use systemd, one approach to generate the redpanda.yaml file is to use `rpk redpanda config bootstrap`. This commit adds a test for such a deployment with seeds-driven bootstrap.
=> rpk_start_test: test with `rpk redpanda config bootstrap`

src/go/rpk/pkg/tuners/irq/device_info.go, src/go/rpk/pkg/tuners/irq/device_info_test.go
rpk now will try to find the modalias file in the parent directories, we are adding this change because right now we search for irqs in:
`/sys/devices/device-name/block/block-name/`
And if no irqs are there, we get the device info from the same directory (by reading the modalias file).
The modalias could not be there and instead be in a parent directory:
`/sys/devices/device-name/modalias`
Fixes #6809
* none
Full verbose logs of an instance that reproduced the issue in 6809:
```
Looking for interface with '[172.31.8.73 172.31.8.73]' addresses
Checking 'lo' address '127.0.0.1/8'
Checking 'lo' address '::1/128'
Checking 'ens3' address '172.31.8.73/20'
Checking 'ens3' address 'fe80::8f1:f2ff:fe6a:9b05/64'
Creating disk IRQs tuner with mode 'def', cpu mask 'all', directories …
```
=> rpk/tuner: recursively find modalias in sys/device

docs/rfcs/20201208_fragmentation.md
Discusses some of the causes of fragmentation with a look at how
bad it can get.
Issue #211.
=> Add an RFC discussing the problem of fragmentation

src/v/cluster/rm_stm.cc
Changed `take_snapshot` method of `rm_stm` to use futures. 
Fixes #6768
=> c/rm_stm: refactored take snapshot to use futures

tests/rptest/services/redpanda_installer.py
We were previously using `rpk redpanda admin brokers list` directly without supplying hosts. This resulted in us unable to retry other nodes when the targeted node was not yet a part of the controller group.
It's less noise to hit the admin endpoint directly, so this commit updates the behavior to use the admin endpoint directly, as we commonly do in tests elsewhere.
Fixes #7137
=> redpanda_installer: retry version check on failure

src/v/kafka/client/client.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/7141.
Fixes https://github.com/redpanda-data/redpanda/issues/7234,
=> [v22.1.x] tests/pp: account for partition movement

src/v/kafka/client/client.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/7141.
Fixes https://github.com/redpanda-data/redpanda/issues/7236,
=> [v22.2.x] tests/pp: account for partition movement

src/v/kafka/client/client.cc
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/7141.
Fixes https://github.com/redpanda-data/redpanda/issues/7238,
=> [v21.11.x] tests/pp: account for partition movement

src/v/archival/ntp_archiver_service.cc
Fix edge cases using ss::when_all
Fixes: #7262
=> archival: fix abandoned exceptional future

src/v/archival/archival_policy.cc, src/v/archival/tests/ntp_archiver_test.cc
Backport from pull request: #7096
=> [v22.2.x] archival_policy: fix off-by-1 error for timeboxed uploads

src/v/archival/archival_policy.cc, src/v/archival/tests/ntp_archiver_test.cc
Backport from pull request: #7096
=> [v22.1.x] archival_policy: fix off-by-1 error for timeboxed uploads

tests/rptest/clients/kafka_cli_tools.py, tests/rptest/tests/e2e_shadow_indexing_test.py, tests/rptest/tests/retention_policy_test.py, tests/rptest/utils/si_utils.py
This PR introduces new functional and end-to-end tests for cloud retention.
* none
* none
=> cloud_storage: harden cloud retention testing

src/v/raft/configuration_manager.cc, src/v/raft/offset_translator.cc, src/v/storage/disk_log_impl.cc, src/v/storage/storage_resources.cc, src/v/storage/storage_resources.h
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6932.
=> [v22.2.x] storage: upper bound on frequency of snapshots

src/v/raft/recovery_throttle.h
Signed-off-by: Michal Maslanka <michal@redpanda.com>
=> r/recovery_throttle: fixed raft_recovery group name

tests/rptest/services/redpanda_installer.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/7203.
Fixes https://github.com/redpanda-data/redpanda/issues/7257,
=> [v22.2.x] redpanda_installer: retry version check on failure

tests/rptest/tests/partition_movement.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/7205.
Fixes https://github.com/redpanda-data/redpanda/issues/7335,
=> [v22.1.x] tests: retry getting partition assignments

src/go/rpk/pkg/tuners/irq/device_info.go, src/go/rpk/pkg/tuners/irq/device_info_test.go
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/7202.
Fixes https://github.com/redpanda-data/redpanda/issues/7338,
=> [v22.2.x] rpk/tuner: recursively find modalias in sys/device

tests/rptest/services/redpanda.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/7180.
Fixes https://github.com/redpanda-data/redpanda/issues/7305,
=> [v22.3.x] dt/redpanda: Improve write_node_conf_file

src/v/cloud_storage/tests/common_def.h, src/v/cluster/tests/partition_allocator_tests.cc, src/v/http/tests/framing_test.cc
llvm-15 is incoming - here are some small cleanups.
* none
* none
=> treewide: Small cleanups for llvm-15

tests/docker/Dockerfile, tests/rptest/scale_tests/cloud_retention_test.py, tests/rptest/scale_tests/franz_go_verifiable_test.py, tests/rptest/scale_tests/many_partitions_test.py, tests/rptest/services/kgo_verifier_services.py, tests/rptest/tests/e2e_topic_recovery_test.py, tests/rptest/tests/upgrade_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7263
=> [v22.3.x] Cloud retention stress test

src/v/cluster/members_backend.cc, src/v/cluster/members_backend.h, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h
When node count changes the unevenness error increases. Made the error
value not dependent from the number of nodes to prevent situation in
which rebalancing is interrupted when another node is added to the
cluster.
=> Post review rebalance on demand

.github/workflows/lint.yml, src/v/cluster/controller.h, src/v/cluster/members_backend.cc, src/v/cluster/members_backend.h, src/v/redpanda/admin/api-doc/partition.json, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h, tests/rptest/services/admin.py, tests/rptest/services/redpanda.py, tests/rptest/tests/scaling_up_test.py
Backport of: 
- https://github.com/redpanda-data/redpanda/pull/6814
- https://github.com/redpanda-data/redpanda/pull/7367
- https://github.com/redpanda-data/redpanda/pull/7388
=> [V22.2.x] Backport of #6814, #7367, #7388

src/v/cluster/members_backend.cc, src/v/cluster/members_backend.h, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/7388
=> [v22.3.x] Post review rebalance on demand

src/v/cluster/controller_backend.cc, tests/rptest/scale_tests/node_operations_fuzzy_test.py, tests/rptest/services/redpanda.py
Backport from pull request: https://github.com/redpanda-data/redpanda/pull/6223.
Fixes https://github.com/redpanda-data/redpanda/issues/7347,
=> [v22.2.x] Fixed logging abort_requested_exception with error severity

src/go/k8s/tests/e2e/endpoint-template/00-assert.yaml
Due to failing PostStart hook it seems that one of the Redpanda broker is in
degraded state and AdminAPI is not responsive. The Pod log collector does not
work if pod is in `PodInitializing` state.
To find more evidence what is happening kind export logs command was added.
It should be collected by the buildkite agent and served for later investigations.
* none
https://github.com/redpanda-data/redpanda/issues/7396
=> k8s: Gather k8s events from failed test

tools/dev_cluster.py, tools/panda.py
This tool can be used to easily spin up a local cluster without docker.
I'm finding this useful for development.
=> tools: add local cluster control tool

src/v/cluster/members_backend.cc, src/v/cluster/members_backend.h, tests/rptest/tests/scaling_up_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7408
=> [v22.3.x] Unevenness error stop condition improvements/fixes

src/v/kafka/server/handlers/alter_configs.cc, tests/rptest/clients/kcl.py, tests/rptest/tests/alter_topic_configuration_test.py
When topic property is not set in alter_configs request it is set to
default. We need to make an exception for replication factor to make sure
that it will not be accidentally changed to default when changing topic
configuration.
=> Fix alter topic configuration

tests/rptest/services/compatibility/example_runner.py
It's unclear why, but in a case where this threw from _worker, the test ended up hanging during teardown.
We don't need to throw from _worker: it is neater
to capture the exception and promptly raise it in
the test body via condition_met.
Fixes https://github.com/redpanda-data/redpanda/issues/7426
None
* none
=> tests: improve error handling in ExampleRunner

src/v/cloud_storage/offset_translation_layer.cc, src/v/cloud_storage/offset_translation_layer.h, src/v/cloud_storage/partition_recovery_manager.cc, src/v/cloud_storage/partition_recovery_manager.h, tests/rptest/tests/e2e_topic_recovery_test.py
=> [v22.2.x] cloud_storage: fix partition recovery with data-less segments

src/v/cluster/rm_stm.cc
In Kafka LSO denotes the first offset that is greater from the one for which all the transactions are resolved. Given the definition LSO is never negative.
Fixed `rm_stm` by applying the 'next offset' rule in the situation in which LSO is not initialized.
Fixes: #7438
=> c/rm_stm: fixed returning non initialized offset as LSO

src/v/redpanda/application.cc
=> [v22.2.x] redpanda: Recommend rpk config set

src/v/redpanda/application.cc
=> [v22.1.x] redpanda: Recommend rpk config set

tests/rptest/tests/license_upgrade_test.py
Reported failure:
```
File "/usr/local/lib/python3.10/dist-packages/ducktape/tests/runner_client.py", line 135, in run
data = self.run_test()
File "/usr/local/lib/python3.10/dist-packages/ducktape/tests/runner_client.py", line 227, in run_test
return self.test_context.function(self.test)
File "/root/tests/rptest/services/cluster.py", line 35, in wrapped
r = f(self, *args, **kwargs)
File "/root/tests/rptest/tests/license_upgrade_test.py", line 148, in test_license_upgrade
assert license is not None and license['loaded'] is True
AssertionError
```
License is not observed post upgrade due to the fact that the query occurs on a follower in the case the follower hasn't yet caught up completely with the controller log.
Fixes: #7363
=> Fix failing flaky license_migration_test

tests/rptest/tests/license_upgrade_test.py
Backport of:
- https://github.com/redpanda-data/redpanda/pull/7312 (Just the unit test commit)
- https://github.com/redpanda-data/redpanda/pull/7478
=> [v22.3.x] Backport license upgrade test

src/v/config/base_property.h, src/v/config/bounded_property.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/config/tests/bounded_property_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7244
=> [v22.3.x] config: force an odd value for default_topic_replications

tests/rptest/services/compatibility/example_runner.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7427
Fixes https://github.com/redpanda-data/redpanda/issues/7463,
=> [v22.3.x] tests: improve error handling in ExampleRunner

src/v/archival/ntp_archiver_service.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7468
Fixes https://github.com/redpanda-data/redpanda/issues/7479,
=> [v22.3.x] archival: downgrade upload failure from ERR to WARN

src/v/archival/ntp_archiver_service.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7468
Fixes https://github.com/redpanda-data/redpanda/issues/7481,
=> [v22.2.x] archival: downgrade upload failure from ERR to WARN

tests/rptest/services/compatibility/example_runner.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7427
Fixes https://github.com/redpanda-data/redpanda/issues/7461,
=> [v22.2.x] tests: improve error handling in ExampleRunner

src/v/kafka/server/handlers/describe_configs.cc, src/v/kafka/server/tests/alter_config_test.cc, tests/rptest/clients/kafka_cli_tools.py, tests/rptest/tests/describe_topics_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/6259
Fixes https://github.com/redpanda-data/redpanda/issues/7487,
=> [v22.2.x] Do not describe replication factor and partition count in describe configs result

tests/rptest/tests/consumer_group_test.py
=> [v22.2.x] Fixed `test_dead_group_recovery`

src/go/k8s/config/rbac/role.yaml, src/go/k8s/controllers/redpanda/cluster_controller.go, src/go/k8s/helm-chart/charts/redpanda-operator/templates/clusterrole.yaml
Backport of PR https://github.com/redpanda-data/redpanda/pull/7484
=> [v22.3.x] k8s: clone generated rbac to helm chart

tests/rptest/tests/end_to_end.py
=> [v22.1.x] tests/end_to_end: fixed enabling si in end to end test

src/go/rpk/pkg/cli/cmd/redpanda/admin/brokers/brokers.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/7474
=> [v22.3.x] rpk: avoid decommissioning a node if its in maintenance mode

src/go/rpk/pkg/cli/cmd/redpanda/admin/brokers/brokers.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/7474
=> [v22.2.x] rpk: avoid decommissioning a node if its in maintenance mode

src/go/rpk/pkg/cli/cmd/cluster/config/import.go, src/go/rpk/pkg/cli/cmd/cluster/config/set.go, tests/rptest/tests/cluster_config_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7421
Fixes https://github.com/redpanda-data/redpanda/issues/7514,
=> [v22.2.x] rpk: encourage users to restart nodes on config change if required

src/go/rpk/pkg/cli/cmd/cluster/config/import.go, src/go/rpk/pkg/cli/cmd/cluster/config/set.go, tests/rptest/tests/cluster_config_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7421
Fixes https://github.com/redpanda-data/redpanda/issues/7516,
=> [v22.3.x] rpk: encourage users to restart nodes on config change if required

src/go/rpk/pkg/cli/cmd/redpanda/admin/brokers/brokers.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/7518
=> [v22.3.x] rpk: add nil check for maintenance mode

src/go/rpk/pkg/cli/cmd/redpanda/admin/brokers/brokers.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/7518
=> [v22.2.x] rpk: add nil check for maintenance mode

src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/tests/remote_partition_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7502
=> [v22.3.x] cloud_storage: Make read-path resilient to inconsistencies

src/go/rpk/pkg/api/admin/api_node_config.go
=> rpk: Reword godoc to match guidance style

tests/rptest/tests/nodes_decommissioning_test.py
This test could end up trying to use a decommed node's admin API to query the status of the cluster, and fail on too many 503s.
Fixes https://github.com/redpanda-data/redpanda/issues/6721
None
* none
=> test: make test_recommissioning_one_of_decommissioned_nodes more robust

src/go/k8s/pkg/console/sasl.go
When errors could happen in sasl.go code it was unknown which line was causing the error. The duplicated code was put on separated function, so that context could be added to the error.
When reconciliation in operator would error, then it would be very hard to know which line causes error.
* none
=> k8s: Add context to error messages

tests/rptest/services/redpanda.py, tests/rptest/tests/topic_recovery_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7549
Fixes https://github.com/redpanda-data/redpanda/issues/7563,
=> [v22.2.x] Wait for cluster membership in topic_recovery_test

src/go/k8s/controllers/redpanda/suite_test.go
To make debugging of the AdminAPI tests easier, add logging to the mock functions.
Associated with #7395 
N/A
* none
=> operator: add mockAdminAPI logging

tests/rptest/services/redpanda.py, tests/rptest/tests/topic_recovery_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7549
Fixes https://github.com/redpanda-data/redpanda/issues/7565,
=> [v22.3.x] Wait for cluster membership in topic_recovery_test

tests/rptest/tests/retention_policy_test.py
The test previously waited 5s for local segments to be removed, even though by default, we can end up backing off our segment uploads (thereby preventing segment removal) for up to 10s if the segments were closed after some backoffs. This commit bumps the timeout to something more suitable for the default value.
Fixes #7400
=> tests: increase timeout for segment removal

src/v/kafka/server/handlers/alter_configs.cc, tests/rptest/clients/kcl.py, tests/rptest/tests/alter_topic_configuration_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7429
=> [v22.3.x] Fix alter topic configuration

tests/rptest/services/redpanda.py
We previously explicitly set these to `debug` to have more logs and make it easier to debug issues. Now that CI runs with trace logs by default, that intention is lost, and we end up with less logging.
This commit returns the archival/cloud_storage subsystems to the default, and leaves the remaining explicitly set subsystems, as they tend to be much chattier.
=> tests: use default logging for archival/cloud_storage

src/v/cluster/rm_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7458
Fixes https://github.com/redpanda-data/redpanda/issues/7597,
=> [v22.3.x] c/rm_stm: fixed returning non initialized offset as LSO

src/v/cluster/rm_stm.cc, src/v/kafka/server/handlers/fetch.cc, src/v/kafka/server/handlers/list_offsets.cc, src/v/kafka/server/materialized_partition.h, src/v/kafka/server/partition_proxy.h, src/v/kafka/server/replicated_partition.h, src/v/kafka/server/tests/fetch_test.cc, src/v/model/fundamental.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/7544
Fixes https://github.com/redpanda-data/redpanda/issues/7599,
=> [v22.3.x] transactions: preserve monotonicity of LSO

tests/rptest/tests/node_id_assignment_test.py
This introduces a test that adds several nodes in parallel, verifying that all nodes are assigned unique node IDs.
=> tests: assign multiple node IDs in parallel

src/go/rpk/pkg/cli/cmd/cloud/auth/auth.go, src/go/rpk/pkg/cli/cmd/cloud/byoc/install.go, src/go/rpk/pkg/cli/cmd/root.go, src/go/rpk/pkg/plugin/plugin.go
This PR Includes:
* Changing the Auth0 URL.
* A patch in the plugin code to avoid installing a managed plugin to the root command.
* Trimming whitespace when we prompt for the clientID and clientSecret.
* Removing context timeout when installing the plugin, slow connections might suffer from this.
=> rpk cloud patch

src/go/rpk/pkg/cli/cmd/cloud/auth/auth.go, src/go/rpk/pkg/cli/cmd/cloud/byoc/install.go, src/go/rpk/pkg/cli/cmd/root.go, src/go/rpk/pkg/plugin/plugin.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/7596
=> [v22.3.x] rpk cloud patch

src/v/cluster/partition.cc, src/v/cluster/partition.h, src/v/cluster/partition_manager.cc, src/v/cluster/partition_manager.h, src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h, src/v/cluster/tests/idempotency_tests.cc, src/v/cluster/tests/rm_stm_tests.cc, src/v/cluster/tests/tx_compaction_tests.cc, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/application.cc, tests/rptest/tests/transactions_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7057
Fixes https://github.com/redpanda-data/redpanda/issues/7617,
=> [v22.3.x] [transaction] Clear old pids from rm_stm state in overflow

src/v/cloud_storage/remote.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7630
Fixes https://github.com/redpanda-data/redpanda/issues/7631,
=> [v22.3.x] cloud_storage: Remove assertion from delete_object

src/v/http/client.h, src/v/http/tests/http_client_test.cc
just a small cleanup of includes
* none
=> Http/client headers: small cleanup

src/v/cloud_storage/tests/remote_partition_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7634
Fixes https://github.com/redpanda-data/redpanda/issues/7635,
=> [v22.3.x] cloud_storage: Fix remote_partition randomized test

src/v/cluster/members_backend.cc, src/v/cluster/members_manager.h, tests/rptest/tests/nodes_decommissioning_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7533
Fixes https://github.com/redpanda-data/redpanda/issues/7575,
=> [v22.3.x] Fixed finishing recommissioning update

tests/rptest/tests/nodes_decommissioning_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7509
Fixes https://github.com/redpanda-data/redpanda/issues/7545,
=> [v22.3.x] test: make test_recommissioning_one_of_decommissioned_nodes more robust

src/v/cloud_storage/tests/remote_partition_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7634
=> [v22.2.x] cloud_storage: Fix remote_partition randomized test

src/v/storage/offset_to_filepos.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7655
=> [v22.3.x] storage: protect optional access

tests/rptest/services/openmessaging_benchmark_configs.py
It appears that the leadership balancer is kicking in during the benchmark. This patch increases the warmup time to 5 mins in the hopes that the partition assignment stabilizes by then and the cluster reaches a stable state.
- [] none - not a bug fix
- [] none - issue does not exist in previous branches
=> omb/perf: increase warmup time for perf run

tests/rptest/services/openmessaging_benchmark_configs.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7686
=> [v22.3.x] omb/perf: increase warmup time for perf run

src/v/kafka/server/handlers/describe_configs.cc, tests/rptest/tests/topic_creation_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7602
Fixes https://github.com/redpanda-data/redpanda/issues/7659,
=> [v22.3.x] kafka: report default-matching SI topic properties as DEFAULT_CONFIG

src/v/archival/ntp_archiver_service.cc, src/v/archival/ntp_archiver_service.h, src/v/archival/service.cc, src/v/cloud_storage/remote.cc, src/v/cloud_storage/remote.h, src/v/s3/client.cc, src/v/s3/client.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/7666
=> [v22.3.x] archival: Improve AWS S3 object tags

.yapfignore, tests/rptest/services/redpanda.py
Changes useful for collect coredumps in ducktape. Tested on FC38 segfaults are now coredumping to systemd-coredump and then accessible via coredumpctl.
=> ducktape: configure asan to collect coredump

src/v/storage/log_reader.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7633
Fixes https://github.com/redpanda-data/redpanda/issues/7699,
=> [v22.3.x] storage: assert out on EIO in read

tests/rptest/tests/scaling_up_test.py
Changed the condition validating if partition replicas are rebalanced to include the range boundaries.
Fixes: #7418
* none
=> tests: adjusted check of rebalanced partitions to include range ends

tests/rptest/tests/compaction_end_to_end_test.py
PR #7607 bumped timeout for data generation and
compaction but turns out on ARM CDT, consumption
is slow too.
Extends the timeout to consumer validation.
Note: We don't have DEBUG/TRACE logs to validate if the consumer is
making progress but given this only fails occasionally it probably is just
very close to the existing timeout.
Fixes #7138
=> ducktape: extend timeout to consumer validation.

.github/workflows/render-pr-body-release-notes.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/7718
=> [v22.3.x] gha: workflow to render pr body release notes

.github/workflows/render-pr-body-release-notes.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/7718
=> [v22.2.x] gha: workflow to render pr body release notes

.github/workflows/render-pr-body-release-notes.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/7718
=> [v22.1.x] gha: workflow to render pr body release notes

.github/workflows/render-draft-release-notes.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/7722
=> [v22.3.x] gha: workflow to render draft release notes

.github/workflows/render-draft-release-notes.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/7722
=> [v22.2.x] gha: workflow to render draft release notes

.github/workflows/render-draft-release-notes.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/7722
=> [v22.1.x] gha: workflow to render draft release notes

src/go/rpk/.goreleaser.yaml
Backport of PR https://github.com/redpanda-data/redpanda/pull/7728
=> [v22.3.x] rpk/pkg: bring back linux build and tweak the archive name template

src/v/cluster/errc.h, src/v/cluster/topics_frontend.cc, src/v/kafka/server/errors.h, src/v/storage/ntp_config.h, tests/rptest/clients/kafka_cli_tools.py, tests/rptest/tests/e2e_shadow_indexing_test.py
This commit updates the handling retention getters to handle the `is_disabled()` case incurred when provided with a negative value.
Fixes https://github.com/redpanda-data/redpanda/issues/7748
* Redpanda will now correctly honor negative values to mean an infinite value for the `retention.ms` and `retention.bytes` topic configurations.
=> cloud_storage: handle infinite retention tristates

src/go/k8s/pkg/resources/statefulset.go
The redpanda container user and group id changed from 101 to 999. This caused a permissions issue where the redpanda.yaml was owned by 101 (rw-------) and redpanda was unable to read it.
This change ensures the configurator and redpanda will use the same ids.
* none
=> operator: set redpanda uid and gid

src/v/kafka/client/broker.cc, src/v/kafka/client/client.cc, tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7735
Minor conflict in the ducktape tests
=> [v22.3.x] kafka/client: Improve connection error handling

src/v/redpanda/application.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7744
=> [v22.3.x] schema_registry: Don't batch writes unless explictly configured to

src/v/redpanda/application.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7744
=> [v22.2.x] schema_registry: Don't batch writes unless explictly configured to

src/v/cluster/tx_gateway_frontend.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7762
Fixes https://github.com/redpanda-data/redpanda/issues/7780,
=> [v22.3.x] Fix incorrect txn log level

src/v/redpanda/application.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7744
=> [v22.1.x] schema_registry: Don't batch writes unless explictly configured to

src/go/k8s/pkg/resources/statefulset.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/7771
=> [v22.3.x] operator: set redpanda uid and gid

tests/rptest/tests/partition_balancer_test.py
Investigation https://github.com/redpanda-data/redpanda/issues/7020#issuecomment-1344356285
Fixes #7020 
* none
=> ducktape: Add log_allow_list to test_fuzz_admin_ops

src/v/features/feature_table.h, src/v/features/tests/feature_table_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7729
=> [v22.3.x] c/feature_table: fixed the tx_stm_cache feature flag

tests/rptest/services/redpanda_installer.py
This can happen during releases, when the release exists in github but the package doesn't, either because the release is in flight or because something went wrong.
We should not fail all our CI runs when the release is in this state: let it skip back up to 2 versions to find one that has packages available for upgrade tests.
None
* none
=> tests: improve package search to ignore releases with no tarball

tests/rptest/tests/connection_rate_limit_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7648
Fixes https://github.com/redpanda-data/redpanda/issues/7793,
=> [v22.3.x] ducktape: Change diff for connection_rate_test

tests/rptest/tests/connection_rate_limit_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7648
Fixes https://github.com/redpanda-data/redpanda/issues/7795,
=> [v22.2.x] ducktape: Change diff for connection_rate_test

src/v/cloud_storage_clients/client.h, src/v/cloud_storage_clients/s3_client.cc, src/v/cloud_storage_clients/s3_client.h, src/v/cloud_storage_clients/test_client/s3_test_client_main.cc, src/v/cloud_storage_clients/tests/s3_client_test.cc
Implementation for S3 DeleteObjects
The api accepts only 1000 keys - like s3 and returns a list of keys for which deletion was not possible.
The precondition is checked with an assert.
Note that keys not found in a bucket are reported as a success by s3, so they will not appear in the returned list
* none
=> s3::client: implement DeleteObjects request

src/v/cluster/tm_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7806
=> [v22.3.x] transactions: Lower tx transferring log severity

src/v/cluster/members_table.cc, tests/rptest/tests/nodes_decommissioning_test.py
Issue #7370 is fixed on dev by a wide refactor that isn't ideal for backporting. This commit is a lighter-weight fix for the issue.
This commit ignores removed nodes when considering whether nodes can be placed into maintenance mode, matching the behavior on dev.
Fixes #7370
=> [v22.2.x] cluster: ignore removed nodes for maintenance commands

src/v/cloud_storage/materialized_segments.cc, src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_partition.h, src/v/cloud_storage/types.h
This PR contains minor fixes for merged #7366 pull-request.
* none
=> cloud_storage: Folloup for #7366

src/v/cluster/members_manager.cc, src/v/cluster/topics_frontend.cc, tests/rptest/tests/nodes_decommissioning_test.py, tests/rptest/tests/random_node_operations_test.py, tests/rptest/tests/scaling_up_test.py
Controller uses optimistic approach to provide correctness when
executing commands i.e. result of the operation is determined when
records are applied to the state machine. This cause a problem when
an operation is retried mulitple times as it may cause the controller
log to grow really fast. Added preliminary validation to topics frontend
to prevent controller log from growing.
Fixes #7816 
- fixes pathological case in which a controller log may grow very large when partition op is being retried
=> Improved validation in topics frontend

src/go/k8s/pkg/resources/statefulset.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/7771
=> [v22.1.x] operator: set redpanda uid and gid

src/go/k8s/pkg/resources/statefulset.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/7771
=> [v22.2.x] operator: set redpanda uid and gid

src/go/k8s/controllers/redpanda/cluster_controller.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/7828
Fixes https://github.com/redpanda-data/redpanda/issues/7837,
=> [v22.3.x] k8s: Fix wrong WithValues invocation

tests/rptest/tests/scaling_up_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7698
Fixes https://github.com/redpanda-data/redpanda/issues/7726,
=> [v22.3.x] tests: adjusted check of rebalanced partitions to include range ends

src/v/cluster/members_manager.cc, src/v/cluster/members_table.cc, src/v/cluster/members_table.h, src/v/cluster/topics_frontend.cc, tests/rptest/tests/end_to_end.py, tests/rptest/tests/node_id_assignment_test.py, tests/rptest/tests/nodes_decommissioning_test.py, tests/rptest/tests/partition_balancer_test.py, tests/rptest/tests/random_node_operations_test.py, tests/rptest/tests/scaling_up_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7789
Backport of PR https://github.com/redpanda-data/redpanda/pull/7821
=> [V22.3.x] Backport of #7789, #7821

src/v/redpanda/tests/fixture.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/7815
=> [v22.3.x] archival: set test reconciliation interval

src/go/k8s/tests/e2e/superusers-prefix/01-assert.yaml
Fix minor typo in superuser-prefix test
* None
=> operator: fix typo in e2e test

src/v/cluster/tests/autocreate_test.cc, src/v/kafka/server/handlers/create_topics.cc, src/v/kafka/server/handlers/metadata.cc, src/v/kafka/server/handlers/topics/topic_utils.cc, src/v/kafka/server/handlers/topics/topic_utils.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/7731
=> [v22.3.x] cluster: wait for leadership with auto create

src/v/cloud_storage/materialized_segments.cc, src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_partition.h, src/v/cloud_storage/types.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/7674
=> [v22.3.x] cloud_storage: Folloup for #7366

src/v/cloud_storage/materialized_segments.cc, src/v/cloud_storage/materialized_segments.h, src/v/utils/retry_chain_node.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7844
=> [v22.3.x] Fix race condition in the eviction loop

src/v/redpanda/tests/fixture.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/7815
=> [v22.2.x] archival: set test reconciliation interval

tests/docker/Dockerfile
Local testing indicates this is all that is needed for ASAN to pick up the llvm-symbolizer and decode ASAN backtrace reports.
Signed-off-by: Noah Watkins <noahwatkins@gmail.com>
* none
=> ducktape: add llvm-symbolizer to ducktape image

src/v/cluster/tm_stm.cc, src/v/cluster/tm_stm.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/7807
Fixes https://github.com/redpanda-data/redpanda/issues/7905
=> [v22.3.x] Fix InvalidTxnState on adding partition or group

tools/dev_cluster.py
dev_cluster: support cores options and graceful ctrl-c shutdown
* none
=> dev_cluster: support cores options and graceful ctrl-c shutdown

src/v/cluster/members_backend.cc, src/v/cluster/members_manager.h, tests/rptest/tests/nodes_decommissioning_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7533
Fixes https://github.com/redpanda-data/redpanda/issues/7573,
=> [v22.2.x] Fixed finishing recommissioning update

tools/dev_cluster.py
...and default CPU count to a fair share of the CPUs on the machine.
None
* none
=> tools: enable -- passing extra args into dev_cluster

src/v/cloud_storage/tests/remote_partition_test.cc
=> [v22.3.x] cloud_storage: Set limits on segments and readers in tests

src/v/cloud_storage/remote.cc, src/v/cluster/members_backend.cc, src/v/cluster/members_manager.h, src/v/cluster/topics_frontend.cc, src/v/kafka/client/broker.cc, src/v/kafka/client/client.cc, src/v/net/connection.cc, src/v/net/connection.h, src/v/redpanda/tests/fixture.h, tests/rptest/tests/nodes_decommissioning_test.py, tests/rptest/tests/scaling_up_test.py, tests/rptest/tests/schema_registry_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7789
=> [V22.2.x] Improved validation in topics frontend

tests/rptest/tests/nodes_decommissioning_test.py
Failing very frequently https://github.com/redpanda-data/redpanda/issues/7874
* none
=> test: mark test ok_to_fail

tests/rptest/tests/controller_erase_test.py
In test we do 4 leadership transfers, so it should creates 4 segments for controller log. And we should count also first segment for initial leader after start.
Previously we assert wrong expected segment count, but sometimes it was true, because we stop victim node right after last transfer, so final segment might be not replicated for victim node
Fixes #7558 
-->
* none
=> ducktape: Fix assert for controller_erase_test

src/v/cluster/tm_stm.cc
=> tm_stm: remove duplicated fmt placeholder

src/v/redpanda/application.cc, tests/rptest/utils/node_operations.py
When redpanda startup procedure is aborted with SIGTERM signal the log
should indicated that. Added explicit handling of
`abort_requested_exception` to handle aborted startups explicitly.
Previously error was logged and terminated process returned an error
status code which indicates a problem.
Fixes: #7956
* none
=> Fixed treating aborted startup as an error

src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/utils/CMakeLists.txt, src/v/utils/prefix_logger.h, src/v/utils/tests/CMakeLists.txt, src/v/utils/tests/tracking_allocator_tests.cc, src/v/utils/tracking_allocator.cc, src/v/utils/tracking_allocator.h
Adds diagnostics for memory usage breakdown for tx subsystem in data partitions. Helps diagnose bad_alloc issues if caused by tx/idempotency usecases. Implements a custom allocator that tracks allocated/deallocated bytes which is then plumbed into all containers with non trivial memory usage.
Fixes #7295
=> tx/observability: utilities and metrics for memory usage

src/v/cluster/topic_table.cc, src/v/cluster/topic_table.h, src/v/coproc/reconciliation_backend.cc, src/v/coproc/reconciliation_backend.h, src/v/kafka/server/group_manager.cc, src/v/kafka/server/group_manager.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/7782
Fixes https://github.com/redpanda-data/redpanda/issues/8009,
=> [v22.2.x] Fix quadratic behavior in notify_waiters

src/v/cluster/topic_table.cc, src/v/cluster/topic_table.h, src/v/coproc/reconciliation_backend.cc, src/v/coproc/reconciliation_backend.h, src/v/kafka/server/group_manager.cc, src/v/kafka/server/group_manager.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/7782
* Fixes https://github.com/redpanda-data/redpanda/issues/8007
=> [v22.3.x] Fix quadratic behavior in notify_waiters

tests/rptest/clients/offline_log_viewer.py
=> tests: removed debugging sleep from offline_log_viewer.py

src/v/pandaproxy/api/api-doc/rest.json, src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/rest/handlers.cc, src/v/pandaproxy/rest/handlers.h, src/v/pandaproxy/rest/proxy.cc, src/v/pandaproxy/schema_registry/handlers.cc, src/v/pandaproxy/schema_registry/handlers.h, src/v/pandaproxy/schema_registry/service.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7080
=> [v22.1.x] Schema Registry and REST Proxy: health checks

src/v/pandaproxy/api/api-doc/rest.json, src/v/pandaproxy/api/api-doc/schema_registry.json, src/v/pandaproxy/rest/handlers.cc, src/v/pandaproxy/rest/handlers.h, src/v/pandaproxy/rest/proxy.cc, src/v/pandaproxy/schema_registry/handlers.cc, src/v/pandaproxy/schema_registry/handlers.h, src/v/pandaproxy/schema_registry/service.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7080
=> [v22.2.x] Schema Registry and REST Proxy: health checks

src/v/cluster/rm_stm.cc
=> tx/logging: minor addendum to observability patch

tests/rptest/tests/partition_balancer_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/8014
Fixes https://github.com/redpanda-data/redpanda/issues/8034,
=> [v22.3.x] tests: deflake partition_balancer_test.test_decommission

src/v/archival/tests/service_fixture.cc, src/v/archival/types.h, src/v/cloud_storage/remote.cc, src/v/cloud_storage/remote.h, src/v/cloud_storage/tests/remote_partition_test.cc, src/v/cloud_storage/tests/remote_segment_test.cc, src/v/cloud_storage/tests/remote_test.cc, src/v/cloud_storage/tests/s3_imposter.cc, src/v/cloud_storage/tests/s3_imposter.h, src/v/cloud_storage/types.cc, src/v/cloud_storage/types.h, src/v/cloud_storage_clients/CMakeLists.txt, src/v/cloud_storage_clients/client_pool.cc, src/v/cloud_storage_clients/configuration.cc, src/v/cloud_storage_clients/configuration.h, src/v/cloud_storage_clients/s3_client.cc, src/v/cloud_storage_clients/s3_client.h, src/v/cloud_storage_clients/s3_error.cc, src/v/cloud_storage_clients/s3_error.h, src/v/cloud_storage_clients/test_client/s3_test_client_main.cc, src/v/cloud_storage_clients/tests/s3_client_test.cc, src/v/cloud_storage_clients/util.cc, src/v/cloud_storage_clients/util.h, src/v/cluster/tests/archival_metadata_stm_test.cc, src/v/redpanda/application.cc, src/v/redpanda/tests/fixture.h
This PR contains a set of preliminary patches for supporting ABS with Tiered Storage. It contains a few renamings and hopefully obvious lifiting of utility functions.
* none
=> cloud_storage: Azure Blob Storage support prerequisites

tests/rptest/tests/random_node_operations_test.py, tools/offline_log_viewer/controller.py
Fixes: https://github.com/redpanda-data/core-internal/issues/302
* none
=> Fixed parsing ACL command in offline log viewer

src/v/archival/segment_reupload.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7890
=> [v22.3.x] archival: change start offset related warning in segment collector to debug

src/v/cluster/partition.cc, tests/rptest/tests/timequery_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7938
=> [v22.3.x] cloud_storage: Fix timequery in read-replica

tests/rptest/services/redpanda.py, tests/rptest/tests/e2e_shadow_indexing_test.py, tests/rptest/tests/read_replica_e2e_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7471
Fixes https://github.com/redpanda-data/redpanda/issues/7763,
=> [v22.3.x] tests: fix NoSuchBucket failures in ShadowIndexingWhileBusyTest

src/v/cloud_storage_clients/s3_client.cc, src/v/http/client.h
Modifies s3_client to print response_header on a single line with format ```[field_name: field_value];*```
Fixes #7936
Warn log lines with HTTP response header are now one line (as opposed to multiline) 
* Log lines with s3 response header are now on one line only
=> cloud_storage: log headers as single line messages

src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/utils/CMakeLists.txt, src/v/utils/prefix_logger.h, src/v/utils/tests/CMakeLists.txt, src/v/utils/tests/tracking_allocator_tests.cc, src/v/utils/tracking_allocator.cc, src/v/utils/tracking_allocator.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/7585
Fixes https://github.com/redpanda-data/redpanda/issues/8049,
=> [v22.3.x] tx/observability: utilities and metrics for memory usage

src/v/kafka/server/group.cc, src/v/kafka/server/group_manager.cc, src/v/kafka/server/group_manager.h, tests/rptest/tests/consumer_group_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7957
Fixes https://github.com/redpanda-data/redpanda/issues/7969,
=> [v22.3.x] Loading consumer groups asynchronously and in parallel

src/v/cluster/rm_stm.cc
=> tx/observability: Reduce mem_tracker log level to debug

CONTRIBUTING.md
fix typos in CONTRIBUTING.md
* none
* none
=> doc: fix typos in CONTRIBUTING.md

tests/rptest/tests/nodes_decommissioning_test.py
After node is decommissioned it is still able to answer Admin API requests. Until this issue is fixed we must query nodes that were not decommissioned to get an up to date information.
Fixes: #8029
* none
=> tests: do not query decommissioned node

src/v/cluster/tests/health_monitor_test.cc
Tightens the check for readiness of the partitions. A topic is available in the cluster report does not mean all it's partitions are ready. Some of them may still be waiting for leadership to be assigned.
Fixes #7941
* none
=> tests: deflake health_monitor_test::test_ntp_filter

src/v/kafka/server/group.cc, src/v/kafka/server/group.h, src/v/storage/record_batch_builder.h, src/v/storage/tests/record_batch_builder_test.cc
Some helpers and refactoring used as part of the larger offset retention project.
* none
=> kafka: offset retention helpers

src/v/cluster/tx_gateway_frontend.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7996
Fixes https://github.com/redpanda-data/redpanda/issues/8064,
=> [v22.3.x] tx: graceful commit/abort of 'ready' state txs

tests/rptest/tests/nodes_decommissioning_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/8044
Fixes https://github.com/redpanda-data/redpanda/issues/8123,
=> [v22.3.x] tests: do not query decommissioned node

src/v/cluster/members_backend.cc, src/v/cluster/members_backend.h
Using a simple loop instead of a timer to handle node operations reconciliation. The loop allow us to process to the next update immediately and wait only if current update must be retried as the reconciliation process returned an error.
Fixes: #8076
* none
=> c/members_backend: do not wait before proceeding to next update

tests/rptest/services/admin_ops_fuzzer.py
As lots of test became unstable after fixing validation in admin operations fuzzer. We disable validating result of topic configuration alteration not to disturb normal development process with constantly failing tests.
Related: #8083, #8102
* none
=> Disable admin operation validation for alter_topic_configuration

src/go/rpk/pkg/cli/cmd/topic/consume.go, src/go/rpk/pkg/cli/cmd/topic/consume_test.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/7971
Fixes https://github.com/redpanda-data/redpanda/issues/8133,
=> [v22.2.x] rpk: handle duration in offset range properly

tests/rptest/services/redpanda.py
The `LLVM_PROFILE_FILE` should be placed after the `preamble` and `env_preamble` variables
ref https://github.com/redpanda-data/devprod/issues/435
* none
=> add llvm_profile_file env var before running redpanda

src/go/rpk/pkg/cli/cmd/topic/consume.go, src/go/rpk/pkg/cli/cmd/topic/consume_test.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/7971
Fixes https://github.com/redpanda-data/redpanda/issues/8131,
=> [v22.3.x] rpk: handle duration in offset range properly

README.md
docs: remove stray newline
* none
* none
=> docs: remove stray newline

tests/rptest/tests/nodes_decommissioning_test.py
One of the nodes in this test is started using `RedpandaService.start_node` which does not include clean up from previous instances. This can cause log leftovers to creep in and spoil otherwise good test results. This PR manually calls `clean_node` for that node before staring it.
Fixes #7988
* none
* none
=> `NodesDecommissioningTest`.`test_decommissioning_rebalancing_node` cleanup after rouge RP instances

src/v/storage/disk_log_impl.cc, src/v/storage/log_manager.cc, src/v/storage/segment_utils.cc, src/v/storage/tests/storage_e2e_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7912
=> [v22.3.x] storage: clean up staging files on deletion

src/v/storage/disk_log_impl.cc, src/v/storage/log_manager.cc, src/v/storage/segment_utils.cc, src/v/storage/tests/storage_e2e_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/7912
=> [v22.2.x] storage: clean up staging files on deletion

tests/rptest/services/redpanda.py
In KgoVerifierWithSiTest, we sometimes use a set_cluster_configs immediately before an alter_topic_config.
There was a hidden bug here, which was un-hidden when error handling on Rpk wrapper was fixed: these alter_topic_config calls were not working, because the controller had no leader immediately after the config-driven restart.
This caused failures in
- KgoVerifierWithSiTestLargeSegments.test_si_with_timeboxed
- KgoVerifierWithSiTestSmallSegments.test_si_with_timeboxed
Example of failing tests: https://buildkite.com/redpanda/vtools/builds/5181#0185a506-5283-4950-936b-c336ab5ceee9
None
* none
=> tests: stabilize controller leader after config restart

src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/tests/remote_partition_test.cc, tests/rptest/tests/cloud_retention_test.py
This PR adds additional testing that would have helped catch #8110.
* none
=> more tests for fetching from partitions with truncated manifests

src/v/cluster/rm_stm.cc
try_emplace does not move from its value parameter when an insertion does not take place. however, a change in
https://github.com/redpanda-data/redpanda/commit/898e54132791c2fb591952c806ba1983da56ec08#diff-31c312a88efb2dcf54d8fc5447d59316554d9f7df36fa3125cacbf768a3bdeb0R2356-R2358
moved the value into a wrapper structure creating a temporary which would not have been moved from if insertion didn't take place, but the entry was still moved from.
the consequence of this is that an empty entry may be inserted into the sequence table during an upsert.
https://godbolt.org/z/rvc854reo
* none
=> rm_stm: fix use-after-move

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/8173
Fixes https://github.com/redpanda-data/redpanda/issues/8196,
=> [v22.3.x] tests: add "leftover file" error to allowed logs

src/v/storage/tests/storage_e2e_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/8163
=> [v22.3.x] storage_e2e_test: silence botched remove() in test

src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/tests/remote_partition_test.cc, tests/rptest/tests/cloud_retention_test.py
This PR adds additional testing that would have helped catch #8110.
Backport of https://github.com/redpanda-data/redpanda/pull/8157
* none
=> [v22.3.x] more tests for fetching from partitions with truncated manifests

src/v/redpanda/admin_server.cc, src/v/security/license.h, tests/rptest/tests/rpk_cluster_test.py, tests/rptest/util.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/8195
=> [v22.3.x] Implement operator== for license struct

tests/docker/Dockerfile, tests/docker/Dockerfile.dockerignore, tests/docker/ducktape-deps.sh
Backport from pull request #8156 
ref https://github.com/redpanda-data/devprod/issues/514
* none
=> [v22.3.x] backport 8156

tests/docker/Dockerfile, tests/docker/Dockerfile.dockerignore, tests/docker/ducktape-deps.sh
Backport from pull request #8156 
ref https://github.com/redpanda-data/devprod/issues/514
* none
=> [v22.2.x] test/docker: moved ducktape dependencies to standalone script

src/go/k8s/Makefile
Release notes https://github.com/kudobuilder/kuttl/releases/tag/v0.15.0
None
* none
=> k8s: Bump kuttle version to latest 0.15.0

src/v/archival/tests/archival_metadata_stm_test.cc, src/v/cluster/controller.cc, src/v/cluster/health_monitor_backend.cc, src/v/cluster/partition.cc, src/v/cluster/partition.h, src/v/cluster/partition_balancer_backend.cc, src/v/cluster/partition_balancer_backend.h, src/v/cluster/partition_balancer_planner.cc, src/v/cluster/partition_balancer_planner.h, src/v/cluster/persisted_stm.cc, src/v/cluster/persisted_stm.h, src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h, src/v/cluster/tests/partition_balancer_planner_fixture.h, src/v/cluster/tests/rm_stm_tests.cc, src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/tests/append_entries_test.cc, src/v/raft/tests/raft_group_fixture.h, src/v/raft/tests/state_removal_test.cc, src/v/storage/snapshot.cc, src/v/storage/snapshot.h, src/v/storage/tests/snapshot_test.cc
To calculate partition disk size properly we need to take into account all everything that we keep on disk for partition.
For this we add size of partition substructures snapshots to partition size
Also partition must be able to do fallocation step on new node after movement.
Partition size field in health report now contains size of non log files on disk
=> Partition balancer: better partition size calculation

src/v/kafka/server/server.cc, src/v/security/gssapi_authenticator.cc, src/v/security/gssapi_authenticator.h, src/v/security/gssapi_principal_mapper.cc, src/v/security/gssapi_principal_mapper.h, src/v/security/krb5.h, src/v/security/tests/gssapi_principal_mapper_test.cc, tests/rptest/services/kerberos.py, tests/rptest/tests/redpanda_kerberos_test.py
Applies principal mapping rules to Kerberos principals after GSSAPI authentication succeeds.
Force push `3919bee`:
* Fixed clang format in `krb5.h`
Force push `249833c`:
* Fixes in `krb5.h`
* Fixed incorrect configuration mapping
Force push `fe33440`:
* Fixes for PR
* Removed commit noise
Force push `70f026d`:
* Returning default rule when no rules are provided to be parsed
* Applies principal mapping rules to Kerberos principals after GSSAPI authentication
=> security/kerberos: gssapi apply mapping rules

src/go/k8s/tests/e2e/additional-configuration/00-redpanda-cluster.yaml, src/go/k8s/tests/e2e/additional-configuration/01-verify-config.yaml, src/go/k8s/tests/e2e/additional-configuration/02-update-config.yaml, src/go/k8s/tests/e2e/additional-configuration/03-verify-config-changed.yaml, src/go/k8s/tests/e2e/additional-configuration/verify-config.sh, src/go/rpk/pkg/config/schema.go, src/go/rpk/pkg/config/weak.go
To correctly handle new node config property in operator the field need to be added explicity to rpk config schema. Thanks to that it will not be used to reconfigure Redpanda using central configuration feature.
The `crash_loop_limit` node configuration can be set in cluster CR
as additional configuration.
* treat crash_loop_limit as node configuration option in configuration drift detection
=> rpk: Add crash_loop_limit to NodeConfiguration struct

src/v/cluster/tx_gateway_frontend.cc
If current tx is committed we have to check tx_seq with fetched transaction from old leader.
old is ongoing, new is committed, old.tx_seq==new.tx_seq we need to pick new 
and in this case old is ongoing, new is committed, old.tx_seq==new.tx_seq+1 we need to update old
* none
* none
=> [transactions] Fix get_ongoing_tx

src/v/cluster/tx_gateway_frontend.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/8171
=> [v22.3.x] [transactions] Fix get_ongoing_tx

src/v/cloud_storage_clients/client_probe.cc, src/v/cloud_storage_clients/client_probe.h
The recently introduced new counters were not being initialised, which lead to the metric displaying bogus values. This commit fixes the issue, and moves initialisation of all counters from the constructor to the header file.
* none
=> cloud_storage_client: zero init probe counter

tests/rptest/services/kerberos.py, tests/rptest/tests/redpanda_kerberos_test.py
Ensure the Java CLI tools also work with GSSAPI support in Redpanda.
* none 
* none
=> ducktape/kerberos: Add tests for Java CLI tools

src/v/security/gssapi_principal_mapper.cc, src/v/security/tests/gssapi_principal_mapper_test.cc, tests/rptest/tests/redpanda_kerberos_test.py
* Improve unit-test coverage
* Perform e2e test with Kerberos rules and ACL
Force-push `b52a6ba`
* Removed 'over testing' of ACL
* Fixed up format string
Force-push `9f54ca07`:
* Merge conflict fix
* none
* none
=> ducktape/kerberos: Expand kerberos tests

src/v/kafka/server/server.cc, src/v/kafka/server/server.h, src/v/security/gssapi_authenticator.cc, src/v/security/gssapi_authenticator.h, src/v/security/gssapi_principal_mapper.cc, src/v/security/gssapi_principal_mapper.h
Moved the kerberos rule mapper to the Kafka server, so it isn't created for every new connection.  Instead, when a new SASL handshake is started, and it requires the rules, those rules are passed to the
gssapi_authenticator created for that connection.
Force push `deb54bb`:
* Rebase off `dev` to fix merge conflict
Force push `8853bd4`:
* Fix clang-format error
* none
* none
=> security/kerberos: Moved kerberos rules to server

src/v/kafka/server/request_context.h
`throttle_ms` is a common response member, it was set up in the code later than the contents of the response was written to the log. This change populates `throttle_ms` before logging it, thus making it visible.
* none
* none
=> Logged kafka API response was missing `throttle_ms`

src/v/raft/consensus.cc
When re-configuring raft replica set at some point it does not make sense to cancel the reconfiguration even if the cancellation was requested. When configuration change is in the stage where nodes that are to be removed are demoted to learners it makes more sense to let the configuration change finish as canceling the change would require more larger quorum.
Consider configuration change from replica set A to replica set B.
- `A + B` denotes a set union
- `A - B` denotes a set difference
Raft configuration is presented as:
```
{'c': {'v': [A], 'l': []}, 'o':{}}
```
Where:
`c` - current configuration
`o` - previous configuration (present when configuration is in joint consensus)
`v` - voters
`l` - learners
`to_add` - nodes to add to configuration
`to_rm` - nodes to add to remove from …
=> Do not cancel reconfiguration when nodes are about to be removed

tools/offline_log_viewer/controller.py, tools/offline_log_viewer/reader.py
Adds decoding for bootstrap_cluster_cmd_data v1,
and logging on to read_envelope function to better help catch non-implemented decodings.
Partially Fixes https://github.com/redpanda-data/redpanda/issues/8360
* none
=> tools/offline_log_viewer: update for bootstrap_cluster_cmd_data v1

tests/rptest/services/admin_ops_fuzzer.py
Made deletion validation more strict. As metadata propagation in redpanda is eventually consistent we must check on every node to confirm deletion.
Fixes: #8333, Fixes #8179
* none
=> tests/admin_ops_fuzzer: strict deletion validation

tests/rptest/tests/e2e_topic_recovery_test.py
Signed-off-by: Noah Watkins <noahwatkins@gmail.com>
* none
=> cloud_stroage: disable test_restore_with_config_batches

src/v/cluster/controller_backend.cc, src/v/cluster/controller_backend.h, src/v/storage/fs_utils.h, src/v/storage/log_manager.cc, src/v/storage/log_manager.h, tests/rptest/tests/topic_delete_test.py
=> [v22.2.x] Topic delete orphan files

tests/rptest/tests/timequery_test.py
This commit adds more info in case the test fails. We currently don't have much context outside of the test failing, since the bug was caught in CDT where we don't have trace logs.
See https://github.com/redpanda-data/redpanda/issues/8291
* none
=> timequery_test: add more info to debug mismatched offset

tests/rptest/services/kerberos.py, tests/rptest/services/redpanda.py, tests/rptest/services/templates/redpanda.yaml, tests/rptest/tests/e2e_topic_recovery_test.py
This addresses e2e_topic_recovery_test instability caused by #8402.
This does not address #7758.
Signed-off-by: Michael Boquard <michael@redpanda.com>
* none
* none
=> ducktape/kerberos: Conditionally enable listener

src/v/cluster/members_backend.cc
If movement for partition is already in progress, we don't need to
create one more movement for this partition. So we need just to skip
meta for this partition
Fixes #8031
- Fix bug with movement on node addition of partition that is already moving
=> Skip moving partition on node addition if movement is already in progress

tests/docker/ducktape-deps.sh
Update to the latest client-swarm version. This new version adds some useful metrics over the current version. 
* none
=> Update client-swarm dependency

tests/rptest/tests/cloud_retention_test.py
The archival metrics aren't necessarily robust to leadership changes (in v22.3 and below, they get reset to 0). To ensure the test works in older versions, this commit changes the "segments deleted" condition to query the manifest rather than using the metrics endpoint.
This manifested as a test failure in the [backporting](https://github.com/redpanda-data/redpanda/pull/8411) of the test.
* none
=> cloud_retention_test: check manifest instead of metrics

src/go/k8s/hack/install-cert-manager.sh, src/go/k8s/kind.yaml
The old 1.21 nodes end of life was set to 2022-06-28.
Currently the 1.24 seems to be the most common in cloud providers portfolio.
* https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar
* https://cloud.google.com/kubernetes-engine/docs/release-notes#current_versions
* https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#available-versions
https://github.com/kubernetes-sigs/kind/releases/tag/v0.17.0
None.
* none
=> k8s: Bump k8s nodes to 1.24

src/v/cluster/members_manager.cc
A recent change in raft configuration cancellation logic prevents raft re-configuration canceling when nodes to be removed are demoted to learners. Since 'moving back' is not longer possible we should prevent recommissioning a node when it is already a learner in previous part of raft joint configuration.
The fix doesn't fix the race condition entirely but it reduces the possibility of it occurring. The race condition will be fixed with an introduction of simplified raft configuration. Also the race condition isn't really breaking anything. A user may receive success from recommission API however the node will simply be removed. It is a behavior that we accepted for partition movement cancel API.
Fixes: #8179
* none
=> Do not recommission a node when it is demoted to learner 

src/v/raft/group_configuration.cc
A learner should never be allowed to request votes. Fixed an error in raft configuration that might have lead to situation in which a node that couldn't be elected as a leader was sending votes preventing other nodes from becoming a leader.
Fixes: #6614
* none
=> Never allow learners to request votes

src/v/cluster/partition_manager.cc, src/v/cluster/partition_manager.h, src/v/cluster/raft0_utils.h, src/v/raft/group_manager.cc, src/v/raft/group_manager.h, src/v/raft/tests/mux_state_machine_fixture.h, src/v/raft/types.h, tests/rptest/tests/nodes_decommissioning_test.py
Using more robust API to set cluster configuration in node decommissioning tests. 
Fixes: #8452
* none
=> Use more robust config change mechanism

src/v/cluster/persisted_stm.cc, src/v/raft/state_machine.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/8271 and https://github.com/redpanda-data/redpanda/pull/8296
=> [v22.1.x] raft: fix handle_eviction in snapshots

src/go/k8s/pkg/resources/pdb.go, src/go/k8s/pkg/resources/pdb_test.go
Kubernetes deprecate pod distribution budget version v1beta1. This PR bumps the version.
Fixes #7715
~It should be merged after #8310~
[Force push]
Rebase to the tip of the dev.
None
* Pod distribution budget version v1 is used now in the operator
=> k8s: Bump pod distribution budget version

tests/docker/ducktape-deps.sh
Backport of PR https://github.com/redpanda-data/redpanda/pull/8526
=> [v22.3.x] Update omb git ref

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7995
=> [v22.1.x] add llvm_profile_file env var before running redpanda

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7995
=> [v22.2.x] add llvm_profile_file env var before running redpanda

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7995
=> [v22.3.x] add llvm_profile_file env var before running redpanda

src/v/cloud_roles/refresh_credentials.cc, src/v/cloud_roles/request_response_helpers.cc, src/v/cloud_roles/request_response_helpers.h, src/v/cloud_roles/tests/fetch_credentials_tests.cc, src/v/config/configuration.cc, src/v/config/configuration.h
=> Backport v22.2.x 8403 cloud roles handle conn timeout

src/go/rpk/pkg/api/admin/api_config.go, src/go/rpk/pkg/cli/cmd/cluster/config/import.go, tests/rptest/tests/cluster_config_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/8339
=> [v22.3.x] rpk: redact secret values when importing from file

tests/rptest/scale_tests/many_clients_test.py
This PR limits the per-node throughput to 30MiB/s in RP. This effectively limits the throughput of each producer to ~55KB/s or ~220MB/s over all producers. This limit is to ensure that regardless of instance size `client-swarm`'s producers have the same throughput as they would on a `i3en.xlarge` instance.
Note that this PR is largely to get the test passing. A follow-up task will be to look into why RP doesn't apply enough back-pressure to clients to ensure it doesn't run out of memory.
Fixes #8356 
* none
=> Limit producer rate in `ManyClientsTest`

tests/rptest/tests/partition_balancer_test.py
full_nodes test is pretty flaky.
1) We add more disk space for more stable population of disk on node.
2) Change segment_size because default 1GiB segment is 10% of full disk. For more stable population of disk we lower segment size
Fixes #8226, Fixes #8220
* none
=> ducktape: partition_balancer full_nodes test stability

src/v/security/gssapi_authenticator.cc, src/v/ssx/thread_worker.h
Without this change there is a data race that can result in a heap-use-after-free.
* none
* none
=> security/gssapi: Ensure krb5 objects are freed on the thread_worker.

src/v/cluster/health_monitor_frontend.cc, src/v/cluster/metadata_dissemination_service.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/8579
Fixes https://github.com/redpanda-data/redpanda/issues/8585,
=> [v22.3.x] Add exception logging to some background fibers

src/v/cloud_roles/refresh_credentials.cc
When refreshing credentials we need to handle all possible exceptions not to stop the credentials refresh loop. Previously any exception would result in a situation where credential refresh loop stops and finally credentials expire resulting in client reporting `ExpiredToken` error.
- fix situations in credentials are not refreshed leading to expired token errors
=> Handling all exceptions in refresh credentials loop

src/go/rpk/pkg/cli/cmd/cloud/auth/auth.go, src/go/rpk/pkg/cli/cmd/cloud/login.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/8581
=> [v22.3.x] rpk: use survey type password for cloud login

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/8502
=> [v22.3.x] coverage: fix inconsistent enabling option

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/8502
=> [v22.2.x] coverage: fix inconsistent enabling option

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/8502
=> [v22.1.x] coverage: fix inconsistent enabling option

src/v/kafka/client/broker.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/8578
Fixes https://github.com/redpanda-data/redpanda/issues/8603,
=> [v22.3.x] kafka/client: Better system_error handling

src/v/kafka/client/broker.h
Backport of PR #8578
Fixes #8608
=> [v22.1.x] kafka/client: Better system_error handling

src/v/kafka/client/broker.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/8578
Fixes https://github.com/redpanda-data/redpanda/issues/8605,
=> [v22.2.x] kafka/client: Better system_error handling

src/v/redpanda/admin_server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/8347
=> [v22.3.x] admin: correct added_replicas calculation

src/v/raft/consensus.cc, src/v/raft/consensus.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/8420
=> [v22.3.x] Upgrade raft configuration before entering transitional state

src/v/cluster/partition_manager.cc, src/v/cluster/partition_manager.h, src/v/cluster/raft0_utils.h, src/v/raft/group_manager.cc, src/v/raft/group_manager.h, src/v/raft/tests/mux_state_machine_fixture.h, src/v/raft/types.h, tests/rptest/tests/nodes_decommissioning_test.py
Backport of PR: https://github.com/redpanda-data/redpanda/pull/8497
=> [v22.3.x] Backport of #8497

tests/rptest/tests/cloud_retention_test.py
Backport of https://github.com/redpanda-data/redpanda/pull/8254
CONFLICT:
- removed new ABS-related changes to test infra, no change to actual test
tests/cloud_retention_test was a copy of its scale_test/ variant, scaled down to be runnable in CI. This commit removes the original scale_test/ and parameterizes instead to avoid leaving around significantly duplicated code.
This also marks the test debug-only, since the original was only run with release binaries.
(cherry picked from commit 9f9a45a62a407c7149352b3b87900500d6729e96)
* none
=> [v22.3.x] tests: reconcile cloud_retention scale test

src/v/utils/stream_utils.h, src/v/utils/tests/input_stream_fanout_test.cc
If the source stream throws an exception readers of all fanout streams will hang indefinitely. The exception won't be processed and the background producer fiber will exit with ignored exception. As result the reader will wait for new data indefinitely if the 'stop' method is not called.
This commit changes this behavior. The exception in the background producer thread is saved and bubbled up to readers if the source stream throws.
* Fix hang during shutdown when tiered storage is actively used
=> utils: Fix hang in input_stream_fanout

src/v/kafka/server/group.cc, src/v/kafka/server/group.h, src/v/kafka/server/rm_group_frontend.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/8566
Fixes https://github.com/redpanda-data/redpanda/issues/8635,
=> [v22.3.x] Fixes #8236 (stuck transactions) by aborting expired transactions

src/go/rpk/pkg/cli/cmd/topic/add_partitions.go
Introducing a guardrail on changing the partition count in `__consumer_offsets` since it's generally a bad idea to do so. Added a new flag `-f` to enforce the change.
New behavior:
```
$ rpk topic add-partitions test __consumer_offsets -n 10
It's generally a bad idea to change the partition count in __consumer_offsets. Exiting.
Add the '-f' flag if you really want to change it.
```
=> Fail when changing partition count in __consumer_offsets by default

src/go/k8s/pkg/resources/statefulset_update.go
Previously it was:
```
INFO	controllers.redpanda.Cluster	Verify that Ready endpoint returns HTTP status OK	{"redpandacluster": "kuttl-test-communal-loon/up-img", "Kind": ""}
```
Operator will log context during rolling update.
* Pod name included during rolling update procedure
=> k8s: Include pod name in the log statement context

tests/rptest/archival/s3_client.py
We are seeing a spooky behavior where a bucket is created, later listobjectsv2 requests fail with NoSuchBucket, and then toward the end of the test list operations start succeeding.
This test does two things:
- issue a listobjectsv2 right after the bucket is created, to detect a situation where the server is clearly failing read-after-write rules (seems unlikely)
- in general, if a listobjectsv2 request fails, follow it with a listbuckets request: i.e. "If this bucket doesn't exist, which buckets *do* exist?"
None
* none
=> test: add debug for NoSuchBucket exceptions

src/v/features/feature_table.cc, src/v/features/feature_table.h, src/v/kafka/server/group_manager.cc
=> Offset retention legacy timestamps

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/kafka/server/snc_quota_manager.cc, src/v/kafka/server/snc_quota_manager.h
Cluster wide TP limit properties added are synonmical to node wide limit for now, and are not exposed to users. If both cluster and node properties are set, the minimum value wins, otherwise the set propery is the one that controls node wide TP limit on each node.
* none
* none
=> Cluster wide throughput limit cluster properties

src/v/kafka/server/group_manager.cc
Catch gate/abort exceptions when replicating into consumer group partition and stop the version fence writing process because the raft group appears to be shutting down.
Fixes: #8667
* none
=> kafka: handle replicating into raft group shutting down

tests/rptest/tests/acls_test.py
A few auth combinations in the test matrix result in cluster auth being returend when trying to setup the cluster. Check for these cases explicitly.
Fixes: #8202
* none
=> test: check for auth exception in test matrix

src/v/archival/ntp_archiver_service.cc, src/v/cloud_storage/base_manifest.h, src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/partition_manifest.h, src/v/cloud_storage/remote.cc, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/tests/partition_manifest_test.cc, src/v/cloud_storage/tests/topic_manifest_test.cc, src/v/cloud_storage/tests/tx_range_manifest_test.cc, src/v/cloud_storage/topic_manifest.cc, src/v/cloud_storage/topic_manifest.h, src/v/cloud_storage/tx_range_manifest.cc, src/v/cloud_storage/tx_range_manifest.h
Futurize manifest serialization to prevent reactor stalls with large manifests. The serialization for most manifest types is not asynchronous because they are small. Serialization for `partition_manifest` calls `ss::maybe_yield` to prevent reactor stalls.
Fixes #8511 
* Fix reactor stalls on partitions with large number of segments in the cloud storage
=> cloud_storage: Futurize manifest serialization

src/go/k8s/tests/e2e/update-image-and-node-port/02-new-image-and-pv.yaml, src/go/k8s/tests/e2e/update-image-tls-client-auth/02-new-image-and-pv.yaml, src/go/k8s/tests/e2e/update-image-tls/02-new-image-and-pv.yaml
Due to the following error
```
Failed to reconcile resource	{"redpandacluster": "kuttl-test-helping-dove/up-img", "error": "unable to construct object: cannot retrieve cloud storage secret for data archival: secret name archival-update-image-tls-client-auth, ns default, data key archival-update-image-tls-client-auth: cannot find key in secret data"}
```
Each test should have key matching the Kubernetes Secret name.
None
* none
=> k8s: Fix the incorrect key name

tests/rptest/utils/node_operations.py
Improved the decommissioning waiter to query for decommissioning progress only those nodes which has decommissioning progress available. When test involves upgrade scenario it may happen that the previous version of redpanda not yet supports the decommission progress API, this caused the test to fail as the progress wasn't reported.
Fixes: #8580
Fixes: #8654
* none
=> Query decommission progress when it is available

src/v/storage/disk_log_impl.cc
Clamp max compacted segment size to 1.5GiB to avoid compaction index size overflow.
Fixes https://github.com/redpanda-data/redpanda/issues/7647
This is a workaround for older versions, proper fix is https://github.com/redpanda-data/redpanda/pull/7687
* Clamp max compacted segment size to 1.5GiB to avoid compaction index size overflow that could lead to hangs when trying to compact large segments.
=> storage: clamp max_compacted_segment_size to 1.5 GiB

.github/CODEOWNERS
=> .github/CODEOWNERS: update rpk

src/v/kafka/server/snc_quota_manager.cc
When the quota balancer is disabled, that should reset effective quotas. In #8392, it was done asychronously to balancer updates, which proved incorrect in case of simultaneous change of many related properties. This change makes use of quota_balancer_update() to deliver quota reset values to shards in synch with other updates and the balancer.
Closes #8731.
Related to #8392.
* none
* none
=> Synchronize quota reset on balancer disable

tests/rptest/scale_tests/partition_balancer_scale_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/8598
Fixes https://github.com/redpanda-data/redpanda/issues/8717,
=> [v22.3.x] Improvements for PartitionBalancerScaleTest.test_node_operations_at_scale

src/v/cluster/archival_metadata_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/8616
=> [v22.2.x] archival: fix errc condition for logging

.github/workflows/rpk-build.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/8485
Fixes https://github.com/redpanda-data/redpanda/issues/8767,
=> [v22.3.x] gha: bump goreleaser action version for rpk workflow

src/v/cluster/persisted_stm.cc, src/v/raft/state_machine.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/8271 and https://github.com/redpanda-data/redpanda/pull/8296
=> [v22.2.x] raft: fix handle_eviction in snapshots

src/v/utils/stream_utils.h, src/v/utils/tests/input_stream_fanout_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/8554
=> [v22.2.x] utils: Fix hang in input_stream_fanout

src/v/kafka/server/group_manager.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/8192
=> [v22.2.x] k/group: bump error log messages to info

src/go/rpk/pkg/cli/cmd/plugin/install.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/8771
Fixes https://github.com/redpanda-data/redpanda/issues/8786,
=> [v22.3.x] rpk: bugfix - stop requiring HOME in unrelated cmd

tests/rptest/services/redpanda.py
In ducktape we have periodic queries for Redpanda version. It may be the case that the version query process is interpreted as running Redpanda.
Fixed the issue by filtering version queries when asking about repanda process PID.
Fixes: #8753
* none
=> Filter out version queries when asking for Redpanda pid

tests/docker/Dockerfile, tests/docker/ducktape-deps.sh
Backport of PR https://github.com/redpanda-data/redpanda/pull/8800
=> [v22.3.x] tests: add missing dependency to central script

src/v/pandaproxy/schema_registry/protobuf.cc, src/v/pandaproxy/schema_registry/test/compatibility_protobuf.cc, src/v/pandaproxy/schema_registry/test/compatibility_protobuf.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/8789
=> [v22.3.x] schema_registry/protobuf: Early exit recursion if file exists

src/v/pandaproxy/schema_registry/protobuf.cc, src/v/pandaproxy/schema_registry/test/compatibility_protobuf.cc, src/v/pandaproxy/schema_registry/test/compatibility_protobuf.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/8789
=> [v22.2.x] schema_registry/protobuf: Early exit recursion if file exists

src/v/pandaproxy/schema_registry/protobuf.cc, src/v/pandaproxy/schema_registry/test/compatibility_protobuf.cc, src/v/pandaproxy/schema_registry/test/compatibility_protobuf.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/8789
=> [v22.1.x] schema_registry/protobuf: Early exit recursion if file exists

tests/rptest/remote_scripts/schema_registry_test_helper.py, tests/rptest/services/action_injector.py, tests/rptest/services/admin_ops_fuzzer.py, tests/rptest/services/kgo_verifier_services.py, tests/rptest/tests/pandaproxy_test.py, tests/rptest/tests/topic_recovery_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/8816
Fixes https://github.com/redpanda-data/redpanda/issues/8840,
=> [v22.3.x] Tests: set daemon=True for all background Threads

src/go/rpk/pkg/redpanda/launcher.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/8817
=> [v22.3.x] rpk: remove env from logs in redpanda launcher

src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/vote_stm.cc, tests/rptest/tests/partition_balancer_test.py
Previously a notification was emitted before the term was confirmed and it might lead to situation in which a notification was send before a node was actually recognized as a raft group leader.
Fixes https://github.com/redpanda-data/redpanda/issues/6869
* none
=> Trigger leadership notification after current term is confirmed

tests/docker/ducktape-deps.sh
=> [v22.3.x] ducktape-deps: remove && operator from the script

tests/docker/ducktape-deps.sh
=> [v22.2.x] ducktape-deps: remove && operator from the script

src/v/cluster/members_backend.cc
Starting listening for the updates immediately after `cluster::members_backend` is constructed. This way a `members_backend` update queue will be freed to accept updates coming from the commands applying logic.
Since the size of `_updates_queue` is limited it may previously be exhausted blocking subsequent applies and leading to deadlock.
The fix allows the `_update_queue` to be consumed by the `members_backend` the members_backend will start reconciliation after it is started however incoming updates will be compacted when being applied to `members_backend` updates list.
- Fixed starting redpanda after executing at least 100 node operations
=> c/members_backend: start listening for updates immediately

src/v/kafka/server/replicated_partition.cc
If a partition has been prefix-truncated to remove all data, it may be in a state where dirty_offset=start_offset-1 this caused a runtime_error when calling
offset_translator_state::from_log_offset
Handle this by noticing the case explicitly and falling back to translating the log's start offset and advancing by 1.
This currently only comes up when testing topic recovery from tiered storage, where tiny local retentions may result in removing all local data.
Backport of PR #8843 
None
* Fix a rare issue in topic recovery, where if topic retention was configured to a very small size, subsequent consumer reads could hang.
=> [v22.3.x] Backport #8843 (kafka: handle empty partitions in validate_fetch_offset)

src/v/cluster/members_backend.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/8861
=> [v22.3.x] c/members_backend: start listening for updates immediately

src/v/cloud_storage/materialized_segments.cc, src/v/cloud_storage/remote.cc, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_segment.cc, src/v/cloud_storage/remote_segment.h, src/v/cloud_storage/tests/remote_partition_test.cc, src/v/cluster/controller.cc, src/v/cluster/partition.cc, src/v/http/client.cc, src/v/storage/log_manager.cc
Backport of https://github.com/redpanda-data/redpanda/pull/8587
CONFLICT:
* partition::stop() shutdown order is different in v22.3.x, and there is
no archiver
* name changes from the S3-client-generalization
* Fixed a hang at shutdown when using tiered storage.
=> [v22.3.x] Cloud storage shutdown hang

tests/rptest/scale_tests/ht_partition_movement_test.py, tests/rptest/services/admin.py, tests/rptest/tests/partition_movement.py
When we call movement cancellation, api can return success but movement can already be in non return state so actual cancellation will not happen. So resulting assignments can be assignments from initial movement operation
Fixes #8489
* none
* none
=> ducktape: movement can be in non return state when cancelled

src/v/storage/segment_reader.cc, src/v/storage/segment_reader.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/8790
Fixes https://github.com/redpanda-data/redpanda/issues/8862,
=> [v22.3.x] s/segment_reader: gate in-flight operations

src/go/rpk/pkg/redpanda/launcher.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/8817
=> [v22.1.x] rpk: remove env from logs in redpanda launcher

tests/rptest/scale_tests/node_operations_fuzzy_test.py, tests/rptest/services/admin_ops_fuzzer.py, tests/rptest/tests/partition_balancer_test.py, tests/rptest/tests/random_node_operations_test.py
Stopping `AdminOperationsFuzzer` in a test `teardown` phase prevents it
from operating on stopped redpanda cluster. Previously when test failed
the fuzzer wasn't stopped and it tried to execute operations on stopped
redpanda cluster.
Related: #8576
* none
=> Fixed stopping admin operation fuzzer when test fails

tests/rptest/tests/random_node_operations_test.py
=> tests: stop all nodes before reading controller log with offline viewer

tests/rptest/tests/throughput_limits_snc_test.py
Fixes #8809
Double the minimum tested value for TP limit (both ingress and egress) because there is evidence that 64 B/s on egress side causes timeouts while a client connects to the cluster.
* none
* none
=> Double the minimum TP limit in the `ThroughputLimitsSnc.test_configuration`

tests/rptest/services/redpanda_installer.py
Github rate limits anonymous HTTP clients: if one runs many tests in parallel, this can result in 403s.
We may assume that the set of released packages does not change within the lifetime of a ducktape process, so cache this as a class member.
Populating the cache is protected by a mutex so that when N tests start concurrently, they do not all enter the code for populating the cache.
None
* none
=> tests: cache release list downloaded from github

tests/rptest/tests/partition_balancer_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/8463
Fixes https://github.com/redpanda-data/redpanda/issues/8765,
=> [v22.3.x] ducktape: partition_balancer full_nodes test stability

tests/rptest/tests/partition_balancer_test.py
Backport of PRs https://github.com/redpanda-data/redpanda/pull/6832 https://github.com/redpanda-data/redpanda/pull/8463
(cherry picked from commits 
https://github.com/redpanda-data/redpanda/commit/50d8d684c1ff165a729162c71631e029cd86e71f
https://github.com/redpanda-data/redpanda/pull/8463/commits/76991a89d9ec3bf845e5dbb26cd3557454fd0043)
* none
* none
=> [v22.2.x] ducktape: Partition balancer full nodes test stability

src/v/archival/ntp_archiver_service.cc
Because the semaphore was broken before the co_await on the log merger in ::stop, and the abort source fires after, the upload loop could proceed past its abort source check and hit a broken_semaphore.
Fix the order in stop, and as an extra defensive measure also swallow the exception type along with other shutdown-type exceptions.
Fixes https://github.com/redpanda-data/redpanda/issues/8935
None
* none
=> archival: avoid broken_sempahore ERROR logs

src/v/cluster/health_monitor_backend.cc, tests/rptest/services/rolling_restarter.py
These tests were slower than necessary when waiting for the node's drain status to propagate via the health monitor.  By querying the state on the node directly, this goes faster.
This also makes test logs easier to read, as the drain status doesn't fluctuate depending on which node the test queries.
None
* none
=> tests: speed up tests that do rolling restarts

tests/rptest/scale_tests/many_clients_test.py
Retention limits are firing and deleting logs before consumers have time to consume the data.  This PR simply doubles the retention size limit.
Signed-off-by: Michael Boquard <michael@redpanda.com>
Fixes #8655 
* none
* none
=> test: Increase retention limit for many clients test

tests/docker/Dockerfile, tests/docker/ducktape-deps.sh, tests/rptest/clients/python_librdkafka_serde_client.py, tests/rptest/tests/compatibility/arroyo_test.py
Our tests were running with arroyo 1.0.0, which is fairly old compared to the latest release of 2.5.0 to which this PR upgrades the dependency.
The ci-failure assertion failures in
https://github.com/redpanda-data/redpanda/issues/6826 were removed in arroyo 2.3 test suite with this commit
https://github.com/getsentry/arroyo/commit/84934df1e14f1490682adf91b208e004b23bf82e. So upgrading at least renders the original ticket irrelevant.
Fixes: https://github.com/redpanda-data/redpanda/issues/6826
* none
=> test: upgrade arroyo dependency

tests/rptest/tests/partition_movement.py
Before we check if configuration across the nodes is consistent we must wait for the move to finish as before the move finishes replicas assignment may already be consistent.
Fixes: #8917
* none
=> tests: wait for cancellation to finish before checking configuration

tests/rptest/archival/s3_client.py
This is a workaround for an apparent quirk in AWS S3, where ListObjectsv2 requests returned NoSuchBucket errors when run soon after creating a bucket.
I didn't really want to put this hack in, but the most recent debug logs point pretty unambiguously to a lack of read-after-write consistency in the API when it comes to listobjectsv2.
Fixes: https://github.com/redpanda-data/redpanda/issues/8490
Fixes: https://github.com/redpanda-data/redpanda/issues/8564
Fixes: https://github.com/redpanda-data/redpanda/issues/8754
None
* none
=> tests: wait for listobjects to work after bucket creation

src/v/archival/ntp_archiver_service.cc
topics. The adjacent_segment_merger_job is designed to not to upload compacted seegments. But when the job is running on compacted partition it can still reupload segments which are not compacted yet. It's not necessary because compacted segment reupload will eventually reupload partition data after compaction will happen. This may also cause CI failures because adjacent segment merging may prevent compacted segment reupload from happening because it will aggregate the segments in the cloud and the compacted segment reupload has to be aligned with that large non-compacted segment. This changes the timings of operations (more segments has to be compacted) and the test fails.
Fixes #8958
* none
=> archival: Do not instantiate adjacent segment merging job for compacted partitions

tests/rptest/scale_tests/many_clients_test.py
Since https://github.com/redpanda-data/redpanda/pull/8661, ducktape tests run with a connection count limit enabled by default, so this needs adjusting for a test that intentionally creates many thousands of client connections.
Fixes https://github.com/redpanda-data/redpanda/issues/8979
None
* none
=> tests: set connection limits in many_clients_test

tests/docker/Dockerfile, tests/docker/ducktape-deps.sh, tests/rptest/clients/python_librdkafka_serde_client.py, tests/rptest/tests/compatibility/arroyo_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/8940
Fixes https://github.com/redpanda-data/redpanda/issues/8995,
=> [v22.3.x] test: upgrade arroyo dependency

tests/docker/Dockerfile, tests/docker/ducktape-deps.sh, tests/rptest/clients/python_librdkafka_serde_client.py, tests/rptest/tests/compatibility/arroyo_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/8940
Fixes https://github.com/redpanda-data/redpanda/issues/8997,
=> [v22.2.x] test: upgrade arroyo dependency

tests/rptest/services/producer_swarm.py, tests/rptest/tests/topic_creation_test.py
Moving producer_swarm from background_service to service.
This is usefull for debugging problems connected to producer_swarm.
We will be able to collect logs and use separate node for producer stability
* none
* none
=> ducktape: move producer_swarm to separate service

tests/rptest/services/admin_ops_fuzzer.py
Prev validation for topic deletion uses api that check topic in partition_manager, but it is only check does node contains this topic or not.
But if node read controller log not super fast it can contains expired data in metadata_cache
So in our case slow node can contains info about deleted topic. So in validation we should use another way to check.
Because kafka API request for metadata can return this old expired data
Fixes #I8920
None
* none
=> Use topic_table to check deletion in fuzzy_test

src/v/cluster/controller_backend.cc, src/v/cluster/controller_backend.h, src/v/cluster/shard_table.h
Reverts https://github.com/redpanda-data/redpanda/commit/d3ce3cefeb5aa4eb48ee9ebd9c241d9060ec15d3 and redoes shard table updates to handle parallel bootstrapping across shards by sequencing shard table updates on the update revisions. The original approach is broken after https://github.com/redpanda-data/redpanda/commit/8b500eab322b6a8e80b7ec8a10529bedb9922e98 which runs every update regradless of whether it was eventually canceled. 
Fixes #8981, #8908, #8981
- [] none - not a bug fix
* none
=> c/backend: fix shard table updates with cross core partition moves

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/kafka/server/snc_quota_manager.cc, src/v/kafka/server/snc_quota_manager.h
This PR reverts #8639.
* none
* none
=> Remove cluster wide throughput limit cluster properties

src/v/raft/tests/type_serialization_tests.cc, src/v/raft/types.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/8781
=> [v22.3.x] fixed serialization of mixed failed and successful heartbeat replies

src/go/k8s/controllers/redpanda/cluster_controller.go, src/go/k8s/main.go, src/go/k8s/pkg/resources/featuregates/featuregates.go, src/go/k8s/pkg/resources/resource_integration_test.go, src/go/k8s/pkg/resources/statefulset.go, src/go/k8s/pkg/resources/statefulset_test.go, src/go/k8s/pkg/resources/statefulset_update.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/9016
=> [v22.3.x] Change under replicated query and timeout handling

src/v/redpanda/admin/api-doc/config.json, src/v/redpanda/admin_server.cc, tests/rptest/services/admin.py, tests/rptest/services/redpanda.py, tests/rptest/tests/log_level_test.py
This PR enables trace logging after a shutdown timeout in ducktape. If there's some kind of hang happening, it'd be great to get better insight into what's going on under the hood, especially in environments with limited logging (e.g. nightly CDT runs log at info level).
This adds an endpoint to the admin server to fetch all loggers that is exposed in the ducktape Admin service.
* none
=> enable trace logging after shutdown timeout

src/v/cluster/archival_metadata_stm.cc
If replication of an archival STM batch times out, the batch will be applied from outside of the main upload loop. From logs, this may make it look like we missed uploading a segment, even though subsequent logs may show us reading from the "missing" segment.
This adds a log to the apply steps that currently don't have logging.
* none
=> archival: log when applying batches

src/v/storage/probe.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9020
Fixes https://github.com/redpanda-data/redpanda/issues/9037,
=> [v22.2.x] storage: fix disk space stats to be gauges

src/v/storage/probe.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9020
Fixes https://github.com/redpanda-data/redpanda/issues/9039,
=> [v22.3.x] storage: fix disk space stats to be gauges

src/v/kafka/server/handlers/alter_partition_reassignments.cc
Converted `AlterPartitionReassignmentRequest` handler to use continuation chain. This change was required because of bug in clang (https://github.com/llvm/llvm-project/issues/51843)
Fixes: #9089
* none
* none
=> k/alter_reassignments: converted handler to continuation chain

src/v/kafka/server/handlers/alter_partition_reassignments.cc
Backport of PR #9157 
* none
* none
=> [v23.1.x]   k/alter_reassignments: converted handler to continuation chain

src/v/kafka/server/handlers/alter_partition_reassignments.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9157
Fixes https://github.com/redpanda-data/redpanda/issues/9160,
=> [v23.1.x] k/alter_reassignments: converted handler to continuation chain

src/v/cloud_roles/refresh_credentials.h, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h, tests/rptest/tests/shadow_indexing_admin_api_test.py, tests/rptest/tests/topic_recovery_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/9092
Fixes https://github.com/redpanda-data/redpanda/issues/9162,
=> [v23.1.x] Return ACCEPTED http status during topic recovery

tests/rptest/utils/node_operations.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/8674
Fixes https://github.com/redpanda-data/redpanda/issues/8722,
=> [v22.3.x] Query decommission progress when it is available

src/go/rpk/pkg/cli/cmd/container/common/common.go, src/go/rpk/pkg/cli/cmd/container/start_test.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/9133
=> [v23.1.x] rpk: Fix container panic when using Podman

src/go/rpk/pkg/cli/cmd/container/common/common.go, src/go/rpk/pkg/cli/cmd/container/start_test.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/9133
=> [v22.3.x] rpk: Fix container panic when using Podman

src/v/utils/stream_utils.h, src/v/utils/tests/input_stream_fanout_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/8554
=> [v22.3.x] utils: Fix hang in input_stream_fanout

src/v/cluster/tx_gateway_frontend.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/8773
Fixes https://github.com/redpanda-data/redpanda/issues/8854,
=> [v22.3.x] Fix 8726 by making try_abort fail faster

src/v/cluster/controller_backend.cc, src/v/cluster/health_monitor_backend.cc, src/v/cluster/metadata_dissemination_handler.cc, src/v/cluster/metadata_dissemination_service.cc, src/v/cluster/partition_leaders_table.cc, src/v/cluster/partition_leaders_table.h, src/v/cluster/rm_partition_frontend.cc, src/v/cluster/tx_gateway_frontend.cc, src/v/cluster/tx_gateway_frontend.h, src/v/kafka/server/handlers/find_coordinator.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9074
Fixes https://github.com/redpanda-data/redpanda/issues/8854,
=> [v22.3.x] Fix accidental roll back of the metadata cache

src/v/cluster/archival_metadata_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/8616
=> [v22.3.x] archival: fix errc condition for logging

src/v/bytes/details/io_byte_iterator.h, src/v/bytes/iobuf.h, src/v/bytes/tests/CMakeLists.txt, src/v/bytes/tests/iobuf_fuzz.cc, src/v/bytes/tests/iobuf_tests.cc
libfuzzer based testing for iobuf interface. this can achieve
nearly 100% code coverage of iobuf.h and iobuf.cc, with the following
exceptions:
1. futurized interfaces. libfuzzer and seastar are not playing well
together and fixing this is an on-going project.
2. iobuf::reserve. this interface is hard to use safely with lots of
assumptions and ways for it to break. integrating it into the fuzzer
is difficult because we would have to disqualify all sorts of
operations if an active placeholder existed. the alternative is to
remove iobuf::reserve which is underway in a separate effort.
* none
=> iobuf: add fuzzer

src/go/k8s/tests/e2e/centralized-configuration-upgrade/00-redpanda-cluster.yaml, src/go/k8s/tests/e2e/centralized-configuration-upgrade/01-assert.yaml, src/go/k8s/tests/e2e/centralized-configuration-upgrade/01-first-upgrade.yaml, src/go/k8s/tests/e2e/update-image-and-node-port/00-assert.yaml, src/go/k8s/tests/e2e/update-image-and-node-port/00-current-image.yaml, src/go/k8s/tests/e2e/update-image-and-node-port/01-assert.yaml, src/go/k8s/tests/e2e/update-image-and-node-port/02-assert.yaml, src/go/k8s/tests/e2e/update-image-and-node-port/03-assert.yaml, src/go/k8s/tests/e2e/update-image-and-node-port/04-assert.yaml, src/go/k8s/tests/e2e/update-image-and-node-port/05-assert.yaml, src/go/k8s/tests/e2e/update-image-tls-client-auth/00-assert.yaml, src/go/k8s/tests/e2e/update-image-tls-client-auth/00-current-image.yaml, src/go/k8s/tests/e2e/update-image-tls-client-auth/01-assert.yaml, src/go/k8s/tests/e2e/update-image-tls-client-auth/02-assert.yaml, src/go/k8s/tests/e2e/update-image-tls-client-auth/03-assert.yaml, src/go/k8s/tests/e2e/update-image-tls-client-auth/04-assert.yaml, src/go/k8s/tests/e2e/update-image-tls-client-auth/05-assert.yaml, src/go/k8s/tests/e2e/update-image-tls/00-assert.yaml, src/go/k8s/tests/e2e/update-image-tls/01-assert.yaml, src/go/k8s/tests/e2e/update-image-tls/02-assert.yaml, src/go/k8s/tests/e2e/update-image-tls/03-assert.yaml, src/go/k8s/tests/e2e/update-image-tls/04-assert.yaml, src/go/k8s/tests/e2e/update-image-tls/05-assert.yaml
Currently there is problem in assertion. The `update-image-tls` test incorrectly check container tag (Redpanda version). 
Bump patch version in all tests where `v22.1.X` is used.
Change the way how logs are collected.
* none
https://github.com/redpanda-data/redpanda/pull/9086
=> Fix and improve e2e tests

src/v/kafka/server/group_manager.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/8192
=> [v22.3.x] k/group: bump error log messages to info

lsan_suppressions.txt, tools/cmake_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7888
Fixes https://github.com/redpanda-data/redpanda/issues/8470,
=> [v22.3.x] lsan: ignore memory leak

src/v/archival/archival_policy.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/8693
=> [v22.3.x] archival: Turn assertion into exception

src/go/k8s/pkg/resources/certmanager/type_helpers_test.go
This regression has been fixed in
https://github.com/redpanda-data/redpanda/pull/8057.
* none
=> k8s: add test for broker tls regression

src/go/k8s/pkg/resources/pdb.go, src/go/k8s/tests/e2e/update/00-assert.yaml
Backport of PR https://github.com/redpanda-data/redpanda/pull/8600
Fixes https://github.com/redpanda-data/redpanda/issues/8719,
=> [v22.3.x] Fix policy version

tests/rptest/tests/random_node_operations_test.py
This commit only exists on v22.3.x, as #8406 is addressed with a solution that uses a feature flag and can't be backported.
* none
=> [v22.3.x] tests: add rpc::errc::unknown to log allow list

src/v/cloud_storage/cache_service.cc, src/v/cloud_storage/partition_recovery_manager.cc, src/v/cloud_storage/remote_partition.cc, src/v/cloud_storage/remote_partition.h, src/v/cloud_storage/remote_segment.cc, src/v/kafka/server/replicated_partition.cc, src/v/kafka/server/replicated_partition.h, tests/docker/ducktape-deps.sh, tests/rptest/clients/rpk.py, tests/rptest/services/kgo_verifier_services.py, tests/rptest/tests/e2e_topic_recovery_test.py, tests/rptest/tests/replication_factor_change_test.py, tests/rptest/tests/shadow_indexing_tx_test.py, tests/rptest/utils/si_utils.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7819 , https://github.com/redpanda-data/redpanda/pull/8926
Fixes https://github.com/redpanda-data/redpanda/issues/7842
=> [v22.3.x] kafka: fix transactional reads on tiered storage recovered partitions

src/v/archival/segment_reupload.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/8572
=> [v22.3.x] archival: quieten a noisy INFO-level message

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/8782
Fixes https://github.com/redpanda-data/redpanda/issues/8826,
=> [v22.3.x] Filter out version queries when asking for Redpanda pid

src/go/k8s/pkg/resources/certmanager/type_helpers_test.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/8085
=> [v22.3.x] k8s: add test for broker tls regression

src/go/k8s/tests/e2e/update-image-and-node-port/02-new-image-and-pv.yaml, src/go/k8s/tests/e2e/update-image-tls-client-auth/02-new-image-and-pv.yaml, src/go/k8s/tests/e2e/update-image-tls/02-new-image-and-pv.yaml
Backport of PR https://github.com/redpanda-data/redpanda/pull/8648
=> [v22.3.x] k8s: Fix secret shared between e2e tests

tests/rptest/remote_scripts/schema_registry_test_helper.py, tests/rptest/services/action_injector.py, tests/rptest/services/admin_ops_fuzzer.py, tests/rptest/services/kgo_verifier_services.py, tests/rptest/tests/topic_recovery_test.py
backport of https://github.com/redpanda-data/redpanda/pull/8816
* none
=> [v22.2.x] tests: set daemon=True for all background Threads

src/go/k8s/apis/redpanda/v1alpha1/redpanda_clusterspec_types.go, src/go/k8s/apis/redpanda/v1alpha1/redpanda_types.go, src/go/k8s/apis/redpanda/v1alpha1/zz_generated.deepcopy.go, src/go/k8s/main.go
Should clean up comment blocks that were added for local testing.
=> chore: remove comment blocks and clean code

tests/rptest/tests/e2e_topic_recovery_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/8835
=> [v22.3.x] test: don't loop consumer in EndToEndTopicRecovery

src/go/k8s/Makefile
Change make file test target to use new env-test. This affect only development workflow as taskfile is using different approach.
* none
=> k8s: Use new env-test script

src/go/rpk/pkg/cli/cmd/cluster/maintenance/disable.go, src/go/rpk/pkg/cli/cmd/cluster/maintenance/enable.go
Fixes #8923.
Original commit 089f66a does, 
* `rpk cluster maintenance enable x` shows `Successfully enabled maintenance mode for node` once the node actually starts draining partitions.
* When the target node is dead, it fails with `Error retrieving broker status. The node x is likely dead?` 
* When `-w` is passed, `All partitions on node %d have drained.` will be printed once it's done.
Changes in 46add3d 
* `rpk cluster maintenance enable x`
* exits when the node x is dead
* returns `Successfully enabled maintenance mode for node %d. Check the partition draining status with 'rpk cluster maintenance status'.` once the command succeeds
* Improve UX in `rpk cluster maintenance` commands
=> rpk: Better UX in switching maintenance mode 

src/v/storage/segment_reader.cc, src/v/storage/segment_reader.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/8790
Fixes https://github.com/redpanda-data/redpanda/issues/8864,
=> [v22.2.x] s/segment_reader: gate in-flight operations

src/go/k8s/tests/e2e/update-image-and-node-port/00-assert.yaml, src/go/k8s/tests/e2e/update-image-and-node-port/02-assert.yaml, src/go/k8s/tests/e2e/update-image-and-node-port/03-assert.yaml, src/go/k8s/tests/e2e/update-image-and-node-port/04-assert.yaml, src/go/k8s/tests/e2e/update-image-and-node-port/05-assert.yaml, src/go/k8s/tests/e2e/update-image-tls-client-auth/00-assert.yaml, src/go/k8s/tests/e2e/update-image-tls-client-auth/02-assert.yaml, src/go/k8s/tests/e2e/update-image-tls-client-auth/03-assert.yaml, src/go/k8s/tests/e2e/update-image-tls-client-auth/04-assert.yaml, src/go/k8s/tests/e2e/update-image-tls-client-auth/05-assert.yaml, src/go/k8s/tests/e2e/update-image-tls/00-assert.yaml, src/go/k8s/tests/e2e/update-image-tls/02-assert.yaml, src/go/k8s/tests/e2e/update-image-tls/03-assert.yaml, src/go/k8s/tests/e2e/update-image-tls/04-assert.yaml, src/go/k8s/tests/e2e/update-image-tls/05-assert.yaml, src/go/k8s/webhooks/redpanda/console_webhook.go, src/go/k8s/webhooks/redpanda/validate_enterprise.go, src/go/k8s/webhooks/redpanda/validate_enterprise_test.go
Console customer resource controller uses finalizers to stop deletion.
The main reason for finalizers is that controller is creating resources
outside of the k8s api. First resource is ACL and second is service account.
In order to correctly remove those resource the cluster reference, which is
part of the console spec, is used to build Admin API and Kafka client. Once
those resources are removed the finalizers should be removed. The problem
with such scenario is that finzalizers are removed by invoking client.Update
method. On the k8s api server side it triggeres an webhook for console. Due
to the fact that user trigger deletion webhook shouldn't check anything and
should pass immediately.
Additionally small fix to the reporting of prometheus secret reference.
None.
* Do not validate …
=> Fix console deletion validation

src/go/k8s/Dockerfile, src/go/k8s/Makefile, src/go/k8s/go.mod, src/go/k8s/go.sum, src/go/k8s/hack/install-cert-manager.sh, src/go/k8s/hack/wait-for-webhook-ready.sh, src/go/k8s/main.go, src/go/k8s/pkg/resources/configuration/configuration_test.go, src/go/k8s/pkg/resources/resource.go, src/go/k8s/pkg/resources/statefulset_update.go, src/go/k8s/pkg/utils/patch.go
Over the course of 12 hours, the operator has been building up memory utilization to the point where it's being OOM killed.
This PR changes the `patch` library usage to allow the GOGC to clean up compressed blobs that are no longer needed.
Fixes #9137 
* Fix a memory leak in the operator
=> operator: fix memory leak related to the patch library

src/v/cluster/persisted_stm.cc, src/v/raft/state_machine.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/8271 and https://github.com/redpanda-data/redpanda/pull/8296
=> [v22.3.x] raft: fix handle_eviction in snapshots

tests/rptest/services/redpanda_installer.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/9118
=> [v23.1.x] redpanda_installer: update tgz url

tests/rptest/services/redpanda_installer.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/9118
=> [v22.3.x] redpanda_installer: update tgz url

README.md, tests/rptest/services/redpanda_installer.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/6343
=> [v22.2.x] Update package download URL

tests/rptest/services/redpanda_installer.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/9118
=> [v22.2.x] redpanda_installer: update tgz url

src/v/utils/hdr_hist.cc, src/v/utils/hdr_hist.h, src/v/utils/tests/CMakeLists.txt, src/v/utils/tests/seastar_histogram_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9192
=> [v23.1.x] metrics: ensure consistent histogram upper bounds

tests/rptest/services/verifiable_consumer.py, tests/rptest/tests/end_to_end.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/9034
Fixes https://github.com/redpanda-data/redpanda/issues/9259,
=> [v23.1.x] Support CG rebalancing while verifiable consumer with many nodes is shutting down

src/v/cloud_storage/remote.cc, src/v/cloud_storage/remote.h, src/v/cloud_storage_clients/configuration.cc, src/v/cloud_storage_clients/configuration.h, src/v/cloud_storage_clients/tests/CMakeLists.txt, src/v/cloud_storage_clients/tests/backend_detection_test.cc, src/v/config/configuration.cc, src/v/config/configuration.h, src/v/config/convert.h, src/v/config/property.h, src/v/config/rjson_serialization.cc, src/v/config/rjson_serialization.h, src/v/model/metadata.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/9209
=> [v23.1.x] cloud_storage: Add storage backend inference

src/go/k8s/pkg/resources/statefulset_update.go
During rolling upgrade there might be race condition between operator reconcilliation with rpk library retry and postStart hook. The hook could disable maintenance mode, but when operator retries it will put back the maintenance mode. This change tries to unblock upgrade procedure.
* none
=> k8s: Remove maintenance mode during rolling upgrade

tests/rptest/scale_tests/partition_balancer_scale_test.py
Followup to https://github.com/redpanda-data/redpanda/pull/9257
* none
=> tests: fix partition count in partition_balancer_scale_test.py

src/v/cluster/metrics_reporter.cc, src/v/config/config_store.h, tests/rptest/tests/metrics_reporter_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/8846
=> [v23.1.x] Add config properties to metrics report

src/v/kafka/server/tests/produce_consume_test.cc
Saw this when backporting the https://github.com/redpanda-data/redpanda/pull/9264:
```
INFO  2023-03-07 09:39:41,835 [shard 0] raft - [group_id:1, {kafka/test-topic/0}] vote_stm.cc:264 - becoming the leader term:3
DEBUG 2023-03-07 09:39:41,835 [shard 0] raft - [group_id:1, {kafka/test-topic/0}] consensus.cc:2626 - triggering leadership notification with term: 3, new leader: {{id: {1}, revision: {5}}}
DEBUG 2023-03-07 09:39:41,835 [shard 0] raft - [group_id:1, {kafka/test-topic/0}] consensus.cc:2156 - Replicating group configuration {current: {voters: {{id: {1}, revision: {5}}}, learners: {}}, old:{nullopt}, revision: 5, update: {nullopt}, version: 4, brokers: {{id: 1, kafka_advertised_listeners: {{:{host: 127.0.0.1, port: 9092}}}, rpc_address: {host: 127.0.0.1, port: 33145}, rack: …
```
=> test_offset_for_leader_epoch: make wait for leader more robust

src/v/kafka/server/tests/produce_consume_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9304
=> [v23.1.x] test_offset_for_leader_epoch: make wait for leader more robust

src/v/cluster/members_manager.cc
Regression introduced by ece6f648ee5f (not in other release branches).
The check that compares whether the added node id is self is done on a wrong class member that is always 0.
cmd.key is always 0, so the bug was manifesting as missing connections on node with node_id 0 when new nodes are added as a part of node_ops_fuzz. This was detected by stuck decommissions trying to move partitions from a node with missing tcp client.
* none
=> c/members_mgr: fix buggy conn cache updates on node additions

tests/rptest/archival/s3_client.py
=> Test: check endpoint is not none for gcp storage before deleting objects

src/v/redpanda/admin/api-doc/config.json, src/v/redpanda/admin_server.cc, src/v/redpanda/admin_server.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/9331
=> [v23.1.x] admin: Add blocked_reactor_notify_ms command

src/go/k8s/tests/e2e/additional-configuration/verify-config-dev.sh, src/go/k8s/tests/e2e/additional-configuration/verify-config-v22.1.sh, src/go/k8s/tests/e2e/additional-configuration/verify-config-v22.2.sh, src/go/k8s/tests/e2e/additional-configuration/verify-config-v22.3.sh, src/go/k8s/tests/e2e/additional-configuration/verify-config-v23.1.sh, src/go/k8s/tests/e2e/additional-configuration/verify-config.sh
Fix some linter errors that were merged to main
* none
=> k8s: fix shfmt linter errors

src/go/rpk/pkg/cli/cmd/debug/bundle/bundle_linux.go, src/go/rpk/pkg/config/schema.go, src/go/rpk/pkg/config/weak.go, src/go/rpk/pkg/config/weak_test.go, tests/rptest/services/redpanda.py, tests/rptest/tests/rpk_start_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7719
Fixes https://github.com/redpanda-data/redpanda/issues/9368,
=> [v23.1.x] rpk: do not modify redpanda.rpc_server_tls field

tests/rptest/services/verifiable_consumer.py, tests/rptest/tests/end_to_end.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/9034
Fixes https://github.com/redpanda-data/redpanda/issues/9358,
=> [v22.2.x] Support CG rebalancing while verifiable consumer with many nodes is shutting down

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/8782
Fixes https://github.com/redpanda-data/redpanda/issues/8828,
=> [v22.2.x] Filter out version queries when asking for Redpanda pid

src/v/test_utils/async.h
Previously, we slept but sometimes saw that the sleep was insufficient: this was addressed in
https://github.com/redpanda-data/redpanda/pull/8464
However, it appears that sometimes in debug mode tests can still not see the ordering they expect, probably because of the scheduler's shuffle().  So in debug mode, reinstate the simple sleep(10ms), in addition to the inter-CPU task calls that aim to flush preceding work.
In this PR run (https://buildkite.com/redpanda/redpanda/builds/24705#0186c6a7-e6dc-42d5-b9b1-bf65c3d3b7bc) the order of execution doesn't make sense wrt the calls to flush_tasks() in a test that advances a manual_clock, and then expects resulting futures to have fired on the other side of a flush_tasks() call.  In #8464 we discussed that the seastar scheduler will shuffle tasks …
=> test_utils: sleep in debug mode in flush_tasks

src/v/archival/ntp_archiver_service.cc, tests/rptest/tests/cloud_retention_test.py
CONFLICT:
- Reconciling the genericizing of s3_client in ducktape
Backports:
- https://github.com/redpanda-data/redpanda/pull/8968
- https://github.com/redpanda-data/redpanda/pull/8993
* Fixed an issue that could prevent uploads after all cloud segments have been garbage collected.
=> [v22.3.x] archival: always use last_offset if available to schedule uploads

src/v/raft/consensus.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9384
Fixes https://github.com/redpanda-data/redpanda/issues/9390,
=> [v22.3.x] Do not update follower received sequence if not leader

src/v/raft/consensus.cc, src/v/raft/follower_stats.h, src/v/raft/types.cc, src/v/raft/types.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/9273
Backport of PR https://github.com/redpanda-data/redpanda/pull/9384
=> [v22.2.x] Added test verifying behavior when data folder is lost + Do not update follower received sequence if not leader

tests/rptest/tests/cloud_storage_usage_test.py
This test had two issues:
1. PR #9514 changed the manifest upload logic. For partitions, with high segment throughput (like the ones in the test), manifest uploads can be delayed by `cloud_storage_manifest_max_upload_interval_sec` (60s by default). The test expects more timely manifest updates. This is fixed by configuring the cluster to upload the manifest more often.
2. The test checked the `start_offset(s)` present in the partition manifest in order to ensure that retention had kicked in by the end of the test. When considering, adjacent segment merging this is problematic because the test can end with no segments in the manifest (and hence no `start_offset` to check against). This has been fixed by checking the metric for cloud segment deletions instead.
Fixes #9385 
* none
=> rptest: fix CloudStorageUsageTest timeouts

src/v/cluster/members_backend.cc, src/v/cluster/members_backend.h, src/v/cluster/members_manager.cc, src/v/cluster/members_manager.h, src/v/cluster/scheduling/allocation_node.cc, tests/rptest/services/admin_ops_fuzzer.py
Previously we did not set configuration revion when changing raft_0 configuration. With the new controller command based configuration handling we use raft_0 revisions to check if the update was already applied. Fixed incorrect handling of revisions update before the command based configuration feature is active leading to backward incompatibility and assert.
Fixes: #9336
- none
=> Do not set revision when using raft0 base cluster configuration

src/go/rpk/pkg/cli/cmd/debug/bundle/bundle_k8s_linux.go
We were using IPs but that's not suitable for
brokers with TLS enabled since the IP won't be
in the certificate.
Instead, we are going to use the FQDN to talk to
the rest of the cluster's admin API addresses.
* rpk bugfix: now `rpk debug bundle` in k8s works for brokers with TLS enabled.
=> rpk/debug bundle: use FQDN in admin API addresses

src/v/archival/ntp_archiver_service.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9409
=> [v23.1.x] archival: Avoid reuploading if log is truncated

src/go/rpk/pkg/cli/cmd/debug/bundle/bundle_k8s_linux.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/9320
=> [v23.1.x] rpk/debug bundle: use FQDN in admin API addresses

src/v/cluster/members_manager.cc, src/v/raft/replicate_entries_stm.cc, tests/rptest/services/redpanda.py, tests/rptest/tests/nodes_decommissioning_test.py, tests/rptest/utils/node_operations.py
Backporting: https://github.com/redpanda-data/redpanda/pull/7949
Fixes: #9166
Backport of PR https://github.com/redpanda-data/redpanda/pull/8547
Fixes https://github.com/redpanda-data/redpanda/issues/9394,
* none
=> [V22.3.x] Backport of #7949, #8547

tests/rptest/tests/cloud_storage_usage_test.py
This commit tweaks the CloudStorageUsage tests to maintain a sliding window of the reported usages and check if the usage inferred from the manifest is present in the window. Even after the previous fixes, we've seen failures due to the uploaded manifest lagging behind.
The size of the sliding window allows the test to "look back" in time by 2 seconds. Manifest uploads are performed every 1 second, so this should be more than enough.
Fixes #9385 
* none
=> rptest: relax cloud storage usage checks

src/go/rpk/pkg/cli/cmd/debug/bundle/bundle_linux.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/9448
=> [v23.1.x] rpk: redact SCRAM credentials in debug bundle

src/go/rpk/pkg/cli/cmd/debug/bundle_linux.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/9448
=> [v22.3.x] rpk: redact SCRAM credentials in debug bundle

src/go/rpk/pkg/cli/cmd/debug/bundle_linux.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/9448
=> [v22.2.x] rpk: redact SCRAM credentials in debug bundle

src/v/kafka/client/consumer.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9105 to branch v23.1.x. (just the bugfix)
Fixes https://github.com/redpanda-data/redpanda/issues/9310
=> [v23.1.x] Backport #9105 bugfix

src/v/kafka/client/consumer.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9105 to branch v22.3.x. (just the bugfix)
Fixes https://github.com/redpanda-data/redpanda/issues/9310
=> [v22.3.x] Backport #9105 bugfix

tests/rptest/clients/rpk.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/8963
Fixes: #9285
=> [v22.3.x] Fix for CI issue in ManyPartitionsTest where DescribeGroups request fails

src/go/k8s/apis/redpanda/v1alpha1/cluster_webhook.go
Set `redpanda.default_topic_replications` on newly created `Cluster` resources if not already set.
* none
=> set default_topic_replications if not set

src/go/k8s/apis/redpanda/v1alpha1/cluster_webhook.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/9488
=> [v23.1.x] set default_topic_replications if not set

.github/workflows/rpk-build.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/9514
=> [v23.1.x] override goreleaser tag

.github/workflows/rpk-build.yml
Backport of PR https://github.com/redpanda-data/redpanda/pull/9514
=> [v22.3.x] override goreleaser tag

src/v/archival/segment_reupload.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9566
Fixes https://github.com/redpanda-data/redpanda/issues/9577,
=> [v23.1.x] archival: lock segments before opening readers

tests/rptest/tests/cluster_config_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/9581
=> [v23.1.x] rptest: tweak allow list of ABS key change test

src/v/compression/internal/lz4_frame_compressor.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9563
Fixes https://github.com/redpanda-data/redpanda/issues/9595,
=> [v23.1.x] compression: use fragmented allocation in LZ4 decompress

src/v/cloud_storage/tx_range_manifest.cc, src/v/cloud_storage/tx_range_manifest.h, src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h
Addressing some comments post merge.
* none
=> (addendum) rm_stm: replace std::vector usage with fragmented_vector

.github/workflows/kics-iac.yml
Adds KICS IaC scanning to Redpanda repo.
=> Adds KICS IaC scanning

src/v/archival/ntp_archiver_service.cc, src/v/archival/retention_calculator.cc, src/v/redpanda/admin_server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9615
=> [v23.1.x] archival: improve cloud retention logging

tests/rptest/utils/node_operations.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/9311
Fixes https://github.com/redpanda-data/redpanda/issues/9401,
=> [v23.1.x] ducktape/node_ops: fix draining state check

tests/rptest/services/redpanda.py, tests/rptest/tests/redpanda_multi_region_test.py, tests/rptest/utils/cluster_topology.py
Added basic utilities allowing to simulate mulit-region multi-az topology in ducktape tests. The topology utility leverages Linux traffic control utility i.e. `tc` to introduce artificial delay and packet loss between nodes.
Fixes: https://github.com/redpanda-data/core-internal/issues/398
* none
=> Cluster topology in ducktape

tests/rptest/services/verifiable_consumer.py, tests/rptest/tests/end_to_end.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/9034
Fixes https://github.com/redpanda-data/redpanda/issues/9280,
=> [v22.3.x] Support CG rebalancing while verifiable consumer with many nodes is shutting down

src/go/rpk/pkg/cli/cmd/topic/consume.go
* If a ListOffsets request succeeds, but the partitions with them have failures, we should fail. kadm.ListOffsets* skips any unknown topics, so we should only have partition errors if something problematic is up.
* If an offset is `-o @:-1h`, we want to consume from the start to 1hr ago. Previously, we would not consume from the start. We now list start offsets in this case and properly consume from the start. This also allows us to exit early if there is nothing to consume: filterEmptyPartitions previously did not filter without the start offsets.
* Expands the duration parsing docs because it was a bit confusing.
* rpk now properly handles `-o @:-1h` to consume from the start to one hour ago
=> rpk topic consume: offset parsing fixups

src/v/cluster/id_allocator_stm.cc, src/v/cluster/rm_stm.cc, src/v/cluster/tm_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9656
Fixes https://github.com/redpanda-data/redpanda/issues/9678,
=> [v23.1.x] Added missing set for _in_sync offset in stms

src/v/config/configuration.cc, src/v/config/configuration.h, src/v/redpanda/CMakeLists.txt, src/v/redpanda/application.cc, src/v/redpanda/application.h, src/v/redpanda/monitor_unsafe_log_flag.cc, src/v/redpanda/monitor_unsafe_log_flag.h, src/v/utils/CMakeLists.txt, src/v/utils/utf8.cc, src/v/utils/utf8.h, tests/rptest/services/redpanda.py, tests/rptest/tests/control_character_flag_test.py
Added new flag that permits unsafe log operations by permitting control characters in
user provided strings.
Force push `739bc4a`:
* Fixed lint error
Force push `93bc374`:
* Fixed failing test (missing `cluster`)
Force push `edce768`:
* Added `legacy_unsafe_log_warning_interval_sec` flag
* Removed the `__REDPANDA_FLAG_NAG_CHECK_INTERVAL_SEC` env variable
* Added comment
* Cherry-picked [89839a5](https://github.com/redpanda-data/redpanda/pull/9655/commits/89839a52ac3c8b9de03ed8abc71b2260b8953ec6)
* Test updates
* None
=> config: Add legacy log permission flag

src/v/cluster/partition.cc, tests/rptest/tests/read_replica_e2e_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/9684
=> [v23.1.x] archival: instantiate archiving even when no shadow indexing

src/v/storage/segment.cc
This commit fixes a race between segment rolls (releasing the appender, more specifically) and `puts` to the `readers_cache` from the read path.
Previously, `segment::release_appender_in_background` did not hold on to the readers cache lock while acquiring the segment write lock. If the entry was inserted into the cache before the write lock request was registered into the waiters list, then the write lock would only be granted after the the new entry was evicted from the `readers_cache` (30 seconds is the default eviction timeout).
Having a write lock sit in the waiters list also blocks all read lock requests that come in after it. This had knock-on effects to the cloud storage upload path, which expects to be able to acquire segment read locks within 30 seconds.
* Fix a rare race …
=> storage: fix race between rolls and readers cache

src/v/storage/segment.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9676
=> [v23.1.x] storage: fix race between rolls and readers cache

src/v/cluster/topic_table.cc
If topic property update command is redundant i.e. it does not change any of the topic properties its delta may not be generated as it is irrelevant and would be a no op.
* Makes starting Redpanda with long controller log containing redundant topic properties update faster
=> c/topics_table: do not generate deltas for no op update properties

src/go/k8s/controllers/redpanda/cluster_controller.go
Node ID annotation which is set in Redpanda PODs could be not updated
if underlaying data folder is gone. That can happen e.g. in GKE when local
SSDs are used as PersistentVolumes and VM is repaired by Instance Group
Manager.
* Always reconcile Node ID annotation in Redpanda POD
=> k8s: Always update annotation if node ID does not match

tests/rptest/tests/scaling_up_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/7430
=> [v22.3.x] Changed rebalancing timeout in scaling up test

src/v/archival/tests/archival_metadata_stm_test.cc, src/v/archival/tests/ntp_archiver_reupload_test.cc, src/v/archival/tests/ntp_archiver_test.cc, src/v/archival/tests/service_fixture.cc, src/v/archival/tests/service_fixture.h, src/v/cloud_storage/remote.cc, src/v/cloud_storage/remote.h, src/v/cloud_storage/tests/cloud_storage_fixture.h, src/v/cloud_storage/tests/remote_partition_fuzz_test.cc, src/v/cloud_storage/tests/remote_partition_test.cc, src/v/cloud_storage/tests/remote_segment_test.cc, src/v/cloud_storage/tests/remote_test.cc, src/v/cloud_storage/tests/util.h, src/v/cloud_storage_clients/client_pool.cc, src/v/cloud_storage_clients/client_pool.h, src/v/cloud_storage_clients/client_probe.cc, src/v/cloud_storage_clients/client_probe.h, src/v/cloud_storage_clients/logger.h, src/v/cloud_storage_clients/tests/CMakeLists.txt, src/v/cloud_storage_clients/tests/client_pool_mt_test.cc, src/v/cloud_storage_clients/tests/s3_client_test.cc, src/v/redpanda/application.cc, src/v/redpanda/application.h
The `client_pool` is turned into a `peering_service` so individual pools can exchange information and borrow unused connections to each other. Every `client_pool` maintains stats so it can make informed decisions based on it.
We're going to increase number of uploaded artefacts per segment to 3. Because of that it's more likely that individual shards will be running out of connections to S3. This can be helped by balancing connections between different shards.
This PR only introduces the mechanism without enabling it. More testing is needed in order to enable it.
* Cloud storage connections are balanced between the shards according to workload
=> cloud_storage: Connection balancing

src/v/archival/ntp_archiver_service.cc
The upload loop needs to sync before doing anything in a given term, otherwise it is liable to upload inconsistent state. I noticed this in an upcoming test with read replicas, that after a restart of the source cluster a node became leader, and then immediately uploaded an empty manifest, resulting in an error log from the read replica:
```
ERROR 2023-03-30 21:54:04,489 [shard 1] archival - [fiber3 kafka/panda-topic/0] - ntp_archiver_service.cc:510 - Ignoring remote manifest.json contents: last_offset 0 behind lastseen last_offset 1031 (remote insync_offset -9223372036854775808)
```
* none
=> archival: sync before first manifest upload

src/v/cluster/members_backend.cc, src/v/cluster/members_backend.h, src/v/cluster/topic_table.cc, tests/rptest/tests/scaling_up_test.py
Backport of the follwing PRs.
Backporting: 
- https://github.com/redpanda-data/redpanda/pull/9515
- https://github.com/redpanda-data/redpanda/pull/9739
- https://github.com/redpanda-data/redpanda/pull/9344
- none
=> [v22.3.x] Backport of #9739 #9515 #9344

src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/prevote_stm.cc, src/v/raft/recovery_stm.cc, src/v/raft/replicate_entries_stm.cc, src/v/raft/types.h, src/v/raft/vote_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9254
=> [v23.1.x] Validate raft response node

src/v/raft/consensus.cc, src/v/raft/follower_stats.h, src/v/raft/types.cc, src/v/raft/types.h, tests/rptest/tests/node_folder_deletion_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/9273
=> [v23.1.x] Added test verifying behavior when data folder is lost 

src/go/rpk/pkg/cli/cmd/cluster/storage/recovery/status.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/9795
=> [v23.1.x] rpk: fix command name in cluster storage recovery

src/v/cloud_storage/segment_meta_cstore.cc, src/v/cloud_storage/segment_meta_cstore.h, src/v/cloud_storage/tests/segment_meta_cstore_test.cc
segment_meta_cstore now support inserting entries that replaces previously inserted one. these new entries have to be [base_offset, committed_offset] aligned to a group of pre-existing entries.
insertion is performed by cloning the old frames up to the frame containing entries that will be replaced. after that, the rest of the frames are rebuilt by merging in the new segment_meta and discarding the one replaced. 
To speed up this operation, a write_buffer is used to buffer operations so as to coalesce various operations into one rebuild.
Fixes #9422 
* none
=> cloud_storage/segment_meta_cstore: support for insert in the middle via a write_buffer

src/go/rpk/pkg/api/admin/api_user.go
RPK should have the ability to update users.
* none
=> feat: create update user function in admin api obj

src/go/k8s/controllers/redpanda/cluster_controller.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/9814
=> [v23.1.x] k8s: Fix first pod annotation

tests/rptest/tests/read_replica_e2e_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/9834
Fixes https://github.com/redpanda-data/redpanda/issues/9843,
=> [v23.1.x] read_replica_e2e_test: remove bad assertion

tests/rptest/tests/read_replica_e2e_test.py
NOT ON DEV
Fixes a botched cherry-pick:
- CloudStorageType does not exist in this branch
- set cloud_storage_housekeeping_interval_ms after upgrade, since it
doesn't exist on v22.2
- removed assertion bad assertion
Fixes #9821
* none
=> [v22.3.x] tests: fix botched cherry-pick

src/v/cluster/controller_backend.cc
Setting partition properties if a partition instance is available on the
shard no matter what is the current partition assignment. Previously
partition replicas that the partition was moved from didn't have the
properties set. Additionally fixed calculating bootstrap deltas now we
newer stop on properties update command and always look further in the
list of partition deltas.
- none
=> Fix calculating bootstrap deltas

tests/rptest/services/redpanda.py
Previously a version check pid might have been returned.
Fixes: #9806
- none
=> tests/redpanda: only return redpanda pid from `pids()` method

tests/rptest/tests/nodes_decommissioning_test.py
Waiting for all the nodes reporting that the node is being decommissioned.
Fixes: #9424 
Fixes: #9752
* none
=> tests: made decommissioning operation more reliable

src/go/k8s/pkg/resources/certmanager/type_helpers.go
This is to enable sharing of certificates between listeners, instead of creating one per listener type. It allows configuring one TLS certificate e.g. on the Redpanda listener, then reuse it on other listeners by referencing the corresponding secret.
The problem is that the operator requires that the secret is already present before the cluster is created, while normally controllers don't enforce this rule (e.g. the statefulset or pod controllers just wait for the secret to be created). If the operator blocks the reconciliation, we cannot reference a secret that will eventually be injected into the cluster, like secrets generated by cert-manager.
The reason why the operator needs the secret is for checking if it's self-signed or not (i.e. is `ca.crt` present in the secret?). We can assume …
=> operator: do not fail if certificate secret is not yet created

src/v/raft/probe.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9747
=> [v22.3.x] consensus: Add some missing metrics to the probe

src/v/pandaproxy/error.cc, src/v/pandaproxy/error.h, src/v/pandaproxy/schema_registry/error.cc, src/v/pandaproxy/schema_registry/error.h, src/v/pandaproxy/schema_registry/handlers.cc, src/v/pandaproxy/schema_registry/requests/post_subject_versions.h, src/v/pandaproxy/schema_registry/requests/test/post_subject_versions.cc, src/v/pandaproxy/schema_registry/seq_writer.cc, src/v/pandaproxy/schema_registry/seq_writer.h, src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h, src/v/pandaproxy/schema_registry/test/CMakeLists.txt, src/v/pandaproxy/schema_registry/test/client_utils.h, src/v/pandaproxy/schema_registry/test/post_subjects_subject_version.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9691
Fixes https://github.com/redpanda-data/redpanda/issues/9825,
=> [v23.1.x] schema_registry: Allow a schema id and version to be supplied

src/v/pandaproxy/error.cc, src/v/pandaproxy/error.h, src/v/pandaproxy/schema_registry/error.cc, src/v/pandaproxy/schema_registry/error.h, src/v/pandaproxy/schema_registry/handlers.cc, src/v/pandaproxy/schema_registry/requests/post_subject_versions.h, src/v/pandaproxy/schema_registry/requests/test/post_subject_versions.cc, src/v/pandaproxy/schema_registry/seq_writer.cc, src/v/pandaproxy/schema_registry/seq_writer.h, src/v/pandaproxy/schema_registry/sharded_store.cc, src/v/pandaproxy/schema_registry/sharded_store.h, src/v/pandaproxy/schema_registry/test/CMakeLists.txt, src/v/pandaproxy/schema_registry/test/client_utils.h, src/v/pandaproxy/schema_registry/test/post_subjects_subject_version.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9691
Fixes https://github.com/redpanda-data/redpanda/issues/9825,
Added a couple of commits from #7159
=> [v22.2.x] schema_registry: Allow a schema id and version to be supplied

src/v/cluster/cluster_utils.h, src/v/cluster/controller_backend.cc, src/v/cluster/controller_backend.h, src/v/cluster/controller_snapshot.cc, src/v/cluster/controller_snapshot.h, src/v/cluster/partition_balancer_state.cc, src/v/cluster/partition_balancer_state.h, src/v/cluster/partition_leaders_table.cc, src/v/cluster/partition_leaders_table.h, src/v/cluster/scheduling/allocation_state.cc, src/v/cluster/scheduling/allocation_state.h, src/v/cluster/scheduling/partition_allocator.cc, src/v/cluster/scheduling/partition_allocator.h, src/v/cluster/scheduling/types.cc, src/v/cluster/scheduling/types.h, src/v/cluster/topic_table.cc, src/v/cluster/topic_table.h, src/v/cluster/topic_updates_dispatcher.cc, src/v/cluster/types.cc, src/v/cluster/types.h, src/v/coproc/reconciliation_backend.cc, tests/rptest/tests/controller_snapshot_test.py, tests/rptest/tests/partition_movement_test.py, tests/rptest/tests/random_node_operations_test.py
Add topics-related data to controller snapshots.
* none
=> Controller snapshots: topics

src/go/k8s/tests/e2e/regressions/00-assert.yaml, src/go/k8s/tests/e2e/regressions/00-redpanda-cluster.yaml, src/go/k8s/tests/e2e/regressions/01-assert.yaml, src/go/k8s/tests/e2e/regressions/01-call-controller-status.yaml
Fixes https://github.com/redpanda-data/redpanda/issues/9781
* none
=> Operator: feat -  add new tests to verify reconcile loop does not grow uncontrollably

src/v/cluster/id_allocator_stm.cc, src/v/cluster/rm_stm.cc, src/v/cluster/tm_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9656
Fixes https://github.com/redpanda-data/redpanda/issues/9680,
=> [v22.3.x] Added missing set for _in_sync offset in stms

src/v/kafka/server/group.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9851
Fixes https://github.com/redpanda-data/redpanda/issues/9859,
=> [v23.1.x] Fix 9850: return committed_leader_epoch on offset_fetch

src/v/cloud_storage/tests/remote_partition_test.cc
Backport of PR #8527
None
* none
=> [v22.3.x] Backport #8527 (cloud storage test fix)

src/v/redpanda/admin/api-doc/broker.json, src/v/redpanda/admin_server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9797
Fixes https://github.com/redpanda-data/redpanda/issues/9810,
=> [v23.1.x] admin: include internal RPC endpoint in /v1/brokers

src/v/config/configuration.cc, src/v/config/tests/validator_tests.cc, src/v/config/validators.cc, src/v/config/validators.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/9710
=> [v23.1.x] config: validate that strings are non-empty

src/v/kafka/server/group.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9851
Fixes https://github.com/redpanda-data/redpanda/issues/9861,
=> [v22.3.x] Fix 9850: return committed_leader_epoch on offset_fetch

src/v/compression/internal/gzip_compressor.cc, src/v/compression/internal/lz4_frame_compressor.cc, src/v/compression/tests/zstd_stream_bench.cc, src/v/compression/tests/zstd_tests.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9598
=> [v23.1.x] compression: fix bad_allocs in lz4 compression, gzip compression+decompression

src/v/cluster/id_allocator_stm.cc, src/v/cluster/rm_stm.cc, src/v/cluster/tm_stm.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9656
Fixes https://github.com/redpanda-data/redpanda/issues/9682,
=> [v22.2.x] Added missing set for _in_sync offset in stms

src/v/http/client.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9903
=> [v22.2.x] http: Close output stream in exceptional cases

src/v/http/client.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9903
=> [v22.3.x] http: Close output stream in exceptional cases

tests/rptest/services/redpanda_installer.py
This fixes running many repeats of upgrade tests, which will otherwise get 403s from github's rate limiting.
The caching I previously added was process-wide, which ignored the way that ducktape spawns subprocesses for tests.
To share the cache across processes, use an on-disk cache, protected by the same lock file as other installer disk content.  I've left the original caching in there too, as in principle tests could end up reading concurrently from different threads and/or the code might get reused in a different context.
* none
=> tests: file cache of github releases

tests/rptest/tests/scaling_up_test.py
Partitions are balanced separately in each allocation domain since #5460. The change in this PR evaluates whether the partitions are balanced well enough within each of the allocation domains.
How topics are assigned to allocation domains is currently hardcoded: `__consumer_offsets` belongs to domain `-1`, all the rest belong to domain `0`. If that becomes more complicated, there should be a better way to determine allocation domain association than this.
The ±20% range rule is preserved for each domain, but is somewhat relaxed by rounding the boundary values outwards. This is required to handle small partition counts, e.g. 3 partitions for 2 nodes would otherwise give range of [1.2, 1.8] which no integer value will satisfy; the rounding makes that range [1, 2] instead.
Fixes #7418.
* …
=> Support for allocation domains in scaling_up_tests

src/go/k8s/pkg/resources/certmanager/type_helpers.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/9847
=> [v23.1.x] operator: do not fail if certificate secret is not yet created

src/v/redpanda/admin/api-doc/security.json, src/v/redpanda/admin_server.cc, src/v/security/scram_credential.h, tests/rptest/services/admin.py, tests/rptest/tests/admin_api_auth_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/9936
=> [v22.3.x] admin: Exclude ephemeral users from list_users

tests/rptest/tests/random_node_operations_test.py
Replaced Verifiable consumer/producer pair with more robust and easier to use KgoVerifier service. Also merged running with compacted and regular topics in a single test run.
Fixes: https://github.com/redpanda-data/core-internal/issues/449
* none
=> tests: replaced verifiable consumer/producer with kgoverifier

src/v/cluster/controller.cc, src/v/cluster/controller_stm.cc, src/v/cluster/controller_stm.h
When redpanda is shutting down `cluster::controller_stm` shouldn't assert and cause redpanda to crash. Ignoring exceptions know to be related with shoutdown when thrown during snapshot application.
Additionally fixed a segfault that might happen when an STM tried to apply state to already destroyed `configuration_manager`
Fixes https://github.com/redpanda-data/redpanda/issues/9961
* none
=> c/controller_stm: do not assert on shutdown related exceptions

src/v/raft/configuration_manager.cc, src/v/raft/configuration_manager.h, src/v/raft/consensus.cc, src/v/raft/offset_translator.cc, src/v/raft/tests/configuration_manager_test.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9827
=> [v22.2.x] r/configuration_manager: add highest_known_offset checkpoint mutex

tests/rptest/tests/scaling_up_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/9947
Fixes https://github.com/redpanda-data/redpanda/issues/9968,
=> [v23.1.x] Support for allocation domains in scaling_up_tests

tests/rptest/tests/scaling_up_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/9947
Fixes https://github.com/redpanda-data/redpanda/issues/10011,
=> [v22.3.x] Support for allocation domains in scaling_up_tests

src/v/raft/consensus.cc
The same way as other RPC driven request the install snapshot request must be wrapped with the gate to prevent it from continuing execution after consensus is stopped.
Fixes: #10033
- none
=> Wrap install snapshot request with gate

src/v/storage/chunk_cache.h, src/v/storage/segment_appender.cc, src/v/storage/segment_utils.cc, src/v/storage/storage_resources.cc
The configuration value for `append_chunk_size` can change based on user configuration. This can leave different parts of Redpanda with different values for the `append_chunk_size`, which causes issues. This commit moves the source of truth for `append_chunk_size` from configuration to the `chunk_cache`. This ensures every part of RP has the same `append_chunk_size` value.
Fixes #10023
* none
=> Use `chunk_cache` as source of truth for chunk size

src/v/pandaproxy/error.cc, src/v/pandaproxy/error.h, src/v/pandaproxy/json/error.cc, src/v/pandaproxy/json/error.h, src/v/pandaproxy/json/requests/fetch.h, src/v/pandaproxy/json/rjson_util.h, src/v/pandaproxy/rest/test/consumer_group.cc, src/v/pandaproxy/rest/test/fetch.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9867
Fixes https://github.com/redpanda-data/redpanda/issues/10036,
=> [v23.1.x] Error checking pp json serialization

src/v/raft/recovery_stm.cc, src/v/raft/recovery_stm.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/9928
Fixes https://github.com/redpanda-data/redpanda/issues/10062,
=> [v23.1.x] Flush at set intervals in `recovery_stm`

src/v/pandaproxy/error.cc, src/v/pandaproxy/error.h, src/v/pandaproxy/json/error.cc, src/v/pandaproxy/json/error.h, src/v/pandaproxy/json/requests/fetch.h, src/v/pandaproxy/json/rjson_util.h, src/v/pandaproxy/rest/test/consumer_group.cc, src/v/pandaproxy/rest/test/fetch.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9867
Fixes https://github.com/redpanda-data/redpanda/issues/10037,
=> [v22.3.x] Error checking pp json serialization

src/v/pandaproxy/error.cc, src/v/pandaproxy/error.h, src/v/pandaproxy/json/error.cc, src/v/pandaproxy/json/error.h, src/v/pandaproxy/json/requests/fetch.h, src/v/pandaproxy/json/rjson_util.h, src/v/pandaproxy/rest/test/consumer_group.cc, src/v/pandaproxy/rest/test/fetch.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9867
Fixes https://github.com/redpanda-data/redpanda/issues/10040,
=> [v22.2.x] Error checking pp json serialization

src/v/cluster/drain_manager.cc, src/v/cluster/partition.cc, src/v/cluster/partition.h, src/v/cluster/scheduling/leader_balancer.cc, src/v/cluster/scheduling/leader_balancer.h, src/v/cluster/service.cc, src/v/compat/raft_compat.h, src/v/compat/raft_generator.h, src/v/raft/consensus.cc, src/v/raft/consensus.h, src/v/raft/types.h, src/v/redpanda/admin_server.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/10026
=> [v23.1.x] Add a `timeout` parameter to transfer_leadership_request

src/go/k8s/controllers/redpanda/cluster_controller.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/10054
=> [v23.1.x] k8s: fix bug where secret not initialized

src/v/cluster/scheduling/allocation_strategy.cc, src/v/cluster/scheduling/constraints.cc, src/v/cluster/scheduling/constraints.h, src/v/cluster/scheduling/types.cc, src/v/cluster/scheduling/types.h
Made an allocation constraints hierarchical with the root level of hierarchy being defined by set of hard constraints and the all subsequent levels with soft constraints. The hierarchical approach allows specifying explicitly the importance of a allocation constraints.
Fixes: https://github.com/redpanda-data/core-internal/issues/390
* Flexibility while defining topic constraints
=> Made soft allocation constraints fully hierarchical

tests/docker/ducktape-deps.sh
Updated kgo-verifier version to include:
- key set cardinality support
- compression
- fixes for repeater latency stats
- none
=> ducktape: updated kgo-verifier version

src/v/archival/ntp_archiver_service.cc
The order of operations needs to be:
1. Move segments to 'replaced' list
2. Upload manifest so that anyone reading the bucket no longer sees the to-be-removed segment as readable.
3. Actually delete the segments
Previously we were doing 1,3,2 instead of 1,2,3.
This is most obvious when doing an end-of-test validation of the bucket, because the validation tool sees what a read replica cluster would see: a manifest that points to segments that no longer exist.
There are some cases where we could avoid doing the manifest upload even if it is dirty, if it had been uploaded since the segment moved to the replaced list, but this would require tracking a segment-by-segment record of at what stm offset it was moved into the list, and would only rarely yield any perf benefit, as manifests are …
=> archival: sync manifest before GC'ing segments

src/v/cluster/members_backend.cc, src/v/cluster/members_backend.h
Backport of PR: https://github.com/redpanda-data/redpanda/pull/9992
- none
=> [v23.1.x] Backport of #9992

tests/rptest/services/openmessaging_benchmark.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/9949
Fixes https://github.com/redpanda-data/redpanda/issues/10120,
=> [v23.1.x] tests: permit OMB log error

src/v/raft/consensus.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/10034
Fixes https://github.com/redpanda-data/redpanda/issues/10050,
=> [v22.3.x] Wrap install snapshot request with gate

src/v/cloud_roles/refresh_credentials.h, src/v/config/configuration.cc, src/v/config/configuration.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/10146
Fixes https://github.com/redpanda-data/redpanda/issues/10152,
=> [v23.1.x] Make credentials endpoint configurable

cmake/FindAvro.cmake, cmake/FindHdrhistogram.cmake, src/v/kafka/CMakeLists.txt, src/v/kafka/protocol/CMakeLists.txt, src/v/pandaproxy/schema_registry/CMakeLists.txt
A few fixes for shared library support.
* none
=> A few fixes for shared library support

src/go/k8s/tests/e2e/superusers-prefix/01-assert.yaml, src/go/k8s/tests/e2e/superusers-prefix/01-redpanda-cluster.yaml, src/go/k8s/tests/e2e/superusers-prefix/02-assert.yaml
Backport of PR https://github.com/redpanda-data/redpanda/pull/10094
=> [v23.1.x] Improve readability for the failure test

src/go/k8s/tests/e2e/superusers-prefix/01-assert.yaml, src/go/k8s/tests/e2e/superusers-prefix/01-redpanda-cluster.yaml, src/go/k8s/tests/e2e/superusers-prefix/02-assert.yaml
Backport of PR https://github.com/redpanda-data/redpanda/pull/10094
=> [v22.3.x] Improve readability for the failure test

src/v/cluster/tm_stm.cc, src/v/cluster/tm_stm.h, src/v/cluster/tm_stm_cache.h, src/v/cluster/tx_gateway_frontend.cc, src/v/cluster/tx_gateway_frontend.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/10035
=> [v23.1.x] c/tm_stm: Convert tm_snapshot to fragmented_vector

src/v/cluster/tm_stm.cc, src/v/cluster/tm_stm.h, src/v/cluster/tm_stm_cache.h, src/v/cluster/tx_gateway_frontend.cc, src/v/cluster/tx_gateway_frontend.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/10035
=> [v22.3.x] c/tm_stm: Convert tm_snapshot to fragmented_vector

src/v/cloud_roles/refresh_credentials.h, src/v/cloud_roles/tests/fetch_credentials_tests.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/10162
=> [v23.1.x] cloud_roles: Initialize hostname with sstring

src/v/pandaproxy/json/requests/fetch.h, src/v/pandaproxy/rest/test/CMakeLists.txt, src/v/pandaproxy/rest/test/consumer_group.cc, src/v/pandaproxy/rest/test/fetch.cc, src/v/pandaproxy/schema_registry/storage.h, src/v/storage/parser_utils.cc, src/v/storage/parser_utils.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/10117
Fixes https://github.com/redpanda-data/redpanda/issues/10173,
=> [v23.1.x] Support compressed batches in kafka client

src/v/cluster/tests/backend_reallocation_strategy_test.cc
The test has been really slow in CI debug builds. Reduced the scale not to lose coverage but make the test faster to run.
* none
=> Reduced scale of backend reallocation strategy test

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/9084
Fixes https://github.com/redpanda-data/redpanda/issues/10204,
=> [v23.1.x] duck: stop process in node before starting rp with rpk

src/v/raft/consensus.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/10034
Fixes https://github.com/redpanda-data/redpanda/issues/10048,
=> [v23.1.x] Wrap install snapshot request with gate

tests/rptest/services/action_injector.py
Previously it could leave a node in state
where the process had been started but hadn't
finished starting up yet.  That caused the
post-test validation code to trip up trying
to access a node's admin API.
In general, it is valuable for our test primitives to leave the cluster in a well known state, so rather than tolerate this in the validation, I'm updating the action injector to wait for all nodes to be fully ready before returning.
Fixes https://github.com/redpanda-data/redpanda/issues/10087
* none
=> tests: improve action injector shutdown

tests/rptest/tests/cloud_storage_timing_stress_test.py
GH issue https://github.com/redpanda-data/redpanda/issues/10241
* none
=> rptest: Disable CloudStorageTimingStressTest

src/go/rpk/pkg/cli/redpanda/start.go
Improvement of error messages in rpk redpanda start when used alongside `tune` and `check`
Fixes #6445
* none
=> rpk: improve check/tune error messages in rp start

tests/go/go-kafka-serde/client.go, tests/go/go-kafka-serde/go.mod, tests/go/go-kafka-serde/go.sum
Updated go-kafka-serde client to wait for all messages to be produced or time out
Bug fix in test (so no release notes).
Fixes #10001 
Force push `69cb541`:
* Removed dead code
Force push `1b64af0`:
* Sending messages synchronously
* Added `--timeout` flag
Force push `c493531`:
* Removed errgroup for timeout
* Fixed up how timeout works
* Added some more log messages
Force push `bb134eb`:
* Additional cleanup from PR comments
Force push `1efb466`:
* Fixed comments
* none
=> send messages synchronously in go-kafka-serde client

src/v/kafka/server/group.cc
Error replicating cleanup/delete tombstone record is not a critical error that we should be logging with `ERROR` severity. In future we may add a retry mechanism in case when replication failed. For now we treat it as a best effort.
Fixes: #9839
- none
=> Log error replicating special records with warn severity

src/v/compression/stream_zstd.cc, src/v/storage/segment.cc, src/v/storage/storage_resources.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/10235
Fixes https://github.com/redpanda-data/redpanda/issues/10254,
=> [v22.3.x] storage: further compression fixes

src/go/k8s/Makefile, src/go/k8s/apis/redpanda/v1alpha1/webhook_suite_test.go, src/go/k8s/config/manager/kustomization.yaml, src/go/k8s/pkg/resources/resource_integration_test.go
The intent is to revert a few changes that were meant for quick development.
* none
=> k8s: clean to merge into dev

tests/go/go-kafka-serde/client.go, tests/go/go-kafka-serde/go.mod, tests/go/go-kafka-serde/go.sum
Backport of PR https://github.com/redpanda-data/redpanda/pull/10184
Fixes https://github.com/redpanda-data/redpanda/issues/10308,
=> [v22.3.x] send messages synchronously in go-kafka-serde client

src/v/cluster/node_status_backend.cc, src/v/http/client.cc, src/v/kafka/client/transport.h, src/v/net/batched_output_stream.cc, src/v/net/batched_output_stream.h, src/v/net/connection.cc, src/v/raft/consensus.cc, src/v/raft/heartbeat_manager.cc, src/v/raft/prevote_stm.cc, src/v/raft/prevote_stm.h, src/v/raft/vote_stm.cc, src/v/rpc/connection_cache.h, src/v/rpc/response_handler.h, src/v/rpc/rpc_compiler.py, src/v/rpc/service.h, src/v/rpc/test/netbuf_tests.cc, src/v/rpc/test/response_handler_tests.cc, src/v/rpc/test/rpc_gen_cycling_test.cc, src/v/rpc/transport.cc, src/v/rpc/transport.h, src/v/rpc/types.h
=> [22.3.x] RPC timeout diagnosis improvements

src/v/storage/disk_log_impl.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/10258
=> [v23.1.x] storage: refine retention_adjust_timestamps

src/v/compression/stream_zstd.cc, src/v/storage/segment.cc, src/v/storage/storage_resources.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/10235
Fixes https://github.com/redpanda-data/redpanda/issues/10252,
=> [v23.1.x] storage: further compression fixes

src/v/archival/ntp_archiver_service.cc
ERROR 2023-04-21 07:43:48,271 [shard 1] archival - [fiber5 kafka/panda-topic/3] - ntp_archiver_service.cc:604 - Can't replicate archival_metadata_stm configuration batch: Unable to replicate given state across cluster nodes
Spotted this in CI: it's fine if we fail to replicate a message: the next iteration will proceed as normal. Other such replication errors are also done at warn level.
* none
=> archival: demote replication error to warning

src/v/cluster/partition.cc, src/v/cluster/partition.h, src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h, src/v/raft/offset_translator.cc, tests/rptest/tests/idempotency_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/10232
Fixes https://github.com/redpanda-data/redpanda/issues/10273,
=> [v23.1.x] Fixed issue with offset translation that may lead to offset gaps

tests/rptest/tests/scaling_up_test.py
=> [v22.2.x] Support for allocation domains in scaling_up_tests (manual)

src/v/cloud_storage_clients/util.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/9991
Fixes https://github.com/redpanda-data/redpanda/issues/10045,
=> [v23.1.x] cloud_storage: handle 'partial message' errors

tests/rptest/scale_tests/tiered_storage_single_partition_test.py
This reproduces #10100 reliably because it has a good chance
that the shutdown will fall within a tiered storage upload.
* none
=> tests: add restart stress test for tiered storage uploads

src/v/cluster/members_backend.cc, src/v/cluster/partition.cc, src/v/cluster/partition.h, src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h, src/v/raft/offset_translator.cc, tests/rptest/tests/idempotency_test.py
Backporting: 
- #10232 
- #9870 
- Fixed issue with offset translation in `rm_stm` on snapshot hydrate
=> [v22.3.x] Backport of #10232 #9870

src/v/kafka/server/group.cc
=> [v23.1.x] Backporting #10226

src/v/storage/kvstore.cc
On start up kvstore will GC segments that are ordered before a snapshot's next_offset. The segments are replayed are closed, but not removed after replay and snapshot creation. The replayed segments can be removed after the snapshot has been taken and synced to disk. See segment rolling in kvstore where we also removed the last segment after snapshot is created.
This is also useful for disk space management tracking: otherwise kvstore disk usage computation needs to consider that these old segments may be sitting on disk.
* none
=> kvstore: remove segments after snapshot in recovery

tests/go/go-kafka-serde/client.go, tests/go/go-kafka-serde/go.mod, tests/go/go-kafka-serde/go.sum
Backport of PR #10184 
Fixes #10310
=> [v22.2.x] send messages synchronously in go-kafka-serde client

src/v/archival/ntp_archiver_service.cc
CONFLICT:
- tests/cloud_retention_test.py doesn't exist and uses S3Snapshot which doesn't exist in this branch
Backports:
- https://github.com/redpanda-data/redpanda/pull/8968
* Fixed an issue that could prevent uploads after all cloud segments have been garbage collected.
=> [v22.2.x] archival: always use last_offset if available to schedule uploads

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/10154
Fixes https://github.com/redpanda-data/redpanda/issues/10456,
=> [v22.2.x] tests/redpanda: do not include command with no args into pid list

src/v/redpanda/application.cc
The duplicate initialization only seems to create then destroy chunks in a loop. This could potentially introduce unneeded fragmentation in memory and slows down startup.
* none
=> Remove duplicate initialization of chunk_cache

src/v/cluster/partition.cc, src/v/cluster/partition.h, src/v/cluster/rm_stm.cc, src/v/cluster/rm_stm.h, src/v/raft/offset_translator.cc, tests/rptest/tests/idempotency_test.py
Backporting: #10232 
- Fixed issue with offset translation in `rm_stm` on snapshot hydrate
=> [V22.2.x] Backport of #10232

src/v/model/record_batch_reader.cc, src/v/model/record_batch_reader.h, src/v/raft/consensus_utils.cc, src/v/raft/consensus_utils.h, src/v/raft/recovery_stm.cc, src/v/raft/types.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/10397
Fixes https://github.com/redpanda-data/redpanda/issues/10481,
=> [v23.1.x] [recovery_stm] Buffer record_batches using fragmented vector

src/v/storage/probe.cc
=> storage: update segment metrics descriptions

tests/setup.py
The library was updated as a part of
9c095b95cb05605e6a843bfec09baf03ceb555a0
the change was not applied while solving conflicts in #10167
* none
=> [v22.3.x]tests/setup: updated confluent_kafka version

src/v/redpanda/application.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/10382
=> [v23.1.x] Remove duplicate initialization of chunk_cache

.github/workflows/backport-on-merge.yml
=> Removing an unused character.

.github/workflows/backport-on-merge.yml
=> Set the variable vs evaluate the variable.

.github/workflows/backport-on-merge.yml
=> Update the environment variable correctly.

tests/rptest/services/redpanda.py
Backport of PR #10294 
Fixes #10516
=> [v23.1.x] Fix ps filtering in ducktape

tests/rptest/services/redpanda.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/10294
Fixes https://github.com/redpanda-data/redpanda/issues/10514,
=> [v22.2.x] Fix ps filtering in ducktape

src/v/storage/disk_log_impl.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/10506
=> [v23.1.x] storage: Fix race condition in force_roll

src/v/cluster/controller_backend.cc, src/v/cluster/tests/topic_table_fixture.h, src/v/cluster/topic_table.cc, src/v/cluster/topic_table.h, src/v/cluster/types.h, src/v/coproc/reconciliation_backend.cc, src/v/coproc/reconciliation_backend.h, src/v/kafka/server/group_manager.cc, src/v/kafka/server/group_manager.h, src/v/utils/fragmented_vector.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/9738
=> [v23.1.x] c/topic_table: switch _pending_deltas to fragmented_vector

src/v/archival/ntp_archiver_service.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/10538
=> [v23.1.x] archival: Disable adjacent segment merging when not a leader

src/v/cluster/controller_backend.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/10567
Fixes https://github.com/redpanda-data/redpanda/issues/10571,
=> [v23.1.x] c/backend: s/parallel_for_each/max_concurrent_for_each

tests/rptest/tests/throughput_limits_snc_test.py
Double the minimum tested value for TP limit (both ingress and egress) because there is evidence that 128 B/s is still close to the edge and may fail the test when used for both ingress and egress.
Fixes #8809
* none
=> k/quotas: double the minimum TP limit

src/v/redpanda/application.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/10522
=> [v23.1.x] pandaproxy: Add a client id to SR and PP

src/v/redpanda/application.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/10522
=> [v22.3.x] pandaproxy: Add a client id to SR and PP

src/v/cloud_storage/cache_service.cc
This issue was added in the 23.2 revamp of cache size management, so never made it into a release.
When the disk became un-full, we were just logging: not actually clearing the flag that controls write blocking.
* none
=> cloud_storage: fix write blocking on low disk

tests/rptest/tests/throughput_limits_snc_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/10462
Fixes https://github.com/redpanda-data/redpanda/issues/10576,
=> [v23.1.x] k/quotas: double the minimum TP limit

tests/rptest/services/openmessaging_benchmark.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/9949
Fixes https://github.com/redpanda-data/redpanda/issues/10295,
=> [v22.3.x] tests: permit OMB log error

src/v/model/record_batch_reader.cc, src/v/model/record_batch_reader.h, src/v/raft/consensus_utils.cc, src/v/raft/consensus_utils.h, src/v/raft/recovery_stm.cc, src/v/raft/types.cc
Backport of #10397
Fixes: #10483
* none
=> [v22.3.x] Buffer record_batches using fragmented vector

src/v/archival/ntp_archiver_service.cc, src/v/cloud_roles/tests/env_override_tests.cc, src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/topic_manifest.cc, src/v/pandaproxy/schema_registry/protobuf.cc, src/v/security/gssapi_principal_mapper.cc, src/v/security/license.cc, src/v/security/mtls.cc, src/v/serde/envelope.h, src/v/storage/segment_set.cc, src/v/utils/to_string.h
Various fixes for issues encountered with newer compilers and libstdc++
* none
=> Fixes for gcc/libstdc++/clang16

src/go/k8s/apis/redpanda/v1alpha1/common_types.go, src/go/k8s/apis/redpanda/v1alpha1/common_types_test.go, src/go/k8s/pkg/console/sasl.go, src/go/k8s/tests/e2e/console-finalizers/00-assert.yaml, src/go/k8s/tests/e2e/console-finalizers/00-create-ns.yaml, src/go/k8s/tests/e2e/console-finalizers/01-assert.yaml, src/go/k8s/tests/e2e/console-finalizers/01-cluster.yaml, src/go/k8s/tests/e2e/console-finalizers/02-assert.yaml, src/go/k8s/tests/e2e/console-finalizers/02-console.yaml, src/go/k8s/tests/e2e/console-finalizers/03-unmanage-cluster.yaml, src/go/k8s/tests/e2e/console-finalizers/04-assert.yaml, src/go/k8s/tests/e2e/console-finalizers/04-shutdown-cluster.yaml, src/go/k8s/tests/e2e/console-finalizers/05-assert.yaml, src/go/k8s/tests/e2e/console-finalizers/05-delete-console.yaml, src/go/k8s/tests/e2e/console-finalizers/06-cleanup.yaml
Backport of PR https://github.com/redpanda-data/redpanda/pull/10496
=> [v23.1.x] Operator: add timeout option for console finalizers

src/v/cluster/metadata_dissemination_handler.cc, src/v/cluster/metadata_dissemination_service.cc, src/v/cluster/metadata_dissemination_types.h, src/v/cluster/tests/serialization_rt_test.cc, src/v/compat/check.h, src/v/compat/json.h, src/v/compat/metadata_dissemination_compat.h, src/v/compat/metadata_dissemination_generator.h, src/v/json/json.h
`get_leadership_reply` now contains a `fragmented_vector` instead of a `std::vector` to contain `ntp_leader`'s.  Multiple updates to address tests and compat.
Fixes: #10352
Force push `f602e77`:
* Changed solution
Force push `67c56a4`:
* Fixed lint error
Force push `fcdbe8a`:
* PR clean up
Force push `dcfff56`:
* PR clean up
* Fix over allocation in metadata dissemination leadership update
=> Fix overallocation in `cluster::get_leadership_reply`

src/v/kafka/server/handlers/fetch.h, src/v/storage/types.cc
=> Add missing fields to operators<<

src/v/cluster/cluster_utils.cc, src/v/cluster/cluster_utils.h, src/v/cluster/members_manager.cc, src/v/cluster/tests/cluster_utils_tests.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/10325
Fixes https://github.com/redpanda-data/redpanda/issues/10426,
=> [v23.1.x] Validate resulting configuration only in terms of changed field

src/v/storage/disk_log_impl.cc
Previously, we could be partway through truncating a previously cleanly-shutdown segment, and have written out indices but not data files, and thereby violate the invariant that a "clean" segment has all its data and indices on disk in a consistent state.
This would be unlikely to cause immediate issues, but could be a serious problem if we e.g. later delete the truncated indices and it gets rebuilt from the un-truncated data file.
* none
=> storage: drop clean_segment record on truncate

src/v/cluster/metadata_dissemination_handler.cc, src/v/cluster/metadata_dissemination_service.cc, src/v/cluster/metadata_dissemination_types.h, src/v/cluster/tests/serialization_rt_test.cc, src/v/compat/check.h, src/v/compat/json.h, src/v/compat/metadata_dissemination_compat.h, src/v/compat/metadata_dissemination_generator.h, src/v/json/json.h
Backport of PR #10585
Fixes #10614
=> [v23.1.x] Fix overallocation in `cluster::get_leadership_reply`

src/v/cluster/metadata_dissemination_handler.cc, src/v/cluster/metadata_dissemination_service.cc, src/v/cluster/metadata_dissemination_types.h, src/v/cluster/tests/serialization_rt_test.cc, src/v/compat/check.h, src/v/compat/json.h, src/v/compat/metadata_dissemination_compat.h, src/v/compat/metadata_dissemination_generator.h, src/v/json/json.h
Backport of PR #10585 
Fix #10612
=> [v22.3.x] Fix overallocation in `cluster::get_leadership_reply`

src/go/rpk/pkg/tuners/irq/device_info.go, src/go/rpk/pkg/tuners/network/nics.go, src/go/rpk/pkg/utils/files.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/10568
Closes #10596.
=> [v23.1.x] Force NIC tuner to use mq exclusively

src/v/raft/heartbeat_manager.cc
In Raft we have a mechanism that drops the connection if there is a particular number of failed heartbeats. The connection should only be dropped if it is unresponsive. Currently all the errors in heartbeat responses result in a connection being dropped.
Changed the implementation to only mark heartbeats as failed if the whole request failed with timeout. This way a connection will only be dropped when the node is not responsive.
- one faulty raft group will not influence others
=> Do not drop connections on logical Raft heartbeat errors

src/v/cloud_storage/base_manifest.h, src/v/cloud_storage/probe.cc, src/v/cloud_storage/probe.h, src/v/cloud_storage/remote.cc, src/v/cluster/CMakeLists.txt, src/v/cluster/cloud_metadata/cluster_manifest.cc, src/v/cluster/cloud_metadata/cluster_manifest.h, src/v/cluster/cloud_metadata/key_utils.cc, src/v/cluster/cloud_metadata/key_utils.h, src/v/cluster/cloud_metadata/tests/CMakeLists.txt, src/v/cluster/cloud_metadata/tests/cluster_manifest_test.cc, src/v/cluster/cloud_metadata/types.h
This commit adds a new cluster_metadata_manifest class that will serve as the foundation for cluster metadata uploads.
This only includes the maniefst structure, serialization and deserialization code, and some tests. The code is otherwise unused.
* none
=> cloud_metadata: add cluster metadata manifest

src/v/cluster/tests/CMakeLists.txt, src/v/cluster/tests/tm_coordinator_mapper_tests.cc, src/v/cluster/tests/tm_stm_tests.cc, src/v/cluster/tests/tm_tx_hash_ranges_tests.cc, src/v/cluster/tm_stm.cc, src/v/cluster/tm_stm.h, src/v/cluster/tm_tx_hash_ranges.h, src/v/cluster/tx_coordinator_mapper.h, src/v/cluster/tx_gateway_frontend.cc, src/v/cluster/tx_gateway_frontend.h, src/v/kafka/server/coordinator_ntp_mapper.h, src/v/model/model.cc, src/v/model/record_batch_types.h, src/v/redpanda/admin_server.cc, src/v/redpanda/application.h, src/v/reflection/adl.h, src/v/reflection/type_traits.h, tests/rptest/tests/transactions_test.py
Introduce new tm_stm batch type to store hosted hash ranges
Every tm_stm partition is responsible for section of possible hash result [0, UINT32_MAX] by default.
Sections are evenly distributed between partitions. 
New hash approach to identify coordinator partition for a transaction.
Currently coordinator hash range is immutable, so we can identify partition from default calculation.
Later we will make a request for it. So now we also have approach to check coodinator leaders on current node if they host particular transaction.
Fixes: #9879
* none
=> Tm stm static partitioning new hash ranges

src/v/raft/heartbeat_manager.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/10341
=> [v23.1.x] Do not drop connections on logical Raft heartbeat errors

src/v/kafka/server/handlers/fetch.cc, src/v/kafka/server/handlers/fetch.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/10677
=> [v23.1.x] Soft assert on different sizes of `shard_fetch` collections

src/go/k8s/apis/redpanda/v1alpha1/zz_generated.deepcopy.go, src/go/k8s/config/rbac/role.yaml, src/go/k8s/controllers/redpanda/cluster_controller.go, src/go/k8s/controllers/redpanda/console_controller.go, src/go/k8s/controllers/redpanda/redpanda_controller.go, src/go/k8s/go.mod, src/go/k8s/go.sum, src/go/k8s/hack/get-redpanda-info.sh, src/go/k8s/main.go, src/go/k8s/pkg/resources/configuration/configuration_test.go, src/go/k8s/pkg/resources/configuration/serialization_test.go, src/go/k8s/tests/e2e/update-image-and-node-port/04-assert.yaml, src/go/k8s/tests/e2e/update-image-and-node-port/04-v23-1-1.yaml, src/go/k8s/tests/e2e/update-image-tls-client-auth-external-ca/00-assert.yaml, src/go/k8s/tests/e2e/update-image-tls-client-auth-external-ca/00-v23-1-1.yaml, src/go/k8s/tests/e2e/update-image-tls-client-auth-no-external-ca/04-assert.yaml, src/go/k8s/tests/e2e/update-image-tls-client-auth-no-external-ca/04-v23-1-1.yaml, src/go/k8s/tests/e2e/update-image-tls-no-client-auth/04-assert.yaml, src/go/k8s/tests/e2e/update-image-tls-no-client-auth/04-new-image.yaml
Update rpk dependency. Fix unit tests as UUID is removed from Redpanda configuration file. Update generated code/files.
* none
=> Fix Redpanda operator build

src/go/k8s/hack/get-redpanda-info.sh
=> k8s: Fix equal condition in bash

src/go/k8s/tests/e2e/console-finalizers/00-assert.yaml, src/go/k8s/tests/e2e/console-finalizers/00-create-ns.yaml, src/go/k8s/tests/e2e/console-finalizers/01-assert.yaml, src/go/k8s/tests/e2e/console-finalizers/01-cluster.yaml, src/go/k8s/tests/e2e/console-finalizers/02-assert.yaml, src/go/k8s/tests/e2e/console-finalizers/02-console.yaml, src/go/k8s/tests/e2e/console-finalizers/03-unmanage-cluster.yaml, src/go/k8s/tests/e2e/console-finalizers/04-assert.yaml, src/go/k8s/tests/e2e/console-finalizers/04-shutdown-cluster.yaml, src/go/k8s/tests/e2e/console-finalizers/05-assert.yaml, src/go/k8s/tests/e2e/console-finalizers/05-delete-console.yaml, src/go/k8s/tests/e2e/console-finalizers/06-cleanup.yaml
There are 2 tests cases that have fixed `console` namespace. The `console-finzalizers` and `console` e2e tests could run in parallel as `kuttl-test.yaml` configuration set it to `2`. In some occasions cluster custom resource could be deleted by other test case execution.
This change renames the namespace and adds required parameter for `get-redpanda-info.sh` script.
Fixes #10758
* none
=> k8s: Rename e2e test K8S namespace

tests/rptest/services/redpanda_installer.py
After enough new releases were created, some of the old ones used in tests fell off the end.
Fixes https://github.com/redpanda-data/redpanda/issues/10717
* none
=> tests: use pagination on releases API

tests/rptest/util.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/10607
Fixes https://github.com/redpanda-data/redpanda/issues/10624,
=> [v23.1.x] tests: wait for recovery rate only on active brokers

src/v/net/tests/CMakeLists.txt, src/v/net/tests/dns.cc, src/v/net/unresolved_address.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/6560
=> [v23.1.x] net: Improve IPv6 support

tests/rptest/services/redpanda_installer.py
Backport of PR #10762
Fixes: #10773
=> [v23.1.x] tests: use pagination on releases API

tests/rptest/services/redpanda_installer.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/10762
Fixes: https://github.com/redpanda-data/redpanda/issues/10772
=> [v22.2.x] tests: use pagination on releases API

tests/rptest/services/redpanda_installer.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/10762
Fixes: https://github.com/redpanda-data/redpanda/issues/10771
=> [v22.3.x] tests: use pagination on releases API

src/v/cloud_storage/remote_partition.cc
Backport of PR #10782 
Fixes #10844
=> [v23.1.x] cloud_storage: fix empty segment check in reader

.github/workflows/backport-command.yml
=> GH Actions (backport on merge): add missing variable.

tools/offline_log_viewer/controller.py
adl decoding for create_non_replicable_topic, cancel_moving_partition_replicas serde updates for security::license v1
fixes related to unread bytes
log.error now dumps the json that has unread bytes, for easier fixing on ducktape
partially Fixes #10943
* none
=> offline_log_viewer updates

src/v/archival/ntp_archiver_service.cc, src/v/archival/ntp_archiver_service.h, src/v/archival/tests/archival_metadata_stm_test.cc, src/v/archival/tests/ntp_archiver_reupload_test.cc, src/v/archival/tests/ntp_archiver_test.cc, src/v/archival/tests/service_fixture.cc, src/v/cloud_storage/CMakeLists.txt, src/v/cloud_storage/async_manifest_view.cc, src/v/cloud_storage/async_manifest_view.h, src/v/cloud_storage/cache_service.h, src/v/cloud_storage/partition_manifest.cc, src/v/cloud_storage/partition_manifest.h, src/v/cloud_storage/segment_meta_cstore.cc, src/v/cloud_storage/segment_meta_cstore.h, src/v/cloud_storage/spillover_manifest.h, src/v/cloud_storage/tests/CMakeLists.txt, src/v/cloud_storage/tests/async_manifest_view_test.cc, src/v/cloud_storage/tests/cloud_storage_e2e_test.cc, src/v/cloud_storage/tests/partition_manifest_test.cc, src/v/cloud_storage/types.h, src/v/cluster/archival_metadata_stm.cc, src/v/cluster/archival_metadata_stm.h, src/v/cluster/partition.cc, src/v/cluster/partition.h, src/v/config/bounded_property.h, src/v/config/configuration.cc, src/v/config/configuration.h
This PR implements spillover into the archive tier. When the manifest grows to configured limit the `ntp_archiver` will "spill" oldest metadata into the separate manifest which is uploaded to the cloud storage. The read path is supposed to be able to download the manifest from the cloud and use it. This allows us to keep manifest in the `archival_metadata_stm` small and manageable. 
The PR also adds `materialized_manifest_cache` class which is supposed to be used by the read path. It stores spillover manifests in memory and preserves size restrictions by evicting least recently used manifests when new manifest need to go in.
* Archive tier in the tiered-storage
=> cloud_storage: Implement spillover in tiered-storage

src/go/k8s/controllers/redpanda/cluster_controller.go, src/go/k8s/controllers/redpanda/cluster_controller_test.go, src/go/k8s/pkg/resources/statefulset.go, src/go/k8s/pkg/resources/statefulset_test.go, src/go/k8s/pkg/resources/statefulset_update.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/10877
=> [v23.1.x] k8s: set Status.Version when all pods have that version

tests/rptest/scale_tests/many_partitions_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/9570
=> [v23.1.x] tests: disable many_partitions_tiered_storage

src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_types.cc, src/v/cluster/health_monitor_types.h, src/v/cluster/tests/randoms.h, src/v/cluster/tests/serialization_rt_test.cc, src/v/compat/cluster_json.h, src/v/compat/json.h, src/v/json/json.h, src/v/serde/serde.h, src/v/test_utils/randoms.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/10810
Fixes https://github.com/redpanda-data/redpanda/issues/10882,
=> [v23.1.x] Change topic_status partitions to be a chunked_fifo

src/go/k8s/controllers/redpanda/cluster_controller_configuration_test.go, src/go/k8s/pkg/resources/configuration/patch.go, src/go/k8s/tests/e2e/additional-configuration/04-update-version_and_config.yaml
Backport of PR https://github.com/redpanda-data/redpanda/pull/10961
=> [v22.3.x] k8s: parse configuration arrays correctly

src/v/cluster/metadata_dissemination_handler.cc, src/v/cluster/metadata_dissemination_handler.h, src/v/cluster/metadata_dissemination_rpc.json, src/v/cluster/metadata_dissemination_service.cc, src/v/cluster/metadata_dissemination_service.h, src/v/cluster/metadata_dissemination_types.h, src/v/cluster/tests/serialization_rt_test.cc, src/v/compat/metadata_dissemination_compat.h, src/v/compat/metadata_dissemination_generator.h, src/v/compat/run.cc
Replaced `std::vector` with `ss::chunked_fifo` in `update_leadership_request_v2` to prevent oversized allocations 
Fixes: #10753
Fixes: #10752 
- none
=> Using `ss::chunked_fifo` in metadata dissemination `update_leadership_request_v2`

src/go/k8s/controllers/redpanda/cluster_controller.go
=> k8s: Remove nolinter linter comment

src/go/k8s/controllers/redpanda/cluster_controller_configuration_test.go
Removed redundant go import.
* none
=> k8s: Fix redundant imports

src/go/k8s/pkg/console/admin.go
Backport of PR https://github.com/redpanda-data/redpanda/pull/11016
=> [v23.1.x] operator: close kadm connections created by console controller

src/go/k8s/controllers/redpanda/console_controller.go, src/go/k8s/controllers/redpanda/console_controller_test.go
Fixes #10927
* k8s: allow console to be deleted even if cluster is not configured
=> k8s: continue console deletion if cluster not configured

.clangd
Encountered after upgrade to clang16. More info here:
https://github.com/clangd/clangd/issues/1648
* none
=> clangd: disable flaky clang tidy check

src/v/cluster/health_monitor_backend.cc, src/v/cluster/health_monitor_backend.h, src/v/cluster/health_monitor_types.cc, src/v/cluster/health_monitor_types.h, src/v/cluster/tests/health_monitor_test.cc, src/v/cluster/tests/partition_balancer_planner_fixture.h, src/v/cluster/tests/randoms.h, src/v/cluster/tests/serialization_rt_test.cc, src/v/compat/cluster_json.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/10884
=> [v23.1.x] Change node_health_report::topics to be ss::chunked_fifo

tests/rptest/clients/kafka_cli_tools.py, tests/rptest/clients/types.py, tests/rptest/services/kaf_consumer.py, tests/rptest/services/rpk_producer.py, tests/rptest/tests/memory_stress_test.py
Backport of PR #9905
Fixes #10653
=> [v22.3.x] Reproduce the OOM on fetching from many partitions

src/go/rpk/pkg/cli/topic/consume.go
* rpk now supports `--rack` to specify the rack to consume from, which also opts into follower fetching
=> rpk: support --rack as an argument to topic consume

tests/rptest/services/kcat_consumer.py, tests/rptest/tests/throughput_limits_snc_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/10785
=> [v23.1.x] DT for limiting the kafka API api_keys scope

tests/rptest/tests/topic_recovery_test.py
=> [DNM] 10219 no fix

src/v/cluster/controller_backend.cc, src/v/storage/log_manager.cc
=> fix typo oprhan -> orphan

src/v/cluster/self_test/diskcheck.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11173
Fixes https://github.com/redpanda-data/redpanda/issues/11195,
=> [v23.1.x] c/self-test/diskcheck: Avoid large allocations

src/v/config/tls_config.h
Backport of PR https://github.com/redpanda-data/redpanda/pull/11167
=> [v22.3.x] tls: Prefer faster ciphers and use server preference

tests/rptest/tests/scaling_up_test.py
Backport of PR https://github.com/redpanda-data/redpanda/pull/11054
Fixes https://github.com/redpanda-data/redpanda/issues/11127,
=> [v22.3.x] Check for perfect replicas distribution in `ScalingUpTest.test_adding_nodes_to_cluster`

src/v/raft/consensus_utils.cc
Backport of https://github.com/redpanda-data/redpanda/pull/10535
* Fix post-recovery Raft boostrap
=> [v23.1.x] c/consensus_utils: adjust recovery offset ranges

src/v/storage/chunk_cache.h, src/v/storage/segment_appender.cc, src/v/storage/segment_utils.cc, src/v/storage/storage_resources.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/10032
=> [v22.3.x] Use chunk_cache as source of truth for chunk size

src/v/cloud_storage/tests/remote_test.cc, src/v/cloud_storage/tests/s3_imposter.cc, src/v/cluster/CMakeLists.txt, src/v/cluster/cloud_metadata/cluster_manifest.cc, src/v/cluster/cloud_metadata/cluster_manifest.h, src/v/cluster/cloud_metadata/error_outcome.h, src/v/cluster/cloud_metadata/manifest_downloads.cc, src/v/cluster/cloud_metadata/manifest_downloads.h, src/v/cluster/cloud_metadata/tests/CMakeLists.txt, src/v/cluster/cloud_metadata/tests/cluster_manifest_test.cc, src/v/cluster/cloud_metadata/tests/manifest_downloads_test.cc, src/v/cluster/cloud_metadata/tests/uploader_test.cc, src/v/cluster/cloud_metadata/uploader.cc, src/v/cluster/cloud_metadata/uploader.h, src/v/config/configuration.cc, src/v/config/configuration.h
This adds the structure for an upload loop that will be used to upload cluster metadata. Unlike the NTP archiver loops, this is not driven by a `persisted_stm`. Instead it will still rely on leadership to ensure a single uploader at once, but regularly (upon term changes) examine S3 to resync its view of what has been uploaded.
In this PR the loop only uploads the cluster metadata manifest. Subsequent PRs will add more metadata, and plug it into the controller. It is currently unused outside of tests.
Fixes https://github.com/redpanda-data/redpanda/issues/9551
* none
=> cloud_metadata: initial structure for metadata upload loop

src/v/cloud_storage_clients/abs_client.cc
Backport of PR https://github.com/redpanda-data/redpanda/pull/11225
=> [v23.1.x] cloud_storage_clients/abs: fix arg count for log
